### ISSUE TITLE
Extract addUserToRoom/removeUserFromRoom logic to separate function that doesn't require logged in user

### ISSUE THREAD

**Issue by rwakida** [RocketChat/Rocket.Chat#454]
Use Case: 
Allows automated, anonymous (bot) adding/removal of users from a room.  For example, we create a channel based on a user's location, and automatically add the user to the channel.  

The logic to update the ChatRoom/ChatSubscription, and create a new ChatMessage would be extracted to a new non-exposed, serverside function.  The existing Method methods would check that Meteor.userId() exists, and that the current user created the room then delegates to the new methods.  The backend "bots" would call the extracted method.
##

**Comment by engelgabriel** [comment]
Agreed! We did something similar with sendMessage.. we should do the same with ALL methods.

**Comment by geekgonecrazy** [comment]
With our bots now being logged in, and having our permission in place.  Is this still relevant?

**Comment by rwakida** [comment]
@geekgonecrazy I haven't kept up with the RocketChat changes, but I'm cool with closing this issue as long as bots can execute the function.  This also applies to issue #455.

**Comment by engelgabriel** [comment]
I don't think we should close it. We still need to move all logic from all methods into internal functions. Maybe we can re-title it?

**Comment by graywolf336** [comment]
@engelgabriel Most of the requirements of the original request are now implemented and can be accessed in many ways, either the rest api or ddp method calls. Can this be closed now?
