### ISSUE TITLE
Ldap SizeLimitExceeded

### ISSUE THREAD

**Issue by khobbits** [RocketChat/Rocket.Chat#4542]
Your Rocket.Chat version: 0.41.0

I've got an active directory group with about 2200 users in it, that I'd like to sync to rocketchat.
While i'm not expecting more than 200 active users, the users who are using it complain that they can't invite users who haven't yet logged in to a channel.

This is the error I see when I try to sync the group:

`Exception while invoking method 'ldap_sync_users' SizeLimitExceededError: Size Limit Exceeded     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)     at LDAP.searchAllSync (packages/meteor/helpers.js:119:1)     at LDAP.searchUsersSync (packages/rocketchat:ldap/server/ldap.js:231:15)     at sync (packages/rocketchat:ldap/server/sync.js:213:27)     at [object Object].ldap_sync_users (packages/rocketchat:ldap/server/syncUsers.js:18:18)     at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)     at packages/ddp-server/livedata_server.js:711:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/ddp-server/livedata_server.js:709:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/ddp-server/livedata_server.js:707:46     at Session.method (packages/ddp-server/livedata_server.js:681:23)     at packages/ddp-server/livedata_server.js:551:43     - - - - -     at messageCallback (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:77:13)     at Parser.emit (events.js:169:7)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:117:8)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at end (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)     at Socket.onData (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:77:13)     at Socket.emit (events.js:169:7)     at readableAddChunk (_stream_readable.js:153:18)     at Socket.Readable.push (_stream_readable.js:111:10)     at TCP.onread (net.js:536:20)`

**Comment by hExPY** [comment]
Hey @khobbits ,

we actually had the same problem with around ~600 users but using openldap.
The solution was quite simple. It was needed to add the 'sizelimit' option which is used to resize the pagination from 500 to the value.

Maybe there's a similar option for MS AD.

Kind regards,

**Comment by Garen** [comment]
Active Directory (AD) is similar in that it has a limit, but it's 1000 (not 500) by default.

@hExPY  where did you add the 'sizeLimit' option?   I can see that it's an option in the ldap.js docs here:

http://ldapjs.org/client.html

As well as the paged property, but didn't see any way to set those options from the UI in the LDAP section or from a custom JSON property/value.

**Comment by hExPY** [comment]
Hi @Garen,

i added the sizeLimit option in the ldap settings not in rocketchat.

Kind regards,

**Comment by hExPY** [comment]
We updated a day ago to Version 0.57.0 and now it works like charm.

Thank you guys.

**Comment by Garen** [comment]
@hExPY I'm assuming you mean that you changed the limit on your openldap server?   Well, lucky for you. :)

**Comment by hExPY** [comment]
@Garen we haven't changed anything yet. ^^
But yeah, lucky for us 👍
