### ISSUE TITLE
Use relative urls when ever possible

### ISSUE THREAD

**Issue by angshallen** [RocketChat/Rocket.Chat#4553]
Rocket.Chat version: 0.42

Request: I would really appreciate the use of dynamic urls application wide instead of the mix of static and dynamic. Static URLs/fqdn is a problem when using a reverse proxy for outside connections but wanting to use LAN only for the inside access.
Example:
When uploading files, the URL/fqdn used is the one set in the server vars (ie. the one you see in the log) instead of the actual URL/fqdn. If you do not connect with the same URL/fqdon that the server has in the vars, upload wont work (stuck at 0%). This is also true when display/viewing files in the chat window.
In the Files List the URL/fqdn is dynamic ie. it varies depending on what the client used to connect.

**Comment by rodrigok** [comment]
The idea here is to change the client to always use relative URLs to prevent errors like we have on uploads today. But a main url (Site URL) is still necessary to mount links then sending things from the server (like emails).
