### ISSUE TITLE
Need to increase length of LDAP timeout [$250]

### ISSUE THREAD

**Issue by IonicSecurityOps** [RocketChat/Rocket.Chat#4561]
Rocket.Chat version:0.37.1

We're encountering an issue using Rocket.Chat with our 2-factor auth proxy. The user barely has enough time to acknowledge the 2-factor notification before LDAP auth times out. We're looking for a way to increase this timeout to allow users to comfortably sign in.

<a href="https://www.bountysource.com/issues/38191649-need-to-increase-length-of-ldap-timeout?utm_source=38191649&utm_medium=shield&utm_campaign=ISSUE_BADGE"><img src="https://api.bountysource.com/badge/issue?issue_id=38191649" /></a>

**Comment by robmccoll** [comment]
Made a simple fix that was enough for our needs (I work for Ionic Security).  Upping the timeout does resolve our two-factor auth timeout issue.
