### ISSUE TITLE
IMPORTANT! Guidlines explanations 

### ISSUE THREAD

**Issue by Aria-Groult** [RocketChat/Rocket.Chat#4567]
Hey i have been assigned a task . Let me describe it.

I can use any language . I chose NodeJS , to build a Rest API that can be able to : 
Object if :

Connect  
Logon with REST API
Get list of public rooms via REST API
Join a room via REST API
Sending a message via REST API

I am very lost in all i have to do and i would really appreciate help.
Thanks so much.

**Comment by graywolf336** [comment]
@Aria-Groult Please see this: https://rocket.chat/docs/developer-guides/rest-api/
