### ISSUE TITLE
cant disable email verification 

### ISSUE THREAD

**Issue by 112madgamer** [RocketChat/Rocket.Chat#457]
cannot seem to find the disable email verification setting and every time i try to login it says user account deactivated

**Comment by marceloschmidt** [comment]
@112madgamer we created a migration file so every user would have it's active flag turned on. Have you, by any chance, clicked on "Deactivate" on your user when you were online?

**Comment by katopz** [comment]
actually I hit same problem with fresh install locally on Mac.

// register state
I did register new user then I got confirmation link print out via terminal (I didn't set SMTP yet) 
so I copy that link and open via browser, login screen come up.

// login state
then I try login with `username` it will throw `user not found`.
and when I try login with `email` it will throw `user deactivated`.

IMHO : email verification should be off by default for easier setup and run.
and when we're happy with chat system, now we can turn verification on and continue develop anything related to email later.

Another thing is email sender should has an option for 3rd party like Mandrill or else 
so people can use template and else separately.

Not sure it same issue. Thanks

**Comment by engelgabriel** [comment]
The // login state is now fixed :)

We will now work on the // register state

**Comment by 112madgamer** [comment]
its is fixed issue can be closed

**Comment by engelgabriel** [comment]
Yes, the remaining work is already described on https://github.com/RocketChat/Rocket.Chat/issues/250
