### ISSUE TITLE
Delete files after an upload

### ISSUE THREAD

**Issue by pascalrobert** [RocketChat/Rocket.Chat#4571]
Your Rocket.Chat version: 0.42

It would be great if uploaded files could be automatically deleted when the receiver have downloaded all of the files. This is especially true for places where users exchanges big files between them. Maybe the automatic cleanup could be done only for private conversations.

**Comment by graywolf336** [comment]
@pascalrobert How do you propose this working? Would it only be in direct messages and what settings would be configurable?

**Comment by pascalrobert** [comment]
Yeah, I think it should be done only for direct messages. I think a simple on/off setting for the whole server would be enough.

**Comment by Darlelet** [comment]
Would definitely be useful to save storage space.

**Comment by tgoetheyn** [comment]
+1

**Comment by jszaszvari** [comment]
What happens when the user wants to go back to the conversation and re download the file? This would mostly defeat the purpose of the attached files Tab. 

Use a Amazon S3 bucket. We pay roughly $25 per TB stored per month.

**Comment by AmShaegar13** [comment]
Because it is not possible for us to host files with an external contractor we ran into the same *problem*. Here is a Gist of a MongoDB query to delete outdated files from GridFS we are using in a daily cron job.

https://gist.github.com/AmShaegar13/8a2be6895e6058e67d05a7596dd9bfca

Thoughts and feedback welcome!

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap so we will revisit once other priorities have been addressed.
