### ISSUE TITLE
Web Conference UI Clipping

### ISSUE THREAD

**Issue by kevincolten** [RocketChat/Rocket.Chat#4573]
Anyone get clipping when video conferencing?

![screen shot 2016-10-07 at 11 56 39 am](https://cloud.githubusercontent.com/assets/4411115/19198563/6a669b9e-8c85-11e6-8ce2-6550deacdea2.png)

Is this by design? Should there be something below the video?

**Comment by joseluis** [comment]
It seems to be a recent change in [meet.jit.si](https://meet.jit.si), issue: https://github.com/jitsi/jitsi-meet/issues/969

For the meantime you can use [appear.in](https://appear.in) as an alternative.
 
You can change the domain in Administration > Video Conference > Domain

**Comment by IntellixWeb** [comment]
Not sure if it helps but latest version of Chrome fixes this issue. 

Chrome Version 55.0.2883.75 (64-bit)

**Comment by jszaszvari** [comment]
@IntellixWeb Just installed the latest and still got the issue

**Comment by jack17529** [comment]
@JSzaszvari is it solved now ?

**Comment by gabriellsh** [comment]
I think this doesn't happen anymore, if you are still experiencing this, please reopen this issue.
