### ISSUE TITLE
Clear old push tokens from database

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4574]
Your Rocket.Chat version: 0.42.0

Hey guys,

i used the function "send me a push message" and the message shows me that the push message is send to !9! devices. But i only have 1 device connected for push :-). Is there a function to cleanup old push tokens?

Here is the log:

```
Push: send to token { apn: '98358e702b26ee8bd36188fa6ae4681a0a7b4946d1cf0125482808f093cffe80' } 
[34mI20161007-17:31:16.842(0) Push: send to token { apn: '028541dad721cbf6b403bd561344c46c1212cc2928818a5bcdb9de' } 
[34mI20161007-17:31:16.844(0) Push: send to token { apn: 'bdba5790a6e16c598c0d399d9f2fcb0577bd7a71cb437dfc1123400' } 
[34mI20161007-17:31:16.846(0) Push: send to token { apn: 'f17f5f6186b364ebdd15e50433a0695c0bdaa2d5af3dad82fc2f0d3' } 
[34mI20161007-17:31:16.848(0) Push: send to token { apn: '0a1ed3efb76781a232f33f59618cefc848f8fd43c4fadd3a7f3f9ce8' } 
[34mI20161007-17:31:16.850(0) Push: send to token { apn: 'fff2193c98c55546ebf544c18855199f9a88834853170aa76b9285' } 
[34mI20161007-17:31:16.851(0) Push: send to token { apn: 'f7e1bd55aef037291d1c1ef2ae488ccb0c73964372886ba5b316' } 
[34mI20161007-17:31:16.853(0) Push: send to token { apn: '909fa006f3e64e1ae80a73508ff3458ddad3af8eed1a170051e36' } 
[34mI20161007-17:31:16.854(0) Push: send to token { apn: '3c75d64a73c1f23e36fe376efe981ee9b0318852e4e3926f46197' } 
```

(Dont wonder about the short push tokens, delete some characters just for privacy)

**Comment by TheReal1604** [comment]
Some news on this? This is also important for users which migrate from android to iOS.. or from iOS to android. To keep the push tokens clean.

**Comment by TheReal1604** [comment]
@rodrigok your commit should fix this issue right? https://github.com/RocketChat/Rocket.Chat/commit/4a92810a4c9456262233876aead9938cfc655044

**Comment by rodrigok** [comment]
We already remove invalid tokens as you can see [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/lib/cordova.js#L99) when using our push gateway and it's removed by the library [here](https://github.com/RocketChat/push/blob/master/lib/server/push.api.js#L260) when configuring push notification directly.

**Comment by TheReal1604** [comment]
@rodrigok thanks for clarification! That’s cool. :)

**Comment by horstepipe** [comment]
Hello
when I send a test push notification via settings, server reports to have sent push messages to 11 devices. I definitively do not have 11 devices, so something still seems to go wrong here? 
How can I enable extended logging for push notifications to provide more info?

**Comment by rodrigok** [comment]
@horstepipe you can go to `Admin > Logs > Log Level` and set it to `2 - Errors, Information and Debug`, then you should see more details.

**Comment by horstepipe** [comment]
thanks @rodrigok 

Something definitely goes wrong here. 

`I20200825-12:31:27.777(2) Meteor ➔ method push_test -> userId: xxx, arguments: [] 
I20200825-12:31:27.789(2) Push ➔ debug Sending notification {   createdAt: 2020-08-25T10:31:27.786Z,   createdBy: '<SERVER>',   sent: false,   sending: 0,   from: 'push',   title: '@xxx',   text: 'This is a push test message',   userId: 'xxx',   sound: 'default',   apn: { text: '@xxx:<br>This is a push test message' } } 
I20200825-12:31:27.792(2) Push ➔ debug send message "@xxx" to userId xxx 
I20200825-12:31:27.970(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:27.972(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:27.978(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:27.980(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:27.988(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:27.991(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:27.998(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.000(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.026(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.030(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.043(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.048(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.061(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.065(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.077(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.081(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.091(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.095(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.106(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.108(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.118(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.122(2) Push ➔ debug send to token {   apn: 'xxx' } 
I20200825-12:31:28.134(2) Push ➔ debug Sent message "@xxx" to 11 ios apps 0 android apps 
I20200825-12:31:31.696(2) API ➔ debug GET: /api/v1/stdout.queue `

Maybe the problem only occurs with IOS devices?

**Comment by horstepipe** [comment]
So I'd vote to reopen this issue as from what I see you're trying to get your push system as efficient as possible, so this seems to be quite a big issue if every IOS user is affected...?

**Comment by TheReal1604** [comment]
@MartinSchoeler @rodrigok @horstepipe We also had problems clearing old push tokens from the database. This seems to affect every version of Rocket.Chat. In regards to the hard limits on the push gateway, this is possibly a critical bug. 

I resolved the issue manually, removing the old entries from the collection... based on timestamp.

**Comment by geekgonecrazy** [comment]
Failed pushes aren’t counted at push gateway towards total.

Regarding the tokens there might be a way to clear via the api
