### ISSUE TITLE
Voice Chat

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#4575]
it would be nice to have a feature to have just voice chat (similar to paltalk) , lets say ppl dont want to type and just discuss via audio - ( sort of conference call) , can be enabled by default or have ppl raise hands to talk in order, moderator can mute them,.. with options to have many ppl talk in the same time.. this will be good specially on the phone when you are driving.. ppl can just talk in chat room.. 

so just stand alone voice chat.. 
http://www.paltalk.com/

btw Love the fact we have Screen sharing working via jitsi, still need some work on permissions and who can start it or which room to have it etc.. 

Your Rocket.Chat version:0.42

**Comment by scj643** [comment]
Kinda like discord

**Comment by IQ2022** [comment]
Nice is Discord open source?  would be nice if we have voice chat enabled, and controlled by Admin or Room Owner

**Comment by scj643** [comment]
It isn't open source sadly

**Comment by sampaiodiego** [comment]
you can do this using any of our conference options
