### ISSUE TITLE
Auto Correct Text while typing like that which happens in whatsapp.

### ISSUE THREAD

**Issue by deep0892** [RocketChat/Rocket.Chat#4579]
It would be a great add on to have a autocorrect text while typing and suggestions(if possible).
It sometimes get difficult to keep track of spelling while typing and that may not be well received if one if using the app for professional purposes.
It should be configurable and can be switched on or off depending on ones use as auto correct are sometimes annoying.

**Comment by deep0892** [comment]
Another new feature can be having keyword shortcuts like a word followed by a special character and when ever someone types that, the sentence or phrase mapped with the shortcut would be automatically replaced in the input box. Eg,

hi;   would automatically be replaced with   Hi, how are you ?

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
