### ISSUE TITLE
Can not load message on mobile browser?

### ISSUE THREAD

**Issue by fantashi** [RocketChat/Rocket.Chat#458]
Hello,

If i open rocket.chat on browser and send message between 2 peoples. I received message as normal.
But when i'm complete close browser and some one send message to me. Then, i open browser again. I do not receive new message.

**Comment by marceloschmidt** [comment]
Hey @fantashi thanks for your feedback. Can you try that again, just to be sure it wasn't some kind of instability on our servers? Since we're still in the middle of development, there is a chance we were deploying some changes the exact same time you were testing... Thank you.

**Comment by engelgabriel** [comment]
@fantashi Let us know if that happens again using the new server https://demo.rocket.chat

Please reopen the issue if the error persists
