### ISSUE TITLE
Google Oauth isn't working

### ISSUE THREAD

**Issue by DeMiNe0** [RocketChat/Rocket.Chat#4580]
Running latest Rocket.Chat docker container. When I tried to authenticate using google, I get the following error:

rocketchat_1         | {"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Google. tunneling socket could not be established, statusCode=400","time":{"$date":1475957359222},"level":"warn"}
rocketchat_1         | Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Google. tunneling socket could not be established, statusCode=400
rocketchat_1         |     at getTokens (packages/google/google_server.js:59:1)
rocketchat_1         |     at Object.handleOauthRequest (packages/google/google_server.js:10:1)
rocketchat_1         |     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
rocketchat_1         |     at middleware (packages/oauth/oauth_server.js:173:1)
rocketchat_1         |     at packages/oauth/oauth_server.js:146:1

**Comment by DeMiNe0** [comment]
Checked my Key and Client ID since that seems to be the most likely cause of the 400 error, but no success.

**Comment by DaBlitzStein** [comment]
+1
rocketchat_1          | {"line":"428","file":"oauth.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Google. tunneling socket could not be established, statusCode=400","time":{"$date":1483832682761},"level":"warn"}
rocketchat_1          | Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Google. tunneling socket could not be established, statusCode=400
rocketchat_1          |   at getTokens (packages/google.js:83:20)
rocketchat_1          |   at Object.handleOauthRequest (packages/google.js:34:18)
rocketchat_1          |   at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
rocketchat_1          |   at middleware (packages/oauth.js:203:5)
rocketchat_1          |   at packages/oauth.js:176:5

**Comment by nopnop** [comment]
@DeMiNe0, @DaBlitzStein 
Have you set the HTTP(S)_PROXY env ?  
See https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml#L16

**Comment by okaufmann** [comment]
After setting both env vars `HTTP_PROXY=http://chat.mydomain.com` and `HTTP_PROXY=https://chat.mydomain.com` it's still not working. Any other suggestions?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support or feature request category
