### ISSUE TITLE
Send no text in Farsi Mobile

### ISSUE THREAD

**Issue by bazarnew** [RocketChat/Rocket.Chat#4582]
Your Rocket.Chat version: (make sure you are running the latest) 0.43.0
In Persian, the mobile app sends a text field clamp remembered why?

**Comment by bazarnew** [comment]
@engelgabriel

**Comment by bazarnew** [comment]
@diegoprates

**Comment by MartinSchoeler** [comment]
@bazarnew  could you send us a screen shot of the problem?

**Comment by bazarnew** [comment]
`https://doorgoo.chat/file-upload/dQWaKRQKcMaCQtNTz/Screenshot_2016-10-11-19-31-32.jpeg`

**Comment by bazarnew** [comment]
@MartinSchoeler

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
