### ISSUE TITLE
OTR Issues

### ISSUE THREAD

**Issue by samihaq** [RocketChat/Rocket.Chat#4583]
Your Rocket.Chat version: (0.4.1)
Issues If we exchange OTR key and open a new browser sender & receiver get garbage like below
Admin 12:04 PM 
{"$binary":"q0aCyaYI72n5gG6MwC0jFCyq+OYfAzZM9Kr1NqtSJalkl/igC4gCYqVmZe/0JP14G3/0uiY/RXxpu3oaGNhGbLpX0EaFL/PNUiJmgUBqJnqsW2KMXpgjtW21nTfKLAudtXJUH9Gx3GDWyPeSnE0vKsbxDZ/lDfXrkmqXP8JxzWRB19NjJq8Yz2l/PAiJ73L5iR8zT8Qc2dlfNC0o8nFmCyP8KVoqVuyx"}

{"$binary":"3LKhElYOfVn8nPAoN9InK3dxcvxNcCNlA/n5Okds8mec2DK563O0DNdDqe1dkhuDHRYNBbV+gTzJtKdxsySiDJ9DEUz9lQuvFL++AflUSxSKA5WgLT+QtbtEzwmx3CWfV0ChJaHU0vbZUdAqboBvFSfKy8XjFcyD/BTdxI4pIJtn5LuhoXsitsAbeUPFDbfpEd7PxXFvavb/wWlqJOUdVkhihY3TD8u7Cw=="}

If we pin any readable message in OTR and try to PIN and or Star the message it also show garbage
{"$binary":"YwN1JZFEKrTzYVMHKWn8cX1N70pJQrAHuApjxTiJlJ93b3kps9QJ0jvb63HHZwSBozotJNF4v8NW+H1E8nVdMBZMszyh0Rrkt4sUEWNUNAcmVwR2FGHjXZ5Oxh7tINXmoKZQrZTEhZIA41OcaBaDUbNQ/ecDbhE4NN1k1CrYUFLUtk0fghRM9K5RIKoIG7epDjEleZEuY/HCPVt/Qc50bsHv+g=="}

**Comment by Flipez** [comment]
In Rocket.Chat version 0.44.0 this also happens if you edit a OTR message. The old message turns into garbage on the senders site. The receiver will correctly see the old and new edited message.

**Comment by geekgonecrazy** [comment]
Can you try this on a recent version?  If this still happens feel free to re-open.

**Comment by Flipez** [comment]
Still an issue in 0.57.3. Also quoting does not work.

**Comment by geekgonecrazy** [comment]
I believe we have a revamp of OTR coming.  Possibly fixing all of these
