### ISSUE TITLE
Heroku H15 Idle Connection Errors

### ISSUE THREAD

**Issue by kevincolten** [RocketChat/Rocket.Chat#4589]
Has anyone uncovered the reason why you get so many idle connection errors when deployed on Heroku? There is some chatter on the internet about being sure you use CNAME records and that they are "flattened" if you are using Cloudflare, which I'm doing. Also, [Heroku has some literature on websockets](https://devcenter.heroku.com/articles/websockets#timeouts).

![screen shot 2016-10-10 at 8 48 44 am](https://cloud.githubusercontent.com/assets/4411115/19238322/a02fff16-8ec6-11e6-916d-5bfc96ec57f5.png)

**Comment by kevincolten** [comment]
Here is a relevant SO on the issue. http://stackoverflow.com/questions/25735207/node-js-web-socket-h15-idle-connection-timeout-on-heroku

**Comment by marceloschmidt** [comment]
This belongs to Heroku.
