### ISSUE TITLE
i can't run Rocket.chat with meteor 

### ISSUE THREAD

**Issue by boulakar** [RocketChat/Rocket.Chat#4591]
Hi i used this link but not working 
https://rocket.chat/docs/developer-guides/pre-requisites/

I have these errors 

![2016-10-10_1853](https://cloud.githubusercontent.com/assets/6246661/19245901/24822e46-8f13-11e6-91df-dbf7b130df32.png)
![2016-10-10_1717](https://cloud.githubusercontent.com/assets/6246661/19245903/248256b4-8f13-11e6-87c9-a4f392956ab4.png)

Thanks for your help

**Comment by lc3t35** [comment]
seems you did not : meteor npm install ?

**Comment by boulakar** [comment]
@lc3t35 thnaks
I only used thes command line
curl https://install.meteor.com/ | sh
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor

**Comment by lc3t35** [comment]
so before meteor, do : meteor npm install

**Comment by boulakar** [comment]
@lc3t35 thanks so much for your reutor

why without Rocket.Chat it's working 
 
   http://screencast.com/t/miQIDI4h28

and with your solution is stoping in "Building for os.linux.x86_64 "

http://screencast.com/t/CK0lKgl6O

**Comment by lc3t35** [comment]
the result of npm install is not correct : it failed at rebuilding bcrypt.
you need first : sudo apt install build-essential
then meteor npm install

**Comment by boulakar** [comment]
thanks so much :)

**Comment by boulakar** [comment]
@lc3t35 thanks 👍
