### ISSUE TITLE
No Push notifications on @user or Direct Messages 

### ISSUE THREAD

**Issue by Sonoma95SS** [RocketChat/Rocket.Chat#4594]
Rocket.Chat version -
Version: 0.42.0

OS -
Ubuntu 16.04.1 LTS

 Rocket.Chat Startup using Docker Compose Version 1.8.8 build f3628c7 -
`[34mI20161011-01:33:49.317(0) Updating process.env.MAIL_URL 
[34mI20161011-01:33:59.620(0) (migrations.js:114) Migrations: Not migrating, already at version 63
[34mI20161011-01:34:01.390(0) Updating process.env.MAIL_URL 
[34mI20161011-01:34:03.090(0) [32mUsing GridFS for custom emoji storage 
[34mI20161011-01:34:03.341(0) Push: configuring... 
[34mI20161011-01:34:03.360(0) Push.Configure { apn: undefined,   gcm: undefined,   production: true,   sendInterval: 1000,   sendBatchSize: 10 } 
[34mI20161011-01:34:03.364(0) [32mUsing GridFS for Avatar storage 
[34mI20161011-01:34:03.565(0) [32m➔ serverRunning.coffee:9 [32mSystem ➔ startup`

Trying to send a Push notification -
`[34mI20161011-01:34:23.533(0) Push: send message "@ofadmin" via query { userId: 'ofEP6ac6gyHHQAcCP' } 
[34mI20161011-01:34:23.537(0) Push: send to token { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' } 
[34mI20161011-01:34:23.670(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161011-01:34:23.863(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (1 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161011-01:34:24.981(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (2 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161011-01:34:35.092(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' }`

Logging onto Google Play Rocket.Chat App -
`[34mI20161011-01:35:35.901(0) Push: Settings userId "ofEP6ac6gyHHQAcCP" for app: y9nbizgAMWKgsTWpQ 
[34mI20161011-01:35:35.931(0) Push: Got push token from app: { id: 'y9nbizgAMWKgsTWpQ',   token: { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' },   appName: 'main',   userId: 'ofEP6ac6gyHHQAcCP',   metadata: {} } 
[34mI20161011-01:35:35.958(0) Push: updated { _id: 'y9nbizgAMWKgsTWpQ',   token: { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' },   appName: 'main',   userId: 'ofEP6ac6gyHHQAcCP',   enabled: true,   createdAt: Sun Oct 09 2016 19:41:27 GMT+0000 (UTC),   updatedAt: Tue Oct 11 2016 01:23:43 GMT+0000 (UTC) }`

Trying to send a new message to @ofadmin and receive the same errors as above from "Trying to send a Push notification" section.

Push Settings -
Enable - True
Debug - True
Enable Gateway - True
Gateway - https://gateway.rocket.chat

Certs and Keys - (only testing Android so far)
GCM API Key - Filled in from my account
GCM Project Number - Filled in from my account

So far I'm getting notifications from the Desktop App and Web Page, just not the Apps which is something I direly need. Even if there was some kind of addin that I could configure to text message a cell phone number to alert the end user that someone was wanting to chat with them. If user=idle/offline, then send=textalert, else send=messagetowindow

But, not to get off subject I really would like to get this instance rolling and able to get my guys using it ASAP. Thanks in advance, Quas

**Comment by TheReal1604** [comment]
@Sonoma95SS Please try to delete your personal GCM API Key and GCM Project Number, if you use the rocket.chat gateway you dont need that. Then restart your server and try again.

**Comment by Sonoma95SS** [comment]
First login after stop/restart and login from android app -
`[34mI20161011-06:40:48.408(0) Push: Settings userId "ofEP6ac6gyHHQAcCP" for app: y9nbizgAMWKgsTWpQ 
[34mI20161011-06:40:48.440(0) Push: Got push token from app: { id: 'y9nbizgAMWKgsTWpQ',   token: { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' },   appName: 'main',   userId: 'ofEP6ac6gyHHQAcCP',   metadata: {} } 
[34mI20161011-06:40:48.470(0) Push: updated { _id: 'y9nbizgAMWKgsTWpQ',   token: { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' },   appName: 'main',   userId: 'ofEP6ac6gyHHQAcCP',   enabled: true,   createdAt: Sun Oct 09 2016 19:41:27 GMT+0000 (UTC),   updatedAt: Tue Oct 11 2016 01:35:35 GMT+0000 (UTC) } `

**Comment by Sonoma95SS** [comment]
Complete logs from restart and trying to send a message afterwards where it seems the push locked up -
`[34mI20161011-06:37:48.324(0) Updating process.env.MAIL_URL 
[34mI20161011-06:37:58.751(0) (migrations.js:114) Migrations: Not migrating, already at version 63
[34mI20161011-06:38:01.440(0) Updating process.env.MAIL_URL 
[34mI20161011-06:38:02.963(0) [32mUsing GridFS for custom emoji storage 
[34mI20161011-06:38:03.208(0) Push: configuring... 
[34mI20161011-06:38:03.226(0) Push.Configure { apn: undefined,   gcm: undefined,   production: true,   sendInterval: 1000,   sendBatchSize: 10 } 
[34mI20161011-06:38:03.230(0) [32mUsing GridFS for Avatar storage 
[34mI20161011-06:38:03.458(0) [32m➔ serverRunning.coffee:9 [32mSystem ➔ startup 
[34mI20161011-06:38:03.458(0) [32m➔ [32m+----------------------------------------------+ 
[34mI20161011-06:38:03.459(0) [32m➔ [32m|                SERVER RUNNING                | 
[34mI20161011-06:38:03.459(0) [32m➔ [32m+----------------------------------------------+ 
[34mI20161011-06:38:03.460(0) [32m➔ [32m|                                              | 
[34mI20161011-06:38:03.460(0) [32m➔ [32m|       Version: 0.42.0                        | 
[34mI20161011-06:38:03.461(0) [32m➔ [32m|  Process Port: 3000                          | 
[34mI20161011-06:38:03.461(0) [32m➔ [32m|      Site URL: http://*************:3000  | 
[34mI20161011-06:38:03.462(0) [32m➔ [32m|                                              | 
[34mI20161011-06:38:03.462(0) [32m➔ [32m+----------------------------------------------+ 
[34mI20161011-06:40:48.408(0) Push: Settings userId "ofEP6ac6gyHHQAcCP" for app: y9nbizgAMWKgsTWpQ 
[34mI20161011-06:40:48.440(0) Push: Got push token from app: { id: 'y9nbizgAMWKgsTWpQ',   token: { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' },   appName: 'main',   userId: 'ofEP6ac6gyHHQAcCP',   metadata: {} } 
[34mI20161011-06:40:48.470(0) Push: updated { _id: 'y9nbizgAMWKgsTWpQ',   token: { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' },   appName: 'main',   userId: 'ofEP6ac6gyHHQAcCP',   enabled: true,   createdAt: Sun Oct 09 2016 19:41:27 GMT+0000 (UTC),   updatedAt: Tue Oct 11 2016 01:35:35 GMT+0000 (UTC) } 
[34mI20161011-06:43:50.892(0) Push: send message "@rquasdorf" via query { userId: 'sxKwcYmKzX9EthGrH' } `

**Comment by Sonoma95SS** [comment]
Sorry, hit wrong button

**Comment by Sonoma95SS** [comment]
Still no push notifications.

**Comment by TheReal1604** [comment]
Hm. Sry, dont have any further idea to resolve this.. maybe @sampaiodiego can help here?

**Comment by Sonoma95SS** [comment]
@TheReal1604 
Thanks for your help letting me know that I didn't need to try and have a push from GCM though, hopefully I can get this figured out soon.

**Comment by electropolis** [comment]
Last day I tested that and notice that the push is available on DM also on General channels providing '@' in front of the nick and without it on DM .. Got pushed on my Rocket.Chat client o Mac OSx and on android.

**Comment by Sonoma95SS** [comment]
I've tried DM's and using the '@' to get the push notification, but still nothing. I really wouldn't mind starting over using an OS of one of the developers choice for testing, I'm a Windows admin and hardly ever use Linux except for projects like this. We had an OpenFire XMPP server up and running and I was able to get everything I wanted out of it except the file transfers that I needed. We used AstraChat as the client app, so even using pictures wouldn't work because it was using their servers to host the files. We have to have everything in house for auditing purposes.

**Comment by electropolis** [comment]
I would like to help but.. like I said it's fine by me. Did you enable push in settings and made test of push?

**Comment by Sonoma95SS** [comment]
Yes, push is enabled and I've tested on PC Client, Web App and Android App. The only ones that give me a desktop notification and an alert are the PC Client and Web App. Android doesn't receive a notification or alert.

**Comment by Sonoma95SS** [comment]
Here is what I got after uninstalling and reinstalling the app as suggested in another thread I'm following on this issue. Does it seem like it could be an issue of my internal server not reaching the Rocket.Chat push gateway?

`[34mI20161019-13:40:18.812(0) Push: Settings userId "null" for app: MHcKhromBTgxvLwxE 
[34mI20161019-13:40:18.927(0) Push: Got push token from app: { id: 'MHcKhromBTgxvLwxE',   token: { gcm: 'eFfpHeYd_wI:APA91bGEtw4cER2mC9Vj355O5uBnv6XRtumDbXl6G5opuO6NZwe4Bi-OuqHIMUk2doUyhLUDUJtL83D12Z6yc8se7_CoPtlX1LRijOrHE_T4X8pz5fvRlfABwcpmPj18IkjNny5sTZHl' },   appName: 'main',   userId: null,   metadata: {} } 
[34mI20161019-13:40:18.948(0) Push: updated { token: { gcm: 'eFfpHeYd_wI:APA91bGEtw4cER2mC9Vj355O5uBnv6XRtumDbXl6G5opuO6NZwe4Bi-OuqHIMUk2doUyhLUDUJtL83D12Z6yc8se7_CoPtlX1LRijOrHE_T4X8pz5fvRlfABwcpmPj18IkjNny5sTZHl' },   appName: 'main',   userId: null,   enabled: true,   createdAt: Wed Oct 19 2016 13:40:18 GMT+0000 (UTC),   updatedAt: Wed Oct 19 2016 13:40:18 GMT+0000 (UTC),   _id: 'MHcKhromBTgxvLwxE' } 
[34mI20161019-13:40:46.374(0) Push: Settings userId "ofEP6ac6gyHHQAcCP" for app: MHcKhromBTgxvLwxE 
[34mI20161019-13:41:31.390(0) Push: send message "@rquasdorf" via query { userId: 'ofEP6ac6gyHHQAcCP' } 
[34mI20161019-13:41:31.395(0) Push: send to token { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' } 
[34mI20161019-13:41:31.401(0) Push: send to token { gcm: 'eFfpHeYd_wI:APA91bGEtw4cER2mC9Vj355O5uBnv6XRtumDbXl6G5opuO6NZwe4Bi-OuqHIMUk2doUyhLUDUJtL83D12Z6yc8se7_CoPtlX1LRijOrHE_T4X8pz5fvRlfABwcpmPj18IkjNny5sTZHl' } 
[34mI20161019-13:41:31.540(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:31.545(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:31.738(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (1 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:31.742(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (1 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:32.843(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (2 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:32.847(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (2 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:42.938(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:41:42.942(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:43:23.092(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (4 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:43:23.105(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (4 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161019-13:45:42.812(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (5 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } `

**Comment by Sonoma95SS** [comment]
I'm willing to pay for support if a developer would like to work with me directly to get this fully functional. We really love the setup and are excited to go live, just need the push to work for us.

**Comment by TheReal1604** [comment]
@Sonoma95SS Can you please send us some details about your infrastructure? Is your server behind a proxy? can you resolve the dns entry for the push gateway? Can you try to connect manually? I think it is a network related issue.

**Comment by Sonoma95SS** [comment]
Windows Server 2012 R2 running Ubuntu 16.04.1 LTS in Hyper-V, server is in a data center, I control the firewall instead of them(all inbound and outbound traffic goes directly to me), no proxy, gateway resolves

As far as the connect manually, elaborate if you don't mind.

`C:\Windows\system32>ping gateway.rocket.chat

Pinging gateway.rocket.chat [45.55.199.111] with 32 bytes of data:
Reply from 45.55.199.111: bytes=32 time=36ms TTL=57
Reply from 45.55.199.111: bytes=32 time=36ms TTL=57
Reply from 45.55.199.111: bytes=32 time=36ms TTL=57
Reply from 45.55.199.111: bytes=32 time=36ms TTL=57

Ping statistics for 45.55.199.111:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 36ms, Maximum = 36ms, Average = 36ms`

**Comment by Sonoma95SS** [comment]
![rocketchat](https://cloud.githubusercontent.com/assets/17284322/19523876/7d2d8e4e-95e1-11e6-9744-ed906eed7761.png)

**Comment by Sonoma95SS** [comment]
Just an update, I'm still having trouble with push notifications. Going to check the latest posts on here to see if there are any suggestions in the meantime.

**Comment by geekgonecrazy** [comment]
Please try a recent release and see if you still have this problem.

Key things here: 
* Make sure you have our gateway set and the gateway on.
* Make sure you join the channel from your mobile device **after** you do this.  So if you had joined before make sure to uninstall.  Clear application data and re-install.
* Make sure the Rocket.Chat server you have this installed on can communicate with the gateway.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
