### ISSUE TITLE
why meteor build not working

### ISSUE THREAD

**Issue by boulakar** [RocketChat/Rocket.Chat#4598]
Hi 

"meteor build" not working for me 

http://screencast.com/t/iOjtsnA2l

i use ubuntu 14 on AWS
and 
i used these steps 
  https://rocket.chat/docs/developer-guides/pre-requisites/

Thanks for your help

**Comment by gregmckeon** [comment]
If you just want to run the app, try just "meteor".  Meteor build packages for deployment, and needs an output directory.

**Comment by boulakar** [comment]
Thanks 
My goal is deployment so I must to use "meteor build " but not working :(

**Comment by MartinSchoeler** [comment]
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
