### ISSUE TITLE
Google sign-in 

### ISSUE THREAD

**Issue by dotocan** [RocketChat/Rocket.Chat#4599]
Hi,

I am trying to develop native Android application. My application uses websockets to communicate with the server, but since I can't find any documentation I have to look at network traffic in my browser using Chrome Dev Tools and see which websocket messages the browser sends to the server and which ones it receives as a response, and then implement those messages in my application. This is all going well so far, I am able to login using Rocket Chat credentials, get a list of rooms, send and receive chat messages and so on, but the problem occurs when I try to sign in via Google.

When I sign in with Google in browser, all I can see is this message being sent via websocket:
_[{
    "msg":"method",
    "method":"login",
    "params":[
        {
            "oauth":{
                "credentialToken":"some string",
                "credentialSecret":"some string"
            }
        }
    ],
    "id":"24"
}]_

The problem is, I don't have any idea how to get credentialToken and credentialSecret. All I can get from Google account stored in my phone are ID, IdToken and ServerAuthCode - and none of those strings looks even remotely similar to credentialToken and credentialSecret. 
I tried to send IdToken and ServerAuthCode anyway in a message mentioned above, and I received:

_"error":145546287,
"reason":"No matching login attempt found"_

I also tried hardcoding credentialToken and credentialSecret from web browser into my application but i receive the same error.

So to me it looks like there is some step in between that I can't see in Chrome Dev Tools. Like, when in browser I press Google sign in, the browser gets ID, IdToken and ServerAuth code (I guess) and sends some or all of those to the server, and the server then generates credentialToken and credentialSecret. That's just my assumption, of course it could work totally different.

I want to know what exactly do I have to do to sign in with Google, what do I have to send to the server, what do I receive, how to get those credentialToken and credentialSecret strings?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
