### ISSUE TITLE
Create Help / Shortcuts modal window

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#46]
##

**Comment by klatys** [comment]
Is there a list of shortcuts? so far I only noticed cmd/ctrl+p and those in window navigation

**Comment by stevoPerisic** [comment]
I'd like to have a go at this issue, would be good to start getting familiar w/ codebase. Are there any additional requirements like how to link to the modal?

**Comment by frdmn** [comment]
Would be indeed quite helpful, especially for new users of Rocket.Chat.

**Comment by karan-96** [comment]
i would like to work on this issue . Can i start working on it?

**Comment by danilomiranda** [comment]
How about that? Need some work on style, off course
![help-shortcut](https://user-images.githubusercontent.com/1092454/27163150-dd24e564-515b-11e7-812a-de849e5e030f.gif)

**Comment by danilomiranda** [comment]
Let me know if the "help / shortcut" can stay on flextab

**Comment by marceloschmidt** [comment]
Personally, I think a `/?` command would be best, then you could send a message seen only by that user (like when you try to `/join #invalid_channel`)

![image](https://user-images.githubusercontent.com/1986378/27226160-041f238c-5274-11e7-9634-e2e75b7edcf4.png)

**Comment by danilomiranda** [comment]
@marceloschmidt that`s even better!

**Comment by danilomiranda** [comment]
![help-shortcut](https://user-images.githubusercontent.com/1092454/27254910-f7cc2cf6-5368-11e7-8791-bdaed29b6861.gif)

**Comment by marceloschmidt** [comment]
I would like to see this `/help` being able to handle other slashcommands helps, such as `/leave`, `/ join`, etc. (eg. `RocketChat.SlashHelp.add('/leave #general', 'Leaves general channel');`)
