### ISSUE TITLE
Can't go beyond login screen with latest master

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#460]
I just pull the latest master and can't login with an existing or a new user.

In the console I can see that the confirmation email will not be sent ( I don't have configure my ```MAIL_URL``` ) but when I try to log in with that user shows the ```User not found``` error and if I try to create that same user again will said the the email already exists

**Comment by marceloschmidt** [comment]
You did have an installation before and you're trying to use the same user/pass you used before pulling changes? Can you access your meteor shell and reset your password, just to be on the safe side?

**Comment by oinirio** [comment]
I've try with my current installation and with a clear git clone and the result is the same

**Comment by marceloschmidt** [comment]
I've fixed this bug by setting user active:true upon registration. Thanks for the feedback. First error is also fixed.
