### ISSUE TITLE
Display current RocketChat version within clients

### ISSUE THREAD

**Issue by Nirkus** [RocketChat/Rocket.Chat#4612]
Your Rocket.Chat version: (not visible within clients)

Hey,
please display the current app version (client/server) within the clients.

As far as I understood, the client is JavaScript code downloaded from the server during login/connect. Still, the current version would be a practical peace of information to display within clients / for users while is currently only available to admins.

Gruß, Linus

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
