### ISSUE TITLE
Explanation Required: FlowRouter, queryParams, Layout, and "click-message-link"

### ISSUE THREAD

**Issue by netpoetica** [RocketChat/Rocket.Chat#4613]
`isEmbedded` is defined as such, in rocketchat-lib package:

```
RocketChat.Layout = new (class RocketChatLayout {
    constructor() {
        Tracker.autorun(() => {
            this.layout = FlowRouter.getQueryParam('layout');
        });
    }

    isEmbedded() {
        return this.layout === 'embedded';
    }
});
```

and the determination is made as to whether or not to `fireGlobalEvent` like so (showing compiled JS for readability):

```
$(document.body).on("click", "a", function(t) {
        var n;
        if (n = t.currentTarget,
        n.origin === s.rtrim(e.absoluteUrl(), "/") && /msg=([a-zA-Z0-9]+)/.test(n.search)) {
                if (t.preventDefault(),
                t.stopPropagation(),
                c.Layout.isEmbedded())
                        return fireGlobalEvent("click-message-link", {
                                link: n.pathname + n.search
                        });

                FlowRouter.go(n.pathname + n.search)
        }
        if ($(n).hasClass("swipebox") && c.Layout.isEmbedded())
                return t.preventDefault(),
                t.stopPropagation(),
                fireGlobalEvent("click-image-link", {
                        href: n.href
                })
})
```

How is one supposed to make sure that Layout.isEmbedded returns `true` so that this event will be fired properly? 

I do not see any place in the code where this is set, but I am assuming there is some sort of undocumented query param required at the time you are embedding an app in an iframe. I do not see any such documentation either in RocketChat docs or in FlowRouter docs.

Thanks!

PS: `packages/rocketchat-ui-master/master/main.coffee` is one amongst many files (almost all files in this project) that are really good candidates for some code comments (there are literally 0 comments throughout the entire file).

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
