### ISSUE TITLE
how to update to latest version if running on Docker 

### ISSUE THREAD

**Issue by nitinbhadauria** [RocketChat/Rocket.Chat#4617]
Hello Team,

How do we update from version 0.39.0 to latest without losing changes we made while using docker image ?

**Comment by guyspronck** [comment]
You should be using a separate docker container for the database, all the settings live in here. So as long as you have a backup of the database you can upgrade safely.

**Comment by TheReal1604** [comment]
@nitinbhadauria its like this: 

`docker stop rocketchat`
`docker rm rocketchat`
`docker pull rocketchat/rocket.chat:latest`
`docker-compose up -d` (If you use docker-compose, otherwise use your docker run command)

**Comment by geekgonecrazy** [comment]
Looks like this one is resolved.  I'm going to go ahead and close.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
