### ISSUE TITLE
Only possible to use username in CTRL+P dialog to switch to private chat.

### ISSUE THREAD

**Issue by Franziskus1988** [RocketChat/Rocket.Chat#4618]
In the versions before it was possible to switch to a private chat in CTRL+P dialog by typing first or last name of user. Now it's only possible with username. Can I change this in settings? Is it a bug? Or is it meant to behave like this?

Really missing the possibility to use first or last name.

Your Rocket.Chat version: 0.42

**Comment by adelura** [comment]
+1 I miss this functionality, especially when I have about 50 people in my chat, so it's very hard to find people now.

**Comment by CheungJ** [comment]
+1 I used this functionality very frequently.

**Comment by MatteoWebDesigner** [comment]
+1 I loved it, it was like using Atom

**Comment by gdelavald** [comment]
Hey,
just tested this and it is working as expected.
For `Real Names`, the search return the user real name in the user list, when using the default username view, the username will be returned with no mention of the full name, but the search is being filtered by that.
