### ISSUE TITLE
REST API usage stats

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#4619]
Your Rocket.Chat version: 0.42.0

Hey guys,

i've been wondering if theres an endpoint available to get the usage of rocket chat. E.g. getting the count of registered users.

Kind regards,

**Comment by graywolf336** [comment]
There is not, however it would be pretty easy to add. Assigning to myself to add this, however only admins would be able to get this information.

**Comment by graywolf336** [comment]
This will be closed when #5625 is merged
