### ISSUE TITLE
Admin and Commands

### ISSUE THREAD

**Issue by 112madgamer** [RocketChat/Rocket.Chat#462]
How do you know if your a admin and how do you set a admin

also what commands a currently on here

**Comment by Sing-Li** [comment]
How do you know:  your left blue drawer is different
How to set:  right now, you must access Mongo directly
What commands: we're still implementing it - give us a couple of weeks :smile:

**Comment by engelgabriel** [comment]
Hi, what version are you using? The latest commit from master? It should turn the first users to login into admin.. so there will be a last link on the left blue drawer. 
![image](https://cloud.githubusercontent.com/assets/1000217/9275793/1a079752-4276-11e5-8399-8dd68c7ee53c.png)

We have a few settings and user amin tools to ban and delete users.

![image](https://cloud.githubusercontent.com/assets/1000217/9275822/4343bac4-4276-11e5-8c67-e1910d44fc47.png)
