### ISSUE TITLE
When you add a emoji the send button does not show

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#4621]
![screenshot from 2016-10-13 11-20-31](https://cloud.githubusercontent.com/assets/20868078/19352692/23ef7350-9137-11e6-9eec-5db44e3dbe99.png)
it should be like this: 
![screenshot from 2016-10-13 11-20-48](https://cloud.githubusercontent.com/assets/20868078/19352705/36f78e38-9137-11e6-8064-9185cba683df.png)

**Comment by Prakharsvnit** [comment]
@MartinSchoeler I tested  this feature, it works for me.
![screenshot from 2017-04-12 14-32-19](https://cloud.githubusercontent.com/assets/19989448/24950108/7b7975e6-1f8d-11e7-9eea-f6f4c6aedc76.png)
