### ISSUE TITLE
change icon/logo

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#4625]
how to change the little smile icon/logo on the browser tab right next to Rocket.chat? I went in admin-assets and changed the favicon.png (256x256), still no change happened..

**Comment by MatthewFox7** [comment]
Hi, i have the same problem, can someone help us?

**Comment by justinbaciao** [comment]
Can't figure this out myself. Any tips would be most welcomed.

**Comment by geekgonecrazy** [comment]
You can do this in admin->assets.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
