### ISSUE TITLE
OTR Timeout

### ISSUE THREAD

**Issue by brady-young** [RocketChat/Rocket.Chat#4626]
Your Rocket.Chat version: 0.42.0

Hello,
We are having an issue with OTR where it will not work.  It either gives a timeout error after a few seconds or it will connect, prompt the other user to accept the OTR then it will give a time out error and red shield error on the other user.  

![rocketchat timeout](https://cloud.githubusercontent.com/assets/22377631/19368141/d77c5950-915b-11e6-9cef-a12cb7c5b5a4.PNG)
![otr](https://cloud.githubusercontent.com/assets/22377631/19368142/d95322c2-915b-11e6-8558-b02da315b9b0.png)
![redotr](https://cloud.githubusercontent.com/assets/22377631/19368144/dc7eb452-915b-11e6-8dc9-60660ab72993.png)

**Comment by jaceq** [comment]
I have the same issue...

**Comment by Nemra1** [comment]
I have the same issue...

**Comment by TheReal1604** [comment]
Same issue here.

**Comment by Venomen** [comment]
Same issue here on 0.44.0

**Comment by rockneverdies55** [comment]
:+1:

**Comment by Jazun713** [comment]
Seeing this on 0.50.1  Any status on this?

**Comment by Xarkam** [comment]
Same issue here on 0.51.0

**Comment by Jazun713** [comment]
I feel like this is tied to network config.

**Comment by Xarkam** [comment]
@Jazun713 I activated https on my domain and now It's running but him bug on chat display
![image](https://cloud.githubusercontent.com/assets/331816/22890956/194f72a0-f20e-11e6-8982-c04fc8551bd7.png)
Message are displayed with no order. And no timestamp on each message :frowning:

**Comment by geekgonecrazy** [comment]
Yes sounds like the issue here for most is ssl.  You must be accessing over https for this to work.  

Going to go ahead and close since most messages are old.
