### ISSUE TITLE
hubot RC adapter  installation issue 

### ISSUE THREAD

**Issue by Jasmine2010** [RocketChat/Rocket.Chat#4629]
when i install hubot alwasy get the npm permission issue, i tried NVM and two options on https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory
still couldn't fix it.

what should i do?

**Comment by geekgonecrazy** [comment]
Please open an issue here: https://github.com/rocketchat/hubot-rocketchat and give a little more info on what you've tried and the specific error you've gotten
