### ISSUE TITLE
Can't build rocket.chat with meteor 1.4.1.2.

### ISSUE THREAD

**Issue by SongTreasure** [RocketChat/Rocket.Chat#4631]
Hello.
I am newbie of meteor and rocket.chat.
Rocket.chat is latest.
I can't build rocket.chat on windows 10.

D:\Work\Rocket.Chat\new\Rocket.Chat>meteor
[[[[[ ~\D\Work\Rocket.Chat\new\Rocket.Chat ]]]]]

=> Started proxy.
=> A patch (Meteor 1.4.1.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at DirWriter.<anonymous> (C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at DirWriter.emit (events.js:166:7)
    at C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:38:10
    at C:\Users\sch\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\mkdirp\index.js:30:20
    at FSReqWrap.oncomplete (fs.js:82:15)

What problem?

**Comment by MichalW** [comment]
This same here:
`$meteor`
`/home/michal/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165`
`      throw error;`
`      ^`
` `
`Error: ENOENT: no such file or directory, open '/tmp/mt-1sussnk/os.json'
    at Error (native)`

**Comment by MichalW** [comment]
https://github.com/meteor/meteor/issues/7923

**Comment by harish-myaccount** [comment]
This is my error stack when i tried rocket chat
=> Errors prevented startup:                  package rocketchat:migrations    -
    2016 Microsoft Corporation. All rights reserved.
   While building package rocketchat:cas:
   error: couldn't install npm packages from npm-shrinkwrap: Command failed:                 Building package rocket
   C:\Users\Rajeswari\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
   install:slackbridge: updating npm dependencies -- slack-c
   npm ERR! git fetch -a origin (https://github.com/kcbanner/node-cas.git) fatal: Unable to find remote helper
   for 'https'um: updating npm   Building package rocketchat:migrations    /
   npm ERR! Windows_NT 10.0.14393pm dependencies -- less, less-plugin-autoprefix...
   npm ERR! argv                              ndencies -- xml2js, xml-crypto, xmldom, connect, xmlbuilder,
   "C:\\Users\\Rajeswari\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"/initializing project:
   "C:\\Users\\Rajeswari\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "install"n't install np   Building package rocketchat:message-star  /:
   npm ERR! node v4.6.0ata\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\bin\npm.cm
   npm ERR! npm  v3.10.8
   npm ERR! code 128a origin (https://github.com/kcbanner/node-cas.git) fatal: Una   Building package rocketchat:mes
   e-star  /
   npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
   npm ERR! fatal: Unable to find remote helper for 'https'
   npm ERR! Rajeswari\   Building package rocketchat:message-star  /l\\1.4.1_2\\mt-os.windows.x86_32\\dev_bundle\\bi
   npm ERR!
   npm ERR! If you need help, you may report this error at:eteor-tool\\1.4.1_2\\mt-os.windows.x86_32\\dev_bundle\\li
   npm ERR!     <https://github.com/npm/npm/issues>                              Building package rocketchat:message
   n   |"
   npm ERR! Please include the following file with any support request:
   npm ERR!m  v3.10.8
   D:\Coding\Workspace\meteor\Rocket.Chat\packages\rocketchat-cas\.npm\package-new-em7n8n\npm-debug.log
   npm ERR! git fetch -a origin (https://github.com/kcbanner/node-cas.git) fatal: Unable to find remote helper
   for 'https'                    re.longpaths=true fetch -a origin
   npm ERR! Windows_NT 10.0.14393mote helper for 'https'                     Building package rocketchat:message-pin
   npm ERR! argv
   "C:\\Users\\Rajeswari\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" need help, you may report this error at:
   "C:\\Users\\Rajeswari\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "install"                  llowing file with any support request:
   npm ERR! node v4.6.0Workspace\meteor\Rocket.Chat\packages\rocketcha   Building package rocketchat:message-m...  |
   npm ERR! npm  v3.10.8igin (https://github.com/kcbanner/node-cas.git) fatal: Unable to find remote helper for
   npm ERR! code 128
    ERR! Windows_NT 10.0.14393
   npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
   npm ERR! fatal: Unable to find remote helper for 'https'eteor-tool\\1.4.1_2\\mt-os.windows.x8
   npm ERR!
   npm ERR! Rajeswari\\AppData\\Local\\.meteor\\packages\\meteor-t   Building package rocketchat:message-a...  |\\li
   npm ERR! If you need help, you may report this error at:
   npm ERR!     <https://github.com/npm/npm/issues>
    ERR! node v4.6.0             Loading package yasinuslu:blaze-meta@...  -              => Your application has er
rors. Waiting for file change. following file with any support request:

   D:\Coding\Workspace\meteor\Rocket.Chat\packages\rocketchat-cas\.npm\package-new-em7n8n\npm-debug.log
    ERR! Command failed: git -   Loading package yasinuslu:blaze-meta@...  -ckage rocketchat:message-a...  \
    ERR! fatal: Unable to find remote helper for 'https'

npm ERR!
np   Building package rocketchat:mentions-...  \rror at:
npm ERR!     <https://github.com/npm/npm/issues>                                                                    
npm ERR! Please include the following file with any suppor   Building package rocketchat:mentions-...  \
npm ERR!     D:\Coding\Workspace\meteor\Rocket.Chat\packages\rocketchat-cas\.npm\package-new-52cos4\npm-debug.log

                                                                                                                     Building package rocketchat:mentions      \
D:\Coding\Workspace\meteor\Rocket.Chat>                                                                             
D:\Coding\Workspace\meteor\Rocket.Chat>meteor            Building package rocketchat:mentions      \
[[[[[ ~\D\Coding\Workspace\meteor\Rocket.Chat ]]]]]

=> Started proxy.                                                                                                Building package rocketchat:markdown      \
rocketchat:cas: updating npm dependencies -- cas...                                                                           g package rocketchat:livechat      \
WARNING: The output directory is under your source   Building package rocketchat:markdown      \
         Your generated files may get interpreted as source code!
         Consider bu
         meteor build ../output                                                                              Building package rocketchat:markdown      -
A subdirectory or file ..\public already exists.                                                                          d file - D:\Coding\Workspace\meteor\Rocket.Chat\packages\rocketchat-livechat\public\head.html
.meteor/build/bundle/programs/web.browser\3b5b   Building package rocketchat:mapview       -
1 File(s) copied
.meteor/build/bu                                              b13296ac3d9398d063b1.js
1 File(s) copied                                                                                         Building package rocketchat:mapview       -b.browser\head.html
1 File(s) copied                                                                                                      eteor\build\bundle\programs\server\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-syntax-trailin
g-function-commas\test\fixtures\trailing-f   Building package rocketchat:mailer        -is not empty.
.meteor\build\bundle\programs\server\npm\node_modules\meteor\babel-compiler\node_modules\babel-plugin-syntax-trailing-function-c                                              all\expected.js - The file name is too long.
.meteor\build\bundle\programs\server\npm\node_modules\meteor\babel-compiler\node_modules\babel-plu   Building package rocketchat:mailer        -res\trailing-function-commas\declaration\actual.js - The file name is too long.
.meteor\build\bundle\programs\server\npm\node_modules\meteor\babel-c                                              in
g-function-commas\test\fixtures\trailing-function-commas\declaration\expected.js - The file name is too long.
.meteor\build\bundle\programs\server\n   Building package rocketchat:mailer        -ules\babel-plugin-syntax-trailin
g-function-commas\test\fixtures\trailing-function-commas\new-expression - The directory is not empty.
.meteor\                                              meteor\ddp-client\node_modules\faye-websocket\node_modules\web
socket-driver\node_modules\websocket-extensions\lib\pipeline\ring_buffer.js - The file name is   Building package rocketchat:mailer        -grams\server\npm\node_modules\meteor\ddp-client\node_modules\faye-websocket\node_modules\web
socket-driver\node_modules\websocket-extensions\lib\websocket_ex
.meteor\build\bundle\programs\server\npm\node_modules\meteor\ddp-server\node_modules\sockjs\node_modules\faye-websocket\node_modules\websocket-driver\   Building package rocketchat:livechat      /able - The file name is too long.
.meteor\build\bundle\programs\server\npm\node_modules\meteor\ddp-server\node_modules\sockjs\node_modules\faye-websocket\                                              socket-extensions\CHANGELOG.md - The file name is too long.
.meteor\build\bundle\programs\server\npm\node_modules\meteor\ddp-server\node_modules\sockj   Building package rocketchat:livechat      /socket-driver\node_modules\websocket-extensions\lib - The directory is not empty.
.meteor\build\bundle\programs\server\npm\node_modules\meteor                                              aye-websoc
ket\node_modules\websocket-driver\node_modules\websocket-extensions\package.json - The file name is too long.
.meteor\build\bundle\programs\   Building package rocketchat:livechat      /_modules\sockjs\node_modules\faye-websoc
ket\node_modules\websocket-driver\node_modules\websocket-extensions\README.md - The file name is too long.

**Comment by graywolf336** [comment]
This is a higher up issue, please see this Stackoverflow answer that just worked for me. http://stackoverflow.com/questions/39153477/how-do-i-resolve-this-error-enoent-no-such-file-or-file-or-directory-open-t/39174861#39174861
