### ISSUE TITLE
504 Gateway time-out 

### ISSUE THREAD

**Issue by joybhadhanroy** [RocketChat/Rocket.Chat#4632]
Your Rocket.Chat version: (latest)
AWS Ubuntu 14.04 LTS

I am trying to deploy rocketchat server in AWS EC2 ubuntu instance. I am following this [official document](https://rocket.chat/docs/installation/paas-deployments/aws/) for the installation. For free domain I registered a free domain with freenom.com. 

After I have deployed rocketchat, while I try to access it on browser, I get 504 Gateway timeout error. I can ssh to the ubuntu instance without any problem.

Any suggestion how I can debug the issue would be highly appreciated.

**Comment by TheReal1604** [comment]
@joybhadhanroy there is an issue in the documentation... 

change 
``` proxy_pass http://<ABC.DOMAIN.COM>:3000/;```
to 
``` proxy_pass http://localhost:3000/; ```

Can you please try that and send an info if it works?

Thx.

**Comment by joybhadhanroy** [comment]
Thanks, it has solved the issue. And closing it.

**Comment by TheReal1604** [comment]
@MartinSchoeler can you do something regarding to this documentation issue?
