### ISSUE TITLE
S3 file uploads don't get deleted from S3

### ISSUE THREAD

**Issue by cdhowie** [RocketChat/Rocket.Chat#4634]
Your Rocket.Chat version: 0.42.0

When deleting uploaded files using the FileSystem backend, files get deleted from the disk.  When using the AmazonS3 backend, the uploaded files remain in S3 even after they are deleted from the Rocket Chat interface.  The relevant IAM user has permission to delete S3 objects, and there are no errors in the Rocket Chat log indicating that the deletion was attempted or failed.

**Comment by matyee** [comment]
Same here with Rocket.Chat version 0.43.0.

**Comment by cdhowie** [comment]
I can't reproduce anymore on 0.44.0.  I have two theories:

1. This was fixed in 0.44.0.
2. A restart of the Rocket Chat service is *required* to fully apply this change.  We've already found some other (undocumented!) cases where settings aren't applied unless the service is restarted.  (For example, the custom emoji filesystem settings.  I updated that to store images on the disk, but new emoji uploads were still going into the database.  When we next restarted the server, all the emoji were missing because Rocket was suddenly looking on the disk for them, and we have to pull them all out of the DB...)

**Comment by steven-tib** [comment]
Version 0.51.0 
Have the same issue here. Tried to restart the container but didn't work. 
@cdhowie which version are you now using and is this still ok for you? 
Thank you

**Comment by general-naga** [comment]
Having the same issue on 0.60.4. Files deleted via the UI are not deleted from the S3 bucket. Tried restarting the server but same result.

I'm using the CORS in the documentation & left the ACL unset. CDN is also unset.

Reviewing the logs all I see is this:
`[34mI20180119-11:11:01.324(0) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method deleteFileMessage -> userId: P3jo6j3FEnXXPB9ju , arguments:  { '0': 'ZUpRcdeutfSFTRtsS' } `

**Comment by geekgonecrazy** [comment]
We know for sure delete works now days :) closing
