### ISSUE TITLE
"who is writing" getting mixed with tips under input line

### ISSUE THREAD

**Issue by landergate** [RocketChat/Rocket.Chat#4636]
Your Rocket.Chat version: 0.42.0

Small interface issue, nothing serious.

Currently tips under the input line and names, who are writing right now, getting mixed:
![2016-10-14_19-31-22](https://cloud.githubusercontent.com/assets/904839/19395300/9fc1a93a-9245-11e6-87af-7445d32545d0.png)

It could be a good idea to add some background for "<nickname> is writing" text.

**Comment by MartinSchoeler** [comment]
This was fixed by the new design
