### ISSUE TITLE
More noticeable message options button

### ISSUE THREAD

**Issue by landergate** [RocketChat/Rocket.Chat#4638]
Your Rocket.Chat version: 0.42.0

Maybe we can design some more noticeable buttons for message options?
Like something bigger, or appearing on hover?

Right now it's not very intuitive on what user can do with message, and for some users it's not very comfy to target this small cog everytime.

Not a big deal, just user experience (and some comparison to Slack, as Rocket.Chat is trying to keep it's main design concepts).

**Comment by lucasvanhalst** [comment]
I agree, and there are just too many buttons at the moment and some of them aren't even all that useful.

**Comment by MartinSchoeler** [comment]
Please see our ui redesign on [demo](https://demo.rocket.chat) server
