### ISSUE TITLE
Global setting on converting ASCII emoticons to emojis

### ISSUE THREAD

**Issue by landergate** [RocketChat/Rocket.Chat#4639]
Your Rocket.Chat version: 0.42.0

Not everybody likes, when their `:)` converts to some huge emoji.
And even if you disable this convertation on your side, you wouldn't know that your reader would receive it still as huge emoji.

Maybe it's possible to disable ascii convertations on global level? Like, set is as "False" by default, but allow to enable this on your preferences.

**Comment by sampaiodiego** [comment]
there is a server level default preference for that already under `Admin > Accounts > Default User Preferences > Convert ASCII to Emoji`
