### ISSUE TITLE
Room Permissions based on Role

### ISSUE THREAD

**Issue by derrickdunville** [RocketChat/Rocket.Chat#4645]
I would like to see a way to control the permissions of the various rooms on a server based on the role of the user. 

Ie. If user is Admin role they are allowed to post in a room and Moderator and User role can not post.
If user is Admin or Moderator role they are allowed to post in room and User role can not post.

**Comment by engelgabriel** [comment]
Not sure I understand @derrickdunville. Have you already tried changing the settings in the admin panel to reflect what you have described?

**Comment by MartinSchoeler** [comment]
Hey @derrickdunville , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Comment by Sparkfiber** [comment]
Actually this is a feature that would be very helpful - currently you cannot group users with a global role and allow access to that group in rocket.chat as far as I can see. Being able to gate off access to rooms based on a global role/group would be extremely helpful. 

For example: having a role for marketing - allowing all members with the marketing access to marketing-related rooms but not access to HR rooms. 

Currently you have to add users to private rooms - but if you want larger private rooms it is a pain to individually add each user to multiple rooms vs adding a role to each user who needs access to multiple private rooms.

I am surprised nothing like this was implemented yet as it is a concept that people are able to easily understand if they have used Discord at all - it allows a lot more flexibility and security for administrators.

**Comment by shortstack** [comment]
@MartinSchoeler @senethz @derrickdunville @engelgabriel 

bumping for feature request!!!

we need to be able to have users dropped into their respective private rooms/groups based on the global role that gets assigned via SSO/oauth

currently, assigning them to a role gives them that role , but that role can't designate what private group/room they get put in because the role is only scoped globally

**Comment by danielbarankin** [comment]
Agreed, it would be helpful to have that functionality.
