### ISSUE TITLE
Meteor build failure

### ISSUE THREAD

**Issue by markhorsman** [RocketChat/Rocket.Chat#4646]
When I try to run Rocket.Chat using meteor --port 333 I get the following error:

/home/markhorsman/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-75m2ti/os.json'
    at Error (native)

Meteor version: 1.4.1.2
Ubuntu 16.04

Any ideas how to fix this?

**Comment by frdmn** [comment]
Maybe a DNS issue?

http://stackoverflow.com/a/39174861/2940412

**Comment by markhorsman** [comment]
Works! Thanks a lot!

**Comment by adelgado** [comment]
Could we re-open this issue? I'm having this problem and granting trust to a random IP doesn't make me particularly comfortable. Are there known workarounds?
