### ISSUE TITLE
XSS in email validation (tooltip)

### ISSUE THREAD

**Issue by winnie22** [RocketChat/Rocket.Chat#4650]
Rocket.Chat version: 0.43.0

Hi,
I've found 2 reflected XSS in email validation functionality when tooltip is shown. First is in My Account -> Profile -> Email. When you add [script]alert(1)[/script] to email field and save changes, you will get Invalid email error and js code is executed. Similar vulnerability is in registration (email field). When you insert [script]alert("XSS")[/script].xx@test.cz as email and click register new account, js code is executed when Invalid email error is shown.

**Comment by attritionorg** [comment]
Was this issue resolved or determined to be invalid?

**Comment by winnie22** [comment]
Definitely not fixed in 0.45.0
![rocketchat_xss](https://cloud.githubusercontent.com/assets/6103248/20486609/ad24f298-b000-11e6-8224-e4a5ff8d0756.png)

**Comment by winnie22** [comment]
Neither in 0.46.0

**Comment by attritionorg** [comment]
Per https://github.com/RocketChat/Rocket.Chat/blob/develop/SECURITY.md, have you tried emailing them with this information?

**Comment by MichalStaruch** [comment]
@attritionorg How about adding [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy) header to block inline scripting? Something like
`Content-Security-Policy: default-src 'self'`
or
`Content-Security-Policy: script-src 'self'; object-src 'none'`
for a starter - it would improve Rocket.Chat security a lot.

**Comment by attritionorg** [comment]
I am not a developer for this project. Just trying to determine if the issue was acknowledged and/or fixed.
