### ISSUE TITLE
Add rootUrlPathPrefix for OAuth views

### ISSUE THREAD

**Issue by Huljo** [RocketChat/Rocket.Chat#4653]
Your Rocket.Chat version: 0.43.0

I'm running Rocket.chat in a subfolder and I attempt to use OAuth but views arn't including subfolder prefix.
_programs/server/assets/packages/oauth/end_of_popup_response.html_

``` html
[...]
  <script type="text/javascript" src="/packages/oauth/end_of_popup_response.js"></script>
[...]
```

The file end_of_popup_response.js is still absolute URLed to '/'.
The script can't be loaded and I just get a blank page.

**Comment by Irker** [comment]
Also login with custom OAuth send redirect uri to OAuth server with absolute path "https://example.com/_oauth/custom_oauth"  instead something like "https://example.com/subfolder/_oauth/custom_oauth"

**Comment by Huljo** [comment]
Fix incoming : https://github.com/meteor/meteor/pull/8081
