### ISSUE TITLE
use Rchat authentication to login user for other website

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#4655]
Your Rocket.Chat version: 0.42

I have my own website and it has its own authentication. However I want to integrate authentication of my own website and rchat, I know i can't use my website's authentication to login rchat, is it possible to use Rchat authentication to login user from my website? all i can see here is how to login rchat using other vendor, like google, facebook, I want the other way around, let me know if it is possible and what tool i should use to make that happen.

**Comment by Xqua** [comment]
You can (theoretically, I'm working on it but have not yet succeeded) use and LDAP server on your website, that register users in the LDAP DB. 
Then have RC connect to the same LDAP DB.
That way credentials are checked against the same LDAP DB. 

Another cheap trick, you use Google Auth to login everyone on your website and on RC, that way ... you have a unique ID accross instances.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
