### ISSUE TITLE
Mobile App Slow When Resuming From Background

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#4656]
Your Rocket.Chat version: (make sure you are running the latest)

Whenever you resume RC (cordova) it takes about 10 seconds before the app becomes responsive. During this time I know data is being d/l'ed from the RC server. It's incredibly frustrating when you try to scroll and the app does nothing during this process. Any ideas?

This is not related to the Meteor.reconnect() where the app needs to reestablish a connection to the RC server.

**Comment by Syirrus** [comment]
[possible solution](https://github.com/RocketChat/Rocket.Chat.Cordova/issues/130)

**Comment by ggazzo** [comment]
@Syirrus rocketchat cordova is deprecated
