### ISSUE TITLE
How to get push notification to work again on android (tooltip)

### ISSUE THREAD

**Issue by Xqua** [RocketChat/Rocket.Chat#4657]
Your Rocket.Chat version: (0.42)

Hi,

so at the begining of time push was working great ! But then, push stoped working, the why I do not know. BUT if you find yourself having no push on android, here are the steps that made it work for me:

Uninstall the RC app
Reinstall the RC app

DONE ! 

When looking at the log, I noticed that the Token that was send by the app to the server has changed.
Thus I am wondering if the app is not storing a wrong token and passing it ? I will see if it stops working again, then I'll assume that it has something to do with token passed by the app !

**Comment by lucasvanhalst** [comment]
Didn't fix it for me. When I press 'test notification' it does nothing except for deleting the push token again, so when pressing it a second time it says no mobile tokens are found.

**Comment by Xqua** [comment]
@lucasvanhalst what are your push setting in RC ?

**Comment by lucasvanhalst** [comment]
nothing special, just the defaults ![](https://i.imgur.com/fWwLqOG.png)

**Comment by Xqua** [comment]
Sorry at that point I'm not sure ... what I can do to help then ... are you using theither latest version of RC ? 
You should activate the debug mode and look at the logs to check what is going on

**Comment by rasos** [comment]
And push works only with the Android App downloaded from the Google Play Store, not wehn side-loaded, except when you register your own push keys.

**Comment by shellster** [comment]
Tried all the suggestions in this thread, nothing works for me.  When I turn on debugging it shows gcm keys and all, and appears to think I actually got the push, but I don't.

I deleted my version and went to the play store and grabbed the latest copy

**Comment by geekgonecrazy** [comment]
I know this issue is old.  But just to clarify.  If you are using our apps from the app store make sure you are using our gateway on your server.

If you have built or sideloaded your own, you will need to get tokens and set all of that up.
