### ISSUE TITLE
iOS push notification broken (android 100% functional) 

### ISSUE THREAD

**Issue by Xqua** [RocketChat/Rocket.Chat#4658]
Your Rocket.Chat version: 0.44

So, I am using the default app
and the default gateway 
I have nothing on the APN or GCM fields. 

Push works great on android ! 
But I can't figure out how to make it work on iOS, no one receive anything. 

Is there some magic I am missing ? 

Thanks !

**Comment by Xqua** [comment]
I can add that I see iOS user registering there token on the debug log, and that RC sends push to their token. 
And that reinstalling the app generates a new token.

**Comment by acrogenesis** [comment]
I have this settings and it works on iOS and android my **Certificates and Keys** are empty.
<img width="708" alt="screen shot 2016-10-26 at 10 18 37 pm" src="https://cloud.githubusercontent.com/assets/1312687/19753437/2e5ece24-9bca-11e6-8b12-ed5e793fc319.png">

**Comment by Xqua** [comment]
So after further test it seems this is due to the iOS 10 upgrage

**Comment by marbetschar** [comment]
same issue here :( when will this be fixed?

**Comment by sampaiodiego** [comment]
since this is a very old issue and there is no such complains on newer rocket.chat versions, I'll close this issue.

please let me know if this is still an issue and I can reopen it. thx
