### ISSUE TITLE
Messenger like Status

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#4659]
Your Rocket.Chat version: 0.42.0

Hey guys,

i've been wondering if theres a planning implementing a status field for Users. Like e.g. Skype have.

Kind regards,

**Comment by graywolf336** [comment]
@hExPY Mind providing a screenshot of what you mean and how you see it being implemented inside of Rocket.Chat?

**Comment by engelgabriel** [comment]
dup https://github.com/RocketChat/Rocket.Chat/issues/2422
