### ISSUE TITLE
Outgoing webhooks for all channels and direct messages

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#4662]
We would like to use this - https://rocket.chat/docs/administrator-guides/integrations/giphy
for all possible kinds of rooms and messages. As of now I can leave the "Channel (optional)" option in Webhooks menu empty, but this means that the webhook will be available just in all public channels. Is there any way how to use the webhook everywhere and let the users use giphy (and other webhooks of course) everywhere?

Thanks.

**Comment by danpospisil** [comment]
0.45.0 brings this feautre - thank you all! :)

**Comment by biphasic** [comment]
what do I then insert? leaving the field blank does not work on private messages in 0.48
Thanks

**Comment by davidfm** [comment]
Might be too late but just for people who come from Google, I've done this to enable the webhook on all channels.

Channel: `all_public_channels,all_private_groups,all_direct_messages`
