### ISSUE TITLE
Add Labels to our Docker Containers

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#4665]
See for label options:
http://label-schema.org/rc1/ 

I have none at the moment:
https://microbadger.com/images/rocketchat/rocket.chat

We should have at least licence, git url, and vcs-ref

**Comment by hugocostadev** [comment]
Is this still valid?  
I saw that the label schema was deprecated...  
 And I think that the docker containers are consolidated at https://hub.docker.com/u/rocketchat, right?  Thanks
