### ISSUE TITLE
Cannot change channel name

### ISSUE THREAD

**Issue by Xqua** [RocketChat/Rocket.Chat#4669]
Your Rocket.Chat version: latest

Upon changing a channel name the save button does not work. I can click on it but it does not 1) change the channel name 2) disappear as if it accepted the change.

There is nothing in the logs either.

**Comment by Xqua** [comment]
Update: So I forgot to check the browser console
On click I am getting this error message :

> 3d0a28d904f450b3cfeed1ccc35c905f68483edb.js?meteor_js_resource=true:234 Uncaught TypeError: this.validateRoomName is not a function

**Comment by graywolf336** [comment]
@Xqua Please actually provide a version and not "latest", we won't be able to help you until you actually provide that.

**Comment by Xqua** [comment]
I was at 0.43 just updated to 0.44 and the bug is gone. We can close this as I tried on another 0.43 and no issue.
