### ISSUE TITLE
Slack Bridge and BOT's posts

### ISSUE THREAD

**Issue by tpaycom** [RocketChat/Rocket.Chat#4677]
Your Rocket.Chat version: (0.42)
Hi guys!
I've made slack BOT called rocketbot, invited him to some channels on Slack, and added his token to RocketChat slack bridge. Everything is working fine, when I post a message on slack channel, I get it in my RocketChat channel.
But there is one problem: I have some integrations with services which are only for slack like Brand24, which posts me some messages on slack channels. Brand24 is a BOT but its not configurable, and my rocketbot doesn't posts his messages to RocketChat. I've made an user on RocketChat with same name as BOT on slack but nothing happens.
Can anybody help me with that?
Or maybe the better way is to add outgoing hook on slack and incomming on RocketChat, but I actually don't know how to process data from slack with custom script.

**Comment by kuba-rogalski** [comment]
Hey there, I am afraid I won't be able to help with RocketBot, but I wanted to add a few words about Brand24. 
At first, many thanks for using it! As some people reading this might not be aware of this fact, it's not a service only for Slack but a comprehensive social media monitoring tool. Slack integration is one of the available features and it's also configurable to some extent as you can use the filters within the tool and only streamline the filtered results into the integrated Slack channel. 
Hope you'll get your problem with RocketBot solved!

**Comment by tpaycom** [comment]
Brand24 told me, that is impossible to do it by rocketbot and I should use webhooks.
I've made outgoing webhook on slack, but I don't have any idea how to process data from slack in incoming webhook on RocketChat.
As far as I know slack sends data using POST or GET method but RocketChat scripts are in JS which can't capture this data.

**Comment by kuba-rogalski** [comment]
Oh, sorry I misunderstood the connection between Rocketbot and Brand24 in your initial post then.

**Comment by tpaycom** [comment]
I don't think so ;)
It's still this chain of data transfer brand24-slack-rocketchat.
rocketbot is a custom made bot on slack, and brand24 is a bot made by slack app.

**Comment by marceloschmidt** [comment]
@tpaycom I'll take a look at your issue. I admit I didn't play with bots in slack to see how they'd integrate with our slackbridge, and will do it now.

**Comment by tpaycom** [comment]
I would be very greatful if you could implement this and release in new version :)
I'm looking forward to your progress.
Best regards!
