### ISSUE TITLE
Microsoft Azure Active Directory Oauth

### ISSUE THREAD

**Issue by matyee** [RocketChat/Rocket.Chat#4681]
We need integration with Microsoft Azure OAuth. The custom OAuth module works well until the point the user details is retrieved. In the case of Azure AD the user information needs to be queried from the Microsoft Graph service. I can set the the URL, but Graph API require custom header name for the token, other than standard OAuth.

I would like to make the modifications to handle Azure AD OAuth. What would be your preference? 1) Create a completely new setup section for Azure AD, 2) Add new option to custom OAuth module which specifies the name of the Header how the OAuth token is sent.

I am not sure yet if the second option is possible, maybe custom curl call is necessary to get the user info.

Could you please provide me as much information as possible in order to guide me?

**Comment by matyee** [comment]
I was wrong, that's not just a different header. I could modify the CustomOAuth to get the user details. The getAccessToken function need to send an additional resource parameter that specifies that the token will be used with the Graph AD service. The generated token can be used to get the user details, but the returned user object is custom:

```
{ 'odata.metadata': 'https://graph.windows.net/.../$metadata#directoryObjects/Microsoft.DirectoryServices.User/@Element',
     'odata.type': 'Microsoft.DirectoryServices.User',
     objectType: 'User',
     objectId: '...',
     deletionTimestamp: null,
     accountEnabled: true,
     signInNames: [],
     assignedLicenses: [ [Object], [Object], [Object] ],
     assignedPlans:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     city: '...',
     companyName: '...',
     country: null,
     creationType: null,
     department: '...',
     dirSyncEnabled: null,
     displayName: '...',
     facsimileTelephoneNumber: null,
     givenName: '...',
     immutableId: null,
     isCompromised: null,
     jobTitle: '...',
     lastDirSyncTime: null,
     mail: '...',
     mailNickname: '...',
     mobile: null,
     onPremisesSecurityIdentifier: null,
     otherMails: [ '...' ],
     passwordPolicies: 'None',
     passwordProfile: null,
     physicalDeliveryOfficeName: '...',
     postalCode: '...',
     preferredLanguage: 'en-US',
     provisionedPlans: [ [Object], [Object], [Object], [Object], [Object] ],
     provisioningErrors: [],
     proxyAddresses:
      [ ... ],
     refreshTokensValidFromDateTime: '2016-07-18T10:56:32Z',
     sipProxyAddress: '...',
     state: 'BNES',
     streetAddress: null,
     surname: '..',
     telephoneNumber: null,
     usageLocation: '...',
     userPrincipalName: '...',
     userType: 'Member' 
}
```

All the required information is there, but not the right structure. The provided user object can't be saved as serviceData: 

```
Exception while invoking method 'login' MongoError: The dotted field 'odata.metadata' in 'credential.serviceData.odata.metadata' is not valid for storage.
```

Modifying the CustomOAuth will be messy with the exceptions for Microsoft. I think the best would be to create a new Oauth setting section for Microsoft AD and create a new handler instead of CustomOAuth. What do you think about this solution?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
