### ISSUE TITLE
List of channels alphabetically out of order if channel name begins with a capital letter.

### ISSUE THREAD

**Issue by goobersmooch** [RocketChat/Rocket.Chat#4682]
Rocket.Chat version: 0.43.0

If you name all of your channels using lowercase characters, they get listed alphabetically.

If you have a channel name that begins with a capital letter, then it puts that channel at the top.

For example:

Channel-a
Channel-b
Channel-c
a-channel
channel-a
channel-b
channel-c

It would be nice if they were not case sensitive so that all channels would be in alphabetically order.

**Comment by marceloschmidt** [comment]
This is not yet available by MongoDB. It will be available in their next major version: https://jira.mongodb.org/browse/SERVER-90.

**Comment by ggazzo** [comment]
closed by #10697
