### ISSUE TITLE
livechat transcript option for agents 

### ISSUE THREAD

**Issue by AlecTroemel** [RocketChat/Rocket.Chat#4684]
Rocket.Chat version: 0.43

currently only livechat guest's can recieve a transcript, it would be nice for agents on the other side of that conversation also

**Comment by deep0892** [comment]
Yup, this would be a good addon.
if not to the agents, the script should be delivered to the livechat managers.

**Comment by juliomac** [comment]
+1

**Comment by CONFORM-IT** [comment]
+1

Either the transcript is sent to a static address that the admin can configure, or the agent has to put in the destination address himself. The transcript should contain not only the messenges but also the timestamps.

**Comment by dairaine** [comment]
+1

**Comment by rlmccallu** [comment]
+1

**Comment by rodrigok** [comment]
Maybe have a setting to define the roles that would receive the email.

**Comment by paulobernardoaf** [comment]
Hey Guys, any solid plan of adding this in the near future?

**Comment by rrcamc** [comment]
We are also anxiously anticipating this feature.

**Comment by hugocostadev** [comment]
Fixed
