### ISSUE TITLE
Allow login on custom oauth services using iframe events

### ISSUE THREAD

**Issue by fabiomontefuscolo** [RocketChat/Rocket.Chat#4685]
I would like to have the rocket.chat in a iframe. Whe user login on my website and use the chat section, he will automatically be logged in RocketChat, using my website as an oauth provider to send credentials.

**Comment by IQ2022** [comment]
What is your website using?? Wordpress with social login?

**Comment by fabiomontefuscolo** [comment]
@IQ2022  No, I'm using Django with the django-oauth-toolkit plugin.

**Comment by anthonymanzo** [comment]
Wow, it's been 5 years and I need help with this same thing.  I'm using Django, and trying to configure Django Oauth Toolkit to get the same functionality -- If a user is logged into Django, they can automatically get logged in to the chat, which I have in an iframe.  I've been using iframe auth before this, but it has been flakely, hoping this is more solid. 
Cheers
