### ISSUE TITLE
Could not log in the browser UI using logon REST API

### ISSUE THREAD

**Issue by rojesh** [RocketChat/Rocket.Chat#4690]
I'm new to rocket chat and was exploring the REST api. I tried login in my rocket chat account using the logon api. It returns me the success response just as stated in the documentation but it doesn't logs me in the browser. Is this the expected behaviour? Is there a way to login in the browser using the api?

```
curl http://localhost:3000/api/login \
     -d "user=myusername&password=mypassword"

{
  "status": "success",
  "data": {
      "authToken": "9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq",
      "userId": "aobEdbYhXfu5hkeqG"
   }
}
```

**Comment by anaida07** [comment]
@MartinSchoeler  I am also facing the same issue. Is this something that needs to be build or are we implementing in a wrong way?

**Comment by graywolf336** [comment]
Yes, that is the expected behavior. The rest api and items it returns is only to be used for other rest api calls.
