### ISSUE TITLE
How to backup ubuntu snap installation

### ISSUE THREAD

**Issue by d-sko** [RocketChat/Rocket.Chat#4692]
Your Rocket.Chat version: snap rocketchat-server  0.43.0   rev. 88

Hello, how can I do a backup of rocket.chat? I have not found informations on how to do this with a snap installation.

**Comment by marceloschmidt** [comment]
Hello. Easiest way is to backup your `/var/snap/rocketchat-server` directory.

**Comment by d-sko** [comment]
Thank you for the answer, should I stop any services or something before doing this (to prevent files being locked or something like that)?

**Comment by marceloschmidt** [comment]
That's probably a good thing to do.

**Comment by gollum53** [comment]
Hello, could you please add more info on this? Is it sufficient to do snap disable, backup, snap enable ? How can the backuped files be restored on another snap enabled server? Thank you very much.

**Comment by saigop** [comment]
Yes, how to restore the data back to some new machine, if at all the Ubuntu instance got crashed. I have one crashed version of old RocketChat which i installed manually in Ubuntu 14.04, still am not able to retrieve the data.

**Comment by saigop** [comment]
Finally got the LDAP Working.
