### ISSUE TITLE
Add Userlist Sorted  by User level

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4694]
Your Rocket.Chat version: (make sure you are running the latest)
This is first time to use rocket chat and after setup...

**i want admin & owner & moderator in top menu** 
and normal user and bot sort by A-B ...

Becus all levels is random in userlist...how i do that??

ALSO : Top levels  must have special color and font strong and Special icon like this
![2016-10-21_220317](https://cloud.githubusercontent.com/assets/22897987/19610360/757e7bd4-97dc-11e6-8361-8bed4b10e14e.png)

**Comment by marceloschmidt** [comment]
It's not wrong, it was just built this way. You could, instead, request for a change that would allow you to sort the users list on a channel based on their status, role, name, etc.

**Comment by Nemra1** [comment]
thx for replay.. im comming from 123flashchat and always User list sorted by level and i hope to get that her in rocket chat

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
