### ISSUE TITLE
Upload file protection causes problems with the native apps

### ISSUE THREAD

**Issue by cdhowie** [RocketChat/Rocket.Chat#4695]
When using file protection, links to download files don't work well when a native (Windows, OS X, etc.) app is used for Rocket Chat.  The download links open in a browser, which doesn't have a session with Rocket Chat, and the user is presented with a blank page and the download does not start.

It seems like the link should be augmented with some authentication token that can be used to satisfy the protection mechanism when it is opened from a native app.

**Comment by Hudell** [comment]
The apps now download the files directly, so I'll be closing this issue. If any app still has problems downloading protected uploads, please create an issue on the corresponding app repository.
