### ISSUE TITLE
Add Mice and Camera icon in same line (New feature)

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4697]
Your Rocket.Chat version: (make sure you are running the latest)
_New feature_
Add Mice and Camer and sex icon in same line like this
![2016-10-21_213917](https://cloud.githubusercontent.com/assets/22897987/19609420/64d4c432-97d7-11e6-8194-31e2537b2e0e.png)
 1-if user used only camera..show cam only
2- if user used only mice ..show mice only
3-if user used both A/V together..show all
also if he male - add male icon
 if female - add female icon..

add new line in admin role ...admin can shutoff any cam or mice for all users

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
