### ISSUE TITLE
How to install plugins?

### ISSUE THREAD

**Issue by elfeffe** [RocketChat/Rocket.Chat#4698]
I'm running snap version on Ubuntu 16.04
I have seen that plugins must be installed on include/plugins
But I only see include folder, do i have to create plugins folder?
If I try to clone inside include folder, I get a "Read only" error.

**Comment by Nemra1** [comment]
im lost her ..i cant find theme folder

**Comment by geekgonecrazy** [comment]
@elfeffe our integrations are done via the UI.  There is no folder or files required to be managed via the snap.

Going to go ahead and close this.  Please join [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) for help with the ubuntu snap
