### ISSUE TITLE
any manual for edit defualt skin pls

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4702]
Your Rocket.Chat version: (make sure you are running the latest)
i have 15 hrs searching about edit chat skin and icant find any thing...
 Wher is the skin path or css path ..i want edit size and add some lines in css... but ican finde any thing in my server.. any help pls

**Comment by timkinnane** [comment]
See https://rocket.chat/docs/developer-guides/ui-and-theming/themes/

**Comment by Nemra1** [comment]
Thx @timkinnane im look now

**Comment by timkinnane** [comment]
@RocketChat/core - this can be closed I'm pretty sure.
