### ISSUE TITLE
Camera was not found - Mobile App

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4704]
Your Rocket.Chat version: (make sure you are running the latest)
@im using rocket.chat last version and when im starting video call from mobile i see this message
![screenshot_2016-10-22-13-53-42](https://cloud.githubusercontent.com/assets/22897987/19619134/aeb632d8-985f-11e6-8765-7c4b57bf3f6a.png)
MY device : Samsung NOTE 3 N9005

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
