### ISSUE TITLE
No Sound Notifications When User Sent and Recevied Call

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4705]
Your Rocket.Chat version: (make sure you are running the latest)
**No Sound Notifications When User Sent and Recevied Call** 
Must be rocket.chat have ringtone when users make calls ..for all device
i hope To add this in future

**Comment by Loki-Afro** [comment]
any progress here?

**Comment by Nemra1** [comment]
Im figure some way but its working only in pc..not in mobile device

**Comment by Loki-Afro** [comment]
Its neither working in Chrome nor the Electron App (at least on Linux & Windows)

**Comment by Nemra1** [comment]
Tested in Chrome pc...but not yet in electron..but

**Comment by Loki-Afro** [comment]
@Nemra1 do you need more input? How can I help? ;)

**Comment by Nemra1** [comment]
Have u skype or fb whatsapp..!

**Comment by Loki-Afro** [comment]
We are talking about RocketChat and you come up with ... skype fb or whatsapp? 😀 

No I don't. xmpp & mail, like in the 90s this is all I got.

**Comment by Nemra1** [comment]
I mean direct way to tallk ...if u have better IM service. .. share it with me

**Comment by Loki-Afro** [comment]
https://en.wikipedia.org/wiki/XMPP is instant messaging ...

**Comment by Nemra1** [comment]
@Loki-Afro iknow what is xmpp....
this is not help for now ..come her https://my-rocket.rocket.chat/

**Comment by gdelavald** [comment]
The issue has been fixed in the current version.
