### ISSUE TITLE
Ability for user to define personal time format

### ISSUE THREAD

**Issue by LukeFlynn** [RocketChat/Rocket.Chat#4706]
Your Rocket.Chat version: 0.43.0

Loving RocketChat so far, and have been testing it extensively for use in our organization. After using many solutions, both self hosted and commercial.. we have settled on Rocket Chat for it's community driven approach.

In light of that approach, I want to make one fairly important (IMO) feature request:

**Please** allow users to set their own time format, independent of the server setting. Some folks like 24hr time, some folks like AM/PM. It's not a big deal, but something I wish could be done. At the least use the system's time format. 

I don't think I've missed this.. but if so, I do apologize for creating the issue.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
