### ISSUE TITLE
Missing Social Login Buttons on Desktop Browsers

### ISSUE THREAD

**Issue by ptcarino** [RocketChat/Rocket.Chat#4707]
Your Rocket.Chat version: 0.43.0

How do you even login using OAuth? I tried setting up github on Administration > Settings > OAuth but I don't see anything different on the login page?

Same with the demo website. Don't know where I could use OAuth as login.

**Comment by ptcarino** [comment]
Update:

Upon inspecting elements in the login page, it turns out the buttons under "social-login buttons-group" css class are hidden even though they were enabled on Administration > Settings > OAuth. I could login with github using the Developer Console command Meteor.loginWithGithub

I installed my rocket.chat using "snap install rocketchat-server" if that makes any difference.

**Comment by ptcarino** [comment]
Ok, this seems to be a browser issue. I can't see the OAuth buttons on desktop browsers (Firefox 49 and Chrome 54.0.2840.71) but I could see them on the Mobile App and Firefox on Android.

I've only tested the desktop browsers on Ubuntu 16.04. Can't tell if it's the same on Windows.

**Comment by geekgonecrazy** [comment]
Please try newer version of Rocket.Chat It hasn't been reported since, so it seems like it must have been fixed.

If not please re-open
