### ISSUE TITLE
Maintenance Announcement  

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#4710]
Make it possible to make an maintenance announcement on the chat. 

There is no way to announce a schedule maintenance windows.. 

"This rocket.chat server will be down on 2016-10-24 between 20:00-23:00" 
Either on top of the header frame or in the chat frame.

**Comment by marceloschmidt** [comment]
Duplicate of #1048

**Comment by Sing-Li** [comment]
@lunitic   are you thinking of a one-time, dismiss-able, notification.  Once a user dismisses it, he will never see it again?

Or a retained list of maintenance announcement that can be (somehow be) referenced at any time?

**Comment by lunitic** [comment]
@Sing-Li Very quick ms paint jobb of what i mean..

![image](https://cloud.githubusercontent.com/assets/17207375/19687972/f15887ac-9ac7-11e6-9e77-5022004a7f63.png)

**Comment by DalePayman** [comment]
+1 
Is there nothing new on this one? :-(
