### ISSUE TITLE
Safari or Rocket.Chat App on iOS cannot Upload Media

### ISSUE THREAD

**Issue by terwey** [RocketChat/Rocket.Chat#4714]
Your Rocket.Chat version: 0.43.0

When uploading an Image on Mobile the following happens, selecting one works...
![image](https://cloud.githubusercontent.com/assets/1596124/19647720/b5c9a310-99ff-11e6-8f47-7c6fa736f3a8.png)

However, afterwards nothing happens. Oddly enough inside the iOS Simulator it works, but on my iPhone with iOS10 it doesn't work. The App or inside Safari, no error, no progress. Simply nothing happens.

Let me know if I should provide more information.

**Comment by FlowsenAusMonotown** [comment]
In the actual version of the iOS app it is not possible to upload media files. This was working in earlier versions.

**Comment by TheReal1604** [comment]
@terwey Seems thats an issue specific to your deployment. On my 2 rocket.chat setups (1 with HA and 3 nodes and single server setup) all is working fine with the iOS clients and 0.43.0 and 0.44.0-develop. Maybe errors in the webserver logs from reverseproxy?

**Comment by FlowsenAusMonotown** [comment]
I have the rocket.chat iOS app version 2.4.0 and the server version is 0.37.0. In the app there is no possibility to use media files from my phone to post it.

**Comment by TheReal1604** [comment]
@FlowsenAusMonotown Please update to the latest version and try again ;-).

**Comment by terwey** [comment]
@TheReal1604 I checked the logs, nothing in there. It seems to not even connect to it.
The odd thing is, that it works from withing the iOS Simulator. I could upgrade it to the latest version later (requires some fiddling with Xcode I'm afraid) to test if I can reproduce it.

Recap: nothing in the nginx reverse proxy error logs. I can see a request being made to the channel in question but no POST or whatsoever. It seems to die before this.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
