### ISSUE TITLE
Fontello config.json is not checked into git

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#4716]
Hi, 

I would like to add icons to the fontello font.  But to be able to add icons I would need the current config.json. 

Would it be possible to check it in?

**Comment by marceloschmidt** [comment]
Do you mean https://github.com/RocketChat/Rocket.Chat/blob/develop/private/fontello.json?

**Comment by lunitic** [comment]
@marceloschmidt no when you use http://fontello.com/ you will get a config.json which contains all the selected icons.. 

![image](https://cloud.githubusercontent.com/assets/17207375/19686157/47c49714-9ac0-11e6-8b60-5f7d33cb2cdd.png)

If i want to add icons to the current fontello font then I either need to select all icons that is used in RC. (and probably miss some) or I can import the config.json and then add icons and redownload it.

thanks for answering

**Comment by marceloschmidt** [comment]
Please check the file I mentioned. I'm 99% sure that's what you're looking for, but with another name ;)

**Comment by lunitic** [comment]
YES there it is is :)

**Comment by lunitic** [comment]
Yeas it was you answered faster than I manage to delete my comment :-)

**Comment by lunitic** [comment]
And thanks for the fast answer
