### ISSUE TITLE
add slug

### ISSUE THREAD

**Issue by bazarnew** [RocketChat/Rocket.Chat#4717]
Your Rocket.Chat version: (0.44.0)
Hello
Add Slug to shorten the link
In Persian, the URL is too long

**Comment by bazarnew** [comment]
![Uploading 4443.png…]()

**Comment by bazarnew** [comment]
![4443](https://cloud.githubusercontent.com/assets/13213506/19675739/043fc20c-9a9d-11e6-94bf-f9bd9b2b26fc.png)
example

**Comment by bazarnew** [comment]
@MartinSchoeler
@sampaiodiego

**Comment by bazarnew** [comment]
@engelgabriel

**Comment by geekgonecrazy** [comment]
I think we actually do sluggify now.  Going to go ahead and close
