### ISSUE TITLE
Merge as much as possible from Chat-Locker back to our master branch

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#472]
https://github.com/sscpac/chat-locker

**Comment by engelgabriel** [comment]
Maybe @rwakida could start with the permissions features?

**Comment by rwakida** [comment]
@engelgabriel .  chat-locker's permissions are very domain specific.  I think most of RocketChat's end users would need something more generic like the roles / permissions task  you just assigned me #292.   I can tackle this after the roles/permissions task.  As you suggested earlier, I'll move this to it's own package.
