### ISSUE TITLE
[FEATURE] Display personal timezone in-line.

### ISSUE THREAD

**Issue by FerusGrim** [RocketChat/Rocket.Chat#4722]
My feature request is pretty simple. Continue to display the relative timezones as-is but additionally (perhaps as a configuration), display the _sending users_ timezone next to it.

![Current](https://cloud.githubusercontent.com/assets/5481250/19690758/b13dddca-9a9f-11e6-87db-fbb985e755c6.png)
![New](https://cloud.githubusercontent.com/assets/5481250/19690759/b1457170-9a9f-11e6-8179-4c943eac78a7.png)

I apologize for the crappy photoshop, but I'm sure you can live with it. 😛

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
