### ISSUE TITLE
Quoting link broken in direct messages

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#4728]
Your Rocket.Chat version: develop

If I quote a former message in my chat history with lets say: `bob` if I quote the message it'll create a link like: https://demo.rocket.chat/direct/bob?msg={msgid}

but if he clicks that it'll take him to a 404

Not sure how to handle this... Maybe just use a relative link in direct messages?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Cannot reproduce on 0.61.0

Cheers
Thomas
