### ISSUE TITLE
Rocket.Chat update to new version (Example: Rocket.Chat server 0.28.0 update to 0.44.0

### ISSUE THREAD

**Issue by sophornsna** [RocketChat/Rocket.Chat#4734]
Hi developer,

I am very wonder with update Rocket.Chat to new version. I  am using the Rocket.Chat old version by git and I want to update it to new version. I run the **meteor** to startup Rocket.Chat server.  

Thanks,

**Comment by geekgonecrazy** [comment]
@sophornsna are you using the mongo database built into meteor or an external database?

**Comment by sophornsna** [comment]
I am using the mongo database built into meteor.

**Comment by geekgonecrazy** [comment]
Any guide or advice we give will be away from using meteor to run in production.

My advice would be to export your database from the meteor mongo, and install rocket.chat using a recommended method.

To do this first make sure meteor is running.  Then run: `mongodump -h 127.0.0.1 --port 3001 -d meteor`

It'll dump the database in a folder called dump.

Then install mongodb on your system.  Please see the mongo section in one of our guides: https://rocket.chat/docs/installation/manual-installation/ubuntu/

Once Mongo is installed restore the data using: `mongorestore -d meteor dump/meteor` if you want to use a different database, you'd take this as your opportunity to change the database name.  Replacing `-d meteor` with your desired database name.

Then follow the remainder of the guide on setting up Rocket.Chat.

**Comment by sophornsna** [comment]
>> mongodump -h 127.0.0.1 --port 3001 -d meteo

After run this command it create a directory /dump/meteor , but it blank. Any idea?

**Comment by geekgonecrazy** [comment]
if you run: `meteor mongo` does it connect?

**Comment by sophornsna** [comment]
When I run meteor mongo it is connect.

**Comment by geekgonecrazy** [comment]
@sophornsna try it with out the `-d meteor`

Like:

```
mongodump -h 127.0.0.1 --port 3001
```

See what that gives you

**Comment by sophornsna** [comment]
Thank you so much  for your support. Now I can backup database from meteor and I can restore it in my production Rocketchat server. Now I use command **node main.js** instead command meteor to start up rocketchat.

**Comment by geekgonecrazy** [comment]
@sophornsna great!
