### ISSUE TITLE
Deploy Rocket Chat on VPS server?

### ISSUE THREAD

**Issue by fantashi** [RocketChat/Rocket.Chat#474]
How to deploy Rocket.Chat on my VPS server with mongoDB have setup.
I using RoboMongo connect to MongoDB

but i can not authorized

**Comment by Sing-Li** [comment]
Try this (follow the instructions) : [deploy to Linux VPS](https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux)

**Comment by fantashi** [comment]
None, I want to using another mongo database, i dont want using default db: "meteor".

**Comment by Sing-Li** [comment]
Change line # 10 in [this file](https://github.com/RocketChat/Deploy.to.Cloud/blob/master/GenericLinux/docker-compose.yml) -- you can use ANY mongo database you want

**Comment by engelgabriel** [comment]
@fantashi 

Meteor uses the environment variable MONGO_URL, so you can point to any DB.

Format: https://docs.mongodb.org/v3.0/reference/connection-string/

Please reopen the issue if that doesn't help.
