### ISSUE TITLE
Rocket Chat - Invalid URL

### ISSUE THREAD

**Issue by CliffS** [RocketChat/Rocket.Chat#4742]
Rocket.Chat version: 0.44.0
Client Version: 1.3.1

The server is publicly accessible at http://chat.19ft.com/ but the client won't connect to it.

![633fc2](https://cloud.githubusercontent.com/assets/103800/19737549/35454a3a-9bb4-11e6-96e9-7b4f3e22957d.png)

The server certificate is valid.  The setup is that the Rocket-Chat server sits behind nginx.  http://chat.19ft.com/ redirects to the https version.

Any suggestions?

**Comment by Nemra1** [comment]
when u export url in ssh console !
export with https or http?

**Comment by CliffS** [comment]
I'm sorry @Nemra1, I don't understand your question.  Could you explain please?

**Comment by MartinSchoeler** [comment]
@CliffS something is blocking the electron app from accessing the chat, are you using any firewall or reverse proxy?

**Comment by CliffS** [comment]
@MartinSchoeler There is no firewall.  Indeed, at this stage, http://chat.19ft.com:3000 is still exposed (it won't be later, when everything's working).

I am using nginx as a reverse proxy on https://chat.19ft.com/.  http://chat.19ft.com/ is a redirect to the https version.

**Comment by engelgabriel** [comment]
What do you get when you try to open https://chat.19ft.com/api/info ?

**Comment by GeoDirk** [comment]
I've got the exact same issue as this one.  Details here:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/258

**Comment by marceloschmidt** [comment]
I just tried this with https and it works... 

![image](https://cloud.githubusercontent.com/assets/1986378/20526085/aade7456-b0a9-11e6-9531-7074aa0fa056.png)


![image](https://cloud.githubusercontent.com/assets/1986378/20526098/ba27842a-b0a9-11e6-88c4-ad8ea1e322ba.png)

**Comment by akrabat** [comment]
To follow up, we fixed this by turning off HTTP2.

**Comment by GeoDirk** [comment]
As @akrabat said, the solution is to disable http2 in your /etc/nginx/conf.d/rocket.chat.conf:

```
server {
    #listen 443 ssl http2 default_server;
        listen 443 ssl default_server;
    #listen [::]:443 ssl http2 default_server;

```
