### ISSUE TITLE
Error : Updating files..UNDIFINED/UNDIFINED (mobile app)

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4743]
Your Rocket.Chat version: ( the latest)
well...When update setting from dashboard..and Received Notifications to update from Mobile app
 ( android app)
isee this msg
![screenshot_2016-10-26-19-34-00](https://cloud.githubusercontent.com/assets/22897987/19737837/5a5bd1da-9bb5-11e6-8c75-ba8c5010ff63.png)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
