### ISSUE TITLE
New Future | Hiden files link when attached !

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4744]
Your Rocket.Chat version: (make sure you are running the latest)
I hope in next Version to Hiden file link for all attached files to pretect server path from spamer
We Want to Be like this
![2016-10-26_201814](https://cloud.githubusercontent.com/assets/22897987/19739265/9790caa6-9bba-11e6-9f34-c83aab41397c.png)
**User Send file : /path/to/image.jpg**  **to User Send file : auto fetch content without attach id or link**

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue as this feature is not on our short-term roadmap.
