### ISSUE TITLE
LDAP logon error

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#4745]
Your Rocket.Chat version: 0.45-develop

Hello,

When I try to login using LDAP I get this error in the log:

[34mI20161026-15:08:01.364(-4) rocketchat:ldap ldap.js:348 [34mLDAP ➔ Auth.info Authenticating uid=Arnaud,ou=Users,o=5810adae1708992e032c5000,dc=jumpcloud,dc=com 
[34mI20161026-15:08:01.404(-4) rocketchat:ldap ldap.js:352 [34mLDAP ➔ Auth.info Authenticated uid=Arnaud,ou=Users,o=5810adae1708992e032c5000,dc=jumpcloud,dc=com 
[34mI20161026-15:08:01.405(-4) rocketchat:ldap ldap.js:365 [34mLDAP ➔ Connection.info Disconecting 
[34mI20161026-15:08:01.409(-4) rocketchat:ldap loginHandler.js:90 [34mLDAPHandler ➔ info Querying user 
[34mI20161026-15:08:01.411(-4) rocketchat:ldap loginHandler.js:91 [34mLDAPHandler ➔ debug userQuery { 'services.ldap.id': '35303032' } 
[34mI20161026-15:08:01.415(-4) rocketchat:ldap loginHandler.js:101 [34mLDAPHandler ➔ debug userQuery { username: 'arnaud' } 
[34mI20161026-15:08:01.418(-4) rocketchat:ldap loginHandler.js:131 [34mLDAPHandler ➔ info User does not exist, creating arnaud 
[34mI20161026-15:08:01.422(-4) Exception while invoking method 'login' SyntaxError: Unexpected token n     at Object.parse (native)     at packages/rocketchat:ldap/server/sync.js:66:25     at getDataToSyncUserData (packages/rocketchat:ldap/server/sync.js:65:44)     at addLdapUser (packages/rocketchat:ldap/server/sync.js:161:17)     at [object Object].<anonymous> (packages/rocketchat:ldap/server/loginHandler.js:134:9)     at packages/accounts-base/accounts_server.js:471:32     at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:468:18)     at [object Object].methods.login (packages/accounts-base/accounts_server.js:531:27)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)     at packages/ddp-server/livedata_server.js:711:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/ddp-server/livedata_server.js:709:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/ddp-server/livedata_server.js:707:46     at Session.method (packages/ddp-server/livedata_server.js:681:23)     at packages/ddp-server/livedata_server.js:551:43 

Any idea why this doesn't work ?

Regards

Arnaud

**Comment by Lucky21110** [comment]
Any news for this issue ?

Regards

**Comment by Lucky21110** [comment]
Resolved. Bad Mapping

**Comment by pyhtongates** [comment]
Could you provide more details?  I am having the same issue.
