### ISSUE TITLE
0.44.0 changelog

### ISSUE THREAD

**Issue by tupcakes** [RocketChat/Rocket.Chat#4747]
0.44.0

Will there be a changelog for version 0.44.0? one isn't listed in the normal fashion.

https://github.com/RocketChat/Rocket.Chat/releases

**Comment by lucasvanhalst** [comment]
You can always find the changelog here as well https://github.com/RocketChat/Rocket.Chat/blob/develop/HISTORY.md

**Comment by graywolf336** [comment]
@engelgabriel Might want to fix the latest release tag here
