### ISSUE TITLE
Push notification not working: Android

### ISSUE THREAD

**Issue by chiuaua27** [RocketChat/Rocket.Chat#4748]
After reading all the related issues for this problem, i haven't managed to find a working solution.

I run the server on a HP Proliant DL380 under Ubuntu 16.04LTS. (RocketChat installed with SNAPS).
Before that i was running it on the same server under Ubuntu 14.04LTS (RocketChat installed manually).

I made the build using latest version of cordova and then generated the APK directly from Android Studio as a Gradle project.

I can connect to the server, send messages, between clients, make video and audio calls, but i DON'T get vibration, sound and notifications when i receive a message or call.

NOTE: All the permissions ar enabled for camera, call. phone, message, notifications, etc..

I already disabled the http://gateway.rocket.chat gateway and added credentials for GCM (project number and api key from google console).

If i go (from the android client) to: My account > prefferences and i press "TEST DESKTOP NOTIFICATIONS", the phone receives a notification in the notification bar. Other than this, it doesn't work.

I tested the application on Android 6.0.1 and Android 5.1
None of them receives notifications.

Any ideas?

**Comment by Nemra1** [comment]
all clients it same thing..( web- android - iphone - desktop ) all i think will fix in next version or make some patch

**Comment by chiuaua27** [comment]
So, this happens to all of you?

**Comment by Nemra1** [comment]
@chiuaua27 yes my Dear and i have this issu too

**Comment by reetp** [comment]
Android 6 using standard gateway for notificatons. Rocket behind reverse proxy.

Mobile app:
Notification vibration works
Sound notification does not

Lots of issues with video and sound as well which basically just don't work.

Video and sound are fine on the built in Android Chome Browser, ironically.

Be nice to get the mobile app fixed to at least get sound notifications working.

**Comment by dmc1961** [comment]
No sounds at all using the Android client. Also not on Fedora 23 and 24 desktops. (Nor in Chrome Web browser).
Was thinking I must be missing something but can see I am not alone.
Beautiful software solution but no sounds will be a deal breaker.
I am using KDE Plasma desktop in Fedora. I did get the sound to make a noise once but not upon subsequent comments, so assuming this is the new conversation or 'joining' chat notification.... which only works once in a blue moon.

**Comment by mohamedhagag** [comment]
anyway to get sound notifications on android? we get vibration only.

**Comment by kkumaresan** [comment]
Hi, we at Mongrov have developed a react-native mobile client library for Rocket.Chat. Please check this url: https://github.com/mongrov/roverz . Works both on iOS and Android.  If you get a chance, do check this project for a comprehensive native mobile app using Rocket.Chat. We welcome your feedback 😄

**Comment by Hudell** [comment]
We've recently refactored the notification system so this old issue is no longer relevant. If you run into any problems with notifications you can open a new issue.
