### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by katopz** [RocketChat/Rocket.Chat#475]
When I try to run with current master via localhost Mac.
```sh
$ sudo meteor
```
I got
```sh
=> Errors prevented startup:                  
   
   While building the application:
   node_modules/loglevel/test/manual-test.html:1: bad formatting in HTML template
   node_modules/loglevel/test/test-qunit.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   
=> Your application has errors. Waiting for file change.
```

Any hint?

**Comment by sampaiodiego** [comment]
is it a fresh clone?
what is the output for `meteor list`?
have you tried without `sudo`?

**Comment by katopz** [comment]
Weird enough. It's working fine via my home Mac (10.10.5) but not my office's Mac (10.10.4).
I'll try clean setup again tomorrow at office and report back if I can reproduce this. (I hope not)

Thanks for assist. @sampaiodiego

**Comment by sampaiodiego** [comment]
ok @katopz 

I'll close the issue for now. Feel free to open it again if you still got trouble.
