### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Hostile** [RocketChat/Rocket.Chat#4751]
Your Rocket.Chat version: 0.44.0

Hi, how to make Google Analytics works? Should I put google code somewhere? 

What is it   Admin/Meta/Google veryfication

and Admin/Meta/Facebook APP ID ?

How to make it google anaystic show results in google panel ?

Thanks

**Comment by net-activities** [comment]
You need to use Google Tag Manager to get your Google Analytics into rocket.chat. ;-)

**Comment by Hostile** [comment]
Not same is it
