### ISSUE TITLE
Livechat agent "auto-away" setting

### ISSUE THREAD

**Issue by paulhibbitts** [RocketChat/Rocket.Chat#4759]
I am using Livechat for virtual office hours with my students, and one more than one occasion I forget to turn off Livechat when away from my Mac, which results in students getting frustrated that I am not replying to them.

It would be great to have an agent "auto-away" setting, where if my local computer status goes to away/sleep Livechat automatically turns off. Ideally, having it automatically go back on upon wake-up would be also expected.

Thanks very much for considering this request.

**Comment by reetp** [comment]
+1 for this
Still the same in 0.52

**Comment by sampaiodiego** [comment]
we have an auto-away feature that should affect agents availability, we'll make sure that's true =)

**Comment by reetp** [comment]
What is happening with the MR https://github.com/RocketChat/Rocket.Chat/pull/12540 ?
