### ISSUE TITLE
Emoji broken after upgrade from 0.24 - 0.44

### ISSUE THREAD

**Issue by joesecurity** [RocketChat/Rocket.Chat#4768]
I upgraded Rocket.Chat as outlined in the upgrade guide. Everything worked well, except the Emoji are wrong:

![untitled](https://cloud.githubusercontent.com/assets/10660177/19801844/2b5879cc-9d01-11e6-85ab-3864bf952461.png)

How can I get the correct Emojis?

**Comment by joesecurity** [comment]
We are using the Windows Desktop client. In the web browser the problem does not exist!

**Comment by ramden** [comment]
Mac client also. Website works

**Comment by jdoose** [comment]
I am using windows client, everything's correct: Windows 10 (10.0.14393)
Maybe it is something with the windows version?
In Microsoft Windows [Version 6.1.7601] it is not working.

**Comment by CodeKittey** [comment]
I am using Linux Cient on linux x64 4.7.0-coreos-r1
And Client Version: Version 1.3.1
and it's not working.

**Comment by MartinSchoeler** [comment]
@joesecurity what client version are you using?

**Comment by joesecurity** [comment]
1.3.1 on Windows 7 x64

**Comment by graywolf336** [comment]
This is a cache issue, I had this happen to me. Try to remove the server from your desktop client and see if that fixes it

**Comment by joesecurity** [comment]
Thank you, that did it!

**Comment by graywolf336** [comment]
Glad to hear, thanks for following up. 👍

**Comment by jdoose** [comment]
I was told it is sufficient to "Reload the server" from the context menu when right clicking on the server entry.
