### ISSUE TITLE
readonly and post-readonly permission not working properly

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#4769]
Your Rocket.Chat version: 0.45.0-develop

The `post-readonly` permission is not checked when the user tries to send a message, but only when the room is set to readonly.

re: https://github.com/RocketChat/Rocket.Chat/pull/4034#issuecomment-256892300

**Comment by infinitnet** [comment]
@marceloschmidt (in reply to https://github.com/RocketChat/Rocket.Chat/pull/4034#issuecomment-256892300): Thanks for looking into this so quickly. After removing `post-readonly` from `admin` group I actually did try setting read-only to false and then true again, but that didn't do the trick either. I just did it again just to be sure and admins still aren't being muted.

**Comment by timkinnane** [comment]
I remember discussing this with the original contributor. I think it was by design to reduce overhead by not checking the permission on every post. Probably just needs a few lines shifted, I'll look into a fix.

**Comment by cyclops24** [comment]
Part of #8494

**Comment by engelgabriel** [comment]
https://github.com/assistify/Rocket.Chat/issues/70

**Comment by engelgabriel** [comment]
Duplicates: 
https://github.com/RocketChat/Rocket.Chat/issues/8388
https://github.com/RocketChat/Rocket.Chat/issues/7356
https://github.com/RocketChat/Rocket.Chat/issues/6302

**Comment by mnlbox** [comment]
Any news guys?

**Comment by Hudell** [comment]
The #11311 PR is handling this issue. It still needs some tweaks, but I'll try to have it ready for the next release.
