### ISSUE TITLE
Disabled incoming webhooks should be logged

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#4773]
Your Rocket.Chat version: 0.43.0

Please add a log message that clearly warns when a disabled incoming webhook is called. I've just wasted about 4 hours trying to get a webhook to work just to notice afterwards that I forgot to turn it on...

**Comment by knrt10** [comment]
@ulope this is fixed in latest in latest version `1.0.0-develop`. Now you get the message `Service Unavailable`. Please check, and if fixed feel free to close this issue.

**Comment by sampaiodiego** [comment]
thanks @knrt10 .. that's right.. if you hit a disabled webhook endpoint on latest Rocket.Chat version you'll receive a `503 Service Unavailable`
