### ISSUE TITLE
Allow integration scripts to resolve asynchronously

### ISSUE THREAD

**Issue by cdhowie** [RocketChat/Rocket.Chat#4775]
Your Rocket.Chat version: 0.44.0

It would be nice if integration script hooks could resolve asynchronously, either by accepting a callback parameter or returning a promise.  We have some cases where we would like to call out to a third-party API to fetch some information about an object mentioned in chat.

Right now we have two integrations: one to send the message to a specialized node server we've written, and one to receive messages from that server.  It would be nice if we could just put the code inline in a single integration, but right now script hooks must resolve synchronously, making this impossible.

**Comment by Sing-Li** [comment]
Please see our documentation for Rocket.Chat Apps.   It will handle the exact case you need.
