### ISSUE TITLE
With new combined list flex, create new footer button code should include create-p premission

### ISSUE THREAD

**Issue by danielbressan** [RocketChat/Rocket.Chat#4777]
I don't think this has been found/updated yet from the lastest code on develop I could see. 

The footer button "Create New", from the "More Channels...." select right now does only a select hasAtLeastOnePermission on create-c, but the button shows for create-c/create-p

Thus:

```
    'click footer .create': ->
        if RocketChat.authz.hasAtLeastOnePermission('create-c')
            SideNav.setFlex "createCombinedFlex"
```

Should be:

```
    'click footer .create': ->
        if RocketChat.authz.hasAtLeastOnePermission [ 'create-c', 'create-p']
            SideNav.setFlex "createCombinedFlex"
```

**Comment by MartinSchoeler** [comment]
@danielbressan Yes you are right, you want to do the pull request or want us to do it?

**Comment by danielbressan** [comment]
@MartinSchoeler I don't have a clean checkout right now. If it's easy for you, feel free, otherwise I can do it a little later in the week. Thanks!
