### ISSUE TITLE
Couldn't create an account on mobile via Facebook login

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#478]
Could login with facebook only after FB-logined in web version.
Before that facebook returned me to an app with empty loginscreen without any error message.

via: Илья Туменко

**Comment by engelgabriel** [comment]
iOS or Android?

**Comment by rodrigok** [comment]
@engelgabriel android, but I didn't tried in iOS too

**Comment by rodrigok** [comment]
Can't reproduce
