### ISSUE TITLE
Write EPIPE Error in future.js 

### ISSUE THREAD

**Issue by danishsoomro** [RocketChat/Rocket.Chat#4784]
Website was working smooth, I updated the docker-compose file with a new BOT user Id and restarted the server. The website went down .. https://digitalnomad.chat. BOT container logs are fine - RockatChat container logs come up with an error [SCREENSHOT IS ATTACHED]. P.S Docker-compose had rocketchat:latest, I changed it to v0.43.0 - problem persist. right now its 0.44.0

![log](https://cloud.githubusercontent.com/assets/2918180/19833961/a7f5249a-9e09-11e6-8dce-8297fb0a7400.PNG)
Your Rocket.Chat version: (make sure you are running the latest)

**Comment by danishsoomro** [comment]
nginx rocket chat ERROR LOG below

![log1](https://cloud.githubusercontent.com/assets/2918180/19834155/0892e344-9e11-11e6-9e2e-c141c4be2ab9.PNG)

**Comment by anilCSE** [comment]
Facing same issue. Its running initially, but after few operations like login, admin, check users list or import from slack, its throwing the error.

**Comment by geekgonecrazy** [comment]
Please try on a newer version of Rocket.Chat and if still persists hop on our community server or one of our other support methods https://rocket.chat/docs/getting-support
