### ISSUE TITLE
[Help]Cannot startup the service, it's always pending on 'Building package rocketchat:theme'

### ISSUE THREAD

**Issue by yuanhongb** [RocketChat/Rocket.Chat#4786]
I clone the project and try to startup the service by the source code. But it always blocks on 'Building package rocketchat:theme'. Here's the screenshot:
![image](https://cloud.githubusercontent.com/assets/9713291/19837727/bf9a5da8-9efa-11e6-83a7-47bc96b04556.png)

Could anyone make me out ??

Rocket.Chat version: 0.44.0

**Comment by mcmdhr** [comment]
+1

**Comment by MartinSchoeler** [comment]
@yuanhongb @mcmdhr Is this issue still happening in the latest version?

**Comment by yuanhongb** [comment]
@MartinSchoeler No, it works well now! Thank you~
