### ISSUE TITLE
cannot connect to rocket chat in browser after upgrade to latest version

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#4788]
i was running (i think) version 0.33 of rocket chat and just upgraded it to the latest version (0.44.0). i am now unable to connect to rocket chat via my browser. i see in the rocket chat log for nginx, that there is an 'upstream timeout', but that's the only info in there.
i did have a problem when upgrading to node 4.7 in fedora 23, as i had to do that from node's own repo and when i upgraded npm i got a bunch of conflict messages. i haven't yet fixed that, but as i had already run the install process i thought i might be able to get away with it as it is.

so i now have a few options - install rocket chat 0.43.0 instead... and get npm working (not sure how to).

any thoughts and tips are welcome here.

**Comment by propertunist** [comment]
so i have now apparently got npm and dependencies installed and ran the install for rocketchat via npm. however, i still cannot connect to rocketchat via my web browser.
the output in the terminal from running rocketchat is:
```
Updating process.env.MAIL_URL
ufs: permissions are not defined for store "fileSystem"
{"line":"114","file":"migrations.js","message":"Migrations: Not migrating, already at version 63","time":{"$date":1477859270170},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom emoji storage
ufs: permissions are not defined for store "rocketchat_uploads"
Using FileSystem for Avatar storage
��� System ��� startup
��� +-----------------------------------------+
��� |              SERVER RUNNING             |
��� +-----------------------------------------+
��� |                                         |
��� |       Version: 0.44.0                   |
��� |  Process Port: 3000                     |
��� |      Site URL: https://mydomain/  |
��� |         OpLog: Disabled                 |
��� |                                         |
��� +-----------------------------------------+
```

**Comment by propertunist** [comment]
i am also unable to connect to the server via the standalone rocket chat app in fedora. i just see a white screen.

**Comment by propertunist** [comment]
i just tried going back to 0.43.0 and that made no change

**Comment by lucasvanhalst** [comment]
You might want to enable oplog, that will speed it up by a huge amount.

**Comment by propertunist** [comment]
@lucasvanhalst - thanks for the tip, however, i have not seen that option mentioned anywhere previously. how do i enable oplog and what is it?

**Comment by propertunist** [comment]
so i see that oplog is a facet of mongodb - is this page along the right lines? https://themeteorchef.com/snippets/setting-up-mongodb-oplog-tailing/

**Comment by propertunist** [comment]
form what i have understood, oplog refers to the duplicating of information among numerous databases. is the purpose of using it with rocket chat to duplicate data between rocket chat's own store and mongodb?

**Comment by propertunist** [comment]
after a few days of working with this issue, i fixed a couple of minor configuration issues, but the chat server still was not reachable via a browser. today i came back to it and without explanation i could connect to rocket chat correctly. i don't know what the problem was or what solved it, but at least now it is working - so i will close this for now.
