### ISSUE TITLE
Error: EBADF: bad file descriptor

### ISSUE THREAD

**Issue by Naoki2015** [RocketChat/Rocket.Chat#4790]
When I bulild and run Rocket.chat , I get an Error:
```
Started MongoDB.

rocketchat:cas: updating npm dependencies -- cas...
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
throw error;
^

Error: ENFILE: file table overflow, open '/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-authorization/server/publications/usersInRole.coffee'
at Error (native)
=> awaited here:
at Promise.await (/Users/yiwei/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:39:12)
at wrapper (/tools/fs/files.js:1522:32)
at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
.........
```
Why will appear the problem: “command not found” and "No such file or directoryges/rocketchat-livechat/app" ? actually, the directoryges of "/rocketchat-livechat/app" is existed .

Rocket.chat is 0.44.0, meteor is 1.4.2, node is v6.2.0, npm is 3.8.9
How can I fix it?

**Comment by Naoki2015** [comment]
if i create a  new meteor demo, the demo can normal  build and run . so i think that my meteor environment is OK， i have try some methord to  solution , but failed.

**Comment by hugetiny** [comment]
I got the same problem~

**Comment by ESGC6E** [comment]
Same problem here too. Any updates on fixing this?

**Comment by hugetiny** [comment]
try to reinstall the meteor 1.4.2 in global envirment,it works

**Comment by vimes1984** [comment]
I've tried to reinstall from meteor again: ```curl https://install.meteor.com/ | sh```
and it still fails :D

**Comment by Naoki2015** [comment]
me too, still fails...

**Comment by wandonye** [comment]
same here

**Comment by wandonye** [comment]
In my case, I tried `meteor` and `meteor run`, didn't work. Then I tried to reinstall meteor and `meteor`, same error, then I tried `meteor run` and it suddenly worked. 

Some other resource reported that deleting the repo and downloading it again under good network connection fixed the problem.

Still a myst for me

**Comment by marceloschmidt** [comment]
Not sure why it's happening, but just for reference: https://github.com/meteor/meteor/issues/4201 here's a meteor issue regarding it.

**Comment by Naoki2015** [comment]
`=> Started MongoDB.                           
rocketchat:cas: updating npm dependencies -- cas...
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: command not found
/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-livechat/plugin/: No such file or directoryges/rocketchat-livechat/app
/Users/yiwei/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, open '/Users/yiwei/MeteorProject/Demo/Rocket.Chat/packages/rocketchat-authorization/server/publications/usersInRole.coffee'
    at Error (native)
 => awaited here:
    at Promise.await (/Users/yiwei/.meteor/packages/meteor-tool/.1.4.2.zi1w5b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:39:12)
    at wrapper (/tools/fs/files.js:1522:32)
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
`

Why will appear this problem:  “command not found”  and  "No such file or directoryges/rocketchat-livechat/app" .   actually, the  directoryges of "/rocketchat-livechat/app" is existed .

**Comment by CharlesOy** [comment]
Same here, any solution now?

**Comment by engelgabriel** [comment]
Meteor 1.4.2 needs node v4.7.0, anything about it is not recommended (yet).

**Comment by CharlesOy** [comment]
It worked after I stopped all my else Meteor instances and reinstalled Meteor.

**Comment by drallgood** [comment]
If anyone encounters this, here's what fixed it for me:
https://gist.github.com/abernix/a7619b07b687bb97ab573b0dc30928a0

**Comment by saifur-rehman** [comment]
I have tried every thing but my error is little bit different what is this for 

native: ENOENT: no such file or directory, scandir 'packages/rocketchat-katex/node_modules/katex/dist/fonts/'

**Comment by saifur-rehman** [comment]
I Follow These Steps and Solve my Problem.

https://groups.google.com/forum/#!topic/jenkinsci-users/Idcjf4ZQxT4
