### ISSUE TITLE
Feature Request : Transcript for Livechat Agents

### ISSUE THREAD

**Issue by CONFORM-IT** [RocketChat/Rocket.Chat#4791]
Our Rocket.Chat version: 0.43

This is a follow-up to Livechat Transcript #4522  - it would be great if the livechat agent could receive the transcript of a completed livechat as well, not just the visitor. Preferably this would automatically be sent to a standardized address that the admin can configure, or to the mail address of the agent that closed the livechat session.

**Comment by MartinSchoeler** [comment]
Duplicate of #4684
