### ISSUE TITLE
Skype Bridge - 2-way. This can be a handy feature!

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#4797]
I often do business talk via Skype with my clients. We use RC on https://chat.vanila.io and have 1200 registered users (mostly developers, designers) and around 200k messages.

I had idea for some time to merge all emails, social chats, skype into one place. 

Anyway, idea came recently to create **skype bridge** for 2 way messaging. I googled little bit and found Skype Web SDK https://msdn.microsoft.com/en-us/skype/websdk/startconversation. 

As we use RC for collaboration, project managing and team communication, I got need to be able to chat with a clients (who are using skype) in our RC instance both private/public channels or direct messages.

This will give us chat all in one place, instead to go over few different platforms.

I think this can be really handful feature and who know what features can result from this.

I mention this to @engelgabriel and he said to create feature over here.

Let me know what you think guys.

**Comment by ajw-dev** [comment]
This is a functionality we could really use as well. It would be really useful if we could synchronize certain Skype conversations with Rocket Chat private groups. Does it look like that is something that might happen?

**Comment by jelenajjo** [comment]
It's a truly exciting feature.

**Comment by Merryfurr** [comment]
Its very possible to do this with a skype and Rocket.Chat bot.
The bot on the rocket.chat instance would generate a random key that you can send to the Skype bot. After that the bots would listen and send messages to the other platform.
I'll make a better explanation later today when I get back home

**Comment by mikeboltonca** [comment]
Any action on this? I'd love to merge Skype and Rocket.Chat at my company.

**Comment by jelenajjo** [comment]
I think there is no action yet @mikeboltonca  .

Ping me on jelena@vanila.io if you would like this to develop. Me and my team can develop this features for you.

**Comment by koyan** [comment]
I am interested in a smaller integration: We use RocketChat for all the text messages, but because of video/audio quality of skype (especially if there are bandwidth and connectivity issues) being superior to anything else at the moment we revert to skype for meetings. This means having to synchronise the partitipants from a RC room to a skype group. 
So, the wished functionality would be twofold:
a) ability to define skypeID for each RC user
b) Ability to one-click create-skype-group-and-call-them

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App or external integration. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
