### ISSUE TITLE
Setting ADMIN_PASS shows password in log

### ISSUE THREAD

**Issue by asthomasdk** [RocketChat/Rocket.Chat#4806]
Your Rocket.Chat version: 0.43.0, 0.45.0

When a rocket instance starts up - if the ADMIN_PASS environment variable is set - this password is displayed in the log. it is ok to display that the password is being set - but to actually write it to the log is not a good idea. 

Although this password can easily be changed, it could be a security problem. 

I would suggest just logging that the admin user password is being set - without showing what it is.

**Comment by andypost** [comment]
Looks a duplicate of #3069
