### ISSUE TITLE
rocketchat 0.45 direct audio call not working

### ISSUE THREAD

**Issue by jmls** [RocketChat/Rocket.Chat#4808]
after upgrading to 0.45 from 0.44, direct audio calls are no longer working. There is no notification of an inbound call , so you can never pick it up

We tried on 0.43 and 0.44, and it worked perfectly there.

**Comment by jmls** [comment]
this leaves us with a broken system, as we can't move back to 0.44 (https://github.com/RocketChat/Rocket.Chat/issues/4809)

**Comment by asthomasdk** [comment]
Is anyone else seeing problems with not being able to make calls in 0.45.0? This basically makes the audio features unusable at the moment.

**Comment by andi242** [comment]
same here.

The call indicator is not shown at the target users session.
My turn server does not show any connections. This worked well in previous versions (apart from group calls). 

Appears to be broken at this time.

**Comment by andi242** [comment]
@jmls did you have the chance to test the development branch? is this still an issue?

**Comment by asthomasdk** [comment]
@andi242 we have not tested it with a local development branch yet. 

We will try and find some time for this in the next couple of days - but hope someone else who has worked on the audio stuff already can take a look and find out what has broken it ;-)

**Comment by andi242** [comment]
@asthomasdk I've got a bit of a concern, that no one else but us reported this problem.

I'm running RC on Ubuntu 16.04 LTS with latest security patches behind an apache2 proxy.
Installed from source, no snap-based installation.

**Comment by Nemra1** [comment]
same here v45

**Comment by tlebris** [comment]
I confirm, WebRTC not working at all in 0.45

**Comment by gcommit** [comment]
seems to be the same issue in the latest version again
