### ISSUE TITLE
Windows 2008 installation error

### ISSUE THREAD

**Issue by rbjoernd** [RocketChat/Rocket.Chat#4810]
Your Rocket.Chat version: 0.34.0
Hi all! Trying to get Rocket chat running on my Windows 2k8 srvr. following this guide:
https://rocket.chat/docs/installation/manual-installation/windows-server/

Everything works fine untill I get to the step where I am doing the npm install. Then I'm getting this error: 
![rocketerr](https://cloud.githubusercontent.com/assets/23192215/19891903/8030ba7e-a042-11e6-9486-46bc6a34ff3e.jpg)

Anyone have any knowledge about the error?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
