### ISSUE TITLE
Server freeze at Updating process.env.MAIL_URL after including rocketchat:livechat

### ISSUE THREAD

**Issue by ziedmahdi** [RocketChat/Rocket.Chat#4811]
Your Rocket.Chat version: 0.46.0-develop

Hello,
I want to integrate a chat feature in one of my own project. So i started by exploring the rocket chat app and including some of rocket chat packages in my app.

When I add `rocketchat:livechat` to my app, the server doesn't start any more. It freeze at `Updating process.env.MAIL_URL`

![image](https://cloud.githubusercontent.com/assets/5032634/19892480/5a2444ba-a045-11e6-9f47-c32a10e6ec87.png)

Without the `rocketchat:livechat` it's working. Does any one have a clue on this or faced similar problem?

I created a repo for problem reproduction, here is [the link](https://github.com/ziedmahdi/rocketchat-integration-problem).

Thank you very much for your help.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
