### ISSUE TITLE
Channel indexed in search engines (google)

### ISSUE THREAD

**Issue by bazarnew** [RocketChat/Rocket.Chat#4814]
Your Rocket.Chat version: (make sure you are running the latest)

The proposal for channels
Channel indexed in google and ... !
This option is for social networking
![443334](https://cloud.githubusercontent.com/assets/13213506/19899642/23a22db8-a076-11e6-98aa-6c26b8271e00.png)

**Comment by bazarnew** [comment]
@MartinSchoeler

**Comment by bazarnew** [comment]
@engelgabriel

**Comment by geekgonecrazy** [comment]
I think this feature request is a bit too broad and not detailed enough for anyone to really work on.  

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/6095
