### ISSUE TITLE
Feature : add font option to input chat box

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4816]
Your Rocket.Chat version: (latest)
 i hope from rocket chat team to add font option to input box like this
![2016-11-01_221419](https://cloud.githubusercontent.com/assets/22897987/19906004/c8a4336e-a081-11e6-8ea7-19ea58c6061e.png)
input box missed important future from font side like
text color - text font - bold text button (not *text* ) italic button not (_text_) and finaly .. 
**button to choose text color**

**Comment by fazilou** [comment]
thats great feature

**Comment by GalGreenfield** [comment]
Was something done eventually about this?

**Comment by jszaszvari** [comment]
I sure hope not

Letting users change the font will just result in a screen full of size 72 times new roman or comic sans. 

The whole design and feel would break and it would look tremendously unclean. 

You can already apply formatting with markdown and the buttons at the bottom which is more than sufficient 

![2018-01-01_14-07-28](https://user-images.githubusercontent.com/872463/34465369-5dc33664-eefd-11e7-83a7-0edab8b9b4bc.gif)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I agree with @JSzaszvari here, that's why I'm closing this. If you still feel this is important to you, please elaborate extensively, what's the value of this for the general audience.

Cheers
Thomas
