### ISSUE TITLE
theme.css route returns HTML during first few seconds of server startup

### ISSUE THREAD

**Issue by kentonv** [RocketChat/Rocket.Chat#4818]
Your Rocket.Chat version: 0.45.0 (sandstorm)

Early in the server's startup process, the `theme.css` route does not appear to be registered yet, and instead returns the standard Meteor initial HTML content that any other route returns.

On Sandstorm, this is very visible: When creating a new grain or opening a grain that wasn't running (thus forcing it to start up), the user is presented with mostly-unstyled content (see screenshot). Upon refresh, the problem goes away, since `theme.css` now responds with a proper stylesheet.

I believe this problem has been around for a while, but it appears to have gotten worse in 0.45.0: It now consistently happens every time, whereas in the past the problem only happened occasionally.

![screenshot from 2016-11-01 14-01-16](https://cloud.githubusercontent.com/assets/4001805/19907412/f6760722-a03b-11e6-9238-c295064e1d94.png)

**Comment by kentonv** [comment]
It turns out this problem is affecting the current published version of Rocket.Chat as well. I'm not sure why it didn't happen in my testing but users are complaining about it. This is a very poor first-time experience for users. I think we need to get this fixed ASAP.

@paulproteus is available to assist.

Complicating matters, the 0.45.0 version of Rocket.Chat hasn't been approved yet because it seems that an extremely deep path name is hitting a limit in the current Sandstorm release. The deep path is caused by a long npm dependency chain that appears to be pulling in dev dependencies, which seems wrong. We can increase the limit in the next release (this weekend), but it also appears that dev dependencies were not supposed to be included in the build.

So presumably we need to fix that problem as well -- or wait for a Sandstorm release -- before we can ship a package to users.

@engelgabriel @Sing-Li

**Comment by engelgabriel** [comment]
Sorry for the delay @kentonv I was traveling for a few conferences last 2 weeks. I'll push the fix today.
