### ISSUE TITLE
i cant sign up with arabic username ..help pls

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4820]
Your Rocket.Chat version: (make sure you are running the latest)
My problem her.. when i trying signup with arabic utf username .. Get this error

عربي is not  a valid Username
![2016-11-02_030327](https://cloud.githubusercontent.com/assets/22897987/19913206/1654e7b2-a0a9-11e6-9af9-64f8677cd678.png)
i need to fix that becuz all my member from ( dubai ,UAE,EGYPT,KUWITE )

**Comment by alexandrezia** [comment]
Try to disable  "UTF8 Names Slugify"  in Administration -> General -> UTF8 (at the bottom of the page)

**Comment by Nemra1** [comment]
Thanks ..but not workin and icant find any option for enable UTF8 names

**Comment by MartinSchoeler** [comment]
![screenshot from 2016-11-03 09-56-40](https://cloud.githubusercontent.com/assets/20868078/19965009/1e53367c-a1ac-11e6-8018-7599abb32635.png)

(You have to be a admin to access this screen)

**Comment by Nemra1** [comment]
Already  do that & iknow about that but ithink ineed some code to enable utf in signup

**Comment by fduraibi** [comment]
You need to add the Arabic letters range to the allowed unicode field under `UTF8 Names Validation` 

change it to:
```
[\u0600-\u06FF0-9a-zA-Z-_.]+
```

and keep names Slugify disabled.

**Comment by MartinSchoeler** [comment]
Closing this for @fduraibi solution. If that doesn't solve the issue, please reopen this.
