### ISSUE TITLE
About dialog in Windows client has menu

### ISSUE THREAD

**Issue by rillig-nm** [RocketChat/Rocket.Chat#4823]
Your Rocket.Chat version: 1.3.1

When opening the About dialog in the Windows client, it shows a full menu bar. From there it is possible to open another About dialog, and so on.

The about dialog should not have a menu bar at all.

**Comment by MartinSchoeler** [comment]
hey @rillig-nm  could you post a screen shot of the problem?

**Comment by rillig-nm** [comment]
![2016-11-03 15_54_03-einstellungen](https://cloud.githubusercontent.com/assets/8994464/19970915/cb2fcc62-a1dd-11e6-9941-d01721bf4d81.png)

**Comment by MartinSchoeler** [comment]
Please reopen this issue here https://github.com/RocketChat/Rocket.Chat.Electron . Thanks!

**Comment by rillig-nm** [comment]
It is fixed in Rocket.Chat.Electron 2.8.0. Thanks.
