### ISSUE TITLE
0.45.0 - hubot packages as default

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat#4826]
We have Rocket Chat 0.45.0 version and there are feature "Add hubot packages as default". Is there any specific configuration needed? So... how i understand, hubot is rocket.chat user right? But it looks like it not working. I added hello.coffee but when i write "Hello!" nothing happens. 
Feature Internal Hubot is True. Username set to Rocket.Chat

**Comment by andi242** [comment]
I believe it's rocket.cat (that animal everyone is so excited about. ;-) )

**Comment by reetp** [comment]
Is this linked to the file not found #4807 ?

**Comment by LXSysadmin** [comment]
No, i don't see any error messages. Everything and all settings are saved fine. Is there any way to see logs or test hubot except writing in chat window? I use docker image.

**Comment by geekgonecrazy** [comment]
We revamped this please try in our latest release. If still having issues feel free to re-open
