### ISSUE TITLE
JQuery Button does not shown on iPad and Samsung tablet

### ISSUE THREAD

**Issue by Buzzele** [RocketChat/Rocket.Chat#4828]
Your Rocket.Chat version: 0.43

Hi,

I want to set a css-box in top of the room. Therefore I have inserted the code in packages/rocketchat-ui/views/app/room.html: 

`<template name="room">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	 <script type="text/javascript">
	 $(document).ready(function () {
			$("button").click(function(){
			   $("#cssBox").toggle();
		        });
        });
        </script>`

This should show a button to show/hide the css box which I have put also in room.html.

On pc, android, iPhone and a huawei tablet it works perfectly. On ipad, ipad Mini and a Samsung tablet the button is not shown.

Has anyone an idea please?

Regards Benny

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
