### ISSUE TITLE
"<br>" in attachment of incoming WebHook

### ISSUE THREAD

**Issue by Franziskus1988** [RocketChat/Rocket.Chat#4830]
Your Rocket.Chat version: 0.45.0

I have an incoming WebHook which contains `<br>` tags in the value property of fields of attachments. Unfortunately it doesn't break lines.

Example:

`"value":"Agent: Build-03<br>Elapsed: 3m:16s"`  

![image](https://cloud.githubusercontent.com/assets/5774027/19929684/d93f0b44-a104-11e6-8572-cc4eeb68f764.png)

**Comment by geekgonecrazy** [comment]
I use `<br>` in webhooks all the time.  Try in text field, also make sure to give this a shot in a newer version of Rocket.Chat.  Its possible we solved the issue you were having.
