### ISSUE TITLE
Avatar, username and date didn't render in main chat window when sending a message to a room

### ISSUE THREAD

**Issue by ronaldosaheki** [RocketChat/Rocket.Chat#4831]
Your Rocket.Chat version: 0.43

I've sent a message and it was rendered on my screen looking like it was sent by the user who sent the previous message, because it didn't render the avatar, name or date. 

Hitting F5 fixed the rendering, showing my avatar, name and message datetime before my messages.

Server details: Single process, single mongo installation, reverse proxy with apache.
Browser details: Chrome windows Versão 54.0.2840.59

**Comment by lunitic** [comment]
Related to #4100 #4610 , seems like more and more start to see this issue.

**Comment by rodrigok** [comment]
Hi @ronaldosaheki, thanks by this report.

Do you have the steps to reproduce? Or can you send us a video/gif or, at least, a screen shoot of your problem?

If your message is not rendering the username too, the problem should not be related with issue #4100

**Comment by rodrigok** [comment]
@ronaldosaheki I will close this issue in favor of #4100 , please reopen it if you can provide more information as I asked you before.

Thanks
