### ISSUE TITLE
[Feature] Mute all guest user on all Room same if the room is not read-only

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#4833]
Your Rocket.Chat version: develop

Hello,

I would like to be able to mute all guest user from all room same if the room is not read only.
How I can do this ?

Regards

**Comment by Nemra1** [comment]
nice idea

**Comment by Lucky21110** [comment]
Maybe a new permissions like Always_mute and if this permissions is checked, all users in the group will be muted in all channel

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
