### ISSUE TITLE
[Help] Configure Filters for Oauth

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#4834]
Your Rocket.Chat version: Develop

Hello,

I'm using WordPress Oauth with WP-Oauth plugin.
How I can set the filters in Rocket Chat ?
Normally you need to do this change on your functions.php file inside your theme in WordPress.

Where I can do that to filters Oauth in Rocket Chat ?

**Comment by wargamesqcf** [comment]
Are you using WP Oauth server v3.2?

**Comment by Lucky21110** [comment]
Yes 3.2.86.
Its works perfectly yes

WP-Oauth settings:

Authorization Code: Checked
Client Credentials: Checked
User Credentials: Checked
Refresh Tokens: Checked
Allow Implicit:	Checked

Token Length	: 30
Require Exact Redirect URI: Unchecked
Enforce State Parameter:	 Checked

OpenID Connect 1.0a : Leave default settings
Token Lifetimes : Leave default settings

On Client tab, you need to set this Redicrect URI : http://yourrocketchatinstance/_oauth/wordpress

Let me know if its works for you.

**Comment by wargamesqcf** [comment]
You must have the pro verison then because the one I just pulled is 3.2.0001 and lacks alot of those checks.

**Comment by flantascience** [comment]
Looks like this guy got it working??

**Comment by wargamesqcf** [comment]
I don't

**Comment by johnlund** [comment]
Hi @RocketChatApp there appears to be some on-going issue with the WP integration. I've updated #747 with the details of the issue I'm having. The built-in Wordpress oAuth doesn't seem to work with WP oAuth Server plugin non-pro.

I have it setup and _almost_ working with WP oAuth Server non-pro v 3.2.001, I'm just getting a strange base64 error as referenced in the issue above. Thanks!

**Comment by gjsman** [comment]
I am using non-pro, and have this issue:

 [34mI20171013-16:52:39.025(0) Exception while invoking method 'login' SyntaxError: Unexpected token <   at Object.parse (native)   at CustomOAuth.getAccessToken (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_custom-oauth.js:166:17)   at Object.handleOauthRequest (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_custom-oauth.js:224:28)   at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)   at middleware (packages/oauth.js:203:5)   at packages/oauth.js:176:5

**Comment by geekgonecrazy** [comment]
Please feel free to reach out via our [forum](https://forums.rocket.chat) or our [community server](https://open.rocket.chat) to discuss.

Forum would be a bit more appropriate to continue. That way we keep this for bugs and planned features
