### ISSUE TITLE
Integration not showing up

### ISSUE THREAD

**Issue by davidyyoo** [RocketChat/Rocket.Chat#4835]
Your Rocket.Chat version: .44

Created an outgoing webhook and deleted but the trigger word is still working.

**Comment by davidyyoo** [comment]
[34mI20161102-19:47:52.456(0) rocketchat:lib debug.js:15 [34mMeteor ➔ method updateMessage -> userId: RouHpv5JC3viSj3XF , arguments:  { '0':     { _id: 'dnyeWRxeQw2Jhrv7s',      msg: '!gifr test',      rid: 'miLdvdrLXmMvFA47o' } } 
[34mI20161102-19:47:52.559(0) rocketchat_integrations triggers.coffee:154 [34mIntegrations ➔ Outgoing WebHook.info Will execute trigger GiphyRocket to https://api.giphy.com/v1/ 
[34mI20161102-19:47:52.560(0) rocketchat_integrations triggers.coffee:155 [34mIntegrations ➔ Outgoing WebHook.debug { token: 'xNMSNwZ4dttG4wQ78jZS6iN2',   channel_id: 'miLdvdrLXmMvFA47o',   channel_name: 'general',   timestamp: Wed Nov 02 2016 19:46:57 GMT+0000 (UTC),   user_id: 'RouHpv5JC3viSj3XF',   user_name: 'dyoo',   text: '!gifr test',   bot: { i: 'c64nioDXoc6XgxAGt' },   trigger_word: '!gif' } 
[34mI20161102-19:47:52.561(0) rocketchat_integrations triggers.coffee:84 [34mIntegrations ➔ Outgoing WebHook.debug [Script method [ prepare_outgoing_request ] result of Trigger GiphyRocket :] 
[34mI20161102-19:47:52.563(0) rocketchat_integrations triggers.coffee:85 [34mIntegrations ➔ Outgoing WebHook.debug { url: 'https://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=!gifr+test&rating=pg',   headers: { 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36' },   method: 'GET' } 
[34mI20161102-19:47:52.619(0) rocketchat_integrations triggers.coffee:210 [34mIntegrations ➔ Outgoing WebHook.info Status code for trigger GiphyRocket to https://api.giphy.com/v1/ is 200 
[34mI20161102-19:47:52.620(0) rocketchat_integrations triggers.coffee:84 [34mIntegrations ➔ Outgoing WebHook.debug [Script method [ process_outgoing_response ] result of Trigger GiphyRocket :] 
[34mI20161102-19:47:52.621(0) rocketchat_integrations triggers.coffee:85 [34mIntegrations ➔ Outgoing WebHook.debug { content: { attachments: [ [Object] ] } }

**Comment by davidyyoo** [comment]
More info.  Seems like after an integration is created and removed or changed, the trigger word is still working...

**Comment by davidyyoo** [comment]
If you have !gif and add another command called !giftest, it only uses !gif and anything after !gif is assumed to be part of the previous command...hope I'm making sense.

**Comment by geekgonecrazy** [comment]
@davidyyoo do you still have this issue?  Also just to check... The title indicates a integration isn't working. 

Is it that as well, or is it only that you add one and remove it and the trigger word is still active?

**Comment by graywolf336** [comment]
Closing this because recent updates to the Integrations have improved them and removing an integration actually removes them. However, if something tries and fails and the retries is on then it will keep retrying even if the integration was removed or disabled. Working on fixing that now.
