### ISSUE TITLE
[Sandstorm] File upload fails (v 0.45.0)

### ISSUE THREAD

**Issue by neynah** [RocketChat/Rocket.Chat#4836]
Rocket.Chat version: 0.45.0

![image](https://cloud.githubusercontent.com/assets/855341/19945465/7d430aa4-a0fd-11e6-8b2a-5fd52bda4677.png)

**Comment by dwrensha** [comment]
This regression happened between 0.39.0 and 0.40.0. It looks like the same problem as in #910. @Sing-Li: how did that eventually get resolved? #4944 fixes this, but maybe there's a nicer solution.

**Comment by Sing-Li** [comment]
That might have been a different cause. As far as I remember, it had to do
with Imagemagik resizing images using same file name for output. And only
affected image files.
