### ISSUE TITLE
android app in f-droid o apk download

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#4838]
Hello Devs.

Is it possible to push rocketchat to f-droid or make it possible to get the apk for all no google users among us?

thanks and cheers
t.

**Comment by knarf-hackatal2016** [comment]
Having it on Aptoide would be nice too.

**Comment by geekgonecrazy** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Cordova/issues/104
