### ISSUE TITLE
How to start the service

### ISSUE THREAD

**Issue by yuanhongb** [RocketChat/Rocket.Chat#4840]
Greetings,

I'm a developer, and would like to start the app. I did follow the orders:
![image](https://cloud.githubusercontent.com/assets/9713291/19964978/b5863104-a1ff-11e6-8c9d-e3af9c38a97c.png)

But it throws me an error: 

![image](https://cloud.githubusercontent.com/assets/9713291/19964908/53db006a-a1ff-11e6-9ab3-932823a3941f.png)

I'm the fresh guy on Rocketchat, so could anyone help me solve this ?? 

Rocket.Chat version: 0.45

**Comment by andi242** [comment]
You may want to have a look at the installation instructions: https://rocket.chat/docs/installation/manual-installation/ubuntu/

Seek for your OS, if it isn't ubuntu.

once all is set you can start the service with `node main.js` in your rocketchat directory (e.g. /opt/rocketchat)

**Comment by yuanhongb** [comment]
I don't just want run the server. I would like to know how to run the service with source code.

**Comment by karlprieb** [comment]
@yuanhongb You need to have a c++ compiler, like g++

**Comment by andi242** [comment]
@yuanhongb services (like: start RocketChat at system startup) are dependend on your OS.
You'll need to learn about how your OS handles services.

Example (**this may not apply to your system**):
I run on an Ubuntu system and created a systemd file to control RocketChat.
Ubuntu comes with systemd and relies on files that have specific suffixes (like `.service`) that are located in `/lib/systemd/system/`.

Create file: `/lib/systemd/system/rocketchat.service`
contents:
```
[Unit]
Description=rocketchat service
After=network.target
Requires=mongod.service

[Service]
Type=simple
Environment=ROOT_URL=https://<your-url>
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat
Environment=PORT=3000
WorkingDirectory=/path/to/Rocket.Chat/
ExecStart=/usr/local/bin/node main.js

[Install]
WantedBy=multi-user.target
```
This creates a service. Nonetheless... you need to know about your OS.

**Comment by yuanhongb** [comment]
@andi242 @karlprieb Thank you, guys! I just solve this issue by increasing my VM memory to 2G.
