### ISSUE TITLE
Option to remove "forgot your password" link

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#4843]
Your Rocket.Chat version: 0.45

Our Rocket Chat is using an LDAP back-end for account management.  So, in our Rocket Chat environment, we set "Allow Password Change" to false, since Rocket Chat can't change LDAP passwords currently.  However, in spite of this, when users go to their Rocket Chat login page, they still see a link for "Forgot your password".  If password reseting is set to false, it seems to me that the "Forgot your password" link should be removed from the login page.

**Comment by 78c59635bdd8** [comment]
OK, as a temporary work around, I've hidden the forgot your password link by adding the following to our custom CSS: 
.forgot-password{display:none;}

**Comment by Citizen01** [comment]
I'm also using LDAP auth and you can disable the "Forgot your password" link by setting ```Admin > Account > Register > Reset password``` to ```False``` instead of adding a custom CSS rule.

**Comment by mddvul22** [comment]
Awesome, thanks for pointing that out.

**Comment by Kubpent** [comment]
Hi, 

With this options, the API request /api/v1/users.forgotPassword is still callable

How can we disable the api method ? 

Thanks
