### ISSUE TITLE
File Uploaded text on attachments to i18n Bugged

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#4845]
This was suppose to be fixed for about 3 months ago #4058 .
However there is something bugged about this one becouse it's not reacting to the translation. 
![1](https://cloud.githubusercontent.com/assets/17712562/19970069/2a0d7462-a1db-11e6-8bc0-ada879ef9d91.PNG)

**Comment by geekgonecrazy** [comment]
@Molle500 is this a file uploaded prior to the translation?  If so its not going to change. That text is stored on the message record.

**Comment by engelgabriel** [comment]
@geekgonecrazy if that is the case, we should create an issue to change that, and use the message rendered to translate the message on the UI and not in the backend.

**Comment by geekgonecrazy** [comment]
Yeah looks like we translate on creation of the attachment and store it:

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-file-upload/server/methods/sendFileMessage.js#L18

**Comment by Molle500** [comment]
@geekgonecrazy This is a new uploaded file so it's after the translation. You can change language to swedish and try for urself if u want :)

**Comment by MartinSchoeler** [comment]
@Molle500 @geekgonecrazy I think the problem with 'UNREAD MESSAGES' is that this text is being added on a css file, here: 
https://github.com/RocketChat/Rocket.Chat/blob/8fcfa3f5ab9cbb4e35480300fe62cc157d9af41a/packages/rocketchat-theme/assets/stylesheets/base.less#L180
not even using the i18n system

**Comment by geekgonecrazy** [comment]
@MartinSchoeler I completely missed that one.  Yeah that one it does look like is in css

**Comment by engelgabriel** [comment]
@MartinSchoeler @Molle500 has this been fixed now?

**Comment by Molle500** [comment]
@engelgabriel not on your demo.rocket.chat atleast. Dont know about your dev branches

![rc](https://cloud.githubusercontent.com/assets/17712562/25038447/2869bd16-20ff-11e7-8257-acd391e7fe73.gif)

**Comment by Molle500** [comment]
It might have been fixed, i saw there was a few lines at lingohub that wasn't translated with "File Uploaded". I will check after next lingo update :) @engelgabriel

**Comment by Molle500** [comment]
This one still do not work :/

**Comment by MartinSchoeler** [comment]
Hey @Molle500 i'm working on that issue and i wanted to know your opinion on what to do with the old file names, I can either create a migration to remove the "File Uploaded" string from files or leave them as is.
Thanks!

**Comment by geekgonecrazy** [comment]
I personally think we should have the fix take place from here forward.  On large servers like say the demo server where we have a looooooooooot of file uploads.  This could be a very heavy migration.  So I think it would be better to just have all messages here on out be properly translated.

Just my two cents :)
