### ISSUE TITLE
Click to Join doesn't work

### ISSUE THREAD

**Issue by davidyyoo** [RocketChat/Rocket.Chat#4846]
Your Rocket.Chat version: .44

Click to join button doesn't work.

**Comment by Nemra1** [comment]
same issu her 4.5

**Comment by MartinSchoeler** [comment]
@davidyyoo could you give us more info on the problem?

**Comment by Nemra1** [comment]
@MartinSchoeler its simple
when new user click in join to channel in footer ..nothing happen just stuck in join button

**Comment by davidyyoo** [comment]
What @Nemra1 said.

**Comment by childnode** [comment]
often enough just the "sidebar" not opens automatically when clicking the button! That is - to me - the bug seen here.

**Comment by hadifarnoud** [comment]
not working, neither video conference nor webrtc.
version .53

**Comment by MartinSchoeler** [comment]
Closing this due lack of info.
If you continue to have this issue, please open a new issue after testing with the latest release and posting any errors in the [console](https://rocket.chat/docs/contributing/reporting-issues#gathering-logs)

Thanks!
