### ISSUE TITLE
Windows client: clicking on "MORE UNREAD MESSAGES" should go to the unread messages

### ISSUE THREAD

**Issue by rillig-nm** [RocketChat/Rocket.Chat#4847]
Your Rocket.Chat version: 1.3.1

![2016-11-03 15_56_51-rocket chat](https://cloud.githubusercontent.com/assets/8994464/19971079/48560224-a1de-11e6-906d-039c205288d8.png)

When I click on the `MORE UNREAD MESSAGES` field, nothing happens. I expect to reach the unread messages when clicking on this text, since it looks like a button.

**Comment by geekgonecrazy** [comment]
This should no longer be an issue... mainly because we no longer even have this element. :smile:
