### ISSUE TITLE
[iOS hybrid] Scrolling issue

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#485]
While in a channel open Members List -> scroll - result: the channel messages scroll below. 

i have not seen a channel with enough members to enable scrolling - but i suspect both lists would scroll.
##

**Comment by engelgabriel** [comment]
@rodrigok I think we should copy the behaviour you implemented for the left nav to the right flextab. Make it fixed behind, and the messages box to slide over. That would be a nicer UX, and would fix this bug too.

**Comment by rodrigok** [comment]
@engelgabriel only for mobile?

**Comment by engelgabriel** [comment]
both

**Comment by rodrigok** [comment]
Don't seems to be an emergency issue, we can delay to after 1.0

**Comment by gmsecrieru** [comment]
I could not reproduce this error with iOS app, is that still an issue for you @raulfiru ?

**Comment by klatys** [comment]
This is still happening. Additionaly if members list is long enough to be scrolled, channel messages do not scroll underneath

**Comment by engelgabriel** [comment]
@karlprieb please verify if the problem still exists?

**Comment by MartinSchoeler** [comment]
@engelgabriel managed to reproduce this bug on the cordova app for android

**Comment by MartinSchoeler** [comment]
With the new UI this problem was fixed, If you think I'm closing this in error, please reopen this. Thanks!
