### ISSUE TITLE
GPS Location button not usable anymore

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4850]
Rocket.chat version: 0.45.0 

Hey Guys, 

on my iPhone the Geolocation button is not clickable / usable anymore. Nothing happens on tap on that button. 

Happens on demo and my deployments.

**Comment by MartinSchoeler** [comment]
@TheReal1604 Only in the IOS? Or in the computer browser as well?

**Comment by TheReal1604** [comment]
Hey Martin,

this is only on the iOS mobile client.

Am 04.11.2016 um 13:41 schrieb Martin Schoeler <notifications@github.com<mailto:notifications@github.com>>:


@TheReal1604<https://github.com/TheReal1604> Only in the IOS? Or in the computer browser as well?

-

**Comment by MartinSchoeler** [comment]
@rodrigok What you think about this one? Maybe some script or plugin missing with the cordova app?

**Comment by TheReal1604** [comment]
@rodrigok @MartinSchoeler Tested this also with the docker image from the experimental branch, there it is broken also.

**Comment by TheReal1604** [comment]
@rodrigok @MartinSchoeler broken in 0.47.0-development also! :-1:
