### ISSUE TITLE
Future : Add User Status For Members

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4852]
Your Rocket.Chat version: (latest)
Hope From RC team to add User status option for users like that
Step 1
![2016-11-03_224818](https://cloud.githubusercontent.com/assets/22897987/19984712/3c69f184-a218-11e6-8d9c-025e739dc710.png)

step 2-Showing Status under username in userlist
![2](https://cloud.githubusercontent.com/assets/22897987/19984736/5632f106-a218-11e6-9f91-9f653ce263c8.png)

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
