### ISSUE TITLE
"Mobile Setup" UI for home footer & configuration subpage

### ISSUE THREAD

**Issue by neynah** [RocketChat/Rocket.Chat#4855]
Rocket.Chat version: 0.39.0

There's a demand for connecting the Rocket.Chat mobile app with the web app (see #1352), however, this capability as well as the steps involved are invisible/undiscoverable to most users. This UI proposal makes the mobile setup instructions more accessible while also accomplishing informing users that they can connect their web and mobile apps.

These mock-ups show what we plan on implementing for Rocket.Chat on Sandstorm (over the next week), however, it might be worth considering adding similar UI to the main Rocket.Chat app as well. I'd love to get feedback (over the next few days) from Rocket.Chat users & the Rocket.Chat team on this design.

Proposed flows:
- (1) User starts inside the web/mobile browser -> Clicks on "Mobile Setup" on the home page or navigates to "Mobile Setup" under /My Account -> Downloads & installs mobile app (if they haven't yet) -> Clicks on "Connect to mobile app"
- (2) User starts inside the Rocket.Chat mobile app -> Enters "oasis.sandstorm.io" (we do an XHR to detect the sandstormness) -> UI displays with instructions to open up web/mobile browser -> Flow (1)

![flow](https://cloud.githubusercontent.com/assets/855341/19987407/38e5da7c-a1d8-11e6-9e9a-57732cd25c1c.png)

So far I've designed mock-ups of the UI required in flow (1). Mock-ups for flow (2) are in the works.

- Display a fixed footer on the "home" page of the app that describes and links to the "Mobile Setup" (which will be under /My Account). The footer will remain visible even if the home page is content-heavy; any excess content will overflow scroll.

![home1](https://cloud.githubusercontent.com/assets/855341/19986919/d0e7d09e-a1d5-11e6-9e23-b24921fcb6ae.png)
![home-mobile-1](https://cloud.githubusercontent.com/assets/855341/19987074/883b0cd4-a1d6-11e6-8e96-52753972be50.png)

- Add "Mobile Setup" subpage under /My Account. The "Mobile Setup" page title will appear under "Preferences" in the left sidebar.

![mobile-setup2](https://cloud.githubusercontent.com/assets/855341/19988240/5c23803a-a1dc-11e6-8af0-813abacda01d.png)

Notes: 

- Styling in the mock-ups are rough/approximate. We would want to use the same font styling & button styling to be identical to the existing Rocket.Chat styling.
- Mock-ups can also be viewed here: https://oasis.sandstorm.io/shared/WZSsZua4ru7n4Om_t0MxJvdOHpuCu3WLLgv0LKG0T93

**Comment by Nemra1** [comment]
nice idea

**Comment by engelgabriel** [comment]
@neynah sorry for the late reply, but we were overloaded with other bugs/fetaures.

We now have @karlprieb a front-end engineer that will work with you on this issue.
