### ISSUE TITLE
New bug : i cant Make any channel or edit (im adminstrator )

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4856]
Your Rocket.Chat version: (the latest)
after setup RC and trying to add new channel isee this msg
![1](https://cloud.githubusercontent.com/assets/22897987/19990964/6b63e7f2-a23a-11e6-8e83-73cfaef8cdcb.png)
trying big latter ,small latter, only numbers,any thing dosnt work..to now i have the general room also i cant edit or add channels
any idea?

**Comment by MartinSchoeler** [comment]
Hey @Nemra1 take a look in the utf8 settings under administration > general
By default it should be like this:
![screenshot from 2016-11-03 09-56-40](https://cloud.githubusercontent.com/assets/20868078/20006397/7745707e-a27e-11e6-99a4-354333ba2450.png)

**Comment by Nemra1** [comment]
already do that but the problem when im trying to install rocket chat in home/live
i mean when im setup RC in different dir ..im using centos 6 and cpanel11

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
