### ISSUE TITLE
Invite new users by Email and register these Emails automatically.

### ISSUE THREAD

**Issue by oychao** [RocketChat/Rocket.Chat#4858]
#### My Rocket.Chat version: 0.46.0-develop

I've noticed current version can send invitation mail, but it's just a simple invitations mail, like asking someone to come and see this site, nothing more, for now all users have to sign up themselves.

Could we invite new users by emails and sign up automatically, like the invitation email is just a verification email?

**Comment by ehginanjar** [comment]
+1

**Comment by sampaiodiego** [comment]
hey, looks like we have this feature already.

when creating a user via `Admin > Users` you can send him an welcome email:
![image](https://cloud.githubusercontent.com/assets/8591547/25489377/01e8602a-2b40-11e7-9b92-70f6b4dea141.png)

**Comment by FaizanZahid** [comment]
+1
