### ISSUE TITLE
[osX App] Strange Channel Change 

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#486]
When someone joined #general while i was in #dev the view changed to #general.

Attached (the selection on the left side is correct)

![screen shot 2015-08-17 at 22 51 20](https://cloud.githubusercontent.com/assets/11820636/9315995/c74aab7a-4532-11e5-88e6-dbbdcbb4f167.png)

**Comment by engelgabriel** [comment]
Thats a known bug, and it probably about time to fix it. Can we make it a priority @rodrigok today?

**Comment by engelgabriel** [comment]
I believe i has to do with the RoomManager object, expiring the wrong room. It used to "know" what room was opened and never expire it. But know seem that it is stuck thinking that the GENERAL is the "unexpirable" room.

**Comment by rodrigok** [comment]
@engelgabriel sure

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/4bfd882096e11b806aea63cfe0ffcf29db485544
