### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by nk1506** [RocketChat/Rocket.Chat#4860]
with the latest version. when I am trying to deploy it on AWS free tier. Seeing following error.  Can you please explain root cause?

Extracting templating-compiler@1.2.15...  \                                     

<--- Last few GCs --->

   35289 ms: Scavenge 249.4 (294.3) -> 249.0 (294.3) MB, 3.4 / 0 ms [allocation failure].
   35301 ms: Scavenge 249.7 (294.3) -> 249.3 (295.3) MB, 1.5 / 0 ms [allocation failure].
   35312 ms: Scavenge 250.0 (295.3) -> 249.7 (295.3) MB, 1.3 / 0 ms [allocation failure].
   35326 ms: Scavenge 252.2 (297.2) -> 251.8 (297.2) MB, 2.0 / 0 ms [allocation failure].
   53677 ms: Scavenge 259.1 (303.9) -> 261.0 (3216.9) MB, 8301.6 / 104 ms [allocation failure].

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
