### ISSUE TITLE
Windows client should open when clicking on the tray icon

### ISSUE THREAD

**Issue by rillig-nm** [RocketChat/Rocket.Chat#4862]
Your Rocket.Chat version: 1.3.1

When I click on the tray icon of Rocket.Chat+, nothing happens. Double clicking opens the chat window.

A single click should be enough to open the chat window. This change would make Rocket.Chat+ feel less clumsy and therefore improves user experience.

**Comment by geekgonecrazy** [comment]
This is a feature request/bug report for the desktop client.  Please open an issue here: https://github.com/rocketchat/rocket.chat.electron/issues
