### ISSUE TITLE
any help with this rocketchat_internal_hubot path not found

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4863]
Your Rocket.Chat version: ( latest)
this hapend with setup rocket chat
![2016-11-04_151117](https://cloud.githubusercontent.com/assets/22897987/20007013/0604d628-a2a3-11e6-8b30-2815e05c9dd0.png)

OS :CENTOS 6
RC-Latest

**Comment by MartinSchoeler** [comment]
@Nemra1 We are all getting this error, probably some left over code or missing module, nothing to worry about for now

**Comment by Nemra1** [comment]
@MartinSchoeler thx sir
