### ISSUE TITLE
Users can bypass "block delete/edit after X minutes" by changing system clock

### ISSUE THREAD

**Issue by ksuquix** [RocketChat/Rocket.Chat#4865]
Your Rocket.Chat version: 0.45.0

**Comment by ksuquix** [comment]
To be clear, they can do it by changing the time on their workstation.

**Comment by ksuquix** [comment]
More information: this seems to be the Windows client only as far as we can tell.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
