### ISSUE TITLE
npm install fails with 0.4.5

### ISSUE THREAD

**Issue by cutzenfriend** [RocketChat/Rocket.Chat#4866]
Your Rocket.Chat version: 0.4.5

I'm using Rocket.Chat since 0.4.2 every version since then I installed on my Ubuntu 16.04 system with nodejs set to 4.5 as non-root user in the home directory. Since Version 0.4.5 this doesn't work. I always get the following error:

=========================================================================
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
|
> fibers@1.0.15 install /home/hubot/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /home/hubot/Rocket.Chat/programs/server
> node npm-rebuild.js

> fsevents@1.0.14 install /home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/build'
  SOLINK_MODULE(target) Release/obj.target/.node
  COPY Release/.node
make: Leaving directory '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/build'

> sauce-connect-launcher@0.13.0 postinstall /home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/sauce-connect-launcher
> node scripts/install.js

> phantomjs-prebuilt@2.1.13 install /home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Found PhantomJS at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
Writing location.js file
Error checking path, continuing { [Error: EACCES: permission denied, open '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' }
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1478284081795/phantomjs-2.1.1-linux-x86_64 -> /home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Phantom installation failed { [Error: EACCES: permission denied, open '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' } Error: EACCES: permission denied, open '/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at writeLocationFile (/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/install.js:88:5)
    at nextTickCallback (/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/kew/kew.js:47:28)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/npm-debug.log

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hubot/Rocket.Chat/programs/server/npm-debug.log

=========================================================================

could anyone help?

Just for reference I did the upgrade like it was explained here: https://rocket.chat/docs/installation/manual-installation/ubuntu/#install

**Comment by lucasvanhalst** [comment]
The error is clear enough, npm doesn't have permission to write in that folder. try `sudo npm install`

**Comment by cutzenfriend** [comment]
The user is "hubot" and the folder is in his home directory I tried a:

`chown -R hubot:hubot /home/hubot/Rocket.Chat`

before my 2nd install attempt. Didn't work... In fact this folder is writable for that user:

/home/hubot/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js

Same error!

**Comment by cutzenfriend** [comment]
Got it working with: `npm install --unsafe-perm` and after that an `chown -R hubot:hubot /home/hubot/Rocket.Chat`

0.4.5 is running :)

**Comment by engelgabriel** [comment]
Hi guys, this is a Meteor issue https://github.com/meteor/meteor/issues/7958

I have already implemented the work around on the develop branch.

**Comment by KheireddineAzzez** [comment]
_### Error: EACCES: permission denied, stat ‘/home/dev/Projects/vendor-chat/data/db/_tmp/.meteorignore’_


**These two commands saved my life**
**

-  npm install --unsafe-perm


**

- And then ownership change command for current user.


sudo chown -R user:user path_to_rocketchat_codebase_directory 


   Example sudo chown -R **Alex** /myrocketchat
