### ISSUE TITLE
[osX] Notification on all messages

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#487]
On the native osX app every new message on every channel generates a notification (icon "jumps").

This is annoying and the fact that opening the app does not show you in witch channel you have new messages just adds to the annoyance.

**Comment by rodrigok** [comment]
Agreed :(

**Comment by engelgabriel** [comment]
I didn't get the second point:

> opening the app does not show you in which channel you have new messages

The channels with unread messages should be in bold. Is this not the case?

**Comment by raulfiru** [comment]
i didn't see it on mac.

I will recheck this evening when i get home. But i didn't see #general in bold... however i expected some sort of a bubble like in slack

**Comment by engelgabriel** [comment]
We have exactly the same behaviour as Slack defaults settings. You only get the bubble if you have been mentioned, otherwise, you only get a bold highlight.

**Comment by engelgabriel** [comment]
Maybe you didn't see #general in bold because that was the room you were in already? So it immediately marked as read when you opened the app.

**Comment by raulfiru** [comment]
could be related to the other bug.. that there was a "view" change when a new message was in #general while the left pannel as still selecting #dev... but i am speculating - let me check this evening.

Or feel free to try for yourself ;)

**Comment by raulfiru** [comment]
you are right about Slack...  but that bold is very evident so i wonder how i would have missed it...

**Comment by raulfiru** [comment]
it turned bold...

however the channel got bold even if i was in it... in order to reset i had to change to another and back.

**Comment by rodrigok** [comment]
@raulfiru sorry about that, my fault, I just fixed it and we will deploy ASAP.

**Comment by rodrigok** [comment]
@raulfiru is fixed now

**Comment by engelgabriel** [comment]
@raulfiru can you confirm is it all working now?

**Comment by raulfiru** [comment]
yup. works.

the channel name gets bold for a split second and then back. i don't see an issue with that... not now anyway

good work!
