### ISSUE TITLE
Rocket.cat bot 

### ISSUE THREAD

**Issue by Hostile** [RocketChat/Rocket.Chat#4871]
0.45.0

Hi I run RC with docker compose its got Hubot conf in it and it works fine. Bot replies.

In latest update theres some bot settings and rocket.cat but when I enable it it dosent responds. How do I talk to it?

**Comment by Julianoe** [comment]
hey @Hostile i also run RC with Docker. Could you describe the basic set of things you did so the bot works ? It seems the Internal Bot works but i can't make work the bot set in my docker file
