### ISSUE TITLE
Hubot Issue with V0.45

### ISSUE THREAD

**Issue by daemienb** [RocketChat/Rocket.Chat#4873]
I'm seeing the issue in 0.45 non docker install -

I've used npm install hubot-rocketchat@1 : should i be using a different hubot version? and how do i upgrade or downgrade?
Thanks

[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Starting Rocketchat adapter version 0.1.4...
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Once connected to rooms I will respond to the name: alfred
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] WARNING No services ROCKETCHAT_URL provided to Hubot, using localhost:3000
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] WARNING No services ROCKETCHAT_ROOM provided to Hubot, using GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Connecting To: localhost:3000
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Successfully connected!
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Logging In
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Successfully Logged In
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Looking up Room ID for: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Joining Room: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO rid: [ 'GENERAL' ]
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO All rooms joined.
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Successfully joined room: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Preparing Meteor Subscriptions..
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] INFO Subscribing to Room: GENERAL
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription 'stream-messages' not found","message":"Subscription 'stream-messages' not found [404]","errorType":"Meteor.Error"} Reason: Subscription 'stream-messages' not found
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] ERROR {"error":404,"reason":"Subscription 'stream-messages' not found","message":"Subscription 'stream-messages' not found [404]","errorType":"Meteor.Error"}
[Sat Nov 05 2016 17:52:58 GMT+1100 (AEDT)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.

**Comment by Hostile** [comment]
Works with docker compose tho

**Comment by lucasvanhalst** [comment]
You should use version 1.0.5 of the hubot adapter, then it will work.

**Comment by daemienb** [comment]
how does one install 1.0.5 of the hubot adapter?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
