### ISSUE TITLE
Unable to make video calls when setup in my private servers....

### ISSUE THREAD

**Issue by ianubhav** [RocketChat/Rocket.Chat#4874]
Your Rocket.Chat version: (make sure you are running the latest)
This is the error shown
![screen shot 2016-11-05 at 5 37 45 pm](https://cloud.githubusercontent.com/assets/14806508/20029883/9af4fbec-a37e-11e6-84f9-3113f1578c7c.png)

**Comment by lucasvanhalst** [comment]
If you run your site on https it will work, this is just google not allowing insecure (http) access to their STUN/TURN server which is used for those calls.

**Comment by geekgonecrazy** [comment]
Exactly as said above :top:
