### ISSUE TITLE
Audio /Video record not work in chrom /video record not work at all

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4875]
Your Rocket.Chat version: ( latest)
with fresh install then trying to record audio from chrome last version  Version 54.0.2840.87 m-64-bit-
nothing work like as u see
when click in mice button  chrome must warrn me to allow used mic ..but nothing happend ..just blank click
![2016-11-05_183316](https://cloud.githubusercontent.com/assets/22897987/20031912/3d00d858-a388-11e6-957b-f2c7cf850dc2.png)
 then trying record with another browser like spark browser http://en.browser.baidu.com/
audio record work perfect so to now for audio record i think is not compatible 
but its worked in demo at all browser like  demo.rocket.chat 
this issu for mice record.
===
Video record not work in chrome last version (Version 54.0.2840.87 m (64-bit) )
![2016-11-05_185503](https://cloud.githubusercontent.com/assets/22897987/20031963/6fa9052c-a389-11e6-8688-565b525dea05.png)
 soo as u see..blanked.........
lets try from another browser
for example spark browser http://en.browser.baidu.com/
![2016-11-05_184305](https://cloud.githubusercontent.com/assets/22897987/20031985/aefa1004-a389-11e6-97b3-f0c5969e68b7.png)
its worked but not record even click in record button nothing happen and this my upload ext 

![2016-11-05_190842](https://cloud.githubusercontent.com/assets/22897987/20032081/60fcee10-a38b-11e6-8cfa-f10acd54d3ce.png)
 browser console
![2016-11-05_193821](https://cloud.githubusercontent.com/assets/22897987/20032277/8b4fdbb0-a38f-11e6-98cf-ca33be0add98.png)

==================================
My setting
![2016-11-05_183914](https://cloud.githubusercontent.com/assets/22897987/20031999/ecffae18-a389-11e6-9bba-71dc5a1da11c.png)
![2016-11-05_183855](https://cloud.githubusercontent.com/assets/22897987/20032007/05f68266-a38a-11e6-81c8-3a63388cbcbf.png)
==========================
this Notifications showing only in spark browser but not in chrome
![2016-11-05_184232](https://cloud.githubusercontent.com/assets/22897987/20032045/83383a1c-a38a-11e6-9d20-0eeb423093f1.png)
and this when i trying to make call from chrome
![2016-11-05_192948](https://cloud.githubusercontent.com/assets/22897987/20032226/5b7963a8-a38e-11e6-990f-13ad93a16e5a.png)

any Idea?????**

**Comment by MartinSchoeler** [comment]
hey @Nemra1 if you open the chrome settings you can take a look on its permissions
go in the chrome settings tab
![screenshot from 2016-11-07 08-47-03](https://cloud.githubusercontent.com/assets/20868078/20055188/225afc14-a4c7-11e6-8640-257f0c6da5c6.png)
and click on "Content Settings" under "Privacy" and it should open something like this
![screenshot from 2016-11-07 08-47-31](https://cloud.githubusercontent.com/assets/20868078/20055249/59945c70-a4c7-11e6-96aa-ab2e261f0de7.png)
there you can look if something is blocking your camera or mic

**Comment by Nemra1** [comment]
thx fore replay @MartinSchoeler  but nothing blocked in my browser .... the only reason for my issu  im setup Rocket chat in http Protcol not https..then New version of google chrome browser dosnt support get user media from http protcol any more in (getUserMedia() )see this article http://stackoverflow.com/questions/34215937/getusermedia-not-supported-in-chrome 
 =============================
icant use https for now !
unfortunately im forced now to delet chrome last version Version 54.0.2840.87 and back to version 27.0.1453.94 
and as u see mice is workin now in chrome 27
![2016-11-08_015949](https://cloud.githubusercontent.com/assets/22897987/20084342/4e1ffa7c-a56a-11e6-90f3-8b4ac8aa1866.png)
to now i think all my member must back to chrome 27????

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
