### ISSUE TITLE
Push Gateway outage

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4879]
Your Rocket.Chat version: 0.45.0 - Demo

Hey Guys,

the push gateway is down:

![image](https://cloud.githubusercontent.com/assets/5877910/20037521/083d1af2-a421-11e6-8286-e46c2fd46af8.png)

`[34mI20161106-11:56:19.700(0) app.js:466 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: failed [502] <html>  <head><title>502 Bad Gateway</title></head>  <body bgcolor="white">  <center><h1>502 Bad Gateway</h1></center>  <hr><center>nginx/1.10.2</center>  </body>  </html>  ]   response:     { statusCode: 502,      content: '<html>\r<br><head><title>502 Bad Gateway</title></head>\r<br><body bgcolor="white">\r<br><center><h1>502 Bad Gateway</h1></center>\r<br><hr><center>nginx/1.10.2</center>\r<br></body>\r<br></html>\r<br>',      headers:        { server: 'nginx/1.10.2',         date: 'Sun, 06 Nov 2016 11:56:19 GMT',         'content-type': 'text/html',         'content-length': '173',         connection: 'close' },      data: null } } 
[34mI20161106-11:56:20.063(0) app.js:466 [31mSystem ➔ error Error sending push to gateway (1 try) -> { [Error: failed [502] <html>  <head><title>502 Bad Gateway</title></head>  <body bgcolor="white">  <center><h1>502 Bad Gateway</h1></center>  <hr><center>nginx/1.10.2</center>  </body>  </html>  ]   response:     { statusCode: 502,      content: '<html>\r<br><head><title>502 Bad Gateway</title></head>\r<br><body bgcolor="white">\r<br><center><h1>502 Bad Gateway</h1></center>\r<br><hr><center>nginx/1.10.2</center>\r<br></body>\r<br></html>\r<br>',      headers:        { server: 'nginx/1.10.2',         date: 'Sun, 06 Nov 2016 11:56:20 GMT',         'content-type': 'text/html',         'content-length': '173',         connection: 'close' },      data: null } } 
[34mI20161106-11:56:21.330(0) app.js:466 [31mSystem ➔ error Error sending push to gateway (2 try) -> { [Error: failed [502] <html>  <head><title>502 Bad Gateway</title></head>  <body bgcolor="white">  <center><h1>502 Bad Gateway</h1></center>  <hr><center>nginx/1.10.2</center>  </body>  </html>  ]   response:     { statusCode: 502,      content: '<html>\r<br><head><title>502 Bad Gateway</title></head>\r<br><body bgcolor="white">\r<br><center><h1>502 Bad Gateway</h1></center>\r<br><hr><center>nginx/1.10.2</center>\r<br></body>\r<br></html>\r<br>',      headers:        { server: 'nginx/1.10.2',         date: 'Sun, 06 Nov 2016 11:56:21 GMT',         'content-type': 'text/html',         'content-length': '173',         connection: 'close' },      data: null } } 
[34mI20161106-11:56:31.592(0) app.js:466 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: failed [502] <html>  <head><title>502 Bad Gateway</title></head>  <body bgcolor="white">  <center><h1>502 Bad Gateway</h1></center>  <hr><center>nginx/1.10.2</center>  </body>  </html>  ]   response:     { statusCode: 502,      content: '<html>\r<br><head><title>502 Bad Gateway</title></head>\r<br><body bgcolor="white">\r<br><center><h1>502 Bad Gateway</h1></center>\r<br><hr><center>nginx/1.10.2</center>\r<br></body>\r<br></html>\r<br>',      headers:        { server: 'nginx/1.10.2',         date: 'Sun, 06 Nov 2016 11:56:31 GMT',         'content-type': 'text/html',         'content-length': '173',         connection: 'close' },      data: null }`

**Comment by MartinSchoeler** [comment]
@TheReal1604 everything seems to be in order now, but thanks for keeping an eye out!
