### ISSUE TITLE
[iOS Hybrid] Clicking on an image

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#488]
...in the chat opens it in a browser control (i imagine) and there is no way back.

Must restart app

**Comment by rodrigok** [comment]
Are you sure? This file https://github.com/RocketChat/Rocket.Chat/blob/master/client/lib/cordova/urls.coffee tries to resolve this opening urls starting with http:// or https:// in external browser.

**Comment by raulfiru** [comment]
i can't reproduce it anymore. Strange..

will reopen if i figure out how to reproduce
