### ISSUE TITLE
Offline Email Notifications

### ISSUE THREAD

**Issue by ianubhav** [RocketChat/Rocket.Chat#4880]
Your Rocket.Chat version: (make sure you are running the latest)
How to turn off offline email notifications by default for a new user?

**Comment by isabellarussell** [comment]
This is a similar issue to: #3355 they are related.
Closing this one but do let us know if you require additional support.

**Comment by isabellarussell** [comment]
Hi there, just found this in our documentation and it will help you with your issue:
https://rocket.chat/docs/user-guides/managing-your-account/
