### ISSUE TITLE
Spaces in channels names

### ISSUE THREAD

**Issue by Huljo** [RocketChat/Rocket.Chat#4886]
Your Rocket.Chat version: 0.45.0

The current release is not allowing spaces in channel names. I guess that is due to the way it stored in db.
_server/methods/createChannel.coffee_
````javascript
if not /^[0-9a-z-_\x00-\x7F]+$/.test name
throw new Meteor.Error 'name-invalid'
````

However it seem legit to allow users to create channels names containing spaces. (e.g: "funny things").

Why is that not accepted ? Is there a setting to allow it ?

**Comment by marceloschmidt** [comment]
You can set allowed characters in Administration -> General -> UTF8 -> UTF8 Names Validation.

**Comment by Huljo** [comment]
Thanks, but why is there this warning above the field "Do not allow special characters and spaces." ?

**Comment by marceloschmidt** [comment]
Ha! **That** is a bug :) 
![image](https://cloud.githubusercontent.com/assets/1986378/20176735/4f0aaf8c-a730-11e6-8ffe-7015d9e9f1f0.png)

This message refers to **our** default value for this setting and should not be there.

**Comment by marceloschmidt** [comment]
@MartinSchoeler could you please change the text for `UTF8_Names_Validation_Description` to reflect something more meaningful? Something like "RegExp that will be used to validate usernames and channel names"

**Comment by lunitic** [comment]
Will RC under stand a channelname **#my channel** or will it just make it **#my** channel

**Comment by marceloschmidt** [comment]
Ah, now that's a good question @lunitic I don't think we support spaces indeed...

**Comment by marceloschmidt** [comment]
@MartinSchoeler please test that as well

**Comment by MartinSchoeler** [comment]
You can create a channel with spaces but some features will not work properly:
![selection_005](https://cloud.githubusercontent.com/assets/20868078/20177229/d9af5ac8-a732-11e6-82d3-95353e835936.png)
marking the channel dont work: 
![selection_006](https://cloud.githubusercontent.com/assets/20868078/20177230/dd13b8c6-a732-11e6-8787-ee363fdbd1d3.png)

**Comment by Huljo** [comment]
Thanks @MartinSchoeler. I'll probably open an other issue for the marking bug.
