### ISSUE TITLE
Installation problem with Docker

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#4889]
Your Rocket.Chat version: (make sure you are running the latest)

I am using Ubuntu 16.04 with Docker and Docker Composer installed. 
I follow the instruction in the guide to a tee and when I run the Docker image of rocketchat I get the following error:

rocketchat_1 | /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat_1 | 						throw(ex);
rocketchat_1 | 						^
rocketchat_1 | 
rocketchat_1 | Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
rocketchat_1 |     at Error (native)
rocketchat_1 |     at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:218:13)
rocketchat_1 |     at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
rocketchat_1 |     at new MongoConnection (packages/mongo/mongo_driver.js:222:25)
rocketchat_1 |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
rocketchat_1 |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
rocketchat_1 |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
rocketchat_1 |     at new Mongo.Collection (packages/mongo/collection.js:103:40)
rocketchat_1 |     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
rocketchat_1 |     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)

I'm a bit of a noob when it comes to Mongo. What else do I need to do to get this working out of the box?

**Comment by TheReal1604** [comment]
@Syirrus Please post your docker-compose.yml here. (Take care of sensitive information)

**Comment by Syirrus** [comment]
This is taken from [here](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml)

rocketchat:
  image: rocketchat/rocket.chat:latest
  volumes:
    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
    - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    - MAIL_URL=smtp://smtp.email
    - HTTP_PROXY=http://proxy.domain.com
    - HTTPS_PROXY=http://proxy.domain.com
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  labels:
    - "traefik.backend=rocketchat"
    - "traefik.frontend.rule=Host: your.domain.tld"

mongo:
  image: mongo:3.2
  volumes:
   - ./data/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128 --replSet rs0
  labels:
    - "traefik.enable=false"

mongo-init-replica:
  image: mongo:3.2
  command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
  links:
    - mongo:mongo

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:latest
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=botpassword
    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
    - rocketchat:rocketchat
  labels:
    - "traefik.enable=false"
  volumes:
    - ./scripts:/home/hubot/scripts
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080

#traefik:
#  image: traefik:latest
#  command: traefik --docker --acme=true --acme.domains='your.domain.tld' --acme.email='your@email.tld' --acme.entrypoint=https --acme.storagefile=acme.json --defaultentrypoints=http --defaultentrypoints=https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS.Certificates:'
#  ports:
#    - 80:80
#    - 443:443
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock

**Comment by Zegorax** [comment]
Same problem here. Can't figure it out, even after doing a rs.initiate() in the Mongo container.

**Comment by TheReal1604** [comment]
@Zegorax Okay. Thanks for the Infos. It is really important to initiate the replicaset with the second "mongo-init-replica" docker container. Can you post the logs from this container here?

`docker logs <container-name>`

**Comment by akmad** [comment]
@TheReal1604 I am experiencing the same issue. I am using the example docker-compose.yml file (from [here](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml)) and [this](https://gist.github.com/akmad/11c3afe8b429efcf32ffac3c01be39a6) is the output of the logs for the mongo container.

**Comment by TheReal1604** [comment]
@akmad That looks ok. But i need the logs from the "rocketchat_mongo_init-replica..." container. This is enabling oplog for you.

**Comment by akmad** [comment]
@TheReal1604 Thanks for the quick reply! I do not have a container for the replica. 

Perhaps I am not following the correct steps to get this up and running with docker-compose. I am using the steps [here](https://rocket.chat/docs/installation/docker-containers/docker-compose) and simply started mongo with:

`docker-compose up -d mongo`

Thanks for any help that you can provide!

**Comment by TheReal1604** [comment]
@akmad Okay.. some explanation :-).

If you want to use the oplog (this is really really suggested) you have to init a replicaset via the docker-compose.yml section mentioned above.

You have 2 Docker Containers - one with mongo itself - and one container which only initalize a replicaset in your running mongo instance. If you dont do that, you dont have a oplog. 

You need this in your docker-compose.yml:

```mongo-init-replica:
  image: mongo:3.2
  command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
  links:
    - mongo:mongo
```

After that, your RC Instance can use the oplog.

**Comment by akmad** [comment]
@TheReal1604 Thanks again for the help! I resolved this by manually starting the mongo-init-replica container. Hopefully that is a viable option that doesn't mess something else up. 

I'm not sure if this is the place for this, but I would suggest updating the docker-compose.yml file or setup instructions to reflect this.

**Comment by TheReal1604** [comment]
@akmad Yes, its absolutely okay to do that. And you need this only on a fresh mongodb to initiate the rs the first time.

Looks fine. :+1: 

@Syirrus Do you need further help?

**Comment by thiesschneider** [comment]
if I try to start the docker-compose the replica is exiting immediately. If I run `docker-compose up -d mongo-init-replica` the database also does not start.
the logs fom the mongo-init-replica container:

```connecting to: mongo/rocketchat
{
	"info" : "try querying local.system.replset to see current configuration",
	"ok" : 0,
	"errmsg" : "already initialized",
	"code" : 23
}```

**Comment by engelgabriel** [comment]
Our `docker-compose.yml` file has been updated and commented for clarity:

https://github.com/RocketChat/Rocket.Chat/blob/1f867246b047c88a1c18eadafe9222e6ca96077f/docker-compose.yml#L35-L36

I'll close this issue now, so please join the conversation at:

https://github.com/RocketChat/Rocket.Chat/issues/5212
