### ISSUE TITLE
Pressing Ctrl+W in the About dialog closes the main window

### ISSUE THREAD

**Issue by rillig-nm** [RocketChat/Rocket.Chat#4893]
Your Rocket.Chat version: 1.3.1

1. Start the Windows client
2. Open the About dialog
3. Press Ctrl+W

I expected the about dialog to be closed, since it is the foreground window.
Instead, the main window is closed, although from the user's point of view it doesn't have the keyboard focus.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. Please report this issue in the Repository for the Windows Client: https://github.com/RocketChat/Rocket.Chat.Electron/issues/355

Cheers
Thomas
