### ISSUE TITLE
Archiving user chats

### ISSUE THREAD

**Issue by akashkaveti** [RocketChat/Rocket.Chat#4895]
Is it possible to archive users chats (individual)?

**Comment by MartinSchoeler** [comment]
@akashkaveti do you mean Direct Messages? You can try hide them.

**Comment by akashkaveti** [comment]
@MartinSchoeler Yeah Direct messages, I want to archive/export the direct messages.

**Comment by graywolf336** [comment]
Duplicate of #3348
