### ISSUE TITLE
Trouble with Force SSL on Ubuntu Snap

### ISSUE THREAD

**Issue by Vortelf** [RocketChat/Rocket.Chat#4896]
Your Rocket.Chat version: 0.46

I for no obvious reason enabled the Force SSL feature and now I cannot connect to the server via any client. Is there any config file which in which I can disable this. I built and installed the 0.46 snap for raspberry.

**Comment by maxlinux2000** [comment]
yes... with ssl enabled I can't login from mobile device to my RC server

**Comment by geekgonecrazy** [comment]
if you get stuck with this use: `rocketchat-server.mongo`  and then `use parties` and finally `db.rocketchat_settings.update({_id: "Force_SSL"}, {$set: {value: false}})`
