### ISSUE TITLE
File Upload not working

### ISSUE THREAD

**Issue by mehdiyahyaoui** [RocketChat/Rocket.Chat#4897]
Your Rocket.Chat version: 0.45.0
Hello we installed 0.45.0 RC on Ubuntu 16 with snap 
File Upload isn't working - file stuck on 0% on the info bar

do you have a workaround
Tested with GridFS and filesystem, removed size and file type restriction 

Thx

**Comment by Nemra1** [comment]
Make sure from extension in upload section /
image/*,audio/*,video/webm*,application/zip,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document
________
And storage type.is gridfs

**Comment by mehdiyahyaoui** [comment]
left extension empty to allow all 
still not working...

**Comment by Nemra1** [comment]
Pm me to help u.. odratop10 # Skype

**Comment by mehdiyahyaoui** [comment]
>Pm me to help u.. odratop10 # Skype
Thx @Nemra1 but sorry our corp policy does not allow skype
you do Team viewer ?

**Comment by bazarnew** [comment]
I also uploaded files does not work site

**Comment by algonza** [comment]
We're running 4.5 and have changed the File System from GridFS to File System. In doing so, we encountered the same no access issue from the Windows client and browsers. By changing the Protected uploaded files from True to False in the Admin section, both UI types prompt to download the file. We are running this internally (LAN) only and for a rather small set of users, so this workaround works for the meanwhile. Docs are not sensitive. However, not having the files protected will prevent adoption from the upper echelon.
Hope the RC folks get this right soon.

**Comment by zmx312502865** [comment]
Do you solve this  problem?

**Comment by gregharvey** [comment]
I'm having exactly this issue on Debian 8.7 - package versions:

```
# nodejs --version
v0.10.29
# npm --version
2.15.9
```

Rocket.Chat version is 0.52.0, avatar uploads using GridFS work just fine, file uploads don't work at all, stop at 0% uploading. Tried FileSystem, GridFS, turned off Protected mode as suggested in some related threads, all to no avail. File upload into a chat and microphone recordings simply do not work. I also don't get any messages in the server syslog or the Rocket.Chat log in the UI (can't find where Rocket.Chat logs on disk, the nodejs log is empty).

Any suggestions / ideas? :-)

**Comment by gregharvey** [comment]
Sorry, disregard, re-posted in *active* thread #4923.

**Comment by AnshD12** [comment]
slingshot/uploadRequest method is not working throwing error
`"The directive rocketchat-uploads does not seem to exist"`

is there any new method to upload file as slingshot has been deprecated

**Comment by scottalanmiller** [comment]
Same issue currently on multiple systems.  Seems normal and universal.  Does anyone have this working?  Both GridFS and filesystem fail the same.

**Comment by drchanas** [comment]
I am using rocketchat-server 0.66.3 snap on Ubuntu. I could not get file uploads to work and Chrome dev console was throwing CORB/Cross Site errors and too many references to localhost URLs. 
So I did the caddy thing:

```
sudo snap run rocketchat-server.initcaddy
pico /var/snap/rocketchat-server/current/Caddyfile
```

Edited it to this

```
http://chat.my.lan
proxy / chat.my.lan:3000 {
  websocket
  transparent
}
```
Where chat.mylan is how you access the server.
and reboot.

And now no more errors and uploads work fine.

**Comment by souhaib22** [comment]
I have the same error,

error : 
```
Aug 22 12:24:23 servername rocketchat: store: 'Uploads' } }
Aug 22 12:24:23 servername rocketchat: #033[34mUploadProxy ➔ debug#033[39m Upload URL: /ufs/GridFS:Uploads/pvcM2TyKRcJBJGxWq?token=Db29aB3B1A&progress=1
Aug 22 12:24:23 servername rocketchat: #033[34mUploadProxy ➔ debug#033[39m Correct instance
Aug 22 12:24:23 servername rocketchat: ufs: cannot write chunk of file "pvcM2TyKRcJBJGxWq" (ENOENT: no such file or directory, open '/tmp/ufs/pvcM2TyKRcJBJGxWq')
```
Solution : 
`mkdir /tmp/ufs/ && chmod -aw /tmp/ufs`
