### ISSUE TITLE
custom Emoj Not work ( invalid file type

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4901]
Your Rocket.Chat version: ( latest)
This happend when im trying to upload new emotion to RC
![2016-11-08_064445](https://cloud.githubusercontent.com/assets/22897987/20127843/cf03b282-a64b-11e6-9e13-7d2bdaeef324.png)
trying .gif .png .jpg all it same 
any idea???

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
