### ISSUE TITLE
Deliver correct file format for generated avatars

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#4904]
Avatars are provided as jpg files: /avatar/testuser.jpg?_dc=0
However, auto generated avatars (with initials like TU) are delivered as svg!
Most browsers do not care about it. To avoid avatar presentation issues, the server should transform to jpg (or png) first. See also #4100 and #3766.
As we are working on a native Qt5 based client, we have no fault tolerance when presenting the image file type and better do not want to patch this on the client side.

Your Rocket.Chat version: 0.41

**Comment by Molle500** [comment]
Aren't they jpg tho? or am i missing something?
![image](https://cloud.githubusercontent.com/assets/17712562/20148388/a67fef68-a6ac-11e6-8847-29420da6f399.png)

**Comment by rasos** [comment]
These are SVGs:
![bildschirmfoto_2016-11-09_20-34-18](https://cloud.githubusercontent.com/assets/485723/20151826/f864b1e2-a6bb-11e6-8a26-8f7448573444.png)
whilst any uploaded avatar photos are JPGs.

**Comment by nanovim** [comment]
Please fix it, it is really annoying.
Or better make the standard avater jpg or png.
The svg seems somehow incompatible with any qt based application.

**Comment by rasos** [comment]
Added $30.- bounty https://www.bountysource.com/issues/39097344-deliver-correct-file-format-for-generated-avatars

**Comment by engelgabriel** [comment]
@rodrigok is changing the server to accept the avater URL without the `.jpg` so

```
/avatar/testuser.jpg?_dc=0
```

will be just 

```
/avatar/testuser?_dc=0
``` 

Can you test you app with our develop branch?
