### ISSUE TITLE
Gif's are not showing up

### ISSUE THREAD

**Issue by Hostile** [RocketChat/Rocket.Chat#4905]
0.45.0 
Gif not showing up, I dont know its my chat or general problem, it used to works fine, youtube links working fine.

It looks like it dosent works in demo too  https://demo.rocket.chat/channel/general

When I type bot gif me it only shows link no gif clip playing.

**Comment by MartinSchoeler** [comment]
@Hostile strange, i tested in demo and everything seems to be in order. Could you send some screenshots?

**Comment by Hostile** [comment]
@MartinSchoeler demo   [https://gyazo.com/04841ac1dd5bbfc661458893f2c1586e](url)

my chat [https://gyazo.com/e98b15e15d816449dc82dd1098ed400d](url)

**Comment by MartinSchoeler** [comment]
@Hostile yes you are right (i was trying with file upload), saw this bug in the demo server but it worked on the latest develop branch version.

**Comment by Hostile** [comment]
yep, it used to works on 0.44.0

0.45.0 not working

**Comment by MartinSchoeler** [comment]
It looks like its working now, if not, please reopen this.Thanks
