### ISSUE TITLE
German Translation on Startup: Load xy -> Lade xy

### ISSUE THREAD

**Issue by mld18** [RocketChat/Rocket.Chat#4906]
Your Rocket.Chat version: 0.45.0

During start-up of the mobile Rocket client it' looking for files on the server. It shows a pop-up to the user saying: "Loading xy" (where xy is the Host-URL of the Rocket server).

The German translation is erroneous: it says "Laden xy" but it supposed to say "Lade xy".

**Comment by rasos** [comment]
This phrase is not available in RC's Lingohub i18 files https://translate.lingohub.com/rocketchat/editor?targetLocale=de&q=Laden&project=rocket-dot-chat

Phrase seems to be provided by Meteor. How do they manage translations?

**Comment by MartinSchoeler** [comment]
This is probably a Meteor translation issue, since this phrase is not on our i18n files. Please reopen this in their repository. Thanks!
