### ISSUE TITLE
Working in Development but not in Production

### ISSUE THREAD

**Issue by mitijain123** [RocketChat/Rocket.Chat#4908]
I had installed in my development machine :
https://github.com/RocketChat/Rocket.Chat#quick-start-for-code-developers
made some changes in packages/rocketchat-ui-login/login/form.html:

and deployed in ubuntu server following:
https://rocket.chat/docs/installation/manual-installation/ubuntu/#manual-install

Now how to deploy my changes made in file packages/rocketchat-ui-login/login/form.html to the server?

I want this to customize the login page html tags.

**Comment by marceloschmidt** [comment]
You have taken two different tutorials for two different audiences. The second tutorial doesn't take into account any modifications to the source code. It gets the latest codes from our repositories. If you need to deploy custom made code, you need to learn how to deploy a meteor application, and that is outside the scope of our GitHub issues. Please follow the tutorials at https://guide.meteor.com/ or ask a question on http://superuser.com/. 
Thanks.

**Comment by mitijain123** [comment]
@marceloschmidt thanks for help, I had followed it and working fine, below is the process i had followed if any one want it:

1. Make the changes in development code that is develop branch
2. Then deploy using the commands below:
```
    # for example if deploying to a Ubuntu linux server:
    npm install --production
    meteor build /path/to/build --architecture os.linux.x86_64
```
replace /path/to/build with your path to build tar.gz file.

3. Then deploy your tar.gz to the server using commands below:

```
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
cd ../..

export ROOT_URL=http://your-host-name.com-as-accessed-from-internet:3000/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3000

node main.js
```
