### ISSUE TITLE
how to Mobile push notifications with new Firebase

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4909]
Your Rocket.Chat version: ( latest)

im trying to setup my owne google cloud bcs https://gateway.rocket.chat/ not send any thing 
im used https://play.google.com/store/apps/details?id=com.konecty.rocket.chat
![2016-11-09_185047](https://cloud.githubusercontent.com/assets/22897987/20147017/e9c1d514-a6ae-11e6-96f1-0a3f66b48a99.png)

for my server so im trying this
> Go to https://console.developers.google.com/ and create a project there.
> Go to API Manager, and enable "Google Cloud Messaging for Android"
> In API Manager, open the "Credentials" tab, click 'New credentials -> API key. In the window that pops up, choose "Server key"
> Fill in the correct IP address from your server and Click "Create"
> Fill in the obtained API key in your rocketchat administrator panel (GCM API Key)
> The GCM Project Number which you also have to fill in on rocketchat can be found on the dashboard of your Google developers project, first block that shows up . (https://console.developers.google.com/home/dashboard, http://i.imgur.com/3DXHEKy.png)
> For iOS you need an apple developer account which I don't have, and don't plan on getting because it costs 99$ per year and so I haven't looked into it much, but maybe this can help: https://github.com/raix/push/blob/v3.x/docs/IOS.md
==========================================
but google direct me to https://console.firebase.google.com/
![2016-11-09_185721](https://cloud.githubusercontent.com/assets/22897987/20146900/67577f5c-a6ae-11e6-8512-67f9366093be.png)

some time when i click Send a test push to my user isaw successfully push but is lie and nothing happend 
so any idea to get push notifications working

**Comment by RichardFoxworthy** [comment]
I've had success with Firebase Cloud Messaging for Android push alerts. 

Set up or migrate a project to Firebase, and go to Settings --> Cloud Messaging in console - https://console.firebase.google.com/project/<your_project>/settings/cloudmessaging

You'll see a 'Project Credentials' card with 'Server Key' and 'Sender ID'. There's actually two versions of Server Key - a legacy version and and updated version.

I used the updated Server Key string in the 'GCM API Key' field in Rocket chat, and the Sender ID in the 'CGM Project Number' field. 

It seems to work

**Comment by Nemra1** [comment]
Can you be more clearly. ..or pls take some print screen for setting from dashboard  to get that work   ... imean explain this way with pics .. im new in Rc @RichardFoxworthy t

**Comment by LinuxWax** [comment]
This issue is still open, and it don't seem to work. Any positive experience is welcome.

**Comment by mskogorev** [comment]
Привет.

Данную проблему решил добавлением в панели администратора в поле  GCM API Key  ключ сервера из firebase > project > settings >  Cloud Messaging > server key

А в поле GCM Project Number добавил "Идентификатор отправителя" 

Все работает, спасибо Richard Foxworthy

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
