### ISSUE TITLE
Click on icon-paper-plane error

### ISSUE THREAD

**Issue by katopz** [RocketChat/Rocket.Chat#491]
Hi guys,

When I click `icon-paper-plane` it throw this error

![screen shot 2558-08-18 at 12 14 31](https://cloud.githubusercontent.com/assets/97060/9322806/dc658640-45a2-11e5-9a4a-492b15b2ca0b.png)

Thanks

**Comment by engelgabriel** [comment]
I think the icon-paper-plane should be delete, it just makes the input box lose focus, what is very annoying on the mobile app.

What do you think @RocketChat/owners ?

**Comment by rodrigok** [comment]
It's good to have an option to send message without require keyboard "return", all message applications have buttons like that.

We can fix this behavior of loose focus.

**Comment by engelgabriel** [comment]
On mobile yes.. on desktop no

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/951c90bac7cbddb0c1072154c79b944d31f9ee3e
