### ISSUE TITLE
URL Parsing in message is incorrect

### ISSUE THREAD

**Issue by tomarra** [RocketChat/Rocket.Chat#4911]
Your Rocket.Chat version: 0.45.0

URL's for internal systems are not being picked up the right way.

Example: http://suus111.w10:8090/display/test/AI

In the example above only "http://suus111.w" get's picked up as a URL.

**Comment by marceloschmidt** [comment]
This is an autolinker issue, for which I have created an issue on their repo. Let's keep an eye there.

**Comment by olafleur** [comment]
@tomarra What do you mean by internal systems?

According to IANA, w10 is not a valid TLD. Here is the full list of valid TLDs (of which some contain numbers, so we still have a bug in the library) : 
http://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by marceloschmidt** [comment]
@olafleur I think he means a custom domain, such as when you set up on your hosts file.

**Comment by tomarra** [comment]
It's a little bit of both @marceloschmidt. We do have some domains that are setup in hosts files but in this case the URL I reported does resolve as a correct URL due to an internal DNS lookup that we have in a corporate network.

I have been following the issue over in the auto linker project and I think the compromise that you guys came up with works for me too. Most of the time the URL that is pasted in is a full copy and paste from the URL bar which would have the http:// so were good :)

**Comment by marceloschmidt** [comment]
https://github.com/gregjacobs/Autolinker.js/issues/180
