### ISSUE TITLE
Reply in direct messages only shows the message id instead the message itself

### ISSUE THREAD

**Issue by sweetkandy** [RocketChat/Rocket.Chat#4914]
Your Rocket.Chat version: 0.45.0

If you use the reply function in a direct message, it only shows the id, not the whole message:
?msg=Lh8p47jup2j7SnX3c) @user Here´s my reply

Happens in browser and windows client

**Comment by MartinSchoeler** [comment]
@sweetkandy hey i couldn't seem to reproduce this bug. Can you give more info on your setup and post some screen shots of the bug?

**Comment by sweetkandy** [comment]
@MartinSchoeler no problem.
platform: Debian 3.16.36-1+deb8u1  x86_64
mongodb version: 3.0.14
rocket.chat is running behind nginx as reverse proxy, users are imported from LDAP (AD). I tried it with client version 1.3.1 and firefox 49.0.2.
Tell me if you need more information.

This is only happening in direct messages, not in public rooms:

![rchat](https://cloud.githubusercontent.com/assets/23373621/20174613/fddfa842-a73e-11e6-8751-58e7c104efa2.png)

**Comment by graywolf336** [comment]
@sweetkandy I just tried it as well on my servers and it is working fine. Can you check for any errors on the client side and the server side?

**Comment by sweetkandy** [comment]
@graywolf336 There was no errors in the log. I will update to the newest version, if the problem still exists I will turn on the debug and will try to get more information.

**Comment by sweetkandy** [comment]
Ok, I found out what the problem is. We´re using spaces and brackets in the usernames in form of: #{givenName} #{sn} (#{sAMAccountName})

It seems that special characters don´t get escaped.
