### ISSUE TITLE
RocketChat client version(1.3.1) crash on windows 10

### ISSUE THREAD

**Issue by nadeemshahzad** [RocketChat/Rocket.Chat#4915]
Your Rocket.Chat version: (1.3.1)
Rocketchat client crashing on windows 10 after logged in 5 to 10  minutes. I am facing this issue frequently and repeated on 3 machines.

**Comment by anthonymasset** [comment]
Same problem for me.
Apparently, the problem only occurs when the app window is minimized.

**Comment by nbrownksu** [comment]
Mine crashes regardless of whether it's minimized or not. Every 5-10 minutes seems accurate

**Comment by shellster** [comment]
We have the same issue with at least one Win10 user.

**Comment by danpospisil** [comment]
Try to use Franz - its much better, stable and it includes Rocket Chat.

**Comment by MartinSchoeler** [comment]
If you still have this issue, please reopen it here https://github.com/RocketChat/Rocket.Chat.Electron Thanks!
