### ISSUE TITLE
Webclient - Copy not possible since 0.45.0

### ISSUE THREAD

**Issue by cbajohr** [RocketChat/Rocket.Chat#4916]
Copying text  (cmd+c) in a webclient chat is not possible anymore since the newest 0.45.0 Version. I guess that behavior is a side effect of the global key event handling changes?

Tested on macOS Sierra with Safari
Your Rocket.Chat version: 0.45.0

**Comment by MartinSchoeler** [comment]
@cbajohr Don't worry, this bug will be fixed in the next release! Thanks for the feedback!
