### ISSUE TITLE
Wrong Custom Emoji Icon

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#4918]
When you add a custom emoji and name it with a name that already exists it shows the wrong icon. For example create a custom emoji called cat and will show the cat icon, but it sends the wright emoji
![selection_008](https://cloud.githubusercontent.com/assets/20868078/20178900/6d72133e-a73a-11e6-962f-6bff98059cfa.png)
![selection_007](https://cloud.githubusercontent.com/assets/20868078/20178901/7061402e-a73a-11e6-9a7c-9a3b7a9ebca2.png)

**Comment by MartinSchoeler** [comment]
Maybe a warning saying the emoji that you are trying to create already exists?

**Comment by nokobon** [comment]
I replaced the emojione gun using custom emoji and it works as expected, it shows up as the custom emoji in the picker and when used in chats.

![image](https://cloud.githubusercontent.com/assets/828413/20182408/4d0c17d8-a727-11e6-9eed-92ac719f1e85.png)

![image](https://cloud.githubusercontent.com/assets/828413/20182418/52f2aaf4-a727-11e6-95c1-2cf1e8b0fdc6.png)

A warning would probably be nice to prevent unexpected emoji replacements.

**Comment by cyclops24** [comment]
Part of #8494

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing, because IMO this has been implemented.

![image](https://user-images.githubusercontent.com/179595/36217558-14ad01ee-11b2-11e8-8af7-25db5668f37f.png)

Cheers
Thomas

**Comment by engelgabriel** [comment]
I thought that it is not implemented

**Comment by TwizzyDizzy** [comment]
But you agree it is, do you? :)

Cheers
Thomas
