### ISSUE TITLE
Feature request: Custom sound notifications per user or user group

### ISSUE THREAD

**Issue by msklywenn** [RocketChat/Rocket.Chat#4924]
The documentation of "Notifications" is quite succinct and I couldn't find the requested feature in the settings, it might be there already ?

In our case, it would be useful to have different sound notifications for users and bots.

**Comment by rasos** [comment]
As of RC 0.56, only those users can upload custom sounds who have the "manage-sounds" permissions. The pool of custom sounds is available for all users.  Any user can choose standard and custom sounds for notifications in their settings.

**Comment by msklywenn** [comment]
My request would be to have something set for the users rather than asking all the users to choose the same sound. They would still be able to customize, the admin would just set the defaults. 

Daniel Borges
Game Programmer
(+33) 6 11 92 32 84
http://manufacture43.com

**Comment by Paulpatou** [comment]
Hi,

I wanted to know if it was now possible to set a specific notification sound when a user posts a message? For example, to differentiate between users and Bots.

Thank you

**Comment by Sx3** [comment]
Do we have a config file to set the default sound for all users at once instead of asking them to change it manually.

**Comment by sampaiodiego** [comment]
we do have custom sounds per server and you can choose custom sounds per room. we don't plan to have custom sounds per user.
