### ISSUE TITLE
record not working in Rocket.Chat Desktop Application

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4925]
Your Rocket.Chat version: ( latest)
Rocket.Chat Native Cross-Platform Desktop Application via Electron.
when click in record button nothing happend just fake button
![2016-11-11_171508](https://cloud.githubusercontent.com/assets/22897987/20220039/a8eb6456-a834-11e6-93b1-c726124a63ae.png)

**Comment by maxlinux2000** [comment]
go in Administration/File Uploar and add "video/webm,audio/wav" to Accepted Media Types.

**Comment by ggazzo** [comment]
@Nemra1 I'm closing that issue because its quite old, we changed a lot and I think its not an issue anymore :)
