### ISSUE TITLE
can't login from android in my RC server

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#4928]
Your Rocket.Chat version: 0.45.0  

I just installed the fresh version of RocketChat from .tgz without docker.
I can login from browser but not with the official android app from playstore, nor cordova app just builded for me.

My server is a digitalocean VPS with regular domain and public IP running at port 80.
The server is very basic: no ssl, no proxy and the protocol is the simple http.

seem that the app is trying to connect to port 443 ...it's wrong?

I've tried too to put the the form "rocket.mydomain.com:80" , but it still failed the connection

here the screenshot (official app)

![xrc-bug](https://cloud.githubusercontent.com/assets/5683921/20237620/2854b0e6-a8d8-11e6-80eb-a5dc633a2271.png)

**Comment by Nemra1** [comment]
shutdown rc server and change http port  try to change 443 to 190 for example

**Comment by rauhmaru** [comment]
Try with valid certificate (certbot can help you)

Em 13/11/2016 13:13, "Ahmed El Sheikh" <notifications@github.com> escreveu:

**Comment by Nemra1** [comment]
Im also trying to setup in port 80...but not workin

**Comment by maxlinux2000** [comment]
ok, I solved it installing the nginx proxy server and certificate.

I you need it I posted a script for automactly install nginx and get the certificates for free, here:
https://github.com/RocketChat/Rocket.Chat.Cordova/issues/151
