### ISSUE TITLE
Anonymous server statistics collector (with opt-out option)

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#493]
It could be very useful for the dev team to know:
- [x] Versions of the instances
- [x] Registered users on each instance
- [x] Avg online users on each instance
- [x] Max online users on each instance
- [x] Avg room/channel members count
- [x] Max room/channel members count
- [x] Total messages
- [x] OS Version, Hardware
- [x] Unique deployment ID

**Comment by rodrigok** [comment]
We need another project like the MMS is for MongoDB.

In the installation time we can ask for all admin users to allow to connect with our server so we can create one key and auto register in this new system to start monitoring some things.

Will be useful if we can offer some advantage to admins, like statistics, new version warnings, etc...

**Comment by engelgabriel** [comment]
Sounds good. Any name suggestions for the new project? Os should we build this inside the Website repo for now?

**Comment by rodrigok** [comment]
My suggestions:
* RMS
* Rocket.Monitor
* Rocket.Cloud
* Rocket.Analytics (this name can limit the features)
* Apollo ( :smile: )
* Houston ( :smile_cat: )

**Comment by engelgabriel** [comment]
Should we have smaller projects for: monitoring, plugins marketplace, announcements, communities directory, etc.. Or on single project as Mission Control?

**Comment by rodrigok** [comment]
I really don't know, but I know that this issue is in the wrong milestone! We can't do this until 1.0.

**Comment by engelgabriel** [comment]
Hehehe.. the initial idea was just to have a very simple collector on our websiteand an option enable true/false on rocket.chat servers to send data every hour.

**Comment by Sing-Li** [comment]
I vote for all-in-one 'mission control' style, and if one area becomes too big/complex, can spin it off later.
Should we also throw in admin / config that either doesn't make sense, or too dangerous, to be included in the core?  This can be an incentive for admin to allow their install phone home - at least from time to time  :smiley:

**Comment by engelgabriel** [comment]
Agreed! Lets do it! Our https://rocket.chat is already using https://github.com/RocketChat/Rocket.Chat.Website

**Comment by engelgabriel** [comment]
Will close this issue and create another for the enhancements 
https://github.com/RocketChat/Rocket.Chat/issues/726
