### ISSUE TITLE
Only embed video after thumbnail was clicked

### ISSUE THREAD

**Issue by b2ag** [RocketChat/Rocket.Chat#4931]
Hi,

I have a channel which is full of youtube links and I don't want to mess it up my browser memory and kill performance (especially while scrolling). So I would like to have a feature, where thumbnails are shown for youtube links, but player is only embedded after I clicked the thumbnail. Would help a lot with usability over here.

Br,
b2ag

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
