### ISSUE TITLE
[Help] Mute all guest user by default

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#4932]
Your Rocket.Chat version: 0.45.0
Hello,

Anyone can help me to implement a way to mute all guest user by default in all channel ?

Thank you

**Comment by akachapati** [comment]
You can create a readonly room that mutes all users expect those that have the following permissions enabled: post-readonly

**Comment by sampaiodiego** [comment]
guest users cannot send messages already if that is what you asked for.
