### ISSUE TITLE
Add settings to hide "muted by" messages

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#4933]
Currently, the following messages can be hidden using settings.  See attached pix.

![screen shot 2016-11-13 at 8 09 10 pm](https://cloud.githubusercontent.com/assets/122633/20250504/5f5a388a-a9dd-11e6-95da-1604824d79ca.png)

Add the ability to hide the "muted by" messages. 

Often, when combatting users abusing or attacking a popular public server, anonymity is a key advantage.

**Comment by IQ2022** [comment]
where is this located??
