### ISSUE TITLE
import slack error

### ISSUE THREAD

**Issue by damody** [RocketChat/Rocket.Chat#4934]
Your Rocket.Chat version: 0.45.0

`Exception in defer callback: Error: Invalid user [error-invalid-user]   at [object Object].Meteor.methods.createChannel (/snap/rocketchat-server/143/programs/server/packages/rocketchat_lib.js:8121:13)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/143/programs/server/packages/rocketchat_lib.js:1014:26)   at maybeAuditArgumentChecks (/snap/rocketchat-server/143/programs/server/packages/ddp-server.js:2107:12)   at /snap/rocketchat-server/143/programs/server/packages/ddp-server.js:2026:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Server.apply (/snap/rocketchat-server/143/programs/server/packages/ddp-server.js:2025:47)   at Server.call (/snap/rocketchat-server/143/programs/server/packages/ddp-server.js:1959:19)   at [object Object].<anonymous> (/snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:381:39)   at packages/dispatch_run-as-user.js:211:14   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)   at [object Object].<anonymous> (/snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:379:26)   at packages/dispatch_run-as-user.js:211:14   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)   at /snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:339:29   at /snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:405:15   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at packages/meteor.js:445:45   at runWithEnvironment (packages/meteor.js:1176:24)  `

**Comment by marceloschmidt** [comment]
@damody can you provide more info? 

1. Is this a brand new install or one that you have used for some time now? 
2. Have you created any user other than the administrator before attempting to import from slack?
3. Have you attempted to run the import more than once?
4. Has anything been imported?

Thanks

**Comment by graywolf336** [comment]
This error comes from a bug in the Slack importer. If you unchecked a user from being imported and that user had created a channel that is being imported, we would try to create the channel with that user even though that user doesn't exist. I've got it fixed here locally and will check it in.

**Comment by damody** [comment]
[Slack export Nov 15 2016.zip](https://github.com/RocketChat/Rocket.Chat/files/593622/Slack.export.Nov.15.2016.zip)
I create new rocket.server  and import all, then error

**Comment by graywolf336** [comment]
@damody You will need to post the error that is happening, otherwise we can't help you.

**Comment by damody** [comment]
I follow this hint
https://rocket.chat/docs/administrator-guides/import/slack/

   1 Go to https://[your_app].slack.com/services/export
   2 Click on Start Export
   3 Wait until your download is ready and download it (it will be a .zip file)
   4 Go to https://[your_rocketchat]/admin/import/prepare/slack
   5 Choose your downloaded .zip file and wait until Rocket.Chat can read it (it can take a few minutes, depending on the size of your Slack export)
   6  Deselect any items you don’t want to import
   7 At the top of the page, click on Start Importing
and get "The importer was not defined correctly. it is missing the Import class"
and I find error from log
`Exception in defer callback: Error: Invalid user [error-invalid-user] at [object Object].Meteor.methods.createChannel (/snap/rocketchat-server/143/programs/server/packages/rocketchat_lib.js:8121:13) at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/143/programs/server/packages/rocketchat_lib.js:1014:26) at maybeAuditArgumentChecks (/snap/rocketchat-server/143/programs/server/packages/ddp-server.js:2107:12) at /snap/rocketchat-server/143/programs/server/packages/ddp-server.js:2026:20 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at Server.apply (/snap/rocketchat-server/143/programs/server/packages/ddp-server.js:2025:47) at Server.call (/snap/rocketchat-server/143/programs/server/packages/ddp-server.js:1959:19) at [object Object].<anonymous> (/snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:381:39) at packages/dispatch_run-as-user.js:211:14 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33) at [object Object].<anonymous> (/snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:379:26) at packages/dispatch_run-as-user.js:211:14 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33) at /snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:339:29 at /snap/rocketchat-server/143/programs/server/packages/rocketchat_importer-slack.js:405:15 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at packages/meteor.js:445:45 at runWithEnvironment (packages/meteor.js:1176:24)`
