### ISSUE TITLE
Docker container.ERROR: Service 'web' failed to build: lstat requirements.txt: no such file or directory

### ISSUE THREAD

**Issue by gibbsville** [RocketChat/Rocket.Chat#4936]
hi can somebody please help me overcome this issue when I am trying to create a new container for Django with docker compose.
![image](https://cloud.githubusercontent.com/assets/23453496/20265548/f9d318de-aa71-11e6-9a02-f405875e6122.png)

**Comment by gibbsville** [comment]
btw this is using ubuntu trust 14.1

**Comment by lucasvanhalst** [comment]
I don't think you posted this in the correct repository
