### ISSUE TITLE
Mobile Layout 

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#4937]
Your Rocket.Chat version: 0.46.0-develop

Please improve the layout for smartphones.

We need something like ?layout=embedded
https://github.com/RocketChat/Rocket.Chat/pull/4319

but with working sides menus 

![x-rc2](https://cloud.githubusercontent.com/assets/5683921/20268136/1f02f64a-aa7e-11e6-98af-ad1ac84f79d0.jpg)

Note that the clip and the camera was in the header, near a second menu button that open the right side menu.

... the ideal is to create a  ?layout=mobile

where are the documentation how to do it?

**Comment by Molle500** [comment]
@maxlinux2000 #2970

**Comment by maxlinux2000** [comment]
You are right. Closing
