### ISSUE TITLE
Conference permission problem in Cordova r.c.

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#4939]
Your Rocket.Chat version: 0.45.0 and 0.46.0. development

When I try to join in video conference from r.c.cordova, appears  this message:

![screenshot_20161114-183642](https://cloud.githubusercontent.com/assets/5683921/20276610/41e48f1a-aa9d-11e6-9150-84423ba48f19.png)

But in AndroidManifest.xml are good with permission:record... Where is the problem?

**Comment by Nemra1** [comment]
Im report about that since v44 to now no body answer  me

**Comment by maxlinux2000** [comment]
I think that the problem come because Android do no accept to share the mic and camera with the external JavaScript of the conference

**Comment by ggazzo** [comment]
I'm closing because we dont offer support for cordova anymore =/
