### ISSUE TITLE
Need global cross platforms install counter

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#494]
Devs love to be on the trending, winning team.

We need to capture and maintain a running count of client installs/user registrations across all mobile, desktop, web, cloud, and alternative emerging platforms ... over the Internet, Intranets, and private Internet. 

Prominently feature the exponential growth on our home page.
##

**Comment by marceloschmidt** [comment]
Isn't this a duplicate of #493?

**Comment by Sing-Li** [comment]
@marceloschmidt ... Inspired by #493 :smile:   I think we get client install stats from various web stores. And that is not part of #493.  This counter is a PR # ... and not necessarily an accurate engineering number.

**Comment by marceloschmidt** [comment]
Nice! Let it be then :)

**Comment by louisemessage** [comment]
Closing this issue as there hasn't been activity on it in over two years. We're trying to clear up our backlog of issues :)
