### ISSUE TITLE
Support/show avatars for channel groups

### ISSUE THREAD

**Issue by a-abella** [RocketChat/Rocket.Chat#4943]
Particularly on mobile where the channel menu is hidden, an easy way to visually distinguish between channels would be colorized channel headers. They could be generated from a pre-approved pool of "safe" colors, like the colors on username-generated avatars, or owner/admin-selectable (perhaps also from a selection of "safe" colors). This would help reduce the frequency of events such as posting to the wrong channel (which in itself is a security risk).

**Comment by sampaiodiego** [comment]
we'll have avatars for channels as well that will help to solve this issue.

**Comment by esindic** [comment]
Pardon my limited experience around using Github.  I was very excited to see this feature implemented.  But it doesn't appear to have made it on the .70 release and I can't find an update on it in any of the project roadmaps.  What is the status of this feature?

**Comment by esindic** [comment]
Great. Thank you!

**Comment by ankar84** [comment]
Hi, @sampaiodiego!
We have a Rocket.Chat server version **2.1.0** but still did not find a way to change the avatar for a group or channel.
When that feature will be implemented?
