### ISSUE TITLE
Determine the environment

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#4948]
Your Rocket.Chat version: 0.46.0

Can we determine where the app we are using is in **Browser** or in **Desktop**?

Since i want the **My Account** section to be visible only in Desktop App but not in Browser for the same Person.

Thank you in advance.

**Comment by graywolf336** [comment]
You could check the `navigator.userAgent` since the desktop client is something like `Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/1.2.0-rc.1 Chrome/47.0.2526.110 Electron/0.36.10 Safari/537.36`

**Comment by ramanamatya** [comment]
@graywolf336 Is there any way to **add/remove a stylesheet** file based on **userAgent** ?

**Comment by graywolf336** [comment]
@ramanamatya Sorry for the delayed response, I thought I had responded. You could write some javascript to do it, yes.
