### ISSUE TITLE
All channels disappear after drop Admin status

### ISSUE THREAD

**Issue by Plup-io** [RocketChat/Rocket.Chat#4949]
Your Rocket.Chat version: 0.43.0

My user can't see any channel if I drop the Admin privileges. 
Promoting the user Admin agin solve the problem. 

This user was the first user connected to the Rocket.chat.

**Comment by MartinSchoeler** [comment]
Hey @Tymk That happens because the first user registered receives only the 'admin' role, so if you remove it this user wont have any role thus not having the permission to see rooms, you can easily fix this by giving the user a 'user' role.

**Comment by MartinSchoeler** [comment]
Maybe the first user should receive the 'user' role as well?

**Comment by Tymk** [comment]
Thanks for the quick answer. 

I agree with this proposal. It might be a rare use case but for a first use of Rocket.chat, this behavior appears like a bug whereas it's normal. So, adding the `user` role as well would avoid this wrong perception.
