### ISSUE TITLE
Can’t update snap

### ISSUE THREAD

**Issue by Har01d** [RocketChat/Rocket.Chat#4951]
Your Rocket.Chat version: 0.43

```
root@root:~# snap list
Name               Version  Rev  Developer  Notes
rocketchat-server  0.43.0   88              -
ubuntu-core        16.04.1  423  canonical  -
root@root:~# snap refresh rocketchat-server
error: cannot refresh "rocketchat-server": cannot refresh local snap "rocketchat-server"
```

It seems like there's a bug with Snaps. Auto-update also doesn't work.

**Comment by geekgonecrazy** [comment]
@Har01d Do you happen to be on an arm device like the Raspberry pi?

**Comment by Har01d** [comment]
@geekgonecrazy, no, I use a Linode VPS.
Here’s a similar issue: #4752

**Comment by geekgonecrazy** [comment]
@Har01d did you actually disable and re-enable the snap?  If so then yes that would be the same issue.

**Comment by Har01d** [comment]
@geekgonecrazy, yep, I did.

**Comment by geekgonecrazy** [comment]
@Har01d alright please refer to that issue, we'll see if we can figure out a way to get you guys past this until they fix the issue with snapd.
