### ISSUE TITLE
Rest API feature additions

### ISSUE THREAD

**Issue by 116davinder** [RocketChat/Rocket.Chat#4953]
My Rocket.Chat version/api version
```
  "status": "success",
  "versions": {
    "api": "0.1",
    "rocketchat": "0.5"

can you guys extend the rest-api for private group/channel  creation ,
user addition to any private group/channel and creating integration webhooks .
i don`t wanna do from GUI.

**Comment by graywolf336** [comment]
The rest api has private group creation https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/routes.coffee#L273 and it includes setting the initial users of the channel there is also a pull request open to manage integrations https://github.com/RocketChat/Rocket.Chat/pull/4719
