### ISSUE TITLE
How to override the toastr options

### ISSUE THREAD

**Issue by mitijain123** [RocketChat/Rocket.Chat#4954]
Your Rocket.Chat version: 0.46.0-develop

I found chrismbeckett_toastr.js present in `.meteor/local/build/programs/web.browser/packages/chrismbeckett_toastr.js `
I think we should not edit this file directly.

So, How can I override the toastr options for example adding class using toastClass and increasing the toastr duration.

**Comment by MartinSchoeler** [comment]
Closing this issue due lack of activity. 
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
