### ISSUE TITLE
Future : Add option to ignore users

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4956]
Your Rocket.Chat version: (latest)
Hope to add Add option to user ignore user for more privace
Rocket.Chat Need User privacy option to make control about others for example
User1 >ignored User2
User1 > Report Admin About User2
Admin cant ignored from less levels ..i mean owner,moderator, cant ignored admin
Users Can Enable / Disable Private Chat..
User Can Choose Font option. .like color,bold,italic, Kind Font like important, arial,etc..to add to user text input. .
User Can linked All social account without change default account..

**Comment by MartinSchoeler** [comment]
@Nemra1 Unfortunately there is none, but we are accepting Pull Requests :smile:

**Comment by Nemra1** [comment]
thx martin im change the title now to Future Post

**Comment by Hudell** [comment]
You can block direct messages from users by opening a DM window with them, clicking on the "User Info" button and then on the "Block User" option.

**Comment by marceloschmidt** [comment]
Handled by #9785
