### ISSUE TITLE
Rocket Cloud instance lockout due to misconfiguration

### ISSUE THREAD

**Issue by viniciusrtf** [RocketChat/Rocket.Chat#4960]
Your Rocket.Chat version: 0.45.0

With mixed feelings of embarrassment and apprehension, I'm locked out of Rocket Chat instance on Rocket Cloud after trying some different Iframe login configurations.

In my defense I can say that user session is NOT holding for 90 days as configured. User session is actually expiring constantly after a few minutes. So I kept my admin user logged in, then I performed tests only in anonymous tabs, but that didn't help and I ended up locked out anyway.

Since this is a Rocket Cloud instance, I don't have access to MongoDB, so I can't undo the misconfiguration directly on database.

For reasons beyond my control I can't disclosure the URL here, so I'll send that by email and hope that you guys can do something for me.

**Comment by geekgonecrazy** [comment]
@viniciusrtf closing here.  We'll handle follow up on this one via email Thanks!

**Comment by marceloschmidt** [comment]
If you ever find yourself locked out again, you can login via REST and reset your iframe settings (or whatever settings).

Login is explained [here](https://rocket.chat/docs/developer-guides/rest-api/#logon) and then you can run the following snippet (which will disable iframe login on localhost:3000 -- change accordingly):

```
curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/settings/Accounts_iframe_enabled \
     -d '{ "value": false }'
```

**Comment by viniciusrtf** [comment]
Thanks a lot guys, you're awesome.
