### ISSUE TITLE
Proxy for not encrypted links previews

### ISSUE THREAD

**Issue by maciej-c** [RocketChat/Rocket.Chat#4963]
I believe that rocket.chat need solution to deal with not encrypted links causing mixed content warnings. SSL labs says: "We tend to talk a lot about other aspects of SSL/TLS, but mixed content is arguably the easiest way to completely mess up your web site encryption."

The solution suggested by community on official rocket.chat #support channel is to implement proxy in rocket.chat itself, for encrypting content on https enabled rocket.chat servers, when origin resource is insecure.

**Comment by Koopzington** [comment]
Duplicate of #971?

**Comment by geekgonecrazy** [comment]
Duplicate of #971
