### ISSUE TITLE
[Cordova] Play sound don't works in iOS

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#497]
* https://github.com/apache/cordova-plugin-media
* http://stackoverflow.com/questions/22515699/play-sound-on-phonegap-app-for-android

**Comment by maxlinux2000** [comment]
same error in android. 
Seem that cordova-plugin-media can't select the correct audio device.

**Comment by geekgonecrazy** [comment]
Not sure if this issue is still happening, but i've created an issue on the cordova project to track it. https://github.com/RocketChat/Rocket.Chat.Cordova/issues/107
