### ISSUE TITLE
Snap: Ability to set ROOT_URL

### ISSUE THREAD

**Issue by allytech** [RocketChat/Rocket.Chat#4971]
Your Rocket.Chat version: 0.45.0

This may be just something I am not doing correctly.  I am testing snaps on ubuntu 16.04LTS.

When setting up a Nginx reverse proxy with a valid cert the mobile clients will not connect to the server anymore.  They hang at a connecting screen.  If you use the web client you will get a popup error saying that you have a certificate for https://chat.domain.com but you are accessing https://10.10.1.5 and it waits on a confirmation that it is ok to connect.  The ROOT_URL in the snap is set to localhost and I did not know if there was a clever way to have that set during install or after without messing up the snap too much.  Not sure if this is a feature, bug or support issue.  Thanks again, the snap option is very cool.

**Comment by exactt** [comment]
Can you still login using the non-HTTP URL? Have you set the ROOT_URL there?

"Note: You must use the outside https address for the value at ROOT_URL in [[Section 3|Deploy-Rocket.Chat-without-docker#3-download-rocketchat]] above. This includes the “https://“ and leave off the port number. So instead of ROOT_URL=http://localhost:3000 use something like https://your_hostname.com"
Source: https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy

**Comment by allytech** [comment]
Thanks for your reply.  Yes the HTTPS interface and the desktop client work great.  This is a SNAP on Ubuntu so I am looking for a clever way to set the ROOT_URL for the snap.  I cannot find an easy way to do this during the install.  After the install it is read only and you have to jump through hoops to change it and then an update wipes it all away.  The reverse proxy works great and when you first login using the dektop app you get a warning that you are connecting to https://ip instead of https://name and you click ok.  The iOS app will not bring up a box to say that is okay so you cannot use the iOS app at all.  The web app on the phone does work though.  If I could manipulate the ROOT_URL during the snap install that would solve all the issues.

**Comment by ge-ku** [comment]
I'd also love to see this feature. Here's how it [works in Wekan](https://github.com/wekan/wekan-snap/wiki/Install#url-settings) (also Meteor based app): `sudo snap set wekan root-url="https://example.com/wekan"`.
