### ISSUE TITLE
Set the color (and background) of a message

### ISSUE THREAD

**Issue by birchcode** [RocketChat/Rocket.Chat#4975]
Your Rocket.Chat version: 0.45.0

We are migrating from Hipchat and we have used that to post a lot of server statuses into a channel. Things like errors, warnings etc, and we color code them. Hipchats implementation is a bit limiting in that they only give you a couple of lame colors to choos efrom.

At the moment a message's color in Rocket.chat can be defined as any color in the webhook's payload which is awesome, and it puts a little colored thing on the left side of the message, but at a glance, it doesn't really stand out.

![green-status](https://cloud.githubusercontent.com/assets/1013599/20422616/29600080-ad74-11e6-898a-25d7515430ae.jpg)

It would be great if message had a switch so that it would highlight a background color in the attachment part of the payload, e.g.:

    {
        "username":"rocket.dog",
        "attachments":[
        { 
            "text": 'some message', 
            "color": '#af2a2b',
            "highlight-background-color": true
        }]
    }

If `highlight-background-color` is true or something to that affect, then it could use the color that is set with a light opacity.

![green-status-bg](https://cloud.githubusercontent.com/assets/1013599/20422654/5a09313e-ad74-11e6-8961-1f612ead9289.jpg)

I think this would help a lot for using rocket.chat to parse through logs quickly and easily and create better demarcation of messages. It could also be used to give extra emphasis to messages that need to be highlighted.

**Comment by Frankstar** [comment]
absolutley love this!
Also we could use this to highlight/background own messages for a better readability

**Comment by danielo926** [comment]
good idea!

**Comment by garychapman** [comment]
Building on what @Frankstar suggested, users could set their own text & background colours.

There could then be a system-wide switch to determine whether all other users see these colours (which could result in public rooms turning into a rainbow nightmare), or users can only see their own colours (which would allow them to see their own messages amongst all the noise).

**Comment by thiagosanchz** [comment]
This is a great idea but we have 2 problems to resolve:
If we use it is like a "bubble", and we don't use background for any kind of message component.
We have themes for mobile apps, and the message background impacts on the themes too. 
We working to differentiate the simple text to the bots or another kind of messages and we'll consider this idea to the future. Thanks.
