### ISSUE TITLE
Sort private messages chronological

### ISSUE THREAD

**Issue by gempir** [RocketChat/Rocket.Chat#4976]
Your Rocket.Chat version: 1.3.1

It would be nice if I could sort my private messages chronological so that people that I talk frequently to are always at the top of the list.

We have a lot of users in our rocketchat and if you even sent them one message they will show up in that list. So it becomes a scrolling nightmare if someone frequent is further down.

**Comment by MartinSchoeler** [comment]
duplicate of #4377
