### ISSUE TITLE
[Feature] Option to hide the typing status for other users

### ISSUE THREAD

**Issue by serpentes-me** [RocketChat/Rocket.Chat#4977]
Hi there,

it would be very nice if I have an option via "My Account->Preferences->Messages" to hide the "typing status" for other users.
![image](https://cloud.githubusercontent.com/assets/23552876/20428246/4ce6ae8c-ad88-11e6-8873-b5d848a3384a.png)

**Comment by marceloschmidt** [comment]
To hide your own typing status, or to hide the information that someone is typing?

**Comment by serpentes-me** [comment]
What I mean was to hide my own typing status for other users, but your idea would be also a nice feature.
I think both options would be a benefit.

**Comment by dopykuh** [comment]
👍

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
