### ISSUE TITLE
Deleting an unactivated user via the API causes an error

### ISSUE THREAD

**Issue by JamieH** [RocketChat/Rocket.Chat#4982]
Your Rocket.Chat version: 0.45

When deleting a user via the API `api/v1/users.delete` it'll throw an error if the user hasn't been activated: `Invalid user [error-invalid-user]`  but it does actually delete the user 😂

Note: I haven't actually tried deleting an activated user so it might just be that the API never returns successful

**Comment by viniciusrtf** [comment]
I'm also affected.

**Comment by jaredhilton** [comment]
I'm on v0.51 (NodeJS v4.6.2). Trying to reproduce with all of the various roles in both activated and deactivated statuses and am not having this issue. Can either of you confirm whether or not you are still experiencing this issue?

**Comment by marceloschmidt** [comment]
@JamieH could you please retry? I would try it myself, but what do you mean by unactivated user? Is your server setup with "Manually approve new users" set to true? Or do you mean the user has not verified their e-mail? Anything else? :) Thanks

**Comment by JamieH** [comment]
"Manually approve new users" is set to true

**Comment by marceloschmidt** [comment]
@JamieH if you can, please try on a newer version. I have tested it with different settings and they are all working for me. I'll close this issue until further notice. Thanks!
