### ISSUE TITLE
Page Slider mobile - Simple proposal of interface improvement and usability 

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#4984]
Your Rocket.Chat version: 0.46.0 develop

It is about adding a simple "ionic like, page slider" where Rocket.chat occupies a page, and there are 2 or three more, where the user through Admin/Layout, can add what hi want, such as a News portal or a Search engine or his YouTube channel, all within an iframe (one per page).

![slidebox](https://cloud.githubusercontent.com/assets/5683921/20454732/c772ab08-ae49-11e6-8c16-ded72385b70f.gif)

http://ionicframework.com/docs/api/directive/ionSlides/
or here:
http://ionicframework.com/docs/api/directive/ionSlideBox/

the code to add is simple and you can use the method that you prefer, like for example:
https://github.com/richsilv/meteor-page-swiper

tnx
MaX

**Comment by Nemra1** [comment]
Nice Idea

**Comment by ggazzo** [comment]
sorry @maxlinux2000 but we dont think this feature will be implemented by us... we have native apps now, and its not worth it to spend time. but feel free to implement by yourself, any question just ask :)
