### ISSUE TITLE
Windows Server 2012 R2 Installation

### ISSUE THREAD

**Issue by ahmadfrompk** [RocketChat/Rocket.Chat#4986]
I am trying to install Rocket Chat 0.34 on Windows Server 2012 R2.

I have followed the document and reinstall Visual studio/Win SDK many times. But still it is giving me an error that C++11 Compiler is required for npm-bcrypt.

I have update fiber: 1.0.10
and npm-bcrypt: 0.8.5

I have also tried to install it with MS Build 2015 and Win SDK 8 but it has same compiler issue.

**Comment by tntobias** [comment]
I've found the CAS package causes this issue when trying to build on Windows. I personally don't have a need for it so I've removed it as a dependency and deleted it from the packages directory.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
