### ISSUE TITLE
LDAP_disabled

### ISSUE THREAD

**Issue by delatbabel** [RocketChat/Rocket.Chat#4990]
Your Rocket.Chat version: 0.45

We are trying to get a rocket.chat installation working on the local network, however we are unable to get to the point where AD/LDAP integration works or can even be tested.

I have set up all of the LDAP parameters under /admin/LDAP -- host, port, domain base, domain search user & password, etc.

I have tested the user account that I have set up for domain search user from the command line on the rocket.chat server using ldapsearch from OpenLDAP and it works fine.

I have enabled LDAP in the configuration and see this:

![screenshot_20161121_162355](https://cloud.githubusercontent.com/assets/2335362/20477641/1e5100d0-b009-11e6-80d8-39c5ca43ef5f.png)

I have saved the configuration, restarted the server, etc, etc.  Everything that I can think of.

However when I go to the bottom of the /admin/LDAP page and click the **TEST CONNECTION** button I see this:

![screenshot_20161121_162816](https://cloud.githubusercontent.com/assets/2335362/20477672/44567940-b009-11e6-86aa-660a939aeeff.png)

I have looked through the source code, I admit that I'm not the strongest JS programmer about, but I can see a few instances of this error about in code blocks that look like this:

```
if (RocketChat.settings.get('LDAP_Enable') !== true) {                                                              // 14
    throw new Meteor.Error('LDAP_disabled');                                                                           // 15
}
```

I see a few old configuration guides about setting this LDAP_Enable configuration variable but I can't see where in the code this variable gets set.  Surely setting the **Enable** parameter on the /admin/LDAP screen should set this?  If not then perhaps LDAP is disabled somewhere in the core but I can't see anything in the admin guide as to enabling it -- do I have to hack something in the source code or a config file to get it enabled?

**Comment by marceloschmidt** [comment]
Sorry about that @delatbabel . Could you please test disabling LDAP (save Enabled to false) and then re-enabling it? If that doesn't work, after you enable it, could you please restart your server and test it again? Thank you.

**Comment by delatbabel** [comment]
Yes, I have tried all of that.  No effect.

Is there somewhere else I can set Enabled to be true?

Is the setting stored in Mongo somewhere where I can fetch it or debug it or similar?

**Comment by marceloschmidt** [comment]
Yes, you could go to your `rocketchat_settings` collection.
`db.getCollection('rocketchat_settings').find({_id: 'LDAP_Enable'})` 
And check the `value` property.

**Comment by delatbabel** [comment]
OK -- excuse my MongoDB ignorance but how do I get to the point where I have a command line that will allow me to enter the above command?

**Comment by marceloschmidt** [comment]
That depends on how you're running your rocket.chat project. If you are running it with meteor, then you'd have to fire a new terminal and type `meteor mongo`. If you are running with docker-compose then you'd have to go inside the mongo container and type `mongo`. So it depends... how are you running Rocket.Chat?

**Comment by delatbabel** [comment]
Thanks for your help so far, it's much appreciated.

We installed Rocket Chat on CentOS 7 using these instructions: https://rocket.chat/docs/installation/manual-installation/centos/

I can't find a "meteor" command.  I can find a "mongo" command and I get this output:

```
[root@rocketchat Rocket.Chat]# mongo
MongoDB shell version: 2.6.12
connecting to: test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
Server has startup warnings: 
2016-11-18T17:15:16.785+0700 [initandlisten] 
2016-11-18T17:15:16.785+0700 [initandlisten] ** WARNING: Readahead for /var/lib/mongo is set to 4096KB
2016-11-18T17:15:16.785+0700 [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
2016-11-18T17:15:16.785+0700 [initandlisten] **          http://dochub.mongodb.org/core/readahead
> db.getCollection('rocketchat_settings').find({_id: 'LDAP_Enable'})
> 
```

(i.e. no output to the db.getCollection.find method).

**Comment by delatbabel** [comment]
This has now worked fine on a clean Rocket.chat installation
