### ISSUE TITLE
Users Lose Rights to all channels

### ISSUE THREAD

**Issue by lhaig** [RocketChat/Rocket.Chat#4991]
Your Rocket.Chat version: 0.45

I have an issue where several users have lost access to all the channels in the list even the general one.

It happens randomly with some users who use the cloud. Some of them even if I create the users they login once and then lose access to the channels.

Is there a way for me to remedy this so that I don't have to delete and recreate the users?

**Comment by marceloschmidt** [comment]
Before they lost access, did you change any roles or permissions? 
Did you manually add or remove roles for any other user? 
I'm trying to figure out how to reproduce the error. 
Thanks.

**Comment by lhaig** [comment]
Hi Sorry,

No I have not changed any roles or permissions on any of them.
It seems that it happens perhaps when they set the passwords?
We don't allow registration we send out a link.
So they have to set the password when they create their passwords

I cloud not provide a better replication scenario sorry.

I will see if I can use mongo to find the users with null roles

**Comment by marceloschmidt** [comment]
Cool, I'll test with what you mentioned above.

**Comment by lhaig** [comment]
So I have confirmed that there are half the users who have "roles" : [ null ],

**Comment by marceloschmidt** [comment]
Do you manually register your users, or is your server configured as "Secret URL" registration? 
If you manually register them, what's the role you select?

![image](https://cloud.githubusercontent.com/assets/1986378/20481906/c2140cdc-afd0-11e6-98c3-c534dfef7b95.png)

**Comment by lhaig** [comment]
Apologies for the delay.

The users are sent a secret URL and they register themselves

Regards

Lance

On 21 Nov 2016 12:56 pm, "Marcelo Schmidt" <notifications@github.com> wrote:

Do you manually register your users, or is your server configured as
"Secret URL" registration?
If you manually register them, what's the role you select?

[image: image]
<https://cloud.githubusercontent.com/assets/1986378/20481906/c2140cdc-afd0-11e6-98c3-c534dfef7b95.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RocketChat/Rocket.Chat/issues/4991#issuecomment-261917932>,
or mute the thread

**Comment by marceloschmidt** [comment]
I can't reproduce the error :( 
Do you have a step by step procedure to reproduce it? Thanks

**Comment by lhaig** [comment]
Hi Marchello,

I have not seen any new issues since when I reported this.

I will see if I can get some information from them as to the circumstances
when the login failed.

Regards
Lance
