### ISSUE TITLE
Link previews doesn't update when the message is edited and link is removed

### ISSUE THREAD

**Issue by lashae** [RocketChat/Rocket.Chat#4993]
We have been using Rocket.chat as a deployed service on "Rocket.Chat Deploy" servers with the version 0.45.0.

*Use Case 1 (No bug)*
1. Create a message with text: `Hello it is http://www.google.com and http://www.yahoo.com` and send it.
2. As exprected Google and Yahoo previews are shown.
3. Edit the message and remove Google link, make it: `Hello it is http://www.yahoo.com` and send it.
4. As expected Google preview is removed however Yahoo preview is kept; which is OK!

*Use Case 2 (bug)*
1. Create a message with text: `Hello it is http://www.amazon.com` and send it.
2. As exprected Amazon preview is shown.
3. Edit the message and remove Amazon link, make it: `Hello it is nobody!` and send it.
5. Google preview is NOT removed although it's link is removed!

**Comment by ondrejtichacek** [comment]
Just for a reference -this is still broken in 0.59.3.

**Comment by maxsdw** [comment]
@karlprieb I have a fix for this if you want to try it:

In: Rocket.Chat/packages/rocketchat-lib/server/functions/updateMessage.js

Change this:

`if (urls) {
	message.urls = urls.map((url) => { return { url: url }; });
}`

to this:

`if (urls) {
	message.urls = urls.map((url) => { return { url: url }; });
} else {
	message.urls = [];
}`

**Comment by reitzig** [comment]
Seconded, and [screen-capped](https://imgur.com/a/j5W4c).

**Comment by Hudell** [comment]
Duplicate of #2833
