### ISSUE TITLE
latest version error with ssl

### ISSUE THREAD

**Issue by johnfelipe** [RocketChat/Rocket.Chat#4999]
[Wed Nov 09 2016 19:52:29 GMT-0500 (COT)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
	can't load hubot-help/src/help.coffee
	{ [Error: ENOENT: no such file or directory, open '/home/felipesneideradmin/Rocket.Chat/programs/server/npm/rocketchat_internal-hubot/node_modules/hubot-help/src/help.coffee']
	  errno: -2,
	  code: 'ENOENT',
	  syscall: 'open',
	  path: '/home/felipesneideradmin/Rocket.Chat/programs/server/npm/rocketchat_internal-hubot/node_modules/hubot-help/src/help.coffee' }

I have this

	server {
		listen 192.168.0.41:443 default_server;
		error_log /var/log/nginx/rocketchat.access.log;

		ssl on;
		ssl_certificate /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

		location / {
			proxy_pass http://192.168.0.41:3000/;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $http_host;

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forward-Proto http;
			proxy_set_header X-Nginx-Proxy true;

			proxy_redirect off;
		}
	}

how solved

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
