### ISSUE TITLE
Installation with gihub and metoer crash

### ISSUE THREAD

**Issue by johnfelipe** [RocketChat/Rocket.Chat#5001]
This is my steps:

	git clone https://github.com/RocketChat/Rocket.Chat.git
	cd Rocket.Chat
	curl https://install.meteor.com/ | sh
	meteor

	Meteor 1.4.2.3 has been installed in your home directory (~/.meteor).
	Writing a launcher script to /usr/local/bin/meteor for your convenience.
	This may prompt for your password.

	To get started fast:

	  $ meteor create ~/my_cool_app
	  $ cd ~/my_cool_app
	  $ meteor

	Or see the docs at:

	  docs.meteor.com

	felipesneideradmin@academiaweb:~/Rocket.Chat$ meteor
	[[[[[ ~/Rocket.Chat ]]]]]

	=> Started proxy.
	=> Started MongoDB.
	rocketchat:lib: updating npm dependencies -- bad-words, node-dogstatsd,
	localforage, bugsnag...
	rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...
	rocketchat:assets: updating npm dependencies -- image-size, mime-types...
	rocketchat:theme: updating npm dependencies -- less, less-plugin-autoprefix...
	rocketchat:api: updating npm dependencies -- busboy...
	rocketchat:autolinker: updating npm dependencies -- autolinker...
	rocketchat:cas: updating npm dependencies -- cas...
	rocketchat:crowd: updating npm dependencies -- atlassian-crowd...
	rocketchat:file-upload: updating npm dependencies -- mime-types, filesize...
	rocketchat:importer: updating npm dependencies -- adm-zip, bson...
	rocketchat:importer-csv: updating npm dependencies -- csv-parse...
	rocketchat:internal-hubot: updating npm dependencies -- coffee-script, hubot,
	hubot-scripts, hubot-help...
	rocketchat:irc: updating npm dependencies -- coffee-script, lru-cache...
	rocketchat:sms: updating npm dependencies -- twilio...
	Livechat: updating npm dependencies -- shelljs...
	rocketchat:livechat: updating npm dependencies -- ua-parser-js...
	rocketchat-livechat@1.0.0 /home/felipesneideradmin/Rocket.Chat/packages/rocketchat-livechat/app
	├── autolinker@1.3.2
	└─┬ babel-runtime@6.18.0
	  ├── core-js@2.4.1
	  └── regenerator-runtime@0.9.6

	rocketchat:oembed: updating npm dependencies -- he, jschardet, iconv-lite,
	ip-range-check...
	rocketchat:slackbridge: updating npm dependencies -- slack-client...
	rocketchat:ui-master: updating npm dependencies -- clipboard...
	rocketchat:tutum: updating npm dependencies -- redis...
	rocketchat:ui-sidenav: updating npm dependencies -- less,
	less-plugin-autoprefix...
	steffo:meteor-accounts-saml: updating npm dependencies -- xml2js, xml-crypto,
	xmldom, connect, xmlbuilder, querystring, xml-encryption...
	W20161109-19:57:13.008(-5)? (STDERR) /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:348
	W20161109-19:57:13.130(-5)? (STDERR) }).run();
	W20161109-19:57:13.131(-5)? (STDERR)    ^
	W20161109-19:57:13.132(-5)? (STDERR)
	W20161109-19:57:13.134(-5)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules
	W20161109-19:57:13.139(-5)? (STDERR) directory. Please run the following command to install it:
	W20161109-19:57:13.140(-5)? (STDERR)
	W20161109-19:57:13.142(-5)? (STDERR)   meteor npm install --save babel-runtime
	W20161109-19:57:13.144(-5)? (STDERR)
	W20161109-19:57:13.146(-5)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
	W20161109-19:57:13.147(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
	W20161109-19:57:13.149(-5)? (STDERR)     at require (packages/modules-runtime.js:106:16)
	W20161109-19:57:13.151(-5)? (STDERR)     at packages/babel-runtime.js:139:15
	W20161109-19:57:13.151(-5)? (STDERR)     at packages/babel-runtime.js:150:3
	W20161109-19:57:13.152(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:295:34
	W20161109-19:57:13.153(-5)? (STDERR)     at Array.forEach (native)
	W20161109-19:57:13.154(-5)? (STDERR)     at Function._.each._.forEach (/home/felipesneideradmin/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
	W20161109-19:57:13.154(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:128:5
	W20161109-19:57:13.155(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:344:5
	=> Exited with code: 1
	W20161109-19:57:21.767(-5)? (STDERR) /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:348
	W20161109-19:57:21.768(-5)? (STDERR) }).run();
	W20161109-19:57:21.769(-5)? (STDERR)    ^
	W20161109-19:57:21.769(-5)? (STDERR)
	W20161109-19:57:21.770(-5)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules
	W20161109-19:57:21.770(-5)? (STDERR) directory. Please run the following command to install it:
	W20161109-19:57:21.771(-5)? (STDERR)
	W20161109-19:57:21.772(-5)? (STDERR)   meteor npm install --save babel-runtime
	W20161109-19:57:21.772(-5)? (STDERR)
	W20161109-19:57:21.773(-5)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
	W20161109-19:57:21.773(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
	W20161109-19:57:21.774(-5)? (STDERR)     at require (packages/modules-runtime.js:106:16)
	W20161109-19:57:21.775(-5)? (STDERR)     at packages/babel-runtime.js:139:15
	W20161109-19:57:21.776(-5)? (STDERR)     at packages/babel-runtime.js:150:3
	W20161109-19:57:21.777(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:295:34
	W20161109-19:57:21.778(-5)? (STDERR)     at Array.forEach (native)
	W20161109-19:57:21.779(-5)? (STDERR)     at Function._.each._.forEach (/home/felipesneideradmin/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
	W20161109-19:57:21.779(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:128:5
	W20161109-19:57:21.779(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:344:5
	=> Exited with code: 1
	W20161109-19:57:28.404(-5)? (STDERR) /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:348
	W20161109-19:57:28.405(-5)? (STDERR) }).run();
	W20161109-19:57:28.405(-5)? (STDERR)    ^
	W20161109-19:57:28.406(-5)? (STDERR)
	W20161109-19:57:28.406(-5)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules
	W20161109-19:57:28.407(-5)? (STDERR) directory. Please run the following command to install it:
	W20161109-19:57:28.407(-5)? (STDERR)
	W20161109-19:57:28.408(-5)? (STDERR)   meteor npm install --save babel-runtime
	W20161109-19:57:28.408(-5)? (STDERR)
	W20161109-19:57:28.409(-5)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
	W20161109-19:57:28.409(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
	W20161109-19:57:28.410(-5)? (STDERR)     at require (packages/modules-runtime.js:106:16)
	W20161109-19:57:28.410(-5)? (STDERR)     at packages/babel-runtime.js:139:15
	W20161109-19:57:28.411(-5)? (STDERR)     at packages/babel-runtime.js:150:3
	W20161109-19:57:28.411(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:295:34
	W20161109-19:57:28.412(-5)? (STDERR)     at Array.forEach (native)
	W20161109-19:57:28.413(-5)? (STDERR)     at Function._.each._.forEach (/home/felipesneideradmin/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
	W20161109-19:57:28.413(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:128:5
	W20161109-19:57:28.414(-5)? (STDERR)     at /home/felipesneideradmin/Rocket.Chat/.meteor/local/build/programs/server/boot.js:344:5
	=> Exited with code: 1
	=> Your application is crashing. Waiting for file change.

How can solve that?

**Comment by marceloschmidt** [comment]
You have to run `meteor npm install` before running `meteor` for the first time. If the error persists, also run `meteor npm install --save babel-runtime`.

**Comment by johnfelipe** [comment]
Every time when need up service of RocketChat i need put **meteor**, that process is to long, is other way to do it?

**Comment by engelgabriel** [comment]
@johnfelipe on production you should use `meteor build` and run the compiled version with something like PM2.
