### ISSUE TITLE
latest rocketchat windows app issue voice, video and webrtc

### ISSUE THREAD

**Issue by johnfelipe** [RocketChat/Rocket.Chat#5003]
I have latest rocketchat server and rocketchat windows app issue

![errorrocketchat](https://cloud.githubusercontent.com/assets/428820/20499661/72cd5b26-b000-11e6-991e-469deeb29ed0.png)

How solved?

**Comment by Nemra1** [comment]
same issue

**Comment by codersofthedark** [comment]
I am facing the same issue. I am using MacbookAir - Chrome Browser

**Comment by fk0** [comment]
same here
Ubuntu 16.10
installed via snap 
snap install rocketchat-server
Tested in chrome  55.0.2883.87 (64-bit) and ubuntu desktop client
Works fine in Firefox 50.1.0

**Comment by MartinSchoeler** [comment]
For the camera and microphone to work on chrome you need to be in a https environment. https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by johnfelipe** [comment]
And if we use Firefox?
