### ISSUE TITLE
Migrate rocketchat to another server (with upgrade)

### ISSUE THREAD

**Issue by oyeaussie** [RocketChat/Rocket.Chat#5007]
Your Rocket.Chat version: 0.46.0

Hello,

I am trying to move my installation from a centos 6 server to centos 7 server. On the centos 6 server, I was running v0.34.0 and on the new centos 7 server we are running v 0.46.0. Steps I have taken so far:
1) Upgraded the current centos 6 v0.34.0 -> 0.46.0
2) Upgrade went fine, logs are as follows:

-bash-4.1# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
 
> fibers@1.0.15 install /opt/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/opt/Rocket.Chat/programs/server)
amdefine@1.0.1 node_modules/amdefine

underscore@1.5.2 node_modules/underscore

asap@2.0.5 node_modules/asap

meteor-promise@0.8.0 node_modules/meteor-promise

semver@4.1.0 node_modules/semver

source-map-support@0.3.2 node_modules/source-map-support

source-map@0.1.32 node_modules/source-map

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

promise@7.1.1 node_modules/promise

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── escape-string-regexp@1.0.5
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

fibers@1.0.15 node_modules/fibers
-bash-4.1# cd ../..
-bash-4.1# node main.js 
Updating process.env.MAIL_URL
ufs: permissions are not defined for store "fileSystem"
ufs: store created at 
ufs: permissions are not defined for store "fileSystem"
ufs: store created at 
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Migrating from version 54 -> 64","time":{"$date":1479798939679},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 55","time":{"$date":1479798939687},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 56","time":{"$date":1479798939727},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 57","time":{"$date":1479798939770},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 58","time":{"$date":1479798939841},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 59","time":{"$date":1479798939904},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 60","time":{"$date":1479798944732},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 61","time":{"$date":1479798945016},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 62","time":{"$date":1479798945027},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 63","time":{"$date":1479798945163},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 64","time":{"$date":1479798945428},"level":"info"}
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1479798945453},"level":"info"}
Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.
{"line":"159","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 64","time":{"$date":1479798955471},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom emoji storage
[Tue Nov 22 2016 18:15:58 GMT+1100 (EST)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
ufs: permissions are not defined for store "rocketchat_uploads"
Using GridFS for Avatar storage
➔ System ➔ startup
➔ +--------------------------------------------------+
➔ |                  SERVER RUNNING                  |
➔ +--------------------------------------------------+
➔ |                                                  |
➔ |       Version: 0.46.0                            |
➔ |  Process Port: 3000                              |
➔ |      Site URL: http://chat......com.au:3000/  |
➔ |         OpLog: Disabled                          |
➔ |                                                  |
➔ +--------------------------------------------------+
^C
-bash-4.1# 

- After the upgrade and making sure the new version works with the current database, I exported the db using mongodump and imported that db into the new server using mongorestore

Issues:
1) File uploads that were uploaded on the old server are not accessible on the new server. Like images would have placeholder, but if you click on them you just get the loading spinner and no image.
2) I am running rocketchat on the old server now till the above issue is resolved. As the old server is running centos 6, I get the following when I try to start the rocket chat service:

## There is an issue with `node-fibers` ##
`/opt/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-11/fibers.node` is missing.

Try running this to fix the issue: /usr/bin/node /opt/Rocket.Chat/programs/server/node_modules/fibers/build

/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	      ^
Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
error: Forever detected script exited with code: 8
error: Script restart attempt #171

- Server runs using node main.js command.

Appreciate if someone can provide any help with this migration.

Thanks.

**Comment by tntobias** [comment]
This is a lot to go through but I'd recommend a few things:
1. If your Rocket.Chat uploads are on the file system, make sure the directory specified in the database exists and the service account has permissions to it. The logs above appear to indicate an issue accessing
2. It looks like you're running npm install with elevated permissions. If you must do this, use the --unsafe-perm switch to make sure it 
3. If you've been tinkering with it for awhile, try cleaning the npm cache to make sure there's no leftover garbage.
4.  You say you're able to run the server using the node main.js command but you get errors launching the forever service? I'd think there's probably permissions issues there as well

Unfortunately I'm not as versed in modern CentOS as I am in Debian variants but maybe someone can chime in on whether there were significant changes to security in CentOS 7.

**Comment by oyeaussie** [comment]
The primary issue got fixed. it was DNS issue. The dns needed to be pointed to the new server.
