### ISSUE TITLE
Can't download sent files on desktop client

### ISSUE THREAD

**Issue by lashae** [RocketChat/Rocket.Chat#5011]
We have been using Rocket.chat as a deployed service on "Rocket.Chat Deploy" servers with the version 0.45.0.

When someone sends a file to a channel, it can be previewed within the application. However when you click the download icon on the desktop app, a new browser tab opens and we get a HTTP/403 error always.

**Comment by MartinSchoeler** [comment]
@lashae are your 'protect files' setting set to true? You can try to set that to false or log in your server via browser first

**Comment by lashae** [comment]
Hi Martin,

first of all thank you for the prompt response. When I set "protect files" setting to `false`, it works as expected. However, I share the concerns on the issue #4150 as Rocket.chat should display a login page for unauthenticated access. I'll try to contribute to the mentioned issue whereas appropriate.
