### ISSUE TITLE
Disable link preview in formatted code chat

### ISSUE THREAD

**Issue by s17t** [RocketChat/Rocket.Chat#5013]
Your Rocket.Chat version: 0.45

When using the formatted strings (with markdown \```) the link preview is active. This can lead to weird and unusable chat when the pasted code contains a lot of links (i.e. a JSON with data or debug messages about crawled urls or tweets or facebook content).

Would be possible to disable link preview for link a the formatted part of chat message ? Thank you.

**Comment by martinvonwittich** [comment]
This issue is one of the top 10 issues when sorting by +1, but it doesn't even have a milestone assigned (along with only two others from the top 10 list). It would be nice if we could see some progress on this; it's pretty annoying and seems to be an easy fix.

**Comment by towijo** [comment]
Please fix this issue. It is extremely annoying especially when sharing XML-code with a lot of namespace declarations and you have to scroll for a while to see the actual code, as the chat-window is spammed with link preview output. Remove it for formatted code or at least make it configurable / optional.

**Comment by sampaiodiego** [comment]
this was fixed already
