### ISSUE TITLE
Mobile "Downloading Files" stuck after update to 0.46.0

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#5014]
Your Rocket.Chat version: 0.46.0

Updated my docker installation and the official Android app no longer works on my server, still works on the demo. I cleared the data but after the server is validated it gets to "downloading files" but it doesn't show the download progress or even how many files there are.

The last access in apache is /__cordova/manifest.json

Browsing to https://myserver/__cordova/manifest.json outputs lots of stuffs, looks fine.

I disabled haproxy and ran RC strait through apache but still no go.

RC runs in docker-compose on port 3000, apache reverse proxies it with my LE certificate and it works fine on desktop with SSL humming along nicely. It's just the mobile app thats not working anymore, mobile web works as expected.

**Comment by mrplow** [comment]
Reverting to 0.45 fixed my issue. No other configuration changes were made other than changing the version in docker-compose.xml, didn't even roll back the db.

**Comment by mrplow** [comment]
Figured I should attach my config files
[site.conf.txt](https://github.com/RocketChat/Rocket.Chat/files/608063/site.conf.txt) (apache)
[docker-compose.yml.txt](https://github.com/RocketChat/Rocket.Chat/files/608064/docker-compose.yml.txt)

**Comment by shellster** [comment]
I am also experiencing this problem.  I tried using root and manually deleting all the files on my phone related to rocket.chat and doing a clean install, but I still have the same problem.  I can access my server just fine from firefox or chrome, both on my phone or PC.  Other users who had previously installed the phone app (before the upgrade to 0.46.0) can still access the instance.

**Comment by mrplow** [comment]
That's correct.

I just restored an old Android backup of my RC installation with titanium backup. When I started RC it connected to my server, updated files properly and it's working as it should.

If I wipe user data and re-login the original symptom appears.

**Comment by shellster** [comment]
I also validated that a previous Titanium backup allowed me to update to the latest version.

-----Original Message-----

**Comment by letic** [comment]
Hi there,

We can confirm this as well. We deployed 0.45 to production for our 80+ users and upgraded to 0.46 to get the WebRTC fixes.

All new users can not use the mobile app with the issue described above. 

It's very easy to reproduce by just uninstalling the mobile app and try to connect to a 0.46 rocket chat instance.

Can an official dev confirm this as this is a critical issue.

Cheers
Anthony

**Comment by shellster** [comment]
Any updates?  This is kind of a show stopper for new deployments.

**Comment by letic** [comment]
We did some more testing and this is not occurring with https://demo.rocket.chat so there must be a bug in the hosted version. Otherwise the devs should have noticed it.

**Comment by skizzors** [comment]
Some of our users having this same issue, one on andriod other on iOS, not sure how to fix issue. It seems to be linked to downloading the app as new and trying to connect to a 0.46 server

**Comment by mrplow** [comment]
How is everyone experiencing this issue deploying RC?

I'm seeing the issue deploying through docker as explained above.

**Comment by shellster** [comment]
I'm deploying manually from the latest tar.gz and proxying via Caddyserver.

**Comment by Againstreality** [comment]
Same here on two 100+ Users Systems on 0.47

**Comment by hadifarnoud** [comment]
this an important issue, any ETA on when it would be fixed? can the issue be with the mobile app?

**Comment by LeDistordu** [comment]
+1

**Comment by Angl0r** [comment]
+1

**Comment by rodrigok** [comment]
We found the reason of this bug, we need to update the mobile apps to solve it.

I'll do it tomorrow, the Android version will be available tomorrow, the iOS version will take more time (apple review process)

**Comment by thiesschneider** [comment]
Thx!

**Comment by shellster** [comment]
Is there an updated timeline for the Android release?

**Comment by mrplow** [comment]
@shellster the fix is included in the beta android app
https://play.google.com/apps/testing/com.konecty.rocket.chat

**Comment by hadifarnoud** [comment]
when does the android app fix will get out of beta?

**Comment by hadifarnoud** [comment]
it's been two weeks. still waiting for iOS app update

**Comment by daemienb** [comment]
Any update on the IOS update guys?

**Comment by engelgabriel** [comment]
Apple rejected the release because our server did not support IPv6. We have fixed it yesterday and re-submitted the app.

**Comment by daemienb** [comment]
Thanks guys

**Comment by flayks** [comment]
Same problem here!
