### ISSUE TITLE
Invitation to participate of a podcast interview

### ISSUE THREAD

**Issue by omaciel** [RocketChat/Rocket.Chat#5016]
Please accept my apologies in advance for filing an issue that does not involve an issue per se.

My name is Og Maciel and together with @elyezer and @rochacbruno we host [Castálio Podcast](http://castalio.info/), a podcast in Portuguese (we're all Brazilians) focusing on people and projects we find interesting and exciting!

I would like to check your availability for an interview to talk about **RocketChat** over Skype?

Thanks in advance!

@omaciel

**Comment by k0nsl** [comment]
@omaciel: Sounds cool. So as you say, this will be in Portuguese? That's too bad (for me, at least) as I can't understand it so well.
Also, why not conduct the interview about Rocket.Chat over Rocket.Chat? That would be way more appropriate :smirk_cat:

**Comment by omaciel** [comment]
@k0nsl thanks for replying. Actually, we can do it in English too, we're all fluent :) I like what you suggested, doing the interview over Rocket.Chat, but I do need the audio of our chat for the podcast. What do you suggest? I see that @engelgabriel is assigned this issue, so I'll wait for his comment about his availability ;)

**Comment by engelgabriel** [comment]
OI @omaciel pode entrar em contato comigo no https://demo.rocket.chat/direct/gabriel.engel

Qual o teu usuário no nosso servidor de demo? Abraços.

**Comment by omaciel** [comment]
> On Nov 24, 2016, at 4:20 PM, Gabriel Engel <notifications@github.com> wrote:
> 
> OI @omaciel pode entrar em contato comigo no https://demo.rocket.chat/direct/gabriel.engel

Bom dia, já entrei la’ :)

> Qual o teu usuário no nosso servidor de demo? Abraços.

Usuario é omaciel e te deixei umas msgs por la’. Grade abraço e muito obrigado por seu tempo.
--
Og Maciel - GPG Keys: CD03D583
omaciel@ogmaciel.com
https://omaciel.github.io
