### ISSUE TITLE
Disable "invisibility mode"

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#5020]
Your Rocket.Chat version: 0.46.0

It would be great if we could be given the option to entirely disable the "invisible"-mode. The available ones are "Online", "Away", "Busy" and "Invisible". Me and some of my users find the "invisible"-mode very annoying and somewhat frustrating at times.

Anyway, just a thought I had!

**Comment by hollowisation** [comment]
What happened to this feature? I need it too.

**Comment by Prakharsvnit** [comment]
@MartinSchoeler I would like to work on this feature,should we make a different 'status' section in administration that has options to turn off Invisible button.

**Comment by geekgonecrazy** [comment]
Feel free!  None of us are currently working on it.  But please be sure that by default invisible is there.  It needs to only be hidden by an admin explicitly disabling it.

**Comment by ChrisKendallVA** [comment]
I would very much like to see this feature included. invisible/offline should only be available to accounts currently not connected to RC i.e Offline. and shouldnt really be an option to hide yourself as this causes issues within staffing (in my experience of it)

**Comment by juldut** [comment]
Need to disable "invisible"-mode too. As the rocket chat admin, I can not detect whether the user is online or not.

**Comment by dmoldovan123** [comment]
+1

**Comment by richardwlu** [comment]
+1

**Comment by chatnl** [comment]
+1
I am running a public chatbox with rocket chat. Invisble mode is being abused by users who want to spy on conversations.

**Comment by wemu** [comment]
don't like it at all this status cannot be disabled. even the rest api displays an invisible user as offline. As an administrator I can't say who is online. Would best like to have this on a per group level, but disabling it globally would work for me too. For my community invisible users don't work at all.

**Comment by ggazzo** [comment]
related https://github.com/RocketChat/Rocket.Chat/pull/9353

**Comment by blmt** [comment]
I don't really get why the invisible feature is even there: I second an offline state that can be handy if a user doesn't want to close the chat's browser tab but IMHO there should be no such thing as a user being able to read and even _write_ while invisible. Could someone explain the rationale behind?

**Comment by geekgonecrazy** [comment]
Honestly invisible is a super common thing in communications platforms... It's rationale shouldn't really need explained :)

But... its because some like to use as a real time communication only platform.  If your status shows green they expect that you will respond quickly.

If someone just needs to send an occasional message for async comms but doesn't want to be treated as online and readily available for instant conversation.. invisible is a good thing for them.

**Comment by kneufeld** [comment]
I personally like "invisibility" mode as sometimes I want to monitor things (alerts, etc) but not get bothered with direct questions. However, I'd really like it if the message box would be disabled and/or change color to remind me when I'm in invisible mode. The tiny dot on my avatar in the top corner is too easy to miss and forget about.

**Comment by blmt** [comment]
I guess the best compromise would probably be to disable the ability to write messages while invisible.

**Comment by geekgonecrazy** [comment]
Seems like the best compromise is the option to disable invisible.  That way it can continue to work for those that like it how it is :)

**Comment by chatnl** [comment]
> Honestly invisible is a super common thing in communications platforms... It's rationale shouldn't really need explained :)
> 
> But... its because some like to use as a real time communication only platform. If your status shows green they expect that you will respond quickly.
> 
> If someone just needs to send an occasional message for async comms but doesn't want to be treated as online and readily available for instant conversation.. invisible is a good thing for them.

Judging from your reply you are still thinking that Rocket Chat should be seen only as a solution for Slack / collaborationware. If that's the case you are probably not realizing that Rocket Chat is en will be more and more used for standard chatboxes. Both have different needs and it would be wise to also have a couple of options included that are good for developers of chatboxes. The installed base of Rocket Chat will only be growing and growing which will be great for exposure of the brand and future funding etc. 

I am developing a chatplatform that has the potential of becoming one of the largest chatcommunities in our country. I expect to run several hundred instances of Rocket Chat in the near future. 

What I really need before I can start promoting this platform is to be able to switch off the invisible mode. Actually, I wouldn't mind it if setting the status manually could be switched off completely in the permissions of Rocket Chat. People are either online, away (after xx minutes of inactivity) or logged out. 

If people are using Rocket Chat as a Slack alternative then they simply keep the option to set a status switched on. Including the invisible mode if that makes people happy. 

I am testing with a small group of people and already have people that use invisible mode to read everything that users are talking about, afraid that somebody is talking about them, and never contribute. You are creating lurkers this way and that's not what we want in a chatbox environment. If you enter, you should participate.

So please please, include the option to switch the manual setting of the userstatus on/off.

**Comment by chatnl** [comment]
More than two years have past after the first post in this topic. Does somebody know if there is any progress regarding the development of the option to switch the status option off? I really can not use Rocket Chat at this moment as a chat platform because of people lurking in the background and staying hidden...

**Comment by chatnl** [comment]
Ok, because of the lack of a proper solution I have just nukes my invisible status option by entering the following at "custom css" in the layout section:

li.rc-popover__item.rc-popover__item--offline.js-action {
display: none !important;
}

Now I can atleast start using it...

**Comment by istatwat** [comment]
i can't get thiscode working  do i need to put somthing before li.?

**Comment by geekgonecrazy** [comment]
adding contrib easy pr’s for sure welcome.  🙂

**Comment by kanishk98** [comment]
@geekgonecrazy I'm getting myself up to speed with Rocket.Chat, and I'd like to begin with this issue. Hope that's okay.

**Comment by chatnl** [comment]
> @geekgonecrazy I'm getting myself up to speed with Rocket.Chat, and I'd like to begin with this issue. Hope that's okay.

If there is anything that I can test just let me know. I still have users that use the app and set invisible mode.

**Comment by githubetc** [comment]
Having "invisibility" is a MUST for privacy reasons. This is an important feature in chat platforms e.g. xmpp.

Imagine a stalker/boss/partner knowing exactly what you are up to in real-time !

In fact, this should be configured per person, so we can block our presence status to some and not to others.

**Comment by ashwaniYDV** [comment]
I have previously worked with settings and would like to work on this too.
I think the best way is to add an option to disable invisible in the admin settings.

**Comment by chatnl** [comment]
> I have previously worked with settings and would like to work on this too.
> I think the best way is to add an option to disable invisible in the admin settings.

YES! Please please if you could get this to work like that you will be my hero! If possible I would love two see two options:

1. (most important): being able to disable the invisble mode in the admin settings. This would end the lurking of users that never take part in a discussion but want to know everything that people are talking about. For a public chatbox this is a real problem. 

2. If possible: being able to disable the option that somebody can set himself busy (red) or away (yellow) totally. If it is disabled Rocket chat should simply use timeout t1 to switch a user to away and log them off when they aren't back by t2. This would make it perform like a normal chatbox. I now have users who switch themselves to red (busy) and stay online all day without participating. 

Please let me know if I can test anything for you or if you need more info.

**Comment by subham103** [comment]
Does pr #9353 solve this issue?

**Comment by chatnl** [comment]
Hi,

No I don’t think so? People can still choose to set themselves offline. If the status message is altered that doesn’t give me any info if somebody is really offline or not. I need the complete option of choosing to offline gone.

Or am I missing somehting?

Regards,

Stef

Van: Subham Sahoo <notifications@github.com>
Verzonden: zondag 2 februari 2020 17:25
Aan: RocketChat/Rocket.Chat <Rocket.Chat@noreply.github.com>
CC: Stef Westheim <stef.westheim@topdata.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [RocketChat/Rocket.Chat] Disable "invisibility mode" (#5020)


Does pr #9353<https://github.com/RocketChat/Rocket.Chat/pull/9353> solve this issue?

**Comment by awunder** [comment]
i would really love to have this setting too.. i hate it when people hide and just want to sponge up knowledge of others..

**Comment by buso** [comment]
I need this feature also.  Especially now that my team and myself are working from home.  We use RC for team engagement.  Some people I supervise turn their status to invisible and I cannot tell if they're on or not.  I've been query the DB to see if they are on.  This feature would be a huge help.
