### ISSUE TITLE
Connecting the Ios app when using subdir behind a proxy

### ISSUE THREAD

**Issue by Dynabix** [RocketChat/Rocket.Chat#5026]
Your Rocket.Chat version: 0.46

I am running the latest version successfully in a subdir called /chat behind an apache httpd proxy. The proxy is configured using the instructions on this page:
[https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-a-nginx-ssl-reverse-proxy]
Connecting from a browser works well, but connecting from the app does not work with the configured url (https://my.hostname.com/chat). In the apache log I see that the app succesfully accesses urls with /chat, but that the calls to e.g. /sockjs/info? get a 404 response.

So probably the app should be reconfigured to also use the /chat subdir for the sockjs calls?
Or is there another solution?

Regards,
David

**Comment by stealthybox** [comment]
We're also seeing this issue.

Rocket.Chat version: 0.48.1
- ROOT_URL=https://{my-domain}.com/chat

Linked to #2810

from our HA-Proxy logs:
**request from browser** (working)
`[14/Dec/2016:17:50:49.366] https_in~ rocket_chat_backend/{my-domain}.com 284/0/2/2/288 200 216 - - ---- 4/4/2/3/0 0/0 "GET /chat/_timesync HTTP/1.1"n <obfuscated>:25003`

**request from Cordova app on iOS/Android** (broken)
`[14/Dec/2016:17:48:19.681] https_in~ https_in/<NOSRV> -1/-1/-1/-1/53 503 212 - - SC-- 3/3/0/0/0 0/0 "GET /_timesync HTTP/1.1"n <obfuscated>:59287`

**Comment by Huljo** [comment]
[Maybe here](https://github.com/RocketChat/Rocket.Chat/blob/744d25a6264c0daf3c3c357fc65754010c4fa476/packages/meteor-timesync/timesync-client.js#L56)

**Comment by stealthybox** [comment]
Nice!
Looks like that should be
```javascript
syncUrl = Meteor.absoluteUrl(syncUrl);
```
instead of
```javascript
syncUrl = Meteor.absoluteUrl("_timesync");
```
