### ISSUE TITLE
Support bulleted & numbered lists in messages

### ISSUE THREAD

**Issue by tyrel** [RocketChat/Rocket.Chat#5027]
In addition to the limited Markdown already supported in Rocket.Chat, several individuals in my organization have requested the ability to have numbered and bulleted lists.

## Ideal behavior

1. Any consecutive lines within a message starting with `*` or `-` shall be treated as an unordered list (`<ul>`) with each said line as an item (`<li>`) in that list.
2. Any consecutive lines within a message starting with `#` shall be treated as an ordered list (`<ol>`) with each said line as an item (`<li>`) in that list.
   - Alternatively, this could be done using numbers with periods as in Markdown.

### Bullets
```
Hey @Fred, these are my ideas:
* Eat daily
* Breathe most of the the time
* Always have your towel
```
Hey **@Fred**, these are my ideas:
- Eat daily
- Breathe most of the time
- Always have your towel

### Numbers
```
@John, take the following steps:
# Eat breakfast
# Eat lunch
# Eat dinner
```
**@John**, take the following steps:
1. Eat breakfast
2. Eat lunch
3. Eat dinner

## Rationale
The indentation, especially of wrapped lines, in bulleted and numbered lists significantly increases the readability of them. The workarounds of just using `-` or `*` and numbers does not provide the necessary readability improvements.

## Optional Behavior
A nice-to-have is nested lists (for both numbered and bulleted lists).
```
* Item
** Subitem
* Next
```
- Item
  - Subitem
- Next

**Comment by RichardFoxworthy** [comment]
duplicate #918

**Comment by adrianovieira** [comment]
On iOS app it's working fine enough, but it doesn't work neither on browsers or desktop app.

iOS app working example:

```
* Item
  * Subitem
    * Subsubitem
* Next
```

**Comment by isabeaups** [comment]
Yes. This doesn't work on Linux App. :( 
@MartinSchoeler
