### ISSUE TITLE
Editing reaction emoji to an image causes it to go back to 'click to load'.

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#5028]
Your Rocket.Chat version: [I am still not aware of any way for a non-admin user of Rocket.Chat to obtain this information. Please let me know how to do this if possible.]

When I 'click to load' an image, and then someone adds or removes a reaction emoji on the message, the image goes back to the 'click to load' state.

**Comment by Hudell** [comment]
The default state is now loaded, but the problem still exists: If you collapse an image and someone adds a reaction, it will be expanded again.
