### ISSUE TITLE
First bug in v4.6 : server restart when add new user

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5030]
Your Rocket.Chat version: (0.46)
This happend to me today !
When im add new user from admin panel..server restart and never back online ..must start manually
![2016-11-24_020315](https://cloud.githubusercontent.com/assets/22897987/20582536/b6f234b6-b1ea-11e6-9760-6e5424ae99a3.png)
Server info : Centos 6.4

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
