### ISSUE TITLE
Email verification enabled throws incorrect error on login

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#5031]
0.46.0-develop

When the setting `Accounts_EmailVerification` is enabled, users can't login if they haven't verified email. But the error they are shown says: `User not found or incorrect password`.

However, when a user is already logged in and verification is enabled, it displays the appropriate warning: `You_have_not_verified_your_email`. That should be the message in both cases.

It would also be better if there was some communication on register that the email verification is required, before they can proceed.

**Comment by timkinnane** [comment]
Another note, that `Email Verification` (true|false) might be a misleading label, since email verification happens regardless of the setting, it's just that it's not enforced as a login requirement if set to false. Maybe `Email Verification Required` or `Force Email Verification` would be clearer.

**Comment by Gautime** [comment]
@timkinnane  Can i work on this? Please point me to the relevant file needed to be changed in this issue.

**Comment by luixxiul** [comment]
@ggazzo should this not be included 3.2.0 like the PR which this issue closed (#16236) ?

**Comment by ggazzo** [comment]
it will be included in the pr milestone... thanks
