### ISSUE TITLE
Share location button out of work

### ISSUE THREAD

**Issue by soenkef** [RocketChat/Rocket.Chat#5033]
Your Rocket.Chat version: 0.46

The location share button doesn't work (neither apps nor browsers). The button is displayed, but nothing happens when tap on it.

Any ideas?

**Comment by ArchimedesFM** [comment]
Is the bug still present in Rocket.Chat 0.55? In our Installation the button doesn't work at all (the button is visible). The Debug-Log doesn't even show a Method / Trigger.

**Comment by KirschbaumP** [comment]
I have the same bug in version 0.57.0-develop
the button doesn't work (the button is visible)
