### ISSUE TITLE
File uploads containing % in the file name not URL-escaped correctly

### ISSUE THREAD

**Issue by revlis-x** [RocketChat/Rocket.Chat#5036]
Your Rocket.Chat version: 0.46

When I upload a file with `%` in the file name, the file gets uploaded correctly, but rocketchat generates a wrong link to it, because the %-character is not URL-escaped correctly.

E.g. File: `100%.png`
Link generated by rs: `/.../100%.png` > results in 400 Bad Request
File manually accessible by changing URL to `/.../100%25.png`

**Comment by Hudell** [comment]
This has already been fixed.
