### ISSUE TITLE
Live chat text strikethrough, no notification (anonymous user)

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat#5048]
Your Rocket.Chat version: 0.46.0

When an anonymous user opens the Live Chat widget and sends a message, we do not receive the message. Additionally, the user message text is strikethrough:

![screenshot_20161125_115132](https://cloud.githubusercontent.com/assets/17307/20621153/df01b4d8-b305-11e6-9018-40c7133e17a4.png)

How do we enable Live Chat for anonymous users?

**Comment by graywolf336** [comment]
Are there any errors in the browser?

Btw @sampaiodiego 🔝

**Comment by sampaiodiego** [comment]
@brylie can you see if this is still hapenning?
