### ISSUE TITLE
Styling the live chat embedded box

### ISSUE THREAD

**Issue by YuniSocial** [RocketChat/Rocket.Chat#5054]
Hi. I customized the styling for the embedded chatbox, how would I apply it to my own Rocket.Chat installation?

I am editing livchat.je, rocket-livechat,js and livechat.css, I was trying to link to my own customized css and js files directly from the embed code

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by hooramin** [comment]
@martinschoeler so please add custom css for livechat embedded box. (feature request)
