### ISSUE TITLE
[Feature request] Multiple LDAP auth backends

### ISSUE THREAD

**Issue by NicolasVigier** [RocketChat/Rocket.Chat#5058]
Your Rocket.Chat version: 0.40.1

Hi,
Would it be possible to implement multiple LDAP backends for authentication, for two sister companies to share the same application?

Thanks,
Nicolas

**Comment by mfilotto** [comment]
Any news on this one ?

**Comment by marceloschmidt** [comment]
We don't plan on adding this due to its limited use, but we welcome PRs with that implementation.
