### ISSUE TITLE
Seen by for Direct Messages and Channels

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5071]
Seen by for Direct Messages and Channels

**Comment by TheReal1604** [comment]
@zorenleo Thanks for that issue. I think that would be a feature request? Maybe you can go more into detail for issues in the future.. 

Thanks!

**Comment by MartinSchoeler** [comment]
@zorenleo i think that is a duplicate of #4957, if not please reopen this issue
