### ISSUE TITLE
DDP client with file upload is showing error

### ISSUE THREAD

**Issue by firozcitrus** [RocketChat/Rocket.Chat#5077]
I am trying to upload file through ddp client connection. In that  iam download a packages from [node-ddp-client ](https://github.com/hharnisc/node-ddp-client  )  .connections and send and retrive text message is working fine. But iam trying to upload a file with options like 

```
{
    "msg": "method",
    "method": "slingshot/uploadRequest",
    "id": "42",
    "params": [
        "rocketchat-uploads", 
        {
            "name": _"https://domain.com/aws_logo._V400518270_.png",
            "size": 15664,
            "type": "image/png"
        },
        { "rid": "room-id" }
    ]
}
```

in client side shows the error 

```
{ error: 'Invalid directive',
  reason: 'The directive rocketchat-uploads does not seem to exist',
  message: 'The directive rocketchat-uploads does not seem to exist [Invalid directive]',
  errorType: 'Meteor.Error' }

```

What is the problem and where i change my code. ?
Please help...!!!

**Comment by wandonye** [comment]
Very likely you didn't set your storage configuration right. For example, if in `File Upload->Storage Type`, you selected `AmazonS3`, but you didn't set up S3 bucket. Then you will see this error

**Comment by ajaykumarCubix** [comment]
{
error:
error: 500
errorType: "Meteor.Error"
isClientSafe: true
message: "Internal server error [500]"
reason: "Internal server error"
id: "send_file_message"
}
please help me.

**Comment by reetp** [comment]
@ajaykumarCubix Please don't hijack issues.. You have given no information as to whether your issue relates to the original issue reported here which was most likely a configuration error. 

If your own issue is actually a bug then please open a new issue with a proper bug report including logs.

If it is a problem with your configuration please go to the forums https://forums.rocket.chat/ or chat https://open.rocket.chat and ask for help there.

Closing the original issue as notabug.

**Comment by reetp** [comment]
@rocket-cat close
