### ISSUE TITLE
[Avatar Initial] Use Name instead of Username.

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#5078]
Your Rocket.Chat version: 0.46.0,

Hello Developer,

Can we use **Name** instead of **Username** for Avatar initial ?

Thank you.

**Comment by fadanner** [comment]
+1 for this because if LDAP integration is used, username is mostly sAMAccountName which is most time a "cryptic" username and not the real name of the user.

**Comment by johnyb0y** [comment]
Any update on this FeatureRequest ? Thanks!

**Comment by swatoff** [comment]
+1 search users by username it's not informatly

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by facundomedica** [comment]
Can this be reopened?
