### ISSUE TITLE
Avatar doesn't display 

### ISSUE THREAD

**Issue by xjtufjj** [RocketChat/Rocket.Chat#508]
I cloned the code from the git and run rocket via the following commands: 

// start the mongodb 
docker run --name db -v data/runtime/db:/data/db -v data/dump:/dump -d mongo mongod --smallfiles
// Start the rocket 

 docker run --name rocketchata -p 8080:80 --env ROOT_URL=http://fishyfly.top --env MONGO_URL=mongodb://db:27017/meteor  --link db -d rocket.chat

After the rocket booting up, everthing is fine except the avatar does not display in the char window. seems this feature works fine on demo site. 

BTW: my server runs on a ubuntu system and my client runs on a mac, I tries the chrome and the safari, none of them works. 

<img width="643" alt="2015-08-19 11 33 10" src="https://cloud.githubusercontent.com/assets/2138665/9360750/b4b7d610-46ca-11e5-8e08-342b9f9cef11.png">

**Comment by rodrigok** [comment]
Can you inspect which url each avatar is trying to use and how is the response of this url?

**Comment by xjtufjj** [comment]
I think I found the root cause. 

On my server, the port 80 is used by nginx, so I use the port mapping for the rocket. "-p 8080:80", this will cause the client can not find the avatar correctly. 

I shutdhwn the server on 80 and use the -p 80:80 to start the docker, everything is fine.

also another solution is  to start the docker as follows:
docker run --name rocketchata -p 8080:80 --env ROOT_URL=http://fishyfly.top:8080 --env MONGO_URL=mongodb://db:27017/meteor --link db -d rocket.chat

we should add the port to the ROOT_URL. 

Thanks
Jinjun

**Comment by rodrigok** [comment]
:smiley:
