### ISSUE TITLE
Rocket Chat not login after power failure

### ISSUE THREAD

**Issue by vagpag** [RocketChat/Rocket.Chat#5080]
My Rocket.Chat version: (rocketchat-server 0.39.0).
Installation is on raspberry pi3 with ubuntu snap.

Hi, could you please help me with the below issue?
After a power failure I can no longer connect-login. Server and mongodb seems to run.

Thank you in advance.

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
