### ISSUE TITLE
LDAP - add ability to map ldap groups to roles

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#5085]
Your Rocket.Chat version: 0.46.0

In larger environments people tend to manage rights though ldap roles. Therefore it would be nice to be able to map a ldap provided group / user attribute to a rocket.chat role as this would make it much easier to integrate it with an existing ldap with larger numbers of users.

**Comment by a-abella** [comment]
This is the one feature I dream of for our enterprise deployment. At the moment we default users to the most restrictive role and must manually assign roles to our "elevated" users with room creation rights. In a very large organization, this can be annoying. Mapping to LDAP groups would be fantastic.

**Comment by drderkummer** [comment]
We just set up a server and thought we could filter teamleads to assign them to a room creation role but it seems not to be possible. It would be great to have that feature. It's a lot of work doing it by hand!

**Comment by teha75** [comment]
Same situation here!

**Comment by JigSawFr** [comment]
+1

**Comment by QantumEntangled** [comment]
Is this feature in the pipeline yet? I've got a number of groups I want to keep in/out of specific rooms and managing it in the LDAP alone would make life much easier. Not to mention cleaner.
I could write a script is bot to check LDAP groups & update every user hourly or something but that's just exacerbating the problem.

**Comment by tonylixu** [comment]
+1

**Comment by pasquinid** [comment]
+1

**Comment by koma85** [comment]
+1

**Comment by TheSharpieOne** [comment]
Linking #1196 as it is similar.

**Comment by wreiske** [comment]
Pull request is in #14278
