### ISSUE TITLE
LDAP - add ability to configure an "auto join" for users with a specific group

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#5086]
Your Rocket.Chat version: 0.46.0

When having a larger number of users in an ldap directory permissions the membership to teams is often handled through ldap groups. IMHO it would be a good feature to let people with a specific user attribute / group join 1 to n channels automaticaly (initially).

**Comment by goiaba** [comment]
We have chosen Rocket.Chat as the IM tool to be used in a +3000 employees Brazilian government institution and this functionality would be very very important for us. We are at this moment trying to figure out how to implement it locally (hints are welcome), but of course, an official solution would be better. We are anxiously waiting for it.

**Comment by jothoma1** [comment]
Hi, same for us, will be really helpful !!

**Comment by localguru** [comment]
Would like it!

**Comment by drderkummer** [comment]
I'd also like that!

**Comment by bhotrock** [comment]
I also vote for this.  It would help greatly!

**Comment by mxmo0rhuhn** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39685519)](https://www.bountysource.com/issues/39685519-ldap-add-ability-to-configure-an-auto-join-for-users-with-a-specific-group?utm_source=39685519&utm_medium=shield&utm_campaign=ISSUE_BADGE)
We would also be super happy to see this feature

**Comment by wreiske** [comment]
Pull request is in: https://github.com/RocketChat/Rocket.Chat/pull/14278
