### ISSUE TITLE
Role not updated while updating user

### ISSUE THREAD

**Issue by a5his** [RocketChat/Rocket.Chat#5092]
Your Rocket.Chat version: 0.46.0

Hi, I was trying to create and update users with Rest API and was able to create along with assigned role. While updating the user, the API failed to update user role. After going through the code I came to know that the role wasn't included at all. Is there any reason why `user.update` API is ignoring role?

Thanks

**Comment by engelgabriel** [comment]
@a5his is you pass an array of `roles` it will now be saved.
