### ISSUE TITLE
 asteroid.call('sendMessage', {msg: text, rid: roomid})  does not always pass all text

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#5097]
See screenshot for hubot log and arriving text. Reproduce by installing  https://github.com/radicallyopensecurity/pentext/blob/master/chatops/scripts/rosbot.coffee
![screen shot 2016-12-02 at 19 16 13](https://cloud.githubusercontent.com/assets/13427371/20845167/fe39ee9c-b8c3-11e6-87a0-bdcb68afb035.png)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
