### ISSUE TITLE
When unread channels list is enabled, the curently-visible channel should never be shown in it.

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#5098]
Your Rocket.Chat version: [I still have no idea how a non-admin user of a Rocket.Chat instance can determine this, so I have no idea.]

When the unread channels list is enabled, and someone speaks in the currently-open channel, it bounces into the list for a moment, highlights, then gets immediately marked read and bounces out of the list again and unhighlights. The motion is extremely distracting and causes all the other channels in the list to move around unnecessarily.

The currently-visible channel should be exempted from getting marked as having unread messages in it, or moved to the unread list, since they're going to be marked read immediately.

**Comment by SeanPackham** [comment]
Cannot duplicate in the new UI.
