### ISSUE TITLE
Disallowed useragent using Google OAuth

### ISSUE THREAD

**Issue by BarnumD** [RocketChat/Rocket.Chat#5103]
It seems that google has changed their OAuth requirements so that web views no longer work.
http://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

This issue is causing us not to be able to use the rocket.chat app on any IOS devices.  We recieve the following after clicking on the google login button on the login screen.

![img_7466](https://cloud.githubusercontent.com/assets/2438253/20850246/3927b2d0-b8a8-11e6-81c0-c0141c4f072a.PNG)
Rocket.Chat Server version 0.46.0

**Comment by BarnumD** [comment]
If this belongs in RocketChat/Rocket.Chat.iOS I will recreate it there.

**Comment by rodrigok** [comment]
@BarnumD This issue belongs to https://github.com/RocketChat/Rocket.Chat.Cordova, can you open there?

**Comment by BarnumD** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat.Cordova/issues/159
