### ISSUE TITLE
Still some issues with using subdir behind a proxy

### ISSUE THREAD

**Issue by Dynabix** [RocketChat/Rocket.Chat#5104]
Your Rocket.Chat version: 0.46

Apart from the issue I contributed in using the iOS App also in the browser there are still some errors in using a subdir /chat behind a proxy which will reduce functionality. They are visible in the developer console in the browser:
- https://my.domainname.example/packages/rocketchat_videobridge/client/public/external_api.js?_=1480768663069 Failed to load resource: the server responded with a status of 404 (Not Found)
- https://my.domainname.example/assets/logo.png  
Failed to load resource: the server responded with a status of 404 (Not Found)

It looks like in both cases my subdir /chat is not added to the url.

**Comment by birkb** [comment]
With version 0.47 i have to subdir related problems:

1. logo url on logon screen broken
https://hostname.fqdn/subdirimages/logo/logo.svg instead of https://hostname.fqdn/subdir/images/logo/logo.svg
2. logo url in the sidebar after logon is broken
https://hostname.fqdn/assets/logo.png instead of https://hostname.fqdn/subdir/assets/logo.png

**Comment by Dynabix** [comment]
I can confirm that in 0.47 the issue with the videobridge is solved but the issue with the logo still exists like birkb commented above.

**Comment by birkb** [comment]
I have also tested it with 0.47.1 and the problem still exists. These three issues https://github.com/RocketChat/Rocket.Chat/issues/2646 https://github.com/RocketChat/Rocket.Chat/issues/4546 https://github.com/RocketChat/Rocket.Chat/issues/4798 seem to be related.

**Comment by Abraka** [comment]
Same problem with logo in 0.48.2

**Comment by jooola** [comment]
Subdir URL really needs to be fixed, they always are some little problems linked to using a subdir behind a proxy ...

**Comment by jooola** [comment]
I got a 404 too on the logo at connexion screen and at the bottom of the sidebar !

Subdir is written in the URL but a "/" is missing !

HTTPS://host.dn/chatassets/logo.png
 Ans should be :
HTTPS://host.dn/chat/assets/logo.png

Well i really don't know where to look to change those settings !

**Comment by mattlin** [comment]
Same problem with logo in 0.49.4

**Comment by mattlin** [comment]
I can not upload file with using subdir on 0.49.4 I find I can upload file with using subdir on 0.39

**Comment by jooola** [comment]
Still not in 50.1....

Fix this please !

**Comment by mattlin** [comment]
@engelgabriel Hope it will be fixed soon :P  Thanks 💯
