### ISSUE TITLE
Workaround for disabled registrations.

### ISSUE THREAD

**Issue by bugsbunny1996** [RocketChat/Rocket.Chat#5108]
Your Rocket.Chat version: (0.46.0)
New users can still register using OAuth after disabling registration in control panel.

**Comment by cpitman** [comment]
Just to make sure, is the setting "Registration with Authentication Services" disabled?

**Comment by geekgonecrazy** [comment]
@bugsbunny1996 as @cpitman said.  This should do the trick.  I want to say this is intentional.  This way if you want to force your users to use your companies authentication provider you can, and they will be unable to create an account otherwise.
