### ISSUE TITLE
Show uploaded image

### ISSUE THREAD

**Issue by sanbor** [RocketChat/Rocket.Chat#511]
I'd like to see a thumbnail of the upload instead of a link to it.

If the size of the image is big, I'd expect that the thumbnail is a reduced version of the original file.

![screen shot 2015-08-19 at 18 55 07](https://cloud.githubusercontent.com/assets/51512/9370136/52b60b38-46a4-11e5-9117-a8f9d08560e9.png)

**Comment by rodrigok** [comment]
You need to enable Embed on settings page

**Comment by marceloschmidt** [comment]
If you are an admin, go to http://localhost:3000/admin/API and enable Embed option. This is on by default on new installations now. If you are not an admin, you must first set yourself as admin by going to the database and setting `admin: true` under your own Meteor.users record.

**Comment by sanbor** [comment]
Thank you very much for the help. What about adding this information to the README?

**Comment by sanbor** [comment]
I follow all your steps and Embed is enabled, but I still not seeing the embed images. Maybe I should pull again?

**Comment by sanbor** [comment]
Restarting meteor and/or pulling seems that made it work.
