### ISSUE TITLE
Missing useful fields in admin user list

### ISSUE THREAD

**Issue by xiaket** [RocketChat/Rocket.Chat#5110]
Your Rocket.Chat version: latest

I can see from the source code that we have only three hard-coded fields in user list. Please at least add user role and user status(whether user has been deactivated) to the fields.

https://github.com/RocketChat/Rocket.Chat/blob/a4e380814db3a2de2ead34f8529d5ea3c22f97d9/packages/rocketchat-ui-admin/admin/users/adminUsers.html

**Comment by xiaket** [comment]
Moreover, enable sorting on those fields would not hurt anybody.

**Comment by ddoron** [comment]
Just to add some contextual need for this: we have a lot of users join our team, that we then want to deactivate, and we audit that list often. It's awfully tedious to click each user and check their status when you've started using the product for months in a busy business.
