### ISSUE TITLE
Unread messages bar overlaps

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5115]
Since the new design on the upcoming 0.47.0-develop release the "unread messages" bar overlaps the text. ![](http://i.imgur.com/LT8FupM.jpg)

**Comment by sampaiodiego** [comment]
@TheReal1604 are you using a "compact" view mode?

**Comment by TheReal1604** [comment]
@sampaiodiego i use the "cozy" view mode.. but set that back to normal. Maybe that could be related.. i test it out.
