### ISSUE TITLE
Issue with Rate Limiting messages in Rocketchat

### ISSUE THREAD

**Issue by KanoYugoro** [RocketChat/Rocket.Chat#5119]
Your Rocket.Chat version: 0.41.0 (though this is applicable on the latest master)

We've encountered an issue with our own chatbot being ratelimited in RocketChat.  Our company chatbot is a hubot instance that has to be deployed to a separate container for audit purposes.  I've looked into the issue and discovered this section of code which I believe to be the culprit.

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/sendMessage.coffee#L46-L51

It appears that the limit is non-configurable and hardcoded to be no more than 5 messages in a second from any source that is not the internal hubot to rocketchat.

Some ideas for possible solutions:
A toggle on/off for the ratelimiting function
A possible exclusion from ratelimiting for bot users
A ratelimiting configuration per user 

A simple toggle would work for us, but I don't think that is the best long term solution.  My question is, what do the maintainers think the best solution to this issue is?

**Comment by graywolf336** [comment]
@KanoYugoro I agree that bot users should not be rate limited, so I have opened the pull request #5200 which now will not rate limit users who have the role `bot` assigned to them.
