### ISSUE TITLE
Support Gitlab oAuth Provider

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#512]
See http://doc.gitlab.com/ce/integration/oauth_provider.html

@RocketChat/owners maybe create a generic account package so other meteor  app can use it too?

**Comment by Sing-Li** [comment]
Basically done.  

You first get API key and secret from your own GitLab server.

![gitlab1](https://cloud.githubusercontent.com/assets/122633/9426619/3afccae8-491c-11e5-9a04-a55ddea2322e.png)

Then you click the oauth(2) button for GitLab on Rocket.Chat --- on the right --  **we need a logo icon !**

![gitlab2](https://cloud.githubusercontent.com/assets/122633/9426623/59f0d0e8-491c-11e5-96eb-312e81058260.png)

Rocket.Chat then pops up the oauth2 login from GitLab, and you sign in using your gitlab credentials.

![gitlab3](https://cloud.githubusercontent.com/assets/122633/9426625/9b70ff48-491c-11e5-8a95-1daabe97a7d3.png)

Once you logged in, authorize Rocket.Chat to access your GitLab account via API.

![gitlab4](https://cloud.githubusercontent.com/assets/122633/9426628/c78ccc9c-491c-11e5-82d3-511996157175.png)

And you're in.

![gitlab5](https://cloud.githubusercontent.com/assets/122633/9426644/393e0450-491d-11e5-859e-1e0a44f4324f.png)

You can switch back to Rocket.Chat at anytime before the auth token expires.

You can also revoke the auth token from GitLab dashboard at any time.

![gitlab6](https://cloud.githubusercontent.com/assets/122633/9426648/56bf3300-491d-11e5-947d-1fb1037f0fdd.png)

The code is a generic Meteor package, so good for Atmosphere publishing, and enable any Meteor app to use GitLab as an oauth2 provider.

Right now, the code is a  crazy  #(@(#@# mess - hooks everywhere; debug crud all over the place.   I'll tidy up tomorrow and commit.  After some sleep :sleepy:

**Comment by rodrigok** [comment]
Fucking awesome! :laughing:

**Comment by gaving** [comment]
:+1:

**Comment by engelgabriel** [comment]
@Sing-Li rocks! Or Rocket... I dont know.

Either way, how can we not succeed with developers likes this?

**Comment by dosire** [comment]
@Sing-Li Awesome work! Our logo can be found on https://about.gitlab.com/press/

**Comment by Sing-Li** [comment]
Thanks, guys. 

I'm totally inspired by @rodrigok 's  *talk less, write more code that solve problems style* of technical leadership  :+1: 

NOTE:

Before #557 is done,  just go to the file `packages/gitlab/gitlab_common.js`  and change the URL to your own GitLab server.

**Comment by Sing-Li** [comment]
While we have the attention of the GitLab pros -- please take a moment to checkout #525 and comment on what may be possible and desirable.   

We want to do for GitLab  (in the team server, private Internet, and Intranet environments) as much as we will for the Github ecosystem (on the Internet).  Thanks.

**Comment by dosire** [comment]
@Sing-Li I'm on it.

**Comment by Sing-Li** [comment]
@dosire - thank you.

**Comment by rodrigok** [comment]
Thanks @Sing-Li  :smile_cat:

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9471174/8aaf8656-4b25-11e5-8a87-0ed7faf1e7b7.png)

Working on demo

**Comment by Theaxiom** [comment]
Is this documented anywhere? I can't seem to find how to enable this.
