### ISSUE TITLE
No push notifications on Android

### ISSUE THREAD

**Issue by chispaa** [RocketChat/Rocket.Chat#5122]
Your Rocket.Chat version: 0.46.0

Hi,

Since a couple of versions I'm having issues with the notifications (I don't get any).

Re-installing the app registers my GCM but after 2 tries it removes it from the server:

```
5|rocketch | Push: send message "@sergio" via query { userId: '22qthXXXr7WH' }
5|rocketch | Push: send to token { gcm: 'eS5sjoh55rU:APA9XXXXXXXXXXXXXXXXX5DUMgji_-VScc7OCaenXXXXXXXXXXXXXXXXXXXX3gzYlGB1xHcYSJ1KII8HjpW' }
5|rocketch | Meteor ➔ method UserPresence:away -> userId: 22qthALNNrxtBr7WH , arguments:  {}
5|rocketch | Meteor ➔ method push_test -> userId: 22qthXXXr7WH , arguments:  {}
5|rocketch | Push: send message "@sergio" via query { userId: '22qthXXXr7WH' }
5|rocketch | Push: send to token { gcm: 'eS5sjoh55rU:APA9XXXXXXXXXXXX5DUMgji_-VScc7OCaenXXXXXX3gzYlGB1xHcYSJ1KII8HjpW' }
5|rocketch | removing push token eS5sjoh55rU:APA9XXXXXXXXXX5DUMgji_-VScc7OCaenXXXXXXXXXXXXXgzYlGB1xHcYSJ1KII8HjpW
5|rocketch | Meteor ➔ method push_test -> userId: 22qthXXXr7WH , arguments:  {}

```

After the push token is removed, I get: **Error: There are no tokens for this user.**

I'm using the latest version, with push gateway gateway.rocket.chat and node 4.5.

If you need to do any debugging please let me know, thanks!.

**Comment by Nemra1** [comment]
Push notifications not work with me since v44

**Comment by lucasvanhalst** [comment]
Same for me, been broken for months

**Comment by chispaa** [comment]
@Nemra1 and @lucasvanhalst , could you post your logs to check if we have the same issue?. Also try re-installing the app so it registers again and post those logs.

Thanks!, the more info we have the easier it is to fix it.

**Comment by zacharyrohrbach** [comment]
I also am not able to get Android channel notifications. I can get direct message notifications, but not channel. I'm using gatway.rocket.chat and node 4.5.

I have reinstalled the app and that made zero difference. Let me know which logs you want me to send, and I'll gladly provide them!!!

**Comment by mohamedhagag** [comment]
I'm using official docker image with GCM/FCM server key and project number but I always get MismatchSenderId error.

Using gateway.rocket.chat gives error can not connect to gateway.

Any help will be appreciated.

**Comment by mohamedhagag** [comment]
BTW the official docker image have a problem connecting to any https site and it tries to connect to localhost:1080 if I try to request any https site.

This issue prevents the docker container to connect to https://gateway.rocket.chat and prevents the push notifications .

I can't find the reason for this behavior .

**Comment by geekgonecrazy** [comment]
Just to clear something up.  If using the gateway: https://gateway.rocket.chat paired with our official app you do not need to specify the GCM/FCM project info.  

That being said... It shouldn't effect you as long as you have it set to use the gateway.  

When you fail to get notifications do you have your Rocket.Chat instance up on the computer logged in or anywhere else?

**Comment by Nemra1** [comment]
@geekgonecrazy im used official app and no notification since 4.4
also idont know how ican used GCM api or from wher/ after google move to firebase

**Comment by mohamedhagag** [comment]
@geekgonecrazy I troubleshooted the issue with gateway on docker image and found that the docker container can not connect to any https service - this is the rocket.chat docker image.
every time I enter the container shell and try to connect to any https site the connection some how redirects to localhost port 1080.
I'm a newbie with docker but when I try the same with the db container I can connect normally.

Regards,

**Comment by mohamedhagag** [comment]
@geekgonecrazy I'm running the application normally now without docker and it's working fine with push notifications using gateway.rocket.chat.

I will try again with docker after updating it to 48 or dev version or beta version of the image .

**Comment by geekgonecrazy** [comment]
@mohamedhagag what platform do you have docker installed on?  and what version of docker? This doesn't sound like typical out of the box docker behaviour.

**Comment by zacharyrohrbach** [comment]
I just tested with the newest version available at the time of testing (0.48.1). I still do not get channel push notifications on Android (reinstalled the app as well just to be sure) or on my Windows 10 machine (reinstalled the rocketchat client just to be sure). Since I mostly use direct messaging this hasn't been too big of an issue for me, but it's a really crucial thing that needs to get fixed.

**Comment by mohamedhagag** [comment]
@geekgonecrazy I just tested the latest 0.48.0 image and it seems the https connection redirect have been solved as I can access the https://gateway.rocket.chat from the shell after apt-get install wget inside the container.
I'm using Docker version 1.12.3, build 6b644ec installed on ubuntu 16.04.01 LTS using the docker repo.

BTW the notification is not working although, I'm testing and troubleshooting now.

**Comment by mohamedhagag** [comment]
@geekgonecrazy strange - wget and telnet working fine - but curl redirects to the URL defined in my case is chat.dvit.me port 1080 when trying to access https://gateway.rocket.chat or any https site

Also debug logs gives below error:
app.js:471 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: tunneling socket could not be established, statusCode=302] code: 'ECONNRESET' }

**Comment by shellster** [comment]
I don't know how this plays in, but I haven't been able to get alerts for months.  This included me reinstall rocket chat after uninstalling it, and manually removing all left over data (I have root on this phone).  Then today, I blew away my entire operating system and reinstall CyanogenMod 13.  Once I did that, I started getting Rocket Chat alerts again.  I should note that the entire time where I couldn't get alerts before in Rocket Chat, every other application's alerts worked just fine.  Nothing changed on the server between the time I wasn't getting alerts and the time I started getting alerts again.

**Comment by geekgonecrazy** [comment]
Interesting... It kind of sounds like it was the new device id created by google play service being initialized again that caused it to start working again.  That for sure shouldn't be necessary.

**Comment by shellster** [comment]
That is my best guess as well.  Whenever I turned on debug and did a test push from the server, it always said "Sending test push to two devices".  The debug showed the resuts, no errors.  I am assuming that if those device ID's ever change, Rocket Chat is not smart enough to catch this, and continues to push to the old ID's.  It would be awesome, if there was an easy way to force Rocket.Chat to re-register the device id.  There must be a way to do this via mongodb query, if I knew what I was doing.

**Comment by mohamedhagag** [comment]
anyway to get the docker image work with gateway.rocket.chat ?

**Comment by geekgonecrazy** [comment]
@mohamedhagag the docker image works just fine with the gateway.  

As I asked before, what platform do you have docker installed on?

**Comment by mohamedhagag** [comment]
@geekgonecrazy ubuntu 16.04.1 with docker 1.12.3

**Comment by mohamedhagag** [comment]
still with latest build of docker:
`app.js:471 System ➔ error Error sending push to gateway (4 try) -> { [Error: tunneling socket could not be established, statusCode=302] code: 'ECONNRESET' }`

Any solution ?

**Comment by geekgonecrazy** [comment]
@mohamedhagag seems something is wrong with your setup.  I'm not sure what it is.  Like I said before, for sure not an issue with our docker container.  It's being used all over the place and notifications work fine.  

Can you try the docker image on another machine on your network?  Maybe with a different operating system?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Please re-open if still facing this
