### ISSUE TITLE
Improve images on phones

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#5123]
Would be great if the entire background went black when you open a image on the phone. Right now it's almost impossible to notice the (x) to close the image. Also would be very nice if you could zoom in and out on images on the phone.

Both Slack & Discord has these 2 features. Would be great if Rocket chat had it as well.

**Comment by soenkef** [comment]
Great!

**Comment by engelgabriel** [comment]
closed in favor of https://github.com/RocketChat/Rocket.Chat/issues/2278
