### ISSUE TITLE
LDAP-Users are not automatically verified

### ISSUE THREAD

**Issue by dmeier86** [RocketChat/Rocket.Chat#5124]
Your Rocket.Chat version: 0.46.0

Hi,

i have a problem with LDAP-Users on my RocketChat installation:
They are not automatically verified - wich is (IMHO) not what everyone expect.

If you handle your user-accounts via LDAP they exist and should not manually verified.

If there a trick to verify all users automatically - or an option in the admin-interface which allows me to verify every (new) user?

Thank you!

**Comment by DalePayman** [comment]
Maybe anyone else have the same issue?
All Users come from LDAP.
Registration is possible - but only with the secret link.

Passwort-Verification is disabled.
Mailverification is disabled.
Activate new users manually is disabled too.

That's why no user is verified and because of that the system won't send mails to them e.g. if you mention a user who's offline...

Because of my system-settings all users should be verified automatically!

Thx!

**Comment by VedranOP** [comment]
That would be a nice option to take windows login/pass automatically.

**Comment by DalePayman** [comment]
@engelgabriel 
i think this is a bug and it shoud be in the next milestone?!

**Comment by Abraka** [comment]
Its definitely a bug. Viz. https://github.com/RocketChat/Rocket.Chat/issues/5353

**Comment by Abraka** [comment]
Any progress here? When we can expect this functionality?

**Comment by DalePayman** [comment]
It's already implemented. 
I'm running 51

**Comment by Abraka** [comment]
I have 52 and nothing change. User get login dialog after visiting default page of rocket chat instead of been logged in automatically. Is there in admin interface some new settings for this? What I missing?

**Comment by DalePayman** [comment]
This ticket never was about auto-login.

**Comment by reetp** [comment]
I have this exact issue on 0.52 - happened an hour ago !

Add a new user in LDAP
Go to Rocket and attempt to login with new user id and password and it fails
Go to Admin, new user is present but has to be activated.
Activate new user and they can then login

Note we have no SSO or other confusing artefacts ;-)

Anonymous login etc is disabled. We have one local 'system' user to prevent us getting locked out and all other users are authenticated via LDAP

**Comment by reetp** [comment]
Just moseying through settings and I noticed Accounts/Registration/Manually approve new users and wondering if this would affect anything re LDAP users?

I need to do a test but can't at the minute.

**Comment by Hudell** [comment]
LDAP are auto verified now.
