### ISSUE TITLE
logo (svg, png, jpg) is resized

### ISSUE THREAD

**Issue by VedranOP** [RocketChat/Rocket.Chat#5125]
Your Rocket.Chat version: 0.46.0
logo (svg, png, jpg) is resized in aplication for Windows.
How to make it normal size?

**Comment by engelgabriel** [comment]
Can you please share a screenshot?

**Comment by karlprieb** [comment]
Hi @VedranOP This is still happening?

**Comment by VedranOP** [comment]
@karlprieb everything works fine! Sorry for delayed answer.
