### ISSUE TITLE
Remove add Server + sign

### ISSUE THREAD

**Issue by VedranOP** [RocketChat/Rocket.Chat#5126]
Your Rocket.Chat version: 0.46.0
I would like an option that users cannot add server, when 1 server is added

**Comment by Merryfurr** [comment]
On what platform? Desktop or Mobile?

**Comment by VedranOP** [comment]
On the Desktop version. 
If I plan it for internal business use we only have one server and it looks more slick and simple without option we don't need.

**Comment by Nemra1** [comment]
With u with this idea

**Comment by graywolf336** [comment]
It's already possible on the desktop. `View -> Toggle Server List`

**Comment by VedranOP** [comment]
I meant as a feature on Admin interface in website GUI. This option each PC will have to adjust?

**Comment by graywolf336** [comment]
Yes. You will have to create your own customized version if you're wanting to default to one.

**Comment by VedranOP** [comment]
Ok, thank you a lot. I have to say RocketChat is awesome...
