### ISSUE TITLE
Can not upload .py and .sql file from rocketchat client

### ISSUE THREAD

**Issue by nadeemshahzad** [RocketChat/Rocket.Chat#5127]
1.3.1
I can not share .py and .sql file from rocktchat client running on windows,mac and linux, files having these extension does not appear while selecting to upload.
Mimetypes is enabled in server option as using browser login  I can upload these files.

**Comment by graywolf336** [comment]
Does it work on the web browser? @nadeemshahzad

**Comment by vmalaga** [comment]
Hi we have the same problem, can't share .py files. I have tried at Accepted Media Types with

- application/x-python
- text/python

**Comment by fhoda** [comment]
@nadeemshahzad Did you try adding 

application/x-sql

Accepted Media Types in your File Uploads settings?

**Comment by geekgonecrazy** [comment]
Can you try this with a newer version of Rocket.Chat? Please re-open if still happening

**Comment by r-chris** [comment]
This is still happening for me with the latest version.

**Comment by geekgonecrazy** [comment]
Can you provide more details with what it does when you try to upload?

**Comment by prashanthym** [comment]
Still I am facing the same issues while uploading .py files on rocketchat  0.72.3

**Comment by BjoernLudwigPTB** [comment]
For anybode still having this problem, there is this open issue #14144 where the problem still is discussed.
