### ISSUE TITLE
Ability to sticky/pin channels to top of channel list by admin

### ISSUE THREAD

**Issue by doomdance** [RocketChat/Rocket.Chat#513]
The Admin should be able to flag and order specific channels that will always appear at the top of the channel list. All other channels appear below that list. The admin should be able to pin user created channels as well.

Pretty much this:
![pin-stickychannel](https://cloud.githubusercontent.com/assets/2876364/9372299/aa4adfce-46a2-11e5-91ae-300352a2dee3.png)
##

**Comment by graywolf336** [comment]
:+1: I like this idea a lot, would be very useful.

**Comment by cotamix** [comment]
I like this too. Can help to keep order.

**Comment by doomdance** [comment]
Adding to this, if the channel is pinned by an admin, it may be a good idea to prevent the creator from renaming.

**Comment by AdrianoCahete** [comment]
> Adding to this, if the channel is pinned by an admin, it may be a good idea to prevent the creator from renaming.

Or prevent remove from pinned list.

**Comment by doomdance** [comment]
Just bumping to see if this is something that was put on the back-burner or not. Would still really love to see this feature!

**Comment by danborufka** [comment]
+1

**Comment by itaditya** [comment]
Hey is anyone working on this, I would love to try this one

**Comment by raldjr** [comment]
Adding on to this idea, would be great to have a on/off setting for this. Either pinned channels be dictated by admin or users get to have their own pinned channels that are important to them. So each user has their own list of pinned channels.

**Comment by Hudell** [comment]
@raldjr Users can already pin their own channels, by setting them as favorite and checking the "Group Favorites" option on the sort popup.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.

**Comment by geekgonecrazy** [comment]
Please feel free to open a topic on our forum in the feature request section to properly detail this proposed feature.
