### ISSUE TITLE
Feature Request: Need ability to restrict access to username dialog

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#5131]
Your Rocket.Chat version: 39

Our OAuth provider sets the "username" attribute in the JSON returned from the user profile request and we would prefer only admins be able to change that value.  However at initial login, the user is presented with a dialog that allows them to change it.  Currently, after the initial login the user's ability change the username in their profile can be restricted by admin setting.  We would like a similar capability that avoids displaying the username dialog on initial login.

**Comment by rodrigok** [comment]
@howellsd I'm working on it right now. Can I have access to your OAuth with an account for tests? If yes can you send me the OAuth confit at https://demo.rocket.chat/direct/rodrigo.nascimento ?

I'm working on it at https://github.com/RocketChat/Rocket.Chat/pull/5146

Thanks

**Comment by howellsd** [comment]
Hi Rodrigo,

I just installed your updates with 0.48.1.  The ability to specify the username via template and restrict access to the dialog to set it works great, but I’m running into a problem.  I can create new users via OAuth with no problem, but I can’t login a second time with those users.  There doesn’t appear to be any errors in the logs (turned logging up to errors + debug but no luck).  Is there something new I’m missing in the server or custom oauth config that’s causing the issue?

Scott Howell

On Dec 7, 2016, at 11:31 AM, Rodrigo Nascimento <notifications@github.com<mailto:notifications@github.com>> wrote:


@howellsd<https://github.com/howellsd> I'm working on it right now. Can I have access to your OAuth with an account for tests? If yes can you send me the OAuth confit at https://demo.rocket.chat/direct/rodrigo.nascimento ?

I'm working on it at #5146<https://github.com/RocketChat/Rocket.Chat/pull/5146>

Thanks

**Comment by howellsd** [comment]
I think I figured out the issue, I can’t seem to have an OAuth user log back in after initial creation until “Merge Users” is enabled in the custom oauth config.  Is that how its intended to work?

Scott

On Dec 13, 2016, at 3:53 PM, Scott Howell <showell@solidyn.com<mailto:showell@solidyn.com>> wrote:

Hi Rodrigo,

I just installed your updates with 0.48.1.  The ability to specify the username via template and restrict access to the dialog to set it works great, but I’m running into a problem.  I can create new users via OAuth with no problem, but I can’t login a second time with those users.  There doesn’t appear to be any errors in the logs (turned logging up to errors + debug but no luck).  Is there something new I’m missing in the server or custom oauth config that’s causing the issue?

Scott Howell

On Dec 7, 2016, at 11:31 AM, Rodrigo Nascimento <notifications@github.com<mailto:notifications@github.com>> wrote:


@howellsd<https://github.com/howellsd> I'm working on it right now. Can I have access to your OAuth with an account for tests? If yes can you send me the OAuth confit at https://demo.rocket.chat/direct/rodrigo.nascimento ?

I'm working on it at #5146<https://github.com/RocketChat/Rocket.Chat/pull/5146>

Thanks
