### ISSUE TITLE
UI has changed in terms of colors and behavior 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5133]
I Noticed few changes in the way the tool looks and feels, 
1- little bit darker..
2- the "unread messages" gets on the top of the users name and it hides a portion - u cant click on setting wheel until it disappears.. 

![image](https://cloud.githubusercontent.com/assets/12454319/20954368/aed71fbc-bc08-11e6-9c0e-c937609aaf30.png)

3- tables looks different (better CSS applied?? ) it looks good 

Your Rocket.Chat version: (.47)

**Comment by MartinSchoeler** [comment]
@IQ2022 Yes we are making some changes in the ui colours take a look in #5040 #4803 and #5089

**Comment by IQ2022** [comment]
yes but this "unread messages" is really bad it goes over user name or create a wide space.. hope you guys fix it

**Comment by karlprieb** [comment]
Fixed here #5117
