### ISSUE TITLE
Regexp / wildcards within highlight words.

### ISSUE THREAD

**Issue by tonobo** [RocketChat/Rocket.Chat#5135]
Your Rocket.Chat version: 0.47.0

Due to the following pull request https://github.com/RocketChat/Rocket.Chat/pull/2223 and https://github.com/RocketChat/Rocket.Chat/pull/2236 [(diff)](https://github.com/RocketChat/Rocket.Chat/pull/2236/files#diff-0925f8763a039a22e134ac95bbb98349R20).
It would be nice to support wildcards or regular expressions within highlight words.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.

**Comment by mychecknix** [comment]
I have over six thousand words for highlighting. It would be less than 20 if regexp / wildcards would work for highlight words. Changing a list of 20 will be much easier than a list of over six thousand!!!
Please re-open this issue.

**Comment by Crayder** [comment]
So it's been a few years now. This would still be nice. For example, my last name's is in the middle of numerous words. I can't tell Rocket Chat to match it only if it's a full word.
