### ISSUE TITLE
Ability to delete multiple users at once

### ISSUE THREAD

**Issue by alexmsierra** [RocketChat/Rocket.Chat#5136]
Your Rocket.Chat version: 0.46.0
 Hi all,

Is there a possibility to add select option so that you could delete several users at the same time? 
At the moment you have to select every user and delete it.

Thank you,
Alex

**Comment by VedranOP** [comment]
I agree on such feature. Cheers!

**Comment by hughlroberts** [comment]
+1

**Comment by amaranto** [comment]
+1

**Comment by fenelon** [comment]
+1

**Comment by peylight** [comment]
+1

**Comment by kiblik** [comment]
+1

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by keithhenning** [comment]
+1
