### ISSUE TITLE
Improved email notification

### ISSUE THREAD

**Issue by fenuks** [RocketChat/Rocket.Chat#5137]
Your Rocket.Chat version: 0.47.0

I search if there is similar issue to this, and I didn't find one. Sorry if it's a duplicate. 

It would be really useful to have following configuration options in rocketchat.

* sending email notification to online users (it's easy to miss browser notification, and with numerous tabs opened – notice that rocketchat tab appearance indicate new unread messages)
* global option to enable sending email notification for messages with `@all`, as far I understand, now you can either get email notifications for messages mentioning you, or all messages; it would be very useful to have more granular options for administrator; of course users should have possibility to override global setting in their account and/or channel settings. Thanks.

**Comment by Mte90** [comment]
As I can see when @all is used the people not receive an email notification so is very unpleasure because after all is a notification to all the users also if not mentioned.

**Comment by phate1** [comment]
+1 for this have @all send an email to all would great

**Comment by marceloschmidt** [comment]
`@all` is already sending e-mail notifications. With the auto-away feature implemented, we don't think we should ever send e-mail notifications to online users.
