### ISSUE TITLE
Chat channels complete control in WEB UI

### ISSUE THREAD

**Issue by VedranOP** [RocketChat/Rocket.Chat#5138]
Your Rocket.Chat version 0.47.0
Would be nice that admins in administration/rooms can add a room(department) and then assign(department workers) and other settings.

**Comment by graywolf336** [comment]
Please explain what you mean. Livechat has departments already

**Comment by VedranOP** [comment]
Sure. Web GUI/Administration/Rooms. I would like to create rooms and add users there.

**Comment by graywolf336** [comment]
That's possible, please try out the [demo](https://demo.rocket.chat) to see what is possible.
