### ISSUE TITLE
Users can generate public rooms by switching room-type

### ISSUE THREAD

**Issue by DalePayman** [RocketChat/Rocket.Chat#5141]
Your Rocket.Chat version: 0.46.0

if you disable "create-c" under
/admin/permissions to role "user"
users are not longer able to create public rooms.
cool!
but...

If they can create private rooms, they are able to switch the room-type to public.. 
so - this option is not efficient enough.

you have to take the "edit-room" role from "owner" so they're can't do switch room-types anymore BUT they can edit nothing else on there own room wich is uncool.

**Comment by graywolf336** [comment]
Just submitted a pull request to fix this, #5143
