### ISSUE TITLE
How to send an email to all users

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#5142]
I see in the documentation that an admin can send an email to all users.  How do I actually do this?

It says it in permissions: 
access-mailer	Accessible from Administration -> Mailer. Permission to send mass email to all users.

https://rocket.chat/docs/administrator-guides/permissions/

**Comment by graywolf336** [comment]
https://rocket.chat/docs/administrator-guides/mailer/ 😆 RocketChat -> Admin -> Mailer

**Comment by flantascience** [comment]
Well I feel stupid.  I had used that for sending test emails to myself to
make sure the mailer worked, didn't even occur to me it's actual purpose
was to reach all users.

Thank you!

Jim Flannery

jim-flannery.com
p. 860-212-8862
e. jim@jim-flannery.com
s. jim_flannery

**Comment by graywolf336** [comment]
No worries, as we do need to improve the documentation for it better. :)

**Comment by jooola** [comment]
Could someone correct the link , its a 404 for now ...

**Comment by olearytd** [comment]
@jooola I found the new doc but its empty...

https://rocket.chat/docs/administrator-guides/notifications/mailer

**Comment by jooola** [comment]
Yup ... Maybe looking in the old files remaining on the git hub that we can use

**Comment by andysavage** [comment]
Hi, Could someone post instructions here, please? A search returns this page but no actual page with instructions, and the 2 above are 404 so at least if it is here people will be able to find it. Thanks
