### ISSUE TITLE
ufs/GridFS file upload does not work in Rocket 0.47.0

### ISSUE THREAD

**Issue by danielmorlock** [RocketChat/Rocket.Chat#5144]
Upload a file results in: 
![file-upload-rocket](https://cloud.githubusercontent.com/assets/1263320/20978626/d6d66634-bca9-11e6-97e2-31f447beeb8d.jpg)

Log file does not report any errors:
```json
rocketchat_lib rocketchat_lib.js:1011 Meteor <E2><9E><94> method ufsCreate -> userId: r3GAPpbHTGcpjtf3g , arguments:  { '0': 
   { name: 'file-upload.jpg',
     size: 160324,
     type: 'image/jpeg',
     rid: 'GENERAL',
     store: 'rocketchat_uploads' } }
rocketchat_lib rocketchat_lib.js:1011 Meteor <E2><9E><94> method ufsComplete -> userId: r3GAPpbHTGcpjtf3g , arguments:  { '0': 'CCbCWNApKz3qxth6k'
  '1': 'rocketchat_uploads',
  '2': '98F89adA9b' }
rocketchat_lib rocketchat_lib.js:1011 Meteor <E2><9E><94> method sendFileMessage -> userId: r3GAPpbHTGcpjtf3g , arguments:  { '0': 'GENERAL',
  '1': null,
  '2': 
   { _id: 'CCbCWNApKz3qxth6k',
     type: 'image/jpeg',
     size: 0,
     name: 'file-upload.jpg',
     url: '/ufs/rocketchat_uploads/CCbCWNApKz3qxth6k/file-upload.jpg' } }
```

In error.log, I get this:
```
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
```

Please let me know how I can investigate this further.

**Comment by danielmorlock** [comment]
Furhter investigation. The upload size is 0:
```json
{
    "_id" : "CCbCWNApKz3qxth6k",
    "name" : "file-upload.jpg",
    "size" : 0,
    "type" : "image/jpeg",
    "rid" : "GENERAL",
    "store" : "rocketchat_uploads",
    "complete" : true,
    "uploading" : false,
    "extension" : "jpg",
    "progress" : 1,
    "userId" : "r3GAPpbHTGcpjtf3g",
    "path" : "ufs/rocketchat_uploads/CCbCWNApKz3qxth6k/file-upload.jpg",
    "token" : "9B2A89497a",
    "uploadedAt" : ISODate("2016-12-07T17:18:31.753Z"),
    "url" : "/ufs/rocketchat_uploads/CCbCWNApKz3qxth6k/file-upload.jpg"
}
```

**Comment by rodrigok** [comment]
@danielmorlock it's working ok for me. Do you have GraphicsMagic or ImageMagick installed?

**Comment by TheReal1604** [comment]
@rodrigok Working for all of my 0.47.0 Instances also. (with mongodb replicaset backend and with single hosts..)

But sometimes i got the same issue, then i have to refresh the site and all is looking fine. Hm.

**Comment by danielmorlock** [comment]
@rodrigok We have ImageMagick installed.

**Comment by danielmorlock** [comment]
Browser: www-client/chromium-54.0.2840.100
DB: Mongo 2.6.12
OS: Gentoo, Kernel 3.18.9-hardened

**Comment by danielmorlock** [comment]
Update: It seems that only JPEG files cannot be uploaded. I successfully tested a *.txt and *.png and *.pdf file.

**Comment by danielmorlock** [comment]
Guys, what are you using to convert uploaded images? Where do you convert them? I think the problem is that `convert` is not properly executed and/or returns an error. How can I investigate this?

**Comment by danielmorlock** [comment]
I was able to find the reason. We had no jpeg support enabled in ImageMagick. This was clearly a dependency mistake and not a bug of RocketChat. But shouldn't RocketChat complain if the conversion of an upload fails? I think this is pretty much transparent to RocketChat - but the error investigation was really hard and wasted a lot of time. A quick check for a `file_size > 0` after the conversion would have helped me a lot.
