### ISSUE TITLE
Unread Messages bar not clearing

### ISSUE THREAD

**Issue by agentirons** [RocketChat/Rocket.Chat#5145]
Your Rocket.Chat version: 0.47.0

After updating our server to .47 yesterday, the grey unread messages bar in the chat window is no longer disappearing after seeing the new messages. Typing a response and hitting enter does clear it.

![screen-shot-2016-12-07-at-09 38 52](https://cloud.githubusercontent.com/assets/17654661/20979433/c20e2626-bc61-11e6-822f-e6dc7404d734.jpg)

**Comment by engelgabriel** [comment]
@agentirons, when you see it, it only changes colors. When you change rooms, it disappears. This has been the behaviour from the beginning, we just changed the thickness.

**Comment by agentirons** [comment]
Something else is happening then, because it doesn't disappear when changing rooms. The only thing that makes it go away is to enter a response or reload the interface.

**Comment by agentirons** [comment]
For anyone interested, this is still the behavior I'm seeing in 0.52.0 using a browser interface. I just watched the unread messages bar change color as @engelgabriel mentioned, but the actual bar doesn't disappear when changing rooms.

**Comment by saeedjalali1** [comment]
```UNREAD MESSAGES``` not changing when language change. I think the localization not working for this

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of: https://github.com/RocketChat/Rocket.Chat/issues/9319. If you think this is something different and you can still produce your issue on the latest stable version of Rocket.Chat, please get back to me!

Cheers
Thomas
