### ISSUE TITLE
Consider adding feature Emoticon access to read only channels.

### ISSUE THREAD

**Issue by tempestb** [RocketChat/Rocket.Chat#5147]
So this is an improvement suggestion.

Right now, a lot of Rocket Chat users have administrative channels that they use to send announcements and have them locked to not include replies or new posts from the public.

However, on a per channel basis, it would be nice if they could choose to allow the public to post an Emoticon but not anything else.

For instance, you might make an announcement that says, "We released Rocket Chat version 4000." and then we could click on the :thumbsup: icon.  Or any of the various other icons, to show our appreciation for this announcement, while also respecting the limits of the room's access to prevent unwanted chatter.

I think administrators like the feedback, but don't want the clutter of responses that are better posted in other channels.  But of course, making this an option for the channel would be the best solution, so that those who don't want any activity would not see the emoticons, but those that do want them, can see them.

Thanks for considering this idea!

**Comment by MartinSchoeler** [comment]
@tempestb i think a emoji reaction would fit best in your scenario, because it won`t clutter the channel and its easier to see.
![screenshot from 2016-12-08 08-52-13](https://cloud.githubusercontent.com/assets/20868078/21007378/bcee5b3a-bd23-11e6-999a-83871ef9c05f.png)

**Comment by tempestb** [comment]
Yes, that is what I meant.  Sorry for the confusion.  That would be a great feature.


-------- Original message --------

**Comment by graywolf336** [comment]
@tempestb Check out the pull request: #5189
