### ISSUE TITLE
Per-Room Collaborative Document Editing

### ISSUE THREAD

**Issue by nathan-at-least** [RocketChat/Rocket.Chat#5156]
Wouldn't it be awesome if there were a plugin such that:

* each room had an associated set of documents that users could upload.
* a document browser or a single document could be viewed in the same context as the chat (perhaps the document is at the top of the window while chat log is below.
* users could collaboratively edit documents.
* users can individually choose which document associated with a room they are viewing, or they can turn off that view.
* the state of which document is being viewed is part of the URL (so for example, if a user is in a channel and asks what document others are discussing, they can paste the URL and by clicking on that the room view showing the document is rendered. The result would be the same if the URL were posted elsewhere such as an email.)
* upload and editing access controls were sensible.
* documents are in open standard formats and any particular revision can be downloaded by users.
* Bonus: There's some kind of revision tracking, so that individual users can view prior revisions in their individual view. They can download those revisions separately.

For example, if eveyone on an engineering project could collaboratively edit flow or component diagrams with an associated discussion, this would be an awesomely useful feature!

Subsets of the feature ideas above could still be invaluable, for example if there were no collaborative editing, but the ability for someone to upload newer revisions of a diagram to the channel this would still be a great first step. Another potential way to simplify the scope is pick a single document format (eg: I obviously like diagrams) and focus on that first instead of "any document".

**Comment by rasos** [comment]
Connect Rocket.Chat and nextcloud+collabora with LDAP, where you manage the groups. Needs some more effort to map groups, see https://github.com/RocketChat/Rocket.Chat/issues/5252

**Comment by lucasvanhalst** [comment]
I don't think this sort of functionality should be included in a chat platform, just use google docs instead. They've got pretty much what you want, it even has a chat function as well.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue as this feature is not on our short-term roadmap.
