### ISSUE TITLE
My Account navbar hover issue

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#5161]
Your Rocket.Chat version: Demo
When you open the my account navbar and hover the mouse over the options, this happens: 
![screenshot from 2016-12-09 13-09-07](https://cloud.githubusercontent.com/assets/20868078/21055331/2d24084c-be18-11e6-8170-7c7accbffa2f.png)
all of the options are highlighted

**Comment by Molle500** [comment]
@MartinSchoeler @karlprieb Someone already fixed this and made a PR.
It's actually already fixed on demo  . Dont remember the PR number tho

**Comment by karlprieb** [comment]
@MartinSchoeler it still happening to you?

**Comment by MartinSchoeler** [comment]
No looks like someone fixed it, i will close this issue now.
