### ISSUE TITLE
S3 Frankfurt Region

### ISSUE THREAD

**Issue by jsenon** [RocketChat/Rocket.Chat#5163]
When I tried to download image, uploaded in S3 Frankfurt region I receive error :
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

Does Rocket.chat will support v4 for authentication?
http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

Linked with #3099

**Comment by engelgabriel** [comment]
Update https://github.com/RocketChat/Rocket.Chat.Docs/pull/144 when fixed.

**Comment by engelgabriel** [comment]
Closed in favor of #5163

**Comment by jsenon** [comment]
@engelgabriel In favour of #3099 instead of 5163?
