### ISSUE TITLE
Able to react on message that has been deleted

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#5164]
Your Rocket.Chat version: develop (12/09/16)

Message is deleted and can still add / remove reactions.

![image](https://cloud.githubusercontent.com/assets/51996/21059473/2f7ab8b2-be08-11e6-82af-e85ccac438bf.png)

**Comment by marceloschmidt** [comment]
That's so you can show your satisfaction in the message being deleted 😂

**Comment by geekgonecrazy** [comment]
😆  I almost can't argue with that logic haha
