### ISSUE TITLE
Message bar often wrong size after switching channels

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#5168]
The message bar is very often when switching to another channel the wrong size. It's two lines instead of the normal 1 line default. So you always have to press backspace or start typing to reset it to normal.
This happens both on our server (.43) but also here on demo.

See the gif below ( Some of message bar is twice as big)
![animation](https://cloud.githubusercontent.com/assets/17712562/21072941/804563c6-bed2-11e6-8e2c-07e1d7c9f2e7.gif)

**Comment by rodrigok** [comment]
@Molle500 We know this bug, but we don't know how to reproduce it to debug and test. Do you know how to reproduce it always?

**Comment by Molle500** [comment]
I dont know how to exactly reproduce it but it happens very very often. I think it's happening more often on the desktop client compared to the browser client but i´m not 100% sure

**Comment by MartinSchoeler** [comment]
@Molle500 have you seen this bug recently?

**Comment by Molle500** [comment]
@MartinSchoeler I think this is fixed. I will close it and re-open if i see the bug again.
