### ISSUE TITLE
Share location permanently through the app

### ISSUE THREAD

**Issue by itisNathaniel** [RocketChat/Rocket.Chat#517]
In the way that Apple's Find my Friends does and allows permanent location sharing within the app.
Could this be implemented in both the desktop and phone apps where cross platform sharing can then happen where the user chooses what device is their primary one to track whether their phone, tablet or laptop.

I understand this may be niche in terms of userbase using it but I think it would be a useful feature to add.
##

**Comment by engelgabriel** [comment]
I like the idea

**Comment by Sing-Li** [comment]
Added value for family chats.   Locate your kids.  Where in the city are your elderly parents :bulb:

**Comment by itisNathaniel** [comment]
That's exactly the use I was thinking of, Sing-Li!

**Comment by Sing-Li** [comment]
:smile:  @itisNathaniel  

I hope it is hackathons that you are thinking of.  Otherwise .... @engelgabriel  -  we have a friendly competitor :grinning:

**Comment by itisNathaniel** [comment]
At the moment I'm still trying to get a grasp of swift and I will then move to javascript. When I have enough of an understanding to be of assistance I'll try to come help build more features into this awesome project. 
At the moment I think I would be more of a hinderance than help though.

**Comment by Sing-Li** [comment]
:+1:  Thanks in advance @itisNathaniel 
To exercise your Swift chops.  You may want to consider helping our [iOS team](https://github.com/RocketChat/Rocket.Chat.iOS)  (from the beautiful island of Crete)  out on hammering out the high performance native mobile app using Swift 2 on iOS 9  <-  which is pretty much new to everyone not working at Apple  :grinning:

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
