### ISSUE TITLE
"Old Version" in iOS App

### ISSUE THREAD

**Issue by thiesschneider** [RocketChat/Rocket.Chat#5174]
Hi,

I am running the latest Developer Version of Rocketchat (5c311c8) and cant connect via the iOS app. The update process of the App does not work and if I try to add the server again it says that I should contact the admin of my server (me hehe) to update to the latest Rocket.Chat version.

Any ideas?
thx in advance!

**Comment by TheReal1604** [comment]
Type only https://chat.domain.de don't use a ending / or something else.

**Comment by thiesschneider** [comment]
Thats the way I do it.
My issue looks similar to https://github.com/RocketChat/Rocket.Chat/issues/5014

**Comment by TheReal1604** [comment]
@thiesschneider Wow, doesn't know that this was a showstopper bug in 0.46.0 and above! Thanks for the info. Got this when i type in the server url and /home at the ending..

**Comment by rodrigok** [comment]
@thiesschneider Can you share your domain with me, if you don't want to do it as public you can contact me at https://demo.rocket.chat/direct/rodrigo.nascimento 

I need to try to connect to your server to see what's happening.

**Comment by rodrigok** [comment]
@thiesschneider It's not necessary, I found the problem, fixing now.

**Comment by thiesschneider** [comment]
:) thanks wasnt reading your previous post

**Comment by rodrigok** [comment]
@thiesschneider fixed, please let us know if it's working for you too.

And thanks by reporting 😄

**Comment by hadifarnoud** [comment]
@rodrigok does this mean a simple iOS app update will fix the issue? I'm on 0.46.0

**Comment by thiesschneider** [comment]
It is getting better... but not perfect, yet ;)
Now it is stuck at the point where it shoud download the data.
It seems to connect (but I cant see anything in the logs) but I see the "downloading data" screen forever...

**Comment by mrplow** [comment]
This is definitely the same as #5014 
The commit pushed added /api/info back but it's still stuck at downloading data.
@rodrigok mind if I pm you my server address?
