### ISSUE TITLE
Snap: Newest releases for ARM architectures - Raspberry Pi

### ISSUE THREAD

**Issue by redcap3000** [RocketChat/Rocket.Chat#5178]
iOS mobile application unable to connect to raspberry pi ubuntu.

Cites: 

**The server ***http://myserver.com*** is running an out of date version. Please ask your server admin to update a new version of Rocket.Chat**

**Comment by geekgonecrazy** [comment]
@redcap3000 what version do you see when you goto Administration->Info ?

**Comment by redcap3000** [comment]
0.39.0

**Comment by engelgabriel** [comment]
@redcap3000 can you try the version 0.47.0?

**Comment by redcap3000** [comment]
Is it possible? Its the ubuntu snap needs to be updated with the latest versions, and i'm not familiar enough ubuntu snappy to do that.

**Comment by geekgonecrazy** [comment]
@redcap3000 we actually need to release a new version of the raspberry pi version.  Currently its not automated like we have it for other platforms.  We were waiting on a few things to line up before we could automate it.  I'll check on the status and see if we can do this.

**Comment by redcap3000** [comment]
Thanks much... snappy is neat, but there documentation behind creating /editing them is sparse and almost non-existant for IoT devices. Hopefully Ubuntu see's the value in its creations and starts documenting it then we can all be happy, but I appreciate your help.

**Comment by geekgonecrazy** [comment]
@redcap3000 we love IoT devices like the raspberry pi.  We're continuing to work on getting these builds. 

I'm going to rename this issue so we can track getting automated builds for the raspberry pi and other arm devices.  Hopefully it'll also make it easy for us to get you updated when we get it there.

**Comment by The-Big-V** [comment]
Is there anything further on this? I notice a new amd64 snap was released today (19 April), but armhf still won't update past 0.39

**Comment by geekgonecrazy** [comment]
@The-Big-V I'm working on this still.  Automating is still a bit off.  But working on getting an updated snap manually published for you guys. I'm currently away from my arm server until next week. I'll send an update here as soon as I'm able to do either

**Comment by bstone108** [comment]
anything I can do to help with these builds?  I'm setting up a rpi to use as an active public chat server for me and a bunch of friends.  Don't mind testing a bit.  built on ubuntu core.

**Comment by geekgonecrazy** [comment]
if you want to give it a try you can download and use the classic snap on ubuntu core using:
`sudo snap install classic --edge --devmode`

Then type: `sudo classic` and it'll drop you into a chroot where you can try building.  The code for the multi-arch snap is currently at: https://github.com/rocketchat/rocketchat-server-snap

Once I get it all working i'll be merging the changes there here into this repo so builds will be done automatically.  I'm available in the [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) channel on our demo server if you wanna talk a bit more.

**Comment by bstone108** [comment]
attempting this now.  Will see if I can resolve any compile issues and let you know.

**Comment by geekgonecrazy** [comment]
Last night I managed to get an updated snap for raspberry pi.  Right now its in the edge channel.  Use at your own risk.  :) Make sure to back up files.  `sudo snap refresh rocketchat-server --edge`

**Comment by bstone108** [comment]
well until I get a backup power system setup for the pi,  won't be using it production anyway,  it doesn't recover at all from power failures.  pi boots,  rocketchat doesn't work and requires reinstall everytime power is lost.  to be expected honestly since the pi does badly with power outages.  Going to try and build a snap with all needed python scripts to support the backup system I'm using for safe shutdowns if power is lost.  basically meaning until done,  at own risk is perfectly fine.

**Comment by geekgonecrazy** [comment]
Sounds like an awesome snap.  As a snap enthusiast would be very curious to see what you end up with :+1:

**Comment by bstone108** [comment]
it's nothing fancy.   it's this.  https://www.amazon.com/gp/product/B06XKLN3L9/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
it just finished on kickstarter.  It has some python scripts to talk to the hat and read battery levels and safely shut down the pi when battery is low.  going to see if I can package them as a snap and get everything working.  don't know if I can but will be fun to try.  this way it's snap install the package and pop on the battery hat.  I like that it uses a very common battery size so it's easy to get replacements.

**Comment by bstone108** [comment]
fyi, I think I bought the last one, it now shows out of stock :(

**Comment by geekgonecrazy** [comment]
Awesome!  Sounds like you might need gpio and shutdown interfaces. I hangout in [#raspberrypi](https://demo.rocket.chat/channel/raspberrypi) and [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) have done a bit of snapping and would be glad to lend a hand if you need it.

**Comment by bstone108** [comment]
will look you up if I run into trouble.

**Comment by bstone108** [comment]
well,  I got this far...  time to find out why.

Preparing to build caddy
Building caddy
go install ./github.com/mholt/caddy/...
# github.com/lucas-clemente/quic-go/h2quic
github.com/lucas-clemente/quic-go/h2quic/client.go:247: res.Uncompressed undefined (type *http.Response has no field or method Uncompressed)
Command '['/bin/sh', '/tmp/tmpnta_0642', 'go', 'install', './github.com/mholt/caddy/...']' returned non-zero exit status 2

**Comment by geekgonecrazy** [comment]
@bstone108 will be pushing some changes shortly.  But basically requires a newer version of go.  My solution was to just download the compiled copy instead.  That way I didn't have to worry about the version of go

**Comment by bstone108** [comment]
ubuntu repository doesn't have newer version?  is their a location you can get source from and compile directly on pi during build time?

**Comment by geekgonecrazy** [comment]
@bstone108 check out: https://github.com/RocketChat/Rocket.Chat/pull/6842 but no caddy is not in the ubuntu repos yet.

**Comment by bstone108** [comment]
pulled,  testing compile in a clean environment.  lets see what breaks.  :)

**Comment by geekgonecrazy** [comment]
0.55.1 is now on the stable channel for armhf and will automatically get new versions as we cut them.
