### ISSUE TITLE
'katex is not defined' error since 0.47.0 update

### ISSUE THREAD

**Issue by adirwilliamson** [RocketChat/Rocket.Chat#5179]
katex seems to be broken in the 0.47.0 release. When you try to do a katex expression you get a 'katex is not defined error'. Using the official docker image of rocket.chat. I rolled back to the 0.46.0 image and it seems to work fine, so seems like an issue with the new release.

**Comment by engelgabriel** [comment]
@rodrigok can you take a look at this before we do our release today?

**Comment by graywolf336** [comment]
This was fixed via d1212c59c36d95829b32566b1738cc180cf714f9
