### ISSUE TITLE
Hello Github Members

### ISSUE THREAD

**Issue by ABWelder** [RocketChat/Rocket.Chat#5183]
Total Rocket.Chat newbie here. Can someone please point me in the right direction? I do not know where a post like this goes? I do not see a forum for this type of request.

I am looking to hire a rocket.chat developer to perform a complete install and then continuously work with tweaking the software to meet my needs.

I have left a similar request in the #jobs channel on the demo rocket.chat, but no major response.

Thank You

**Comment by engelgabriel** [comment]
Hi @ABWelder 

The #jobs channel is the right place for now. We are still building a jobs listing on our website.

**Comment by ABWelder** [comment]
Okay, thank you.
