### ISSUE TITLE
Livechat popout window for chat with website visitor

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#519]
We started the package called rockectchat:livechat

See  /packages/rocketchat-livechat

We should have many interfaces

* Popup window (LiveZilla)
* Floating window (Zopim, Olark, LiveChat, SnapEngage)
* Right panel (Disqus)

**Comment by BetaUliansyah** [comment]
Ill be more than happy to test it!

**Comment by mkorfmann** [comment]
Is someone working on this already?

**Comment by engelgabriel** [comment]
Please, take a look at https://rocket.chat/livechat-demo.html using an anonimous browser window :)

**Comment by skyred** [comment]
Anyway that I can test the backend of this livechat demo?

**Comment by sampaiodiego** [comment]
@skyred the backend is the rocket.chat itself..

**Comment by geekgonecrazy** [comment]
@skyred If you want to test the server like @sampaiodiego said its rocket.chat its self.

Or are you wanting to test the receiving end of the live chat, as in actually getting messages etc?

**Comment by skyred** [comment]
I want to test this either

1. point me to the documentation so that I can enable this feature on top of docker rocket.chat image?

2. provide the access to the server/receiving end of this https://rocket.chat/livechat-demo.html popup?

**Comment by Sing-Li** [comment]
1 is not possible without re-building.  Default configuration of our build does not include the livechat package - and there is no way to 'enable feature' after a build for docker images 

For 2 --  @sampaiodiego...   is it possible to route messages to a specified registered user for these sort of tests?

**Comment by sampaiodiego** [comment]
actually, only online users with `operator` flag set to true will receive those livechats. BUT, there is no UI to set an user as operator atm, so a update directly on database is needed.. it might be something like this (in mongo shell):

`db.users.update({ username: 'SOME_USERNAME' }, { $set: { operator: true } });`

**Comment by liuliming2008** [comment]
1 Cloud team manger/admin set operator flag for team users at the plan?
2 It is better to support image upload, the it can be used to be helpdesk.

**Comment by ic5y** [comment]
I loaded the plugin, rebuilt rocket.chat, and the plugin is loaded successfully. I set the operator status on myself as true, but the livechat still shows that no operator is available :(

**Comment by ic5y** [comment]
So, I made myself an operator, livechat is set up. But when someone writes to me on livechat, I cannot see the message.

**Comment by sampaiodiego** [comment]
@ic5y the current command to make an user an operator is the following:
`db.users.update({ username: 'SOME_USERNAME' }, { $push: { "roles.__global_roles__": { $each: ['livechat-agent', 'livechat-manager'] } }, $set: { operator: true } })`

**Comment by ic5y** [comment]
hm, the new livechat interface comes up, but when a guest sends a message, i got an internal server error :/

**Comment by sampaiodiego** [comment]
please try in an anonymous window (or another browser).. there is a bug when using a session created before.

**Comment by ic5y** [comment]
okay thanks! its working now :)

**Comment by dalenoe** [comment]
Just found this issue. Interesting, and can't wait to see it ship..

**Comment by engelgabriel** [comment]
We will make it an standard feature this week! Stay tuned!

**Comment by diogobernini** [comment]
Any updates here?

**Comment by engelgabriel** [comment]
Yes, it is almost there. :)

Will be included on the next release, on monday.

**Comment by llinzzi** [comment]
Live chat is so cool, but the demo doesn't work. 
https://rocket.chat/livechat-demo.html

**Comment by sampaiodiego** [comment]
it's working @llinzzi , I just tested .. did you get some errors? what happened to you?

**Comment by llinzzi** [comment]
@sampaiodiego it works for Chrome, but not work for Safari. 
```
SyntaxError: Unexpected token ')'
(anonymous function)rocket-livechat.js:16
```

**Comment by sampaiodiego** [comment]
ohh.. ok.. have to check it so.

**Comment by sampaiodiego** [comment]
for those who are interested in livechat features, I'm working on livechat manager that you can check at #1683 

any feedback are welcome

**Comment by engelgabriel** [comment]
This package is now part of the default distribution.

**Comment by Sing-Li** [comment]
Yay!  And I thought it was for Monday :flushed:

**Comment by david-strejc** [comment]
Will there be such a functionality like "triggers" and other cool things like Zopim has? Whole backend management for handling customer who is online on your web page?

Thanks for info. Great product!

**Comment by sampaiodiego** [comment]
yes @david-strejc .. please follow the issue #1824
