### ISSUE TITLE
hubot allow in private chats

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#5191]
Your Rocket.Chat version: 0.48 dev

This isn't so much a bug as it is a feature request.

Internal and external hubot isn't allowed to chat in private groups as a basic rule I believe.

I think there should be an settings option to allow him into all or specified private groups.

**Comment by geekgonecrazy** [comment]
@mrplow I can't comment for internal hubot.  But I know external hubot if you add to the room and you use the `LISTEN_ON_ALL_PUBLIC=true` environment variable and don't specify a room it will join any room its a part of.

**Comment by mrplow** [comment]
@geekgonecrazy good to know, I'll test that out when I get a chance. Thanks

**Comment by reetp** [comment]
Rocket v0.57

I'm trying to find a resolution to this so I can add the internal bot to a private channel.

Why is it disabled for Private channels ? (we only use Private within our organisation)

Is there a work around ? Is there a DB entry that could be modified, or an ENV var ?

Could it be made switchable ? 

Wondering if this closed bug is related : https://github.com/RocketChat/Rocket.Chat/issues/3132

Any advice appreciated.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8933
