### ISSUE TITLE
Auto-generated Avatars text renders badly when zoomed 

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#5194]
Your Rocket.Chat version: (make sure you are running the latest) 0.48 develop

We often use zoomed-in browser views of RC for demonstrations. The auto-generated avatars go a bit haywire at certain zoom resolutions

When Rocket.chat is zoomed to 200% scale in browser, the auto-generated test in avatars looks something like this:
![screen shot 2016-12-13 at 10 43 38 am](https://cloud.githubusercontent.com/assets/1432373/21121590/79a874d0-c121-11e6-82f5-12cd359a404e.png)

at 250% it looks fine again:
![screen shot 2016-12-13 at 10 47 38 am](https://cloud.githubusercontent.com/assets/1432373/21121627/a0e66944-c121-11e6-85e7-149031df487d.png)

But at 300% the same issue reappears:
![screen shot 2016-12-13 at 10 48 39 am](https://cloud.githubusercontent.com/assets/1432373/21121659/c19e45da-c121-11e6-9687-876a78199a21.png)

Issue is the same in both Chrome and Firefox

**Comment by karlprieb** [comment]
Hi @RichardFoxworthy ! 
I can't reproduce this bug.
Which browser an OS do you use?

**Comment by RichardFoxworthy** [comment]
Hi @karlprieb - I just rechecked and now I cant seem to reproduce the issue either! Weird because I've noticed this happening over quite a long period of time.

Anyway, I will close this issue and reopen in future if it reoccurs for me.

Cheers
