### ISSUE TITLE
Custom oauth registering two buttons on login page

### ISSUE THREAD

**Issue by johnlund** [RocketChat/Rocket.Chat#5197]
Your Rocket.Chat version: 0.48.0

I'm using a single custom oauth for login, and it's been working fine, but recently it is displaying a new empty button on the login page:

<img width="956" alt="chat_-_modern_masters" src="https://cloud.githubusercontent.com/assets/9579511/21131517/5b567f7c-c0cc-11e6-98e8-de855eb43a33.png">

The button on the right labeled `Enter` is the correct button, and still works to log me in. The grey button on the left does nothing when clicked.

**Comment by geekgonecrazy** [comment]
@johnlund I suspect this has something to do with a migration.  Can you verify that you only have a single version of this under oauth in administration?  If so can you try disabling and re-enabling it?

**Comment by johnlund** [comment]
@geekgonecrazy I checked for a duplicate version in oauth first and only saw the one - that is still the case. I just tried disabling the single custom oauth I see there, and when I did, my purple button disappeared and the grey remained. After re-enabling it, there was no change from above. Thanks for your help.

**Comment by geekgonecrazy** [comment]
@johnlund it kind of appears some how the custom oauth method got messed up during migration.

Last thing off the top of my head to try is remove the oauth method and re-add it.  Checking to see if it goes away after you remove it and before you add it back.

**Comment by johnlund** [comment]
@geekgonecrazy Ok. I removed the custom oauth, and there were no other custom oauths in the admin section, and no other oauths enabled. After doing so, the login page appeared unchanged - is showed two buttons, the grey, and the purple.

I then added a new custom oauth, with a new name, and now I have three buttons on my login screen:

<img width="1108" alt="modern_masters_chat" src="https://cloud.githubusercontent.com/assets/9579511/21169011/c444d0de-c175-11e6-8897-2b7e9f18096f.png">

This is becoming a more urgent issue. :)

**Comment by johnlund** [comment]
If I disable the new ouath I just created - even though it is the only custom oauth in admin, and the only oauth enabled - I see two buttons. And the button for the original custom oauth still works, even though that custom oauth doesn't appear in the admin section.

Definitely appears to be a DB issue.

**Comment by geekgonecrazy** [comment]
@rocketchat/core it looks like we removed custom_ in front of the custom oauth... and maybe the migration didn't work?  Ideas?

**Comment by graywolf336** [comment]
@rodrigok might wanna take a look at this, seems related to the pull request https://github.com/RocketChat/Rocket.Chat/pull/5146

**Comment by geekgonecrazy** [comment]
It looks like the migration takes `[A-Za-z0-9]` so upper or lowercase.. but the setting only finds settings with lowercase.   I'm not sure if that's it. https://github.com/RocketChat/Rocket.Chat/pull/5146/files#diff-e650e7e88fed89c795f64365501321abR76
