### ISSUE TITLE
ufs: permissions are not defined for store "fileSystem"

### ISSUE THREAD

**Issue by CRCbary** [RocketChat/Rocket.Chat#5198]
Your Rocket.Chat version: (0.48.0)

Hi All,

i'm new in Rocket Chat and i want to try it in my Linux Ubuntu Server 16.04 Virtual Machine.

i follow the steps mentioned in this link https://www.howtoforge.com/tutorial/how-to-install-rocket-chat-with-nginx-on-ubuntu-16-04/#step-install-the-rocketchat-dependencies 

and i get stuck in Step 5 - Install Rocket.Chat Server 

when i enter the node main.js command its return me this message : 

root@ubuntu:/var/www/Rocket.Chat# node main.js
Updating process.env.MAIL_URL
ufs: permissions are not defined for store "fileSystem"
ufs: store created at 
ufs: permissions are not defined for store "fileSystem"
ufs: store created at 
{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 71","time":{"$date":1481616605412},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom emoji storage
[Tue Dec 13 2016 00:10:12 GMT-0800 (PST)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
ufs: permissions are not defined for store "rocketchat_uploads"
Using GridFS for Avatar storage
➔ System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |       Version: 0.48.0                        |
➔ |  Process Port: 3000                          |
➔ |      Site URL: http://192.168.241.255:3000/  |
➔ |         OpLog: Disabled                      |
➔ |                                              |
➔ +----------------------------------------------+

can any one help me please

**Comment by engelgabriel** [comment]
Looks like rocketchat is running, did you try to open  http://192.168.241.255:3000/ in your browser?

**Comment by zmx312502865** [comment]
@engelgabriel
 ufs: permissions are not defined for store "fileSystem"
How  to solve this problem?   Is it a permission problem?  Which dir set 777?

**Comment by geekgonecrazy** [comment]
@zmx312502865 this is more of a warning.  Safe to ignore :smile:

**Comment by zmx312502865** [comment]
@geekgonecrazy    Upload  file is not woking ....So i think file permissions  cause this problem.....
In browser:
Failed to load resource: net::ERR_CONNECTION_REFUSED
http://www.zmx.com/ufs/rocketchat_uploads/3PKgDhZY9P447RjvS?token=58BaEBBa38&progress=1 net::ERR_CONNECTION_REFUSED
