### ISSUE TITLE
Can't access snap

### ISSUE THREAD

**Issue by jmowatt** [RocketChat/Rocket.Chat#5204]
When installing the snap version of RocketChat I am unable to access through port 3000, when I netstat only port 22 and MongoDB port are open.

Any ideas how I can fix this?

**Comment by geekgonecrazy** [comment]
@jmowatt can you confirm a few questions

What Architecture x86 / x64 ?
How much RAM?

**Comment by jmowatt** [comment]
Ubuntu 16.04 x64
512mb RAM

It's a digitalocean droplet

**Comment by jmowatt** [comment]
I have resolved this with a 1Gb instance

**Comment by geekgonecrazy** [comment]
@jmowatt yes for sure a ram issue.  To get around this 1Gb instance or adding swap to the 512MB would do the trick.
