### ISSUE TITLE
incoming webhooks not working anymore correctly since 0.48.0

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#5205]
Rocket.Chat version: 0.48.0

Hi Devs.

After upgrading to 0.48.0 incoming webhooks are broken.  Using the example hook:

> {
>   "text": "Example message",
>   "attachments": [
>     {
>       "title": "Rocket.Chat",
>       "title_link": "https://rocket.chat",
>       "text": "Rocket.Chat, the best open source chat",
>       "image_url": "https://rocket.chat/images/mockup.png",
>       "color": "#764FA5"
>     }
>   ]
> }

leads to 
![bildschirmfoto 2016-12-13 um 17 16 21](https://cloud.githubusercontent.com/assets/631865/21148254/ef0121ec-c157-11e6-9b61-4f2e7aca7ac5.png)

so at least the textfield is missing. Any hints how to solve this?

thanks and cheers

**Comment by himbeere** [comment]
Also i have a lot of this messages in the logfile:

ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "fileSystem"
ufs: permissions are not defined for store "rocketchat_uploads

Could this be related?

**Comment by graywolf336** [comment]
Please update to 0.48.1
