### ISSUE TITLE
 Sockjs not using CDN_Prefix 

### ISSUE THREAD

**Issue by AlecTroemel** [RocketChat/Rocket.Chat#5206]
Rocket.Chat version: 0.49-develop

Running Rocketchat behind a subdirectory throws errors because Sockjs is using metoers path prefix instead of CDN_Prefix when it is set. 

I am running RC at `localhost:3000` with CDN_PREFIX set to `chat`

I am using a simple nginx reverse proxy which looks like this 
```
        location /chat {
            proxy_pass http://127.0.0.1:3000/;
        }    
```

but seeing this 
<img width="1073" alt="screen shot 2016-12-13 at 10 32 57 am" src="https://cloud.githubusercontent.com/assets/8620042/21148965/87f58b74-c11f-11e6-9401-5294377ec348.png">

I've tried a bunch of different things but always seem to hit this.

**Comment by geekgonecrazy** [comment]
Do you also have your site url set?

**Comment by julienkoziel** [comment]
Hello,

I think there is a link with` https://github.com/RocketChat/Rocket.Chat/issues/4832`

**Comment by muus84** [comment]
Same problem here. Rocket.Chat 48.1 in a docker container. The SITE URL is https://delin-build/chat.

If i try to upload a file:
![image](https://cloud.githubusercontent.com/assets/2518781/21228711/2ad32e62-c2df-11e6-9600-829e4cae5d74.png)

**Comment by AlecTroemel** [comment]
What I was attempting to do was host my under a different path then what it was served. So for example have the site url be `mysite.com/abc` and set the cdn_prefix to `/xyz` so that I could reverse proxy through nginx like this
```
location /xyz {
   proxy_pass http://mysite.com/abc;
}
```
For the issue I simplified. I'm skeptical of whether thats even possible, but the concept of the cdn prefix gave me a bit of hope.

**Comment by geekgonecrazy** [comment]
@AlecTroemel wow sounds like a complicated setup.  If you're going to try the CDN route.. You might try putting your chat on http://chat.mysite.com and then cdn at mysite.com/chat.  With:
```
location /xyz {
   proxy_pass http://chat.mysite.com;
}
``` 
That might be more likely to work

**Comment by AlecTroemel** [comment]
I agree in the complexity, it feels like over engineering. I'm considering now to just create a page with a full iframe of my rocketchat instance at `mysite.com/chat`. I believe that would bypass my issues altogether

**Comment by geekgonecrazy** [comment]
Did either of those ways work for you?    Going to go ahead and close.  Please re-open if your problem isn't solved.
