### ISSUE TITLE
Simple Community Forum Needed

### ISSUE THREAD

**Issue by ABWelder** [RocketChat/Rocket.Chat#5207]
Hello,

Let me start by saying, I really am impressed with Rocket.Chat thus far and I appreciate everyone's effort in the project.

Now... I only joined GitHub.com because I could not find another way to communicate with others about rocket.chat. However, it seems that this platform is more geared towards developers and not the general public. As a matter of fact, I am most likely posting this information in the wrong place as I am not very familiar with this GitHub platform.

So, my question to the developers/ users at rocket.chat, where can I have a normal discussion with rocket.chat users and developers about rocket.chat? Other than making chat entries in the rocket.chat demo? Is there a traditional forum somewhere that I am not seeing? Where is the best place to have a variety of organized discussions about Rocket.Chat?

Thank you in advance.

**Comment by k0nsl** [comment]
@ABWelder: You can find us all here: https://demo.rocket.chat/channel/support

**Comment by Molle500** [comment]
@ABWelder Go to their demo of Rocket Chat. Tons of users there + the developers themselves
https://demo.rocket.chat

**Comment by geekgonecrazy** [comment]
@ABWelder currently we all hang out on https://demo.rocket.chat  This is the primary way we talk to users.

Just to get the conversation started... 

What types of things would you be discussing on a forum vs a chat room or github issue?

**Comment by ABWelder** [comment]
Hello geekgonecrazy,

In my opinion, having a organized forum is great for reference past issues, opposed to only relying on a search feature to bring up keywords. Don't get me wrong, I really like Rocket.Chat, but I find it difficult to reference past conversations and topics while you have a dynamic chat going on.

By having a support forum for Rocket.Chat, users would easily be able to reference past topics simply by reviewing the list of threads, whereas chat does not have that feature.

For example, I am new to the Rocket.Chat environment and not yet a owner of a site that has it running. However, I am very much interested in doing so and I have a ton of questions. However, I have proposed several questions and comments on Rocket.Chat that have gone unanswered. Most likely because they may have not been seen by all users. 

Rocket.Chat to me is a great social tool and I intend on using it when the time is right. I just wish there was a more structured platform for support, instead of relying on a dynamic chat entries that a person may or may not seen and most likely would have to be there at the time when the topic was written in order to notice the new discussion. I hope that makes sense.

**Comment by engelgabriel** [comment]
Maybe we could have our own http://www.discourse.org/ server, like:

https://forums.meteor.com/
https://forum.mattermost.org/

Or we should implement some FORUM like channels on and keep all in the RC server.

**Comment by engelgabriel** [comment]
I vote for the second :)

**Comment by djeber** [comment]
i think a discourse forum will be the best solution because :
a- it was made to handle such situations 
b- implementing forum like channels will consume a lot of time and resource of the team while it could be used in improving rocket chat 

this is just my opinion

**Comment by marceloschmidt** [comment]
Why not keep discussing things here in GitHub? There's `@mentioning` and notifications will let you know if anything happened to issues you've subscribed to... I don't think we have the people resources to keep another eye on another forum.

**Comment by rahul7471** [comment]
@geekgonecrazy I am not able to join any group on rocket chat https://demo.rocket.chat . Can you help me with the steps please. it is very urgent.
I am not able to see any channels to join

**Comment by geekgonecrazy** [comment]
https://demo.rocket.chat/channel/support try a direct link :)

**Comment by rahul7471** [comment]
Thanks for your reply.
I am able to join general.

**Comment by reetp** [comment]
Discourse -1 Yuck. 
I must be getting old ;-)

**Comment by SamSaffron** [comment]
It is looking super likely we are going to move off Slack to use Rocket Chat at Discourse, we would be happy to host you a Discourse instance for free or donate a digital ocean droplet if you wish to self host. 

Reach out to me if you would like to do so... 

I think a community would help tons, we are implementing now and there are so many little tweaks to share, stories to tell and so on.

**Comment by geekgonecrazy** [comment]
@SamSaffron We'd definitely love to have you guys using Rocket.Chat!  😄 

I've passed your offer along to the team.  I think we're still wrestling a bit if we want to add something else for the team to need to check, or stick with github issues and chat.  :grin: 

Either way thanks for the offer! We'll definitely follow up either way the ball rolls. 👍

**Comment by Sing-Li** [comment]
@SamSaffron   awesome to learn about Discourses' potential migration to Rocket.Chat from Slack.  Please let us know if you need assistance in any way.    

And welcome to our extended community of open source communities!  😁 

We will happily take you up on your offer of hosting an instance!  Thanks in advance.  We can really use a forum at the end of each of our blogs, similar to what you have with your blogs:

https://blog.discourse.org/

Ours, off statically generated site:

https://rocket.chat/blog/

@geekgonecrazy is already in conversation with @jomaxro , can you please give us a hand to make it happen?   Thanks in advance.

Furthermore, I would like to see if you might want to further explore potential deeper "crossover" integrations between our two projects - benefiting both of our communities.  

One idea: within structured discussion flow, often there is a need to jump into a real-time ad-hoc rapid-fire meeting /  chat  session to hash out some details (might involve external participants not part of the original structured discussion) , and then upon reaching some conclusion - return back to the structured discussion with the entire chat message history made available as part of the original discussion.

Another idea: this one from within chat - outbound to structured forum : https://github.com/RocketChat/Rocket.Chat/issues/830

Please let us know what you think. Perhaps we can get a meeting of the minds together for more brainstorming 👍

**Comment by SamSaffron** [comment]
Awesome, this is great news @Sing-Li  will leave this for @jomaxro to organise! 

Ideas sound interesting let's hash them out either on meta.discourse.org or your new forum when it is out! We do have an official chat integration provider for RocketChat that covers shipping transcripts from chat over to Discourse on demand and shipping notifications to Chat back from Discourse to RocketChat.

**Comment by jomaxro** [comment]
> We do have an official chat integration provider for RocketChat that covers shipping transcripts from chat over to Discourse on demand

We don't actually support transcripts for Rocket.Chat yet. If I'm not mistaken, Rocket.Chat does not support custom slash commands at this time, and that is how our plugin exposes the transcript send UX. Something we can talk about further once we get everything up and running.

I should be able to get your site up this evening. I'll ping @geekgonecrazy once it's ready to go. Up to you and your team to decide when to announce it publicly.

**Comment by Sing-Li** [comment]
@ABWelder   Thanks to the generosity of @SamSaffron 's  discourse.org team and expert technical assistance from @jomaxro and his team - we now have our official "Simple Community Forum" that you have described.  Please access it here and start actively participating in discussions:

https://forums.rocket.chat

The BEST way to login is via your https://open.rocket.chat   account!  Once you are logged onto our open.rocket.chat Rocket.Chat server - you can access forums.rocket.chat without logging in again.

We look forward to work with the discourse team in 2018 - to figure out a more seamless user experience transcending these two slightly different forms of open source collaboration.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as the Rocket.Chat Discours (https://forums.rocket.chat) is now up and running. If I missed something and this issue should still stay open, please get back to me :)

Cheers
Thomas
