### ISSUE TITLE
Video Call Terminated

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#521]
If you have two windows open of the same instance and start a video chat in one you'll get a notification that the person you started it with invited you to a video chat. Declining that invite will end the current video call.

Steps to reproduce:
1. Open two windows of that same chat instance (I used Chrome on Android and Chrome on Windows)
2. Start a call from one to another user, let them accept (I used one opened Android)
3. Look at the other window and see an Invite to Video chat from the person you started the video call with
4. Hit the no button and the current video call ends

Hopefully that's clear, let me know if you have any questions.
##

**Comment by Sing-Li** [comment]
@graywolf336 -  in step 1 - are you opening two windows on the same browser on the same machine?  Thx.

**Comment by graywolf336** [comment]
No, I opened one on Chrome for Windows and then the same location on Chrome for Android.

**Comment by Sing-Li** [comment]
@graywolf336  - are you saying that you logged on as the same user - on both Windows and Android in Step 1?  Thx

**Comment by graywolf336** [comment]
That is correct

**Comment by Sing-Li** [comment]
@graywolf336  - so in step 3 ... you are seeing an invite to video from PERSON-A on a session logged in as PERSON-A ?

**Comment by graywolf336** [comment]
No. Person A starts a video with Person B from one of the windows. Person B accepts and they talk. When Person B accepts, Person A sees an invite in their other window from Person B even though the call is already happening. Person A hits the `No` button and the ongoing call ends.

**Comment by Sing-Li** [comment]
@graywolf336 - so in step 3 ... you are seeing an invite to video from PERSON B  even though PERSON A was the one who initiated the video call.   Correct?

**Comment by graywolf336** [comment]
Correct

**Comment by Sing-Li** [comment]
@graywolf336 - thank YOU!    That's a bug.  The first ever bug publicly reported on Video Chat :+1:

**Comment by graywolf336** [comment]
Glad to help! :smile:

**Comment by Sing-Li** [comment]
:smiley:  If you don't mind answering one more question.... did you find video chat to be stable --> connects 80% + of the time.   Or are your connections hit-and-miss?   thanks again.

**Comment by graywolf336** [comment]
When they would connect, it was very stable on WiFi. But sadly towards the end, them connecting was hit-and-miss.

**Comment by geekgonecrazy** [comment]
It looked like it was mainly an issue with the other person not getting alerted of the video request.

Almost like the webrtc stuff was setup and the other side was never told about it.

But like @graywolf336 said once connected it was awesome.

**Comment by Sing-Li** [comment]
Thanks @graywolf336  and @geekgonecrazy.  The QoS feedback is very valuable.

**Comment by Megatronic79** [comment]
Not sure of this belongs here but when trying the video calling feature the remote user never gets the video request - tried from different browsers and the rocket.chat windows client.. any logs we can view to see the connection \ request attempt?

**Comment by Sing-Li** [comment]
@Megatronic79  --- please follow the instructions at the end of this to 'switch in' the rocketchat:webrtc-ib signaling stack:

https://github.com/RocketChat/Rocket.Chat/wiki/Using-Face-to-face-video-conference-(aka-webrtc)

-- and let us know if the problem goes away for you.   Thanks.

**Comment by Megatronic79** [comment]
Thanks @Sing-Li that now works with mozilla.

Tested with the Windows Client (0.0.7) and it doesnt work yet even after that change, will this be implemented in a later build?

**Comment by Sing-Li** [comment]
WebRTC is a browser standard.   

Even though our desktop and mobile apps often embed browser technologies, WebRTC compatibility is seldom a concern/feature for the underlying framework.  It is impossible to ensure compatibility.  

So, no, not likely.    

Use the latest Chrome or Firefox on Windows if WebRTC is core to your use case - they have been both thoroughly tested to work.

**Comment by Sing-Li** [comment]
@graywolf336 - just an update for you.  This bug has been reproduced, confirmed, and a fix crafted.  Just pending some time to thoroughly test it.

**Comment by graywolf336** [comment]
@Sing-Li awesome, thanks!

**Comment by gmsecrieru** [comment]
There are so many changes on WebRTC about to merged into `master` from #989 that this might be addressed as well. Would you try again with latest code @graywolf336 ?

**Comment by graywolf336** [comment]
Sure will!

**Comment by graywolf336** [comment]
@gmsecrieru Yes it is still happening. I started a video chat with someone on my phone and it came up on my desktop with "Direct video call from my.username".

**Comment by engelgabriel** [comment]
TO be completed as part of https://github.com/RocketChat/Rocket.Chat/issues/933

**Comment by MartinSchoeler** [comment]
@graywolf336 can we close this?
