### ISSUE TITLE
Latest versions seem to require NPM 3

### ISSUE THREAD

**Issue by toupeira** [RocketChat/Rocket.Chat#5210]
Rocket.Chat version: 0.48.1
NodeJS version: 4.7.0 (upstream Debian package from nodesource.com)

I just upgraded from 0.43 and ran into a build error for the `bcrypt` package on `npm install`, same error as [this Meteor issue](https://github.com/meteor/meteor/issues/7568) (`sh: 1: node-pre-gyp: not found`)

On a whim I tried upgrading to NPM 3 (`npm install -g npm@3` as root) and after that the build finished successfully.

It would be great if the required NodeJS and NPM versions were clearly mentioned somewhere, for example in the README.

**Comment by geekgonecrazy** [comment]
@RocketChat/core can we confirm if 0.48.1 needs npm 3?

**Comment by Sing-Li** [comment]
@toupeira 

> It would be great if the required NodeJS and NPM versions were clearly mentioned somewhere, for > example in the README.

That's a great idea - maybe with release notes , since each release may have different requirements.

This is especially *useful* since our TGZ is now cross platform.  It answer the questions for ARM or Windows based deployment, for example.

**Comment by Sing-Li** [comment]
Verified, confirmed, and updated .... see:

https://github.com/RocketChat/Rocket.Chat/releases/tag/0.48.1

**Comment by toupeira** [comment]
@Sing-Li thanks!
