### ISSUE TITLE
Ability to change the default values for a new user

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#5211]
I think it would be great if there was a tab in the admin panel where we could change the default values for a new created user to easier modify the server how we want it.

Lets say for as an example that we want "save mobile bandwith" to be false as default and dont want any sound at all on our server.

I made a mockup how it could look like.
![example](https://cloud.githubusercontent.com/assets/17712562/21160236/61cccb00-c184-11e6-9e7a-e193035cbf59.png)

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
