### ISSUE TITLE
Cannot read property 'onOplogEntry' of null (Database Bricked)

### ISSUE THREAD

**Issue by Noculi** [RocketChat/Rocket.Chat#5212]
Your Rocket.Chat version: 0.49.0-develop

```
2016-12-13T23:08:42.980527+00:00 app[web.1]:     at require (packages/modules-runtime.js:106:16)
2016-12-13T23:08:42.980538+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:343:11
2016-12-13T23:08:42.980537+00:00 app[web.1]:     at Function.run (/app/.meteor/heroku_build/app/programs/server/profile.js:480:12)
2016-12-13T23:08:42.980536+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:128:5
2016-12-13T23:09:05.364725+00:00 heroku[router]: at=error code=H20 desc="App boot timeout" method=GET path="/" host=(URL Had to censor) request_id=39f5ebf6-3835-4278-b310-00081832f6fd fwd="(IP Had to censor)" dyno= connect= service= status=503 bytes=
2016-12-13T23:09:35.738224+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-12-13T23:09:35.738352+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-12-13T23:09:35.866785+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-13T23:09:35.841403+00:00 heroku[web.1]: Process exited with status 137
```

**Comment by thiesschneider** [comment]
My docker image is also broken:

```
Exception in callback of async function: TypeError: Cannot read property 'onOplogEntry' of null
    at ModelsBaseCache.startOplog (packages/rocketchat:lib/server/models/_BaseCache.js:433:3)
    at ModelsBaseCache.target.(anonymous function) [as startOplog] (packages/rocketchat:lib/server/models/_BaseCache.js:50:24)
    at ModelsBaseCache.load (packages/rocketchat:lib/server/models/_BaseCache.js:423:8)
    at meteorInstall.node_modules.meteor.rocketchat:lib.server.startup.cache.CacheLoad.js (packages/rocketchat:lib/server/startup/cache/CacheLoad.js:36:31)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
    at packages/rocketchat_lib/startup/defaultRoomTypes.coffee:62:1
    at packages/rocketchat_lib/startup/defaultRoomTypes.coffee:62:1
    at /app/bundle/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /app/bundle/programs/server/boot.js:128:5
    at /app/bundle/programs/server/boot.js:344:5
    at Function.run (/app/bundle/programs/server/profile.js:480:12)
    at /app/bundle/programs/server/boot.js:343:11
```

**Comment by Merryfurr** [comment]
Sucks because I checked the commits and 0.49.0 has some cool stuff in it.

**Comment by thiesschneider** [comment]
even if I try to downgrade to 0.47 it does not start up anymore :(

**Comment by Syirrus** [comment]
Yeah this is a serious problem. I'm having the same issue.

**Comment by geekgonecrazy** [comment]
> Yeah this is a serious problem. I'm having the same issue.

Guys just first off upgrading to an unofficial release always is going to come with risks like this.  0.48.0 and 0.48.1 were just very freshly released.  Right after that we merged down a pretty huge change to the caching layer.  I'm guessing you guys both tried it after these big changes were merged.

If these aren't production systems I suggest a db wipe or hang tight its likely a db migration and we'll get this fixed prior to 0.49.0 being cut.

If this is production. I'd like to re-iterate. Please don't use develop in production.  Until it hits master (ie a release) its likely to have bugs like this. :smile:

Can you guys goto administration->info and get the commit?  You both look to be having very different problems.

**Comment by thiesschneider** [comment]
This are the risks of developer versions... thats true! nevertheless it would be nice if we can fix that. Probably its not the same issue. But both servers are not starting and in my case you see the output of the docker logs.
Because the server does not start I cant go in administration and find the commit. In docker inspect there is no record of the commit. Any ideas to find the commit? I pulled the image from the developer channel about 9 hours ago

**Comment by Merryfurr** [comment]
The commit used was 39b20d13

**Comment by geekgonecrazy** [comment]
@merryfurr you definitely caught the merge down of the new branch.  

@thiesschneider if you specified with the develop tag you would probably have to find the id of the image your container is using.  Then go over to docker hub and see if you can tell based on the dockerfile

**Comment by thiesschneider** [comment]
its the same commit as merryfurr is using

**Comment by robertsoakes** [comment]
I'm seeing the same issue. In my case, though, it's in a completely clean development environment. I ran into it while trying to merge a branch of code that I've been working on with extensions to the REST API. New installation of Node, new installation of Meteor, new Mongo instance, fresh checkout.

**Comment by engelgabriel** [comment]
Can you all confirm if you are using the MongoDB in ReplicaSet mode or not?

**Comment by thiesschneider** [comment]
I did not use a ReplicaSet. Ran the same docker-compose since 0.21 or so :)

**Comment by CzEMC** [comment]
I am not using a RaplicaSet as well.

**Comment by engelgabriel** [comment]
I think this is the source of the issue. We had done some performance enhancements that rely on ReplicaSet mode. We need to test it against standalone mode gaian.

But FYI, you should ALWAYS use ReplicaSet mode in production, ALWAYS!

**Comment by thiesschneider** [comment]
would it solve the issue if we add this in the docker-compose for example?

**Comment by engelgabriel** [comment]
@thiesschneider we did at https://github.com/RocketChat/Rocket.Chat/commit/601533187859667e5ffd19f4d41c5a06fc88b01a

**Comment by thiesschneider** [comment]
yes I know. I mean if I resolve my error by adding this in my own docker-compose file?

**Comment by engelgabriel** [comment]
@thiesschneider I believe it would resolve the error. Also, you'd get a big boost on performance.

**Comment by thiesschneider** [comment]
yay... i will try it!

**Comment by thiesschneider** [comment]
I still get an error:

```
mongo-init-replica_1  | MongoDB shell version: 3.2.11
mongo-init-replica_1  | connecting to: db/rocketchat
mongo-init-replica_1  | {
mongo-init-replica_1  | 	"info" : "try querying local.system.replset to see current configuration",
mongo-init-replica_1  | 	"ok" : 0,
mongo-init-replica_1  | 	"errmsg" : "already initialized",
mongo-init-replica_1  | 	"code" : 23
mongo-init-replica_1  | }
rocketchat_1          | /app/bundle/programs/server/boot.js:348
rocketchat_1          | }).run();
rocketchat_1          |    ^
rocketchat_1          |
rocketchat_1          | TypeError: Cannot read property 'slice' of null
rocketchat_1          |     at packages/meteor.js:1221:19
rocketchat_1          |     at packages/meteor.js:1233:4
rocketchat_1          |     at packages/meteor.js:1380:3
rocketchat_1          |     at /app/bundle/programs/server/boot.js:295:34
rocketchat_1          |     at Array.forEach (native)
rocketchat_1          |     at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
rocketchat_1          |     at /app/bundle/programs/server/boot.js:128:5
rocketchat_1          |     at /app/bundle/programs/server/boot.js:344:5
rocketchat_1          |     at Function.run (/app/bundle/programs/server/profile.js:480:12)
rocketchat_1          |     at /app/bundle/programs/server/boot.js:343:11
backuprc_mongo-init-replica_1 exited with code 0
backuprc_rocketchat_1 exited with code 1
```

**Comment by rodrigok** [comment]
@thiesschneider are you passing `MONGO_OPLOG_URL` as env? It should be passed like `MONGO_URL` but pointing to database `local`

**Comment by thiesschneider** [comment]
yes. I added the variables from the docker-compose in the github repository

**Comment by rodrigok** [comment]
@thiesschneider strange, are you use the latest docker image?

**Comment by thiesschneider** [comment]
yep - i tried both: develop and latest

**Comment by rodrigok** [comment]
@thiesschneider Latest does not require oplog, you are doing something wrong. Can you call me at https://demo.rocket.chat/direct/rodrigo.nascimento ?

**Comment by thiesschneider** [comment]
the problem seems to be, that the replica instance is starting too early. is there a possibility to add a sleeptime in docker compose or into the replica instance?

**Comment by engelgabriel** [comment]
@sampaiodiego do you know how to do this in the right sequence?

**Comment by rodrigok** [comment]
I added more information when running without Replica Set enabled (https://github.com/RocketChat/Rocket.Chat/commit/93373bfff1591c70795a82d686e4887eb2ce2d49)

**Comment by engelgabriel** [comment]
@thiesschneider did you try https://docs.docker.com/compose/compose-file/#depends-on ?

**Comment by sampaiodiego** [comment]
I'll update the `docker-compose.yml` file to user the version 2 spec including the `depends_on`

**Comment by sampaiodiego** [comment]
Please see #5298 for and updated `docker-compose.yml`

**Comment by thiesschneider** [comment]
I will try this later! thx

**Comment by thiesschneider** [comment]
I changed to version 2
here is my error log (part of it):

```db_repl_rc    | connecting to: mongo/rocketchat
db_repl_rc    | 2016-12-22T15:14:21.534+0000 W NETWORK  [thread1] Failed to connect to 172.18.0.2:27017, reason: errno:111 Connection refused
db_repl_rc    | 2016-12-22T15:14:21.534+0000 E QUERY    [thread1] Error: couldn't connect to server db_rc:27017, connection attempt failed :
db_repl_rc    | connect@src/mongo/shell/mongo.js:231:14
db_repl_rc    | @(connect):1:6
db_repl_rc    |
db_repl_rc    | exception: connect failed
```

**Comment by thiesschneider** [comment]
If i start the database and the rocketchat container first and afterwards `docker-compose up mongo` the log is:

```db_repl_rc    | MongoDB shell version: 3.2.11
db_repl_rc    | connecting to: db_rc/rocketchat
db_repl_rc    | {
db_repl_rc    | 	"info" : "try querying local.system.replset to see current configuration",
db_repl_rc    | 	"ok" : 0,
db_repl_rc    | 	"errmsg" : "already initialized",
db_repl_rc    | 	"code" : 23
db_repl_rc    | }
db_repl_rc exited with code 0
```

**Comment by sampaiodiego** [comment]
@thiesschneider with the new [docker-compose.yml](https://github.com/RocketChat/Rocket.Chat/blob/22bea00d1f76964846723a16b778c9589dde7e47/docker-compose.yml) the only thing you have to do is `docker-compose up -d`

You'll see the `already initialized` on startup, but there is no need to worrie. it says it's already configured and good to go.

**Comment by thiesschneider** [comment]
the first post is with `docker-compose up -d` only. 
but the container is exiting afterwards immediately.

**Comment by sampaiodiego** [comment]
> but the container is exiting afterwards immediately.

it's fine.. you'll end up with only 3 containers running, like this:
```
5ff6da062a30        rocketchat/hubot-rocketchat:latest   "/bin/sh -c 'node -e "   3 minutes ago       Up 3 minutes        0.0.0.0:3001->8080/tcp     rocketchat_hubot_1
2a8732dc798b        rocketchat/rocket.chat:latest        "node main.js"           3 minutes ago       Up 3 minutes        0.0.0.0:3000->3000/tcp     rocketchat_rocketchat_1
22de0dd15649        mongo:3.2                            "/entrypoint.sh mongo"   3 minutes ago       Up 3 minutes        27017/tcp                  rocketchat_mongo_1
```

**Comment by thiesschneider** [comment]
oha... okay... so it is normal that the replica is not running. i think this should be in the docs :)

thank you so much

**Comment by sampaiodiego** [comment]
> oha... okay... so it is normal that the replica is not running. i think this should be in the docs :)

the `mongo-init-replica` container only initiate the replica set.. the replica set itself is the `mongo` container..

agreed that should be documented some how. thanks

**Comment by Syirrus** [comment]
Still having a problem with this on heroku.
I'm using mlab (shared $18 per month plan) which is clustered with a replica set enabled.
However, when I build rocket.chat on heroku I get the following error:

 Your MongoDB is not with ReplicaSet enabled.

**Comment by engelgabriel** [comment]
We are working to make OpLog optional again in #5371
