### ISSUE TITLE
Issue with saml on pm2

### ISSUE THREAD

**Issue by shrynx** [RocketChat/Rocket.Chat#5213]
SAML authentication works for me on a single processes, but it repeatedly fails on multiple process using pm2. From the logs i could detect that the access token generated by login request wan't found by the login response as they both ran on different processes. One solution is to keep the access token in db , Any other work arounds or if someone else faced the issue ?

**Comment by pierre-lehnen-rc** [comment]
This was fixed years ago by #10681
