### ISSUE TITLE
GitLab oauth - "Service not configured"

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#5214]
Your Rocket.Chat version: 0.48.1

Normally we use the remember button on GitLab self hosted login page to get connected most of the time. But today i did some changes and then logged out, when i click on the GitLab logo on rocket chat login page, its showing "service not configured". Even though nothing is changed in this while. It was working before not sure which version broke this.

**We are in the situation of a bit like locked out right now.**

We have only GitLab instance for logins, other all forms are disabled.

Any one have this issue?

**Comment by Key4ce** [comment]
We have the same issue here.

**Comment by mmarif4u** [comment]
We are using snap in Ubuntu 16.04.1. Is remove the correct command to downgrade as i cant find a relevant command.
[https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/)
snap list output:
Name               Version  Rev  Developer   Notes
rocketchat-server  0.48.1   303  rocketchat  -

In case of downgrade where can i find the previous rev no.?

Not sort of related to this topic but let me ask, currently the snap update itself to latest version, is there a setting to stop that?

**Comment by Key4ce** [comment]
I am currently not using the snap version as i like to have more control over the version i am using. L

Looking online i think you need to use "snap list -v" to find the revision.

**Comment by mmarif4u** [comment]
Thanks @Key4ce .
snap list do provide the info needed(my previous comment above). What i was referring to have the rev no. for lets say 0.47.1 in case of downgrade.

**Comment by mmarif4u** [comment]
**Update1:**
@geekgonecrazy @Sing-Li 

I have reverted back to version 0.47.1, and rocket chat stopped working.
`snap revert --revision=282 rocketchat-server`

With the help of @geekgonecrazy i reverted back to the working version with:
`snap revert rocketchat-server`

At least things are moving now. Enabled form based logins for now and created passwords for the team.
Issue under active investigation.

**Update2:**
Turned out that [demo.rocket.chat](demo.rocket.chat) gitlab login have this issue too. I am not alone then.
Click on gitlab icon and will see the error "Service not configured".

**Comment by Sing-Li** [comment]
Reproduce:

1.    go to https://demo.rocket.chat  (logout, or in a new session/browser if you're already logged in)
2.   click the GitLab oauth button 

Result:    "Service not configured" toast

**Comment by engelgabriel** [comment]
@rodrigok I think your migration did not work.

**Comment by engelgabriel** [comment]
@marceloschmidt can you please help here?
