### ISSUE TITLE
Why are you using HTTP POST to update rooms,users ... ?

### ISSUE THREAD

**Issue by mahmoudmahdi24** [RocketChat/Rocket.Chat#5219]
Hello,

I think that you should be using the PUT HTTP verb to update a model ! why did you make the choice to use the POST verb to update entities ?

Thanks,

**Comment by geekgonecrazy** [comment]
@mahmoudmahdi24 primary reasoning I believe is we are aiming to be slack compatible.  As you'll notice the api in its current form is more RPC style then a true rest api.  If it was true rest api following the /resource/{id} style pattern I think we would push a bit for using proper HTTP methods.

**Comment by mahmoudmahdi24** [comment]
@geekgonecrazy I see !
I am actually using RocketChat for a Cloud project, and i need to interact with rocket chat automatically by making HTTP calls.
Thanks for the clarification,
