### ISSUE TITLE
Change window size bug

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#5225]
If you open the side nav while in the mobile resolution: 
![screenshot from 2016-12-15 10-59-10](https://cloud.githubusercontent.com/assets/20868078/21224937/a39fdbb2-c2b5-11e6-8fb0-87bc33eb85b3.png)
and maximize the screen this happens: 
![screenshot from 2016-12-15 10-59-23](https://cloud.githubusercontent.com/assets/20868078/21224951/b3e5b0e6-c2b5-11e6-8f42-275368d971ba.png)

**Comment by Nemra1** [comment]
Yup also in demo site...
