### ISSUE TITLE
Direct Message unread count buggy

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#523]
When you have a direct message conversation open.  It flashes an unread count temporarily even while window is in focus.

Haven't figured out the exact circumstances to reproduce.  But also sometimes when the conversation is not in focus.  Say when in the general channel.  It'll flash and go away.  Same as if that conversation were in focus.
##

**Comment by graywolf336** [comment]
I realize this is hard to see as there isn't much context there, but I was focused on the general channel and he was direct messaging me. I couldn't figure out how to reproduce it though, was very odd.

![2015-08-20_15-10-28](https://cloud.githubusercontent.com/assets/850391/9395166/7c85cfee-4752-11e5-8c15-c7a936c65e74.gif)

**Comment by engelgabriel** [comment]
Is this still a problem?

**Comment by geekgonecrazy** [comment]
I haven't noticed this particular notification issue lately.

**Comment by graywolf336** [comment]
Just had this happen again. It seems the server thinks I'm away yet I'm active. It sends me push notifications as well for a channel I have set to notify me of everything. I am unsure how to replicate this issue.

**Comment by geekgonecrazy** [comment]
@graywolf336 you seen this?  I actually haven't seen this for a while.  This might be resolved?

**Comment by MartinSchoeler** [comment]
@geekgonecrazy  @graywolf336 Can we close this?

**Comment by geekgonecrazy** [comment]
@MartinSchoeler I think so.  I haven't seen this happen in a long time.
