### ISSUE TITLE
Images with percent sign not displayed and cannot be downloaded. 

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#5232]
Your Rocket.Chat version: (make sure you are running the latest) : 0.48.1

When a user uploads a file with a percent symbol starting in the name rocket chat does not escape ir correctly and fails to display or download the image. it should escape it as percent 25. e.g. the file "% sporcle.png" attached is not displayed and cannot be downloaded correctly.

 
![sporcle](https://cloud.githubusercontent.com/assets/17622866/21246908/71877a4c-c2e0-11e6-8d0e-4d195a3ecd51.PNG)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as I cannot reproduce it on 0.62.0. If you still see this, please provide more details so I can try to reproduce.

Cheers
Thomas
