### ISSUE TITLE
Server 0.48.1. file sending in Rocket.Chat.Electron does not working, at all, any way!

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat#5236]
With server 0.48.1 with Rocket.Chat.Electron 1.3.1 you cannot download file any way, this stop to work at all. Totally useless desktop client..... for now.
Of course workaround, you must open WEB and login to chat server, then why we need this client?!? 👎

**Comment by Nosferous** [comment]
Same issue - Also having download issues with server 0.48.1 and Electron 1.3.1

Previously the download icon in the attachments list right-side bar would work (in-line message download icon wouldn't, there is an open issue ticket for that one). Now the attachments list no longer works. The download options have further reduced.

Only solution in-app is to drag attachment out from message, only tested with images so far. But the file name link and download icon do not work message in-line or attachments list. This is going to halt my deployment I was about to do unfortunately.

**Comment by LXSysadmin** [comment]
Really sad.... people are very angry about this.

**Comment by alexandre-zia-movile** [comment]
Having this issue also, please fix this with priority, we have hundreds of users complaining

**Comment by geekgonecrazy** [comment]
What OS are you uploading these from?  What method has the server been deployed?  We need more info to reproduce.  I've tried on several clean installs and upload works fine from the desktop client.

So any more info you can provide us would be useful

**Comment by bruno-rocha-movile** [comment]
It seems like the client apps don't know the correct link to the file. If I try to open the file through the client, I get a http://(our server)/fileupload/ link that doesn't work. Opening the file through the web however, opens the correct S3 link where the file is hosted.

**Comment by engelgabriel** [comment]
@rodrigok please put this on the top of the list.

**Comment by LXSysadmin** [comment]
Yes, upload works fine but no one can download this upload using desktop client.

**Comment by rodrigok** [comment]
I'm working on this issue now

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/34d7109c38bab91dab9efd1c883c2f37d14cbef2

@engelgabriel will release a new version `0.48.2` with this fix

**Comment by LXSysadmin** [comment]
Nice work. 
Question: If something must happen when i click on blue link with file name?
![image](https://cloud.githubusercontent.com/assets/19779209/21389100/81735352-c788-11e6-8692-61d5f10c21fa.png)

**Comment by rodrigok** [comment]
@LXSysadmin It will open a file preview, it's working with images now, but we need to implement to more file types.

**Comment by LXSysadmin** [comment]
For now in desktop client file preview not working, in fact, in desktop client click on link not working at all. This would be nice, if new functionality will be added. Thanx.
