### ISSUE TITLE
Deploying in Bluemix not working.

### ISSUE THREAD

**Issue by jesusprubio** [RocketChat/Rocket.Chat#5238]
Your Rocket.Chat version: 0.49.0-develop

Hi, I have two problems following this steps: https://rocket.chat/docs/installation/paas-deployments/ibm-bluemix

- The service "mongolab" doesn't exist in Bluemix now. I can solve it using another one with the proper environment variable (MONGO_URL).

- Making the last push is always fail with this error:

Cloning into '/tmp/buildpacks/bluemix-buildpack-meteor'...
       No version of Node.js specified in nodeversion, using '0.10.*'
       Using Node.js version: 0.10.48
-----> Fetching Node.js binaries
        - downloading and extracting node from http://nodejs.org/dist/v0.10.48/node-v0.10.48-linux-x64.tar.gz
       Installing meteor
######################################################################## 100.0%
Downloading Meteor distribution
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
sudo: no tty present and no askpass program specified
Couldn't write the launcher script. Please either:
  (1) Run the following as root:
        cp "/tmp/node-meteor-tAgz/.meteor/packages/meteor-tool/1.4.2_3/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
  (2) Add "$HOME/.meteor" to your path, or
  (3) Rerun this command to try again.
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
       Meteor installed
Ignoring build of mobile platforms
       Building meteor bundle

FALLIDO
Error al reiniciar la aplicación: StagingError

Thanks in advance.

**Comment by engelgabriel** [comment]
You need to specify node version 6.7.0

We don't support 0.10.* anymore.

**Comment by engelgabriel** [comment]
Can you please see http://stackoverflow.com/questions/38654482/meteor-1-4-buildpack-for-bluemix and let us know if that works?

**Comment by engelgabriel** [comment]
And please read https://medium.com/@guidouil/meteor-1-4-on-ibm-bluemix-f36aac93856f#.pwenjxwen

**Comment by jesusprubio** [comment]
Hi again,

I've checked with a simple meteor project and the buildpack you proposed worked well, but not for RocketChat. BTW, the one linked in the doc neither works with this simple example, I have this error.
<img width="511" alt="captura de pantalla 2016-12-20 a las 14 15 59" src="https://cloud.githubusercontent.com/assets/2753855/21352549/49ec5bf2-c6c2-11e6-8b39-272a9d26c1f1.png">

In our case, the error I have now is this one:
<img width="545" alt="captura de pantalla 2016-12-20 a las 14 40 55" src="https://cloud.githubusercontent.com/assets/2753855/21352655/c4a213e6-c6c2-11e6-8414-5475b058feb4.png">

It seems that it breaks during the install of the meteor packages. Other logs about the same thing just in case:
 OUT -----> Building Meteor app with ROOT_URL: https://test5-world.mybluemix.net
 OUT rocketchat:lib: updating npm dependencies -- bad-words, object-path,
 OUT node-dogstatsd, localforage, lokijs, bugsnag...
 ERR encountered error: Staging error: failed to stage application:
 ERR Script exited with status 255

PS: The manual solution proposed in the post didn't work for me. Moreover it's not a comfortable solution.

**Comment by engelgabriel** [comment]
@jesusprubio 

- Can you check if the version 0.48.1 works?
- And are you using the MongoDB in ReplicaSet mode?

**Comment by engelgabriel** [comment]
Docs updated at https://github.com/RocketChat/Rocket.Chat.Docs/commit/58fc8b13d6fab51857b58f7c33e9dd5fe2b09920

**Comment by engelgabriel** [comment]
0.49.0-develop only works with MongoDB in ReplicaSet mode. We are working to change that.

Onde @rodrigok  has finish the option to turn of the caching layer, I'll ask you guys to try again.

**Comment by engelgabriel** [comment]
@jesusprubio can you try again with the `develop` branch? It now supports MongoDB without ReplicaSet mode

**Comment by engelgabriel** [comment]
Please reopen if the problem persist.
