### ISSUE TITLE
any new notification system for custom cordova apk?

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5239]
Your Rocket.Chat version: (4.7)
i want to know if rocket chat have any new notification system for custom cordova apk
for example : im build new cordova app for my server for example: com.custom.pack.apk
and after build no notification working like official app from play stor>?

**Comment by maxlinux2000** [comment]
yes... .you can setup your own push notification system. Please search "push"  in the menus admin and in the Documentation

**Comment by Nemra1** [comment]
you mean this https://github.com/RocketChat/push
but idont know from wher i can start !!

**Comment by maxlinux2000** [comment]
No, it's much simpler. 
For android you have to log in at https://console.developers.google.com and create your key for the push messages that are formed by the project number and a secret API key like: ALZAfsdjfklsdfjksdlfjdkl.fsddddd456456456456.

Open the control panel of your installation of Rocket.chat and insert in the fields of GCM push, the project number, the API key and tell him that he does NOT want to use the gateway of rocket.chat

In cordova, is simple. look here:
Https://github.com/RocketChat/Rocket.Chat.Cordova

And insert the same keys with these linux commands

```
echo 'Bugsnag.apiKey = "YOUR-API-KEY-HERE";' > www/js/bugsnag_apikey.js
echo 'window.ANDROID_SENDER_ID = "YOUR-ANDROID-ID-HERE";' > www/shared/js/android_sender_id.js
```

**Comment by Nemra1** [comment]
( and create your key for the push messages ) wher is where is exactly 
![2016-12-17_183633](https://cloud.githubusercontent.com/assets/22897987/21288283/cd197c86-c487-11e6-965e-2619ae237c3e.png)

**Comment by maxlinux2000** [comment]
Hi, I just realized that there are some problems with Cordova push
notifications due the recent migration of GCM to a new system and you can't
use the keys with Cordova.push.plugin. I'm out now but tomorrow I try to
investigate a bit

**Comment by maxlinux2000** [comment]
https://github.com/fechanique/cordova-plugin-fcm



I think that Cordova app need to use this plugin now, but I never use it,
because I have a lot of old GCM keys that I can use for my apps.

**Comment by Nemra1** [comment]
thx for replay but to now RC team dosnt have any plan to add firebase to Rocket chat !

**Comment by maxlinux2000** [comment]
Try with the client rocket.chat-android. it's new, fast and easy to build.
It's not complete, but I hope that it will solved soon

El 17 dic. 2016 7:06 p. m., "Ahmed El Sheikh" <notifications@github.com>
escribió:

thx for replay but to now RC team dosnt have any plan to add firebase to
Rocket chat !

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/RocketChat/Rocket.Chat/issues/5239#issuecomment-267777539>,
or mute the thread

**Comment by Nemra1** [comment]
wher is that ( rocket.chat-android ) ??
sorry im new her

**Comment by maxlinux2000** [comment]
https://github.com/RocketChat/Rocket.Chat.Android

**Comment by antgel** [comment]
Closing as ancient and support-related.
