### ISSUE TITLE
Inline Code Formatting Doesn't Escape Emojis

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#524]
When trying to "escape" the emoji formatting to show someone the code for one, the emoji is displayed instead of what I typed.

![2015-08-20_15-28-18](https://cloud.githubusercontent.com/assets/850391/9394833/44e2148c-4750-11e5-87bb-bc1b8387e057.png)

**Comment by geekgonecrazy** [comment]
This appears to be resolved.  Closing..
