### ISSUE TITLE
create a new private group or direct message from the message input window

### ISSUE THREAD

**Issue by BigMayo** [RocketChat/Rocket.Chat#5240]
Your Rocket.Chat version: 0.48.1
command to create a new private group or direct message from the message input window? 
Similar to /create for channels?

i.e.,
`/create #channel|@username public|private`

**Comment by marceloschmidt** [comment]
Hey @ggazzo could you please open a Pull Request with your solution? Thanks!

**Comment by ggazzo** [comment]
It's done :)
