### ISSUE TITLE
Chat status isn't conveyed accessibly

### ISSUE THREAD

**Issue by ndarilek** [RocketChat/Rocket.Chat#5243]
As a screen reader user, I can't easily find my or other users' chat status.

Where is this information conveyed, both for my own account and for others? I'd like to submit a PR, but the DOM is rather large, and if I knew specific IDs/classes of elements conveying user status then it would help in knowing what to target for the fix.

Thanks.

**Comment by engelgabriel** [comment]
@karlprieb can you please work with @ndarilek to get this improved? I believe we have a ID or CLASS already, please let him know what it is.

**Comment by karlprieb** [comment]
Ofc :)

@ndarilek What exactly do you mean by user status? The status that shows if the user is online, away, busy or offline?

**Comment by geekgonecrazy** [comment]
Related: #3625

**Comment by ndarilek** [comment]
Yes, and I imagine there's some status shown by users in the room list 
as well?

Do the buttons to change status alter in any way? Like, if I click the 
button to go online, does it change to indicate that I'm now online? If 
so, then they may be better modeled as ARIA switches.

**Comment by engelgabriel** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/3625
