### ISSUE TITLE
Jenkins bot for builds not working (API broke ?)

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#5244]
Your Rocket.Chat version: (make sure you are running the latest) 0.48.1
was running 0.46 and everything was working fine. 
now with jenkins rocket chat notifier configured on /api/ -
https://github.com/baloise/rocket-chat-notifier

i get the following error on test - 
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: <!DOCTYPE html>
<html>
<head>
<style>body { background-color: #424242;}</style>
<title>Chat</title><meta name="application-name" content="Chat"><meta name="apple-mobile-web-app-title" content="Chat">
<meta http-equiv="content-language" content=""><meta name="language" content="">
<meta name="robots" content="">
<meta name="msvalidate.01" content="">
<meta name="google-site-verification" content="" />
<meta property="fb:app_id" content="">

<base href="/">

  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/b138a6119577d2c540f72746452efb12c944a556.css?meteor_css_resource=true">  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/theme.css?ef2605775acd262a95c0568523871856947cd221">
<meta charset="utf-8" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="expires" content="-1" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="fragment" content="!" />
<meta name="distribution" content="global" />
<meta name="rating" content="general" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="msapplication-TileColor" content="#04436a" />
<meta name="msapplication-TileImage" content="images/logo/mstile-144x144.png?v=3" />
<meta name="msapplication-config" content="images/logo/browserconfig.xml?v=3" />
<meta name="theme-color" content="#04436a" />
<link rel="manifest" href="images/logo/manifest.json?v=3" />
<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/nocfbnnmjnndkbipkabodnheejiegccf" />
<link rel="icon" sizes="any" type="image/svg+xml" href="assets/favicon.svg?v=3" />
<link rel="icon" sizes="256x256" type="image/png" href="assets/favicon_256.png?v=3" />
<link rel="icon" sizes="192x192" type="image/png" href="assets/favicon_192.png?v=3" />
<link rel="icon" sizes="128x128" type="image/png" href="assets/favicon_128.png?v=3" />
<link rel="icon" sizes="96x96" type="image/png" href="assets/favicon_96.png?v=3" />
<link rel="icon" sizes="64x64" type="image/png" href="assets/favicon_64.png?v=3" />

<link rel="shortcut icon" sizes="16x16 32x32 48x48" type="image/x-icon" href="assets/favicon_ico.ico?v=3" />
<link rel="apple-touch-icon" sizes="57x57" href="images/logo/apple-touch-icon-57x57.png?v=3" />
<link rel="apple-touch-icon" sizes="60x60" href="images/logo/apple-touch-icon-60x60.png?v=3" />
<link rel="apple-touch-icon" sizes="72x72" href="images/logo/apple-touch-icon-72x72.png?v=3" />
<link rel="apple-touch-icon" sizes="76x76" href="images/logo/apple-touch-icon-76x76.png?v=3" />
<link rel="apple-touch-icon" sizes="114x114" href="images/logo/apple-touch-icon-114x114.png?v=3" />
<link rel="apple-touch-icon" sizes="120x120" href="images/logo/apple-touch-icon-120x120.png?v=3" />
<link rel="apple-touch-icon" sizes="144x144" href="images/logo/apple-touch-icon-144x144.png?v=3" />
<link rel="apple-touch-icon" sizes="152x152" href="images/logo/apple-touch-icon-152x152.png?v=3" />
<link rel="apple-touch-icon" sizes="180x180" href="images/logo/apple-touch-icon-180x180.png?v=3" />

</head>
<body>

<style>
.loading {
top: 0;
right: 0;
bottom: 0;
left: 0;
display: flex;
align-items: center;
position: absolute;
justify-content: center;
text-align: center;
}
.loading > div {
width: 10px;
height: 10px;
margin: 2px;
border-radius: 100%;
display: inline-block;
-webkit-animation: loading-bouncedelay 1.4s infinite ease-in-out both;
animation: loading-bouncedelay 1.4s infinite ease-in-out both;
background-color: rgba(255,255,255,0.8);
}
.loading .bounce1 {
-webkit-animation-delay: -0.32s;
animation-delay: -0.32s;
}
.loading .bounce2 {
-webkit-animation-delay: -0.16s;
animation-delay: -0.16s;
}
@-webkit-keyframes loading-bouncedelay {
0%, 80%, 100% { -webkit-transform: scale(0) }
40% { -webkit-transform: scale(1.0) }
}
@keyframes loading-bouncedelay {
0%, 80%, 100% { transform: scale(0); }
40% { transform: scale(1.0); }
}
</style>
<div id="initial-page-loading" class="page-loading">
<div class="loading">
<div class="bounce1"></div>
<div class="bounce2"></div>
<div class="bounce3"></div>
</div>
</div>

<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.4.2.3%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fchat.iugome.com%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%221d10m9yd7fq1hsv663c%22%2C%22accountsConfigCalled%22%3Atrue%2C%22autoupdateVersion%22%3A%22c040473cf15be71851569afbb2bf296e27b7f0f4%22%2C%22autoupdateVersionRefreshable%22%3A%22a1ba008f2912e565e789c834e2d27d3154ed53bf%22%2C%22autoupdateVersionCordova%22%3A%224cd5c977981ce5df322f2748315573ea6c52c2bd%22%7D"));</script>

  <script type="text/javascript" src="/7ed3ecfcc413b624530e9a3126e937921714e74f.js?meteor_js_resource=true"></script>

<script>
if (Meteor._localStorage._data === undefined && window.sessionStorage) {
Meteor._localStorage = window.sessionStorage;
}
</script>

</body>
</html>
; line: 1, column: 2]

**Comment by engelgabriel** [comment]
@graywolf336 did we change some of the URL?

**Comment by graywolf336** [comment]
@engelgabriel Yes, we broke that however I have been working with the maintainers of that package to get it updated. See https://github.com/baloise/rocket-chat-rest-client/pull/5 and https://github.com/baloise/rocket-chat-rest-client/issues/9

**Comment by graywolf336** [comment]
@admin-crowd-iugo Please open an issue about this on the repository of the Jenkins Bot Notifier, as they need to update the internal package they use to point to the new rest api (see my links in the comment above for details).
