### ISSUE TITLE
snap install don't works on Ubuntu 16.04 server

### ISSUE THREAD

**Issue by 4ntoni0** [RocketChat/Rocket.Chat#5246]
Good morning, 
I'm trying (unsuccessfully) to Install rocket.chat-server on a Ubuntu 16.04 LTS server (on a virtual machine with vmware).
The command we use is:

`Snap install rocketchat-server`

After downloading about 70 MB, the system gives me the following error:

```
can not perform the Following Tasks:
- Download snap "rocketchat-server" channel from "stable" (Snap not `found)
```

Can someone help me figure out where I'm wrong?

I had to install it in 30 seconds and I'm going crazy behind by one day :)
Thanks at all.

**Comment by Sing-Li** [comment]
@4ntoni0   more information please ...   vmware on x86_64 platform ?    Are you using the 64bit image of Ubuntu 16.04 ?    [no support for 32 bits]

**Comment by 4ntoni0** [comment]
@Sing-Li hello and thanks for the help.
My vm was installed starting from x86 iso.
Now I'm downloading the iso for amd64 and hope to solve.
I have not been careful to the incompatibility for x86.
Thank you again.
Antonio

**Comment by 4ntoni0** [comment]
With the 64-bit iso the installation procedure has been completed successfully.
Thanks again.
Antonio

**Comment by trendvisor** [comment]
for me not! :( Ubuntu-1604-xenial-64-minimal - this is my command

`sudo snap install rocketchat-server
error: cannot perform the following tasks:
- Download snap "core" (641) from channel "stable" (sha3-384 mismatch downloading core: got 63ed4068fd6cd955a87405b1137c09c7c9665c8961ec9cf7869452907847ad51346624ab3fdb7b47af1ae1b7ffaf68df but expected c234315c8afa2e4e42f951f23650c686d60e44a085fd2ab0933511ee0e136517df96362757c9a2dbfd45bc93f5b0ab20)`

**Comment by 4ntoni0** [comment]
If this can help you I have used this iso:
ubuntu-16.04.1-server-amd64.iso
