### ISSUE TITLE
Border around LDAP-imported avatars

### ISSUE THREAD

**Issue by MarPiRK** [RocketChat/Rocket.Chat#5247]
Your Rocket.Chat version: 0.46.0

For avatars that are imported from LDAP there is white border around it and it is smaller than normal, as you can see in the screenshot:
![screenshot_20161217_231808](https://cloud.githubusercontent.com/assets/1504981/21290140/516c8ab0-c4af-11e6-876f-29d237ff3f7a.png)

Native avatars are presented normally.

**Comment by ToroNZ** [comment]
This happened to me last week. I've fixed it by disabling the option that says "Resize avatar". Can't remember if this was under LDAP or Accounts.

**Comment by MarPiRK** [comment]
Nice, it works for me.
