### ISSUE TITLE
Linux : Multiple separate App popup notifications

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#5248]
I am using Linux(ubuntu16.04) and using the app available. Every time i get a message i get a popup notification and if several messages means several popup messages which i need to close one by one.
As it is an Electron App based on Chromium engine i assume it have the same notification popups, but it is not.

Is there any thing planned for this to sort this issue out?

**Comment by geekgonecrazy** [comment]
@mmarif4u our next release will fix this.  But open a terminal and type this in: `sudo touch /usr/lib/libunity-electron_notification_fix` and restart your Rocket.Chat client.
