### ISSUE TITLE
Add Github (and GitLab) Features

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#525]
Bouncing some ideas around on how to make Rocket.Chat more userful for modern developers after release 1.0.

Got a whole bunch of Github related feature enhancements.   They can also be useful for GitLab users on team servers, private Internet, and Intranets.

Now open for community review.  Please drop a note to let us know if you think any of this may be useful for you or your team.
#### Background:
- good for distributed open source teams, pair programming, code review, tech discussions, scrums
- enable development teams to access ALL aspect of Github repo, 100% within Rocket.Chat
- become member of Github Developers Program 
- for 100% JavaScript based projects  ->  complete workflow integration; no need ever to leave Rocket.Chat
- benefits our alma mater, give back to the global developers community that makes open source projects like Rocket.Chat possible 
- by developers, for developers
- also good for university courses, programming classes, technical training, mentoring, consultants
#### Configuration
- optional, configurable via settings
- only for user logged in oauth'd via Github
#### Features
- per Github project channels
- switch channel to switch project teams
- multiple joined channels = simultaneous multiple teams interactions
- when in project channel - @mentions fetches info from PR and/or Issues
- Gist oembed
- commit notifications
- user info shows recent Github activities
- /merge @PR to merge pull requests
#### Advanced features
- right flex embedded [Ace Editor](https://github.com/ajaxorg/ace) (syntax highlight and other programmer features)
- search and view any source module
- search and view any commit diffs
- blame hover over any source code line
- checkout-edit-commit-PR cycle all within customized Ace embed
- single switchable writer, multiple viewers - broadcast shared Ace session for code review 
- bi-directional link between issues and archived chat messages in which the issue is mentioned
#### Future advanced JavaScript-only features
- webstorm in Javascript - any symbol search source fetch, one-click declaration source fetch, ES6 classes explorer and so on
- local build and deploy workflow
- staging build and deploy workflow
- production build and deploy workflow
- hooks into server-farms offered by emerging 'platform providers' - Galaxy, Famo.us services, and so on
##

**Comment by dosire** [comment]
I was asked to look at this in https://github.com/RocketChat/Rocket.Chat/issues/512#issuecomment-133888391 This all sounds interesting. I'm sure we can do the same things for GitLab. One of the things that I think would be great is cross-linking chats and issues. If I mention an issue in a chat the issue should gain a backlink to the chat conversation. This way information is not lost.

**Comment by Sing-Li** [comment]
Thanks @dosire.   Great idea.  

Rocket.Chat will need to have some sort of archiving capability to effectively support this  (giving every message revision - inclusive of modification and deletion - a permanent unique retrievable address) .  Interesting.  I'll add this to the master list.

**Comment by engelgabriel** [comment]
@Sing-Li we added the archiving capability for modification and deletion  on a PR done by @marceloschmidt last week :)

It is optional tho, you need to turn the feature on in the settings.

**Comment by Sing-Li** [comment]
Very cool :)    @engelgabriel   

Two items:
* how to 'render' a retrieved message revision (a dynamically generated web page?  a read-only chat window? But we can probably just offer an API and the other side does the rendering)
* how to maintain/retrieve the visual context of that message (the screenful of related messages as seen by the user before and after it)

**Comment by Julia991** [comment]
Also I recommend you take a look at the article GitHub vs BitBucket vs GitLab - [https://www.cleveroad.com/blog/github-vs-bitbucket-vs-gitlab-developers-research](https://www.cleveroad.com/blog/github-vs-bitbucket-vs-gitlab-developers-research)

**Comment by louisemessage** [comment]
Nice idea, closing for now as trying to free up issues backlog :)

**Comment by geekgonecrazy** [comment]
These would make for some great app features.  

Maybe we should propose some of these features individually that are missing from the apps functionality?
