### ISSUE TITLE
Mapping user in channels based on LDAP groups?

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#5252]
Your Rocket.Chat version: latest

Hello,
Its possible with latest version of rocket chat make connection between user channels and LDAP groups?
Main idea is, adding user in AD to specific group like ROCKETCHAT-HR, ROCKETCHAT-MANAGERS etc. and base on this user will be automatically joined into channel-s lets say with the same name(or group of channels) - ROCKETCHAT-HR. So I will have control over what default channel-s user will be joined at start.

**Comment by o-jans** [comment]
That feature would be very useful.

**Comment by lucassmacedo** [comment]
Please!! This feature would be very useful.

**Comment by adanielvv** [comment]
duplicate of #2759

**Comment by wreiske** [comment]
Pull request is in: #14278
