### ISSUE TITLE
API login digest password

### ISSUE THREAD

**Issue by steven-tib** [RocketChat/Rocket.Chat#5255]
Is there a way to login with the API/v1/login using the hash password ? 

something like : 

```
curl -H "Content-type:application/json" \
      http://localhost:3000/api/v1/login \
      -d '{ "username": "myusername", "password": "mypassword" }'

```
`mypassword` being : 
```
{
       "digest": "some-digest",
       "algorithm":"sha-256"
}
```

I'm trying to automatically login from my main-app to my chat-app, using the API.

When login on the main app, I would like to catch the password on the server-side with `Accounts.onLogin(doc)` event which returns me the hash password, connect to the chat and be able to run any API commands to mirror/sync the changes from my main-app-->chat-app (new user created, change of username, name, e-mail, avatar,...)

thanks for your help

**Comment by engelgabriel** [comment]
Can't you use the token instead?

**Comment by steven-tib** [comment]
which token should I use ? 

To help you understand my situation: 

my config at the moment is: 
**1) main-app with its own database**
**2) chat-app with its own database**

I have integrated the chat in the main app in an iframe so it's flawless for the user and the login is done only once from the main app. 

I am using workarounds to "clone" the users data from **main-app-db** to **chat-app-db** (on creation, on update, on delete) directly using remote mongoInternals connection to change the chat-db from the main app. 
No updates of the user data is allowed from the chat-app, these parameters are disabled from the rocket.chat settings.

to share the login state, when a user logs in the main app, the resume loginToken is as well inserted in the chat-app-db and I'm using this package [meteor-subdomain-persistent-login](https://github.com/jfrolich/meteor-subdomain-persistent-login) which automatically login/logout the chat app according to the main app.

Is there a cleaner way to have a consistent user database on both side, with same _id, username, pwd, e-mail, OAuth services synchronized at all time? (avoiding direct updates in the chat-db from the main app as I do now..)

I have read solutions where people use the same db for main-app and chat-app which simplifies it but I would like to keep the possibility to scale each independently and keep all control on my main-app-db structure. (avoiding also to change the alanning-roles packages to support array of string structure needed with RC roles).

thanks for the help

**Comment by a5his** [comment]
@steven-tib  what about `iFrame Integration`?

**Comment by steven-tib** [comment]
@a5his I'm trying since few days to test by integrating with iframe,

I'm now having problems with saving the settings of iframe integration, see: [5333](https://github.com/RocketChat/Rocket.Chat/issues/5333) for this issue details.

**Comment by steven-tib** [comment]
I'm closing this issue, all works now.
As suggested above I'm now using the tokens and iframe integration to sync both apps login state. thanks for the advice and help.
