### ISSUE TITLE
(Livechat) Can't reopen channels closed by guests

### ISSUE THREAD

**Issue by iCredibleInc** [RocketChat/Rocket.Chat#5256]
Your Rocket.Chat version: 0.48.1

   Hi ,

1. When our users (most of them guests) press end chat in options.Popup appears when yes clicked popup doesn't close.

2. After (1) channel(between agent and guest) getting close.And users can't send message to us again.
Is there anyway to reopen this channels or a new channel by guest ?

How can i handle this situation please help.

Thanks.

**Comment by sampaiodiego** [comment]
if the guest closes the conversation, the agent cannot open it again.

but the guest can still send messages, if so it will open a new livechat conversation.

**Comment by iCredibleInc** [comment]
Fixed after version 0.48.2 thanks.
