### ISSUE TITLE
Android Push Alert Audio

### ISSUE THREAD

**Issue by shellster** [RocketChat/Rocket.Chat#5263]
This is a feature request: 
I would be really helpful to be able to set audio alerts for Rocket Chat.  When notifications work, they are only vibration alerts.  Audio alerts would be very useful.  Ideally it would be nice to be able to chose the sound.

**Comment by geekgonecrazy** [comment]
Please see: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/132
