### ISSUE TITLE
Rocket.chat not respecting defined color scheme, falls back to default.

### ISSUE THREAD

**Issue by peerchemist** [RocketChat/Rocket.Chat#5265]
**Rocket.Chat version: 0.48.1**

Since last server restart my [rocket.chat instance](peercoin.chat) stopped respecting defined color scheme and started using the default one. There is nothing about this in the logs and this is first such incident in 3 months of operation (multiple upgrades since).

Layout/Colors of this instance are set as following:

* Content Background Color: #f6f6f6

* Primary Background Color: #373737

* Primary Font Color: #444444

* Secondary Action Color: #ffffff

and so on.

Yet this is how app is rendered:

![screenshot from 2016-12-19 20-30-17](https://cloud.githubusercontent.com/assets/7818961/21326239/02e3c328-c62a-11e6-91bd-5402806094c4.png)

I use no custom CSS or scripts.

**Comment by engelgabriel** [comment]
We had some issues with the migrations of color definition from one version to the new settings, can you please try setting up the color again? They should stick this time.

**Comment by peerchemist** [comment]
I am not sure what do you mean to set them again? I've tried that already for almost all fields and nothing worked. Is there a way to reset all values to default maybe, so it purges it and I set it again?

**Comment by engelgabriel** [comment]
Do you have access to the DB? You can delete all settings with `{_id : /theme/}` and restart the server.

Usually when one of the color has an invalid value, it breaks the LESS compiler and the colors don't change.

**Comment by engelgabriel** [comment]
Maybe we need a method to reset the colors.

**Comment by peerchemist** [comment]
@engelgabriel 

Mongo is in docker container and I am no expert with mongo. I think I can enter docker container and use mongo cli utility to access the database. I will need some pointers on how to locate those elements and delete them though.

**Comment by engelgabriel** [comment]
@karlprieb is working on a reset button for the next release.

**Comment by peerchemist** [comment]
I got this from log while upgrading to v0.48.2

> rocketchat:theme ➔ stop_rendering 19
{ [Error: Could not parse call arguments or missing ')']
  type: 'Parse',
  filename: 'input',
  index: 667,
  line: 19,
  callLine: NaN,
  callExtract: undefined,
  column: 46,
  extract: 
   [ '@transparent-lighter: rgba(255,255,255,0.30);',
     '@transparent-lightest: rgba(255, 255, 255, 0.6;',
     '@tertiary-background-color: #373737;' ],
  message: 'Could not parse call arguments or missing \')\'',
  stack: undefined }

**Comment by engelgabriel** [comment]
Go to the admin, and set the value of the transparent-lightest to `rgba(255, 255, 255, 0.6)`

From the log, the last `)` was missing.

**Comment by peerchemist** [comment]
Please re-open this. That was not the reason why it was broken.

I've found this in the log as well: 

> { [Error: error evaluating function `lighten`: color.toHSL is not a function]
  type: 'Runtime',
  filename: 'input',
  index: 178074,
  line: 7318,
  callLine: NaN,
  callExtract: undefined,
  column: 21,
  extract: 
   [ '@selection-background: lighten(@selection-color, 30%);',
     '@success-background: lighten(@success-color, 45%);',
     '@success-border: lighten(@success-color, 30%);' ],
  message: 'error evaluating function `lighten`: color.toHSL is not a function',
  stack: undefined }

It seems to be relevant as well.
