### ISSUE TITLE
Style formatting tweak

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#5266]
I think we should change at least this rule to:
```
		"rule-nested-empty-line-before": [ "always-multi-line", {
			except: ["first-nested"],
			ignore: ["after-comment"],
		} ],
```

**Comment by engelgabriel** [comment]
I agree, but only if we can set the auto formating tool to do it too.

**Comment by sampaiodiego** [comment]
I don't think we should consider the auto formating tool someone uses on his computer as a blocker for a code standards decision.

code standards should aim code quality, readability and maintainability.

please see #5269
