### ISSUE TITLE
Upload of excel issue

### ISSUE THREAD

**Issue by VedranOP** [RocketChat/Rocket.Chat#5268]
Your Rocket.Chat version: 0.48.1

Steps: 
I added application/vnd.openxmlformats-officedocument.spreadsheetml.sheet as supported file upload
Sent an excel file to User A 
User gets a message and the he clicks on a Download button.
Then Internet browser open on rocketcharserverIP/sharelocation.xls and below is a message Access denied to that host.

Please help :) Cheers!

**Comment by VedranOP** [comment]
Update: When I set protect uploaded files to false, the the issue is resolved.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing then...

Cheers
Thomas
