### ISSUE TITLE
joinRoom in REST API is not available

### ISSUE THREAD

**Issue by Jagruti-sangani** [RocketChat/Rocket.Chat#5270]
I am using REST API which are mentioned in Docs as below:
https://rocket.chat/docs/developer-guides/rest-api
I want to allow user to join in conference itself and for that i am trying to find REST API.
I found one API channel.invite but using that API admin user adding the user to conference.
And due to it in channel messages showing "User testuser added by admin."
In web UI i can see the feature where user can join itself.
 So can we expect this feature by Rest API?
This is currently basic feature required in almost mobile application chat so hoping to get this feature in REST API.

Thanks.

**Comment by graywolf336** [comment]
We will add this in the near future, unless you or someone else beat us to submitting a pull request. 👍

**Comment by graywolf336** [comment]
This will be added whenever pull request #5411 gets merged.
