### ISSUE TITLE
Ability to translate messages to different spoken languages.

### ISSUE THREAD

**Issue by ergins23** [RocketChat/Rocket.Chat#5278]
Your Rocket.Chat version: 1.3.1

We have a highly distributed team who speak various languages, it would be great to have a link that translates the message to your spoken language.  This is similar to the feature in Skype, very handy.

**Comment by OnthegOinOz** [comment]
We're also at a point of needing his as well :) - Checking in to see any progress has been made?

**Comment by sampaiodiego** [comment]
you can do this using the `AutoTranslate` feature. It is under `Admin > Message` menu.
