### ISSUE TITLE
Files Uploaded to Channel on Right Panel

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#528]
Having the ability to quickly see what files have been uploaded to the channel you're currently in on the right panel would be really good.

**Comment by gmsecrieru** [comment]
What do you folks think about this? Hacked on browser, very straightforward, we can improve UI based on feedback.
![screen shot 2015-09-30 at 09 14 23](https://cloud.githubusercontent.com/assets/190883/10192622/0907099e-6754-11e5-84a8-7fbc1131244a.png)

**Comment by marceloschmidt** [comment]
I agree! Let's start with that and maybe @rcaferati can work on UI later on, if that's even needed.

**Comment by shtefcs** [comment]
:+1:  for this!

**Comment by sunnipaul** [comment]
I am really looking forward for this simple but useful feature.

**Comment by geekgonecrazy** [comment]
:+1: 

additional :+1: for that dialog you posted a screenshot of ;)
