### ISSUE TITLE
Move room search to main nav

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5280]
![screen shot 2016-12-20 at 20 26 18](https://cloud.githubusercontent.com/assets/1000217/21370463/f2485974-c6f2-11e6-873d-b7177647f8c8.png)

Should be like in the admin area

![screen shot 2016-12-20 at 20 29 35](https://cloud.githubusercontent.com/assets/1000217/21370489/104eedde-c6f3-11e6-9b14-0bcd3ea49c8e.png)

And the current `cmd + p` shortcut would move to focus to the search input.

**Comment by engelgabriel** [comment]
@laggedHero we should have this on the Android too.

**Comment by laggedHero** [comment]
Opening the issue there!

**Comment by karlprieb** [comment]
Done in #5703
