### ISSUE TITLE
Turn emoji tabs into a single scrolling list

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5281]
- [ ] Turn emoji tabs into a single scrolling list divided by sections title
- [ ] Move tone selector beside search field
- [ ] Add footer preview and info 
- [ ] Add tip text on the bottom of the  list

See http://emojicopy.com/

![image](https://cloud.githubusercontent.com/assets/1000217/21370707/3c79d382-c6f4-11e6-9f65-2ac3599f95b1.png)

![screen shot 2016-12-20 at 20 43 35](https://cloud.githubusercontent.com/assets/1000217/21370870/2dadd014-c6f5-11e6-9b19-4f2730bc3536.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"
