### ISSUE TITLE
Running Test

### ISSUE THREAD

**Issue by a5his** [RocketChat/Rocket.Chat#5284]
Your Rocket.Chat version: 0.48.2

I am not able to run the existing test. Below is what I am getting after running `npm test` command. The error says `/tmp/build-test/bundle/main.js`is missing. I don't see this particular path in codebase as well. Am I missing anything while running this test? Can you shed some light on this?

```
> Rocket.Chat@0.49.0-develop test /Users/a5his/dev/Rocket.Chat
> node .scripts/start.js

module.js:341
    throw err;
    ^

Error: Cannot find module '/tmp/build-test/bundle/main.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
Meteor App exited with code 1
npm ERR! Test failed.  See above for more details.
```

**Comment by MartinSchoeler** [comment]
Hey @a5his  The `npm test` command is used for testing in Travis. To run the tests locally you should use the command `meteor npm run chimp-test` with rocket chat running.

**Comment by a5his** [comment]
Thanks @MartinSchoeler 
I am still not able to pass the test. I have attached some screenshots as well. 

<img width="1055" alt="screen shot 2016-12-22 at 12 21 54 am" src="https://cloud.githubusercontent.com/assets/330362/21401554/eef4934c-c7dc-11e6-9184-1af60789a940.png">
<img width="483" alt="screen shot 2016-12-22 at 12 21 33 am" src="https://cloud.githubusercontent.com/assets/330362/21401553/eef22eb8-c7dc-11e6-8d73-dec49e15b9da.png">
<img width="579" alt="screen shot 2016-12-22 at 12 21 20 am" src="https://cloud.githubusercontent.com/assets/330362/21401555/ef17be8a-c7dc-11e6-859e-fb70a0064653.png">

```
Mocha failed

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/a5his/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/a5his/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "run" "chimp-test"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! Rocket.Chat@0.49.0-develop chimp-test: `chimp --ddp=http://localhost:3000 --mocha --path=tests/steps`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the Rocket.Chat@0.49.0-develop chimp-test script 'chimp --ddp=http://localhost:3000 --mocha --path=tests/steps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Rocket.Chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     chimp --ddp=http://localhost:3000 --mocha --path=tests/steps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Rocket.Chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Rocket.Chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a5his/dev/Rocket.Chat/npm-debug.log
```

**Comment by MartinSchoeler** [comment]
@a5his oh sorry my bad! Forgot to mention that you have to start the server and the tests with some environment variables. Take a look in this comment https://github.com/RocketChat/Rocket.Chat/issues/5283#issuecomment-268514944 , it explains how to do it.

**Comment by a5his** [comment]
Closing this. Navigating to #5283
