### ISSUE TITLE
Drag and Drop Channel To/From Favorites

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#529]
Would be neat to have the ability to drag and drop a channel into and out of the favorites.

**Comment by Morgul** [comment]
@graywolf336 How would you guys want to implement drag/drop? The HTML 5 api has good desktop support, and no mobile support: http://caniuse.com/#feat=dragndrop

Alternatively, there's some polyfills, but they all have drawbacks of some kind. Personally, I find drag/drop to be awkward on touch screens a lot of the time anyway, so perhaps not supporting those is acceptable?

**Comment by engelgabriel** [comment]
I don't think this is an important feature. Clicking on the star it easy and clear enough.
