### ISSUE TITLE
Possibility to disable leave Channels 

### ISSUE THREAD

**Issue by mguspero** [RocketChat/Rocket.Chat#5292]
Your Rocket.Chat version: (0.48.1)
Hi, is possible to disable leave a channel? For example the general channel?
Thanks!

**Comment by MartinSchoeler** [comment]
@mguspero could you specify a little bit more what you want? Would you like to prohibit users from leaving a room?

**Comment by mguspero** [comment]
Yes Martin, sorry for my poor explanation. We want to do some communications in the general channel for all the company and disable the possibility to leave these channel. It would also be nice to have the ability to enable or disable it by profile or by channel. Is possible right now?
Thanks!

**Comment by alexandrezia** [comment]
This is also an issue for us, it would be great if users were unable to leave General channel, because the same reasons, such as corporative announcements, etc.

**Comment by mguspero** [comment]
Hi everyone, any news with this? Thanks!

**Comment by JulioFN** [comment]
+1 on this!

**Comment by SergeSpinoza** [comment]
+1

**Comment by ToniIltanen** [comment]
Also, It would be a nice feature to remove #General completely as in none public channels. Now it comes back after server restart (at least it did in the past). We dont have any use for public channels.

**Comment by pokapow** [comment]
+1
Same problem for use, we use de general channel for shoutbox for the community of our website, and as we have lots of people, if users leave and join that can flood the chat

**Comment by edubrites** [comment]
+1 
I'm having the same problem.
I wish there was an option in admin to disable the option to leave the channel, by the users. Because users are included by administrators so they can communicate only among their groups during the project period.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #7268.

Cheers
Thomas

**Comment by GoetheG** [comment]
So is this possible now or not? Would be nice to find out :)

**Comment by GoetheG** [comment]
Are there any news?
