### ISSUE TITLE
All mobile apps broken ?

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#5293]
Your Rocket.Chat version: (make sure you are running the latest) 0.48.1

Downloaded released mobile apps from google store and apple store for rocket chat and they get stuck at downloading files with v0.48.1.
I also signed up for the beta from google play store and it gets past it but does not remember logins if you have multiple rocket chat servers loaded in the app. Closing the app wipes out the login and no notifications appear using the beta app.

**Comment by engelgabriel** [comment]
@admin-crowd-iugo we will push a new version to the stores today with updated cache files. But I just removed and reinstalled the app no my iPhone and it worked ok. Can you share any screenshots of the problem?

**Comment by admin-crowd-iugo** [comment]
Problem still exists in iphone. see attached.
also looks like the android one is just the beta gone official and it auto logs people out with an invalid user message after the app is closed and reopened. 
![img_0093](https://cloud.githubusercontent.com/assets/17622866/21439581/b82d68c2-c843-11e6-99f2-4824af1da35c.PNG)

**Comment by admin-crowd-iugo** [comment]
we are using LDAP auth so i dont know if thats a factor contributing to the auto logout problem.

**Comment by divergefx** [comment]
Hi guys I was having the same issue with the login being stuck at downloading files.  I previously had all the images uploaded in the assets section.  After I removed all except logo, favicon.ico and favicon.svg, my mobile clients were then able to connect.

![image](https://cloud.githubusercontent.com/assets/19717574/21443157/f2c10908-c870-11e6-9388-776832bb4004.png)

**Comment by admin-crowd-iugo** [comment]
yes we have all custom assets loaded as well.

**Comment by engelgabriel** [comment]
Please, wait until apple approves the version 2.5.0 of the iOS apps.

**Comment by engelgabriel** [comment]
The version 2.5.0 of the iOS apps is at the store! Can you please try again?

**Comment by divergefx** [comment]
Hi, I reupped all assets and now it is working perfectly.  Tested on several iOS devices and android tablet. Thank you

**Comment by engelgabriel** [comment]
@admin-crowd-iugo did you manage to test with the version 2.5.0 of the apps?

**Comment by admin-crowd-iugo** [comment]
yes we did. it has the same issue as the android one -  it auto logs people out with an invalid user message after the app is closed and reopened.

**Comment by admin-crowd-iugo** [comment]
notifications come through fine, however (when the app is closed).
clicking on the notification results in a login dialog.

**Comment by divergefx** [comment]
@admin-crowd-iugo did you make sure to click this button on the assets page?

![image](https://cloud.githubusercontent.com/assets/19717574/21702787/bc899614-d37b-11e6-98d5-b3a8aa11f588.png)

I just tested on android phone and we are not having that issue.  closed app open notification and it does not log user out.  opens right up.

**Comment by admin-crowd-iugo** [comment]
i did the apply and refresh clients. it now comes up with there is an update prompt - i click update and it goes to the logon screen. 
next time around it does the same thing. 
so yes i clicked the button and it didnt do much. 

we have all assets loaded including the SVG (which displays as broken  on the mobile clients).

**Comment by admin-crowd-iugo** [comment]
also sometimes on android it seems to get stuck on updating files inifinitely. 
also on ios it goes white screen and hangs.

**Comment by admin-crowd-iugo** [comment]
we are now on 0.48.2 with 7 nodes behind nginx in HTTPS mode. mongodb with replset. node 4.7.0.

**Comment by admin-crowd-iugo** [comment]
maybe just add a ignore assets if there is something wrong / unable to display check ? that would take care of the issue i think....assuming that is what it is related to.

**Comment by admin-crowd-iugo** [comment]
@engelgabriel I have emailed your our private url. you can visit with any mobile client and see the issue right away without logging on. it throws the clients into a update now loop or hangs them.

**Comment by engelgabriel** [comment]
@admin-crowd-iugo can you try the new version 0.49.0?

**Comment by admin-crowd-iugo** [comment]
we have upgraded to 0.49 and hit the image refresh button. Looks like some assets disappeared but we can reupload them. The infinite updating loop is gone in the mobile apps but it still logs the user out with invalid user message after the user quits the app and restarts it. good progress, 90% there. hopefully the next version will fix it completely and allow the user to stay logged in after closing and reopening the app.

**Comment by admin-crowd-iugo** [comment]
i should add the invalid user message also appears on the rocketchat desktop windows client as well now.

**Comment by admin-crowd-iugo** [comment]
Here is the debug log when i relaunch the windows app -
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': '4KwzfgfFnJocsMLET/message', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish roles -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish meteor_autoupdate_clientVersions -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish userData -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish activeUsers -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'roles-change', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'updateEmojiCustom', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'deleteEmojiCustom', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': '4KwzfgfFnJocsMLET/otr', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': '4KwzfgfFnJocsMLET/webrtc', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': '4KwzfgfFnJocsMLET/notification', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'updateAvatar', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish activeUsers -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish userData -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'public-settings-changed', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': '4KwzfgfFnJocsMLET/rooms-changed', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-user -> userId: null , arguments:  { '0': '4KwzfgfFnJocsMLET/subscriptions-changed', '1': false }
rocketchat_lib rocketchat_lib.js:1046 Meteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'permissions-changed', '1': false }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method getUserRoles -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method listEmojiCustom -> userId: null , arguments:  {}
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method public-settings/get -> userId: null , arguments:  { '0': Fri Jan 13 2017 07:35:08 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method permissions/get -> userId: null , arguments:  { '0': Fri Jan 13 2017 07:34:58 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method public-settings/get -> userId: null , arguments:  { '0': Fri Jan 13 2017 07:35:08 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method rooms/get -> userId: null , arguments:  { '0': Wed Dec 31 1969 16:00:00 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method subscriptions/get -> userId: null , arguments:  { '0': Thu Jan 12 2017 16:29:47 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method rooms/get -> userId: null , arguments:  { '0': Wed Dec 31 1969 16:00:00 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method subscriptions/get -> userId: null , arguments:  { '0': Thu Jan 12 2017 16:29:47 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method permissions/get -> userId: null , arguments:  { '0': Fri Jan 13 2017 07:34:58 GMT-0800 (PST) }
rocketchat_lib rocketchat_lib.js:1027 Meteor ➔ method UserPresence:away -> userId: TW5dqLqy9DcWLgCiG , arguments:  {}

**Comment by admin-crowd-iugo** [comment]
we lost around 500+ messages reverting back to 0.48.2. 
0.49 is very buggy.

**Comment by rodrigok** [comment]
The problem of this issue was resolved?

**Comment by admin-crowd-iugo** [comment]
not yet.

**Comment by rodrigok** [comment]
@admin-crowd-iugo Did you upgrade to version 0.49.4? Are you still getting the infinity loading screen?

**Comment by admin-crowd-iugo** [comment]
i tried it on a test server. i no longer get infinity loading screen but i am logged out everytime i connect with the message Invalid User.

**Comment by Mte90** [comment]
I am not sure of this but also us on mobile and desktop lost the notifications of new messages.

**Comment by lapvanluu** [comment]
We are currently on build 0.51.0-develop and we are still having this issue.  You can log in to the server and on the bottom 1/3 of screen is just black, you restart the app and you get invalid user and have to relog in again.

**Comment by TwizzyDizzy** [comment]
Can anybody reproduce this in latest stable (0.62.1)?

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. If this is still reproducible with the latest versions of the mobile clients and the latest server: please get back to me :)

Cheers
Thomas
