### ISSUE TITLE
Room based view modes.

### ISSUE THREAD

**Issue by tonobo** [RocketChat/Rocket.Chat#5299]
Your Rocket.Chat version: 0.48.2

It would be a nice feature to provide users the ability to change the view mode room based. Eg. when your setting up a monitoring channel it would be nice to switch to compact mode. Otherwise on normal discussions a comfortable view mode would be better

**Comment by sampaiodiego** [comment]
thanks for the suggestion. we don't plan to do this but we consider a pull request.
