### ISSUE TITLE
Allow inviting all users from another channel

### ISSUE THREAD

**Issue by childnode** [RocketChat/Rocket.Chat#5301]
would be nice to get something like
`/invite #fun`
i.e.
`/invite #fun@all`
i.e.
`/invite_all_users_from_channel #fun`

should be simple to implement but might be really helpful to "move over" some discussions to a seperate channel without "leaving" the other readers but not force them to activly joining the new channel

labels:
* `type: new feature`
* `contrib: easy`

related:
* Allow giving channel permissions to a bulk of users #5302

**Comment by marceloschmidt** [comment]
Hey @ggazzo could you please open a Pull Request with your solution? Thanks!
