### ISSUE TITLE
Chats are being duplicated or empty left sidebar renders

### ISSUE THREAD

**Issue by RomanKisilenko** [RocketChat/Rocket.Chat#5306]
Your Rocket.Chat version: 0.48.2

We run a rocket.chat in an iframe and test how it works using multiple accounts.

From time to time we experience following issues:
1. Chats or channels might get duplicated. When this happens messages are often not marked as read after user opens a chat and reads the messages. Clearing browser cache solves this in Chrome and restarting Safari helps. 
2. Sometimes the left sidebar renders empty. If this happens a following error can be seen in the console: https://gist.github.com/RomanKisilenko/b0e7c61443f6b148b874dcd9d1e9a4b5. Again, clearing cache in Chrome or restarting safari helps.

This might be two different bugs, let me know if I need to split them.

I would be thankful for any help and we are ready to provide any additional information required.

**Comment by sampaiodiego** [comment]
This is related to our client cache.

@engelgabriel @rodrigok what do you guys think on removing (or at least being able to disable) the client cache? I'm not sure it does what we wanted it to do. I personally don't like how it works and don't see any benefits having it.

**Comment by engelgabriel** [comment]
@rodrigok Maybe we can have a off/on setting for the server until we get this working flawlessly?

**Comment by rodrigok** [comment]
@sampaiodiego @engelgabriel we can add an option to not persist the cache.

@sampaiodiego what about help me to improve it and discuss about benefits?

**Comment by engelgabriel** [comment]
@rodrigok we discussed it briefly, and Diego understand the benefits, we just need to fix this and change a bit of the UX.

**Comment by rodrigok** [comment]
@RomanKisilenko Can you update your server to the latest RC version (0.49.3 currently) and see if the issue still occurs?

**Comment by RomanKisilenko** [comment]
We tested it on 0.49.3 for a few days and this issue did not happen yet. It can be resolved or we did not test enough actively it yet.

**Comment by MartinSchoeler** [comment]
@RomanKisilenko I will be closing this issue then. If the bug reoccurs please reopen this. Thanks for your feedback!
