### ISSUE TITLE
Desktop notification settings is ignored

### ISSUE THREAD

**Issue by RomanKisilenko** [RocketChat/Rocket.Chat#5308]
Your Rocket.Chat version: 0.48.2

We attempted to set desktop notification setting on #general channel to all notifications, but it is still emitting notifications only for mentions

**Comment by marceloschmidt** [comment]
@RomanKisilenko have you tested this on our demo server? It seems to me that it's working as expected.

**Comment by MartinSchoeler** [comment]
Closing this due lack of response
