### ISSUE TITLE
OpLog is Disabled on Sandstorm apps.

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5309]
Sandstorm apps run with OpLog: Disabled

This won't be supported on version 0.49.0 for performance.

![image](https://cloud.githubusercontent.com/assets/1000217/21438205/f838e132-c86e-11e6-8891-c2132d47530c.png)

**Comment by engelgabriel** [comment]
@jadeqwang @kentonv @paulproteus @jparyani  can we enable oplog on sandstorm apps?

**Comment by kentonv** [comment]
As discussed in e-mail, for Sandstorm apps, oplog doesn't bring any benefit, since there is only one Rocket.Chat instance writing to the database. Under Sandstorm, scalability is achieved by running multiple grains, with a small number of channels per grain.

We could nevertheless enable oplog, but it would have the downside of adding several seconds to startup due to forcing Mongo to run a replica master election to elect itself.

If the problem is only performance at scale, can the check be skipped under Sandstorm? Or is there also new code being added that only functions correctly when oplog is enabled?

**Comment by Sing-Li** [comment]
Thanks @kentonv for the thoughtful analysis.

> If the problem is only performance at scale, can the check be skipped under Sandstorm? 

Yes. As @engelgabriel indicated in e-mail discussion, it can.  

Implementation may take some time though.  Meanwhile, we'll likely have to freeze the Sandstorm supported version.

> Or is there also new code being added that only functions correctly when oplog is enabled?

That is indeed the case, starting with 0.49.0 - mainly for the benefit of performance at scale.

@rodrigok  - what do you think of @engelgabriel 's suggestion of a wrapper?

> We could nevertheless enable oplog, but it would have the downside of adding several seconds 
> to startup due to forcing Mongo to run a replica master election to elect itself.

Is this an all-or-none alternative?   Possible to have both accommodated depending on the need of the hosted app?  We certainly do not want to burden other "faster starting" Sandstorm apps.

**Comment by kentonv** [comment]
We could make the oplog optional. This will add a bunch of tricky corner cases to test, though, especially in terms of migrating existing grains to oplog and then migrating grains  back some day if we decide we want to turn it back off.

Before embarking on that I'd like to understand the complexity of supporting single-instance with no oplog. What exactly is the new code in 0.49.0 doing that requires oplog? Can you point me at the code so I can read it?

**Comment by rodrigok** [comment]
@Sing-Li It's not so simple cuz we use some on database calculated operations line `$now`, `$inc`, etc. We need to study this option carefully.

@kentonv We use OpLog to sync our in memory cache. https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/models/_BaseCache.js#L439

**Comment by engelgabriel** [comment]
@rodrigok We could avoid using the `$now` if we trust the server to set the time, and we can do the `$inc` directly on the cached data. Let's evaluate this option further.

**Comment by engelgabriel** [comment]
@kentonv we are working on https://github.com/RocketChat/Rocket.Chat/pull/5371 to close this
