### ISSUE TITLE
Snap: Add ability to configure settings

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#5311]
Need ability to be able to configure the snap and have it restart Rocket.Chat and reflect the changes.

The configuring part should be easy, but causing the service to be restarted we will need to store pid in a file, so that we can kill it.  Because snaps can't execute systemctl

Good reference: https://github.com/nextcloud/nextcloud-snap/blob/master/src/https/utilities/https-utilities#L77

**Comment by sampaiodiego** [comment]
do we know how to do this?

**Comment by geekgonecrazy** [comment]
I think we do still need.  Basically the idea is to use the snap ability to set config to maintain environment variables that are set before startup.

This will allow external mongo and serveral other things too

**Comment by marceloschmidt** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/12351
