### ISSUE TITLE
Constant 100% processor load with multiple rocket.chat instances

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#5312]
Your Rocket.Chat version: 0.48.2 on CentOS 7.3 64bit. 

When I run more than one instance of "node main.js" my processor get hit by 100% load - no single user connected. Running single instance is without problems.

**Comment by engelgabriel** [comment]
Anything in the logs?

**Comment by Abraka** [comment]
Unfortunatelly no.

[root@Rocket.Chat]# MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs ROOT_URL=http://localhost/ PORT=3002 /usr/bin/node /opt/Rocket.Chat/main.js &
[2] 8756
[root@Rocket.Chat]# Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
Updating process.env.MAIL_URL
Updating process.env.MAIL_URL
ufs: permissions are not defined for store "fileSystem"
ufs: store created at
ufs: permissions are not defined for store "fileSystem"
ufs: store created at
ufs: permissions are not defined for store "fileSystem"
ufs: store created at
[Fri Dec 23 2016 09:35:01 GMT+0100 (CET)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
[Fri Dec 23 2016 09:35:01 GMT+0100 (CET)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
[Fri Dec 23 2016 09:35:01 GMT+0100 (CET)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 71.1","time":{"$date":1482482107090},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom emoji storage
[Fri Dec 23 2016 09:35:08 GMT+0100 (CET)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
ufs: permissions are not defined for store "rocketchat_uploads"
Using GridFS for Avatar storage
â System â startup
â +------------------------------------------------+
â |                 SERVER RUNNING                 |
â +------------------------------------------------+
â |                                                |
â |       Version: 0.48.2                          |
â |  Process Port: 3002                            |
â |      Site URL: https://localhost  |
â |         OpLog: Enabled                         |
â |                                                |
â +------------------------------------------------+

**Comment by engelgabriel** [comment]
@rodrigok do you think the 2 process are having problem connecting to each other and getting into a loop?

@Abraka can you turn the debug mode on via the admin interface?

**Comment by Abraka** [comment]
I did that and found one error message which repeat itself in loop:

stream error Can't establish a connection to the server at ws://localhost:3001/websocket
stream error Can't establish a connection to the server at ws://localhost:3002/websocket
stream error Can't establish a connection to the server at ws://localhost:3001/websocket

**Comment by engelgabriel** [comment]
@Abraka can you please try it out with the new version 0.49.0?

**Comment by Abraka** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.27.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.27.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/Rocket.Chat/server/npm-debug.log

**Comment by rodrigok** [comment]
@Abraka Are your processes running in the same machine?
Are you using docker to run each process?
Are you using ports 3001 and 3002?

**Comment by Abraka** [comment]
Are your processes running in the same machine? - yes
Are you using docker to run each process? - no, Im running "MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs ROOT_URL=http://localhost/ PORT=3001 /usr/bin/node /opt/Rocket.Chat/main.js &" 2x with different port, just like in documentation
Are you using ports 3001 and 3002? - yes

**Comment by rodrigok** [comment]
@Abraka Strange, can we talk via chat? Call me at https://demo.rocket.chat/direct/rodrigo.nascimento

**Comment by rasathus** [comment]
I believe I have a similar issue if you need another source of logs.  Im currently running 0.49.3.    Slightly differently I experienced it when running a single instance, but have subsequently increased the instance count as it seems to be the only way to make it useable.  We made ~20 release jump to get here, so can't roll back.

```
top - 13:26:08 up 22 min,  1 user,  load average: 4.08, 3.89, 2.75
Tasks: 147 total,   5 running, 142 sleeping,   0 stopped,   0 zombie
%Cpu(s): 48.9 us,  1.2 sy,  0.0 ni, 49.8 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:   4046680 total,  1505072 used,  2541608 free,    83068 buffers
KiB Swap:  1046524 total,        0 used,  1046524 free.   360748 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                            
 1885 root      20   0 1372672 212616  21080 R 100.1  5.3  15:38.81 nodejs                                                             
 1930 root      20   0 1380372 219952  21100 R 100.1  5.4  15:33.17 nodejs                                                             
 2151 root      20   0 1371456 211352  21108 R 100.1  5.2   7:30.68 nodejs                                                             
 1824 root      20   0 1381988 220484  21052 R  99.8  5.4  16:03.71 nodejs                                                             
  872 mongodb   20   0 13.606g  68016  18144 S   0.7  1.7   0:18.67 mongod                                                             
    1 root      20   0   33472   3908   2648 S   0.0  0.1   0:02.18 init   
```

**Comment by rodrigok** [comment]
Dup of https://github.com/RocketChat/Rocket.Chat/issues/4543

**Comment by rodrigok** [comment]
@rasathus Please see issue https://github.com/RocketChat/Rocket.Chat/issues/4543 We do not support nodejs version 6, please use version 4.x
