### ISSUE TITLE
Right sidebar blank on Internet Explorer 11

### ISSUE THREAD

**Issue by fadanner** [RocketChat/Rocket.Chat#5313]
Your Rocket.Chat version: rocketchat-server  0.48.2   326

Recently installed rocketchat as snap on ubuntu. In Firefox everything I tested works fine, but in Internet Explorer 11, the right sidebar menu is blank only, doesn't matter which tab on the right sidebar. Everything else works as expected in Internet Explorer, too.
IE:
![2016-12-23 10-36-54_constant 100 processor load with multiple rocket chat instances issue 5312](https://cloud.githubusercontent.com/assets/7578777/21450996/febb2a0a-c8fb-11e6-95ba-04830f27899e.png)
FF:
![2016-12-23 10-37-45_pwo chat](https://cloud.githubusercontent.com/assets/7578777/21451005/01ba9952-c8fc-11e6-9594-3150423dee9b.png)

**Comment by Abraka** [comment]
I can confirm this.

**Comment by Abraka** [comment]
Added to 0.50? This is major set back! for installations in corporate enviroments where is only IE. Latest release shouldnt be put out with such a error. Rocket.chat project definitelly need pay much more attention to testing before release of new versions. If you guys really want to get your project even to corporate enviroment, such errors must be covered, else rocket.chat will stay small community project for few fans around.
I dont want to sound hars or something, but such a basic functionalities must be covered so implementators in enterprise enviroments can have some faith in upgrade process.

**Comment by Abraka** [comment]
thx

**Comment by engelgabriel** [comment]
We have the fix, now we just need to merge into develop and test it for a few days, so it can be included on the next release.

**Comment by fadanner** [comment]
So this is included in 0.49? or in version 0.50?
 Btw. is there any documentation about the release plan for ubuntu snap packets. We want to use Rocket.chat hosted as snap package in our company. But it is hard for me to argument for rolling out rocket.chat without a working ie11 version and without a defined date to have it work. Like Abraka said, such things are crucial for corporate environments.
