### ISSUE TITLE
Inconsistencies in REST API

### ISSUE THREAD

**Issue by Fab1en** [RocketChat/Rocket.Chat#5316]
Your Rocket.Chat version: 0.48.2
Hi everybody.

I'm beginning to write a simple PHP client to use the REST API. It's working great, but I have noticed that some methods are using `userID` to reference a user (like [groups.kick](https://rocket.chat/docs/developer-guides/rest-api/groups/kick)) and other are using the user name (like [groups.create](https://rocket.chat/docs/developer-guides/rest-api/groups/create)). Why not using the same identifier for users everywhere ?

Edit : here is the list of inconsistencies I found so far (see comments bellow). 
- [x] userID and userNames for each method call
- [ ] `login` method response does not have the `success` parameter (same for methods that require to be logged-in)
 - [x] there is no way to delete a private group or a channel
 - [x] cannot post a message with `postMessage` using `roomId` param
 - [ ] There is no simple way to get the userId from its username
 - [x] There is no way to change the channel owner after its creation
 - [x] There is no way to list the settings

**Comment by engelgabriel** [comment]
Thanks @Fab1en we are in the process of mapping all the REST APIs to standardize them. Ideally we  would like all APIs to support both `userID` and `username`. Please list here all the inconsistencies you find and we can work together to fix them.

**Comment by Fab1en** [comment]
Great, thanks @engelgabriel. 
I found another inconsistency, but I'm not sure how this can be fixed. All methods reply with a `success` field set to `true` if the method is successful. But `login` answers with a `status` field set to `success`. But that's perhaps to make the difference between a failed call to login (wrong params), and a failed login attempt (wrong password).

**Comment by Fab1en** [comment]
I found another issue : **there is no way to delete a private group**. `groups.close` only close the group for the REST API logged-in user, so that it does not appear in the channel list, but the group itself is still existent (you cannot recreate one with the same name).

**Comment by Fab1en** [comment]
When an action is performed without being logged-in, the answer does not follow the same structure. There is no `success : false` and `error` field in the response, but `status:error` and `message` field.

Example : 
 `chat.postMessage` with a wrong `roomId` : 
```
success: false
error: "Match error: Unknown key in field roomId"
```
`chat.postMessage` without being logged-in : 
```
status: "error",
message: "You must be logged in to do this."
```

**Comment by Fab1en** [comment]
I cannot post a message into a private group using its roomId. 
`chat.postMessage('HCksbzjGo5y6G7aW6', 'test message')` => Match error: Unknown key in field roomId
But the private group exist, and I'm part of it.

Posting to a channel using its channel name works. Posting to a private group using its name (with a leading #) works. The documentation is misleading : `channels.create` creates a public group, `groups.create` creates a private group, groups and channel are both called by the generic term `room`, but groups can still be referenced by their name using the `channel` parameter. Perhaps the parameter should be `roomName` instead of `channel` ?

**Comment by Fab1en** [comment]
There is no simple way to get the userId from its username. Either you login as this user and call `me`, or you call `users.list` and look for the user. We could have a `username` parameter in `users.info` or a filtering parameter in `users.list`.

**Comment by Fab1en** [comment]
There is no way to change the channel owner after its creation. The owner is by default the user that is logged-in when the channel is created.

I would like to forbid users to create new channel so I cannot login as the desired user before creating the channel.

**Comment by Fab1en** [comment]
There is no way to list the settings. If you want a setting value, you have to know its name.

**Comment by mahmoudmahdi24** [comment]
Currently, i am able to Delete a Channel, but it doesn't delete the room in the list of rooms.
In that case, i am not able to recreate a channel with the same name.
I want to be able to delete completely the channel.

**Comment by Fab1en** [comment]
I cannot post a message into a channel via the rest API if I'm logged-in as a non-admin user.
Posting to a channel with admin user account works.
Posting a message with the non-admin user via the web app works.
Making the non-working user an admin solves the issue.
This issue is not present for groups : posting messages to a private group works for non-admin users

**Comment by Fab1en** [comment]
Here is the PHP client I built to use the REST API : https://github.com/Fab1en/rocket-chat-rest-client

**Comment by engelgabriel** [comment]
@Fab1en please use the `develop` branch for tests, as the PR #5261 is now merged.

**Comment by Fab1en** [comment]
@engelgabriel I updated my instance to the latest develop branch (version 0.49.0-develop, commit 757a55ad), and I found that one of the issues listed above is resolved : a message can now be posted using the `roomId` parameter. But other issues are still relevant (or I don't know how to solve them).

I put the list of remaining inconsistencies in this issue description, and I checked the one that are solved. Do you want that I create one issue for each inconsistency ?

**Comment by graywolf336** [comment]
> I cannot post a message into a channel via the rest API if I'm logged-in as a non-admin user.

Are you sure? As I just tried this on a new instance and with a new default user to post to the `#general` channel.

**Comment by graywolf336** [comment]
Also, I'm going to go ahead and check off items as I get them completed in the pull request #5411 so I can use this issue as a reference of what is done and what is left to do. :+1:

**Comment by Fab1en** [comment]
@graywolf336 thanks for your feedback.

Further tests lead me to the root cause : the problem about not being able to post a message via REST API is related to permissions. I have unchecked the `post-readonly` permission for users, and this create a different behaviour between REST API and webapp. A user without the `post-readonly` permission can post to a channel via the webapp but not via the REST API. 
As I already said, groups are not affected by this bug.

**Comment by graywolf336** [comment]
@Fab1en `post-readonly` isn't checked by default for users, so my user in testing never had that permission assigned to them and even with that checked a normal user can post to a normal room just fine.

**Comment by graywolf336** [comment]
Newly implemented: endpoints for deleting channels and groups. Do note, by default regular users can not delete any type of rooms until they are explicitly given permission to do so. These methods obey those rules and if you want regular users to be able to delete channels or groups, they must be given permission to.

**Comment by graywolf336** [comment]
You can now search the `.list` items, so if you wanted to get one user and you have their id:

`http://localhost:3000/api/v1/users.list?query={ "_id": "R4jgcQaQhvvK6K3iY" }&fields={ "username": 1 }&count=1`

Would then return the following:
```json
{
  "users": [
    {
      "username": "graywolf336",
      "_id": "R4jgcQaQhvvK6K3iY"
    }
  ],
  "count": 1,
  "offset": 0,
  "total": 1,
  "success": true
}
```

**Comment by Fab1en** [comment]
Thanks @graywolf336 for those new enhancements, that's cool ! I will test it as soon as possible.

**Comment by Fab1en** [comment]
OK, the permission that makes a difference between REST API and webapp access when you post a message to a channel is not `post-readonly` but `view-c-room`. When `view-c-room` is not checked, you can post via the webapp, but you can't via the REST API.

**Comment by graywolf336** [comment]
Okay, can you open a new issue for that? As that is a little more complex and I'd like to track it separately..thanks

**Comment by graywolf336** [comment]
@Fab1en Please checkout my pull request and test out the changes, all of the items which can be changed have been added. :+1: Let me know your thoughts after testing them! Documentation on our docs will be added shortly after the release comes out. :)

**Comment by Fab1en** [comment]
I tested your pull request @graywolf336 . Great work !
I can now use `username` parameter instead of `userId`. I can change the owner of a channel. I can delete channels and groups completely.  I can list all the settings (433 so far !).

I found an issue with the `users.list?query` method : I get the following error "app is crashed", and the response even doesn't have any `success` or `status` field, just an `error` one.

I noticed a bug, but I don't know if its a regression or not : when I try to delete a group via the web app admin interface, the group is deleted but it does not disappear form the list. If I click again on the same group and click on the DELETE button, I get a 500 error. I have to reload the page to make it disappear.

**Comment by Fab1en** [comment]
I created a new issue (#5477) for the "cannot post a message into a channel via the rest API if I'm logged-in as a non-admin user." item

**Comment by graywolf336** [comment]
Thanks for testing it! 👍

There had to be an error when that happened, can you get the logs for that along with the entire url you used that way I can try to reproduce it.

Please test with a new url and the develop branch to see if that is an issue with these changes or something in develop. As we introduced a cache layer recently, so we just need to verify it isn't my branch and that we can reproduce it very easily.

Thanks for the new issue as well!
