### ISSUE TITLE
Join new channel sound too loud

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#5317]
Your Rocket.Chat version: 48.2

rocketchat's sounds in general are too loud for a lot of my users is there any way to replace or reduce the sounds rocket makes?

**Comment by SeanPackham** [comment]
We have no plans to change the audio levels of the default sounds in the new future. You can edit the default sounds, accessible from `https://github.com/RocketChat/Rocket.Chat/tree/develop/public/sounds`
