### ISSUE TITLE
rocket.cat api webhook -> direct message "error-not-allowed"

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#5318]
Hello,
I've created an incoming webhook and successfully send messages via curl to a channel #general.

For a direct message I used this example: https://github.com/RocketChat/Rocket.Chat/issues/2705 

`curl -X POST --data-urlencode "payload={\"channel\": \"@THEUSERNAME\", \"username\": \"botname\", \"text\": \"test\", \"icon_emoji\": \":asterisk:\"}"  https://rocketchat/hooks/......`

If I try to send a message, I see this reply on the prompt:
{"success":false,"error":"error-not-allowed"}

Then I logged into the system with "THEUSERNAME" and began a conversation with rocket.cat .
The above curl then worked.
**"success":false,"error":"error-not-allowed"}**

Issue: rocket.cat seems to have no right to open up a new conversation with a user to send a direct message, or I'am missing here something.

Version of rocket.chat that is used:
`snap list`
core               16.04.1  641  canonical   -
rocketchat-server  0.48.2   326  rocketchat  -

`uname -ar`
Linux lxvm193-174 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`lsb_release -a`
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Thanks for your assistance
max

**Comment by engelgabriel** [comment]
What user are you using for the webhook? and what role does it have?

**Comment by maxdwit** [comment]
I used the rocket.cat "out of the box" / without changing any permissions or roles.

I just tried to find out where I can see all permissions and/or roles that this user has. I was unlucky.

From the permissions list I think it has something to do with the creation of a new private conversation with a user: "create-p", which is per default not assigned to the Role "bot". ( I guess this is what rocket.cat has, can't see it anywhere in the gui ).
I tried to assign this to the role "bot" however this didn't work out.

**Comment by graywolf336** [comment]
@maxdwit That's because `create-p` is for private groups, if you want bots to start direct messages with users they will need `create-d`. Pull request #5405 will have that permission given to bots by default in new installations if it gets merged.

**Comment by maxdwit** [comment]
Thank you. adding create-d to the permissiongroup "bot" worked like a charm.

**Comment by nguyenvantuan2391996** [comment]
Please add default user : rocket.cat 👍
