### ISSUE TITLE
Is schema doc anywhere?

### ISSUE THREAD

**Issue by katopz** [RocketChat/Rocket.Chat#532]
Hi guys,

I'm trying to find reference like this https://developer.gitter.im/docs/rooms-resource
but can't find any, or maybe it's no schema (yes I'm new to nosql btw)?

Thanks

**Comment by engelgabriel** [comment]
Like this? https://github.com/RocketChat/Rocket.Chat/wiki/Schema-Definition

**Comment by katopz** [comment]
@engelgabriel  Oh! Nice! Thanks
