### ISSUE TITLE
Copy option on mobile app does not copy to clipboard on iOS app

### ISSUE THREAD

**Issue by divergefx** [RocketChat/Rocket.Chat#5322]
Your Rocket.Chat version: 0.48.2

Users are reporting that on iphone and ipad the copy message feature not working.

In addition, the app sometimes crashes when pushing and holding on a message to get the options dialog.

**Comment by laggedHero** [comment]
Hello @divergefx.

I've just fixed the copy issue. If the second issue (crash when open options dialog) still happens, please open a new issue.

C ya!

**Comment by divergefx** [comment]
Thanks @laggedHero
