### ISSUE TITLE
Slash command for changing rooms

### ISSUE THREAD

**Issue by divergefx** [RocketChat/Rocket.Chat#5323]
Your Rocket.Chat version: 0.48.2

Would be a cool feature to have a slash command to change rooms from prompt.

Example:
/jump #ROOMNAME 

reminiscent of IRC but I would find this useful in everyday chat experience

**Comment by a5his** [comment]
@divergefx 

Did you noticed `/open room-name`?

**Comment by engelgabriel** [comment]
you can also use `cmd + p`  on mac or `ctrl + p` on windows.
