### ISSUE TITLE
Disable Chat history per Channel

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5330]
Your Rocket.Chat version: (last)
im lookin about any way to disable Chat history in Public Channel or some Permissions to hiden chat history !

**Comment by wargamesqcf** [comment]
Or a way to limit the back log to normal users would be nice like to the last 20-30 messages. But Admins can every everything forever.

**Comment by Nemra1** [comment]
okey how to limit history? like show only last message

**Comment by wargamesqcf** [comment]
I am also asking for this feature.

**Comment by Nemra1** [comment]
realy we need this ..I have many MSG in My Channels :100:

**Comment by engelgabriel** [comment]
Can you explain better the use case? Why would you limit the history of the public channel?

**Comment by wargamesqcf** [comment]
Performance, and not everyone really needs to know the messages of everyone for the past year.

**Comment by Nemra1** [comment]
I'm using rocket chat like public chat room..so that mean many visitors many members with hundreds of messages..I don't need to save a huge amount messages to databases

**Comment by Lee303** [comment]
Would also like to see this functionality introduced!

**Comment by sampaiodiego** [comment]
we have implemented message retention policy https://github.com/RocketChat/Rocket.Chat/pull/11236

**Comment by GoetheG** [comment]
Hey there. I don't quite get what has been implemented.

What I am looking for is an option to disable the history of a channel for new users. I do not mean to delete anything. I just wish to avoid new users in a group to see what people have been talking about.

We are using Rocket.Chat for our club, our managing board has a separate channel. Most of the time we use Rocket.Chat to discuss potential new members. this conversations are private. So if we vote for a potential new member and add him to our group, then he will be able to see all the previous conversations.

What I am looking for is a way to allow new users to see only the conversations after the time the user joined the channel. Is this possible somehow?

**Comment by sampaiodiego** [comment]
hi @GoetheG .. this is not possible right now. Do you mind opening a new issue on https://github.com/RocketChat/feature-requests describing what you need? thx
