### ISSUE TITLE
Images not shown in dev

### ISSUE THREAD

**Issue by fonsich** [RocketChat/Rocket.Chat#534]
Hi,

no images are shown in dev enviroment. How can i set the ROOT_URL when i want to start up with meteor?

**Comment by rodrigok** [comment]
You can start meteor as:

```
ROOT_URL=http://myurl.com meteor
```

**Comment by fonsich** [comment]
I tried already, command nor found ROOT_URL

**Comment by rodrigok** [comment]
Which SO are you using?

**Comment by fonsich** [comment]
Im running on Windows. Everything works fine just the ROOT_URL is giving me trouble

**Comment by rodrigok** [comment]
So, I don't know how to use env variables in Windows :(

You can try this http://superuser.com/questions/223104/setting-environment-variable-for-just-one-command-in-windows-cmd-exe

**Comment by Sing-Li** [comment]
From an ex-windows user :smile:

set  ROOT_URL = http://myurl.com

or

http://stackoverflow.com/questions/19715617/set-root-url-of-meteor-app-on-windows

**Comment by Sing-Li** [comment]
@fonsich  - pls close issue if you got it working - thx

**Comment by fonsich** [comment]
Thanks, i could set the Var but still don't see any Avatars or Image uploads.
It still says running on localhost:3000

**Comment by Sing-Li** [comment]
are you running meteor from the same command window that you set the ROOT_URL ?

**Comment by fonsich** [comment]
Yes exactly

**Comment by Sing-Li** [comment]
When you type 'set' alone in the command window, make sure you see the ROOT_URL env set correctly.  I just fired up an old windows laptop and tried.   

The meteor sessions should indicate  => App running at: your_root_url

**Comment by Sing-Li** [comment]
Also 'echo %ROOT_URL%'  should print the value you expect.

**Comment by Sing-Li** [comment]
If 'echo %ROOT_URL%' did not print the correct value.  You've probably added a space after the name. Make sure there is no space before and after the equal sign.

**Comment by fonsich** [comment]
Thanks worked for me. Muito Obrigado!
