### ISSUE TITLE
Direct message conversations not sorted alphabetically

### ISSUE THREAD

**Issue by Igloczek** [RocketChat/Rocket.Chat#5341]
Right now users can create usernames with capital letters, which makes sorting results not so friendly, b/c instead of `['apple', 'Banana', 'Pineapple']`, we have `['Banana', 'Pineapple', 'apple']`. It's extremely confusing when you have opened like 30 chats all the time and everyone follows different naming convention (at all the best option will be to replace nicknames with real names, but AFAIK there is an open PR with this feature)

So we have few possible solutions:

Disclaimer: I'm not a back-end guy, I have no idea what's are good patterns here.

1. Force users to use usernames without capital letters - for me this is best option, b/c users have to keep usernames unique, even now we can't create `@user`,`@USER`, `@User` and `@UsEr`, so why not make this simpler? Also this will make everything more consistent, b/c channel names are already limited to lowercase and it works as expected.

2. Use `caseInsensitive` option for `ensureIndex` method, but it's available in MongoDB >= 3.3.11 ->  https://jira.mongodb.org/browse/SERVER-90
AFAIK Rocket.Chat didn't fit this requirements.

3. Store additional field in DB with name in lowercase and use it for sorting purposes only. I tried to make this, but without luck 😢

**Comment by Igloczek** [comment]
@MartinSchoeler any updates on this? It's really painful 😢 
Even when we enable real names, the list is still sorted by nicknames.

**Comment by TwizzyDizzy** [comment]
Could you please have a look at the latest stable? There have been a lot of changes regarding the sorting stuff.

Cheers
Thomas

**Comment by SeanPackham** [comment]
Newer versions of Rocket.Chat prevent users from making channels with capital letters, this fixes the sorting issue mentioned.

**Comment by TwizzyDizzy** [comment]
> Newer versions of Rocket.Chat prevent users from making channels with capital letters, this fixes the sorting issue mentioned.

Erm... even when special characters are allowed in admin settings?

Cheers
Thomas

**Comment by Igloczek** [comment]
@TwizzyDizzy @SeanPackham Is your open.rocket.chat using current version? If it is, this problem is not fixed at all. User names are not sorted ![](https://i.imgur.com/bVMaGFN.png) and channels still have capital letters, but I wasn't reporting it, my goal was to get sorted list under "Direct messages"

**Comment by SeanPackham** [comment]
@Igloczek @TwizzyDizzy I am sorry I thought you were referring to private channels when you mentioned "chat rooms" I tested on private direct messages and can confirm your finding that this is still an issue.
