### ISSUE TITLE
CPU spikes and timeout

### ISSUE THREAD

**Issue by quanticware** [RocketChat/Rocket.Chat#5345]
Your Rocket.Chat version: 0.48.2

Hello,
Each 25~30 sec I have a spike of CPU to 30% of process /opt/Rocket.Chat/main.js, and as result, all clients (web, app OS, etc.) have micro-timeout and show the top-bar "Connection to..." .

What is it?
Thanks!

**Comment by antgel** [comment]
Closing as ancient.
