### ISSUE TITLE
Can't @ offline users

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#535]
I only see the online ones in the list and i didn't find a way to see offline ones...

and hwne i want to @ someone i get a list of more than 2.. but less then 18... why?

![image](https://cloud.githubusercontent.com/assets/11820636/9407400/03f9c60e-4809-11e5-93b1-12d1d9929868.png)

**Comment by geekgonecrazy** [comment]
@raulfiru it really shouldn't show a huge amount when you've just typed the `@`.  That's not enough characters for it to even begin filtering down a potentially massive list.

The issue with it not matching against offline users though, that would be the true issue.

**Comment by rodrigok** [comment]
@raulfiru we have issues with rooms with 10k user or more.

Maybe we can allow show offline users for rooms with less than a certain amount of users, like 200 (maybe can be configured in settings).

**Comment by rodrigok** [comment]
Related https://github.com/RocketChat/Rocket.Chat/issues/337#issuecomment-133486326

**Comment by raulfiru** [comment]
@rodrigok or start the autofill query after a certain number of characters - related to the amount of users... 

Ex: 1000 offline users means the autocomplete starts after 3 characters...

however how realistic will it be to have a room with more than 1000 users? there will be some, but not many.

**Comment by rodrigok** [comment]
@raulfiru we will have some use cases with more than 10k users in the near future.

I will implement some solution so we can test and improve.

**Comment by geekgonecrazy** [comment]
Just thought of this... Its more related to autocomplete in general.  But it should match against most recently spoke in the room.

So if bobsmith recently sent a message when I start typing `@bob` then bobsmith should be first highlighted unless one matches @bob directly.

**Comment by rodrigok** [comment]
Agreed

**Comment by raulfiru** [comment]
It just happened now that i @ someone that didn't say anything in the channel for a long time... on slack

But i guess any fix is better than today. 

i also like the slack feature that you can @ anyone and if they are not in the channel it does an invite. i happened to use it a couple of times as invites
