### ISSUE TITLE
[0.48.2] node-pre-gyp missing

### ISSUE THREAD

**Issue by deogracia** [RocketChat/Rocket.Chat#5350]
* Debian jessie
* Rocket.Chat version: 0.48.2
* node v4.7.0
* npm 1.15.11

when I go into programs/server and ran npm install, I got
```
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
\
> meteor-dev-bundle@0.0.0 install programs/server
> node npm-rebuild.js


> bcrypt@1.0.1 install programs/server/npm/node_modules/meteor/rocketchat_livechat/app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@4.7.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory programs/server/npm/node_modules/meteor/rocketchat_livechat/app/node_modules/bcrypt/build'

[...]


> bcrypt@1.0.1 install programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--update-binary"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bcrypt@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

```

I needed to run _npm install node-pre-gyp_  to make the npm insytall run successfully

I'm not sure if it's here I need to report this issue, but in node-bcrypt, node-pre-gyp is in its package.json.

**Comment by tanc** [comment]
You need to install using npm version 3: https://github.com/RocketChat/Rocket.Chat/issues/5210
`npm install -g npm@3`

**Comment by deogracia** [comment]
Thanks @tanc 

Just read #5210 : I totally didn't see this when I upgraded to 0.48.1 :/
And, since I always reopen rocket.chat's doc following debian setup/update, in case I miss something, it should be stated, for example, that after "npm install -g n", we have to use npm 3.

But since I use debian and nodesource repo (like docs says), it's really weird to says to use 'n' to set nodejs version to 4.x, since it is ship with npm 2.x ( npm 2.15.11 with nodejs 4.6.2 - https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#2016-11-08-version-462-argon-lts-thealphanerd). 

I'll try next time on my dev platform the same upgrade I did here, with the correct version of npm
