### ISSUE TITLE
Cannot compile rocketchat:livechat in OS X

### ISSUE THREAD

**Issue by jm4rc05** [RocketChat/Rocket.Chat#5351]
Version: 0.49.0-develop, updated to the latest right now.

Error: `Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/rocketchat_livechat/assets/talk.html`

Running under OS X 10.12.2.

For now, I commented out rocketchat:livechat from .meteor/packages.

**Comment by engelgabriel** [comment]
I think this is fixed on the develop branch now.
