### ISSUE TITLE
Delete Room from the REST API

### ISSUE THREAD

**Issue by mahmoudmahdi24** [RocketChat/Rocket.Chat#5352]
Hello, 

When are you willing to expose the functionality to Delete a ROOM from the REST API ? 
Currently, i am able to Delete a Channel, but it doesn't delete the room in the list of rooms.
In that case, i am not able to recreate a channel with the same name.
I want to be able to delete completely the channel.

Thanks,

**Comment by graywolf336** [comment]
Duplicate of items mentioned in #5316.
