### ISSUE TITLE
Exit code 139 

### ISSUE THREAD

**Issue by boniyustin** [RocketChat/Rocket.Chat#5356]
Hi, I'm running rocket.chat in docker-toolbox.
I've got this error almost every day.
Any clue to solve this?

I'm using virtual box with 4GB RAM

![error](https://cloud.githubusercontent.com/assets/1172366/21517069/7b6f1ffa-cd0e-11e6-907a-6210e81fd76e.jpg)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
