### ISSUE TITLE
Missing message from edited content in the channel

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5357]
Rocket.Chat version: (0.48.2)

I've posted a message in the channel with mentioning @all. When done posting with the edited text the additional text won't display.
I got this error on View Logs
`Exception while invoking method 'updateMessage' TypeError: Cannot read property '_id' of undefined   at /snap/rocketchat-server/326/programs/server/packages/rocketchat_lib.js:9629:48   at /snap/rocketchat-server/326/programs/server/packages/rocketchat_lib.js:339:24   at Array.reduce (native)   at Object.RocketChat.callbacks.run (/snap/rocketchat-server/326/programs/server/packages/rocketchat_lib.js:334:8)   at Object.RocketChat.updateMessage (/snap/rocketchat-server/326/programs/server/packages/rocketchat_lib.js:3211:33)   at [object Object].updateMessage (/snap/rocketchat-server/326/programs/server/packages/rocketchat_lib.js:9576:25)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/326/programs/server/packages/rocketchat_lib.js:1013:26)   at maybeAuditArgumentChecks (/snap/rocketchat-server/326/programs/server/packages/ddp-server.js:2108:12)   at /snap/rocketchat-server/326/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/326/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/326/programs/server/packages/ddp-server.js:1040:48   at Session.method (/snap/rocketchat-server/326/programs/server/packages/ddp-server.js:1018:23)   at /snap/rocketchat-server/326/programs/server/packages/ddp-server.js:880:89  `

**Comment by MartinSchoeler** [comment]
Hasn't seen this bug in a while. I will close this issue for now, if you see this bug again in the latest version, please reopen this. Thanks!
