### ISSUE TITLE
Leave room bug

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#5358]
Your Rocket.Chat version: Demo
If you try to leave a room where you are the last owner, you get a warning saying that you must set someone to be owner before you leave but the UI shows you that you have left the room. Refreshing the page seems to fix it.
![screenshot from 2016-12-28 09-15-44](https://cloud.githubusercontent.com/assets/20868078/21520762/4971e1b6-ccde-11e6-8532-4fa6d74ac97d.png)

## Steps to reproduce: ##
* Create a channel
* Try to leave the channel 
* Refresh the page

**Comment by MartinSchoeler** [comment]
@karlprieb any ideas?

**Comment by a5his** [comment]
@karlprieb 

Maybe app should warn with a message asking to set another owner when a user(owner) clicks leave icon or want to leave room from any UI for the better experience. 

Also, join icon shouldn't appear unless user/owner leaves a room.

![leave-room](https://cloud.githubusercontent.com/assets/330362/24548938/ce89b684-1636-11e7-80a7-2046f8d14da3.gif)

**Comment by a5his** [comment]
@RocketChat/core

Do we really need client side method `leaveRoom` since there is no any validation against an owner and the total number of an owner? Server method `leaveRoom` already has these validations.

**Comment by rafaelks** [comment]
On **0.63.0-develop**, there's another bug on this UI: the "OK" button now is "Send", but doesn't makes sense.

![screen shot 2018-03-28 at 09 19 54](https://user-images.githubusercontent.com/551004/38028503-799e58f0-3269-11e8-9f53-ee78a49e970c.png)
