### ISSUE TITLE
iOS and Android server trying connect

### ISSUE THREAD

**Issue by viniciogomez89** [RocketChat/Rocket.Chat#5368]
Server Rocket.chat version 0.40.1
iOS Rocket.chat version 2.4.0

![img_4016](https://cloud.githubusercontent.com/assets/16264396/21549511/98277d92-cdc0-11e6-8f03-d3330d25533e.PNG)
![img_4017](https://cloud.githubusercontent.com/assets/16264396/21549512/9829d024-cdc0-11e6-82a0-b383f6b399f9.PNG)
![img_4018](https://cloud.githubusercontent.com/assets/16264396/21549514/982d4524-cdc0-11e6-8d40-cf0cfadd912f.PNG)
![img_4019](https://cloud.githubusercontent.com/assets/16264396/21549513/982b0322-cdc0-11e6-9cad-6694342cbf5d.PNG)
![img_4020](https://cloud.githubusercontent.com/assets/16264396/21549515/982daa28-cdc0-11e6-8c52-385212938958.PNG)

I open Safari, it works fine
![img_4021](https://cloud.githubusercontent.com/assets/16264396/21549516/982f3a1e-cdc0-11e6-929d-8fc036da19db.PNG)
![img_4022](https://cloud.githubusercontent.com/assets/16264396/21549517/9846f712-cdc0-11e6-96cf-b7fc7d28c444.PNG)

**Comment by engelgabriel** [comment]
We have release new version with a lot of fixes.

The iOS one is still waiting for review. 

Can you please check if the problem persist with the latest version of Mobile apps and server?

**Comment by viniciogomez89** [comment]
Can you tell me, what last version number?

**Comment by keypair** [comment]
Just standard rocket.chat app from store? Using android, but happy to try out if you tell me where to download it.

**Comment by viniciogomez89** [comment]
The app for Android downloads in the Play Store, for iOS I downloaded it in AppStore. They are official applications.

**Comment by engelgabriel** [comment]
Server Rocket.chat version should be 0.49.0 (in develop)
iOS Rocket.chat version 2.5.0 (currently in-review)

**Comment by viniciogomez89** [comment]
Well I would have to test the server update, with version 0.48.0, but I do not know much about command lines for CentOS, to perform the update. Without losing the configuration that has been made.

**Comment by engelgabriel** [comment]
iOS Rocket.chat version 2.5.0 is out, please try it?

**Comment by engelgabriel** [comment]
@viniciogomez89 please talk to me at https://demo.rocket.chat if the problem persists.

**Comment by viniciogomez89** [comment]
Yeah, I still with problem

**Comment by madcry** [comment]
have same problem with IOS App
