### ISSUE TITLE
Signup with Email Verification enabled broken.

### ISSUE THREAD

**Issue by sduensin** [RocketChat/Rocket.Chat#5375]
Your Rocket.Chat version:  0.48.2 (snap install)

No username is asked for during signup with email verification enabled.  The resulting user account is not usable.

**Comment by engelgabriel** [comment]
the theory is that only when the users clicks on the email verification he will be able to choose a username. Can you please confirm that even this flow is not happening?

**Comment by sduensin** [comment]
Ah!  That makes sense.  Not usually how validation is done.  I'm used to filling everything out and then just getting that link that activates it.  

Apparently the user didn't receive the validation email.  We were in a hurry and I used the admin panel to verify them and filled in a user name.  Things were kind of odd after that.  (Couldn't invite them to #general, couldn't see them online.)
