### ISSUE TITLE
High nodejs CPU utilization on CentOS 7

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#5379]
Collecting community reports of abnormally high CPU utilization on CentOS 7.

**Comment by Abraka** [comment]
viz. https://github.com/RocketChat/Rocket.Chat/issues/5312

**Comment by engelgabriel** [comment]
Lets keep the focus on #5312

**Comment by engelgabriel** [comment]
PLEASE NOTE THAT NODEJS 6 is NOT currently supported by our framework
