### ISSUE TITLE
Upload File Too Large Message Not Showing

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#538]
Uploading a file too big doesn't give you the notification that it is too big and the upload progress bar stays there.

![2015-08-21_09-21-14](https://cloud.githubusercontent.com/assets/850391/9410518/57bb50a0-47e6-11e5-950d-66882181012d.png)

**Comment by rodrigok** [comment]
<img width="660" alt="captura de tela 2015-08-21 as 22 58 02" src="https://cloud.githubusercontent.com/assets/234261/9422014/2351d7c2-4858-11e5-9d7b-b2c161a77de0.png">
