### ISSUE TITLE
The rocketbot generated a chat option on the left?

### ISSUE THREAD

**Issue by waltonzhang** [RocketChat/Rocket.Chat#5382]
The rocketbot generated a chat option on the left?
Can communicate directly infoshop click directly on the left
USES: can be used to send alerts and so on

![aq 1swa89 b n1c9da zpi](https://cloud.githubusercontent.com/assets/24843320/21577091/0764e702-cf89-11e6-87c8-cb3f37af123f.png)

**Comment by justechn** [comment]
Since we already have rocket.cat, do we need another bot? Let's just have one system bot. In addition rocketbot is not even a real user, so the avatar and username cannot be changed.

**Comment by timkinnane** [comment]
Related #4103

**Comment by timkinnane** [comment]
Duplicates #4016 - closing this one because that and other related tickets have more detail.
