### ISSUE TITLE
Snap: Add builtin Reverse Proxy with auto ssl

### ISSUE THREAD

**Issue by lillstrumpa** [RocketChat/Rocket.Chat#5383]
is there an easy way to configure reverse proxy on a snap installation?!

**Comment by geekgonecrazy** [comment]
@lillstrumpa No built in way currently though we would like to do that in the future.

Currently I would recommend following the instructions in our documentation to setup a reverse proxy like nginx or caddy.  This might be the easiest setup here: https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-a-caddy-reverse-proxy-with-free-ssl

**Comment by geekgonecrazy** [comment]
Going to go ahead and use this ticket to track the adding of built in proxy.
