### ISSUE TITLE
Auto Expand User list For all channels !

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5384]
Your Rocket.Chat version: (make sure you are running the latest)
im lookin about code to auto open user list tap when im login to channel
like this
![2017-01-01_161442](https://cloud.githubusercontent.com/assets/22897987/21581531/7df61260-d03d-11e6-929c-d0e37d27c68f.png)
if any user login to channel > User list open automatic ! any idea how to get that ?

**Comment by SeanPackham** [comment]
We won't support automatically opening the user list when entering a channel.
