### ISSUE TITLE
Unread alert settings are ignored by messages from integrations

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#5385]
Your Rocket.Chat version: 0.49

I've got a channel that is mostly only used by a bot which posts messages in it every few hours, and setting 'unread alert' to 'off' does nothing, I still get 'x unread messages' for that channel

**Comment by geekgonecrazy** [comment]
I believe this is fixed on newer versions.  Please re-open if not the case

**Comment by Sylordis** [comment]
Hi, I'm getting the exact same issue. Windows 7, v2.13.3.
