### ISSUE TITLE
How about making flex-tab closable when we call(audio)?

### ISSUE THREAD

**Issue by Gyubin** [RocketChat/Rocket.Chat#5386]
User may want to chat or send files to opponent while audio-calling. How about placing a calling bar at the top of the screen not opening flex-tab? like iOS?

I was trying to change things but couldn't find the code which opens flex-tab when user click the call button. Would you give me a hint?

![Imgur](http://i.imgur.com/VtfNwuk.jpg)

**Comment by Nemra1** [comment]
rocket chat missing many and many things like call status or call ringtone many and many ...i think RC TEAM need to look at skype or viber style

**Comment by Gyubin** [comment]
I got it. Thank you. 😄
