### ISSUE TITLE
How can I delete "Powered by" field in livechat ?

### ISSUE THREAD

**Issue by iCredibleInc** [RocketChat/Rocket.Chat#5387]
Your Rocket.Chat version: 0.48.2

I checked livechat.js but its unformatted and too complicated.

Can you help me how can i delete or replace it ?

Thanks.

**Comment by Nemra1** [comment]
I think is not cool when u try to delet copyright !

**Comment by vfxpandit** [comment]
Put this in custom css

.powered-by {
  display: none;
}

**Comment by andreapx** [comment]
It doesn't work for me, should I enable the custom css somewhere?

**Comment by RichardFoxworthy** [comment]
this custom CSS does not work on my Snap installation. 

I also saw #10541 - is custom CSS broken generally?, or maybe just for LiveChat? Or maybe just for Snap installations?

**Comment by renatobecker** [comment]
In our current version this is not possible. The only way to do this is forking the project and replacing the logo in there.
The good news is that we have been working on our new Livechat client, you can find the new repository here: https://github.com/RocketChat/Rocket.Chat.Livechat
We're planning many improvements like the one you are requesting here, so my suggestion is to stay tuned to know when we will launch our new Livechat client.

Thanks.

**Comment by atinse** [comment]
Could someone expose just as a little basics how to fork the project like that? I only need to change "Powered by" and icon.svc in Rocket live chat popup cause of my visitors. I have live-chat in my Captive-portal wireless window (home network). But it seams too difficult to made any modifications on that product.

**Comment by reetp** [comment]
Fork github.
Read developer documentation
https://rocket.chat/docs/developer-guides

**Comment by lferezy4** [comment]
Is there any update on this? I was wondering the same thing.

**Comment by durdenclub** [comment]
Hi, Is there any way to remove this. I am using Rocket chat installed via Snap.

**Comment by l3dlp** [comment]
> Hi, Is there any way to remove this. I am using Rocket chat installed via Snap.

I found one tip, by using Caddy server to proxy the snap, and using its filtering method.
Works like a charm for months.

The Caddyfile:
``
domain.tld {
        tls email@domain.tld

        proxy / 127.0.0.1:3000 {
                header_upstream X-Forwarded-Proto {scheme}
                header_upstream X-Forwarded-For {host}
                header_upstream Host {host}
                websocket
        }

        filter rule {
                content_type text/css.*
                search_pattern a,abbr,acronym,address,applet,article,aside,audio,b,big,blockquote
                replacement ".powered-by{display:none !important}a,abbr,acronym,address,applet,article,aside,audio,b,big,blockquote"
        }

        gzip
}
``

**Comment by atinse** [comment]
One solution is to just stop the service. Copy the whole project somewhere else: cp -r /snap/rocketchat* /elsewhere/*. After change the original folder name mv /snap/rocketchat-server --> /snap/old_rocketchat-server.
And finally copy the /elsewhere/rocketchat into same name into /snap/ folder. 
Now you have write access to all snap files. Seems to work like a charm. :)

**Comment by reetp** [comment]
It is bad advice to go messing with snaps as you will lose all your changes on update. It is not really designed to be modified.

Solution is as above. Use the development version.

However, why you can't give Rocket.Chat a bit of credit for powering your site with their Open Source and free software, I don't know. Seems churlish and mean if you ask me.

**Comment by atinse** [comment]
Yes... Sorry, Sir.
For my time with in Linux I have learned at least one thing. That is that there are no such a question like "is that possible" it´s always more like "how is that done possible". 
And within that reason I was hoping to have an answer like "Yes, You can do, but..." and claims within included- off-course.
Than having a lot of false information and lies "you can´t",.. nor  "it´s isolated".
It is my own problem if I want to drive my car in the tree, yes you can do, but think twice before you go there, I want guidings.
Rocket is running only in my home, giving credits for sure if outsourcing ever.....

**Comment by reetp** [comment]
To be honest, trying to remove the Rocket logo is not going to get you a lot of help or sympathy. They need to earn so they can continue to provide Rocket as Open Source. What are you ashamed about?

Of course there may be multiple ways to do things.

But be careful with your advice, and remember inexperienced users may try some methods without realising the consequences may be dangerous.

Snaps are simply not designed to be hacked about, and your method makes no mention of what happens when it autoupdates.

The right answer how to do this has been given above.

Fork, clone, follow the development documentation, and you can then do whatever you want.

**Comment by MuneebKalathil** [comment]
I have added following in **/opt/Rocket.Chat/programs/web.browser/app/livechat/1.chunk.0c6a0.css**

_.powered-by__3NpjT{display:none;}_

Version 3.3.3

It is not snap. Manual Installation.

**Comment by parthamjangir2020** [comment]
> .powered-by {
> display: none;
> }

but how to remove in chatwoot live chat widget branding
