### ISSUE TITLE
New User Form Ignores the "tab" Key

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#5389]
When creating a new user via the admin user form, you can't tab to the next input field.

**Comment by karlprieb** [comment]
@graywolf336 I can't reproduce this bug
![2017-01-02 13 50 41](https://cloud.githubusercontent.com/assets/9200155/21592188/8bde30b4-d0f2-11e6-9785-11df80e9ba85.gif)

Can I close this issue?

**Comment by sampaiodiego** [comment]
@karlprieb that happens sometimes and affects the login screen as well
