### ISSUE TITLE
Prefix Rocket.Chat env variables with ROCKETCHAT

### ISSUE THREAD

**Issue by stephaneeybert** [RocketChat/Rocket.Chat#5390]
Your Rocket.Chat version: 4.7.1

It would help avoid conflicts if environments variables had a ROCKETCHAT_ prefix.

These are good candidates:
export ROCKETCHAT_ROOT_URL=http://localhost:3000/;
export ROCKETCHAT_MONGO_URL=mongodb://localhost:27017/rocketchat;
export ROCKETCHAT_PORT=3000;

**Comment by engelgabriel** [comment]
This is not possible because they are required by Meteor, our JS framework and we cannot change it.
