### ISSUE TITLE
BUG: Video Conference showng in /admin/rooms and hiden in public ! 

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5397]
Your Rocket.Chat version: (48.2)
this in rocket chat deploy from RC SERVER 
https://*****.rocket.chat/channel/general
today im trying to enble Video Conference in public room sound is work and control is completly hiden from all user like this 
![2017-01-03_023256](https://cloud.githubusercontent.com/assets/22897987/21598033/33d6bc40-d15d-11e6-80e6-0df93eb37b0d.png)
now in admin/rooms manger
![2017-01-03_021226](https://cloud.githubusercontent.com/assets/22897987/21599388/b0cfecc8-d174-11e6-9bc5-5555725e6d7f.png)

What Thaaat???

**Comment by Nemra1** [comment]
small fixed and work for me guys.. just open Custom CSS from dashboard and add this code 
```
.list-view {
    z-index: -1;
}
.flex-tab .content {
  z-index: 10;
}
```
its worked for me now and i hope to work for all

**Comment by gabriellsh** [comment]
This doesn't happen anymore. In any case, if you still experience this, please reopen this issue.
