### ISSUE TITLE
Providing overrides / white label container via docker volume mounts

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#540]
@Sing-Li asked me to create this issue.  

Pretty much I started with just wanting to be able to override the favicon.  So I came up with this snippet below.

```
docker run --name rocketchat -p 3000:3000 \ 
-v $(pwd)/favicon.ico:/app/bundle/programs/web.browser/app/favicon.ico \
-v $(pwd)/logo.png:/app/bundle/programs/web.browser/app/images/logo/16x16.png \
-v $(pwd)/logo.png:/app/bundle/programs/web.browser/app/images/logo/57x57.png \
-v $(pwd)/logo.png:/app/bundle/programs/web.browser/app/images/logo/75x75.png \
-v $(pwd)/logo.png:/app/bundle/programs/web.browser/app/images/logo/128x128.png \
--env ROOT_URL=http://site.com:3000 --link db:db -d rocket.chat 
```

So I guess the idea would be that you could override things like this via environment variables.

So things like:
* Favicon
* logo
* css overrides

I'm sure several more.

This would allow many instances of this to be spawned up.

In code this would probably be something like:

`variable = process.env.favicon || defaultvalue;`

**Comment by Sing-Li** [comment]
Related to #277.

The real ingenious part of @geekgonecrazy's approach is that each deployed instance can have a completely different look  - configured at deployment time - without having to customize and re-build and maintain multiple code bases.

For those deploying via docker, this can allow one single VPS or bare-metal to host multiple private-labeled instances of Rocket.Chat simultaneously.  If these are lightly loaded instances, over provisioning (just like shared host) is possible.

**Comment by rodrigok** [comment]
What about use db to store these settings? Maybe the url that respond the favicon can read the settings and look the right file in FS or load from GridFS (maybe we can upload these files in the settings page)

**Comment by geekgonecrazy** [comment]
@rodrigok problem with that is, now the UI depends on the db just to render the page right?  Also increasing the load on the db in larger instances.

**Comment by rodrigok** [comment]
@geekgonecrazy If we use only the settings and get the file from FS using the path in settings we don't use DB, just "redirect" the normal behavior.

**Comment by geekgonecrazy** [comment]
ah! I get what you're saying now.

So technically I could do something like:

```
docker run --name rocketchat -p 3000:3000 \
-v $(pwd)/data:/customdata \ 
-e ROOT_URL=http://site.com:3000 --link db:db -d rocket.chat
```

Then in the settings set `favicon` from disk at `/customdata/favicon.ico`

**Comment by rodrigok** [comment]
Exactly

**Comment by mitar** [comment]
It would be great if those theming would also be pushed to mobile apps. So that when an user open a hosted project, it gets logos and colors over.

**Comment by engelgabriel** [comment]
Icons, logos and favicons can now be set on the Admin Panel.

![image](https://cloud.githubusercontent.com/assets/1000217/11588957/af304110-9a6b-11e5-81a7-6f99a581d6bb.png)

![image](https://cloud.githubusercontent.com/assets/1000217/11588968/c1d8d89a-9a6b-11e5-96fa-f492c8a4c6b1.png)
