### ISSUE TITLE
get user(s) by search email or username API

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5403]
Is there any plan to add new api to search users by fields and customFields like search by email or name or any customFields

**Comment by graywolf336** [comment]
This was implemented in 0.49, the `users.list` takes a query parameter with json search. Documentation is to come.

**Comment by hussamEddinAlhendi** [comment]
yeah thank you today I figure it out I'm trying to implement get info of private group by name now

**Comment by graywolf336** [comment]
`groups.list?query={ "name": { "$regex": "g" } }` You could do something like that

**Comment by hussamEddinAlhendi** [comment]
I'm trying to do groups.info?roomName=testing

**Comment by graywolf336** [comment]
Any of the `.info` require the `roomId` to be passed in.

**Comment by hussamEddinAlhendi** [comment]
yes I know

**Comment by hussamEddinAlhendi** [comment]
I did it

**Comment by hussamEddinAlhendi** [comment]
I will make my first pull request to rocket.chat

**Comment by graywolf336** [comment]
Looking forward to it :+1:

**Comment by billynoah** [comment]
Search users by email:

    groups.list?query={"emails.address" : "johndoe@example.com"}
