### ISSUE TITLE
UX Improvement - No visible notification or exception when failed upload exceeds max size

### ISSUE THREAD

**Issue by alexmarkley** [RocketChat/Rocket.Chat#5406]
Your Rocket.Chat version: 0.48.2 (hosted rocket.chat)

Under certain circumstances (we haven't yet determined which) Rocket Chat fails to upload certain media and displays no feedback in response:
- Nothing appears in the room.
- No error message appears on the screen.
- Nothing appears in the logs at Administration > View Logs

The media which fails to upload includes:
- All videos. (This includes the videos which have been trimmed/recompressed by the mobile app. After the video chooser and the "Upload file?" dialog, nothing happens.
- Some pictures. (We have no idea what triggers this. Some photos will upload and some will not. It doesn't appear to relate to file size, because some larger photos will upload and some smaller photos will not.)

The affected clients:
- Web and iOS. (Unsure about Android as of right now.)

This is effectively a critical issue for us, because we are an entertainment group and we need to collaborate via images and snippets of video.

**Comment by Sing-Li** [comment]
@alexmarkley   

Admin -> Settings -> File Uploads -> Max File Uploads Size 

Please double check and confirm that the size of files you're trying to upload did not exceed the configured (or default) size.

**Comment by alexmarkley** [comment]
Okay, I have experimented with this some more. I can confirm that any file bigger than the default maximum file size of 2MB is triggering this bug. (I was confused about the file sizes because JPEG causes different pictures of the same canvas size to compress to different file sizes.)

So now I guess this is an issue because it *silently* drops the file instead of warning the user that they've hit a global limit. A _lot_ of confusion and tail-chasing on my end could have been avoided if we had a simple error message here.

**Comment by RichardFoxworthy** [comment]
I've just experienced this same bug - pics taken on mobile phone silently failed to upload.

We've increased the max filesize to 5MB mitigate the problem. Newly taken pics do now upload successfully, but the original image files that failed to upload the first time still cannot be uploaded from the phone's file library. 

Any ideas how to enable upload for those previously failed files?

**Comment by louisemessage** [comment]
Tested in Rocket.Chat 2.10.5 on Mac OS 10.13.3. Error message displays for files larger than 2MB.
