### ISSUE TITLE
Can't connect to LDAP server when server has a self signed SSL certificate

### ISSUE THREAD

**Issue by ashrawat** [RocketChat/Rocket.Chat#5408]
Your Rocket.Chat version: 0.48.2

When trying to "Test Connection" to LDAP from admin console, get an error message, "Error. Self signed certificate in certificate chain". Can an option be added to allow connections to an LDAP server that uses self-signed certificate for SSL.

**Comment by seriouz** [comment]
Which format did you pass into the `CA Cert` box?

**Comment by ashrawat** [comment]
I could successfully connect to my LDAP after updating "Reject Unauthorized" to False on the LDAP settings page. There is nothing in the documentation or any additional help text available with "Reject Unauthorized" on the settings page. So, this radio button does allow self-signed LDAP certificates. Thank you.
