### ISSUE TITLE
Document VPS deployment for non-docker users

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#541]
This was pointed out by @carlokok.

We currently do not have instructions for non-docker users deploying Rocket.Chat on either bare-metal or VPS - which happens to be the  way we are deploying the demo server right now :anguished: 

This documentation will be very useful for hackers and makers like @carlokok who may be deploying Rocket.Chat on raspberry pi's,  storage appliances, drones, robotic vacuums, refrigerators, microwave ovens, wine coolers, and so on.

**Comment by rodrigok** [comment]
We have instructions to install in Ubuntu https://github.com/RocketChat/Rocket.Chat/wiki/Installation#ubuntu-install-guide
