### ISSUE TITLE
Add an s3_url property for messages

### ISSUE THREAD

**Issue by wandonye** [RocketChat/Rocket.Chat#5410]
Your Rocket.Chat version: (48.0)

Currently there isn't an API to get the aws s3 url of files attached in messages. As a result, if the storage is set to be AWS_S3, I cannot display pictures sent and stored in my bucket in my React Native app. I checked that the iOS client doesn't support S3 file storage.
It is possible to compute the URL locally in the app. But that would give away the aws access secret to every user, which should never be done.

Suggestion: 
1. add a property to Message, which contains the aws s3 url generated by [`generateURL`](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-file-upload/server/config/configFileUploadAmazonS3.js)
2. expose a method which returns the url above for a given relative url stored in Message. This is needed in addition to 1 because the s3_url could expire.

**Comment by engelgabriel** [comment]
We already to the second option, with a http redirect. You can test it on the demo server. If you upload a file, it will have a relative URL, but if you open that URL on a new window, you will see that it is redirected to a AWS URL. This Redirect is dynamic, as the access token has a 5 minutes expiration token that can be only generated on the server. Can you follow the redirect?

**Comment by wandonye** [comment]
@engelgabriel With what currently demo server has, we would still need a REST api/meteor method which returns the redirected URL for a given relative URL. If I just feed the relative URL to an image component in React Native app, the result is equivalent to requesting the URL without logged in -- Although I have actually already logged in with Meteor.loginWithPassword(). 
There might be other ways around this. Will update here if I have any.

**Comment by engelgabriel** [comment]
We can create a REST api/meteor method which returns the redirected URL for a given relative URL, but you'd need to be logged in to access it, so I am not sure if that would help?

@sampaiodiego can we create this REST api?

**Comment by wandonye** [comment]
@engelgabriel Yes, that will solve the problem. Then I can wrap an Image/Video/etc component with the api/method and pass the redirected URL to the Image/Video/etc component. With this approach, an s3_url property for Message class is not needed. I can cache the media file locally and only invoke the redirecting api when local cached file is not available.

**Comment by wandonye** [comment]
Meteor method will be better since it is faster than REST api.

**Comment by wandonye** [comment]
Is this implemented:

    create a REST api/meteor method which returns the redirected URL for a given relative URL

If not, I will start to work on it.

**Comment by wandonye** [comment]
I have created a PR #5992
