### ISSUE TITLE
mobile layout embedded - main-content translate-x

### ISSUE THREAD

**Issue by steven-tib** [RocketChat/Rocket.Chat#5414]
Your Rocket.Chat version: (0.49)

When using `?layout=embedded` on mobile the `main-content main-modal` div can be translated. This is probably to show the side-nav on touch-slide towards the right direction when not in embedded mode. 

below are two screenshots from chrome mobile devtool showing what happens when translating to the right.

<img width="401" alt="capture d ecran 2017-01-03 23 43 23" src="https://cloud.githubusercontent.com/assets/18457235/21627416/e80da13c-d217-11e6-8f6b-d83724b9dc0c.png">
<img width="391" alt="capture d ecran 2017-01-03 23 43 38" src="https://cloud.githubusercontent.com/assets/18457235/21627417/e80e5aa0-d217-11e6-9f00-738ccb87302f.png">

**Also, testing it directly on the iphone:**
this is what I have when trying to move rocketchat on the mobile with keyboard open : 

_picture 1_: there is a gap between the keyboard and the `main-content `div 
_picture 2_: and this gap can be increased by moving the chat up.
_picture 2_: the same behavior with the translate-x as mentionned above.

PICTURE 1:
![image3](https://cloud.githubusercontent.com/assets/18457235/21627690/cd7ff9a8-d219-11e6-8698-2fca5bcf5611.PNG)

PICTURE 2:
![image2](https://cloud.githubusercontent.com/assets/18457235/21627689/cd7e021a-d219-11e6-87b4-da03659e0ab5.PNG)

PICTURE 3:
![image1](https://cloud.githubusercontent.com/assets/18457235/21627688/cd78e97e-d219-11e6-9d6f-646ced1be70c.PNG)

**Comment by karlprieb** [comment]
It was already fixed.
