### ISSUE TITLE
Add customFields to group.create api

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5416]
We are integrating with rocket.chat system. we have requirement to create groups inside rocket.chat using provided api, however we need to pass additional data as customFields, unfortunately this is not supported by /api/v1/group.create

**Comment by graywolf336** [comment]
@hussamEddinAlhendi And how is this supported in the browser?

**Comment by graywolf336** [comment]
@RocketChat/core Is this something we want to support?
