### ISSUE TITLE
Letter with accents are removed

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat#5417]
Your Rocket.Chat version: 0.48.2

As Italian speaker we use character like `àìòè` that we write but they are stripped from the message after the publish.
We have the same problem also with emoji so I guess that there is a problem of support of unicode text but is a blocking feature for the migration on rocketchat.

**Comment by Mte90** [comment]
Ok I disabled the badwords filter and now I can use the òìàè but can be only a temporary solution because we need also the badwords filter.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I cannot reproduce this on latest stable with the information you provided. Please provide more detail, if this is still present for you on current stable (0.62.1). I'll reopen then.

Cheers
Thomas
