### ISSUE TITLE
Is there is any way to duplicate private groups name 

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5418]
We need to create multiple private groups with the same name.
e.x: two teachers have same class room name (Math) need to create private group for their students named with (Math)

**Comment by engelgabriel** [comment]
Hi @hussamEddinAlhendi 
Unfortunately this is not possible, there is a unique index on the name and we use it :(

**Comment by hussamEddinAlhendi** [comment]
Is there a way to add display name for group instead of name and make name for internal use by rocket.chat this will make it more flexible to show group with any name without restriction  (Allow spaces) like (Math A) (Math B)
