### ISSUE TITLE
Support audio only calls

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#542]
Support for audio only *(without video)* calls would be nice to have feature...

When/If you add the feature...
Please put a separate button for audio calls. Closing the camera after making a video call is annoying...

**Comment by graywolf336** [comment]
:+1:

**Comment by Sing-Li** [comment]
:+1:  

On native mobile apps, it would be ideal to hook into the contact list so you can Rocket.Chat 'call' a contact directly.

**Comment by Sing-Li** [comment]
Implemented on #989.  Closing this ticket.
