### ISSUE TITLE
Bug: 0.48.2 Audio call button does not change hover colour

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#5422]
Your Rocket.Chat version: 0.48.2

Noticed that when you view the panel for a user to call the hover over colour changes for the Video call but not Audio. Some users therefore think that Audio is not working.

I checked the CSS in both Chromium & Firefox

Here the Audio button css does not change

.button.secondary  background-colour #fff
.button.secondary.hover  background-colour #fff

vs here the Video button css does change

.button.primary  background-colour #13679a;
.button.prmary.hover  background-colour #0b3e5c;

See this for some screenshots http://en.zimagez.com/zimage/callbuttons.php

Tried to find out where this is going wrong but it's beyond my coding skills.

**Comment by MartinSchoeler** [comment]
@karlprieb have you seen this bug?

**Comment by reetp** [comment]
FYI it is still there in 0.49.3

**Comment by reetp** [comment]
And 0.49.4

**Comment by MartinSchoeler** [comment]
Looks like it was fixed. Thanks for the feedback!

**Comment by reetp** [comment]
Nope - this is still there in 0.54.2 but I can't reopen the bug.

![demo](https://cloud.githubusercontent.com/assets/3800384/24451195/0aaf280c-147e-11e7-934d-864d755e3258.png)
