### ISSUE TITLE
Rocket.Chat crashes at startup if Slack bridge enabled and slack.com is not reachable

### ISSUE THREAD

**Issue by kentonv** [RocketChat/Rocket.Chat#5426]
Your Rocket.Chat version: 0.48.2 (sandstorm)

If the admin has enabled the Slack bridge option, but slack.com in unreachable, Rocket.Chat crashes at startup. Because it won't start up, the admin cannot use the UI to change the setting back and thus the Rocket.Chat server is broken unless someone tweaks Mongo manually.

This is especially bad on Sandstorm because:
* Slack.com is never directly accessible in the Sandstorm sandbox.
* Sandstorm regularly shuts down grains, after which they can't start up again.
* There is no way for a user to access Mongo directly to fix the problem.

Hence, anyone who enables the slack bridge on Sandstorm permanently loses access to their Rocket.Chat room.

    Exception in callback of async function: Error: getaddrinfo ENOTFOUND slack.com slack.com:443
      at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
      at Object.call (packages/meteor.js:213:24)
      at Object.HTTP.get (/programs/server/packages/http.js:77:20)
      at SlackBridge.populateChannelMap (/programs/server/packages/rocketchat_slackbridge.js:1275:24)
      at /programs/server/packages/rocketchat_slackbridge.js:200:13
      at Function.time (/programs/server/profile.js:301:28)
      at /programs/server/boot.js:304:13
      at /programs/server/boot.js:345:5
      at Function.run (/programs/server/profile.js:480:12)
      at /programs/server/boot.js:343:11

        - - - - -
      at errnoException (dns.js:27:10)
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)

**Comment by kable-wilmoth** [comment]
FYI - I created this pull request that seems to fix this issue.
https://github.com/RocketChat/Rocket.Chat/pull/5430

Not sure if this is how one tries to address an issue in git, especially since it is already assigned.

**Comment by keypair** [comment]
thank you, @kentonv, for reporting! And big thanks also to the quick fix by the rocket chat team!

how can I update? would be great

**Comment by kentonv** [comment]
We'll need the rocket.chat team to submit a new build to the app market so that people can update. Thanks!

**Comment by engelgabriel** [comment]
I can send it tonight.

**Comment by kentonv** [comment]
The new Rocket.Chat build is now available in the app market's "experimental" section:

https://apps.sandstorm.io/?experimental=true

Unfortunately, we identified a bug which breaks migrations from a few versions ago (#5541). Because of this I don't think we should release this version.

However, people who are currently on 0.48.2 (the most recent released version) should be able to upgrade to 0.49.0 with no problems. So, @keypair, I suggest you try it out. Maybe download a backup of your grain first, just in case.

**Comment by engelgabriel** [comment]
We are working on a 0.49.1 version now.
