### ISSUE TITLE
Remove jQuery MiniColors

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5427]
jQuery MiniColors adds over 100k to our CSS for very little use.

Either replace it with ColPick (used by Slack) that is far more efficient. See https://github.com/mrgrain/colpick and we can use from NPM.

Or we should just use http://caniuse.com/#feat=input-color since the color picker is not a core feature of the chat anyway.

@RocketChat/core what do you think?

**Comment by engelgabriel** [comment]
Also very interesting, as has no CSS, just JS: http://jscolor.com/

**Comment by sampaiodiego** [comment]
I think we should use the lightest lib for that.
it's a feature we already have, replacing it by the native color picker would be a downgrade in terms of funcionality to me.

**Comment by sampaiodiego** [comment]
it looks like this:

![image](https://cloud.githubusercontent.com/assets/8591547/21684907/a868af2e-d346-11e6-90a5-ee36f6fe7bc8.png)

but, my concern is that you cannot easily copy & paste the HEX color

**Comment by karlprieb** [comment]
As we discussed here in the office we will use this colorpicker -  https://github.com/DavidDurman/FlexiColorPicker right?
