### ISSUE TITLE
Stop loading KaTeX by default

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5428]
Change our KaTeX package, so the CSS and JS are not included via `api.addFiles`, but using `api.addAssets` , so they can be injected into the `HEAD` of the `index.html` __only__ on servers that have KaTeX enable.

The default should be disabled.

Maybe start using KaTex from NPM?

**Comment by ggazzo** [comment]
we are loading katex using dynamic imports now :)
