### ISSUE TITLE
perform APM level monitoring with newrelic 

### ISSUE THREAD

**Issue by SudeepParajuli** [RocketChat/Rocket.Chat#5432]
Rocket.Chat version: 0.48.2

I am struggling to make a APM level monitoring of rocketchat app with new relic . According to new relic documentation the steps to perform are : 

**Steps :** 

1. Inside the project directory run : 

`npm install newrelic --save` 

2. Add the depencdency inside the package.json file 

“newrelic”: “^1.15.0”

3. Copy the newrelic.js file from the folder node_modules to the project main directory 

`cp node_module/newrelic.js .` 

4. Requre the newrelic inside app.js 
require(“newrelic"); 

I am stuck with step number 4 . I am not sure where to require("newrelic") in the rocketchat project directory .

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
