### ISSUE TITLE
Shortcut to add a reaction

### ISSUE THREAD

**Issue by fabioperrella** [RocketChat/Rocket.Chat#5433]
Hi, it would be nice if it was possible to add a reaction using only the keyboards. (at least, the last message)

I looked in docs and I didn't find anything about this.

So this is a feature-request!

**Comment by Kiran-Rao** [comment]
Slack implements this using `+:emoji:`.

This seems like a good approach.

**Comment by marceloschmidt** [comment]
Duplicate of #3756
