### ISSUE TITLE
Option to set direct messages to private shouldn't exist

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#5438]
Your Rocket.Chat version: 0.49

![image](https://cloud.githubusercontent.com/assets/9200155/21690317/d7b9d2bc-d35a-11e6-811c-7d764056fd46.png)

**Comment by Romich777** [comment]
0.50.1
I made this mistake. How now to repair corrupted direct message channel. Maybe some API request to /api/v1/channels.setType ?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:54601 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWnvv-003j1x-Pu
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:34:03 -0600
Date: Wed, 25 Jan 2017 15:56:49 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485388609;
	bh=0buTQRzWeDII84ytvvJqsfv38StcyExsqsRPdx53uJQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tZpIBdwSjXce23ZS9P5ExMVcI0ZzqhPNV8JzcxUCyGiTXIGro2yLlRAP1CXnIgUAP
	 uE7DrWDwGoUrL6ESoPptBNhztVgVmmB7Pw2mhucopI837heEs4vW6wMnr7a6nsYU20
	 zNv51qkF92gKaa3ZnLz4k8LaTl0dH3aj0h/hQ1jo=

**Comment by karlprieb** [comment]
Closed in favor of #5808
