### ISSUE TITLE
WordPress Oauth - Modify code to verify Wordpress User role

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#5440]
Your Rocket.Chat version: 0.49-develop

Anyone can help me to edit the rocket chat code to verify wordpress user role during Oauth WordPress Login ?

I would like in addition to verify user role before allowing or not the connection to the rocket chat.
If user is member of the role ABC or DEF for example, connection must be granted if not, connection must be denied.

How I can accomplish that ?
Regards

**Comment by wargamesqcf** [comment]
Some of us can't even get the WP plugin to talk with rocket at all to even allow login's. This does include the the paid version.

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
