### ISSUE TITLE
Nothing is happening when I launch click the Jitsi camera in Rocket Chat

### ISSUE THREAD

**Issue by mbcote1111** [RocketChat/Rocket.Chat#5441]
Your Rocket.Chat version: (make sure you are running the latest)

See attached image. Camera is not launching. I have tested on multiple devices.
![issue22](https://cloud.githubusercontent.com/assets/24943174/21692927/64292dfc-d355-11e6-8d65-9ba3353a9659.png)

**Comment by karlprieb** [comment]
Thanks @mbcote1111
We are fixing that :)

**Comment by mbcote1111** [comment]
Thanks. Do you have an ETA for resolution?

**Comment by divergefx** [comment]
I noticed that Jitsi works great in firefox.  Chrome and IE do not.

**Comment by mbcote1111** [comment]
It does not work for me in any browser. It was working up until two days ago and then stopped working.

**Comment by geekgonecrazy** [comment]
Can you give a screenshot of what its doing to you?  I have noticed some bad UI things happening, but the audio video worked just fine.

**Comment by mbcote1111** [comment]
This is very strange. I found the solution. For some reason I needed to
delete the rooms / channels and then re-create them for jitsi to start
working again.

Any idea what would cause this ?

I also upgraded to the newest version but the UI is much worse than
previous versions. The video is very small and awkwardly placed. Are
efforts being made to improve this ?

Thanks

Matt

**Comment by geekgonecrazy** [comment]
This sounds like a recent migration might have failed.  @RocketChat/core anyone have thoughts on that?

As to the UI yes we are aware.  A lot of CSS changes are being made, unfortunately effecting that.

What version of Rocket.Chat are you on currently?

**Comment by mbcote1111** [comment]
This is getting really frustrating. It just happened again. I need to
delete channels and then create new ones for jitsi to continue working...

Can anyone help me?

**Comment by geekgonecrazy** [comment]
@mbcote1111 in the initial post you did not very version of Rocket.Chat you are running.  Which version are you running?

**Comment by mbcote1111** [comment]
0.48.2

**Comment by mbcote1111** [comment]
Any update here? I have't heard anything in days.  Jitsi is no longer working in the new channels that I created.

**Comment by geekgonecrazy** [comment]
@mbcote1111 unfortunately this one did not get resolved in time for this new release.  I would suggest how ever checking out the open in new window feature.

Goto: Admin->Video Conference
![image](https://cloud.githubusercontent.com/assets/51996/21915239/2bd1b812-d8fe-11e6-9462-d446f14a904b.png)

Toggle this to True.  Now when you click it, it'll just pop it out into a new window.  We'll get this resolved though.

**Comment by geekgonecrazy** [comment]
@karlprieb Just an extra visual to show the problem in a different stage: 
![image](https://cloud.githubusercontent.com/assets/51996/21915465/980f9782-d8ff-11e6-93a6-e8edc187a476.png)

**Comment by jszaszvari** [comment]
@geekgonecrazy  - Is that 'Always open in new window' a feature of the upcoming 49.0 release?

That would be super helpful for us as we really want to use jitsi, But I cant see it in ours (Running 48.2)

Thanks 👍

**Comment by sampaiodiego** [comment]
guys since https://github.com/RocketChat/Rocket.Chat/pull/5394 was merged, the bug should be fixed.

**Comment by mbcote1111** [comment]
So if we upgrade to 0.49 it should be fixed?

**Comment by sampaiodiego** [comment]
> So if we upgrade to 0.49 it should be fixed?
@mbcote1111 no. #5394 fix is only on `develop` branch

**Comment by geekgonecrazy** [comment]
I believe will be in 0.49.1 though.  Which won't be too long

**Comment by mbcote1111** [comment]
Seems to be working in open in new window mode which is great in 0.49.0

**Comment by jszaszvari** [comment]
Thanks @geekgonecrazy - it's working perfect in 0.49.2 with the new window functionality 👍 🥇

**Comment by geekgonecrazy** [comment]
@mbcote1111 / @jszaszvari can either of you confirm it works like you expect in the traditional mode also?

**Comment by jszaszvari** [comment]
@geekgonecrazy  - Happy to confirm its working well in both modes now

**Comment by geekgonecrazy** [comment]
Thanks for reporting back :+1:
