### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by dcbell** [RocketChat/Rocket.Chat#5447]
Your Rocket.Chat version: 0.48.2

I have Rocket.Chat running on a virtual server. I installed it via snap. Recently it just completely stopped responding. The server itself seems to be fine. I've tried disabling and re-enabling the snap as well as refreshing it.

Snap info:
tracking:    stable
installed:   0.48.2 (326) 146MB -
refreshed:   2016-12-20 15:21:10 -0600 CST
channels:
  stable:    0.48.2         (326) 0B -
  candidate: 0.39.0         (7)   0B -
  beta:      0.39.0         (7)   0B -
  edge:      0.49.0-develop (384) 0B -

Any suggestions?

**Comment by juesor** [comment]
sudo apt dist-upgrade.

Run that then reboot.

**Comment by dcbell** [comment]
That fixed it right up. Thank you.
