### ISSUE TITLE
(LiveChat) Is there a way to show a preview of an image ?

### ISSUE THREAD

**Issue by iCredibleInc** [RocketChat/Rocket.Chat#5449]
Your Rocket.Chat version: version 0.48.2

I want to send Google Maps location preview url like static image.
When rocket.chat shows preview of it.Livechat doesn't show.

How can i fix this ? Or this feature will be add soon to livechat ?

Thanks.

**Comment by vdittgen** [comment]
+1
Image preview is very useful for support, like when we need to show a process gif for example.
