### ISSUE TITLE
Snap failed to start rocketchat or mongo

### ISSUE THREAD

**Issue by saigop** [RocketChat/Rocket.Chat#5450]
Your Rocket.Chat version: 0.48.2 installed via snap
All of sudden today morning, rocket chat failed by showing 502 Bad Gateway in the browser. 

When i check the status in Journalctl i see the below message,
**

Failed to start Service for snap application rocketchat-server.rocketchat-mongo

**.

I tried restarting the service, restarted the host itself, still it didn't comeup. 

We are taking backup of the common folder available in /var/snap/rocketchat-server/common, and now we are trying to restore it in new instance. 

Anyone faced this issue?

**Comment by Satotripe** [comment]
We have to do `dist-upgrade` for update ubuntu-core for fix it and restart your service or your VM.

**Comment by geekgonecrazy** [comment]
@saigop was @satotripe 's advice helpful?

How much free ram?

Is it on a new version from what it was last time you checked?
Was this unconnected to the internet / off for a while?  0.48.2 has been out for a while, so shouldn't have just freshly landed on yours.  So I don't think it is a change in code base.

**Comment by mvo5** [comment]
@Satotripe if a `apt dist-upgrade` fixed the issue for you, could you please attach the /var/log/apt/{history.log,term.log} files (feel free to edit and only include the relevant parts that include the snapd upgrade). This might give us some clues why hte upgrade fixed the issue.

**Comment by mvo5** [comment]
The `systemctl status -l ` output of the failed unit(s) would also be super helpful :)

**Comment by saigop** [comment]
Sorry for my late reply, am not able to recover the old machine, so all i did is the following,

1. Installed new Ubuntu 16.04 in a new VM Instance
2. Installed latest RocketChat application via snap
3. Took the backup of the tar file of the old RC, which i used to capture daily to my NAS
4. Restored it in the common directory
4. Finally the app got UP and running

**Comment by saigop** [comment]
@geekgonecrazy for your query, its been in 0.48.2, and there is no issue on internet connectivity for that instance. All was fine, all of sudden this happened.

**Comment by Satotripe** [comment]
Ok, I'm in Ubuntu 16.04 server, here my log : 

From /var/log/apt/history.log

`Start-Date: 2017-01-06  10:24:50
Commandline: apt-get dist-upgrade
Requested-By: myuser (XXXX)
Install: snap-confine:amd64 (1.0.43-0ubuntu1~16.04.1, automatic)
Upgrade: snapd:amd64 (2.0.10, 2.17.1ubuntu1), ubuntu-core-launcher:amd64 (1.0.27.1, 1.0.43-0ubuntu1~16.04.1)
End-Date: 2017-01-06  10:24:58`

From /var/log/apt/term.log

`Preparing to unpack .../ubuntu-core-launcher_1.0.43-0ubuntu1~16.04.1_amd64.deb ...
Unpacking ubuntu-core-launcher (1.0.43-0ubuntu1~16.04.1) over (1.0.27.1) ...
Selecting previously unselected package snap-confine.
Preparing to unpack .../snap-confine_1.0.43-0ubuntu1~16.04.1_amd64.deb ...
Unpacking snap-confine (1.0.43-0ubuntu1~16.04.1) ...
Preparing to unpack .../snapd_2.17.1ubuntu1_amd64.deb ...
Warning: Stopping snapd.service, but it can still be activated by:
  snapd.socket
Unpacking snapd (2.17.1ubuntu1) over (2.0.10) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up snap-confine (1.0.43-0ubuntu1~16.04.1) ...
Setting up ubuntu-core-launcher (1.0.43-0ubuntu1~16.04.1) ...
Removing obsolete conffile /etc/apparmor.d/usr.bin.ubuntu-core-launcher ...
Setting up snapd (2.17.1ubuntu1) ...
Log ended: 2017-01-06  10:24:58`

**Comment by mvo5** [comment]
@Satotripe Thanks a lot! This looks all normal.

I tried to reproduce this with snapd 2.17.1ubuntu1, ubuntu-core r423 and then upgrading ubuntu-core to r1357. However I did not see the rocketchat-mongo.service failing. I also rebooted and it kept working. A apt full-upgrade also worked (across reboots too). Would love to get to the bottom of the issue, maybe someone can dig out an old log which might give us some clues.

**Comment by geekgonecrazy** [comment]
@Satotripe going to re-open so we can track until we know this is gone.

https://demo.rocket.chat/channel/ubuntu-snap?msg=HRz4H7hocA8RJw5ik some related info possibly available here when debugging another issue.

**Comment by geekgonecrazy** [comment]
I haven't seen this issue pop up specifically.  So going to go ahead and close

**Comment by chandrahasan** [comment]
Hi Team, I am getting this error 
Failed to start Service for snap application rocketchat-server.rocketchat-mongo 
when i tried to check mongo  db status
