### ISSUE TITLE
Deactivate the @all functionality for specific user groups

### ISSUE THREAD

**Issue by MaxKK** [RocketChat/Rocket.Chat#5451]
I'm using Rocket.Chat as a public, community chat. Some of our users are using the @all functionality too often and all other users think that something important happened. 

Therefore it would be very helpful to be able to deactivate the @all functionality for specific user groups, so that administrators or moderators can update the whole channel, but users are not using it for their own benefit (e.g. promotions).

**Comment by MartinSchoeler** [comment]
@maxKK you can block users from using '@all' in the permission grid in admin view
![selection_018](https://cloud.githubusercontent.com/assets/20868078/21725705/bf6e5da6-d420-11e6-8eaa-162e6e0bcd12.png)

**Comment by MartinSchoeler** [comment]
Closing this due lack of response.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
