### ISSUE TITLE
about nodejs versions

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#5452]
Hello Devs.

On every rocketchat release I struggle to find out which nodejs versions are necessary/supported. For the upcoming 0.49 release. Which nodejs *can* i use? Up to which nodejs release rocketchat works? I'm on gentoo and i cloud install the following versions:

```
-rw-r--r-- 1 root root 3432 Dec 16 01:51 nodejs-0.12.10.ebuild
-rw-r--r-- 1 root root 3432 Dec 16 01:51 nodejs-0.12.17.ebuild
-rw-r--r-- 1 root root 4444 Sep 29 17:39 nodejs-4.6.0.ebuild
-rw-r--r-- 1 root root 4442 Oct 26 12:13 nodejs-4.6.1.ebuild
-rw-r--r-- 1 root root 6080 Oct 19 19:39 nodejs-6.9.0.ebuild
-rw-r--r-- 1 root root 6080 Oct 25 08:28 nodejs-6.9.1.ebuild
-rw-r--r-- 1 root root 6080 Dec 28 19:01 nodejs-6.9.2.ebuild
-rw-r--r-- 1 root root 6080 Oct 27 19:51 nodejs-7.0.0.ebuild
-rw-r--r-- 1 root root 6137 Dec  3 10:18 nodejs-7.2.0.ebuild
-rw-r--r-- 1 root root 6137 Dec 28 19:01 nodejs-7.3.0.ebuild
```

thanks a lot

**Comment by lucasvanhalst** [comment]
4.6.1 is the one you should use

**Comment by MartinSchoeler** [comment]
@himbeere does this solve your question?

**Comment by himbeere** [comment]
@MartinSchoeler well sort of. :-) A lot of things remain in the dark. Do I have to use 4.6.1? Or can I use 4.6.0 also? And what is with 4.7.1 or even one of the 6 series? What I am looking for is a list of recommended nodejs versions. Something like:

0.12.17 does not work
4.6.0 works
4.6.1 works
4.7.1 works
6.* does not work

and so on.

thanks and cheers

**Comment by engelgabriel** [comment]
@himbeere please see https://github.com/RocketChat/Rocket.Chat/releases

**Comment by engelgabriel** [comment]
Or you can search for `nodejs` at our https://github.com/RocketChat/Rocket.Chat/blob/develop/HISTORY.md

**Comment by reetp** [comment]
Looks like it will be 4.7.1 shortly

https://github.com/RocketChat/Rocket.Chat/commit/e4c34638c879bf15edfb1851866ef1e57f7fbce0
