### ISSUE TITLE
Convert (Y) to thumbs up emoji like :) is

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#5453]
Your Rocket.Chat version: 0.48.2

As (Y) is quite popular for a thumbs up 👍 , it would be good to get it to automatically in the same way that :) and :( works

**Comment by FibreFoX** [comment]
Would be nice to configure this globally, this kind of feature is kinda annoying, because you don't expect some URLs or code-snippets to have EMOJIS inside them. (I really got annoyed by this with Skype)

**Comment by happy-dev** [comment]
I am willing to take this on. Any clue where to start, because I am having a hard time to find where the :) :( translation to emoji is made

**Comment by rbprado** [comment]
@happy-dev it looks to be imported from [here](https://github.com/Ranks/emojione/blob/master/emoji.json), as said in this [file](packages/rocketchat-emoji-emojione/generateEmojiIndex.js):

```
var emojiList = JSON.parse(fs.readFileSync('emoji.json', 'utf-8'));

/**
 * update emojiList variable with the most recent emojione release then
 * run: node generateEmojiIndex.js
 * grab the results and put into emojiPicker.js file
 */
```

Maybe the [emojione](https://github.com/Ranks/emojione) project has to provide a support to custom aliases, while I was researching for this, I found this [issue](https://github.com/Ranks/emojione/issues/411).

**Comment by happy-dev** [comment]
Quite busy this week but I have a look ASAP

**Comment by marceloschmidt** [comment]
I wonder if we can't manually change that in the emojilist (while the official package doesn't implement)? 

`var emojiList = JSON.parse(fs.readFileSync('emoji.json', 'utf-8'));`

then 

`emojiList['thumbsup'].aliases.push('(Y)')` or something like that.

**Comment by rbprado** [comment]
Yes, sure! It would perfectly insert the (Y) to the emojiList['thumbsup']['aliases'] key. But I was afraid about hardcoding it right after reading the emoji.json. I dunno but I assumed that it would not be desirable.

I also tried to build and run the app with this fix, following [this issue comment](https://github.com/RocketChat/Rocket.Chat/issues/4908#issuecomment-259613358) and while running the here the (Y) doesn't work. So maybe need to change something more.

**Comment by FibreFoX** [comment]
It is already possible to have custom emojis, why not creating a default-conversion-map which is configurable via global admin-mask? And making it enabled/disabled per user-basis ;) don't be annoying

**Comment by Abi-Abhisek** [comment]
@FibreFoX I am willing to solve this issue. I have gone through the packages of emoji, emoji-custom, emoji-emojione. till now i have deciphered that what emoji-custom ,  emoji-emojione does. But Does the emoji package was created to build to provide the user to choose an emoticon ??

**Comment by FibreFoX** [comment]
Don't know about the package itself, but it I have an area for custom emojis inside the administration ;) so I guess it was might not be created in that fashion, but the RocketChat interfaces say so.

**Comment by abhigyank** [comment]
I would like to be assigned on this one.

**Comment by allmonty** [comment]
Hello, i would like to try to fix this issue.

**Comment by simonv3** [comment]
If I understand @FibreFoX here I think this should kind of be a `won't implement` because an admin can easily add this already to the list of emojis?

I feel like this should be something that the admin toggles, and while we're at it, I think that should be the case for the `B)` translation to 😎 and those kinds of things. I've only ever see them annoy users.

**Comment by FibreFoX** [comment]
@simonv3 Yes, my idea was that this is already possible, at least for some "quick-win" solution. Maybe this can be some setting, which is delivered "out-of-the-box" with a normal installation, but it's a design-decision whom to annoy most. Some users (like me too) are often "confronted" with non-changable decisions. If the administrator chooses to enable this translation, some users might not be honored in their usage of the chat, so this might even turn out to be not a complete solution in case of adding these to the custom emojis.

These are the options as far as I can see:
* server-wide (this just makes it able)
* channel-wide (some channels might not want to have them)
* user-specific (some users are extremly annoyed by these emojis)

This can even be expanded to "permission-level" for using emojis :D a lot of crazy ideas here possible.

**Comment by vchrombie** [comment]
I am really interested to contribute to Rocket.Chat.
Can you help me in getting started?

**Comment by AnshumanPati** [comment]
I would like to be assigned on this issue. Can someone help me guide me on getting started here?

**Comment by vaibhav4595** [comment]
@gdelavald @marceloschmidt Hello, I have just submitted a PR #10064  for this issue. Please take a look and review. 

Thanks.

**Comment by 26prajval98** [comment]
Is this issue fixed  ??

**Comment by vishnu2112** [comment]
I would like to solve this issue and I am a beginner to open source. Can someone helps me or guides me in solving it.

**Comment by ashwaniYDV** [comment]
@tassoevan (y) is rendered as thumbs up emoji but not (Y). Is this issue can be solved by just adding (Y) where (y) is converted to emoji.
I would like to work upon it.

**Comment by subham103** [comment]
I would like to solve this Issue, in fact I am working on it:)

**Comment by ConstantTime** [comment]
Very much willing to contribute to this issue but seeing that already couple of approaches (PR #16659 and PR #10064) have been closed for solving this. Are we looking at some other solution to fix this issue?

**Comment by J-Ankit2020** [comment]
I would like to be assigned on this one.

**Comment by sidharthkumar2019** [comment]
Is it fixed or not?

**Comment by hugocostadev** [comment]
As commented in this PR, the `(y)` is supported and its already working, closing it. Thanks 👍 
https://github.com/RocketChat/Rocket.Chat/pull/16559#pullrequestreview-369771131
