### ISSUE TITLE
After registration, won't direct to chat page unless click back button 

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5456]
After i register, I hit register button, then the page just keeps buffering, won't go to the chat page, unless i hit back button on browser, then it will direct itself to the chat page, why is this happening?

**Comment by MartinSchoeler** [comment]
@jy2008 winch version are you using?

**Comment by jy2008** [comment]
0.42

**Comment by engelgabriel** [comment]
@jy2008 can you please update to the lates version?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
