### ISSUE TITLE
No push notifications on Android when simultaneously logged in in browser

### ISSUE THREAD

**Issue by p-try** [RocketChat/Rocket.Chat#5457]
Your Rocket.Chat version: 0.48.2

Hi,
Push notifications on Android work fine out of the box using the default configuration with gateway.rocket.chat. However, my Android does not receive any notifications when my user is simultaneously logged in on a desktop browser. As soon as I close the browser window on the desktop, notifications on the mobile device continue. Is this a bug or a feature? I would like to have notifications on both devices.

Best regards,
Julian

Thank you, by the way, for this great project. Finally a chat system that I seem to be able to integrate in our self-made CRM.

**Comment by Lucky21110** [comment]
Hello,

Please read this : https://github.com/RocketChat/Rocket.Chat/issues/1602

You can change the code to allow notification to all locations

**Comment by engelgabriel** [comment]
This was a design decision, we did not think people would like to receive push notification when they already in front of their computer. But should turn this into a setting as in the discussion #1602
