### ISSUE TITLE
Move Room Panels under the Room Header

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5459]
@RocketChat/huia 

## Current

Our current Room Panels (called Flex-Tab) is under the Room Header, confusing.

![image](https://cloud.githubusercontent.com/assets/1000217/21727775/0ad8aee6-d42a-11e6-879c-235260816c4e.png)

We need to put the panels under the room header to make clear it is a subsection of the room.

The navigation between panels can also be improved. Maybe use a dropdown menu?

## Refs

Some examples from other chat apps:

![image](https://cloud.githubusercontent.com/assets/1000217/21727436/9227ad7c-d428-11e6-926b-bd6d664367ee.png)

![image](https://cloud.githubusercontent.com/assets/1000217/21727440/9b2dab7e-d428-11e6-88f3-27fb5cc55ef3.png)

![image](https://cloud.githubusercontent.com/assets/1000217/21727452/b5537bfa-d428-11e6-9403-5172dd449526.png)

![image](https://cloud.githubusercontent.com/assets/1000217/21727570/1b9c1930-d429-11e6-8416-c4323cc21ebd.png)

**Comment by Nemra1** [comment]
wow...its amazing

**Comment by fazilou** [comment]
coooooooool

**Comment by MartinSchoeler** [comment]
Done!
