### ISSUE TITLE
Create Master Layout Wireframe

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5460]
![draw](https://cloud.githubusercontent.com/assets/1000217/21728162/f04876f4-d42b-11e6-802d-65e4ec8f5239.png)

Some more samples created by @timkinnane 

[rc-color-files.zip](https://github.com/RocketChat/Rocket.Chat/files/690512/rc-color-files.zip)

**Comment by thiagotomasi** [comment]
@engelgabriel can I help with this issue?
@caioogata are you on this? Do you need any help?

**Comment by caioogata** [comment]
hey thanks @thiagotomasi we are working on it, soon we'll publish here.
would be nice if we can count with your review.

Best,
Caio

**Comment by thiagotomasi** [comment]
@caioogata awesome, I'd love to, count on me!

**Comment by bott0r** [comment]
any news on the updated UX

**Comment by caioogata** [comment]
@bott0r https://app.zeplin.io/project/58890b673c1ac9e62f9ea4db
Here are some screens. Rocket team are now coding.

**Comment by timkinnane** [comment]
@caioogata that link requires a login.

**Comment by bott0r** [comment]
@caioogata  thx!

**Comment by jszaszvari** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/7643

**Comment by caioogata** [comment]
@timkinnane You need to create a user on zeplin and then we need to invite you to the board project.

Just post your user here.

Thanks.

**Comment by timkinnane** [comment]
@caioogata - username: **teeks** - thanks!

**Comment by jszaszvari** [comment]
@timkinnane If you could add **jszaszvari** as well that would be much appreciated 

Thanks!

**Comment by caioogata** [comment]
dammit, gonna need your email @timkinnane 
@jszaszvari add.

thanks

**Comment by timkinnane** [comment]
@caioogata timkinnane@gmail.com ;) thanks agin.

**Comment by jszaszvari** [comment]
Thanks! Looking good :)

**Comment by caioogata** [comment]
Done!

**Comment by bott0r** [comment]
invite spam0r

**Comment by caioogata** [comment]
zeplin needs a e-mail for a first invite. @bott0r

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, because IMO this has been implemented.

Cheers
Thomas
