### ISSUE TITLE
Improve Message Form

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5462]
The current message form is a bit messy

## Current

![image](https://cloud.githubusercontent.com/assets/1000217/21730127/6a99f03c-d435-11e6-904c-78913286dd15.png)

- Replace the several buttons with a single PLUS button that opens a popup
- Make the border prettier
- Remove help message from underneath
- Create reply/quote area (thread)

## Refs

![image](https://cloud.githubusercontent.com/assets/1000217/21730194/be3fcb12-d435-11e6-899d-07288658eb57.png)

![image](https://cloud.githubusercontent.com/assets/1000217/21730230/ee8f3bc2-d435-11e6-9703-395d4549ecc5.png)

![image](https://cloud.githubusercontent.com/assets/1000217/21731521/e9ffe222-d43b-11e6-9006-2d4088ee1047.png)

![image](https://cloud.githubusercontent.com/assets/1000217/21731661/8d4a6330-d43c-11e6-84f5-af5bef04469a.png)

**Comment by Nemra1** [comment]
nice work 
any future to add font color?

**Comment by Molle500** [comment]
Please make the list customizable of which options we want to be in there like be able to remove google drive and onedriv etc.. :)

**Comment by fazilou** [comment]
will be amaizing

**Comment by engelgabriel** [comment]
See https://github.com/RocketChat/Rocket.Chat/issues/346 too.

**Comment by thiagotomasi** [comment]
Hey guys, I believe I can help with this issue!
Here is one idea that I got to organize and improve the hierarchy of this component.

In this picture, I made the normal state and the active state of every action, like plus button, placeholder text, help text (with will only appear when the user starts to type) and the popup.

In the popup, I made 2 different approaches, one with labels and another without labels. 

![artboard](https://cloud.githubusercontent.com/assets/4387026/23441703/868ed674-fe2c-11e6-9501-937c735b150a.png)

Let me know your thoughts! 😄

**Comment by jsumners** [comment]
Please add support for https://github.com/RocketChat/Rocket.Chat/issues/4563

**Comment by cyclops24** [comment]
@engelgabriel +1 for this new reply design:
![asdasd](https://cloud.githubusercontent.com/assets/1000217/21731521/e9ffe222-d43b-11e6-9006-2d4088ee1047.png)
Now `Reply` and `Forward` are very messy.

**Comment by cyclops24** [comment]
@engelgabriel any news about new design?

**Comment by engelgabriel** [comment]
This have been implemented.
