### ISSUE TITLE
Improve Message Actions

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#5464]
## Current

![jan-06-2017 21-07-05](https://cloud.githubusercontent.com/assets/1000217/21735933/52d60746-d454-11e6-9ebf-87edaba01a81.gif)

The cog is too small, and since is hides ALL actions, it requires an extra click to do ANYTHING, even frequent actions like add reaction or reply.

It also does not work well on narrow screens.

# Refs

### Slack

![jan-06-2017 21-10-32](https://cloud.githubusercontent.com/assets/1000217/21735991/a883ea32-d454-11e6-9920-ac09d3c7fa52.gif)

### Gitter

![jan-06-2017 21-13-14](https://cloud.githubusercontent.com/assets/1000217/21736039/01728766-d455-11e6-8544-1d4c2a25412c.gif)

### Discord

![jan-06-2017 21-18-20](https://cloud.githubusercontent.com/assets/1000217/21736147/b2856136-d455-11e6-8709-17c22cd3352b.gif)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, because IMO this has by & large been implemented.

Cheers
Thomas
