### ISSUE TITLE
Centos 6 systemctl: command not found

### ISSUE THREAD

**Issue by naguchennai** [RocketChat/Rocket.Chat#5465]
How configure Rocket.Chat to start as a service.?
if run 
`systemctl enable rocketchat.service`
-bash: systemctl: command not found

Rocket.Chat centos6 not support?

**Comment by reetp** [comment]
Works perfectly on CentOS 6 but you cannot use a systemd service file as you have no systemd (Yay... !!)

You need to use the forever-service installer which will generate a init.d service script.

Take look here for an idea of how to install and use the forever-service:

https://wiki.contribs.org/Rocket_Chat

Note that once you have generated the init file you can keep yourself a copy and do not need the forever-service in the future

Or just use Koozali which is based on CentOS 6 and just use my installer :-)

https://wiki.contribs.org/Rocket_Chat:Contrib

**Comment by MartinSchoeler** [comment]
Closing this issue due @reetp answer. If this answer does not solve this, feel free to reopen this. Thanks!
