### ISSUE TITLE
Rest api Auth-Token where i get it?

### ISSUE THREAD

**Issue by naguchennai** [RocketChat/Rocket.Chat#5466]
Your Rocket.Chat version: (make sure you are running the latest)
User Create
`curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/users.create \
     -d '{"name": "name", "email": "email@user.tld", "password": "anypassyouwant", "username": "uniqueusername", "customFields": { "twitter":"userstwitter" } }'`

"X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" where i get it?

-H "X-User-Id: aobEdbYhXfu5hkeqG" \ who is this uder id?

**Comment by Sing-Li** [comment]
@naguchennai  

Please see the documentation:

https://rocket.chat/docs/developer-guides/rest-api/authentication/#rest-api-authentication

**Comment by naguchennai** [comment]
/api/v1/login this is for login
/api/v1/logout this is for logout
/api/v1/me this is for get info after login

How can user register? 
/api/v1/users.create this one ask User-Id ..  i think old user can creat new user? why is this?

where is sign-up api?

**Comment by linaseniorwebdev** [comment]
/api/v1/users.register

This is an API for users to register.

Please see https://rocket.chat/docs/developer-guides/rest-api/users/register/ for further information.
