### ISSUE TITLE
Rest api what is signup/ register?

### ISSUE THREAD

**Issue by naguchennai** [RocketChat/Rocket.Chat#5467]
Your Rocket.Chat version: (make sure you are running the latest)
How can register user with rest api? there is no api https://someServer.com/api/bulk/register

**Comment by naguchennai** [comment]
[https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/users.js](url)

`RocketChat.API.v1.addRoute('users.create', { authRequired: true }, {`

Create user need authRequired?
where is register user api?

**Comment by MartinSchoeler** [comment]
@naguchennai have already read the documentation on the api? Here: https://rocket.chat/docs/developer-guides/rest-api

**Comment by graywolf336** [comment]
There is no rest api for a user to register their own account, the users.create allows users with permission to create other users. I am not sure if we even want to allow user registrations via the rest api..

**Comment by naguchennai** [comment]
If this is my chat site "https://chat.rocket.chat" there is a link to register option. But if i want develop my mobile app or insert in to workpress joomla for my site No API for register? really? Lol

**Comment by engelgabriel** [comment]
@graywolf336 I understand @naguchennai use case. Indeed any REST client that allows for registration would need such API, so lets wrap the Method into a REST API like the others?
