### ISSUE TITLE
Add user session specific class or attribute to manipulate with custom css

### ISSUE THREAD

**Issue by saram-kon** [RocketChat/Rocket.Chat#5469]
Your Rocket.Chat version: 48.1

This is a feature request. It is already possible to alter the style of messages from specific users with the attribute selector for the data-username attribute. It would be really awesome, if it would additionally be possible to alter the css just for specific users, by adding a session specific class or attribute to be used with selectors. I don't know if this is something which is desired by the dev team and how this could be made possible in the best way, but I could eventually invest some time into trying to implement it, if I get some feedback.

**Comment by saram-kon** [comment]
I found a solution and created a pull request. This is my first pull request ever so don't judge too harshly 😄

**Comment by graywolf336** [comment]
See my comment on #5478
