### ISSUE TITLE
Rename channel/group throws error

### ISSUE THREAD

**Issue by rwakida** [RocketChat/Rocket.Chat#547]
To replicate:
1. create a channel c1
2. rename channel c2
3. notice url is wrong and room name disappears
4. click on c2 channel in the SideNav.  
5. console error: TypeError: Cannot read property '_id' of undefined
6. Rooms no longer load properly

Renaming the room leaves the old room name in RoomManager openedRooms cache.  On tracker invalidation, openedRooms are retrieved but invalid room returns undefined.

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/pull/570
