### ISSUE TITLE
Scrolling lags

### ISSUE THREAD

**Issue by dopykuh** [RocketChat/Rocket.Chat#5470]
Your Rocket.Chat version: 0.48.2

After pushing a lot of messages to any channel, this channel / window will start lagging during scroll events. Possibly this is caused by just appending messages. After reloading the window all seems fine.
Tested browsers (latest firefox and chromium)

**Comment by lucasvanhalst** [comment]
See #31

**Comment by dopykuh** [comment]
Oh ok ;)
