### ISSUE TITLE
Rest Api users.getAvatar

### ISSUE THREAD

**Issue by naguchennai** [RocketChat/Rocket.Chat#5471]
SetAvatar /api/v1/users.setAvatar working fine..
How can i GetAvatar? and setCustumField? getCustumField? and no gender filed?
i think this is all are basics in chat... right?

**Comment by graywolf336** [comment]
`users.getAvatar` will be added, however if you want to get the customFields then you will need to do a `users.info` and if you want to update their customFields then you will need to update the user and add that information.

**Comment by graywolf336** [comment]
@naguchennai What's the expected result when calling `users.getAvatar`?

**Comment by naguchennai** [comment]
Sorry we not going to use Rocket chat.. Rest api missing lot of function even register user also.. thank u.. i will back after one year .. then i will see what u added .. sorry to say this bye

**Comment by graywolf336** [comment]
@naguchennai Do you mind still answering my question? What is the expected return value that you would expect when calling `/api/v1/users.getAvatar`?

**Comment by naguchennai** [comment]
Lol .. When u use this /api/v1/users.setAvatar  we need /api/v1/users.getAvatar right?
i expect what i Set using users.setAvatar i need get return value with users.setAvatar.. or what?

**Comment by graywolf336** [comment]
So, you expect the value to not be `json` but instead be an actual image? If so, then that is avaiable via `/avatar/graywolf336` and should *not* be part of the rest api.
