### ISSUE TITLE
REST API : inconsistencies in rights management

### ISSUE THREAD

**Issue by Fab1en** [RocketChat/Rocket.Chat#5477]
Your Rocket.Chat version: 0.49.0-develop

I cannot post a message into a channel via the rest API if I'm logged-in as a user that does not have the `view-c-room` permission. The error message is "Not allowed [error-not-allowed]"
However, the same user with the same permissions can post to the same channel via the web app interface.

**Comment by graywolf336** [comment]
Will be fixed in the next version. :+1:
