### ISSUE TITLE
Support for `/msg`

### ISSUE THREAD

**Issue by martindale** [RocketChat/Rocket.Chat#5479]
It'd be extremely convenient to simply type `/msg <username>` to open the private chat with a user, and `/msg <username> <message...>` to send them a specific message.  Most chat clients support this, so to lose it when migrating to Rocket is an impediment to workflow.

**Comment by martindale** [comment]
Also noticed #5297, which appears to have a similar intent.

**Comment by ggazzo** [comment]
in version 0.54.x you can use ```/msg @user <message>``` to send a message and ```/open @user``` to open a user event if you have not started a conversation before.
