### ISSUE TITLE
Unable to delete closed Livechat

### ISSUE THREAD

**Issue by areichmann76** [RocketChat/Rocket.Chat#5481]
Your Rocket.Chat version: 0.48.2

Could not delete closed Livechats, in room list a room with empty name is displayed (also could not delete this).

**Comment by jszaszvari** [comment]
+1

**Comment by sampaiodiego** [comment]
I'll keep all discussions related to livechat deletion on this thread.

I would like to know the bast way of implementing this:

* add a delete button on livechat room list (under `Livechat > Current chats` or even `Administration > Rooms`)
* add a delete button one the "info" panel (alogin with the close button. but I can see this can got confuse)
* having a setting to delete all closed livechat rooms after a period of time

Just pinging you guys from other issues I just closed @nmolinski @localguru @adamprice56 @chainmueller

I would like have a feedback on the options listed above and also new ones =) thanks

**Comment by chainmueller** [comment]
I would love to see 2 of your implementation ideas:

- add a delete button on livechat room list under Livechat > Current chats with the possibilty of choosing multiple livechat rooms to delete
- having a setting to delete all closed livechat rooms after a period of time

thank you for your help, also for the code to delete it from mongo db! worked like a charm. you are doing a wonderfull job with rocketchat.

**Comment by ajw-dev** [comment]
I could also really benefit from having a way to delete closed Livechats. I would be happy with either of the two implementations mentioned for deleting them one at a time, either from the livechat room list under Livechat > Current chats, or on the "info" panel. The setting to delete all closed livechat rooms after a period of time would be nice, but not as essential as the other. Deleting all chats isn't likely to be my preferred method since there may be reasons you hang on to a chat or two for a time.

**Comment by GetGeeks** [comment]
So this is still a manual db action until when ?

**Comment by sampaiodiego** [comment]
You guys can already delete livechats from the admin panel (Rooms page).

But there is no "right" way for filtering livechats. But searching for "guest" room name, make the trick.

**Comment by GetGeeks** [comment]
I am having trouble finding any livechat(s) in administration > rooms any suggestions I have loads of cluttering test livechats with no clear delete methods I would love to know what I might do to flush these records out. As of what version do livechats appear in rooms? Im am using 0.61.0 and they do not show for me.

**Comment by sampaiodiego** [comment]
@GetGeeks I'm sorry but you're right, you can't filter for livechat rooms there. I thought you could, but I was wrong

**Comment by kevmasonk1** [comment]
Any update on this? Also how do I perform manually struggling to locate the DB

**Comment by renatobecker** [comment]
@kevmasonk1, please take a look at this PR: #10301.

**Comment by kevmasonk1** [comment]
I dont see this maybe on an outdayed version? 0.39.0

**Comment by Leen15** [comment]
news @renatobecker? we have version 0.65.1 but we are still not able to delete closed chats.

**Comment by Leen15** [comment]
@sampaiodiego any eta here?

**Comment by renatobecker** [comment]
Hi @Leen15. As you can see here -> #10301, the review process is complete and it will be released in 0.66.
Thanks.

**Comment by Leen15** [comment]
Great thanks!
