### ISSUE TITLE
Enable SSH or PGP key login

### ISSUE THREAD

**Issue by saram-kon** [RocketChat/Rocket.Chat#5484]
Your Rocket.Chat version: 49.0 develop

This is a feature request. To make the user authentication more secure and at the same time ease the login process, it would be nice, if it would be possible to login with an SSH or PGP key, where a public key is stored on the server. While it is probably not possible to implement this in the browser versions, it should be implementable with the client applications. This could also give the administrators the option to disable password login completely and force the users to login with a client app, to ensure the key login.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I know of no such web standard that implements this and could be leveraged. In my understanding though, this would be needed. Also I don't really see the benefit of only having this in non-browser clients.

I will close this issue. If you feel you still want this, please do provide some ideas on how to implement this :) I'll happily reopen then...

Cheers
Thomas
