### ISSUE TITLE
Channel argument or description?

### ISSUE THREAD

**Issue by Mte90** [RocketChat/Rocket.Chat#5485]
Your Rocket.Chat version: 0.48
I see that there are this 2  value in every channel but only argument get written on the top of the chan itself.
So what is the purpose of description? Before understand the difference (the fact of the top) i mixed and now I am changing all the text in all the channel.
Maybe a label about the behaviour of both the field will be useful.

**Comment by MartinSchoeler** [comment]
Closing this issue due lack of activity

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
