### ISSUE TITLE
LDAP config example?

### ISSUE THREAD

**Issue by xxedgexx** [RocketChat/Rocket.Chat#549]
Yes, so I have the latest version built and I actually see the Administration option now and the ability to configure LDAP, but there isn't very much information, such as what is the format of the LDAP URL? I'm trying ldaps://10.0.0.1/ for example. I'm not sure exactly what is expected of the LDAP DN? I'm trying to authenticate against a FreeIPA LDAP server. Is there a way to set the Login attribute? Maybe just an example of a working connection would help.

**Comment by marceloschmidt** [comment]
We are not very familiar with LDAP either. We have done this as per user request and it was sufficient for their uses. Check out this link: https://github.com/RocketChat/Rocket.Chat/wiki/LDAP-Authentication
If you need anything else, let us know.

**Comment by drcursor** [comment]
@xxedgexx  where you able to get it working ? I'm still trying to figure out what format is expected for each one of the options.

**Comment by drcursor** [comment]
OK...after taking a look at the code its actually quite easy to get it working:
 LDAP_Dn = uid=#{username},cn=users,dc=whatever

the key part here is #{username} which is replaced by whatever the user inputs as his username.

LDAP_Url - the usual kind of url ldap://yourserver
LDAP_port - self explanatory

LDAP_Bind_Search - leave blank (if you need prebinding take a look at https://github.com/RocketChat/Rocket.Chat/tree/master/packages/rocketchat-ldap to have an idea how its working - didn't try it as I didn't need it.)
