### ISSUE TITLE
User password change fails (by admin) and triggers rate-limiter message

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#5491]
Your Rocket.Chat version: 0.49-develop

Also happens on 0.48.2

To reproduce:

As an admin, select an existing user, choose EDIT,  change her/his password.  

The password change fails and a "toast" from rate-limiter popsup, warning of too many calls made in too  short a time.

**Comment by engelgabriel** [comment]
@MartinSchoeler can you please test if this is still happening?

**Comment by MartinSchoeler** [comment]
@Sing-Li @engelgabriel Tested on latest develop and it worked fine, when you first change the password, its successful. And after that you have to wait 60 seconds to change it again.
