### ISSUE TITLE
REST API for direct messages

### ISSUE THREAD

**Issue by bnornholm** [RocketChat/Rocket.Chat#5492]
Your Rocket.Chat version: 0.48.2

Is there a way to have an API call for all direct messages for the server that will show the direct messages (to:from) and the content of those messages?

**Comment by graywolf336** [comment]
There is `GET /api/v1/im.list.everyone` currently to get the list of all the direct message rooms. As far as getting the messages from those rooms, that is not a feature and is a security concern that I'm concerned about since it is direct messages between users.

**Comment by bnornholm** [comment]
We are looking to roll this out in a corporate setting in a healthcare workplace.  Because of this, we need to be able to monitor all conversations between users to ensure no mishandling of HIPPA information, and need to be able to pull up conversations at will.

I do agree with you that it is a security concern.  Making this feature only available to admins would help lock it down.

**Comment by graywolf336** [comment]
Hmm not only that, but also a setting that has to be enabled which allows
that. Also the setting would not be enabled by default and maybe a warning
about user privacy. 👍 I'll see about getting this added today.

**Comment by bnornholm** [comment]
Thank you!

**Comment by graywolf336** [comment]
@bnornholm And pull request #5691 adds this functionality. The setting is under `Admin -> General -> REST API -> Enable Direct Message History Endpoint` and the permission required to call that is `view-room-administration`

**Comment by gabrielew** [comment]
> @bnornholm And pull request #5691 adds this functionality. The setting is under `Admin -> General -> REST API -> Enable Direct Message History Endpoint` and the permission required to call that is `view-room-administration`

Hey, this helps me a lot, thanks!
