### ISSUE TITLE
Disable link preview when message is send by a bot

### ISSUE THREAD

**Issue by maethor** [RocketChat/Rocket.Chat#5495]
Your Rocket.Chat version: 0.48.2

Hi,

Is there an equivalent to the Slack attributes `unfurl_link` and `unfurl_media`? On slack, `unfurl_link` is False by default, so when a bot post a link, Slack doesn't try to display a preview.

Or is there any way to simply post a link with a bot without having Rocket Chat displaying a preview?

Thanks

**Comment by maethor** [comment]
By the way, if anyone is looking for a way to disable preview on a message send by a bot, I found a (quite ugly) workaround. Previews are auto-attachments. So if you put an attachment, or even if you force `"attachments": [{}]`, preview will not show up.

But I think it would really be better to add `unfurl_link` and `unfurl_media` variables :smile:

**Comment by MartinSchoeler** [comment]
@maethor have you tried to add the bot username in Disable Embed for Users setting in administration->Message?
![screenshot from 2017-01-11 12-54-24](https://cloud.githubusercontent.com/assets/20868078/21853159/1c9a0702-d7fd-11e6-9c8d-dbe097b9d321.png)

**Comment by maethor** [comment]
I didn't. I prefer a way that don't completely forbid it (because the same bot is used by hubot to display pictures).

But you are right, it is always possible to make two bot account, one allowed to embed preview, and another who is not. With that said, I  still prefer my "attachments" :)

If you don't think it would be usefull to implement `unfurl_media` and `unfurl_links`, you can close this issue. I least someone looking for it will find two workarounds :smile:

**Comment by bviktor** [comment]
@MartinSchoeler where can I find this option exactly? I'm trying to disable previews for messages sent by the RSS app, but to no luck so far.

**Comment by bviktor** [comment]
Oh nevermind, google failed on me :D

**Comment by tazotodua** [comment]
Seems it's available now by  `disable_web_page_preview` parameter:

https://core.telegram.org/bots/api#editmessagetext

**Comment by sourabhsinha396** [comment]
As, told by ttodua ,you need to pass, `disable_web_page_preview=True` argument

**Comment by ouoertheo** [comment]
> Seems it's available now by `disable_web_page_preview` parameter:
> 
> https://core.telegram.org/bots/api#editmessagetext

I'm ridiculously confused. Is rocket.chat using telegram's core spec?

**Comment by calebjacobson** [comment]
Payload documentation should be updated [here](https://github.com/RocketChat/developer-docs/blob/master/reference/api/rest-api/endpoints/core-endpoints/chat-endpoints/postmessage.md) to include `disable_web_page_preview=true` option.
