### ISSUE TITLE
Some download links are broken on the website

### ISSUE THREAD

**Issue by SplittyDev** [RocketChat/Rocket.Chat#5498]
Downloads links for Windows and Linux are broken: https://rocket.chat/download
Not sure if this belongs here, I couldn't find a repository for the website.

**Comment by MartinSchoeler** [comment]
@SplittyDev for me they are working fine, is this still happening to you?

**Comment by MartinSchoeler** [comment]
@SplittyDev sorry I was looking at the wrong links, you are right they are broken.

**Comment by engelgabriel** [comment]
Fixed
