### ISSUE TITLE
Login with LDAP via Iframe

### ISSUE THREAD

**Issue by tomasz-nowak** [RocketChat/Rocket.Chat#5499]
Hi,
I have a Rocket.Chat instance on my server with standalone LDAP server. Iframe.contentWindow.PostMessage with login-with-token event works great for logging users, but only for those previously logged in with Meteor.loginWithLDAP method. Is there a way to login users with LDAP via Iframe (or API) ? Or just run Meteor.loginWithLDAP from iframe parent window?

**Comment by tpayen** [comment]
Hi,
Same problem here, API actually doesn't use LDAP auth

**Comment by sebudot** [comment]
Hi, 
Would be usefull for API to use LDAP auth
