### ISSUE TITLE
Feature request: Webinar delivery

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#5500]
Customize / enhance current Video Chat panel (Jitsi) for broadcast webinar.
Allowing participants to continue text chat concurrently with video broadcast.

Perhaps:
*  moderated chat stream (channel)
*  announcement of ongoing event (as toasts?) 
*  ability to "go away" and return quickly 
*  functional on mobile  (requires careful design but big differentiator)
*  membership / attendee management and control

Will be useful for hosting events on our community server; as well as future training ops.

**Comment by louisemessage** [comment]
Nice suggestions but closing for now due to a lack of activity on this issue.
