### ISSUE TITLE
Register gcm token at rocket.chat

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5503]
I have a custom mobile android app I want to register gcm token on my rocket.chat server How I can do that Is there any restful api to add/update tokens

**Comment by sampaiodiego** [comment]
You have to send the following DDP messages:

- on connect, call method `raix:push-update` - data:
```
{
	'0': {
		id: '[RANDOM_ID]',
		token: {
			gcm: '[GCM_APP_TOKEN]'
		},
		appName: 'main',
		userId: null,
		metadata: {}
	}
}
```

- on user login, call method `raix:push-setuser` - data:
```
{
	'0': '[SAME_ID_AS_ON_CONNECT]'
}
```

**Comment by engelgabriel** [comment]
Did it work @hussamEddinAlhendi ?

**Comment by hussamEddinAlhendi** [comment]
We are working on other tasks, I will inform you if it is work or not.

**Comment by andreaazzara** [comment]
Hi! I have the same issue, I managed to connect and login via websockets to the rocket chat server using this message format:

```
{
                    "msg": "method",
                    "id": randomId,
                    "method": methodName,
                    "params": []
                }
```

@engelgabriel What is the exact format for GCM and APNS token registration?
thanks

**Comment by imrealashu** [comment]
@hussamEddinAlhendi were you able to make it work ?

**Comment by imrealashu** [comment]
Hey @sampaiodiego 
I'm sending this data using websocket...
```json
{
  "msg": "method",
  "method": "raix:push-update",
  "params": [
    {
      "id": "bq6G5kApbi7bmyyFM",
      "token": {"gcm": "token"},
      "appName": "main",
      "userId": null,
      "metadata": []    
    }
  ]
}
```

I'm getting "Malformed method invocation" error

**Comment by geekgonecrazy** [comment]
Please feel free to reach out via our [forum](https://forums.rocket.chat) or our [community server](https://open.rocket.chat) to discuss.

Going to go ahead and due to non response by author.
