### ISSUE TITLE
Feature: Static HTML Pages

### ISSUE THREAD

**Issue by Kiran-Rao** [RocketChat/Rocket.Chat#5506]
For my project, I need to build in Rooms containing containing static html (editable by admins). They need the same functionality as regular channels (add/remove users, sidenav, etc). 

1. Would this feature be useful to RocketChat?
1. What is the best way to implement this?

I've looked at how livechat is implemented and I like the approach of keeping everything in a self-contained module.  

Any suggestions will be helpful. Cheers,  
Kiran

**Comment by engelgabriel** [comment]
That can be interesting.. can you describe the use case better so we can suggest the best approach?

**Comment by Kiran-Rao** [comment]
@engelgabriel 
We're designing a learning platform with RocketChat as the base. 

A requirement is having instructional content accessible to students (videos, text, links, etc.). We also need the ability to create/delete pages and invite/kick people from these pages. Currently, we're using read-only channels, but they are fairly ugly and unintuitive for our purposes.  

We need a separate sidebar containing only those pages:
![screen shot 2017-01-15 at 5 19 12 pm](https://cloud.githubusercontent.com/assets/920422/21966726/dda09d3e-db46-11e6-8e6c-e61e6dab8e42.png)

We also need pages that admins/mods can edit. 
![screen shot 2017-01-15 at 5 25 45 pm](https://cloud.githubusercontent.com/assets/920422/21966764/b3e8d64a-db47-11e6-92f5-848678280e69.png)

This feels similar in nature to the home/terms and conditions/privacy policy page. However, it will be a more generic solution with many of the features for rooms.

**Comment by mixrat** [comment]
Another use case...

I am setting up a community project page. Users have different channels where they can discuss  the different aspects of the overall project. However, I need static pages where the progress and results of the efforts of those sub-projects can be posted. Trying to bunch everything into the home page doesn't work. Also, using a channel to post the information kills any formatting that would help organize the data, and clutters the channels list.

**Comment by sampaiodiego** [comment]
With the upcoming release of our Rocket.Chat Apps framework.  I think this is more fitting as a Rocket.Chat App.  

Please feel free to post your Rocket.Chat App idea to our [forum](https://forums.rocket.chat) so maybe someone (even you) can create it.

**Comment by SteveUNSW** [comment]
Any updates from this?

**Comment by reetp** [comment]
@SteveUNSW 
As per Diegos comment please follow up in the forums
