### ISSUE TITLE
Security Vulnerability: Allow Password Change admin setting doesn't work

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#5507]
Your Rocket.Chat version: 0.48.2

Setting the administration setting "Allow Password Change" to false under Administration -> Accounts does not prevent users from resetting their password under My Account -> Profile -> New Password.  The only effect of setting "Allow Password Change" to false appears to adding a comment to the text field element:

<input type="password" name="password" id="password" title="Your Rocket.Chat administrator has disabled the changing of passwords”>

but the user is able to enter and save a new password without an error being raised (and the new password is written to the DB).  The restrictions on other fields in the Profile (i.e. Username and Email) do appear to function (i.e. raise an error when an attempt to save new values is made).

**Comment by graywolf336** [comment]
@howellsd What browser are you using? As with Chrome, I'm not able to even click in the new password field.

**Comment by howellsd** [comment]
I’m using Chrome 55.0.2883.95 (64-bit) and testing with RocketChat 0.48.2.  I can definitely click in the password field, modify it and save it.

[cid:411B1F46-0F55-40F3-A243-3A916B098E64@udev.six3]

[cid:B2A33904-0448-4E21-8336-8C36D3871720@udev.six3]


On Jan 18, 2017, at 1:12 PM, Bradley Hilton <notifications@github.com<mailto:notifications@github.com>> wrote:


@howellsd<https://github.com/howellsd> What browser are you using? As with Chrome, I'm not able to even click in the new password field.

**Comment by graywolf336** [comment]
![image](https://cloud.githubusercontent.com/assets/850391/22082000/14842362-ddad-11e6-9a97-95522db2c8ed.png)
That will now be shown and the server won't allow it as well when #5655 is merged.
