### ISSUE TITLE
Login page has no input elements after enabling oath

### ISSUE THREAD

**Issue by jakimfett** [RocketChat/Rocket.Chat#5508]
Rocket.Chat version: 0.48.2

After setting up Google OAth (following the instructions [here](https://rocket.chat/docs/administrator-guides/authentication/oauth#setup-1)), I can't log in to my rocketchat instance (no username/password prompt is available):
![image](https://cloud.githubusercontent.com/assets/2565176/21871722/e446fbf0-d818-11e6-8cd1-34429432cbe6.png)

See https://chat.redthread.tech for the actual site.

I'd like _either_ a way to log in that always allows an admin to log in, or a way to set a "safe mode" which disables all plugins, or some other mechanic that avoids locking everyone out of a rocket.chat instance.

**Comment by Perksls** [comment]
i think you can login, in the console paste 

Meteor.loginWithPassword('your-admin-username', 'your-password');

**Comment by jakimfett** [comment]
Thanks, that got me in.

**Comment by chatnl** [comment]
Thanks that saved my day. I had the same problem!

**Comment by ramonjoaquim** [comment]
> i think you can login, in the browser console paste
> 
> Meteor.loginWithPassword('your-admin-username', 'your-password');
> 
> And then try to fix the oauth error you have

Thanks bro!
