### ISSUE TITLE
OAuth fails with "redirect_uri_mismatch" error

### ISSUE THREAD

**Issue by jakimfett** [RocketChat/Rocket.Chat#5511]
Rocket.Chat version: 0.49.0

After configuring OAuth in admin/OAuth, I can see the "Google Login" button, but attempting to log in using the Google OAuth method results in the following application error:

<pre>
{"line":"428","file":"oauth.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Google. failed [400] {   \"error\" : \"redirect_uri_mismatch\" }","time":{"$date":1484184078162},"level":"warn"}
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Google. failed [400] {   "error" : "redirect_uri_mismatch" }
  at getTokens (packages/google.js:83:20)
  at Object.handleOauthRequest (packages/google.js:34:18)
  at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
  at middleware (packages/oauth.js:203:5)
  at packages/oauth.js:176:5
</pre>

I've double verified that my ID, Secret, and Callback URL are correct, and I've put the Callback URL into the Google API Authorized redirect URIs for my application.

**Comment by rodrigok** [comment]
@jakimfett Can you paste here the url of the opened popup for login? And your `Site Url` setting?

**Comment by geekgonecrazy** [comment]
@rodrigok just a heads up

Looks like we have two seperate issues going on.  Both related to oauth.  #5516 / #5519 that were referred here both have a `Exception while invoking method 'login'`.  

This one seems to be related just to the redirect URI.   

Going to keep #5536 open to track this second issue and refer the other two there.

**Comment by engelgabriel** [comment]
@jakimfett can you confirm if the problem was solved on version `0.49.2`?

**Comment by jakimfett** [comment]
@engelgabriel my rocketchat instance is currently broken, but I'll update you as soon as I get my server back online.

**Comment by jakimfett** [comment]
@engelgabriel the update to 0.49.2 fixed it! Thank you!
