### ISSUE TITLE
Uploaded file renaming - keyboard overlaps fields on mobile

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5513]
Your Rocket.Chat version: 0.49.0

Hey Guys,

thanks for implementing this feature! But i get a very annoying issue on mobile with this.

If i try to upload a picture from my iPhone all seems fine:

![2017-01-12 07-47-44 3768](https://cloud.githubusercontent.com/assets/5877910/21880053/246a257a-d89d-11e6-9c84-418d657c979d.png)

Until I try to rename the file upload.. then the keyboard overlaps the fields and its almost unusable.

![2017-01-12 07-47-48 3769](https://cloud.githubusercontent.com/assets/5877910/21880073/3999694c-d89d-11e6-99c8-bd02737d418d.png)

How did you test this mobile app features? (Use the developers another than the cordova one? 😆)

Can you please improve the ui? This prevents me to do the upgrade.

**Comment by karlprieb** [comment]
We already fixed that with our new modal.
