### ISSUE TITLE
Resizing of the app after image upload not correct

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5514]
Your Rocket.Chat version: 0.49.0

The cordova app not resizing properly with the size of my phone, you can see this in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/5877910/21880283/6a6f6188-d89e-11e6-88eb-645bfe784606.png)

In the red square the UI is not properly aligned.

You can reproduce this if you make a picture and upload it, after taking the picture and the upload screen is shown, the size is not aligned correctly anymore.

**Comment by TheReal1604** [comment]
@laggedHero @engelgabriel This is also happening on 0.52.0.

**Comment by engelgabriel** [comment]
@karlprieb can you please take a look at this?

**Comment by karlprieb** [comment]
@engelgabriel sure

**Comment by RichardFoxworthy** [comment]
any updates on this one? Makes the image upload function unusable on iOS

**Comment by TheReal1604** [comment]
@RichardFoxworthy Karl told me that this is a bug in a cordova plugin (statusbar I think.) So this maybe could be difficult to fix.

**Comment by RichardFoxworthy** [comment]
@TheReal1604 @karlprieb is there a Cordova bug logged for this? Makes Rocket.chat Cordova iOS unusable for our usecase. Its a big deal for us

**Comment by MartinSchoeler** [comment]
#7750 Might fix that

**Comment by karlprieb** [comment]
Seems that we already fixed that. I can't reproduce that anymore on my phone.

@TheReal1604 @RichardFoxworthy can you guys test again?

**Comment by TheReal1604** [comment]
Closing this.
