### ISSUE TITLE
Problems occur when refreshing the Internet browser.

### ISSUE THREAD

**Issue by ktt9117** [RocketChat/Rocket.Chat#5517]
Your Rocket.Chat version: 0.48.2

I created a VM on the Azure Cloud and manually installed the last release version of Rocket.Chat.

I tried two different browsers (Chrome, Safari) on one computer and logged in as a different user and it worked fine. 

However, if one of the browsers is refreshed and re-tested, there is a problem that the message can not be sent or received in real time.

**Comment by engelgabriel** [comment]
Can you give as a link to your test environment?

**Comment by ktt9117** [comment]
@engelgabriel Sorry for the delay

You can test here : http://mobilechatweb1.japanwest.cloudapp.azure.com:3000
if you need administrator, use it : admin / admin

I started the main.js using pm2.

**Comment by ktt9117** [comment]
@engelgabriel The problem has not coming up at the moment. If the problem happens again, I'll report it. Thanks for your help.

**Comment by engelgabriel** [comment]
thanks for the update @ktt9117
