### ISSUE TITLE
Arabic group names support 

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5518]
Is there a way to name group in arabic letters not just english

**Comment by Nemra1** [comment]
[0-9a-zA-Z-_.-ي-ا]+
![2017-01-13_064018](https://cloud.githubusercontent.com/assets/22897987/21918578/55648846-d95b-11e6-8c48-7440c5e047c7.png)

**Comment by engelgabriel** [comment]
Maybe we should add some more indo on the description

**Comment by MartinSchoeler** [comment]
You can use either @Nemra1 solution or this one https://github.com/RocketChat/Rocket.Chat/issues/4820#issuecomment-269453939
