### ISSUE TITLE
clustering Rocket.Chat

### ISSUE THREAD

**Issue by galrotem1993** [RocketChat/Rocket.Chat#5520]
Your Rocket.Chat version: 0.49.0

Hi, 
how should i install Rocket.Chat across multiple servers?

thanks

**Comment by juanwolf** [comment]
Hi,

Please have a look at @TheReal1604 tutorial:
https://github.com/RocketChat/Rocket.Chat.Docs/issues/87

**Comment by engelgabriel** [comment]
We will turn that into a howto in our doc.

**Comment by galrotem1993** [comment]
i didn't unerstand how to do that
i am running the app (after i run 'meteor build') on ubuntu 14.04 with the following commang with upstart:
    export MONGO_URL=mongodb://ip
    export ROOT_URL=https://myApp
    export PORT=3000
    exec node Rocket.Chat/main.js

thanks for helping

**Comment by raymondfeliz** [comment]
Heres a copy of my service for my rocketchat for clustering.  I have 3 copies of this service, one on port 3000, then 3001, then 3002 all pointing at a mongo cluster. Hopefully this helps some. Assuming you have the mongo cluster. this is assuming you have a cluster on the localhost, and the cluster is called rs0

[Unit]
Description=Rocket.Chat Server
After=syslog.target
After=network.target

[Service]
Type=simple
Restart=always
StandardOutput=syslog
SyslogIdentifier=RocketChat
User=root
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs0
Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaset=rs0
Environment=ROOT_URL=http://rocketchat
Environment=PORT=3000
WorkingDirectory=/opt/Rocket.Chat
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
LimitNOFILE=1024000

[Install]
WantedBy=multi-user.target
