### ISSUE TITLE
Gmail and any other mail system calender sync up with rocket chat.

### ISSUE THREAD

**Issue by spathare21** [RocketChat/Rocket.Chat#5523]
Your Rocket.Chat version: (make sure you are running the latest)

As we have an option to login with gmail/configure rocket chat to allow login using gmail credentials.
can we integrate/sync up our gmail calendar with  rocket chat. so that whenever we have a meeting our rocket chat profile status automatically will change to "In Meeting", also if meeting ends/canceled it should have to change to "Online".

**Comment by geekgonecrazy** [comment]
With the upcoming release of our Rocket.Chat Apps framework.  I think this is more fitting as a Rocket.Chat App.

Please feel free to post your Rocket.Chat App idea to our [forum](https://forums.rocket.chat) so maybe someone(even you) can create it.
