### ISSUE TITLE
Windows Desktop App - Launch app on login feature

### ISSUE THREAD

**Issue by ST-KW** [RocketChat/Rocket.Chat#5525]
Rocket.Chat version: 2.2.0

As a Windows user, I want a "Launch app on login" option so that Rocket.Chat is always online / available and I can't overpass messages.

**Comment by bgomelsky** [comment]
This can be implemented using [auto-launch](https://www.npmjs.com/package/auto-launch ) package.

**Comment by engelgabriel** [comment]
I'll close this issue here and refer the new isso on the desktop app project.

https://github.com/RocketChat/Rocket.Chat.Electron/issues/292
