### ISSUE TITLE
Feature - personal notepad

### ISSUE THREAD

**Issue by AufGehts** [RocketChat/Rocket.Chat#5527]
A useful extension in the section "private messages" would be the possibility for an user to create a private message at himself.
The user could use this as a personal notepad to save important informations within the system. Therein a user could save quick notes or to-do lists, which can be updated or deleted by the edit-function. The content of the own private messages would simply be searchable and always-accessible by the user.

**Comment by lucasvanhalst** [comment]
You can already do this, just start a conversation with rocket.cat.

**Comment by engelgabriel** [comment]
Indeed @lucasvanhalst but it would be good to be able to start a conversation with oneself, for Slack import compatibility :)

**Comment by geekgonecrazy** [comment]
Its possible now to start a conversation with your self.

This would also make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
