### ISSUE TITLE
Mark pinned messages button if messages exist

### ISSUE THREAD

**Issue by ksb4ever** [RocketChat/Rocket.Chat#5528]
Your Rocket.Chat version: 1.3.1 (15)
Mark pinned messages button in chat, if at least one pinned message exists.

**Comment by rekeds** [comment]
+1,
this could be great, to notify the user of changes in pinned messages "tab", without opening the side menu.

a red color pin if somethings new/unread :>

**Comment by beeing** [comment]
+1 - Yes, also applies to starred messages too.
