### ISSUE TITLE
RC rendered unusable - browser errors after upgrade from 48.2 to 49.0/50-develop

### ISSUE THREAD

**Issue by corecache** [RocketChat/Rocket.Chat#5529]
Your Rocket.Chat version: 49.0 / 50-develop (8e15592f64bddc70336f6a1d87263410d044f7bc)

No errors or warnings in the server log - enabled "Log_Level" in Settings documents by setting its value to 2 - it is already fully showing whats going on - seems like everything is fine server-side.

I've checked my browser console and it shows a few errors:

![rc49](https://cloud.githubusercontent.com/assets/736666/21895192/0f4a6444-d8e2-11e6-8a80-f218d8902a26.png)

**Comment by engelgabriel** [comment]
I guess you are running the Rocket.Chat via the `meteor` command, right?

You need to do a `meteor npm i` before running `meteor` or even before `meteor build`.

Please reopen if the problem persist.
