### ISSUE TITLE
Missing Direct messages in Admin Room list

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#5538]
Your Rocket.Chat version: 0.49.0

If you goto Admin-> Rooms and click direct messages.  There are none.  It doesn't seem they have disappeared... but they are not discoverable here. 

New ones after the upgrade to 0.49.0 are showing there.  But their names are gone.

![image](https://cloud.githubusercontent.com/assets/51996/21916977/c87663ce-d909-11e6-9f57-8971e2aff5e4.png)

Assuming related to loki cache.

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/f2978b37ba09986f6552595b6ad5346275d359b1
