### ISSUE TITLE
Edit channel settings impossible (when admin)

### ISSUE THREAD

**Issue by steven-tib** [RocketChat/Rocket.Chat#5539]
Your Rocket.Chat version: (0.49)

It's not possible to edit channel settings anymore, the "pencil" button is not showing.
see picture below:

![image](https://cloud.githubusercontent.com/assets/18457235/21912542/ef51d858-d926-11e6-890e-a21df077476d.png)

**Comment by karlprieb** [comment]
We fixed this bug here #5395 

![image](https://cloud.githubusercontent.com/assets/9200155/21918058/1b2a6258-d934-11e6-818d-8a40af9dbd3d.png)

Its working in develop branch.
Can you build develop branch and test?

Thanks!

**Comment by MartinSchoeler** [comment]
@steven-tib is this still a issue in the latest release?

**Comment by steven-tib** [comment]
Nope not an issue anymore, all good ! thanks for the fix
