### ISSUE TITLE
wrong translation (French) - accounts settings

### ISSUE THREAD

**Issue by steven-tib** [RocketChat/Rocket.Chat#5540]
Your Rocket.Chat version: (0.49)

Wrong translation in the accounts settings:  "do not remember session..." --> 

![image](https://cloud.githubusercontent.com/assets/18457235/21912666/aa5a62fa-d927-11e6-8444-a66271723759.png)

should be : 
"**Ne pas se souvenir de la *session* utilisateur lors de la fermeture de la fenêtre**"

Cheers

**Comment by engelgabriel** [comment]
@steven-tib do you want to join our translation team? We use Lingohub.com

**Comment by steven-tib** [comment]
Sure if I can help!
I've just created an account with this same username (steven-tib) waiting for your invite.

**Comment by engelgabriel** [comment]
I think I need you  email

![image](https://cloud.githubusercontent.com/assets/1000217/21932905/0c32de64-d98a-11e6-80c0-107bc2e4ae6b.png)

**Comment by engelgabriel** [comment]
Invitation sent :) Please fix the translation there.

**Comment by steven-tib** [comment]
thanks, I will do that now.
