### ISSUE TITLE
Favicon lost after update to 0.49.0

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#5544]
Your Rocket.Chat version: 0.49.0

Guessing this is a migration issue?

**Comment by karlprieb** [comment]
@geekgonecrazy Which favicon? We have a lot of options in the admin. Thanks!

**Comment by IQ2022** [comment]
assuming any, it was fine in all previous upgrades that i have done, this last one did something different.. this is what i have now..

![image](https://cloud.githubusercontent.com/assets/12454319/21917599/f1975436-d916-11e6-9722-f12c28062c01.png)

i will be happy if you guide me somewhere to create better looking favicon :)

**Comment by karlprieb** [comment]
Hey @IQ2022 thanks for your feedback 😄  👍 

We removed several favicon sizes (precisely 64x64, 96x96, 128x128 and 256x256) and we added another sizes and iOS/Android specific images.

So your Assets page should have these options:
- logo (svg, png, jpg)
- favicon (ico)
- favicon (svg)
- favicon 16x16 (png)
- favicon 32x32 (png)
- android-chrome 192x192 (png)
- android-chrome 512x512 (png)
- apple-touch-icon 180x180 (png)
- apple-touch-icon-precomposed 180x180 (png)
- mstile 144x144 (png)
- mstile 150x150 (png)
- mstile 310x310 (png)
- mstile 310x150 (png)
- safari pinneed tab (svg)

Which options do you have?

**Comment by geekgonecrazy** [comment]
@karlprieb I'm not sure which is shown in the tab in chrome.  But for example https://rocket.ubuntu.com had their favicon and then when snap auto updated it reverted to the Rocket.Chat favicon

**Comment by karlprieb** [comment]
@geekgonecrazy I know.
After upgrade you will need to upload 16x16 and 32x32 favicons.
Now ico favicon is used as fallback to png.

**Comment by geekgonecrazy** [comment]
@karlprieb OK cool!  I'll go ahead and close this since this is expected. 👍

**Comment by karlprieb** [comment]
@geekgonecrazy Thanks! Maybe we just need to make this information more explicit in 0.49.0 changelog.

**Comment by IQ2022** [comment]
okay thanks, any app u recommend to create favicon?

**Comment by IQ2022** [comment]
wait they are all PNG so what is the issue?

**Comment by karlprieb** [comment]
No, they are PNG, SVG and ICO.

I believe that [realfavicongenerator](https://realfavicongenerator.net/) is one of the best favicon generators.

**Comment by IQ2022** [comment]
thank you,.. yes thats a great one :)...

however it seems not workign still i loaded the ones you suggested - not all of them.. which one for the chrome browser?

![image](https://cloud.githubusercontent.com/assets/12454319/21918625/2c4594e4-d921-11e6-92cf-6efa7fedf3dd.png)

**Comment by karlprieb** [comment]
Which favicon is chrome loading?

Chrome should load 16x16 or 32x32 png.

Can you open chrome devtools in network tab, reload and search for favicon and post the results?
Like this:
![image](https://cloud.githubusercontent.com/assets/9200155/21918739/b80c3a54-d93b-11e6-9a34-b08593e7ea8c.png)

**Comment by IQ2022** [comment]
![image](https://cloud.githubusercontent.com/assets/12454319/21918818/4894b6dc-d923-11e6-97ee-fb8c64d06bf9.png)

**Comment by karlprieb** [comment]
Ok, can you do a force reload (ctrl + F5 or cmd + shift + R). It can be a cache problem.

**Comment by IQ2022** [comment]
same thing nothing happened

**Comment by karlprieb** [comment]
We tried to clear the server and browser cache and didn't work, so I will reopen this issue to keep tracking of it.

**Comment by arty-name** [comment]
Should I open a separate issue for "Firefox shows low-res favicon despite SVG being provided"?

**Comment by engelgabriel** [comment]
@arty-name I think it is related, so post the info here.

**Comment by arty-name** [comment]
Even when logged out, Firefox on a HiDPI system does not request svg and instead requests `favicon-16x16.png`, while HTML contains following:

```html
<link rel="icon" sizes="any" type="image/svg+xml" href="assets/favicon.svg?v=3" />
<link rel="icon" sizes="32x32" type="image/png" href="/images/logo/favicon-32x32.png?v=3" />
<link rel="icon" sizes="16x16" type="image/png" href="/images/logo/favicon-16x16.png?v=3" />

**Comment by engelgabriel** [comment]
@IQ2022 @arty-name can you please try the develop branch?

**Comment by arty-name** [comment]
I can’t unfortunately, I am not an administrator of the server.

**Comment by thepkaew** [comment]
![image](https://user-images.githubusercontent.com/45059090/49143335-61853d80-f32d-11e8-8f50-9ae643e9d90b.png)

Why up load file ? logo 70x70 png
