### ISSUE TITLE
unable to log in via mobile

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5545]
okay this is probably related to SSO, as am not able to login with google/facebook .. 
issue:
using RC IOS app to login to my server (which was previously logged in),  click update to new version - > new files get updated> then it try to login to rooms - nothing happen but the 3 dots of waiting ...
unable to use double finger swap to change server ..

i am still getting phone notifications.. - which means am still logged in :) 

logged out of all devices.. phone still give me loading screen.... 
fyi IPAD NO ISSUE..

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by KervyN** [comment]
I can confirm this issue.
iPhone SE 
iOS 10.2

**Comment by Jannibal** [comment]
I can confirm the issue, as well as the fix @KervyN suggested. Worked for both Android and iOS

**Comment by engelgabriel** [comment]
It is fixed on the after version 0.49.2
