### ISSUE TITLE
Missing Direct Messages in Admin Livechat Manager

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5547]
Rocket.Chat version: (0.49.0)
Missing direct messages in admin livechat manager when selecting the `Current Chats` menu then selecting one of message in the lists.
<img src="https://i.imgsafe.org/849baaadc2.png" alt="Mountain View" style="width:304px;height:228px;">

**Comment by sampaiodiego** [comment]
I'm unable to reproduce it.

@zorenleo can you provide us more details?

- can you send a print with the URL included?
- what are the user's roles? is he admin or just a livechat manager?
- is there any errors on the browser console?

**Comment by exceed73** [comment]
Same problem here, no problem with the functionnality before 0.49:

- url type is : https://chat.domain.tld/live/25
- Some of them (I found 1 old discussion) are OK, but most are not.
- User is admin and livechat manager (tried to remove and  add role, same issue)
- Another user with same credentials (admin rocket + livechat) has no problem
- No error in console

I tried 
- to modify root url in config (with or without / at end, mine has)
- Restart server & mongodb
but same issue.

**Comment by exceed73** [comment]
Precision: it seems to be an ACL problem if liveChat admin is also liveChat operator.
In my case, we are 2 livechat admin **and** operator.
I can't see chats opened by my friend, and he can't see mine.

**Comment by sampaiodiego** [comment]
thanks @exceed73 .. I'm able to reproduce it now..

the problem is you cannot see livechat rooms from another livechat agent.
