### ISSUE TITLE
selecting from tools over right some of the message

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5548]
When you click the setting wheel to edit or use one of the options, it goes over the text.

NOTE This issue only with Direct Messages, it seems to be fine in general Channel...!!!!!!!!! 
![image](https://cloud.githubusercontent.com/assets/12454319/21917921/c18cfba8-d919-11e6-86ab-e4446af793ef.png)

Your Rocket.Chat version: (49.0)

**Comment by karlprieb** [comment]
Thanks for your report @IQ2022 👍 

Im fixing this right now!

**Comment by IQ2022** [comment]
no problem ...:)
