### ISSUE TITLE
Temporarily mute bot in a room

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#555]
Allow bot to be banned temporarily in a room, by any user, while concentrating on a discussion.

Somewhat related, but not exactly, to #168.

Depends on our awareness of bots in a room -  #292.    

Need a prominent status indicator showing bots are muted, or a built-in timeout - so that vital / productive work-bots are not shut out inadvertently. 
##

**Comment by louisemessage** [comment]
Thanks for your suggestion, Sing. Closing this issue for the meantime as there hasn't been activity on it for over a year.
