### ISSUE TITLE
Unable to scroll upwards on iOS devices

### ISSUE THREAD

**Issue by KervyN** [RocketChat/Rocket.Chat#5551]
Your Rocket.Chat version: 0.49.0

We have the issue that we can not scroll upwards on iPhones (tested with iPhone SE 10.2, iPhone 7 10.2).
You need to hold the screen, scroll some pixels downwards and then you are able to scroll upwards.

**Comment by engelgabriel** [comment]
Can you test on the demo server? I think we have already fixed it. If it work on the demo server, we will include the fix on the 0.49.1 release.

**Comment by KervyN** [comment]
Looks good on the demo server.

**Comment by engelgabriel** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/5531
