### ISSUE TITLE
SSO logins broken once again with 0.49 update

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#5552]
Your Rocket.Chat version: 0.49.0

We are using SSO with our own hosted GitLab instance and once again logins are broken. It happened with 0.48.x and fixed in 0.48.2 and now again broken in 0.49.0.

Here is the access log error : 

`[34mI20170113-17:02:34.311(8) Exception while invoking method 'login' TypeError: fun is not a function   at Resultset.find (/snap/rocketchat-server/385/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2197:17)   at Resultset.findAnd (/snap/rocketchat-server/385/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1965:14)   at Resultset.find (/snap/rocketchat-server/385/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:2038:53)   at new Resultset (/snap/rocketchat-server/385/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:1462:21)   at LokiEventEmitter.Collection.findOne (/snap/rocketchat-server/385/programs/server/npm/node_modules/meteor/rocketchat_lib/node_modules/lokijs/src/lokijs.js:4232:20)   at ModelsBaseCache.findOne (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:7965:60)   at ModelsBaseCache.target.(anonymous function) [as findOne] (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:7066:30)   at ModelsBaseCache.update (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:8241:66)   at ModelsBaseCache.target.(anonymous function) [as update] (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:7066:30)   at ModelsBaseDb.<anonymous> (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:7690:14)   at emitOne (events.js:77:13)   at ModelsBaseDb.emit (events.js:169:7)   at ModelsBaseDb.update (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:8635:11)   at ModelUsers.update (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:3569:36)   at ModelUsers.setEmailVerified (/snap/rocketchat-server/385/programs/server/packages/rocketchat_lib.js:6755:17)   at AccountsServer.Accounts.updateOrCreateUserFromExternalService (/snap/rocketchat-server/385/programs/server/app/app.js:4505:31)   at [object Object].<anonymous> (packages/accounts-oauth.js:133:21)   at /snap/rocketchat-server/385/programs/server/packages/accounts-base.js:938:30   at tryLoginMethod (/snap/rocketchat-server/385/programs/server/packages/accounts-base.js:763:14)   at AccountsServer.Ap._runLoginHandlers (/snap/rocketchat-server/385/programs/server/packages/accounts-base.js:937:18)   at [object Object].methods.login (/snap/rocketchat-server/385/programs/server/packages/accounts-base.js:994:27)   at maybeAuditArgumentChecks (/snap/rocketchat-server/385/programs/server/packages/ddp-server.js:2108:12)   at /snap/rocketchat-server/385/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/385/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/385/programs/server/packages/ddp-server.js:1040:48   at Session.method (/snap/rocketchat-server/385/programs/server/packages/ddp-server.js:1018:23)   at /snap/rocketchat-server/385/programs/server/packages/ddp-server.js:880:89`

Any one else have this problem?

**Comment by rodrigok** [comment]
Duplicated of #5536
