### ISSUE TITLE
Direct-Download from Client

### ISSUE THREAD

**Issue by DalePayman** [RocketChat/Rocket.Chat#5554]
Your Rocket.Chat version: 0.46.0

First thank you for adding further of my feature-requests to rocketchat!
See:
https://github.com/RocketChat/Rocket.Chat/issues/5141
https://github.com/RocketChat/Rocket.Chat/issues/5124

In the chatclient is another bug:
You can't download a shared file directly from the client - he try's to open a new browser window/tab and will download the file there.
In some cases this is not working - that's why i want to ask if you can implement a "direct-download" service for shared files in your clients.

Thanks!

**Comment by engelgabriel** [comment]
We have fixed a few of those problem with download on the lates versions. Can you please try with our demo server an let us know if the problem you are talking about persists?

**Comment by DalePayman** [comment]
Hey @engelgabriel,

yep, it's working! The client itself serves a download-window.
Perfect! Thx!
