### ISSUE TITLE
Pack unsupportet Filetypes for sharing

### ISSUE THREAD

**Issue by DalePayman** [RocketChat/Rocket.Chat#5555]
Your Rocket.Chat version: 0.46.0

Hi There!

Some useful filetypes do have no support for sharing them within rocketchat...
For example:
xlsx
pptx
or "Apple" Files for keynotes etc.

Can you support those types?
If you can't / you won't maybe another idea:
pack them! If someone want's to share a file with an unsupportet filetype the server can pack it (zip) and it's downloadable...

Thanks!

**Comment by engelgabriel** [comment]
Hi, you can configure the file type on the admin panel:

Administration -> Uploads -> Accepted Media Types -> File Upload

**Comment by DalePayman** [comment]
@engelgabriel 
Thanks for your Support but...

If i clean the List(should enable share of ANY type) i can't share eg XMLX
a window will show up, it says:

> Mediatype not accepted

> application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

if i append 
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
to allowed mediatypes it doesn't work...
