### ISSUE TITLE
Roles are ignored when creating new users via admin

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#5556]
rocket.chat Version used: snap package / ubuntu 16.04:
rocketchat-server  0.49.0   385  rocketchat  -
Your Rocket.Chat version: 0.49

The default "guest" role without any permission enabled, lacks a few security related things.
(Not a single option in the permission role "guest" has been set.)

We need to have a "guest" role, that is  permitted
 - to login
 - to be invited to a channel and/or private conversation - and can only talk there.
 - can't join any other Channel on their own / without invite
 - is per default not assigned to any channel ( we create them "by hand", so we leave the default channels switch off)

Why:
We have non private channels that can be used by regular (ldap) users, these should not be used by guests.
We wan't to have guests on the system, which should not be able to "free roam" around in the system.

User creation for guests is handled via admin interface registration is disabled. 
Assigned role for external people is: "guest"

question:
Is there something missing? how we can "fence" guests from the non private channels?
How can we make every channel invite-only for guests?

**Comment by IQ2022** [comment]
just create a new roll "name it member" give it the current users (default) roles, then modify users roles to basic.. sorry i dont know if i understood your question..

**Comment by engelgabriel** [comment]
@marceloschmidt can you please test this?

**Comment by engelgabriel** [comment]
What you described was the idea for the guest user indeed.

- only talk when invited to channels or private conversations
- can't join any other channel on their own without invite
- is per default not assigned to any channel

**Comment by engelgabriel** [comment]
The permissions are right, the problem seems to be that it is ignoring the ROLES when creating new users via admin.

**Comment by MartinSchoeler** [comment]
@maxdwit for now you can remove the users permission from these guest users and add them to the guest permissions, you can add and remove users from a role by clicking in the role name
![selection_019](https://cloud.githubusercontent.com/assets/20868078/21934511/cbd4a062-d990-11e6-9da4-3d0454cf57ae.png)
![selection_020](https://cloud.githubusercontent.com/assets/20868078/21934515/cfbbf3ba-d990-11e6-9f90-3f9554c2adee.png)

**Comment by maxdwit** [comment]
@MartinSchoeler thank you, that worked fine.
And yes, the WebGUI ignores the selected role "guest".
Looking forward to 0.49.2.
