### ISSUE TITLE
Missing/Hidden Direct Messages in 0.49

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#5558]
Your Rocket.Chat version: 0.49

We upgraded from 0.48.2 to 0.49 yesterday morning in our company.  It didn't take long before we started receiving reports of people not seeing direct messages.  The reports were all the same: their client (both desktop clients and browsers) would notify them of a new direct message, but the message wouldn't be there.  It was almost as if the message was hidden.  Logging out and logging back in would seem to fix it, the missing message would now be visible.  However, the problem would occur again within a short time.  Unfortunately, it doesn't happen with every message.

We were forced to downgrade back to 0.48.2.  As soon, as we did this, the problem went away.  Not sure how to troubleshoot this.  I'd be happy to supply any other information the developers would like.

Thanks.

**Comment by engelgabriel** [comment]
We believe we have a issue with the new version of the cache engine. We are working on that now.

**Comment by IQ2022** [comment]
how did you downgrade?

**Comment by mddvul22** [comment]
@IQ2022 

1. Shutdown all Rocket.Chat instances.
2. Access mongoDB directly, open the migrations collection and changed the version of the control record to version as it was in 0.48.2.  In this particular case, the command to update the collection was:
`db.migrations.update({"version":79},{"version":71.1})`
4. Move Rocket.Chat directory to Rocket.Chat.0.49
5. Move Rocket.Chat.0.48.2 to Rocket.Chat
6. Start up all instances of Rocket Chat.

**Comment by rodrigok** [comment]
@mddvul22 Are you running multiple instances of RocketChat? Are you using mongodb with replicaset enabled?

**Comment by mddvul22** [comment]
@rodrigok Two instances of rocketchat. Answer to replicaset is: no.

**Comment by rodrigok** [comment]
@mddvul22 Ok, so you should enable the replicaset, we are not supporting multiple instances without replicaset enabled.

@engelgabriel We should add this warning to our change log.

**Comment by engelgabriel** [comment]
@rodrigok agreed.

**Comment by engelgabriel** [comment]
@rodrigok can we put a warning on the ADMIN INFO? 

Since we know how many process are running and we also know if the DB is on ReplicaSET mode.

**Comment by rodrigok** [comment]
@engelgabriel Yes, but what do you think about a warning on top of the application? Like the reconnect warning.

**Comment by engelgabriel** [comment]
Ok if ONLY for admins... and we need to consider the process restarting flow, when it may appear as there are 2 instances when actually it is just 1 restarting.

**Comment by mddvul22** [comment]
Might I also suggest that something be added to https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/  because these were the instructions I used for running multiple instances.  I don't see anything there, either, about replica set being required.

**Comment by engelgabriel** [comment]
Sorry for not being clear. 

The resolution is that if you have multiple process, you must use OpLog, otherwise the system will go out of sync.

But we also fixed some minor bugs for the cache on single instances without OpLog :)

**Comment by mddvul22** [comment]
Got it, thanks!
