### ISSUE TITLE
Emoji titles translation not working

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#5559]
Your Rocket.Chat version: (0.49)
![bsehartgsmpoab6tg](https://cloud.githubusercontent.com/assets/17712562/21933433/b00c9082-d9a5-11e6-857d-4ddbbfeb59e9.png)

![image](https://cloud.githubusercontent.com/assets/17712562/21933438/b383b98e-d9a5-11e6-89ff-95a29150d938.png)

**Comment by saeedjalali1** [comment]
yes, I have the same issue.

**Comment by MartinSchoeler** [comment]
Fixed by #7195
