### ISSUE TITLE
Does new version change with the view of video chat; Is Ubuntu 14 preferred over 16 for RC?

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5569]
I am using RC v 0.42 and i am iframe RC in other website. so the window is smaller, then when i do video chat, there is a big blank space on the right of video chat window and window is blocked partially. Is the newer version still the same in terms of this feature? 

I followed tutorial on Digital Ocean on how to deploy RC on Ubuntu 14. Is there a tutorial for deploying RC on Ubuntu 16? is Ubuntu 14 preferred?

**Comment by antgel** [comment]
Closing as ancient and there are Ubuntu 16 tutorials out there.
