### ISSUE TITLE
Create a new setting for GitLab server URL

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#557]
Please see #512  

A new setting needs to be created to configure the gitlab server URL.

See  `packages/gitlab/gitlab_common.js`

**Comment by marceloschmidt** [comment]
@Sing-Li, I believe `packages/gitlab` is under our control, right? So that it would be possible for us to add a gitlab_startup + tapi18n files? I'm working on adding a settings option and I would like it to be set up under this package files...

**Comment by Sing-Li** [comment]
@marceloschmidt   ... Thanks, the thought is to contribute it  via Atmosphere so any meteor app can oauth via GitLab servers. I think we can still add anything we like to it as long as it doesn't break things for non Rocket.Chat users.

**Comment by marceloschmidt** [comment]
I see... but then adding the URL as a RocketChat.settings.get('API_Gitlab_URL') would not be good, because non-Rocket.Chat users would not be able to set the URL?

**Comment by Sing-Li** [comment]
They have to, somehow :-)  Open for ingenious implementations.

**Comment by marceloschmidt** [comment]
@Sing-Li I have added rocketchat-gitlab package, which creates the API_Gitlab_URL and overwrites Gitlab.Server with defined value in that setting. The package also loads the language files required for displaying the translated labels in settings page. Check out #563

**Comment by Sing-Li** [comment]
@marceloschmidt  :+1:   You da man!
