### ISSUE TITLE
Support for name as SAML claim

### ISSUE THREAD

**Issue by ygini** [RocketChat/Rocket.Chat#5570]
Your Rocket.Chat version: 0.49.0

When using SAML authentication, it could be interesting to grab name from SAML claim info.

At this time, email is grabbed from the claim and both name AND username are set to cn or username claim field.

Having the opportunity to set a proper display name as name with SAML could be a great improvement.

**Comment by engelgabriel** [comment]
Can you help we develop this?

**Comment by ygini** [comment]
Of course. In SAML you've a claim system that allow you to set user's infos in the consuming service.

In Rock.Chat+ user profile are made with name, username, e-mail, avatar and password.

When you use SAML, password is not needed (and never known), but other fields can be provided by the SAML server.

So IT team can set the SAML server to fill the name with de display name of the directory user, e-mail with e-mail, username with samAccountName, UniversalPrincipalName or shortname (depending of the kind of the source directory service).

At this time, SAML authentication has two issue.
- Username and name are filled with the same source info. We can't tell username to be a shortname and real name to be a display name.
- Unique identifier (NameID in SAML world) is the e-mail address, this mean when business will change e-mail pattern (for example with a domain update from examplecorp.com to example.com), all chat history will be lost for end user. Unique ID must be something unique AND consistent accros time. This isn't the case for e-mail. shortname/samAccountName/UniversalPrincipalName can be, or even better, ObjectID.

Tell me if you need more infos.

**Comment by localguru** [comment]
I have patched steffo_meteor-accounts-saml.js to read the displayName from my IdP and write it to profile.

``
/* name: loginResult.profile.cn || loginResult.profile.username, */                                                    // 111
name: loginResult.profile.realname || loginResult.profile.username,
```

and 

```
                                if (!profile.email && profile.mail) {                                                                            // 406
                                        profile.email = profile.mail;                                                                                   // 407
                                }                                                                                                                // 408

                                /* *** patch read displayName for profile */
                                if (!profile.displayName && profile['urn:oid:2.16.840.1.113730.3.1.241']) {     
                                        // See http://www.incommonfederation.org/attributesummary.html for defin
                                        profile.displayName = profile['urn:oid:2.16.840.1.113730.3.1.241'];
                                }

                                if (!profile.realname && profile.displayName) {                                 
                                        profile.realname = profile.displayName;                                 
                                } 
                                /* *** end patch */
``
Ciao

**Comment by pierre-lehnen-rc** [comment]
Current version of Rocket.Chat now supports this.
