### ISSUE TITLE
User profile from SSO must not have password change option

### ISSUE THREAD

**Issue by ygini** [RocketChat/Rocket.Chat#5571]
Your Rocket.Chat version: 0.49.0

Using SAML as user authentication source, user profile are created and presented as local profile.

This mean user is able to change the password and admin to reset it.

And when they do this, username + new password work at login time as local user, bypassing all security feature linked to SAML.

**Comment by engelgabriel** [comment]
@rodrigok do we have a setting to disable password change for SAML, LDAP, etc users?

**Comment by ygini** [comment]
I the global setting I've disabled the password change option (but this mean I can't have both local users and SSO provided one [usecase: SSO for employee, local account for external users]).

This seems to block the password change for the end user, even the password change field is still available and say the password change is OK.

But this does not block the password reset for the admin.

Regarding SSO, by nature, disabling password change must not be an option. SSO users may have a link provided to access to a centralized password change web page. But in any case, it's impossible for a consuming app to offer a builtin password change option.

**Comment by ygini** [comment]
Small note, I use SAML and you tagged the issue related to SAML auth, but this apply to all kind of SSO.

**Comment by Perksls** [comment]
That's true, but this has an advantage, for instance i have login form disabled, and when I updated to 0.49.0 the SSO broke, but my users were still capable of login trough console with Meteor.LoginWithPassword() with a generic password I've set them, then they changed it. Other advantage it's that The upcoming android app doesn't have SSO to custom oAuth, but the users can still login with it using username and password, so I'd ask you guys, if you change this, make it a setting instead of disabled it all along

**Comment by ygini** [comment]
@Perksls I'm sorry for you but what you describe isn't SSO, you use a bug as a feature and should really find an other way. Any other service without this implementation error won't allow you to work that way.

Also, SSO (and more over SAML/OAuth) is made for high level security. Third part service never get access to end user password, plus any third part service can be really secure with two factor authentication of any kind (SMS OTP? Mail OTP? QRCode Based OTP? etc.).

So, implementation error on this kind of topic should absolutely not exist. People using it has high expectation.

@Perksls for what it's worth, I recommend you to use LDAP backend.

**Comment by Perksls** [comment]
I know you're right, but that's why I was asking to make it a setting, like under custom oauth a setting to allow user set a local password. Unfortunately I can't use ldap as the board I'm using to authenticate users against it  doesn't have that feature

**Comment by ygini** [comment]
@Perksls I some way, your scenario isn't that bad. Some service already use OAuth as a prefill solution. It's not a really good user experience but could be OK.

Maybe Rocket.Chat+ could allow the admin to set the SSO as a source of identity and let the authentication part optional. That could fit the needs for both scenario.
