### ISSUE TITLE
Stream "notify-room-users" is missing in the document

### ISSUE THREAD

**Issue by wandonye** [RocketChat/Rocket.Chat#5573]
Your Rocket.Chat version: (48.2)

The document mentioned 4 streams: 
stream-notify-all
stream-notify-user
stream-notify-room
stream-room-messages

I found 'notify-room-users' used [here](https://github.com/RocketChat/Rocket.Chat/blob/9de71af4b44a204d607f272c7eefd63116b5f88d/packages/rocketchat-lib/client/Notifications.coffee), but is not mentioned at all. 
Does it function the same way as the above 4? (So there is a stream I can subscribe named "stream-notify-room-users")? What parameters it requires?

**Comment by geekgonecrazy** [comment]
Which document did you find these in? Check out our real time documentation: https://rocket.chat/docs

**Comment by engelgabriel** [comment]
@rodrigok do we need to update the docs?

**Comment by wandonye** [comment]
@geekgonecrazy The streams were mentioned in [the real time documentation](https://rocket.chat/docs/developer-guides/realtime-api/subscriptions).
