### ISSUE TITLE
Adding Channel go hides logo portion 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5576]
When you click on (+) to add channel it hides the logo section.. 

![image](https://cloud.githubusercontent.com/assets/12454319/21955485/069816b2-da3a-11e6-9e2b-a4ceee1613c1.png)

Your Rocket.Chat version: (49.1)

**Comment by Nemra1** [comment]
This is problem with z-index..u need to up number from 3 to 10
