### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by a-abella** [RocketChat/Rocket.Chat#5577]
Version 48.1

All I have available to share is the below log output:

```
Jan 14 05:26:02 chat rocketchat: #033[34mSyncedCron ➔ info#033[39m Finished "Generate and save statistics".
Jan 14 05:26:19 chat rocketchat: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Jan 14 05:26:19 chat rocketchat: <--- Last few GCs --->
Jan 14 05:26:19 chat rocketchat: 2717981129 ms: Scavenge 1352.5 (1458.8) -> 1352.5 (1458.8) MB, 1.6 / 0 ms (+ 0.1 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
Jan 14 05:26:19 chat rocketchat: 2717983713 ms: Mark-sweep 1352.5 (1458.8) -> 1345.4 (1458.8) MB, 2584.1 / 0 ms (+ 8.0 ms in 77 steps since start of marking, biggest step 0.8 ms) [last resort gc].
Jan 14 05:26:19 chat rocketchat: 2717986269 ms: Mark-sweep 1345.4 (1458.8) -> 1351.7 (1458.8) MB, 2556.2 / 0 ms [last resort gc].
Jan 14 05:26:19 chat rocketchat: <--- JS stacktrace --->
Jan 14 05:26:19 chat rocketchat: ==== JS stack trace =========================================
Jan 14 05:26:19 chat rocketchat: Security context: 0x31b40a2b4629 <JS Object>
Jan 14 05:26:19 chat rocketchat: 1: init [_linklist.js:~3] [pc=0x2abca789955f] (this=0x14baf73496d1 <an Object with map 0x28d58ceb2059>,list=0x221aa830b1a9 <an Immediate with map 0x28d58ceb1ea1>)
Jan 14 05:26:19 chat rocketchat: 2: /* anonymous */(aka /* anonymous */) [timers.js:425] [pc=0x2abca7b0aa78] (this=0x31b40a2041b9 <undefined>,callback=0x221aa830b259 <JS Function (SharedFunctionInfo 0x269b27a9849)>,arg1=0x31b40a2041b9 <undefined>,arg2=0x31b40...
Jan 14 05:26:20 chat systemd: rocketchat.service: main process exited, code=killed, status=6/ABRT
Jan 14 05:26:20 chat systemd: Unit rocketchat.service entered failed state.
Jan 14 05:26:20 chat systemd: rocketchat.service failed.
```

The server has 4GB of RAM/4GB swap and there are currently no active rocketchat users so load shouldn't be high.

**Comment by engelgabriel** [comment]
Can you give us some more info?
How many users?
Home many chat process?
Is the MongoDB running on the same machine?
Is the MongoDB running in ReplicaSet mode?
Can you backup your data and try with the version 0.49.1?

**Comment by a-abella** [comment]
17 registered users but 0 active--it's in preproduction.
Single process.
Mongodb on same machine, yes.
No replicaset.
I can update but I can't reproduce the crash conditions. It just crashed in the early morning, no one was using it.

**Comment by engelgabriel** [comment]
Can you turn ReplicaSET mode on?Meteor works better with it, in general. It will reduce the amount of CPU and memory used to keep in sync with the DB.

**Comment by a-abella** [comment]
I've turned ReplicaSet on and updated to latest.

I'll be sure to keep an eye on it and report back if anything happens. The server's been in preproduction for nearly three months without a crash so I don't know what circumstances could have led to this one.

**Comment by engelgabriel** [comment]
Thanks @a-abella please open a new issue if the problem happens again. I'll close this one as we have already to many to track ourselves. 😄

**Comment by thehoss** [comment]
This just happened to me too.
