### ISSUE TITLE
Side Nav Bug : Big space between Side Nav and main-content v0.49.1

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5579]
Your Rocket.Chat version: (0.50.0)
Today i catch this error in all browser 
![2017-01-14_211918](https://cloud.githubusercontent.com/assets/22897987/21957479/960b245a-da9f-11e6-8bb3-48454e2b363b.png)
i think this is in css ! any fix?

**Comment by engelgabriel** [comment]
How can we replicate it? Do you have some custom CSS?

**Comment by Nemra1** [comment]
yup but not contain .side-nav or .main-content class

**Comment by engelgabriel** [comment]
We can only help if we see the server... as this is not happening in any other server.

**Comment by Nemra1** [comment]
okey ..how i can give u My Data?

**Comment by engelgabriel** [comment]
on the demo server

**Comment by Nemra1** [comment]
Okey im come

**Comment by MartinSchoeler** [comment]
Maybe related to #5225 ?

**Comment by engelgabriel** [comment]
If this only happens on screen resize, this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/5225
