### ISSUE TITLE
Add GitLab icon for Oauth button

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#558]
Relates to #512.

Need UI guru help to add GitLab oauth button icon /  glyph

See `client/views/login/services.coffee`   (look for comment)

Artwork can be found here:

https://about.gitlab.com/press/

**Comment by engelgabriel** [comment]
Added on https://github.com/RocketChat/Rocket.Chat/commit/d0c89fbf3708470cece830f5b5c8a36f05c42d93
