### ISSUE TITLE
UI on iphone app is not working properly 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5580]
I have iphone 5s, IOS 10.2

![image](https://cloud.githubusercontent.com/assets/12454319/21959578/7ecbbc88-da99-11e6-9b21-b038b2eebb93.png)
![image](https://cloud.githubusercontent.com/assets/12454319/21959583/9a55f734-da99-11e6-959d-7778a32b126f.png)

![image](https://cloud.githubusercontent.com/assets/12454319/21959581/8eeee4d2-da99-11e6-9b27-2829daea7706.png)

Your Rocket.Chat version: (49.1)

**Comment by Nemra1** [comment]
same thing her and more !

**Comment by engelgabriel** [comment]
@IQ2022 @Nemra1 what version of the server are you using now?

**Comment by engelgabriel** [comment]
Just seen on the bottom...

> Your Rocket.Chat version: (49.2)

**Comment by IQ2022** [comment]
@engelgabriel sorry that was a typo, its 49.1...

**Comment by IQ2022** [comment]
fyi same issue happen with running demo.rocket.chat on my phone it doesnt fit screen and UI is all over the place..

**Comment by Nemra1** [comment]
Its same thing with last version
