### ISSUE TITLE
user list is very slow after update

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5581]
Your Rocket.Chat version: ( latest)
Before update to 49.1 evrything wass fine
after update from 0.44.0 to .0.49
get some issu like this
![2017-01-15_044913](https://cloud.githubusercontent.com/assets/22897987/21959899/7508f18a-dade-11e6-968b-a3ba5d61363e.png)
take from 3 Sec to 5 sec
it wass faster before update ! any way to fix that or back to old version?

**Comment by engelgabriel** [comment]
@rodrigok maybe we can send the list of users for small channels?

**Comment by Nemra1** [comment]
@rodrigok look at v44.0  more faster

**Comment by rodrigok** [comment]
@Nemra1 Yeap, we are not sending the user list within the room's information, we are getting that list only when users open the users tab. That turns the load of channels faster.

We can think in a solution, maybe send the first 20 users, or send users when the list is not large, etc. Or we can get the user's list after getting the room's data, then users can start chatting while we are downloading the user's list.

**Comment by Nemra1** [comment]
@rodrigok blv me when i said im trying evry rocket chat version. .and specific version 44.0 its more faster for video call ..switch between  rooms..get userlist..specifc userlist...no mistake in this version .....but..some options not work like add custom emojj or restart server button. ..to now this options not fixed after all updates ...blv me i need to update for new add ones in higher versions but i cant bcs no staple version to now..also none of my future request add in any versions to now ( click on my name )..
But ..i love rocket chat..im coming from 123flashchat im sure u know this company
but is dead now..and start to learn Rocket Chat system for now
this script missing important Options like

1-  anti Flood Control (  some bad user can flood my channel with 30 txt line in 5 second ( and idont have option to clear the msgs from room 
maybe u need to add auto mute option in this situation 

2- Ban System allowed  to banned
 ( ip, username,mac address, android device id, ban from some channel or all channels )

3-  Kick from channel and comback after 15 Minutes  ( For example ) in this time when im remove some user ..its easy to click join again and login 

4- Font option.( color button ,bold button ,font selected)
this addones get more traffic and nice style ..
im using Rocket Chat like A public Messenger Not for Team ..
in the end..im sorry for my long words..but realy i Wich more successful for Rc team in the future. ...

**Comment by rodrigok** [comment]
@Nemra1 Sorry if we are not doing the things you need, we have a list of priorities and a small team to maintain this software free for every one.

But as we are Open Source, you can help you, us and the community opening new PRs with implementations of what you need, we will be happy to review and help you to do that.

If you can't contribute with code you can contribute with strategy on how to implement these things, how it will cost for our performance and ideias on how to make it usable and faster.

I know you understand that. We are working hard to create the best chat, to get more people involved and to get more devs in our core team.

Any help is welcome. And, please keep creating issues and helping us to identify the places we should put our focus.

We are working to improve performance, so I'll close this issue for now.
