### ISSUE TITLE
Can we have a capturing minutes of meeting or running meeting functionalilty in rocket chat.

### ISSUE THREAD

**Issue by spathare21** [RocketChat/Rocket.Chat#5584]
Your Rocket.Chat version: (make sure you are running the latest)

As we have a functionality for running meeting in IRC chat using meetbot [](https://wiki.debian.org/MeetBot
). do we have such functionality for rocket chat. so that we can start meeting and capture the details/minutes of meetings in below format and we can send mail directly to anyone with details.

format : 

#Channel Name.

Meeting started by

Meeting summary   

    Roll Call 
    Tasks update 
    Next Meeting at 

Meeting ended at 

Action items
    (none)

People present (lines said) 

Generated by

**Comment by engelgabriel** [comment]
Maybe we can add the meetbot integration script?

**Comment by engelgabriel** [comment]
@spathare21 can you share the link to the meetbot document?

**Comment by spathare21** [comment]
@engelgabriel  find meetbot details here [](https://wiki.debian.org/MeetBot) did't found any link about its integration with other chat applications.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
