### ISSUE TITLE
Mobile Apps stuck at loading screen after files update

### ISSUE THREAD

**Issue by klatys** [RocketChat/Rocket.Chat#5585]
Your Rocket.Chat version: 0.49.1
After updating from 0.49.0 most of our users report that updating files in mobile app causes them to get stuck on loading screen (blue fullscreen with three dots). Reinstalling the entire app (from appstore) helped to solve this issue. Anyone with same issue?
Any idea what might cause this or how to prevent it in future?

**Comment by engelgabriel** [comment]
Thanks @klatys we will investigate it.

**Comment by admin-crowd-iugo** [comment]
we had broken displays/CSS after updating in the mobile apps. We have downgraded now from an old backup to 0.48.2
.

**Comment by klatys** [comment]
FYI after updating server from 0.49.1 to 0.49.2, updating in mobile client today did not reproduce this - confirmed by multiple users.

**Comment by akachapati** [comment]
I'm getting same problem with 0.49.3. Anybody else?

**Comment by TheReal1604** [comment]
On my multinode deployment 0.49.3 all went fine. Updating the mobile clients works as expected..

**Comment by klatys** [comment]
Same problem again with 0.49.4 Unfortunately I will have to downgrade and stop automatic updating till this is resolved :/

**Comment by Key4ce** [comment]
I have updated to 0.49.4 and same issue here. Anybody have a work around?

**Comment by hall9** [comment]
Any update on this issue?

I have this issue on 48.2 but it only happens in very particular situations otherwise update works very well.
It seems to trigger an update when the auto-scaling kicks in and users get dished off to the new server which results in the update hang. I've also seen this issue when rebuilding (with no changes) and swapping servers in my blue-green environment.

I figure its an issue with calculating the hash file version (which may not be the same across servers)

**Comment by klatys** [comment]
I'm not sure if that's what you mean, but we have only one instance running in docker..

**Comment by mrsimpson** [comment]
Having the same issue heee on iOS and the RC demo server: just updated the app in-app (five files were loaded). 
Since then, I only get the blue screen with the three loading dots.

**Comment by KirbySSmith** [comment]
This issue is fixed by https://github.com/RocketChat/Rocket.Chat.Cordova/pull/182

**Comment by kkumaresan** [comment]
Hi, we at Mongrov have developed a react-native mobile client library for Rocket.Chat. Please check this url: https://github.com/mongrov/roverz . Works both on iOS and Android. If you get a chance, do check this project for a comprehensive native mobile app using Rocket.Chat. We welcome your feedback 🙂

**Comment by Hudell** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat.Cordova/pull/182
