### ISSUE TITLE
User rename via admin panel throws internal server error

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#5586]
Your Rocket.Chat version: 0.49.1

Seems like the username rename feature is broken again. Now some users are in an inconsistent state e.g. messages are showing the new name but direct messages channels still the old one :(

```
[34mI20170116-10:23:29.628(0) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at MongoConnection.<anonymous> (packages/meteor.js:213:24)   at MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:766:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/app/bundle/programs/server/packages/mongo.js:4007:31)   at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:8632:32)   at _Class.update (/app/bundle/programs/server/packages/rocketchat_lib.js:3592:36)   at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (/app/bundle/programs/server/packages/rocketchat_lib.js:4296:17)   at /app/bundle/programs/server/packages/rocketchat_lib.js:3153:41   at SynchronousCursor.forEach (/app/bundle/programs/server/packages/mongo.js:1038:18)   at Cursor.(anonymous function) [as forEach] (/app/bundle/programs/server/packages/mongo.js:890:44)   at RocketChat._setUsername (/app/bundle/programs/server/packages/rocketchat_lib.js:3150:64)   at Object.setUsername (/app/bundle/programs/server/packages/rocketchat_lib.js:1122:19)   at Object.RocketChat.saveUser (/app/bundle/programs/server/packages/rocketchat_lib.js:2534:15)   at [object Object].Meteor.methods.insertOrUpdateUser (/app/bundle/programs/server/packages/rocketchat_lib.js:11576:23)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1029:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)   at /app/bundle/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1040:48   at Session.method (/app/bundle/programs/server/packages/ddp-server.js:1018:23)   at /app/bundle/programs/server/packages/ddp-server.js:880:89      - - - - -   at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1048:67   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:436:9)   at process._tickDomainCallback (node.js:406:13) 
```

**Comment by graywolf336** [comment]
I just tested this locally, and it worked...

**Comment by engelgabriel** [comment]
@subesokun what version of MongoDB are you using?
If you try to rename again, does the problem persists?

**Comment by rodrigok** [comment]
I tested on my machine and it's working.

**Comment by subesokun** [comment]
@engelgabriel I'm using MongoDB version 3.2.6

Mhhh seems like then this feature is working on a clean instance of Rocket.Chat but our instance is running already quite some time and hence we've performed already many updates of Rocket.Chat. Maybe over the time some user data has been corrupted or some DB migrations after an update have failed :/ Is there some way to perform a sanity check on the DB? Or on which collection should I have a look to figure our which data is missing that could have potentially caused this issue?

**Comment by rodrigok** [comment]
@subesokun Can you access you database, execute a query and paste the result?

```
db.rocketchat_message.find({ 'mentions': {$exists: true}, 'mentions.0': {$exists: false} })
```

**Comment by rodrigok** [comment]
@subesokun Sorry, that was a wrong query, the correct one is:

```
db.rocketchat_message.find({ $and: [{'mentions': {$exists: true}}, {'mentions': {$ne: []}}], 'mentions.0': {$exists: false} })
```

**Comment by subesokun** [comment]
@rodrigok The query returns no records hence I think the message collection is ok.

`MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username`

I've tried to debug it and if I run the exact same update query (see [here](https://github.com/RocketChat/Rocket.Chat/blob/c02efa2738067b3c94bd6ef6e52dd559252d68c2/packages/rocketchat-lib/server/models/Messages.coffee#L311)) with Robomongo then I get no error... 

I've also tried to rewrite the update query to use $elemMatch and use the userId instead of the username in the find query but still getting the same error :( Could there be something wrong with the mongo package that gets used by Rocket.Chat?

```
db.getCollection('rocketchat_message').update({ _id: 'CvRYKmTPn8Qo8nKTe',   mentions: { '$elemMatch': { _id: 'cnohnM4dBATZbwbvk' } } }, { '$set':     { 'mentions.$.username': 'abc',      msg: '@abc: some message' } });
```

**Comment by rodrigok** [comment]
The message RC is trying to update is `CvRYKmTPn8Qo8nKTe`? Can you paste the content here?

**Comment by subesokun** [comment]
```
{
    "_id" : "CvRYKmTPn8Qo8nKTe",
    "rid" : "RCjZs6jsCuFSc5tBj”,
    "msg" : “@SomeUser: message”,
    "ts" : ISODate("2016-04-25T06:11:37.767Z"),
    "u" : {
        "_id" : "aKNHMGuxAYykWH8ZY",
        "username" : “SomeOtherUser”
    },
    "mentions" : [ 
        {
            "_id" : "cnohnM45BATZbwbvk",
            "username" : “SomeUser”
        }
    ]
}
```

But I think the content is ok. Maybe something is broken with our MongoDB instance, code-wise everything looks ok so far.

**Comment by subesokun** [comment]
Migrated DB onto an other MongoDB running version 3.2.10 but still having the same problem.

**Comment by subesokun** [comment]
@rodrigok Does the following work for you on your local instance?

1.) Create new user someuser
2.) Login as someuser
3.) Create a room "test" and invite someuser + your admin user into it
4.) Write a message from admin user to someuser in the test room e.g.
   `@someuser Hello World`
5.) Try to rename someuser to someotheruser

This throws for me also the same mongo update.

**Comment by subesokun** [comment]
Awesome, thanks for fix :)!
