### ISSUE TITLE
RocketChat returns to default language after browser refresh

### ISSUE THREAD

**Issue by danersc** [RocketChat/Rocket.Chat#5592]
Your Rocket.Chat version: 0.48.2

RocketChat returns to the default language after selecting "pt" in the admin panel.
The error does not appear immediately, only after the user refreshes the browser.
In this way all translated terms and also labels are placed in English.

Before refresh
![screen_pt_before_refresh](https://cloud.githubusercontent.com/assets/1556959/21984067/495cd274-dbdb-11e6-9e09-746a591e9979.png)

After

![screen_en_after_refresh](https://cloud.githubusercontent.com/assets/1556959/21984073/502d58d0-dbdb-11e6-9f49-8674016de523.png)

**Comment by rodrigok** [comment]
Can you help us to reproduce the error?

The user who see the error is the same that changed the admin setting? What was the personal language preference of that user? It was set?

**Comment by cyclops24** [comment]
Hi @engelgabriel  and @rodrigok ,
I have same problem.
Can you help me to fix this?

**Comment by mnlbox** [comment]
@rodrigok I have same issue.
RocketChat returns to default language sometimes then I go to `My Account` and set language to `English` and then set to my favorite language and then it's fix.

@engelgabriel please reopen this issue until fix completely.

**Comment by cyclops24** [comment]
@engelgabriel I can confirmed that this issue still exist.
Part of #8175

**Comment by cyclops24** [comment]
Part of #8494

**Comment by MrLiNk** [comment]
can confirm, bug still exist

**Comment by lequy1010** [comment]
> Your Rocket.Chat version: 0.48.2
> 
> RocketChat returns to the default language after selecting "pt" in the admin panel.
> The error does not appear immediately, only after the user refreshes the browser.
> In this way all translated terms and also labels are placed in English.
> 
> Before refresh
> ![screen_pt_before_refresh](https://cloud.githubusercontent.com/assets/1556959/21984067/495cd274-dbdb-11e6-9e09-746a591e9979.png)
> 
> After
> 
> ![screen_en_after_refresh](https://cloud.githubusercontent.com/assets/1556959/21984073/502d58d0-dbdb-11e6-9f49-8674016de523.png)

I think Rocket.Chat have not fix it.
You can flow here and try again
https://github.com/RocketChat/Rocket.Chat/issues/12628
