### ISSUE TITLE
Routes NOT loading in 0.49.2?

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#5594]
Your Rocket.Chat version: (make sure you are running the latest)

Cannot load any route other than channels (channels load just fine). For instance, if I try to go to: /home I get the following error: 

TypeError: RocketChat.TabBar.showGroup is not a function
    at v.action [as _action] (259977a….js?meteor_js_resource=true:555)
    at v.callAction (259977a….js?meteor_js_resource=true:210)
    at 259977a….js?meteor_js_resource=true:210
    at Object.o.nonreactive (259977a….js?meteor_js_resource=true:57)
    at 259977a….js?meteor_js_resource=true:210
    at o.Computation._compute (259977a….js?meteor_js_resource=true:57)
    at o.Computation._recompute (259977a….js?meteor_js_resource=true:57)
    at Object.o._runFlush (259977a….js?meteor_js_resource=true:57)
    at Object.o.flush (259977a….js?meteor_js_resource=true:57)
    at g._invalidateTracker (259977a….js?meteor_js_resource=true:210)

**Comment by engelgabriel** [comment]
Can you give more info? It is working on our demo server.. so I am not sure how to reproduce.

**Comment by Syirrus** [comment]
It is working on the DEMO server. I have been upgrading my instance since 0.17 so things might be FUBAR'ed

I'm also getting this error:

on start up 

`I20170117-17:35:29.572(-5)? Exception in defer callback: WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: meteor.rocketchat_room index: name_1 dup key: { : \"general\" }","op":{"_id":"GENERAL","ts":"2017-01-17T22:35:29.559Z","t":"c","name":"general","usernames":[],"msgs":0,"default":true,"_updatedAt":"2017-01-17T22:35:29.559Z"}})
I20170117-17:35:29.572(-5)?   at Object.Future.wait (/Users/johnhand/.meteor/packages/meteor-tool/.1.4.2_3.1hogi08++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20170117-17:35:29.572(-5)?   at MongoConnection.<anonymous> (packages/meteor.js:213:24)
I20170117-17:35:29.573(-5)?   at MongoConnection.(anonymous function) [as insert] (/Users/johnhand/Documents/Sandbox/clarapy.com/Server/Rocket.Chat/.meteor/local/build/programs/server/packages/mongo.js:766:49)
I20170117-17:35:29.573(-5)?   at Object.<anonymous> (packages/matb33_collection-hooks.js:395:18)
I20170117-17:35:29.573(-5)?   at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
I20170117-17:35:29.573(-5)?   at [object Object].insert (/Users/johnhand/Documents/Sandbox/clarapy.com/Server/Rocket.Chat/.meteor/local/build/programs/server/packages/mongo.js:3944:38)
I20170117-17:35:29.574(-5)?   at ModelsBaseDb.insert (/Users/johnhand/Documents/Sandbox/clarapy.com/Server/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:8621:54)
I20170117-17:35:29.574(-5)?   at ModelRooms.insert (/Users/johnhand/Documents/Sandbox/clarapy.com/Server/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:3614:36)
I20170117-17:35:29.574(-5)?   at ModelRooms.createWithIdTypeAndName (/Users/johnhand/Documents/Sandbox/clarapy.com/Server/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:5368:10)
I20170117-17:35:29.574(-5)?   at /Users/johnhand/Documents/Sandbox/clarapy.com/Server/Rocket.Chat/.meteor/local/build/programs/server/app/app.js:4212:31
I20170117-17:35:29.575(-5)?   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170117-17:35:29.575(-5)?   at packages/meteor.js:445:45
I20170117-17:35:29.575(-5)?   at runWithEnvironment (packages/meteor.js:1176:24)
I20170117-17:35:29.575(-5)? 
I20170117-17:35:29.575(-5)?     - - - - -
I20170117-17:35:29.575(-5)?   at Function.MongoError.create (/Users/johnhand/.meteor/packages/npm-mongo/.2.2.16_1.gm2nm1++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
I20170117-17:35:29.576(-5)?   at toError (/Users/johnhand/.meteor/packages/npm-mongo/.2.2.16_1.gm2nm1++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:114:22)
I20170117-17:35:29.576(-5)?   at /Users/johnhand/.meteor/packages/npm-mongo/.2.2.16_1.gm2nm1++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:657:23
I20170117-17:35:29.576(-5)?   at handleCallback (/Users/johnhand/.meteor/packages/npm-mongo/.2.2.16_1.gm2nm1++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:95:56)
I20170117-17:35:29.576(-5)?   at resultHandler (/Users/johnhand/.meteor/packages/npm-mongo/.2.2.16_1.gm2nm1++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:421:14)
I20170117-17:35:29.576(-5)?   at /Users/johnhand/.meteor/packages/npm-mongo/.2.2.16_1.gm2nm1++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:455:18
I20170117-17:35:29.577(-5)?   at nextTickCallbackWith0Args (node.js:436:9)
I20170117-17:35:29.577(-5)?   at process._tickDomainCallback (node.js:406:13)
I20170117-17:35:29.577(-5)? 
=> Started your app.`

**Comment by engelgabriel** [comment]
@Syirrus how are you running your server? Downloading our compiled version? Docker image? What version of the DB? Is it on replicaset mode? Please share as much info as you can for use to try to help you.

**Comment by Syirrus** [comment]
@engelgabriel Sorry for the previous posts being that they were vague. 
I'm running a standard heroku install of Rocket.Chat. The backend is on MLAB with oplog enabled. 

When I try to run the instance on heroku all is well, but when I go to /home I just get the load screen. After about a minute or so, the left side bar will load, but the load screen is still there. If I go to a channel things load up just fine quickly with all of my chat messages.

When I try to run this on my local machine, I'm getting the same behavior essentially. I've even cleared the DB on my local machine with the same results.  

Thank you so much for responding to me.

Syirrus

**Comment by rodrigok** [comment]
@Syirrus Which Rocket.Chat version are you using?

**Comment by Syirrus** [comment]
@engelgabriel @rodrigok 
I'm running the latest version or commits rather in the "develop" branch.

After updating, I'm still getting:

`Exception from Tracker recompute function:
meteor.js?hash=e3f53db…:930 TypeError: RocketChat.TabBar.showGroup is not a function
    at Route.action [as _action] (router.coffee:58)
    at Route.callAction (kadira_flow-router.js?hash=863da7f…:889)
    at kadira_flow-router.js?hash=863da7f…:619
    at Object.Tracker.nonreactive (tracker.js?hash=9f8a0ce…:631)
    at kadira_flow-router.js?hash=863da7f…:603
    at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)
    at Tracker.Computation._recompute (tracker.js?hash=9f8a0ce…:358)
    at Object.Tracker._runFlush (tracker.js?hash=9f8a0ce…:523)
    at Object.Tracker.flush (tracker.js?hash=9f8a0ce…:483)
    at Router._invalidateTracker (kadira_flow-router.js?hash=863da7f…:661)`

This only occurs on routes other than the channels, if that makes any sense.

**Comment by rodrigok** [comment]
@Syirrus Can you simulate this problem with a fresh install? I can't simulate it here on my machine.

**Comment by Syirrus** [comment]
@rodrigok I did a fresh install and it seems to work. It must be on my end :(

**Comment by Syirrus** [comment]
@rodrigok I'm not so sure it's on my end.... I've rolled back on my source control and things work (along with my DB). As soon as I update to the latest, things break in the same manner.

**Comment by engelgabriel** [comment]
can you give us a link to test this and debug?

**Comment by Syirrus** [comment]
@engelgabriel https://clarapy.chat

**Comment by MartinSchoeler** [comment]
@Syirrus Is the problem solved then?

**Comment by Syirrus** [comment]
@MartinSchoeler Yes everything seems to be working :)
