### ISSUE TITLE
Nav organization

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#560]
Just suggestion that we move "Administration" to the drop down next to your name in the top left for those who have admin, next to "My Account" and also make quick admin links in the area that opens from the right when you click a name in a chat room.. (such as to ban/deactivate them).

**Comment by rodrigok** [comment]
I totally agree with the position of "Administration" button.

**Comment by rodrigok** [comment]
Please open another issue for Right Panel quick admin links
