### ISSUE TITLE
Max number of Active Socket Connections

### ISSUE THREAD

**Issue by littlep13** [RocketChat/Rocket.Chat#5608]
Rocket.Chat version: 0.34.0

I'm writing a scalability tool (in C# using Net.DDP.Client) that would create more than 1000 ddp connections in a short time window in order to test the behaviour of Rocket.Chat under huge loading. 

In the testing, after connecting about 1000 ddp clients (e.g. creating 1100 clients), I found that the rest of ddp clients wouldn't be able to connect anymore. 

If I try to log in from Chrome, it falls back to an error page saying "The site could be temporarily unavailable or too busy". If I have any browser session that has already connected to the Rocket.Chat instance, it will be working without any issue. After killing my scalability tool (clearing out the connections), the site would then be back online.

I've done a little bit of research online and suspected this was an http-proxy issue. According to the logic in Meteor, maxSocket of http.agent should be defaulted as 100, and I couldn't relate the value to the behaviour that I was seeing.

Does anyone know what the maximum number of active connections is supported in Rocket.Chat? And, is the max. number configurable? Ideally, I would like to see how Rocket.Chat would behave with 10k active connections.

**Comment by beginrescueend** [comment]
Are you running on Linux?  You may have your open files limit set to 1024 (which would cause TCP sockets to max out some where around 1,000).

Check `ulimit -n` in the script that starts up Rocket.Chat:
  https://serverfault.com/questions/48717/practical-maximum-open-file-descriptors-ulimit-n-for-a-high-volume-system
  https://unix.stackexchange.com/questions/157351/why-are-tcp-ip-sockets-considered-open-files

This affects both open files and open TCP sockets (1,024 total).

I have no idea of the limit of connections in Rocket.Chat.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Kinda old with no new posts.

Would be interested to hear what else you found.

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support category
