### ISSUE TITLE
online counter isn't not updated till the page reloads

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5609]
Rocket.Chat version: (latest version)
<img src="https://i.imgsafe.org/d94fc12b86.gif" alt="Mountain View" style="width:304px;height:228px;">

**Comment by Nemra1** [comment]
Yup..same thing her

**Comment by IQ2022** [comment]
issue persist after upgrading 49.3 user list doesn't update... its actually frustrating.. i dont know who is online or not.. i'd say this is important..

**Comment by engelgabriel** [comment]
@zorenleo @Nemra1 @IQ2022 we are working on this, but you don't need to refresh the page, you can simple close/open the members list.

**Comment by zorenleo** [comment]
Alright @engelgabriel thank you, you're awesome.

**Comment by karlprieb** [comment]
It's already fixed
