### ISSUE TITLE
Sidebar broken on cordova / mobile

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5612]
Your Rocket.Chat version: 0.49.2

After the update to 0.49.2 the sidebar is broken for me on cordova, you can reproduce this with the following steps:

- open room
- click on any of the icons of the right sidebar
-> Sidebar is hiding

(this also happens on demo!!!)

Screenshots:

before the click:

![2017-01-17 07-21-40 3772](https://cloud.githubusercontent.com/assets/5877910/22009802/bb1d673e-dc85-11e6-8ece-5259b6d6201f.png)

after clicking one of the icons from the sidebar:

![2017-01-17 07-21-44 3773](https://cloud.githubusercontent.com/assets/5877910/22009809/c75b67f8-dc85-11e6-80c0-c282185169e4.png)

Why are you breaking things for cordova in the stable branch? :( There is no alternative for mobile users.

**Comment by Nemra1** [comment]
Same thing her 0.49.1+0.49.2

**Comment by engelgabriel** [comment]
Sorry @TheReal1604 the code for the Cordova is the one and the same of the web app. We tested on many responsive windows, but for some reason the Cordova was differente.

@karlprieb, please prioritise this issue here.

**Comment by TheReal1604** [comment]
@engelgabriel @karlprieb thanks for the real fast fix. Until the cordova app is in heavy usage it should be better tested. :(
