### ISSUE TITLE
Slack import fails

### ISSUE THREAD

**Issue by axeloz** [RocketChat/Rocket.Chat#5615]
Hello at all, 

I'm running Rocket.chat latest version on a brand new Ubuntu box using snaps. 
The Slack import doesn't work, it freezes quite quickly. It imports 7 users, sometimes 6, sometimes 0 channel, sometimes 1 channel.
When changing page, I get an error message saying : 
`The importer wasn't defined properly, it's missing the Import class` 
I tried many times but no luck. 

Thanks a lot,

Axel

**Comment by graywolf336** [comment]
Please view the logs and let me know what errors occur.

**Comment by axeloz** [comment]
Hello, 

Here's what I get in journalctl when I start a migration

`
Jan 17 16:28:02 chat snap[28664]: Exception in defer callback: Error: [error-invalid-domain]
Jan 17 16:28:02 chat snap[28664]:   at /snap/rocketchat-server/398/programs/server/app/app.js:255:13
Jan 17 16:28:02 chat snap[28664]:   at /snap/rocketchat-server/398/programs/server/packages/accounts-base.js:1730:10
Jan 17 16:28:02 chat snap[28664]:   at Array.forEach (native)
Jan 17 16:28:02 chat snap[28664]:   at Function._.each._.forEach (packages/underscore.js:139:11)
Jan 17 16:28:02 chat snap[28664]:   at AccountsServer.Ap.insertUserDoc (/snap/rocketchat-server/398/programs/server/packages/accounts-base.js:1729:5)
Jan 17 16:28:02 chat snap[28664]:   at AccountsServer.<anonymous> (/snap/rocketchat-server/398/programs/server/app/app.js:163:23)
Jan 17 16:28:02 chat snap[28664]:   at AccountsServer.insertUserDoc (packages/underscore.js:797:22)
Jan 17 16:28:02 chat snap[28664]:   at _createUser (/snap/rocketchat-server/398/programs/server/packages/accounts-password.js:1024:25)
Jan 17 16:28:02 chat snap[28664]:   at AccountsServer.Accounts.createUser (/snap/rocketchat-server/398/programs/server/packages/accounts-password.js:1088:10)
Jan 17 16:28:02 chat snap[28664]:   at [object Object].<anonymous> (/snap/rocketchat-server/398/programs/server/packages/rocketchat_importer-slack.js:280:39)
Jan 17 16:28:02 chat snap[28664]:   at packages/dispatch_run-as-user.js:211:14
Jan 17 16:28:02 chat snap[28664]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jan 17 16:28:02 chat snap[28664]:   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
Jan 17 16:28:02 chat snap[28664]:   at /snap/rocketchat-server/398/programs/server/packages/rocketchat_importer-slack.js:258:29
Jan 17 16:28:02 chat snap[28664]:   at /snap/rocketchat-server/398/programs/server/packages/rocketchat_importer-slack.js:334:15
Jan 17 16:28:02 chat snap[28664]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
Jan 17 16:28:02 chat snap[28664]:   at packages/meteor.js:445:45
Jan 17 16:28:02 chat snap[28664]:   at runWithEnvironment (packages/meteor.js:1176:24)
`

**Comment by graywolf336** [comment]
@axeloz Seems like you have domain validation enabled, as the import is failing because of `[error-invalid-domain]`. Turn it off and try again.

**Comment by axeloz** [comment]
Nice thanks. Could you please tell me how to disable domain validation?

**Comment by graywolf336** [comment]
Try to go to `Admin -> Accounts` and then scroll down and set `Use Default Blocked Domains List` to false and see if the import works?

**Comment by axeloz** [comment]
Yes sorry, just found it. I didn't get it was about the email domain validation. This error is a little bit misleading. Thank you for pointing me to the right direction.

**Comment by engelgabriel** [comment]
@graywolf336 how can we make the error more clear? Or should the import by-pass the domain validation? (my opinion is that it should).

**Comment by axeloz** [comment]
@engelgabriel agreed, this setting should be ignored

**Comment by engelgabriel** [comment]
@RocketChat/core should this setting be ignored?

**Comment by geekgonecrazy** [comment]
That or try to alert them that there are some with invalid domains ahead of time.

**Comment by graywolf336** [comment]
I think what I will do is temporarily disable that setting and when the import is finished then set it back, unless there is another better way @RocketChat/core

**Comment by pierre-lehnen-rc** [comment]
Fixed in #8390
