### ISSUE TITLE
Error warning on the admin info page

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5635]
Rocket.Chat version: (latest)
After upgrading to 0.49.3 I've got this error on the admin info page.
<img src="https://i.imgsafe.org/f04f89caa5.png" alt="Mountain View" style="width:304px;height:228px;">

**Comment by engelgabriel** [comment]
Do you have multiple instances of Rocket.Chat running?
Is your MongoDB configured on ReplicaSET mode?

**Comment by Nemra1** [comment]
its same thing is her i have only one rc not many
![2017-01-18_205716](https://cloud.githubusercontent.com/assets/22897987/22078498/cc366d40-ddc0-11e6-8150-9cb3991fe129.png)
