### ISSUE TITLE
Allow users to disable "away" and "no longer away" sounds

### ISSUE THREAD

**Issue by maethor** [RocketChat/Rocket.Chat#5638]
To quote @ulope in #2238 

> Please, please let us disable this horrendously distracting and completely useless "ding, dong" airplane sound. We're running rocket.chat in a small team (~20 active users) and even now this sound is triggered many times an hour. I don't know how larger teams bear this.

The solution proposed in this issue was to disable « new room notifications », but we cannot do that, because we really need the new room notification for the livechat. So it would be really nice to be able to really disable "away" and "no longer away" sounds, or maybe to disable the "automatic away" feature. In fact, I am never away, I'm just running my chat in the background while working in other windows… but I am not away.

Thanks.

**Comment by sampaiodiego** [comment]
@maethor as I said on #2238 rocket.chat doesn't have "away" and "no longer away" sounds.

if you are facing it, it's a bug I cannot reproduce.. can you please give us more detail?

**Comment by maethor** [comment]
OK, that's funny :smile: 

So, it's quite simple. After some time of inactivity (I don't know, maybe 5 minutes?), my account automatically pass "away" (orange label, etc.). When it happens, I get a sound.

When I get the focus back on the window, my account automatically pass "connected" (green label), and I get this sound again.

The sound seems to be the same as the "new room" sound.

I'm using the electron app on GNU/Linux Debian, and the last version of Rocket.Chat. I have disabled "new message notifications", and I kept "new room notifications" enabled.

**Comment by sampaiodiego** [comment]
ok.. can you contact me on demo server? looks like you have some inconsistency on your subscription data. please use this link to contact me: https://demo.rocket.chat/direct/diego.sampaio

**Comment by maethor** [comment]
I just talk about this with some coworkers, and it seems I have another unexpected ding dong that they don't have. When I close the rocket chat tab, and reopen it, I have the same ding dong just after the loading.

OK, I am coming on demo.rocket.chat.

**Comment by ulope** [comment]
Just to weigh in @sampaiodiego helped me resolve this back in #2238.

In my case the culprit was somehow broken subscription data.

Running the following command in the browser console: 
`JSON.stringify(ChatSubscription.find({open:true, ls:{$exists:false}}).fetch(), null, '  ')` 
should return an empty list. If it doesn't exit and re-join the room(s) it lists and the bug should be gone.

**Comment by maethor** [comment]
Doesn't seems to be the same problem @ulope. But thanks :smile:

Big thanks to @sampaiodiego who solved it. I open a new issue #5645.
