### ISSUE TITLE
Validate meteor methods

### ISSUE THREAD

**Issue by Dandandan** [RocketChat/Rocket.Chat#564]
It seems that many methods aren't validated and don't check for permissions, valid data etc.

For example, I tried: Meteor.call('eraseRoom', RoomManager.openedRooms.cgeneral.rid) and that seems to remove the general channel.

**Comment by marceloschmidt** [comment]
Thanks for letting us know, but you could have done that on a less-destructive way, couldn't you?

**Comment by Dandandan** [comment]
Yes, I'm sorry for that.
