### ISSUE TITLE
GitLab Integration failes with "body-empty" error

### ISSUE THREAD

**Issue by DalePayman** [RocketChat/Rocket.Chat#5640]
Your Rocket.Chat version: 0.46.0

Hi,

i want to have GitLab Integration in RocketChat - so i followed your documentation here:
https://rocket.chat/docs/administrator-guides/integrations/gitlab
there are two scripts. One directly on the site and one in github.

I tryed both - but i get the same error.

If i start the curl-call from the Example i get this error message back:
`{"success":false,"error":"body-empty"}`

On Serversite this got pastet into access.log:
`X.X.X.X - - [18/Jan/2017:09:39:24 +0100] "POST /hooks/aEtYXd8fVc45Hn8G/hk52JiaHDAFtrujTFAHssSDcxd4GbjiK82SdbXwHGJumBtdT HTTP/1.1" 400 49 "-" "curl/7.43.0" "-"`

Maybe someone can test this with a newer version...

Thx!

**Comment by graywolf336** [comment]
@DalePayman I just tested with the latest version of Rocket.Chat and the latest version of the GitLab Incoming Webhook Integration in our Docs and it worked for me inside of gitlab.com:

![image](https://cloud.githubusercontent.com/assets/850391/22164508/aefdd91e-df3e-11e6-8555-daa0355dd947.png)
