### ISSUE TITLE
Change user role

### ISSUE THREAD

**Issue by axeloz** [RocketChat/Rocket.Chat#5642]
Hello, 

Using Rocket latest version : when you create a new user, the field "role" appears in the form. However, this field doesn't appear when editing a user. 
So my question is : how do you change an existing user's role?

Thanks

**Comment by engelgabriel** [comment]
This is a known issue. Since the user can have multiple roles, it the only UI built so far os inside each role ou can add and remove users from it. This is far from ideal, and it is planed to be fixed.

**Comment by rasos** [comment]
Go to the role page and click on the small icon near each role. There you can assign users to each role. Working for us, but UX could be improved by allowing to assign roles at user settings.

**Comment by mrtopf** [comment]
can I also see which roles a user has? (and here it's called "Permissions", maybe that changed recently?).

**Comment by nekohayo** [comment]
I need to mention that even when you create the user, the system actually ignores whatever role you pick, so if you create a "guest" user, it will assign it to the "users" type and not even "guest".

**Comment by MartinSchoeler** [comment]
fixed by #7309
