### ISSUE TITLE
Per-user settings for role tags

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#5643]
Your Rocket.Chat version: 0.48.1

We've disabled role tags site wide as per #2950. However, the pull request added the setting globally, even though its title was "Create global and personal settings". So this is a feature request to allow per-user overrides. Thanks in advance.

**Comment by marceloschmidt** [comment]
I agree we could add that as a personal option, though if it's disabled as a server setting, I think users should not be able to override it. I mean, users can hide if server is displaying, but user cannot display if server hides it. Agreed?

**Comment by marceloschmidt** [comment]
This has already been done
