### ISSUE TITLE
Room admin panel broken

### ISSUE THREAD

**Issue by elfrinjo** [RocketChat/Rocket.Chat#5648]
Your Rocket.Chat version: 0.49.2

For a channel or message an admin is not member of, the attached panel will be shown in the room-list.
It seems to be a default panel without delete button and the customization for direct-messages (removal of topic, type, etc.)

This was still ok in 0.48.2

![image](https://cloud.githubusercontent.com/assets/25196347/22071623/04c67cac-dda0-11e6-9f8b-82e6a7ac012c.png)

**Comment by engelgabriel** [comment]
Please upgrade to version `0.49.3`

**Comment by engelgabriel** [comment]
Please reopen if the problem still exists for you on version `0.49.3`

**Comment by elfrinjo** [comment]
Ups, sorry. That was a typo in my original post. Actually I am on 0.49.3.

The update from 0.49.2 to 0.49.3 solved the issue that the rooms table did not show "foreign" rooms but the admin panel still has some issue.
