### ISSUE TITLE
Server Side File Uploads

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#5650]
Right now the only way to upload files to the server's configured upload system (s3, file system, or database) is via the client, however we now have requirements to upload files via the server to whatever is configured for the server from features such as the importers, rest api, and slack bridge.

**Comment by Nemra1** [comment]
i hope to add upload to external ftp server like cdn server with ftp:ip@port:21@username:@password

**Comment by redgang** [comment]
i also hope to add upload to external ftp server or a file server.
Whether there is a related plan？

**Comment by ben-andersen** [comment]
We need this feature as well.  Is there any work around at the moment?

**Comment by MartinSchoeler** [comment]
@graywolf336 is this still an issue?

**Comment by graywolf336** [comment]
I don't think so. We can close it now and open it again later if we need to.
