### ISSUE TITLE
Cannot find module 'fibers' after 0.48.2 -> 0.49.3

### ISSUE THREAD

**Issue by rasathus** [RocketChat/Rocket.Chat#5659]
Whilst attempting to upgrade from 0.48.2 to 0.49.3, I've run into an issue where rocket chat will not start, and simply outputs the following ...

```
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/rocket_chat/programs/server/boot.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error: Forever detected script exited with code: 1
error: Script restart attempt #55
module.js:471
    throw err;
    ^
```

I was keen to upgrade as the current 0.48.2 install is very slow, with both instances permanently pinned at 100%.

There seem to be a number of tickets refering to issues with 'fibers', but most recommend upgrading to a version older than the currently installed 1.0.15.

After rolling back to my original system snapshot I attempted to install 0.49.2, but ran into the same issue.  Any help would be most appreciated.

Thanks

**Comment by tntobias** [comment]
@rasathus This is usually due to some failure with npm dependencies. I'd start with an `npm cache clean` followed by a `npm install` in the pathToRC/programs/server directory. Make sure you're at NodeJS 4.7.1 (a new requirement for 0.49+) and npm 3 or better.

**Comment by engelgabriel** [comment]
How are you deploying? Are you building from source?  @rasathus is right, this is usually a NPM install or update missing.

**Comment by rasathus** [comment]
I've just updated npm to 4.0.5 , purged the npm cache and it seems to have deployed successfully. 

```
> fibers@1.0.15 install /opt/rocket_chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-48` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /opt/rocket_chat/programs/server
meteor-dev-bundle@0.0.0 /opt/rocket_chat/programs/server
├── amdefine@1.0.1 
├── asap@2.0.5 
├─┬ chalk@0.5.1 
│ ├── ansi-styles@1.1.0 
│ ├── escape-string-regexp@1.0.5 
│ ├─┬ has-ansi@0.1.0 
│ │ └── ansi-regex@0.2.1 
│ ├── strip-ansi@0.3.0 
│ └── supports-color@0.2.0 
├─┬ eachline@2.3.3 
│ └── type-of@2.0.1 
├── fibers@1.0.15 
├── meteor-promise@0.8.0 
├── promise@7.1.1 
├── semver@4.1.0 
├── source-map@0.1.32 
├── source-map-support@0.3.2 
└── underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
```

And rocket chat now runs up.  I've still got the 100% cpu issues I was see'ing before, but I'll join the other ticket for that.

Thanks for the help
