### ISSUE TITLE
Upload via GridFS broken

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#5661]
Your Rocket.Chat version: 0.50.0-develop  latest 

Can no longer upload images via drag and drop
![screen shot 2017-01-18 at 9 32 43 pm](https://cloud.githubusercontent.com/assets/122633/22091776/bfce42e8-ddc6-11e6-9ae8-30e2fcaa99d8.png)
, see screen capture:

**Comment by Sing-Li** [comment]
This might be the problem - `localhost` :

![screen shot 2017-01-18 at 10 45 18 pm](https://cloud.githubusercontent.com/assets/122633/22092999/fa3d361a-ddcf-11e6-986a-ef9335c6fa02.png)

**Comment by Sing-Li** [comment]
Tested on 0.49.3 - same problem.

**Comment by TheReal1604** [comment]
Its working for me on my 2 Setups with 0.49.3 but i get the same as shown above from @Sing-Li 

![image](https://cloud.githubusercontent.com/assets/5877910/22097237/52b421fa-de20-11e6-8fdf-caa79dd69eb1.png)

**Comment by Sing-Li** [comment]
Fixed on the latest HEAD (edge snap).   So I'm closing this for now.  If anyone else see this problem, please reopen or post follow-ups.
