### ISSUE TITLE
Cannot mention users

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#5662]
Your Rocket.Chat version: 0.49.3

In the latest version of Rocket.Chat, I am getting a strange issue where I cannot mention some members in a room. When I type in a person's username, it doesn't appear in search. But if I correctly type in the full name, in the chat message it appears like a mention. 
Didn't see anything in permissions that influence this. Could this be a bug with the latest release?

**Comment by karlprieb** [comment]
Hi @akachapati did you have erros on your console?

**Comment by akachapati** [comment]
Here are a few things I noticed.
If I am logged in as an administrator, I am able pull up everyone in the room when mentioning someone. So for example @username pulls up all matching users as I fill in the term. 
When I am logged in to the same room as a normal user, I am not able to tag some of the users. But strangely, once they come online, I am able to search, tag them again. 

Could this be related to caching? Anybody else seeing this problem?

There's nothing in the log either.

**Comment by rodrigok** [comment]
@akachapati Can you send us a screen shoot of your permissions page?

**Comment by rodrigok** [comment]
I tried locally and can't reproduce this behavior

**Comment by akachapati** [comment]
@rodrigok Thank you for looking into this. Screenshot is attached.

Please try following steps to recreate the issue
1) Add a new user to your server, set email as verified. Add said user to a room
2) Log in as a regular user, go to same room
3) Try to mention the newly added user who's yet to log in. When you hit @[username] the search box doesn't pop up with suggestions 
<img width="450" alt="permissions" src="https://cloud.githubusercontent.com/assets/4548294/22134928/e752b178-def2-11e6-98ef-31107af5b4f2.png">

In the screenshot, the admin and regular user roles are shown in arrow

**Comment by rodrigok** [comment]
Users should have permission `view-d-room` to be able to mention other users

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/publications/spotlight.coffee#L12-L13

I'll close this issue, please reopen it if the problem persists.

**Comment by akachapati** [comment]
Thanks @rodrigok
