### ISSUE TITLE
Capital letters change to small letters after editing room name

### ISSUE THREAD

**Issue by j-ew-s** [RocketChat/Rocket.Chat#567]
Follow the steps:

1 - Create a new room whit at least  one capital letter EX: Developing_For_Soup
2 - Access and edit the room name  adding a new text EX: Developing_For _Soup_Bauru

The result will be  developing-for-soup-bauru
* All the capital letters now are small 
* All the underscore are now dash

**Comment by rodrigok** [comment]
Thanks, room names must be always lowercase.

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/571917cfbd65143cdb04f2cceed1dd9a513bed84
