### ISSUE TITLE
Mocha failed

### ISSUE THREAD

**Issue by pachox** [RocketChat/Rocket.Chat#5674]
Version: 0.50.0-develop 
i'm running TEST_MODE=true meteor, then in another shell meteor npm run chimp-test

it fails with:
  242 passing (4m)
  65 pending
  15 failing
Mocha failed

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "chimp-test"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! Rocket.Chat@0.50.0-develop chimp-test: `chimp tests/chimp-config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Rocket.Chat@0.50.0-develop chimp-test script 'chimp tests/chimp-config.js'.
npm ERR! This is most likely a problem with the Rocket.Chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     chimp tests/chimp-config.js

In travis same result with npm test.

see debug log attached.
thank you
[npm-debug.txt](https://github.com/RocketChat/Rocket.Chat/files/717301/npm-debug.txt)

**Comment by MartinSchoeler** [comment]
@pachox could you show me the tests that failed? The errors with numbers, like this : 
```
1) Admin Login Admin view users should show rocket.cat:
     AssertionError: expected false to be true
      at doAsserterAsyncAndAddThen (node_modules/chimp/node_modules/chai-as-promised/lib/chai-as-promised.js:293:29)
      at null.<anonymous> (node_modules/chimp/node_modules/chai-as-promised/lib/chai-as-promised.js:283:21)
      at null.Object.defineProperty.get (node_modules/chimp/node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Context.<anonymous> (tests/end-to-end-ui/11-admin.js:215:5)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```

**Comment by pachox** [comment]
here you go.
thanks a lot.

 1) Main Elements Render side nav bar render should show the new channel button:
     AssertionError: expected false to be true
  

  2) Main Elements Render side nav bar render should show the plus icon:
     AssertionError: expected false to be true
  

  3) Main Elements Render side nav bar render should show the new direct message button:
     AssertionError: expected false to be true
  

  4) Main Elements Render side nav bar render should show the plus icon:
     AssertionError: expected false to be true
  

  5) Channel creation create a public channel create a public channel:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:46:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  6) Channel creation create a private channel create a private channel:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:53:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  7) Channel creation direct channel start a direct message with rocket.cat:
     Error: element (.rooms-list .add-room:nth-of-type(2)) still not visible after 3000ms
      at SideNav.startDirectMessage (tests/pageobjects/side-nav.page.js:89:28)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:60:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

 8) Messaging in different channels Messaging in GENERAL channel fileUpload should show the file in the message:
     Error: element (.message:last-child .body .attachment-description p) still not visible after 10000ms
      at Context.<anonymous> (tests/steps/06-messaging.js:90:32)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  9) Messaging in different channels Messaging in created public channel "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/06-messaging.js:285:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  10) Messaging in different channels Messaging in created private channel "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/06-messaging.js:299:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  11) Messaging in different channels Messaging in created direct message "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(2)) still not visible after 3000ms
      at SideNav.startDirectMessage (tests/pageobjects/side-nav.page.js:89:28)
      at Context.<anonymous> (tests/steps/06-messaging.js:313:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  12) channel usage "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/09-channel.js:17:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  13) Admin settings test the permissions when clicked should not show the new channel name input :
     Error: An element could not be located on the page using the given search parameters.
      at Context.<anonymous> (tests/steps/12-admin-settings.js:127:26)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  14) Admin settings test the permissions when clicked should not show the new direct message user input :
     Error: An element could not be located on the page using the given search parameters.
      at Context.<anonymous> (tests/steps/12-admin-settings.js:136:32)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

**Comment by pachox** [comment]
here you can find a travis session too:
https://travis-ci.org/pachox/Rocket.Chat/builds/193206070

**Comment by engelgabriel** [comment]
@pachox you have removed the env variables

```
env:
  global:
  - MONGO_OPLOG_URL: "mongodb://localhost:27017/local"
  - MONGO_URL: "mongodb://localhost:27017/meteor"
  - TEST_MODE: "true"
```

So you are using the Meteor internal DB, and it is being cached between builds...

You need to put the variables back, or do a `meteor reset` before starting your tests.

**Comment by pachox** [comment]
they are there, look:
**From Travis:**
 "global_env": "DISPLAY=:99.0 CXX=g++-4.8 HrPOM5sBibYkMcf9aeQThYPCDiXeLkg0Xgv0HvH88/ku/gphDpNEjHNReHZM3cyfm9y3RhHpVdD+Zzy38S2goKyewRzpXJsuyerOYkjND0v3tivhs9CAX8PAUxj1U5zllTyH4bgW2ZwRtNnwnmtIM/JJlnySMpKVDqIZBpbhn3ph9bJ2J+BW3D3Jw8meQ1vCX8szIibyJK/5QX6HG2RBFXJGYoQ8DmR8jQv0aJQvT1Az5DO4yImk8tX4NP95qOc19Jywr1DsbaSBZeJ8lFJAmBpIGx7KAmUVCcxSxfbXGRhs2K4iEYb3rJ/dU6KiyPsKGUG4aYNGgbvcX0ZxX/BZ6ZU9ff0E4IIf43IxoN3ElrOqOFk5msJAXbrJEreINSzDqKOy8NFYtCQ49E2gwzfage4ZXkhFyx3wMPa5bzpr3ncsTceMjMVz03uL781X6NLuCkUmXv+n8K2MNhJU9Xinpdx1GRJm+0lXJspNNJ1ruHeJtls4epj4bmCwKmmZbFKPXqa5e8xVcMIkwt1LMiHduhE+WgKNHdOMhXrCcTxF62ybLlsHXmyLLJeNjTeKS8QG2XSoonClDAz/1R41I1DsMPblcgz9uvYCf7UtyftbhJ83bnJeEmOYQiwijLG0+QMq+B2+mmZan3Z7Hl7O53dnwuLxz7EO7EhQhY+CqHVgc6s=[secure] **_MONGO_OPLOG_URL=mongodb://localhost:27017/local MONGO_URL=mongodb://localhost:27017/meteor TEST_MODE=true_** COMMIT=${TRAVIS_COMMIT::8}

**My ows .travis.yml:**
env:
  global:
  - DISPLAY=:99.0
  - CXX=g++-4.8
  - secure: HrPOM5sBibYkMcf9aeQThYPCDiXeLkg0Xgv0HvH88/ku/gphDpNEjHNReHZM3cyfm9y3RhHpVdD+Zzy38S2goKyewRzpXJsuyerOYkjND0v3tivhs9CAX8PAUxj1U5zllTyH4bgW2ZwRtNnwnmtIM/JJlnySMpKVDqIZBpbhn3ph9bJ2J+BW3D3Jw8meQ1vCX8szIibyJK/5QX6HG2RBFXJGYoQ8DmR8jQv0aJQvT1Az5DO4yImk8tX4NP95qOc19Jywr1DsbaSBZeJ8lFJAmBpIGx7KAmUVCcxSxfbXGRhs2K4iEYb3rJ/dU6KiyPsKGUG4aYNGgbvcX0ZxX/BZ6ZU9ff0E4IIf43IxoN3ElrOqOFk5msJAXbrJEreINSzDqKOy8NFYtCQ49E2gwzfage4ZXkhFyx3wMPa5bzpr3ncsTceMjMVz03uL781X6NLuCkUmXv+n8K2MNhJU9Xinpdx1GRJm+0lXJspNNJ1ruHeJtls4epj4bmCwKmmZbFKPXqa5e8xVcMIkwt1LMiHduhE+WgKNHdOMhXrCcTxF62ybLlsHXmyLLJeNjTeKS8QG2XSoonClDAz/1R41I1DsMPblcgz9uvYCf7UtyftbhJ83bnJeEmOYQiwijLG0+QMq+B2+mmZan3Z7Hl7O53dnwuLxz7EO7EhQhY+CqHVgc6s=
  **- MONGO_OPLOG_URL: mongodb://localhost:27017/local
  - MONGO_URL: mongodb://localhost:27017/meteor
  - TEST_MODE: 'true'**

**Comment by pachox** [comment]
I've tried a meteor reset too, still no joy:

109 passing (8m)
  63 pending
  40 failing

  1) User Creation create user:
     Error: An element could not be located on the page using the given search parameters.
      at LoginPage.gotToRegister (tests/pageobjects/login.page.js:26:23)
      at Context.<anonymous> (tests/steps/03-user-creation.js:49:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  2) Main Elements Render side nav bar render should show the new channel button:
     AssertionError: expected false to be true
  

  3) Main Elements Render side nav bar render should show the plus icon:
     AssertionError: expected false to be true
  

  4) Main Elements Render side nav bar render should show the new direct message button:
     AssertionError: expected false to be true
  

  5) Main Elements Render side nav bar render should show the plus icon:
     AssertionError: expected false to be true
  

  6) Channel creation create a public channel create a public channel:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:46:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  7) Channel creation create a private channel create a private channel:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:53:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  8) Channel creation direct channel start a direct message with rocket.cat:
     Error: element (.rooms-list .add-room:nth-of-type(2)) still not visible after 3000ms
      at SideNav.startDirectMessage (tests/pageobjects/side-nav.page.js:89:28)
      at Context.<anonymous> (tests/steps/05-channel-creation.js:60:12)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  9) Messaging in different channels Messaging in GENERAL channel fileUpload should show the file in the message:
     Error: element (.message:last-child .body .attachment-description p) still not visible after 10000ms
      at Context.<anonymous> (tests/steps/06-messaging.js:90:32)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  10) Messaging in different channels Messaging in GENERAL channel Message actions Message Actions usage Message star "before all" hook:
     Error: Promise was rejected with the following reason: timeout
      at MainContent.sendMessage (tests/pageobjects/main-content.page.js:71:11)
      at Context.<anonymous> (tests/steps/06-messaging.js:230:18)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  11) Messaging in different channels Messaging in created public channel "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/06-messaging.js:285:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  12) Messaging in different channels Messaging in created private channel "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(1)) still not visible after 10000ms
      at SideNav.createChannel (tests/pageobjects/side-nav.page.js:56:22)
      at Context.<anonymous> (tests/steps/06-messaging.js:299:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  13) Messaging in different channels Messaging in created direct message "before all" hook:
     Error: element (.rooms-list .add-room:nth-of-type(2)) still not visible after 3000ms
      at SideNav.startDirectMessage (tests/pageobjects/side-nav.page.js:89:28)
      at Context.<anonymous> (tests/steps/06-messaging.js:313:13)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14

  14) emoji render should show the emoji picker menu:
     unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  Error: unknown error: session deleted because of page crash
      at MainContent.get (tests/pageobjects/main-content.page.js:45:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:29:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      from unknown error: cannot determine loading status
      from tab crashed

  15) emoji render click the emoji picker people tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:46:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:33:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  16) emoji render should show the emoji picker people tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:46:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:37:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  17) emoji render should show the emoji picker nature tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:47:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:41:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  18) emoji render should show the emoji picker food tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:48:45)
      at Context.<anonymous> (tests/steps/07-emoji.js:45:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  19) emoji render should show the emoji picker activity tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:49:49)
      at Context.<anonymous> (tests/steps/07-emoji.js:49:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  20) emoji render should show the emoji picker travel tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:50:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:53:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  21) emoji render should show the emoji picker objects tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:51:48)
      at Context.<anonymous> (tests/steps/07-emoji.js:57:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  22) emoji render should show the emoji picker symbols tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:52:48)
      at Context.<anonymous> (tests/steps/07-emoji.js:61:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  23) emoji render should show the emoji picker flags tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:53:46)
      at Context.<anonymous> (tests/steps/07-emoji.js:65:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  24) emoji render should show the emoji picker custom tab:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:56:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:69:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  25) emoji render should show the emoji picker change tone button:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:55:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:73:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  26) emoji render should show the emoji picker search bar:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:58:43)
      at Context.<anonymous> (tests/steps/07-emoji.js:77:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  27) emoji render "after all" hook:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:61:36)
      at Context.<anonymous> (tests/steps/07-emoji.js:24:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  28) emoji usage send emoji via screen "before all" hook:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:14:34)
      at Context.<anonymous> (tests/steps/07-emoji.js:84:5)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  29) emoji send emoji via text adds emoji text to the message input:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:6:38)
      at MainContent.addTextToInput (tests/pageobjects/main-content.page.js:77:3)
      at Context.<anonymous> (tests/steps/07-emoji.js:110:16)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  30) emoji send emoji via text should show the emoji popup bar:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:62:38)
      at Context.<anonymous> (tests/steps/07-emoji.js:114:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  31) emoji send emoji via text the emoji popup bar title should be emoji:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:63:43)
      at Context.<anonymous> (tests/steps/07-emoji.js:118:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  32) emoji send emoji via text should show the emoji popup bar items:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:64:43)
      at Context.<anonymous> (tests/steps/07-emoji.js:122:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  33) emoji send emoji via text click the first emoji on the popup list:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:65:47)
      at Context.<anonymous> (tests/steps/07-emoji.js:126:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  34) emoji send emoji via text the value on the message input should be the same as the emoji clicked:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:6:38)
      at Context.<anonymous> (tests/steps/07-emoji.js:130:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  35) emoji send emoji via text send the emoji:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:7:33)
      at Context.<anonymous> (tests/steps/07-emoji.js:134:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  36) emoji send emoji via text the value on the message should be the same as the emoji clicked:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at MainContent.get (tests/pageobjects/main-content.page.js:24:37)
      at Context.<anonymous> (tests/steps/07-emoji.js:138:4)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  37) channel usage "before all" hook:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at SideNav.get (tests/pageobjects/side-nav.page.js:14:44)
      at checkIfUserIsValid (tests/data/checks.js:22:7)
      at Context.<anonymous> (tests/steps/09-channel.js:15:3)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  38) Admin Login "before all" hook:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at SideNav.get (tests/pageobjects/side-nav.page.js:14:44)
      at checkIfUserIsAdmin (tests/data/checks.js:55:7)
      at Context.<anonymous> (tests/steps/11-admin.js:14:3)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  39) Admin Login "after all" hook:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at SideNav.get (tests/pageobjects/side-nav.page.js:41:42)
      at Context.<anonymous> (tests/steps/11-admin.js:20:3)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)

  40) Admin settings "before all" hook:
     no such session
  (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)
  Error: no such session
      at SideNav.get (tests/pageobjects/side-nav.page.js:14:44)
      at checkIfUserIsAdmin (tests/data/checks.js:55:7)
      at Context.<anonymous> (tests/steps/12-admin-settings.js:16:3)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
      (Driver info: chromedriver=2.27.440196 (3b42f4145a4fd223b41f39bb38aaf90508be7a96),platform=Linux 3.16.0-4-686-pae x86)



Mocha failed

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/home/pacho2/.meteor/packages/meteor-tool/.1.4.2_3.mea2r9++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node" "/home/pacho2/.meteor/packages/meteor-tool/1.4.2_3/mt-os.linux.x86_32/dev_bundle/bin/npm" "run" "chimp-test"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! Rocket.Chat@0.50.0-develop chimp-test: `chimp tests/chimp-config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Rocket.Chat@0.50.0-develop chimp-test script 'chimp tests/chimp-config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Rocket.Chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     chimp tests/chimp-config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Rocket.Chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Rocket.Chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pacho2/Rocket.Chat/npm-debug.log
pacho2@meteor:~/Rocket.Chat$
