### ISSUE TITLE
Reset permissions after testing 

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#5678]
Sometimes when you finish a test the permissions dont go back to their default state thus making some of the next tests fail

**Comment by Kiran-Rao** [comment]
The real solution to this would be setting up db mocks for each test. That way, each test will operate with a mock database containing only the components required. It will not only solve this problem, but this whole class of problems in the future.

**Comment by engelgabriel** [comment]
@Kiran-Rao we are creating the mock data for the new unit tests, but the end-to-end test we want to run on a empty db as a fresh install.
