### ISSUE TITLE
How to Get Involved?

### ISSUE THREAD

**Issue by ilrein** [RocketChat/Rocket.Chat#568]
Just saw this post: https://crater.io/posts/RN7JY9bY4ixDsQT3u/gitlab-7-14-released-bundling-of-mattermost-now-possibly

Currently working full time as a dev, but MeteorJS is my passion -- I'd love to be a part of the team.

**Comment by rodrigok** [comment]
Hi @ilrein, we are glad with your interest.

You can look the opened issues and pick up some that you want to do, only, comment in the issue saying that you are working so we can mark the issue with label "In Progress".

Thanks

**Comment by rodrigok** [comment]
Any doubt feel free to reopen this issue.
