### ISSUE TITLE
what is command line to build from developer version !

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5680]
Your Rocket.Chat version: (lastest)
Today  finaly i'm finished from edit Custom Rocket Chat Version and iwant release The Finaly Version but idont know how !
 Example : http://192.168.1.10:3000
how to build ?

**Comment by graywolf336** [comment]
Checkout out [.travis.yml](https://github.com/RocketChat/Rocket.Chat/blob/develop/.travis.yml) or look at [meteor's documentation](https://docs.meteor.com/commandline.html#meteorbuild).

**Comment by Nemra1** [comment]
@graywolf336 Thank u ..im found this script ./build.sh is working
