### ISSUE TITLE
can't delete uploaded file even if Admin side

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5682]
Rocket.Chat version: (latest)
<img src="https://i.imgsafe.org/18225cf68f.gif">

**Comment by Kiran-Rao** [comment]
What are your current permission settings?

**Comment by zorenleo** [comment]
@Kiran-Rao this is my current permission settings
<img src="https://i.imgsafe.org/1a2ecd148a.png">

**Comment by graywolf336** [comment]
Is that your own message or someone else's?

**Comment by graywolf336** [comment]
The fix has been submitted as a pull request. This was only happening when trying to delete others messages which contained files. It would delete the message but would error out at removing the file.
