### ISSUE TITLE
nodejs 6.9.2

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#5684]
Your Rocket.Chat version: 0.49.3

Hello Devs.

To my big surprise rocketchat is running fine with nodejs 6.9.2. Do you recommend running rocketchat with that nodejs version?

thanks and cheers

**Comment by engelgabriel** [comment]
Hi, we need to follow Meteor JS recommendation, as this is the framework we use, so `4.7.0` 😄
