### ISSUE TITLE
This is not working

### ISSUE THREAD

**Issue by vallabh-linux** [RocketChat/Rocket.Chat#5685]
Your Rocket.Chat version: (make sure you are running the latest)
Trying to setup with camera logitech C310 but on production (Ubuntu 16) Rocketchat meteor command is not working.Its not showing option to setup or install after login through monitoring user in location room at installed camera machine.

**Comment by graywolf336** [comment]
Sorry, but I don't understand the problem. If you need support for Rocket.Chat's usage, please join us on the community server's [#support channel](https://demo.rocket.chat/channel/support).
