### ISSUE TITLE
iOS & Android App not refreshing channels until you close and reopen de App

### ISSUE THREAD

**Issue by rccerezuela** [RocketChat/Rocket.Chat#5686]
Your Rocket.Chat version: (make sure you are running the latest)

**Comment by engelgabriel** [comment]
Hi @rccerezuela, when opening an issues, you need to give more info, as it is working for the rest of us, so without any info we won't be able to help you.

You must list the server version, number of instances, mongodb version, replicaset mode, mobile app platform and version too.
