### ISSUE TITLE
Zoom Resets.

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat#5688]
Rocket.Chat server version: (0.49.3)
Number of instances: (4)
MongoDB in Replicaset mode: (yes)

The issue in question is a bug when a user zoom out to make the text smaller so that they can fit more text on screen utilising screen space better, this is fine for every channel apart from the general channel, if a user visits the general channel their zoom level resets to its original value. I can replicate it every time, I have reason to believe this happens when it hits a cached video.

**Comment by engelgabriel** [comment]
I can confirm that a YouTube video preview triggers the zoom reste.

**Comment by engelgabriel** [comment]
It only happens on Electron, and I think it has something to do with the old version of jQuery there.

**Comment by engelgabriel** [comment]
@oliver-bowman i'll close this issue here and keep https://github.com/RocketChat/Rocket.Chat.Electron/issues/165
