### ISSUE TITLE
Client zoom keys the opposite way to be expected.

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat#5689]
Rocket.Chat server version: (make sure you are running the latest)
Number of instances: (you can see this on the admin/info)
MongoDB in Replicaset mode: (yes/no)

Testing it on the latest version of the client on multiple OS's (OSX & Linux) the zoom keys appear to do the opposite action. The + key zooms out and the - zooms. This effects multiple users within my company.

**Comment by engelgabriel** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat.Electron/commit/4f361bc33fa2d79044c03e3c84b4027d0716d4ca
