### ISSUE TITLE
Browser has to be refreshed to see new messages.

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#5693]
Rocket.Chat server version: (0.49.3)
Number of instances: (8) Currently 4
MongoDB in Replicaset mode: (yes)

After the upgrade to 0.49.3 users started to contact me on the message refresh of the clients. That is users would send a message and no one would see it unless they refreshed the browser. Because of the number of users I had I was not able to go down to 1 instance and try it to see if it had something to do with users being on separate instances.  On a direct message the user will get the notification on their mobile and win desktop but the RC screen would not show the message (you could see the user status of typing). This was all working fantastic on 48.1 until I upgraded to 0.49.3. I'm now getting a message in the administration info screen stating Oplog should be enabled when running multiple instances. Its been awhile but I had set this up when I did my initial mongodb setup. Maybe I missed something there. 
One other message in the exception log that I hadn't seen before when starting RC instances:
Stream Error: Network error: ws://localhost:3003/websocket: connect ECONNREFUSED 127.0.0.1:3003
I get this for each RC instance I start.

So current status is all users have to refresh the system in-order to see their messages.
Any help would be appreciated. 
One last thing is there an issue going back to 0.48.1 after the upgrade to 0.49.3. I may have to if I'm not able to fix this problem.

**Comment by vitamindck** [comment]
I had a similar problem a long time ago when transitioning from 0.35 to 0.4x in a high availability setup. I needed to set the INSTANCE_IP environment variable for rocketchat and that solved the problem. This doesn't sound like the same issue but it's similar and probably worth checking.

https://github.com/RocketChat/Rocket.Chat.Docs/issues/87

**Comment by drickerusa** [comment]
Thanks @vitamindck I do have INSTANCE_IP in my config. As I mentioned above this just started after I upgraded last night. Of course I didn't see the issue until a lot of people started to use the system. I'm pulling my hair out trying to figure out if the latest version is incompatible with previous config settings that worked under 0.48.1

**Comment by rodrigok** [comment]
@drickerusa Is your MongoDB running with OpLog/ReplicaSet enabled?

**Comment by drickerusa** [comment]
Here is the oplog status using rs.printReplicationInfo()
configured oplog size:   10240MB
log length start to end: 9257541secs (2571.54hrs)
oplog first event time:  Wed Oct 05 2016 11:00:08 GMT-0600 (MDT)
oplog last event time:   Fri Jan 20 2017 13:32:29 GMT-0700 (MST)
now:                     Fri Jan 20 2017 13:32:29 GMT-0700 (MST)

Am I missing something here?

**Comment by rodrigok** [comment]
@drickerusa No, sorry, I missed this info on your first message.

Can you paste here the first lines of your logs? Including the `SERVER RUNNING` box.

**Comment by engelgabriel** [comment]
@drickerusa or can you send a screenshot of your `admin/info` page?

**Comment by drickerusa** [comment]
I was able to get the oplog config to work properly. I no longer get the notification in the administration info screen. Right now I'm checking with my users to see if they are still having refresh the screen to get messages issue. I'll let you know in a few.

**Comment by drickerusa** [comment]
@engelgabriel @rodrigok Since I have changed all the config for each instance with and updated and working oplog entry I have not received any feedback on issues with refreshes. So far everything seems to be working. I'm still a little puzzled why this worked fine under 0.48.1. Thanks for your help.

**Comment by engelgabriel** [comment]
Version 0.49.x introduced a cache layer for performance, and that depends on the OpLog to sync multiple instances. Keeps us informed, thanks.

**Comment by HoldOffHunger** [comment]
This is still an issue, in 2021.

**Comment by sumitsrv** [comment]
I am facing the same issue, however, I have a single instance deployment of the latest version (4.8.1) of Rocket Chat. 

Server: Ubuntu 20.04 (Behind a proxy)
Browser: Firefox, Chrome

Any suggestions about what could be the potential issue?

**Comment by reihsr** [comment]
We have the same problem after updating from an old version to 4.8.2
Server: K8s cluster
All client apps (Windows, Mac, Linux)

**Comment by sumitsrv** [comment]
> We have the same problem after updating from an old version to 4.8.2 (single instance) Server: K8s cluster All client apps (Windows, Mac, Linux)

I completely removed the existing installation and re-installed 4.8.3 and it has started to work. I am not sure if that is a possibility for you. In any case, if the situation changes going forward, I will update.

This seems to be a recurring issue across versions. As far as Github open issues are concerned, I see this issue popping up in older versions as well and then suddenly it goes off.
