### ISSUE TITLE
Permanent Badge Notification after upgrade

### ISSUE THREAD

**Issue by jprone** [RocketChat/Rocket.Chat#5697]
Rocket.Chat Version: 0.49.3
Running Instances:  1
DB Replicaset OpLog: Disabled
Node Version: 4.6.2

I have a permanent badge notification after upgrading to Rocket.Chat Version 0.49.3  
![screen shot 2017-01-20 at 10 20 49 am](https://cloud.githubusercontent.com/assets/13991449/22160400/25a5ec18-defa-11e6-818e-900203895fc9.png)
![screen shot 2017-01-20 at 10 21 15 am](https://cloud.githubusercontent.com/assets/13991449/22160414/349e67ea-defa-11e6-9c66-717be6dba029.png)

Reinstalling changes nothing.

**Comment by engelgabriel** [comment]
What version of the desktop client are you using?

**Comment by jprone** [comment]
Version 2.2.2 (2.2.2.222)

**Comment by engelgabriel** [comment]
What do you see when you open the browser web client? Does it also say you have 1 message?

**Comment by jprone** [comment]
![screen shot 2017-01-20 at 12 46 48 pm](https://cloud.githubusercontent.com/assets/13991449/22165017/90134d20-df0e-11e6-82a5-3ef1a1a2da3b.png)
Yes, with all browsers (Chrome, Firefox, Safari).

**Comment by engelgabriel** [comment]
And are you sure you have not closed a channel/group that you do have an unread message?

You can press Shift+Esc to clear them all.

**Comment by jprone** [comment]
Wow!  That simple.  That did fix the concern on my end in all instances (browser, OS X App, iOS)

**Comment by jprone** [comment]
> you have not closed a channel/group that you do have an unread message?

That was more than likely the reason, because we did recreate all the channels/groups from our previous installation.  

I truly appreciate the response.

**Comment by k0nsl** [comment]
I've got the same issue as well on the same version of Rocket.Chat.

**Comment by engelgabriel** [comment]
@k0nsl press Shift+Esc to clear them all.

**Comment by k0nsl** [comment]
@engelgabriel: I mean in my browser, not the desktop client. Very annoying. I simply deactivated `Unread Alert` in my account profile for now.
