### ISSUE TITLE
GitHub login fails to get primary email

### ISSUE THREAD

**Issue by dmlittle** [RocketChat/Rocket.Chat#57]
When trying to login with a GitHub account, an alert saying "You don't have any email as public email in your GitHub account" pops up.

**Comment by engelgabriel** [comment]
Did you configured your primary email to be public?

**Comment by dmlittle** [comment]
Yes.
![](https://cloud.githubusercontent.com/assets/3803621/7903279/29de15bc-079c-11e5-8da8-dc8c42c03335.png)

**Comment by rodrigok** [comment]
@dmlittle I understand, this it is a little bit confusing :(

You need to go to your "Profile" and after the input with your name exists another input to select which email you want use as public email, the default value is "none".

**Comment by engelgabriel** [comment]
@dmlittle did you understand?
