### ISSUE TITLE
Improvement: Threads

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#5704]
Just released at Slack: Threads.
You can start a Thread on any post:
![Start Thread](https://cloud.githubusercontent.com/assets/193273/22165948/c611defa-df5e-11e6-8e75-e63e04020a77.PNG)
You may select notification for full channel or just Thread internal
![Reply](https://cloud.githubusercontent.com/assets/193273/22165959/d74697b0-df5e-11e6-8b1f-2f9c859a8f34.PNG)
You may select the notification option on each reply
![Notification option](https://cloud.githubusercontent.com/assets/193273/22165985/0096e85e-df5f-11e6-9fbb-955132c0f3da.PNG)
Replies are hidden by default
![Hidden replies](https://cloud.githubusercontent.com/assets/193273/22166070/70ed721c-df5f-11e6-860f-011fa8b7809f.PNG)

**Comment by engelgabriel** [comment]
Dup of #1112 👍
