### ISSUE TITLE
Update Rocket.Chat

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#5705]
Rocket.Chat Version:  0.49.3
Running Instances: 1

I am trying to find information on how to update Rocket Chat.  I see 0.49.4 was released but my info still shows 0.49.3.  I deployed using SNAP.  Could someone let me know how to update or will it automatically update?  Is there the ability to upgrade manually?

Thank you,
David

**Comment by engelgabriel** [comment]
Aaron, can ou check the snap building process?

**Comment by dmkjr** [comment]
@engelgabriel Thank you.  I believe it has auto updated in the past.  I only deployed about a week ago, but I don't see an option to upgrade... assumed it was automatic.  Not sure if I need to do something to trigger an upgrade.

Thx,
David

**Comment by geekgonecrazy** [comment]
@dmkjr can you check again?  Snaps auto update usually with in 3-4 hours of being released.  I think can be up to 6 hours.  I can confirm 0.49.4 has definitely been released into the snap stable channel.

If you haven't gotten the update and need the update sooner you can run: `sudo snap refresh rocketchat-server` this will force it to check.

**Comment by dmkjr** [comment]
Let me check.  I just checked the /info screen.  I'll pull it up once again.

**Comment by dmkjr** [comment]
@geekgonecrazy The refresh snap command worked.  I'm not sure when you released the 0.49.4 but I originally posted 4 hours ago and saw it released a few hours before then.  I'm on a Droplet from DO, NY3.

**Comment by geekgonecrazy** [comment]
@dmkjr I'm not sure the exact timing involved in the snap auto update.  I'll try and get exact numbers and add to our FAQ.
