### ISSUE TITLE
Navigating to a Channel that doesn't exists only shows loading screen

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#571]
Pretty much the title. When I manually type in a channel name in the url which I know doesn't exist causes the application to load but gets stuck at the loading screen. The use case I imagine this happening is if a user bookmarks the page and they're in a channel which later gets deleted.

**Comment by rodrigok** [comment]
What do you suggest? Send user to /home?

**Comment by graywolf336** [comment]
I'm thinking a channel/group/user not found page along with a link to home.
