### ISSUE TITLE
Wordpress Integration

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#5710]
Rocket.Chat Version: 0.49.4

I have installed the Rocket.chat Wordpress plugin and read the documents included with the plugin.  I am having issues getting it to display properly.  There was only one setting in which is asked what my installation URL was for Rocket.Chat.  Afterwards, I copied the script provided in "LiveChat >> Installation".

Have no luck getting it to disply on my site.

**Comment by dmkjr** [comment]
Ahh, nevermind.  I resolved this issue myself.

**Comment by k0nsl** [comment]
It would be useful for others if you described how you resolved your issue.
