### ISSUE TITLE
Script won't load from unauthenticated sources

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#5711]
Rocket.Chat Version: 0.49.4

Browsers will not load my chat window (using Wordpress plugin).  I'm getting the "this page is trying to load scripts from unauthenticated sources" error.

Any idea how to resolve this so I can display it?  Our website currently has a SSL installed on the domain.

**Comment by dmkjr** [comment]
I think the problem may be because I don't have a SSL cert installed on the Rocket.Chat server.  I'll try that and update this issue.

**Comment by engelgabriel** [comment]
Indeed, you need SSL on all sources :)

**Comment by dmkjr** [comment]
Thank you.  I have resolved the issue by installing a SSL cert on that domain.
