### ISSUE TITLE
add custom provider to storage type (file upload)

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5712]
Can you add new provider api based to storage type so we can manage file uploading storage and handle any further business.

There are three types for storage type : amazon s3, file system, gridfs.
is there is a possibility to add new type (custom api) that accept binary data and the userId.

**Comment by engelgabriel** [comment]
@hussamEddinAlhendi This is definitely on our roadmap, but we haven't started on it. Do you want/like to help?

**Comment by hussamEddinAlhendi** [comment]
@engelgabriel I started implementing this feature today

**Comment by engelgabriel** [comment]
Awesome, you can open an Work In Progress pull request, so we can help you reviewing the code and giving you directions :)

**Comment by hussamEddinAlhendi** [comment]
yeah sure :)

**Comment by hussamEddinAlhendi** [comment]
@engelgabriel @rodrigok Please Can you help me how to get the binary data of a file in meteor or if there is any package to use?

**Comment by thiesschneider** [comment]
can you also add nextcloud?

**Comment by louisemessage** [comment]
Seeing as progress on this issue does not appear to have been made, I am closing this issue for the meantime.
