### ISSUE TITLE
Push message formatting broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5714]
Rocket.Chat Version: 0.49.4

Hey Guys,

since the update to 0.49.4 my push message formatting is a bit broken: 

![image](https://cloud.githubusercontent.com/assets/5877910/22184450/f48eb5e0-e0d1-11e6-8f37-5a2e438f49d5.png)

The @ is missing.

Maybe it could be related that i have turned on the option that only the username is pushed. The test pushnotification seems ok.

**Comment by sampaiodiego** [comment]
it was actually changed by https://github.com/RocketChat/Rocket.Chat/pull/5504 to allow better styled push notifications..

why do you think it is broken?

**Comment by TheReal1604** [comment]
@sampaiodiego its fixed.
