### ISSUE TITLE
Livechat not loading due to DENY or multiple X-Frame-Options

### ISSUE THREAD

**Issue by rapcal** [RocketChat/Rocket.Chat#5716]
`Rocket.Chat Version:  0.49.4 | Ubuntu 16.04 | snap`
`Running Instances: 1`
`DB Replicaset OpLog: N/A`
`Node Version: 4.6.2`

I'm trying to install livechat and I'm facing a weird problem. If I make no changes to the allowed domains list, the `X-Frame-Options` header is set to `DENY`. This seems to contradict the help block in the admin area: `Leave blank to allow all domains.`

![no-whitelist](https://cloud.githubusercontent.com/assets/620436/22186337/3eba6b4c-e0db-11e6-9c4c-a7b859494fb3.png)

But here's the strange part: if I whitelist a domain, an `ALLOW FROM` is included in the header, but the `DENY` is kept, causing the browser to opt for the strictest one. See: 

![in-whitelist](https://cloud.githubusercontent.com/assets/620436/22186338/3ec38fba-e0db-11e6-8eb1-a3e9675a81cb.png)

[These lines](https://github.com/RocketChat/Rocket.Chat/blob/f2ecc5cac06dec51295b428be3691bba5606a7c4/packages/rocketchat-livechat/livechat.js#L21-L26) are the only reference I found in the source code mentioning `X-Frame-Options` or `ALLOW FROM` and they're specific to livechat.

Any help is much appreciated! Thanks in advance 👍

**Comment by engelgabriel** [comment]
@sampaiodiego can you take a look at the logic and confirm if this is a bug?

Thanks @rapcal can you please do a PR with your proposed fix?

**Comment by engelgabriel** [comment]
@rodrigok can you help check the logic here?

**Comment by rodrigok** [comment]
The code seems correct, will not return the `X-Frame-Options` if the setting is empty.

Are you using some reverse proxy like nginx?

**Comment by rapcal** [comment]
Gosh... duh. Yup ☹️ , with a global DENY clause.
I'll close the issue now and confirm with an updated nginx config later today. If it doesn't fix I'll let you know, but I'm sure you found the root cause.
Sorry to have taken your time, guys, and thanks for the asap response!

**Comment by rapcal** [comment]
@rodrigok confirmed it was the Nginx config. Thanks!

**Comment by guoxiangke** [comment]
@rapcal  how config nginx? I use https://cloudron.io/ thanks
