### ISSUE TITLE
LiveChat Offline Message destination?

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#5717]
Rocket.Chat Version: 0.49.4

I'm opening the issue, but I cannot readily identify the problem.

I have Livechat turned off from my username to ensure that the chat window show's "Offline" and to leave a message.  In testing, I'm trying to find out where that offline message is actually delivered and/or how to change where that offline message is delivered.  I'm not seeing it in my account, nor my email.

Any ideas?

**Comment by dmkjr** [comment]
If it helps, my domain is 'cityofhanahan.com'

Thanks,
David

**Comment by rapcal** [comment]
@sampaiodiego running 0.50.1 installed via snap on Ubuntu 16.04
Seems the email address is not persisting after save. Refresh the page and the email is gone.

**Comment by neha1deshmukh** [comment]
hey.. Any update on this issue.

**Comment by sampaiodiego** [comment]
@rapcal I've made a fix for it: #6077
