### ISSUE TITLE
Open custom TabBar on entering room?

### ISSUE THREAD

**Issue by garg** [RocketChat/Rocket.Chat#5718]
Rocket.Chat Version: 0.49.4
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.7.2

I have a custom package added to RocketChat. One action it takes is that it changes the template of the TabBar and opens it when entering a room. In version 0.33 the following code was used in the package:

~~~
RocketChat.callbacks.add 'enter-room', ->
	setTimeout ->
		RocketChat.TabBar.setTemplate 'customTemplateName', ->
			RocketChat.TabBar.openFlex()
	, 500
, RocketChat.callbacks.priority.HIGH, 'open-flex'
~~~

I recently updated to 0.49.4 and noticed that RocketChat.TabBar no longer has getTemplate or setTemplate functions. They have been moved to class RocketChatTabBar. I've been looking and there doesn't seem to be a global object anywhere that I can use to setTemplate, getTemplate, or OpenFlex  tabbar contents from inside my custom package. 

Am I mistaken or is there a better way of setting and getting templates and opening the tabbar programatically without clicking on it?

Thanks

**Comment by engelgabriel** [comment]
@karlprieb can you give some guidance here?

**Comment by karlprieb** [comment]
Hi! @garg. You can do something like that https://github.com/RocketChat/Rocket.Chat/blob/0c4944884b298fe6c9660ac4c7d23164ce19429e/packages/rocketchat-ui/views/app/room.coffee#L655

Create your logic and open your TabBar panel when the user enter in the room :)

**Comment by IQ2022** [comment]
can you show us sample image of what is this about?

**Comment by garg** [comment]
@karlprieb Thanks! It appears like I can only get to it from within the Template instance? 

@IQ2022 Sure! Thanks.  I'm attaching a screenshot. It is a tabBar with a canvas element inside it. 
<img width="1269" alt="screen shot 2017-01-23 at 7 05 13 pm" src="https://cloud.githubusercontent.com/assets/16932/22228471/63385f6e-e19f-11e6-8d4b-62a12a24bcfb.png">

Inside the custom package, I have a tabBar.coffee file that worked in 0.33.0:

```
Meteor.startup ->
	RocketChat.TabBar.addButton(
		groups: ['channel', 'privategroup', 'directmessage']
		id: 'paint',
		i18nTitle: 'Paint',
		icon: 'fa fa-refresh fa-spin',
		template: 'drawingBoardMain',
		width: 675,
		order: 11
	)

RocketChat.callbacks.add 'enter-room', ->
	_.each(PaintChat.tools.list, (tool, idx) -> tool.index.set(idx))
	PaintChat.tools.count.set(PaintChat.tools.list.length)
, RocketChat.callbacks.priority.MEDIUM, 'enter-room-tabbar-paint'

RocketChat.callbacks.add 'enter-room', ->
	PaintChat.getTextures() # Load all the textures for the brushes.
	#console.log RocketChat.TabBar.getTemplate()
	if RocketChat.TabBar.getTemplate() == "drawingBoardMain"
		#console.log "I found drawingBoardMain"
		Session.set('settingsTemplate', null)
		if PaintChat.drawingCanvas
			Blaze.remove(PaintChat.drawingCanvas)
			PaintChat.Strokes.stop();
			PaintChat.drawingCanvas = Blaze.render(Template.drawingCanvas, $('#drawingCanvas')[0])
			#console.log ('replaced drawingCanvas');
	else
		return 0
, RocketChat.callbacks.priority.MEDIUM, 'deal-with-room-change'

RocketChat.callbacks.add 'enter-room', ->
	setTimeout ->
		RocketChat.TabBar.setTemplate 'drawingBoardMain', ->
			RocketChat.TabBar.openFlex()
	, 500
, RocketChat.callbacks.priority.HIGH, 'open-flex'
```

This loaded the template that I needed, and once loaded, opens up the tabbar, and displayed it. And then destroyed it if there was a channel change. Now in 0.49, RocketChat.TabBar does not have the getTemplate and setTemplate functions and I'm having trouble figuring out how I can access it from outside a Template.

I feel like I'm missing something very obvious :)

**Comment by engelgabriel** [comment]
@garg do you want to do a PR with your package so we can help you to make it work? Looks like an interesting features to add to the core project too :)

**Comment by garg** [comment]
@engelgabriel That sounds like a very good idea! :) I'll do exactly that later today.

**Comment by garg** [comment]
@engelgabriel I have made a PR at #5788. 

<img width="551" alt="screen shot 2017-01-25 at 10 16 11 pm" src="https://cloud.githubusercontent.com/assets/16932/22318886/2d7da6fa-e34c-11e6-834e-09f08aeae6c3.png">

**Comment by Nemra1** [comment]
can you share this packge her..i want test it
