### ISSUE TITLE
"Clipboard... 0%" Message stays forever

### ISSUE THREAD

**Issue by danimaiochi** [RocketChat/Rocket.Chat#5719]
When I paste an image to someone or a group, it shows 2 loading bars on the top of the screen showing the upload progress, but one of the bars keep still at 0% and stays there even after the upload is complete.

Rocket.Chat Version: 0.49.4
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0

**Comment by engelgabriel** [comment]
This was fixed on https://github.com/RocketChat/Rocket.Chat/pull/5702 but not released yet.
