### ISSUE TITLE
Reoccurring java script popup 

### ISSUE THREAD

**Issue by oliver-bowman** [RocketChat/Rocket.Chat#5720]
Rocket.Chat Version: 0.49.1
Running Instances: 4
DB Replicaset OpLog: Yes
Node Version: 4.5 LTS
Rocket Chat Client version: 2.2.2

The issue one of my colleagues is experiencing comes after the commit: https://github.com/RocketChat/Rocket.Chat.Electron/commit/4f361bc33fa2d79044c03e3c84b4027d0716d4ca he is expriencing multiple popups wit the message ![jserror](https://cloud.githubusercontent.com/assets/7502243/22200513/521f4da2-e157-11e6-9be3-bc0620dcabe7.png) 

This appears every time after zooming in or out in the client.

**Comment by engelgabriel** [comment]
Thank @oliver-bowman 

Can you please open this issue on the https://github.com/RocketChat/Rocket.Chat.Electron project and close ti here?

**Comment by MartinSchoeler** [comment]
Moved to https://github.com/RocketChat/Rocket.Chat.Electron/issues/318
