### ISSUE TITLE
Dropdown items are not displayed

### ISSUE THREAD

**Issue by rauhmaru** [RocketChat/Rocket.Chat#5721]
Rocket.Chat Version: 0.49.4
Running Instances: 1
DB Replicaset OpLog: Não

By clicking on "more channels ..." and then in the dropdown menu, the items appear to be white, the same color as the background, and you can not see the options.
![dropdown](https://cloud.githubusercontent.com/assets/2289237/22201498/a7085c74-e142-11e6-82e5-b9a33d6d9035.png)

**Comment by Jannibal** [comment]
A temporary workaround for this is the following:
Administration --> Layout --> Custom CSS, paste the following
`aside select.c-select option { background-color: #04436a; }`

**Comment by rauhmaru** [comment]
Works perfect, @Jannibal. Thanks.

**Comment by rauhmaru** [comment]
Now a new problem:
After removing this custom CSS, it still continues to influence the layout.
![dropdown](https://cloud.githubusercontent.com/assets/2289237/22206745/327f4228-e15b-11e6-9a76-5cad43cf20d0.png)
Even after removing the CSS and reloading the page, the background still looks as if the CSS was applied.

**Comment by karlprieb** [comment]
@rauhmaru Can you open a new issue for that?

**Comment by rauhmaru** [comment]
Roger that :)
