### ISSUE TITLE
Improve Room Header

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#5728]
Through experiences like this - again and again ....

![screen shot 2017-01-23 at 10 37 45 am](https://cloud.githubusercontent.com/assets/122633/22210544/31a38e20-e158-11e6-9f5d-8b26856a2e92.png)

It is clear that it is not our community members that do not read the topic.

BUT  -  the topic is too hard to read on most monitors / setups.   

Please improve the UI aesthetics so that the topic "grabs as much attention" as the room name.

**Comment by engelgabriel** [comment]
Inded, let's make it less faded.


![image](https://cloud.githubusercontent.com/assets/1000217/22212395/b2470484-e177-11e6-89ca-bf51af2416f5.png)

**Comment by jonatassalgado** [comment]
What do you guys think about this less faded text? 

The second image is the proposed adjustment. Some guideline about font-family? I thought to change to Arial and decrease opacity a bit. If Arial is not a good option I can try to maintain the same font and adjust only size and opacity (option 3). Thoughts?

1 - original
2 - Arial with less opacity (I vote to this)
3 - only less opacity

![faded_text_assets_1](https://cloud.githubusercontent.com/assets/9335343/23148916/5073b0b6-f7c7-11e6-839e-665850f7fdbd.png)

PS: It's my first contribute and I have a few hours a week, so I get easy and fast issues until I get a better understood about RocketChat. :)
