### ISSUE TITLE
 Unknown job: rocketchat`

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5731]
Rocket.Chat Version: 0.49
Running Instances: Ubuntu 14.04 x 64
DB Replicaset OpLog:
Node Version: 0.45

when i do `sudo start rocketchat`, it gave me error saying: `start: Unknown job: rocketchat`, why is that?

**Comment by soundstorm** [comment]
Did you mean `service rocketchat start` or `systemctl start rocketchat`? Did you follow the installation instruction and created the `rocketchat.desktop` file?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
