### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5737]
Rocket.Chat Version: 0.50.0
Running Instances: 
DB Replicaset OpLog:
Node Version:
After upgrading to 0.50.0 version got this error on the site
<img src="https://i.imgsafe.org/6e6ce50677.png">

**Comment by engelgabriel** [comment]
the server was restaring

**Comment by zorenleo** [comment]
@engelgabriel should I restart our server too?

**Comment by scjudd** [comment]
@zorenleo This was how #5739 was manifested for me. If you installed the server via `snap install rocketchat-server`, do a `snap revert rocketchat-server` until #5739 is resolved.

**Comment by zorenleo** [comment]
@scjudd Yeah I just did `snap revert rocketchat-server` command then I just started working properly from the previous version. Thank you, you help a lot.
