### ISSUE TITLE
Need rocket chat feature list

### ISSUE THREAD

**Issue by neha1deshmukh** [RocketChat/Rocket.Chat#5738]
Hi,

i am new to rocket chat. i want know what are the features currently available, under planning/ discussion in rocket chat ??

**Comment by jszaszvari** [comment]
Features: https://rocket.chat/features

In Progress: https://github.com/RocketChat/Rocket.Chat/labels/stat%3A%20in%20progress

Feature Requests: https://github.com/RocketChat/Rocket.Chat/labels/type%3A%20new%20feature

You can sort through what you are looking for by using Labels in GitHub 

https://github.com/RocketChat/Rocket.Chat/labels

Why dont you give it a go and see the features first hand?

**Comment by marceloschmidt** [comment]
Thanks @jszaszvari

**Comment by neha1deshmukh** [comment]
Thanks @jszaszvari
