### ISSUE TITLE
Snap: missing .node_version.txt file

### ISSUE THREAD

**Issue by scjudd** [RocketChat/Rocket.Chat#5739]
So, I've installed Rocket.Chat via `snap install rocketchat-server`, and it appears the latest release (444) won't start up. If I revert to the previous release with `snap revert rocketchat-server`, everything comes up fine.

It looks like a /snap/rocketchat-server/444/.node_version.txt file is trying to be opened, but it doesn't exist.

This is kind of annoying, because it automatically updated to this revision and took our chat server offline while I was away from the computer.

**Comment by geekgonecrazy** [comment]
@scjudd sorry you experienced this.  Thanks for reporting.  Digging into this now to see if we can get this quickly resolved

**Comment by geekgonecrazy** [comment]
@scjudd Good news is i'm able to replicate.  Bad news is its an issue.  Trying to resolve as quick as possible to get a fix out for you guys.

@rocketchat/core https://github.com/RocketChat/Rocket.Chat/blob/develop/server/startup/serverRunning.coffee#L12

**Comment by ParkerMc** [comment]
Just thought I would add this we are getting the bug to.

**Comment by scjudd** [comment]
Thanks for the blazing fast response time! :100:

**Comment by geekgonecrazy** [comment]
@ParkerMc / @scjudd I apologize for the inconvenience.  I've pushed out a build to fix this straight to the stable channel.   Revision 446.  

Also #5740 will close this issue for good.

Thanks for your patience and for reporting it :+1:

**Comment by axeloz** [comment]
Rocket is back now thanks for the fix. 
For those who wonder, just issue a 
```
snap refresh rocketchat-server
systemctl restart snap.rocketchat-server.rocketchat-server
```

**Comment by zorenleo** [comment]
@axeloz is it your rocketchat version still on 0.50.0 that you've fixed after restart command?

**Comment by ParkerMc** [comment]
Thank you for the quick fix!

**Comment by geekgonecrazy** [comment]
@ParkerMc No problem :)  We've implemented some safe guards to hopefully prevent a bad release from coming out like that again. 

Thanks for your patience!
