### ISSUE TITLE
[Feature Request] Support Minio as File-Upload Backend

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5741]
more information coming soon...

https://www.minio.io/

**Comment by ruriky** [comment]
I have had a small test setup running with minio as File Upload storage for a while.

The setup uses newest available docker images. Minio's bucket was created manually.
In RocketChat's File Upload menu:
- Storage Type: AmazonS3
- Bucketname: name of my bucket
- Key and ID are what ever minio has generated
- BucketUrl https://internal_domain.com/bucketname

The setup has been running only for my test purposes so no heavy stress testing has been done. But image uploading seems to work. I have seen some problems with uploaded images not showing in chat without refreshing the chat page first, but the newest minio version might have fixed that.

**Comment by TheReal1604** [comment]
@ruriky oh nice! Thanks for that sample config.. this is now working.

My mistake was that i formed my Bucketurl like i access it via web:

https://internal_domain.com/minio/bucketname - the upload is not working then. If i delete "minio" out of the bucketurl it works like a charm. Awesome. :+1:

**Comment by graywolf336** [comment]
@ruriky and @TheReal1604 Do you guys mind writing some documentation for this?

**Comment by TheReal1604** [comment]
@graywolf336 @ruriky https://github.com/RocketChat/Rocket.Chat.Docs/pull/196

**Comment by TheReal1604** [comment]
i close this issue because we now have merged docs. 👍

**Comment by MaxwellDPS** [comment]
Was this removed in the docker version?
