### ISSUE TITLE
DM does not appear in 0.50.0

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#5746]
Rocket.Chat Version: 0.50.0

In the latest version of rocket.chat, direct messages does not appear at all. Anybody else having the same issue?

**Comment by cgaspard** [comment]
We are getting the messages, but we're not seeing an alert beside the name indicating unread messages.

**Comment by Nemra1** [comment]
yup..unread msg NTF is dead since upadate but ithink v50 is not official to now

**Comment by cgaspard** [comment]
Looks like v50 is official.   At least enough to show up on the download page.

https://rocket.chat/download

**Comment by kajisaap** [comment]
To keep the sanity in our chat window, we would usually _hide_ the 1-1 conversations provided by "hide button" such that it would pop up only when new activity happens in that DM. That visual sanity trick is futile now :( 

**HELP! HELP!!**

**Comment by dmkjr** [comment]
One thing I found as a work around (because we too are having this bug) is to click on "More Direct Messages" and then it will appear and notifications start functioning again.

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/6ca9b47f68e18db76180da5e2d63b1d9b7dee45f

**Comment by kajisaap** [comment]
waiting for the snap to pick up the new version!! 

@geekgonecrazy when would new version get picked up by `snapd` system?

**Comment by dmkjr** [comment]
@kajisaap I do am seeking that answer.  I have tried multiple times to start it manually without such luck.

**Comment by geekgonecrazy** [comment]
@kajisaap / @dmkjr its building now.  

@dmkjr i'll let you know as soon as its there as mentioned in #5748 I promise ;)

**Comment by geekgonecrazy** [comment]
@kajisaap / @dmkjr revision 451 / Release 0.50.1 is now in the stable channel.   As always will auto update, but `sudo snap refresh rocketchat-server` will do it quicker.
