### ISSUE TITLE
0.50.0 Snap Upgrade Issues

### ISSUE THREAD

**Issue by cgaspard** [RocketChat/Rocket.Chat#5747]
My Ubutnu Server / Snap installed rocket chat is experiencing some issues this morning after it auto upgraded last night to 0.50.0.

Here is the list of issues.

1.   After the upgrade, I had to restart the server to get rocket chat to respond again.   NGINX was responding, but it wasn't proxying to rocket chat.

2.  Direct messages and channel messages are not causing notification badges to appear beside their name in the list of users and channels.

3.   Direct messages show a notification badge next to the person you are sending to for a brief instant, than disappears.    This is only for outbound messages.   Inbound messages do not show notification badges next to the names at all. 

Rocket.Chat Version:  0.50.0
Running Instances: 1 server with about 25 clients
DB Replicaset OpLog: How do I get this?
Node Version:  I'm using the snap version.  Node isn't actually installed on the server other than through snap.

**Comment by cgaspard** [comment]
Here is something I noticed just now.

<img width="804" alt="screen shot 2017-01-24 at 8 05 43 am" src="https://cloud.githubusercontent.com/assets/759034/22250279/efe208cc-e20b-11e6-9485-8e2588eadaa5.png">

**Comment by cgaspard** [comment]
Restarting the server brought the instances back down to one, but the other problems persist.

<img width="593" alt="screen shot 2017-01-24 at 8 14 32 am" src="https://cloud.githubusercontent.com/assets/759034/22250606/2909ae1a-e20d-11e6-845f-f13e24158514.png">

**Comment by MartinSchoeler** [comment]
@cgaspard could you create different issues for each item on the list? Thanks!

**Comment by cgaspard** [comment]
@MartinSchoeler  sure thing.

**Comment by cgaspard** [comment]
Moved to #5748 #5749 #5750 #5751
