### ISSUE TITLE
SNAP Upgrade Requires Restart

### ISSUE THREAD

**Issue by cgaspard** [RocketChat/Rocket.Chat#5748]
I'm splitting this out of the original message I posted here #5747

After the upgrade of my snap package to version 0.50.0 rocket chat was not responding.    NGINX  was responding, but it wasn't proxying to rocket chat.

Unfortunately I didn't do a lot of troubleshooting to see why it wasn't responding, I just rebooted the server and things came back up.

Rocket.Chat Version: 0.50.0
Running Instances:  1
DB Replicaset OpLog: 
Node Version: Version bundled with SNAP

**Comment by geekgonecrazy** [comment]
@cgaspard did this happen to be last night?  Did you happen to see the revision number? 

Might be related to: #5739 0.50.0 was briefly in the stable channel last night in a broken state.  We fixed it pretty quickly, but if your instance caught it before I pulled the build.  A restart I believe would cause it to check for new builds.

If you have any other info please let me know.  I think this is isolated and we've taken measures in #5755 to ensure this doesn't happen to snap users again.

**Comment by cgaspard** [comment]
It was last night, and I couldn't pull up the rocket chat UI to see the revision number.

My first reaction was to restart.  I'm sure I could have found the revision in the source, but I was in a hurry to get the server back up so I tried a restart first.   I'll look for it if it happens again.

**Comment by cgaspard** [comment]
@geekgonecrazy I have 3 other tickets that might be related to rocket chat being in a broken state in the stable channel.    Is there a way for me to verify that my version is the current stable, and not the broken state?

**Comment by geekgonecrazy** [comment]
@cgaspard running: `sudo snap refresh rocketchat-server` is best way to do a check for new versions of the snap.  0.50.0 is the latest version though.  Once those issues are fixed and we cut a new release we will fast track testing / promoting the release to stable.

Just keep an eye on them to be closed, easiest way to see we've fixed them.

**Comment by engelgabriel** [comment]
@cgaspard and @geekgonecrazy version `0.50.1` have been shipped, with the https://github.com/RocketChat/Rocket.Chat/issues/5739 included.

**Comment by dmkjr** [comment]
How long does it take Snap to update?  Says no updates are available at the moment when running snap refresh rocketchat-server

**Comment by geekgonecrazy** [comment]
@dmkjr The snap is still building and not yet in the stable channel.  Once it lands usually it will auto update in around ~4-6 hours after released.  Of course manually checking via: `sudo snap refresh rocketchat-server` checks sooner.

I'll drop a note here once it has landed.  Thanks :smile:

**Comment by geekgonecrazy** [comment]
@cgaspard  / @dmkjr revision 451 / Release 0.50.1 is now in the stable channel.   As always will auto update, but `sudo snap refresh rocketchat-server` will do it quicker.
