### ISSUE TITLE
After 0.50.0 Upgrade, Missing Notification Badges

### ISSUE THREAD

**Issue by cgaspard** [RocketChat/Rocket.Chat#5749]
Direct messages and channel messages are not causing notification badges to appear beside their name in the list of users and channel when new messages arrive.

Rocket.Chat Version: 0.50.0 (Snap Installed)
Running Instances:  1
DB Replicaset OpLog:
Node Version: Snap installed version

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/6ca9b47f68e18db76180da5e2d63b1d9b7dee45f
