### ISSUE TITLE
Visual clue / button to exit edit mode.

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#575]
There currently is no indicator of how to exit / cancel edit.  Hitting escape exits... But there should be a visual way to do this.  Somewhere to just click and cancel the edit.

**Comment by rockneverdies55** [comment]
+1

**Comment by Sing-Li** [comment]
Aha!   Hitting escape?!   How do you do it on android or iphone?  :confused:

**Comment by geekgonecrazy** [comment]
@Sing-Li yeah I don't know escape is being bound to the cancel or if its coincidental.

You don't.  lol Editing on mobile is currently broken also:  #552

**Comment by Sing-Li** [comment]
But up until very recently, I've been able to edit in place - right where the message is displayed; and it even worked on mobile.  Hmm.... mmmm ..... mmmmm.    Awa

mm..... awaiting  enlightenment from UI gurus.

**Comment by geekgonecrazy** [comment]
I know that is the way slack works.  If done right, editing on the bottom could be pretty sweet.

Kinda cool being able to just hit the up arrow to get to your last message and update it.  Even though I hit the up arrow out of habit to get last command so I can repeat it :smile:

**Comment by rodrigok** [comment]
I totally agree with buttons to cancel and commit edition.

Slack also keep the editing at bottom in mobile, so we think this is the better way, keep the same behavior in all devices.

Navigate among history is a good ideia, maybe we can create another shortcut like CMD/CTRL + UP/DOWN.

**Comment by rockneverdies55** [comment]
Pressing `ESC` key doesn't cancel edit for me on window 7 machine with chrome browser version 43.0.2357.134 m.

However, when I click `esc to cancel` link at the bottom of text box, it works.

I didn't know if I should re-open this one or create a new issue?

**Comment by rodrigok** [comment]
@rockneverdies55 Please open a new issue, seems to be more related with Windows.

**Comment by stuartpb** [comment]
for posterity, the above issue was opened as #603
