### ISSUE TITLE
After 0.50.0 Upgrade, Notificaiton Badges Appear on Outbound Messages

### ISSUE THREAD

**Issue by cgaspard** [RocketChat/Rocket.Chat#5750]
Outbound messages flash badge breifly, then disappears.

![notificationissue](https://cloud.githubusercontent.com/assets/759034/22251543/bbe0ec28-e210-11e6-9c6c-5840a71d85bc.gif)

Rocket.Chat Version: 0.50.0 (Snap installed)
Running Instances:  1
DB Replicaset OpLog:
Node Version: Snap installed version

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/6ca9b47f68e18db76180da5e2d63b1d9b7dee45f
