### ISSUE TITLE
After 0.50.0 Upgrade, Desktop Notification Settings Ignored

### ISSUE THREAD

**Issue by cgaspard** [RocketChat/Rocket.Chat#5751]
After snap install upgraded to 0.50.0, desktop notificaiton settings appear to be ignored.

Here is the channel settings I have set.

<img width="402" alt="screen shot 2017-01-24 at 8 43 07 am" src="https://cloud.githubusercontent.com/assets/759034/22251686/4c65ab94-e211-11e6-9535-8c7e2c4f8a8f.png">

After receiving messages in the channel, no desktop notifications were generated.

This appears to only be related to channels.  DM are still showing desktop notifications.

Rocket.Chat Version:  0.50.0 (Snap Installed)
Running Instances:  1
DB Replicaset OpLog:
Node Version:  Snap installed version

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/6ca9b47f68e18db76180da5e2d63b1d9b7dee45f
