### ISSUE TITLE
0.50.0 First user not admin

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#5752]
Rocket.Chat Version: 0.50.0
Running Instances: 1
Deployment method: Snap

I don't think this is specific to snaps.  But first user as of 0.50.0 is not automatically set as admin

**Comment by Sing-Li** [comment]
Verified for snaps :(

**Comment by geekgonecrazy** [comment]
Another verified via docker.  So for sure not deployment specific.

**Comment by avantasia** [comment]
Verified for snaps

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/6ca9b47f68e18db76180da5e2d63b1d9b7dee45f
