### ISSUE TITLE
Issue with reading custom fields from database

### ISSUE THREAD

**Issue by igorstajic** [RocketChat/Rocket.Chat#5754]
Rocket.Chat Version: 0.50.0
Running Instances: 1
DB Replicaset OpLog: disableld
Node Version: v4.6.2

The issue came up after updating from version 0.46.0-develop.
Basically we have added some extra data to the "rocketchat_room" collection, a "details" object containing some room specific information (project full name, description, link etc.). Now after merging with the most recent master branch I am no longer able to read that extra data from the collection.

Any help would be appreciated.

**Comment by rodrigok** [comment]
Can you try version 0.50.1?

**Comment by igorstajic** [comment]
@rodrigok Still the same.

**Comment by engelgabriel** [comment]
@igorstajic we will release the version 0.51.0 on monday, lets give it another try.

**Comment by rodrigok** [comment]
@igorstajic How are you reading these information? Are you using our REST API, our reactive API or did you change the client code?

**Comment by igorstajic** [comment]
Works now with the latest version.
