### ISSUE TITLE
Publish master branch snap to Candidate channel

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#5755]
Quick stop to future disaster, as explored in our discussion on demo.

Basically, a "buggy" master release can impact (take down) all snap users running Stable channel  - due to automatic rollout.     

We need to test before publishing to Stable, adding Candidate channel allow us some time.

Until we fully integrate automated testing into the lengthy (elapsed time) build pipeline.

**Comment by geekgonecrazy** [comment]
All new snap builds for releases now goto the candidate channel where we can review and move over to stable after passing QA. :+1:
