### ISSUE TITLE
0.50.0 Live Chat is dead

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#5757]
Rocket.Chat Version: 0.50.0

LiveChat seems to have died when using the Wordpress Plugin.  Cannot get it to display on my site.  Worked in the last 0.49.4

**Comment by engelgabriel** [comment]
Please try version 0.50.1 and reopen if the problem was not fixed by https://github.com/RocketChat/Rocket.Chat/commit/6ca9b47f68e18db76180da5e2d63b1d9b7dee45f
