### ISSUE TITLE
MOD - "IRC style" go easy on client resources

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#5763]
Rocket.Chat Version: 49.3

Lets call it IRC mod, as irc text chat cant eat up yours client resources. 
Suggestion: create setting in server administration for forcing entire server and-or specific channels to get drop resource hungry animations, gifs, videos etc. Allow the channels became simple text chat with avatars(localy load avatar) without any graphic-resource hungry crazyness.

**Comment by engelgabriel** [comment]
Maybe the best way to do this, would be to develop a new thin client, what do you think?

**Comment by Abraka** [comment]
Well thats sound like lot of work for few performance optimalizations. I was thinking more like adding options when you creating channel...you will choose from standart-rich display or simple-performace one which will drop hungry animations, gifs, videos etc. 
If you thing that for achieveing this functionality we will need new client, lets put this on long term(0.65-70) when everything is done and developers get bored from lack of requets here :) 
There are things like LDAP(SSO)! which need much more and immediate attentions from developers.

**Comment by SeanPackham** [comment]
We have made significant improvements to our data usage but have no plans on our roadmap to implement a specific feature like this. We will continue to strive to produce a lean messaging protocol and implement bandwidth saving techniques such as not download images automatically etc.
