### ISSUE TITLE
[Feature Request] Have a online users list for end users

### ISSUE THREAD

**Issue by jprone** [RocketChat/Rocket.Chat#5764]
My end users are wanting a similar view that Administrators have under "Administration > Users" - are there plans to maybe implement something like that?  Or am I missing a "Permissions" checkbox that I could assign to a certain type of user that also isn't a sweeping admin?

**Comment by rasos** [comment]
User list needed for:  
1. inviting someone for private chat
2. adding someone to chat group
3. managing users (e.g. check, if a user already registered) 
Ideally we have a role "list-users". Task 3 is not necessarily done by the admin, but a secretary, who takes care of the onboarding.  
For an organization or company, it would be normal that all logged in users can see others.

**Comment by SeanPackham** [comment]
We currently support viewing online, offline and all users in a channel for non-admin users.
