### ISSUE TITLE
AWS installation - no admin user

### ISSUE THREAD

**Issue by dauletico** [RocketChat/Rocket.Chat#5765]
Today I installed the RocketChat following AWS installation.
App is working, I registered a new user, but do not see any Administration tab in the navigation sidebar.
In mongo db in users collection I see two records: 1) rocket.cat with "roles": ["bot", "admin"] and 2) my user with "roles": [ "user" ]. Tried to push admin role in "roles", but Administration tab didn't appear.
What should be done in order to receive Administration tab? 

App version: 0.50.0
Commit hash: 5a66c80631cd7030a2f889ad71ab389617f2b33d

**Comment by engelgabriel** [comment]
You need to install 0.50.1, this was fixed.
