### ISSUE TITLE
Can RC chat serve as hubot?

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5768]
Rocket.Chat Version: 0.49
Running Instances: Ubuntu 14
DB Replicaset OpLog:
Node Version:4.5

I installed RC that comes with a internal bot rocket.chat Cat. Can i use that as my RC hubot?

**Comment by LiorHaim** [comment]
Same question. Seems like the Internal-Hubot usage isn't explained well...Or just to me.
Also the doc about it is empty:
https://rocket.chat/docs/administrator-guides/internal-hubot/

**Comment by engelgabriel** [comment]
It does need to be explained. Let's us work on the documentation. But also we need to make the hubot scripts folder configurable.

**Comment by timkinnane** [comment]
Duplicated by #8025, closing this because the other issue has more specific discussion.
