### ISSUE TITLE
Multi server capability for mobile apps

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#577]
Currently neither desktop or android application allows accessing custom rocket.chat instance. They're strictly working only against demo server. To me, those apps without being able to reach our instance of rocket.chat are useless.

It directly loads login page when I launch the application. It should load some sort of settings page and ask for remote server address first.

**Comment by Sing-Li** [comment]
Only good for technical end-users.   And if typos were made, the install can be problematic.

What about a 'provisioning service' -- on web, over the phone, standalone tool -- that can issues a code that installer enters (and can be visually validated  by installer with a logo and message of the organization/community) prior to install?

**Comment by rockneverdies55** [comment]
If I understand correctly, the root cause of the problem is that with the current design approach, the app is loading from pre-set remote server as soon as it starts.

As opposed to that, I think login page should not be loaded from the server right away, that page (with additional field to enter remote url as well) should be kept in the client side code. End user will get that page when they install the application. So upon start, the app renders the new login page without making any kind of remote connections or requests yet. Then when user enters the remote url, application will know what remote url/server to load from or communicate.

**Comment by rodrigok** [comment]
We can do this in the Electron application, but we don't know how to do this in Cordova.

**Comment by rockneverdies55** [comment]
I'm not %100 clear on what's the issue with cordova. 
Is it about not being able to make cross domain requests or something like that? If so, whitelisting is the issue maybe? https://cordova.apache.org/docs/en/4.0.0/guide_appdev_whitelist_index.md.html

**Comment by rodrigok** [comment]
The problem is that we use the Meteor compiler for Cordova that just pack the application in cordova. Probably we can do a lot more creating a new app from scratch.

**Comment by rockneverdies55** [comment]
@rodrigok - do you mean new cordova app from scratch?

And also is there any plan to fix the problem in electron (desktop version) where it seems possible atm? So at least we have a true desktop client for now...

**Comment by rodrigok** [comment]
It isn't a bug to fix, is a improvement since you can compile and run your own desktop app.

We can't define dates now because we need more help to do all this things :)

Will be great if someone help us with this issue.

**Comment by geekgonecrazy** [comment]
I think you're right.  Probably easiest approach is to do exactly like with the electron app.  Make it separate.  Then you could put a configuration page or what ever before the actual app.  

Then you could load the app from the instance pointed to.  Maybe caching as much as possible in the process.

**Comment by rodrigok** [comment]
Exactly @geekgonecrazy, so we need some help from someone with more knowledge about cordova, I have zero.

**Comment by engelgabriel** [comment]
Agreed.. Should I create the Rocket.Chat.Cordova project?

**Comment by Sing-Li** [comment]
:+1:   I can help splicing in crosswalk.  Perhaps others can contribute platform specific hacks.

**Comment by geekgonecrazy** [comment]
:+1: Gladly help contribute as much as I can to making this work.  From what I can tell it shouldn't take much.

**Comment by engelgabriel** [comment]
Let's give it a try... https://github.com/RocketChat/Rocket.Chat.Cordova

**Comment by sampaiodiego** [comment]
is it a cordova app really necessary? I mean, a native iOS app is on the road, why create another app?

**Comment by graywolf336** [comment]
What's the roadmap for the native iOS app and native Android look like? If it's not soon, then I would say a Cordova app is needed to get custom instances supported right off the bat and then improve down the road with the native apps. Should the Cordova route be the one to take, I would be happy to continue testing and possibly help out as much as I can with any part of it.

**Comment by geekgonecrazy** [comment]
@sampaiodiego mainly the need for creating another app is so the host connection screen can easily be done.

I'm working with @graywolf336 on another project using cordova.  So we're kinda having to beef up on it.

**Comment by Sing-Li** [comment]
Perhaps @gsaslis can give a rough ball park estimate.  But industry average for native apps of similar complexity by a pro team is about 3 months to non-crashing beta.  IMHO 3 months in Rocket.Chat time is almost a life time.   How long has this repo been up ?  :smile:

**Comment by engelgabriel** [comment]
It should be a relatively easy and useful project. Can probably copy a lot from Meteor Cordova built?

**Comment by geekgonecrazy** [comment]
@Sing-Li for sure takes about a while.  A lot more to writing native.  Not to mention a completely different language for each platform.  Both of which are different then the web app / backend.

**Comment by gsaslis** [comment]
I probably wouldn't really count on the native apps being production-ready in any less than a month.. This is NOT to say we'll have sthn ready in a month, but there is some progress already... 
On the other hand, we've only really just started working on this and it's very (very!) hard to make any sort of estimates, especially since for most of us on the team this is a part-time project (if that : )  )

Any help on the native iOS side is definitely welcome!!!  ; )

on the particular issue in this thread though, i think @rodrigok 's point about forking your own app is probably the best solution available right now... (?)

**Comment by rockneverdies55** [comment]
It's a good idea to have a separate cordova project till native apps be ready.

What about the fix in desktop application though?

**Comment by geekgonecrazy** [comment]
Im attempting that fix here.

RocketChat/Rocket.Chat.Electron#25

Was already in progress, just trying to help push it along

**Comment by mitar** [comment]
What about using Meteor settings for this? Or Meteor settings do not work on Cordova?

**Comment by Sing-Li** [comment]
**SOLUTION AVAILABLE for IMMEDIATE DOWNLOAD** For Android devices with versions as far back as 4.0.x, and Blackberry Passport, the solution has been available for over  a month and used by hundreds already -   just  [download the APK in the page](https://github.com/RocketChat/Rocket.Chat/wiki/Build-the-Android-Cordova-Web-App-and-connect-to-your-own-Rocket.Chat-Server).

**Comment by mradke** [comment]
@Sing-Li is there a roadmap for an iOS solution? This is currently holding me back to roll out an instance. :rocket:

**Comment by gthorne** [comment]
Agreed, need iOS solution.  Lack of an app may be a deal-breaker.

**Comment by philip-peterson** [comment]
+1 for iOS being able to access a custom instance!

**Comment by Pweta** [comment]
+1 here as well please, one of the iOS key Features on the App store is "BYOS (bring your own server)" not much use if you cannot connect to it??

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat.Cordova now supports that. We will release the binaries shortly.

**Comment by digcatmarkp** [comment]
Woohoo the iOS app connects on our custom instance as of this morning. Way to go guys!!!!

**Comment by jashot7** [comment]
I'm really excited that digcatmarkp mentioned the iOS app now connects to their custom instance, but we're not finding that to be the case with the version in the iOS app store as of right now. Can someone give me a little feedback on whether the version in the app store should work, if we need do do a build of the Cordova app and deploy it to our devices (ugh), and let me know what the 'custom build parameter' is that we use when building the server app from source? (We couldn't find this in the documentation for the server app.) I think anyone coming here would benefit from this information :) Thanks!

**Comment by engelgabriel** [comment]
Did you not see the screens below? Did you try swiping the 2 fingers up from the bottom?

![image](https://cloud.githubusercontent.com/assets/1000217/11693661/419f4774-9e8d-11e5-9622-82b62e6b2c9b.png)
![image](https://cloud.githubusercontent.com/assets/1000217/11693666/46cb0562-9e8d-11e5-839e-4b0b9697eeb3.png)

**Comment by jashot7** [comment]
Thanks, totally did see those screens. I believe our issue is that in order to connect to our custom server instance, we need to build the source with a custom parameter. At the GitHub page for the Cordova cross-platform mobile app, it says:

"This application only connects with servers that were compiled with mobile platforms enabled"

I'm guessing that we needed to build from source and provide this parameter, but we can't find it in the documentation. 

I could be way off here, but basically - when trying to connect to our custom server using the UI you're showing (activated by the two finer swipe), it just hangs. The same thing happens for the OS X app. Maybe its a different issue, but this seemed like the culprit. Thanks for responding - we're really excited to get this to work.

**Comment by graywolf336** [comment]
@jashot7 Mind checking to see if the issues you're describing are reported on the Cordova project? https://github.com/RocketChat/Rocket.Chat.Cordova/issues as there are a few issues currently with the mobile application when adding more than one server (https://github.com/RocketChat/Rocket.Chat.Cordova/issues/45)..

**Comment by jashot7** [comment]
I looked through all of the issues and then went to test the connection again. The OS X app now connects and I'm getting this already documented issue: 

"loading undefined" when connecting to a new server #41
https://github.com/RocketChat/Rocket.Chat.Cordova/issues/41

I've made a comment there confirming that I'm seeing that bug.

- Not sure what changed, but I can no longer duplicate the 'hang' that was occurring for both the iOS and OS X apps.

Thanks for your quick response. If I can repeatedly duplicate this 'new/different' issue I'll open a ticket!

**Comment by digcatmarkp** [comment]
Hi all

iOS
![img_4398](https://cloud.githubusercontent.com/assets/13026322/11702466/fc17e578-9f2a-11e5-8a3b-836692e8b3fa.jpg)
![img_4396](https://cloud.githubusercontent.com/assets/13026322/11702467/fc1b45d8-9f2a-11e5-8c60-6ffd8ef5d557.jpg)

OSX
<img width="1016" alt="screen shot 2015-12-10 at 10 december 2015 10 47 44 am" src="https://cloud.githubusercontent.com/assets/13026322/11702525/77f4e858-9f2b-11e5-8e28-441e8cbca5f2.png">

Confirming that my iOS version is from the iOS app store.

Both the iOS and OSX chats are in syncing in real time.

We are running inside a 4GB Ubuntu VM.

Thanks

**Comment by geekgonecrazy** [comment]
:+1: awesome!

**Comment by jashot7** [comment]
We updated our server, deleted the iOS apps on our devices and reinstalled them and now we can connect to our custom instance just fine. Confirmed working! Also, the undefined issue is not a blocker for us (https://github.com/RocketChat/Rocket.Chat.Cordova/issues/41).

**Comment by avital** [comment]
Hi everyone, I am helping with an app that's based on Rocket.Chat and I found this thread. I'd like to better understand why people decided to create a separate Cordova app instead of using the default Meteor Cordova commands.

The most concerning thing from my perspective is that the separate Cordova app will be slower to load, since it loads all assets from the network. This is in contrast with Meteor's Cordova implementation that stores the latest working version of the app on the device itself -- this way, loading it the next time only has to go to the network to load external assets and data.

Can someone share insight as to the need for a separate Cordova shell app that doesn't store the application assets on the device?

**Comment by mitar** [comment]
@avital: Is this ticket really related to your question?

**Comment by rodrigok** [comment]
@avital we need a separated cordova app to allow you to connect to multiple servers, and no, we not download the files again, we use the same cache strategy that meteor does, but for multiple servers.

**Comment by engelgabriel** [comment]
Hi @avital, nice to see you around :) 

As we discussed by email a while ago, we had to implement a few improvements to the Meteor update script, like the hash key to avoid downloading assets that were already up-to-date. I glad to hear that now this is part of the 1.3 release! Yeah!

But our MAIN barrier to use the standard Meteor Cordova packager, is the ability to support multiple backend servers. After seeing your presentation ad the devShop, we are scheduling some time to take a look again at the new features and evaluate what we can use on our Cordova project.

Having said that, if it was easy to maintain and keep compatibility, we would love to allow people that want to build their app for a single server, to be able to use the regular Meteor Cordova Wrapper, do you think you could help us?

**Comment by avital** [comment]
Hi @engelgabriel :)

I totally understand the idea of letting you connect to multiple servers. And that would require a different wrapper. I think Rocket.Chat in this case is a pretty a-typical example. Most apps are downloaded from the person who runs the server. Rocket.Chat is more like IRC in this regard.

Do you think there should be problems using the Rocket.Chat codebase directly with Meteor 1.3's Cordova wrapper? Is anyone trying that? What could be the challenges with this approach?

**Comment by graywolf336** [comment]
@avital We currently have Cordova iOS and Android applications out on the respective stores. The code base for them is https://github.com/RocketChat/Rocket.Chat.Cordova. Or am I misunderstanding your comment?

**Comment by avital** [comment]
@graywolf336 I think you understood me correctly :)

To clarify the point made by @engelgabriel: Are you asking, can Meteor core's Cordova build process have a special mode where it lets you choose from a list of servers? I'm not sure this is something that'll be useful to many apps other than Rocket.Chat, it would be hard to justify the work on that feature in Meteor I would think.

**Comment by engelgabriel** [comment]
@avital what if the work was limited into making it possible to implement the UI and behaviour, by allowing the DOMAIN to be used as a key on cache storage, etc. We could work on a PR with MDG. 

The UI would be implemented by the app.

@rodrigok what do you think?

**Comment by rodrigok** [comment]
@engelgabriel I don't know, I need to take a look into the new plugin code
