### ISSUE TITLE
How can I remove sidebar completely

### ISSUE THREAD

**Issue by dauletico** [RocketChat/Rocket.Chat#5770]
I use rocketchat for iframe integration and don't want to show sidebar in the iframe.
How it could be done?
Tried to use Administration -> Layout -> Custom script to accomplish this with removing aside tag, but some empty container is still present in a left side.

**Comment by engelgabriel** [comment]
You can use the embedded layout.

@MartinSchoeler can you point him to the documentation? I could not find it.

@sampaiodiego did we added it to the docs yet?

**Comment by dauletico** [comment]
I don't want to bother you, but I have tried many thing with no luck. Could you tell me more about embedded layout?
