### ISSUE TITLE
Update from to 0.28 to 0.51

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#5773]
Rocket.Chat Version: 0.28.0
Running Instances: 1
DB Replicaset OpLog:
DB_Migration : 48
Node Version: v0.10.10

Deployed via meteor (without Docker)

we need to update Rocketchat from 0.28 to 0.51.0.

Let us know,

How to restore existing private room message?

**Comment by engelgabriel** [comment]
Make a back first, and just install the new version, the DB should be migrated automatically.

Open an issue if you have a problem.
