### ISSUE TITLE
Immediately "mark as read" toggle

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#5775]
Sometimes you don't want to check all messages before and scroll up all the way or hit "mark as read". Maybe there could be a toggle (my account) to mark a channel as read as soon as you open it and optionally a option to hide that toggle (if used for office and all messages should be read first).

**Comment by engelgabriel** [comment]
Interesting idea. In the mean time, you can use the pressing ESC shortcut when you enter the room.

**Comment by pandada8** [comment]
what about adding an icon/button beside current `leave-room` and `hide-room` button and when clicked simply mark the room as read
A global `mark as read` button could be added too

**Comment by soundstorm** [comment]
In the cordova mobile apps and even on desktop sometimes the window to mark as read vanishes (just displayed for a tenth of a second or so). On desktop with Escape okay, on mobile you have to scroll up and down and try to hit the button in the right moment or just reply.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
