### ISSUE TITLE
Incorrect resource path

### ISSUE THREAD

**Issue by SeMeKh** [RocketChat/Rocket.Chat#5776]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.7.1

When opening RocketChat on its Android app, and connecting to the demo server, it tries to load `http://httpsdemorocketchat.meteor.local/sounds/notify.ogg` which results in a 404, and the app keeps retrying.
Same behavior is happening on our own servers.

**Comment by engelgabriel** [comment]
Is this the same or similar problem fixed on https://github.com/RocketChat/Rocket.Chat/pull/5706 ?

**Comment by SeMeKh** [comment]
I can confirm that `http://httpsdemorocketchat.meteor.local/sounds/door_chime.mp3` is another missing resource indeed.

**Comment by rodrigok** [comment]
The file exists, is there, is accessible, but the server does not hit the file. I tried to debug and change the headers inside the Objective-C code, with no success :(

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/6202
