### ISSUE TITLE
Service Temporarily Unavailable after update 5.0

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5777]
Rocket.Chat Version: 5.0.1
Running Instances: 1
DB Replicaset OpLog: Disable
Node Version: 4.6.2
after update to 5.1 from 4.9.3
server is work for 2 hour only and givme 
Service Temporarily Unavailable
![2017-01-25_174215](https://cloud.githubusercontent.com/assets/22897987/22297650/987be56e-e326-11e6-9f53-78a48c68415b.png)
 Httpd.conf
`<VirtualHost cdn.example.com:443>
NameVirtualHost 192.168.1.4:443
ServerName cdn.example.com
ServerAlias www.cdn.example.com
ServerAdmin info@example.com
DocumentRoot /home/example/public_html
ErrorLog /var/log/cdn.example.com_error.log
TransferLog /var/log/cdn.example.com_access.log
LogLevel info
SSLEngine On
SSLCertificateFile /etc/letsencrypt/live/cdn.example.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/cdn.example.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/cdn.example.com/chain.pem
<Location />
        Order allow,deny
        Allow from all
</Location>

ProxyPreserveHost On
ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:90/sockjs/$1/websocket
ProxyPass / http://localhost:90/
ProxyPassReverse / http://localhost:90/

</VirtualHost>
`
Error log
[Wed Jan 25 10:30:50 2017] [error] (111)Connection refused: proxy: HTTP: attempt to connect to 127.0.0.1:90 (localhost) failed

[Wed Jan 25 10:30:50 2017] [error] ap_proxy_connect_backend disabling worker for (localhost)
[Wed Jan 25 10:30:50 2017] [error] proxy: HTTP: disabled connection for (localhost)
[Wed Jan 25 16:05:30 2017] [info] [client 41.232.121.252] Connection closed to child 5 with abortive shutdown (server cdn.example.com:443)

[Wed Jan 25 16:05:33 2017] [info] [client 41.232.121.252] (70014)End of file found: SSL input filter read failed.
[Wed Jan 25 16:05:33 2017] [info] [client 41.232.121.252] Connection closed to child 11 with standard shutdown (server cdn.example.com:443)
[Wed Jan 25 16:05:33 2017] [info] [client 41.232.121.252] (70014)End of file found: SSL input filter read failed.
[Wed Jan 25 16:05:33 2017] [info] [client 41.232.121.252] Connection closed to child 10 with standard shutdown (server cdn.example.com:443)
[Wed Jan 25 16:05:33 2017] [info] [client 41.232.121.252] (70014)End of file found: SSL input filter read failed.

[Wed Jan 25 16:05:33 2017] [info] [client 41.232.121.252] Connection closed to child 4 with standard shutdown (server cdn.example.com:443)
[Wed Jan 25 16:05:43 2017] [info] [client 41.232.121.252] (70014)End of file found: SSL input filter read failed.
[Wed Jan 25 16:05:43 2017] [info] [client 41.232.121.252] Connection closed to child 1 with standard shutdown (server cdn.example.com:443)
Any Idea Bcs this happen only after update

browser console after start the server manual

![2017-01-25_182337](https://cloud.githubusercontent.com/assets/22897987/22299446/c668a830-e32c-11e6-857f-67ad6085987b.png)

**Comment by MastricX** [comment]
I'd found that the .node_version.txt file contained v0.10.40, while I have v4.5.0 installed.

Altering the .node_version.txt file to v4.5.0 allowed me to start Rocket.Chat, but I'm unsure if this is a correct fix.

**Comment by Nemra1** [comment]
@MastricX the problem not in start server ...the problem about after server start / Rc port disconnected
from himself after 2hr or 33..this is never happen before

**Comment by engelgabriel** [comment]
Rocket.Chat does not handle the SSL, so it looks like the problem is elsewhere. There is not enough info here to help.
