### ISSUE TITLE
Push notifications configuration

### ISSUE THREAD

**Issue by jm4rc05** [RocketChat/Rocket.Chat#5778]
This more a support request!

Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.2 - x64

I'm trying to get push notifications working. Everything in the configuration panel seems fine, except for the "Gateway" attribute. 

- What is this? 
- Can I have my own https://gateway.totalworlddomination.net service running? 
- Where can I configure this service?

**Comment by engelgabriel** [comment]
You only MUST use the gateway, if you want your users to use our mobile apps from our account on Google and Apple app stores. 

If you are building your own mobile apps, with your own certificates, you have to remove the gateway config and put your own certificates used to compile your own apps.
