### ISSUE TITLE
Inline code followed by a comma is not styled

### ISSUE THREAD

**Issue by sanbor** [RocketChat/Rocket.Chat#578]
Write the following message:
```
if the `inline_code` is followed by a `comma`, then it doesn't work.
```

Screenshot:

![screen shot 2015-08-25 at 13 05 00](https://cloud.githubusercontent.com/assets/51512/9472172/031977ba-4b2a-11e5-803f-e6b9c8a80d9e.png)

**Comment by engelgabriel** [comment]
Fixed by @geekgonecrazy
