### ISSUE TITLE
Internal hubot default user name should be lower-case

### ISSUE THREAD

**Issue by elespike** [RocketChat/Rocket.Chat#5781]
Note: installed with snap
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.1

https://github.com/RocketChat/Rocket.Chat/pull/5780

**Comment by engelgabriel** [comment]
@marceloschmidt can you create a migration to fix `InternalHubot_Username` on old servers?

**Comment by engelgabriel** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/5792
