### ISSUE TITLE
Stream error in exception log

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#5782]
Rocket.Chat Version: 0.49.3
Running Instances: 8
DB Replicaset OpLog: Yes
Nginx: Yes

I have the exception log setup (level 2) in the admin tool to push all exception information over to a channel called log_exceptions. Every time I start an RC instance I get the following error for every instance I start with the difference being the ip address for separate servers and the port numbers.

Network error: ws://localhost:3000/websocket: connect ECONNREFUSED 127.0.0.1:3000

These errors don't seem to affect anything but I want to make sure that is the case. I'm concerned that I'm missing a config parameter etc. that would fix this message since all the instances seem to be working together fine.

**Comment by beranPro** [comment]
Hi,
i have the same problem here in the current version.
I'm using docker swarm and the latest 3.5.2 Version.

**Comment by rodrigok** [comment]
@beranPro thanks. I'll close this issue since it's not a problem anymore.
