### ISSUE TITLE
The new search box overlaps with the 'online' status option

### ISSUE THREAD

**Issue by elespike** [RocketChat/Rocket.Chat#5783]
- This can be seen on demo.rocket.chat
- Screenshots attached
![no_online_status](https://cloud.githubusercontent.com/assets/14970655/22303650/391974d4-e302-11e6-8b38-e880a3d52445.png)
![no_online_status_2](https://cloud.githubusercontent.com/assets/14970655/22303649/39151e84-e302-11e6-8509-612d48b05063.png)

**Comment by Nemra1** [comment]
quick fix
```
toolbar {
    z-index: 1;
}
```

**Comment by engelgabriel** [comment]
:)
