### ISSUE TITLE
userlist not Not affected by user status 50.1

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5785]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog:
Node Version:4.7.2
 when users change status (offline ,online, away ,,etc )
User list Not affected like this 
![2017-01-25_182846](https://cloud.githubusercontent.com/assets/22897987/22307290/12b55e90-e34b-11e6-92b4-846855b9d3ed.png)

**Comment by engelgabriel** [comment]
This is a known problem reported in other issues. We are working to fix it.
