### ISSUE TITLE
Memory leak when uploading file in Chrome

### ISSUE THREAD

**Issue by teamsoo** [RocketChat/Rocket.Chat#5789]
Rocket.Chat Version: 0.50.1
Deploy Method: Docker
Running Instances: 1
Node Version: v4.7.1
Linux Chrome Version: 55.0.2883.87 (64-bit) 
Linux Memory: 24GB

According to Chrome's Task Manager, RocketChat page shows high memory consumption when uploading files (much higher than the actual file size). 

Page will crash when uploading file bigger than 4GB

Is this mean that RocketChat will store the whole file in client memory before upload to the server?

**Comment by engelgabriel** [comment]
@rodrigok am I right in thinking that this is a Chrome implementation and not Rocket.Chat's issue?

**Comment by teamsoo** [comment]
@engelgabriel I've checked with some other products that support file sharing. Uploading large files didn't cause any problem.

Maybe it's how Rocket.Chat processes the uploading file before it actually starts uploading the file that cause this issue.

**Comment by geekgonecrazy** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/6598 May close this.

**Comment by teamsoo** [comment]
@geekgonecrazy thanks.
