### ISSUE TITLE
OAuth in production results in redirect_uri_mismatch

### ISSUE THREAD

**Issue by danXyu** [RocketChat/Rocket.Chat#579]
![error](https://cloud.githubusercontent.com/assets/4897245/9478935/b0ec480e-4b48-11e5-9fc3-fe3c8b03282e.png)

Using Github Oauth, I set the proper Client ID and Client Secret through the admin page. The oauth works perfectly in a development environment, but when pushed to production, it results in a redirect_uri_mismatch as shown above (tested running 'node main.js' with env variables set).

Authorization callback URL when in production is set to:
http://104.131.8.9/_oauth/github

That IP Address resolves to the production app on the remote server, served with nginx.

**Comment by Sing-Li** [comment]
You MUST set the callback URL, and your ROOT_URL to the exact domain name.   Not IP address in one, and domain name in another.  It is a 'string compare' and will not 'resolve'.

**Comment by danXyu** [comment]
That was quick. It worked. I didn't know it was a string compare between the two values. Guess it wasn't much of an issue after all haha, thanks a ton though.
