### ISSUE TITLE
[Feature Request] match, filter or search for active channels (public, private, direct messages)

### ISSUE THREAD

**Issue by pedro-nonfree** [RocketChat/Rocket.Chat#5795]
In my situation, I have a lot of channels (public, private, direct messages), sometimes is difficult to find them or switch to them.

- I would like to have a general filter or search at the top of the channel list that when you start typing it only shows channels that are matched.

- When you scroll down in channel list, the seach/filter/match is still visible and available to use

- When you have text there, a cross symbol should be shown to note to the user that a match/search/filter is being applied (see image)

![filter applied](https://cloud.githubusercontent.com/assets/2603422/22331998/d757fa2c-e3ce-11e6-8849-594146e3df6a.png)

**Comment by MartinSchoeler** [comment]
Hey @pedro-nonfree , have you tried to use the ctrl+p command? It opens a user/channel search bar.
https://rocket.chat/docs/user-guides/keyboard-shortcuts

**Comment by pedro-nonfree** [comment]
@MartinSchoeler That's great, and enough for me.

But you know shortcuts are somehow advanced interaction with computer. Other people are also complaining about "too much channels". I think a more user-friendly option should be available like the one I presented. Ctrl+p looks like an extra feature for power users.

For example, I don't know if there is an option to search channels for people using it through Android and iOS (this people cannot use shortcuts).

So, could be this one, but integrated, always visible on top of the channel list?

**Comment by MartinSchoeler** [comment]
@pedro-nonfree actually we are implementing something like you said, take a look in our demo server https://demo.rocket.chat/

**Comment by pedro-nonfree** [comment]
@MartinSchoeler That's great! Just a detail. It should distinguish between the channels I already joined, and the other channels.

**Comment by engelgabriel** [comment]
@pedro-nonfree we are adding this distinction.
