### ISSUE TITLE
[Feature Request] by default and user friendly way to follow up unread messages / channels

### ISSUE THREAD

**Issue by pedro-nonfree** [RocketChat/Rocket.Chat#5796]
When you are subscribed to a lot of channels is difficult to follow the unread messages (scroll up, scroll down, click).

Is it possible to have a small list at the beginning of channel list with unread channels? or order by unread, and if not alphabetical? Would be nice to have all unread channels "in the same place": at the top.

**Comment by rebeld** [comment]
Doesn't My Account -> Preferences -> Unread Rooms Mode = True do that?

**Comment by pedro-nonfree** [comment]
Great! Why is not enabled by default this feature?

**Comment by engelgabriel** [comment]
Because some people get confused with the room links jumping around :)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:57850 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1cWo58-003o1A-9r
	for greg@biomassiv.es; Thu, 26 Jan 2017 11:43:34 -0600
Date: Thu, 26 Jan 2017 09:42:53 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1485452573;
	bh=cRA5Q2N11muMdjUmRas58SgyEiqNdAHwmyd1JLD0Nkk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LInQsQUd/QNEumM3QEULkad5Y/iP/w9evb+2oLbt6SWmemQNCmYd3N+/npS0MLRo3
	 q22SvDodnS2hvJvh1ElRNziP/JEJwvAcBKK1EvK2RFoo6cJT/ovITnLwNkG7EP4skJ
	 yzzGlFIzIkpAu3G0LSO0VFr/bB3PNcOz6jk7eo1o=

**Comment by pedro-nonfree** [comment]
And what about something like a bell icon that when you click show the notifications?

**Comment by Romich777** [comment]
Unread Rooms Mode was removed in v.0.59 ? Why ? This is very useful think.

**Comment by reko888** [comment]
it's not gone, look for 'side bar channel list mode'

**Comment by pedro-nonfree** [comment]
Sorry, I will close this issue because currently as there is a way to do it
