### ISSUE TITLE
Cannot send chat messages via email

### ISSUE THREAD

**Issue by mtcoliveira** [RocketChat/Rocket.Chat#5797]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog:
Node Version: V4.6.2

i`m trying to use the mail message function and i get this error:

34mI20170126-13:19:58.432(-2) Sending messages to e-mails: [ 'theemailiinput@gmail.com' ] 
[34mI20170126-13:19:58.437(-2) Exception while invoking method 'mailMessages' TypeError: Cannot read property 'defineLocale' of undefined at eval (<anonymous>:14:20) at eval (<anonymous>:10:4) at eval (<anonymous>:11:2) at [object Object].mailMessages (/opt/Rocket.Chat/programs/server/packages/rocketchat_channel-settings-mail-messages.js:119:29) at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1064:26) at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:2108:12) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1042:22 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1041:43 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1040:48 at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1018:23) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:880:89

right now i`m using the system with a pt-BR language, I took a test using English as language and the e-mails is send.

**Comment by n30ngruu3n** [comment]
I already have the same problem. Running RC 0.52.0 with german language setting.

Server log:

Exception while invoking method 'mailMessages' TypeError: Cannot read property 'defineLocale' of undefined   at eval (<anonymous>:30:20)   at format.m (<anonymous>:12:4)   at eval (<anonymous>:13:2)   at [object Object].mailMessages (/app/bundle/programs/server/packages/rocketchat_channel-settings-mail-messages.js:119:29)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1064:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)   at /app/bundle/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:1040:48   at Session.method (/app/bundle/programs/server/packages/ddp-server.js:1018:23)   at /app/bundle/programs/server/packages/ddp-server.js:880:89

**Comment by n30ngruu3n** [comment]
Persistent problem even in RC 0.53.0 with german language setting and the same errors in log..

**Comment by jhaohai** [comment]
same issue in 0.54 with chinese

**Comment by pmjunior** [comment]
Same issue in 0.53 with pt-br +1

**Comment by danielo926** [comment]
+1

**Comment by localguru** [comment]
same here 0.56.0 see #6179

**Comment by n30ngruu3n** [comment]
Still persistent in 0.57.1 (already german language settings)

**Comment by localguru** [comment]
Please reopen, #7846 doesn't fix it
