### ISSUE TITLE
Deleted image while trying to delete description

### ISSUE THREAD

**Issue by msklywenn** [RocketChat/Rocket.Chat#5807]
If you add a message to an image by mistake while trying to edit a different message, it's impossible to remove it without removing the image.

Steps to reproduce : 
1. Upload image
2. Press UP
3. Type something then enter to edit description
4. Press UP again (to fix)
5. Remove message associated with image
6. RocketChat prompts to warn user that message will be deleted

Expected:
RocketChat should remove associated text, leave the image and not warn the user. If the user wants to delete the image, it can use the regular cogwheel + trashbin icons.

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/6204
