### ISSUE TITLE
Direct Message Locked

### ISSUE THREAD

**Issue by lepetitjan** [RocketChat/Rocket.Chat#5808]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.1

Hi there, 
I was talking to a colleague and when I clicked on the INFO icon on the top right, I saw a toggle "Private". I thought a DM already was private, but it could not hurt to click it right?

Well I was wrong...when I toggled, I got thrown out of the DM as well as my collegue and we are not able to open a new DM to each other anymore. 
I went into Administration --> Rooms, but could not find our DM room in the list...

How can I revert the change?
And why is it possible to toggle private in a DM?

![screen shot 2017-01-27 at 13 02 21](https://cloud.githubusercontent.com/assets/6282726/22370404/9249d1c6-e491-11e6-9654-8ad767041e5c.png)

**Comment by lepetitjan** [comment]
Loggin out and back in seems to help. But we lost all of our previous messages.

**Comment by engelgabriel** [comment]
@karlprieb this is URGENT, and there are a few other issues opened about this.

**Comment by engelgabriel** [comment]
@rodrigok let's add a migration to fix the rooms that have been affected.
