### ISSUE TITLE
Security Implemented

### ISSUE THREAD

**Issue by chellem** [RocketChat/Rocket.Chat#5812]
Hello, 
May I know which security implementation exists in rocket chat?
The OTR is not ready (#36), is there others apart from HTTPS?
I've checked the documentation already, I know there's a section concerning security but there's nothing detailed.

Kind Regards,
Chellem

**Comment by kpcyrd** [comment]
Your messages are only protected by https and are stored in mongodb as plain text.

There is a feature called "OTR", but it's a [custom implementation][1] that I don't recommend for anything remotely serious. :)

[1]: https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-otr/client/rocketchat.otr.room.js

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

If you need additional information, please let me know. For now I'm closing this as the question is rather broad.

Except from OTR, this is correct:

> Your messages are only protected by https and are stored in mongodb as plain text.

Cheers
Thomas
