### ISSUE TITLE
Hubot doc is empty on website

### ISSUE THREAD

**Issue by BryanQuigley** [RocketChat/Rocket.Chat#5824]
https://rocket.chat/docs/administrator-guides/internal-hubot shows an empty page.

Rocket.Chat Version: n/a

**Comment by engelgabriel** [comment]
Can you please reopen this issue on https://github.com/RocketChat/Rocket.Chat.Docs ?

**Comment by BryanQuigley** [comment]
Found a dupe there, sorry for the noise -https://github.com/RocketChat/Rocket.Chat.Docs/issues/172
