### ISSUE TITLE
Assets and images url broken on proxy suburl installation

### ISSUE THREAD

**Issue by HighwayStar** [RocketChat/Rocket.Chat#5825]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0

I have problem with images and assets on installation configured to be located on https://mydomain.com/chat url.

Login page failed to show image with link https://mydomain.com/chatimages/logo/logo.svg
and chat window failed to show log located at https://mydomain.com/assets/logo.png its meant to be https://mydomain.com/chat/assets/logo.png

I also have issues #4832 and #5026

**Comment by Abraka** [comment]
Installation into subdir is loooong time broken. Just search here for subdir. It was reported many time over and over again. Looks like nobody care about it as it is a minor thing which only few people using...

**Comment by engelgabriel** [comment]
Indeed @Abraka we strongly recommend installing Rocket.Chat into a subdomain rather than a subfolder. Even creating automated tests is hard, because involve adding a proxy in the middle and there are many variations to what the configuration would look like. We try our best to keep it working on subfolders, but it has been a best effort and we have been counting on the community to find and fix bugs when they appear.

**Comment by HighwayStar** [comment]
Still same issue on just upgraded 0.54.1. 
```
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ +------------------------------------------------------+
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |                    SERVER RUNNING                    |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ +------------------------------------------------------+
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |                                                      |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |  Rocket.Chat Version: 0.54.1                         |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |       NodeJS Version: 4.5.0 - x64                    |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |             Platform: linux                          |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |         Process Port: 3000                           |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |             Site URL: https://projects.iszf.irk.ru/  |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |     ReplicaSet OpLog: Disabled                       |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |          Commit Hash: 309d617b8c                     |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |        Commit Branch: HEAD                           |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ |                                                      |
Mar 24 11:41:12 ubuntu-rocket nodejs-example[22451]: ➔ +------------------------------------------------------+

```

**Comment by HighwayStar** [comment]
Login page logo now works, chat page logo not https://mydomain.com/assets/logo

**Comment by recteurlp** [comment]
Another issue is open #6383
