### ISSUE TITLE
Resize Avatars

### ISSUE THREAD

**Issue by pew** [RocketChat/Rocket.Chat#583]
Avatars are uploaded in full resolution and are sometimes very large which causes Rocket.Chat to lag for a brief period of time (at least on heroku free). It also takes a while for low bandwidth clients to download the avatar until it's cached. Avatars should be converted to a smaller resolution and file size.

**Comment by rodrigok** [comment]
Good point.

Can you help us with this issue?

**Comment by pew** [comment]
I'm not sure, will try.
