### ISSUE TITLE
Public / Private Channel Name Uniqueness

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#5831]
Right now a channel must be unique whether it is public or private.

If user A creates a private channel called #dancingbananas and user B comes along and searches for dancingbananas.  Nothing will show up.  So user B tries to create that channel.  They will get:
![image](https://cloud.githubusercontent.com/assets/51996/22399882/58f95406-e56c-11e6-8421-28d1ffdda4e9.png)  This can be bad UX.  They are quickly confused as to why they can't create their channel.

One reason for not listing private groups is their names can be just as private as the contents in them.  But once they get this error message, we might as well list it for them because they know it exists. :grin:

One thought would be to allow a public channels to be named the same as private groups.  If a private group tries to switch to public it would not allow them without changing their name.

Obviously this has some trade offs.  Now switching back and forth between public and private has potential to be limited.

Thanks to @sergiusens @kyrofa for bringing this up!

**Comment by engelgabriel** [comment]
This cannot be changed (not easily), and I don't believe this is an issue worth working on. The same problem would happen if two different users try to create private channels with the same name. We can clarify the message to avoid confusing. @geekgonecrazy please suggest a better wording for the error message?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  This is more a matter of messaging in response :)
