### ISSUE TITLE
Discrepancies between web and desktop version

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#5837]
Rocket.Chat Version: 0.50.1

Hello, some of my users are complaining of the following discrepancies between the web and desktop version:

1. When using both the desktop app and using rocket chat directly from the browser, received messages appear in the web version but does not appear in the desktop version. After you reload the server in the desktop app, messages are synced again
2. Channels marked as favorite from the browser does not appear in the desktop app. 

Anybody else having similar issues?

**Comment by engelgabriel** [comment]
You need to provide all the information from your Admin->Info page.

**Comment by akachapati** [comment]
Thanks @engelgabriel We've a couple of implementation of rocket.chat that we use for different reasons and have extended one of them with some custom code. I noticed that it's breaking only in the version that we've extended which is running on 0.48.2

Is if there's anything we should be looking at to resolve this issue? Any help will be much appreciated.

**Comment by engelgabriel** [comment]
can you upgrade to the latest version?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.

If the problem occurs again please reopen this. Thanks!
