### ISSUE TITLE
Links are not correctly detected when they contain a triple ...  ellipsis 

### ISSUE THREAD

**Issue by brendanheywood** [RocketChat/Rocket.Chat#5838]
Rocket.Chat Version: 0.49.3
Running Instances: 
DB Replicaset OpLog:
Node Version:

![image](https://cloud.githubusercontent.com/assets/187449/22411304/8277e5aa-e6f6-11e6-8d12-db9ea68f713e.png)

The weird thing is that the link is correctly detected enough to go and load the preview, but the original link doesn't work, the preview link does.

**Comment by olafleur** [comment]
This is an Autolinker issue. Will fill an issue there.

**Comment by debdutdeb** [comment]
Closing since not present in the latest.
