### ISSUE TITLE
Changing fireUrl from 'file-upload' to something else

### ISSUE THREAD

**Issue by teamsoo** [RocketChat/Rocket.Chat#5839]
Rocket.Chat Version: 0.50.1
Running Instances: 1
Node Version: v4.7.1

Is there a way to change fileUrl from '/file-upload/' to something else?
This is because some network proxy usually block URLs that contain 'upload' word.

Normally, fileUrl is '/file-upload/' + file._id + '/' + file.name

**Comment by engelgabriel** [comment]
@rodrigok can this be turned into a config?

**Comment by rodrigok** [comment]
Sure, we can create a new setting for that

**Comment by louisemessage** [comment]
As there haven't been any comments on this issue for more than a year, I am closing it for the meantime.
