### ISSUE TITLE
integrate rocket chat with existing CRM

### ISSUE THREAD

**Issue by neha1deshmukh** [RocketChat/Rocket.Chat#5840]
Hello,

Can anyone explain for me, how we can integrate rocket chat with existing CRM for support? I am not able find any documentation about this.

**Comment by graywolf336** [comment]
It would depend heavily on the CRM system you're using and how they allow integrations.

**Comment by engelgabriel** [comment]
@neha1deshmukh what CRM are you looking into?

**Comment by engelgabriel** [comment]
@MartinSchoeler can you add the LiveChat api to the documentation? Ask @sampaiodiego for help.

**Comment by sampaiodiego** [comment]
@engelgabriel the docs are already there https://rocket.chat/docs/administrator-guides/livechat/#integrations

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
