### ISSUE TITLE
MongoDB use all Disk ressources

### ISSUE THREAD

**Issue by NQNetwork** [RocketChat/Rocket.Chat#5841]
Hello,

Sometimes we have the processs mongod  that use all of disk ressources.
We can see that with an iotop. The server is unreachable when this problem occurs.

We are about 70 users on the tchat, usually is all right.

It's seems to be a "rotate" of the DB content, but I have find anything about that.

Have you ever encountered this problem?

Thanks.

Rocket.Chat Version:  0.50.1
Running Instances: 4
DB Replicaset OpLog: 
Node Version: 4.6.2

**Comment by engelgabriel** [comment]
What is the status of your DB Replicaset OpLog?

**Comment by NQNetwork** [comment]
Hello,

My OpLog is disabled.
And in the console we have : 
rs.status();
{ "ok" : 0, "errmsg" : "not running with --replSet", "code" : 76 }

Thanks.

**Comment by engelgabriel** [comment]
You MUST enable it, and configure Rocket.Chat to use it.

**Comment by engelgabriel** [comment]
All Meteor apps use a busy pooling mechanism when OpLog is not enabled, and that can be very hard on the database.
