### ISSUE TITLE
[Feature request] Specify default role for OAuth users

### ISSUE THREAD

**Issue by jeromepin** [RocketChat/Rocket.Chat#5842]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.2

Hi,

We're using Rocket.Chat for our internal chat system (which is awesome by the way ! Great Work !). Now we would like to open our chat system to the outside world using Github's OAuth. The problem is that users are in the 'user' role by default, which is too permissive for our external user.

I would like to be able to specify a default role for external users (i.e the ones who are logged-in through Github). It's looks pretty similar to [this issue](https://github.com/RocketChat/Rocket.Chat/issues/5037) by the way.

Is it planned yet ? Did I miss something ?

Thanks in advance :)

**Comment by marceloschmidt** [comment]
Sorry, I referenced the wrong issue on my PR.
