### ISSUE TITLE
Windows The server is not enabled for mobile apps

### ISSUE THREAD

**Issue by smoslinux** [RocketChat/Rocket.Chat#5845]
Rocket.Chat Version: 0.34.0
Running Instances: Windows_NT
DB Replicaset OpLog:
Node Version: v4.5.0

Hi all,

I installed Rocket Chat successively and after the installation, i try to login via mobile iphone 7 but its said: "The server is not enabled for mobiles apps."

I checked all familiar issue regarding this error but nothing. My SSL is A checked with sslabs.

Do someone has some suggestion what to try?

**Comment by TheReal1604** [comment]
@smoslinux You already checked the docs?

https://rocket.chat/docs/installation/manual-installation/windows-server/

The docs saying that the mobile apps are not supported atm if you install Rocket.Chat on a Windows Server.

![image](https://cloud.githubusercontent.com/assets/5877910/22497524/9741c89a-e852-11e6-96cb-eb06c753ee73.png)

Also your version of rocket.chat is very old, maybe you can update it to the latest?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
