### ISSUE TITLE
Create new space about the profile

### ISSUE THREAD

**Issue by carolsilveira** [RocketChat/Rocket.Chat#5849]
![screen shot 2017-01-30 at 17 58 18](https://cloud.githubusercontent.com/assets/24963820/22439242/0228d40c-e716-11e6-981b-745017168305.png)

**Comment by engelgabriel** [comment]
➤ Thiago Sanchez commented:

[Gabriel Engel](https://app.asana.com/0/154207300337537/list) Can you give more details about this task?

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/18194
