### ISSUE TITLE
how create admin with snap?

### ISSUE THREAD

**Issue by rafaelmr2** [RocketChat/Rocket.Chat#5855]
Hi,

I installed rocket chat with snap in Ubuntu 16.04. I set the env variables to create admin and restart server (systemctl restart snap.rocketchat-server.rocketchat-server.service) but the login is still invalid. I search web, git hub and docs but can't find a solution. How can I create admin account with snap server?

Thanks,

Rocket.Chat Version: Snap is the last version, right?
Running Instances: Snap
DB Replicaset OpLog:
Node Version: Snap version

**Comment by engelgabriel** [comment]
The first user to register will be made admin. Do you need it to be pre configured with something else?

**Comment by rafaelmr2** [comment]
Thanks, that's works.

**Comment by masterharry** [comment]
how to chage admin password in rocketchat ? i forgot password and now i am not able to login. please help me out.
