### ISSUE TITLE
Channels not grouping messages from the same day when users have different languages

### ISSUE THREAD

**Issue by danimaiochi** [RocketChat/Rocket.Chat#5859]
This happend suddenly, I don't know what information is important but, the user with the franz has left the group and then I noticed this.
before, the channel was working just fine

![image](https://cloud.githubusercontent.com/assets/8352137/22475044/e9b4419a-e7c4-11e6-8fde-e8aa9f97e675.png)

Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

**Comment by engelgabriel** [comment]
This is really odd, I cannot even think how to try to reproduce it :(

**Comment by danimaiochi** [comment]
yeah, I know, we have this group for quite some time and this is the first time it happend.
the 3 of us use to leave the computer and the rocketchat open for days, and sometimes when we go to the rocketchat, messages are not showing and we need to refresh the page.
this happened after one of these moments

**Comment by engelgabriel** [comment]
Lets see if the problem persists on the next release? Please install and test with version 0.51.0 when it comes out.

**Comment by karlprieb** [comment]
Hi @danimaiochi have you tested with 0.51?

**Comment by danimaiochi** [comment]
Hello! Unfortunately I lost the scenario, the others on that chat doesn't have it anymore, so if we update to .51, we won't know for sure of the problem was fixed :(
