### ISSUE TITLE
[Mobile Apps] App in background stills "reading" messages

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#586]
Steps to reproduce (on Android):

* Open the app
* Go to #general room
* Closes the app (hit 'home' button)
* Open https://demo.rocket.chat on a browser
* Go to another channel, e.g. #core-team
* You'll notice that every new message on #general room will be "automatically" read by tha app

**Comment by geekgonecrazy** [comment]
Can we do window blur / focus to set away on mobile?

**Comment by engelgabriel** [comment]
I believe this was fixed.
