### ISSUE TITLE
Shouldn't stream-notify-user/notification return msg object?

### ISSUE THREAD

**Issue by wandonye** [RocketChat/Rocket.Chat#5864]
Rocket.Chat Version:  demo.rocket.chat (?50.x?)
Running Instances: 
DB Replicaset OpLog:
Node Version:

Currently stream-notify-user/notification return an object like this:

    payload:Object
        _id:"qYvsGwpEAEEpWRaaY"
        rid:"YdpayxcMhWFGKRZb3vqtNHfvcz3ttFh8tW"
        sender:Object
            _id:"YdpayxcMhWFGKRZb3"
            username:"hubot"
        type:"d"
        text:"test"
        title:"@hubot"

In case someone uploads a file, such as an image or video, the subscriber will have to make another call to request the msg. Why not just send the entire message object to the subscribers?

There is another subscription available: stream-notify-user/subscriptions-changed. This one returns many information about a new msg but not the msg itself(not even the text of the msg). So I'm really confused about how the streams are designed. I would expect stream-notify-user/notification is used for notification badge, and stream-notify-user/subscriptions-changed is for sending the new msg to the client. But it seems this is not how it works for now.

**Comment by wandonye** [comment]
I guess stream-notify-user/message is the one used to receive the msg?

**Comment by engelgabriel** [comment]
@rodrigok can you help here?

**Comment by wandonye** [comment]
I can confirm now that
`stream-room-messages/(room-id)` is the right stream to receive the complete msg.
`stream-notify-user/subscriptions-changed` and `stream-notify-user/notification` can be used to send notification
