### ISSUE TITLE
Typing indication when someone is typing in group/1:1 chat.

### ISSUE THREAD

**Issue by spathare21** [RocketChat/Rocket.Chat#5866]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: 
Node Version: v4.5.0

Can we have a typing indication when someone is typing in group/ in 1:1 chat like whatsapp/Hangout indication in group and personal chat.  

i.e abc is typing, if more than one people then 2 peoples are typing something like that.

**Comment by TheReal1604** [comment]
@spathare21 This is already implemented left under your text box?!

**Comment by spathare21** [comment]
ohh sorry i think my rocket chat version is 0.46.0  thats why it is not showing.
