### ISSUE TITLE
[Q] How to change the default settings for channel notifications?

### ISSUE THREAD

**Issue by gradler** [RocketChat/Rocket.Chat#5867]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.5

Each channel has a mobile & desktop notification settings.
The default value is "mentions".

However, I would like to our server's default to "All messages".
How can I do this?
I do not want to change every new channel I create.

Thanks for your help!
G'day mate

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/4339

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/7479
