### ISSUE TITLE
ldap userprofile personel logo sync issue

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#5868]
Rocket.Chat Version: 0.50.1 ( Ubuntu 16.04 snap )
Running Instances: 1
DB Replicaset OpLog: disabled

Users are created via ldap login.
Settings: 
- ldap sync is on
- sync user logo is on
- Users are allowed to upload new logo

Tests: 
Uploaded new UserLogo.
Relogged.
ldap User Logo is synced from ldap

Suggestion:
If "Users are allowed to upload new logo" then the ldap UserLogo is only synced on initial UserCreation.
Yes, I want the ldap sync for everything else, but the UserLogo.

Also a customization for the usage of "thumbnailPhoto" in the admininterface would be nice. ( like: i.e. thumbnailPhotoHIGHRES )

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

IIRC the users collection now flags the avatar source in MongoDB. I'm closing this. If you can still reproduce this o 0.62.1, please get back to me and I'll happily reopen.

Cheers
Thomas
