### ISSUE TITLE
Variable required in rocketchat.desktop (.deb package)

### ISSUE THREAD

**Issue by kurobeats** [RocketChat/Rocket.Chat#5869]
When launched the desktop app is iconless and independent from the launcher. This line added to the rocketchat.desktop file ensures the launcher and the app remain as one on the desktop.

`StartupWMClass=Rocket.Chat+`

So, once complete, rocketchat.desktop will appear as the following:

```
[Desktop Entry]
Name=Rocket.Chat+
Comment=Rocket.Chat Native Cross-Platform Desktop Application via Electron.
Exec="/opt/Rocket.Chat+/rocketchat"
Terminal=false
Type=Application
Icon=rocketchat
StartupWMClass=Rocket.Chat+
```

**Comment by MartinSchoeler** [comment]
@kurobeats i think this issue should be on the electron repository, please reopen this issue here: https://github.com/RocketChat/Rocket.Chat.Electron , Thanks!
