### ISSUE TITLE
Microphone button doesn't work in mobile

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#587]
Microphone button (one of the coolest things in rocket.chat besides other many) to record audio next to chat text box doesn't seem to be functioning in mobile version (on android in my case).

**Comment by Sing-Li** [comment]
Please move this issue over to the [cordova project](https://github.com/RocketChat/Rocket.Chat.Cordova).   It can be fixed, per platform, there for sure.

**Comment by rockneverdies55** [comment]
Alright I was kind of on the fence where to put this.

@Sing-Li - thanks, will do so.

**Comment by Sing-Li** [comment]
@rockneverdies55   we're slow to start there because we needed a way to link to the main repo without copying it over ... and end up merge down endlessly.   so just hoping @geekgonecrazy will come up with some solution

**Comment by rockneverdies55** [comment]
Should we create another thread for discussing that then?

**Comment by rockneverdies55** [comment]
What comes to my mind immediately is to `bower install` the main project as a dependancy...

**Comment by geekgonecrazy** [comment]
@Sing-Li ah yes.. that will be an interesting problem... Unless we do like with the electron app?

**Comment by rockneverdies55** [comment]
What's wrong with bower installing it?

**Comment by geekgonecrazy** [comment]
@rockneverdies55 nothing is necessarily wrong with it.  Adding bower also means adding a config file, and wrestling with getting it to put the files where we want.  

Almost makes sense to make it part of our build task.  This way we don't have to keep anything up to date.  It can just fetch latest commit/release as part of the task.

**Comment by rockneverdies55** [comment]
I don't think it's any hard to configure bower at all. Very straight forward stuff.

You create `bower.json` file once, if all you want is to fetch the latest then perhaps you never need to touch it again.

**Comment by Sing-Li** [comment]
Sorry guys. Just got stable wifi again @ sbucks.
@geekgonecrazy  ... please see 'advanced build customizations' section here https://github.com/meteor/meteor/wiki/Meteor-Cordova-Phonegap-integration  ... there is a shadow dir override built in.  Plesse take the lead on this one. We'll run with whatever solution you put up ... until we can't stand it  ;-)

**Comment by Sing-Li** [comment]
@rockneverdies55  ...yes. please start a new thread over at cordova to continue the discission. I will chime in there.
