### ISSUE TITLE
Video conference on private channels still visible though it was being disabled

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5870]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.6.2
Video conference on private channels still visible except in the public channels though it was being disabled in channel on the Admin settings.

**Comment by ggazzo** [comment]
@zorenleo , could you be more specifc? There are 2 "ways" to do a video conference. I made some test but works fine.

1º way -> webrtc button into "room info, or user info"
![image](https://cloud.githubusercontent.com/assets/5263975/24117588/88e2acae-0d89-11e7-9a87-3aa8ab369912.png)

2º way ->jitsi button on right bar
![image](https://cloud.githubusercontent.com/assets/5263975/24117482/2b7ac4a2-0d89-11e7-994f-8be8afa02760.png)
