### ISSUE TITLE
Request: Add more state of "invisibility" for user

### ISSUE THREAD

**Issue by Rohlik** [RocketChat/Rocket.Chat#5873]
Hi,

It would be very nice to add more level of "Invisible" status.

For example:
**"invisible"** - Same behavior as now
**"semi-invisible"** - Invisible status in public channels and in search window, but **visible** in private groups and direct chats.

**Why?**

Because sometimes you don't want to be disturbed by others, but you still want working with close co-workers.

**Comment by engelgabriel** [comment]
Thanks for the suggestion, but this requires A LOT of work to achieve, and I don't think we will be able to do it. If you'd like to develop this, I'd be happy to review a pull request.
