### ISSUE TITLE
Add "Last Message" to the "Rooms" Admin View

### ISSUE THREAD

**Issue by DiJu519** [RocketChat/Rocket.Chat#5877]
An addition column in the Administration -> Rooms channel to allow an Admin to see when the last message sent was.

This would provide an easy method to audit and delete old channels, thereby preventing a huge log of channels in the "Channels" drop-down.

Thanks.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
