### ISSUE TITLE
Password reset emails not working

### ISSUE THREAD

**Issue by kenspi** [RocketChat/Rocket.Chat#5878]
When users try to reset their password via the "forgot your password" link, they see an error in their browser stating "Error trying to send email: Message delivery failed".  The log only indicates this error:
`[34mI20170201-17:55:22.254(0) [34mMeteor ➔ method sendForgotPasswordEmail -> userId: null , arguments:  { '0': '<email_address_removed>' } `

The SMTP settings have been tested and are functional (test emails work, new account notifications work).

Possibly related, when an admin creates a new account, the user cannot login using the password that was generated. If the password is manually set, the user still cannot login using the manual password.

Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: runtime v.4.7.1

**Comment by Isabello** [comment]
Password reset is broken for certain providers for us as well. It works with gmail but not hotmail.

**Comment by engelgabriel** [comment]
Can you give more info? Are the users form a specific domain?

**Comment by kenspi** [comment]
Yes, the accounts are from the same domain, as is the main admin account. This domain is defined in the accepted domains setting.

**Comment by engelgabriel** [comment]
@RocketChat/core ideas?

**Comment by cescgie** [comment]
Mine is broken as well. I got this error:

> Error trying to send email: Mail from command failed -501 Syntax error in parameters

SMTP test is working but reset password shows above error.
I use sendgrid and docker.

**Comment by rasos** [comment]
Password reset works here with 0.52 and our own SMTP server.
However:
- Sent link is neither clickable nor translated nor nicely formatted.
- New password given needed to contain at least one number. Where are the password rules defined?

**Comment by pierreozoux** [comment]
Can you detail if you set up MAIL_URL or Admin settings for SMTP or both?

**Comment by kenspi** [comment]
I've since rebuilt the system from scratch using a conventional build rather than docker and it seems to be OK now.

**Comment by cescgie** [comment]
Thank you for all your responses.
I have version 0.53.0 now and it seems work, but...
> We have sent you an email with password reset instruction. If you do not receive an email shortly, please come back and try again.

i have tried couple times but i still don't get an email even i got above message

**Comment by teamsoo** [comment]
@engelgabriel  Mine isn't working now (it used to work long time ago. just received a report from user).

Snap Rocket.Chat Version: 0.53.0
NodeJS Version: 4.7.3 - x64 
Platform: linux 
ReplicaSet OpLog: Disabled 
Commit Hash: cbdc26ded8
Commit Branch: HEAD 

Log
`rocketchat_lib rocketchat_lib.js:1092 Meteor ➔ method sendForgotPasswordEmail -> userId: null , arguments:  { '0': 'email@company.com' }`

Forgot password: Custom is False
The SMTP setting is working OK. I received an email from Test SMTP Settings button

**Comment by cescgie** [comment]
Ok i finally found the problem.
This is message that i got in my sendgrid from each email activity that had been blocked from sendgrid

> Reason
[XXXXXXX] Our system has detected that this message is not RFC 5322 compliant: 'From' header is missing. To reduce the amount of spam sent to Gmail, this message has been blocked. Please visit https://support.google.com/mail/?p=RfcMessageNonCompliant and review RFC 5322 specifications for more information.XXXXX - gsmtp 

So... after i changed my email to another email except gmail, i finally see all response messages from my rocket chat!!!

**Comment by teamsoo** [comment]
@cescgie You're saying that RocketChat password reset email module might not support sending email from Gmail? Because I can send test email from SMTP setting page.

**Comment by geekgonecrazy** [comment]
It appears this is just a matter of an email header missing. Do you have a valid from address set @cescgie?

**Comment by teamsoo** [comment]
@geekgonecrazy Hi, thanks for the reply. Can you also check my from address below.

![Image of SMTP setting](http://imgh.us/Screenshot_from_2017-03-31_11:40:13.png)

The test email works fine with the configuration but not the forget password email.

Thanks

**Comment by geekgonecrazy** [comment]
Does the verification email send?  When you sign up for a new account?  You'll have to have verify emails turned on I believe

**Comment by teamsoo** [comment]
@geekgonecrazy The Email Verification doesn't send to new user. Only welcome email with password was sent to user and the user can't login with the password (maybe it's because the Email Verification step doesn't work)

Please suggest.

**Comment by geekgonecrazy** [comment]
@RocketChat/core it appears that the emails that are sent via the accounts package are missing the from header we set.  Ideas?

**Comment by pierreozoux** [comment]
@teamsoo Can you try restarting your server after changing your emails details and try sending a forgot password email

**Comment by cescgie** [comment]
@teamsoo actually i only set my smtp via docker-compose.yml. 
Yes. I don't set my EMAIL FROM header because as far as i know there is no option to set your email form in rocket chat docker-compose.yml

**Comment by teamsoo** [comment]
@pierreozoux I have both docker and snap version of rocket chat installed on 2 different machines. I tried restarting both and the forgot password still doesn't work on both instances.

The following error message keeps showing
![Error](http://imgh.us/Screen_Shot_2560-04-01_at_12.28.20_AM.png)

Is it works on your system? Are you using Gmail?

**Comment by pierreozoux** [comment]
@teamsoo actually, don't use this kind of `from`, it is not supported, just use the email.
Can you also check server errors?

Here we are again losing time debugging this because the `test email` and `the forgot password email` are 2 different functions:
https://github.com/RocketChat/Rocket.Chat/issues/6196

**Comment by geekgonecrazy** [comment]
Agreed if we get that merged and use the single method or all email sending I think the issue described here will go away

**Comment by teamsoo** [comment]
@pierreozoux @geekgonecrazy  @cescgie 

I changed From Email to just info@company.com and the reset password email works again. Thank you so much.

**Comment by teamsoo** [comment]
I was following this guide in https://rocket.chat/docs/administrator-guides/notifications/email

If those kind of from is not supported, maybe someone should update the document?

**Comment by arungcs** [comment]
This doesn't seem to have been fixed in the most recent release (version 0.55.1). I tried all the suggestions here including the info@company ... SMTP test works just fine - but forgot password doesn't - gives me the syntax error message. 

Any help or pointers on how to resolve?

**Comment by teamsoo** [comment]
My docker deployment is also 0.55.1
The forgot password works just fine. Can you show me your current SMTP configuration?

**Comment by arungcs** [comment]
SMTP seems to be working fine (when I try "send a test mail to my user", I get the email)... it goes through my Mailgun.org account. Forgot password is the thing that doesn't work and I am not sure how to debug it... 
<img width="266" alt="screen shot 2017-05-02 at 1 22 42 pm" src="https://cloud.githubusercontent.com/assets/17802192/25637625/8014b8ce-2f3a-11e7-9392-51c53b174afc.png">

**Comment by sscholl** [comment]
@arungcs same here 
+1

**Comment by sscholl** [comment]
this issue was closed via #6940 in 0.56.0 FOR ME

Go to Administation->E-Mail->SMTP->Protocol (smtps)

**Comment by midnightcodr** [comment]
I have 0.56.0 using Amazon SES. Test email works but password reset gives me a slightly different error (no detail error message given):

> Error trying to send email: Mail from command failed

Settings:
```
Protocol: smtp
Port: 587

```
I also tried with the followings
```
Protocol: smtps
Port: 465
```

It makes no difference in the final result.

**Comment by geekgonecrazy** [comment]
@midnightcodr we use Amazon SES and just rest my password on our community server.

One thing you might check... has the email been verified for the user you are trying with?  Also, did they login with twitter oauth?

**Comment by midnightcodr** [comment]
@geekgonecrazy The sender's email address has been verified. As a matter of fact, the same setting has been used in many programs without issues. We are not using twitter oauth for our chat server.

**Comment by midnightcodr** [comment]
Never mind, the problem was fixed by restarting the chat server.

**Comment by pwilkin** [comment]
Had the same - restarting the server fixed the problem of the missing "From" header.

**Comment by santhosh9** [comment]
I am using an email hosted at hostgator for smtp and it sends emails to only those emails that are related to my domain, none of the emails or forgot password or verification mails go to gmail accounts, any user signed up with gmail does not get any emails, does anyone know how to fix this???

I installed rocketchat in digital ocean centos server and using the IP to access the rocket chat. Installed rocket chat recently by following instructions on the rocket chat docs, so the versions used are recent ones...

Anyone else facing same issue? can someone help me with this?
Thanks!

**Comment by santhosh9** [comment]
is there a particular link where I can get some help regarding this application and issues related to this?
I am waiting for someone to help me with the smtp issue, so that I can try pushing this to live.

thanks!

**Comment by teamsoo** [comment]
@santhosh9 try posting it on #support channel in https://demo.rocket.chat
The support team might be able to help.

**Comment by santhosh9** [comment]
@teamsoo I have done that already and no response there. I will try again to contact them there and will check.
thanks.

**Comment by rodrigok** [comment]
Are you guys still having problems with reset password email?

**Comment by teamsoo** [comment]
My 0.59.3 deployment works fine. Thanks.

**Comment by rodrigok** [comment]
I'll close this issue, please let me know if you still have problems with reset password email and we can open it again.

**Comment by paulkernstock** [comment]
I am actually having this error on this server:

+----------------------------------------------------------+ 
|                      SERVER RUNNING                      | 
+----------------------------------------------------------+ 
|                                                          | 
|  Rocket.Chat Version: 0.71.1                             | 
|       NodeJS Version: 8.11.3 - x64                       | 
|             Platform: linux                              | 
|         Process Port: 3000                               | 
|             Site URL: https://chat.xn--kernstck-c6a.com  | 
|     ReplicaSet OpLog: Enabled                            | 
|          Commit Hash: e73dc78ffd                         | 
|        Commit Branch: HEAD                               | 
+----------------------------------------------------------+ 

I also had the `From` field customized in in the `E-Mail` admin setting pane. When trying to reset a user's password, I got the error message "Mail command failed." on the client (browser, "Unknown error" on iOS client). When I reset the `From`-field everything is working as expected.

**Comment by paneda1998** [comment]
Hey
I have some problems with reset password

after i send request i didnt receive any email i check yahoo gmail hotmail and...
also there are no errors
just didnt receive any email...
i check spam too.

and for more details : in creating account i receive emails and everything is ok
