### ISSUE TITLE
Pinned already pinned msg

### ISSUE THREAD

**Issue by Rohlik** [RocketChat/Rocket.Chat#5879]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: True
Node Version: 4.7.2

You can pinned already pinned message. Screen tell you more.

![image](https://cloud.githubusercontent.com/assets/2051154/22521900/dbc0ec78-e8b9-11e6-979e-a10ea3bcb858.png)

**Comment by graywolf336** [comment]
This only affects compact mode viewers.
