### ISSUE TITLE
Current channel should show on search results so we can easily go back to it

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#5880]
![image](https://cloud.githubusercontent.com/assets/1986378/22523921/449a4f62-e8a8-11e6-9511-567d257fd014.png)

When you have an open channel and you go to the administration and then you want to go back to your current channel, you'd have to find it by scrolling instead of quickly accessing it in your recent channels.

**Comment by engelgabriel** [comment]
We already have an issue to go back to the current channel when you close the admin.
