### ISSUE TITLE
Extremely slow or unsuccessful logins

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#5881]
Since our latest upgrade we observe login times of up to 20 seconds or the browser timed out completely (only three dots running), but not at each attempt. 
No special load on mongodb or CPU observed, though, 4GB RAM is plenty, only few concurrent users.
Anybody else having this issue?

Somebody observed this behaviour with Meteor 1.4.2.3 and could resolve the issue when downgrading to 1.3.5.1:  https://forums.meteor.com/t/meteor-login-method-is-very-slow/31229  - but I guess this is not an option.

We are on latest Rocket.Chat Version: 0.50.1 - observed on two separate instances (test / production), continuos upgrades done since 0.34 and had a long period of quick responses.

**Comment by engelgabriel** [comment]
How many process instances running in productions? Do you have OpLog enabled?

**Comment by rasos** [comment]
Here only one instance is in production. But we have currently only very few concurrent users and node does not use much CPU, server load is around 0.05, mongod however may spike to 80% CPU when logging in.
I don't think we use OpLog, typical response times in the mongo log are 100ms.

**Comment by rasos** [comment]
Reason was that MongoDB log grew to 700MB in /var/log/mongodb
Applied logrotate. Sorry, this is definetely a sysadmin issue ;-)
Much faster experience now.
