### ISSUE TITLE
Quick Switcher aka Shortcuts

### ISSUE THREAD

**Issue by NargiT** [RocketChat/Rocket.Chat#5887]
Hello,

Is it possible to implement a quick way (shortcuts) as it is done today with Slack (QuickSwitcher CTRL+K). This is the only think that block me to use 100% rocket chat because I have to use the mouse.... :)

**Comment by Jannibal** [comment]
Ctrl - P

**Comment by rodrigok** [comment]
@NargiT `CTRL+P` / `CMD+P` solves your problem?

**Comment by engelgabriel** [comment]
@karlprieb lets give some visual hint about the  `CTRL+P` / `CMD+P`  on the search element.

**Comment by karlprieb** [comment]
Fixed in #6034
