### ISSUE TITLE
[FeatureRequest] Allow users to delete themself

### ISSUE THREAD

**Issue by childnode** [RocketChat/Rocket.Chat#5889]
to say it out loud simple stupid:
https://demo.rocket.chat/account/profile has no button for "delete (my) profile / user / account"

not even on a demo instance this is a good to have but also for those who just want to stop using their account, no longer being able to get DMs anymore which is like calling to /dev/null in a case of an unused account.

Problem I see we have to discuss (or perhaps it already has been?!):
* what about conversations?
  * is the author "anonymous" afterwards the deletion was done?! then this might relate to #604 
  * is the author's username still visible and blocked for re-registration?

any personal information, either profile picture or informational data should be removed anyway

**Comment by nbaum** [comment]
This feature already exists, but must be enabled in the "Accounts" page of administration: it's the first option there. Enabling it adds a "delete my account" button to users' "profile" page.

**Comment by childnode** [comment]
oh ... ups 🙃 i.e. just looked for s.th. in https://rocket.chat/docs/administrator-guides/permissions/ 
I see ... and any of it's data is deleted, even his messages and private channels ... and the nick is free again for registration ... then ... I will go forward to look for requests or file one 
1. to keep old messages of deleted users
1.a. mark them "anonymous"
1.b. delegate private channel permissions
2. at least mark points in conversions that has been deleted
