### ISSUE TITLE
Integrations not working

### ISSUE THREAD

**Issue by NQNetwork** [RocketChat/Rocket.Chat#5896]
Hello,

After this issue https://github.com/RocketChat/Rocket.Chat/issues/5841 we have sold our problem by updating the docker-composer.yml with your new file.
But after that, our integrations like Giphy not working. 
When we try to use it, we have this error log:

Exception in callback of async function: TypeError: Cannot read property 'statusCode' of null   at /app/bundle/programs/server/packages/rocketchat_integrations.js:1316:30   at runWithEnvironment (packages/meteor.js:1176:24) 

Thanks.

Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Active 
Node Version: 4.7.1 
Running with docker-compose

**Comment by manuelbachl** [comment]
Hi there, could anyone determine if this is a RC related issue or if we have to adjust our giphy integration? If so, please open an issue here: https://github.com/FinndropStudios/GifRocket
Thanks in advance for figuring out - unfortunately we're limited in time at the moment

**Comment by thiesschneider** [comment]
We are running the same version and it is working...

**Comment by NQNetwork** [comment]
@manuelbachl , the problem is not just for the Giphy integration. We have an integration for Redmine, and this is the same issue.

**Comment by graywolf336** [comment]
This happens when the result from going out to the urls doesn't work and errors out.

**Comment by manuelbachl** [comment]
checked this on our RC instance this weekend and it worked like a charm. We just reintegrated the whole integration again.

**Comment by NQNetwork** [comment]
Hello,

When we try a curl on an url with the container, it's appear that Rocket.Chat try to connect by proxy.domain.com. How to disable that?

docker exec -it b47060af2214 curl -l  "https://api.giphy.com/v1/"
curl: (7) Failed to connect to proxy.domain.com port 1080: Connection timed out

**Comment by graywolf336** [comment]
Have you setup a proxy for it to use? As Rocket.Chat by default won't try to proxy (that I'm aware of) unless it has been told to.

**Comment by rodrigok** [comment]
@NQNetwork You should remove the `HTTP_PROXY` and `HTTPS_PROXY` environment variables from your [docker-compose.yml](https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml?ts=2#L15-L16)  or change to your proxy settings.

**Comment by rodrigok** [comment]
Please reopen this issue if the problem persists

**Comment by anthok** [comment]
I'm having the same issue except I'm running through snap. Is there a specific way to set the proxy through snap/systemd. I've tried setting the EnvironmentFile=/etc/environment is the service files of caddy and mongo.
