### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#5899]
Rocket.Chat Version: 0.50.1
Running Instances: 1

Issue: when editing the "layout"-option in the administration area, specifically the footer, the change is not applied. All the other items change correctly, all but the footer.

How to replicate? Browse to `Administration > Layout > Content > Side Navigation Footer` and try to put anything in the textbox and apply the change. The change will not be visible even when reloading the browser.

Am I the only one facing this issue?

**Comment by engelgabriel** [comment]
@MartinSchoeler can you please try that on the `develop` branch?

**Comment by MartinSchoeler** [comment]
@engelgabriel In develop branch it's working properly, maybe was it already fixed?

**Comment by engelgabriel** [comment]
@k0nsl can you test with the develop branch?

**Comment by k0nsl** [comment]
I currently cannot test, I'm afraid. But if you say it is fixed, then I trust your word :)

**Comment by k0nsl** [comment]
I upgraded to `0.51.0` the other day and re-tried adding something in the `Side Navigation Footer` textbox and it never became visible. Even just text, nothing shows up. I tested in several browsers and in so-called `incognito mode`.
Do @MartinSchoeler or @engelgabriel know if this was fixed in `0.51.0`?

**Comment by k0nsl** [comment]
Oh dear. I sure wasted my own time and others time with this issue (luckily I hope I didn't waste too much of your time!)

See, I just discovered some ancient left-over custom CSS that I used a year or so ago where I wanted to just hide the side navigation footer, like so:
```
// Hide the Rocket.Chat logo
aside .footer{
    display: none !important;
}

// Make sure left sidebar expands to 100% height
.side-nav .rooms-list, .account-box .options, .flex-nav .content {
    height: 100% !important;
}
```
That CSS was produced by somebody in the demo chat because we had a common issue. It worked so I stuck with it. Now, I completely forgot about this little change of mine! 😳

Sorry about that and for wasting some of your time.

**Comment by k0nsl** [comment]
There is still some type of a issue left which needs fixing and I don't understand why the discrepancy exists since nothing else has been touched, except for removing the CSS which interfered with the sidebar navigation footer (which was the root problem of my issue, to begin with).

The text after the logo simply doesn't line-up properly like it does on the Rocket.Chat demo server. Look at my screenshot and compare it with what you see on your own instance or that of the Rocket.Chat demo server.Do anyone have some suggestion in order to make it properly lined-up?

**Comment by karlprieb** [comment]
@k0nsl do you have `left: 10px` and `position: absolute` in the `img` on `footer`? If yes, can you remove this inline style to see if works?

**Comment by k0nsl** [comment]
@karlprieb: Hi, I edited my response just as you posted. The only line I have in `Layout Content > Sidebar Navigation Footer` is the following:
```
<a href="https://twitter.com/k0nsl" class="logo" target="_blank"> <img src="https://proxy.img-cdn.ru/http:/k0nsl.img-cdn.ru/static/devnet_logo-836-EK.png"> <small><i class="icon-twitter"></i> Follow k0nsl on Twitter</small> </a>
```
So I am kind of "stumped". Cache and all the usual has been cleared. I tried in several different browsers and on several different devices. The result is still the same, so I'm clearly missing _something_, but I can't think of what that would be.

**Comment by karlprieb** [comment]
Ok, I found the problem. Ill do a PR later today, but you can add the style above on your custom CSS for a quick fix :)
```
.side-nav .footer img {
    margin-bottom: 0;
}
```

**Comment by k0nsl** [comment]
Thank you, @karlprieb ! 👍

**Comment by karlprieb** [comment]
The issue was not fixed yet 😄

**Comment by k0nsl** [comment]
Oh, right. Anyway, I applied the CSS and it looks much better:
![2017-02-09 20_08_11-sok](https://cloud.githubusercontent.com/assets/2517921/22798778/8848bf8a-ef03-11e6-90bb-e22f97150d44.png)
