### ISSUE TITLE
Create a default `admin` user for project

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#59]

**Comment by tlongren** [comment]
So what's the default? Tag was deleted so link to commit is gone...

I don't know where to find it in master.

**Comment by sabatesduran** [comment]
@tlongren searching into the code i found in the file Rocket.chat/server/startup/initialData.coffee
That the default email is "admin@admin.com" and the password is "admin" (without the quotes).

**Comment by engelgabriel** [comment]
Hi, we need to create a setup wizard #119 for that
