### ISSUE TITLE
Invite user to room if mention an user that is not in the room

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#590]

**Comment by rodrigok** [comment]
Idea from https://github.com/RocketChat/Rocket.Chat/issues/535#issuecomment-134895629

**Comment by geekgonecrazy** [comment]
:+1:

**Comment by geekgonecrazy** [comment]
Related also `/invite` would probably trigger the same function.

**Comment by rodrigok** [comment]
Closed via #600
