### ISSUE TITLE
Channel not found but listed

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#5903]
Rocket.Chat Version: 0.49.3
Running Instances: 10
DB Replicaset OpLog: Yes
Node Version: 4.5.0

I think this started once I upgrade to 0.49.3 but not quite certain. A channel had been created and member count is 4. The information on the channel says 4 users and 4 messages. But when I try to go to it I get the big red message that the channel does not exist. 
Any ideas how to best approach the issue?

![capture-rc-room-info](https://cloud.githubusercontent.com/assets/21371983/22603653/79a5fbb2-ea05-11e6-9f7a-6b4c021cc813.JPG)
![capture-rc-room-error](https://cloud.githubusercontent.com/assets/21371983/22603660/7d345382-ea05-11e6-9a58-b6e0ebd2472e.JPG)

**Comment by vitamindck** [comment]
this sounds like what happened to me when i was testing 0.49 and i toggled "private" in the room info of a direct message. i believe i was unable to access private groups afterward.

**Comment by engelgabriel** [comment]
Can you try again with the develop branch?

**Comment by drickerusa** [comment]
This is a production system. I have a standard change update on a monthly bases which is not until Feb. 23rd. To my knowledge this is the only channel that has this problem. Wasn't sure if anyone else had seen this behavior. I wouldn't be opposed to deleting it if someone can give me a pointer or two on mongo syntax.

**Comment by drickerusa** [comment]
A little more info. If I go into the admin util and look up that room. I can not add a name, topic or change the type. Even I I do make a change it seems to save but  no change in the UI. 
![image](https://cloud.githubusercontent.com/assets/21371983/22606345/cced560c-ea10-11e6-8278-294443b35a80.png)

**Comment by drickerusa** [comment]
@engelgabriel I updated our system to 0.51.0 last night because of #5940. I see no more issues with the room. I'm able to see it just fine.
Thanks

**Comment by ogubchenko** [comment]
Have same issue on 0.52.0

**Comment by andrewfwalters** [comment]
Have this issue on 0.59.3
