### ISSUE TITLE
REST API's channels.list.joined does not include private channels

### ISSUE THREAD

**Issue by tulip0** [RocketChat/Rocket.Chat#5906]
"version": "0.50.1",

`channels.list.joined` should logically include private channels, but there is apparently no method at all for seeing them through the REST API methods. The API seems generally unaware that there are different types of channel visibility, there's seemingly no mention of it in the documentation.

**Comment by graywolf336** [comment]
That's because private channels are private groups according to the rest api. See: https://rocket.chat/docs/developer-guides/rest-api/groups/list#group-list
