### ISSUE TITLE
RocketChat freezes on reboot

### ISSUE THREAD

**Issue by pletchman** [RocketChat/Rocket.Chat#5907]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

We've been plagued with the server becoming "unresponsive" when restarting it. In digging it seems similar to the issue others reported with Slack bridge (screenshot attached). We aren't using that and the only change we make to the admin side is using a custom OAuth to attempt to connect to a boonex site.

I thought maybe it was an issue with our rocket.chat installation or even our VPS server but I deployed a clean set up on Rocket.chat beta cloud deployment and had the same thing happen when attempting to restart that server.

Any insight or guidance would be appreciated.
<img width="728" alt="screen shot 2017-02-05 at 3 04 19 pm" src="https://cloud.githubusercontent.com/assets/25571366/22629935/1a7c6088-ebb6-11e6-8884-06c3b72b2e0c.png">

**Comment by engelgabriel** [comment]
I believe this have been fixed on the latest versions, can you please check?

**Comment by pletchman** [comment]
It froze on your beta cloud deployed so I assumed that was the latest version. 


Pletchman
adam@neotekcorp.com

**Comment by Rohlik** [comment]
I have almost same problem. After click on restart button Rocket.chat freeze.
So only solution for me is restart via systemctl command via terminal.
**My settings:**
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: True
Node Version: 4.7.2
OS: RHEL 7

**Comment by engelgabriel** [comment]
@Rohlik I believe that the freeze Slack due to connectivity has been fixed on version `0.51.0`, can you please confirm this?

@pletchman the problem with the Reboot button on our cloud hosting, is a bug with Docker that we are working on. I'll open another issue for that.

**Comment by engelgabriel** [comment]
@pletchman see https://github.com/RocketChat/Rocket.Chat/pull/5430

**Comment by Rohlik** [comment]
@engelgabriel I dont have slack bridge active, but still...After restarting via admin web page, RC freeze.
Tested with 0.51.0

**Comment by engelgabriel** [comment]
@Rohlik just to be clear, are you using something like `forever` or `pm2` to keep the process running? NodeJS alone can't restart the process, and all the Reboot button does, is to kill the current process, and it expects the system to restart it.

**Comment by engelgabriel** [comment]
@geekgonecrazy can you check if the Reboot button is working on our cloud environment?

**Comment by geekgonecrazy** [comment]
@pletchman I believe we've got an active email thread going and yours taken care of.

@engelgabriel yes reboot button inside any docker container causes the server to lock up.  We need to disable the button when in a container.  No errors thrown it just locks up.

**Comment by pletchman** [comment]
@geekgonecrazy thanks last I tried a reboot form the administration panel on a VPS server it still became non-responsive. I'll cross my fingers. Also, any luck on getting the Dolphin OAuth in the list of presets on the cloud beta would be greatly appreciated.

**Comment by Rohlik** [comment]
@engelgabriel I don´t use anything of those, just systemd. Thx for explanation.

**Comment by engelgabriel** [comment]
@sampaiodiego can you help test reboot button inside any docker container?

**Comment by engelgabriel** [comment]
@geekgonecrazy can write and explanation for @karlprieb to add an explanation under the reboot button?

**Comment by engelgabriel** [comment]
Refs to https://github.com/meteor/meteor/blob/87681c8f166641c6c3e34958032a5a070aa2d11a/tools/tool-env/cleanup.js

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/938c258d3154dcd56873d93c1c79ab2b82c72eaf

**Comment by pletchman** [comment]
Our chat server on the beta cloud just froze when I tried to restart it via the admin panel. It's the first time I've tried since posting about it before so I don't think whatever issue is causing it has been resolved.

**Comment by geekgonecrazy** [comment]
@pletchman it's for sure been resolved.  Updating your instance and restarting it.  I'll follow up via email
