### ISSUE TITLE
Not able to update roles while registering the user

### ISSUE THREAD

**Issue by neha1deshmukh** [RocketChat/Rocket.Chat#5910]
Hello,

While registering the new user using 'https://xx.xxx.xxx/api/v1/users.register' api i am passing "livechat-agent" as role to api but  its taking only "user" as role. 

Thanks for your continued support!
-Neha

**Comment by MartinSchoeler** [comment]
@neha1deshmukh have you tried to use the users.create? https://rocket.chat/docs/developer-guides/rest-api/users/create

**Comment by neha1deshmukh** [comment]
@MartinSchoeler to use the users.create i need Auth-Token and User-Id which i don't have as i am trying to register new user through api.

In this case which Auth-Token and User-Id should i use and how?

**Comment by MartinSchoeler** [comment]
@neha1deshmukh you can try to login with a admin user using /login( https://rocket.chat/docs/developer-guides/rest-api/authentication/login )
and that should return a json with the auth-token and user-id

**Comment by engelgabriel** [comment]
@neha1deshmukh make sure you are passing an `array` of `roles` and not `role` as `string` and please use the `0.51.0` release.
