### ISSUE TITLE
mongoDB authentication issue after auth enabled

### ISSUE THREAD

**Issue by aitzol76** [RocketChat/Rocket.Chat#5912]
I'm trying to set the environment variables to run rocketchat snap in ubuntu 16.04 as follows:
<pre>
Export MONGO_URL = mongodb: // user: password @ localhost: 27017 / parties
Export ROOT_URL = https: //chat.mysite.com
Export Port = 3000
</pre>
-/etc/mongod.conf - security.authenticacion: enabled

when I run:
<pre>
$ Snap run rocketchat-server
</pre>
, I receive the following error message:
<pre>
MongoError: not authorized on parties to execute command { listIndexes: "users", cursor: {} }
    at Object.Future.wait (/snap/rocketchat-server/451/node_modules/fibers/future.js:449:15)
    at MongoConnection._ensureIndex (meteor://💻app/packages/mongo/mongo_driver.js:828:10)
    at null.Mongo.Collection._ensureIndex (meteor://💻app/packages/mongo/collection.js:685:20)
    at setupUsersCollection (meteor://💻app/packages/accounts-base/accounts_server.js:1491:9)
    at new AccountsServer (meteor://💻app/packages/accounts-base/accounts_server.js:51:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (meteor://💻app/packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:188:9)
    at require (packages/modules-runtime.js:111:16)
    at /snap/rocketchat-server/451/programs/server/packages/accounts-base.js:1972:15
    at /snap/rocketchat-server/451/programs/server/packages/accounts-base.js:1983:3
    - - - - -
    at Function.MongoError.create (/snap/rocketchat-server/451/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/snap/rocketchat-server/451/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /snap/rocketchat-server/451/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
</pre>
However, if I run in console
<pre>
mongo -u user -p password parties
</pre>
I have no authentication problems. Any advice?

Rocket.Chat Version: 0.50.1
Running Instances:
DB Replicaset OpLog:
Node Version: v.7.4.0

**Comment by engelgabriel** [comment]
Please see 
https://github.com/RocketChat/Rocket.Chat/issues/5437
https://github.com/RocketChat/Rocket.Chat/issues/2584

**Comment by engelgabriel** [comment]
Please upgrade to version `0.51.0`

**Comment by engelgabriel** [comment]
@geekgonecrazy do you think this is something specific to SNAP deploy?

**Comment by aitzol76** [comment]
Maybe. I just removed the SNAP and installed RocketChat manually and now it works well.
Anyway, I will try again with the upgraded SNAP and I will tell you. Thanks.

**Comment by geekgonecrazy** [comment]
Problem is with snaps you setting the environment variables is ignored.  So you created a password on the DB, but now rocket.chat in the snap doesn't know how to connect.  

This is something we'd like to enable in snaps in the future, but currently not possible.

**Comment by geekgonecrazy** [comment]
Also just to note our snap has built in mongo.  So by running mongo externally you are causing the one internal to the snap to actually crash.  I'd be cautious of this... Because if the snap mongo starts before your external one at any point it will appear as if all your data is gone.  But you just are connected to a different server all together

**Comment by aitzol76** [comment]
SNAP works for me with disabled authentication in mongo config, that is, <pre>-/etc/mongod.conf - security.authenticacion: disabled</pre> and if I disable the **snap.rocketchat-server.rocketchat-mongo.service** in systemctl.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by geekgonecrazy** [comment]
Please feel free to hop in [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) on our community server if you need to follow up on this.

**Comment by shopglobal** [comment]
I need authentication with MongoDB, and the snap is using no auth enabled. Please point me in the right direction as to using the secured mongodb with the snap. This has been brought up in #ubunu-snap and has remained unanswered and unsupported.
