### ISSUE TITLE
Invite user to room via slash command "/invite"

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#592]
Idea from https://github.com/RocketChat/Rocket.Chat/issues/590#issuecomment-135158361

**Comment by graywolf336** [comment]
:+1:

**Comment by marceloschmidt** [comment]
Invite by mention has been merged from PR #600

**Comment by geekgonecrazy** [comment]
Will this invite instantly add them or pop up like video call / delete message etc?

**Comment by graywolf336** [comment]
@geekgonecrazy How slack has done it is automatically adds them. Due to a user might not be online when they get invited so they can't accept/deny the invite via that pop up

**Comment by rodrigok** [comment]
Exactly @graywolf336

**Comment by graywolf336** [comment]
This can be closed now, as it was merged. :+1:

**Comment by geekgonecrazy** [comment]
Good catch :+1:
