### ISSUE TITLE
Cannot change the translation of titles in the administration section

### ISSUE THREAD

**Issue by djulien19** [RocketChat/Rocket.Chat#5920]
Rocket.Chat Version: 0.43.0
Running Instances: 1
DB Replicaset OpLog: 63
Node Version: v4.6.0

**Comment by karlprieb** [comment]
@djulien19 which titles can't you translate?

**Comment by engelgabriel** [comment]
The Sections Titles, AFAIK.

**Comment by karlprieb** [comment]
We translate section titles already. I don't know which title @djulien19 meant.

**Comment by djulien19** [comment]
see, there is still some left in French version in layout page.
https://www.evernote.com/l/ACbAqK0ok2tDE7mhM1z3VISS7b7BbJHGla4B/image.png

**Comment by karlprieb** [comment]
Sorry @djulien19, but I dont understand tou screenshot.

**Comment by djulien19** [comment]
Sorry for that! I corrected it, here's again https://www.evernote.com/l/ACaGlHrP3VJIKI766WkmJ5OTThtoQDrZP70B/image.png

**Comment by MartinSchoeler** [comment]
@djulien19 if you find more untranslated sections, please reopen this and report them to us. Thanks!
