### ISSUE TITLE
Support multiple certificates/apps on Push Notification (iOS and Android)

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#5926]
Dear @RocketChat/core ❤️ ,

We currently support just one certificate (iOS) and one push-key (Android) to send push notifications. But since we'll now have more than one app for each platform, it would be required to support different keys.

My suggestion is to send the application id (or some unique identifier) when registering the device for push. On the JSON object today we currently have the `appName` that maybe can be used to that? We could have the app identifier here, instead of `main`. Example:

```swift
let request = [
    "msg": "method",
    "method": "raix:push-update",
    "params": [[
        "id": "some-crazy-string-here"
        "userId": "user-identifier",
        "token": ["apn": deviceToken],
        "appName": "com.rocket.chat.ios",
        "metadata": [:]
    ]]
]
```

**Comment by rodrigok** [comment]
@rafaelks Yes, that probably is the best way to do that.

**Comment by rafaelks** [comment]
Closing it since it's working fine after a few adjustments. Thanks @rodrigok. 🚀
