### ISSUE TITLE
images are not getting parsed

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#593]
I've try uploading an image but it's not making a preview of it and it's not working with urls neither

**Comment by rodrigok** [comment]
Can you check if the option **Embed** is enabled in settings?

**Comment by dbussert** [comment]
I had this same issue when upgrading from an older commit, the embed was neither `true` or `false`.

**Comment by oinirio** [comment]
ember was off (not disable but off) after turning it on still doesn't worl

**Comment by rodrigok** [comment]
Did you restarted the application?

**Comment by oinirio** [comment]
thanks, after turning Embed on and restarting the app the images load again

**Comment by kakawait** [comment]
will be fix with #849
