### ISSUE TITLE
Incoming web hook can not use "@"

### ISSUE THREAD

**Issue by mattlin** [RocketChat/Rocket.Chat#5930]
Rocket.Chat Version: 0.49.3

**Incoming web hook can not use "@"**

curl -X POST --data-urlencode 'payload={"text":"@all Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' http://www.myrocketchat.com/hooks/abccd/WoY2p4SM2tGGhv9po5jaLPBKo4P5RLz4DeSRk5gdNPabccd

server response：  {"success":false,"error":"error-action-not-allowed"}

I find that if payload's text include "@" character, the server will response the error;

**Comment by mattlin** [comment]
@MartinSchoeler  Thanks a lot

**Comment by engelgabriel** [comment]
@graywolf336 have we been able to replicate the issue here?

**Comment by graywolf336** [comment]
This is because the user, can be a bot, doesn't have the permission `mention-all` enabled by default, thus it's working as intended since enabling that permission on the user, or bot, fixes this.
