### ISSUE TITLE
Add a option to switch between toolbar search and spotlight search

### ISSUE THREAD

**Issue by jszaszvari** [RocketChat/Rocket.Chat#5936]
Rocket.Chat Version:  0.51.0
Feature Request: 

Would it be possible to have a option to switch between the spotlight old search style and the new toolbar one? 

I can see from the changes here that it looks to have been completely removed, And I've already gotten multiple emails from staff complaining that they dont like the new search box just sitting there as a primary component all the time 

I personally much preferred the old search and am going to try and pull down the older code and merge it back in for our instance, But I cant imagine I will be the only one that does not like the new search box style. 

I was in love with the spotlight feature now its gone with no option to turn it back on :(

**Comment by engelgabriel** [comment]
Hi @jszaszvari 

I am sorry to hear that. We have no plans to keep both templates working, and I'd strongly recommend you not to do that yourself as the change on templates and functions was significant.

If I were you, I'd leave the complains site there for a week or two, and re evaluate if putting the spotlight back in the previews place is worth your time... is would bet it is not.

What we can do, is to have an option to hide the search until the shortcut is pressed, but we are not changing its place.

Cheers,

Gab
