### ISSUE TITLE
Custom light layout theme is confusing other colours

### ISSUE THREAD

**Issue by flayks** [RocketChat/Rocket.Chat#5937]
Hey,
I customized my RocketChat install with some of my brand colors and apparently this is not working well with light scheme… the icons and secondary stuff on the sidebar are kinda invisible and there is no option to modify it.
Any help? Or maybe an enhancement for the next version?
Thank you!

![capture d ecran 2017-02-07 a 16 44 03](https://cloud.githubusercontent.com/assets/273716/22698635/5cfc2880-ed55-11e6-9508-7531e9f69802.png)

—
Rocket.Chat Version: 0.51.0
Running Instances: 1
Node Version: 4.7.3

**Comment by engelgabriel** [comment]
@flayks we need to improve this on the next release. It is a know issue with light themes.

**Comment by flayks** [comment]
Any news on it?

**Comment by flayks** [comment]
🤞

**Comment by flayks** [comment]
Any news about it? It's kind of confusing…

**Comment by karlprieb** [comment]
@flayks We are changing the sidebar layout and that will be fixed on the new sidebar release.

**Comment by flayks** [comment]
@karlprieb cool! Good to know. Any ETA about it?

**Comment by MartinSchoeler** [comment]
@flayks #7643 Closes this

**Comment by flayks** [comment]
Wow cool, can't wait to see it released! Thanks for updating

**Comment by flayks** [comment]
@MartinSchoeler Okay, tried the 0.59.0-rc.0 and apparently it doesn't fix yet the problem :/
