### ISSUE TITLE
Alert admin DM or Email when new user signs up

### ISSUE THREAD

**Issue by divergefx** [RocketChat/Rocket.Chat#5945]
Rocket.Chat Version: 0.50.0
Running Instances: 
DB Replicaset OpLog:
Node Version:

Simple feature to alert admins with either a DM or email when new users register.

**Comment by engelgabriel** [comment]
This is in progress, with the new APIs that can fire on almost any events :) You will be able to trigger your own scripts, that can fire a DM, for example.

Follow https://github.com/RocketChat/Rocket.Chat/pull/5823

**Comment by engelgabriel** [comment]
@graywolf336 maybe we should have a setting to just turn on a callback that does this? It could be a package that uses our new APIs to register this call back?

**Comment by graywolf336** [comment]
@engelgabriel  We could create a default integration that is disabled by default on new installations which uses the new event. Would adding this functionality really be needed inside of Rocket.Chat core?

**Comment by jgtoriginal** [comment]
@engelgabriel you mention the `new APIs` is there any issue to track progress on those? 
I find the `rocketchat-api` package pretty well done, are you planning to extend it??
If so, I'd like to know more. Thx!

**Comment by graywolf336** [comment]
@jgtoriginal The new APIs were added for our outgoing integrations. The pull request was merged and has been in production for quite some time now: https://github.com/RocketChat/Rocket.Chat/pull/5823

**Comment by jgtoriginal** [comment]
@graywolf336 ok, I got it then.
I was just being curious about the Rest API (which I'm using quite a bit) and the Realtime API (which I plan to use soon). And I see that today you guys updated the docs. And there's a lot going on on that arena. Just want to be sure I'm aware of any news related to these.

**Comment by graywolf336** [comment]
@jgtoriginal Best place to keep updated is to watch our activity here on GitHub. We currently do not have a single source of news, except for GitHub, as to what has been added, removed, or changed. We are all on our community server of https://open.rocket.chat/, so feel free to come join us and ask any questions.

**Comment by jgtoriginal** [comment]
@graywolf336 ok, I'll go on and join you guys on the community server, where I happen to go once and again. Any specific channel though?? Mainly because here on GH I find issues related to occurring problems, but I'm more into what's the horizon here, what needs to get done, what's the roadmap. Maybe there's a specific channel for that. Thanks once again!!

**Comment by graywolf336** [comment]
@jgtoriginal We do not have a channel for that, however any open issues are open game - if you want to work on something to implement it, tag me and I'll find out if someone else internally is working on it or not and if not then I'll let you know. :) `#dev` is a good channel which we have had some previous discussions in

**Comment by jgtoriginal** [comment]
@graywolf336 good to know, thanks for the heads up. and will keep you posted!

**Comment by sampaiodiego** [comment]
this was done by https://github.com/RocketChat/Rocket.Chat/pull/7098
