### ISSUE TITLE
Mapping interactions

### ISSUE THREAD

**Issue by AmauryVanEspen** [RocketChat/Rocket.Chat#5947]
Good morning mates,

i would like to know a bit more about integration and features likes "mapping" through API.
For exemple, i could be interesting to map participation and interactions of users and channels through MetaMaps.
Like, getting a public web page with a map of channels and users, in a list view and on a map view 
https://github.com/metamaps/metamaps

What do you think about ?

best

Amaury

**Comment by engelgabriel** [comment]
This could be awesome. We have been planning to integrate something like https://github.com/RocketChat/Rocket.Chat/issues/3824

But you will also be able to integrate almost anything with the new APIs from https://github.com/RocketChat/Rocket.Chat/pull/5823

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by engelgabriel** [comment]
Ref: https://github.com/RocketChat/Rocket.Chat/issues/10726

**Comment by sampaiodiego** [comment]
I'm sorry but we don't plan to support this.

it could be implemented as an app in the future though.
