### ISSUE TITLE
Can't activate new users

### ISSUE THREAD

**Issue by pbelau** [RocketChat/Rocket.Chat#5949]
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.1

"activate" button does not turn green after new users have been registered and verified.

**Comment by pbelau** [comment]
FYI, this is not just a UI issue. The user is not activated.

**Comment by engelgabriel** [comment]
@MartinSchoeler please add a test on our CI for this.

**Comment by engelgabriel** [comment]
@pbelau can you test it with the develop branch now?

**Comment by pbelau** [comment]
@engelgabriel I'm swamped today but I can check it out tomorrow. Also, if you've got a single command that I can use to pull and install the dev branch that would save me some time. Thanks again for being so responsive.

**Comment by engelgabriel** [comment]
Are you using docker? You can use the develop tag.
