### ISSUE TITLE
Using iframe integration not able to login to exact user which i am suppose to

### ISSUE THREAD

**Issue by neha1deshmukh** [RocketChat/Rocket.Chat#5951]
Hello,

What I want to accomplish is: a user login in in my website and in a transparent way it gets logged in to rc inside the iframe too.

i am able to do login to iframe when user logged to my website using iframe integration.
but in iframe its showing me different user than which username and password i used to login my website.

Its taking any ramdom user from the active/online users list of rc.

Thank you for your efforts & support.
Neha

**Comment by engelgabriel** [comment]
@neha1deshmukh please provide the information about your deployment, listed on the issue template.

**Comment by neha1deshmukh** [comment]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

**Comment by rodrigok** [comment]
You can use both.

How are you doing the login automatically?

**Comment by c-thomasFR** [comment]
@engelgabriel I would like to do the same, can you explain me how you've done ? Thanks for your help

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
