### ISSUE TITLE
Add setting for Google Analytics

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5955]
Let's have a setting for admins to add Google Analytics ID, as not everyone has Google Tag Manager.

Also, let's move the GTM script to the index.html injection, so it is already available before users finish loading the JS.

**Comment by engelgabriel** [comment]
@jy2008 You can put the Google Tag Manager Id on the `/admin/General`

**Comment by karlprieb** [comment]
@RocketChat/core What you guys think about that? We really need this?

@jy2008 you can put your Google Analytics script in Admin > Layout > Custom Scripts

**Comment by graywolf336** [comment]
Yes. I think we need to convert the piwik package to a generic analytics item and add support to it for Google Analytics.

**Comment by jy2008** [comment]
From your reply, i take it as RC currently only has entry for Google tag manager, but not google analytics?
