### ISSUE TITLE
Open Channel / User search (CTRL/CMD + P) does not show when window does not show channel/user bar.

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#5957]
Rocket.Chat Version: 0.51
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.6.2

When client window width is below the threshold of showing the blue bar to the left, i.e. it only shows the chat area, the Open Channel / User search does not show when invoked via keyboard shortcut CTRL/CMD + P.

The search bar is still activated and searching does happen, but without visual representation on screen.

**Comment by engelgabriel** [comment]
Good point.

**Comment by karlprieb** [comment]
@engelgabriel so we disable CTRL/CMD + P on small screens or make it open the sidenav and focus on search?

**Comment by engelgabriel** [comment]
Bring the sidenav and focus on search.
