### ISSUE TITLE
Since 0.51.0 cordova message action menu broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5963]
Rocket.Chat Version: 0.51.0
Running Instances: 3
DB Replicaset OpLog: Enabled

Since the update to 0.51.0 the context menu to interact with a message is broken in cordova, you can reproduce this with ease:

- Open Cordova app
- enter a channel
- Hold and press long on the message
-> Nothing happens (in versions before there is a menu for deleting the message or editing it)

**Comment by engelgabriel** [comment]
@karlprieb make this top priority.
