### ISSUE TITLE
0.51.0 layout issue

### ISSUE THREAD

**Issue by MrDragon** [RocketChat/Rocket.Chat#5966]
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version:  4.7.1 (runtime), however "build" says "4.6.2"?!

OS: Ubuntu 14.04.5 LTS, Trusty Tahr, 64-bit

I updated from 0.48.2 to 0.51.0, after updating NodeJS to 4.7.1
Now the search bar and the right sidebar are "off" - and the right sidebar's popups don't like window resizes anymore either (if I widen the window, the popup is off to the left, where the old window size used to be)

Browsers:
- FireFox 51.0.1 on Windows-10 64-bit
- Chrome Version 56.0.2924.87 on Win-8
- rocket.chat windows desktop client v. 2.4.0 (Win 10 and Win 8)
- rocket.chat windows desktop client v. 1.3.1 Win 10
- rocket.chat windows desktop client v. 1.2.0 Win 7

"#support" - user Hannes-3 (2/9/2017) reported "we got the same problem with our Installation, began with Installation of 49.1 at our side"

See attached PNGs for a visual
![rocket1](https://cloud.githubusercontent.com/assets/1017487/22792972/70b42036-eebc-11e6-8520-b4ae3888a153.PNG)
![rocket2](https://cloud.githubusercontent.com/assets/1017487/22792982/73b50d22-eebc-11e6-87e1-4b97cc302ba6.PNG)

**Comment by engelgabriel** [comment]
Do you use any custom CSS?

**Comment by MrDragon** [comment]
There is an entry in "Custom CSS", not sure if our web developer put that in, or if it's a leftover from older versions. See attached:
[CustomCSS.txt](https://github.com/RocketChat/Rocket.Chat/files/764401/CustomCSS.txt)

**Comment by rhruiz** [comment]
I am seeing similar issues on Safari 10.0.3 (12602.4.8) and Chrome 57.0.2987.37 beta (64-bit) both on macOS Sierra.

I had all the layout section on admin reset and the issue remains.

**Comment by MrDragon** [comment]
Update on CustomCSS: removed CustomCSS, restarted server and app(s), issue remains for me as well.

**Comment by MrDragon** [comment]
We fixed it for us but don't know any root cause.
We went into Admin -> Colors (minor) and hit "Reset"
Then Admin -> Colors, hit "Reset"
As soon as we hit "Save", everything worked.

Not sure what the "Reset" button actually does, but it seems to have helped things!

(By "We", I mean our web developer who can reads CSS as if it were his first spoken language. He got sidetracked into https://github.com/RocketChat/Rocket.Chat/issues/4004, last comment, and just gave the reset button a whirl.)

I hesitate to close the issue, because I don't really know/understand what happened.

**Comment by engelgabriel** [comment]
Can you guys try to change the custom CSS to something dummy, like:

```
body { }
```

**Comment by engelgabriel** [comment]
The bug is that when `Custom CSS` is set to empty, it wont trigger the re-compilation.

**Comment by rhruiz** [comment]
@engelgabriel that seem to have solved it 👍
