### ISSUE TITLE
Suggestion for "Manually Approving Users"

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#5977]
I think it would be very good to have the option of letting the registrant leave a message for when he/she makes the registration. That way it can be used as a sort of "justification" of why he/she should be approved and the ones in charge can then base their decision upon what is submitted.

**Comment by mrplow** [comment]
I'm using the livechat script in the logged out users script setting for this sort of functionality.

**Comment by rasos** [comment]
And the approving person(s) should get an e-mail notification as well. We should have an extra role "approve-users" for those users (which are in our case not the sysadmins).

**Comment by rasos** [comment]
The permission
edit-other-user-active-status is available.   
edit-other-user-info must be set as well, so that you can see them.    
What is still missing is the notification handling both to the pending user and users with the permission edit-other-user-active-status .

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/7098
