### ISSUE TITLE
Read Mark Not Resetting When Line Is Visible and Clicking in Textbox

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#598]
When there the mark is visible, it doesn't reset when switching to a channel and clicking on the text box.

![2015-08-27_15-08-28](https://cloud.githubusercontent.com/assets/850391/9531853/c6f6607c-4ccd-11e5-8bb7-520ebcdb4e60.gif)

**Comment by rodrigok** [comment]
@graywolf336 can you confirm if this was fixed?

**Comment by graywolf336** [comment]
Confirmed it was fixed. :)
