### ISSUE TITLE
"Protect uploaded files" feature doesn't work

### ISSUE THREAD

**Issue by nesimtunc** [RocketChat/Rocket.Chat#5988]
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.1

Doesn't show a preview of uploaded image inline, even can't download it due to protection.

**Comment by louisemessage** [comment]
Tested: this feature is working in Rocket.Chat 2.10.5. Tested on Mac OS 10.13.3.
