### ISSUE TITLE
Unread Message bar disappears after few seconds 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5989]
I Just upgraded my instant to 51.0, so i dont' have any unread messages, but i noticed in demo.rocket.chat  as of Feb 11, 2017 the unread message bar on top of the room disappears after few seconds, without clicking read.

**Comment by tkuhrt** [comment]
I have Version 1.3.1 (15) for Mac installed, and I have the same problem.  This it makes it extremely difficult to find the last unread message in a busy chat window.
