### ISSUE TITLE
Starting a codeblock and pressing enter should not send a message

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#599]
Starting a codeblock with ``` and pressing enter should not send a message but allow you to continue writing the code.
##

**Comment by rockneverdies55** [comment]
What about `Shift + Enter` instead of `Enter` not to send the message?

**Comment by mitar** [comment]
Shift + Enter works, but it is a really nice goody to automatically detect ```. At least Slakck does it like that.

**Comment by graywolf336** [comment]
@mitar Are you sure slack does it like that? I haven't experienced it... Is that one desktop, mobile, or web browser?

**Comment by mitar** [comment]
I have it in Slack under Advanced Options on Desktop version: "When typing code with ```, ENTER should not send the message. *"

**Comment by graywolf336** [comment]
Interesting, never knew that. That is a good thing to have

**Comment by xmclark** [comment]
Looks like this hasn't been touched in awhile. Is this open for pull requests? I would be interested in implementing this feature.

**Comment by graywolf336** [comment]
@xmclark Go for it!

**Comment by xmclark** [comment]
@graywolf336 awesome. I cloned the project and am poking around, getting familiar with the architecture. I need to sign the developer agreement, but that should be easy. I will mark this issue as progressing. 

@mitar suggested that Slack has an option in the Preferences that turns this feature on. Unless anybody has an issue with that, I'm going to mimic that behavior.

**Comment by graywolf336** [comment]
@xmclark How's the progress going?

**Comment by SeanPackham** [comment]
Currently we support multiline messages by pressing CTRL+Enter. This enhancement is not on our short term roadmap. We will revisit it the future.
