### ISSUE TITLE
Integrating Rocket.chat with laravel

### ISSUE THREAD

**Issue by allw1994** [RocketChat/Rocket.Chat#5990]
Looking to integrate rocket.chat to a laravel site in development using some sort of single sign on without the need of rocket.chat to present a login page - so far the docs are a little vague in this area. If it meant easy implementation the laravel auth could be changed quite readily.

**Comment by iPublicis** [comment]
The same here :)

**Comment by jinshunlee** [comment]
hi @allw1994, i'm trying to do the same thing here, do you have any success in doing so yet?

**Comment by allw1994** [comment]
So far i have thought about using laravel passport to provide an interface for rocket.chat but the only way I see of being able to using that would be to manually get users to add rocket.chat to the clients list which would be way too complicated...

**Comment by chrispecoraro** [comment]
I'm looking through the code for the Drupal 8 package. This should be useful to provide some code to recycle.

**Comment by geekgonecrazy** [comment]
Closing due to age
