### ISSUE TITLE
Auto SSL with snaps will take care of the SSL proxy thing?

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5993]
if i do Auto SSL with Snaps (enable Caddy ), do i still need to do the SSL Ngix proxy setup to move SSL to Ngix?

**Comment by geekgonecrazy** [comment]
No you do not.  In fact you will likely cause issues if you use nginx in front of caddy.

If you turn on caddy, then you will not want to use nginx or another reverse proxy to terminate ssl.
