### ISSUE TITLE
Auto SSL snap install not successful

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5994]
I did snap install first
then when i did `sudo rocketchat-server.initcaddy`, i got this error message "Replace /var/snap/rocketchat-server/487/Caddyfile with your own to customize reverse proxy", what should i do?

**Comment by buschmann** [comment]
https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl

sudo nano ...

**Comment by geekgonecrazy** [comment]
@jy2008 the document here: https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl will tell you how to finish setting it up

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this, feel free to open it back if you still have the issue.
