### ISSUE TITLE
Admin lost Permissions section in menu

### ISSUE THREAD

**Issue by imsamthomas** [RocketChat/Rocket.Chat#5996]
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.1

I'm an admin and owner of chat.
I unchecked Role > Permissions for `admin` group by mistake.
So I lost `Permissions` section in my menu.

Is there any way to get Permission back?

I think, there is a higher role: `Supper Admin`, it includes all permissions and nobody can change.

**Comment by engelgabriel** [comment]
Do you have access to the DB? You need to add the permission there manually I am afraid :(

**Comment by imsamthomas** [comment]
Yes, please tell me how?

**Comment by imsamthomas** [comment]
hi @MartinSchoeler @engelgabriel 
Please tell me know, our team is chatting on this everyday.
I'm a developer, so just tell me `table`, `key` and default value

**Comment by imsamthomas** [comment]
Hi @MartinSchoeler ,

How to resolve this permission issue?

Regards,
Sam

**Comment by imsamthomas** [comment]
Hi @MartinSchoeler ,

We need your helps, please response.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
