### ISSUE TITLE
ta-IN language doesn't work

### ISSUE THREAD

**Issue by garychapman** [RocketChat/Rocket.Chat#5997]
Selecting _ta-IN_ has no visible effect on the UI, despite ta-IN.i18n.json being fairly comprehensive. Also, after selecting _ta-IN_ the Language dropdown defaults to the first selection (currently Arabic).

**Comment by MartinSchoeler** [comment]
@garychapman #7190 should have fixed this, could you test it again in the latest release? Thanks!

**Comment by garychapman** [comment]
Looks good to me!
