### ISSUE TITLE
Allow visitors to switch departments (livechat)

### ISSUE THREAD

**Issue by drallgood** [RocketChat/Rocket.Chat#5998]
Right now, a visitor is not able to switch to a different department, once he has registered.

This has severe limitations in situations where people might ask different questions over time, e.g. developers asking about fronted and backend questions.

I'd like to allow the visitor to easily switch to a different department.
Any open chats would need to be closed, as I don't think visitors should be allowed to forward open requests on their own.

**Comment by Jannibal** [comment]
How do you mean, "departments"? Do you mean roles? In that case, you can change them for users. It's just not very intuitive to do.

Go to Administration-->Permissions and then click the small square with the pen in it.
![selection_005](https://cloud.githubusercontent.com/assets/2311513/22876382/b709aea4-f1d0-11e6-8ced-8efed60c6d53.png)
You can add or remove users from roles here.

**Comment by drallgood** [comment]
@Jannibal 
I'm talking about the departments in the livechat feature.

**Comment by Jannibal** [comment]
@drallgood Sorry! Never tried the livechat, so I didn't know that there were departments in there :)

**Comment by drallgood** [comment]
Current state. I've successfully implemented the core functionality.
Needs some polishing, but it's working:

<img width="374" alt="screen shot 2017-02-14 at 12 16 57 am" src="https://cloud.githubusercontent.com/assets/127142/22907769/1935a338-f24b-11e6-87f8-7a6173da6633.png">
Switching to a different department will automatically close the current conversation.

What I haven't figured out yet, is how to get to the selected department so that I could preselect it. Doesn't seem to be stored anywhere other than the backend?

**Comment by juliomac** [comment]
Can I disallow it? I don't want users to see departments at all in some cases.

**Comment by renatobecker** [comment]
@juliomac, Yeah.. There is a specific Livechat settings(`Allow Visitor to Switch Departments`) to enable/disable this feature.

**Comment by arielc387** [comment]
Hi. Where I could find and set up the Livechat settings "Allow Visitor to Switch Departments"?

**Comment by renatobecker** [comment]
> Hi. Where I could find and set up the Livechat settings "Allow Visitor to Switch Departments"?

In the Omnichannel admin area.

**Comment by arielc387** [comment]
Thank you very much
