### ISSUE TITLE
Language options

### ISSUE THREAD

**Issue by rickbenetti** [RocketChat/Rocket.Chat#6]
O forked your project and will be create two branchs: spanish-language and italian-language to be able add to more languages.

It's ok this way? I pull request after that.

**Comment by engelgabriel** [comment]
Sure, but you don't need to create 2 branches.. just create the languages files on the i18n folder

**Comment by engelgabriel** [comment]
Please use this link: https://www.transifex.com/organization/rocketchat/dashboard/rocketchat

Let me know if it works for you?

**Comment by jcarloos** [comment]
It works perfectly

**Comment by rickbenetti** [comment]
Sorry I have problems, but it is because my account, I'm in contact withh
their support.

Em quinta-feira, 4 de junho de 2015, Carlos Rodríguez <
notifications@github.com> escreveu:

> It works perfectly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/6#issuecomment-108892916>
> .
>


-- 

Atenciosamente,

Rick Benetti
Celular: +55 (11) 98202-8104
Skype: rickbenetti
