### ISSUE TITLE
How to delete multi messages in a room or clear all message in a room?

### ISSUE THREAD

**Issue by nth4** [RocketChat/Rocket.Chat#6000]
Please guide me how to delete multi message and clear all message in a room (chanell, direct message).
Thanks!
-------------------------------------
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: 1
Node Version: v4.6.2

**Comment by Nemra1** [comment]
u can only clear one by one select all not avaible

**Comment by engelgabriel** [comment]
You can delete them directly form the DB if you have access to it.

**Comment by nth4** [comment]
@engelgabriel I use on Rocket.Chat cloud (https://vinhlong.rocket.chat). How do I can access to Database.
Thank you so much.

**Comment by ChrisKendallVA** [comment]
I would very much like to see this feature implemented! we have hundreds of notifications per day to an observance channel and its a pain to delete them all one by one...

**Comment by cs-1** [comment]
I second this, this feature is absolutely essential for us. We're currently deploying Rocket.Chat in our university environment and it's gaining momentum. Having this feature would greatly support the deployment.

**Comment by bbrauns** [comment]
We used the rest api for this purpose: https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory

**Comment by cs-1** [comment]
Thanks for the link! However, what I meant was that this feature should also be available to moderators of private channels and administrators and members of private conversations from within the UI. Sorry, I should've phrased that more clearly in my earlier post.

**Comment by MartinSchoeler** [comment]
Duplicate of #1861

**Comment by poka-IT** [comment]
> We used the rest api for this purpose: https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory

New like for this doc: https://rocket.chat/docs/developer-guides/rest-api/rooms/cleanhistory/

**Comment by chimsue245** [comment]
> You can delete them directly form the DB if you have access to it.

hi sir what is the name of the table for direct message ?

**Comment by asarubbo** [comment]
> You can delete them directly form the DB if you have access to it.

Hello, would you mind to share the mongodb query to do that?

I would like to delete all messages in a room called #room from a nickname that contains a string or a message content that contains a string. Thanks
