### ISSUE TITLE
File commenting feature requring

### ISSUE THREAD

**Issue by spacegoing** [RocketChat/Rocket.Chat#6002]
In slack we can comment on a shared file. This is very useful for reviewing documents.
![screenshot 2017-02-13 20 31 54](https://cloud.githubusercontent.com/assets/5180020/22883514/8a8b9742-f22b-11e6-9c25-1ff152ff2201.png)

**Comment by gcthomas** [comment]
we also want this feature!!!

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
