### ISSUE TITLE
webhooks not working in sandstorm

### ISSUE THREAD

**Issue by jimscarver** [RocketChat/Rocket.Chat#6003]
I created an incoming webhook for github which gave me the url
http://127.0.0.1:8000/hooks/mLf7WKdkWTDTtvYPJ/rXPhjrXkCE6jAotTq...
I modified that to
https://myhost.sandcats.io/grain/YtAM4DH2iSEStX2taThBmX/hooks/mLf7WKdkWTDTtv...
github reports success with either json or form encoding selected but nothing is added to the channel in rocketchat

Did I do something wrong? Are webhooks supposed to work in sandstorm?

Thanks in advance.
Rocket.Chat Version: 0.49.3
Running Instances: 1
DB Replicaset OpLog:disabled
Node Version:v4.4.7

**Comment by graywolf336** [comment]
@jimscarver Contact me on the demo server (bradley.hilton) so we can see what the issue is

**Comment by jimscarver** [comment]
Thanks @graywolf336 for seeing the obvious error :-p

I replace the localhost:8080 with an invite link rather than the grain url in the incoming weblink and it is working. hurray!

**Comment by graywolf336** [comment]
@Sing-Li Your guidance/experience would be helpful here. :+1:

**Comment by jimscarver** [comment]
while the hooks are processed given the right url the json is not apparently because sandstorm is monkeying with the headers or something. Nothing is posted if I send the json.

**Comment by jonfortescue** [comment]
I'm not super familiar with Sandstorm, but I think you may be going about this the wrong way. AFAIK, the kosher way to send API requests is through Sandstorm's [HTTP APIs](https://docs.sandstorm.io/en/latest/developing/http-apis/). It doesn't look like Rocket.Chat is currently configured to do this.

**Comment by faburem** [comment]
I have a similar setup working perfectly fine on our sandstorm instance. I think what is missing here is the creation of a "Webkey":
<img width="469" alt="screen shot 2017-03-13 at 11 07 10" src="https://cloud.githubusercontent.com/assets/11456790/23849827/50fe0d58-07dd-11e7-89ea-910d39cbfb0b.png">
Especially the part of the URL after the # is very important. You need to provide this authorization bearer with your request to have it processed by sandstorm. There is a good read on this topic in the sandstorm docs [https://docs.sandstorm.io/en/latest/developing/http-apis/](https://docs.sandstorm.io/en/latest/developing/http-apis/).

I am pushing logs from journalctl to a rocket.chat channel this way, so I can use curl to provide this in the headers i.e.:
/usr/bin/curl -H "Authorization: Bearer xxxxxxxxxxxxxxxxxx" -X POST --data-urlencode "payload={\"text\":\"$LINE\"}" https://api-xxxxxxxxxxxxxx.xxxxxx.sandcats.io/hooks/xxxxxxxxxxxxxxxxx

Not sure if you can add authorization headers with github webhooks, but instead you could probably use the method suggested for websockets in the sandstorm docs (adding the auth token through the .sandstorm-token URL parameter.

**Comment by graywolf336** [comment]
@jimscarver Did you get this working with the response and details from @faburem?

**Comment by jimscarver** [comment]
Sandstorm changes the request and I was not able to get the integration
working.

**Comment by graywolf336** [comment]
Okay thanks for following up, @Sing-Li any ideas?

**Comment by jimscarver** [comment]
I missed the update from @faburem and have not tried again yet. His success is encouraging for self hosted sandstorm via sandcats. Its not clear it can work hosted on sandstorm.io. Its not a priority for me right now but will try again when I have time....

**Comment by jeje42** [comment]
Hi all,

I could get it work using postman with @faburem 's solution.

In the header, I had to add thew following parameters : 
  - Content-Type : application/json
  - Authorization : Bearer xxxxxxx(part of the url after the #)

Thanks a lot !

**Comment by timkinnane** [comment]
Just wanted to leave a reference to #9361 - for issues that end up providing examples to follow and learn the API via Postman, I think it would be really helpful if the team and community could contribute solutions to Postman Collections for all to benefit from, maybe even pick up some new users from the visibility.
