### ISSUE TITLE
Creating New DM Issue - Cannot search users by First Name for new Direct Messages since V 0.51.0 - still present up to current version 0.54.2

### ISSUE THREAD

**Issue by Nosferous** [RocketChat/Rocket.Chat#6006]
Issue introduced in Rocket.Chat Server Version 0.51.0
Issue still present up to current version release 0.54.2

Hosted on an Ubuntu 16.04 LTS

Behavior is the same in Browser and Electron App version 2.4.0 (which I would expect as this is a server code issue not electron app).

Creating Direct Messages is a pain now for my users. While we understand how the function works, it just doesn't work as well. Particularly searching for a user is clumsy and very specific. Before you could search either first, last name or username and accurate suggestions would pop-up immediately. Similar to how it does now when creating a private group channel and selecting Users. That still works OK. But direct messages- not really. It is so bad it has halted the rest of my deployment to the remaining departments at my company.

Current behavior with Direct Messages when you enter a first name I only get suggestions of people I've previously chatted with almost instantly. Otherwise I don't get a proper name of who I'm looking for unless I search for Last Name or Username. 95% of my user bases instinct is to search first name. They've already made a fuss about searching usernames before First/Last name searches were developed to work solidly in the add user fields before the recent server updates.

Our usernames are in the format of FLast (first initial last name). And the left side-bar interface is garbage when I search for a first name and it's trying to find a room, see screen: This is the same result whether I'm using a browser or Electron app.

**Searching First Name Behavior current version (not working):**
![screen shot 2017-02-13 at 8 01 10 am](https://cloud.githubusercontent.com/assets/22967603/22891188/65ff113c-f1c3-11e6-902e-f490ff2153ef.png)
_^ Note the searching for room notification is cutoff._

**Searching Last Name behavior (working - same fine behavior when searching username ):**
![screen shot 2017-02-13 at 8 01 44 am](https://cloud.githubusercontent.com/assets/22967603/22891197/6ab572b6-f1c3-11e6-9c9c-280f167e4f44.png)

**Searching First Name in the Private Groups select Users window (this is how direct messages used to prompt quick and painlessly and how we need direct messages to work again):**
![screen shot 2017-02-13 at 8 03 21 am](https://cloud.githubusercontent.com/assets/22967603/22891209/731cd570-f1c3-11e6-90e1-72c32f3952b8.png)

**Comment by engelgabriel** [comment]
Thanks for the detailed explanation. Indeed I believe the new search query ignored the first name. We are already planning to add the option to use the Full Name in all areas of the platform, and because that was not completed yet, we had this gap in functionality. I'll ask the team to add the Full name field back in the query.

**Comment by Nosferous** [comment]
Thank you for the explanation. 

I see the left bar "Room not found" text has been fixed in version 0.52.0 and is no longer cutoff and this issue is now adjusted to a version 0.53.0 milestone. Looking forward to the update for full name in the query in 0.53.0!

**Comment by Nosferous** [comment]
What is the likeliness this one will be fixed in version 0.54.0? 
Originally it was milestoned for 0.52.0

My deployment is still halted due to this 1 issue.

thanks!

**Comment by localguru** [comment]
Yes please :D #6406

**Comment by engelgabriel** [comment]
@MartinSchoeler can you test this on the `develop` branch?

**Comment by engelgabriel** [comment]
Did https://github.com/RocketChat/Rocket.Chat/pull/3851 closed this?

**Comment by alexbrazier** [comment]
Yes, it now works on the latest version

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/3851

**Comment by Nosferous** [comment]
Confirmed that first name and full name searches are working again. Thank you for fixing this! I can now move forward with deployment!
