### ISSUE TITLE
Add Rocket.Chat to G Suite Marketplace

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6010]
Add Rocket.Chat to https://apps.google.com/marketplace/

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by rodrigok** [comment]
We don't have plans to work on this right now, please open a discussion in our [forums](https://forums.rocket.chat) if you want this feature.
