### ISSUE TITLE
Integration with Google+ Hangouts

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6012]
Google Hangouts lets you communicate with your team via instant messaging, voice calls, and video calls. This integration will allow you to easily start a Hangout with the members of a channel. To start a Hangout, enter `/hangout` in any channel. You will be given a link from which you can start the Hangout with a handy Rocket.Chat control panel on the right-hand side. From that panel, you can invite other Rocket.Chat team members to the Hangout.

**Comment by Rohlik** [comment]
I think that Hangouts is impossible to integrate RC - https://www.theregister.co.uk/2017/01/08/hangouts_hangs_up_on_third_party_apps/

**Comment by engelgabriel** [comment]
We can try something similar to Jitsi

```
https://hangouts.google.com/hangouts/_/[domain]/[rid]
```

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Closing as an app idea.  Could likely be implemented with existing alpha level feature set :smile:

**Comment by nopynoop** [comment]
We've been experiencing problems with jitsi and bbb lately. Would you consider implementing Google Hangouts again?

**Comment by geekgonecrazy** [comment]
Actually have seen someone integrate hangouts in the jitsi meet domain.  

Putting hangouts.google.com/ in the domain and hangouts/_/org-domain.com/ in the url room prefix

Kind of a hack taking advantage of how we show jitsi in iframe.  But works last I tested it

**Comment by nopynoop** [comment]
> Actually have seen someone integrate hangouts in the jitsi meet domain.
> 
> Putting hangouts.google.com/ in the domain and hangouts/_/org-domain.com/ in the url room prefix
> 
> Kind of a hack taking advantage of how we show jitsi in iframe. But works last I tested it

Wow, I just tested it and it really opens the hangout chat. 

Great idea @geekgonecrazy. Were you able to see someone else joining that hangout or you didn't test that far?

However, I can only see myself and the other party can see himself.

![V1hastes52](https://user-images.githubusercontent.com/25570106/76942307-d226e380-68fd-11ea-9850-4ebd2ad3b49f.png)

**Comment by geekgonecrazy** [comment]
It definitely used to work.  Actually was someone else in the community that suggested it.  Can’t remember where.

Is this in a google apps domain?  Are both of you signed into same org?
