### ISSUE TITLE
Integration with Google Calendar

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6013]

**Comment by Valiantiam** [comment]
+1

**Comment by koyan** [comment]
Hallo there,
I have created an integration, but it is using a python script (that accesses the google calendar API to receive the data, and post it to the RocketChat webhook. 
https://github.com/koyan/rocketchat-google-calendar
A better integration (for anyone who can do it) would be to do the same with Javascript (and have it integrated to RocketChat).

**Comment by hidalgo67** [comment]
Hi Koyan
I tried your python script and it works quite well. Except an issue with timezone. Always get the wrong time, no matter if I try to modify the script. The script gets the time from Google calendar correctly (CET) but thinks it’s UTC and adds 1 hour. I tried to remove the timezone shifting without any difference. Any hints?

**Comment by koyan** [comment]
Unfortunately this is something that I never gotten to fix either. It keeps on showing the timezone of the user who shared the calendar.

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Closing as an app idea
