### ISSUE TITLE
Integration with Google Sheets

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#6015]
Sheets is like a swiss army knife for information. Giving people an easy way to export to sheets, or to integrate sheets would open a world of possibilities for users. Especially less technical ones.

Thanks @MichaelJohnstone !

**Comment by graywolf336** [comment]
https://www.npmjs.com/package/google-spreadsheet

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Closing as an app idea and not a built in feature
