### ISSUE TITLE
Integration with Google Cloud Speech API

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6018]
# Powerful Speech Recognition

Google Cloud Speech API enables you to convert audio to text by applying neural network models in an easy to use API. The API recognizes over 80 languages and variants, to support your global user base. You can transcribe the text of users dictating to an application’s microphone or enable command-and-control through voice among many other use cases.

https://cloud.google.com/speech/

**Comment by TwizzyDizzy** [comment]
As discussed at the summit: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by rodrigok** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/11138
