### ISSUE TITLE
.bin extension added to dowloaded files

### ISSUE THREAD

**Issue by yannfill** [RocketChat/Rocket.Chat#6026]
Rocket.Chat Version: 0.51.0

Protect uploaded files enabled.

I sent a text file with a .conf extension, but when I download it a .bin extension is added (so it became file.conf.bin).

The file itself is a simple config file, but it contains a base64 encoded certificate.

**Comment by zyio** [comment]
Seeing same issue but seemingly only with .psd files.

**Comment by richardt3** [comment]
Have this in 0.53.0

Going via nginx.

**Comment by Gandalf-the-Grey** [comment]
Still present in `0.54.2`
"Storage Type" set to "FileSystem"
"Accepted Media Types" set to blank (otherwise it doesn't allow to upload text file with arbitrary extension)

**Comment by tomepsilva** [comment]
Same issue with 0.56.0 with FileSystem storage type.
After download the file it has a .bin extension

**Comment by Schobers** [comment]
Reproducable with Rocket.Chat version 0.56.0 using GridFS as "Storage Type" and "Accepted Media Types" empty as well.

**Comment by tomepsilva** [comment]
I've figured out that adding, editing or removing any character on file name in the saving path dialog, it works well. It removes the extra .bin extension
Tested with Rocket.Chat+ 2.8.0 and 0.56.0 with FileSystem storage type

**Comment by densik** [comment]
Hope this isn't forgotten, this is still a problem on 0.59.1, I'm using docker if that makes any difference. Also on GridFS and Accepted Media Types as empty.

@MartinSchoeler

**Comment by pascalrobert** [comment]
Just got the same issue with a Python script (.py). Didn't happen for a .php file.

**Comment by Maqsyo** [comment]
this issue still exists

**Comment by axchemezov** [comment]
Yes, there is problem with .PSD. Its uploading in messages but not sowed up in there.
https://ibb.co/jKGtty
https://ibb.co/caXoRJ

**Comment by KANU82** [comment]
The problem is also relevant in the release of 0.69.1, but it's far from the same with the files. Problem types * .dbf, * cdw, * .exp and many more non-standard formats. Help please solve.

**Comment by stleitner** [comment]
I have the same problem with Indesign *.indd files with version 0.69.2

**Comment by tassoevan** [comment]
@Hudell and @rodrigok: While triaging #8540, I discovered the `FileUpload.addExtensionTo(file)` method. Is it mandatory?

**Comment by fabien4455** [comment]
The problem is still present please fix it.

I have this problem with a lot of files.

**Comment by Nicolas-Alain** [comment]
Please help. I don't want to switch back to slack or go to Mattermost
