### ISSUE TITLE
Pressing ESC to cancel previous post editing mode doesn't work

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#603]
Pressing ESC key doesn't cancel edit for me on window 7 machine with chrome browser version 43.0.2357.134 m.

However, when I click `esc to cancel` link at the bottom of text box, it works.

**Comment by graywolf336** [comment]
Think this escape capture and the read line escape capture are conflicting.

**Comment by marceloschmidt** [comment]
I could not reproduce this error. If this is still an issue, please report back.
