### ISSUE TITLE
Internal Bot not Working with the Live Chat

### ISSUE THREAD

**Issue by NoahDragon** [RocketChat/Rocket.Chat#6030]
Rocket.Chat Version:  0.51.0
Running Instances:  1
DB Replicaset OpLog:
Node Version: 4.6.2

I have added the internal Bot as the livechat agent, but it doesn't reply any messages in the live chat channel.

I tested it on the general channel, the bot works.

**Comment by vdittgen** [comment]
In my tests it responds on Livechat only if you put the bot name as the first word.
I need the bot to respond even if his name is not in the phrase, like an normal DM.
Is there any configuration I am missing?

Using `RESPOND_TO_DM=true` works on DMs but not on Livechat.

➔ +---------------------------------------------------------+
➔ |                      SERVER RUNNING                     |
➔ +---------------------------------------------------------+
➔ |                                                         |
➔ |  Rocket.Chat Version: 0.53.0                            |
➔ |       NodeJS Version: 4.8.0 - x64                       |
➔ |             Platform: linux                             |
➔ |     ReplicaSet OpLog: Disabled                          |
➔ |          Commit Hash: cbdc26ded8                        |
➔ |        Commit Branch: HEAD                              |
➔ |                                                         |
➔ +---------------------------------------------------------+

**Comment by gugahoa** [comment]
How it's working right now:
- Livechat guest/user creates a room with first message
- Bot is added to the room after it's created 
- Livechat Room is not considered DM, so you need to mention the bot

I made a basic PR to add the feature to respond the livechat (https://github.com/RocketChat/hubot-rocketchat/pull/211)

**Comment by timkinnane** [comment]
@sampaiodiego @geekgonecrazy - can either of you confirm if this is closed? The PR was merged, but does it need testing?

**Comment by geekgonecrazy** [comment]
@timkinnane my experience with internal hubot is very limited.  😁 I think should work with that PR though

**Comment by timkinnane** [comment]
Closing then. Please see the [last comment on this related issue](https://github.com/RocketChat/Rocket.Chat/issues/8025#issuecomment-381470969).

**Comment by AmirHadifar** [comment]
Same issue as @NoahDragon 
hubot help not working in livechat. It respond to General channels but not livechat.

Any fix on this?

**Comment by AmirHadifar** [comment]
Thanks for your answer. My problem fixed when I set hubot as a only agent of livechat.

**Comment by BigBangBit** [comment]
> Please try setting `RESPOND_TO_LIVECHAT=true` in your environment.

Please, tell me where I put this variable.

many thanks
