### ISSUE TITLE
Narrow view CMD+P followed by Esc leaves sidenav locked

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#6031]
Rocket.Chat Version: 0.53.0-develop (demo.rocket.chat), 0.52.0 (snap)

Tested with Chrome:
When sidenav is invoked from a narrow view (CMD+P), followed by Esc to dismiss it again, the sidenav remains open and locked in place, instead of being moved off screen. Chat is reactivated, which is good, but the sidenav stays until a site refresh.

**Comment by rodrigok** [comment]
@karlprieb can you fix this one? The best solution is to close the sidenav always when the message box receives focus. The esc on toolbar search is already setting focus on message box and everything should works 😄
