### ISSUE TITLE
Livechat Widget -  Unable to type.

### ISSUE THREAD

**Issue by deep0892** [RocketChat/Rocket.Chat#6042]
![whatsapp image 2017-02-15 at 9 52 13 am](https://cloud.githubusercontent.com/assets/14363289/22960758/8003da96-f366-11e6-8200-01c1d4635b66.jpeg)
![whatsapp image 2017-02-15 at 9 52 00 am](https://cloud.githubusercontent.com/assets/14363289/22960759/80082f42-f366-11e6-932f-7ecb16f297f1.jpeg)

The Livechat Widget on Iphone does not work properly. On clicking on any of the textareas the textarea and the widget disappears and the one cannot see what is being typed.
![ezgif com-547a9fbdf0](https://cloud.githubusercontent.com/assets/14363289/22960827/14a10a2a-f367-11e6-9106-f50537db0b2d.gif)

**Comment by deep0892** [comment]
I know i am being pushy but someone please help me out with this is on production and has great impact on customer experience.

**Comment by jitendrasPB** [comment]
I am also facing the same issue on ios for both offline and online chat widget,

**Comment by deep0892** [comment]
Thanks alot @karlprieb !!!
