### ISSUE TITLE
Exception from sub stream-notify-room 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#6043]
Rocket.Chat Version: 052.0
Running Instances: 
DB Replicaset OpLog:enabled
Node Version: 4.6.2 - x64 
when deleted room and created another room i get this error:
Exception from sub stream-notify-room id Xu34v6Th7Xh5sXqab { stack: 'TypeError: Cannot read property \'t\' of undefined<br>  at Subscription.<anonymous> (/root/wetalk/programs/server/packages/rocketchat_lib.js:3493:15)<br>  at Streamer.isReadAllowed (/root/wetalk/programs/server/packages/rocketchat_streamer.js:326:38)<br>  at Subscription.<anonymous> (/root/wetalk/programs/server/packages/rocketchat_streamer.js:457:16)<br>  at Subscription.<anonymous> (/root/wetalk/programs/server/packages/rocketchat_lib.js:1083:15)<br>  at packages/matb33_collection-hooks.js:307:21<br>  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)<br>  at Subscription._handler (packages/matb33_collection-hooks.js:306:28)<br>  at maybeAuditArgumentChecks (/root/wetalk/programs/server/packages/ddp-server.js:2108:12)<br>  at Subscription._runHandler (/root/wetalk/programs/server/packages/ddp-server.js:1382:19)<br>  at Subscription.subscriptionProto._runHandler (packages/meteorhacks_kadira.js:2781:24)<br>  at Session._startSubscription (/root/wetalk/programs/server/packages/ddp-server.js:1192:11)<br>  at Session.sub (/root/wetalk/programs/server/packages/ddp-server.js:946:14)<br>  at packages/meteorhacks_kadira.js:2644:34<br>  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)<br>  at Session.sessionProto.protocol_handlers.sub (packages/meteorhacks_kadira.js:2643:44)<br>  at /root/wetalk/programs/server/packages/ddp-server.js:880:89<br>',   source: 'subscription' }

**Comment by ggazzo** [comment]
@fifou17 closing this issue, please reopen if the problem persists
