### ISSUE TITLE
iOS image upload

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#6045]
Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: false
Node Version: 4.6.2

Image upload from camera on iOS via native app is poor. Seems to work OK on Android.

Using iOS 10.2.1 on iPhone 6s

- after taking picture, upload file interface loads with input field for file description. When try to enter text, keyboard overlays the interface so user cannot see the text being input (NB on Android the interface repositions so that input field remains visible) 
![img_4246](https://cloud.githubusercontent.com/assets/1432373/22961628/ba5cefe0-f39b-11e6-94e5-3da56f9d740e.PNG)

- after collapsing keyboard (which itself seems unreliable - took several taps around screen to get rid of it) the buttons on file upload interface fall off bottom of screen and are unusable
![img_4248](https://cloud.githubusercontent.com/assets/1432373/22961672/09590584-f39c-11e6-9cf4-b4f1bd565181.PNG)

**Comment by TheReal1604** [comment]
duplicate https://github.com/RocketChat/Rocket.Chat/issues/5514 https://github.com/RocketChat/Rocket.Chat/issues/5513
