### ISSUE TITLE
Client files that live outside `/client` folders.

### ISSUE THREAD

**Issue by Kiran-Rao** [RocketChat/Rocket.Chat#6046]
Any client-only files that do not live within a client/ folder causes meteor server to reboot rather than a client refresh. 

@rodrigok 
Related: https://github.com/RocketChat/Rocket.Chat/pull/6016#issuecomment-279896521

Packages:

### Meteor (I'm not sure we should modify these)
- [ ] meteor-accounts-saml 
- [x] meteor-autocomplete
- [x] meteor-timesync

### Rocketchat
- [x] rocketchat-autolinker
- [x] rocketchat-cas
- [x] rocketchat-colors
- [x] rocketchat-custom-oauth
- [x] rocketchat-custom-sounds # admin 
- [x] rocketchat-emoji
- [x] rocketchat-emoji-emojione
- [x] rocketchat-favico
- [x] rocketchat-highlight-words
- [ ] rocketchat-iframe-login
- [x] rocketchat-logger # antispan.js, logger.coffee
- [ ] rocketchat-markdown
- [x] rocketchat-mentions
- [x] rocketchat-slackbridge # slashcommand
- [x] rocketchat-slashcommands-archiveroom
- [x] rocketchat-slashcommands-create
- [x] rocketchat-slashcommands-invite
- [x] rocketchat-slashcommands-inviteall
- [x] rocketchat-slashcommands-join
- [x] rocketchat-slashcommands-kick
- [ ] rocketchat-slashcommands-leave # Should be split into client/server
- [x] rocketchat-slashcommands-open
- [x] rocketchat-slashcommands-topic
- [x] rocketchat-slashcommands-unarchiveroom
- [x] rocketchat-tooltip
- [x] rocketchat-ui
- [x] rocketchat-ui-account
- [x] rocketchat-ui-admin
- [x] rocketchat-ui-flextab
- [x] rocketchat-ui-login
- [x] rocketchat-ui-master # master
- [x] rocketchat-ui-message
- [x] rocketchat-webrtc
- [x] rocketchat-wordpress

I would say go through the `rocketchat-ui-` first as they'll benefit the most.

**Comment by vcapretz** [comment]
hi @Kiran-Rao as the PR's I opened were already approved, can you mark the checkboxes so people will know they are completed? I'm going to take a few more now!

**Comment by Kiran-Rao** [comment]
@vcapretz Sure. 

I'll watch out for them in the next few days.

**Comment by Kiran-Rao** [comment]
@vcapretz Can you tag me when these get merged?
