### ISSUE TITLE
Can we have a emoji's in gif.

### ISSUE THREAD

**Issue by spathare21** [RocketChat/Rocket.Chat#6047]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

can we have a face emojis gif . it will be very good looking. 

I think no any app is having and gif emojis. if we will implement it wil be an good future for us. and will be an advantage to increase users.

Also if we implement , personal chatbot for everyone, like chat support/like google Alo personal assistance. will increase the rocket chat publicity.

**Comment by divergefx** [comment]
I downloaded all the skype emoji and uploaded to custom emoji using admin UI. They are all animated gif, and everyone loves them.

**Comment by graywolf336** [comment]
Yes, gifs can be used as custom emojis.
