### ISSUE TITLE
How to add packages

### ISSUE THREAD

**Issue by kiamgrebgnur** [RocketChat/Rocket.Chat#6048]
#Hi,

the last time I added a package (to version 0.30) I used something like that:

```
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
git checkout 0.30.0
curl https://install.meteor.com/ | sh
cd Rocket.Chat/packages/
mkdir my-own-package & cd 
vim client.coffee
vim package.js
meteor add rocketchat:my-own-package
meteor build rocketbuild
```

is that still the right way? I can't find any documentation for that...

Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: v4.6.2

**Comment by kiamgrebgnur** [comment]
Ok seems that it's possible to just add the script to _bundle/programs/server/packages/modules.js_
_bundle/programs/server/program.json_ and copy it to _bundle/programs/server/packages/_  in the release version. So I don't need to do the whole `meteor build` stuff.

Is that the preferred way?

**Comment by stuurgurs** [comment]
There is an answer: http://stackoverflow.com/questions/28473806/how-to-add-a-meteor-package-manually

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)

**Comment by miguelmota** [comment]
To add a package, do:

```
meteor add rocketchat:my-package-name
```
