### ISSUE TITLE
Allow post to join the channel

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#605]
Currently, you have to join the channel to be able to post. Could we make it so that user can just join the channel by typing a message? This would be much more welcoming.
##

**Comment by palacz123** [comment]
I'd like to upvote for this feature. 
It would be extremely helpful if messages containing channel name would be also posted to that channel. I.e if finance person posts message "we need to talk to #sales" on #finance channel, the same message would be also posted on #sales channel

**Comment by giray** [comment]
+1

**Comment by philipwhiuk** [comment]
> It would be extremely helpful if messages containing channel name would be also posted to that channel. I.e if finance person posts message "we need to talk to #sales" on #finance channel, the same message would be also posted on #sales channel

That's a totally different feature request palacz. IMO just mentioning a channel by name shouldn't by default do this behaviour.

**Comment by Sing-Li** [comment]
Agreed.  I believe @mitar is talking about  `/join #sales`  and `/join #finance`  and not auto join on channel mentions.

**Comment by palacz123** [comment]
Ok, I may have misunderstood his statement...  I agree with philipwhiuk that it shouldn't be default but an option that you can enable (global or per channel level). Idea is to send messages to specified group of people without having to join their channel or having to get all recepients to join channel where original message was posted.  Currently there's no other way to address groups of people afaik.

**Comment by Sing-Li** [comment]
@palacz123   I believe we're both (all three) saying that your 'feature' requirement is worthy of another independent github issue :smile:

**Comment by palacz123** [comment]
@Sing-Li ok, thanks,  I will open a new one  :)

**Comment by mitar** [comment]
Hm, I am saying that typing message "hi people" should join the channel if you opened it. No need to explicitly join the channel first.

**Comment by mmenze** [comment]
This would be very useful. 
+1

**Comment by geekgonecrazy** [comment]
In its current suggested state this isn't something we plan to implement.   Going to go ahead and close. 

Feel free to open a detailed post in our [forum](https://forums.rocket.chat) in the feature request category for others to upvote and help improve the idea.
