### ISSUE TITLE
'callInProgress' variable in WebRTCClass.coffee doesn't change.

### ISSUE THREAD

**Issue by Gyubin** [RocketChat/Rocket.Chat#6051]
Rocket.Chat Version: 0.53-develop
Running Instances: I don't know
DB Replicaset OpLog: Enabled
Node Version: 4.7.3

`onRemoteStatus` method in `WebRTCClass` class is never called. For this reason, i think, `callInProgress`'s value doesn't change. The value is always `false`.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
