### ISSUE TITLE
Thumbnail doesnt show with links 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6052]
Hyper links posted in chat room, doesnt show the thumbnail images, it used to work before upgrading from 0.48.1 to recent models, 49,50,51,52...  

![image](https://cloud.githubusercontent.com/assets/12454319/22977769/112ef1a8-f35e-11e6-96de-7c4c98b12246.png)

http://www.recode.net/2017/2/14/14619444/jack-dorsey-twitter-stock-buy

Rocket.Chat Version: 52.00
OS Platform	linux
OS Arch	x64
OS Release	4.4.0-51-generic
Node version	v4.7.3

**Comment by IQ2022** [comment]
any update on this one? i still dont get any thumbnails show when i post a hyper link

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Cannot reproduce on current stable. Can you? If so, please get back to me!

Cheers
Thomas
