### ISSUE TITLE
Hide edited status from message box not working

### ISSUE THREAD

**Issue by divergefx** [RocketChat/Rocket.Chat#6054]
Rocket.Chat Version: 0.52.0
Running Instances: 
DB Replicaset OpLog:
Node Version: Latest

This issue started in 0.51.0 I believe.  I used the option to hide edited message status from the message box.

![image](https://cloud.githubusercontent.com/assets/19717574/22981148/9cdc4f60-f369-11e6-9996-bd905863e269.png)

![image](https://cloud.githubusercontent.com/assets/19717574/22981191/be863464-f369-11e6-8e1e-11f818d3e6ac.png)

**Comment by saram-kon** [comment]
I don't have this problem, but as a workaround you could add to your custom css (under Layout):
`.edited {
display: none;
}`

**Comment by divergefx** [comment]
That doesnt fix the issue.  Not urgent though.

**Comment by divergefx** [comment]
Needed both:

.edited{
	display: none;
}

.message.sequential .info .edited {
    display: none;
}  

Thanks @saram-kon

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
