### ISSUE TITLE
Could we add a voting system to the channel ? 

### ISSUE THREAD

**Issue by toby1991** [RocketChat/Rocket.Chat#6063]
Rocket.Chat Version: 

> 0.51.0

Running Instances: 

> 1

DB Replicaset OpLog: 

> Disabled

Node Version:

> I use docker image.

**Comment by graywolf336** [comment]
I do believe this is a duplicate of: https://github.com/RocketChat/Rocket.Chat/issues/3615

**Comment by toby1991** [comment]
@graywolf336  wow! excellent!  So I'll close this issue.
