### ISSUE TITLE
Room  stays marked as unread until a new message is written

### ISSUE THREAD

**Issue by saram-kon** [RocketChat/Rocket.Chat#6069]
Rocket.Chat Version: 52
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.7.3

This problem is haunting us since our deployment in December last year. Occasionally a room stays marked as unread after every message is read and it persists after switching to another channel and back to the original. The only solution seems a new message. The problem occurs often for multiple people at the same time, but definitely not for everyone. We think it might occur, if the last message in the room was deleted before reading it, but testing did not lead to the bug.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
