### ISSUE TITLE
fix user edit form - email verification

### ISSUE THREAD

**Issue by johnny333** [RocketChat/Rocket.Chat#6072]
if you try change email verification on false, Mongo throw error about empty $set
packages/rocketchat-lib/server/functions/saveUser.js#L166-L166

My proposition is : 
if (userData.hasOwnProperty('verified')) {
			updateUser.$set['emails.0.verified'] = userData.verified;
		}

Rocket.Chat Version: develop
Running Instances: 
DB Replicaset OpLog: 3.2.11
Node Version:4.6.2

**Comment by Hudell** [comment]
This issue was already fixed.
