### ISSUE TITLE
E-mail notifications are blocked from getting to google servers 

### ISSUE THREAD

**Issue by udezekene** [RocketChat/Rocket.Chat#6074]
I use sendgrid for e-mail notifications but e-mails to Google.com gets blocked because "FROM" is missing from the message Header.

Anyone know how I can fix this?
 

Rocket.Chat Version: v0.1.4
Running Instances: using Docker

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

As far as I can see, this is not the case anymore. Please correct me, if I'm missing something.

Cheers
Thomas
