### ISSUE TITLE
How to update the Rocket.Chat in Heroku without losing data?

### ISSUE THREAD

**Issue by NoahDragon** [RocketChat/Rocket.Chat#6076]
Rocket.Chat Version:  0.51.0
Running Instances:  1
DB Replicaset OpLog:
Node Version: 4.6.2

I'm trying to update the Rocket.Chat to the 0.52.0 version. Currently, I only figure out to recreate a dyno, but all data are lost. Is there any way to update without losing configuration and data?

**Comment by engelgabriel** [comment]
The data is stored on the mLab MongoDB, so you just need to point to the same database.

**Comment by NoahDragon** [comment]
@engelgabriel Thanks, it works. But when I in the admin page, it always popup the error message, which is annoy. Do you have any ideas?

![image](https://cloud.githubusercontent.com/assets/5704064/23521981/57ffcf88-ff4f-11e6-826f-5b0d1eca4cab.png)
