### ISSUE TITLE
issues on mailers and email registration verification

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#6078]
Rocket.Chat Version: 0.52 on Ubuntu 16.04 

1. email registration verification: i set it up as email verification for registration. it does show on RC the   message: "we have sent an email to verify your registration...", and i set up STMP and did test try and it works. But user just won't get the verification email. user used Hotmail.

2. I am trying to send email to everyone in Mailer section, i didn't work, this is what i put in 
    From:  info@example.com
    Dry run: unchecked
    Query: left blank
    Subject: Email Subject
    Email body: Email body
  
   Then when i tried it, i always get the error message saying: "you must provide [unsubscribe link]". I        don't know how to do that?

**Comment by pierreozoux** [comment]
Did you configure MAIL_URL or SMTP settings in Admin? or both?

**Comment by pkgodara** [comment]
Hi, for sending the mails using mailer section, just type "[unsubscribe]" in Email body. It will automatically provide unsubscribe link and would work.

**Comment by jy2008** [comment]
Thanks it works now. another question: it will always present a link to whoever i email to as below
https://chat.usorgames.com/mailer/unsubscribe/rYNQ7mvHv2hPpLDyy/1487221408395.
What is the purpose of this link, i clicked on it, it took me to some RC pg, is this link customizable?

**Comment by pkgodara** [comment]
I think it's unsubscribe link and compulsory to protect user rights and I don't think it's customizable.

**Comment by pkgodara** [comment]
It lets users unsubscribe themselves from such emails.

**Comment by pkgodara** [comment]
Please close the issue if problem is solved. Thanks
