### ISSUE TITLE
The username is lost after updating a user 

### ISSUE THREAD

**Issue by stephaneeybert** [RocketChat/Rocket.Chat#6080]
As an admin, when I update a user, changing its user name, saving, and then coming back to editing that same user, its user name is blank again. I'm talking of the user name, and not the display name.

Rocket.Chat Version: 0.49
Running Instances: 1
DB Replicaset OpLog:
Node Version: 6.8.1

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
