### ISSUE TITLE
The user name is always required, ignoring the settings not to.

### ISSUE THREAD

**Issue by stephaneeybert** [RocketChat/Rocket.Chat#6081]
As an admin, when editing a user, the user name is always required, ignoring the settings in the registration not to require a name to register.

Rocket.Chat Version: 0.49
Running Instances: 1
DB Replicaset OpLog:
Node Version: 6.8.1

**Comment by marceloschmidt** [comment]
If user name is not required, should we allow setting it to empty after it has been set to something?
