### ISSUE TITLE
Avatoar upload permission error

### ISSUE THREAD

**Issue by imtrobin** [RocketChat/Rocket.Chat#6092]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version:4.7.3

Hi, I just updated from 0.39 to latest (docker version). The 0.39, server would crash when I set avatar. 0.52.0, I'm getting an error when I set upload.

Exception in callback of async function: Error: EACCES: permission denied, open '/app/uploads/robin.jpg'   at Error (native)

**Comment by saram-kon** [comment]
This sounds like a mistake in your user and permission management. How do you start your container? And which operating system are you using?

**Comment by imtrobin** [comment]
ubuntu

docker-compose -f /home/rocketchat/docker-compose.yml  up -d web
in rc.local to autoboot

**Comment by saram-kon** [comment]
This should start the process as root. I had some ideas, what could have caused the issue, but testing them lead to nothing. Could you still check, just to be sure, that all the docker processes run as root with `ps -eF | grep docker
`?

**Comment by imtrobin** [comment]
root@rocketchat:~# ps -eF | grep docker
root      1074     1  0 143122 20048  0 Feb21 ?        00:00:15 /usr/bin/docker daemon -H fd://
root      1081  1074  0 69437  5896   0 Feb21 ?        00:00:01 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc --start-timeout 2m
root      1369  1081  0 50124  2396   0 Feb21 ?        00:00:00 docker-containerd-shim 2ff1596c622a964dd620d1cd257bdf0678e157fb790c7a1355efb4cfc7fbc733 /var/run/docker/libcontainerd/2ff1596c622a964dd620d1cd257bdf0678e157fb790c7a1355efb4cfc7fbc733 docker-runc
root      1464  1074  0 40119  7640   0 Feb21 ?        00:00:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.3 -container-port 3000
root      1493  1081  0 50124  4092   0 Feb21 ?        00:00:00 docker-containerd-shim e4d90c5bd326706f840b40fcbf9e910944f39516d17ae562ef45f6b4f683356b /var/run/docker/libcontainerd/e4d90c5bd326706f840b40fcbf9e910944f39516d17ae562ef45f6b4f683356b docker-runc
root     11142 11126  0  3629  1012   0 00:55 pts/0    00:00:00 grep --color=auto docker

**Comment by saram-kon** [comment]
Sorry that I did not write anything again, here is carnival.
It seems alright. Could you maybe check, what is set as the storage type for the avatars in the administration panel under Accounts/Avatar?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
