### ISSUE TITLE
Video calls not working since upgrading from 0.44 to 0.52.0

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#6099]
Used to have video chat working and now it's not.  I'm not getting an error message.  But when I click the video button, the little light on my webcam turns on, but nothing happens except the icon to start a video chat and audio chat disappear.

Rocket.Chat Version: 0.52.0
Running Instances:  1 
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by geekgonecrazy** [comment]
Closing since a version long since not supported
