### ISSUE TITLE
Support Atlassian FishEye and Crucible

### ISSUE THREAD

**Issue by kumairyosuke** [RocketChat/Rocket.Chat#6102]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

JIRA seems to be supported by Rocket.Chat, but is FishEye or Crucible supported? If not, are you planning to support?

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
