### ISSUE TITLE
Invalid Code message for password protected channel

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#6106]
When there is a password set to a channel - users can't join the channel even when they know the password. When they click "Join" they are not prompted for the password but they get "Invalid Code" error immediately. 
Maybe I am missing something - how are users to supposed to join password protected channels when they know the password? And also I think the message should be "Invalid Password" after changing the terminology from Code to Password :)

The log is not saying anything useful even on Debug settings. The only information is (ids were changed):
`rocketchat_1  | Meteor ➔ method joinRoom -> userId: XXXXXXXXX , arguments:  { '0': YYYYYYYYYYYYY', '1': null }`

Rocket.Chat Version: 0.52
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by saeedjalali1** [comment]
Hi @danpospisil @marceloschmidt 
I have same issue, is there any solution for that?

**Comment by cyclops24** [comment]
+1
Please provide some fix for this feature. Password protected room is very important feature for me.

**Comment by marceloschmidt** [comment]
@rodrigok can you please take a look?

**Comment by cyclops24** [comment]
@rodrigok did you found anything? I try find that why this issue happens but I can't found anything. 😢

**Comment by saeedjalali1** [comment]
Hi, @rodrigok, @marceloschmidt, @ cyclops24 @danpospisil
I'm trying to fix this bug.In this code 
```html
{{#if joinCodeRequired}}
	<input type="text" name="joinCode" placeholder="{{_ 'Code'}}" style="width: 100px">
{{/if}}
```
the `joinCodeRequired` is `undefined`. but is insert to database. I don`t understand why joinCodeRequired is undefined in client.
is there any solution?
thanks

**Comment by rogueslerv21** [comment]
I too get invalid coce on 57.2 when users try to join password protected channel. They are not prompted anywhere for the pw

**Comment by ruKurz** [comment]
same issue on our side.
Are there any plans how to deals with this issue?

**Comment by gjsman** [comment]
This needs fixing as soon as possible. The next release shouldn't be approved until this is fixed. We can't have obviously broken logic like this.

**Comment by cyclops24** [comment]
Part of #8494
