### ISSUE TITLE
How to find owner of a room?

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#6107]
Is it somehow possible to find out who is the room owner for a regular user? The only way I can think of now is to click every single user in the room and find the owner which is not really useful. If its not possible, could it be added? 

Rocket.Chat Version: 0.52
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by jblobel** [comment]
Maybe with badges ? https://github.com/RocketChat/Rocket.Chat/issues/5848

**Comment by nakic** [comment]
I just had Martin's problem, trying to find out who the owner was. Never in a million years would I expect that I should look into the main discussion log for this (and what if the owner didn't actually say anything yet? no badge, no info?).

I would strongly suggest that the owner name should be prominently placed in the "Room info" or "Members list" side view.

**Comment by rodrigok** [comment]
We may add the roles by the user's name/username at the members list.
Changing this to planned for UI/UX definition.

**Comment by jouniaj** [comment]
What happened to this feature request? Could this be added again to some of the next milestones? I think it's still very hard to find owner of the channel.

**Comment by sennewood** [comment]
Similar, but better issue: https://github.com/RocketChat/Rocket.Chat/issues/13967

**Comment by cgm-test** [comment]
Would be nice if you could add a @owner tag to address the owner directly without knowing who it is.

**Comment by ankar84** [comment]
Users ask for it!

**Comment by erget** [comment]
:+1:

**Comment by ankar84** [comment]
> We may add the roles by the user's name/username at the members list. Changing this to planned for UI/UX definition.

@rodrigok @tassoevan @brunosquadros hello!
Is that still planned?
I think a simple sorting rules could be the solution for that:
1. Owners
2. Moderators
3. Regular chat members
What do you think?

**Comment by sandrotanner** [comment]
I get asked this by users alomost every week

**Comment by TBG-FR** [comment]
We need that feature, I agree !

**Comment by eidze1** [comment]
I have to use this software for some information exchange. Really, really politely said, it's somewhat disappointing, that this seemingly very basic thing to implement won't get anywhere.

**Comment by sandrotanner** [comment]
@rodrigok this issue has the flag "planned". could you let us know for which release it is planned?

**Comment by smuuf** [comment]
Issue https://github.com/RocketChat/feature-requests/issues/508 may be "similar, but better", but since it's been open for 6 years, it might be that simply showing `owner` next to a user in room's member's list could be done more quickly.

Edit: It looks like it's been already done in https://github.com/RocketChat/Rocket.Chat/pull/35208
