### ISSUE TITLE
Offer tab for Etherpad page per room

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6111]
One of our chat communities is making heavily use of etherpad pages for collaborative notes. It would be awesome if for each channel a pad would be assigned by default and could be opened similar to the Jitsi Videobridge tab as an iFrame.

We do not even need any API calls to the etherpad instance, simply call a URl https://myEtherpad.tld/p/hashedroomname and show it in the iFrame. As an example, have a look at our date finder, which offers also an etherpad to write meeting notes: http://termino.osalliance.com/rocket_chat_demo/

I know that Jitsi Videobridge allows to use a joint etherpad during a video call as well. Ideally they use the same hash value as if an etherpad would be called directly.

This may be a starting point for implementation:  https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-videobridge/client/tabBar.js

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,

**Comment by mibressler** [comment]
any updates on this? would certainly be a great App!
