### ISSUE TITLE
Android App - very slow loading while on wifi since 0.52

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#6112]
Last days I get a lot of complains from Android users that Rocket.Chat is loading very slow. After its loaded its fast as before. 
But it happens only on wifi - when they switch to mobile data its very quick. Now I experience it as well - when I am on wifi the app screen is showing message "Loading example.com..." for 1.5 minutes. When I try it again on mobile data it gets loaded within 10 seconds (I kill the app every time). I have tried many wifi networks and android phones and it acts the same. Funny thing is, when I connect the phone on wire network it loads quickly also. 
So as a last call I tried to connect the App to demo.rocket.chat - and it does the same. 
I have tried the iOS app and it loads in seconds even on wifi. 
Any advice what to do? It seems something has changed in v 0.51 or 0.52 - Franz client started to report Rocket.Chat servers as "The URL you have entered is not a valid server" even though I am connected to it and new clients can't connect with Franz anymore.

Rocket.Chat Version: 0.52
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: v 4.7.3

**Comment by danpospisil** [comment]
So I have tried to do a fresh install (docker image with example docker-compose) with just one user and I started with 0.50.1 - it was working ok. The same with 0.51.0 .. but immediately after I upgraded to 0.52.0 the issue appeared. So it seems to be related to this version.

**Comment by danpospisil** [comment]
One last piece of information - Rocket.Chat loads quickly in web browser on the same devices connected to wifi. But at the same time the App loads very slow.

**Comment by TheReal1604** [comment]
Got the same reports from my android users!

**Comment by rodrigok** [comment]
@danpospisil Thanks by the report. We start a contact with franz guys to see what is happening, we did some change on our API `/api/info` to prevent data leak, maybe they are using more info from their.

About the slow behavior, we are investigating, I can't reproduce here, I'll ask the team to test this.

**Comment by danpospisil** [comment]
Its really weird that it happens just on wifi - i started to blame the wifi itself, but then I have seen its on every wifi and when I load it in the browser it loads fine. 
Also the alternative app Rocket.Chat+ gets stuck on login screen with bubbles going and going and it doesn't matter if I am on wifi or mobile data. 
Release 0.52.0 really broke A TON of things for us and I would really like to downgrade back to 0.51.0 - would that be difficult?

**Comment by amenk** [comment]
Can reproduce as well. How can this be debugged? `logcat` is not showing much useful.


without wifi - one second

    02-24 22:14:17.961   751  2549 I ExtendedNuUtils: printFileName fd(8) -> /data/app/com.konecty.rocket.chat-1/base.
    02-24 22:14:18.616  9187 10080 V meteor.cordova.updater: remapUri http://httpschat2examplede.meteor.local/packages/rocketchat_videobridge/client/public/external_api.js?_=1487970854861



with WIFI - one minute

    02-24 22:15:42.206   751  2549 I ExtendedNuUtils: printFileName fd(8) -> /data/app/com.konecty.rocket.chat-1/base.apk
    02-24 22:16:43.238 25829 25867 V meteor.cordova.updater: remapUri http://httpschat2examplede.meteor.local/packages/rocketchat_videobridge/client/public/external_api.js?_=1487970939140

**Comment by TheReal1604** [comment]
Some news on this? This is URGENT for us. :(

**Comment by Rohlik** [comment]
@TheReal1604 Milestone 0.53.0 was set, so I thing we can expect fix in next release.

**Comment by TheReal1604** [comment]
This also happens with 0.53.0. Tested it with a Nexus 5.

**Comment by danpospisil** [comment]
@TheReal1604 - yep, still the same. 
@rodrigok - is actually anyone working on this? Can we help somehow?

**Comment by laggedHero** [comment]
It is related to the new notification sounds ( `ding` and etc) but I cannot figure out what to do; it may be file corruption, no file at all, mp3 format errors, incorrect loading...

The error comes from chromium when it talks to some native lib

I tried to find out where it's loading

But, well... I failed

**Comment by TheReal1604** [comment]
@laggedHero Is there a workaround to disable the loading of this files or changing the files myself?

**Comment by danpospisil** [comment]
@TheReal1604 By now I am affraid that the workaround is called Slack because I dont see any effort from the developpers to solve this...

**Comment by laggedHero** [comment]
Hi all,

Sorry if I'm not a JS/HTML/CSS guy and that I have no prior experience with Cordova apps and its details.

We know that this bug is really annoying and we are working on it. I'd love to give a deadline but that I cannot do.

We'll fix this. For real. We just need some extra time.
