### ISSUE TITLE
Franz - invalid URL since 0.52.0

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#6115]
Since version 0.52.0 we are not able to add our server to client Franz. I have installed a fresh docker instance to test starting at 0.51.0 which was working. The I upgraded the server to 0.52.0 and Franz started throwing error message "The URL you've entered is not a valid server". Its showing this message even for demo.rocket.chat. See attached screenshot. 
![franz](https://cloud.githubusercontent.com/assets/1143037/23145463/9758aaf2-f7ce-11e6-9649-914f1571284d.png)

Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.7.3

**Comment by tarabanton** [comment]
Same issue here.

```
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.6.0
```

**Comment by danpospisil** [comment]
I have found a workaround for now. 

1. Install older Rocket.Chat somewhere (even locally)
2. Create new Rocket.Chat instance in Franz pointing to older Rocket.Chat version - it will connect without problem.
3. Quit Franz
4. Open services.json file (in %USERPROFILE%\AppData\Roaming\Franz\settings) and edit server URL from server specified in step 1 to your 0.52.0 server and save.
5. Start Franz again and it should connect to your server with no problem.

**Comment by ebalsumgo** [comment]
can you post an example block?

**Comment by danpospisil** [comment]
@ebalsumgo - what exactly do you mean by "example block"?

**Comment by ebalsumgo** [comment]
@danpospisil example of the json block you have in the settings.json file

**Comment by danpospisil** [comment]
@ebalsumgo - its useles as Franz generates somehow unique instance ID and its not transferable (RC will not load at all - you will see just a blank window). So you have to go through this procedure. 
Example is this:
```
{
  "services": [
    {
      "notifications": true,
      "count_message_direct": 0,
      "count_message_indirect": 0,
      "zoom": 0,
      "showIndirectMessages": true,
      "enabled": true,
      "focusMode": true,
      "id": "UNIQUE_ID",
      "order": 1,
      "service": "rocketchat",
      "name": "Name",
      "mute_audio": false,
      "customURL": true,
      "team": "https://URL_HERE"
    }
  ]
}
```

**Comment by danpospisil** [comment]
So .. there is an update workaround without the need of older server:
1) Install Franz and quit it (ot just quit if you have it installed).

2) Open services.json file (in %USERPROFILE%\AppData\Roaming\Franz\settings) and change it to following (don't forget to change ( "team": "https://URL_HERE") (still I have no idea what the field "id" does, but it works):
```
{
  "services": [
    {
      "notifications": true,
      "count_message_direct": 0,
      "count_message_indirect": 0,
      "zoom": 0,
      "showIndirectMessages": true,
      "enabled": true,
      "focusMode": true,
      "id": "abcd123",
      "order": 1,
      "service": "rocketchat",
      "name": "Name",
      "mute_audio": false,
      "customURL": true,
      "team": "https://URL_HERE"
    }
  ]
}
```
(if you already have some services there, you will have to add one service in the json list).

3) Start Franz and click the tab even when its selected  (this got me confused on the first try). It will load RC.

4) Login and enjoy :)

**Comment by cpitman** [comment]
This is an issue with how Franz validates the URL. I've submitted a patch to fix this in https://github.com/meetfranz/plugins/pull/231

**Comment by graywolf336** [comment]
Since there's nothing we can do inside Rocket.Chat, can this be closed since the pull request above seems fix the issue?

**Comment by oojacoboo** [comment]
Knock knock - pull request, merge, release... please.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:41913 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.88)
	(envelope-from <noreply@github.com>)
	id 1cy1Qa-000Ed7-5P
	for greg@biomassiv.es; Tue, 11 Apr 2017 14:26:12 -0500
Date: Tue, 11 Apr 2017 12:25:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1491938733;
	bh=art0oKfUYOsDTd5QP1jURrnS/tLFxqHcFa9MXxBF0Jg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nfwrkU1ZwkVb70ysdZLcfVZz9YeCaHE6NsS0v7nwnosBTnkTgm6jud5ws2O+LgKY4
	 0SUUkVaDA7tKi2tU61yseNSp5W2b55wzF20Nuqhs5S1cNEiadY3INQbKkxCSJUma3T
	 tthSpFu8MlxpMl3wTIMU+FNBMmkj2l9RNaGup/+s=

**Comment by jourdanrodrigues** [comment]
+1

**Comment by GCHPX** [comment]
+1

**Comment by dnl-blkv** [comment]
+1

**Comment by Henry31** [comment]
+1

**Comment by Bak3y** [comment]
Still having this issue.

**Comment by vadikace** [comment]
+1

**Comment by jsfoon** [comment]
+1

**Comment by schuch** [comment]
running meetfranz 5 with rocket.chat 0.58.1 successfully. but look for the new franz pricing: a paid plan is required for self hosted services.

**Comment by danpospisil** [comment]
@schuch - yeah, I moved from Franz to Rambox. I would maybe consider paying but not after this over 6 months of ignore...

**Comment by ptillemans** [comment]
Any news on this issue? I can't join the serinity-bdd chat channel with Franz.

**Comment by Bak3y** [comment]
Gave up on Franz due to the lack of response on this.  Thanks to @danpospisil I'm happily using Rambox.

**Comment by GCHPX** [comment]
same here, we are using Rambox now. Thanks @danpospisil . Besides that we would have had to pay for using Franz and RC.

**Comment by BeneStem** [comment]
Hey fellas, this is not a Rocket.Chat issue....

I opened up a issue at Franz and was able to find a workaround.

Will do a PR in the next few days...

https://github.com/meetfranz/franz/issues/325

Greetings,
ben

**Comment by mitsumiki** [comment]
Also waiting for Franz to be updated so we can start to use Rocket chat!

**Comment by TwizzyDizzy** [comment]
So Franz seems to now require an account on their site, if I'm seeing this correctly. Also they have some betas of their new clients... could somebody test this?

Cheers
Thomas

**Comment by BeneStem** [comment]
> So Franz seems to now require an account on their site, if I'm seeing this correctly. Also they have some betas of their new clients... could somebody test this?

It does work with the beta. My fix on their side also made custom Rocket.Chat clients possible.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

That's good to hear. So it seems that I can, effictively, close this issue.

Cheers
Thomas
