### ISSUE TITLE
Windows Server 2012 R2 instructions failing

### ISSUE THREAD

**Issue by catmanjan** [RocketChat/Rocket.Chat#6116]
Rocket.Chat Version: 0.34.0
Running Instances: 0?
DB Replicaset OpLog: ?
Node Version: 4.5 x86

Tried following them verbatim and I get the following, even when running the SDK console as admin

C:\RocketChat\programs\server>npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
\
> fibers@1.0.5 install C:\RocketChat\programs\server\node_modules\fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio
instead.

C:\RocketChat\programs\server\node_modules\fibers>if not defined npm_config_node
_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" reb
uild --release )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\RocketChat\pro
grams\server\node_modules\fibers\undefined'
gyp ERR! stack     at Error (native)
gyp ERR! stack     at Object.fs.openSync (fs.js:549:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:397:15)
gyp ERR! stack     at readCAFile (C:\Program Files (x86)\nodejs\node_modules\npm
\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (C:\Program Files (x86)\nodejs\node_modules\npm\n
ode_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild" "--release"
gyp ERR! cwd C:\RocketChat\programs\server\node_modules\fibers
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\RocketChat\programs\server\npm-debug.log

C:\RocketChat\programs\server>

**Comment by catmanjan** [comment]
I read in #2292 that a user got it to work by deleting npm-shrinkwrap, this doesnt result in an error, but as far as I can see the install doesnt actually complete and there is no rocket.service.js to run

**Comment by catmanjan** [comment]
Also #5069 doesnt seem to work either:

C:\RocketChat\programs\server>npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.

C:\RocketChat\programs\server>

**Comment by geekgonecrazy** [comment]
Windows server isn't officially supported

Going to go ahead and close this.  

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support.  Also take a look at community guides.
