### ISSUE TITLE
Edit email notification for direct message

### ISSUE THREAD

**Issue by droup** [RocketChat/Rocket.Chat#6118]
Rocket.Chat Version: latest

Hi everyone, 
how can I edit the email when I've got private message. 
"[Site_name] You have been direct messaged by " and change the button "Go to message" ?
Thank you

**Comment by ggazzo** [comment]
Sorry about the delay =/

You can change `Offline_Mention_All_Email` template... but I'm afraid you cant make a distinction between public and private channels =/... if you really need that, please open an issue asking for a special field to private and public rooms


[]s 

Administration > Email > Subject > Mention All Email Subject

```javascript
export function sendEmail({ message, user, subscription, room, emailAddress, hasMentionToUser }) {
	const username = settings.get('UI_Use_Real_Name') ? message.u.name : message.u.username;
	let subjectKey = 'Offline_Mention_All_Email';

	if (room.t === 'd') {
		subjectKey = 'Offline_DM_Email';
	} else if (hasMentionToUser) {
		subjectKey = 'Offline_Mention_Email';
	}
