### ISSUE TITLE
Migrate from Rocketchat 0.42 to latest snap without data loss

### ISSUE THREAD

**Issue by mm-jatkins** [RocketChat/Rocket.Chat#6119]
Hi guys, 

Firstly, thanks for an awesome server, it's great! :)

I've just tried to move to the latest version and this appears to all work via snaps now, which is great in terms of managing upgrades etc. but it's not clear how to either 

a) move old mongodb db (rocketchat) to the new snaps db
b) point the rocketchat snap server at the old mongo db with all my users stored in it. 

Am I missing something obvious?! 
Many thanks in advance

Jay
 
Rocket.Chat Version: previously 0.42, currently latest snap version
Running Instances: 1
Node Version: 0.45

**Comment by mm-jatkins** [comment]
Ignore me, I worked it out ;)

Dumped my old rocketchat DB and did a drop and restore to the new parties DB. 
Everything seems to be up and running now. 

Thanks

Jay

**Comment by alexweissman** [comment]
@mm-jatkins any interest in contributing the steps for this, to the official docs?

**Comment by thakilla** [comment]
+1

**Comment by azrul** [comment]
Would be great if someone can write the steps down.

**Comment by thakilla** [comment]
Old Setup:
- Manual setup of rocketchat on debian 8
- Manual setup of mongodb on debian 8

New Setup
- Ubuntu 14.04
- rocketchat with snap

That worked for me:
- stop rocketchat
- "mongodump --out rocketdump"
- stop mongodb
- copy "rocketdump" folder to new server

Switching to new ubuntu server
- "snap install rocketchat-server"
- "sudo service snap.rocketchat-server.rocketchat-server stop"
- "sudo /snap/rocketchat-server/current/bin/mongorestore --drop --db parties /home/user/rocketdump/rocketchat
- "sudo service snap.rocketchat-server.rocketchat-server start"

done
