### ISSUE TITLE
Customize favicon

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#612]

**Comment by Morgul** [comment]
:+1:

**Comment by shtefcs** [comment]
Exactly what I was looking for.

**Comment by LeCoupa** [comment]
:+1:

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/12566729/43e00e4e-c3a2-11e5-9307-4f339cad599c.png)
