### ISSUE TITLE
Rocket chat missing i18n file

### ISSUE THREAD

**Issue by CorentinDy** [RocketChat/Rocket.Chat#6120]
Rocket.Chat Version: 2.4.0
Running Instances: 1
DB Replicaset OpLog:
Node Version:

![clipboard](https://cloud.githubusercontent.com/assets/6079068/23168292/ffa8cd0c-f847-11e6-893c-9117825ba90f.png)
![image](https://cloud.githubusercontent.com/assets/6079068/23168439/6f41ee78-f848-11e6-9674-9d1cbc30b488.png)

Hi, 
since fresh install of rocket chat, i'm not able to see all text translated in my language like on the demo rocket chat server.

Is this error linked to my problem ? 
If so , what can i do to fix it 

Thx

**Comment by Kingbalou** [comment]
Still nothing ?

**Comment by Kingbalou** [comment]
Soooooo it's been 3 month from now ...

**Comment by TheReal1604** [comment]
@Kingbalou Which server version are you using? 2.4.0 seems not correct. (maybe electron version?)

The requested file seems to be wrong. The i18n file for FR is named like:

fr.i18n.json (https://github.com/RocketChat/Rocket.Chat/blob/ebf8dd9e8d64b1d879615c1035745fa65f8b23cf/packages/rocketchat-i18n/i18n/fr.i18n.json)

**Comment by geekgonecrazy** [comment]
That file doesn't exist.  Must be custom code base?  Going to go ahead and close.  

Old issue and nothing actionable for the team.

**Comment by CorentinDy** [comment]
Don't worry we have already moved on Discord, little late to answer ;)
