### ISSUE TITLE
Replying to an email from rocket.chat and have it posts message to the channel

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#6129]
Rocket.Chat Version: 0.52

Hello, 
A frequent request at my company is a feature to post a message to a rocket.chat channel directly from an email reply. Similar to how basecamp or google docs work. I was wondering if something like this is in the near term roadmap?

**Comment by rasos** [comment]
It has been suggested as a Summer of Code project: https://rocket.chat/docs/contributing/google-summer-of-code . Would like to see that earlier :-)

**Comment by msears** [comment]
+1 
but I don't think any of the Summer of Code projects cover this (Integrated Personal Email Gateway is close but different from my reading)
I understand driving back into chat is ideal but not always feasible and the option to respond by email OR jump into rchat seems obvious and definitely ideal from our side.
May need to open up a bounty...

**Comment by akachapati** [comment]
Is there an update on this?

**Comment by hughlroberts** [comment]
+1

**Comment by pkgodara** [comment]
This feature is planned under GSoC project (Integrated Personal Email Gateway) https://summerofcode.withgoogle.com/projects/#6045777290854400 .

Suggestions on further features/improvements are welcome.
