### ISSUE TITLE
Customize loading icon

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#613]
Currently it is rocket.

**Comment by propertunist** [comment]
anyone know how to do this manually in the current version of rocket.chat? i saw the other ticket that mentions: <template name="loading">
but that is not found when i search the rocket.chat source code.
i found the icon files at: /home/ura/apps/rocketchat/Rocket.Chat/programs/server/assets/app/images/
but i'm not sure if they are the right files, plus they would get over-written if i upgrade the software.
