### ISSUE TITLE
No way how delete custom sounds

### ISSUE THREAD

**Issue by Rohlik** [RocketChat/Rocket.Chat#6130]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: True
Node Version: 4.7.2

Hi,
please add option to delete custom sounds via RC admin page.
Thx.

**Comment by localguru** [comment]
Yes, please! Any way to delete a custom sound via mongodb?

**Comment by Rohlik** [comment]
In version 0.60.0 is option to delete custom sounds, finally.
