### ISSUE TITLE
cant start Version 0.52.0 Developer

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6133]
Rocket.Chat Version: 0.52.0
Running Instances: 
DB Replicaset OpLog:
Node Version:4.8.0
trying to start developer version but no luck
 LOG.......
METEOR@1.4.2.6
Node Version:4.8.0
=> Started proxy.
=> Started MongoDB.
I20170222-08:05:33.911(-5)? Will load cache for users
I20170222-08:05:37.035(-5)? 0 records load from users
I20170222-08:05:37.058(-5)? Will load cache for rocketchat_room
I20170222-08:05:37.062(-5)? 0 records load from rocketchat_room
I20170222-08:05:37.079(-5)? Will load cache for rocketchat_subscription
I20170222-08:05:37.091(-5)? 0 records load from rocketchat_subscription
I20170222-08:05:37.094(-5)? Will load cache for rocketchat_settings
I20170222-08:05:37.098(-5)? 178 records load from rocketchat_settings
I20170222-08:05:37.101(-5)? Exception in callback of async function: Error: Cannot find module './lib/mime-type'
I20170222-08:05:37.145(-5)?     at require (packages/modules-runtime.js:114:19)
I20170222-08:05:37.149(-5)?     at meteorInstall.node_modules.file-type.index.js.module.mime-type.with-db.js (packages/modules.js:8658:16)
I20170222-08:05:37.188(-5)?     at fileEvaluate (packages/modules-runtime.js:188:9)
I20170222-08:05:37.191(-5)?     at Module.require (packages/modules-runtime.js:111:16)
I20170222-08:05:37.225(-5)?     at Module.Mp.import (/home/rc/.meteor/packages/modules/.0.7.7.catt8l++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
I20170222-08:05:37.246(-5)?     at meteorInstall.node_modules.meteor.rocketchat:assets.server.assets.js (/home/rc/rc52/.meteor/local/build/programs/server/packages/rocketchat_assets.js:35:321)
I20170222-08:05:37.253(-5)?     at fileEvaluate (packages/modules-runtime.js:188:9)
I20170222-08:05:37.260(-5)?     at require (packages/modules-runtime.js:111:16)
I20170222-08:05:37.262(-5)?     at /home/rc/rc52/.meteor/local/build/programs/server/packages/rocketchat_assets.js:724:1
I20170222-08:05:37.280(-5)?     at /home/rc/rc52/.meteor/local/build/programs/server/packages/rocketchat_assets.js:730:3
I20170222-08:05:37.285(-5)?     at /home/rc/rc52/.meteor/local/build/programs/server/boot.js:295:34
I20170222-08:05:37.300(-5)?     at Array.forEach (native)
I20170222-08:05:37.301(-5)?     at Function._.each._.forEach (/home/rc/.meteor/packages/meteor-tool/.1.4.2_6.v60ywf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
I20170222-08:05:37.338(-5)?     at /home/rc/rc52/.meteor/local/build/programs/server/boot.js:128:5
I20170222-08:05:37.341(-5)?     at /home/rc/rc52/.meteor/local/build/programs/server/boot.js:344:5
I20170222-08:05:37.344(-5)?     at Function.run (/home/rc/rc52/.meteor/local/build/programs/server/profile.js:480:12)
I20170222-08:05:37.357(-5)?     at /home/rc/rc52/.meteor/local/build/programs/server/boot.js:343:11
I20170222-08:05:37.360(-5)? Updating process.env.MAIL_URL

**Comment by whuber-work** [comment]
I had to manually call 
``meteor npm install --save mime-type
``meteor npm install --save mime-db
but I get also this error:
``Error: Already registered the facebook OAuth `service

**Comment by whuber-work** [comment]
perhaps it's the same as in  #5425:
does
`` meteor npm i --production``
help?

**Comment by Nemra1** [comment]
i think this pkg is missing Exception in callback of async function: Error: Cannot find module './lib/mime-type'
but how ?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
