### ISSUE TITLE
Custom translations not effective

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6135]
According to the example given, we tried to alternate the translation for Channels to Rooms in German language. However, the side bar is still showing "Kanäle". Logout / Restart does not help either.

Is the syntax correct? Anybody using custom translations successfully?
```
{
	"en": {
		"key": "Channels"
	},
	"de": {
		"key": "Räume"
	}
}
```

Rocket.Chat Version: 0.52
Running Instances: 1

**Comment by billtt** [comment]
```
{
	"en": {
		"Channels": "Channels"
	},
	"de": {
		"Channels": "Räume"
	}
}
```

You should use the key for "Channels", which is "Channels"

**Comment by rasos** [comment]
Thanks, this did the trick, and sounds so logical ;-/  
Still I suggest to replace the example with:
 
```
{
	"en": {
		"Channels": "Rooms"
	},
	"de": {
		"Channels": "Räume"
	}
} 
```

**Comment by rasos** [comment]
It seems to us that custom translation is not working. We have: 

`{
	"en": {
		"Channels": "Rooms"
	},
	"de": {
		"Channels": "Räume"
        "Create a New Channel": "Neuen Raum einrichten"
        "Invalid channel.": "Ungültiger Raum."
        "Join the given channel": "Diesem Raum beitreten"
        "Opens a channel, group or direct message":"Öffnet einen offenen oder geschlossenen Raum" 
        "Has joined the channel.":"Ist dem Raum beigetreten."
        "Has left the channel.":"Hat den Raum verlassen."
        "Invalid channel. Start with @ or #":"Ungültiger Raum. Muss mit @ oder # beginnen."
        "Invite one user to join this channel":"BenutzerIn in diesen Raum einladen" 
        "Post to Channel":"In diesen Raum posten"
	}
}`

and we still see "Kanäle" (see screenshot). Tested with RC 0.56.   
![customtranslation](https://cloud.githubusercontent.com/assets/485723/26397421/90913b94-4076-11e7-948c-f8e05aa029d4.png)

@MartinSchoeler - could you re-open this issue?

**Comment by billtt** [comment]
@rasos The configuration is incorrect. Each key / value pair should be separated by a comma. Like:
{
	"de": {
		"Channels": "Räume",
		"Create a New Channel": "Neuen Raum einrichten",
		"Invalid channel.": "Ungültiger Raum."
	}
}

You can check your grammar online: https://jsonlint.com/

**Comment by rasos** [comment]
Ah, thanks, sure it should be valid JSON :~]   

The new help text does not render the html tags correctly on 0.56:
![translationscreen](https://user-images.githubusercontent.com/485723/26970425-a7aa4416-4d09-11e7-8285-5734f896833e.png)

**Comment by billtt** [comment]
Sorry I didn't pay attention to the content. You need to use the **keys**, not the English version of **texts**.
For example, instead of
`"Create a New Channel": "Neuen Raum einrichten"`
You should write
`"Create_A_New_Channel": "Neuen Raum einrichten"`

Keys can be found in the `en.i18n.json` file. They are not simply made from English texts by connecting words with underlines.

**Comment by rasos** [comment]
Just for documentation (and to improve the help text):    
Usage: "key":"translation", whereas you find the keys here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/en.i18n.json

{
	"en": {
		"Channels": "Rooms"
	},
	"de": {
		"Channels": "Räume",
        "Create_A_New_Channel": "Neuen Raum einrichten",
        "error_invalid_channel.": "Ungültiger Raum.",
        "Join_the_given_channel": "Diesem Raum beitreten",
        "Opens_a_channel_group_or_direct_message":"Öffnet einen offenen oder geschlossenen Raum",
        "User_joined_channel":"Ist dem Raum beigetreten.",
        "User_left":"Hat den Raum verlassen.",
        "error_invalid_channel. Start with @ or #":"Ungültiger Raum. Muss mit @ oder # beginnen.",
        "Invite_user_to_join_channel":"BenutzerIn in diesen Raum einladen", 
        "Post_to_Channel":"In diesen Raum posten"
	}
}

**Comment by larsziegelmann** [comment]
Some German translations were missing in our Rocket Chat, so we decided to add it manually. I managed to find some of the keys in the list above, but it still didn't apply the changes I've made. We tried to restart but it didn't help.

Is this syntax correct?

```
{
"de":  {
"Started_a_video_call": "Eine Videokonferenz gestartet",
"Keyboard_Shortcuts_Title": "Tastenkombinationen",
"Edit_Status": "Status bearbeiten",
"Timezone": "Zeitzone",
"Role": "Rollen",
"Video_Conference": "Videokonferenz starten",
"Join_video_call": "An der Konferenz teilnehmen",
"Call_Already_Ended": "Die Konferenz wurde bereits beendet",
}
}

```

**Comment by rasos** [comment]
Correct JSON lists have no comma after the last item, so delete the last one.

**Comment by mattelacchiato** [comment]
This problem still exists in latest version `6.2.5`!

Given this JSON:
```json

{
  "de": {
    "registration.component.form.confirmPassword": "Passwort bestätigen",
    "Confirm_password": "Passwort bestätigen"
  }
}
```
But when I go to the registration page, it is still shown as "Confirm Password" instead of the German translation...
