### ISSUE TITLE
window meteor 1.4.2.7 Rocket.Chat-0.52.0 develop  start fail

### ISSUE THREAD

**Issue by zhangshiwan** [RocketChat/Rocket.Chat#6136]
Rocket.Chat Version:  Rocket.Chat-0.52.0
Running Instances:  1
DB Replicaset OpLog:
Node Version:

f:\git\Rocket.Chat-0.52.0>meteor
[[[[[ ~\f\git\Rocket.Chat-0.52.0 ]]]]]

=> Started proxy.
=> Started MongoDB.

Changes to your project's package version selections:

rocketchat:cas  added, version 1.0.0

W20170222-23:32:19.644(8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20170222-23:32:21.192(8)? (STDERR) While this implementation will work correctly, it is known to be
W20170222-23:32:21.194(8)? (STDERR) approximately three times slower than the native implementation.
W20170222-23:32:21.195(8)? (STDERR) In order to use the native implementation instead, run
W20170222-23:32:21.197(8)? (STDERR)
W20170222-23:32:21.199(8)? (STDERR)   meteor npm install --save bcrypt
W20170222-23:32:21.200(8)? (STDERR)
W20170222-23:32:21.202(8)? (STDERR) in the root directory of your application.
I20170222-23:32:21.358(8)? Will load cache for users
I20170222-23:32:21.546(8)? 0 records load from users
I20170222-23:32:21.633(8)? Will load cache for rocketchat_room
I20170222-23:32:21.734(8)? 0 records load from rocketchat_room
I20170222-23:32:21.765(8)? Will load cache for rocketchat_subscription
I20170222-23:32:21.767(8)? 0 records load from rocketchat_subscription
I20170222-23:32:21.768(8)? Will load cache for rocketchat_settings
I20170222-23:32:21.770(8)? 178 records load from rocketchat_settings
I20170222-23:32:21.772(8)? Exception in callback of async function: Error: Can't find npm module 'mime-type/with-db'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
I20170222-23:32:21.774(8)?     at Object.require (f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\boot.js:200:17)
I20170222-23:32:21.776(8)?     at options.fallback (packages\modules-runtime.js:479:18)
I20170222-23:32:21.777(8)?     at Module.require (packages\modules-runtime.js:126:16)
I20170222-23:32:21.780(8)?     at Module.Mp.import (C:\Users\zhangsw\AppData\Local\.meteor\packages\modules\0.7.9\npm\node_modules\reify\lib\runtime.js:75:16)
I20170222-23:32:21.782(8)?     at meteorInstall.node_modules.meteor.rocketchat:assets.server.assets.js (packages/rocketchat:assets/server/assets.js:1:85)
I20170222-23:32:21.784(8)?     at fileEvaluate (packages\modules-runtime.js:197:9)
I20170222-23:32:21.786(8)?     at require (packages\modules-runtime.js:120:16)
I20170222-23:32:21.787(8)?     at f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\packages\rocketchat_assets.js:704:1
I20170222-23:32:21.790(8)?     at f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\packages\rocketchat_assets.js:710:3
I20170222-23:32:21.794(8)?     at f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\boot.js:295:34
I20170222-23:32:21.798(8)?     at Array.forEach (native)
I20170222-23:32:21.801(8)?     at Function._.each._.forEach (C:\Users\zhangsw\AppData\Local\.meteor\packages\meteor-tool\1.4.2_7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
I20170222-23:32:21.803(8)?     at f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\boot.js:128:5
I20170222-23:32:21.804(8)?     at f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\boot.js:344:5
I20170222-23:32:21.806(8)?     at Function.run (f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\profile.js:480:12)
I20170222-23:32:21.809(8)?     at f:\git\Rocket.Chat-0.52.0\.meteor\local\build\programs\server\boot.js:343:11
I20170222-23:32:21.812(8)? Updating process.env.MAIL_URL

**Comment by Nemra1** [comment]
same thing in centos 6.8

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
