### ISSUE TITLE
Proposal: setting to set compression quality for images and videos on upload

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#6137]
On iOS native app, we're currently compressing all images and videos in medium quality (1024x1024), but I think that would be interesting to have this as an option in the server. For example, if the users want to send files to each other in original quality (high resolution photographs or movies), we should not compress it.

My proposal is to have a few options:

**Compress_Quality_Video**
- Low (640px)
- Medium (1024px)
- High (1080p)
- Original

**Compress_Quality_Image**
- Low (640px)
- Medium (1024px)
- High (1080p)
- Original

What do you guys think?

**Comment by SeanPackham** [comment]
This would be a useful enhancement, to simplify the backlog I am closing it for now and we can revisit it once the bug backlog has been reduced.

**Comment by tekook** [comment]
Any news on this one?
