### ISSUE TITLE
Income Hook say {"success":false,"error":"error-code-invalid"}

### ISSUE THREAD

**Issue by KehaoWu** [RocketChat/Rocket.Chat#6139]
```
curl -X POST --data-urlencode 'payload={"username":"GitLab","icon_emoji":":ghost:","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' https://mydomain/hooks/PE3w7cPGs3EDBxo3L/G2JNJDPoabKf7qvkzRbGhJcXgt4pDZAHNQGccMZWnQkojJ5
```

**Comment by biomassives** [comment]
Kehao -

You need to change the last part of the curl statement

The domain, localhost or IP address should work!

'mydomain

**Comment by KehaoWu** [comment]
I know. I edit my domain name before I paste the code here. Thus, I don't think that's the answer.

**Comment by graywolf336** [comment]
Did you enable the Incoming Webhook?

**Comment by KehaoWu** [comment]
Yes, I enable the imcoming Webhook on such page /admin/integrations/incoming/PE3w7cPGs3EDBxo3L

**Comment by graywolf336** [comment]
The `error-code-invalid` comes from when someone is trying to join a room and the room requires a join code to join.

@RocketChat/core thoughts on allowing users with the `bot` role to join channels ignoring the `joinCode` requirement?

**Comment by graywolf336** [comment]
@RocketChat/core would like your opinions on the above, otherwise I will just submit a pull request with changes to allow it.

**Comment by sampaiodiego** [comment]
bots are becoming more powerful as admins.

my only concern is that all this _power_ is not clearly warned, so bot users can be not "secure" as they need to be.

otherwise I'm good with it.

**Comment by graywolf336** [comment]
@sampaiodiego How would you recommend overcoming that and fixing that?

**Comment by graywolf336** [comment]
After some discussion, it has been decided to add a permission to do what I suggested above. New permission would be something like `join-without-join-code` and every time the "bot" user needs to do something special we add a new permission instead of hard coding the role of bot.
