### ISSUE TITLE
How to remove social media links in the chat sidebar?

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#614]
In the chat sidebar there are social media links to Rockat.Chat sites? How could those be removed/replaced with another content? The issue is that our users could be confused because we are trying to integrate the chat tightly with the rest of our project experience.

**Comment by rockneverdies55** [comment]
+1

**Comment by marceloschmidt** [comment]
We decided to remove it altogether. No reason for keeping social links on channel sidebar.
