### ISSUE TITLE
Cannot open attached file if filename contains "%"

### ISSUE THREAD

**Issue by yukidaruma** [RocketChat/Rocket.Chat#6141]
Rocket.Chat Version: 0.52.0
Running Instances: 1
Node Version: v4.7.3

![image](https://cloud.githubusercontent.com/assets/6897821/23254602/edb0728e-f9fb-11e6-80a9-457df21adbe1.png)

**Comment by MrBunBuns** [comment]
Hello me and my group are working on Rocket.Chat for our Intro to Software Engineering project. We are interested in being assigned this bug so that we can fix it. Let us know if you would like us to!
