### ISSUE TITLE
Create DEB/RPM Packages

### ISSUE THREAD

**Issue by scoopex** [RocketChat/Rocket.Chat#6145]
Installing software by deb/rpm on linux systems is the regular way for installing software on linux systems.

The rocketchat documentation provides various ways to install it on linux systems (snap, docker, from tarball, ...). I think it would be a good thing to increase the acceptance of rocket chat by many linux system administrators by providing regular operating system packages in a apt/rpm respository.
This will also help to automate the installation by configuration management systems like puppet and chef.

Probably FPM would be a good solution to create packages.

See also:
- https://github.com/jordansissel/fpm
- https://www.digitalocean.com/community/tutorials/how-to-use-fpm-to-easily-create-packages-in-multiple-formats
- https://github.com/carroarmato0/puppet-rocketchat

**Comment by graywolf336** [comment]
We'd love to see a pull request for this. :+1: Only issue is the license issues for NPM Packages.

**Comment by scoopex** [comment]
What is the problem with "license issues for NPM Packages"?

**Comment by graywolf336** [comment]
@scoopex some of the NPM packages we use might not have MIT license and their license might prevent packaging that up which is one of the reasons why we have that "automated" on the installers which are automated. That make sense?

**Comment by scoopex** [comment]
Whats the difference with the already available Ubuntu SNAP Packages?

**Comment by dlasalle** [comment]
We're in the early stages of launching a service that integrates with github for building linux packages you might want to use for this (https://bytepackager.com/). Right now it builds Arch, CentOS, Fedora, and Ubuntu packages.

**Comment by scoopex** [comment]
Great to read this, where can i download test packages?

**Comment by dlasalle** [comment]
The packages for this project have been built with it: https://github.com/dlasalle/wildriver/releases/tag/v1.0.0

Or do you mean something else by test packages?

**Comment by scoopex** [comment]
Where i can find the created packages?

**Comment by sampaiodiego** [comment]
we'll not have officially support to system specific packages, as we have snap package for now.

but we accept and can promote community maintained packages though.
