### ISSUE TITLE
False-Positive Malware Detect (HEUR/QVM20.1.0000.Malware.Gen)? :o

### ISSUE THREAD

**Issue by ecrazor1911** [RocketChat/Rocket.Chat#6148]
More details: https://www.virustotal.com/hu/file/32b82c872fda564c6a9cc005e9a825896c662ea90d1680f917adc45d515d5c2d/analysis/

| Antivirus       | Result                                                     | Update      |
| -------------- | ------------------------------------------ | ----------- |
| Qihoo-360	| HEUR/QVM20.1.0000.Malware.Gen	| 20170223 |
| Rising|	Malware.Heuristic!ET (cloud:SlGVBQc87DS)	| 20170223 |

| | |
| -------------- | ------------------------------------------ |
| SHA256: | 32b82c872fda564c6a9cc005e9a825896c662ea90d1680f917adc45d515d5c2d |
| File name: | rocketchat-Setup-2.4.0.exe |
| Detection ratio: | 2 / 58 |
| Analysis date: | 2017-02-23 10:08:07 UTC ( 9 hours ago ) |

I voted to harmless.

**Comment by graywolf336** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron you can view the source code there and the build scripts, there should be no malware being generated so yes it should be a false positive.
