### ISSUE TITLE
Admins should be able to delete (and/or) edit other users' mesages

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#615]
From our experience it happens that users share their passwords and other sensitive information on the chat. It would be great if admins could delete those even if users do not themselves.

**Comment by geekgonecrazy** [comment]
My 2c should make sure to say "edited by so-and-so" prevent abuse of power.  :)

**Comment by marceloschmidt** [comment]
This is possible now that PR #818 has been merged. Let's add a new issue for the "edited by {{username}}"

**Comment by mitar** [comment]
Link to the issue?

**Comment by marceloschmidt** [comment]
Issue created: #824
