### ISSUE TITLE
Administratively Create/Maintain Direct Messages for users?

### ISSUE THREAD

**Issue by jdashn** [RocketChat/Rocket.Chat#6150]
I would like to be able to set-up a Direct Message list for my users when they first login (or at login) so they will always (at least) have their 'team-members' shown under Direct Messages (so the users don't have to search for and add them themselves).

I can see there may be a way to show a hidden direct message 'room' via the API - but i'm unsure if it would allow me to 'create' these rooms, or to do so for a user that isn't me.

Is this something that is currently possible? 

Thanks!

Jdashn

**Comment by SeanPackham** [comment]
Closing as this feature is not a feature we intend to support. Something similar can be achieved with default channels or creating a bot to start conversations.
