### ISSUE TITLE
OTR leaks images

### ISSUE THREAD

**Issue by timothyparez** [RocketChat/Rocket.Chat#6151]
When posting an image in OTR it's displayed as some text link.
When closing the OTR conversation and refreshing the page, the messages
are gone but the image that was pasted during the session is now visible.

Rocket.Chat Version:  0.51.0-develop
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.6.2

**Comment by mddvul22** [comment]
Maybe I should open a bug request on this.  I don't know if this is related, or not.  We are running 0.53.  When we upload an image over an OTR session, nothing is shown to the other user, not even a text link.  In fact, the person doing the uploading doesn't see the uploaded image, either.  And then, to complicate things, if the person opens another RC client (perhaps in a different browser, or on a different device) they DO see the image in that session and it isn't OTR encrypted, at all.

**Comment by localguru** [comment]
@timothyparez I can confirm this on RC 0.52.0.
@mddvul22 I can confirm this too!

 Is it fixed in newer versions? To my mind this is an [#security](url) bug as uploads do bypass OTR.

**Comment by localguru** [comment]
Anything going on on this serious bug, which makes OTR completely useless.

**Comment by mrinaldhar** [comment]
Hi, thanks for raising this issue!

#7181 is a new implementation of end to end encryption in rocket chat, and it handles direct messaging, private group messaging, as well as file uploads. Files are encrypted on the clients before they're sent.

We're in the process of improving that implementation, and it should be ready soon!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #7507 

Cheers
Thomas
