### ISSUE TITLE
Messages not being synced

### ISSUE THREAD

**Issue by rojesh** [RocketChat/Rocket.Chat#6154]
Rocket.Chat Version: 0.48.2
Running Instances: 2
DB Replicaset OpLog: true [Our replicaset currently is only with 1 server i.e master]
Node Version: 4.6.2

The messages sent in the channel are not being synced properly across all users. The message gets populated in the channel for some user while not seen in other users. But when the session and cookies are cleared in the browser, the problem no longer persists.

**Comment by TheReal1604** [comment]
@rojesh https://github.com/RocketChat/Rocket.Chat.Docs/issues/87

**Comment by rojesh** [comment]
Sadly, we haven't used docker containers to host our app instances. @TheReal1604

**Comment by TheReal1604** [comment]
@rojesh That's no problem, so you have to set the same env variables .. not in docker, but on your webhosts. And take attention that each instance can connect to each other.

**Comment by Hudell** [comment]
I'll close this one due to inactivity. If necessary it can be opened again.
