### ISSUE TITLE
Jumping between channels should show unread channels

### ISSUE THREAD

**Issue by trepidity** [RocketChat/Rocket.Chat#6156]
When using the `cmd + p` or `ctrl + p` to jump to channels, it will not show channels/direct messages that contain unread messages.

This kinda relates to issue #4256

As long as the channels with unread were listed first, and maybe with a different color. I do see that the unread count is listed next to the channel name, but it's very obscure.

![image](https://cloud.githubusercontent.com/assets/737629/23308172/d9842d36-fa6f-11e6-9aee-58d6da3988cd.png)

**Comment by MartinSchoeler** [comment]
Could you please test this out with the latest version? Channel searching has changed a lot since this issue was created. Thanks!
