### ISSUE TITLE
Direct-message API

### ISSUE THREAD

**Issue by xsoft** [RocketChat/Rocket.Chat#6157]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: 88
Node Version: v4.7.3

Hello,
I'm creating simple PHP notification APP which sends DIRECT MESSAGE to user. Question is how to do so (PHP)? Sending to room is fine, but direct message is something else.

I found
https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage
and https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message/
but all require roomId (channel is @uesr right)?

I need to create a room (for direct message) and then send message to this room?

Older tip was:
https://github.com/RocketChat/Rocket.Chat/issues/2705

```
Use @user instead #chanel
curl -X POST --data-urlencode "payload={\"channel\": \"@admin\", \"username\": \"Asterisk*\", \"text\": \"test\", \"icon_emoji\": \":asterisk:\"}" $webhooklink
```

**Comment by graywolf336** [comment]
You can use the `chat.sendMessage` with the channel being a username like the webhook example.

**Comment by xsoft** [comment]
Do you have some example or link to documentation?
I can't find any. I don't know the URL to send this to (none at REST API section)

**Comment by graywolf336** [comment]
`<serverAddress>/api/v1/chat.postMessage`

**Comment by xsoft** [comment]
```
{
  "status": "error",
  "message": "API endpoint does not exist"
}
```
I can't use this endpoint at 0.52 (/api/v1/chat.postMessage)

```
*Server info*
object(stdClass)[1]
  public 'version' => string '0.52.0' (length=6)
  public 'success' => boolean true
```

**Comment by graywolf336** [comment]
What HTTP Verb are you using?

**Comment by xsoft** [comment]
php and/or curl to call
json encoding

**Comment by graywolf336** [comment]
Yes, but what http verb are you using? GET, POST, PUT, DELETE, etc

**Comment by ibrahimdoqa** [comment]
I tried the postMessage request to send a direct message. i replaced the value of the channel with the username of the receiving user. and i got this error. 

{
    "success": false,
    "error": "[invalid-channel]",
    "errorType": "invalid-channel"
}

can you help me with that? @graywolf336

**Comment by graywolf336** [comment]
@ibrahimdoqa I actually ran into this issue as well. Please open a new issue, it seems we broke support for `channel` property on the object being sent.
