### ISSUE TITLE
Multiline code block has extra two lines

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#616]
If you hover over the multiline code block and you vertically scroll, you will see that it has extra two lines.

![wlan_slovenija_chat_-_2015-08-28_10 29 03](https://cloud.githubusercontent.com/assets/585279/9552812/b01c1c78-4d6f-11e5-9932-b21a676e2e70.png)

![wlan_slovenija_chat_-_2015-08-28_10 29 33](https://cloud.githubusercontent.com/assets/585279/9552814/b42ecef0-4d6f-11e5-9b8c-b983099dd007.png)

**Comment by graywolf336** [comment]
I tried to replicate this but couldn't. Mind giving the exact ones you used so I can replicate it?

**Comment by mitar** [comment]
It seems the issue is only in Firefox. In Chrome it works well.
