### ISSUE TITLE
Cams are "hidden behind" userlist (Chrome)

### ISSUE THREAD

**Issue by sugo23** [RocketChat/Rocket.Chat#6160]
We tested the cam features on rocket.chat cloud and found that there are some bugs:

On my Chrome Browser the cam was kind of hidden behind the user list. The user list was not clickable (or did not do anything when clicked on).

When I changed the window size, a small column on the right appeared, so I could see a small part of the cam window and the button under it. So I could click the button and expand the cam(s). Without that, the only way to make the user list usable again would have been a reload.

**Comment by ggazzo** [comment]
hey, we rewrote this component and I think we dont have this problem anymore...any problem please let me know
