### ISSUE TITLE
Initial setting can't be overwritten by environment variable

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#6161]
Rocket.Chat Version: 0.52

In general, settings can be overridden by environment variables providing an env. variable of name `OVERWRITE_SETTING_<setting_id>`
If a setting however has been created with an empty initial value, this is not possible

**Comment by mrsimpson** [comment]
fixed with 55357f766b8da7773d2b22ae566567f431e65d07

**Comment by sampaiodiego** [comment]
I was enable to reproduce it.

which setting were you not able to overwrite?

**Comment by mrsimpson** [comment]
Sorry for the delay, @sampaiodiego!

I created a custom setting like this:
```
RocketChat.settings.add('Livechat_Knowledge_Redlink_URL', '', {
		type: 'string',
		group: 'Assistify',
		section: 'Knowledge_Base',
		public: true,
		i18nLabel: 'Livechat_Knowledge_Redlink_URL'
	});
```

I am not able to override (set) this externally as in the origin code, as the overriding with a process.Env is only being checked later.
