### ISSUE TITLE
Current password not verified when user modifies profile

### ISSUE THREAD

**Issue by nimetu** [RocketChat/Rocket.Chat#6162]
Meteor.saveUserProfile() never verifies currentPassword.

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/saveUserProfile.js#L19

**Comment by corecache** [comment]
Some profiles - like authenticated through external SSO providers - don't even have a password set. So verifying for currentPassword makes no sense for passwordless logins.

**Comment by ggazzo** [comment]
fixed here #6307  :)
