### ISSUE TITLE
Way to configure the color scheme of the left main sidebar

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#617]
Currently it is blue. But it would be great if it could be configured so that it matches the logo and other "branding" stuff of the whole experience.

**Comment by graywolf336** [comment]
@mitar what else would be nice to be able to change the color of?

**Comment by Sing-Li** [comment]
..

**Comment by mitar** [comment]
Hm, I think in general it would be interesting to be able to define the base color scheme. So currently I see that it is mostly blue, white, and gray. So a way to define those colors would be great.

**Comment by mitar** [comment]
But from what I was looking I would just change the blue color wherever it is used (sidebar, login/registration window, few buttons).

**Comment by AdrianoCahete** [comment]
Why not a way to define templates (colors and modify blocks) by Server Admins?

**Comment by mitar** [comment]
One other idea could be that this is a configuration of host. So that once mobile apps will support multiple projects/hosts linked to the app, each project/host would define their own color scheme, logos, and stuff.

**Comment by engelgabriel** [comment]
![colors](https://cloud.githubusercontent.com/assets/1000217/9717620/96be8f08-554a-11e5-822a-dd285bf2c368.png)

**Comment by Morgul** [comment]
:+1:

**Comment by marceloschmidt** [comment]
Related to #277

**Comment by gmsecrieru** [comment]
Available since #1122

**Comment by kokotko1337** [comment]
I can not find options to change sidebar colour ... Im using latest version, and in Layout or Assets can not find option to change default colour to custom.

**Comment by tassoevan** [comment]
@kokotko1337 `Admin > Layout > Colors > Primary`.

**Comment by kokotko1337** [comment]
@tassoevan oh ... thanks, that description is strange ...  I have just uses custom css... but this way is cleaner
