### ISSUE TITLE
LDAP: User Data Field Map

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6172]
Hi,

the real name of a user is split into sn and givenName in my AD. How do I fill the name field with these two values in LDAP "User Data Field Map" configuration?

This  does not work:
{"#{givenName} #{sn}":"name", "mail":"email"}

whereas 
{"sn":"name", "mail":"email"}
or
{"givenName":"name", "mail":"email"}
does work.

Ciao!
Marcus

**Comment by Flipez** [comment]
As far as I can tell this is currently not supported but should not be too hard to implement.

Maybe something like "fullname" with an Array of LDAP-Keys is possible?

**Comment by rodrigok** [comment]
Closed by #6921
