### ISSUE TITLE
Trying to run locally on windows, get stuck at: Updating process.env.MAIL_URL

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#6177]
Rocket.Chat Version:     0.52.0
Running Instances:    (not able to run)
DB Replicaset OpLog:    (not able to run)
Node Version:    3.10.10

I have seen some people refer to setting the environmental variable for MAIL_URL using 'export' but Windows doesn't recommend that command.  When I deply with MUPX, I set the environmental in the mup.json.  For the moment, I'm just trying to run locally.

Any idea what's happening?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Windows is no supported platforms, you may try in the forums though: https://forums.rocket.chat/c/community-support

Cheers
Thomas
