### ISSUE TITLE
E-Mail message forward throws exception

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6179]
When selecting a message to be forwarded, the subject line contains an "undefined":  
`Hier ist ein ausgewählter Teil aus undefined Nachrichten`

When pressing the Send button, an internal server error is reported to the user. Seems to be related to localisation (ours is "Deutsch" - German, which has a pretty completed translation set).  Here is the log:   

```
Sending messages to e-mails:  [ 'a344r.rer1234@domain.com' ] 
[34mI20170227-13:39:30.578(1) Exception while invoking method 'mailMessages' TypeError: Cannot read property 'defineLocale' of undefined   at eval (<anonymous>:30:20)   at format.m (<anonymous>:12:4)   at eval (<anonymous>:13:2)   at [object Object].mailMessages (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_channel-settings-mail-messages.js:119:29)   at [object Object].methodsMap.(anonymous function) (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:1064:26)   at maybeAuditArgumentChecks (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:2108:12)   at /var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:1040:48   at Session.method (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:1018:23)   at /var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:880:89   
```

Rocket.Chat Version: 0.52
Running Instances: 1

**Comment by rasos** [comment]
Please check when refactoring E-Mail in #6196 . 
Will check for MAIL_URL #3602 .

**Comment by TheReal1604** [comment]
@rasos Got the same issue on my 3 server setup. (but only on a upgraded one)

**Comment by localguru** [comment]
see this on 0.56.0 too

**Comment by localguru** [comment]
If Account locale is set from German to English, sending emails if working. Hmmm ....

**Comment by approximatenumber** [comment]
Same Issue.
Rocket.Chat 0.56.0
`LANG=ru_RU.utf-8`

Changing `Function(moment.localeFn)();` to `Function(moment.localeFn)();` helps. Thanks @localguru

**Comment by localguru** [comment]
My above code doesn't throw an error, but it seems not to be the solution, see #7245

**Comment by sampaiodiego** [comment]
duplicated of #5797

**Comment by localguru** [comment]
Please reopen, #7846 doesn't fix it

**Comment by sampaiodiego** [comment]
thanks @localguru .. tested on `develop` and yes it is still hapenning

**Comment by TheReal1604** [comment]
@sampaiodiego have you some news on this? a really bad bug - which makes this feature unusable for many users. :(
