### ISSUE TITLE
Feature Request: Sort private messages by unread

### ISSUE THREAD

**Issue by jan-spotcap** [RocketChat/Rocket.Chat#6182]
Rocket.Chat Version:  0.52
Running Instances:  ubuntu 16.10

Hi,

it would be nice if direct messages and groups and be automatically sorted by unread messages.
So I don't need to scroll throw 100 conversations until I found my unread one. 

Thanks

**Comment by zorenleo** [comment]
Hey you can do this just go to:
My Account->Unread Rooms Mode->Select true>Save Changes
<img src="https://i.imgsafe.org/4cd222f997.png">

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support category
