### ISSUE TITLE
Can not enter the room

### ISSUE THREAD

**Issue by szluohua** [RocketChat/Rocket.Chat#6183]
After you remove the room, and then create a room of the same name will not enter the room, you need to refresh a few times to enter

**Comment by Dracozny** [comment]
confirmed using demo.rocket.chat site. (unknown if it affects client apps)
steps to reproduce
1. Create room
2. Delete room (room will still show in channel list of joined channels and attempting to leave it will throw up error to assign a new leader
3. Attempt to recreate room which will bring up a preview of the room you had already created and prohibit you from joining you will
4. refresh by going back to demo.rocket.chat root url and the room will no longer persist. attempting to refresh while in the preview will persist the deleted channel.
