### ISSUE TITLE
Notifications count on the application bar icon

### ISSUE THREAD

**Issue by bugy** [RocketChat/Rocket.Chat#6185]
Rocket.Chat Version: 2.3.0
OS: Debian 8 + Gnome 3

Is there any way to display on the icon in application bar how many notifications (or channels with notifications) I have? Currently only exclamation mark is shown there, when there is anything new
![image](https://cloud.githubusercontent.com/assets/1275813/23373500/93ad6d8c-fd20-11e6-890b-28af074d83c9.png)

My colleague reports, that he has similar behavior in windows desktop client.

**Comment by reetp** [comment]
+1

I got feedback today from users about this. They miss the Skype type message notifier which shows how many unread messages there are.

**Comment by Nemra1** [comment]
+1
will be nice future

**Comment by soenkef** [comment]
I miss this information too.

**Comment by Silimilikim** [comment]
+1 no news on this ?

**Comment by rodrigok** [comment]
The desktop count is based on the numbers you see at the left sidebar, if you didn't configured your server to count all messages the counting for each room will just take care of mentions for your user and group mentions `@all and @here`.

You can change this behavior at `Admin > General > Unread Count`
