### ISSUE TITLE
Keep messages of removed users

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6186]
Hi,

if an user is removed, all messages of this user are deleted too. Why not keeping those messages and mark them as from a removed user? Or do I miss an option?

Ciao!
Marcus

**Comment by kaiiiiiiiii** [comment]
Administration -> Message -> Message Erasure Type

I think that’s the option you’re looking for.

**Comment by localguru** [comment]
Ah, nice. Didn't see that. I will check that tomorrow.

**Comment by rodrigok** [comment]
As @kaiiiiiiiii said, we already have that option so I'll close this issue.

Please reopen if necessary
