### ISSUE TITLE
Mobile error jitsi redirect to org.jitsi.meethttps://meet.jit.si/...

### ISSUE THREAD

**Issue by leonidmamontov** [RocketChat/Rocket.Chat#6187]
Rocket.Chat Version: 0.52.0
Running Instances: 
DB Replicaset OpLog:
Node Version:4.5.0 - x64  

When I using link to videochat from the beginner user (who start chat) on the mobile android. I already install jit.si app, when i choose "join to conversation" i'll redirect to org.jitsi.meethttps://meet.jit.si/.... in the internal browser. How i can cut org.jitsi.meet to have a valid url https://meet.jit.si/...?

**Comment by leonidmamontov** [comment]
Hello?

**Comment by leonidmamontov** [comment]
![s70301-114026](https://cloud.githubusercontent.com/assets/20603464/23452146/924e021e-fe7c-11e6-8956-835184f40255.jpg)
![s70301-114040](https://cloud.githubusercontent.com/assets/20603464/23452145/924a0cf4-fe7c-11e6-8ba0-c0dd69d5b85d.jpg)

**Comment by geekgonecrazy** [comment]
Now handled by mobile app
