### ISSUE TITLE
Error 405 on OPTIONS requests

### ISSUE THREAD

**Issue by nicgirault** [RocketChat/Rocket.Chat#6188]
Hello,

I'm trying to connect to demo.rocket.chat via jquery and I get an error 405 (method not allowed) when the OPTIONS request is sent on authenticated requests.

Thanks for your help

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by j0hn5on** [comment]
@nicgirault did u solve this issue.? Facing a similar issue
