### ISSUE TITLE
Suggestion: add ‘Deactivate’ button to profile

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6189]
I think it would be good to have the ‘Deactivate’ button below the ‘Remove from room’ button due to the fact that it would make permanent removal of unwanted elements (read: users) much quicker. The deactivate method is a lot better than trying to remove the user as he/she will just re-join -- thus I usually have to travel to the admin area and search for the user and deactivate him/her which takes up more time than I'd like.

What do you all think? Good, or...?

**Comment by Dracozny** [comment]
I would call it Ban user. It's definitely a must, especially for larger networks. Server admins have more important things to deal with than squabbles in individual chat rooms that could be dealt with by channel mods and owners.

**Comment by sampaiodiego** [comment]
we have discussed and we think that adding both admin and scoped actions can be confusing. what we could do is to add a button to go directly to the admin page and manage the user from there then, what do you think? I'll close this for now.
