### ISSUE TITLE
Hide Room Name, Description messages

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#6191]
Rocket.Chat Version: 0.52

Hello, 
I was wondering if in the roadmap there's something planned for hiding room name and description messages similar to how we now have "User Added", "User Removed" etc. Every time the room name is changed, it posts a message in the chat window, and I was wondering if there's a way to keep a clean window for first time users. 

Any help will be appreciated. 

Thank you

**Comment by SeanPackham** [comment]
We won't support that customization, the intention of that notification is to make sure channel members see the change.
