### ISSUE TITLE
MAIL_URL and Administration -> EMail -> SMTP are both required for a working instance

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#6192]
Rocket.Chat Version: latest

There are 2 ways to configure email in Rocket.chat:
 - MAIL_URL
 - Administration -> EMail -> SMTP

From my experience, they are both required and behave differently.
MAIL_URL is required to send "forgot password email" for instance, I believe, this is the standard meteor way.
Administration -> EMail -> SMTP is required to send verification email, this is I beliweve, something created by rocket, and not meteor standard..

This is related to #5192 and #3602 

Would it be possible to make Administration -> EMail -> SMTP read from MAIL_URL?
And make MAIL_URL read from `Administration -> EMail -> SMTP` if not present?

This way, we would have a consistent way of configuring emails in Rocket.Chat.

**Comment by reetp** [comment]
+1

**Comment by sampaiodiego** [comment]
We actually create the env var `MAIL_URL` from `Administration -> EMail -> SMTP` values at runtime. So they are the same thing.

But yes, we could read from `MAIL_URL` to fill `Administration -> EMail -> SMTP` values.

**Comment by pierreozoux** [comment]
@sampaiodiego thanks for your answer.

Actually the doc is pretty clear about it. As I know about MAIL_URL, it is strange for me as a meteor user.

I created this PR: https://github.com/RocketChat/Rocket.Chat.Docs/pull/260 to simplify the doc, and remove reference to MAIL_URL as it is not really needed then.
