### ISSUE TITLE
Delete all Attachments / Files from a Channel /Chat

### ISSUE THREAD

**Issue by Angl0r** [RocketChat/Rocket.Chat#6193]
Rocket.Chat Version:  0.52.0
Running Instances:  1
DB Replicaset OpLog: disabled
Node Version: V4.5.0

Hi there, 

We would recoment a function wich eareses all Attachments in one Channel or Chat. 

Example 1: a private chat between two Users got now more than 100 files uplaoded. 
Example 2: a channel with more than 30 Users and a lot of files has been added to that channel. 

Many of that files are no Longer used, but its hard work to delet them all single handed.

**Comment by danilomiranda** [comment]
Where this function could be called? In here?
![captura de tela 2017-06-09 as 2 31 25 pm](https://user-images.githubusercontent.com/1092454/26989088-1ea3d622-4d28-11e7-990b-60e8ec33082e.png)

**Comment by marceloschmidt** [comment]
I would suggest it on the attachments flextab.

**Comment by danilomiranda** [comment]
@marceloschmidt  Almost done, but I'm not like the style of delete all buttons

![delete-files](https://user-images.githubusercontent.com/1092454/27762750-46795e7e-5e4e-11e7-9df0-2f817a3034cc.gif)

**Comment by danilomiranda** [comment]
How about that? 🤓 
<img width="449" alt="screenshot 2017-07-01 12 32 22" src="https://user-images.githubusercontent.com/1092454/27763404-70ce42ce-5e59-11e7-8137-e531ab8e1e14.png">

**Comment by danilomiranda** [comment]
I think it`s done!

<img width="410" alt="screenshot 2017-07-01 17 40 34" src="https://user-images.githubusercontent.com/1092454/27765372-9580dd6c-5e85-11e7-93ab-11bd70fddf1a.png">

[See this in action](https://www.youtube.com/watch?v=sCgFyfuaM8c)

**Comment by hikikomorime** [comment]
HI, Any date when this option will be available? It also be great to set some timeframe when attachments are purged automatically like after 7 days etc.

**Comment by imeleges** [comment]
Hi, I just upgraded my RC to version 0.65.1 and I don't see the ability to delete attachments from file list at all. 
Did I miss something? =)
![rc_filelist](https://user-images.githubusercontent.com/13563643/41005183-13139aa0-68e2-11e8-80e1-bd28f59353eb.PNG)
