### ISSUE TITLE
AmazonS3 Storage Type defaults to GridFS when migrating from 0.50 to 0.52 - cannot switch back to S3

### ISSUE THREAD

**Issue by fspc** [RocketChat/Rocket.Chat#6197]
Rocket.Chat Version: 0.52
DB Replicaset OpLog: Disabled
Node Version: 4.8.0 - x64 

This is a UI bug.  When migrating a 0.50 instance with the Storage Type set to AmazonS3 to version 0.52, the Storage Type defaults back to GridFS.  Any attempt to save AmazonS3 as the Storage Type again fails, in fact, the Save Changes dialog does not work.  You can choose FileSystem, then AmazonS3 to ameliorate that issue, however, even then GridFS becomes the default if you click on File Upload again.  Because of this bug, S3 will not work.

These sound like related issues:  #6184, #6123

**Comment by Hudell** [comment]
This was fixed on 0.53
