### ISSUE TITLE
Windows client have no tray icon notification

### ISSUE THREAD

**Issue by SergeSpinoza** [RocketChat/Rocket.Chat#6199]
Hi. 
Have RocketChat client tray icon notification? 

When somebody wrote me – I have notification in web browser like this https://yadi.sk/i/uMpHq2283ErAF6
However, in windows client tray icon I have no any notification (only push notify, but it no usefull), show tray icon like this https://yadi.sk/i/8YyOUAAt3ErAH5 (nothing change). 

Rocket.Chat Version: 0.52.0
Running Instances: 
DB Replicaset OpLog:
Node Version: 4.5.0 - x64

**Comment by SergeSpinoza** [comment]
My problem like this [Rocket.Chat/issues/2984](https://github.com/RocketChat/Rocket.Chat/issues/2984), but on windows 10. 

On MAC it works good - https://img-fotki.yandex.ru/get/226827/175307653.0/0_1b36bf_bef7bf50_orig

**Comment by gdelavald** [comment]
The issue has been fixed in the current version.
