### ISSUE TITLE
Custom Sounds cannot be uploaded from Firefox or IE

### ISSUE THREAD

**Issue by cpitman** [RocketChat/Rocket.Chat#6200]
Rocket.Chat Version: 0.52 via Docker Image

The current client side code checks for a mime type of "audio/mp3", which is used by chrome and opera (and is also non-standard). Firefox and IE show the standard mime type of "audio/mpeg", which fails validation.

**Comment by soohwa** [comment]
I have the same problem (Firefox 53) even if i empty the media file type accepted in /admin/FileUpload.
My /etc/mime.types looks correct :
`audio/mpeg                                      mpga mpega mp2 mp3 m4a`

**Comment by rasos** [comment]
Behaviour confirmed: uploading custom sounds only works with Chrome / Chromium, not with FF browser.
