### ISSUE TITLE
Change default smileys produced by usual ascii to smileys automatic transformation

### ISSUE THREAD

**Issue by joublie** [RocketChat/Rocket.Chat#6203]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: disabled (only one member in replicaSet)
Node Version: v4.7.3

Users are complaining about default emoticons produced when typing usual ascii emoticon characters like :) or :D (and the likes). I found a set of emoticons that could be used and that would suit users, but I can't find a way to configure them in Rocket.Chat so that those icons are displayed instead of the default ones.

I was told by Rocket.Chat support that this is not possible for the time being, unless I compile the sources myself, but I'm not sure I can do that, and even if I could I'm not sure I have the skills to do that.

Can/Will a corresponding feature be developped in Rocket.Chat to accomplish this ?

Thanks !

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of: #1838.

Cheers
Thomas
