### ISSUE TITLE
Want to disable Members List option from Private chat room

### ISSUE THREAD

**Issue by ruushabhdharod** [RocketChat/Rocket.Chat#6212]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5.0 - x64

Hello,

Want to disable Members List option from Private chat room so no one can view or list users of that particular chat room.

**Comment by SeanPackham** [comment]
We don't have plans to support this feature. Have you considered allowing anonymous read only users for your private channels.
