### ISSUE TITLE
Rocketchat vulnerable like Slack? (WebSocket-reconnect to steal your precious token)

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#6213]
Rocket.Chat Version: 0.53.0
Node Version: 4.7.3

Hello Devs.

Just out of curiosity. Is Rocketchat vulnerable to the hack just discovered for Slack?

https://labs.detectify.com/2017/02/28/hacking-slack-using-postmessage-and-websocket-reconnect-to-steal-your-precious-token/

thanks and cheers
t.

**Comment by graywolf336** [comment]
I wouldn't think so, as we don't exactly use events like that.

**Comment by engelgabriel** [comment]
Indeed we don't.
