### ISSUE TITLE
Add role "assign-privileged-role"

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6214]
We have added a role "user+" which is for a secretary, to allow him to add users.
However, he can assign all roles (livechat, Owner, Moderator, etc) except administrator (which is a separate permission "assign-admin-role", not given to that user+ role). This is a security risk. He can even assign another user the confidential user+ role.

Could we have an additional role "assign-privileged-role" which does allow only to add the roles "user" and "guest", but no other role?

Rocket.Chat Version: 0.52

**Comment by sampaiodiego** [comment]
I'm sorry this looks a very specific use case. We don't plan to add such functionality, but we still accept a PR.
