### ISSUE TITLE
Send test push to any user

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat#6219]
Rocket.Chat Version: latest

What about supporting sending test pushes to any user (not just to self)?

It could help troubleshot problems with the push notification per user.

**Comment by KirschbaumP** [comment]
+1

**Comment by KirschbaumP** [comment]
Are there reasons why this ticket get closed?

**Comment by geekgonecrazy** [comment]
We have plans to try to help end users determine push issues from the app it’s self.  The ability to test other users push already exists.  Just shoot them a DM.
