### ISSUE TITLE
Auto-completion of #channel name does not disappear if there are no matches

### ISSUE THREAD

**Issue by dbussert** [RocketChat/Rocket.Chat#622]
When chatting about channels of other irc servers, or anything starting with #, Rocket.Chat starts trying to autocomplete what we're typing.  When nothing matches a Rocket.Chat #channel, the box will stay popped up, but if you simply hit enter to finish the message, it will replace the word with #general.  We're used to Slack's approach which is if no #channel matches, then assume the user doesn't want to auto-complete and allow the user to finish typing without getting in the way.

**Comment by rodrigok** [comment]
@dbussert was fixed in some commit ago. Can you try again?

**Comment by dbussert** [comment]
@rodrigok confirmed it was fixed, closing.
