### ISSUE TITLE
Search box grabs focus on ctrl-k as well as cmd-k

### ISSUE THREAD

**Issue by zanshin** [RocketChat/Rocket.Chat#6220]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled ?
Node Version: v4.5.0

On macOS Sierra the search box grabs focus on control-K as well as command-K. This interferes with using EMACS style key bindings, where ctrl-a+ctrl-k takes you to the beginning of the line and erases the entire line. I suspect that the search box focus is set this way to allow the application to work on Windows (where the control key is used for shortcut keys) and macOS (where the command key is used for shortcut keys). 

If the same app is wrappered for both Windows and macOS, and therefore is going to capture ctrl-K and cmd-K indiscriminately, then the default text in the search box should say "CMD-K/CTRL-K". Ideally the macOS version of the app would not capture ctrl-K.

**Comment by engelgabriel** [comment]
Hi @zanshin when you say *interferes* is it actually causing problems or is it just confusing?

**Comment by engelgabriel** [comment]
Unless it is actually causing problems, I don't think we need to change the default text,

**Comment by zanshin** [comment]
@engelgabriel It is causing problems. You cannot use `ctrl-k` to delete from the current cursor position to the end of the field. Using Cmd/ctrl-k for search breaks the paradigm expected by command line users. "F" is typically the letter used for search (find) in applications.

**Comment by ksuquix** [comment]
@engelgabriel I see this is broken as well...   why is this closed?
