### ISSUE TITLE
Switch Snap to using oplog / replicaset

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#6223]
Switch Snap to using oplog / replicaset to increase performance

**Comment by Sing-Li** [comment]
Please synchronize with the (substantial) work done here, in order to have one single 'snapcraft.yaml' for all archtiecture builds :

https://github.com/RocketChat/rocketchat-server-snap

**Comment by Sing-Li** [comment]
@elespike  can probably help to ensure compatibility - he had done a lot of coding and testing
