### ISSUE TITLE
Add setting to only allow login once email has been verified

### ISSUE THREAD

**Issue by 56kb** [RocketChat/Rocket.Chat#6225]
User registration should be set to approve only by default for better out of the box security
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by graywolf336** [comment]
I would disagree, because then the first user couldn't register..

**Comment by 56kb** [comment]
Once the server is installed and running the first page should be an enrollment wizard to get the Admin account going. Once that is completed new users will need to be approved.

**Comment by engelgabriel** [comment]
We plan to have the initial setup wizard, and this would be one of the basic settings on that.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/2233

**Comment by SeanPackham** [comment]
Added more descriptive title.

**Comment by rodrigok** [comment]
The setting already exists `Admin > Accounts > Registration > Email Verification`
