### ISSUE TITLE
Simple UI improvement to the left bar - save 5% space on the left bar

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#6227]
I have to keep scrolling to use the left bar.

If we can make the left bar more compact that would be helpful.

Here are a couple of suggestions to use the space in the leftbar more efficiently,

![image](https://cloud.githubusercontent.com/assets/6703876/23537185/3930cdb6-ff7f-11e6-9f16-577481dc7888.png)

**Comment by MartinSchoeler** [comment]
Please see our ui redesign
