### ISSUE TITLE
*/zero mq, bridge to somewhere

### ISSUE THREAD

**Issue by griffindoors** [RocketChat/Rocket.Chat#6228]
Maybe before xmpp bridge zero mq or other mq?

vs https://github.com/RocketChat/Rocket.Chat/issues/404

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this due to not enough information. There are already other issues that concern themselves with some of the "bridges" requested here. Please state exactly what you want, if this is still importan to you. I'll happily reopen the issue then.

Cheers
Thomas
