### ISSUE TITLE
Changing settings has no effect on the client

### ISSUE THREAD

**Issue by antpaw** [RocketChat/Rocket.Chat#6231]
I've changed this settings in the `lib/startup/settings.coffee` but and clear all the local storage and any other data, but the client still thinks this settings is `true` and displays all the hint below the textarea. What am i doing wrong?

```
	@add 'Message_ShowFormattingTips', false, { type: 'boolean', public: true }
```
Rocket.Chat Version: 0.53.0 
Node Version: 4

**Comment by antpaw** [comment]
okay, i think i understand this better now, this var is just a default state for the Administration form. Is there any way to change the settings programmatically, something like a seed file?

**Comment by engelgabriel** [comment]
If you set an environment variable with the same setting name before you run the server for the first time, it will use that value instead.

**Comment by engelgabriel** [comment]
Any reason for not using the Administration panel to change the configuration?

**Comment by antpaw** [comment]
well, it's nice that you can check in your settings into git, and have it across all team members and servers no matter how often you drop the database. But the env vars kinda work for this too.

**Comment by MartinSchoeler** [comment]
@antpaw I will be closing this issue. If your question was not answered please reopen this. Thanks for the feedback!
