### ISSUE TITLE
Comment on attachment does not appear

### ISSUE THREAD

**Issue by axeloz** [RocketChat/Rocket.Chat#6232]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

Hello,

When sending a text document on Rocket by dropping the file, the attachment window appears. I enter a comment and submit. 

<img width="493" alt="capture d ecran 2017-03-03 a 12 41 04" src="https://cloud.githubusercontent.com/assets/1597611/23550010/28aca3e4-000f-11e7-8de0-30317e975c22.png">

Once submitted, the attachment appears in the discussion but not my comment:

<img width="368" alt="capture_d ecran_2017-03-03_a_12_41_14" src="https://cloud.githubusercontent.com/assets/1597611/23550037/47223ef6-000f-11e7-9696-aacc44fc4e66.png">

This is a different behavior when sending an image attachment: in this case, the comment appears:

<img width="816" alt="rocket_chat_" src="https://cloud.githubusercontent.com/assets/1597611/23550087/91984084-000f-11e7-9718-ddd366f73726.png">

 Thanks

**Comment by MartinSchoeler** [comment]
Thanks for the feedback! This issue was already fixed in #6217

**Comment by axeloz** [comment]
Sorry, I did make an issues search first but didn't find this one. Thanks
