### ISSUE TITLE
API-Call for adding users into roles

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat#6233]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

I would like to have the possibility to add users to roles using an API-Call.
I wrote a script that adds users to specified rooms based on their LDAP-Group using the API and would like to have the possibility to do so with roles too.

**Comment by graywolf336** [comment]
We currently have that with the rest api: https://rocket.chat/docs/developer-guides/rest-api/users/update#user-update just update the roles property and you'll be good.
