### ISSUE TITLE
Is it possible to configure s3 from env?

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#6235]
I'm working on the Rocket.Chat helm chart, and I'm wondering if this is possible.

Thanks!

**Comment by engelgabriel** [comment]
Yes, it is. @sampaiodiego can you help here?

**Comment by sampaiodiego** [comment]
@pierreozoux you can set the following environment variables at startup:
* `FileUpload_Storage_Type=AmazonS3`
* `FileUpload_S3_Bucket`
* `FileUpload_S3_AWSAccessKeyId`
* `FileUpload_S3_AWSSecretAccessKey`
* `FileUpload_S3_CDN`
* `FileUpload_S3_Region`
* `FileUpload_S3_BucketURL`

**Comment by pierreozoux** [comment]
Thank you very much this helps a lot to know that :)
