### ISSUE TITLE
Javascript Error when Moving Rocket Chat window

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#6237]
Rocket.Chat Version: 53.0

I'm having an issue where when I attempt to drag the Windows version of Rocket.Chat client I get an instant error popup saying Javascript Error.

See attachment.

![capture444](https://cloud.githubusercontent.com/assets/662675/23557432/1394e068-fffe-11e6-9682-4deb49a96d9c.JPG)

**Comment by engelgabriel** [comment]
You need to update your desktop client to the latest version.
