### ISSUE TITLE
Emoticon not displaying correctly on some browsers after update to 0.52.0

### ISSUE THREAD

**Issue by PacketPerception** [RocketChat/Rocket.Chat#6238]
After upgrading to 0.52.0 on more than half of the browsers/apps we've tried emoticons are not displaying correctly. There does not seem to be any rhyme or reason to why it is occurring, it is also not consistent between same browser versions. It does stay consistent to the browser it is occurring on, whether the cache's are cleared or not.

![screen shot 2017-03-02 at 11 11 57](https://cloud.githubusercontent.com/assets/4775056/23559731/f9316d6a-0005-11e7-97c7-4bd12254f63a.png)

Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.5.0

**Comment by engelgabriel** [comment]
Maybe it is the browser cache? Can you try clearing it and see if it fixes?

**Comment by PacketPerception** [comment]
Thanks for trying, but have tried clearing caches on all affected and non-affected browsers.

**Comment by PacketPerception** [comment]
After current updates, this issue seems to have resolved itself. Closing
