### ISSUE TITLE
run own STUN/TURN Server, which software?

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6240]
Hi,

what's a good software to run an own STUN/TURN Server on Linux instead of the preconfigured servers:

stun:stun.l.google.com:19302, stun:23.21.150.121, team%40rocket.chat:demo@turn:numb.viagenie.ca:3478

What are you using on rocket.chat? Jitsi, coturn?

Ciao!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by HumphRey123** [comment]
I use turnserver0.73 , it works.
