### ISSUE TITLE
Add a way to view hidden channels / direct

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#625]
We can hide / leave channels but no way to see which ones we are part of that are hidden.

Same goes for messages.  I've had lots of conversations.  But I don't want to keep them up so I hide them.  But now I don't have an easy way of bringing them back.

Proposal:

Maybe clicking The text shows all?  instead of clicking it creating a channel.  We already have buttons on each of them.

**Comment by marceloschmidt** [comment]
Somewhat related to #647

**Comment by aurora** [comment]
I am not sure, why this issue is closed - as far as i can see #2537 just adds features to address #625. But there is still no possibility to unhide hidden channels.

**Comment by geekgonecrazy** [comment]
all channels you are part of are searched when you do ctrl+k or click search at the top of the channel list

**Comment by aurora** [comment]
Thanks! Seems i searched in the wrong place - "Directories" ( i am new to rocket chat :-) ).
