### ISSUE TITLE
Custom JitsiMeet

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#6250]
I just got my own JitsiMeet server up and running and love it... have noticed that it works slightly differently than the default one (meet.jit.si) though.

The main difference is that meet.jit.si seems to display the usernames on a video call through JitsiMeet within RocketChat - on my own server I don't see my username (it just says 'me')

Are there any tips or tricks for additional hacks to JitsiMeet that would get it to sing in RocketChat better which I should consider?

q./

**Comment by rasos** [comment]
Works here. We see the user names on our own Jitsi meet instance. Using a Jitsi meet nightly build from January 2017.

**Comment by designgurudotorg** [comment]
Weird... not doing it for me... also have some strange problem which is printing an error on screen when more than 1 person is in a JitsiMeet video session!? (ref: https://github.com/jitsi/jitsi-meet/issues/1375 )

**Comment by designgurudotorg** [comment]
Just reinstalled my whole jitsimeet server from scratch to bug hunt this and still, I'm not seeing usernames passing into jitsimeet sessions within RocketChat...

**Comment by amenk** [comment]
How is passing on the username supposed to work technically?

**Comment by designgurudotorg** [comment]
Not sure @amenk but it works out of the box with RC and the default meet.jit.si implementation!

**Comment by geekgonecrazy** [comment]
Closing since been a few years since activity
