### ISSUE TITLE
own camera is flipped

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6254]
Rocket.Chat Version: 0.52.0

The own camera ("you") is flipped. Why that?

![flipped](https://cloud.githubusercontent.com/assets/8544984/23588590/fc3646b4-01bf-11e7-80b8-2e472bacfa14.jpg)

Ciao!
Marcus

**Comment by ggazzo** [comment]
hey @localguru , I dont think that is a bug, actually all services flip your won camera... I will be closing this issue, but feel free to reopen if you think that is really a problem.
hangouts
![image](https://user-images.githubusercontent.com/5263975/40559747-2ecada68-602e-11e8-9b2e-14b370681820.png)
jitsi
![image](https://user-images.githubusercontent.com/5263975/40559870-9308de62-602e-11e8-99ef-a5f3de649921.png)

rocketchat
![image](https://user-images.githubusercontent.com/5263975/40559760-35fd9cda-602e-11e8-8b82-9e16cb64ce25.png)
