### ISSUE TITLE
Bot access via LiveChat

### ISSUE THREAD

**Issue by divesho** [RocketChat/Rocket.Chat#6261]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

I'm tring to integrate bot to rocketchat. Integration of bot with private channel, group is working. But my concern is how to integrate Bot with livechat. [for guest/anonymous login]. There is no api or method to integrate bot to live chat.

**Comment by gugahoa** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/6030

quoting:

> How it's working right now:
> 
> Livechat guest/user creates a room with first message
> Bot is added to the room after it's created
> Livechat Room is not considered DM, so you need to mention the bot
> I made a basic PR to add the feature to respond the livechat (RocketChat/hubot-rocketchat#211)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
