### ISSUE TITLE
Disable the option so that users cant be able to mention others

### ISSUE THREAD

**Issue by rajatkumarpati** [RocketChat/Rocket.Chat#6263]
Hi.

I want to know if there is any option to Disable the mentions option so that users cant be able to mention others.

Please help.

Rocket.Chat Version: 0.49.4
Running Instances: 1
DB Replicaset OpLog: 
Node Version: v4.6.2

**Comment by sampaiodiego** [comment]
I'm sorry but this is use case seems very specific and we don't plan to support it. a PR is still welcome though.
