### ISSUE TITLE
Adding labels to messages

### ISSUE THREAD

**Issue by krystalcode** [RocketChat/Rocket.Chat#6265]
Rocket.Chat Version: 0.53.0

Is it possible to label messages? I haven't found anything so far. That could be for example, when you click on the gear icon for configuring a message, you should get the ability to add a label to the specific message/post. You would then be able to filter a channel's messages with labels.

If it is not possible, I would be willing to develop a plugin that provides this functionality. Since I'm new to Rocket Chat and Meteor as well, any directions on how to get started?

**Comment by rasos** [comment]
This would be awesome and could be a "modern" way of threading messages. Let also users instantly create labels.  See also #5460 for a wireframe redesign, where this could be integrated.

**Comment by niellz123** [comment]
Are there any news regarding this issue? I am really interested in tagging respectively labeling messages with different priorities.

**Comment by rasos** [comment]
See also #3283

**Comment by sampaiodiego** [comment]
I'm sorry but we don't have plans to add this to the core product.

on the future apps will be able to add message actions though, so it will be possible to have capability added from apps.
