### ISSUE TITLE
Allow individual channels to be muted

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#627]
This is sort of related to: #171

My thought is you are in a couple of channels, but don't really want notifications from it you should be able to mute that channel.

It could still glow letting you know there are unknown but shouldn't alert you at all.

**Comment by marceloschmidt** [comment]
Related to #249 too... closing this for being covered on other issues.

**Comment by iridos** [comment]
Hi,
this links to #249, which then is was closed, too for a more generic "channel settings" feature which links to nothing specific to this issue. 

And yet this request has been from 2015, soon 10 years ago. 

What I'd like to know: Is this feature present in current rocket chat after all that time or not? 

I only see the option to "hide" or "leave" a room, but I may be overlooking something.
Best,
I.
