### ISSUE TITLE
Clipboard Name to include date by default

### ISSUE THREAD

**Issue by thehutman** [RocketChat/Rocket.Chat#6270]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: no
Node Version: v4.7.3

A number of people have asked if the name for pasted items can include the date along with "Clipboard" by default.  Otherwise, the list of files attached can get a bit difficult to sort through by just seeing the name "Clipboard" for everything.

Suggestion:

![image](https://cloud.githubusercontent.com/assets/4375809/23638523/c8aa2b7e-02a7-11e7-8ac3-5325e6ec2563.png)

Looking at a list of nothing but Clipboard (people are lazy and don't usually change the names):
![image](https://cloud.githubusercontent.com/assets/4375809/23638563/fcbc946a-02a7-11e7-9229-4e0fb7a89083.png)

**Comment by gdelavald** [comment]
Hey, made a small change to support this, let me know what you guys think:

<img width="380" alt="screen shot 2017-03-07 at 12 49 57 am" src="https://cloud.githubusercontent.com/assets/6303966/23641065/227b1dde-02d0-11e7-85a1-32581e51d45c.png">
<img width="485" alt="screen shot 2017-03-07 at 12 49 02 am" src="https://cloud.githubusercontent.com/assets/6303966/23641066/227bf3ee-02d0-11e7-8015-e67f0b3bd374.png">

**Comment by thehutman** [comment]
That looks great!  Mimics functionality that Slack has for this.
