### ISSUE TITLE
how add custom  chat command like /someaction params   to trigger hobut script action 

### ISSUE THREAD

**Issue by tablecell** [RocketChat/Rocket.Chat#6271]
Rocket.Chat Version: 0.41
Running Instances:
DB Replicaset OpLog:
Node Version: 4.5 

I have a running  RocketChat  instance   and runing hubot  instance  both  deployed  ok 

how integraite  RocketChat and   hobot together 
for example 
wher user input  "/someaction params"  then call a hubot script  and retrurn reply 

follow the guide https://rocket.chat/docs/administrator-guides/hubot/#hubot
 docker run -it -e ROCKETCHAT_URL=127.0.0.1:80    -e ROCKETCHAT_ROOM='nnnn'     -e LISTEN_ON_ALL_PUBLIC=false     -e ROCKETCHAT_USER=mybot     -e ROCKETCHAT_PASSWORD=bot     -e ROCKETCHAT_AUTH=password     -e BOT_NAME=bot     -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help     -v /var/bot/myhubot/scripts   rocketchat/hubot-rocketchat
hubot-help@0.2.0 node_modules/hubot-help

hubot-pugme@0.1.0 node_modules/hubot-pugme
[Tue Mar 07 2017 13:47:24 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 1.0.6...
[Tue Mar 07 2017 13:47:24 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: bot
[Tue Mar 07 2017 13:47:24 GMT+0000 (UTC)] INFO Connecting To: 127.0.0.1:80
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Successfully connected!
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO nnnn
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Logging In
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Successfully Logged In
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Looking up Room ID for: nnnn
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Joining Room: C26fHGv5i6n8d8aXK
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO rid:  [ 'C26fHGv5i6n8d8aXK' ]
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO All rooms joined.
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Successfully joined room: C26fHGv5i6n8d8aXK
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Preparing Meteor Subscriptions..
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Subscribing to Room: __my_messages__
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Successfully subscribed to messages
[Tue Mar 07 2017 23:20:13 GMT+0800 (CST)] INFO Setting up reactive message list...
...

 /var/bot/myhubot/scripts/example.coffee
```
module.exports = (robot) ->

    robot.respond /callme/i, (res) ->
      res.reply " yes Master   "
```
above  code  only works  when chat message  include 'callme'   just like  String.indexOf('callme')
when input  /call 
RocketChat reply " no  such  command：/call "
how to implment   command    like  ' /call  some params  '?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
