### ISSUE TITLE
Room not found after changing room from private to public

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#6275]
Rocket.Chat Version: 0.51.0 
Running Instances: 10
DB Replicaset OpLog: Yes
Node Version: v4.6.2

Previously I had the same issue #5903 but after an upgrade the channel showed up.
It seems to be happening again when some users change their private room to a public channel then users are no longer able to get to them 
The error is: 
![image](https://cloud.githubusercontent.com/assets/21371983/23662964/6b7cc350-030e-11e7-88bf-c11403d194d0.png)

I have two confirm rooms that changed from a private to a public group causes this issue. I did try to duplicate it as an admin and also had another issue without admin rights go through the scenario of creating a private group add users and then change it to public. But my tests do not duplicate the issue. I'm not sure if this is a random failure.

Right now these have been smaller groups but I can see this being a larger issue if there are many participants with a lot of data where this could be nasty. Since the groups have been small a workaround is to create a similar room that is public for that specific subject.

**Comment by localguru** [comment]
I had the "no channel ... was found" messages in to past too, but can't remember the circumstances as it was a test instance. I created a private channel (as normal user), put two other users into it and then changed the channel to public. I had no problems. After that I renamed the channel, also no problems. Version 0.52.0

**Comment by drickerusa** [comment]
Thanks @localguru I was playing with it a few minutes ago and was going through and restarting my instances one at a time. After these restarts completed I was able to see this channel again. Which actually makes me a little more wary of this situation since its possible that everything is not totally in sync. Not sure how I narrow down an RC instance to a problem like this. So this leaves me to believe my previous issue #5903 was not fixed by an update, but by the restarting the RC system. Since this is production I can not narrow down to 1 instance. I need at least 5 instances running to maintain performance.

**Comment by willihelm** [comment]
I have a similar issue when changing the room name. I can add users via API but they cant join a public channel themself with the same error message.
Seems like evry change on a chat room causes this.

**Comment by willihelm** [comment]
Okay after the latest update 54.2.0 and restarting the server it works again.

**Comment by Hudell** [comment]
It seems to be working on the current version. If not, the issue can be reopened.
