### ISSUE TITLE
App links on login page (and...)

### ISSUE THREAD

**Issue by acamarata** [RocketChat/Rocket.Chat#628]
In the admin section put a section "Apps" which then gives a form that allows you to link to your Android, iOS, Win, Mac, (Chrome Store, etc.) apps.

Then at the bottom of the login page read the above and if 1 (or more) exists add a section that says "or use our app on ..." and put a plug for each app that a download link is set.

Allow short code in the Home page setup also to plug for them (which would give a graphical plug for the apps same as on the login page)...

For a "graphical" or nice plug I was thinking like seen at https://telegram.org/
##

**Comment by geekgonecrazy** [comment]
To be clear.  Is this for displaying links to Official Rocket.Chat apps.  Or is this for custom built rocket.chat app for your org/site only?

**Comment by alisalaah** [comment]
If this is rolled into the app and uses links in the Admin section to point
to the Google Play, AppStore, dmg file, etc. then it will be for the
Rocket.Chat app but also can be easily customized for custom apps as well.
Any images to make it graphical like a phone next to computer or the Google
Play icons etc. would be static from code.

**Comment by geekgonecrazy** [comment]
Seems like it'd be good for Rocket.Chat to have links to these.  Might as well make them configurable. What do you guys think @engelgabriel ?

**Comment by mitar** [comment]
That would be great once there will be support for custom servers in apps as well.

At the moment we are simply putting those links to home page.

**Comment by Prakharsvnit** [comment]
@RocketChat/core I am working on this issue, I think we can display Android, iOS, Linux, Windows and Mac apps.
 but I would like to know how  UI should look like, can it be like above-suggested telegram app's page here: https://telegram.org/apps

**Comment by karlprieb** [comment]
@RocketChat/core what you guys think? We should use links or images (app store badges)?

**Comment by geekgonecrazy** [comment]
Badges are used almost everywhere I see mobile apps being linked to.  I think people see them enough they are more intuitive to them

**Comment by p8107406332** [comment]
i want to work on that issue so can i contribute or not

**Comment by engelgabriel** [comment]
We could add something like this:

![image](https://user-images.githubusercontent.com/1000217/35226274-f0965c1c-ff71-11e7-96d6-54bd50855846.png)

To the bottom of the Account menu:

![image](https://user-images.githubusercontent.com/1000217/35226307-0b523d1e-ff72-11e7-95d9-ce3d5b326272.png)

**Comment by dhruvdutt** [comment]
I would like to take this up. :hand:

**Comment by SeanPackham** [comment]
@dhruvdutt please feel free to take this issue. See Gabriel's last comment for a mockup of how this could work.

**Comment by dhruvdutt** [comment]
I've some priority stuff lined up currently and will try to come to this eventually.
Feel free to pick this up if anybody wants.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap and we have had a few attempts to start it with no luck. We can revisit once other priorities have been addressed.
