### ISSUE TITLE
jitsi app not opening on ios

### ISSUE THREAD

**Issue by tribjcrea** [RocketChat/Rocket.Chat#6281]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog:
Node Version:
This is installed and running locally on CentOS 7.3.1611
When trying to start or join video chat on ios, the installed jitsi app doesn't launch and there is just a gray window. However when clicking on a shared video (jit.si) link it launches and works fine.

**Comment by tribjcrea** [comment]
It also works fine on demo.rocket.chat
Just trying to find out if we're missing some config somewhere.

**Comment by rasos** [comment]
You may need to enable CORS at Jitsi Meet's nginx: https://enable-cors.org/server_nginx.html

**Comment by engelgabriel** [comment]
@tribjcrea has this issue been fixed on the latest version?
