### ISSUE TITLE
CAS how to logout?

### ISSUE THREAD

**Issue by coderbaicai** [RocketChat/Rocket.Chat#6287]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: 4.7.3

when using CAS login Rocket.Chat, I login use user1, and then logout . 
And then I click CAS login again, user1 doesn't logout.
how do i logout when using CAS login?

**Comment by corecache** [comment]
The /logout of Rocket.Chat terminats the session within Rocket.Chat and NOT the session with your SSO login provider. The reason for this is that if you have a SSO session witha central SSO provider and you log out of one application, would log you out of all applications.

**Comment by coderbaicai** [comment]
OK, i got it.   
Thanks.
