### ISSUE TITLE
no such package "rocketchat:webrtc-ib"

### ISSUE THREAD

**Issue by shaharido1** [RocketChat/Rocket.Chat#6288]
Hey, 

In the docs you mention as first step to install the package "rocketchat:webrtc-ic", but it's missing in your repo. https://rocket.chat/docs/user-guides/remote-video-monitoring/

I'm trying to configure the video motoring - what's the alternative?

**Comment by shaharido1** [comment]
Hey, any news maybe? @MartinSchoeler  

I don't really understand the instructions of setting up monitoring cams... 
where are the settings..? for exemple I can't locate this "flex window" : "..Click on the top right arrow to open the flex window. You will see THREE buttons:"

thanks!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
