### ISSUE TITLE
Server cache consistency problem

### ISSUE THREAD

**Issue by billtt** [RocketChat/Rocket.Chat#6289]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: true
Node Version: 4.5.0

Recently we've run into a problem with the consistency of server cache and db. One of the users suddenly couldn't see messages in a channel one day, and reloading (client) didn't solve the problem. I (as the owner of the channel) tried to remove him from the channel, but failed (it prompted the use is not member of the channel). I then went to the server, and checked mongodb, and found that his subscription to the channel and the channel's usernames were all ok (he was one of the members of the channel).
From the code I can see that this error is thrown after checking the existence of the user in the room's usernames array. So, I can get the conclusion that the server cache is inconsistent with db.
I haven't restarted server yet. My guess is that if I reboot, the problem is gone.
Anything that I can do to trace the problem? Or does anyone else have this problem?

**Comment by billtt** [comment]
The problem went away after I restarted the server. But I'm afraid it my imply something more serious hidden somewhere.

**Comment by geekgonecrazy** [comment]
Please let us know if you find a reproducable bug.

Going to go ahead and close this.  

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support category
