### ISSUE TITLE
Support end to end encryption

### ISSUE THREAD

**Issue by valentt** [RocketChat/Rocket.Chat#629]
I know that Rocket.Chat is quite new and has gone far in short time, but have you thought of what will happen if Rocket.Chat becomes really big and used a lot? Will you provide privacy for users via end to end encryption?

Where would Rocket.Chat land on EFF's secure messaging [scorecard](https://www.eff.org/secure-messaging-scorecard)? 

Thanks for great product and keep up the good work.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/36?

**Comment by geekgonecrazy** [comment]
Seems related.  OTR / forward secrecy.  A lot of desire for this it seems.

**Comment by marceloschmidt** [comment]
Duplicate
