### ISSUE TITLE
IOS Unread Counter Badge Doesn't Decrement

### ISSUE THREAD

**Issue by lashae** [RocketChat/Rocket.Chat#6290]
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.7.1

We are using rocket.chat as a hosted instance via our alias on rochet.chat domain. On IOS, unread count never syncs with server to decrease the counter. When a new message arrives it is incremented, I read the message on my desktop but IOS app badge still remains at "1"; even after tens of hours.

**Comment by sampaiodiego** [comment]
duplicated of #3618
