### ISSUE TITLE
Disable "rocket.cat" 

### ISSUE THREAD

**Issue by jsumners** [RocketChat/Rocket.Chat#6293]
How do you disable this "rocket.cat" thing?

**Comment by DalePayman** [comment]
In Admin - Internal Hubot - disable.

**Comment by jsumners** [comment]
Thank you. That wasn't at all obvious and I couldn't find any documentation on the feature what-so-ever.

**Comment by hagaymyr** [comment]
This doesn't seem to disable that BOT in all places - 
for example, using the slash-command "invite-all-..." will result in message from the rocket.cat "The users have been added".

**Comment by gstlouisgit** [comment]
> In Admin - Internal Hubot - disable.

I do not see this in my rocket chat version 3.5.2

Version | 3.5.2
-- | --




Version | 3.5.2
-- | --

**Comment by jorueda** [comment]
Hello, I couldn't disable rocket chat (version 3.9.1). Did you disabled it?
