### ISSUE TITLE
Wipe all LiveChat history

### ISSUE THREAD

**Issue by nmolinski** [RocketChat/Rocket.Chat#6294]
Rocket.Chat Version: 0.53
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

Upon switching the Guest Counter from 6 to 1, RocketChat holds the references to all of its previously conducted chats and doesn't allow them to be overwritten. Now new livechats created are not able to be viewed because when clicking on them, it redirects to the older livechat at that id number. 

i.e. Clicking on any of these chats with Jonny Steel just redirects me to a prior chat I had with someone else and I can never view the chat with Jonny Steel.

It would be incredibly useful if we could delete all livechats or delete some of them. 

Really frustrating that now I have 6 unread messages I can't get rid of. I even went into mongo db and deleted the messages but I still have the notifications.

Similar to #5481 #2480

**Comment by localguru** [comment]
Rocket.Chat Version: 0.52.0

Same here, after playing around with livechat

**Comment by adamprice56** [comment]
Any updates on this? I've just been getting a livechat set up for testing, We can't have all the chats piling up in the sidebar!

**Comment by sampaiodiego** [comment]
closing this in favor of #5481
