### ISSUE TITLE
post-readonly permission doesn't seem to work for anyone but an admin

### ISSUE THREAD

**Issue by thehutman** [RocketChat/Rocket.Chat#6302]
Rocket.Chat Version: 0.53
Running Instances: 1
DB Replicaset OpLog: no
Node Version: v4.7.3

We have a need for a few read-only channels that a lot of people are members of, but only a few can write to.  However, it appears the only user that is allowed to post messages to the channel is an Admin.  Moderators and owners with the post-readonly permission do not have rights to post.

Anyone with "post-readonly" should be allowed to post into a read-only channel.

**Comment by thehutman** [comment]
Ok, found a way around it for now.  A bit confusing, might be related to how its implemented.  It appears that when read-only is enabled, users are muted by default.  You can UNMUTE a user in the channel, which then gives them the ability to write into the channel.

If you toggle the read-only status, then the user is re-muted.

Seems non-intuitive, but at least we can work around it.

**Comment by hughlroberts** [comment]
Yeah, having this issue too. Would love if it was fixed, it's a bit annoying 👍

**Comment by hughlroberts** [comment]
Having a similar issue with "Allowing Reactions" in read-only channels. I used the un-mute option but really need to allow my muted users to react in the private group.

**Comment by PhABC** [comment]
Any update on this? Bit annoying indeed!

**Comment by timkinnane** [comment]
Duplicates #4769 - I have a fix for this and will submit PR next week.

**Comment by engelgabriel** [comment]
closed in favor of older issue  #4769
