### ISSUE TITLE
Automatically remove channels when owner deletes his account

### ISSUE THREAD

**Issue by kristinahaendel** [RocketChat/Rocket.Chat#6303]
Rocket.Chat Version: 4.4.0-31-generic
Running Instances: 1
DB Replicaset OpLog:
Node Version:4.7.3

How can I automatically remove a channel when owner deletes his account?
We are just testing the system and when users leave the system, their channels stay there orphanned and only admin can delete these channels.

**Comment by DalePayman** [comment]
+1
Or Archive them - respectively send the content via Mail to the Chat-Admin

**Comment by pizzarabe** [comment]
If somebody got the time, I bet you can write a simple python script to do that.

https://rocket.chat/docs/developer-guides/rest-api/groups/list
https://rocket.chat/docs/developer-guides/rest-api/groups/archive
https://rocket.chat/docs/developer-guides/rest-api/groups/close

**Comment by Dracozny** [comment]
Suggestion: delete channel if it's empty. Some channels may be popular and should be given the chance to be given new ownership.

**Comment by kristinahaendel** [comment]
But in private channels, when owner has left the system, nobody of the other users is able to take over the ownership I think? Not used channels on our system are deleted automatically anyway.

**Comment by Dracozny** [comment]
Private channels should still be able to be taken over by other users on an account deletion event IMO.

**Comment by kristinahaendel** [comment]
We just tested it. when owner leaves the system, no other user in private room is able to take ownership.

**Comment by Dracozny** [comment]
@kristinahaendel I'm not saying that that's how it works currently. I'm suggesting that's how it should be implemented.

**Comment by kristinahaendel** [comment]
OK, missunderstanding. We all would like the same improvement :-)

**Comment by Nemra1** [comment]
+1
nice idea

**Comment by graywolf336** [comment]
We welcome a pull request to add the things mentioned. :+1:

**Comment by SeanPackham** [comment]
On consideration, not deleting the channels is the behaviour we want. It is up to other owners and admins to remove it but we wouldn't want users to lose their conversations.
