### ISSUE TITLE
Allow emoji in channel topic

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#6305]
Rocket.Chat Version: 0.53.0

When setting a topic to `:thumbsup:` it should convert it into emoji, rather that just showing `:thumbsup:` in the channel topic.

**Comment by jszaszvari** [comment]
This would be awesome. 

+1

**Comment by amelieq-c** [comment]
+1 approuved

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@alexbraizer can i work on this

**Comment by alexbrazier** [comment]
@RAJAGOPALAN-GANGADHARAN yes, go for it. I currently don't have plans to work on it.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@alexbrazier lemme understand the codebase rocket chat is pretty amazing
and try to implement it. You might have to help me in this process as i am a beginner thank you 😄

**Comment by alexbartsch** [comment]
@sampaiodiego Duplicate of #12696. See also pull request #12858.

**Comment by sampaiodiego** [comment]
thanks @alexbartsch .. I'll actually close the other one, as this is older.

**Comment by alexbartsch** [comment]
thanks @sampaiodiego. But what happens with the open pull request for the older issue? It will also fix this issue. How can we link it? https://github.com/RocketChat/Rocket.Chat/pull/12858

**Comment by sampaiodiego** [comment]
saw you update the comment referencing this issue @alexbartsch .. so everything is fine =)
