### ISSUE TITLE
SAML configuration questions. Missing documentation.

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6306]
Rocket.Chat Version: 0.52.0

Hi,

I'm trying to get SAML authentication working with our University's shibboleth. I'm not sure about the meaning of some fields in Rocket.Chat SAML configuration and can't find any documentation. Could someone explain the fields to me in a few words please. If I get it working I'll write it down for documentation on https://rocket.chat/docs/administrator-guides/authentication/saml/

- Custom Provider: ?

- Custom Entry Point: ?

- IDP SLO Redirect URL: ?

- Custom Issuer: https://rc.mydomain.de/_saml/metadata/provider-name ?

- Custom Certificate: which certificate is this?

- Public cert contents:  is this the public cert of the domain my RC is running on?

- Private key contents: is this the private SSL key of the domain my RC is running on?

Thanks for helping.

Ciao
Marcus

**Comment by Rohlik** [comment]
Some info about SAML - https://github.com/RocketChat/Rocket.Chat.Docs/pull/232

**Comment by Rohlik** [comment]
@MartinSchoeler I think we can close this, because we already have SAML docs - https://rocket.chat/docs/administrator-guides/authentication/saml
