### ISSUE TITLE
SMTP not sending mail nor returning error

### ISSUE THREAD

**Issue by Julianoe** [RocketChat/Rocket.Chat#6312]
Although I tried to read all the SMTP configuration linked issues here i face always the same problem : when i test my mail sending in Administration, it works well and returns "mail sent", but i never receive the test mail and also i can't figure any error linked to mails in the logs. 
I tried rebooting the server etc but it's always the same problem.

What should be my course of action to at least know where the problem is coming from?

Thanks in advance!

Rocket.Chat Version: 0.53
Running Instances: 1
DB Replicaset OpLog: Disabled (?)
Node Version: v4.7.3

**Comment by santhosh9** [comment]
Same issue for me too. +1

**Comment by geekgonecrazy** [comment]
Please feel free to reach out via our [forum](https://forums.rocket.chat) or our [community server](https://open.rocket.chat) to discuss.

Going to close due inactivity
