### ISSUE TITLE
Getting Syntax errors while IPhone built of Rocket chat project using xcode 

### ISSUE THREAD

**Issue by rajitgarg2** [RocketChat/Rocket.Chat#6313]
Hello, 

I am using Rocket Chat project and trying to build its Iphone app on my mac mini version 10.11.5 (15F34) with Xcode Version 7.3.1 (7D1014), but my build is failing and giving me Syntax errors. I have attached the screenshots as below:-

![image](https://cloud.githubusercontent.com/assets/19546825/23792030/56f37d80-05ab-11e7-8b28-1673422c5190.png)

![image](https://cloud.githubusercontent.com/assets/19546825/23792061/7431c3f2-05ab-11e7-8fa9-d06d224de94d.png)

![image](https://cloud.githubusercontent.com/assets/19546825/23792160/ceec19f0-05ab-11e7-8490-1d62343bee2c.png)

please help me to come out of this, Thanks a lot in advance...

Rocket.Chat Version: 0.53.0
Running Instances: 1
Node Version: v4.2.3

**Comment by jszaszvari** [comment]
You can post issues for the iOS version here: https://github.com/RocketChat/Rocket.Chat.iOS/issues

This issue tracker is for the server/backend/web version
