### ISSUE TITLE
Only logo/white screen is showing from Android app of Rocket chat project

### ISSUE THREAD

**Issue by rajitgarg2** [RocketChat/Rocket.Chat#6314]
Hello,

I am using Rocket Chat project and created android apk, but now when i am opening this app, it stucks at default meteor logo and nothing else show, if i go to back then only complete white screen is showing .I am using mac mini of version 10.11.5 (15F34) to generate apk.

please help me to come out of this, Thanks a lot in advance...

Rocket.Chat Version: 0.53.0
Running Instances: 1
Node Version: v4.2.3

**Comment by jszaszvari** [comment]
You can post issues for the Android project here: https://github.com/RocketChat/Rocket.Chat.Android/issues
