### ISSUE TITLE
SAML problems. Testing SAML with Shibboleth (testshib.org): Required NameID format not supported

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6317]
Rocket.Chat Version: 0.52.0

I'm trying to test RC with SAML and testshib.org. To understand the SAML config fields this was a big help:

https://github.com/RocketChat/Rocket.Chat.Docs/pull/232/files

My SAML Config looks like this:

Custom Provider: schoppa-rocketchat
Custom Entry Point: https://idp.testshib.org/idp/profile/SAML2/POST/SSO
IDP SLO Redirect URL: https://www.testshib.org/Shibboleth.sso/Logout
Custom Issuer: https://rocketchat.mydomain.de/_saml/metadata/schoppa-rocketchat
Custom Certificate: empty. I don't know what this field is for
Public cert contents: the cert of rocketchat.mydomain.de (pem format). It's not self signed, but issued by a trusted CA
Private key contents: the privat key of my rocketchat.mydomain.de domain (pem format)

Metadata calling URL https://rocketchat.mydomain.de/_saml/metadata/schoppa-rocketchat will created. I downloaded the metadata XML and uploaded them to testshib.org. Seems to be fine.

When trying to login via SAML a window pops up, but I get a timeout of my nginx proxy and are not forwarded to the IDPs entry point. RC logfile says:

[34mI20170310-15:02:46.170(1) Exception in callback of async function: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line   at Error (native)   at Sign.sign (crypto.js:279:26)   at SAML.signRequest (/var/www/Rocket.Chat/programs/server/packages/steffo_meteor-accounts-saml.js:485:16)   at /var/www/Rocket.Chat/programs/server/packages/steffo_meteor-accounts-saml.js:575:33   at DeflateRaw.onEnd (zlib.js:227:5)   at emitNone (events.js:72:20)   at DeflateRaw.emit (events.js:166:7)   at endReadableNT (_stream_readable.js:921:12)   at nextTickCallbackWith2Args (node.js:442:9)   at process._tickDomainCallback (node.js:397:17)  

Nginx Log:

2017/03/10 15:03:46 [error] 744#744: *6580 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 129.xxx.xxx.xxx, server: rocketchat.mydomain.de, request: "GET /_saml/authorize/schoppa-rocketchat/Q3HmmPiN4P3TrbBuW HTTP/2.0", upstream: "http://192.168.100.30:3000/_saml/authorize/schoppa-rocketchat/Q3HmmPiN4P3TrbBuW", host: "rocketchat.mydomain.de", referrer: "https://rocketchat.mydomain.de/"

Same error when calling the URL directly, so I don't think something is wrong with my nginx config:

http://192.168.100.30:3000/_saml/authorize/schoppa-rocketchat/Q3HmmPiN4P3TrbBuW

Any ideas?

Ciao!
Marcus

**Comment by localguru** [comment]
Hi,

I did post cert and key without leading and ending to the fields "Public cert contents" and "Private key contents":

-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----

Authentication with testshib.org is still not working, but this timeout error is gone.

Could be mentioned in https://github.com/RocketChat/Rocket.Chat.Docs/pull/232

Anyone ever tested RC with testshib.org successfully?

Ciao!
Marcus

**Comment by localguru** [comment]
I did some search on the "Get a "Error Message: Error decoding authentication request message" error.

The debug log at testshib.org says:

10:53:39.552 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.SSOProfileHandler:366] - Decoding message with decoder binding 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
10:53:39.552 - WARN [edu.internet2.middleware.shibboleth.idp.profile.saml2.SSOProfileHandler:400] - Error decoding authentication request message
org.opensaml.ws.message.decoder.MessageDecodingException: This message decoder only supports the HTTP POST method

Seems that RC uses GET and testship.org only support POST request. So I changed the SAML "Custom Entry Point" from

  https://idp.testshib.org/idp/profile/SAML2/SSO

to

  https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO

Now I can see the "TestShib Identity Provider Login" page, which offers username and password login. :)

nginx log:
129.xx.xx.xx - - [10/Mar/2017:17:32:20 +0100] "GET /_saml/authorize/schoppa-rocketchat/AFEJm8xLYJLqotHSE HTTP/2.0" 302 1105 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0" 

Happily trying to login in with one of the testshib.org test accounts, my Rocket.Chat gives the following error:

"Sorry, an annoying error occured
Error: Unable to validate response url: Error: Missing SAML assertion
Close Window"

nginx log:
129.xx.xx.xx - - [10/Mar/2017:17:49:00 +0100] "POST /_saml/validate/schoppa-rocketchat HTTP/2.0" 200 400 "https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36" "-"

RC logfile doesn't show any errors. Now I'm lost ...

Ciao
Marcus

**Comment by localguru** [comment]
Hi,

got some feedback on the shib user mailinglist on this issue:

_"As the error said, your IDP does not support the requested NameID format. (A Shib IDP does not support email-based NameIDs out of the box, hence Tstshib doesn't either. Whether it's a good idea to adapt your own IDP is questionable and depends whether you get the application to use something else to uniquely identify the subject.)"_

Any chance to change that on RC side?

Ciao
Marcus

**Comment by avoidik** [comment]
@localguru did you find any workaround for this issue?

**Comment by alscheuring** [comment]
@localguru also interested in this. Any news?

**Comment by gdamaskos86** [comment]
Has anybody managed to get Rocketchat authenticating with SAML through testshib.org ?
It should be made clear if this is an unsupported feature.
When I try, after I get a metadata file from rocketchat, testshib on upload says: "The file you are attempting to upload is not valid metadata. Please correct any errors and try again."
