### ISSUE TITLE
sudo rocketchat-server.initcaddy doesn't work (Nextcloud Box)

### ISSUE THREAD

**Issue by Seferi** [RocketChat/Rocket.Chat#6318]
Hi, I just installed rocket.chat on my nextcloud box and i'm trying to enable ssl  as described on this page: 
https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl

and getting command not found error: sudo: rocketchat-server.initcaddy: command not found

I appreciate if someone could help. Thanks.

Rocket.Chat Version: 0.39.0
Running Instances: 1
DB Replicaset OpLog:
Node Version:v0.10.45

**Comment by geekgonecrazy** [comment]
@Seferi can you try `snap run rocketchat-server.initcaddy` ?

**Comment by Seferi** [comment]
@geekgonecrazy getting this error: error: cannot find app "initcaddy" in "rocketchat-server"

**Comment by geekgonecrazy** [comment]
I apologize I didn't read the version number. Caddy is not in the 0.39.0 snap.  I think our raspberry pi snaps are a bit behind currently.  I'll take a look at this.

**Comment by geekgonecrazy** [comment]
Going to close this please refer to: #5178 where we will track this

**Comment by Seferi** [comment]
Thanks  mmate
