### ISSUE TITLE
Windows installer for server

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#632]
More and more requests coming into our demo server - from non developers - for a way to install the server on a Windows PC or Mac.

Although not the 'recommended' way to install Rocket.Chat server, Meteor now fully supports Windows and an installer opens up many more users to Rocket.Chat.  

For some use cases, it might be all that is needed for a small chat instance - an old PC lying round doing nothing.

http://www.jrsoftware.org/isinfo.php

http://www.wampserver.com/en/
##

**Comment by graywolf336** [comment]
I have a windows server 2012 virtual machine I can run this on. Will need to do some research on how to do this.

**Comment by viperscape** [comment]
I started this task, [here are some preliminary steps](https://github.com/RocketChat/Rocket.Chat/wiki/Windows-Deployment)

**Comment by leram84** [comment]
Has there been any progress on this? I really want to get mattermost or rocketchat running on a win10 homelab, but can't find any support other than a couple 1 year old threads in both projects asking for windows support.

**Comment by engelgabriel** [comment]
@rodrigok can we use https://ci.appveyor.com/project/RocketChat/rocket-chat for this?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Windows is not currently among our supported platforms for installation.  This might change in the future.  We have a few community contributors working to make it work.  But its not currently among our supported set.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
