### ISSUE TITLE
Previews doesn't work for (custom) S3

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6322]
Rocket.Chat Version: 0.53.0

**Scenario:** somebody uploads a photograph, doesn't matter what extension, but let's say it is a `PNG`, and the preview isn't available until the message has been edited. I discovered this the other day but didn't think much of it because I was just so tired and didn't pay much attention.
However, now that I tested it again I had to report it even though it is an incredibly minor issue. I am hosting my own S3 instance on a dedicated server and everything works fine -- everything except previews. I tried to upload another `PNG` (or whichever you like, it really doesn't matter) and reloaded the browser. Still no dice. It only shows the preview after I make a edit, adding some ‘message/text’.

Can somebody else running Rocket.Chat with S3 enabled uploads confirm this behaviour, preferably people/organisations running self-hosted S3?

Thanks in advance.

**Comment by TheReal1604** [comment]
@k0nsl i run a minio docker container on a vps and this works like a charm with my rocket.chat setup. No preview issues.
