### ISSUE TITLE
what is the website end-point for realtime communication?

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#6323]
You have provided websocket enpoint as demo.rocket.chat in realtime API docs. But it doesn't seem to be working. Which end-point should I use for communication?

**Comment by ZhaoVitapublic** [comment]
I'm also looking for this information. I have found a url dummy.url/websocket to establish the socket connection via a java-client. But i can not do the authentication for it. Could someone help me on that?

**Comment by arcanjoqt** [comment]
@sacOO7 @ZhaoVitapublic could you try this one wss://demo.rocket.chat/websocket

**Comment by sacOO7** [comment]
Thanks @arcanjoqt
