### ISSUE TITLE
List of all RocketChat community rooms on the rocketchat.com landing page

### ISSUE THREAD

**Issue by uvatbc** [RocketChat/Rocket.Chat#6324]
There's no easy way to know about RocketChat rooms that are open to the community.
If a community allows it, can you please put its information into a list that is on your main landing page?

This will be a great way for new users to use RocketChat without having to set up their own servers or communities.

Please?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

It has been agreed upon, that this is something the admin can do in the `/home` page.

A list of all channels accessible to the current user will be incorporated soon, for that see: #9573

Cheers
Thomas
