### ISSUE TITLE
Livechat users can access Homepage

### ISSUE THREAD

**Issue by Szomy** [RocketChat/Rocket.Chat#6327]
While I'm testing the livechat feature (which is very useful btw) I use **incognito mode** (so I'm not logged in with my administrator user). 

After I send the first message from my website to the livechat I can access my chat homepage by going to **chat.mycompany.com**

_Is it the proper working?_ 
If it is then it would be great if I could turn this off on the administration page because I dont want to allow guest users read my homepage body.

Rocket.Chat Version:  0.51.0

Thanks.

**Comment by Szomy** [comment]
Any update on this?

**Comment by janrudolph** [comment]
@Szomy I added a issue recently which might be same as yours, is it https://github.com/RocketChat/Rocket.Chat/issues/7725 ??

**Comment by MartinSchoeler** [comment]
Giving preference to #7725 since it has more info
