### ISSUE TITLE
Mac OSX installer for server 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#633]
More and more requests coming into our demo server - from non developers - for a way to install the server on a Windows PC or Mac.

Although not the 'recommended' way to install Rocket.Chat server; for some use cases, it might be all that is needed for a small chat instance - an old Mac/Mac-Mini lying around doing nothing.
##

**Comment by rjayako** [comment]
+1 @Sing-Li were you able to install this on your mac mini? I'm in a similar situation and wondering if anyone has a doc they can share?

**Comment by Sing-Li** [comment]
Unfortunately, not for a mac mini :disappointed:      But yes on [Raspberry Pi](https://github.com/RocketChat/Rocket.Chat.RaspberryPi) !  - Run more users and save on energy cost :grinning:

**Comment by Marekai** [comment]
Great idea, lot of folks use their Macs for Web-Devs and similar, it would be handy to have its own rocket.chat server on it. Are there any news about the  installer?

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  OSX is not currently among our supported platforms for installation.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,

**Comment by lkraider** [comment]
Just wanted to add, we are running on macOS hosts using docker with good results.
