### ISSUE TITLE
Add channels open in columns (tweetdeck)

### ISSUE THREAD

**Issue by duckqu** [RocketChat/Rocket.Chat#6331]
![chatchatchat](https://cloud.githubusercontent.com/assets/26363626/23833973/56e8f2d8-075f-11e7-8c05-f5604df3f346.PNG)

Customisable columns
Rocket.Chat Version: 0.53.0

**Comment by Nemra1** [comment]
what is the point or wher u want to add this !  can you explain

**Comment by Nemra1** [comment]
+1
I love it😊

**Comment by sampaiodiego** [comment]
sorry guys but we don't plan to have that..
