### ISSUE TITLE
what i miss in setup 0.52.0 developer

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6332]
Rocket.Chat Version:  0.52.0
Running Instances: 1
DB Replicaset OpLog:
Node Version:
i want to setup V 0.52.0 but i see this error
OS : WIN 8.1 64X
METEOR@1.4.2.6

![2017-03-13_002139](https://cloud.githubusercontent.com/assets/22897987/23836590/6aa9d66a-0783-11e7-8a28-e2de2a7fc8f4.png)

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
