### ISSUE TITLE
Disable File Upload Access in Permissions

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#6333]
I'd love to have a permission which controls the ability to display/edit File Upload settings in RC - limiting access per role; so I could have a certain admin level/role which can't change the file upload settings once they've been set by a super admin.

Any way to do this currently?

q./

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
