### ISSUE TITLE
UI Bug when archiving channel

### ISSUE THREAD

**Issue by thursdaybw** [RocketChat/Rocket.Chat#6334]
Rocket.Chat Version: 0.5.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.0

Toggle changes when click archive. Confirmation box pops up. Click cancel. Toggle remains changed.
(has it really changed??).

Wish I could upload videos here so I could show you.

**Comment by ggazzo** [comment]
![fix](https://cloud.githubusercontent.com/assets/5263975/23857310/9ce141ba-07db-11e7-8092-0c42d18b9c0c.gif)
