### ISSUE TITLE
[Q] How to access to models from outgoing webhook integration?

### ISSUE THREAD

**Issue by green-ghost** [RocketChat/Rocket.Chat#6336]
```
class Script {
  prepare_outgoing_request({ request }) {
    console.log(Messages.findOneByid(msgId)); //Messages is not defined
    console.log(RocketChat.models); //RocketChat is not defined
}}
```

In this case I want to find message and author of this message from outgoing request, but I can't access to models.

**Comment by graywolf336** [comment]
If you're just trying to figure out the owner, the message object contains a `u` property that contains the user's id and username.

**Comment by green-ghost** [comment]
Thanks, but what about another message?
I tying to integrate Rocket Chat with some services with fast replying. Incoming message (comes with incoming webhook) contains some properties like id of owner, link to owner in foreign service, etc. If I replying to this message in channel, data about this message contains only link to original message. From this link I can take message id. And now I want to find other properties for send correct request to foreign service.

**Comment by graywolf336** [comment]
Just submitted a pull request to allow this. :+1:
