### ISSUE TITLE
Integrations with scripts do not work in sandstorm

### ISSUE THREAD

**Issue by faburem** [RocketChat/Rocket.Chat#6339]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.4.7

When I create a new Integration and activate any script (doesn't matter if it's an incoming or outgoing webhook), I get the following error:
`EROFS: read-only file system, mkdir '/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/.babel-cache'`

<img width="1152" alt="screen shot 2017-03-13 at 11 16 23" src="https://cloud.githubusercontent.com/assets/11456790/23850254/ef112b00-07de-11e7-9f42-eed54979ed34.png">

**Comment by graywolf336** [comment]
You'll need to somehow launch Rocket.Chat with a new environmental variable: `BABEL_CACHE_DIR=/tmp` and change the directory to one that Rocket.Chat can write to in sandstorm.

**Comment by faburem** [comment]
Can you please re-open this issue? This is nothing an end-user can fix inside sandstorm, instead this has to be fixed in Rocket Chat's capnp file.

[https://github.com/RocketChat/Rocket.Chat/blob/develop/.sandstorm/sandstorm-pkgdef.capnp#L111](https://github.com/RocketChat/Rocket.Chat/blob/develop/.sandstorm/sandstorm-pkgdef.capnp#L111)

I think you pointed in the correct direction, for sandstorm environments there should be a new key like so:
(key = "BABEL_CACHE_DIR", value = "/var/babel_cache")

Can anybody confirm this?

**Comment by graywolf336** [comment]
Feel free to open a pull request then. :+1:

**Comment by MatheusRV** [comment]
sorry i dont know with here is the best place but i'm using sandstorm and want to know how to integrate external-acess and facebook integrations i already find the repo.

**Comment by Niptide** [comment]
Just ran into the same error today. Great to see there is already a fix in 0.54.0! Sadly the latest Rocket.Chat version available for Sandstorm is still at 0.53.0 from "**Last update: February 22, 2017**'". 

Is there any update planned?

**Comment by Niptide** [comment]
Found a temporary solution:

1. Get the ID of the Rocket.Chat app (not grain!):
In your Sandstorm webapplication navigate to the apps view, f.e. "https://sandstorm.local/apps".
Copy the URL to Rocket.Chat and notice the last parameter:
https://sandstorm.local/apps/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0

2. Search Sandstorm's apps directory for the above parameter to get the appid:
`sudo grep -Rl "vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0" /opt/sandstorm/var/sandstorm/apps`
You should get 2 results like:
`/opt/sandstorm/var/sandstorm/apps/5198a2ec87bcc4b29e787b77079ba590/sandstorm-manifest`
`/opt/sandstorm/var/sandstorm/apps/5198a2ec87bcc4b29e787b77079ba590.appid`
Ignore the error messages "No such file or directory".
In this example the '5198a2ec87bcc4b29e787b77079ba590' is the directory where Rocket.Chat is stored.

3. Simply create the folder, Sandstorm or Rocket.Chat are not able to create:
`sudo mkdir /opt/sandstorm/var/sandstorm/apps/5198a2ec87bcc4b29e787b77079ba590/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/.babel-cache`
*(obviously replace the app directory with the ID you got in step 2)*

That's it!

Still looking forward to see any updates of the awesome Rocket.Chat app for sandstorm. Getting afraid you are giving up sandstorm support.
