### ISSUE TITLE
Profile picture created in cordova app is wrong rotated

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6344]
Rocket.Chat Version: 0.51.0
Running Instances: 3
DB Replicaset OpLog: YES

Hi,

if i update my profile photo with the cordova app und make a picture in the app, it is wrong rotated.

**Comment by karlprieb** [comment]
Hi @TheReal1604 I can't reproduce this bug on android. Have you tried on both android and iOS?

**Comment by TheReal1604** [comment]
Hi Karl,

just tested it on iOS.

Am 13.03.2017 um 18:35 schrieb Karl Prieb <notifications@github.com<mailto:notifications@github.com>>:


Hi @TheReal1604<https://github.com/TheReal1604> I can't reproduce this bug on android. Have you tried on both android and iOS?

-

**Comment by TheReal1604** [comment]
@karlprieb i verified it again.. its happening on iOS.

**Comment by TheReal1604** [comment]
Closing this, cordova is deprecated.
