### ISSUE TITLE
unable to access one of the room

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6345]
I have one of the private rooms, that i can't seem to access, session eventually times out.. 
I havent tested all rooms, but they seems to work.. 

Rocket.Chat Version: 0.53.0
Running Instances: 
DB Replicaset OpLog:
Node Version: v4.7.3

**Comment by IQ2022** [comment]
it was fine with 0.52.0... any idea?? why would one room get to be unavailable?

**Comment by IQ2022** [comment]
i had to delete the room, browser was hanging..

**Comment by MartinSchoeler** [comment]
Probably related to https://github.com/RocketChat/Rocket.Chat/issues/6814 and that was already fixed. If you experience this again please reopen this. Thanks!
