### ISSUE TITLE
where to delete old livechat conversation

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6346]
Rocket.Chat Version: 0.52.0

Just played around with livechat, but I can't find a way to delete closed livechat conversations as admin nor as live chat manager.

**Comment by FibreFoX** [comment]
This might be a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/6294

> It would be incredibly useful if we could delete all livechats or delete some of them.

**Comment by sampaiodiego** [comment]
closing this in favor of #5481

**Comment by GetGeeks** [comment]
still looking for this feature .... is there progress on this?
