### ISSUE TITLE
counter of unread messages doesn't seem to work anymore

### ISSUE THREAD

**Issue by virtuman** [RocketChat/Rocket.Chat#6348]
Counter of unread messages doesn't seem to work anymore on neither the room name or on the icon of the application on desktop and mobile apps. 
Used to work up until an update starting a few versions ago.

Is there a setting for it or has this functionality been removed?

Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: yes
Node Version: 4.7.3

**Comment by PotHix** [comment]
I can confirm that. The workaround for us is restarting the application.
```
Rocket.Chat Version: 0.53.0
Running Instances: 3
DB Replicaset OpLog: yes
Node Version: 4.7.3
```

Running with Docker and streamcast.

**Comment by Hudell** [comment]
Has anybody had this problem recently? I have not seen it happen yet.

**Comment by MartinSchoeler** [comment]
I could not reproduce this Bug on the version 0.71.0. Also closing this issue due lack of response. If the issue occurs on the latest version. Please open a new issue with updated details. Thanks!
