### ISSUE TITLE
Unable to connect because of excessive load 

### ISSUE THREAD

**Issue by axeloz** [RocketChat/Rocket.Chat#6349]
- Rocket.Chat Version: 0.53 installed using Snaps
- Running Instances: 1
- Node Version: 4.2.6
- System: Ubuntu 16.04

Hello, 
My Rocket.chat instance is installed on a dedicated DigitalOcean server using Snaps (nothing else running on the server). There are 20 users connected at most. This is a private chat, no public link nor contribution.

It used to work just fine for weeks until last friday: all clients went down (web and apps). I checked the graphs, the server was clearly overloaded. Reboot did the trick. 

Today again. Load is 20 on the server. Reboot fixed it for a while but couple of minutes later, it went bad again. 

Any idea why?
Thanks

![capture d ecran 2017-03-13 a 17 35 02](https://cloud.githubusercontent.com/assets/1597611/23865031/990e814a-0814-11e7-8a21-d9feaea2db89.png)

<img width="470" alt="capture d ecran 2017-03-13 a 17 37 09" src="https://cloud.githubusercontent.com/assets/1597611/23865040/9f415466-0814-11e7-8504-7b6257a249f7.png">

**Comment by axeloz** [comment]
Some log:

```
root@chat:/snap/rocketchat-server# systemctl status snap.rocketchat-server.rocketchat-server.service
● snap.rocketchat-server.rocketchat-server.service - Service for snap application rocketchat-server.rocketchat-server
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-03-13 17:29:06 CET; 19min ago
 Main PID: 1553 (node)
    Tasks: 12
   Memory: 718.8M
      CPU: 3min 36.667s
   CGroup: /system.slice/snap.rocketchat-server.rocketchat-server.service
           ├─1553 node /snap/rocketchat-server/528/main.js
           ├─2026 gm identify -ping -verbose -
           └─2027 gm convert - -

Mar 13 17:29:56 chat snap[1553]: ➔ |  Rocket.Chat Version: 0.53.0                |
Mar 13 17:29:56 chat snap[1553]: ➔ |       NodeJS Version: 4.7.3 - x64           |
Mar 13 17:29:56 chat snap[1553]: ➔ |             Platform: linux                 |
Mar 13 17:29:56 chat snap[1553]: ➔ |         Process Port: 3000                  |
Mar 13 17:29:56 chat snap[1553]: ➔ |             Site URL: https://chat.xxxx.io  |
Mar 13 17:29:56 chat snap[1553]: ➔ |     ReplicaSet OpLog: Disabled              |
Mar 13 17:29:56 chat snap[1553]: ➔ |          Commit Hash: cbdc26ded8            |
Mar 13 17:29:56 chat snap[1553]: ➔ |        Commit Branch: HEAD                  |
Mar 13 17:29:56 chat snap[1553]: ➔ |                                             |
Mar 13 17:29:56 chat snap[1553]: ➔ +---------------------------------------------+
```

**Comment by IQ2022** [comment]
btw can you go back to 0.52.0, i wasnt able to load it when i went back .. i noticed its bit heavier as well

**Comment by DalePayman** [comment]
show yout htop in tree view please.

**Comment by axeloz** [comment]
OK, I must wait for this to happen again.

**Comment by MartinSchoeler** [comment]
@axeloz  Closing this due lack of updates. If you experience this again, please reopen this with updated details.Thanks!
