### ISSUE TITLE
Disable GridFS and Filesystem from File Upload

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#6350]
In order to avoid running into server caps I want to disable the display of Filesystem and GridFS as storage options for customers - without editing the theme or forking the codebase I'd love to see a simple admin permission to override the default (or hide File Upload from the left-sidebar)

Thoughts?

q./

**Comment by graywolf336** [comment]
We accept pull requests, so if you come up with a solution let us know via a pull request so then it can be discussed. :+1:

**Comment by louisemessage** [comment]
Closing this issue as there hasn't been activity on it for over a year. Feel free to create a PR if you start work on it!
