### ISSUE TITLE
Cannot view a channel that you're not in

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#6355]
If you try to view a channel that you're not in an error is thrown:

```
Cannot read property 'autoTranslateLanguage' of undefined
```
Followed by a series of these:

```
Exception in queued task: TypeError: Cannot read property '2' of null
Exception in queued task: TypeError: Cannot read property '1' of null
```

Rocket.Chat Version: d61d2d5b89cfc9b294f7ebac71d668f5b8c5b105

**Comment by MartinSchoeler** [comment]
@marceloschmidt Any ideas?

**Comment by lucasvanhalst** [comment]
It's not fixed, just pulled master. Same issue.
