### ISSUE TITLE
ios push notification uses always badge:1

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#6356]
We are developing an QT5 based iOS 10/Android 4.4+/WinMobile10, client for RocketChat(which by the way will be released soon under GPLv3), 
and I am now facing the issue, that the iOS push notifications always contain badge:1, instead of sending the absolute number of unread messages.

**Comment by rasos** [comment]
BTW, here is the link to the QT5 based app, where you can download and test a preview version for Android: https://www.osalliance.com/en/ucom-app
