### ISSUE TITLE
Way to disable emoticons and use only ASCII

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#636]
It seems it is possible only to have fancy emoticons, but not ASCII ones.

**Comment by marceloschmidt** [comment]
You can remove the package to disable emojis by running `meteor remove rocketchat:emojione`

**Comment by mitar** [comment]
Hm, but that does not work with a Docker image?

**Comment by mitar** [comment]
I would have to build my own image. Couldn't this be per-user settings? Slack has it like that. A user preference:

> Emoji Style
> How do you like your emoji?

**Comment by engelgabriel** [comment]
@mitar has a point. Since the emoji is rendered on the client, I cannot see why we could not make it option per user too.
