### ISSUE TITLE
[Question] Create/Manage Users via Terminal

### ISSUE THREAD

**Issue by Manu-H** [RocketChat/Rocket.Chat#6362]
Hello! 
I would like to implement RocketChat into our team. I want to install it on an Linux Debian System. Is there any kind of possibilty to create Accounts through the Terminal (eg. with a Script, or an input to a mysql database)?

**Comment by localguru** [comment]
Hi,

did you check the ocket.Chat REST API

  https://rocket.chat/docs/developer-guides/rest-api/users/create

Ciao!

**Comment by Manu-H** [comment]
Thanks!
