### ISSUE TITLE
Must manually type ":" at end of @username in message field to alert user

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#6363]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

In previous versions of RocketChat (i.e. 0.32), if you typed @ and selected a user from the displayed list it would insert @username into the message as a highlighted entry/link to the user into the channel and alert that user. The same functionality exists in 0.52.0, but you have to manually add the a ":' to the end of the username in the message.  Is this an intentional change or a bug?

**Comment by JacksonWages** [comment]
I'm having this issue as well, but only on usernames that have a space in them.

Example: @Jackson Wages: would require the colon
@JacksonWages would not.

**Comment by ToniIltanen** [comment]
bump for this, our idp returnes the username in "firstname lastname" -format, and a username which has this format, is not highlighted nor notified when using @firstname lastname

**Comment by Hudell** [comment]
Regular mentions are working properly. Mentioning usernames with spaces is currently not supported.
