### ISSUE TITLE
Two Custom OAuth Parameters can't be set in UI after 0.32 to 0.52 upgrade

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#6364]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.1

We recently upgraded our system from RocketChat 0.32 to 0.52.  Because new fields were introduced to the Custom OAuth config from one version to the next, we had to delete and recreate our Custom OAuth configuration after upgrade.  The config updated fine in the DB, except for two fields, "Token Sent Via" and "Login Style".  Those two field's values in mongo remained, "payload" and "popup", respectively, no matter what did in the UI.  We ended up having to manually change the values in the DB:

use rocketchat
db.rocketchat_settings.update( { _id: "Accounts_OAuth_Custom-Geoaxis-token_sent_via" }, { $set: { value: "header" } } )
db.rocketchat_settings.update( { _id: "Accounts_OAuth_Custom-Geoaxis-login_style" }, { $set: { value: "redirect" } } )

We don't see the issue when configuring custom oauth on a clean install, only on an upgrade.

**Comment by geekgonecrazy** [comment]
This has been refactored a lot since.  No other reports, so closing
