### ISSUE TITLE
Customize Rocket chat app and create its Web App, Android app and IOS App

### ISSUE THREAD

**Issue by rajitgarg2** [RocketChat/Rocket.Chat#6365]
Hello,

I have require to customize Rocket chat app and create its Web App, Android app and IOS App, is it possible, I have first of all tried with https://github.com/RocketChat/Rocket.Chat and this works fine for web app, but when i follow the steps for creating its android apk using meteor build steps https://guide.meteor.com/mobile.html#building-for-production, i got app with only meteor logo, I also tried to create IOS app by follow meteor IOS build steps, then I got various syntax errors in this, https://i.stack.imgur.com/dggpt.png, can someone please help me how i can achieve this, I have read from various sources like 

https://github.com/RocketChat/Rocket.Chat.Cordova
https://github.com/RocketChat/Rocket.Chat.Android

but I feel customization is not possible using this

I also check the documentation https://rocket.chat/docs/ and https://rocket.chat/docs/developer-guides/mobile-apps, but it also not helps me in customization.

please help..

Thanks a lot

Rocket.Chat Version: "0.53.0"

**Comment by Nemra1** [comment]
i can help you with android but iphone ..im not expert

**Comment by divergefx** [comment]
@rasos I would love to have customized apps, how do we go about doing this?

**Comment by rajitgarg2** [comment]
Hi Nemra1@ Help me for android, i am waiting

**Comment by rasos** [comment]
@divergefx have you tested the Qt5 based app and do you like it? We are glad to help to customize it, send me a PM via our web page mentioned above.

**Comment by Nemra1** [comment]
@rajitgarg2  come to skype odratop10@skype

**Comment by stuurgurs** [comment]
@rajitgarg2  did you have successes in you question? i have the same issue

**Comment by rajitgarg2** [comment]
No @stuurgurs , I have not found any solution and due to that i switched from this and leave this

**Comment by rasos** [comment]
@stuurgurs what exactly do you need for customization?

**Comment by RollingAgain** [comment]
Thanks for the sharing link, my web can use it

**Comment by kkumaresan** [comment]
Hi, we at Mongrov have developed a react-native mobile client library for Rocket.Chat. Please check this url: https://github.com/mongrov/roverz . Works both on iOS and Android. If you get a chance, do check this project for a comprehensive native mobile app using Rocket.Chat. We welcome your feedback 😃

**Comment by graywolf336** [comment]
@kkumaresan Please stop spamming the issues with the same message. :)

**Comment by kkumaresan** [comment]
@graywolf336 Sorry about that.. :)

**Comment by rasos** [comment]
@kkumaresan thanks for notifying here. Nice to see more mobile clients evolving. I will try to test roverz and give some feedback.

We also have been making good progress with a Qt5 based development supporting the RocketChat API, available as "fairchat" App for iOS and Android: https://git.fairkom.net/chat/fairchat Has a similar feature set including photo and video capturing. Lately we integrated into fairchat SAML login which allows easy provisioning in enterprises with single-sign-on. 

@rajitgarg2: to answer your original question of this issue: RocketChat itself offers rich customization for the web. For mobile use you would need to tweak one of the open source apps available. If you use the original RocketChat (non +) beta App all design customizations of the web version are also available on the app automatically.

**Comment by mkarimu** [comment]
Greetings all. Am new to programing and I have installed  Rocket Chat on my linux box. Everything seem to work well  however every time I sign up a new user account, they can view other account. Same xase with the android app. I would like each account to be seperate and not able to switch accounts. 

Any app with such features

**Comment by graywolf336** [comment]
I am going to close this issue. We used to offer consulting for customizing our product, however we have shifted our vision and are no longer offering this service. With that said, we have partners which will do that and you can find more information about that here: https://rocket.chat/partners

**Comment by UmairAhmed420** [comment]
@Nemra1  Hello can you help me also in rocketChat customization related to Android
