### ISSUE TITLE
No error page when connecting to wrong url https://[server_name]/[wrong_name]

### ISSUE THREAD

**Issue by jblobel** [RocketChat/Rocket.Chat#6366]
Rocket.Chat Version:  0.49.2
Running Instances: 1
DB Replicaset OpLog: 79
Node Version: 4.7.1

When connecting with a browser (Firefox 45 ESR) to an URL like https://[rocket_chat_server]/[random_name] user get no error report and is not redirected anywhere. He is connected but have no clue what to do.

Same thing happen in the demo server (see gif attached) : go to https://demo.rocket.chat/nothingthere and see by yourself.

![bugreport](https://cloud.githubusercontent.com/assets/6414633/23958625/fdae975e-09a2-11e7-84b3-f488f64c4aa3.gif)

User should be redirected to an error page, and see his sidebar so he would be able to join another room.

**Comment by Dracozny** [comment]
Or redirected to the main page. perhaps an Admin option of where to redirect 404 would be ideal.

**Comment by jblobel** [comment]
I guess it would be good to give user feedback, so he can aware of his error, and readjust his bookmark for example.
