### ISSUE TITLE
MongoError: failed to connect to server [localhost:27017] on first connect

### ISSUE THREAD

**Issue by dhavalpatelj** [RocketChat/Rocket.Chat#6369]
var express = require('express');
var app = express();

var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient
var dbOperation = null;

MongoClient.connect('mongodb://localhost:27017/training', function(err, db) {
  if (err) throw err
  dbOperation = db;
 })
app.use('/mahadev', express.static('src'));
app.get('/todo', function(req, res) {
  dbOperation.collection('todo').find().toArray(function (err, result){
    if (err) throw err
    res.send(result);
    console.log(result)
})
});
app.listen(3000, function() {
  console.log('Example app listening on port 3000!')
})

**Comment by Rohlik** [comment]
Totally useless issue...
How you deployment RC and mongodb?
Version of RC and mongodb?
Did you setup ENV for RC connect to DB?
And so on....

**Comment by dhavalpatelj** [comment]
solved
