### ISSUE TITLE
[QUESTION] Visibility permissions for groups.

### ISSUE THREAD

**Issue by rash-uk** [RocketChat/Rocket.Chat#6370]
Hello,
is it possible to implement: users from one group are forbidden to see users from other groups?
For example: 
creating groups for departments and that users of some departments will not see users of other departments and only administrators see all users.

**Comment by 1stposition-ad** [comment]
in addition to the above question, if there is a way to do that, is it also possible to hinder people from one group to write private message to another group?

**Comment by sampaiodiego** [comment]
this looks like a multi-tenancy feature that we don't plan to support.
