### ISSUE TITLE
[Improvement] Handling of auto-Links to Private channel/room links in mentions and their visibility

### ISSUE THREAD

**Issue by childnode** [RocketChat/Rocket.Chat#6375]
Rocket.Chat Version: 0.52

if you have or you're member of a private channel / room, you …
* … are able to write room/channel actions by using the autocomplete

But:
* Rocket.Chat doesn't auto-create a link to a given / posted private room / channel. The text `#private_chan` keeps a text, without a link to the room neither any special markup

It would be OK for me if this is the "desired" behaviour for non-members.
For members: it must and should be linked as like for public channels.

But if there is an exception for non-members, what about the case a user get's invited to a room after he received a message with the channel mentioned in.

So for me: non-members should see the link too. Perhaps (that would be the best I see) the link should be attended by a lock icon or marked red, or whatever fits into the UI/UX to make it visible that he is not able to join or is expected to get a permission error.

related issues #5831 , #3155

**Comment by marceloschmidt** [comment]
This has been fixed.
