### ISSUE TITLE
Feature request: LDAP -> add LDAPTLS_REQCERT option

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6376]
Rocket.Chat Version: 0.52.0

I had some problems with authentication using LDAP+SSL against an AD (eg. ad.company.com) which resolves via round robin to different single host names (dc1.ad.company.com etc.) and each host's certificate doesn't include the generic SubjectAlternativName for ad.company.com, but only for its single hostname, eg. dc1.ad.company.com etc.. The result is a certification mismatch. To my mind this is a misconfiguration of the certificates on each DC host, but if you can't change that (or convince the AD admin), it would be nice to have something like an LDAPTLS_REQCERT [1] option in RC LDAP config to set it e.g. to "never | allow | try | demand" instead of connecting to a dedicated DC host, which might go down/change. Default value should be "demand" (With a setting of demand the certificate is requested and a valid certificate must be provided, otherwise the session is immediately terminated [1] ).

Ciao
Marcus

[1] http://www.openldap.org/doc/admin21/tls.html

**Comment by sampaiodiego** [comment]
we accept a PR for this but we don't plan to add a support for it. thx
