### ISSUE TITLE
Confluence support

### ISSUE THREAD

**Issue by dennis-f** [RocketChat/Rocket.Chat#638]
I'd love to see Atlassin Confluence integration.
##

**Comment by nwsheppard** [comment]
+1

**Comment by Sing-Li** [comment]
@dennis-f ,   @nwsheppard  - There is no Confluence expertise in the current team.  Can you please see if any Confluence community members may be able to help out?     There is no need to understand the Rocket.Chat code, they just need to contribute  a 'hubot' adapter over in the [Rocket.Chat Chat Ops Edition](https://github.com/RocketChat/Rocket.Chat.Ops)  project.  Thanks.

**Comment by engelgabriel** [comment]
Depends on #2426

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by manuelbachl** [comment]
Gonna work on this after finishing BitBucket and JIRA integrations

**Comment by ericlevin** [comment]
Hey @manuelbachl .  Any update on this?

**Comment by relyd** [comment]
+1

**Comment by qk4l** [comment]
A I know Confluence Server does not support Webhooks. Only Confluence Cloud supports it.

**Comment by engelgabriel** [comment]
Please see https://github.com/RocketChat/Rocket.Chat.Docs/tree/master/5.%20Administrator%20Guides/Integrations for the current shared integrations.

**Comment by JukieWalsh** [comment]
What assistance could I give on the confluence side?

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App.  But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
