### ISSUE TITLE
Feature Request - use google/guetzli to compress pictures

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6381]
Hey, 

this is a feature request. Google delivered a very good performing compression algorithm to compress jpeg pictures. 

https://github.com/google/guetzli

Maybe this can be useful to compress pictures in rocket.chat?

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
