### ISSUE TITLE
SAML: how to validate further attributes?

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6382]
Rocket.Chat Version: 0.52.0

Beside NameID I'd like to validate further attributes like employee status (eduPersonScopedAffiliation) to handle access to RC. How would I do that? Do I need to hard code that to 
programs/server/packages/steffo_meteor-accounts-saml.js ?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
