### ISSUE TITLE
ios mobile apps unexpectedly closing.

### ISSUE THREAD

**Issue by roketsohbet** [RocketChat/Rocket.Chat#6388]
Hi All; im running version 0.53 on linux. I made the definition of ssl. I have access to the chat system with https://chat.mydomain.com sub domain. I can login from Android systems with Rocket.Chat+ Mobile app. Android perfect. But when i login to the server with RocketChat+ mobile app on iOS, the Mobile app is loaded and turned off. What do i have to do in this regard?

**Comment by rafaelks** [comment]
@roketsohbet 

- Can you send me some video/screenshot?
- The app closes or it just doesn't connect?
- Does your server support SSL (valid)?

**Comment by roketsohbet** [comment]
Hi @rafaelks , i sent u an email related to this  topic. Check ur rafaelks@me.com email .

**Comment by rafaelks** [comment]
@roketsohbet Sorry but I didn't receive anything... can you send here?

**Comment by roketsohbet** [comment]
Video: https://youtu.be/SFng9ITwLVg
Ssl ok: http://i63.tinypic.com/308f6g7.jpg

**Comment by rafaelks** [comment]
@roketsohbet Interesting! Can you invite me to your chat? My email is `rafael.kellermann at rocket.chat`. I believe the crash is happening in some message format that we currently don't support.

**Comment by roketsohbet** [comment]
I send u email Rafael

**Comment by rafaelks** [comment]
This crash is already fixed in our `develop` branch and will be on the next App Store update that we're submitting today (1.0.5).

Thank you @roketsohbet!
