### ISSUE TITLE
avatar picture can be accessed without any login

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6389]
Rocket.Chat Version: 0.52.0

The avatar picture can be accessed without any login:

  https://rc.domain.com/avatar/youruser

**Comment by MartinSchoeler** [comment]
Duplicate of #3480 and #3481

**Comment by localguru** [comment]
Why closed, if there is no solution? I think it's a security issue.

**Comment by jszaszvari** [comment]
As @MartinSchoeler pointed out, it's a duplicate issue with a pull request provided in https://github.com/RocketChat/Rocket.Chat/pull/3481 if you wish to fix it. 

Many external apps and integrations rely on being able to access the avatar, and until there is a mechanism to do that through OAuth it's probally not really a priority for the RC team.

**Comment by localguru** [comment]
@jszaszvari please reopen as this is a security issue and  #3481 has been closed to, so there is no open ticket to this issue.
