### ISSUE TITLE
MySQL/MariaDB support?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#639]
Would it be cumbersome to create support for MySQL/MariaDB and drop MongoDB, or at least have the option to use the former as a choice?

Why not MongoDB? Well, read the following brief run-down and it will make sense: http://cryto.net/~joepie91/blog/2015/07/19/why-you-should-never-ever-ever-use-mongodb/

Best wishes,
-k0nsl

**Comment by Sing-Li** [comment]
@k0nsl  Rocket.Chat is _not_ yet another three tiered web app.  Much of its performance, scalability and reliability is inherited from the Meteor platform upon which it is based.  In turn, Meteor is currently very tightly coupled to MongoDB (with Mongo's scaling and HA strategies) for its operation and realtime properties.   Meteor really needs to be backed by a modern _realtime_ database - but no popular options really exist yet.

Meteor currently has an experimental effort in accommodating legacy SQL databases, starting with PostgreSQL. We are working hard to track this effort, and attempt to make Rocket.Chat work with it.   But do not expect feature and performance parity with the current Rocket.Chat.  

There exists a research and development gap of three decades between relational databases and their modern realtime counterparts.

BTW... we're in no way pro-Mongo, and understand that Mongo is also not a realtime database.  Thanks for your comments.

**Comment by k0nsl** [comment]
Hello @Sing-Li, thanks for the reply. I didn't know there existed experimental legacy support for SQL. That's very interesting and something I'd be willing to experiment with.

Yes, well, I didn't think you were MongoDB fanboys :smirk:

I'm only interested in seeing how this project can improve, as it appears to be probably the best solution available at the moment.

Best wishes,
-k0nsl

**Comment by Sing-Li** [comment]
Hi @k0nsl, thank you for the constructive comments and kind words :smile: 

Our work-in-progress is actually on this branch:

https://github.com/RocketChat/Rocket.Chat/tree/postgresql

The information on how Meteor is attempting to bolt-on realtime features to PostgreSQL is here:

http://meteor-postgres.readthedocs.org/en/latest/

If you check out their [github repo](https://github.com/meteor/postgres-packages) , you will see that it is currently under _red hot_ development.

Any help in these efforts will be greatly appreciated :+1: 

Best regards,  
 -Sing

**Comment by engelgabriel** [comment]
I'll close this issues and reference it on https://github.com/RocketChat/Rocket.Chat/issues/533
