### ISSUE TITLE
How to translate the registration custom field

### ISSUE THREAD

**Issue by wayn** [RocketChat/Rocket.Chat#6390]
Here is my custom field, how can I translate the 'role', and the options

    {
        "role": {
	    "type": "select",
	    "defaultValue": "student",
	    "options": [
	        "teacher",
		"student"
	    ],
	    "required": true,
	    "modifyRecordField": {
	    "array": true,
	    "field": "roles"
	    }
        }
    }

**Comment by marceloschmidt** [comment]
AFAIK, you can't yet. We need to create translatable custom fields.

**Comment by mnlbox** [comment]
+1 I need this feature too.

**Comment by WizaXxX** [comment]
+1

**Comment by piotrkochan** [comment]
It should be done long ago. +1

**Comment by rodrigok** [comment]
@wayn the field (key) you are creating is already translated, if the key isn't part of our i18n database you can add it or override it via `Admin > General > Translations`.

I'll ask our docs team to add this information to the manual.

**Comment by piotrkochan** [comment]
I did it, it does not work.

**Comment by piotrkochan** [comment]
It work for displaying user profile, but keys are not translated in the profile form.

**Comment by rodrigok** [comment]
I just did a test @piotrkochan 

Added a role field
![image](https://user-images.githubusercontent.com/234261/48203546-eb557280-e34e-11e8-9fe4-ea4ae671daeb.png)

Added translation for role to `Role!` for english
![image](https://user-images.githubusercontent.com/234261/48203496-ce20a400-e34e-11e8-986e-04cb058b0db5.png)

And there is the field name translated
![image](https://user-images.githubusercontent.com/234261/48203517-daa4fc80-e34e-11e8-8b33-8a5f7623f760.png)
