### ISSUE TITLE
Add Groups to Channel?

### ISSUE THREAD

**Issue by Manu-H** [RocketChat/Rocket.Chat#6391]
Hello! Is there a way to add a Group to a Channel? I have differnt Groups (like Admins, Team, Sale) with differnt members. I want to add the group "Admin" to Channel "Admin". Is this possible?

**Comment by oliver-bowman** [comment]
I had to do it with hubot as I could not see any other way of doing it.

**Comment by Manu-H** [comment]
How did you do that with the bot?Am 20.03.2017 10:35 Vorm. schrieb Oliver Bowman <notifications@github.com>:I had to do it with hubot as I could not see any other way of doing it.

**Comment by oliver-bowman** [comment]
https://github.com/RocketChat/hubot-rocketchat And a script that places users into groups, places them as export variable.  The combination of two means that you can tag a group like this @platform and they will be dragged into the channel by the bot.

**Comment by Manu-H** [comment]
Thx
