### ISSUE TITLE
Deleted User Account Removes All Posts, Making Chat History Unreadable

### ISSUE THREAD

**Issue by Sentinelrv** [RocketChat/Rocket.Chat#6392]
Hi, we have an instance of RocketChat setup at https://peercoin.chat/

One of our users started up a new account in order to change their user name and deleted their old account name. This apparently had the effect of wiping all of the posts that were posted by the old account.

This was an active user and they had many conversations all over the chat in many channels. Now that all of their posts have been removed, our chat backlogs on various channels are pretty much unreadable and I can't follow simple conversations because it reads as if people are talking to themselves, when it reality they were previously talking to someone whos posts are no longer visible.

Is this an error or is it a normal function of the way the chat is setup? It has been very disruptive to our chat history. I believe deleting an account should remove that person's access to it, but it should not delete all of the user's posts. Deleting all of a user's posts should be left up to the admins in charge of the site. Users should only be able to delete or edit their posts within a limited time window after posting in order to help maintain the integrity of the chat and its history.

Is there anyway to reverse the damage that has been done here? Maybe the posts are still stored in the database, but are invisible? Thanks for any help!

**Comment by k0nsl** [comment]
The content is gone. This routine is the desired outcome when deleting accounts.

**Comment by Sentinelrv** [comment]
So does that mean there is no chance of an improvement changing this to be controlled only by site administrators? This has basically completely destroyed the readability of large sections of our chat. That can't be considered a positive outcome. If a user wants something personal deleted that they shouldn't have posted in the first place, I think it would make more sense for them to contact the admins of the site to have it deleted for them. What happened here is just way too damaging to be allowed. Many past discussions have now lost all context. I hope you'll reconsider.

**Comment by Sentinelrv** [comment]
And if no change, is there anyway for admins to manually disallow account deletion to prevent this from happening again?

**Comment by Sentinelrv** [comment]
I also have to mention that the person who deleted the account did not anticipate this as the outcome and was disappointed when he realized all of his posts were gone, so saying that this is the desired outcome is not true for everyone performing this action.

**Comment by localguru** [comment]
#6186

**Comment by Nemra1** [comment]
i hope to get any option to fix that too..big problem when u delet some one and all posts not deleting with him

**Comment by localguru** [comment]
@Sentinelrv: you can disable deleting accounts as admin: Settings -> Accounts -> Allow users to delete own account. Set it to false and an user can't delete his/her account. Instead of deleting I would deactivate accounts.

**Comment by billtt** [comment]
@Sentinelrv username and name can be changed by the user or admin.

**Comment by Sentinelrv** [comment]
Yes I know. I believe it was something the user did on his own.

Thank you @localguru. I have disabled account deletions until something is done about this.

**Comment by SeanPackham** [comment]
This is the expected behaviour. I'd suggest disabling account deleting and have an admin disable the account.
