### ISSUE TITLE
LDAP : no sync & error with openldap auth

### ISSUE THREAD

**Issue by YoShiiro** [RocketChat/Rocket.Chat#6393]
I got problem when i set LDAP to auth & synchronise user, i got strange errors & strange things, if someone can help me it would be create :).

> Debian Jessie up to date
> Rocket.Chat Version: 0.52.0 
> NodeJS Version: 4.5.0 - x64 
> Running instance : 1
> ReplicaSet OpLog: Disabled 
> Commit Branch: HEAD

On the rocket chat server if i test ldapsearch on the LDAP server (Not the same as the rocket chat server)
`ldapsearch -b dc=domain,dc=local -H ldap://10.0.1.2 -D cn=admin,dc=domain,dc=local -W "(&(objectClass=inetOrgPerson)(uid=*))"` This work and i got the user & all the list

I configure rocket chat like that : 

- Custom Domain Search : `{“filter”: “(&(objectClass=inetOrgPerson)(uid=*))”, “userDN”: “cn=admin,dc=domain,dc=local”, “password”: “MyPassword”}`
- Username Field : empty
- Unique Identifier Field : uidNumber
- User Data Field Map : `{"cn":"name", "mail":"email"}`
- Default Domain : `dc=domain,dc=local`
- Merge existing user : True
- Import LDAP users : True

When i click on "TEST CONNECTION" i got in the up right corner error img on imgur : [here](https://i.imgur.com/H1cO4Bc.png), but in log everything seems good: 

>- [34mI20170320-12:31:28.958(1) [34mMeteor ➔ method UserPresence:away -> userId: okasrpZu72sxQmsmD , arguments:  {} 
>- [34mI20170320-12:31:31.295(1) [34mMeteor ➔ method UserPresence:away -> userId: okasrpZu72sxQmsmD , arguments:  {} 
>- [34mI20170320-12:31:33.812(1) [34mMeteor ➔ method ldap_test_connection -> userId: okasrpZu72sxQmsmD , arguments:  {} 
>- [34mI20170320-12:31:33.816(1) [34mLDAP ➔ Connection.info Init setup 
>- [34mI20170320-12:31:33.817(1) [34mLDAP ➔ Connection.info Connecting ldap://10.0.1.2:389 
>- [34mI20170320-12:31:33.819(1) [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://10.0.1.2:389',   timeout: 600000,   connectTimeout: 600000,   idleTimeout: 600000,   reconnect: false } 
>- [34mI20170320-12:31:33.825(1) [34mLDAP ➔ Connection.info LDAP connected

If i test sync "SYNC USERS", i got no error says fine (image on imgur : [here](https://i.imgur.com/uxxT5tq.png)), and in the logs says good : 
>- [34mI20170320-12:45:32.984(1) [34mMeteor ➔ method ldap_sync_users -> userId: 7B5AaRCtbRSSgM8zD , arguments:  {} 
>- [34mI20170320-12:45:32.990(1) [34mLDAP ➔ Connection.info Init setup 
>- [34mI20170320-12:45:32.993(1) [34mLDAP ➔ Connection.info Connecting ldap://10.0.1.2:389 
>- [34mI20170320-12:45:32.994(1) [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://10.0.1.2:389',   timeout: 600000,   connectTimeout: 600000,   idleTimeout: 600000,   reconnect: false } 
>- [34mI20170320-12:45:33.000(1) [34mLDAP ➔ Connection.info LDAP connected 
>- [34mI20170320-12:45:33.001(1) [34mLDAP ➔ Connection.info Disconecting

And if never i put uid or sAMAccountName in Username Filed i got error when i sync "Internal error server"
>- [34mI20170320-12:53:17.650(1) [34mMeteor ➔ method ldap_sync_users -> userId: 7B5AaRCtbRSSgM8zD , arguments:  {} 
>- [34mI20170320-12:53:17.656(1) [34mLDAP ➔ Connection.info Init setup 
>- [34mI20170320-12:53:17.657(1) [34mLDAP ➔ Connection.info Connecting ldap://10.0.1.2:389 
>- [34mI20170320-12:53:17.658(1) [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://10.0.1.2:389',   timeout: 600000,   connectTimeout: 600000,   idleTimeout: 600000,   reconnect: false } 
>- [34mI20170320-12:53:17.670(1) [34mLDAP ➔ Connection.info LDAP connected 
>- [34mI20170320-12:53:17.673(1) rocketchat_ldap rocketchat_ldap.js:776 [31mLDAPSync ➔ error [Error: Invalid Custom Domain Search JSON] 
>- [34mI20170320-12:53:17.675(1) Exception while invoking method 'ldap_sync_users' Error: Invalid Custom Domain Search JSON   at LDAP.getDomainBindSearch (/home/user/public_html/rocketchat/programs/server/packages/rocketchat_ldap.js:207:12)   at LDAP.bindIfNecessary (/home/user/public_html/rocketchat/programs/server/packages/rocketchat_ldap.js:262:29)   at LDAP.searchUsersSync (/home/user/public_html/rocketchat/programs/server/packages/rocketchat_ldap.js:278:9)   at sync (/home/user/public_html/rocketchat/programs/server/packages/rocketchat_ldap.js:740:26)   at [object Object].ldap_sync_users (/home/user/public_html/rocketchat/programs/server/packages/rocketchat_ldap.js:1089:17)   at [object Object].methodsMap.(anonymous function) (/home/user/public_html/rocketchat/programs/server/packages/rocketchat_lib.js:1064:26)   at maybeAuditArgumentChecks (/home/user/public_html/rocketchat/programs/server/packages/ddp-server.js:2108:12)   at /home/user/public_html/rocketchat/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /home/user/public_html/rocketchat/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /home/user/public_html/rocketchat/programs/server/packages/ddp-server.js:1040:48   at Session.method (/home/user/public_html/rocketchat/programs/server/packages/ddp-server.js:1018:23)   at /home/user/public_html/rocketchat/programs/server/packages/ddp-server.js:880:89

**Comment by josean7link** [comment]
I having the same problems with the setup of the LDAP and the Rocketchat. need to update this post with me info later.
