### ISSUE TITLE
ldap configuration file

### ISSUE THREAD

**Issue by Avlessi** [RocketChat/Rocket.Chat#6396]
Hello!
Is it possible to configure ldap authentication using external configuration file?
In your documentation I've only seen a possibility of LDAP configuration using graphical interface. The context is that I need to have an automatized system of ldap authentication so that I didn't need to configure it manually every time rocket-chat is redeployed.

**Comment by localguru** [comment]
Hi,
you can change any configuration directly in mongodb, eg: 

db.rocketchat_settings.update({'_id':'LDAP_Login_Fallback'}, {$set: { 'value':true }})

or check REST API

https://rocket.chat/docs/developer-guides/rest-api/settings/update

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
