### ISSUE TITLE
ADMIN has the right to Turn ON and OFF Video Conference 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6397]
I like Jitsi, and i have enabled it in private rooms only, however i would like to have the ability to disable it from some rooms? alot of times users with read only join a room and they get to click on camera(jitsi), it would be good if we disable that? give admin more room controls..

Thank you

Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by IQ2022** [comment]
can we at least disable Jitsi From Selected rooms? like lets say its OFF default and only Admin or Room Owner can enable it? wither channels is public or Private?

**Comment by kenanscott** [comment]
+1 for this

**Comment by sampaiodiego** [comment]
that seems too specific. we don't plan to add that but we accept a PR. thx
