### ISSUE TITLE
International characters in usernames, rooms etc

### ISSUE THREAD

**Issue by mathiasfriman** [RocketChat/Rocket.Chat#640]
Hi,
I've just translated Rocket.Chat to swedish and it's an awesome system! However, neither rooms nor usernames can have swedish or international characters, like our åäöÅÄÖ which is common in our language. French characters like for example éÇË also aren't allowed. 

We mean to use this in a setting with perhaps as many as 5000 users. They are a rather conservative crowd and there is no way it will be possible to use if we can't have our character set for naming rooms and public channels.. I'm sure I'm not alone in this :)

Even if this for some reason will not be an upstream fix, where can I go about and change this in our own installation?

**Comment by sunnipaul** [comment]
Is there anyone willing to patch it ?

**Comment by brylie** [comment]
Please review my PR, allowing unicode characters in usernames. I followed [instructions on StackOverflow](http://stackoverflow.com/a/150078/1191545).

**Comment by fduraibi** [comment]
This can be done using regex from `Administration - General` under `UTF8` section. (you have to be an admin on the server to do that)
