### ISSUE TITLE
changing General Room to Private , doesnt stop new members from joining in

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6403]
I have changed my general room default to Private from channel,  however new registered users are still able to join that room?? is this by design?

thanks,

I

Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by TheReal1604** [comment]
Hi @IQ2022,

i think the "default" setting in your room is persisting:

![image](https://cloud.githubusercontent.com/assets/5877910/24137110/8c22bc36-0e12-11e7-8fb2-ab6b2f0efc9e.png)

Can you check that in your admin settings?

**Comment by graywolf336** [comment]
If you didn't set the `default` configuration setting on the room to false as TheReal mentioned, then yes that's working by design.

**Comment by ggazzo** [comment]
@graywolf336  this option (channel ->private) shoud be disabled to default rooms?what do you think?

**Comment by localguru** [comment]
I can confirm. After setting default to false, new users can access the room anymore.

**Comment by IQ2022** [comment]
there is no where to change default to no default

**Comment by IQ2022** [comment]
where to change default? 
![image](https://cloud.githubusercontent.com/assets/12454319/24157371/91dfb6a2-0e2f-11e7-9b04-0a38ed328a86.png)

**Comment by ggazzo** [comment]
You can just change to default if the channel is public... there are a problem if you open the info channel that you dont subscribe, but I will fix it.
