### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by nevson** [RocketChat/Rocket.Chat#641]
Hi, I'm using the Rocket.Chat docker container and I'm running an haproxy which does the SSL stuff for me. To enforce encryption I've completely disabled the Port 80 so that everybody has to use HTTPS. So far so good but now I'm facing following issues:

* Avatars are provided via HTTP
* The verification E-Mail uses as URL `http://` and also the port is wrong (I'm using Port 8443 but in the E-Mail somehow port 8280 gets used)

Is there some way to provide avatars also via HTTPS and how can I set the base URL used in the verification E-Mail?

**Comment by nevson** [comment]
After searching a while I've figured out that I've to set the `ROOT_URL` as you're using the function `Meteor.absoluteUrl()` in order to retrieve the base/root URL. In one example I've seen that it's possible to pass in the variable like `docker run ... -e ROOT_URL=https://mysite` which then should solve also the URL issue in the verification E-Mail. I'll give it a try tomorrow.

Actually is there any documentation about which environment variables can be set for Rocket.Chat? Like `ADMIN_PASS` or `ADMIN_EMAIL`, ...

**Comment by geekgonecrazy** [comment]
Sounds like you found it.  Did updating `ROOT_URL` work for you?

Documentation is being beefed up. @guarilha is doing great things. All environment variables would make a good edition.  :)

**Comment by nevson** [comment]
@geekgonecrazy Sorry for letting this issue pending. Setting the `ROOT_URL` fixed my issue and the avatars are working now and also the verification email should be now correct (didn't verify that one yet). Looking forward to the documentation!

Maybe I've to open another issue regarding the avatars... if I try to upload a custom avatar then the Docker container is crashing immediately for some reason :/ But this has nothing to do with this issue.

**Comment by geekgonecrazy** [comment]
Not a problem.  Just wanted to make sure you had it resolved.   That does sound like you're having another issue.
