### ISSUE TITLE
API setAvatar remove/clear avatar

### ISSUE THREAD

**Issue by alexroosenstein** [RocketChat/Rocket.Chat#6412]
Rocket.Chat Version: 0.53

I'm trying to connect RocketChat to another program I got running, and currently syncing the avatars (using the REST API users.setAvatar endpoint, with the avatarUrl argument). This works great in general, except when a user deletes their avatar (deletes, not replace with a new avatar), I can't remove it from RocketChat so it seems.

I tried sending an empty avatarUrl and also omitted the argument completely but neither seems to work. Am I missing something, or is this currently unsupported?

**Comment by graywolf336** [comment]
@alexroosenstein I do believe you're correct, this is just not currently possible. Feel free to submit a pull request though to implement that feature! :+1:
