### ISSUE TITLE
Image preview seems broken in electron / cordova in 0.54.0

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6423]
Rocket.Chat Version:  0.54.0
Running Instances: 1
DB Replicaset OpLog: yes

On the newest rocketchat build if i try to post a picture to a channel from cordova or electron the preview is broken. (But not the upload!) If i access the site with a web browser like google chrome, all seems fine. Also the native iOS app is working fine.

This is reproducable on the demo system.

Electron:
![image](https://cloud.githubusercontent.com/assets/5877910/24207099/55e26ca2-0f20-11e7-96dc-95ac00f6c2b2.png)

Web:
![image](https://cloud.githubusercontent.com/assets/5877910/24207137/679bb0b6-0f20-11e7-80ea-f0feb5c5f166.png)

**Comment by geekgonecrazy** [comment]
I can confirm.  I'm seeing the same behavior in electron.  No errors in console log either :(

**Comment by danpospisil** [comment]
The same here .. please release a fix ASAP and not in 3 weeks. Users are really starting to ask questions why we dont move to Slack and its harder to me to convice them that RC is a good choice with every release that breaks a major feature..

**Comment by danpospisil** [comment]
And one more thing I have just noticed - Giphy (https://rocket.chat/docs/administrator-guides/integrations/giphy) doesn't even load in browser.

**Comment by danpospisil** [comment]
Thanks guys! I hope this is the version we can finally hold to for a while!
