### ISSUE TITLE
Error while Uploading Picture

### ISSUE THREAD

**Issue by Artraxon** [RocketChat/Rocket.Chat#6431]
Rocket.Chat Version: 0.53.0
Running Instances: 3
DB Replicaset OpLog: enabled
Node Version: 4.8.0 - x64

I'm using GridFS for file uploads, and getting the following error when uploading a file,
sometimes it works, but most of the times, it doesn't.

Error: ENOENT: no such file or directory, open '/tmp/ufs/3zCzpFck6TwDCcgTD'
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].Meteor.methods.ufsComplete (/app/bundle/programs/server/packages/jalik_ufs.js:787:24)
  at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1093:26)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1817:12)
  at /app/bundle/programs/server/packages/ddp-server.js:905:20
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /app/bundle/programs/server/packages/ddp-server.js:904:41
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /app/bundle/programs/server/packages/ddp-server.js:903:46
  at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)
  at /app/bundle/programs/server/packages/ddp-server.js:755:85

    - - - - -
  at Error (native)

this is the docker-compose file i'm using (please ignore the missing spaces):
version: '2'
services:
  rocketchat:
    image: rocket.chat:latest
    restart: always
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.rlg-gsv.de
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    links:
      - mongo:mongo
    networks:
      - mongoint
      - chathttp
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: chat.rlg-gsv.de"
    depends_on:
      - mongo
      - mongo-init-replica
    ports:
      - 3000

  mongo:
    image: mongo:3.2
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"
    networks:
      - mongoint

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    networks:
      - mongoint
    depends_on:
      - mongo
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: always
    environment:
      - ROCKETCHAT_URL=https://chat.rlg-gsv.de
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=rosa.bot
      - ROCKETCHAT_PASSWORD=YQpIM9XRPT6xcK69Ofym
      - BOT_NAME=RosaBot
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    links:
      - rocketchat:rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - ./scripts:/home/hubot/scripts
    ports:
      - 3050:8080
networks:
  chathttp:
    external: true
  chatinternal:
    driver: bridge
  mongoint:
    driver: bridge

some of the networking stuff is due to legacy reasons (should i remove them)
the chathttp is used for an external proxy which is also used by other services.

**Comment by TwizzyDizzy** [comment]
Upgraded from 0.53.0 to 0.54.2 and it fixed this issue. So you might give this a shot. :)

Cheers
Thomas

**Comment by Artraxon** [comment]
I just copied the collections into a new instance. 
I still don't know what the issue was, but the new instance doesn't have the problem. 
I'll close the issue
