### ISSUE TITLE
Review chat conversations

### ISSUE THREAD

**Issue by armandomonzone** [RocketChat/Rocket.Chat#6433]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disable
Node Version: v4.7.3

Hi guys, actually I have implemented rocket.chat in our infraestructure, I review the possibility to review the conversations for the register users.

I followed the steps to install, snap install rocketchat-server Ubuntu 16.

I check the correct path for the database but i do not locate it! 

Can I to export the database chat conversations and restore in SQL? 

Someone can help me

best regards

**Comment by geekgonecrazy** [comment]
@armandomonzone the db for snaps are in: /snap/rocketchat-server/common/

But with snaps you can do a db dump via: `sudo snap run rocketchat-server.backupdb`

As to importing into SQL. Mongodb is a NoSql database you aren't going to be able to simply import into sql.
