### ISSUE TITLE
Rocket.Chat+ not loading on iOS

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#6435]
Rocket.Chat Version: 0.54.0
Node Version: 4.5.0

Just installed RC+ on my iPhone (iOS 10.2.1, not tested with any RC instance before 0.54). But when entering the correct URL, I just see a spinning wheel. Neither local network nor LTE works. Wrong URLs will show error message, so connection from App to server somehow works. Regular Rocket.Chat App works, just the "plus" App not.
![img_9879](https://cloud.githubusercontent.com/assets/193273/24228211/2814ca6a-0f73-11e7-92af-f44a9a46fcca.PNG)

**Comment by soundstorm** [comment]
Seems to be more related to Rocket.Chat instance than the App itself (affects more than one device), so opened it here and over at the iOS Repo https://github.com/RocketChat/Rocket.Chat.iOS/issues/371

**Comment by soundstorm** [comment]
demo.rocket.chat is working with Rocket.Chat+ without problems.

**Comment by TheReal1604** [comment]
@soundstorm got the same issue, and found the problem at my reverse proxy. Please check if it supports websockets. And the correct rewrite:

With this apache2 ProxyPass Rules it works nicely:

```
                ProxyPass /websocket ws://127.0.0.1:3000/websocket
                ProxyPassMatch ^/sockjs/(.*)/websocket ws://127.0.0.1:3000/sockjs/$1/websocket
                ProxyPass / http://127.0.0.1:3000/
                ProxyPassReverse / http://127.0.0.1:3000/
```

**Comment by soundstorm** [comment]
Ah, okay. Thank you, worked.
Is this documented?

**Comment by rafaelks** [comment]
Awesome! Thank you @TheReal1604!

**Comment by chisisi** [comment]
Would anyone know the websocket configuration settings required for this on a Windows IIS 8.0 Server?

**Comment by jianbosu** [comment]
@TheReal1604 iis 10 +arp 3.0+rewrite 
how to config?
