### ISSUE TITLE
Channel search does not find newly created channels

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#6436]
Rocket.Chat Version: 0.54
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

Channel search cannot find newly created channels

To Reproduce:

1. Create a new channel
2. Search for the new channel name

**Comment by MartinSchoeler** [comment]
@RichardFoxworthy are you sure you are currently not in the channel you are searching for? Since it will show the channel in the search if you are in it. Thanks for the feedback!

**Comment by RichardFoxworthy** [comment]
Yes, it will not show the result if you are already in the channel. 

I get it that it's unlike a user would search for a channel that they are already in, but it seems very weird to exclude current   Handel from the search results. 

I think current channel should be included in results list when it matches the search term

**Comment by marceloschmidt** [comment]
This was fixed. Let us know if this happens any time again. Thanks.
