### ISSUE TITLE
Channels disappear for some use users

### ISSUE THREAD

**Issue by juanrhino** [RocketChat/Rocket.Chat#6438]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.8.0

Some users have felt a problem with the channels, it looks like they are not longer part of some channels, such as #general, but when they logout and login again some times it work (in some cases it's worst, and they have to repeat the process). It looks like a cache problem. We already disabled to change the username to avoid problems, so that is no longer a reason.

Thanks for the help!

**Comment by SeanPackham** [comment]
I have not been able to reproduce this in 0.62.0 please let me know if it is still an issue.
