### ISSUE TITLE
interfaceConfigOverWrite does not apply changes.

### ISSUE THREAD

**Issue by nzhtrtlc** [RocketChat/Rocket.Chat#6439]
Rocket.Chat Version: 0.53.0
Running Instances: i don't know whats this
DB Replicaset OpLog: i dont know whats this
Node Version: v6.9.5

I want to configure settings in [LivechatVideCall.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/app/client/lib/LivechatVideoCall.js)

> Line: 49

I'm trying to over write interfaceConfig settings but my configures does not effect to the app.
For example, i want to remove chat from toolbars and set default_display_name to something else etc.
How can i do that?

I'm starting the application with 

> meteor npm start

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
