### ISSUE TITLE
Canned messages, Auto-response and Pro-active chat

### ISSUE THREAD

**Issue by devoger** [RocketChat/Rocket.Chat#6440]
Hello,

Congrats with this amazing software! Loving it even more everyday!

Do you have any future plans to add these functionalities? I do not see an updated roadmap so I am posting it here.

I believe these features are essential for providing an extraordinary support to customers.

1. Canned messages
Would be great if we can create a canned messages. It will allow us to provide a more efficient and fast response to the customer for basic and repeated questions.

2. Auto-response
It would be nice we can prepare a per-made welcome message once the user is connected to the livechat.
Example: Welcome to {Company}. Please let me know......

I was kind of almost achieve this using trigger but...with trigger the registration form do not show...then it gives all live chat user a guest names and no email. With this we cannot know the person unless we asked them by hand.

3. Pro-active chat
This is very useful for a live chat software.With the live chat button setting at the bottom, it takes some good eye to notice it unless I have to use a bright color.

With pro-active chat, it pop-ups and catch attention of the visitor.

With this feature, it immediately doubles our live chat interactions.

Sample from the previous live chat we were using:
https://nimbus.everhelper.me/client/notes/share/827472/mhvtgrevd0l3qpiskxh9

Thank you

Rocket.Chat Version:  0.53.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.7.3

**Comment by otsukaresamurai** [comment]
+bump on proactive. I'm hoping to wire a bot framework into Live Chat to have a bot be the default agent (see [this comment](https://github.com/RocketChat/Rocket.Chat/issues/7798#issuecomment-327016114)), and ideally the bot would be able to initiate a conversation without requiring the user to start it so the bot can be a sort of receptionist on the website. Perhaps make this a feature of triggers, where on certain conditions a trigger auto-starts the conversation

**Comment by sampaiodiego** [comment]
proactive chat is partially achievable with triggers.. you can fake a conversation.. but you can't continue it using a bot.

**Comment by otsukaresamurai** [comment]
@sampaiodiego Thanks for the reply, but given the only possible triggers are a regex on the page URL and a wait timer, and that it doesn't actually initiate the conversation such that an agent (bot or human) can see it, I'm not sure that can be called "proactive."

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,

**Comment by GRMrGecko** [comment]
I have just made an app as I needed a solution for this. Anyone is welcome to use it: https://github.com/GRMrGecko/canned-responses

**Comment by sampaiodiego** [comment]
thanks @GRMrGecko .. the new livechat widget has its own translation string at https://github.com/RocketChat/Rocket.Chat.Livechat 

we should be creating a lingohub project for it soon.
