### ISSUE TITLE
Change of UID broke uploads

### ISSUE THREAD

**Issue by quinox** [RocketChat/Rocket.Chat#6443]
Rocket.Chat Version: 0.54.0

Between version 0.34.0 and 0.53.0 the UID of rocketchat was 999. With 0.54.0 it's 99999:

```
# docker run -t -i rocketchat/rocket.chat:0.34.0 'grep' 'rocketchat' '/etc/passwd'
rocketchat:x:999:999::/home/rocketchat:/bin/sh

# docker run -t -i rocketchat/rocket.chat:0.53.0 'grep' 'rocketchat' '/etc/passwd'
rocketchat:x:999:999::/home/rocketchat:/bin/sh

# docker run -t -i rocketchat/rocket.chat:0.54.0 'grep' 'rocketchat' '/etc/passwd'
rocketchat:x:99999:99999::/home/rocketchat:/bin/sh
```

This broke file permissions of the docker upload volume for me.

---

EDIT: For other people with the same issue: To fix my installation I ran `chown -R 99999:99999 /var/rocketchat/uploads` on the Docker host

**Comment by Xarkam** [comment]
I suggest to modify the https://github.com/RocketChat/Docker.Base.Image/blob/master/Dockerfile to remove the -g 99999 and -u 99999 to let the system make the group and id for user rocketchat.

I my case, my system have already a 999 user. So, rocketchat dont create rocket user/group
