### ISSUE TITLE
Livechat widget and headers

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6448]
Rocket.Chat Version: 0.54.0

I see this in the console log of Chromium:

> Invalid 'X-Frame-Options' header encountered when loading 'https://chat.k0nsl.org/livechat': 'ALLOW-FROM https://k0nsl.org' is not a recognized directive. The header will be ignored.

I have correctly filled `Livechat allowed domains` with the appropriate value. I'm just throwing this out there in case it hasn't been caught already.

**Comment by tiredofit** [comment]
Being able to choose the Department via an API Call or Argument to the URL while limiting the users from being able to switch departments after the fact (However, an Agent being able to transfer would be useful) would give other live chat services a serious contender for competition. Eagerly Awaiting to see what comes out of this.

**Comment by HLFH** [comment]
The X-Frame-Options header has been obsoleted by the frame-ancestors directive from Content Security Policy Level 2.
