### ISSUE TITLE
Can't see uploaded images on desktop apps since 0.54.0

### ISSUE THREAD

**Issue by billtt** [RocketChat/Rocket.Chat#6460]
Rocket.Chat Version: 0.54.0
Running Instances: 1
DB Replicaset OpLog: 1
Node Version: 4.5.0

After upgraded to 0.54.0, all users can't see uploaded images in desktop apps. I find that this problem is caused by commit 2834b3f88ab07221351fc483454ea895151225e1
I don't quite understand the commit, can someone from the team explain it? Thanks.

**Comment by TheReal1604** [comment]
@billtt please update to 0.54.1 which was released yesterday. This fixes the issue. :-)

**Comment by billtt** [comment]
@TheReal1604 thanks!
