### ISSUE TITLE
Rocketchat(+) apps cant connect to Server

### ISSUE THREAD

**Issue by comander192** [RocketChat/Rocket.Chat#6465]
Rocket.Chat Version: 0.54.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.1

Hello,

We have set up a new Rocketchat Server from scratch yesterday with Version 0.54.1. Today none of our mobile apps can connect to the server, happens on Android and iOS. 

We are using the newest app versions 2.5.0 for regular Rocketchat and 1.0.8 for Rocketchat+. Uninstalling and resinstalling of the apps doesnt help. Our Rocketchat is behind a Apache reverse proxy but even tunneling directly on the server and then connect via the local port on the phone doesnt work.

We will try to downgrade to 0.54.0 again and see if that helps. Help is appreciated.

Thanks

**Comment by laggedHero** [comment]
@comander192 We have some updated Apache proxy docs (https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy). Have you seen them?

Could you please contact me on https://demo.rocket.chat (tiago.cunha) with and user and pass?

That way I could try and see what may be happening on the wire.

Thank you.

**Comment by soundstorm** [comment]
See also #6435

**Comment by comander192** [comment]
Hi soundstorm,

Your issue fixed our problem, thanks for that. Our reverse proxy missed the /websocket entry.

Thanks for the help.

**Comment by soundstorm** [comment]
@laggedHero I tried the official one, resulted in "Access to / is denied" - so something seems to be wrong there. Apache 2.6 on CentOS 7. The inofficial solutuion in the referenced issue works. I also got ProxyPreserveHost turned on.

**Comment by soundstorm** [comment]
At least the official solution does not work for me. Copy/Pasted.

**Comment by comander192** [comment]
The following is our config on RHEL7 apache version httpd-2.4.6-45.el7.x86_64. Works fine so far, only Notifications are not working on mobile app but this could be another issue.

`<VirtualHost *:443>
        ServerName xxx

        ErrorLog logs/chat_error_log
        TransferLog logs/chat_access_log
        LogLevel warn
        SSLEngine on
        SSLProtocol xxx
        SSLCipherSuite xxx
        SSLCertificateFile xxx
        SSLCertificateKeyFile xxx
        SSLCertificateChainFile xxx

        SetEnvIf User-Agent ".*MSIE.*" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0

        CustomLog logs/chat_request_log \
                "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
        SetEnv force-proxy-request-1.0 1
        SetEnv proxy-nokeepalive 1

        <Location />
        Order allow,deny
        Allow from all
        </Location>

#       ProxyPreserveHost On
#       ProxyPass /websocket ws://127.0.0.1:3000/websocket
#       ProxyPassMatch ^/sockjs/(.*)/websocket ws://127.0.0.1:3000/sockjs/$1/websocket
#       ProxyPass / http://127.0.0.1:3000/
#       ProxyPassReverse / http://127.0.0.1:3000/

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

        ProxyPassReverse / http://localhost:3000/

</VirtualHost>`
