### ISSUE TITLE
mini-files.js - const unicodeNormalizePath

### ISSUE THREAD

**Issue by mcgoosh** [RocketChat/Rocket.Chat#6477]
I have Rocket.Chat installed and running on a Cent 6 box.  There is no sysinit script so I opted to use the forever route.  Upon boot this is the message I get with forever.  

```
> /opt/Rocket.Chat/programs/server/mini-files.js:74
const unicodeNormalizePath = (path) => {
                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
error: Forever detected script exited with code: 8
```

**Comment by mcgoosh** [comment]
I just ended up setting the exported variables and launch of main.js in rc.local.

**Comment by rabidang3ls** [comment]
I'm having this same issue. Would be great if @mcgoosh would provide a few more details about the solution.

**Comment by osauzet** [comment]
I'am having the same issue, like @rabidang3ls if @mcgoosh can détails the solution... thanks...

**Comment by mcgoosh** [comment]
This is how I accomplished it in Cent 6.8

export BIND_IP=127.0.0.1
export ROOT_URL=https://whatever.whatever.com
export PORT=3000
export MONGO_URL=mongodb://localhost:27017/rocketchat

/usr/local/bin/node /opt/RocketChat/main.js

**Comment by monty241** [comment]
In my case it doesn't help:

```
#!/bin/ksh
export BIND_IP=127.0.0.1
export ROOT_URL=https://rocketchat.acme.com/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3000
node /opt/Rocket.Chat/main.js
```
On running the ksh script it gives:
```
/opt/Rocket.Chat/programs/server/mini-files.js:82
const unicodeNormalizePath = (path) => {
                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
```
Based upon comments for meteor and the use of meteor bij rocket chat, I assume that the wrong node version is listed on the page https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04

**Comment by monty241** [comment]
Rocket Chat server can be started after using:

`n 4.6.1`
