### ISSUE TITLE
Do Rocket.Chat support multiple server load balancing? Distributed deployment

### ISSUE THREAD

**Issue by xilu0** [RocketChat/Rocket.Chat#6480]
Do Rocket.Chat  support multiple server load balancing? The following is my configure nginx reverse proxy:
`upstream backend {
    server 172.19.6.25:3001;
    server 172.19.6.26:3001;
    server 172.19.6.27:3001;
}
server {
    listen 80;
    server_name localhost;

    error_log /var/log/nginx/rocketchat.access.log;
location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}
`
 the messages send are not displayed directly if you are connected to a different node, the user have to refresh the browser to see all other messages send to the other node.
What can I do?
Thank you for answer!

Rocket.Chat Version: 5.30
Running Instances: 3
Node Version:7.73

**Comment by KirbySSmith** [comment]
see https://github.com/RocketChat/Rocket.Chat/issues/6489#issuecomment-289453406

**Comment by xilu0** [comment]
@KirbySSmith
Thank you for respond！
I hadn't validated before fully, by looking at the source code to understand
export INSTANCE_IP=“ip”
