### ISSUE TITLE
Method of tracking every upgrade and performance? 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6482]
I don't know if this fits in an issue, but how do you guys track every upgrade from one release to the other , do you have a mechanism on track performance/bugs added/removed ?? Every time i do an upgraded, i have this fear something might not work,.. so far it has been solid
but as this product get closer 1.. i feel there should be a way to quality control it? thoughts 

Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @IQ2022 

I'm closing this issue. Please have a look at #7476. Some aspects have been discussed there. Apart from that I think Github might not be the right place for this. The RC team is aware of those issues and I guess they're working hard to get better with this.

As for this issue: if you still like to discuss this at length, then please head over to: forums.rocket.chat :)

Thanks!
Thomas
