### ISSUE TITLE
Use SoundManager2 as audio player 

### ISSUE THREAD

**Issue by wandonye** [RocketChat/Rocket.Chat#6484]
Rocket.Chat Version:  0.51.0
Running Instances: 1
DB Replicaset OpLog: N/A
Node Version:

This allows more choices of audio format.
Demo [here](http://www.schillmania.com/projects/soundmanager2/)

SoundManager 2 provides a easy to use API that allows sound to be played in any modern browser, including IE 6+. If the browser doesn't support HTML5, then it gets help from flash. If you want stricly HTML5 and no flash, there's a setting for that, preferFlash=false

It supports 100% Flash-free audio on iPad, iPhone (iOS4) and other HTML5-enabled devices + browsers

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
