### ISSUE TITLE
Rocketchat With Mobile Server

### ISSUE THREAD

**Issue by molochmike** [RocketChat/Rocket.Chat#6488]
**Rocket.Chat Version: 0.53
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3**

**I have some questions simple and straightforward, hope someone could help me out.**

1) I have a production mobile server which have plan to put in chat app.
2) Currently the mobile server is running on LAMP stack and application is written on php.
3) I have setup a rocket chat server as info provided above which runs on docker which also includes the mongodb.
4) Server that run this rocket chat is Ubuntu 16.04.  This rocketchat runs on nginx with the setup followed according to the rocket documentation.
5) My question is what should i do on configuration to allow my mobile server to talk to this rocket chat server?  I read about the incoming and outgoing webhook but don't quite get the point.  Is that what I should use or otherwise?
6) Is there any recommended framework for android or ios for the development of this rocketchat to the mobile server?

Appreciate the feedback.

Thanks.

**Comment by molochmike** [comment]
Hi Guys,

Any feedback to assist me on the matter above?   Thanks.

**Comment by rafaelks** [comment]
@molochmike I'll add some of the back-end guys to the thread. I believe this subject isn't related to mobile development. (cc @rodrigok, @sampaiodiego)

**Comment by sampaiodiego** [comment]
@molochmike from what I understood, you want to write your own ios and android app that communicate with rocket.chat server, is it right? if so you don't need to configure anything.

unfortunately there is not a easy to accomplish it.. you can take a look on our [iOS](https://github.com/RocketChat/Rocket.Chat.iOS) and [Android](https://github.com/RocketChat/Rocket.Chat.Android] repos and start from there.

You'll need to use our realtime API, you can find some documentation at https://rocket.chat/docs/developer-guides/realtime-api

**Comment by molochmike** [comment]
@rafaelks Thanks for the kind assist to have some back-end guys to help out.

@sampaiodiego Hi, you get my point right.  I have an app on my own now running in production, inside the app there is this function chat but it is not real time.  It's written on php.  This app available on android and ios.  If there are user communicate using my app using the chat function, they do not have real-time and you need to pull to refresh the app to get the chat appear from the source.  Ok, so i do not need to configure anything.

i have taken a look at the github docs for both android and ios.  Don't quite get to the point but will have to get the team to study deeper.  My current app backend is supported on MySQL, so is there any problem if the rocket chat supposely assume we got it work into our app but rocket chat uses mongodb, so is it possible to migrate the former mysql db data to mongodb?

I have also went throught the real time api.  The developer is looking into it now.

Our only concern is the team is most familiar with php and mysql structure but not really familiar in javascript, java, node.js, mongodb that kinda stuff.  Assuming we will use mongodb and use php to write our code to ensure rocket chat able to talk to our mobile server, will that workable?

Appreciate the feedback.  Thanks.

**Comment by molochmike** [comment]
Hi guys,

I'm closing this chapter since i do not get any response from rocket chat.  I have also removed away RC from my server.  Looking for some other alternatives to work on the IM.  Anyway thanks a lot for comments put in and really appreciate it.

**Comment by rafaelks** [comment]
@molochmike Sorry to hear that! I've one suggestion for you: why don't you use all of our platform and create your own code that uses our APIs only, throught the socket connection? I think it'll be much easier and it will allow you to get all of our updates and fixes.

**Comment by rafaelks** [comment]
@sachinrkeche What SDK are you using?
