### ISSUE TITLE
Broken umlauts

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat#6490]
Hello,

the umlauts are broken in German and de_at for:
- Google Chrome
- Rocket.Chat+ 2.5.0 Desktop on Windows 10

Screenshots attached.
![allgemein](https://cloud.githubusercontent.com/assets/26709898/24351582/8cd9cbfa-12e6-11e7-93ce-74fc1fb6a29b.JPG)
![channels](https://cloud.githubusercontent.com/assets/26709898/24351612/aefc8c2c-12e6-11e7-8cda-c4d819237886.JPG)

In IE11 they are working.

Ubuntu 16.04 LTS
Installed with snap
Rocket.Chat Version:  0.54.2
Running Instances:  1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

**Comment by MartinSchoeler** [comment]
@ArchimedesFM couldn’t reproduce neither on demo or in the latest release, could you give us more info on your setup? Thanks!

**Comment by ArchimedesFM** [comment]
@MartinSchoeler Sure if you can tell me what you want to know.
Rocket.Chat itself runs as a Snap-Installation on an Ubuntu 16.04 (Language = german) as a virtual System.
The virtual System runs on an Windows HyperV-Setup.
Rocket.Chat was newly installed last week as a test for our Company.
The umlauts were broken right after the finished installation - as an Administrator in the console or as an User via Chrome or the Desktop-App.

**Comment by localguru** [comment]
Can't confirm here: Chrome Version 57.0.2987.110 (64-bit), Rocket.Chat+ Version 2.4.0 on Linux, RC 0.52.0 running on Ubuntu 16.0 TLS.

**Comment by ArchimedesFM** [comment]
Problem visible with:
Windows 10 Pro 64Bit german
Chrome: 57.0.2987.110
Rocket.Chat+ 2.5.0
iPhone on iOS 10.3 with Rocket.Chat 2.5.0
Android 7.1.1 with Rocket.Chat 2.5.0

Working fine on Internet Explorer 11.953.14393.0 on the same Computer.
Reproducible with different PCs on the same Rocket.Chat Server.

**Comment by soundstorm** [comment]
@ArchimedesFM de-AT.UTF-8 as system language or iso?

**Comment by ArchimedesFM** [comment]
@soundstorm We installed a completly new System today with Rocket.Chat 0.55.0 - same behavior than before. New Ubuntu 16.04 LTS Server without any Data-Backup of the old System.
Installation of Rocket.Chat 0.55.0 via snap
We changed nothing, only created the Administrator-Account:
![rocketchat](https://cloud.githubusercontent.com/assets/26709898/25188399/2f0022de-2526-11e7-8ee9-ec3f50675f75.jpg)

The System language of the Ubunut System:
![systemlanguage](https://cloud.githubusercontent.com/assets/26709898/25188247/b4f5f252-2525-11e7-8287-aa695450e5bf.jpg)

**Comment by ArchimedesFM** [comment]
Solved. Rocketchat it self works fine. Rootcause in virt. section of our Apache ReverseProxy. There was a "copy/paste" parameter "AddDefaultCharset de_DE.UTF-8" from an other section. Comment out this parameter an it works.

**Comment by marceloschmidt** [comment]
Awesome!! I appreciate you taking the time to investigate, it would take us a long time to reproduce the problem 😁 Thanks again!
