### ISSUE TITLE
Simplify the Pin/Unpin message API

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#6492]
As we talked privately, we need to have a simpler API to **pin/unpin** messages, just like we have for **starred** messages.

## Requirements
- Instead of sending the entire message object, send just the `_id` and `rid`
- One API to pin/unpin or a flag (true/false) like we have on **starred** API

**Comment by graywolf336** [comment]
All the pin and unpin messages are about are the `{ _id, rid }` so in theory you could just pass those values in and it would work as is.. https://github.com/RocketChat/Rocket.Chat/commit/f16db8ee471d46a3e2e9df5164df22e97f6d4b74

**Comment by rafaelks** [comment]
@graywolf336 That's great! I'll try it tomorrow. Thank you!

**Comment by rafaelks** [comment]
We can close this one. 👍
