### ISSUE TITLE
Starting Docker container error logs

### ISSUE THREAD

**Issue by gdeverlant** [RocketChat/Rocket.Chat#6507]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog:
Node Version: 7.7.4

Servers : Raspberry Pie and Odroid C1

Dockerfile content:

> FROM alpine-nodejs-arm:latest
> 
> ENV RC_VERSION 0.54.2
> 
> RUN apk update \
> 	&& apk upgrade \
> 	&& rm -rf /var/cache/apk/* \
> 	&& apk add --no-cache gnupg curl
> 	
> RUN addgroup -g 9999 -S rocketchat
> RUN adduser -D -u 99999 rocketchat -G rocketchat \
> &&  mkdir -p /app/uploads \
> &&  chown rocketchat.rocketchat /app/uploads
> 
> VOLUME /app/uploads
> 
> # gpg: key 4FD08014: public key "Rocket.Chat Buildmaster <buildmaster@rocket.chat>" imported
> RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104
> 
> WORKDIR /app
> 
> RUN curl -fSL "https://rocket.chat/releases/${RC_VERSION}/download" -o rocket.chat.tgz \
> &&  curl -fSL "https://rocket.chat/releases/${RC_VERSION}/asc" -o rocket.chat.tgz.asc \
> &&  gpg --batch --verify rocket.chat.tgz.asc rocket.chat.tgz \
> &&  tar zxvf rocket.chat.tgz \
> &&  rm rocket.chat.tgz rocket.chat.tgz.asc \
> &&  cd bundle/programs/server
> 
> RUN npm install
> 
> USER rocketchat
> 
> WORKDIR /app/bundle
> 
> # needs a mongoinstance - defaults to container linking with alias 'db'
> ENV MONGO_URL=mongodb://db:27017/meteor \
>     HOME=/tmp \
>     PORT=3000 \
>     ROOT_URL=http://localhost:3000 \
>     Accounts_AvatarStorePath=/app/uploads
> 
> EXPOSE 3000
> 
> CMD ["node", "main.js"]

module.js:472
    throw err;
    ^

Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
module.js:472
    throw err;
    ^

**Comment by gdeverlant** [comment]
This is the output of the last steps for the image compilation.

Step 11/16 : RUN npm install
 ---> Running in d0edbd547551
npm WARN enoent ENOENT: no such file or directory, open '/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
 ---> 70df9500d262
Removing intermediate container d0edbd547551
Step 12/16 : USER rocketchat
 ---> Running in 5612ee5b74ab
 ---> 751c146500ad
Removing intermediate container 5612ee5b74ab
Step 13/16 : WORKDIR /app/bundle
 ---> 9fa07b615596
Removing intermediate container 29d91991c630
Step 14/16 : ENV MONGO_URL mongodb://mongodb:27017/meteor HOME /tmp PORT 3000 ROOT_URL http://localhost:3000 Accounts_AvatarStorePath /app/uploads
 ---> Running in da044382dfea
 ---> a38aa57dc09e
Removing intermediate container da044382dfea
Step 15/16 : EXPOSE 3000
 ---> Running in aa276670781a
 ---> bc0842b5226f
Removing intermediate container aa276670781a
Step 16/16 : CMD node main.js
 ---> Running in af49d6464e12
 ---> 9242823924a5
Removing intermediate container af49d6464e12
Successfully built 9242823924a5

**Comment by geekgonecrazy** [comment]
Shouldn't be an issue any more especially if using our dockerfile
