### ISSUE TITLE
Expire inactive user accounts

### ISSUE THREAD

**Issue by ToeiRei** [RocketChat/Rocket.Chat#6508]
It would be nice to be able to expire inactive user accounts or at least get an idea when they logged in last time looking at the user table.

**Comment by n30ngruu3n** [comment]
I would really appreciate it, if it will be possible to set an expiration date for the accounts. In our term, we're using RC at our university and we've got a huge amount of employee turnovers on the student side (sometimes they leave us after 6 months..) and it will be really helpful not to manual delete every unused account.

Regards
neongruuen

**Comment by ToeiRei** [comment]
I'm thinking of something like 'not logged in since X days, delete the account'

**Comment by n30ngruu3n** [comment]
Something like this will also fit our needs. :-)

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
