### ISSUE TITLE
Slackbridge one way if channel was created in Rocket first

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#6509]
Rocket.Chat Version: 0.49.3

Creating a channel in Rocket.Chat first and then in Slack leads to a one way synchronisation.
Chatbot joined in Slack by invite, message shows up in Rocket. All further messages are synced from Slack to Rocket but not from Rocket to Slack.

Creating it in Slack then in Rocket works seamlessly.

**Comment by tanc** [comment]
This doesn't seem to be the case in an integration I just set up where I created the channel in rocket.chat first and we have two way synced messages working fine

**Comment by tanc** [comment]
Rocket.Chat Version: 0.55.1

**Comment by soundstorm** [comment]
I [still] need to restart RC (currently at 0.58.0) to enable sync from RC to Slack if created in RC first. So there must be some hooks not working live but at startup time for Slackbridge.
