### ISSUE TITLE
iOS app - switching from portrait to landscape often leaves big gap between left pane and room

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#651]
Room does not resize correctly (horizontally) to fill the available space.

**Comment by gmsecrieru** [comment]
Could not reproduce this one, I wonder if we have disabled orientation switching.

**Comment by engelgabriel** [comment]
Is this still an issue? I believe this was fixed.

**Comment by graywolf336** [comment]
Testing this showed a new bug on my iPad Mini: it doesn't rotate to
landscape.

**Comment by Sing-Li** [comment]
Haha ... me too. I think that's how the extra-space bug was 'fixed'  (pun intended).  It no longer rotates.
