### ISSUE TITLE
Error: Cannot find module 'is-property' RC Developer .0.54.0

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6510]
Rocket.Chat Version: 0.54.0
Running Instances: 1
DB Replicaset OpLog:
**iCANT Run Developer Version any more**

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\Users\Ahmed ElSheikh\rc542

C:\Users\Ahmed ElSheikh\rc542>npm install is-property -g
is-property@1.0.2 C:\Users\Ahmed ElSheikh\AppData\Roaming\npm\node_modules\is-pr
operty

C:\Users\Ahmed ElSheikh\rc542>meteor
[[[[[ C:\Users\Ahmed ElSheikh\rc542 ]]]]]

=> Started proxy.
=> Meteor 1.4.3.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.
'C:\Users\Ahmed' is not recognized as an internal or external command,
operable program or batch file.
=> Errors prevented startup:

   While loading package emojione:emojione@2.2.6:
   error: Command failed: C:\Users\Ahmed
   ElSheikh\AppData\Local\.meteor\packages\meteor-tool\1.4.3_1\mt-os.windows.x86
_32\dev_bundle\bin\npm.cmd
   rebuild --update-binary
   module.js:327
   throw err;
   ^

   Error: Cannot find module 'is-property'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous> (C:\Users\Ahmed
   ElSheikh\AppData\Local\.meteor\packages\emojione_emojione\2.2.6\npm\node_modu
les\grunt-contrib-qunit\node_modules\grunt-lib-phantomjs\node_modules\phantomjs\
node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\no
de_modules\generate-object-property\index.js:1:80)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)

   npm ERR! Windows_NT 6.3.9600
   npm ERR! argv "C:\\Users\\Ahmed
   ElSheikh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.3_1\\mt-os.wind
ows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\Ahmed
   ElSheikh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.3_1\\mt-os.wind
ows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild" "--update-binary"
   npm ERR! node v4.7.3
   npm ERR! npm  v4.1.2
   npm ERR! code ELIFECYCLE
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node
   install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     C:\Users\Ahmed
   ElSheikh\AppData\Local\.meteor\packages\emojione_emojione\2.2.6\npm\node_modu
les\.temp-1ak8c7\npm-debug.log
   module.js:327
   throw err;
   ^

   Error: Cannot find module 'is-property'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at Object.<anonymous> (C:\Users\Ahmed
   ElSheikh\AppData\Local\.meteor\packages\emojione_emojione\2.2.6\npm\node_modu
les\grunt-contrib-qunit\node_modules\grunt-lib-phantomjs\node_modules\phantomjs\
node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\no
de_modules\generate-object-property\index.js:1:80)
   at Module._compile (module.js:409:26)
   at Object.Module._extensions..js (module.js:416:10)
   at Module.load (module.js:343:32)
   at Function.Module._load (module.js:300:12)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)

   npm ERR! Windows_NT 6.3.9600
   npm ERR! argv "C:\\Users\\Ahmed
   ElSheikh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.3_1\\mt-os.wind
ows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\Ahmed
   ElSheikh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.3_1\\mt-os.wind
ows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild" "--update-binary"
   npm ERR! node v4.7.3
   npm ERR! npm  v4.1.2
   npm ERR! code ELIFECYCLE
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node
   install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     C:\Users\Ahmed
   ElSheikh\AppData\Local\.meteor\packages\emojione_emojione\2.2.6\npm\node_modu
les\.temp-1ak8c7\npm-debug.log

=> Your application has errors. Waiting for file change.

**Comment by geekgonecrazy** [comment]
Maybe try deleting your node_modules folder and doing: `meteor npm install` again and see what that does for you.

**Comment by Nemra1** [comment]
im already fixe this issu by this way https://github.com/RocketChat/Rocket.Chat/issues/6517

**Comment by geekgonecrazy** [comment]
@Nemra1 great!  I'll go ahead and close this issue then.
