### ISSUE TITLE
Slowness in Messages

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6512]
This was not an issue in the prior versions, i have noticed it and also my users report slowness when they sent a message it shows after few seconds.. this bring back to my performance implications when we upgrade from one rev to the other? 
 
in fact i see it happen on your demo instant but you have 1000s of users active 

Rocket.Chat Version: 0.54
Running Instances: 1
DB Replicaset OpLog:
Node Version:v4.8.1

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. Please try to reproduce on latest stable and give some information on why you think this is a structural Rocket.Chat problem and not something only on your deployment or your hardware.

Cheers
Thomas
