### ISSUE TITLE
Future: Add Monitor To Dashboard

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6513]
Add Monitor Screen In Dashboard To Watch who login + Who logute + Login Room + Who trying connect + who kicked + who banned+ who muted + ....etc
Path in Admin panel ( Dashboard >  Monitor )
Somthing like this screen
![mnt](https://cloud.githubusercontent.com/assets/22897987/24410746/25b45348-13d4-11e7-8876-f37b527a217d.jpg)

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
