### ISSUE TITLE
Future : Add Ban Panel in Dashboard

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6514]
add banned user setting in dashboard  Path ( Dashboard > Users 
                                                                                                        >Ban Manger 
                                                                                                                           > Add Ban + Ban list
with options 
 1-ban username
2-ban ip
3-ban ip range
4- ban computer from mac adress or harddesk serial
5-ban country
6- ban reason 
7 - ban list
![ban](https://cloud.githubusercontent.com/assets/22897987/24411181/854c4aee-13d5-11e7-83af-48c59810f8e6.jpg)
**ban list**
![ban2](https://cloud.githubusercontent.com/assets/22897987/24411185/89561840-13d5-11e7-9e7c-211b13ca0df6.jpg)
 ban box from Rooms
![3](https://cloud.githubusercontent.com/assets/22897987/24411360/f8523c74-13d5-11e7-9e8a-91ad022f6210.jpg)

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed. Users can be banned from their individual accounts.
