### ISSUE TITLE
Livechat guests can't see images + youtube/other links in chat?

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#6516]
Anyone else found this? I tested on a few different installs and am still finding that this seems to be an RC bug - guests participating in LiveChats can't see rich media in chats (and the agent doesn't realize this because they can drop media into chat like normal) - looks like a bug because the guest ends up seeing an empty message on their end.

I looked at the permissions but it doesn't seem like there is a relevant permission...

Thoughts/Ideas/Recommendations?

q./

Rocket.Chat Version: 	0.53.0
Running Instances:  1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by dytec** [comment]
There was a PR for this feature but it got deprecated: #4142

**Comment by designgurudotorg** [comment]
Thanks for the link @dytec ... so the PR relied on code which was changing but has anything happened since that to make rich media and link previews show up in the livechat widget? Anything planned in the product roadmap?

q./

**Comment by ruKurz** [comment]
Are there any plans, solving this issue?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:40728 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1drOIt-004FQF-4O
	for greg@biomassiv.es; Mon, 11 Sep 2017 07:59:07 -0500
Date: Mon, 11 Sep 2017 05:58:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1505134706;
	bh=6IVVyteqeS5bf9dCj9/eawcJtLdovkSoTuRi8r2Fsa4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=dHl8sXETpRHm4qZLzrDXU4A06tlD0Ca/PsxetZEtmSwZjpzh1viShzyOyb6pgV5j2
	 WC3vN7rcOcV52AU37ujOOZDPLsautWRKMdM2UD+Lles4OgJguLylE7fTKURVmhvUaw
	 A4CMSn5bYQfqGNYapx6i+615RMwMqOR96E06D6ww=
