### ISSUE TITLE
Can't  find npm module 'mime-type/with-db'. in developer version 0.54.2

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6517]
Rocket.Chat Version: 0.54.0
METEOR@1.4.3.2
**i cant Run any Developer Version since v 0.52.x**
C:\Users\Ahmed ElSheikh\rc542>meteor
[[[[[ C:\Users\Ahmed ElSheikh\rc542 ]]]]]

=> Started proxy.
'C:\Users\Ahmed' is not recognized as an internal or external command,
operable program or batch file.
=> Started MongoDB.
W20170328-17:40:08.281(2)? (STDERR) Note: you are using a pure-JavaScript implem
entation of bcrypt.
W20170328-17:40:08.468(2)? (STDERR) While this implementation will work correctl
y, it is known to be
W20170328-17:40:08.470(2)? (STDERR) approximately three times slower than the na
tive implementation.
W20170328-17:40:08.474(2)? (STDERR) In order to use the native implementation in
stead, run
W20170328-17:40:08.478(2)? (STDERR)
W20170328-17:40:08.480(2)? (STDERR)   meteor npm install --save bcrypt
W20170328-17:40:08.482(2)? (STDERR)
W20170328-17:40:08.483(2)? (STDERR) in the root directory of your application.
I20170328-17:40:08.618(2)? Will load cache for users
I20170328-17:40:08.622(2)? 0 records load from users
I20170328-17:40:08.629(2)? Will load cache for rocketchat_room
I20170328-17:40:08.652(2)? 0 records load from rocketchat_room
I20170328-17:40:08.655(2)? Will load cache for rocketchat_subscription
I20170328-17:40:08.657(2)? 0 records load from rocketchat_subscription
I20170328-17:40:08.665(2)? Will load cache for rocketchat_settings
I20170328-17:40:08.669(2)? 181 records load from rocketchat_settings
I20170328-17:40:08.671(2)? **Exception in callback of async function: Error: Can't
 find npm module 'mime-type/with-db'. Did you forget to call 'Npm.depends' in pa
ckage.js within the 'modules-runtime' package?**
I20170328-17:40:08.675(2)?     at Object.require (C:\Users\Ahmed ElSheikh\rc542\
.meteor\local\build\programs\server\boot.js:200:17)
I20170328-17:40:08.678(2)?     at options.fallback (packages\modules-runtime.js:
479:18)
I20170328-17:40:08.681(2)?     at Module.require (packages\modules-runtime.js:12
6:16)
I20170328-17:40:08.682(2)?     at Module.Mp.import (C:\Users\Ahmed ElSheikh\AppD
ata\Local\.meteor\packages\modules\0.7.9\npm\node_modules\reify\lib\runtime.js:7
5:16)
I20170328-17:40:08.684(2)?     at meteorInstall.node_modules.meteor.rocketchat:a
ssets.server.assets.js (packages/rocketchat:assets/server/assets.js:1:85)
I20170328-17:40:08.686(2)?     at fileEvaluate (packages\modules-runtime.js:197:
9)
I20170328-17:40:08.689(2)?     at require (packages\modules-runtime.js:120:16)
I20170328-17:40:08.691(2)?     at C:\Users\Ahmed ElSheikh\rc542\.meteor\local\bu
ild\programs\server\packages\rocketchat_assets.js:704:1
I20170328-17:40:08.698(2)?     at C:\Users\Ahmed ElSheikh\rc542\.meteor\local\bu
ild\programs\server\packages\rocketchat_assets.js:710:3
I20170328-17:40:08.700(2)?     at C:\Users\Ahmed ElSheikh\rc542\.meteor\local\bu
ild\programs\server\boot.js:303:34
I20170328-17:40:08.708(2)?     at Array.forEach (native)
I20170328-17:40:08.713(2)?     at Function._.each._.forEach (C:\Users\Ahmed ElSh
eikh\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev
_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
I20170328-17:40:08.719(2)?     at C:\Users\Ahmed ElSheikh\rc542\.meteor\local\bu
ild\programs\server\boot.js:128:5
I20170328-17:40:08.723(2)?     at C:\Users\Ahmed ElSheikh\rc542\.meteor\local\bu
ild\programs\server\boot.js:352:5
I20170328-17:40:08.734(2)?     at Function.run (C:\Users\Ahmed ElSheikh\rc542\.m
eteor\local\build\programs\server\profile.js:510:12)
I20170328-17:40:08.738(2)?     at C:\Users\Ahmed ElSheikh\rc542\.meteor\local\bu
ild\programs\server\boot.js:351:11
I20170328-17:40:08.743(2)? Updating process.env.MAIL_URL

**Comment by MartinSchoeler** [comment]
@Nemra1 have you already did a `meteor npm install` on the rocket chat directory?

**Comment by Nemra1** [comment]
yup i have

**Comment by geekgonecrazy** [comment]
@Nemra1 great glad you got it.  Going to go ahead and close this
