### ISSUE TITLE
CentOS - How to re-enable login / registration?

### ISSUE THREAD

**Issue by hubertkahr** [RocketChat/Rocket.Chat#6518]
Rocket.Chat Version:  0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0

I disbaled the login / registration page. How can I enable it again in CentOS 7?

**Comment by localguru** [comment]
Hi,

on webinterface see Accounts -> Show form-based Login

directly via mongodb (restart Rocket.Chat after change - does anyone know how to handle this without a restart?):

db.rocketchat_settings.update({_id:'Accounts_ShowFormLogin'}, {$set: {'value' : true} });

Ciao
Marcus

**Comment by hubertkahr** [comment]
Sorry, I am new on RocketChat. How do I get into the Webinterface without the ability to log in?

**Comment by localguru** [comment]
I'm not 100% sure, but I think you can't. Did you lose your password? You can enable the login form via mongodb and then create a new user and set role to admin. Check REST API. See #1502

**Comment by hubertkahr** [comment]
Okay, will use MongoDB. I was just confused because you offered the webinterface-option as I am not able to login with disabled login-formular.

**Comment by localguru** [comment]
Sorry, for confusion. For mongodb:

> mongo
use rocketchat
db.rocketchat_settings.find({"_id": "Accounts_ShowFormLogin"});
(this should show a value set to false)
db.rocketchat_settings.update({_id:'Accounts_ShowFormLogin'}, {$set: {'value' : true} });
quit
> restart your rocket.chat

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
