### ISSUE TITLE
Trigger video conferance from custom button (using iframe integration)

### ISSUE THREAD

**Issue by nzhtrtlc** [RocketChat/Rocket.Chat#6519]
Rocket.Chat Version: 0.53.0
Running Instances: 1
Node Version: v6.9.5

I am using RocketChat with iframe integration. I can open direct chats using this code

> let username = 'user1234';
document.querySelector('iframe').contentWindow.postMessage({
  externalCommand: 'go',
  path: '/direct/' + username
}, '*')

But i want to open one-to-one (private) jitsi conferance. I am able to do this in RC iframe but i want to trigger it from my custom button. Not in iframe.
How can i trigger that video-conferance button ? So it'll open conferance between me and selected user.
Note: i can use window.open(jitsi_link); but it doesn't  insert log that in to user chat screen and it wont sent notification to target user.
Thanks.

**Comment by geekgonecrazy** [comment]
@nzhtrtlc currently I don't believe this is possible via iframe.

**Comment by nzhtrtlc** [comment]
Thanks. I found a temporary solution.
I can trigger the camera button via this code
`document.querySelector('camera_selector').click();`

**Comment by geekgonecrazy** [comment]
Awesome! Glad you found a solution that works for you
