### ISSUE TITLE
No Desktop Notifications for Highlight Words in Channels

### ISSUE THREAD

**Issue by Fscape** [RocketChat/Rocket.Chat#6523]
Is it possible for Highlight words to trigger desktop notifications?

Use case:
Multiple teams share a common channel. 
One of those teams wants to be notified when someone types the word "maintenance", so the team members have "maintenance" in their accounts' Highlight words. 
(The rest of this channel's posts aren't urgent for this team, so can be read at their leisure.)
When someone types "maintenance" in the common channel, none of the team members get a desktop notification/popup.

Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

**Comment by sampaiodiego** [comment]
we have updated notifications logic and this should be fixed now.

please let me know if this is still an issue and I reopen it.
