### ISSUE TITLE
How to update my Rocket installed with Docker ?

### ISSUE THREAD

**Issue by Julianoe** [RocketChat/Rocket.Chat#6527]
Hello friends !
I installed ROcket with the help of Docker as it is explained in the documentation.

I don't know how i should proceed to update to the last version available though. Can someone help me please ? :)

Rocket.Chat Version: 0.53
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.7.3

**Comment by lucasvanhalst** [comment]
Assuming you used docker-compose:
```
docker-compose pull
docker-compose up
```

And that should be it

**Comment by Julianoe** [comment]
I'll try this. 
Should i do a bakcup though ? If yes i'm not sure of what/how backup the important data of Rocket ... ?

**Comment by Julianoe** [comment]
Answering my own comment for people who are looking for specific information and are not confortable with docker concepts (newbies like me).

### Updating to the latest Rocket.Chat version

Go where your docker-compose.yml is. For me it was : 
`cd /var/www/rocket.chat`

Then execute the following
`docker-compose pull`
It will update the docker images you have to the latest or specified version in your docker-compose.yml file.
*Warning* : if like me you followed the instructions of the current documentation, your file probably specifies the following 
```
hubot:
  image: rocketchat/hubot-rocketchat:v0.1.4
```
This will make docker look for the v0.1.4 of the rocketchat/hubot-rocketchat image.
If you want it to _pull_ the latest version change it to : 
```
hubot:
  image: rocketchat/hubot-rocketchat:latest
```

Finally when everything is updated do a `docker-compose up` that will update the services using the latest version of the images you just pulled.
To let the command running in the background of your server use `docker-compose up -d rocketchat hubot`

**Comment by Julianoe** [comment]
@sampaiodiego @MartinSchoeler I don't really now how these things work (new to open source project i have to admit) but i feel like these instructions (quite simple indeed) would have gained me a lot of time if they were mentioned somewhere? 

Also i see that the TODO of the concerned documentation page specifies "section for updating and backing up".
Maybe it's a start ? I'm not qualified enough in Docker sailing to know ^^

**Comment by k0nsl** [comment]
@Julianoe: this is how I backup my instance.

```
docker save -o /root/rocketchat-backup/goychat-mongodb-$( date '+%Y-%m-%d_%H-%M-%S' ).tar.gz mongo
```

I think that is likely what everybody else is doing as wel, or maybe they run it on a dedicated server which they've split up into virtual machines, and then backup the entire VM before they make a major change such as upgrading Rocket.Chat. But as for backing up MongoDB, then they probably do it the way I showed you.
