### ISSUE TITLE
Email not displayed when user registered with Oauth

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#6528]
It doesn't look like users' email addresses are stored in RC when they register using an Oauth provider (tested this with twitter and linkedin) - so you can't send them system emails (incl notification emails)

Of course, if someone has registered with their email and then added an oauth provider that wouldn't be a problem but it doesn't look like RC checks whether the email used by the external Oauth account uses a pre-existing email and simply attached the Oauth credentials to that existing registration.

Did I miss something or is this a bug?

q./

**Comment by Hudell** [comment]
Not exactly a duplicate, but this problem should be solved by #3187 as well.
