### ISSUE TITLE
cannot change username 

### ISSUE THREAD

**Issue by 12test12** [RocketChat/Rocket.Chat#6538]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.1

I have an bug the user cannot change the username. But i activated the option to change the username.
![issue1](https://cloud.githubusercontent.com/assets/23378492/24508954/594025ce-1565-11e7-8985-8a9c2cdcd0ad.png)
![issue3](https://cloud.githubusercontent.com/assets/23378492/24508973/5f2d96ce-1565-11e7-838d-d25b79fdc9fc.png)

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Comment by 12test12** [comment]
its work now :D
