### ISSUE TITLE
Connection loss causes client to malfunction

### ISSUE THREAD

**Issue by alexroosenstein** [RocketChat/Rocket.Chat#6546]
Rocket.Chat Version: 0.53.0

I've noticed that the Rocket.Chat client (webbased and desktop clients on Windows and OSX) stop working properly when they lose their connection to the server.

This happened on 3 occasions: when a laptop was closed and went into sleep mode, when the nginx reverse proxy was restarted and when I disconnected my computer from the network (by disabling the network interface temporarily).

It doesn't seem to happen when I was originally at the home page of Rocket.Chat, but if I had a chat window open while losing the connection, the client would stop working and I would have to refresh the page entirely (or in the desktop client Reload the Current Server).

The client does seem to reload by itself (after reconnecting), but on the background Javascript runs into some errors. I attached a file with these errors.
[rocketchat-errors-1490955953426.txt](https://github.com/RocketChat/Rocket.Chat/files/885276/rocketchat-errors-1490955953426.txt)

Not sure if it's related, but I use Iframe integration/authentication.

**Comment by gabriellsh** [comment]
This should no longer be an issue. Please open a new report if you're having problems.
