### ISSUE TITLE
Database Migration Problem on Heroku

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#6549]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3
Database Migration: 90

I was previously running version 0.53 and when to upgrade to the latest on Heroku 0.54.2.
I encontered an error in Heroku and decided to try to build the rocket.chat again. It succeed. However, when I went to start my dyno it kept crashing with the following error:

Updating process.env.MAIL_URL
2017-03-31T13:17:44.178220+00:00 app[web.1]: Will load cache for rocketchat_permissions
2017-03-31T13:17:44.198566+00:00 app[web.1]: 67 records load from rocketchat_permissions
2017-03-31T13:17:46.056924+00:00 app[web.1]: ufs: store created at 
2017-03-31T13:17:48.207101+00:00 app[web.1]: ufs: store created at 
2017-03-31T13:17:55.844754+00:00 app[web.1]: Exception in callback of async function: Error: [Can't find migration version 90]

Any idea on how to fix this? I tried unlocking with the command:
db.migrations.update({_id: 'control'},{$set:{locked:false,version:90}})
but it didn't work. I was able to migrate back to my previous version. Any ideas?  Could this be related to some of the problems people are experiencing here:

By problem I mean not the DB issue, but the initial fail to build on Heroku which lead to a DB issue:

[Issue: 6452](https://github.com/RocketChat/Rocket.Chat/issues/6452)
[Issue: 6444](https://github.com/RocketChat/Rocket.Chat/issues/6444)

**Comment by Syirrus** [comment]
UPDATE: 
After the commits from last night (roughly 120 since yesterday morning), I was able to success build on Heroku. (d88a153)

**Comment by jekuno** [comment]
Did you try a fresh deployment to Heroku and even didn't get the error as described in https://github.com/RocketChat/meteor-buildpack-horse/issues/10?
