### ISSUE TITLE
npm version confusion on ubuntu 16.04 LTS: version 2.15.9 and 3.5.2 are installed

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6550]
Hi,

I've installed npm on ubuntu 16.04 LTS via "apt install npm" [1]. 

npm -v shows version 2.15.9.

There seem to be two versions on the system, one in /usr/local/bin (= 2.15.9) and one in /usr/bin (= 3.5.2).

```
# dpkg -l | grep npm
ii  npm   3.5.2-0ubuntu4      all          package manager for Node.js
```
I've seen a lot of manuals, which say npm should be "3.5.2".

Which one will RC use then?

Ciao!

[1] https://rocket.chat/docs/installation/manual-installation/ubuntu/

**Comment by Prakharsvnit** [comment]
It will be nicer to upgdate your npm version.
You can do this by  typing this command in your terminal `sudo npm install npm@latest -g`

**Comment by localguru** [comment]
@Prakharsvnit thank you. After the upgrade it's now Version: npm -v -> 4.4.4. Is 4.4.4 compatible with RC? node --version -> v4.5.0

Ciao
Marcus

**Comment by lucasvanhalst** [comment]
npm is just a package manager, its version doesn't really matter.

**Comment by Prakharsvnit** [comment]
@localguru it must work now.so what issue are you facing?

**Comment by localguru** [comment]
@Prakharsvnit yes, it does work. I was just confused about the two different versions in /usr/bin (installed by debian package manager) and the on in /usr/local/bin.

**Comment by Prakharsvnit** [comment]
@localguru you can close the issue then.
