### ISSUE TITLE
Trying to LogOut using REST API, getting error "You must be logged in to do this."

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#6556]
Rocket.Chat Version:   0.52.0
Running Instances:  1
DB Replicaset OpLog:   Disabled
Node Version:  v4.7.3

I'm trying to logout of Meteor through my WordPress site.  I am getting this error message: "You must be logged in to do this."

 believe this means I must be getting my x-auth-token and/or x-user-id from the wrong place.  I am pulling them from my Compose database in the Users collection for the specified user.  I'm not sure where else I should be looking.

This is my PHP code (using WordPress)

```php
$url = 'https://members.peerunschooling.net/api/v1/logout';
$args = array(
                  'headers'     => array('x-auth-token' => '**iDjEk/ABSawHgELC1tWRejiTgblkS0sOE6XSAYd4VpI=**',
                                         'x-user-id' =>  '**jH5RH4A8d9akDWYHb**'
                                        )
             ); 
$response = wp_remote_get( $url, $args ); 
error_log(json_encode($response));
```

This is where I'm pulling the x-auth-token and x-user-id in my Compose database:

```
_id: "**jH5RH4A8d9akDWYHb**"
services: {
resume: {
      loginTokens: [
                  {
                       when: ISODate("2017-04-01T02:43:25.952Z"),
                       hashedToken: "**iDjEk/ABSawHgELC1tWRejiTgblkS0sOE6XSAYd4VpI=**"
        }
      ] 
}
```

**Comment by graywolf336** [comment]
After looking into this issue in more detail, I am a little confused as to what you're trying to do. The rest api's login/logout *only* apply to the rest api and not actually the internal loginTokens. For the rest api's logout to work, you must login with the rest api and the return token only is valid for the rest api calls.

What exactly are you trying to achieve?

**Comment by flantascience** [comment]
Here's what I'm going for....

I've got a WordPress site with RocketChat embedded with an iFrame.  My users login to WordPress and then they use the OAuth to login to RocketChat.  That is actually working successfully.

The problem is that when a user logs of out **WordPress**, it doesn't log them out of RocketChat.  So if they logout of WordPress, then login to WordPress as a different user, they'll still be stuck in RocketChat as the old user.  So I went into WordPress and added an action to the WP logout function which would send a signal to RocketChat to logout the user. And I was using this process to send the signal to RocketChat.

**Comment by amirHizkiya** [comment]
@flantascience Did you ever get this working.

I seem to be facing the same issue.

**Comment by flantascience** [comment]
The approach I took.... was to just stop caring about this little bug :)

Only so many battles and this just took up too much time.

Jim Flannery

jim-flannery.com
p. 860-578-4966
e. jim@jim-flannery.com
s. jim_flannery

**Comment by amirHizkiya** [comment]
Seems like quite the issue to not be able to log a user out when needed (If this is indeed the issue). If so and you are able to let this go, then you are bigger man then me...

Im trying to logout a user through the /api/v1/logout end point with no luck.

Thanks for the update.

**Comment by amirHizkiya** [comment]
How about if they access the chat URL directly?

**Comment by ahmadali7** [comment]
Any luck on this issue (exactly same as @flantascience explained in comment )?

**Comment by flantascience** [comment]
Sorry @ahmadali7    I gave up on that approach a long time ago.
