### ISSUE TITLE
how to add User level Roletags in members list?

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6559]
i am work in Rocket Chat Developer Version as i know Rocket Chat Have role Tags For each user but its show only in user info page not in Members list
i need to add level Name for each users in Members list like 

    admin
    (admin)
----------
    John Doe
    (User)
-----------
    john Smith
    (Moderator)

![2017-04-01_185839](https://cloud.githubusercontent.com/assets/22897987/24580790/e4169228-170e-11e7-8668-0df94c8fd85b.jpg)

im found this code in userinfo template
```
	roleTags: ->
		uid = Template.instance().user.get()?._id
		roles = _.union(UserRoles.findOne(uid)?.roles, RoomRoles.findOne({'u._id': uid, rid: Session.get('openedRoom') })?.roles)
		return RocketChat.models.Roles.find({ _id: { $in: roles }, description: { $exists: 1 } }, { fields: { description: 1 } })

```
with view
```
{{#each roleTags}}
      <span class="tag33" data-role="{{description}}">{{description}}<i class="fa fa-superpowers" aria-
        hidden="true"></i>
        </span>
{{/each}}

```and trying to add in memberlist
================
but no luck .... so what i miss?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
