### ISSUE TITLE
Cannot build latest Rocket.Chat

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#6566]
Rocket.Chat Version: Last commit
Running Instances: 1
DB Replicaset OpLog: No
Node Version: 4.7.3

When I try to build rocket.chat meteor application I get the following error:

```
Attempting to install plugin cordova-plugin-device@1.1.1, but it should have a minimum version of 1.1.4 to ensure compatibility with the current platform versions. Installing the minimum version for convenience, but you should adjust your dependencies.

=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin phonegap-plugin-push@1.6.4 to Cordova project:              
   Cordova error: Variable(s) missing (use: --variable SENDER_ID=value).           
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running
   again with the --verbose option to help diagnose the issue.)
```

Does this SENDER_ID=value have to do with compiling the Cordova.Rocket.Chat app and not the server?  If not, Where do I add my GCM value?

Syirrus

**Comment by qge** [comment]
Have same problem here.

**Comment by sitexa** [comment]
Rocket.Chat Version: Last commit
Running Instances: 1
DB Replicaset OpLog: No
Node Version: 4.8.4

```
WARNING: Attempting to install plugin cordova-plugin-device@1.1.1, but it should have a minimum version of 1.1.4 to ensure compatibility with the current
         platform versions. Installing the minimum version for convenience, but you should adjust your dependencies.
%% support for subdirectories is deprecated and will be removed in Cordova@7
%% Failed to install 'cordova-plugin-googleplus':Error: Variable(s) missing: REVERSED_CLIENT_ID
```

**Comment by wcgcoder** [comment]
Pinging on this one. Wondering what kind of CI Rocket Chat has in place...

I've been unable to build a number of releases from source, having to manually remove katex (for example) from the build in order to build successfully.

Is Rocket Chat being built from scratch each time? It seems like some build artifacts are being cached between builds. While this can make builds faster, it doesn't verify that the project is buildable for others.

This is a recurring problem.

**Comment by TriPhoenix** [comment]
As far as I understand the process, the client-ID (assuming you want to work with the public apps) would probably be gathered from https://github.com/RocketChat/Rocket.Chat.iOS/blob/master/Rocket.Chat/GoogleService-Info.plist

However as we don't need to build the client code right now, an alternative is to build using `meteor build --server-only --directory ../rocketchat-build` which only builds the server application.

**Comment by antgel** [comment]
@reist Might it be that your changes will help here?

**Comment by wcgcoder** [comment]
Thanks @antgel. I should have checked!

Indeed, a number of things are cached. With npm any more, things change on a daily basis, so I guess it's not surprising that things won't build for me.

```

before_cache:
- rm -rf $HOME/build/RocketChat/Rocket.Chat/.meteor/local/log
- rm -rf $HOME/build/RocketChat/Rocket.Chat/.meteor/local/run
- rm -rf $HOME/build/RocketChat/Rocket.Chat/.meteor/local/db
cache:
  directories:
  - "$HOME/node_modules"
  - "$HOME/.meteor"
  - "$HOME/.npm"
  - "$HOME/.node-gyp"
  - "$HOME/build/RocketChat/Rocket.Chat/node_modules"
  - "$HOME/build/RocketChat/Rocket.Chat/.meteor/local"
  - "$HOME/build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.npm"
  - "$HOME/build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/app/node_modules"
  - "$HOME/build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/app/.meteor/local"
```

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this due to the lack of activity. Please open a new issue (and reference the one at hand) if this is still an issue on latest stable.

Cheers
Thomas
