### ISSUE TITLE
Bad refresh of DMs' view - Clicking in the date of a reply message 

### ISSUE THREAD

**Issue by amelieq-c** [RocketChat/Rocket.Chat#6568]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

Tests realised with Rocket.chat Desktop application (version: 2.5.0) and browser client

In a channel with an other user (Direct Messages), reply to a message that you sent. Double-click in the hour of the reply message (it's a link, i.e. 10:50AM). There is a kind of refresh of the chat's view and all messages disappears. It's not possible to see them again, but if you restart the desktop application, they show up again.

No relevant logs

**Comment by MartinSchoeler** [comment]
This bug was fixed on the latest versions. Thanks!
