### ISSUE TITLE
Audio upload with localhost in URL

### ISSUE THREAD

**Issue by xldrkp** [RocketChat/Rocket.Chat#657]
I successfully installed Rocket.Chat on Digital Ocean with `docker-compose up`. After uploading an audio file from the mobile website I discovered `localhost` being part of the URL, so the file could not be played in the browser. When I changed the URL of the audio file to my IP address on Digital Ocean it worked.

**Comment by geekgonecrazy** [comment]
To solve this you need to pass in the correct ROOT_URL environment variable.  Edit the docker-compose.yml file and change the path in ROOT_URL to your Digital Ocean ip.  

Should be good to go.  :)

**Comment by xldrkp** [comment]
Alright! Thanks for your support!

**Comment by geekgonecrazy** [comment]
Awesome!  :)

**Comment by david-mendip** [comment]
I hope that this is the right place to add this, but I am experiencing almost the same issue with Docker using `docker run --name rocketchat -p 3000:3000 --env ROOT_URL=http://stringer --link db -d rocket.chat`. The files are available either on the server (where localhost will work correctly) or by replacing it with `stringer` on a workstation within our local network. 
The installation was downloaded and installed on Friday 4th December 2015. 
What have I missed please?

**Comment by geekgonecrazy** [comment]
@david-mendip can you please check Administration under General and see what is in the SITE URL section?

**Comment by david-mendip** [comment]
Ah, easy when you look in the right place! I did need the fully qualified domain name for the image to then display inline (in a browser or the headless Windows client) whereas the shortened version still worked fine when opening the link via a browser. 

Perhaps it was because that url was used in the first time it was loaded up and I then changed it?

Many thanks for your prompt help. 

I must add that it is looking really good. Very easy to setup and get going too (docker is completely new to me, for instance).

**Comment by geekgonecrazy** [comment]
@david-mendip we're looking at a couple of things to remove that requirement for file uploads.  They are still in the planning stage.

>I must add that it is looking really good. Very easy to setup and get going too (docker is completely new to me, for instance).

Glad to hear!  That's always a concern.  We want to make this as easy as possible to use.

**Comment by long-nguyenxuan** [comment]
> @david-mendip can you please check Administration under General and see what is in the SITE URL section?

thanks for you support, got problem with attachment got localhost link and Google guided me here, 
then I updated Administration/General/Site URL and it works now (Y)
