### ISSUE TITLE
Review use of mizzao/meteor-autocomplete

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6570]
Check if we still need the package copied into our repo or can we use the latest from https://github.com/mizzao/meteor-autocomplete or should we just turn into our own?

**Comment by simonv3** [comment]
This package hasn't been updated in a year, and I feel like the autocomplete functionality in RocketChat isn't that good, so I would argue for either using a different package that does auto-complete a bit better or implementing it ourselves.

**Comment by timkinnane** [comment]
Relevant #10872 - if the package gets reviewed, I think it would be a good opportunity to address long standing experience issues with username autocompletion.
