### ISSUE TITLE
.node_version.txt - ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mixrat** [RocketChat/Rocket.Chat#6579]
The Linux 0.54.2 release found [here](https://rocket.chat/releases/0.54.2/download) is missing the .node_version.txt file. When I tried to run a new install I received this...

```
Exception in callback of async function: Error: ENOENT: no such file or directory, open '/root/Rocket.Chat/.node_version.txt'
```
I copied the .node_version.txt file included in the 0.54.0 release to my 0.54.2 installation and it worked.
Just thought it might need to be fixed.

**Comment by geekgonecrazy** [comment]
@mixrat can you confirm this is still the case?  I just downloaded it and I can see the file is present.

![image](https://cloud.githubusercontent.com/assets/51996/24678275/7fb9c302-194f-11e7-8f04-cb5f04c8a9ea.png)

**Comment by mixrat** [comment]
Hmmm. I do see it now. Maybe it didn't get copied to my system because it was a hidden file. Sorry.

**Comment by geekgonecrazy** [comment]
@mixrat all good! We might need to look at making it a none hidden file to avoid that.

I'll go ahead and close this since resolved.

**Comment by bennlich** [comment]
Hmm. Just ran into the same issue with the 0.65.1 package installed via:
```
curl -L https://releases.rocket.chat/latest/download -o rocket.chat.tar
```
