### ISSUE TITLE
iFrame Login

### ISSUE THREAD

**Issue by salj76** [RocketChat/Rocket.Chat#6581]
Rocket.Chat Version: 0.54
Running Instances: 1
DB Replicaset OpLog:
Node Version:

 Hi has anyone tried the first method of iframe login outlined here https://rocket.chat/docs/developer-guides/iframe-integration/authentication

i.e. To do that you should directly access the Rocket.Chat MongoDB database (using a MongoDB library or driver with the programming language that you have created your login page with) and find/create the user record under the collection users set the services.iframe.token and return via your API.
Is the token a token that my web app generates
or is it produced from calling the Rocket.Chat login API
I use SAML as my auth method
there is no password there fore is it possible to use the login api

**Comment by nzhtrtlc** [comment]
You need to set rocketChat token to your localStorage then you can use it your iframe-integration auth login.

In your own auth system you need to save the user to your own database and rocket chat's database. So they can be synced.

**Comment by pierre-lehnen-rc** [comment]
Closing this as obsolete.
