### ISSUE TITLE
IOS application crash

### ISSUE THREAD

**Issue by nORKy54** [RocketChat/Rocket.Chat#6582]
Rocket.Chat Version: 0.54.2
Node Version: 4.71

The rocketchat  (not rocketchat+) IOS application  crash when playing a mp3 file. I use an iPhone 6S, last public firmware

**Comment by TheReal1604** [comment]
Could you please open an Issue on the iOS Repo?

https://github.com/rocketchat/rocket.chat.ios/issues

Thanks!

**Comment by nORKy54** [comment]
Done.
