### ISSUE TITLE
Ability to add custom slash commands

### ISSUE THREAD

**Issue by JSzaszvari** [RocketChat/Rocket.Chat#6583]
Rocket.Chat Version: 0.52
Running Instances: 6

Hello! :)

Apologies if I missed it, But I've searched around and cant find much.

Is there any way to add custom slash commands at the moment that doesn't involve making a package for the commands?

If not would we be able to investigate adding something similar to mattermost where you can add a slash command from the integrations setup?

Like this: 

![integrations](https://cloud.githubusercontent.com/assets/872463/24651155/17633c54-1970-11e7-8baa-2387996c8638.jpg)

Depending on how difficult this might be I could attempt it, If this is missing would there be anything preventing this from being practical? I'm not the best with coding but I can get by and would be willing to give it a shot - Maybe someone on some random repo somewhere has done this already and we can see how hard it would be to get production ready?

Its a feature that would add real value I think.

On the subject of new features, I think I read something a while back how this would be difficult to implement but I cant remember why - Slacks new "Button" functionality and the ability to embed forms in the chat like surveys 

https://api.slack.com/docs/message-buttons

Would be great for in-line surveys/polling 

![156304720851_29cf7dfbb5af989a4634_1600](https://cloud.githubusercontent.com/assets/872463/24651852/b5b86cba-1972-11e7-9c58-083a59056182.png)

Thanks!
John

**Comment by soundstorm** [comment]
Addition to #5732

**Comment by erlend-sh** [comment]
We're very interested in this feature for use with Discourse. With Slack we have an integration that allows us to export chat transcripts, in cases where a conversation ought to be printed out for the rest of the team to participate in asynchronously.

https://streamable.com/ogub9

**Comment by kaialexanderfischer** [comment]
+100

**Comment by sscholl** [comment]
+1 add from API

**Comment by geekgonecrazy** [comment]
Will now be possible via Rocket.Chat Apps.  

Technically this is solved, just have to wait until we officially turn the apps framework on :)
