### ISSUE TITLE
Markdown links are double escaping

### ISSUE THREAD

**Issue by khobbits** [RocketChat/Rocket.Chat#6586]
Rocket.Chat Version: 0.54.2
Running Instances: 2
DB Replicaset OpLog: Enabled
Docker Image

Creating a markdown style link:

`[A link](https://www.google.co.uk/search?q=broken&q=penguin&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi5rcjV_4rTAhXCPBoKHeuOBcoQ_AUIBigB&biw=1920&bih=1108)`

Creates an unusable link, as the link inserts `&amp;` rather than using & symbols.

**Comment by khobbits** [comment]
Just confirming that this is still a problem in 0.56.0.
& symbols in the link are still being changed to &amp;

**Comment by nowagner** [comment]
This is still a problem for us as well.  It affects a lot of the integrations we have with RocketChat.

**Comment by benaryorg** [comment]
Confirming this is still a (rather annoying) problem.

**Comment by gilbertovb** [comment]
I am having that issue too.
Is there a bypass ?

**Comment by ghosty-be** [comment]
issue still present in 0.69.1 ... very annoying since icinga2 also generates this type of URL's with & in between, so alert url in rocketchat are broken :( 
same issue is mentioned in issue #6719

**Comment by josh0412** [comment]
Issue is still present...
