### ISSUE TITLE
login to same instance with two users names? 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6587]
some how i have two general rooms, and i think this is because somehow i was logged via same instance with Twiter+gmail account  is this possible?

as i logged with gmail account twitter confirmation came and accepted it (associated with email)

![image](https://cloud.githubusercontent.com/assets/12454319/24665482/87da10f6-192b-11e7-9237-48dad2c8e8e9.png)

Rocket.Chat Version: 0.54.2
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by IQ2022** [comment]
i know the issue, user 1 "alphatrader" used gmail to longin , user 2 "alphatrader" used twitter to login, each got different permission

**Comment by geekgonecrazy** [comment]
This is old, no other reports and a lot has changed.  Closing
