### ISSUE TITLE
After a user is removed from a room, redirect him to the home page

### ISSUE THREAD

**Issue by stephane-** [RocketChat/Rocket.Chat#6589]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

Hello, 
When I kick an user from private channel, he receive all new messages. He can't write messages, but can read all messages.

Video : https://codazzi.fr/public/Videos/2017-04-04_18-53-36.mp4

**Comment by MartinSchoeler** [comment]
@stephane- Yes the user keeps in a "Preview" mode of that room, instead the user should be redirected to the home page after a kick
