### ISSUE TITLE
Quote marks in Inline code are interpreted

### ISSUE THREAD

**Issue by doctorwho92** [RocketChat/Rocket.Chat#6592]
Rocket.Chat Version: 0.54.2
Running Instances: 2
DB Replicaset OpLog: 
Node Version: v4.8.1

This inline code, encapsulated in three back ticks:
export HISTTIMEFORMAT="%F %T  "
export HISTFILESIZE=
export HISTSIZE=

turns into:
export HISTTIMEFORMAT=`&quot;`%F %T `&quot;`
export HISTFILESIZE=
export HISTSIZE=

i.e. the quote marks are converted into `&quot;`

**Comment by gdelavald** [comment]
Seems like the issue here is that the single line code block had a special treatment for strings that the multiline did not.

```@handle_inlinecode: (message) ->
	# Support `text`
	message.html = message.html.replace /(^|&gt;|[ >_*~])\`([^`\r\n]+)\`([<_*~]|\B|\b|$)/gm, (match, p1, p2, p3, offset, text) -> ...
```

I think adding that to the `@handle_codeblocks` function should fix this issue.
