### ISSUE TITLE
Dissable Force SSL without Web-Access

### ISSUE THREAD

**Issue by Dani-D** [RocketChat/Rocket.Chat#6599]
Hi,

how can I disable the force SSL-Option without having web access?
Platform: Ubuntu
Installation-Method: Snap
Version: Latest

Greetings from Germany
DaniD

**Comment by tamasgal** [comment]
I ran into the same issue, same setup as DaniD posted (running on Debian Jessy)....

**Comment by sampaiodiego** [comment]
you guys can connect to mongo shell (on the appropriate database) and run:
```javascript
db['rocketchat_settings'].udpate({ _id: 'Force_SSL' }, { $set: { value: false } });
```

hopefully it's not too late
