### ISSUE TITLE
[Feature request] Mute users for X hours and auto-unmute

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#6601]
When muting users as moderator or admin, it would be helpful, if you could optionally set the number hours the user will be muted. Users should get unmuted automatically after X hours when using this option.

**Comment by Nemra1** [comment]
nice one

**Comment by fforrest** [comment]
please consider adding this feature, useful one for admins

**Comment by punkr0ck** [comment]
Any news?

**Comment by marceloschmidt** [comment]
Please move this discussion to the [forums](https://forums.rocket.chat) to check on wider community usage. Thanks.
