### ISSUE TITLE
Iframe eventListeners doesn't work

### ISSUE THREAD

**Issue by nzhtrtlc** [RocketChat/Rocket.Chat#6602]
Rocket.Chat Version: 0.53.0
Running Instances: 1
Node Version: v6.9.5

I want to listen new-message event from rocketChat in iframe. (ref: [here](https://rocket.chat/docs/developer-guides/iframe-integration/events))
I wrote this code to the console while iframe is open and logged in.

> window.addEventListener('new-message', function(e) {
    console.log(e.data.eventName); // event name
    console.log(e.data.data); // event data
});

I can not see the logs while message received or send.
It works only when i type this code

> window.addEventListener('message', function(e) {
    console.log(e.data.eventName); // event name
    console.log(e.data.data); // event data
});

But this listener listens all events. Like room-opened. It its not good.
I want to listen only new-message event.

How can i do that ?

**Comment by TimFau** [comment]
I'm having the same issue. Out of curiosity, do you have iFrame enabled at "Adminstration > Accounts > Iframe"?

**Comment by nzhtrtlc** [comment]
@TimFau  Sure, otherwise i wont be able to even login in.

**Comment by kieran-rocks** [comment]
Better late than never....

You need to listen for the event 'message' and THEN look at the eventName to see if it is equal to 'new-message'. Something like this:

```
// Process iframe events
window.addEventListener('message', (e) => {
	// Process message event
	switch (e.data.eventName) {
		case "click-message-link":
			console.log('click-message-link');
			console.log(e.data.data);
			break;
		case "new-message":
			console.log('new-message');
			console.log(e.data.data)
			break;
		default:
			break;
	}
});
```

**Comment by antgel** [comment]
Closing as ancient, support, and solved. ;)

**Comment by sihingbenni** [comment]
The proposed solution doesn't work at this point of time.
The only events that get triggered no mater what are: "ready", "restoreWindow", "callback", "minimizedWindow"

But no event gets for anything else.

`window.addEventListener('message', function(e) {
    console.log(e); // The raw event (should include all?)
    console.log(e.data); // event data
});`
