### ISSUE TITLE
[BUG] Set Owner

### ISSUE THREAD

**Issue by a5his** [RocketChat/Rocket.Chat#6607]
Rocket.Chat Version: 0.55.0-develop

I am using demo.rocket.chat. 
The `SET AS OWNER` button is throwing an error though the user is made the room owner. The UI is also broken. 

![set-owner](https://cloud.githubusercontent.com/assets/330362/24717676/0920f4e0-1a53-11e7-8471-b384927ec294.gif)

**Comment by TwizzyDizzy** [comment]
Is this still present in latest stable?

Cheers
Thomas

**Comment by a5his** [comment]
@TwizzyDizzy Looks like issue has been resolved. Verified with version `0.63.3`. So it should be working in latest stable. Closing this issue.

👍
