### ISSUE TITLE
Combining and minimizing impact of join/parts

### ISSUE THREAD

**Issue by acamarata** [RocketChat/Rocket.Chat#661]
All joins and parts of channels could be made less prominent and by code dynamic so that if there is no talking then it continues to collate (like on IRC Cloud and other chat apps) such as:

"john, joe, rick have joined / bob has left"

and if no talking then adding names to that single line update on the join/parts and if there is talking then starting anew.  Attached is screen shots from how IRC Cloud does it (taken from #Meteor on Freenode)...

![screen shot 2015-09-02 at 20 00 18](https://cloud.githubusercontent.com/assets/277910/9631782/6e7f81c8-51ad-11e5-8308-fd11cdcb2009.png)
![screen shot 2015-09-02 at 20 01 03](https://cloud.githubusercontent.com/assets/277910/9631784/70555464-51ad-11e5-8747-ec4db9e0f9ad.png)
##

**Comment by AdrianoCahete** [comment]
I think this needed to be an option. In my case, i like separate user info messages.
Per user option is good.

**Comment by geekgonecrazy** [comment]
We don't currently even show leave at all.  But I agree.  Especially if they happen back to back they should be joined visually.

**Comment by alfredbez** [comment]
It would also be nice to disable those messages entirely like mentioned in #2180

**Comment by bott0r** [comment]
I for one are a huge fan of the old school IRC chat behavior. Especially with the time stamp being displayed at all times. I'd really like to see some possibility to customize how the chat looks. i.e. user individualized schema.

![irc style](https://cloud.githubusercontent.com/assets/17119942/13570142/bd574180-e46c-11e5-8ce6-d5ecfd365d61.PNG)

**Comment by engelgabriel** [comment]
Closed in favor of https://github.com/RocketChat/Rocket.Chat/issues/906
