### ISSUE TITLE
Exception while invoking method 'mailMessages' TypeError: Cannot read property 'defineLocale' of undefined   at eval (<anonymous>:37:20)

### ISSUE THREAD

**Issue by danielo926** [RocketChat/Rocket.Chat#6611]
Rocket.Chat Version:  0.54.2
Running Instances:   1
DB Replicaset OpLog: Disable
Node Version: 4.7.3

[34mI20170406-13:44:06.724(2) Sending messages to e-mails:  [ 'daniel.asdasdas@sadsad.pl' ] 
[34mI20170406-13:44:06.738(2) Exception while invoking method 'mailMessages' TypeError: Cannot read property 'defineLocale' of undefined   at eval (<anonymous>:37:20)   at eval (<anonymous>:10:4)   at eval (<anonymous>:11:2)   at [object Object].Meteor.methods.mailMessages (/opt/Rocket.Chat/programs/server/packages/rocketchat_channel-settings-mail-messages.js:135:27)   at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1095:26)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1817:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:755:85  

How do repair this error?

**Comment by localguru** [comment]
see this on 0.56.0 too

**Comment by sampaiodiego** [comment]
duplicated of #5797
