### ISSUE TITLE
[Feature Request] Posibility to hide email in LiveChat

### ISSUE THREAD

**Issue by dhpowrhost** [RocketChat/Rocket.Chat#6612]
Rocket.Chat Version: 0.52.0

Often times you do not want customers to write directly to people, but rather to the support mail. Later versions of Rocket.Chat shows your email in LiveChat to Guests. We need an option to hide the email.

**Comment by mrmayfield** [comment]
Why was this closed? Is there a way to do this now?

**Comment by jszaszvari** [comment]
Could probably use a css Override in the admin section to hide it. 

Also this issue is not closed. It's still open. It doesn't say it was closed anywhere.

**Comment by grandsla** [comment]
css would only help in a web situation email would still be visible to desktop and mobile clients.For me this makes rocket unusable.  Urgently need a toggle to suppress email from all but admins and possibly mods

**Comment by appdoodle** [comment]
Yes. This is important information leak issue. It will be great if it can be fixed in the next release.

**Comment by icosamuel** [comment]
Since it's a requirement for my team as well, I started working on this issue.
Here is [my first commit](https://github.com/icosamuel/Rocket.Chat/commit/4eaaa9e2eee777286afe0adb039c5fcb595a8a98)

**Comment by grandsla** [comment]
I'm new to the whole github deleoper community thingy but I assume that the
work you have done will solve our problems? How long does it take to get
this into a release?
Excuse my ignorance.
Thanks

Steve

**Comment by icosamuel** [comment]
@grandsla Im affraid that this issue does not cover all email viewing in rocketchat, but only in the context of the [Live Chat package](https://rocket.chat/docs/administrator-guides/livechat/).

I'm a new contributor on this project, so I don't know how much time a pull request can take to get in a releasable build. But it's definitely not under a week.

**Comment by sampaiodiego** [comment]
awesome @icosamuel .. please have in mind you can open a pull request while still working on this if you want to ask any question related to the code you're writing. I'll be more than happy to help you =)

**Comment by tuzzmaniandevil** [comment]
:+1:
