### ISSUE TITLE
"Connecting..." message appear every 10 seconds when using Caddy as a proxy

### ISSUE THREAD

**Issue by Gerporgl** [RocketChat/Rocket.Chat#6618]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: OpLog Disabled
Node Version: 4.7.3
Caddy Version: 0.9.5

When using the client interface (any of them: web, desktop, mobile) the "Connecting..." message bar at the top with show up briefly (flashes) at an intervals of about 10 seconds.
This only happen when Caddy is setup as the proxy.

I followed the Caddy instruction found in the documentation. Here is what my Caddyfile looks like:
http://rc.example.com, https://rc.example.com
        proxy / 127.0.0.1:3000 {
         websocket
         transparent
        }

If I use nginx as the proxy, or if I access rocket chat directly on port 3000, it works fine, I don't see the connecting message.
Also, even when this message show briefly, Rocket Chat and its core functionalities appear to be working fine. But it is still very annoying.

I haven't seen any mention of such issue, but I've done at least 2 installations on different servers (AWS and another local machine, one with Mint 17 and the other Ubuntu 16.04) and got the same issue.

**Comment by graywolf336** [comment]
Please see: https://github.com/mholt/caddy/issues/1562#issuecomment-291609361

**Comment by Gerporgl** [comment]
I see, disabling Caddy's timeouts solved my issue.

I was suspecting something related to timeouts, I was just being dumb here since there was documentation that seemed to tell how to configure Caddy, so I just followed that without really thinking. Thanks a lot for your time.

**Comment by graywolf336** [comment]
No problem, I experienced it as well so I know the feeling. :)
