### ISSUE TITLE
Enable modular addition of additional fly-in panels as a set of 'tabs' on the right

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#662]
Ideally each new fly-in can be added as an optional Meteor package.  

This allows Rocket.Chat core to maintain control over the UI/UX consistency and design choices of the tabs.  Also allows some of the Chat Op's features to be incrementally added to core even before 1.0. 

This is going to become one of our _Wordpress-like_ extension points, some careful thought needed for the developer interface.   It has to be very simple and straightforward, and well documented.  It needs to be easy to understand for JavaScript developers with no intention to ever learn Meteor.

Plan small (plug-ins), as well as BIG.  It should be possible to fly-in and work with a panel that contains a system that is 10x the size of Rocket.Chat in terms of code size/complexity (example:  a legal document view/edit/processing system in an international law firm's office triggered on a `/XX dossier #`  command and fetched by a bot).

**Comment by leefaus** [comment]
So many :sparkles: here!  I will be watching this one.

**Comment by Sing-Li** [comment]
For those pioneers who want to give this feature a spin (work in progress, fly-in works, but panel contents don't work yet):

`git clone https://github.com/RocketChat/Rocket.Chat.git -b chatops-ui-rightpanel-flexchrome --depth 1`

then

`cd Rocket.Chat`

then 

`meteor`

Thanks to @AdrianoCahete  and @geekgonecrazy.     We are cooking with gas!

**Comment by marceloschmidt** [comment]
Tabs are now enabled. To add a new tab button, type: `RocketChat.TabBar.addButton({ id: 'button-id', title: 'buton-title', icon: 'button-icon', template: 'template-to-be-loaded-into-flex', order: buttonOrderPosition })`
