### ISSUE TITLE
voice channels like discord

### ISSUE THREAD

**Issue by Majaspic** [RocketChat/Rocket.Chat#6622]
would be an awesome feature :)

**Comment by Nemra1** [comment]
make screen of that

**Comment by JohnnyKing94** [comment]
There is another issue opened about that... I link it: https://github.com/RocketChat/Rocket.Chat/issues/3661

**Comment by zzzkeil** [comment]
+1

**Comment by ed5avage** [comment]
This would be really great 😄

**Comment by marceloschmidt** [comment]
Duplicate of #3661
