### ISSUE TITLE
Wrong Keyboard Shortcuts impact local language usage. 

### ISSUE THREAD

**Issue by killstyl** [RocketChat/Rocket.Chat#6623]
Rocket.Chat Version: 0.54.2 and 0.53.0
Running Instances:  0.54.2 - 1 and 0.53.0 - 6
DB Replicaset OpLog: 0.54.2 - Disabled  0.54.2 - Enabled
Node Version:

Key combination "Right Alt+K" does the same as "Ctrl+K"  
This impacts usage of local language (Latvian).  We use "Right Alt" to get specific letters like "ķ, š, ģ, ...."

**Comment by MartinSchoeler** [comment]
@karlprieb maybe we can make the the shortcut customisable via user preferences, what do you think?

**Comment by geekgonecrazy** [comment]
Closing in favor of #6374
