### ISSUE TITLE
Private chatroom block bug 

### ISSUE THREAD

**Issue by 12test12** [RocketChat/Rocket.Chat#6624]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.1

I found another bug. If you block yourself in a chatroom then unblock the other person then the room is blocked no one can write.
To solve this problem you have to block yourself and then unblock yourself.
Could you add that no one could block themselves.

![privateroombug](https://cloud.githubusercontent.com/assets/23378492/24791860/11dcf06e-1b7c-11e7-907f-3b781c1d5ee6.gif)

**Comment by Nemra1** [comment]
samething her

**Comment by DanManB** [comment]
I like this feature.

**Comment by 12test12** [comment]
Rocket.Chat Version: 0.55.1
Running Instances: 1
Node Version: 4.8.1

why did you closed it. I have it still.
