### ISSUE TITLE
Attachments in incoming WebHook are not displayed

### ISSUE THREAD

**Issue by JohnDorianMD** [RocketChat/Rocket.Chat#6625]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

Since early this year (maybe with the update 0.50.1), all of our incoming WebHook attachments are not displayed. Even if you create a new one, the example already shows an empty attachment. Anyone else having that kind of issue?

![rocket chat 2017-04-07 11-06-43](https://cloud.githubusercontent.com/assets/7889192/24793804/aeca1a12-1b83-11e7-8db0-7dfa80425cee.png)

**Comment by graywolf336** [comment]
If you click on the arrow of the attachment, does it show the content?

**Comment by JohnDorianMD** [comment]
No, it does not. The arrow stays as is.

**Comment by geekgonecrazy** [comment]
I believe this is now fixed.

Going to go ahead and close this.  

Feel free to move discussion to [forum](https://forums.rocket.chat) in the community support category
