### ISSUE TITLE
Periodic HIGH Load

### ISSUE THREAD

**Issue by dmeier86** [RocketChat/Rocket.Chat#6628]
Rocket.Chat Version: latest 45

I've running RC on an C4.x4large AWS CentOS7-Instance ATM.
It has 16 Cores, so i have 16 SystemD Scripts and an Reverse-Proxy in Nginx.

Every hour all those Cores get to 100% and the chat (login, typing, chatteing) freezes.
So.. what is this?
In meantime everything seems to work...

**Comment by localguru** [comment]
Sounds to me like some cron job? What's top saying? Did you check processes at that time?

**Comment by neoangin** [comment]
This could be know issue of ldap sync (i have the same issue on my env). During this ldap sync logs show that not only ldap info is synced but also chat history and all rooms state is being synced among all online users. The workaround is to start your apps with a time gap (10-15 mins) to prevent CPU spikes.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as there's not enough information to act on. Since this is rather old, please try with latest stable and open a new issue, if that's still a problem (and maybe reference the issue at hand).

Cheers
Thomas
