### ISSUE TITLE
Can't see New Messages

### ISSUE THREAD

**Issue by dmeier86** [RocketChat/Rocket.Chat#6630]
Rocket.Chat Version: 0.54.2
Running Instances: 16
DB Replicaset OpLog:
Node Version: 

users get an mail-notification if there are still logged in.
they don't see the message - sometimes relogin helps.

is this a bug in my version or is it because we're running 16 rocketchat nodes in one mongoDB?

**Comment by geesper** [comment]
Did you find an answer to this?

Is your mongodb running a replicaset? What is your MONGO_OPLOG_URL set to?

**Comment by geekgonecrazy** [comment]
This is typically because instances can’t communicate setting INSTANCE_IP usually fixes in multi instance setups
