### ISSUE TITLE
Show all channels

### ISSUE THREAD

**Issue by Buzzele** [RocketChat/Rocket.Chat#6638]
Rocket.Chat Version: 0.43

Hi,

is there a way to show all channels by default even when an user is not registered in this channel?

Best Regards
Buzzele

**Comment by Rohlik** [comment]
Yes, you can try on https://demo.rocket.chat
Click on `More channels...`. How simple, right?

**Comment by Buzzele** [comment]
Yes, its really simple. But i have written "BY DEFAULT". Normally that is really simple to read this two words, isnt it?

**Comment by Nemra1** [comment]
you can creat blank page and add all channels in the content like this
![2017-03-26_160956](https://cloud.githubusercontent.com/assets/22897987/25179284/80e56da6-2509-11e7-9af8-0ad70262e72c.jpg)

**Comment by sampaiodiego** [comment]
we have implemented a `Directory` feature for this..
