### ISSUE TITLE
[Error] Unable to watch path

### ISSUE THREAD

**Issue by JulianKingman** [RocketChat/Rocket.Chat#6639]
Rocket.Chat Version: Latest dev (2749206da3b433f792ce151008f67f06ff2e6aad)
Running Instances: just localhost
DB Replicaset OpLog: ?
Node Version: 4.4.4

To replicate: download rocket chat, run `meteor npm i -S`, then `meteor`
Already tried re-installing meteor, which is at version 1.4.2, I believe.

Here's the error log:
````bash
[[[[[ ~/Desktop/Rocket.Chat ]]]]]             

=> Started proxy.                             
=> Started MongoDB.                           
/Users/Julian/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:77
      this.handle = binding.watch(this.path);
                            ^

Error: Unable to watch path
    at Error (native)
    at HandleWatcher.start (/Users/Julian/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:77:29)
    at /Users/Julian/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:53:27
    at FSReqWrap.oncomplete (fs.js:82:15)
MacBook-Pro-4:Rocket.Chat Julian$ npm -v
4.4.4
MacBook-Pro-4:Rocket.Chat Julian$ 
````

**Comment by JulianKingman** [comment]
Huh, running in verbose mode seemed to work... Should I close?

**Comment by JonLev** [comment]
@JulianKingman I have the same problem on my machine. The file watch is generally linked to fsevent and it's confirmed by the error message I think.
After some dig-up on the pathwatcher module, it redirects on https://github.com/atom/node-pathwatcher/issues/29 then on https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#exception-typeerror-unable-to-watch-path that seems to say we need to increase the number of file watcher by default (the default one is 10240 so it seems Rocket.Chat have a looot of files to watch).

I followed this article http://krypted.com/mac-os-x/maximum-files-in-mac-os-x/ to increase the limit and it seems to work.

My question though is: is there anyway to start the app without the watch, that seems to be the case in the verbose mode. (by the way, I would like to know how you do start the app in verbose mode)

**Comment by JulianKingman** [comment]
meteor --v

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
