### ISSUE TITLE
Internal Hubot uses obsolete script repository

### ISSUE THREAD

**Issue by wohali** [RocketChat/Rocket.Chat#6640]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

The Internal Hubot admin settings page says:

> Please enter a comma separated list of scripts to load from `https://github.com/github/hubot-scripts/tree/master/src/scripts`

However, the top-level README for that repository reads:

> *DEPRECATED*, see https://github.com/github/hubot-scripts/issues/1113 for details

which in turn says:

> IMPORTANT: No longer accepting new scripts to this package, create external packages instead 

Reading through the history, the hubot-scripts repo was already deprecated in 2015!

On top of this, many of the scripts don't even work anymore, not having been maintained for 3 years or more - see #5952 for details.

Please revisit how scripts can be added to the internal Hubot without using this deprecated (and mostly non-functional) repository.

**Comment by jszaszvari** [comment]
Yes it has not been used for a very long time.

https://github.com/github/hubot-scripts/blob/master/CONTRIBUTING.md


The scripts don't get loaded from that repo anymore they are loaded from
npmjs.com

**Comment by geekgonecrazy** [comment]
Yes currently it uses a preseeded folder of scripts compiled in.


We are working on resolving this.  The issue here is we can't just let you specify any random script from npm.  Because we won't be able.to handle the installation of the scripts.

It'll have to only point to scripts you've dropped into a folder.

We have an issue open for setting an external folder where you can add your own scripts

**Comment by wohali** [comment]
Is there a list of which scripts are in the preseeded folder anywhere? 
The help text in the settings dialogue is definitely misleading at the 
very least. 

Can you point me to the ticket for the replacement setup as well? 

Thanks for your responses!

**Comment by Rohlik** [comment]
Default scripts can be found here: `rocketchat/programs/server/npm/node_modules/meteor/rocketchat_internal-hubot/node_modules/hubot-scripts/src/scripts/`
So, if you want add new one, just put it there and activate in web `http://your_chat/admin/InternalHubot`.
But every RC upgrade will remove your custom scripts!

**Comment by wohali** [comment]
Thanks - unfortunately I deploy using Docker so I won't be able to leverage this approach easily. And it still doesn't show me what the default list of scripts is from anywhere in this repo, which is what I was looking for.

**Comment by jszaszvari** [comment]
Mount a local folder on the docker host/storage into 

/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_internal-hubot/node_modules/hubot-scripts/src/

Then you can just pop your choice of scripts in there the scripts in there.

**Comment by wemu** [comment]
Hello

a lot of the packaged hubot scripts would already be enough for a lot of things. 

are there plans to update at least those? I've tried a few and a lot of them don't do anything or require environment settings (bing api key for a deprecated api) that are unclear to me where to put them.

there are a lot of scripts. my main focus was search, images, youtube, maps (google or bing). what people use the most :)

**Comment by jszaszvari** [comment]
@wemu the environment variables are set in the same place you set MONGO_URL, ROOT_URL and the PORT url at the time of deployment / startup

**Comment by wemu** [comment]
ah I see. Thanks! I'll try some more of the scripts - quite fun 👍 
yet working versions for google and google images would be much cooler :D

**Comment by teamfighter** [comment]
I have question, too.
How can I make internal hubot working?
I have clean install of rocket chat, I have enabled Internal Hubot in settings and installed with npm install -g  hubot-rocketchat
rocket.cat user seems to be online, and I have that in my log files:
`[Wed May 10 2017 10:59:16 GMT+0000 (UTC)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
Loaded megusta.coffee`
Looks like scripts are being loaded.
But if I am writing, for example, "hello" to rocket.cat user, it doesn`t respond.

**Comment by Rohlik** [comment]
@teamfighter Internal hubot is integrated, so you don't need install anything after you install RC.

**Comment by teamfighter** [comment]
@rohlik
That s great, but why it is not working?

**Comment by wemu** [comment]
is the bot invited to the channel? "bot help" does nothing? is the bot using a username that exists in the users list? does that user have proper permissions?
all I had to do was send a @rocket.cat hello to get the bot into the channel to interact with.

**Comment by teamfighter** [comment]
@wemu
Thanks! It started working after I have invited bot to channel)

**Comment by Rohlik** [comment]
Is this already resolved with https://github.com/RocketChat/Rocket.Chat/pull/7095 ?
