### ISSUE TITLE
Notification about new message but user doesn't exist

### ISSUE THREAD

**Issue by lukmarcus** [RocketChat/Rocket.Chat#6641]
I have problem on https://steemit.chat . In section "private messages" I have notification about new message from user, but that user no longest exists (he was deleted). I can't read it or delete it.

**Comment by subham103** [comment]
Can anyone tell me how we can reproduce this issue?

**Comment by sampaiodiego** [comment]
I don't this is an issue anymore.. 

I'll close for now.. If someone can still reproduce it, I'll open again.
