### ISSUE TITLE
I don't know Custom Oauth....

### ISSUE THREAD

**Issue by Kim-Goon** [RocketChat/Rocket.Chat#6643]
Rocket.Chat Version: 0.54.2

I'm trying to integrate RocketChat into our web-site.
I coded Oauth server part in my web-server. (/authorize, /token, and /me)
It operated very well. my Oauth <-> Rocket.chat Custom Oauth 

but, i don't know "/me" method send to rocket.chat ....
what i send to rocket.chat to login( & join) ????
id? email? nickname?

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
