### ISSUE TITLE
Phone and Mail Link

### ISSUE THREAD

**Issue by lw-schick** [RocketChat/Rocket.Chat#6645]
# Feature Request

When I am in the Member list and choose a user i get the user with avatar, telephone number, email etc.

It would be really nice if RocketChat could provide a link for the phone number (tel:12345) or mail address (mailto:mail@domain.com).

Rocket.Chat Version: 2.6.1

**Comment by Rohlik** [comment]
Similar to https://github.com/RocketChat/Rocket.Chat/issues/4332

**Comment by theorenck** [comment]
Hey @lw-schick, we have it for email but for the phone you could use a custom field. Thanks!
