### ISSUE TITLE
move major buttons 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#6656]
i think its better to move these buttons away, as sometimes, using phone and you click on make ADMIN or Owner by mistake very easily.. i think we should move it away.
![image](https://cloud.githubusercontent.com/assets/12454319/24911007/8b94bd9c-1e97-11e7-9e1b-0caa6a91bd7e.png)

Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by Rohlik** [comment]
Or just add some confirmation dialog.

**Comment by geekgonecrazy** [comment]
The redesign moved all of these.  Going to go ahead and close :)
