### ISSUE TITLE
Different Emotion/Icon Style

### ISSUE THREAD

**Issue by lw-schick** [RocketChat/Rocket.Chat#6657]
I would like to have a different emotion style - I don't like the current style. Something like iOS and Andriod and looks better...

A choice like [here](http://unicode.org/emoji/charts/full-emoji-list.html) would be cool.

Rocket.Chat Version: 2.6.1

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #1838.

Cheers
Thomas
