### ISSUE TITLE
Error: [Can't find migration version 91]

### ISSUE THREAD

**Issue by phoefflin** [RocketChat/Rocket.Chat#6662]
Rocket.Chat Version: 0.54.2
Running Instances:  1
DB Replicaset OpLog:  Disabled
Node Version:  v4.8.2

After a docker pull to the latest version (0.54.2) today the startup of the new container fails with an migration error. Downgrade to 0.54.0 didn't solve the issue.

docker logs output:
```
Will load cache for users
664 records load from users
Will load cache for rocketchat_room
2728 records load from rocketchat_room
Will load cache for rocketchat_subscription
9348 records load from rocketchat_subscription
Will load cache for rocketchat_settings
501 records load from rocketchat_settings
Updating process.env.MAIL_URL
Will load cache for rocketchat_permissions
70 records load from rocketchat_permissions
Will load cache for rocketchat_roles
9 records load from rocketchat_roles
ufs: store created at
ufs: store created at
Exception in callback of async function: Error: [Can't find migration version 91]
  at Object.Migrations._findIndexByVersion (/app/bundle/programs/server/packages/rocketchat_migrations.js:405:8)
  at Object.Migrations._migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:272:22)
  at Object.Migrations.migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:201:20)
  at meteorInstall.server.startup.migrations.xrun.js (/app/bundle/programs/server/app/app.js:4696:24)
  at fileEvaluate (packages/modules-runtime.js:197:9)
  at require (packages/modules-runtime.js:120:16)
  at /app/bundle/programs/server/app/app.js:9509:1
  at /app/bundle/programs/server/boot.js:303:34
  at Array.forEach (native)
  at Function._.each._.forEach (/app/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
  at /app/bundle/programs/server/boot.js:128:5
  at /app/bundle/programs/server/boot.js:352:5
  at Function.run (/app/bundle/programs/server/profile.js:510:12)
  at /app/bundle/programs/server/boot.js:351:11
```

**Comment by phoefflin** [comment]
seems like somehow the migration id was wrong. In the git checkout of tag 0.54.2 i could only find the migration files up to server/startup/migrations/v090.js. For a test i updated the version number in the migration collection to 90 and the instance came up again:

```
use rocketchat
db.migrations.update({_id: 'control'},{$set:{locked:false,version:90}})
```

Any ideas how that migration version 91 was introduced?

**Comment by geekgonecrazy** [comment]
@phoefflin which docker image are you using?

**Comment by phoefflin** [comment]
we are using the official rocket.chat image (https://hub.docker.com/_/rocket.chat).

**Comment by sampaiodiego** [comment]
@phoefflin have you managed it?

**Comment by phoefflin** [comment]
@sampaiodiego  yes, after some digging I managed to get the instance up by manually updating the migration version number in mongo to a number matching the rocket.chat version we were running at the time (see https://github.com/RocketChat/Rocket.Chat/issues/6662#issuecomment-293445049). It is still unclear though how this wrong migration number made its way to mongo.

**Comment by mmarek** [comment]
I have similar issue with 97 migration.
I am running snap 0.56.0 on Ubuntu 15.04

anyway to fix it?

**Comment by sampaiodiego** [comment]
@mmarek please see https://github.com/RocketChat/Rocket.Chat/issues/6662#issuecomment-293445049

@phoefflin if you try a higher version of rocket.chat and then downgrade, this could happen..

**Comment by mmarek** [comment]
i am running snap version and cannot find migration files

**Comment by nebajoth** [comment]
I am also running the snap version, and having the same issue with migration version 98. Is there a fix?

**Comment by soporteSL** [comment]
@nebajoth @mmarek 

I was having the same issue. It seems to be the code version, it wasn't using the update. 
I just modified the link to point to the new version and restarted all services (or restart the server) 

Try this
cd /<snap-dir>/<rocketchat-dir>/ 
(in standard ubuntu 16 snap installation the path is /snap/rocketchat-server)

Check version links
ls -las 
0 drwxr-xr-x 11 root root  547 may 16 10:10 653
0 drwxr-xr-x 11 root root  535 may 16 22:10 671
0 drwxr-xr-x 11 root root  535 jul  3 18:56 801
0 lrwxrwxrwx  1 root root    3 jul  5 02:07 current -> 671

modify the link to the latest code version.
rm -f current && ln -s 801 current

**Comment by nebajoth** [comment]
Unfortunately this seems to have broken it more (in that I cannot get a functional rocketchat server when I revert to the way things were before attempting the changes).

**Comment by geekgonecrazy** [comment]
I would very very strongly recommend not manually changing the links your self if at all possible.  This could mess up snapd's process.  In the future I would recommend using `sudo snap refresh rocketchat-server`  Or `sudo snap refresh rocketchat-server --revision=801`

Though note.. if the latest in the stable channel is 671 its going to install 671 next release.

But this should no longer be happening.  All should be good going forward.

**Comment by soporteSL** [comment]
@geekgonecrazy 
Thank you for the advise, I killed all proceses before doing the change.
