### ISSUE TITLE
Getting UserId using REST API

### ISSUE THREAD

**Issue by LiorHaim** [RocketChat/Rocket.Chat#6663]
Rocket.Chat Version:  0.49

Hey all,
I'm trying to use the REST API to invite/remove users from groups and channels. In order to do that (using the channels/groups.kick and channels/groups.invite APIs), I need to send the userId.

I hold the usernames of all the users, but not the userId. The only way I see at the moment is to use the users.info API which retrives ALL the users information, and then I need to filter using the username - which seems too much work for just getting the userId of a specific user.

Is there any other better way to get the userId by using the username?

Thanks.

**Comment by graywolf336** [comment]
You can pass in the username on latest versions: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/helpers/getUserFromParams.js
