### ISSUE TITLE
Subscription stream-notify-user/event in Real-Time API always make the 'change' response

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#6664]
Rocket.Chat Version: 0.54.2
Meteor-client: `python-meteor`

As in Title. I'm writing a bot in Python. If I subscribe to `stream-notify-user/event` I get the `change` response from `Meteor Client`. The problem is that the change response makes a `Key Error`, because there is no such key in collection. We have never `added` it, because every single message is `changed`.
Any ideas?

**Comment by ggazzo** [comment]
`stream-notify-user` is not a pure publication from meteor, we call 'streamer' the server does not control if the user has the info or not, that way we always send 'changed'
