### ISSUE TITLE
Direct-Messages Real-Time API 

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#6665]
Rocket.Chat Version: 0.54.2

I can't find in `Real-Time API `option to send a direct message to specified user by his `username`(to his direct room for example` SendDirectMessage(message, username)`). There is only way to send a message with the `room_id`, but we do not have it when the room has not been `opened` before.
Moreover we can only open the room when we know it's `room_id`.

**Comment by graywolf336** [comment]
Closing as sending a direct message to someone is a two step process via the real time api:

1. Call `createDirectMessage` as the user who is creating and then passing in the username of the person you want to create a direct message room with.
2. Use the returned room id to then send a direct message.

**Comment by monspid** [comment]
It works, but it is not mentioned in documentation

**Comment by jszaszvari** [comment]
@monspid As this is a open source project, if you feel like something is missing that should be there, and you have the answer for, please feel free to update the documentation by using the "Edit on GitHub" button.

![image](https://user-images.githubusercontent.com/872463/29465245-fc3cb352-847b-11e7-877c-7c3098f8460e.png)
