### ISSUE TITLE
Problem with Changed Room Topic / Description

### ISSUE THREAD

**Issue by izzyu91** [RocketChat/Rocket.Chat#6667]
When changing a room topic or description there is the following in the "chat protocol" instead of the actual topic / description:

Das Thema des Raums wurde von izzyu91 zu __room_topic__ geändert
Raumbeschreibung geändert auf __room_description__ von izzyu91

We use the german language in the interface.

Rocket.Chat Version: 0.55.0-rc.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.0

**Comment by Sing-Li** [comment]
Duplicate #6661  ?

**Comment by MartinSchoeler** [comment]
Yes this is a duplicate
