### ISSUE TITLE
Link previews not working

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6669]
Rocket.Chat Version: 0.54.2

Me and some of my users noticed that link previews are not working. I am on Mozilla Firefox (ver. `53.0b10`). The other user who noticed the same problem is also on FF.

I have not been able to test this on any other browser. So, I am wondering: is anyone else having the same issue?

**Comment by DalePayman** [comment]
Your DNS is working properly?

**Comment by k0nsl** [comment]
Yes, @DalePayman, the DNS is working fine.

**Comment by k0nsl** [comment]
Upgrading to Rocket.Chat `0.55.0` solved it.

**Comment by atirjavid** [comment]
I'm having this issue on 0.59.4 -  None of the posted links generate a preview.

**Comment by pipozzz** [comment]
Hi, when I dropped rocketchat_oembed_cache , embed preview is not working. Can you advise me some workaround ?

Thanks in advance.
