### ISSUE TITLE
Private to Public makes channel inaccessible

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#6675]
Rocket.Chat Version: present at least from 0.50.0 to our current 0.55.0-rc.2

![image](https://cloud.githubusercontent.com/assets/51996/24985247/a42877f0-1fb8-11e7-98cd-c60ab2209fd3.png)

Channel is in this state on the demo server: https://demo.rocket.chat/channel/test-private-to-public

Steps to reproduce.
1. Create the channel as private
2. Do some stuff (probably not required)
3. Switch it to public
4. Try to join the channel from a user not a member of the channel.  Either by searching for it or just going directly to the link like above ^

It seems to only be an issue on the web client.  At least reported that the native iOS does not have this issue.

**Comment by rodrigok** [comment]
It's a problem with server side cache, trying to find why

**Comment by geekgonecrazy** [comment]
:+1: I haven't been able to confirm if the mobile apps can access.  But it's been reported by other users that they can join via the  native iOS app.

**Comment by rjones-lf** [comment]
I can join on the iOS app and the desktop app on MacOS.
