### ISSUE TITLE
File Upload UI from mobile (cordova) broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6676]
Rocket.Chat Version: demo

Hey guys,

the file upload gui seems really broken with cordova at the moment. (from an UI perspective, its functional! 😆 )

![2017-04-13 06-42-00 3869](https://cloud.githubusercontent.com/assets/5877910/24993028/ca886e5c-2024-11e7-8d0b-7a8e797adfce.png)

I know that the native app is now public, but until it supports all the features we have in cordova (core features like who is in the channel, create new channels..) we have to use the cordova app on some projects. So there should be some compatibility for both worlds.

**Comment by teamsoo** [comment]
This should be fixed by  https://github.com/RocketChat/Rocket.Chat/pull/7404 and https://github.com/RocketChat/Rocket.Chat/pull/7376

**Comment by MartinSchoeler** [comment]
Yes fixed by #7404 and #7376
