### ISSUE TITLE
How can I change environment variable ROOT_URL when using snap package?

### ISSUE THREAD

**Issue by ogra** [RocketChat/Rocket.Chat#6691]
Rocket.Chat Version: 0.54.2
Running Instances: 
DB Replicaset OpLog:
Node Version:

I installed Rocket.Chat by

    snap install rocketchat-server

on Ubuntu 16.04 LTS.

How can I change environment variable `ROOT_URL` so that the server runs in a subdirectory?
I tried editing /etc/environment and /etc/systemd/system/snap.rocketchat-server.rocketchat-server.service as shown below, but they don't work. `ROOT_URL` with a running server is still `http://localhost` when I check it by the following command.

    sudo od -S1 -An /proc/2730/environ

(2730 is node server's pid.)

/etc/environment

    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
    ROOT_URL="https://live.oguradio.com/rc/"

/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service

    [Service]
    EnvironmentFile=/etc/rocketchat_envvars.txt

/etc/rocketchat_envvars.txt

    ROOT_URL="https://live.oguradio.com/rc/"

**Comment by rivertam** [comment]
I'm also looking to see how one can change an environment variable, though in my case I would like to specify an external mongo database.

For your usecase, I believe you should be using nginx or something similar, and you can use it to proxy to the rocketchat server.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by nickbroon** [comment]
This looks like it's probably related to #4971

**Comment by LuluGO** [comment]
Hey, you can change it using this now https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-change-other-environmental-variables-in-my-snap

**Comment by githubber** [comment]
While this page (https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-change-other-environmental-variables-in-my-snap) points out that changing env variables is possible, it doesn't help with the syntax on changing the site_url.

**Comment by AdriWild** [comment]
It doesn´t work for me
