### ISSUE TITLE
Where Is Bundle Folder In Archived Releases?

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#6693]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: No
Node Version: 4.5

I am trying to set up a new server in a test environment with 0.54.2 by following the instructions https://rocket.chat/docs/installation/manual-installation/ubuntu/.

I performed a `curl -L https://github.com/RocketChat/Rocket.Chat/archive/0.54.2.tar.gz -o rocket.chat.tgz` and noticed that I was not given a /bundle folder. There isn't a /programs/server folder where I perform `npm install`.

If I follow the instructions and perform `curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tg`, I receive v0.55.0-rc.5

Where can I find the proper download so I can run 0.54.2. The reason for this is based on the assumption that v0.55.0-rc.5 is a pre-release and I would like the latest "release" that should be stable.

Please advise otherwise.

**Comment by Prakharsvnit** [comment]
@richardwlu you can find related bundle over [here.](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.54.2/)

**Comment by richardwlu** [comment]
@Prakharsvnit Downloading the tar.gz there does not provide a `bundle` folder.  Unless I am missing something here?

**Comment by Prakharsvnit** [comment]
If you're trying to setup test environment in Ubuntu you must follow the instructions given[here](https://rocket.chat/docs/developer-guides/pre-requisites).  the instructions that you were following are for deployment, not for testing purpose.

**Comment by richardwlu** [comment]
I see where you're coming from; however, I would like to test as I would deploy it. I am not looking to do a quick start. I would like to replicate what I am doing in production. 

Do you know where I can obtain the proper download containing the bundle folder required for deployment of the version mentioned above?

On Fri, Apr 14, 2017 at 1:01 PM Prakhar tripathi

<
mailto:Prakhar tripathi <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

If you're trying to setup test environment in Ubuntu you must follow the instructions given
https://rocket.chat/docs/developer-guides/pre-requisites
. the instructions that you were following are for deployment, not for testing purpose.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/RocketChat/Rocket.Chat/issues/6693#issuecomment-294203393
, or

**Comment by geekgonecrazy** [comment]
@richardwlu what do you get in your tar.gz? And how are you extracting it?

**Comment by richardwlu** [comment]
@geekgonecrazy 

```
[richlu@den02vmchat01 ~]$ curl -L https://github.com/RocketChat/Rocket.Chat/archive/0.54.2.tar.gz -o rocket.chat.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   130    0   130    0     0     21      0 --:--:--  0:00:05 --:--:--    29
  0     0    0 2997k    0     0   241k      0 --:--:--  0:00:12 --:--:--  760k
[richlu@den02vmchat01 ~]$ tar zxf rocket.chat.tgz
[richlu@den02vmchat01 ~]$ ls
hubot-test  mongo_backups  Rocket.Chat-0.54.2  rocket.chat.tgz  scripts
[richlu@den02vmchat01 ~]$ cd Rocket.Chat-0.54.2/
[richlu@den02vmchat01 Rocket.Chat-0.54.2]$ ls
app.json  CODE_OF_CONDUCT.md  example-build.sh        example-pm2.json       FEATURES.md  install.sh  LICENSE                 package.json  private  publish_packages.sh  scalingo.json  server
client    docker-compose.yml  example-ecosystem.json  example-settings.json  HISTORY.md   lib         nginx-multi-config.txt  packages      public   README.md            SECURITY.md    tests
```

**Comment by geekgonecrazy** [comment]
@richardwlu `Rocket.Chat-0.54.2` is definitely the folder.  I'll take a look and see whats going on.  We might need to update our documentation

**Comment by geekgonecrazy** [comment]
@richardwlu It looks like you are downloading from github using the download source option.  In our documentation we recommend doing:

`curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz`

That should solve your problem :grin:   Let me know if not and we can re-open :+1:

**Comment by richardwlu** [comment]
Based on @geekgonecrazy the doc `curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz` will provide you with the "latest", not a specific version.

If you came here looking for the answer, I found that you can go to https://rocket.chat/download and download the specific version.

Example to download 0.54.2 -> `curl -L https://rocket.chat/releases/0.54.2/download -o rocket.chat.tgz`

I suggest this be added to the docs.

**Comment by geekgonecrazy** [comment]
@richardwlu yes to download a specific version that's how.  Can substitute 0.54.2 with which every version you want.  Follows version number from here.  Also discoverable via our download page. :+1:
