### ISSUE TITLE
Webhook for new channel created not working

### ISSUE THREAD

**Issue by Huljo** [RocketChat/Rocket.Chat#6699]
Rocket.Chat Version: 0.55.0-rc.5
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

I've a problem with outgoing web hooks. It will not call the URL for the event roomCreated (a hook for messages works fine).

There is the logs when a new channel is created : 

````
[Integrations ➔ Outgoing WebHook.debug Execute Trigger: roomCreated 
[Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: roomCreated { event: 'roomCreated',   owner: { username: 'admin', _id: '35kRCc44rxsN9nRGF' },   room:     { name: 'test16',      t: 'c',      usernames: [ 'admin' ],      msgs: 0,      u: { _id: '35kRCc44rxsN9nRGF', username: 'admin' },      customFields: {},      ts: Mon Apr 03 2017 12:12:35 GMT+0200 (CEST),      ro: false,      sysMes: true,      _updatedAt: Mon Apr 03 2017 12:12:35 GMT+0200 (CEST),      _id: 'CuXN92trZSs8E5qSZ' } } 
[Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: CuXN92trZSs8E5qSZ 
[Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
````
The trigger is "Room Created (public and private)" but I got the same result with "channel archived"

If I just change the event trigger to  "Message sent", those lines are now visible : 
````
Integrations ➔ Outgoing WebHook.info Will be executing the Integration "testIntegration" to the url: http://localhost/webhooks/testendpoint
Integrations ➔ Outgoing WebHook.info Status code for the Integration testIntegration to http://localhost/webhooks/testendpoint is 200
````

**Comment by rodrigok** [comment]
@Huljo Is this working with the stable version 0.54?

**Comment by rodrigok** [comment]
@Huljo I can't reproduce, can you post more info like your trigger configuration?

This issue seems to not be related with latest release in `rc.5` now.

**Comment by graywolf336** [comment]
I couldn't reproduce either.

**Comment by graywolf336** [comment]
Please feel free to open if you run into this issue on the latest versions.
