### ISSUE TITLE
Breaking changes broke things: User objects in Channel overview

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#6701]
Currently running rc-5 but must be there since rc-0:
The breaking changes to return a object array instead of a string array beoke the "Users in room" view. Therefore just getting `[object Object]`. Don't know what is all affected by this change but seems the only bug (or does any other function rely on this call too?).
![img_0053](https://cloud.githubusercontent.com/assets/193273/25085243/70fa4ad2-2361-11e7-8975-1c3487efda9b.PNG)

**Comment by rodrigok** [comment]
Did the application ask you to update?

**Comment by engelgabriel** [comment]
@soundstorm can you try re-installing the app? It works for me.

**Comment by soundstorm** [comment]
Okay, works. Thanks :)
