### ISSUE TITLE
I can't update my Rocket.Chat using snaps

### ISSUE THREAD

**Issue by athossouza** [RocketChat/Rocket.Chat#6702]
Hello, 

I can't update my Rocket.Chat, do you know haw I solve it?

![capturar2](https://cloud.githubusercontent.com/assets/16904054/25089964/0d85fc12-2357-11e7-9e56-f35cccada477.PNG)
![capturar](https://cloud.githubusercontent.com/assets/16904054/25089965/0d898e22-2357-11e7-9e78-be80afd05fe1.PNG)

Rocket.Chat Version: 0.53.0
Running Instances: snap
DB Replicaset OpLog:
Node Version:

**Comment by geekgonecrazy** [comment]
@athossouza can you try: `sudo snap refresh rocketchat-server --stable` ?

**Comment by athossouza** [comment]
@geekgonecrazy I tried this `sudo snap refresh rocketchat-server`, but was just testing then I remove and reinstall the Rocket Chat using snap again, I will try your code if this happen again

**Comment by geekgonecrazy** [comment]
Also worth noting that if you haven't ran your updates might be worth doing: `sudo apt-get update && sudo apt-get dist-upgrade` so you can get the newest version of snapd.

I'll go ahead and close this.  Please feel free to open it back up if you encounter the issue.  Or reach out to us in [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap)
