### ISSUE TITLE
Upgrade email package to from 1.1.18 to 1.2.1

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6705]
The version 1.2.0 is broken with AWS SES.

Due to:
https://github.com/RocketChat/Rocket.Chat/issues/6678

We had to downgrade:
https://github.com/RocketChat/Rocket.Chat/pull/6680

Meteor is working to fix:
https://github.com/meteor/meteor/issues/8591
https://github.com/meteor/meteor/issues/8425

Via:
https://github.com/meteor/meteor/pull/8605

**Comment by engelgabriel** [comment]
@rodrigok Would you be able to test the email package from https://github.com/edemaine/meteor/tree/devel/packages/email to see if it works in our scenario?

**Comment by abernix** [comment]
`email@1.2.1` has been officially released! :smile:

**Comment by jancurn** [comment]
For a reference, after upgrading from `email@1.2.0` to `email@1.2.1` a call to `Email.send()` on our production system hang infinitely. Our `MAIL_URL` environment variable was like:
```
smtp://bob%40example.com:password@smtp.gmail.com:465/
```
Changing it to
```
smtps://bob%40example.com:password@smtp.gmail.com:465/
```
fixed the problem.
