### ISSUE TITLE
OAuth login fails with IE11 in Compatibility mode

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#6707]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

When running with Internet Explorer version 11 in compatibility mode, the callback to rocket chat with the authorization code fails (no error message in the logs or on the screen, leaving the user on a blank white page).  The only indication of what has happened is the displayed URL: https://rocketchat.geointservices.io/_oauth/geoaxis?code=<code>

Inspection of the HTML behind the blank page showed no compatibility tag in the head, which might be part of the problem, i.e.  <meta http-equiv=“X-UA-Compatible” content=“IE=edge” /> was not on the page but was on the login page prior to the error occurring

**Comment by geekgonecrazy** [comment]
This has been completely reworked.  Going to go ahead and close since no new reports with later versions of Rocket.Chat
