### ISSUE TITLE
Cannot Create Normal account after Live User creation

### ISSUE THREAD

**Issue by dfpena** [RocketChat/Rocket.Chat#6708]
I am unable to create a normal user account after a live user with the same email is created (User with the same email already exists). This would be fine if I was able to convert the live user to a normal account or delete the live user account. I also cannot search for the live user account in admin.

Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by sampaiodiego** [comment]
this was fixed by https://github.com/RocketChat/Rocket.Chat/pull/5201
