### ISSUE TITLE
Livechat-guest permissions

### ISSUE THREAD

**Issue by raelsan** [RocketChat/Rocket.Chat#6714]
Rocket.Chat Version: 0.55.0-develop
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

I think it's a bug but when i am connected as a livechat-guest, I can see and access default room, create public and private rooms, etc... As if as i had user' permissions.

And in the permissions menu, nothing is checked for livechat-guest.

**Comment by sampaiodiego** [comment]
I'm not able to reproduce this at 0.56-develop .. I get this when I try to access the `#general` channel from a livechat window:

![image](https://cloud.githubusercontent.com/assets/8591547/25631414/bb81537a-2f46-11e7-9af0-9562f26ac093.png)
