### ISSUE TITLE
REST API documentation incorrect for updating settings

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#6718]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

The Rocket.Chat REST API documentation for updating Rocket.Chat settings example is incorrect:

https://rocket.chat/docs/developer-guides/rest-api/settings/update

Example has:

curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     http://localhost:3000/api/v1/settings/Livechat_enabled \
     -d '{ "value": true }'

but it should be this:

curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/settings/Livechat_enabled \
     -d '{ "value": true }'

w/o -H "Content-type:application/json" in the header, the passed in -d JSON body argument will not be correctly parsed, causing the call to fail.  This is true for all settings update calls.

**Comment by graywolf336** [comment]
@howellsd can you close this and open it inside of the Documentation repo? https://github.com/RocketChat/Rocket.Chat.Docs Thanks!

**Comment by howellsd** [comment]
Moved to https://github.com/RocketChat/Rocket.Chat.Docs as requested
