### ISSUE TITLE
Markdown link which url has `&` has broken

### ISSUE THREAD

**Issue by peccu** [RocketChat/Rocket.Chat#6719]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Enables
Node Version: v4.7.1

Markdown link which url has `&` has broken.

ex:
`[url with & has broken](https://demo.rocket.chat/channel/general?test=test&test2=test2)`
becomes a link to https://demo.rocket.chat/channel/general?test=test&amp;test2=test2
( `&` is replaced to `&amp;` )

I think this is because of 590d120ff16c388a57ad0d78c07e096debca3df7.
So I'll try to fix and create PR.

**Comment by thiagoarrais** [comment]
Is this live already? I think I've reproduced it in the demo chat today.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closibg this, as I cannot reproduce this on latest stable version (0.62.2). Please get back to me with additional details if you think this is still the case and I'll happily reopen :)

Cheers
Thomas

**Comment by nbuchwitz** [comment]
@TwizzyDizzy:
I'm able to reproduce it with 0.63.1 (ac16e938693aa04740758f180f2ea6d7a0337280) - maybe be a regression?

**Comment by TwizzyDizzy** [comment]
@rocket-cat open.

Just reproduced on 0.63.1. Reopening.

Cheers
Thomas

**Comment by imeleges** [comment]
Unfortunately, it is the same problem on 0.65.1

**Comment by tassoevan** [comment]
@rodrigok @sampaiodiego Any update? #7454 and #8318 seem to be related to this.

**Comment by sampaiodiego** [comment]
@tassoevan can you please test https://github.com/RocketChat/Rocket.Chat/pull/8318/ to make sure it properly fixes this issue?

**Comment by ghosty-be** [comment]
issue still present in 0.69.1 ... very annoying since icinga2 also generates this type of URL's with & in between, so alert url in rocketchat are broken :(

**Comment by josh0412** [comment]
Issue is sadly still present..

**Comment by starso** [comment]
I have same problem using api to sen messages - every url been sent to rocketchat have ampersant ( &  ) is broken - message is cut just after first occurance of &

**Comment by tassoevan** [comment]
Which markdown parser (`Administration` > `Message` > `Markdown` > `Markdown Parser`) is causing this?

**Comment by starso** [comment]
> Which markdown parser (`Administration` > `Message` > `Markdown` > `Markdown Parser`) is causing this?

Original one

**Comment by MartinSchoeler** [comment]
@starso is this only happening when using the API?

**Comment by starso** [comment]
> @starso is this only happening when using the API?

Yes, If i post message directly with url containing & mark everything is fine. 
Using API string gets cut after first occurence of & mark.

**Comment by MartinSchoeler** [comment]
I've just tested using the API and it seems to be working fine in version `2.3.0-develop` please try to use the latest version, and if the problem persists, please open a new issue with updated details and the specific API call that you are using. Thanks!
