### ISSUE TITLE
Collaborative developer features: cloud-based code editor, integrations, and the works

### ISSUE THREAD

**Issue by guarilha** [RocketChat/Rocket.Chat#672]
Rocket.Chat is following a similar path as other Messaging platforms: becoming a powerhouse of management and monitoring by integrating different services and apps to the collaborative workspace the chat solution provides. 

The goal would be to extend these features to developers:
- Integrate an IDE to code collaboratively in real-time
- Screen sharing and video conference
- Full Github and Gitlab integration
- Continuous Integration and Continuous Deploy
- Built-in terminal working with Docker containers
- Integrate [WeKan](https://github.com/wekan/wekan) or other kanban software

This is somewhat similar to what @jmatsushita proposed with #346. 
The best IDE with an IRC-like chat solution integration I know of is [Koding](https://koding.com).

Some open-source projects that might help:
- http://eclipseche.org/ (used by [codenvy](https://github.com/codenvy))
- https://c9.io/
- https://github.com/Codiad/Codiad
- https://github.com/CodeboxIDE/codebox
- https://nitrous.io/
##

**Comment by Sing-Li** [comment]
Well said.   And in a form that is ready for international press PR :+1:   Thanks.

Of course, we are very different in that we are 100% true open source with the liberal MIT license.  People can copy our code and use it for whatever they like.  We also have distributions ready for most mobile devices, major cloud services and operating systems.

**Comment by mquandalle** [comment]
Hi,

Wekan dev here. I'm busy fixing bugs blocking the next release, but once I get that done, I'll investigate how we can integrate Rocket.chat and Wekan together.

**Comment by guarilha** [comment]
Posts and Snippets are being discussed here #308

**Comment by mquandalle** [comment]
If you are interested in Wekan and Rocket.chat integration, come discuss at http://discuss.wekan.io/t/rocket-chat-integration/15

**Comment by AdrianoCahete** [comment]
Wekan integration will be awesome if it's like in Waffle.io.

**Comment by engelgabriel** [comment]
@mquandalle you have my :+1: 

I'll join the forum.. I have some ideas.

**Comment by xet7** [comment]
Hi! I'm current maintainer of Wekan. ( Original author of Wekan @mquandalle is usually hard to reach https://github.com/wekan/wekan/wiki/Team )

There's Wekan API and Wekan's Outgoing Webhooks, it's possible to add multiple Outgoing Webhooks github.com/wekan/wekan/wiki/Features#webhooks

There's issue about using huginn for integrations https://github.com/wekan/wekan/issues/1160

Huginn has web UI for adding integrations.

All Wekan / Huginn / Rocket.Chat are available as Docker containers. For Wekan, there's Docker Compose script at:
https://github.com/wekan/wekan-mongodb
https://github.com/wekan/wekan-postgresql

**Comment by localguru** [comment]
@guarilha right ... cooking coffee with RC would be a nice feature, ordering food, driving kids to school, do my complete office work, clean my shoes ...

**Comment by localguru** [comment]
Or better idea: why not first fixing basic things like OTR ;)

**Comment by xet7** [comment]
@localguru 

Are you some Rocket.Chat code contributor or [offtopic spammer](https://github.com/wekan/wekan/wiki/FAQ#why-am-i-called-a-spammer) ? I'm still planning to add integrations when I have some time for it.

**Comment by geekgonecrazy** [comment]
This isn't something we plan to add to our code base.  But this would make for a good App idea. 

Please feel free to open a topic in our [forum](https://forums.rocket.chat) in the feature request category for others to upvote and help improve the idea.
