### ISSUE TITLE
Sending selected messages via mail not possible on android app

### ISSUE THREAD

**Issue by fadanner** [RocketChat/Rocket.Chat#6723]
Rocket.Chat Version: 0.55.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Android Rocket.Chat app from Google Playstore

When i try to send messages via mail and i use the button "choose messages" it isn't possible to select any messages on my smartphone, because the right sidebar keeps open only, there is no space with the messages. If I go back via the "android back button" it tooks me to the start screen so this isn't an option, too. I think this is only a design/style issue, but would be nice if the feature is working on smartphones,too.

**Comment by Hudell** [comment]
Since this is related to the old Cordova app and the feature is not available on the new app, I'll be closing this issue. For any problems with mobile apps from now on, please open the issue on the App's repository.
