### ISSUE TITLE
Should Not Show Mute/Block/Kick Buttons for The Current User

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6726]
The last Version in RC
I can block myself in private chat room also i can mute my self in public chat room and private group !!
this is normal???
![2017-04-19_113247](https://cloud.githubusercontent.com/assets/22897987/25173509/b32630da-24f4-11e7-8cc3-134ed30fa391.jpg)

**Comment by MartinSchoeler** [comment]
Yes, also mute/remove from room buttons aren’t necessary. Will rename the issue to reflect that

**Comment by Nemra1** [comment]
@MartinSchoeler i think the members dont need to mute himself or block himself  ...this option must to be for others not for myself ...
