### ISSUE TITLE
Only 46 users are displayed in the Users grid even-though there are more users.

### ISSUE THREAD

**Issue by razanjoshi** [RocketChat/Rocket.Chat#6727]
**Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.6.2 - x64**
-------------------------------------

The Users page from the Administration displays only 46 users even though there are more users in the database.

**Screenshots:**
<img width="941" alt="screen shot 2017-04-19 at 3 45 32 pm" src="https://cloud.githubusercontent.com/assets/4223130/25174556/6c85403a-2517-11e7-82f7-264b58f94263.png">

<img width="274" alt="screen shot 2017-04-19 at 3 47 45 pm" src="https://cloud.githubusercontent.com/assets/4223130/25174592/9366fcac-2517-11e7-951b-614cfc2816e8.png">

**Comment by matthewshirley** [comment]
Do you still have this issue? I tried to replicate in the latest release but the numbers matched up.

<img width="323" alt="capture" src="https://cloud.githubusercontent.com/assets/450704/25558299/9ed8037e-2cd8-11e7-9ac4-cbc1a62b46a0.PNG">

**Comment by Hudell** [comment]
I'll be closing this as per the previous message and the reaction and lack of response of the OP.
