### ISSUE TITLE
Send audio posts to active room when upload finishes not initial room intended

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#673]
I was in a private group and recorded then sent audio which took about 15 seconds to upload.  During that time I switched to the #general chat room which was active when the upload finished but the audio recording posted there instead of the group.

**Comment by sunnipaul** [comment]
It also happens for image uploads. Switching rooms while uploading will result in dropping that file to the unexpected room.

**Comment by marceloschmidt** [comment]
Fixed! https://github.com/RocketChat/Rocket.Chat/commit/faba325bd3511e092c119e79e5fd6141c27269d9
