### ISSUE TITLE
'Collapse embedded media' option hides quotes

### ISSUE THREAD

**Issue by el-dom** [RocketChat/Rocket.Chat#6730]
Rocket.Chat Version: 0.55.0
Running Instances: 1

Steps to reproduce:
- Go to account settings
- Set option 'Collapse embedded media by default' to true
- Enter any chat
- Quote something

Actual behaviour: The quoted text is not visible and there is no icon to expand it
Expected behaviour: Beforementioned option should either not affect quoted text at all or there should be an icon to expand collapsed quotes

**Comment by geesper** [comment]
I am able to reproduce this on RocketChat 0.55.1 also.

**Comment by MartinSchoeler** [comment]
Tested on the latest version and it seems to be fixed, if you happen to experience this again, please reopen this. Thanks!
