### ISSUE TITLE
WebApi - /api/v1/users.create never returns on fresh instance

### ISSUE THREAD

**Issue by MatthiasKainer** [RocketChat/Rocket.Chat#6733]
Rocket.Chat Version: 0.55.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

Hejhej,
Using the official rocket.chat docker image, using the WebApi to create a user never returns a callback. 

Steps to reproduce: 

```sh
docker run --name db -d mongo:3.0 --smallfiles
docker run -p 3000:3000 --env ROOT_URL=http://127.0.0.1 --env ADMIN_PASS=123456 --env ADMIN_USERNAME=admin --name rocketchat --link db -d rocket.chat

declare -i max=0
until [ $(curl --output /dev/null --silent --head --fail http://localhost:3000/api/v1/info) ] || [ "$max" -gt 30 ]; do
    printf '.'
    max=$(( max + 1 ))
    sleep 1
done

curl http://localhost:3000/api/v1/login \
     -d "username=admin&password=123456"
# insert authtoken from last call
curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/users.create \
     -d '{"name": "name", "email": "email@user.tld", "password": "anypassyouwant", "username": "uniqueusername", "customFields": { "twitter": "@userstwitter" } }'
```

Am I too stupid to setup a working docker instance, or is there a bug?

**Comment by qeesung** [comment]
+1

**Comment by graywolf336** [comment]
I just tired this locally and also in our hosting service, which uses docker, with the same exact curl command you provided and it returned the data.

@geekgonecrazy any ideas?

**Comment by MatthiasKainer** [comment]
@graywolf336 I tested it with one of our rocket.chat inprod instances and funny enough - it worked as well.  Locally same issue though. Difference is mongo replica set instead of single, and setup mail server. And lots of custom emojis... 
I'll search for more differences

**Comment by geekgonecrazy** [comment]
@MatthiasKainer first one i'd give a shot is trying to use replica set and see what difference that makes.

**Comment by qeesung** [comment]
I tried the `users.create` interface with postman , and got the exception

```json
{
  "success": false,
  "error": "Adding user is not allowed [error-action-not-allowed]",
  "errorType": "error-action-not-allowed"
}
```

**Comment by MatthiasKainer** [comment]
@geekgonecrazy no difference with replica. Other diffs are domain whitelisting and user has to be validated manually. 

This happens with the 0.45.2 version from rocket.chat as well as with the 0.55 rocketchat/rocket.chat

postman times out with `could not get any response` for me as well. I'll debug some more, see what I can find.

**Comment by graywolf336** [comment]
@qeesung that's an occur that states what it is wrong, you don't have permission to do that or user registration is disabled.

**Comment by MatthiasKainer** [comment]
I've pushed the tests where this issue appeared on travis, and works there without issues. Seems to be an issue with my local configurationn. I'll close this issue and fix my machine

**Comment by MatthiasKainer** [comment]
*good* news everyone - travis has replicated the issue successfully: 

[travis://qeesung/rocketchat-node#223946970](https://travis-ci.org/qeesung/rocketchat-node/builds/223946970)

The failing test has the same issue that happens to me locally. Restarted the build already, issue was reproducible.

**Comment by MatthiasKainer** [comment]
very flaky though - for this build it is reproducible, newer builds work. Maybe some docker-version stuff? I'm on 1.12.3.

**Comment by MatthiasKainer** [comment]
running this in a loop on a instance where this does not occure I had some timeouts as well - user was created. Seems as if something after the initial creation is slow and thus timing out.

**Comment by graywolf336** [comment]
This stems from https://github.com/RocketChat/Rocket.Chat/issues/6754, so when that gets fixed then this will resolve automatically.
