### ISSUE TITLE
Deleted User Still Shows "unread message" Notification 

### ISSUE THREAD

**Issue by mineZcash** [RocketChat/Rocket.Chat#6739]
Hello, I run the rocket chat at chat.zcashcommunity.com

Recently I had to remove a user who was not abiding by the chat rules. I disabled the account (username jessicaLawson) and deleted the user which removed all their messages. 

But now one user (zooko) is still stuck with a permanent notification of an unread message from the deleted user which cannot be cleared 

Log shows: `[34mI20170419-23:31:58.543(0) Empty Room for Subscription { _id: '5YPxqdWuqDZwAgvr7',   rid: 'mevnj6TkuP58hHqXixBwG23PKugnMNyLDp',   name: 'jessicaLawson',   t: 'd',   open: true,   alert: true,   unread: 1,   u: { _id: 'xBwG23PKugnMNyLDp', username: 'zooko' },   _updatedAt: Fri Apr 14 2017 08:31:49 GMT+0000 (UTC),   meta:     { revision: 3,      created: 1491369624412,      version: 0,      updated: 1492158709906 },   '$loki': 3207,   _room: undefined,   _user:     { _id: 'xBwG23PKugnMNyLDp',      createdAt: Fri Nov 04 2016 18:09:10 GMT+0000 (UTC),      services: { password: [Object], resume: [Object] },      username: 'zooko',      emails: [ [Object] ],      type: 'user',      status: 'online',      active: true,      roles: [ 'user', 'admin', 'ZcashCo Team' ],      _updatedAt: Wed Apr 19 2017 23:31:52 GMT+0000 (UTC),      name: 'zooko',      lastLogin: Wed Apr 19 2017 23:31:52 GMT+0000 (UTC),      statusConnection: 'online',      utcOffset: 0,      language: 'en',      settings: { preferences: [Object] },      meta:        { revision: 2085,         created: 1490212205119,         version: 0,         updated: 1492644712647 },      '$loki': 8,      avatarOrigin: 'upload' },   archived: true }`

Here is a screenshot of the error on the users side: 
![zombie-jessica-2017-04-13_16-40-18-0600](https://cloud.githubusercontent.com/assets/27791307/25207593/d2392e20-253d-11e7-8d9d-621ff88476c9.png)

Please advise on how to clear this notification bug

Rocket.Chat Version: 0.53.0
Running Instances: 2
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by MartinSchoeler** [comment]
@mineZcash Have you tried `ctrl`+`esc` shortcut? It marks all messages as read. Thanks!

**Comment by mineZcash** [comment]
I will have the user try and get back to you, hopefully its that simple :)

**Comment by gdelavald** [comment]
I couldn't reproduce this in the current develop branch, my steps were:

> 1. Create a new account and send messages to my actual account;
> 2. Open admin tab without reading the private messages
> 3. Deactivate and delete the new account
> 4. Leave admin tab and check private messages

After step 4, there were no messages from the deactivated/deleted user. I tried deleting without deactivating as well as just deactivating the new account, neither produced the above.

**Comment by mineZcash** [comment]
I'm not sure what the issue is, but the notification is stuck in the loop of continually trying to fulfill the unread request. here is the log from a few minutes ago: 

`[34mI20170421-19:26:45.161(0) Empty Room for Subscription { _id: '5YPxqdWuqDZwAgvr7',   rid: 'mevnj6TkuP58hHqXixBwG23PKugnMNyLDp',   name: 'jessicaLawson',   t: 'd',   open: true,   alert: true,   unread: 1,   u: { _id: 'xBwG23PKugnMNyLDp', username: 'zooko' },   _updatedAt: Fri Apr 14 2017 08:31:49 GMT+0000 (UTC),   meta:     { revision: 3,      created: 1491369624412,      version: 0,      updated: 1492158709906 },   '$loki': 3207,   _room: undefined,   _user:     { _id: 'xBwG23PKugnMNyLDp',      createdAt: Fri Nov 04 2016 18:09:10 GMT+0000 (UTC),      services: { password: [Object], resume: [Object] },      username: 'zooko',      emails: [ [Object] ],      type: 'user',      status: 'online',      active: true,      roles: [ 'user', 'admin', 'ZcashCo Team' ],      _updatedAt: Fri Apr 21 2017 19:26:34 GMT+0000 (UTC),      name: 'zooko',      lastLogin: Fri Apr 21 2017 19:26:34 GMT+0000 (UTC),      statusConnection: 'online',      utcOffset: -6,      language: 'en',      settings: { preferences: [Object] },      meta:        { revision: 2221,         created: 1490212205119,         version: 0,         updated: 1492802794940 },      '$loki': 8,      avatarOrigin: 'upload' },   archived: true } 
[34mI20170421-20:48:49.921(0) Empty Room for Subscription { _id: '5YPxqdWuqDZwAgvr7',   rid: 'mevnj6TkuP58hHqXixBwG23PKugnMNyLDp',   name: 'jessicaLawson',   t: 'd',   open: true,   alert: true,   unread: 1,   u: { _id: 'xBwG23PKugnMNyLDp', username: 'zooko' },   _updatedAt: Fri Apr 14 2017 08:31:49 GMT+0000 (UTC),   meta:     { revision: 3,      created: 1491369624412,      version: 0,      updated: 1492158709906 },   '$loki': 3207,   _room: undefined,   _user:     { _id: 'xBwG23PKugnMNyLDp',      createdAt: Fri Nov 04 2016 18:09:10 GMT+0000 (UTC),      services: { password: [Object], resume: [Object] },      username: 'zooko',      emails: [ [Object] ],      type: 'user',      status: 'online',      active: true,      roles: [ 'user', 'admin', 'ZcashCo Team' ],      _updatedAt: Fri Apr 21 2017 20:48:47 GMT+0000 (UTC),      name: 'zooko',      lastLogin: Fri Apr 21 2017 20:48:47 GMT+0000 (UTC),      statusConnection: 'online',      utcOffset: -6,      language: 'en',      settings: { preferences: [Object] },      meta:        { revision: 2229,         created: 1490212205119,         version: 0,         updated: 1492807727282 },      '$loki': 8,      avatarOrigin: 'upload' },   archived: true } 
[34mI20170421-22:48:40.150(0) Empty Room for Subscription { _id: '5YPxqdWuqDZwAgvr7',   rid: 'mevnj6TkuP58hHqXixBwG23PKugnMNyLDp',   name: 'jessicaLawson',   t: 'd',   open: true,   alert: true,   unread: 1,   u: { _id: 'xBwG23PKugnMNyLDp', username: 'zooko' },   _updatedAt: Fri Apr 14 2017 08:31:49 GMT+0000 (UTC),   meta:     { revision: 3,      created: 1491369624412,      version: 0,      updated: 1492158709906 },   '$loki': 3207,   _room: undefined,   _user:     { _id: 'xBwG23PKugnMNyLDp',      createdAt: Fri Nov 04 2016 18:09:10 GMT+0000 (UTC),      services: { password: [Object], resume: [Object] },      username: 'zooko',      emails: [ [Object] ],      type: 'user',      status: 'online',      active: true,      roles: [ 'user', 'admin', 'ZcashCo Team' ],      _updatedAt: Fri Apr 21 2017 22:48:37 GMT+0000 (UTC),      name: 'zooko',      lastLogin: Fri Apr 21 2017 22:48:37 GMT+0000 (UTC),      statusConnection: 'online',      utcOffset: -6,      language: 'en',      settings: { preferences: [Object] },      meta:        { revision: 2234,         created: 1490212205119,         version: 0,         updated: 1492814917098 },      '$loki': 8,      avatarOrigin: 'upload' },   archived: true } `

**Comment by mineZcash** [comment]
Using CTRL+ESC cleared the issue for the user and the logs, thank you!

**Comment by rtroilo** [comment]
Hi, 
I have the same problem. I deleted a user and now other users could still see the unread direct message with the deleted user and get the same error page "no user with username ...".
The CTRL+ESC is not working more specifically it is doing nothing. Is this a new keyboard-shortcut? Because it is not listed under "https://rocket.chat/docs/user-guides/keyboard-shortcuts".

Is there a way to delete this unread message, maybe direct in the database? If so, please, could you point me in where the message is stored.

Thank you!

**Comment by rtroilo** [comment]
Rocket.Chat Version: 0.54.2
NodeJS Version: 4.8.1 - x64
Running Instances: 1
DB Replicaset OpLog: Disabled
