### ISSUE TITLE
If windows is in specific resolution, the right side bar is not working correctly

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6742]
Rocket.Chat Version: 0.54.2
Running Instances: 3
DB Replicaset OpLog: Yes
Browser: Internet Explorer

If i resize the rocket.chat browser windows to a minimized resolution like in the screenshot. In Internet Explorer the side bar is not working correctly. Only the "show room members" is working correctly. On Google Chrome all is working fine.

![image](https://cloud.githubusercontent.com/assets/5877910/25222845/ed2505fc-25b9-11e7-9201-415b13b7d971.png)

**Comment by MartinSchoeler** [comment]
Hey @TheReal1604 are you using any custom css?

**Comment by TheReal1604** [comment]
Not in this deployment of rocket.chat. ;-)

**Comment by TwizzyDizzy** [comment]
@TheReal1604 can you still reproduce this on current stable?

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this due to lack of feedback.

Cheers
Thomas
