### ISSUE TITLE
iFrame Integration support for Internet Explorer 10

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6743]
Rocket.Chat Version: 0.54.2
Running Instances:  3
DB Replicaset OpLog: Yes
Browser: Internet Explorer 10

If i embed rocket.chat as an iFrame into a sharepoint site, the 3 dots are spinning like crazy and nothing happens.

![image](https://cloud.githubusercontent.com/assets/5877910/25223011/720f254a-25ba-11e7-8139-9f5159b5a808.png)

![image](https://cloud.githubusercontent.com/assets/5877910/25223085/b28da862-25ba-11e7-819b-8ed9b51ddff1.png)

This are errors i can see in the browser console. 

"RocketChat is not defined" and "This Object doesnt support the method or property "fill""
I cant see this error on console if I access the site with the "edge mode" from internet explorer.

**Comment by engelgabriel** [comment]
@MartinSchoeler please test it using https://www.browserstack.com/

**Comment by MartinSchoeler** [comment]
@TheReal1604 @engelgabriel I couldn’t reproduce this using internet explorer and a simple page embedding demo. Maybe some issue with sharepoint? @TheReal1604 Could you test this with another browser? Thanks!
