### ISSUE TITLE
Future: add font picker for Msg input box / Convert text formating code to buttons

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6744]
I hope from the team to add this futures in the next version
First 1- color picker
![2017-04-20_114740](https://cloud.githubusercontent.com/assets/22897987/25224763/a943aa0e-25bf-11e7-98ac-0ac7fbc931e9.jpg)
with option in dashboard ( enable and disable )
![2017-04-20_123054](https://cloud.githubusercontent.com/assets/22897987/25226444/42cfbe10-25c5-11e7-8eed-a76d6008f6ba.jpg)
Seconde 2- Convert bold Btn ,inline,etc / from shortcode to buttons
![2017-04-20_124145](https://cloud.githubusercontent.com/assets/22897987/25226975/1c975c74-25c7-11e7-8409-dd43b337b0b5.jpg)

**Comment by WebSavvyGuy** [comment]
Yes would love to see this!!

**Comment by karan-96** [comment]
I am working on it :)

**Comment by WebSavvyGuy** [comment]
@karan-96 Looking forward to this.  Do you have an idea when you can complete this?  Hopefully we can get it into the 0.56 Full Release.

**Comment by Nemra1** [comment]
@karan-96  you wil share it or private?

**Comment by karan-96** [comment]
@WebSavvyGuy I am not sure about the time but will try to do it as soon as possible. @Nemra1 I will be sharing it.

**Comment by Nemra1** [comment]
@karan-96 let me know if you need any help !

**Comment by theorenck** [comment]
Hey @Nemra1, we have some of your ideas implemented by now namely the style shortcuts but about the color customization we don't see it the same way (mostly because of accessibility issues). Thanks for your ideas!
