### ISSUE TITLE
Deleting old messages?

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#6749]
Rocket.Chat Version: 0.55.0 rc-6
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5.0

Hi

Is there a way to delete (prune) old messages automatically?  Ideally i would only want something like the last 50 messages posted to the room to be saved and viewable for any particular user.

I am rather new to Rocket.chat and did not find this function.   It seems to store the entire history since the beginning and that would take up a lot of disk space if left on long enough.

Thanks

**Comment by WebSavvyGuy** [comment]
Just found a similar request #795 but no progress for a couple years.

**Comment by jszaszvari** [comment]
@WebSavvyGuy - You could easily script it with the API to remove all messages older than lets say 30 days using the cleanHistory method. That would at least limit the amount of messages stored. It's not 50 messages but better than nothing :)

https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory

Just set 'latest' as 30 days ago and 'oldest' as a date from 1 year ago, then run that every evening so only 30 days worth of messages are kept/displayed.

I guess you could use the API to look up all rooms then loop through them with the cleanHistory method with a bit of scripting magic.

**Comment by jszaszvari** [comment]
Although the disk space usage should be minimal, we just hit 80,500 messages total and are using 700mb disk space in Mongo - So I'm not sure I'd worry about the last 50 messages....

<img width="592" alt="screen shot 2017-04-22 at 3 54 23 am" src="https://cloud.githubusercontent.com/assets/872463/25290113/d5e689b8-270f-11e7-848b-31ff47ab6f87.png">
<img width="365" alt="screen shot 2017-04-22 at 3 52 55 am" src="https://cloud.githubusercontent.com/assets/872463/25290114/d61715f6-270f-11e7-8776-44da183e3fb3.png">

**Comment by WebSavvyGuy** [comment]
@jszaszvari Thanks for the reply.    We will look into something like that.  We run a popular website that we might eventually migrate over into Rocket.chat.   We probably would get well over those numbers you have each DAY, so that is why were looking for something that will prune messages down.    The last 50 number is just kind of like what our current chat application does.   It only shows (caches) the last 20 messages posted in the main room.   Private messages are totally deleted if the user leaves the room.   A system like that would better work for us.

**Comment by vynmera** [comment]
I'm making it happen! ---> #11236
