### ISSUE TITLE
Require Two Factor Auth for external authenticators

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#6750]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: off
Node Version: 4.7.3

Hello Devs.

I have an issue with 2FA. After enabling it i can still login without entering a 2FA code. Is that a known issue?

thanks and cheers

**Comment by patrickhanft** [comment]
I just found similar behaviour. We let SAML handle the authentication and just wanted to try out 2FA. But after enabling it, I still get immediately logged in without any 2FA check.

Or is this a feature from your point of view? One could argue that 2FA should also happen on the SAML authentication layer …

**Comment by shakalandy** [comment]
Same Issue here with Active Directory as LDAP backend.

**Comment by sampaiodiego** [comment]
We'll look into requering 2FA to any authentication method.

**Comment by sc10n** [comment]
Thanks for looking into this! Is there a timeline for this? We use AD as the LDAP backend and have a hard requirement for 2FA which is preventing us from rolling out a large scale deployment.

**Comment by baurmatt** [comment]
We're also interested in activating 2FA for our RocketChat Setup which currently uses LDAP authentication.

**Comment by xeidoo** [comment]
Any news regarding this issue?

**Comment by himbeere** [comment]
Any progress on that matter?

**Comment by EtienneBer** [comment]
Hello

Any news ?

**Comment by shakalandy** [comment]
Possible to sponsor this one? Maybe via Bountysource?

**Comment by Hudell** [comment]
@shakalandy it was already implemented and will be included in one of the next releases.

**Comment by marcinkorzycki** [comment]
In which release are you plan to add it? We want to use it ASAP.

**Comment by midse** [comment]
Any news regarding this issue? 2 FA Authentication is bypassed when using LDAP auth.

**Comment by wreiske** [comment]
👀

**Comment by karlettoh** [comment]
Tested this in 1.0.0-rc.2 and 0.74.3 and 2FA is bypassed when using LDAP still.
