### ISSUE TITLE
How to prevent turning off video ?

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#6752]
Hello. How to prevent "Video for xxx has been turned off to save bandwidth" ?
Is there any configuration in order to keep the video running ?

Regards

Rocket.Chat Version: 0.55.0-rc.5
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.8.0

**Comment by geekgonecrazy** [comment]
Sounds like jitsi thing.  Closing

But I doubt you would be able to force this.
