### ISSUE TITLE
Registration Hangs "method RegisterUser"

### ISSUE THREAD

**Issue by nickbunker** [RocketChat/Rocket.Chat#6754]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

When I have users register for a new account it has a 2 minute hang between "Register new account" and when the username screen loads.
I have tested that I don't see this error when running the snap version of Rocket.Chat.
I only see this error when running the GitHub version.
I had the same issue on 0.48.2 as well.
In the screenshot you can see the time difference between line 2 and 3 is just over 2 minutes. 
I would like to use the github version as it is easier to make port, proxy, and DB name changes for setting up multiple instances.
![image](https://cloud.githubusercontent.com/assets/26935562/25278690/2883f802-2672-11e7-9a77-ef38ecbf84a0.png)

Please help troubleshoot this.
I have tried the suggestions in #1516 but they are no help for this issue.

**Comment by graywolf336** [comment]
Seems related to: https://github.com/RocketChat/Rocket.Chat/issues/6733

**Comment by novalis111** [comment]
Issue still exists in latest docker image

Rocket.Chat Version: 0.61.1
NodeJS Version: 8.9.3 - x64
Platform: linux
ReplicaSet OpLog: Enabled

**Comment by brokenmass** [comment]
+1 Issue still present for me using last docker image

**Comment by sshniro** [comment]
Observed similar behavior with docker image v1.0, if the user register's him/her self the registration page pauses for a while (20 sec). But if I create a  user via the admin api then the user is created immediately.

**Comment by Shadoukun** [comment]
I'm having this issue with the latest docker image as well. The snap package doesn't have this problem.

Rocket.Chat Version: 2.3.2 
NodeJS Version: 8.16.2
MongoDB Version: 4.0.14 
Platform: linux
ReplicaSet OpLog: Enabled

**Comment by hashimmm** [comment]
Same issue, running on docker using docker-compose, using the official image, on ubuntu 18.04. My config:

Rocket.Chat Version: 3.4.2
NodeJS Version: 12.16.1 - x64
MongoDB Version: 4.0.19
MongoDB Engine: mmapv1
Platform: linux
Process Port: 3000
ReplicaSet OpLog: Enabled
Commit Hash: e5f93d3f5e
Commit Branch: HEAD

**Comment by geekgonecrazy** [comment]
These are all likely very different causes.  I'm going to close since this is such an old issue.  Please open a new issue with details of things you've changed in the settings and as much info as you have about reproducing it

**Comment by itsarectangle** [comment]
> 
> 
> These are all likely very different causes since this is so old. I can recall us fixing several things related to this. I'm going to close since this is such an old issue. Please open a new issue with details of things you've changed in the settings and as much info as you have about reproducing it

This seems to still be an issue (see https://github.com/RocketChat/Rocket.Chat/issues/17766).  

I added the following comment to that thread:

I'm having the same issue, makes the platform completely unusable if a user can't even register right. Is there really no fix or workaround for this? This same issue has popped up going on some 3-4 years it seems. Thx

EDIT: I have two RC servers running with same settings, one works right, the other does not. What can i do?
