### ISSUE TITLE
Begin adapting import modules in anticipation of lazy/dynamic loading for Meteor at 1.5

### ISSUE THREAD

**Issue by janat08** [RocketChat/Rocket.Chat#6759]
It's difficult to tell which library belongs in what package especially when they're acronyms. It would be great to have imports for this purpose. For those unaware meteor will be adding dynamic loading for faster first page loads.

**Comment by steven-tib** [comment]
Hi, any news on this? Are there any plans of using dynamic imports for Rocket.chat now that it's available?

**Comment by janat08** [comment]
Arguebly it being single page applicationg the endeavour is somewhat
pointless, and then lazy loading may actually be slower since.
