### ISSUE TITLE
local docker deploy issue

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#676]
I'm using OS X 10.10.4

I cloned the repository and ran

````shell
$ docker-compose up
````

and got this 

````
rocketchat_1 | Updating login service Accounts_OAuth_Facebook
rocketchat_1 | Updating login service Accounts_OAuth_Github
rocketchat_1 | Updating login service Accounts_OAuth_Gitlab
rocketchat_1 | Updating login service Accounts_OAuth_Google
rocketchat_1 | Updating login service Accounts_OAuth_Linkedin
rocketchat_1 | Updating login service Accounts_OAuth_Meteor
rocketchat_1 | Updating login service Accounts_OAuth_Twitter
rocketchat_1 | Updating login service SAML_Custom_default
rocketchat_1 | {"line":"63","file":"synced-cron-server.js","message":"SyncedCron: Starting \"Generate and save statistics\".","time":{"$date":1441296000010},"level":"info"}
mongodb_1    | 2015-09-03T16:00:00.029+0000 I COMMAND  [conn2] CMD: drop rocketchat.tmp.mr.rocketchat_room_0
mongodb_1    | 2015-09-03T16:00:00.030+0000 I COMMAND  [conn2] CMD: drop rocketchat.rocketchat_mr_statistics
mongodb_1    | 2015-09-03T16:00:00.030+0000 I COMMAND  [conn2] CMD: drop rocketchat.tmp.mr.rocketchat_room_0
mongodb_1    | 2015-09-03T16:00:00.031+0000 I COMMAND  [conn2] CMD: drop rocketchat.tmp.mr.rocketchat_room_0
mongodb_1    | 2015-09-03T16:00:00.031+0000 I COMMAND  [conn2] CMD: drop rocketchat.tmp.mr.rocketchat_room_0
rocketchat_1 | private group user statistic not found
rocketchat_1 | Sending statistics data to Rocket.Chat
rocketchat_1 | {"line":"63","file":"synced-cron-server.js","message":"SyncedCron: Finished \"Generate and save statistics\".","time":{"$date":1441296000182},"level":"info"}
````

This is my first time with docker so I'm not exactly sure of the steps. I also ran `docker pull rocketchat/rocket.chat` which downloaded the image but not sure if that had any effect on this process.

When I go to <localhost:80> I get nothing.

**Comment by k0nsl** [comment]
@mhkeller:

Unsure, but shouldn't it be on port 3000?

**Comment by mhkeller** [comment]
That's my understanding for the development instructions but for production the docs say

````
and check it out at http://localhost:80
````

**Comment by mhkeller** [comment]
3000 doesn't work either, however.

**Comment by Sing-Li** [comment]
on OSX - docker is running inside a VM -- called boot2docker

**Comment by Sing-Li** [comment]
you need to `docker inspect <container id>` and find the IP address of the VM

**Comment by Sing-Li** [comment]
@k0nsl  thanks for helping :smile:    @mhkeller  please let us know if you got it working and/or close this ticket.  thx

**Comment by mhkeller** [comment]
Ah that makes sense. I'll be back at my computer to test this afternoon and will report back. Another question tho: after running docker-compose up I get the server running in a window in that container. How would I get it running as a service?

**Comment by Sing-Li** [comment]
@mhkeller   On your Mac, Rocket.Chat on docker  it is running insider a Linux Virtual Machine (ORACLE VirtualBox, I think) - that is the window that you see.  There's no real way of running a VM as a 'service' on the Mac.

If you want to run it 'native' as a service on your Mac.  You do not want docker (and the extra VM).  You will need to install node.js on your Mac first.   

We currently do not have instructions for doing this ... but after you got node.js installed, go to the demo chat from our home page, and one of the team member will likely be able to assist you.

**Comment by marceloschmidt** [comment]
@Sing-Li and @mhkeller boot2docker is deprecated. I'll try to run docker on my mac following the new instructions on https://docs.docker.com/installation/mac/ and I'll let you guys know how that goes and probably write a new wiki for using docker to run rocket.chat on a mac.

**Comment by mhkeller** [comment]
@marceloschmidt  I was just about to post. You can use `docker-machine ip default` where `default` is the name of my running docker vm.

now im trying to figure out port forwarding so i can get access rocket chat on other computers than this one. should I open a new issue @Sing-Li

**Comment by Sing-Li** [comment]
@mhkeller  so you've got it going on your  mac?   I think @marceloschmidt 's guide will contain the port forwarding info.  So just closing this ticket is fine.

**Comment by Sing-Li** [comment]
@marceloschmidt  - that would be a great user's guide !    Thanks.

**Comment by mhkeller** [comment]
Ya I have it running, thanks for the help. I definitely have questions that the guide could address:

1. I'm rather confused about where I have to login from to get access to the docker daemon. If i `cd` to where I cloned Rocket.Chat and run `docker-compose up` it tells me the daemon is not running. I have to open the "Docker Quickstart Terminal" app, which seems to log into the `default` VM but when I run `pwd` I'm still in my system. It's a bit confusing.
2. Where does `docker pull rocketchat/rocket.chat` come into play? Is it an alternative to git cloning the repository? If I wanted to run `docker-compose up` on that image, how would I do it?

@marceloschmidt thanks for putting the guide together

**Comment by mhkeller** [comment]
Also worth noting that when you log into the quick start terminal, it prints the IP of the machine.

**Comment by mhkeller** [comment]
many of the walkthroughs on port fowarding describe this

````
VBoxManage controlvm "default" natpf1 "tcp-port80,tcp,,8000,,80";
````

but that doesn't work for me. if there's an alternate way you're finding that would be great.

**Comment by Sing-Li** [comment]
a question is ... are you running this on a macbook?     It is not a typical configuration to use a laptop for a server due to power-safe, etc.

**Comment by Sing-Li** [comment]
@marceloschmidt  hopefully you will cover running docker-compose - with mongo in a separate container. Thanks.

**Comment by mhkeller** [comment]
it's a desktop mac.

**Comment by mhkeller** [comment]
quick q. @marceloschmidt is this something you're currently working on or is longer term? I was going to try and give people a demo this week. I can run it in development mode but it would be great if I could stand it up to see how it's used by the weekend crew.

**Comment by marceloschmidt** [comment]
I'm currently working on it, but I have close-to-zero knowledge on docker. Picking up things as I go. I'm trying to move as quickly as I can, but honestly I don't think I'll be able to give you very detailed information in just a couple of days.

**Comment by mhkeller** [comment]
Got it. So we're in the same boat then! I'll do some research and if I come across anything that looks useful ill paste it here. 

Thanks for the help!

**Comment by marceloschmidt** [comment]
Okay, I was able to access my docker instance from another computer in my LAN, if that's what you're trying to accomplish. Assuming you named your docker `default`, this one-line command will create a tunnel from your host to your docker image:

`machine=default; ssh -i ~/.docker/machine/machines/$machine/id_rsa docker@$(docker-machine ip $machine) -L 8080:localhost:80 -N -f`

Now for other to access your docker image, they have to go to `http://<your_lan_ip>:8080`.

Hope that helps.

**Comment by marceloschmidt** [comment]
You can setup port forwarding in your VirtualBox application.

![image](https://cloud.githubusercontent.com/assets/1986378/9672795/1a3a0710-5274-11e5-8702-26511205a87d.png)

In my case, my lan ip was 192.168.25.45 and I assigned port 8080 to port 80 on docker. So other on my LAN could access http://192.168.25.45:8080 and see my docker instance running

**Comment by marceloschmidt** [comment]
BTW, you can add that port forwarding by running `$ VBoxManage controlvm "default" natpf1 "tcp-port80,tcp,192.168.25.45,8080,,80"
`

of course, change your ip and local port as desired.

**Comment by mhkeller** [comment]
Interesting so that works with port 8080 but not port 80 so perhaps it's a permissions issue. It also works for me without setting the Host IP to the LAN IP as long as I set it to 8080. This is great for now though! Thanks!

**Comment by mhkeller** [comment]
Adding what you need to change in `docker-compose.yaml` would also be great re: https://github.com/RocketChat/Rocket.Chat/issues/686

**Comment by mhkeller** [comment]
@marceloschmidt did you end up publishing that guide somewhere?

**Comment by marceloschmidt** [comment]
Nope, never did :( but yesterday I was giving docker another shot and I think I'll do it today again. If all goes as I expect, I'll create a wiki on setting it up. Thanks for the reminder.
