### ISSUE TITLE
Copy and Paste Disable (but keep for Admins/Owners/Moderators) ?

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#6761]
Rocket.Chat Version: 0.55.0-rc6
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5

Hi

Was just wondering if there is an easy way to disable the copy and paste feature as sometimes it is used to spam on our chat rooms.   The ability to remove this option would help fight alot of spamming especially when a moderator isn't around.

But i think giving permissions for moderators/admins to use it would be beneficial for things such as pasting rules of the rooms once in a while, etc.

Would appreciate some help in this.

Thanks

**Comment by Nemra1** [comment]
@WebSavvyGuy this for evry user...
<body oncopy="return false" oncut="return false" onpaste="return false">

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Going to close this. Disabling copy & paste via JS has always been a bad idea in the web. Disabling the spamming user would be the right course of actions.

Cheers
Thomas

**Comment by WebSavvyGuy** [comment]
@TwizzyDizzy

That would be the right course of action except theres no real ban or kick feature.  Users can come right back in.  One of the biggest problems of this application of the inability to get rid of problem users

**Comment by TwizzyDizzy** [comment]
I see and I feel your pain. Yet building the feature you requested here just to work around another missing feature (if that's the case, I'm not quite sure there) is also no viable option.

I think I have seen some other issues / requests around that had the topic of kicking/banning.

Cheers
Thomas

**Comment by WebSavvyGuy** [comment]
@TwizzyDizzy

Yes you are right alot of features requested months/years ago and still no action.  One of the reasons we’ve looked elsewhere for our chat solutions.

This app is more for small office environments not large scale public websites.
