### ISSUE TITLE
Use existing user database

### ISSUE THREAD

**Issue by BigBoiJefe** [RocketChat/Rocket.Chat#6762]
I wanted to know if it's possible to use an existing user database with RocketChat.  I have users logging into a frontend site and want to eliminate the need for them to create an account in RocketChat.  Any ideas?

Thanks!

Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: ?
Node Version:	v4.8.1

**Comment by WebSavvyGuy** [comment]
I am also wondering about this such as using an existing vbulletin database or other forums software.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
