### ISSUE TITLE
Video Recorder In worng position 

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#6765]
Rocket.Chat Version: 0.55.1
As u see
![2017-04-23_131614](https://cloud.githubusercontent.com/assets/22897987/25313081/a69ef76c-2827-11e7-8492-6f67c214ba8a.png)

**Comment by MartinSchoeler** [comment]
Can you please test this with the latest version? If the issue persists, please reopen this. Thanks!
