### ISSUE TITLE
Integrate with Zendesk

### ISSUE THREAD

**Issue by vyasjay2793** [RocketChat/Rocket.Chat#6769]
Hello,

Can someone help me for integrate Rocket chat with Zendesk in details.

Here below details of Rocket.Chat

Thanks

Rocket.Chat Version: 0.55.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0 x64

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
