### ISSUE TITLE
Hide Emojis in links

### ISSUE THREAD

**Issue by Flipez** [RocketChat/Rocket.Chat#6770]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

We sometimes have the issue that a link contains a MAC address which matches an emoji (such as flags).
Since I normally do not want emojis in my link this should be disabled somehow.

**Comment by wizofaus** [comment]
Sharepoint links often contain ":x:" which RC interprets as a cross. If you use ` ` it's not a clickable link.

**Comment by rgembalik** [comment]
We have a similar problem, also with SharePoint. Sharepoint creates links with `:x:` parts so it's replaced with emoji in RC, but that breaks the entire link. 

The full link looks like this:
`https://thecompany.sharepoint.com/:x:/s/SomethingOrOther/DasdasadgGOIAAmdoassdNVan-dasNb?e=asd`. After parsing it is replaced with a link containing `https://thecompany.sharepoint.com/`, then there is an ❌ emoji (outside of link element) and the rest of it is being displayed right after that as a plaintext `/s/SomethingOrOther/DasdasadgGOIAAmdoassdNVan-dasNb?e=asd`.

**Comment by ggazzo** [comment]
closed by #15516
