### ISSUE TITLE
Livechat Routing Method not changeable

### ISSUE THREAD

**Issue by whuber-work** [RocketChat/Rocket.Chat#6774]
Rocket.Chat Version: 0.52
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: v4.7.3

Livechat Routing Method is set to Least Amount. It's not possible to set it to Guest Pool.

**Comment by raelsan** [comment]
When you select Guest Pool there is no changes in your livechat-agent's menu ?

**Comment by whuber-work** [comment]
I can't even select guest pool

**Comment by sampaiodiego** [comment]
@whuber-work have you tried on a newer version?

also, I'm not able to reproduce this error even on version `0.52`.. using version `0.52` version what happens to me is: I choose _guest pool_, then hit _save changes_ and then after I refresh the page the still says _least amount_ .. *BUT* it is using guest pool.. 

you can confirm it's using `guest pool` when you have `OPEN LIVECHATS` item on left side bar:
![image](https://cloud.githubusercontent.com/assets/8591547/26405111/aada58ca-406a-11e7-96c8-68490aa52f0a.png)

**Comment by whuber-work** [comment]
I changed to 0.56 and can confirm: it changes to Guest_Pool and Open Livechats is also there. 
The reason this came up was that there were complaints about disappearing chats when I noticed that the setting changed somewhat magically to Least_Amount. If the problem with disappearing livechats persists I will open a new issue.
