### ISSUE TITLE
Slack import not completing

### ISSUE THREAD

**Issue by tmyoungjr** [RocketChat/Rocket.Chat#6778]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled (if this is whats being asked)
Node Version: 	v4.8.0

Went to import a slack backup into my brand new install of rocket.chat (I made zero changes to the admin section).   The server got VERY slow during the import and it took a very long time.  I let it run through the weekend.  Upon my return this morning I see users / channels and a small sample of the actual messages (about 10%).  The imported file was about 15MB.

The server itself is a VPS:

30GB HDD
1 CPU Core
2GB of Memory.

Attached is the log file that seems to stop on 4/22.  I rebooted today.   Restarted the import and see the same behavior.

[log.txt](https://github.com/RocketChat/Rocket.Chat/files/952240/log.txt)

**Comment by graywolf336** [comment]
```
Apr 21 16:06:17 localhost snap[1926]: Exception in callback of async function: TypeError: Cannot read property 'pipe' of undefined
Apr 21 16:06:17 localhost snap[1926]:   at gm.identify (/snap/rocketchat-server/616/programs/server/app/app.js:9384:20)
Apr 21 16:06:17 localhost snap[1926]:   at emitMany (events.js:108:13)
Apr 21 16:06:17 localhost snap[1926]:   at gm.emit (events.js:182:7)
Apr 21 16:06:17 localhost snap[1926]:   at gm.<anonymous> (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/getters.js:129:14)
Apr 21 16:06:17 localhost snap[1926]:   at cb (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:322:16)
Apr 21 16:06:17 localhost snap[1926]:   at gm._spawn (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:226:14)
Apr 21 16:06:17 localhost snap[1926]:   at gm._exec (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/command.js:190:17)
Apr 21 16:06:17 localhost snap[1926]:   at gm.identify (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_file/node_modules/gm/lib/getters.js:127:10)
Apr 21 16:06:17 localhost snap[1926]:   at GridFSStore.Meteor.fileStore.UploadFS.store.GridFS.transformWrite (/snap/rocketchat-server/616/programs/server/app/app.js:9399:44)
Apr 21 16:06:17 localhost snap[1926]:   at GridFSStore.transformWrite (/snap/rocketchat-server/616/programs/server/packages/jalik_ufs.js:2364:45)
Apr 21 16:06:17 localhost snap[1926]:   at GridFSStore.Store.self.write (/snap/rocketchat-server/616/programs/server/packages/jalik_ufs.js:2027:22)
Apr 21 16:06:17 localhost snap[1926]:   at /snap/rocketchat-server/616/programs/server/packages/rocketchat_importer.js:224:33
Apr 21 16:06:17 localhost snap[1926]:   at runWithEnvironment (packages/meteor.js:1176:24)
```
Seems to be an issue with the uploads

**Comment by tmyoungjr** [comment]
I forgot to note that this is Ubuntu 16.04 and I'm running the snaps (as is obvious in the log files above).  I saw the behavior during my first install so I wiped the VPS, built another from scratch and re-installed the snaps.   Same behavior again.

**Comment by graywolf336** [comment]
Yeah, seems something change either internally inside of Rocket.Chat or with Slack exports and the downloading of the files from Slack and into Rocket.Chat is breaking things.

**Comment by tmyoungjr** [comment]
I would expect probably the Slack Export (they can't have it being easy to get your hands on all of your message history without paying them through the nose :) ).  But of course if that changed it means RC has to change to keep up too

**Comment by justechn** [comment]
FYI, performed a similar task yesterday and it worked fine. I was using the docker version of rocket and had it hosted on my MAC. Also my slack export was only 3MB

**Comment by i1pro** [comment]
We are experiencing a similar problem.  The import gets stuck while importing users...  We have created users in Rocket, so some users were duplicated.  Any way to import only channels ?

**Comment by RELD** [comment]
Hey there,
first of all, brilliant work!

I am having issues importing data from slack too.
The importer stops for me half ways.. 
it is really not much. 1.5 MB.

I get this error message.
![screen shot 2017-08-03 at 12 05 55](https://user-images.githubusercontent.com/2292575/28916965-42891d80-7844-11e7-872b-bfdba2347e99.png)

Here the exception log:

`[34mI20170803-09:59:23.993(0) Exception in defer callback: TypeError: Cannot read property '_id' of undefined   at /snap/rocketchat-server/829/programs/server/packages/rocketchat_importer-slack.js:566:22   at Array.forEach (native)   at /snap/rocketchat-server/829/programs/server/packages/rocketchat_importer-slack.js:458:22   at Array.forEach (native)   at [object Object].<anonymous> (/snap/rocketchat-server/829/programs/server/packages/rocketchat_importer-slack.js:456:32)   at packages/dispatch_run-as-user.js:211:14   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)   at /snap/rocketchat-server/829/programs/server/packages/rocketchat_importer-slack.js:442:13   at Array.forEach (native)   at /snap/rocketchat-server/829/programs/server/packages/rocketchat_importer-slack.js:440:34   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at packages/meteor.js:445:45   at runWithEnvironment (packages/meteor.js:1176:24)  `

Any insights, or pointing directions on this are highly appreciated :)
Many thanks in advance!
Cheers
R

**Comment by graywolf336** [comment]
@RELD thanks, let us know if you end up finding out what it is.

**Comment by tjhorner** [comment]
I've run into this issue on my Rocket.Chat instance, and part of the problem seems to be that the file is uploaded via WebSocket instead of a normal HTTP file upload, and if it takes too long to upload the file, the WS will close so the file upload never completes. A workaround for this is (if you're able to) connect to the server locally and upload it through there. This should make the upload fast enough and it should import correctly.
