### ISSUE TITLE
add API method to request a single message

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#6783]
add a DDP/REST Method to request a specific message by its ID, to make the handling of messages which got a reply easier, with native applications

**Comment by graywolf336** [comment]
@arminfelder How would you envision this being done? Like what would the name of the real time api be called and what would the rest api endpoint look like?

**Comment by arminfelder** [comment]
something like
REST:
/api/v1/message.get:
- payload
- - messageId 

DDP Method:
getMessage:
- payload
- - messageId
