### ISSUE TITLE
add API method to get metadata of all messages between a certain timespan

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#6784]
add a DDP/REST method, which gives metainformation for a specific timespan, like:
- number of messages
- first/last timestamp and message id
- list of messageIds
- if limited(max 50msgs), number of "pages" etc.

to make it easier to fill gaps on local cache of native clients

**Comment by MartinSchoeler** [comment]
Hey @arminfelder you can use the "history" call for that https://rocket.chat/docs/developer-guides/rest-api/channels/history . Thanks for the feedback!
