### ISSUE TITLE
Special characters in code blocks sometimes displayed as non-interpreted HTML entities

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/Rocket.Chat#6789]
Rocket.Chat Version: 0.55.0-rc.6
Running Instances: 1
DB Replicaset OpLog: _I'm sorry, but I have no idea what this is. Administration -> Info says "OpLog: Disabled". Is that what is asked here?_
Node Version: v4.5.0

Hi,

in many cases where I paste code in a \`\`\`code\`\`\` block into a Rocket.Chat chat, Rocket.Chat will convert some of the special characters into HTML entities which are then displayed verbatim (e.g. single quotes are displayed as `&#39;`). As far as I can figure out, this happens when the \`\`\` isn't preceded/followed directly by a newline.

This works fine:

    ```
    'Test'
    123
    ```

It is displayed as:

```
'Test'
123
```

This doesn't:

    ```'Test'
    123```

It is displayed as:

```
&#39;Test&#39;
123
```

This may be a client bug. The following clients will display non-interpreted HTML entities:

- Ubuntu Rocket.Chat+
- Windows Rocket.Chat+
- iOS Rocket.Chat
- Android Rocket.Chat
- Web site in Google Chrome on Ubuntu

These clients will interpret the HTML entities:
- iOS Rocket.Chat+
- Android Rocket.Chat+

**Comment by martinvonwittich** [comment]
Links are affected too.

```
["Google"](http://google.com)
```

is displayed as

```
&quot;Google&quot;
google.com
Google
```

instead of

```
"Google"
google.com
Google
```

**Comment by ElCoyote27** [comment]
Also seeing this on 	0.56.0-rc.1

**Comment by martinvonwittich** [comment]
Links are still broken for me - `["Google"](http://google.com)` is rendered as `&quot;Google&quot;` in our Rocket.Chat.
