### ISSUE TITLE
error when uploading favicon

### ISSUE THREAD

**Issue by justechn** [RocketChat/Rocket.Chat#6791]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog:
Node Version:

I just installed the docker image to test this out, but when I try and upload a favicon I get an error
```
Invalid file type
image/vnd.microsoft.icon
```
![screen shot 2017-04-25 at 10 35 53 am](https://cloud.githubusercontent.com/assets/1508662/25396993/f292bffa-29a3-11e7-839d-5b58dc5426d6.png)
this should be a valid favicon format

FYI I used [this website](http://www.favicon-generator.org/) to generate the icon incase you want to test it

**Comment by saeedjalali1** [comment]
Hi @MartinSchoeler .
Why this feature is not working?
How to fix it ?

**Comment by rrepolona** [comment]
hi,

we also have the same issue with uploading asset files we cannot upload it, saying "Invalid file type"
plus also we have problem deleting the files for favicon.png (64x64/96x96,128x128). 

![screen shot 2017-05-12 at 12 32 02 pm](https://cloud.githubusercontent.com/assets/5317204/25982481/6e216090-370f-11e7-82df-c779f57de5e5.png)

asking assistance anyone have the same problem po?

**Comment by davidsiaw** [comment]
It is an issue. I cannot upload a favicon too

**Comment by ccfiel** [comment]
any idea how to solve this problem?

**Comment by Supermathie** [comment]
Indeed, us as well on commit 65e06c283226ddb56f2d3a592dfc31df09115421. Here's a file I'm having trouble with: [rocket-chat-discourse.ico.gz](https://github.com/RocketChat/Rocket.Chat/files/1580898/rocket-chat-discourse.ico.gz)

Created using:

```
convert rocket-chat-discourse.png -define icon:auto-resize=128,64,48,32,16 rocket-chat-discourse.ico
```

**Comment by kvingedal** [comment]
I have the same issue as well

**Comment by cdiegosr** [comment]
we have too!

**Comment by rammurthyuio** [comment]
I'm facing the same issue.
Rocket chat version: 0.61.0

Is this solved yet?

**Comment by alexleosumy** [comment]
I have the same issue
RocketChat v 0.62.2

**Comment by rudygodoy** [comment]
I'm running 0.62.1 and facing the exact same issue. Nothing on logs.

**Comment by jamescgalindo** [comment]
You'll need to use another browser. I used Safari and it worked! I was able to set all of my .ico files. Crazy.

**Comment by rudygodoy** [comment]
@jamescgalindo I've tested in Safari, Firefox and with the Desktop client. Problem persist.

**Comment by jamescgalindo** [comment]
Weird....I'm using Safari Version 11.1 (13605.1.33.1.2)
![screen shot 2018-04-15 at 5 31 49 pm](https://user-images.githubusercontent.com/8353776/38785289-ebf16e0c-40d2-11e8-8d86-187d7a254775.png)

**Comment by jamescgalindo** [comment]
I jumped back over to Chrome and all was good.

**Comment by rudygodoy** [comment]
I was able to upload the favicon using the latest Firefox. So, the problem seems to be reduced to the desktop app and Safari < 11.1

**Comment by cloudsandladders** [comment]
I am getting this error as well.  "Invalid file type image/x-icon"

**Comment by ooguz** [comment]
Hello everyone,

I was getting this error and there is no real solution on the web.

The solution is:

- Go to "Administration"
- Enter "File Upload" section
- Append the file type which you get error at the end of "Accepted Media Types" field

Screenshot is on the link:

[https://hackerspace.ist/ico_problem_solution.png](https://hackerspace.ist/ico_problem_solution.png)

Have a nice day!

**Comment by yb-shin87** [comment]
I got same issue (File type invalid image/x-icon)...upload favicon.ico even though I added image/x-icon

**Comment by jdpond** [comment]
File type invalid image/x-icon
![image](https://user-images.githubusercontent.com/271131/55290249-e1d0b380-539e-11e9-8480-168699be2830.png)
Have tried multiple types of upload and image/x-icon added to File Upload
