### ISSUE TITLE
Enter instantly 	to first room after login

### ISSUE THREAD

**Issue by qstore** [RocketChat/Rocket.Chat#6794]
Hello everyone!

I hope you can help me with the following topic:

If user login into a chat with Oauth, or after registration, then  enter automatically to the first channel.
I find the "home page" unnecessary.

Rocket.Chat Version: 0.54.2

What now:
https://gifyu.com/image/bzib

What I want:
https://gifyu.com/image/bziH

Thanks in advance
Rocketchat is really great!

**Comment by qstore** [comment]
I added 15$ bountysource.

https://www.bountysource.com/issues/44518290-enter-instantly-to-first-room-after-login

**Comment by qstore** [comment]
Please add bounty label.

**Comment by engelgabriel** [comment]
This needs to be implemented as an optional setting.

**Comment by novuu** [comment]
I would prefer to store last logged in URL and upon new login, redirect the user to that URL

**Comment by jvacek** [comment]
I'm assuming that this has been implemented by the First channel after login?
![](https://ptpimg.me/wxublg.png)
For some reason I'm still being redirected to home. Is this feature documented anywhere?
Same as https://github.com/RocketChat/Rocket.Chat/issues/4478#issuecomment-404994074

**Comment by jvacek** [comment]
As I mentioned in the other issue, my problem was that I was prepending the channel with a `#`, while it should not be prepended, instead just use `channel`
