### ISSUE TITLE
Livechat Agent Priority

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#6802]
Rocket.Chat Version: 54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.0

I might be missing something but is there any way to assign Agent Priority in Livechat ?

Or how does Rocket determine who to send a new chat to?

**Comment by raelsan** [comment]
There are 2 ways to manage new chat.

- 'Least amout' (default) -> the agent with the least number of open chats is paired with the incoming livechat.
- 'Guest pool' -> An incomming livechat is created as an Inquiry which is picked up from an agent. An Inquiry is visible to all agents (TODO: in the correct department). A room is still created with the initial message, but it is occupied by only the client until paired with an agent.

**Comment by reetp** [comment]
How does the system decide when there are no chats, or say you have 2 agents with equal amounts of chats?

Just curious :-)

**Comment by raelsan** [comment]
I looked at the code and I feel it depends on the order in which the agents accounts have been created.
In your example, If the agent A has been created before the agent B, an incomming livechat will be assigned to the agent A.

**Comment by reetp** [comment]
OK and thanks for looking.

Might be easier to see the (numeric?) assignments and be able to vary them I guess. That would be a NFR.

Guest Pool - do all Agents get notified on a new chat?

**Comment by raelsan** [comment]
All agents see all requests in their menu. Everyone can choose which customer(s) they wish to talk with.
When an agent takes a request, this request moves to another part of the menu and the agent is now the only one who see the chat.
One thing cool is when the agent click on the request, there is an alert with the first customer message and the agent can choose if he want to take the request or not.
During the conversation, the agent can return the request to the list of requests and another agent can takes it.
