### ISSUE TITLE
Fade message not pinned or starred over x-days old.

### ISSUE THREAD

**Issue by reformstudios** [RocketChat/Rocket.Chat#6803]
Rocket.Chat Version: 	0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version:v4.8.1

Feature request : 

Fade message not pinned or starred over x-days old (eg to make it more visually clear that a message in a thread is old).

**Comment by theorenck** [comment]
Hi @reformstudios we have a partial solution to your problems built in the prune messages feature (a filter for pinned messages). We don't plan to add a filter for starred messages cause it was a "per user" selection.
