### ISSUE TITLE
Post ReadOnly permission is automatically removed

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#6805]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version:v4.7.3

Noticing an issue where the post readonly option gets automatically removed from a role. Anybody else had this issue?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
