### ISSUE TITLE
Pressing ESC in the administration instantly closes it, causing me to lose all my changes

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/Rocket.Chat#6806]
Rocket.Chat Version: 0.55.0-rc.6
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

Hi,

I'm currently tinkering with the JS code of an integration (Administration -> Integrations -> <Integration> -> Script) that I've written. Due to the fact that I'm very used to `vim`, I often instinctively press ESC while editing texts; in Rocket.Chat, this causes the administration area to close immediately, causing me to lose all my open changes. That's pretty annoying :/

**Comment by Hudell** [comment]
Couldn't replicate the issue described on the current version. Since it's a very old report, I'll be closing it.
