### ISSUE TITLE
Anonymous user doesn't see topic nor description changes until a refresh

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#6818]
After anonymous user joins a channel it doesn't see topic nor description changes until a refresh:
![image](https://cloud.githubusercontent.com/assets/1000217/25466201/462bf26e-2add-11e7-90cb-df383e46051e.png)

**Comment by ggazzo** [comment]
fixed, use the last version.

![image](https://user-images.githubusercontent.com/5263975/40385932-a279ba3a-5dde-11e8-9561-37e7e6ba2016.png)
