### ISSUE TITLE
Desktop Notification does not work

### ISSUE THREAD

**Issue by anhld** [RocketChat/Rocket.Chat#682]
From the feature list, i can see the Desktop Notifications feature, but it seems that feature does not work correctly, at least for me. Is that feature enabled by default? if not, then how i can enable it?

**Comment by geekgonecrazy** [comment]
Did it work before your recent pull request? #680 

It usually asks you when you very first visit.

**Comment by geekgonecrazy** [comment]
Actually turns it has stopped working.  Its on the agenda to fix.  :)

**Comment by anhld** [comment]
No, it does not work before #680 . I granted notification permission when the browser asked.

**Comment by geekgonecrazy** [comment]
@anhld turns out it hasn't been working for a bit.  We'll get this fixed. :)

**Comment by anhld** [comment]
@geekgonecrazy ok cool, thanks :)

**Comment by soonahn** [comment]
looks like whatever was calling `showDesktop` is no longer calling it

```
justin@destiny: ~/grh/rocket-chat (master)$ git grep showDesktop
client/lib/notification.coffee: showDesktop: (room, msg) ->
```

Can't seem to find in the history where it originally worked.
