### ISSUE TITLE
Would like app to open when clicking link in email notification

### ISSUE THREAD

**Issue by OnthegOinOz** [RocketChat/Rocket.Chat#6820]
Rocket.Chat Version: all
Running Instances: 
DB Replicaset OpLog:
Node Version:

Hi community, 
My first time in the forum so forgive me for jumping straight into a challenge we have. My name is Cameron and we have and continue to work really hard to integrate RC with our platform uBegin.com. One thing that's come up now is that when people click the link in an email to view a message on RC it's defaulting to view it in the browser.

Ideally if on a mobile it would open in the app or prompt a customer to download the app. If on a desktop the same. 

As it opens in a browser, for us we're finding it really confuses customers. Because then they have to login into a screen that's not our website. And if they have the app installed already, they don't understand why they're going to a browser?

We have enough challenges trying to make the integration smooth, so I'm wondering if anyone has any thoughts about making this possible?

I'd app appreciate any feedback from the community.

Thanks in advance
Cameron

**Comment by rafaelks** [comment]
@OnthegOinOz Thanks for opening the issue! That's a great idea, actually. We really want to integrate the native apps with deep links and Universal URLs.

I created an issue on the iOS native project to support it: https://github.com/RocketChat/Rocket.Chat.iOS/issues/440.

It's not a simple feature, but definitely worth it. I guess we can open the issue on Android project too, right @laggedHero?

**Comment by laggedHero** [comment]
I created an issue on Android.

Idk how Universal URLs would work with custom deploys and the default app. But with deep linking, it should be easy to support them.

@rafaelks Does deep link on iOS supports custom schemas?

Something like:
`https://my-custom-deploy/general` could map to `rocketchat://my-custom-deploy/general`

**Comment by rafaelks** [comment]
@laggedHero Yeah, that's the trick part. On iOS, you need to have a deep link scheme (for example: `rocketchat://` or support a specific universal URL, like `https://rocket.chat`. But let's think about it, maybe we can do some tricks on the back-end too, to redirect user to the default URL scheme too, you know?

**Comment by laggedHero** [comment]
We could have a redirect service and work on top of it (like the push gateway).

That could work, too.

**Comment by OnthegOinOz** [comment]
This is great and unexpected quick response :)
To clarify we are looking at this for both mobile and desktop environments, iOS / Mac, Android, and windows. There would be only a very very small amount if any of people in our community with Linux.

**Comment by OnthegOinOz** [comment]
Hmm thinking about that... Linux is an incredible community. We're an early stage platform so we just have not connected into that community yet but I suspect it's going to happen some time.

**Comment by OnthegOinOz** [comment]
Checking in to see if any further thoughts have emerged about this? Being new I'm not sure of the general process in the community for helping features arise?

**Comment by rafaelks** [comment]
@OnthegOinOz We've created the issues on the clients, at some point, we'll start implementing it.

**Comment by OnthegOinOz** [comment]
@rafaelks thanks for letting me know of the updates. Let me know if we can help out? Not sure how? Customer trials? Our Dev unfortunately does not know meteor

**Comment by rafaelks** [comment]
@OnthegOinOz I'm sure that we'll start to develop this feature soon, I'll let you know here on the issue. In the mean time, if you want to help us to test our beta apps, just let send me the emails you want to assign to beta: rafael.kellermann at rocket dot chat.

**Comment by aviv-ko** [comment]
Hi, did anyone solve the issue @OnthegOinOz reported below:
"As it opens in a browser, for us we're finding it really confuses customers. Because then they have to login into a screen that's not our website. And if they have the app installed already, they don't understand why they're going to a browser?"

**Comment by rafaelks** [comment]
Hello guys,

This can already be done on iOS and will be available very soon in Android as well, here's the documentation to do that: https://rocket.chat/docs/developer-guides/deeplink/#deeplink.

I'm closing the issue for now, but we can keep the discussion if you guys have any question.

Thank you!
