### ISSUE TITLE
Capability to change notification E-mails

### ISSUE THREAD

**Issue by failattu** [RocketChat/Rocket.Chat#6822]
Rocket.Chat Version: 	0.55.1
Running Instances: 1
DB Replicaset OpLog:false
Node Version: v4.8.0

So we have an instance running and it sends e-mails to the users as notifications. We would like to change these to have more information such as the real name of the person sending message e.g. 

Could we have the same kind of options as we have for registration etc.

**Comment by rjozwiak** [comment]
Any updates on it?

**Comment by engelgabriel** [comment]
This has been done.
