### ISSUE TITLE
Copypasting the first line from a code block may introduce an invisible leading newline

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/Rocket.Chat#6823]
Rocket.Chat Version: 0.55.0-rc.6
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

1. Type (or copy-paste from this bug report) the following text into a Rocket.Chat conversation:

       ```
       Test
       ```

2. Rocket.Chat displays it like you would expect:

       Test

3. Double-click the "Test" in Rocket.Chat, hit <kbd>Ctrl</kbd>+<kbd>c</kbd> and paste it into an editor. You'd expect the following (the string "Test" on it's own line):

       Test

   but you get instead a newline, and then "Test":

   ```
   
   Test
   ```

This is pretty annoying if you want to paste stuff from Rocket.Chat into a terminal.

**Comment by MartinSchoeler** [comment]
This bug still exists on ver.  0.71.1

**Comment by gabriellsh** [comment]
Tested now, doesn't seem to happen anymore. If you still face this, please reopen.
