### ISSUE TITLE
Reset the unread marker without changing tab

### ISSUE THREAD

**Issue by Ulrar** [RocketChat/Rocket.Chat#6824]
Hi,

Currently when I have finished reading a channel, I have to switch my browser to another tab to make sure the unread marker sets itself to where I've read.
It would be great to have a way, ideally with a keybinding, to set that marker exactly as if I've switched to another tab, but without doing so. The goal being to be able to just leave rocket.chat there and go do something else in another window without having to bother with tabs all the time.

In my IRC client I've bound ^u for that, but I guess anything would do. I have seen the "Mark as unread" feature, but being switched off the channel isn't really what I'm looking for, I basically would just like a way to control the "unread" marker myself I guess.

**Comment by marceloschmidt** [comment]
The read marker should go away when you've read the messages. If it doesn't, you could also hit "ESC" to make it go away. If that's not happening, this is most likely a bug. Please advise.
