### ISSUE TITLE
Room stuck in Loading

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#6825]
Rocket.Chat Version: 0.51
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.6.2

After couple of **refresh / hard refresh**, the room is **stuck** in loading animation.

![bug](https://cloud.githubusercontent.com/assets/4321549/25490654/317e1c56-2b8d-11e7-894b-8690ba6dc61b.gif)

**Comment by geekgonecrazy** [comment]
Can you open up the javascript console and see if you see any errors? Ctrl+shift+i then the console tab

**Comment by ramanamatya** [comment]
@geekgonecrazy Here it is
![screen shot 2017-04-28 at 9 46 36 am](https://cloud.githubusercontent.com/assets/4321549/25513780/ad0ab27a-2bf7-11e7-955c-51ddd2bfa23f.png)

**Comment by geekgonecrazy** [comment]
I think I've seen this happen before.  I'm not sure how to reliably reproduce

**Comment by ramanamatya** [comment]
Hmm, thank you, i would try to replicate it in higher version of rocketchat, lets see what will happen.

**Comment by ramanamatya** [comment]
@geekgonecrazy, having the same problem with Version: **0.56.0-develop** as well.

After couple of refresh, the room is stuck.

![screen shot 2017-04-28 at 1 18 05 pm](https://cloud.githubusercontent.com/assets/4321549/25518884/51146a74-2c15-11e7-8563-6193ddc3afe3.png)

**Comment by MartinSchoeler** [comment]
@geekgonecrazy This happens to me every now and then, and i have to leave the channel and enter it again to make it work. Happens both on demo and local

**Comment by cyclops24** [comment]
Part of #8494

**Comment by engelgabriel** [comment]
I believe this was fixed. Please reopen if the problem persists.
