### ISSUE TITLE
Silent Switch on Windows don't Work

### ISSUE THREAD

**Issue by alexandrebgagne** [RocketChat/Rocket.Chat#6826]
MSI lunches as silent but prompt for the directory to finish the installation. 

Tried with the Client installer 2.5

Thank you

**Comment by geekgonecrazy** [comment]
@alexandrebgagne can you create this issue on the desktop client: https://github.com/rocketchat/rocket.chat.electron

**Comment by alexandrebgagne** [comment]
Done. Thank you
