### ISSUE TITLE
Can't change logging config parameters

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#6828]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: N/A
Node Version: 4.7.3

On the Administration -> Logs page, the "Log Level" and "Debug_Level" parameters can be changed on the UI, but not saved (the "Save Changes" button greys out).  The other fields on the page do not exhibit this behavior (i.e. changing "Show Package and "Show File and Line" work w/o problems).  Attempted to set the two values directly via mongo update commands and REST API calls.  Both succeed (JSON in collection updated and API calls returned with success status), however the logging level, etc does not increase in the log output and the UI does no update.

No workaround that we have been able to find as of yet.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
