### ISSUE TITLE
API - integrations.create fails for "webhook-outgoing"

### ISSUE THREAD

**Issue by MatthiasKainer** [RocketChat/Rocket.Chat#6829]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

When following the documentation from [the documentation](https://rocket.chat/docs/developer-guides/rest-api/integration/create) I receive a 

```json
{
  "success": false,
  "error": "Invalid event type [error-invalid-event-type]",
  "errorType": "error-invalid-event-type"
}
```

From [source](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/integrations.js) I can see there is an undocumented event attribute, but I don't know what to insert. Can you provide information on what to insert here pls? If you want I can help updating the documentation.

Thx,
M :)

**Comment by graywolf336** [comment]
I'm in the process of updating the documentation for everything, but it can be any of these: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/lib/rocketchat.js

**Comment by MartinSchoeler** [comment]
Fixed in https://github.com/RocketChat/docs/pull/652
