### ISSUE TITLE
Problems with analytics

### ISSUE THREAD

**Issue by RichOnPeers** [RocketChat/Rocket.Chat#683]
How does the "analytics" setting work in the admin interface?
I tried with pasting both the UA-... code and the script tag into the field but it doesn't seem to work as no data is logged to Google analytics.
##

**Comment by geekgonecrazy** [comment]
@RichOnPeers looks like the version we're including is Google Tag Manager.  Which from what i'm seeing is completely different. 

I'll look into this and see if there is a specific reason.  :)

**Comment by marceloschmidt** [comment]
We should have a radio button for alternatives (Analytics / Google Tag Manager)

**Comment by engelgabriel** [comment]
We should have 2 settings:
- Google TAG Manager
- Google Analytics
- Custom Tracking Code (textarea)

**Comment by gtribut** [comment]
Is this something that has been added ? I can't find it in last version (only google tag manager ID) and I don't find anymore the entry in the Nice-to-have milestone.

**Comment by marceloschmidt** [comment]
@gtribut we haven't had the time or resource to do it yet. Feel free to open a PR if you can.

**Comment by engelgabriel** [comment]
@RocketChat/core any ideas on how to make the Tag Manager work on demo?

**Comment by flantascience** [comment]
I was able to get the Tag Manager installed.  The trouble I'm having, is I'd like to use Tag Manager to add a Meta Title and Meta Description to the site.  I've not been able to do that..... or maybe there is another way?

**Comment by engelgabriel** [comment]
@flantascience the Title will come form `Site Name` on the Admin -> General config.

**Comment by engelgabriel** [comment]
You can now add any custom meta tags at the `/admin/Meta` -> Custom Meta
