### ISSUE TITLE
login RC without registering?

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#6832]
I` iframe` RC in my website as part of my website. But now i have two register system, RC and main site. I wish user can use RC right away after they register main site instead of registering two sites. Is there a way that user can login RC or see RC chat page right away without registering?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
