### ISSUE TITLE
Threaded messages missing from Slack import

### ISSUE THREAD

**Issue by pshute** [RocketChat/Rocket.Chat#6833]
Rocket.Chat Version: 	0.55.1
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5.0

We've imported all messages from our Slack team. The messages that were threaded are missing. I assume the import doesn't handle this relatively new message type.

**Comment by graywolf336** [comment]
It doesn't because Rocket.Chat doesn't have threaded messages. How would you propose the imported messages appear which are on the threads?

**Comment by pshute** [comment]
I guess the simplest way is for it to ignore the threading information and just import them as normal messages. It looks like the required xml fields are all there for that.

Given that they're likely to suffer from lack of context, the text could be suffixed with a warning like "(was part of Slack thread)". A more sophisticated approach would be to include some kind of pointer to the start of the thread. I'm not sure how easy it would be to include a URL, but it looks like the xml includes the timestamp of the start of the thread, so that could be included. E.g "(was part of thread started 5 May 2016 3:57pm)".

I'd appreciate some tips on how to do a workaround to get this data in now. Can I extract and manipulate the threaded messages into something suitable for import? The import documentation isn't clear about how imports work after you've done the initial import. Do they just add to what's already there, rather than replace it all? Do I need to include the usernames file, and if I do, will it duplicate all the users?

Would it be simpler to use csv importing?

**Comment by pshute** [comment]
It's probably also important to warn the user that threaded messages will be lost/altered during importing. Maybe it already does, it wasn't me that did the import.

**Comment by pshute** [comment]
After checking more carefully, it looks like SOME threaded messages have been imported as normal messages. I'm not sure if I'm just misinterpreting the JSON files. I noticed that some of them have extra fields, where they've been edited or have attachments. Perhaps those are being rejected.

**Comment by zdumitru** [comment]
Now that Threads functionality has been released, Slack threaded messages should probably be imported as RC threads as well.

**Comment by engelgabriel** [comment]
> We have decided that was better to delay our v1 release and get the Threads done properly than get the feature out the way it was initially implemented on the develop branch. We have "rebranded" our current implementation of Threads to Discussions (was it creates a new room type) and will implement Threads exactly the same way as Slack does.
>
> In our vision there are 2 different use cases on how to break out of the main conversation: one very easy and organic, with a single click for small side talk, and other, much more structured, that creates a new conversation with its own life cycle.
>
> We have tried to have a single solution for both, and as a result, no one was happy with it.
So we have given up on having a single approach for both use cases and will implement both: the Slack-like industry standard and our brand new one, called Discussions.

https://github.com/RocketChat/Rocket.Chat/issues/13843

**Comment by lpilz** [comment]
Hi, my organization would very much like to migrate from Slack to Rocket.Chat in the near future. Since we have a lot of messages though, it would be great to be able to import threads so channels are not cluttered.

Is there any ongoing work where I/we could participate maybe? I am a total js noob, but already looked at the code a bit. It seems, the major issue is the conversion of Slack message ids (timestamps) to Rocket.Chat ids in convertSlackMessageToRocketChat. Is that correct?

**Comment by lpilz** [comment]
I hope I found a good implementation for the import of thread messages here. Since this is my first time contributing to a project, I am very eager for reviews and criticism of my changes :)
