### ISSUE TITLE
Cannot upload file without extension

### ISSUE THREAD

**Issue by adam-wierzbicki** [RocketChat/Rocket.Chat#6834]
I am trying to upload a plaintext file without extension to Rocket.Chat. The file simply does not upload. No error message is displayed.

I am using an instance hosted on rocket.chat cloud.

```
Rocket.Chat Version: 0.55.1
Running Instances:   1
DB Replicaset OpLog: Enabled
Node Version:        v4.8.0
```

**Comment by martinvonwittich** [comment]
This might be a duplicate of  #6813

**Comment by JakeSteam** [comment]
Note that on my instance (0.54.2), I can upload an extensionless file, but "INVALID RESPONSE" is received when trying to download it again.

**Comment by adam-kulagowski** [comment]
Issue was fixed by bumping version to 0.56. 
Most likely it was fixed by https://github.com/RocketChat/Rocket.Chat/pull/6935

**Comment by staticjinno** [comment]
i'm on 0.57.3. i'm able to an extension-less file, but trying to download it will fail in browser & do nothing in app.

**Comment by geekgonecrazy** [comment]
@staticjinno if you're having issues downloading the file that's a different issue.  Please search for that ticket or open one for it. Thanks!

Going to go ahead and close this, as this particular issue I believe is resolved.
