### ISSUE TITLE
Unable to  mute or unmute users in room

### ISSUE THREAD

**Issue by lewyg** [RocketChat/Rocket.Chat#6835]
Rocket.Chat Version: 0.55.1

When I try to mute or unmute user(test) in room, I get this message:

`/mute @test`
`The user `#test` is not in this room.`

It is probably caused by wrong ifs in files
[mute.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-slashcommands-mute/server/mute.js#L29)
[unmute.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-slashcommands-mute/server/unmute.js#L29)

Instead of 
`if ((room.usernames || []).includes(username))`
should be
`if (!(room.usernames || []).includes(username))`

**Comment by Nemra1** [comment]
confirm this bugs
![2017-04-30_115334](https://cloud.githubusercontent.com/assets/22897987/25563376/af5c1dde-2d9b-11e7-8e70-df8d092136d3.png)
