### ISSUE TITLE
If there are any rest api to create a direct message channel ?

### ISSUE THREAD

**Issue by qeesung** [RocketChat/Rocket.Chat#6838]
If there are any rest api to create a direct message channel ? I try to create a "channel" or a "group" to test "im" test api, but always throw a exception "RequestError: No direct message room found by the id of: maNZDcap8o99stiry"

**Comment by graywolf336** [comment]
The concept of "creating a direct message channel" doesn't exist inside of Rocket.Chat, your room will be "created" as soon as you send a message to someone the first time

**Comment by qeesung** [comment]
@graywolf336 If there are any rest api to send a message to some one ?

**Comment by madguy02** [comment]
@graywolf336 
If  set the group type to "p" then catched `"RequestError: The private group type is the same as what it would be changed to."`, If do not set the type , then got the `"RequestError: No direct message room found by the id of: kSHywTvStJW9gjL3i"

**Comment by madguy02** [comment]
@MartinSchoeler please look into it: https://rocket.chat/docs/developer-guides/rest-api/groups/settype

**Comment by MartinSchoeler** [comment]
@qeesung you have to call [this](https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage) passing the wanted user id on the channel field.
