### ISSUE TITLE
Selecting Text is disabled on touch screens.

### ISSUE THREAD

**Issue by soonahn** [RocketChat/Rocket.Chat#684]
On my Lenovo T450s, I can't select text on the webpage.  Replicated in machines with touch screens such as the X250s, and a Microsoft Surface Pro.

Touch Events disable the ability to select text in the webpage.

**Comment by AdrianoCahete** [comment]
I fixed locally, but we still have a problem to select messages:
- When you do long touch for a few seconds on user message or username, Rocket.Chat open a "Delete/Report" panel (which i can't cancel -- i can't find this bug, but i already see here);
- When you double click/touch a username, it's opened a user info panel

You can copy everything who don't trigger a function.

The same interations are tested in Google and Reddit sites with Chrome @ DevTools Touch Mode and an Android Phone.

I'll make a PR soon.

**Comment by geekgonecrazy** [comment]
@AdrianoCahete yeah it not closing is another bug
