### ISSUE TITLE
windows 2012 R2 installation error

### ISSUE THREAD

**Issue by reza6610** [RocketChat/Rocket.Chat#6841]
i would like install rocket.chat on windows server 2012 r2 .i done Pre installation but when i started rocket.chat installation some errors occurred . following the error list : 

C:\rocketchat\bundle\programs\server>npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
/
> fibers@1.0.5 install C:\rocketchat\bundle\programs\server\node_modules\fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio
instead.

C:\rocketchat\bundle\programs\server\node_modules\fibers>if not defined npm_conf
ig_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node
 "" rebuild --release )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: ENOENT: no such file or directory, open 'C:\rocketchat\bun
dle\programs\server\node_modules\fibers\undefined'
gyp ERR! stack     at Error (native)
gyp ERR! stack     at Object.fs.openSync (fs.js:549:18)
gyp ERR! stack     at Object.fs.readFileSync (fs.js:397:15)
gyp ERR! stack     at readCAFile (C:\Program Files (x86)\nodejs\node_modules\npm
\node_modules\node-gyp\lib\install.js:466:15)
gyp ERR! stack     at download (C:\Program Files (x86)\nodejs\node_modules\npm\n
ode_modules\node-gyp\lib\install.js:438:22)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\install.js:185:19
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\mkdirp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild" "--release"
gyp ERR! cwd C:\rocketchat\bundle\programs\server\node_modules\fibers
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\rocketchat\bundle\programs\server\npm-debug.log

C:\rocketchat\bundle\programs\server>
C:\rocketchat\bundle\programs\server>cd ../..

C:\rocketchat\bundle>node rocket.service.js install
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\rocketchat\bundle\rocket.service.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

C:\rocketchat\bundle>net start Rocket.Chat

Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

please help me.

**Comment by matthewshirley** [comment]
What is your node version? 

`node -v` in command line

**Comment by matthewshirley** [comment]
The build you're trying to install needs fibers 1.0.5 which needs an old version of node (0.10.40) to install. 

You could try to do an installation with node 0.10.40 (use nvm to switch). However, I believe you need node 4.5 for other Meteor dependencies.

**Comment by MartinSchoeler** [comment]
@reza6610 you have to use the command `meteor npm install` instead of `npm install`
