### ISSUE TITLE
Messages marked as edited even if there are no changes

### ISSUE THREAD

**Issue by jodizzle** [RocketChat/Rocket.Chat#6843]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.0

This isn't a bug per se, but if I go to edit a message and then press the Enter key without making any changes, the message is still marked as edited.

It's true that I can press ESC to cancel the edit (or press the down arrow key one or more times), but it would be nice if Rocket.Chat was tolerant of Enter with no changes as well.

**Comment by MartinSchoeler** [comment]
This issue is still present in 0.71.1

**Comment by ggazzo** [comment]
closed by #13053
