### ISSUE TITLE
Better-explain default settings in Notifications dialog

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#6846]
Rocket.Chat Version: 0.55

Hi, see below screenshot for reference.

If a setting is default ("account preference"), it should explicitly show the user what the default actually is. e.g. for Audio, it should say **Chime (default)** instead of **Use account preference**. (This applies to all settings in the dialog that have a default.)

![rc-notifications](https://cloud.githubusercontent.com/assets/295571/25564801/7e8a4456-2dc3-11e7-9f08-86b34843b9d1.png)

**Comment by antgel** [comment]
@karlprieb Any updates on this? :)

**Comment by rohitkatlaa** [comment]
Hi, I am Rohit.
@marceloschmidt @ggazzo @MartinSchoeler Can I solve this issue please?

**Comment by 26thavenue** [comment]
@ggazzo Can I work on this

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
