### ISSUE TITLE
Info menu doesn't show up

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#6847]
When you click on the name of a user in a channel, the info menu on the right doesn't show up.

Rocket.Chat Version: 0.55.1 
Running Instances: 1
Node Version: v4.8.1

**Comment by MartinSchoeler** [comment]
@avignat is there any errors in your browser console?

**Comment by avignat** [comment]
No errors in browser console. The amazing thing is that, if I click the :bust_in_silhouette: (on the right) the informations of the user have been loaded.
