### ISSUE TITLE
Blank screen every so often

### ISSUE THREAD

**Issue by fabiancook** [RocketChat/Rocket.Chat#6849]
Hi, 

We are receiving a blank screen when opening RocketChat not through the iframe, meaning we can't log into the admin account. 

Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.6.2 - x64

**Comment by MartinSchoeler** [comment]
@fabiancook Yes the default login form is disabled when you use a iframe login. You can login as admin by opening your browser console and using the command `Meteor.loginWithPassword('username-or-email', 'your-password');` . You can read more about that here https://rocket.chat/docs/developer-guides/iframe-integration/authentication Thanks for the feedback!
