### ISSUE TITLE
[Feature Request] Handle users on vacation

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#6852]
We thought of a couple of ideas for this:

1. Have ability for users to define an auto-responder. Options could be set for it running in private chat and / or public / private channels, together with how often it should respond (don't spam more than once per time-period).
2. Add "vacation" status to list of statuses, so that users can set that status and others can see at a glance if they're on vacation.

WDYT?

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

Actually the one working on the Rocket.Chat App framework has already started creating this app.  @graywolf336

**Comment by graywolf336** [comment]
Here's the pull request to add it: https://github.com/RocketChat/Rocket.Chat.Apps-dev-environment/pull/7
