### ISSUE TITLE
[feature] Verification by SMS rather than email

### ISSUE THREAD

**Issue by saeedjalali1** [RocketChat/Rocket.Chat#6853]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version:4.8.1

Hi, how we can verify a user with SMS?  How to change verification from email to SMS?
There is a packages [meteor-accounts-sms](https://github.com/DispatchMe/meteor-accounts-sms) for doing this in meteor. My question is how to implement this feature in the rocket? Do you have any idea?
Thanks for you attention.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
