### ISSUE TITLE
Messages are sometimes appearing out of order or even as the wrong person

### ISSUE THREAD

**Issue by Nepoxx** [RocketChat/Rocket.Chat#6854]
Rocket.Chat Version: 0.55.1
Running Instances: 1

I've had this issue pop-up once in a while but I can't find an easy way to reproduce.

For instance, if I see the following conversation:

```
Bob: Hey you, how is it going?
me: not bad, how about yourself?
Bob: awesome, did you see last night's episode of ...
```

When I go and reply "yes", it'll appear like this, to both of us:

```
Bob: Hey you, how is it going?
me: not bad, how about yourself?
me: yes
Bob: awesome, did you see last night's episode of ...
```

This is not a major concern but is quite annoying since people might miss your question/message. 

I've also seen the following happen, which is arguably much worse:

```
Bob: Hey you, how is it going?
me: not bad, how about yourself?
Bob: awesome, did you see last night's episode of ...
Bob: yes // Bob did not write this, I did!
```

**Comment by TheReal1604** [comment]
@rodrigok can also confirm this, our environments are also affected. Just a feeling, maybe it is related to time sync on the clients. Then they got a little diff the messages are out of sync.

**Comment by Nepoxx** [comment]
I don't think it's an issue with client time sync. I've JUST had this happen:

```
Bob: 1 - message
Me: 2 - message
Me: 5 - message
Bob: 3 - message
Me: 4 - message
```
This is the order in which they appear, the numbers are the order in which they were typed/sent. message 5 appears before message 3 and 4. If it were a time sync issue, both 4 and 5 would be out of order, which isn't the case.

**Comment by Nepoxx** [comment]
I did not see the issue on 0.56, two weeks in, so I consider this closed. I will reopen if it reoccurs.

**Comment by Nepoxx** [comment]
I've had the issue come up again a few times, this issue persists.

**Comment by ggazzo** [comment]
hey @Nepoxx I quite sure we fixed it long time ago, any problem reopen (:

**Comment by Nepoxx** [comment]
I haven't encountered it in a long time indeed, thanks for cleaning the issues!
