### ISSUE TITLE
[BUG] Favicon not changed 

### ISSUE THREAD

**Issue by saeedjalali1** [RocketChat/Rocket.Chat#6855]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version:4.8.1

Hi, when I want change the favicon and upload new file with `*.ico` format give the below error:

![favicon1](https://cloud.githubusercontent.com/assets/15178117/25606115/0686d966-2f25-11e7-8dc5-e99f6ea4efd2.png)

How to fix it ?
Thanks.

**Comment by MartinSchoeler** [comment]
Duplcate of #6791
