### ISSUE TITLE
Required field in custom fileds not throw an error when field is empty

### ISSUE THREAD

**Issue by saeedjalalisj** [RocketChat/Rocket.Chat#6856]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version:4.8.1

Hi, first thanks for this awesome feature. I'm using custom fields in account menu(admin role). I add this code in custom field: 
```javascript
{
    "family":{
        "type":"text",
        "required":true,
        "minLength":2,
        "maxLength":25
    },
    "mobile":{
        "type":"text",
        "required":true,
        "minLength":2,
        "maxLength":12
    }
}
```
After add this `json` code and save it, this field appear  in the registration form. but have some problem. when all field is empty and click register new user button, give this errors:

![fieldsrequired](https://cloud.githubusercontent.com/assets/15178117/25606485/cf4cd822-2f26-11e7-89a6-1f8701f80a2f.png)

but I expect the mobile field give the same error. I don't understand this problem. Can help me to fix this problem. 
Thanks

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
