### ISSUE TITLE
Images don't display correctly in chat

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#686]
I set it up using `docket-compose up` and when an images is pasted into chat, it loads it from localhost, which errors because localhost refers to the VM. 

![screen shot 2015-09-04 at 12 58 58 pm](https://cloud.githubusercontent.com/assets/498744/9689603/2dcb2d2c-5305-11e5-93d0-982d02e1e875.png)

**Comment by graywolf336** [comment]
You need to define the `ROOT_URL`: `ROOT_URL=http://example.com`

**Comment by mhkeller** [comment]
Thanks!
