### ISSUE TITLE
How to change password using REST APi?

### ISSUE THREAD

**Issue by mlsuarezrojas** [RocketChat/Rocket.Chat#6860]
Hello,

I am trying to update a user using the api and update the other data (mail, username, etc.) but does not update the password

Rocket.Chat Version: 0.50.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: V4.7.1

**Comment by matthewshirley** [comment]
I've have tried on the latest release and was unable to replicate the issue. I updated the password by posting to 'api/v1/users.update' with the authentication headers and body:

`{
	"userId": "ar2tiM5Jyxb3Xuhpd", 
	"data": { 
		"name": "Matt",
		"password": "newpass" 
	}
}`

**Comment by mlsuarezrojas** [comment]
![image](https://cloud.githubusercontent.com/assets/28310870/25663032/34889306-2fdc-11e7-8e64-4ff37066afde.png)

**Comment by graywolf336** [comment]
Closing because of the comments above.

**Comment by xlbs-rm** [comment]
This only works if the user has the permission: edit-other-user-password @see: saveUser.js

Due there is no other Option to Change the Users Password (User : me), there is no Possibillity to change the own password via REST API.

This is still a Bug!
