### ISSUE TITLE
Auto Install Rocket.Chat Client on All Windows PCs

### ISSUE THREAD

**Issue by SammyMR** [RocketChat/Rocket.Chat#6863]
Rocket.Chat Version:  Version 2.6.1
Running Instances: MongoDB V3.2.9
DB Replicaset OpLog: 
Node Version: v0.10.26

Please add a setup (.msi) with group policy object (GPO) for Windows Domain Controller to auto install Rocket.Chat client on all Windows PCs in a company network. And it would be cool when the .msi file could be installed for all users (not only one user or admin on a pc)-

**Comment by geekgonecrazy** [comment]
Feature request for the desktop client.  Please open an issue if there isn't one already on that repo: https://github.com/rocketchat/rocket.chat.electron/issues

**Comment by LorneMalvoX** [comment]
Hello,
I'm a SysAdmin and I need to deploy the client app through a Windows Domain. I'm agree with SammyMR, we need a MSI package for a quick deployment in a company.

Thanks and greetings.
