### ISSUE TITLE
Rocket with AD

### ISSUE THREAD

**Issue by Chatrocket** [RocketChat/Rocket.Chat#6865]
hi,

we have a rocket chat with version 0.51.0 connected to a AD in windows server 2012. when i create an user in AD and put a password, rocket chat works fine, but if i reset again any different password in AD, user works always with de first password, doesnt update more.

We supouse that some part in the LDAP configuration is incorrect...

Any idea?

Thanks!

**Comment by ThecaTTony** [comment]
Hi, I have the same problem. After a password expires and is changed, rocket.chat does not resynchronize it.

**Comment by localguru** [comment]
Delete the AD\user and you will still able to login in RC :D
