### ISSUE TITLE
Login logo broken

### ISSUE THREAD

**Issue by codyaray** [RocketChat/Rocket.Chat#6870]
Rocket.Chat Version: 0.54.1
Running Instances: 9
DB Replicaset OpLog: Enabled
Node Version: 4.7.3

The logo on the login page is broken. Viewing the HTML, we see that it's sent as

```
<img src="//assets/logo.svg">
```

This is an incorrect URL. It should be /assets/logo.svg. I believe this issue was introduced with this commit as it introduces an extra slash in the URL: https://github.com/RocketChat/Rocket.Chat/commit/26d92a923c9d395d5e817a409caea57c84c7bdda

Here's the value of `Rocketchat.settings.get('Assets_logo')` (assuming it reads this from mongo):
```
rocketchat-uat:PRIMARY> db.rocketchat_settings.find({"_id":"Assets_logo"})
{ "_id" : "Assets_logo", "type" : "asset", "group" : "Assets", "fileConstraints" : { "type" : "image", "extensions" : [ "svg", "png", "jpg", "jpeg" ], "width" : null, "height" : null }, "i18nLabel" : "logo (svg, png, jpg)", "asset" : "logo", "public" : true, "packageValue" : { "defaultUrl" : "images/logo/logo.svg" }, "valueSource" : "meteorSettingsValue", "ts" : ISODate("2017-02-15T23:00:17.079Z"), "hidden" : false, "blocked" : false, "sorter" : 1, "i18nDescription" : "Assets_logo_Description", "createdAt" : ISODate("2016-04-20T01:20:22.938Z"), "value" : { "url" : "/assets/logo.svg", "defaultUrl" : "images/logo/logo.svg", "_updatedAt" : ISODate("2016-04-26T15:02:40.852Z") }, "meteorSettingsValue" : { "url" : "/assets/logo.svg", "defaultUrl" : "images/logo/logo.svg", "_updatedAt" : ISODate("2016-04-26T15:02:40.852Z") }, "_updatedAt" : ISODate("2017-05-03T20:45:46.866Z") }
```

We see the value is `/assets/logo.svg` which is then prefixed with an extra slash.

I quickly hacked around this so we can upgrade lest mobile clients update first and be incompatible with our current server version (0.52.0 but the client says it requires 0.54.0 now).

```
rocketchat-uat:PRIMARY> db.rocketchat_settings.update({"_id":"Assets_logo"},{$set: {"meteorSettingsValue.url":"assets/logo.svg","value.url":"assets/logo.svg"}})
```

**Comment by codyaray** [comment]
Incidentally, I didn't have this issue upgrading from 0.52 to 0.54.1 in our prod environment tonight. The Rocketchat.settings Assets_url didn't start with a "/" in this environment. Just `assets/logo.svg`. Not sure why one environment had the prefix but the other didn't.

**Comment by MartinSchoeler** [comment]
It seems that the issue was resolved, closing this now. Thanks!
