### ISSUE TITLE
Is it possible to add an easy way for saving chatlogs

### ISSUE THREAD

**Issue by SammyMR** [RocketChat/Rocket.Chat#6872]
Rocket.Chat Version: 2.6.1
Running Instances: MongoDB V3.2.9
DB Replicaset OpLog:
Node Version: v0.10.26

Lot of User want an easy option to save their chatlogs. It would be nice, if Rocket.Chat would have an option in the client to save the logs of channels or direct messages.

**Comment by marceloschmidt** [comment]
You can e-mail messages from a specific channel or download all your data if you go to your profile settings. If you need a download functionality on rooms, please request on the [forums](https://forums.rocket.chat) and let's discuss it.
