### ISSUE TITLE
How to connect local or external mongoDB instead of meteor's internal

### ISSUE THREAD

**Issue by ajaykhunti17** [RocketChat/Rocket.Chat#6877]
Rocket.Chat Version: 0.56.0-develop
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

I cloned the git code and started rocket chat in my local machine Windods 7 by following instructions as bellow. 

`git clone https://github.com/RocketChat/Rocket.Chat.git`
`cd Rocket.Chat`
`meteor npm start`

Now, I want during development my app to use my local mongoDB installation instead of meteors's internal. I tried a lot but did not get any help or clue. I know this is not an issue but I am writing here so anyone who knows can reply. Thanks.

**Comment by jszaszvari** [comment]
Set the MONGO_URL environment variable using this format

MONGO_URL=mongodb://[Address to Mongo]:27017/[MongoDB Database]

**Comment by ajaykhunti17** [comment]
Thanks for your quick reply. I tried but it was not successful. It seems I am missing somewhere. I attaching the screen of what I changed, I hope I am doing the right. I did changed in docker-compose.yml.

![config](https://cloud.githubusercontent.com/assets/28388976/25733659/235e81a0-3179-11e7-9538-d1ca0cec8fab.png)

**Comment by ajaykhunti17** [comment]
Can anyone help me here?

**Comment by geekgonecrazy** [comment]
Make sure when you update the MONGO_URL you also update MONGO_OPLOG_URL having one point to a different host is going to cause you issues.

---
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
