### ISSUE TITLE
Allow selecting which channels should be synced-in in SlackBridge

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#6878]
Rocket.Chat Version: 0.55.1
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: 4.5.0

I've set up a slack bridge with a partner organisation who uses slack. They've created the bot, added it to a specific channel and we've confirmed we have two way communications working. The problem is that whenever someone is added to our shared channel on the slack side they appear in our general channel. Is this because all users, including the slack bot are automatically added to the general channel in slack? Is there some way to restrict which channels will be synced from rocket.chat side?

I've restricted our outgoing sync to just one channel but there appears to be no way to do it for incoming messages and join messages.

**Comment by marceloschmidt** [comment]
That's right @tanc unfortunately at the moment we don't have the feature for selecting which channels are synced-in, only synced-out. I'll change the title to reflect this new feature request.

**Comment by ToferC** [comment]
Any progress on this issue or space for some help?

**Comment by marceloschmidt** [comment]
Moved this to the [forums](https://forums.rocket.chat/t/allow-selecting-which-channels-should-be-synced-in-in-slackbridge-issue-6878/2780) for discussion.
