### ISSUE TITLE
Remove dependence on Google Fonts (or make optional)

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#688]
Using Google Fonts is a privacy issue since it executes code in your app that also tracks users. Here's some more background on the subject: http://fontfeed.com/archives/google-webfonts-the-spy-inside/

And a project to self-host Google Fonts (license permitting of course): http://ranf.tl/2014/12/23/self-hosting-google-web-fonts/

**Comment by mhkeller** [comment]
Here's some more info on the issue: https://www.youtube.com/watch?v=q38HdGGWS78

**Comment by mhkeller** [comment]
And some more info on how 18F is doing it https://github.com/18F/18f.gsa.gov/pull/672

**Comment by geekgonecrazy** [comment]
I like 18F's solution.  Regardless of the privacy issue.. It might be a good idea to remove external dependencies as this could be in a locked down intranet.

**Comment by engelgabriel** [comment]
Agreed, Rocket.Chat should work without any dependency on external resources.
