### ISSUE TITLE
Unable to close images once clicked on username (no close button)

### ISSUE THREAD

**Issue by madguy02** [RocketChat/Rocket.Chat#6880]
Inorder to close the user info appearing vertically,there is no close button,have to reload
Rocket.Chat Version: 0.56.0-develop
Running Instances: 1
DB Replicaset OpLog:Enabled
Node Version:v4.8.2

**Comment by MartinSchoeler** [comment]
@madguy02 you can click this button to close the user info tab 
![selection_005](https://cloud.githubusercontent.com/assets/20868078/25705060/4c6f5906-30b2-11e7-9aba-d1ed7480d65a.png)

Or is this button not working?

**Comment by madguy02** [comment]
its working thanks
