### ISSUE TITLE
Accessing Through Proxy Loads Incorrect Domain Resources

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#6883]
Rocket.Chat Version:  0.55.0
Running Instances: 4
DB Replicaset OpLog: Yes
Node Version: 4.5
nginx Version: 1.12.0

Hi all,

We are running into an odd issue after updating from RC 0.38 to 0.55.0 and updating nginx from 1.8 to 1.12.0 and would like some help. The application is trying to incorrectly load websocket resources **(https://chat.example.us/sockjs/info?cb=)** from our internal server domain name when users are accessing it from a proxy outside in the DMZ. However, when users access the chat.zayo.com through the mobile app (iOS tested), there are no issues. If the user has the chat.example.com instance up and log in/authenticate into the chat.example.us, everything will start working for them on the chat.example.com instance; the websocket resource chat.example.us will load up. 

We have a setup with 2 proxies here:
1. First nginx proxy has domain name **chat.example.com** which sits in the DMZ open to the WWW. This proxies to chat.example.us and should only load resources showing "chat.example.com".
```
# HTTPS server
#

# Upstreams
upstream backend {
    server chat.example.us:443;
}

server {
    listen        80;
   # listen        [::]:80;
    server_name   chat.example.com www.chat.example.com;
    return        301 https://chat.example.com$request_uri;
}

server {
    listen        443 ssl;
    #listen        [::]:443 ssl http2;
    server_name   chat.example.com www.chat.example.com;

    error_log     /var/log/nginx/rocketchat.access.log debug;

    ssl                        on;
    ssl_certificate            /etc/nginx/ssl/example.com/server.crt;
    ssl_certificate_key        /etc/nginx/ssl/example.com/server.key;
    ssl_trusted_certificate    /etc/nginx/ssl/example.com/ca-certs.pem;
    ssl_dhparam                /etc/nginx/ssl/dhparam.pem;
    ssl_protocols              TLSv1.2;
    ssl_session_cache          shared:SSL:30m;
    ssl_session_timeout        4h;
    ssl_session_tickets        off;
    ssl_ciphers                ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
    ssl_prefer_server_ciphers  on;
    ssl_verify_client          off;
    ssl_stapling               off;
    ssl_stapling_verify        off;

    add_header Strict-Transport-Security "max-age=31536000";
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Xss-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy origin-when-cross-origin;

    location / {
        proxy_pass 		      https://backend;
        proxy_http_version            1.1;
        proxy_ssl_name                chat.example.us;
        proxy_ssl_certificate         /etc/nginx/ssl/chat.example.us/chat.example.us.crt;
        proxy_ssl_certificate_key     /etc/nginx/ssl/chat.example.us/chat.example.us.key;
        proxy_ssl_trusted_certificate /etc/nginx/ssl/chat.example.us/ca-bundle.trust.crt;
        proxy_ssl_verify              on;
        proxy_set_header              Upgrade $http_upgrade;
        proxy_set_header              Connection "upgrade";
        proxy_set_header              Host $http_host;
        proxy_set_header              X-Real-IP $remote_addr;
        proxy_set_header              X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header              X-Forwarded-Proto https;
        proxy_redirect                https://chat.example.us/ https://chat.example.com/;
    }
}
```

2. The second nginx reverse proxy server has domain name **chat.example.us** where the Rocket.Chat app resides. This server is behind our corporate firewall and is not available to WWW.
```
# Upstreams
upstream backend {
    server 127.0.0.1:3000 weight=1;
    server 127.0.0.1:3001 weight=1;
    server 127.0.0.1:3002 weight=1;
    server 127.0.0.1:3003 weight=1;
}

# HTTPS Server
server {
    listen 80;
    listen [::]:80;
    server_name chat.example.us www.chat.example.us;
    return 301 https://chat.example.us$request_uri;
}

server {
    listen 443 ssl;
    server_name chat.example.us www.chat.example.us;

    error_log /var/log/nginx/rocketchat.access.log;

    ssl on;
    ssl_certificate     /etc/nginx/ssl/chat.example.us.crt;
    ssl_certificate_key /etc/nginx/ssl/chat.example.us.key;
    #ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

    # add Strict-Transport-Security to prevent man in the middle attacks
    # add_header Strict-Transport-Security "max-age=31536000";

    location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto https;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}
```

When users try hitting chat.example.com, console shows them trying to access chat.example.us/sockjs resource
Firefox:
![console](https://cloud.githubusercontent.com/assets/8405384/25712749/15eda9e0-30b8-11e7-8bdf-400fb74cbcb0.png)

The Network tab shows:
Firefox:
![network](https://cloud.githubusercontent.com/assets/8405384/25713178/72a067b2-30b9-11e7-9095-907758bd5626.png)

My pm2 environment variables:
```
"env": {
			"MONGO_URL": "mongodb://localhost:27017,mongochat02:27017,mongochat03:27017/rocketchat?replicaSet=001-rs&readPreference=primaryPreferred&w=majority",
			"MONGO_OPLOG_URL": "mongodb://localhost:27017/local",
			"ROOT_URL": "https://chat.example.us",
			"DDP_DEFAULT_CONNECTION_URL": "https://chat.example.us",
			"PORT": "3000"
		}
```
- What is `DDP_DEFAULT_CONNECTION_URL`?

- Why would the chat.example.com instance try to load a resource that it should not be aware of? The chat.example.com proxy should hide all the details of chat.example.us and load resources accordingly. In addition, why would it work when accessing the iOS app?

- Would there happen to be an error in my nginx conf that I am missing?

- Are the sockjs resources being loaded incorrectly in the app? Or is there an environment variable I am missing?

This setup was working fine with RC 0.38 and nginx 1.8. Not sure what happened here and would really appreciate any help.

**Comment by jszaszvari** [comment]
Why have the two domains and not just use the 1 internally and externally?  (Curious for the reasoning) 

Just seems like it might un-necessarily complicate things.

I cant see anything initially wrong with the config but I'll have another look tomorrow when i'm not so tired. 

Probally wont help, but just in case here is our working nginx config

`upstream bchat_multinode {
	least_conn;
	server 10.0.55.205:3011;
    server 10.0.55.205:3012;
	server 10.0.55.205:3013;
	server 10.0.55.205:3014;
	server 10.0.52.207:3011;
    server 10.0.52.207:3012;
	server 10.0.52.207:3013;
	server 10.0.52.207:3014;
	server 192.168.39.19:3011;
    server 192.168.39.19:3012;
	server 192.168.39.19:3013;
	server 192.168.39.19:3014;
	server 192.168.39.94:3011;
    server 192.168.39.94:3012;
	server 192.168.39.94:3013;
	server 192.168.39.94:3014;
	server 172.16.22.12:3011;
	server 172.16.22.12:3012;
	server 172.16.22.12:3013;
	server 172.16.22.12:3014;
}
server {

	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	server_name bchat.ourdomain.net.au;
	return 301 https://bchat.ourdomain.net.au$request_uri;
}

# HTTPS Server
server {

	listen 443 default_server;
	server_name bchat.ourdomain.net.au;

	error_log /var/log/nginx/bchat.ourdomain.net.au.error.log;
	access_log /var/log/nginx/bchat.ourdomain.net.au.access.log;
	ssl on;
	ssl_certificate /etc/nginx/certificate.crt;
	ssl_certificate_key /etc/nginx/certificate.key;
	ssl_dhparam /etc/nginx/dhparam-4096.pem;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;
	ssl_session_cache shared:SSL:20m;
	ssl_session_timeout 180m;


	location / {

		proxy_pass http://bbchat_multinode/;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $http_host;
        proxy_buffering off;
		proxy_http_version 1.1;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forward-Proto http;
		proxy_set_header X-Nginx-Proxy true;
		proxy_redirect off;
	}
}
`

**Comment by richardwlu** [comment]
@jszaszvari Thank you for the quick response. The reasoning is we initially just had one internal instance and then brought on the external proxy; we kept the internal domain name up and running since it was already good and its nice to have a backup in case the external proxy fails.

I am assuming that for all your app instances there is no nginx server running on them? You only have one external instance?

**Comment by jszaszvari** [comment]
@richardwlu  There is no NGINX running on the upstream servers, They are directly the app servers (That have firewall config to only allow the NGINX proxy to communicate with them so nobody browses to one of the addresses ie 192.168.39.19:3011 directly and hits a chat instance) 

We have a NGINX proxy in AWS Which is for external access, the 10.0.x.x addresses are our AWS networks. 

There is also one inside our main office which are the 192.168 addresses 
 
They are all listed there as we utilise the Amazon Direct Connect service, so our amazon VPC is essentially on our local network as well. 

My current thinking is maybe you could just try and re-write the domain to catch any requests that are coming back with the wrong domain.. It may work but I'm not 100%

Something like

`
rewrite ^ $scheme://bchat.mydomain.com$request_uri permanent;
`

I'm not sure Rocket.Chat handles multiple domains too well as a lot of stuff seems to rely pretty heavily on the Rocket.Chat ROOT_URL variable.

Will think about this tomorrow, you sparked my interest :)

**Comment by richardwlu** [comment]
@jszaszvari Gotcha. Until tomorrow :)

**Comment by richardwlu** [comment]
@geekgonecrazy Hey Aaron, was wondering if you have any thoughts on this?

**Comment by geekgonecrazy** [comment]
> What is DDP_DEFAULT_CONNECTION_URL?

This is the url that the client will try to use to connect to the servers websocket.

So multiple domains is for sure going to be something that you are going to struggle with for Rocket.Chat.  

Which ever site you have ROOT_URL pointing to is whats going to be used for links and a lot of other functionality.  

As to why the ios app works.  I'm assuming you're using our new native app.  If so then this is because it actually connects directly to https://chat.example.us/websocket Its not written in meteor it isn't doing the typical meteor dance that the web client has to do.

**Comment by richardwlu** [comment]
@geekgonecrazy What would happen if I changed DDP_DEFAULT_CONNECTION_URL to the chat.example.com external instance? Would it then rewrite and load the websocket sources properly?

**Comment by geekgonecrazy** [comment]
if you have dns internal... i'd probably add a record for the external site: chat.example.com pointing to the internal nginx.  Then in your internal nginx add chat.example.com so it'll handle traffic for it.

Then set your DDP_DEFAULT_CONNECTION_URL to the external address.

This way both will connect to the same DDP address.  Internal will hit the internal proxy.  External will go through the external proxy and the internal... to then get the server :) 

Would something like that work?  

My brain hurts now :grin:

**Comment by richardwlu** [comment]
@geekgonecrazy Thank you for your suggestions.  I ended up changing DDP_DEFAULT_CONNECTION_URL to the external address and having all the users go there. The correct socket resource is now loading. Thanks!

**Comment by geekgonecrazy** [comment]
Perfect!  Glad you were able to get it working :smile:
