### ISSUE TITLE
Real Name for chat when pinging 

### ISSUE THREAD

**Issue by failattu** [RocketChat/Rocket.Chat#6887]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog:false
Node Version: v4.8.0

We are using real name as usernames and would like to see that real name in chat instead of the username. When pinging someone

**Comment by madguy02** [comment]
Either you will need to tweak on the client side,or you can rather set your username to your own name,because by default "rocket.chat" creates usernames as "foo.bar" you can change it while registering itself

**Comment by madguy02** [comment]
![screenshot from 2017-05-05 15-11-27](https://cloud.githubusercontent.com/assets/8217234/25740702/3d67b9c8-31a5-11e7-8837-b1fdf62fe5a4.png)

**Comment by madguy02** [comment]
register it accordingly

**Comment by failattu** [comment]
That won't do as we use LDAP and SSO for our usernames and we get users in form like 123456 or z21r41 etc.

**Comment by madguy02** [comment]
https://rocket.chat/docs/administrator-guides/authentication/ldap/ will this help?

**Comment by SeanPackham** [comment]
We don't have any plans to support @'ing real names.
