### ISSUE TITLE
Force User to Change Password Next Load/Login

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#689]
As I'm working on a plan to migrate my Slack instance to Rocket.Chat, I need a method for forcing users to reset their passwords next time they login or load the page (I will be creating users inside Rocket.Chat if they don't exist) since I will be giving them a temporary password.

Hopefully that makes sense...

**Comment by rodrigok** [comment]
Invitations via email solves your problem?

**Comment by graywolf336** [comment]
Kind of, but in my use case no. I'm going to be importing all my data from
slack and will also be creating users in the import so I'd like to give
them a random password or send them a link to reset/set their password. So,
it's not exactly an invite but kind of is. If that makes sense..

**Comment by rodrigok** [comment]
Ok, one flag in user to force password change in logging solve the problem?

**Comment by graywolf336** [comment]
Yeah that sounds good. Could even add a spot in the admin panel when managing users to set that flag, that's my thought for other uses.

**Comment by rodrigok** [comment]
Looks good, i can't do this now, but i can take a look tomorrow at night or monday.

**Comment by graywolf336** [comment]
:+1: sounds good to me

**Comment by geekgonecrazy** [comment]
Could almost tap into the password reset.  Set a password then trigger password reset for import purposes.  That'd let you send them a link they could click and set their password. :)

**Comment by engelgabriel** [comment]
Done
