### ISSUE TITLE
I would like to know about custom script to make interactive background with youtube api

### ISSUE THREAD

**Issue by KensanGG** [RocketChat/Rocket.Chat#6891]
Rocket.Chat Version: 0.56.0-rc.0
Running Instances: 1
DB Replicaset OpLog:disable
Node Version:4.8.0 - x64

This is impossible coz of copy rights?

<Content(HTML)>
<div id="background-front"> </div>
<div id="background"></div>

<CSS>
#background,
#background-front {
    position: fixed;
    left: 0; 
    top: 0;
    width: auto; 
    min-width: 100%; 
    height: auto;
    min-height: 100%;
    z-index: -100;
}

<Custom Script for logged in user(JS)>
var tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
 

var ytArea = 'background';

var ytID = '26xxxxxxxxxg';

function resizeMovie () {
    var $w = $(window),
          bw = 1200, 
          bh = (bw/16) * 9, 
          w = $w.width(), 
          h = $w.height(),
          mw = w, 
          mh =  Math.round(bh * (mw/bw)); 
     
    if ( mh < h ) { 
        mh = h; 
        mw = Math.round(bw * (mh/bh)); 
    }
     
    $('#background').css({
        width: mw,
        height: mh,
        marginTop: (h - mh)/2,
        marginLeft: (w - mw)/2
    });
         
}
 
resizeMovie();
 
$(window).resize(resizeMovie);

function onYouTubeIframeAPIReady() {
    ytPlayer = new YT.Player(ytArea, {
        videoId: ytID,
        playerVars: {
            rel: 0,
            controls: 0,
            showinfo: 0,
            wmode: 'transparent'
        },
        events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
        }
    });
}
 

function onPlayerReady(e) {
    ytPlayer.playVideo();
    ytPlayer.unmute();
}
 

function onPlayerStateChange(e) {
    var ytStatus = e.target.getPlayerState();
    if (ytStatus == YT.PlayerState.ENDED) {
        ytPlayer.playVideo();
        ytPlayer.unmute();
    }
}

**Comment by graywolf336** [comment]
I don't think this is possible at the moment, unless maybe you do a custom script, *not an integration*..

`Admin -> Layout -> Custom Script for Logged Out Users`

But I don't know how it would work and you would have to do some work to get it working.
