### ISSUE TITLE
Firefox clicking the editable fields is not reliable

### ISSUE THREAD

**Issue by failattu** [RocketChat/Rocket.Chat#6893]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog:false
Node Version: v4.8.0

When using Firefox and trying to change the different fields like topic etc. you have to click around a bit to find the correct spot to click otherwise it doesn't allow you to change it. This is annoying and would be nice to be fixed.

**Comment by madguy02** [comment]
@rodrigok

**Comment by madguy02** [comment]
@rodrigok

**Comment by MartinSchoeler** [comment]
@failattu actually the pencil button its not working on firefox, so when you click it, nothing happens.
