### ISSUE TITLE
Link parsing, character encoding, and variable accessing errors when parsing complex room topics

### ISSUE THREAD

**Issue by JakeSteam** [RocketChat/Rocket.Chat#6895]
Rocket.Chat Version: 0.54.2

Setting the room topic to `_[I'm $&](http://google.com)_` should produce underlined text "I'm $&" that links to Google.

Instead, it results in this mess in chat: `__blank">I&#39;m __room_topic__amp;_`, and a slightly different one in the sidebar: https://i.imgur.com/dMa4O2Z.png

1. Underlining breaks the link parser, getting confused with the `_blank` target. Bad parameter escaping?
2. The apostrophe character is incorrectly encoded (applies to other characters too).
3. The $& sequence becomes `__room_topic__amp;`, indicating I'm getting some kind of access to internal variables, which I shouldn't be.

There's almostly certainly a lot more issues here.

**Comment by iangilfillan** [comment]
Confirming this is still an issue in 0.62.2

**Comment by iTob191** [comment]
Seems like this applies not only to room titles but to links in general. For example posting `[a'b](https://hostname.tld)` into the chat results in a link named `a&#39;b`. Looks like the link text is encoded twice.

**Comment by gabriellsh** [comment]
Still happens 2.5.0-develop
