### ISSUE TITLE
Direct messages panel shows all users as offline

### ISSUE THREAD

**Issue by vrooze** [RocketChat/Rocket.Chat#6897]
Rocket.Chat Version: 0.56.0-rc.0
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version:  v4.8.2

Since updating to this version all of the users listed on the left side/previous `Direect Messages` are all showing as offline.

Pressing ctrl+k or clicking search shows the correct status.

![image](https://cloud.githubusercontent.com/assets/16898416/25750887/139c3122-31ab-11e7-86b1-90da1b360ca9.png)

vs (from search)

![image](https://cloud.githubusercontent.com/assets/16898416/25750960/5f23a0b2-31ab-11e7-933b-44f57a8e2540.png)

**Comment by jszaszvari** [comment]
Fixed in rc1 released probably as you posted this

**Comment by vrooze** [comment]
how typical! :)
