### ISSUE TITLE
Not surfacing unread/mention count to desktop client

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#6900]
Rocket.Chat Version: 0.56.0-rc.1 - Demo Server

I have 5 mentions and several channels unread but desktop only gets this:

![image](https://cloud.githubusercontent.com/assets/51996/25757815/acb3e9e6-3191-11e7-9cbc-57928ef870dd.png)

Its not an issue with the desktop client because other servers on 0.55.1 still show properly for example:
![image](https://cloud.githubusercontent.com/assets/51996/25757831/c1cc7618-3191-11e7-97d1-ec813bbb02ab.png)

**Comment by rodrigok** [comment]
Bug introduced by PR https://github.com/RocketChat/Rocket.Chat/pull/6798

**Comment by engelgabriel** [comment]
@sampaiodiego can you take a look at this?

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/6923
