### ISSUE TITLE
Livechat Integration: Sistema não reconhece o JSON exportado para webhook

### ISSUE THREAD

**Issue by diegopn833** [RocketChat/Rocket.Chat#6901]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: 
Node Version:v4.7.3

Olá,

Na empresa onde trabalho pediram para integrar o livechat com o sistema do RD Station. O que eu preciso fazer basicamente é pegar o nome e e-mail passados pelos usuários  e enviar para o RD. Para isso eu criei um método dentro de nosso site para: receber um JSON por POST e enviar os valores recebidos para o sistema do RD (via API deles).

Eu configurei o método para receber um JSON de acordo com o que li na [documentação](https://rocket.chat/docs/administrator-guides/livechat/) do rocketchat. Minha função ficou assim:
**OBS**: Estou usando o Laravel 5

```
public function setLead() {
        $data = $this->request->all();
        
        $data_json = json_encode([
            "email"           => $data["visitor"]["email"],
            "name"            => $data["visitor"]["name"],
            "identificador"   => "Qualiex - Chat",
            "token_rdstation" => "***********"
        ]);
        
        $ch = curl_init("http://www.rdstation.com.br/api/1.2/conversions");
        
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json', 'Content-Length: ' . strlen($data_json)]);
        
        curl_exec($ch);
        curl_close($ch);
    }
```

Eu fiz um pequeno código para ver se esta função estava funcionando, e verifiquei que sim, estava. O código de teste foi esse:

```
$post = json_encode([
    "type"    => "LivechatOfflineMessage",
    "sentAt"  => "2016-06-01T19:55:53.867Z",
    "visitor" => [
        "name"  => "Diego Pereira do Nascimento - Teste",
        "email" => "diego@forlogic.net"
    ],
    "message" => "mensagem de teste" 
]);

echo "Enviando dados!\n\n";

$ch = curl_init("http://www.qualiex.com.br/rocket-chat");

curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json', 'Content-Length: ' . strlen($post)]);

$response = curl_exec($ch);

curl_close($ch);
```

Sempre que utilizo este pequeno código, eu consigo inserir os dados normalmente no sistema do RD, mas sempre que faço os testes dos rocket chat, uma mensagem aparece dizendo que o retorno foi diferente de 200. Eu não se a estrutura do JSON enviado pelo rocketchat está diferente da que estou esperando na função, ou outra coisa.

Desde já agradeço quem possa me ajudar.

**Comment by sampaiodiego** [comment]
a rota que você criou no laravel precisa responder com status code 200, essa é a única verificação que o Rocket.Chat faz.

você comparou se os dados recebidos pela rota que você criou no laravel são iguais aos dados enviados pelo rocket.chat? uma maneira simples de testar isso é utilizando o serviço http://requestb.in/ pois ele mostra os dados RAW enviados.

**Comment by sampaiodiego** [comment]
@diegopn833 conseguiu resolver esta demanda?

**Comment by diegopn833** [comment]
Olá @sampaiodiego sim consegui resolver o problema, o link que você me passou me ajudou muito a resolver o problema.

Mas logo que eu resolvi o problema decidiram utilizar o Freshdesk por já estar sendo usado em outros setores da empresa.

Mas obrigado por tudo!

**Comment by sampaiodiego** [comment]
obrigado pelo feedback @diegopn833 .. esperamos que vocês tentem rocket.chat novamente no futuro. :smiley:
