### ISSUE TITLE
IRC gateway success stories?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6902]
Rocket.Chat Version: 0.55.1
Running Instances: 
DB Replicaset OpLog:
Node Version:

Has anyone actually got this up and running properly? I tried enabling this feature today to sync with the public IRC network I'm running at `irc.k0nsl.org` but I did not have any success with it; nothing appears to happen when enabling the feature. I tried restarting the Rocket.Chat instance as well but it didn't make any difference.

So it would be interesting to hear of any success stories with regard to this feature, since it is one that I would love to have enabled on my server. If you deployed Rocket.Chat via Docker (on Debian*), that's a plus in my book, since it might be easier to troubleshoot -- because that's the way I deployed it.

**Comment by theodotos** [comment]
I have also ignored the 'IRC Support is a work in progress.' warning and went straight ahead to enable the IRC operation. I created a #meetings channel in our internal IRC server and a public #meetings channel in Rocket, but there seems to be no exchange betwwen the two. I used these settings:

* Enabled: **true**.
* Host: irc.**my.org**
* Port: **6667**

I can successfully connect to the IRC server using a standard IRC client (eg, Pidgin)

**Comment by valessiobrito** [comment]
Mine is almost perfect I can't receive feedback from IRC messages on the Rocket.Chat channel;

log msg:

> [34mI20170609-21:41:45.501(0) 
> [33m[irc] sendMessage ->  userName: valessiobrito 
> [34mI20170609-21:41:45.502(0) 
> [33m[irc] ircSendMessageCache.set ->  key: valessiobrito,#channel,okkk ts: 1497044505497 
> [34mI20170609-21:41:45.502(0) 
> [33m[irc] sendRawMessage ->  PRIVMSG #channel : okkk 
> [34mI20170609-21:41:54.609(0) [irc.my.net:6667]: :valessio`test!uid150324@irc.my.net PRIVMSG #channel :teste 
> [34mI20170609-21:41:54.610(0) [irc.my.net:6667]:  
> [34mI20170609-21:41:57.393(0) [irc.my.net:6667]: :valessio`test!uid150324@irc.my.net PRIVMSG #channel :valessiobrito: teste 
> [34mI20170609-21:41:57.393(0) [irc.my.net:6667]:  
> [34mI20170609-21:43:50.490(0) [irc.my.net:6667]: :valessio`test!uid150324@irc.my.net NICK :valessio 
> [34mI20170609-21:43:50.490(0) [irc.my.net:6667]:  
> [34mI20170609-21:44:04.721(0) [irc.my.net:6667]: :valessio!uid150324@irc.my.net PRIVMSG #channel : hiiiiiii 
> [34mI20170609-21:44:04.722(0) [irc.my.net:6667]:

**Comment by theodotos** [comment]
So what is th workflow? Something like this?

* Setup the experimental Rocket to IRC experimental intergration
* Create a #channel in IRC
* Create a #channel in Rocket
* Exchange messages between the two systems

Is it that simple?

**Comment by valessiobrito** [comment]
Yes, but for me it's not working from IRC -> RC

I'm trying to debug, I think RC does not have the necessary authorization or it can not map the message and deliver to the channel correctly.

**Comment by rodrigok** [comment]
Should be fixed by #8656 let me know if it was not.
