### ISSUE TITLE
#updrade External link

### ISSUE THREAD

**Issue by ckiltolier** [RocketChat/Rocket.Chat#6906]
Hi !

Here is our website for the chat : https://chat.lescommuns.org (the chat for commons)

In the informations of the channel I would like to have access to external links (for the website, loomio, wekan, and so on...). To make the chat, a better link tool for projects.

What do you think about it ?

**Comment by ckiltolier** [comment]
Anyone ?

**Comment by marceloschmidt** [comment]
You could add markdown links to the channel description and topic. Let us know if this is not what you intended.
