### ISSUE TITLE
Sort channels by number of users or alphabetical

### ISSUE THREAD

**Issue by AdrianoCahete** [RocketChat/Rocket.Chat#691]
Now i don't know which sorting is used (creation date, maybe?), but It would be good to user if he could sort by name or number of users.

![list_channels_sort](https://cloud.githubusercontent.com/assets/37474/9693367/3ed69266-5326-11e5-8f48-f6d24998f047.PNG)

**Comment by geekgonecrazy** [comment]
Maybe let them sort different ways?  

I almost think channels should be shown in a pop up or in the center so we have real-estate to display better.   That list is hard to scroll through.

**Comment by AdrianoCahete** [comment]
I like the way they are displayed now, i can follow the current channel and search for a new one, but this is relative. Can user choose UI behavior (popup or fixed panel), maybe?

**Comment by geekgonecrazy** [comment]
What if I want to find a channel that is archived?  We're limited on how we can display them there.

**Comment by AdrianoCahete** [comment]
Show active channels first or archived with different color/background/opacity.

**Comment by geekgonecrazy** [comment]
From a UX perspective, how do they really know this?  Needs to be separated.
Something like: 

Archived:
* channel1
* channel2

Still this feels very clunk to have to scroll through this big list. Not user friendly

**Comment by AdrianoCahete** [comment]
> Still this feels very clunky to have to scroll through this big list. Not user friendly
I agree.

I'll try to see a solution/mockup later.
