### ISSUE TITLE
Can't load private registration URL

### ISSUE THREAD

**Issue by dev0tion** [RocketChat/Rocket.Chat#6918]
Rocket.Chat Version:  0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Hey guys,

I'm trying to run a private rocket chat self hosted server, but the browser won't load the secret URL to the registration form. It just keeps on loading.
I'm running rocket chat as a snap on Ubuntu 16.04 and behind a nginx reverse proxy, configured like this:
https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy
I'm using a let's encrypt generated certification.

Has anyone come across this issue?

Thanks in advance.

**Comment by Gerporgl** [comment]
I am also not able to use the secret URL anymore. I've used it before in the previous version (0.54 I think), but now the page keeps loading. I'm out of ideas. I'm using Caddy web server with letsencrypt and configured as recommended. I've setup at least 3 rocket chat install they all don't work. 2 of them uses Ubuntu 16.04 and another Mint 17.

**Comment by joshuahaber** [comment]
I am seeing the same scenario.  Any ideas what's causing this?

**Comment by vialcollet** [comment]
Yeap... same with me

**Comment by rebeld** [comment]
Using docker/docker-compose on Ubuntu 16.0.4, behind nginx as reverse proxy, and RC release 0.56.0 (just updated from 0.41.0) and the secret login URL doesn't work for us either.

I don't see anything suspicious in the RC or nginx logs.

It worked prior to the update, this is annoying as it's our primary mechanism for onboarding new users.

**Comment by geekgonecrazy** [comment]
Confirmed on demo server.  Seems to be a regression

**Comment by NTShop** [comment]
Same for me using the latest snap for Ubuntu and Caddy, totally borkened - can't access the secret URL.

**Comment by localguru** [comment]
Same here, 0.56.0 with nginx ssl proxy. Browser is loading ....

**Comment by jbguerraz** [comment]
relates to #6755

**Comment by jbguerraz** [comment]
@ggazzo maybe an idea ? :)

**Comment by geekgonecrazy** [comment]
@ggazzo  @MartinSchoeler maybe has something to do with the coffeescript to js conversion?

**Comment by joshuahaber** [comment]
Any updates?

**Comment by joelchu** [comment]
I have a docker setup V.0.56.0 

Same problem with the private registration url won't open.

Here is the console 

`
Exception in template helper: TypeError: Cannot read property 'depend' of undefined
    at f.TemplateInstance.subscriptionsReady (https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:135:5153)
    at Object.ready (https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:269:9671)
    at https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:134:31303
    at https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:134:17158
    at https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:134:31936
    at Function.e._withTemplateInstanceFunc (https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:135:5645)
    at https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:134:31843
    at Object.p.call (https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:203:1921)
    at https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:268:6515
    at f.View.<anonymous> (https://chat.newb.im/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:134:27950)
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection public-settings => clearing cache
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection permissions => clearing cache
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection public-settings => 197 records loaded from server
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection public-settings => recomputing 1 queries
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection public-settings => saving cache
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection public-settings => saving cache (done)
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection permissions => 70 records loaded from server
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection permissions => recomputing 0 queries
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection permissions => saving cache
e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js:243 CachedCollection permissions => saving cache (done)
`

**Comment by jszaszvari** [comment]
Fix is in 0.57
