### ISSUE TITLE
Ability to see complete user information

### ISSUE THREAD

**Issue by AdrianoCahete** [RocketChat/Rocket.Chat#692]
Yes, like IRC. Something like /whois (command line and interface), with Real Name, emails (if he make public or for server admins) GeoLocalization (country is good), all public channels he's part, IP (for server admins) and private channels (for admins).

Quick commands from that window it be useful too (ban, kick, edit info, make/remove admin).

Awesome if admins were notified when someone given them whois.
##

**Comment by AdrianoCahete** [comment]
> Choose flag/country in account settings to be displayed before/after the name in chat.

Mentioned in #708

**Comment by rodrigok** [comment]
Admins can see this data in the right panel that opens when you click at some user's name in the chat messages.

We need to add the list of rooms user is part

We are working in commands for kick users too

**Comment by geekgonecrazy** [comment]
#626 would need to factor in

**Comment by marceloschmidt** [comment]
OK, so this needs 
- [ ] a settings entry to allow/disallow public sharing of this information;
- [ ] a user settings group (maybe in profile) to show/hide personal information
- [ ] geolocation settings (ask user for geolocation or use geoip) #708 
- [ ] show user channels on sidebar user info
- [ ] start saving user ips
- [ ] add action buttons to sidebar user info
- [ ] slash commands for kicking, banning, whois, set admin

**Comment by josephfusco** [comment]
looks good!

**Comment by Valiantiam** [comment]
Hiding emails is a huge deal regarding livechat with agents. It is crucial guests cannot see our agents direct email addresses they are signed up with on the chat.

**Comment by mrmayfield** [comment]
Can we still not hide emails?

**Comment by SeanPackham** [comment]
Yes you can still choose to show email. Closing issue as it has already been implemented.

**Comment by mutante** [comment]
Could you point to where "display list of all public/private channels" has been implemented?

**Comment by geekgonecrazy** [comment]
full list of private channels no.  Because they are private.  But public channels are found:
![image](https://user-images.githubusercontent.com/51996/38445226-3e6ab7be-39b8-11e8-8fa3-4da576a49be7.png)
