### ISSUE TITLE
Cannot send files

### ISSUE THREAD

**Issue by banasiakadam60** [RocketChat/Rocket.Chat#6922]
I cannot send some files (eg. `.blender` files) with Rocket.Chat. This bug was found in version `0.55.1`, but is still present in the newest version `0.56.0-rc.1`. There is no error message, I can't find anything interesting in logs, just like nothing happens. Checked on the web client and Ubuntu app (v 2.5.0).
We accept all media types (see screen below), but when I change file extension from `.blend`, to eg. `.jpg`, everything works fine and file can be send.

![image](https://cloud.githubusercontent.com/assets/11528913/25855017/402bcff2-34d2-11e7-9f81-7680e6ef67c2.png)

**Comment by millerlucas** [comment]
I think it's the same bug as the one i've reported here #6917.
