### ISSUE TITLE
Feature Request: Support SASL for IRC

### ISSUE THREAD

**Issue by jamesbeedy** [RocketChat/Rocket.Chat#6924]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: 	Enabled
Node Version: v4.8.1

Feature request for sasl support for irc!

**Comment by madguy02** [comment]
@rodrigok

**Comment by marceloschmidt** [comment]
Moved it to the [forums](https://forums.rocket.chat/t/support-sasl-for-irc/2813) for discussion.
