### ISSUE TITLE
Integration messages on sidebar

### ISSUE THREAD

**Issue by albenstein** [RocketChat/Rocket.Chat#6925]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

Is there any plan for integration messages shown on right sidebar not in channel body?
If there is a page on channel (like pinned messages, starred messages etc.) and integration bot messages (like gitlab commits, jenkins success messages etc.) list and be shown on there, it will be an effective feature.
And it also be useful if admins can select on integration page to show messages on channel or list on this menu.
And last thing; if messages show on channel notifications will send to room users, if list on menu notifications will not send.

**Comment by geekgonecrazy** [comment]
I'm not sure I understand the ask here.  I get that you want to show messages somewhere other then in the channel.  Are you talking about in the right panel?

**Comment by albenstein** [comment]
@geekgonecrazy Yes I'm talking about what you said.

**Comment by albenstein** [comment]
@geekgonecrazy If channel users want to see integration messages, they will open on right panel (for example they will open Integration Messages menu with its icon). By this mean there is no crowd about this type messages on channel body.

**Comment by timkinnane** [comment]
I think this would be best solved by just having specific rooms for integration messages, where there's no other discussion - if the objective is just to see a stream of messages / notifications etc from a specific integration. That's the way it's commonly handled, e.g. to have a room for GitHub issue updates etc.
Having a new sidebar tab for particular message streams sounds like an over-complication for little benefit over the existing widely accepted format of using channels. I vote for keep-it-simple, what does @RocketChat/core think?

**Comment by sampaiodiego** [comment]
I agree @timkinnane ..

**Comment by graywolf336** [comment]
I agree and will close this. With the upcoming Rocket.Chat Apps and the ability it will have, which is contextual bar additions, this will be possible for someone who wants to code it. That's in the future and not now though. :)
