### ISSUE TITLE
Pre-set a channel or user to be a favority for all users?

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#6929]
Rocket.Chat Version: 55.1
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: v4.8.1

Is there any way for an admin to set one or more channels and users so that they will appear as favorites for all users of the instance?

**Comment by nORKy54** [comment]
I think you must use 'pinned messages'

**Comment by marceloschmidt** [comment]
Admins may already choose which channels are default, meaning users will join those channels when registered on the server. Favorites are personal choice, including how they are displayed.

**Comment by marceloschmidt** [comment]
We'll leave this open if someone wants to give it a try.

**Comment by luixxiul** [comment]
fixed on 3.2.0
