### ISSUE TITLE
Custom OAuth force WP username

### ISSUE THREAD

**Issue by Bluer-RC** [RocketChat/Rocket.Chat#6944]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: no
Node Version: v4.8.3

I am using [WordPress Custom OAuth](https://github.com/RocketChat/Rocket.Chat/issues/2815#issuecomment-300560656) and i would like to automatically force both RC username and name to WP username instead of it asking for a new username when authenticating for the first time. Currently it will suggest partial WP user email address as the username, so it is already fetching data that could be changed to WP username as a hidden process?

This is also crucial to know who your users are.

**Comment by Bluer-RC** [comment]
Just my thoughts on this,.. first need to find out what determines the new username suggestion (RC or WP plugin) and edit it accordingly. Can also pay a 30$ reward for whoever solves it (it kind of prevents my site from going public.)

**Comment by geekgonecrazy** [comment]
So it gets the suggestion from oauth based on specified username field.  I'm not sure what the field is for WordPress.  But once you find that you should be able to specify in your oauth config

**Comment by Bluer-RC** [comment]
@geekgonecrazy do you mean i need to manually edit WP plugin files?

**Comment by geekgonecrazy** [comment]
@Bluer-RC not at all.  I'm referring to the username field on the custom oauth:

![image](https://cloud.githubusercontent.com/assets/51996/26069283/f2263ea8-3965-11e7-8c3f-3f7cb03f449e.png)

I want to say its something like... user_login

**Comment by Bluer-RC** [comment]
@geekgonecrazy so i have to use ftp program, find some file and edit the field? Or put something on the actual custom oauth page username field?

**Comment by sampaiodiego** [comment]
there is no way you can configure Rocket.Chat to bypass the username screen.

**Comment by geekgonecrazy** [comment]
@Bluer-RC no you would open Rocket.Chat goto the custom oauth screen and set the "Username field" to user_login

All this is going to do is change it suggest the username from wordpress.  It will not force the username.

**Comment by Bluer-RC** [comment]
@geekgonecrazy it needs to be forced (in otherwords edited in RC files so that it will fetch the WP username and is hidden) otherwise user can just change the suggested username. I tried user_login but it still suggests WP email address (without the **@gmail.com** part)

**Comment by geekgonecrazy** [comment]
As for forcing lets fork that off into a separate issue.  As we said this does not exist for any of the oauth providers.  This would be functionality that would have to be created in rocket.chat.  Lets talk about that here: #6977

@Bluer-RC if you use the the regular wordpress oauth does it show the proper username?  If so then we can go from there to try and figure out why the username isn't carrying over

**Comment by Bluer-RC** [comment]
@geekgonecrazy using **user_login**  in custom oauth "Username field" worked after creating a fresh WP user and it automatically forces it without suggesting anything.

**Comment by geekgonecrazy** [comment]
Great!  Sounds like its resolved then :+1:
