### ISSUE TITLE
Quoting nothing results in a tiny grey area

### ISSUE THREAD

**Issue by JakeSteam** [RocketChat/Rocket.Chat#6948]
Rocket.Chat Version: 0.54.2

Very minor bug, but if nothing is quoted (e.g. the message is just `>`, or `>` followed by spaces), then a tiny grey area appears on screen. Expected behaviour is a full height grey area, or refusing to quote.

Note that the first line also seems to be shorter vertically than the others, I am uncertain why. 

![Quote bug](https://i.imgur.com/RhcrqJe.png)

**Comment by rssilva** [comment]
Hi @JakeSteam. Sorry for the late reply. Can you still reproduce it? I couldn't using the current version. Probably it was solved while fixing other issue.

**Comment by rssilva** [comment]
Duh me! I just did. My bad for the unnecessary mention 😬
