### ISSUE TITLE
RocketChat:version compile version plugin error from meteor-deque

### ISSUE THREAD

**Issue by janat08** [RocketChat/Rocket.Chat#6951]
Rocket.Chat Version: latest as of date i imagine (devel): can't startup
Running Instances: 0
DB Replicaset OpLog: 0
Node Version: 5.6

=> Errors prevented startup:
   
   While loading plugin `compileVersion` from package `rocketchat:version`:
   error: Can't load npm module 'meteor-deque' from packages/meteor.js. Check
   your Npm.depends().

**Comment by sampaiodiego** [comment]
how are you trying to run? `docker`, `snap`, vanilla, etc.

**Comment by janat08** [comment]
clone git.

**Comment by sampaiodiego** [comment]
alright, so after cloning did you use `meteor npm start`?

**Comment by janat08** [comment]
Yes. I would either get errors about livechat (with current solution to it being to just commect it out of packages) or this. Although then video conferencing wouldn't work with livechat commented out.

**Comment by sampaiodiego** [comment]
what is your operating system?

**Comment by janat08** [comment]
linux. I was running it in docker in codenvy.com in meteor environment.

**Comment by janat08** [comment]
It appears to be docker in codenvy to be issue, since other apps are now also showing same error.
