### ISSUE TITLE
backup user info 

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#6952]
Can i backup user info from RC admin? or i have to write code to access mongodb?

**Comment by jszaszvari** [comment]
You need to use mongodump to back up the database

https://www.digitalocean.com/community/tutorials/how-to-back-up-restore-and-migrate-a-mongodb-database-on-ubuntu-14-04

**Comment by Nemra1** [comment]
you can used mongochef

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
