### ISSUE TITLE
Flooding causes annoyance and crash

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#6954]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.8

Hi

Can we please get some sort of flood control?   Users copy and pasting the same thing over and over again, crashes the entire server. (or makes the chat room very laggy).

Disabling copy/paste would help but something more along the lines of only allowing users to post X amount of messages within a set time frame is better.

Or repeated messages results in an automatic mute.

There really needs to be some sort of flood control especially now that we have anonymous use for the chat rooms (which is a good feature).

Please help to make it happen.

**Comment by Nemra1** [comment]
no flood controle for now...we hope to get this option

**Comment by WebSavvyGuy** [comment]
Yes, this is a big issue for those running RC that have many users such as our sites.   There is always a few bad apples that ruin the chat experience by flooding everybody in the room causing heavy lag and nearly crashing the server.

**Comment by geekgonecrazy** [comment]
We already have rate limiting.  Maybe we can break this down into a specific feature and describe what exactly this feature would do?

All feature requests now are created in: https://forums.rocket.chat in the feature request category until planned, at which time they are moved here and added to the appropriate milestone.
