### ISSUE TITLE
Proxy for internal hubot

### ISSUE THREAD

**Issue by akleandrov** [RocketChat/Rocket.Chat#6957]
How set proxy (manual or use http_proxy) for internal hubot?

Rocket.Chat Version: 0.54.2
Running Instances: 1
Node Version: v4.7.3

**Comment by geekgonecrazy** [comment]
Being that this is internal.  Rocket.Chat wide proxy settings should effect this.  This is also needed for #2657 

@soulstyless but in general if you use the environment variable: `HTTP_PROXY` it should work

**Comment by fcoppolani** [comment]
Hi, thanks @geekgonecrazy  for this workaround. Unfortunately this way all requests go through our proxy (locahost included and thus fail). We tried to use NO_PROXY environnement variable ( https://wiki.archlinux.org/index.php/proxy_settings ), but it seems rocket.Chat (or one of its components) does not take it into account.
If you have any insight about this matter I will look forward to read it :)

**Comment by geekgonecrazy** [comment]
@fcoppolani if you export the variable then yes they would.  I would recommend passing this environment variable explicitly to rocket.chat.  

Something like:  `HTTP_PROXY=value node main.js` in what ever start up script / daemon you are using.

**Comment by fcoppolani** [comment]
Thanks for you reply, that is what we have done, HTTP_PROXY works well but everything pass through it (even the localhost requests used by rocket.chat). So we tried the NO_PROXY but this last one is not taken into account (we still see the localhost request coming into our proxy).

**Comment by geekgonecrazy** [comment]
hm.. from a quick search it looks like this NO_PROXY is widely requested across many frameworks.  But seems to not be baked in with nodejs like HTTP_PROXY is.

**Comment by timkinnane** [comment]
@geekgonecrazy was this resolved? Looks like it but I'm not sure if there's changes required to the internal hubot?

**Comment by MartinSchoeler** [comment]
Please move this to the [rocket.chat forums](https://forums.rocket.chat/). Thanks!
