### ISSUE TITLE
[Rocket.Chat+] [Feature Request] Add additional accounts to the app + edit message

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#6958]
I am currently using v1.0.11 of Rocket.Chat+ on Android 0.6.1.
There are two important things missing:

1. The option to edit your message.
2. To possibility to add additional acounts to the app, so you can switch between different chats easy and fast, without logging out, change the URL and log into another chat.

**Comment by jszaszvari** [comment]
What platform are you talking about because those features do exist on desktop?

There's a iOS project you can post this in if that's what you mean.

**Comment by punkr0ck** [comment]
Sorry, I am using Android.

**Comment by jszaszvari** [comment]
You'll probably get a better / more relevant response over in the Android project - https://github.com/RocketChat/Rocket.Chat.Android

**Comment by punkr0ck** [comment]
Thank you. Couldn't find anything like that and tried it here. I'll give it a try. Thanks!

**Comment by MartinSchoeler** [comment]
Reposted Here : https://github.com/RocketChat/Rocket.Chat.Android/issues/286
