### ISSUE TITLE
How to manually open tab on tab bar

### ISSUE THREAD

**Issue by Kolyasya** [RocketChat/Rocket.Chat#6959]
Hello, I'm developing package for RocketChat and want to open tab with it content automatically. So I need to call something like `.show()` function for my tab in TabBar.

As I understood RocketChat creates separate instances of TabBar for each room. Is there any API to access to this TabBar components from outside?

I've tried few ways, but still have no luck and can't find any docs about this. 

Rocket.Chat Version: 0.56-rc1
Running Instances: 1
DB Replicaset OpLog: 1
Node Version: v4.8.2

**Comment by jszaszvari** [comment]
Hopefully this will point you in the right direction.

This will add add a button on the sidebar which marks all messages as read in a room but it should get you going.


```
RocketChat.TabBar.addButton({
    groups: ['channel', 'privategroup', 'directmessage'],
    id: 'mark-as-read',
    i18nTitle: 'Mark as Read',
    icon: 'icon-book',
    openClick: function() {
        readMessage.readNow(true);
        return false;
                          },
    order: 999
});
```

**Comment by Kolyasya** [comment]
@jszaszvari thank you for a prompt reply. I already added a button. 
The problem is I want to open this tab automatically, as soon as user opens new room.
By the way, is there any docs for the `addButton` function?

**Comment by jszaszvari** [comment]
No Docs that I know of sorry :( 

I only know how to add it for All users that are logged in. Have not worked out how to automatically open it though.

In Settings -> Layout -> Custom Script for Logged in Users 

I have this which ensures the button is there for all users when they log in:

![2017-05-12_22-45-35](https://cloud.githubusercontent.com/assets/872463/25998563/f48eac78-3764-11e7-9767-6e344d11f0c2.png)

**Comment by jszaszvari** [comment]
You might be able to work it out by playing with the available methods in the chrome dev console...

![2017-05-12_22-50-37](https://cloud.githubusercontent.com/assets/872463/25998694/91e20f7e-3765-11e7-82f1-3228280d9387.png)

**Comment by Kolyasya** [comment]
@jszaszvari Thank you for your advice, I've already tried `RocketChat.TabBar` functions in dev console, but it didn't help.
It's interesting, that `getButtons()` method works and returns buttons list, but `show()` method doesn't work.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by brunoalano** [comment]
@kolyasya When the user open the Livechat Room, I need to open the User Information page initially. I added this on `room.js`:

```javascript
    Template.room.onCreated(function() {
        // ...
        // Auto-open the User Information Tab
        console.log("auto opening user information");
        const $flexTab = $('.flex-tab-container .flex-tab');
        if (this.tabBar.getState() === 'opened' && this.tabBar.getTemplate() === "visitorInfo") {
            $flexTab.attr('template', '');
            return this.tabBar.close();
        }
        $flexTab.attr('template', "visitorInfo");
        this.tabBar.setData({ label: "Visitor_Info", icon: "info-circled" });
        this.tabBar.open({
            "groups": [
                "live"
            ],
            "id": "visitor-info",
            "i18nTitle": "Visitor_Info",
            "icon": "info-circled",
            "template": "visitorInfo",
            "order": 0
        });
        // end / Auto-open the User Information Tab
```
