### ISSUE TITLE
Enable Drag & Drop for File-Uploading

### ISSUE THREAD

**Issue by rotkppchn** [RocketChat/Rocket.Chat#6960]
**Hello,**
i'm using Rocket.Chat in the browser and missing the "drag&drop" feature for uploading files.

![drag-drop](https://cloud.githubusercontent.com/assets/28300070/25995309/fdcc627e-3711-11e7-94a5-dc7fa3ef4dc9.png)

Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: -
Node Version: -

**Comment by geekgonecrazy** [comment]
@rotkppchn this is already implemented.  Make sure the file you are attempting to drag has been added to the allowed file types.

I would also recommend updating from 0.52.0 to 0.55.1 a few changes have likely been made to file upload since then.
