### ISSUE TITLE
Disallow blocking your self

### ISSUE THREAD

**Issue by 12test12** [RocketChat/Rocket.Chat#6962]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Activated
Node Version: 4.8.1

I still have this bug #6624. But @marceloschmidt closed it with no reason.

> 
> I found another bug. If you block yourself in a chatroom then unblock the other person then the room is blocked no one can write.
> To solve this problem you have to block yourself and then unblock yourself.
> Could you add that no one could block themselves in a direct chatroom.
> 
> ![](https://cloud.githubusercontent.com/assets/23378492/24791860/11dcf06e-1b7c-11e7-907f-3b781c1d5ee6.gif)

**Comment by geekgonecrazy** [comment]
Renamed issue to be a bit more accurate.  Simply disallowing you to block your self should solve this problem.  So disallowing blocking your self with do the trick.

**Comment by gdelavald** [comment]
This should be fixed since you can no longer see the `Block User` message for yourself.
See #6726

**Comment by geekgonecrazy** [comment]
Agreed forgot all about that.  For sure why it's closed.

@12test12 0.56.0 will be launching soon.  Be sure to give it a try there and come back if it doesn't solve your issue

**Comment by 12test12** [comment]
Ok
