### ISSUE TITLE
No push-notification in the mobile app

### ISSUE THREAD

**Issue by sttyru** [RocketChat/Rocket.Chat#6964]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.2

Rocket.Chat+ app do not show any notification about new messages by users or from channel. In the previois version of software (Rocket.Chat without plus) all notify events are success. 
In the general log of server-side application I'm not found any errors. When I try to send test message from the "Settings" -> "Push"  I'm got a message with success. But I have no notification at mobile...
Gateway: **https://gateway.rocket.chat** Also there are settings for GCM.

_I can to send the request to gateway.rocket.chat by 'curl' or another applications from my server. Iiptables, selinux or another security software is disabled._

Thank you!

**Comment by rafaelks** [comment]
Let's keep only one issue opened @sttyru, I'll close this one and let this opened: https://github.com/RocketChat/Rocket.Chat.Android/issues/254.
