### ISSUE TITLE
Blue screen issue

### ISSUE THREAD

**Issue by Shaquille-Kings** [RocketChat/Rocket.Chat#6966]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

Hi, After a week of running rocketserver I get on all new devices the blue screen. It makes the connection with the server, but after that I only get the blue screen and the login tab doesn't appear. Every other device that logged at least once in, can work perfectly fine. What can I do to fix this issue??

**Comment by madguy02** [comment]
Can you elaborate on the situations where you are getting this blue screen issue,if possible can you post some screenshots

**Comment by madguy02** [comment]
@Shaquille-Kings

**Comment by madguy02** [comment]
Also @Shaquille-Kings  can you please mention Version no.:,Running Instances: and DB Replicaset OpLog:

**Comment by Shaquille-Kings** [comment]
Thanks for your time @madguy02 , I get this on pc's IOS devices and androi i get abort. This problem I get at the office and the other shops.

**Comment by madguy02** [comment]
Cool!! awesome :)

**Comment by Shaquille-Kings** [comment]
![test rocketchat](https://cloud.githubusercontent.com/assets/26796253/26067132/7c3e613e-396f-11e7-8924-5e7ae84c42cb.jpg)

**Comment by Shaquille-Kings** [comment]
i run the version of rocketchat using it with snap

**Comment by Shaquille-Kings** [comment]
latest version of rocketchat*
