### ISSUE TITLE
Brief flash of unread messages.

### ISSUE THREAD

**Issue by cr22rc** [RocketChat/Rocket.Chat#6967]
Rocket.Chat Version: 
Running Instances: 
Web, desktop (rocketchat-desktop-2.7.0.rpm) , android client
DB Replicaset OpLog:
Node Version:

When I click on a channel there is a brief flash on the a bar to jump to the latest unread message but before I get to it, it goes away. This happens maybe 1 in 4 times I'm guessing. I see this on the web, desktop client, and on the Android client on my phone.

**Comment by geekgonecrazy** [comment]
I seem to be seeing this more and more on channels that have a large count of unread.  It'll show.. I'll scroll a bit and suddenly its gone.

**Comment by geekgonecrazy** [comment]
@karlprieb I can consistently reproduce in #general after not opening it for 24 hours or so.  :grin: in case you need a location to try it out.

**Comment by cr22rc** [comment]
Any ETA on this please .. It's quite annoying and makes it hard to keep up with conversations

**Comment by MartinSchoeler** [comment]
Apparently this happens when you need to load the channel, if it was recently opened or you are in the channel this doesn't seem to happen

**Comment by geekgonecrazy** [comment]
Yeah this doesn't happen for me if i've recently been in the channel

**Comment by MartinSchoeler** [comment]
Also if there is unread messages that aren't loaded the unread bar disappears after 2 seconds, my guess is that the problem its in [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/lib/readMessages.js#L81) method being called [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/client/lib/openRoom.js#L71)
