### ISSUE TITLE
Docker files ignore local repo

### ISSUE THREAD

**Issue by kpcyrd** [RocketChat/Rocket.Chat#6970]
I've noticed multiple issues with the docker setup:

- docker-compose.yml doesn't use the local repo
- `./.docker/develop/Dockerfile` fails to build by trying to download a non-existent github release (`develop`)

This makes contributing way more complicated, since I can't just start a stack that is based on my local repo.

**Comment by TheReal1604** [comment]
![image](https://cloud.githubusercontent.com/assets/5877910/26052679/916a8a1e-3966-11e7-9f8a-3efc0ecbc9fa.png)

**Comment by sampaiodiego** [comment]
@kpcyrd the `docker-compose.yml` file is not intended for local development, it's meant to be a production example, but I can see it can lead to confusion. for local development you should do `meteor npm start` 

@TheReal1604 is it still saying `release not found` my requests are working:
![image](https://cloud.githubusercontent.com/assets/8591547/26057505/55023b1e-3950-11e7-9f0a-695dc7c9cef8.png)

**Comment by marceloschmidt** [comment]
No longer an issue.
