### ISSUE TITLE
Emoticon reaction: wrong name

### ISSUE THREAD

**Issue by rumaxr** [RocketChat/Rocket.Chat#6975]
Rocket.Chat Version: 2.7.0
Running Instances: Mac desktop client

Emoticon reaction shows a wrong name when someone with the same partial name reacted.

My usename is 'max' and someone else in the chat group is called 'max.s'.

When I hover the emoticon the label shows: 'You.s reacted with :emoticon:'.

So in 'max.s' (my colleague's username) 'max' (my username) is replaced by 'You'. 

I believe the error is in this part of the code.

[https://github.com/RocketChat/Rocket.Chat/blob/ddc6822b33380f34769684d409df73bd4d2da623/packages/rocketchat-ui-message/client/message.coffee#L123](url)

**Comment by madguy02** [comment]
Thanks for pointing it out.@rumaxr .I am not able to go through the code from the link attached.Please create a pull request and the team will review it ASAP :)

**Comment by MartinSchoeler** [comment]
@rumaxr  The correct link for the file is https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-message/client/message.coffee#L123

I think a simple if to check if the username is equal (===) to the current logged user username would solve this.

Thanks for the feedback!
