### ISSUE TITLE
Allow forcing of oauth username

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#6977]
In some cases people do not want to give the option to choose a different username then their authentication provider.

So if they are hooking to wordpress and the username there is `joe123` they do not want their users to have the option to change this username.  They want this name to be automatically taken.

We would likely still have to fall back and show the username suggestion if some how that username was already taken.

**Comment by Bluer-RC** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/6944#issuecomment-301551906

It worked. Name will be Unnamed but username is forced.
