### ISSUE TITLE
RC and releases appear to be diverging from develop?

### ISSUE THREAD

**Issue by abrom** [RocketChat/Rocket.Chat#6980]
See https://github.com/RocketChat/Rocket.Chat/compare/0.56.0...develop

Any reason these would not be getting merged into the RC's and master? At the time I created this issue, I believe there were 42 commits in develop that had not been included in RCs or master?!

**Comment by MartinSchoeler** [comment]
Closing this as is not a bug nor feature request, please use https://forums.rocket.chat/ for discussions. Thanks!
