### ISSUE TITLE
Page with server download is not working

### ISSUE THREAD

**Issue by Rohlik** [RocketChat/Rocket.Chat#6981]
I used `https://rocket.chat/releases/latest/download` for download latest server RC instance. But now, this page return `release not found`.
What happend?

**Comment by Sing-Li** [comment]
Confirmed - both links broken.  

![screen shot 2017-05-16 at 3 17 31 am](https://cloud.githubusercontent.com/assets/122633/26094036/44648b36-39e6-11e7-8f7d-8a80a135da7a.png)

**Comment by Sing-Li** [comment]
Build glitch.

Thanks to @rodrigok , they are fixed .  Closing this now. 

@Rohlik   please verify and re-open if you still have problem.

**Comment by MartinSchoeler** [comment]
@rodrigok fixed this.
