### ISSUE TITLE
Best way to deploy Rocket.Chat app

### ISSUE THREAD

**Issue by raelsan** [RocketChat/Rocket.Chat#6983]
Rocket.Chat Version: 0.55.0-develop
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

Hi !

I'm developping on a VM with CentOS 7. I'm looking for the best way to deploy my app on another server (using CentOS 7 too). 

Can someone help me ?

**Comment by Rohlik** [comment]
I think that Docker is easiest way to deploy RC instance.

**Comment by raelsan** [comment]
I can't use Docker...

**Comment by k0nsl** [comment]
@raelsan: Why not? Due to the virtualization employed?

**Comment by raelsan** [comment]
I never used it. And our customers not either.

**Comment by rodorgas** [comment]
Documentation is very complete about deployment methods.

For instance https://rocket.chat/docs/installation/manual-installation/centos

**Comment by raelsan** [comment]
I did what I wanted to do :) Thanks for your help !
