### ISSUE TITLE
Push notifications do not work for groups/channels

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6988]
Even when setting notifications to receive **all messages** for mobile, in any group or channel they do not arrive at the mobile device. 
`[34kI20170517-00:51:23.974(2) Push: Sent message "#testraum1" to 0 ios apps 0 android apps `

Mentions or notifications for PM work as expected.   
`[34kI20170517-00:51:48.097(2) Push: Sent message "#testraum1" to 0 ios apps 1 android apps`    
Also notifications for desktop work as expected.

See also https://github.com/RocketChat/Rocket.Chat/issues/5308  and https://github.com/RocketChat/Rocket.Chat/issues/1602#issuecomment-226559485 (allow to configure push independent of status).

Rocket.Chat Version: 0.56 (upgraded today), observed also with 0.52

**Comment by rafaelks** [comment]
@rasos 

- What OS are you using?
- What's the app version?
- Are you using our app from the store, or you compiled it?

**Comment by rasos** [comment]
@rafaelks 

- RC server is on CentOS.   
- Tested with apps
 -- latest RC client from iTunes store for iOS 
 -- latest RC+ client for Android (seems not to handle push at all?)
 -- custom ucom App (Qt based, can handle push)

As you see on the log, the RC server does not send a push token.

**Comment by rasos** [comment]
We found that our own Qt based client did not change back the status from "Online" to "Away". As this is a precondition to receive notifications, logged in users never received them. It seemed to be a coincidence, that the App was running when we tested the behaviour in rooms.

**Comment by rasos** [comment]
We have now implemented online/away for the App, the status is shown correctly in Rocket.Chat.   
Still, push notifications do not arrive when "away".  
We also applied the patch https://github.com/RocketChat/Rocket.Chat/issues/1602#issuecomment-226559485 - still no success.   
Notifications only arrive, when there is no connection at all from the app to the server by closing app.   Even if the app shows offline status, it seems that RC thinks the user is still online and does not need push notifications.  

What are the conditions to send push notifications for mobile use? 
I tried to study the code in rocketchat_lib.js:1771 but do not get a clue.

**Comment by rafaelks** [comment]
@rodrigok Can you help us here? What's the conditions to send a push notification to the mobile apps?

**Comment by rasos** [comment]
After studying the code in packages/rocketchat_lib/server/lib/sendNotificationsOnMessage.js around line 150 ( = rocketchat_lib.js on server around line 1820) we found out that push is only delivered to mobile Rocket:chat devices, if their network status is disconnected. Our Qt based App only went to user status "away", when backgrounded, which is not recognized really being away in the push notification logic. We are now also disconnecting and have solved the issue.
