### ISSUE TITLE
Questions on Shields feature

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#6989]
Rocket.Chat Version: 0.56
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Hi @alexbrazier I had a look at your new shields feature https://github.com/RocketChat/Rocket.Chat/pull/6565 which looks cool!

How can we change the branding and colours for the shield to use some other icon than Rocket.chat? Would be nice to have a new shield.svg included in the Assets section under Administration

**Comment by alexbrazier** [comment]
I think this is a good idea. We can add an image to the assets section, as you say, and add some colours to the colours section quite easily.

Is this something you were looking to implement, or just a feature request?

**Comment by meghalagrawal** [comment]
Is this an active issue?

Can I work on it? Whom can I contact in case of suggestions?

**Comment by c0dzilla** [comment]
I'm taking this up.
