### ISSUE TITLE
How many anonymous are connected

### ISSUE THREAD

**Issue by Cikcak** [RocketChat/Rocket.Chat#6993]
Thank you for new feature which enable anonym viewing.
Is it possible show/view how many anonymous are connected in room?
Best way would be for example in user list on right pannel like Anonymous **(3)** or at the head of room.

Rocket.Chat Version: 0.56
Running Instances: 1
DB Replicaset OpLog:
Node Version: v4.8.1

**Comment by madguy02** [comment]
@MartinSchoeler

**Comment by rodrigok** [comment]
We are not planning to have this in our roadmap, the technical implications are high since we don't track anonymous users, please start a discussion in our [forums](https://forums.rocket.chat) if you want to continue this thread.
