### ISSUE TITLE
messages not deleted

### ISSUE THREAD

**Issue by nORKy54** [RocketChat/Rocket.Chat#6994]
Rocket.Chat Version: 0.56
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.8.1

Hi, I delete my own message: the message is deleted, but when I refresh my web page, the message is back

**Comment by Nemra1** [comment]
maybe this happend only with you bcs i have same version and no problem with delet msg for me or for others

**Comment by madguy02** [comment]
@nORKy54 it works on the community server(demo.rocket.chat),on all the channels.can you reproduce the error once again on the localhost?

**Comment by madguy02** [comment]
If it persists,try making a git pull and start over again

**Comment by MartinSchoeler** [comment]
duplicate of #6941
