### ISSUE TITLE
SSL Verification SMTP Server since 0.56.0

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6996]
Rocket.Chat Version: 0.56.0
Running Instances: 3
DB Replicaset OpLog: YES

Since 0.56.0 there seems a smtp server ssl verification in place which causes massive issues at our side - we send mails over a relay with a self signed certificate.

How to disable this in a docker deployment? Is there an env variable?

**Comment by sscholl** [comment]
Go to Administation->E-Mail->SMTP and try Protocol and Pool settings.

**Comment by 1stposition-ad** [comment]
same problem here, in Protocol i only have the choice between smtp and smtps.

**Comment by TheReal1604** [comment]
@sscholl already changed it to "smtp" and it checks the certificate...

**Comment by sscholl** [comment]
@TheReal1604 in fact, the protocol should be smtps if you have self signed certs. maybe you could use letsencrypt to get valid ssl certs. I dont expect, that you will get support from the Rocket.Chat team for self signed certificates.

**Comment by TheReal1604** [comment]
@sscholl dont want support exactly for this - but support for a function to disable this check.

We resolved it by changing the certificate. 👍

**Comment by sscholl** [comment]
That means, this is a feature request for:
**Adding posibility for disabling SMTPS Certificate Check**

**Comment by localguru** [comment]
If the mail server is running on the same host and just listening on localhost, SSL might not make sense in all cases. SSL and smtp_auth should be optional. It should be possible to send mails just through localhost without smtp_auth and SSL.

And what does "pool" setting mean?

**Comment by colin-campbell** [comment]
We have an unencrypted local SMTP server. With protocol set to 'smtp" and on port 25 we get "Error trying to send email: self-signed certificate"

**Comment by deogracia** [comment]
Thanks Rocket.chat team for  your hard work.

@sscholl , it shouldn't be a feature request, since AFAIK, unencypted SMTP isn't deprecated nor forbiden. Can you tell us the reason why you chose to force encrypted SMTP?

**Comment by localguru** [comment]
@colin-campbell you need a certificate signed from a proper CA. I my case I used the certificate from the webserver, which is not self signed. To my mind this is a little bit overkill for a locally running smtp, so there should be a way to send out emails without forcing TLS.

**Comment by localguru** [comment]
And what about an reply-to option for sending out emails. If an user answers and offline messages, I'd like to send that emails to a different address e.g. rocketchat-norelay, so one can just drop such emails and send out an autoresond email.

**Comment by colin-campbell** [comment]
@localguru Why one earth would I need a certificate for SMTP on port 25 without STARTTLS? anyway I have a patch to fix it. I'll submit shortly.

**Comment by deogracia** [comment]
thanks @colin-campbell !

**Comment by localguru** [comment]
@colin-campbell if your smtp really doesn't offer TLS your don't need a cert, right.

**Comment by colin-campbell** [comment]
@localguru that is correct, but the email@1.2.1/node4mailer will starttls automatically even with 'smtp' selected then complain about "self-signed" certificate. My patch will add a setting in the interface and to process.env.MAIL_URL:  "IgnoreTLS"

**Comment by rodrigok** [comment]
I'll close this issue, please test the next RC version and reopen it if necessary.
