### ISSUE TITLE
"meteor npm start " Failed

### ISSUE THREAD

**Issue by sassi1990** [RocketChat/Rocket.Chat#6998]
Hello Everyone, 

I failed to install the app via npm, I’ve tried multiple node and npm versions "including the latest versions", I’m on Ubuntu 16.04
Here are the errors I get: 

Rocket.Chat@0.57.0-develop start /dev/www/Rocket.Chat
> meteor npm i && meteor

npm WARN lifecycle Rocket.Chat@0.57.0-develop~postinstall: cannot run in wd %s %s (wd=%s) Rocket.Chat@0.57.0-develop cd packages/rocketchat-katex && npm i /dev/www/Rocket.Chat
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chimp/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

You are attempting to run Meteor as the 'root' superuser. If you are developing, this is almost certainly *not* what you want to do and will likely result in incorrect file permissions. However, if you
are running this command in a build process (CI, etc.), or you are absolutely sure you know what you are doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass --allow-superuser to proceed.

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your
permissions, run the following command from the root of your project:

  sudo chown -Rh <username> .meteor/local

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@0.57.0-develop start: `meteor npm i && meteor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Rocket.Chat@0.57.0-develop start script 'meteor npm i && meteor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Rocket.Chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor npm i && meteor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Rocket.Chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Rocket.Chat
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aasassi/.meteor/packages/meteor-tool/.1.4.4_2.5g3s0q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-17T13_34_30_913Z-debug.log

**Comment by sampaiodiego** [comment]
as stated by the error message, you're trying to run as _root_ which is unencouraged by meteor.

if you need to run as root, you can export the following env var before trying to run:
```
export METEOR_ALLOW_SUPERUSER=1
```

then you can run the app:
```
meteor npm start
```

**Comment by sassi1990** [comment]
Now i get an access err (permission denied):

optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! path /dev/www/rocket.Chat
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/dev/www/rocket.Chat'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/dev/www/rocket.Chat']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/dev/www/rocket.Chat' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aasassi/.meteor/packages/meteor-tool/.1.4.4_2.5g3s0q++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-19T10_34_13_083Z-debug.log

**Comment by sampaiodiego** [comment]
that's because your folder is already owned by `root`. you have to change it's ownership.. I recommend you start by the beggining using the non-root user. or as I said you can try setting the environment variable:
```
export METEOR_ALLOW_SUPERUSER=1
```

**Comment by sassi1990** [comment]
Stil got this error : 

npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /home/aasassi/.meteor/packages/meteor-tool/1.4.4_2/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-22T07_46_07_800Z-debug.log
   Phantom installation failed { [Error: EACCES: permission denied, open '/tmp/mt-4cxdk1/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path: '/tmp/mt-4cxdk1/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js' } Error: EACCES: permission denied, open
   '/tmp/mt-4cxdk1/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
   at Error (native)
   at Object.fs.openSync (fs.js:549:18)
   at Object.fs.writeFileSync (fs.js:1156:15)
   at writeLocationFile (/tmp/mt-4cxdk1/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
   at Promise._successFn (/tmp/mt-4cxdk1/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
   at nextTickCallback (/tmp/mt-4cxdk1/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
   at nextTickCallbackWith0Args (node.js:489:9)
   at process._tickCallback (node.js:418:13)
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! phantomjs@1.9.20 install: `node install.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the phantomjs package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node install.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs phantomjs
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls phantomjs
   npm ERR! There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /home/aasassi/.meteor/packages/meteor-tool/1.4.4_2/mt-os.linux.x86_64/dev_bundle/.npm/_logs/2017-05-22T07_46_07_800Z-debug.log

**Comment by sampaiodiego** [comment]
I've managed to get it working by calling `meteor npm start` twice.. can you give it a try?

**Comment by linping1229** [comment]
Please install meteor as user not root and then run "meteor npm i"
and then set the environment variable "export METEOR_ALLOW_SUPERUSER=1"
- meteor

That's it.
