### ISSUE TITLE
Unable to invite/add person to private group

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#700]
There is a new user who I can not invite/add to a private group either via the form or the /invite command.  It may be applicable that I believe he is a new signup that may not have spoke (sent any messages) yet.  User was @lhfazry on the demo chat.  Attempted via web, mac app and android app with same result.

![screen shot 2015-09-05 at 20 34 28](https://cloud.githubusercontent.com/assets/277910/9699456/f97e5558-540d-11e5-9d1e-9e434df2c91f.png)

**Comment by alisalaah** [comment]
Worked when I typed his first name "Lhu" then auto-completing finished it.  Was expecting username not real name but not a bug unless we want to change that...

**Comment by geekgonecrazy** [comment]
Was the person online? Going to try this out and see what its doing.  I was under the impression it was searching by username.

**Comment by geekgonecrazy** [comment]
Alright so it does appear to be searching name instead of username like the rest of places.  Maybe it should do both.  Matching username first
