### ISSUE TITLE
Include <html> and </html> in header and footer

### ISSUE THREAD

**Issue by ExTechOp** [RocketChat/Rocket.Chat#7001]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

In file `Rocket.Chat/packages/rocketchat-lib/server/startup/settings.js` the default `Email_Header` and `Email_Footer` values should include a preceding \<html> and a trailing \</html> respectively, or the emails sent by Rocket.chat will [get spam points from SpamAssassin](https://wiki.apache.org/spamassassin/Rules/HTML_MIME_NO_HTML_TAG) due to technically malformed html (typical of spam messages).

**Comment by sampaiodiego** [comment]
thanks for the report.. as you have already correctly found the place to fix it, do you mind to make a pull request with the recommended solution? we would be more than glad to accept it =)
