### ISSUE TITLE
Can't set default rooms anymore

### ISSUE THREAD

**Issue by apmilen** [RocketChat/Rocket.Chat#7007]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

Hi! It seems that setting default rooms is disabled for me somehow? I definitely used to have this admin permission, but now I can't see the option when viewing a room.

<img width="1144" alt="screen shot 2017-05-17 at 7 47 01 pm" src="https://cloud.githubusercontent.com/assets/2745728/26180876/370390d6-3b3a-11e7-9293-1f3885401871.png">

Is there some new UI that I'm missing here? Or am I mistaken in the assumption that members of the admin role can set default rooms?

**Comment by ccesareo** [comment]
This happened to me the other day. I believe when I refreshed the page and went back to it the option appeared again.

**Comment by MartinSchoeler** [comment]
Hey @apmilen looks like you are using a outdated version of Rocket.Chat, this issue has been fixed on version 0.56.0, so updating your instance should fix the issue. Thanks for the feedback!

**Comment by apmilen** [comment]
thanks :)

**Comment by johanricher** [comment]
I'm having the same problem on our instance (chat.codefor.fr): impossible to change the default status of rooms. I've done it before and could swear it was a toggle option within the Rooms page in the Administration panel. It's not there anymore:

![image](https://user-images.githubusercontent.com/10212787/72070533-1d16f000-32ea-11ea-8454-21cb80b8b365.png)

Can we please reopen this issue to get to the bottom of this? 

Version: 2.4.0
Deployment Method: Cloudron
OS: linux x64 4.4.127-mainline-rev1
Node version: v8.12.0
Mongo version: 3.6.3
OpLog | Enabled

**Comment by johanricher** [comment]
@MartinSchoeler Can you give me some advice? Do I open a new issue?

**Comment by MartinSchoeler** [comment]
@johanricher This Bug seems to have returned, I will reopen this issue.

**Comment by ritwizsinha** [comment]
I would like to work on this,

**Comment by MartinSchoeler** [comment]
@ritwizsinha there is no ownership of issues in Rocket.Chat, so nobody should give or ask for permission to work on stuff, if you want to work on something, just create a pull request. We usually review and merge PRs based on their quality, and not by "who made it first", anyways this particular issue will already be closed on #16025

**Comment by GoetheG** [comment]
Having version 2.4.0. I have the same issue here.

**Comment by gabriellsh** [comment]
Fixed by #16433

**Comment by johanricher** [comment]
Problem solved on my end, with Rocket.Chat 2.4.7. :tada: Thank you and congrats to all the team on releasing version 3.0.0 soon. :clap:

**Comment by Attack44** [comment]
The problem has been around for a long time and version 3.2.0 is no different.
![rocket_chat_room](https://user-images.githubusercontent.com/19206966/80486402-65baed80-895b-11ea-8855-e910ec2b5cfb.PNG)
