### ISSUE TITLE
Outgoing webhook questions

### ISSUE THREAD

**Issue by ellisgl** [RocketChat/Rocket.Chat#7008]
I'm converting an IRC bot I developed to used on Rocket.Chat, and was wondering how to how the outbound webhook send the response to the user that triggered it, instead of the channel it was sent from? But I only need it for one case, the rest would respond back to the channel.

**Comment by ellisgl** [comment]
For now, the work around I found is that I can reply with a blank object to the outbound webhook, then fire off a inbound webhook request that has the channel: @user in the payload. But would be nice to have it supported in the outbound response.

**Comment by graywolf336** [comment]
Is this in the script part of the outgoing integrations?

**Comment by ellisgl** [comment]
@graywolf336 So even if I put channel:@user in the process_outgoing_response, it doesn't work:

    class Script
    {
        prepare_outgoing_request({ request })
        {
            let match;
            match = request.data.text.match(/^!(.*)/);

            if (match)
            {
                var args = match[1].split(' ');
                var func = args.shift();
                
                return {
                      url: request.url + '/' + func,
                      headers: request.headers,
                      method: 'POST',
                      data: {
                        args: args,
                        data: request.data
                      }
                };
            }
          
          return false;
        }

        process_outgoing_response({ request, response })
        {
            //console.log(response);
            
            if(response.hasOwnProperty('content') && response.content.hasOwnProperty('text'))
            {
                var content = {
                    content: {
                        text: (Array.isArray(response.content.text)) ? response.content.text.join("\n") : response.content.text,
                        channel: '@myusername'
                    }
                };

                return content;
            }
            else
            {
                return null;
            }
        }
    }

**Comment by graywolf336** [comment]
@ellisgl No, sadly it is not possible to do what you're wanting right now...but I thought it used to. I'm working on something so that in the future ones it can work.
