### ISSUE TITLE
Feature: IRC Color Support

### ISSUE THREAD

**Issue by ellisgl** [RocketChat/Rocket.Chat#7009]
It would be nice to have (m)IRC Color support in webhooks. This way I can color code parts of text, instead of the whole thing.

**Comment by ellisgl** [comment]
Or even allow for HTML code to not be escaped from a webhook, the we could just do spans with a color/bgcolor instead.

**Comment by graywolf336** [comment]
This is a whole new feature set to add to rocket.chat and not that "simple" to add. What format would you recommend we take a look at using? How would it work when sending a message inside of Rocket.Chat's clients? We can't use regular html due to the potential security risks..

**Comment by ellisgl** [comment]
So actually - I've been playing with the mark down code, so here's some code to look over:

    msg = msg.replace(/\{color fg:([#\w]\w+)\}([^{]+)\{\/color\}/img, '<span style="color:$1;">$2</span>');
    msg = msg.replace(/\{color bg:([#\w]\w+)\}([^{]+)\{\/color\}/img, '<span style="background-color:$1;">$2</span>');
    msg = msg.replace(/\{color fg:([#\w]\w+) bg:([#\w]\w+)\}([^{]+)\{\/color\}/img, '<span style="color:$1; background-color:$2;">$3</span>');

**Comment by ellisgl** [comment]
Also it could be restricted to the 16 IRC colors too if need be.

**Comment by ellisgl** [comment]
So to keep it limited to IRC Colors it would be:

    msg = msg.replace(/\{color fg:(White|Black|Blue|Green|Red|Brown|Purple|Orange|Yellow|LightGreen|Cyan|LightCyan|LightBlue|PinkGray|LightGray)\}([^{]+)\{\/color\}/img, '<span style="color:$1;">$2</span>');
    msg = msg.replace(/\{color bg:(White|Black|Blue|Green|Red|Brown|Purple|Orange|Yellow|LightGreen|Cyan|LightCyan|LightBlue|PinkGray|LightGray)\}([^{]+)\{\/color\}/img, '<span style="background-color:$1;">$2</span>');
    msg = msg.replace(/\{color fg:(White|Black|Blue|Green|Red|Brown|Purple|Orange|Yellow|LightGreen|Cyan|LightCyan|LightBlue|PinkGray|LightGray) bg:(White|Black|Blue|Green|Red|Brown|Purple|Orange|Yellow|LightGreen|Cyan|LightCyan|LightBlue|PinkGray|LightGray)\}([^{]+)\{\/color\}/img, '<span style="color:$1; background-color:$2;">$3</span>');
    msg = msg.replace(/\{color bg:(White|Black|Blue|Green|Red|Brown|Purple|Orange|Yellow|LightGreen|Cyan|LightCyan|LightBlue|PinkGray|LightGray) fg:(White|Black|Blue|Green|Red|Brown|Purple|Orange|Yellow|LightGreen|Cyan|LightCyan|LightBlue|PinkGray|LightGray)\}([^{]+)\{\/color\}/img, '<span style="color:$2; background-color:$1;">$3</span>');

**Comment by ellisgl** [comment]
#7040

**Comment by ellisgl** [comment]
#7061 (Fixed to use tabs...)

**Comment by ellisgl** [comment]
So I figure with a lot of request for IRC integration, it might be wise to restrict to IRC colors.

**Comment by graywolf336** [comment]
You could have a setting which defaults to all colors allowed and then the setting restricts them to the IRC colors?

**Comment by ellisgl** [comment]
@graywolf336 Yeah - having a setting for that would be better. I would need to dig around to see how that would get setup.

**Comment by ellisgl** [comment]
Yeah - I would need some help figuring that out...

**Comment by ellisgl** [comment]
So how would I add that to the option btw? Colors: (radio buttons) Off, Full, IRC?

**Comment by graywolf336** [comment]
@ellisgl I apologize for not answering sooner. Create a setting in the Messages section which has this enabled/disabled. Here's where some of the current settings are defined https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/startup/settings.js#L689

**Comment by ellisgl** [comment]
@graywolf336 OK - I've added Message_Colors to that, how to do I detect it in the other part?

**Comment by ellisgl** [comment]
Never mind - put everything in markdown and I think I figured out the settings. See the latest update on the pull

**Comment by ellisgl** [comment]
Any chance of getting the new code reviewed? It does the same thing as the previous pull, but it work with the dev code.

**Comment by ellisgl** [comment]
Going to close this, because yeah, no one cares about it.
