### ISSUE TITLE
Administration page help texts shown incorrectly

### ISSUE THREAD

**Issue by ExTechOp** [RocketChat/Rocket.Chat#7010]
Rocket.Chat Version: 56
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0

In the administration pages, the help texts are shown incorrectly (html code that should not be escaped gets escaped). For example under Message:

> Always search using RegExp ☐ True ☒ False
> We recommend to set \`True\` if your language is not supported on \<a target="_blank" href="https∶//docs.mongodb.org/manual/reference/text-search-languages/#text-search-languages">MongoDB text search\</a>.

**Comment by MartinSchoeler** [comment]
duplicate of #6992
