### ISSUE TITLE
Clear chat room and automatically expire messages

### ISSUE THREAD

**Issue by Bluer-RC** [RocketChat/Rocket.Chat#7011]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: no
Node Version: v4.8.3

So talked in the RC chat and seemed weird that this was not implemented yet, seems like a default feature and definitely something needed. Ability to clear (permanently delete) all messages in the chat room without having to delete the whole room and create it again, for example. /clear command for admins and mods. And the ability to enable message expiration so they are automatically deleted after set amount of age (days).

**Comment by MartinSchoeler** [comment]
duplicate of #2355
