### ISSUE TITLE
Audio not working during screen sharing.. Before sharing the screen, audio is working fine. but after starting screen sharing audio is disconnected

### ISSUE THREAD

**Issue by yneha** [RocketChat/Rocket.Chat#7013]
Rocket.Chat Version: 0.57
Running Instances: trying to run through localhost
DB Replicaset OpLog:
Node Version:4.8.2

**Comment by mborhade** [comment]
same here

**Comment by danielo926** [comment]
Same problem

**Comment by yneha** [comment]
This issue is resolved. 
Comment this lines in the webRTC file
 stream.removeTrack(stream.getAudioTracks()[0]);
stream.removeTrack(stream.getVideoTracks()[0]);
This will not remove the current stream and the call will continue without any issue.

**Comment by mborhade** [comment]
Thanks @yneha , I will check :)

**Comment by mborhade** [comment]
It Work's for me , Thanks @yneha

**Comment by danielo926** [comment]
Where is this file?

**Comment by mborhade** [comment]
~/Rocket.Chat/packages/rocketchat-webrtc/client/WebRTCClass.js

**Comment by danielo926** [comment]
I dont have "rocketchat-webrtc" folder...

**Comment by mborhade** [comment]
ohh , you have packages directory there ?

**Comment by danielo926** [comment]
in /Rocket.Chat/ I dont have packages folder 
I have packages folder in /Rocket.Chat/programs/server/packages

**Comment by mborhade** [comment]
what are packages inside ? like rocketchat-..... ?

**Comment by danielo926** [comment]
rocketchat_2fa.js
rocketchat_2fa.js.map
rocketchat_action-links.js
rocketchat_action-links.js.map
rocketchat_analytics.js
rocketchat_analytics.js.map
rocketchat_api.js
rocketchat_api.js.map
rocketchat_assets.js
rocketchat_assets.js.map
rocketchat_authorization.js
rocketchat_authorization.js.map
rocketchat_autolinker.js
rocketchat_autolinker.js.map
rocketchat_autotranslate.js
rocketchat_autotranslate.js.map
rocketchat_bot-helpers.js
rocketchat_bot-helpers.js.map
rocketchat_cas.js
rocketchat_cas.js.map
rocketchat_channel-settings.js
rocketchat_channel-settings.js.map
rocketchat_channel-settings-mail-messages.js
rocketchat_channel-settings-mail-messages.js.map
rocketchat_colors.js
rocketchat_colors.js.map
rocketchat_cors.js
rocketchat_cors.js.map
rocketchat_crowd.js
rocketchat_crowd.js.map
rocketchat_custom-oauth.js
rocketchat_custom-oauth.js.map
rocketchat_custom-sounds.js
rocketchat_custom-sounds.js.map
rocketchat_dolphin.js
rocketchat_dolphin.js.map
rocketchat_drupal.js
rocketchat_drupal.js.map
rocketchat_emoji-custom.js
rocketchat_emoji-custom.js.map
rocketchat_emoji-emojione.js
rocketchat_emoji-emojione.js.map
rocketchat_emoji.js
rocketchat_emoji.js.map
rocketchat_error-handler.js
rocketchat_error-handler.js.map
rocketchat_favico.js
rocketchat_file.js
rocketchat_file.js.map
rocketchat_file-upload.js
rocketchat_file-upload.js.map
rocketchat_github-enterprise.js
rocketchat_github-enterprise.js.map
rocketchat_gitlab.js
rocketchat_gitlab.js.map
rocketchat_google-vision.js
rocketchat_google-vision.js.map
rocketchat_highlight-words.js
rocketchat_i18n.js
rocketchat_iframe-login.js
rocketchat_iframe-login.js.map
rocketchat_importer-csv.js
rocketchat_importer-csv.js.map
rocketchat_importer-hipchat-enterprise.js
rocketchat_importer-hipchat-enterprise.js.map
rocketchat_importer-hipchat.js
rocketchat_importer-hipchat.js.map
rocketchat_importer.js
rocketchat_importer.js.map
rocketchat_importer-slack.js
rocketchat_importer-slack.js.map
rocketchat_integrations.js
rocketchat_integrations.js.map
rocketchat_internal-hubot.js
rocketchat_internal-hubot.js.map
rocketchat_irc.js
rocketchat_irc.js.map
rocketchat_issuelinks.js
rocketchat_issuelinks.js.map
rocketchat_katex.js
rocketchat_katex.js.map
rocketchat_ldap.js
rocketchat_ldapjs.js
rocketchat_ldap.js.map
rocketchat_lib.js
rocketchat_lib.js.map
rocketchat_livechat.js
rocketchat_livechat.js.map
rocketchat_logger.js
rocketchat_logger.js.map
rocketchat_login-token.js
rocketchat_login-token.js.map
rocketchat_mailer.js
rocketchat_mailer.js.map
rocketchat_mapview.js
rocketchat_mapview.js.map
rocketchat_markdown.js
rocketchat_markdown.js.map
rocketchat_mentions-flextab.js
rocketchat_mentions-flextab.js.map
rocketchat_mentions.js
rocketchat_mentions.js.map
rocketchat_message-attachments.js
rocketchat_message-mark-as-unread.js
rocketchat_message-mark-as-unread.js.map
rocketchat_message-pin.js
rocketchat_message-pin.js.map
rocketchat_message-snippet.js
rocketchat_message-snippet.js.map
rocketchat_message-star.js
rocketchat_message-star.js.map
rocketchat_migrations.js
rocketchat_migrations.js.map
rocketchat_monitoring.js
rocketchat_oauth2-server-config.js
rocketchat_oauth2-server-config.js.map
rocketchat_oauth2-server.js
rocketchat_oauth2-server.js.map
rocketchat_oembed.js
rocketchat_oembed.js.map
rocketchat_otr.js
rocketchat_otr.js.map
rocketchat_postcss.js
rocketchat_push-notifications.js
rocketchat_push-notifications.js.map
rocketchat_reactions.js
rocketchat_reactions.js.map
rocketchat_sandstorm.js
rocketchat_sandstorm.js.map
rocketchat_slackbridge.js
rocketchat_slackbridge.js.map
rocketchat_slashcommands-archive.js
rocketchat_slashcommands-archive.js.map
rocketchat_slashcommands-asciiarts.js
rocketchat_slashcommands-asciiarts.js.map
rocketchat_slashcommands-create.js
rocketchat_slashcommands-create.js.map
rocketchat_slashcommands-help.js
rocketchat_slashcommands-help.js.map
rocketchat_slashcommands-invite-all.js
rocketchat_slashcommands-invite-all.js.map
rocketchat_slashcommands-invite.js
rocketchat_slashcommands-invite.js.map
rocketchat_slashcommands-join.js
rocketchat_slashcommands-join.js.map
rocketchat_slashcommands-kick.js
rocketchat_slashcommands-kick.js.map
rocketchat_slashcommands-leave.js
rocketchat_slashcommands-leave.js.map
rocketchat_slashcommands-me.js
rocketchat_slashcommands-me.js.map
rocketchat_slashcommands-msg.js
rocketchat_slashcommands-msg.js.map
rocketchat_slashcommands-mute.js
rocketchat_slashcommands-mute.js.map
rocketchat_slashcommands-open.js
rocketchat_slashcommands-topic.js
rocketchat_slashcommands-topic.js.map
rocketchat_slashcommands-unarchive.js
rocketchat_slashcommands-unarchive.js.map
rocketchat_slider.js
rocketchat_smarsh-connector.js
rocketchat_smarsh-connector.js.map
rocketchat_sms.js
rocketchat_sms.js.map
rocketchat_spotify.js
rocketchat_spotify.js.map
rocketchat_statistics.js
rocketchat_statistics.js.map
rocketchat_streamer.js
rocketchat_streamer.js.map
rocketchat_theme.js
rocketchat_theme.js.map
rocketchat_tooltip.js
rocketchat_tutum.js
rocketchat_tutum.js.map
rocketchat_ui-account.js
rocketchat_ui-admin.js
rocketchat_ui-admin.js.map
rocketchat_ui-flextab.js
rocketchat_ui.js
rocketchat_ui.js.map
rocketchat_ui-login.js
rocketchat_ui-master.js
rocketchat_ui-master.js.map
rocketchat_ui-message.js
rocketchat_ui-sidenav.js
rocketchat_ui-vrecord.js
rocketchat_ui-vrecord.js.map
rocketchat_version.js
rocketchat_videobridge.js
rocketchat_videobridge.js.map
rocketchat_webrtc.js
rocketchat_webrtc.js.map
rocketchat_wordpress.js
rocketchat_wordpress.js.map

**Comment by yneha** [comment]
@danielo926 you are checking the built version of the code. Please check it in the development code in that you will find this folder.

**Comment by irdet2** [comment]
I am having the same issue on v.0.62.0 and cannot find the file "WebRTCClass.js".

What I have as a file that contains "rtc" is only the following: 

/Rocket.Chat/programs/server/packages/rocketchat_webrtc.js

but doesn't have any of the aforementioned lines.

Any ideas?
