### ISSUE TITLE
Global Moderator??

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#7019]
I'm trying to set moderators that have access to ALL channels.  Is there a setting for this?   It seems like my only option would be to set them as an Admin, but that would give way too many privileges.

Rocket.Chat Version:  0.53
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

**Comment by CzEMC** [comment]
Make a global group and assign them the certain privileges you need.

**Comment by Rohlik** [comment]
Exatly, you can create own roles in `/admin/permissions`.
