### ISSUE TITLE
Stuck login prosess using google account and github account

### ISSUE THREAD

**Issue by camagenta** [RocketChat/Rocket.Chat#702]
A few days a go, I'm registering on demo.rocket.chat using my google account using browser. Every thing is going well. I can post to general room, join channel and post in private channel.

Yesterday, I'm trying to download rocket chat android version. And All is well.

Today, I'm triying to log in using chrome browser. And then login prosess stuck in this close process.
The demo said, No matching login attempt found. Another time it said, 500 internal server error.

https://demo.rocket.chat/_oauth/google?close&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJtQjNuSW1nTUFCemFNMXFMSEhkQUpySWxsa2pjazRoSGJSV2ZHQTZmRkl3IiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&code=4/2IpiJRwlt2UwtGf2yKaXx0BZZmLwwI7pZ6tD-QqTbP4#

https://demo.rocket.chat/_oauth/github?close=&code=de823dff5da75c8d3987&state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJaSTVKX25QU1hLTkhILWZkWXRrRGdxTk1LYVZpRXRrVVJibTJ4dXdlb2d2IiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D

FYI, I'm alredy set my username : kuro
when I'm trying to log in using this username, it said. "User has no password set"

Anyone can give my solution to this problem???

**Comment by geekgonecrazy** [comment]
Going to try and make sure I fully understand the process.

* You logged in a few days ago with your Google Account in the browser.
* You downloaded the Android app and logged in with the same Google Account
* You logged in again in the browser with your same Google Account.

Correct?

Also made no changes to Rocket.Chat application settings in your Google Account?

I see you also linked to a github oauth url.  Did you add github to your account between first time and when it stopped working?

Just trying to get the full picture so we can try to reproduce it.

**Comment by camagenta** [comment]
Yes, just like that.

I don't change anything. Right now, I'm can use the android version, but not in the browser. Even, using chrome in my android device.

I'm yet linked github to my account, I'm just try to login using another method. But the result is same.

**Comment by geekgonecrazy** [comment]
Ok as far as github working.  It would have to have been associated with your account before it'd work.

We'll have to try and replicate this.

So in the mean time you should be able to goto "My Account->Profile" on your phone and set a password.  Then you'll be able to login with your username and password in the browser.

**Comment by camagenta** [comment]
Nah! It's works. 

I open my android apps, set the password as you suggested, then it's works.

Thx

**Comment by geekgonecrazy** [comment]
Ok good.  I'll go ahead an close this then.  We'll keep an eye out for issues related to this.
