### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by gregs007** [RocketChat/Rocket.Chat#7020]
**OS**
Mac OSX El Capitan 10.11.7
Rocket.Chat+ Version 2.8.0
Chrome Version 58.0.3029.110 (64-bit)
Firefox Version 53.0.2 (64-bit)

**RocketChat**
Version	0.56.0
OpLog	Enabled
OS Type	Linux
OS Arch	x64
OS Release	4.4.0-78-generic
Node version	v4.8.1

Permalinking a message via inline button doesn't copy link to clipboard. Tried with both ClipMenu clipboard manager as well as CopyClip. Unloading clipboard managers and using native clipboard doesn't work either.

The little green flag comes up in the upper right hand corner and says it's copied, but the data doesn't get copied to the clipboard.

Tried Electron client 2.8, FireFox and Chrome.

**Comment by jthomae1** [comment]
> The little green flag comes up in the upper right hand corner and says it's copied, but the data doesn't get copied to the clipboard.

We have the same behaviour since version update 0.56.0. 
We tried Rocket.Chat+ Client for MacOS, Chrome and Firefox.

**Comment by geekgonecrazy** [comment]
Seems none of the copy to clipboard functions work any more.

**Comment by mineZcash** [comment]
I am having the same issue on my server, all users on web browser cannot use Copy to clipboard function.

**Comment by localguru** [comment]
RocketChat: Version 0.56.0

Same here, not working with Firefox 53.0.2 or Rocket.Chat+ Version 2.8.0 on Linux

**Comment by designgurudotorg** [comment]
I'm still seeing this - in chrome on the web app and also on my mac in the desktop app.

q./

**Comment by geekgonecrazy** [comment]
@designgurudotorg it'll be in 0.57.0

**Comment by geekgonecrazy** [comment]
@matt-jarrett I just grabbed a perma link to clipboard from our community server that's running 0.57.0 and it worked flawlessly.

**Comment by mineZcash** [comment]
I can also confirm issue is fixed, thanks!

**Comment by designgurudotorg** [comment]
Looks good to me too! :)

**Comment by anktkr** [comment]
Mojave, 10.14.5, Safari Version 12.1.1 (14607.2.6.1.1) sees this issue again. 

So does Firefox 71.0 (64-bit)
