### ISSUE TITLE
[BUG] Login Expiration stoped working

### ISSUE THREAD

**Issue by teon** [RocketChat/Rocket.Chat#7021]
After upgrade from 0.53 to 0.55 (and 0.56 did not fix) login expiration stoped working on our instance.
Each time we close the Mac/Linux/iPhone client and open it again, we see the login page and a red error in right top corner: User Invalid.

We use LDAP as a user backed, but it was working for 2 years - something changed in 0.54/55 that made this error...

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.1 - x64

**Comment by ggazzo** [comment]
too old issue, but let me know if you faced a similar problem on the new versions, thanks
