### ISSUE TITLE
Can we remove canonical url?

### ISSUE THREAD

**Issue by anhld** [RocketChat/Rocket.Chat#703]
Is the canonical url ``` @line 17 in client/views/main.html ``` required to run Rocket.Chat? If not, can we remove it?

**Comment by geekgonecrazy** [comment]
Not required.  What's your thinking behind removal?

**Comment by anhld** [comment]
For SEO purpose. Also, can we make the site title, apple-mobile-web-app-title and application-name be configurable?

**Comment by geekgonecrazy** [comment]
So removed versus updated?  I don't know much about its effects on SEO. Any info you can provide there on that would be useful.

Also title is currently configurable its under administration->general->Site Name.

Unfortunately.. the way we are having to update it now is after it is delivered.  We don't currently have a way to update the markup before delivering it.  Seems to be a limitation of the template framework. It can't update anything in <head>

But this is planned

**Comment by anhld** [comment]
Search engines index the url in canonical tag instead of the url on the address bar. For example: i set up Rocket.Chat on ```mychatdomain.com```, but if i have ```demo.rocket.chat``` in the canonical tag, Google will index ```demo.rocket.chat``` instead of ```mychatdomain.com```.

I know the site title is configurable in the admin, but, as you mentioned, it's set by Javascript on the client side and wouldn't be seen by search engine bots. Is it possible to do it by using settings from a JSON on running ```meteor build```?

**Comment by geekgonecrazy** [comment]
That makes sense.  So removing it'll cause it to just index the current url?

Yeah so that's what we have to figure out.  Ideally the solution would be as easy as possible for someone to change in all deployment situations. Not just `meteor build` since not everyone will deploy this way.

**Comment by anhld** [comment]
Yup, that's correct. 

I see, i will try to find a way to do it then :)

**Comment by mitar** [comment]
You could just use `Meteor.absoluteUrl()` as a value for it?

**Comment by geekgonecrazy** [comment]
Due to the way meteor renders that wouldn't be updated until after the page had reached the client and the javascript was executed.  Which would defeat the purpose cause search bots would possibly read this before executing javascript.  Seems its better not to have it.

**Comment by mitar** [comment]
Ah, true.
