### ISSUE TITLE
Feature request: Let owners edit rooms without letting them change the name of the room

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#7032]
Rocket.Chat Version: 0.56.0

In my Company we decided to not let owners change the rooms' names. 
Unfortunately there is one way to do this. We switched off permissions for owners to `edit-room`, but we do not want this. Is there a possibility to let owners `edit-rooom`, but not let them change the name of rooms? If not, please add this option.

**Comment by marceloschmidt** [comment]
Too specific, probably not gonna happen.
