### ISSUE TITLE
Where is the code for the rocket.chat web app?

### ISSUE THREAD

**Issue by BFush** [RocketChat/Rocket.Chat#7034]
Where is the code for the rocket.chat web app? 
I am specifically looking for the code of the front page rocket.chat

**Comment by ellisgl** [comment]
Everything gets compiled down to /opt/Rocket.Chat/programs/web.browser

**Comment by graywolf336** [comment]
It's all here in this repository, more specially [the packages folder](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages).
