### ISSUE TITLE
Snap: set bind interface

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#7036]
Need to allow binding to 127.0.0.1 so port 3000 won't be accessible from the outside, only via reverse proxy

**Comment by geekgonecrazy** [comment]
Related #5311

**Comment by nickbroon** [comment]
:+1:

**Comment by r-carroll** [comment]
Was this ever resolved? I am still seeing 
`
error: cannot perform the following tasks:
- Run configure hook of "rocketchat-server" snap (snap "rocketchat-server" has n                                                                                                                                                             o "configure" hook)
`
Running server version: `0.65.2` on a pi using snap

**Comment by geekgonecrazy** [comment]
Snaps we are working to get updated to latest changes.  Once they are you should be able to

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#snaps See bottom to FAQ questions.

Can set either PORT=ip:port. Or via environment variables use BIND_IP=iptobind

We will investigate setting bind_ip via the config also

**Comment by debdutdeb** [comment]
Available in the newer releases.
