### ISSUE TITLE
Rocket.Chat server killed with no info

### ISSUE THREAD

**Issue by jacobrayschwartz** [RocketChat/Rocket.Chat#7038]
Rocket.Chat Version: 0.56.0
Running Instances: Single
DB Replicaset OpLog:
Node Version: 4.2.6

Hey guys,

I'm trying to set up a test server to check out Rocket.Chat, but I'm running into an issue getting the server started. Once I run node main.js, the server begins to start up and then at random points, usually after 

Using GridFS for custom emoji storage

the application stops with the message "Killed". I can't find any logs to read and find the reason. Is there something I'm missing? I'm running on a digitalocean droplet.

Here's the console output:

root@osiris:/opt/rocket.chat# node main.js
Will load cache for users
1 records load from users
Will load cache for rocketchat_room
1 records load from rocketchat_room
Will load cache for rocketchat_subscription
0 records load from rocketchat_subscription
Will load cache for rocketchat_settings
485 records load from rocketchat_settings
Updating process.env.MAIL_URL
Will load cache for rocketchat_permissions
70 records load from rocketchat_permissions
Will load cache for rocketchat_roles
10 records load from rocketchat_roles
LocalStore: store created at
LocalStore: store created at
{"line":"147","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 93","time":{"$date":1495309073255},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Killed

Let me know if there's something else I can provide. Thanks!

**Comment by madguy02** [comment]
@geekgonecrazy

**Comment by k0nsl** [comment]
How much memory does the droplet have? It almost sounds like it was “OOM-killed”.

**Comment by geekgonecrazy** [comment]
Agreed this sounds like an oom issue.  How much ram do you have available before starting up Rocket.Chat?

**Comment by jacobrayschwartz** [comment]
@k0nsl @geekgonecrazy 
Ah, yes. I missed the ram on that droplet. It is too low per the requirements. I will test on another device. Thanks for the help! Is there any way we could get a more informative message for this type of error? Or is that something in Node itself?

**Comment by geekgonecrazy** [comment]
@jacobrayschwartz this one is kind of tough.  Technically Rocket.Chat all by its self can run with 512MB of RAM.  But if Mongo is there + OS level stuff then it doesn't truly have 512MB of RAM it has a whole lot less.

Its possible we could add a minimum memory check to the process start.  But after the process starts that memory usage is going to fluctuate.  So we could say needs 200MB to start.  But then once it starts it may actually need 210 and if you don't have that it'd crash again.

For sure move to a higher droplet.  But i'd recommend also enabling swap space.  This gives you a bit of a buffer just in case. https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by jacobrayschwartz** [comment]
@geekgonecrazy, definitely will try a higher droplet. 

I'm not super familiar with system level errors in Node, is there not a general OutOfMemory exception that Node will raise? I'm usually developing in the Java realm, even though you don't catch it in your application (typically) you can still see it logged to console/log4j etc. 

Not exactly a major issue, but it would make it faster to debug.

**Comment by geekgonecrazy** [comment]
You'll usually see an error along the lines of:
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
or
FATAL ERROR: JS Allocation failed - process out of memory

unless the kernel terminates because of memory concerns before nodejs runs out. 

But I think you can usually check dmesg and see the oom killer logs

**Comment by jacobrayschwartz** [comment]
Ah, didn't think to look at dmesg. Thanks guys!
