### ISSUE TITLE
[Feature Request] Threading messages

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#7041]
In Slack this feature is called "[Start a thread". ](https://api.slack.com/docs/message-threading)It is a very useful feature and I hope to see it in RocketChat, too.

**Comment by madguy02** [comment]
@rodrigok

**Comment by lucasvanhalst** [comment]
See #1112

**Comment by MartinSchoeler** [comment]
This is a duplicate of #1112

**Comment by xereda** [comment]
See https://rocket.chat/2019/05/13/rocket.chat-1-0/
:100:  :+1: :smile: :laughing:

**Comment by makhoff** [comment]
Hello.

When I delete thread message, all other sub-messages are moved to top.
If the author of thread wants to delete his 1st message, there are too much messages will be appeared in the channel.
