### ISSUE TITLE
File System

### ISSUE THREAD

**Issue by Vespei** [RocketChat/Rocket.Chat#7042]
I can't find any documents on how to make this work? I've tried making a folder /etc/files, made it permission 777. And It didn't work. :l

**Comment by sampaiodiego** [comment]
@Vespei what exactly are you trying to do? what didn't work?

**Comment by geekgonecrazy** [comment]
A few notes.  Make sure if you are using snaps that you use a path it has access to like: /var/snap/rocketchat-server/common/uploads

Feel free to re-open this ticket if you have additional information.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
