### ISSUE TITLE
Can't import large users.csv file 

### ISSUE THREAD

**Issue by sassi1990** [RocketChat/Rocket.Chat#7047]
Hello, 

I can't  import my users.csv file with a 3000 users in it, i have no errors "even in the log", the only thing is that when i click on "START IMPORTING" no thing happen.

It worked with the same file. but with only 5 users in it. 

I'm on the last version of RC, Node , etc.

**Comment by graywolf336** [comment]
When you try to import it, is your instance of rocket.chat responsive?
