### ISSUE TITLE
newChannel webhook/integration missing data

### ISSUE THREAD

**Issue by Huljo** [RocketChat/Rocket.Chat#7048]
Rocket.Chat Version: 0.56.0
Running Instances: Single
DB Replicaset OpLog:
Node Version: 4.2.6

When a webhook is triggered for 'newChannel', there is no additional information about the channel, only the webhook name. (maybe I missed something)

My webserver logs (receiving the event, expressjs)
````
console.log(req.body) // {} 
console.log(req.params) // { name: 'newchannel' }
````

I need the channel ID to be able to find it in the database.

**Comment by graywolf336** [comment]
Is this in the script or is this in the url which is being hit?

**Comment by Huljo** [comment]
Hey @graywolf336,
This is in an other server, the one that is being hit.

**Comment by graywolf336** [comment]
Rocket.Chat server or web server?

**Comment by Huljo** [comment]
Web server, not on Rocket.Chat side.
A simple Expressjs application: One route that run those 2 console.log when hit.

**Comment by Huljo** [comment]
There is the URL in the integration configuration (Rocket.Chat side) : 
http://localhost/myCustomWebServer/webhooks/newchannel
'newchannel' is available in req.params but there is no more information about the channel in req.body.

**Comment by Huljo** [comment]
I found the doc. Sorry for this oversight.
