### ISSUE TITLE
SAML setup problem?

### ISSUE THREAD

**Issue by allw1994** [RocketChat/Rocket.Chat#7050]
Having an issue setting up SAML with RC and custom iDP, currently all I can get rocketchat to do is throw a proxy error and not redirect away from the rc domain.

SAML settings;

Custom provider: my-app
custom entry point: https://mydomain.com/login
IDP SLO redirect: https://mydomain.com/logout
Custom Issuer: https://mydomain.com/_saml/metadata/my-app

Tried tracing with various saml tools and fiddle and there is no outgoing connections shown, just it trying to load a page https://mydomain.com/_saml/authorize/my-app/'this_changes_every_time' fails with a reason proxy error: error reading from remote server - rocket.chat is installed behind apache.

Help? any input greatly appreciated.

Rocket.Chat Version:  0.51.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.6.2

**Comment by localguru** [comment]
What does the apache error log say?

**Comment by allw1994** [comment]
the only line in the apache log which is worrying is:
request received from client GET /_saml/authorize/my-app/"this_changes_every_time" just like on the error.
everything else is normal stuff...

I should also mention that this is worrying because no part of my idp uses that url - and never will because of the way the iDP has to be setup.

**Comment by localguru** [comment]
Could you post the complete error log line please and your proxy config?

**Comment by allw1994** [comment]
`[Fri May 26 16:38:26.715814 2017] [core:trace5] [pid 12032] protocol.c(647): [client <my-client>] Request received from client: GET /_saml/authorize/<my-app>/WZhRRQmEKEZ8N4H5f HTTP/1.1`



`<IfModule mod_ssl.c>
<VirtualHost *:80>
ServerAdmin webmaster@<my-domain>
ServerName chat.<my-domain>
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
<VirtualHost *:443>

ServerAdmin webmaster@<my-domain>
ServerName chat.<my-domain>
ErrorLog /var/log/chat.<my-domain>_error.log
TransferLog /var/log/chat.<my-domain>_access.log
LogLevel info

SSLCertificateFile /etc/letsencrypt/live/www.mail.<my-domain>/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/www.mail.<my-domain>/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf

<Location />
        Order allow,deny
        Allow from all
</Location>

ProxyPreserveHost On
ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/

</VirtualHost>
</IfModule>`

**Comment by localguru** [comment]
Did you test the Apache config on https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy

**Comment by allw1994** [comment]
that's where the config came from in the first place...

**Comment by allw1994** [comment]
just tried it again using exactly what is on that page just for good measure and it is still failing

**Comment by allw1994** [comment]
Just updated to RC 0.56.0 still no change

**Comment by geekgonecrazy** [comment]
Please feel free to reach out via our [forum](https://forums.rocket.chat) or our [community server](https://open.rocket.chat) to discuss.

From the looks this is support, if we narrow it down to a bug please open a new issue.  But to keep our issue log for bugs and planned features, I'm going to go ahead and close
