### ISSUE TITLE
Strange lines showing up throughout the layout in random places

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#7051]
Rocket.Chat Version: 0.56
Running Instances: 1
DB Replicaset OpLog:
Node Version:

Constantly getting these little lines throughout the layout.   They go away sometimes when the page is refreshed but other times remain.

I have seen it on the rocketchat demo as well.

Here is a screenshot of some of them. (this one showed up beside the userlist)

<img width="80" alt="screen shot 2017-05-22 at 9 04 05 pm" src="https://cloud.githubusercontent.com/assets/24284360/26334342/64386ec2-3f32-11e7-86a6-1cdb4f91fd33.png">

**Comment by MartinSchoeler** [comment]
@WebSavvyGuy  These are the locations of mentions in the channel ( like '@all' or '@here'). If you scroll to the lines you will probably see either someone mentioning you or a '@all' mention. Thanks for the feedback!
