### ISSUE TITLE
How can I use aggregate of mongo?

### ISSUE THREAD

**Issue by Dogyunjeong** [RocketChat/Rocket.Chat#7056]
Rocket.Chat Version: 0.55.1
Running Instances: 
DB Replicaset OpLog:
Node Version: 6.10.2

Hello.
  I want to get users data which is sorted by calculated factor with its properties. So that, I could use mongodb aggregate pipelines. But, the 'RocketChat.models.Users.aggregate' isn't function. 
  How should I do?

**Comment by Dogyunjeong** [comment]
I solved problem with 'RocketChat.models.Users._db.model.aggregate'

**Comment by nitinjiniguru** [comment]
I am facing same problem so my i know  

> I solved problem with 'RocketChat.models.Users._db.model.aggregate'


what _db.model mean in your answer ??

as i am also facing the same problem using your solution

Thanks

**Comment by Dogyunjeong** [comment]
You may can see models of rocketchat.  I guess rocket chat inherit the mongo connnector and put into as RocketChat.models. 
RocketChat also allow to use mongo connectro which is inherited.  You can access it with RocketChat.models[your target]._db.model[you could use  aggregate,find or etc].
For example, if I want to use user model aggregate. It sould be RocketChat.models.Users._db.model.aggregate().

Actually there is another way to reach to inherited mogo connector.  I will check and leave comment later.

**Comment by nitinjiniguru** [comment]
@Dogyunjeong  I have RocketChat.models.Users but what should _db??

and model??

if i directly apply RocketChat.models.Users._db.model.aggregate() still it gives same error

thanks

**Comment by Dogyunjeong** [comment]
I have no idea about it. You might can search about mini mongo aggregate.
