### ISSUE TITLE
Smooch.io integration?

### ISSUE THREAD

**Issue by marbetschar** [RocketChat/Rocket.Chat#7057]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=45481510)](https://www.bountysource.com/issues/45481510-smooch-io-integration?utm_source=45481510&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Integration of the Smooch.io into Rocket.Chat+. This provides access to further communication Channels through the Smooch.io API.

**Comment by graywolf336** [comment]
We would need someone who knows their API and then an action plan to actually integrate it..

**Comment by Prakharsvnit** [comment]
@marbetschar I am working on this issue, can you explain more what do you want with this integration.

> I haven't worked on any integrations before but I'm interested in taking this forward

**Comment by marbetschar** [comment]
@Prakharsvnit awesome!! Basically I was thinking of an integration which behaves quite similar to the one Smooch already provides for Slack: https://app.smooch.io/integrations/slack

**Comment by graywolf336** [comment]
@Prakharsvnit how goes the integration?

**Comment by marbetschar** [comment]
@Prakharsvnit any progress in this issue? Would really love to get this done. Maybe I can help in any way?

**Comment by Prakharsvnit** [comment]
@marbetschar Sorry for negligence,got busy in some work.I started some work but left it incomplete.I will restart after a week.

**Comment by marbetschar** [comment]
@Prakharsvnit nevermind, we all get busy from time to time :) Glad you'll give this another try! Just ping me if I can help in any way.

**Comment by JannikZed** [comment]
Smooch.io would make a much better Livechat than the rocket.chat integrated one!! That would even give you the possibility to answer your customers via SMS, Facebook Messenger etc.. from one single pane of glass! 
AWESOME

**Comment by CyrilPepito** [comment]
Hello folks,
I stumbled upon your issue while browsing Github, have you heard of [Broid](www.broid.ai)?
We offer a web messenger for websites that you can plug with any other messaging apps like Slack with our API.
Basically you can use Broid's API to converse on 20+ messaging channels (including that web messenger) using your favorite app to manager those conversations.

Also open source -> [Github repo](https://github.com/broidHQ/integrations)

Hope it helps!

**Comment by JannikZed** [comment]
No rocketchat integration, so where's the point?

**Comment by tezukzai** [comment]
Is anybody working on an integration with smooch.io?

**Comment by marbetschar** [comment]
@tezukzai I don‘t think so unfortunately. I don‘t have time either. Highly appreciate if you want to give this a shot though :)

**Comment by tezukzai** [comment]
@marbetschar non-developer unfortunately 😞 , but will be happy to add to a bounty for it if anybody wants to work on it!

**Comment by marbetschar** [comment]
@all seems like we may unltimately need the Rocket.Chat / Smooch integration; and maybe I can work on this (not sure yet, have to do further clarification on internal needs first).

Who's willing to help in any way to get this done? @graywolf336, @JannikZed, @tezukzai is this still a need for you?

**Comment by JannikZed** [comment]
Hi @marbetschar. It's still a need of us. We have on the long-term plan the idea to use smooch on customers websites with rocket.chat & CRM backend for live chat. I never developed any rocket.chat feature & just know smooch and rocket chat from the admin perspective. The smooch api itself is well documented.

**Comment by marbetschar** [comment]
https://www.bountysource.com/issues/45481510-smooch-io-integration

**Comment by rterwedo** [comment]
@marbetschar How much do you think would be needed in the bounty to push this forward?  I am working on getting a small prototyping budget approve and would like to add this to the list.

**Comment by marbetschar** [comment]
@rterwedo unfortunately RocketChat and Smooch are no longer part of my stack. So this issue does no longer serve a priority on my end.

Can't tell what would be an appropriate bounty for this either - the higher the bounty, the higher the chance it actually gets done. So I think it all comes down to a "how much is it worth for you" question.

**Comment by Sing-Li** [comment]
@marbetschar   Thanks for your valuable input.  If you don't mind me asking, what has replaced Rocket.Chat on your stack?    🤔

**Comment by engelgabriel** [comment]
Rocket.Chat now provides bridge app directly to most Customer Channels and we will continue to build our own bridges in the future. Smooch is not part of Zendesk.
