### ISSUE TITLE
Admin view User E-mail Address

### ISSUE THREAD

**Issue by jonathanhartman** [RocketChat/Rocket.Chat#706]
I would like to be able to view a user's e-mail address in the Users page.

I would also like to be able to send new users customized welcome e-mails when they sign up.

Simply being able to view a user's e-mail address in the Users page will suffice though, as setting up a customized e-mail system will likely be a more challenging feature to implement.

Thanks,
Jonathan

**Comment by AdrianoCahete** [comment]
> I would like to be able to view a user's e-mail address in the Users page.

As requested in #692 "Ability to see complete user information"

**Comment by geekgonecrazy** [comment]
Only difference is some info will probably be chosen to be hidden by the user.  But admin will be able to see the info regardless.

But for sure related.

**Comment by marceloschmidt** [comment]
Admins can already view user information when they click a username.

**Comment by engelgabriel** [comment]
Admin can already see all info of any user on the right nav when they click on the username.

![image](https://cloud.githubusercontent.com/assets/1000217/9798310/947457a8-57d6-11e5-9894-b114a445803b.png)
