### ISSUE TITLE
Forgot password doesn't work anymore

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7063]
Pressing the 'Reset password" button after entering your email address does nothing, it only changes the button's text to "Please wait". If the account didn't exist it continues and shows the alert with the text "if this account exists an email will be sent" or something similar.

Rocket.Chat Version: 362ac8e
Running Instances: 1
DB Replicaset OpLog: true
Node Version: (from docker image)

**Comment by localguru** [comment]
What does the log say? Is there a connect to the mail server?

**Comment by lucasvanhalst** [comment]
The only log is of the method being called on the server, but that's it. Nothing more.

**Comment by MartinSchoeler** [comment]
@lucasvanhalst I couldnt reproduce this on the latest develop branch,  and I think the user id is null because it didnt find a user with that email. This can be seen here https://github.com/RocketChat/Rocket.Chat/blob/a2b4564d472d1899d66426a450cb25dbe7b5f278/server/methods/sendForgotPasswordEmail.js#L7

**Comment by lucasvanhalst** [comment]
It actually looks like the email can't be send anymore. I was just using a google account and google's SMTP service but it looks like it's not working anymore. So perhaps all that's needed is logging an error in the logs that the mail couldn't be sent.

**Comment by lucasvanhalst** [comment]
I've fixed this by changing the SMTP settings to use port 587 (TLS) instead of 465(SSL) and sending emails works again. Strange why it suddenly stopped working.
