### ISSUE TITLE
Image previews broken

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7064]
Seems like the image previews aren't working anymore on the develop branch. Works fine on 0.56

Rocket.Chat Version: 362ac8ea1800b5fa34da19e1972f398fd7c562b2
Running Instances: 1
DB Replicaset OpLog: true

**Comment by MartinSchoeler** [comment]
Confirmed on develop, but working on demo

**Comment by geekgonecrazy** [comment]
#7208 fixes this.

**Comment by lucasvanhalst** [comment]
Fixed by #7208
