### ISSUE TITLE
nginx: a lot warning "an upstream response is buffered to a temporary file"

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7067]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: v4.5.0

I see a lot of "an upstream response is buffered to a temporary file" warnings in my nginx error log:

``
2017/05/23 21:16:24 [warn] 22012#22012: *13037 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/8/20/0000000208 while reading upstream, client: x.x.x.x, server: rocketchat.mydomain.de, request: "GET /file-upload/TnF2iNZdweGKThuAs/Video%20record.webm HTTP/2.0", upstream: "http://127.0.0.1:3000/file-upload/TnF2iNZdweGKThuAs/Video%20record.webm", host: "rocketchat.mydomain.de", referrer: "https://rocketchat.mydomain.de/group/test"
``

The sever is quite idle so it should be not an performance problem. Any ideas?

Ciao!
Marcus

**Comment by geekgonecrazy** [comment]
I think this is an nginx issue.  It just has to do with how it proxies.  Maybe take a look at: https://serverfault.com/questions/587386/an-upstream-response-is-buffered-to-a-temporary-file#587432

**Comment by localguru** [comment]
I see. Are the any recommended values how to configure the buffers to work best with RC?

**Comment by geekgonecrazy** [comment]
@localguru usually the default values work just fine.  This is actually the first ticket of this sort i've seen.

**Comment by thanhle-phd** [comment]
I have seen this warning lasting for years. the only solution is to set the following response header:

X-Accel-Buffering: no
