### ISSUE TITLE
"Invalid attempt to destructure non-iterable instance" exception while scrolling content in the cordova app.

### ISSUE THREAD

**Issue by flaviogrossi** [RocketChat/Rocket.Chat#7075]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: 4.8.2 - x64

After [this change](https://github.com/RocketChat/Rocket.Chat/commit/a69c69b6452d8ea3f6b8305aa2a0d2ee844a04f9#diff-e7c838650739eb4cc3317679e1881c6dR187), scrolling the main content in the cordova app raises the following exception `Invalid attempt to destructure non-iterable instance`.

This is caused by the TouchList object not being iterable and the exception is raised by [this line of code](https://github.com/babel/babel/blob/d5aa6d3ff8c1acb98c46d2dd883c3649d9f2bd14/packages/babel-helpers/src/helpers.js#L520).

Changing the former line back to `const touch = e.originalEvent.touches[0];` fixes the problem.

**Comment by Hudell** [comment]
I'll close this since it is related to the old Cordova app. If still necessary, please open an issue on the old app's repository.
