### ISSUE TITLE
Adding links in incoming webhooks like in Slack not working

### ISSUE THREAD

**Issue by sleepy86** [RocketChat/Rocket.Chat#7079]
Adding links
To create a link in your text, enclose the URL in <> angle brackets. For example: payload={"text": "<https://slack.com>"} will post a clickable link to https://slack.com.

To display hyperlinked text instead of the actual URL, use the pipe character, as shown in this example:

{
    "text": "**<https://alert-system.com/alerts/1234|Click here>** for details!"
}

The text marked as bold will be displayed as is instead as just displaying "Click here" as link.

EDIT:
here is my concret sample:
{
  "attachments": [
    {
      "color": "good",
      "fields": [
        {
          "title": "Requested by",
          "value": "Normal Paulk",
          "short": true
        },
        {
          "title": "Duration",
          "value": "00:02:03",
          "short": true
        },
        {
          "title": "Build Definition",
          "value": "ConsumerAddressModule",
          "short": true
        }
      ],
      "pretext": "Build <<https://fabrikam-fiber-inc.visualstudio.com/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3|ConsumerAddressModule_20150407.2>> succeeded",
      "mrkdwn_in": [
        "pretext"
      ],
      "fallback": "Build ConsumerAddressModule_20150407.2 succeeded"
    }
  ]
}

That is the link:
**<<https://fabrikam-fiber-inc.visualstudio.com/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3|ConsumerAddressModule_20150407.2>>** 
But it is not correctly displayed as link with the text **ConsumerAddressModule_20150407.2**.

Rocket.Chat Version: 	0.56.0
Running Instances:  1
DB Replicaset OpLog: 
Node Version: v4.8.2

**Comment by graywolf336** [comment]
@rodrigok and @engelgabriel  Thoughts on this? We currently support the markdown style but not Slack's style.

**Comment by geekgonecrazy** [comment]
Is this a standard thats used anywhere other then slack? I never used slack, so i'm not used to this and looks very different to me :)

**Comment by sleepy86** [comment]
I had a deeper look at the issue. Rocket.Chat already supports slack like links. The problem here is that the markdown is in the field 'pretext', which seems to be handled different then the 'text' field. And this issue is already opened several times, so I'll close this one.
Thanks!
