### ISSUE TITLE
Country flags on users

### ISSUE THREAD

**Issue by RichOnPeers** [RocketChat/Rocket.Chat#708]
For running a world wide RocketChat community this could be appreciated.
Choose flag/country in account settings to be displayed before/after the name in chat.

**Comment by marceloschmidt** [comment]
That would require us to depend on geoip or asking user for their location. Maybe that could be an option under settings.

**Comment by geekgonecrazy** [comment]
Probably best to ask right?  From what i'm seeing a lot of people seem to like no external dependencies.

**Comment by marceloschmidt** [comment]
Duplicate of #419
