### ISSUE TITLE
Livechat: Fresher Look?

### ISSUE THREAD

**Issue by marbetschar** [RocketChat/Rocket.Chat#7089]
Can we get a fresher look for the Livechat...? The current one works very well, but unfortunately it feels a bit old fashioned. A design something like the one Smooch uses would be awesome!!

<img width="560" alt="bildschirmfoto 2017-05-25 um 14 02 57" src="https://cloud.githubusercontent.com/assets/392542/26449516/e7a1fc7a-4152-11e7-8b2c-9ed4e8fb2930.png">

**Comment by jszaszvari** [comment]
You can accomplish this through CSS overrides

**Comment by YaroslavOsetrov** [comment]
@JSzaszvari 

Hi John! Could you pls tell the easiest way to override CSS?
I found that the widget using css by this url - localhost/livechat/livechat.css
But whats the best way to make changes and where exactly this file located? 

I've tried with Settings -> Layout -> Custom CSS, but its not working

Thank you!

**Comment by sampaiodiego** [comment]
@YaroslavOsetrov I think what @JSzaszvari said was about overriding CSS on the website you embedding the livechat widget. you'll not be able to change the internal widget look though.

but I have good news for you all. we have already started working on the the new design of the livechat widget https://github.com/RocketChat/Rocket.Chat.Livechat 🎉

**Comment by MartinSchoeler** [comment]
@marbetschar we are developing a new client for livechat, please reopen this issue in it's [repository](https://github.com/RocketChat/Rocket.Chat.Livechat). Thanks!
