### ISSUE TITLE
SAML and Two Factor Auth doesn't work

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7099]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: 4.5

Activating Two Factor Auth doesn't work with SAML authentication. Two Factor Auth is ignored after login via SAML.

**Comment by sampaiodiego** [comment]
Right, currently 2FA does only work with regular password authentication.

do you think rocket.chat should ask for 2FA even if you're using an external authenticator?

**Comment by localguru** [comment]
Yes, I can't find any reasons why not combining LDAP or SAML with 2FA. E.g. my IdP doesn't offer 2FA, so why not activating it on RC side. See #6750 too.

**Comment by sampaiodiego** [comment]
ok.. so I'll close this in favor the older issue and make it clear we should add support for all external authenticators :wink:
