### ISSUE TITLE
Improve sound of new direct message

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#71]
##

**Comment by diomed** [comment]
http://www.soundjay.com/button/sounds/button-43.mp3

**Comment by joepie91** [comment]
I personally find both of those highly aggravating. The default notification sound should probably be more subtle (and only really apply for 'watched' channels, direct messages and highlights/mentions anyway).

Aside from that, the SoundJay sounds are very clearly *not* [OSI-compliant](http://opensource.org/osd-annotated). From their Terms of Use:

> You are allowed to use the sounds free of charge and royalty free in your projects (such as films, videos, games, presentations, animations, stage plays, radio plays, audio books, apps) be it for commercial or non-commercial purposes.

> But you are NOT allowed to

> - post the sounds (as sound effects or ringtones) on any website for others to download, copy or use
- use them as a raw material to create sound effects or ringtones that you will sell, distribute or offer for downloading
- sell or license the sounds (as sound effects or ringtones) to anyone else
- claim the sounds as yours
- link directly to individual sound files on our server
- distribute the sounds in apps or computer programs that are clearly sound related in nature (such as sound machine, funny sounds app, sound therapy app, ringtone maker, etc.). If you are developing such programs, contact us for licensing options.
- distribute the sounds in apps or computer programs that use the sounds as the program's sound resource library for other people's use (such as animation creator, video editing app, song maker software, ebook creator, etc.). If you are developing such programs, contact us for licensing options.
- use the sounds to create so-called 'video sound effects'. An example would be a video titled 'dog sound effect' that simply plays a dog sound effect.

This violates points 1, 3, 6 and 10. Rocket.Chat needs a properly licensed (set of) sound effects. Freesound.org has plenty of these.

Acceptable licenses would be CC0 and CC-BY (plus 'public domain'). Unacceptable licenses are CC-NC (violating point 6), and CC-ND (violating point 3), although I believe the latter isn't used on Freesound.

**Comment by engelgabriel** [comment]
Depends on #222
