### ISSUE TITLE
XSS in image preview

### ISSUE THREAD

**Issue by DerpgonCz** [RocketChat/Rocket.Chat#7106]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.5.0 x64

If you fill in image description with HTML, it shows that code to anyone who clicks on it and views the preview.

https://github.com/RocketChat/Rocket.Chat/blob/a2b4564d472d1899d66426a450cb25dbe7b5f278/packages/rocketchat-ui/client/views/app/photoswipe.js#L47

**Comment by ggazzo** [comment]
Hey, thanks for contribute. For security issues we have a guideline https://rocket.chat/docs/contributing/security (to not expose the problem). Actually this issue is already registered by another person in the "right" way, so I will close it.

**Comment by DerpgonCz** [comment]
@ggazzo Oh, I am sorry, will keep that in mind next time. Maybe you guys should add it to the default issue text as a warning.
