### ISSUE TITLE
logging with timestamp

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#7113]
Hello Devs.

Is it possible to persuade rocketchat to log with timestamps? Currently no timestamp is given which makes it rather difficult to read them.

thanks and cheers

**Comment by localguru** [comment]
Hi,

I use systemd to start RC and log in a separate logfile in syslog format, which sets time stamps:

https://rocket.chat/docs/installation/manual-installation/pm2-systemd-upstart

/etc/rsyslog.d/10-rocketchat.conf:
```
:syslogtag,contains,"rocketchat" /var/log/rocketchat.log
& stop
```

Ciao!

**Comment by rodrigok** [comment]
The timestamping of logs is something you could do in your system
