### ISSUE TITLE
add male ^ Female icon in user profile

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#7116]
i hop to get that future soon
add male and female icon in the user profile for each user

**Comment by localguru** [comment]
Good idea, but it should be optional; think about the possibility of transgender.

**Comment by ckiltolier** [comment]
If you add this kind of feature, you should add all of them : https://neuwritesd.files.wordpress.com/2015/05/1420041082350.png  ;)

**Comment by Nemra1** [comment]
@ckiltolier how to start ??

**Comment by ckiltolier** [comment]
@Nemra1 What do you mean ? If you wanna be the more inclusive you can, you may use all of theses logos. But you don't have to, depends of your objectives.

**Comment by jblobel** [comment]
In what case would that be a usefull information ?

**Comment by Lawri-van-Buel** [comment]
To be inclusive it's better to not have any symbol. It does not add any real information that is needed in a chat environment. And it would allow for discrimination if we did have them.

**Comment by Nemra1** [comment]
@Lawri-van-Buel  make it option with disable and enable

**Comment by Lawri-van-Buel** [comment]
I would recommend it to be disabled on default. This is a hornet eat we would want to keep out of.

**Comment by timkinnane** [comment]
I think the points raised against this concept are more valid than any rationale presented in favour of it.
We'll close this now but you can discuss it in the forum under [Feature Requests](https://forums.rocket.chat/c/feature-requests).
