### ISSUE TITLE
Deleted User Still Shows "unread message" Notification (Reopen)

### ISSUE THREAD

**Issue by rtroilo** [RocketChat/Rocket.Chat#7118]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
NodeJS Version: 4.8.1 - x64

Hello everybody,
I have the same problem as described in issue https://github.com/RocketChat/Rocket.Chat/issues/6739

I deleted a user, but some other user still have an unread message for this user in their sidebar. And if they try to open the direct chat, they get an error page with "no user with username, ...".

I tried to hit CTRL-ESC as mentioned in the closed issue, but with out any success. I don't know if this shortcut do any think at all. I get no response!
I also tried under Administration->Message-> "Clear cache now", but the problem is still there.

Is there is a way to clean this up, I tried to seek the in the mongo database for this deleted user. But without any success. Do you have any idea where this information is stored and how I get rid of it.

Thank you very much.

**Comment by MartinSchoeler** [comment]
@rtroilo apparently the shortcut was changed to `shift` + `esc` could you try that?

**Comment by rtroilo** [comment]
Hi Martin,
thank you for your quick response.  `shift`+`esc` worked. 
Thank you!
