### ISSUE TITLE
Rocket.chat oficial Page. | design

### ISSUE THREAD

**Issue by caioogata** [RocketChat/Rocket.Chat#7119]
Create a new page for the official https://rocket.chat

Bring more RocketChat identity 
Visual refinement
Font sizes/styles
Brand colors

New Header/interaction

++++

Visual references
https://github.com/features
attached:

![231967476](https://cloud.githubusercontent.com/assets/24613261/26587509/f1a010de-4528-11e7-8273-af3b43576318.png)

**Comment by MartinSchoeler** [comment]
I believe that this task was already done, can be seen in current rocket.chat's website.
