### ISSUE TITLE
Deep Service Integration like chatgrape.com

### ISSUE THREAD

**Issue by ProdigyMaster** [RocketChat/Rocket.Chat#712]
![](http://i.imgur.com/XX42La8.gif)
##

**Comment by geekgonecrazy** [comment]
This is pretty cool looking.  I do like the possibilities of including a link to an external item inline like this.

**Comment by engelgabriel** [comment]
This is really awesome! We need to allocate the time to do this.

**Comment by felixtosh** [comment]
Hi Guys,

keep up the awesome work :) 
If you ever plan on supporting internal search as well, a look at our indexapi.com page might be interesting. We are going to open source many of our search index integrations in the future and having a standardised logic would benefit everyone.

Cheers,

- Felix from [Grape](https://chatgrape.com)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by geekgonecrazy** [comment]
I think this is something that might be possible via rocket.chat apps.

Feel free to propose in detail on our [forums](https://forums.rocket.chat) for future consideration as a feature
