### ISSUE TITLE
data back up feature

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#7122]
Rocket.Chat Version: 0.56
Running Instances: 
DB Replicaset OpLog:
Node Version:

I am just wondering if RC in the near future will have the feature in admin section for backing up data, versus now we have to access mongodb to do that?

**Comment by rodrigok** [comment]
We don't have plans to allow database backup from rocket.chat interface, but we have plans to allow admins to export and restore data #758
