### ISSUE TITLE
Pinned message

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#7124]
As the admin, after i pinned the message, i cannot seem to modify that message any more, cannot delete, or edit, or unpin it. Is it true for admin pinned message?

**Comment by MartinSchoeler** [comment]
@jy2008 have you tried to edit/delete the original (not the one on the flexTab) pinned message? Or the cog button doesn’t even show?

**Comment by jy2008** [comment]
yes, i deleted original message, but pinned still there, i cannot do anything with the pinned

**Comment by MartinSchoeler** [comment]
@jy2008 just to be sure, are you talking about the pinned announcement ?
![screenshot from 2017-06-01 16-27-56](https://cloud.githubusercontent.com/assets/20868078/26697168/71ac5386-46e7-11e7-9bab-a092e525ac1b.png)
or the message on the pinned tab?

**Comment by jy2008** [comment]
Pinned message in channel, not in pinned tab

**Comment by geekgonecrazy** [comment]
@jy2008 ah!  Yes when you pin a message a new message is inserted into the channel with the message you pinned attached in the state that you pinned it.
