### ISSUE TITLE
Bot user creation and management view

### ISSUE THREAD

**Issue by Rmafive** [RocketChat/Rocket.Chat#7125]
Is it possible to add a new bot without assigning an email? For example, if I wanted a bot named JIRA, that bot doesn't have an associated email, but I can't create the bot user without one.
 
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.1

**Comment by geekgonecrazy** [comment]
Currently bot users are the exact same as full fledged users.  Currently new users require email address.  

Personally... I usually add my bot users making use of Gmail +addresses.  

Youremail+bot@gmail.com

**Comment by Rmafive** [comment]
Thanks for the update! The Gmail + addresses does seem like a good solution for now to avoid a bunch of random email addresses for the bots.

**Comment by geekgonecrazy** [comment]
:+1: I have 2-3 this way :grin:

**Comment by soundstorm** [comment]
I assigned a web hook to trigger on dms to the bot. You need to login first to stop mailing every dm, which is kind of annoying. A bot shouldn't have a mail and password, could also lead to security issues when using a password like "1234" (I know you shouldn't do this anyway, but as you need to enter anything and think "it's just a bot" you may enter an insecure combination).

**Comment by RickiWeb** [comment]
Hello!
@geekgonecrazy with this method the bot is still offline! are there any other solutions?

**Comment by geekgonecrazy** [comment]
if bot user is offline, then bot has not successfully connected.  Check username/password and connection strings.  Also this is off topic so try our community [#hubot](https://open.rocket.chat/channel/hubot) channel

**Comment by SeanPackham** [comment]
As mentioned by geekgonecrazy, bots are full users and need an email address. We won't be changing this in the short term.

**Comment by timkinnane** [comment]
I don't think this should be closed. Bots should not need an email, emailing them is just generating spam for notifications for their creators. There are some related discussions about how to create and manage bots and normal users separately, because bots don't need email validation or prompts to reset their password either. So it's not a default conclusion that bot fields are and always will be the same as normal users. I will manage this and think we should aim to resolve it but close #7785. Also related #3818.

**Comment by timkinnane** [comment]
Also related https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/25

**Comment by timkinnane** [comment]
Have put this on the Bots Project roadmap to evolve it. This isn't so much a new feature as a range of enhancements to both the user creation logic and the admin UX. It will also hopefully be progressed by the Rocket.Chat apps project and GSOC proposals. Once we have a unified vision for how to handle bot account creation in balance with a range of requirements, we can create distinct feature issues.

**Comment by timkinnane** [comment]
Drafting a spec for this feature on the bots roadmap (below).

## What is this?

A new admin view for creating bot users, allowing simpler provisioning. Would also list existing bot users, with some indication of their status. Could possibly add the ability to shutdown/restart bots and in future be more intelligently integrated with their platform / hosting.

## Why do it?

Bot user accounts within Rocket.Chat have different requirements to normal users. They don’t need email addresses, verification or self-assigned password resets. The flow for admins managing installations with multiple bots is quite unintuitive and could be much improved by this feature.

---

This is a feature request stub, details and requirements will be planned when it’s added to the roadmap. Please discuss if you have particular requirements in mind or a contribution to make.

**Comment by mikaelmello** [comment]
Related: #10832

**Comment by rodrigok** [comment]
We will have an option to create bots via apps https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/49
