### ISSUE TITLE
Allow User Profile Change without changing Name field

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7126]
Rocket.Chat Version: 0.56.0

Is there a way to set "Allow User Profile Change" to "true" but, not allowingto change the "Name" field? I'd like to add further optional custom fields to the user profile, which should be alterable by users. But the user should not be allowed to change the "Name" as this comes via SAML from the IdP.

**Comment by AmShaegar13** [comment]
See my issue #8576 and corresponding PR #8739.

**Comment by gdelavald** [comment]
It would be great to separate the permissions for avatar, email and name so admins can control what the user is able to edit in their profile.

**Comment by localguru** [comment]
Thanks for providing that feature.
