### ISSUE TITLE
Feature Request: notification groups

### ISSUE THREAD

**Issue by nathan-at-least** [RocketChat/Rocket.Chat#7127]
I am in a large community channel (w/ hundreds of participants), and I frequently want to send notifications to a subset of participants (about 8 or so). It's a lot of work to type the list each time. I eventually put that list into a file and I paste it in. I wish I could have Rocket Chat track that group for me.

**Comment by sampaiodiego** [comment]
you mean you want to mention a team or maybe starting a thread with only this few people?

**Comment by sampaiodiego** [comment]
closing as duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2192
