### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by kychanbi** [RocketChat/Rocket.Chat#7129]
When I checked out the demo page, I find that the language preference are wrong for Chinese(Hong Kong).
Hong Kong is using Traditional Chinese, same as Taiwan, but not simplified Chinese.

**Comment by MartinSchoeler** [comment]
Actually when you select the correct Chinese option (zh-HK) it reverts back to the simplified chinese(zh), it happens with the Taiwan chinese (zh-TW) option too

**Comment by MartinSchoeler** [comment]
@kychanbi I think [my PR](https://github.com/RocketChat/Rocket.Chat/pull/7190/files) will fix this issue.
Could you take a look in [this file](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/zh-HK.i18n.json) to see if the translations are correct?
Thanks for your feedback!

**Comment by kychanbi** [comment]
Here is a [ dropbox paper ](https://paper.dropbox.com/doc/Rocket.Chatpackagesrocketchat-i18ni18nzh-HK.i18n.json-J6z9e1IK6UGbYmbs5qhVZ) of my edited version.
I m a Hongkonger and i am glad to see this project consider zh(hk) as an individual language. I m willing to help if you need me. 
Actually written Chinese of Taiwan and Hong Kong are almost the same (Traditional Chinese), but Simplified Chinese is quite different from Hong Kong. You may consider develop HK version based on Taiwan Chinese.
