### ISSUE TITLE
Allow setting for UserPresence.awayTime, change default value to 5 sec

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#7130]
When working on the desktop, it takes 5 minutes, until you start receiving push notifications on your mobile. This is hard coded in client/startup/startup.js with
`UserPresence.awayTime = 300000;`
Our users are missing notifications when leaving the desk. You can not overrule the UserPresence.awayTime with setting your online status to "away" - it still takes five minutes.

We would like to have a config setting for UserPresence.awayTime and we recommend to set the default value to 3000 (= 5 sec.). 

The timer seems to start count down, when you are not having the Rocket.Chat browser tab in front or you are inactive on the desktop.

Rocket.Chat Version: 0.56
See also #7115 ,  #6988 and #1602#issuecomment-226559485

**Comment by sampaiodiego** [comment]
this is now configurable either on level or server level.
