### ISSUE TITLE
'The server http://xyz.com is not enabled for mobile apps'

### ISSUE THREAD

**Issue by niranjans** [RocketChat/Rocket.Chat#7132]
I've setup the LetsEncrypt certificates properly and configured Nginx following the RC documents (hosting on AWS). Everything works well on the desktop browser / Mac native app but when I try to connect to the server from the Android app, I just get an error of 

> The server http://xyz.com is not enabled for mobile apps

I've pulled the latest Rocket.Chat code without any customizations and still get the same error. 

I came across this [issue](https://github.com/RocketChat/Rocket.Chat/issues/5251) but in that case, the issue was resolved somehow randomly. I am not sure what else I can try in my case.

**Comment by geekgonecrazy** [comment]
which Android app?  Rocket.Chat or Rocket.Chat+?

**Comment by geekgonecrazy** [comment]
@niranjans also can you check to see what: http://{yourserver-here}/api/info gives you?

**Comment by geekgonecrazy** [comment]
For the record when starting via meteor you will need to do: `meteor --mobile-server=http://your-ip:3000`

**Comment by visur98** [comment]
getting the same issue i installed rocketchat by snap in ubuntu 16.04 LTS

**Comment by yann-gael** [comment]
Hi,
I have the same problem with:

{"version":"0.72.3","success":true}

What should I do?
Best,
Yann

**Comment by vl-code** [comment]
> Hi,
> I have the same problem with:
> 
> {"version":"0.72.3","success":true}
> 
> What should I do?
> Best,
> Yann

Hi! 
I also have the same version and problem.

**Comment by denis-taranenko-windmill** [comment]
> For the record when starting via meteor you will need to do: `meteor --mobile-server=http://your-ip:3000`

Sorry, but this solution didn't help. I started my server with this string and tried to connect from an android emulator through a native app and got the exception "The server http://... is not enabled for mobile apps."

**Comment by geekgonecrazy** [comment]
This advice is no longer valid with 1.0.3.

Make sure version is newer and web sockets are enabled and working

**Comment by denis-taranenko-windmill** [comment]
> This advice is no longer valid with 1.0.3.
> 
> Make sure version is newer and web sockets are enabled and working

Sorry for the stupid question, but how can I check is sockets are enabled and working?

**Comment by geekgonecrazy** [comment]
easiest way is to open browser to your server.  Then open developer console and goto network tab.  Then refresh.  If you see a lot of requests to xhr / xhr_send then websockets aren't working

**Comment by denis-taranenko-windmill** [comment]
@geekgonecrazy  Okay, I got you. How can I enable WebSockets, because I got an image like this: 
![Screen Shot 2019-05-23 at 11 46 11 AM](https://user-images.githubusercontent.com/49201591/58238884-bb9d1380-7d50-11e9-83af-6841ce563edf.png)

**Comment by sanishan** [comment]
Check websocket working or not

`curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: chat.yourdomain.com" -H "Origin: chat.yourdomain.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://chat.yourdomain.com/websocket`

Change

`chat.yourdomain.com` with your website URL.

**Comment by reetp** [comment]
> How can I enable WebSockets, because I got an image like this:

Check you webserver setup against the documentation. For further help ask in the forums or open.rocket.chat
