### ISSUE TITLE
Upgrade to nodejs 8

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#7133]
Hi folks,

Rocket.Chat uses nodejs 4.x. At least e.g. the [centos manual installation docs](https://rocket.chat/docs/installation/manual-installation/centos) do imply that.

As nodejs 4.x transitioned into maintenance (according to [nodejs LTS schedule](https://github.com/nodejs/LTS#lts-schedule1)) and is only supported in maintenance mode (= only critical bugs, critical security fixes) until April 2018 it might by wise to already transition to nodejs 8 (which is also the new LTS version).

Cheers
Thomas

**Comment by dmoldovan123** [comment]
+1

**Comment by oliver-bowman** [comment]
+ 1

**Comment by TwizzyDizzy** [comment]
Not meaning to poke, but is this on the agenda?

Cheers
Thomas

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/8715
