### ISSUE TITLE
Inconsistencies on groups.list API webservice

### ISSUE THREAD

**Issue by rafacamargo123** [RocketChat/Rocket.Chat#7134]
Rocket.Chat Version: 0.56.0
Running Instances: 4
DB Replicaset OpLog: yes
Node Version: v4.5.0

Our scenario:
Rocketchat using LDAP:
All LDAP settings default, except connection settings and:
Sync Data=TRUE
Sync User Avatar=FALSE
Merge existing users=TRUE

A user with username=rafael
A private group created by admin named group.a
rafael and 9 others users into group.a.

Steps:
1) query the groups.list webservice (/api/v1/groups.list) using user admin and note the users inside group.a
2) with the admin user, edit the username rafael to rafaels using the web client
3) query again the groups.list webservice using user admin and note the users inside group.a
4) log in to the webclient using rafael user and ldap password
5) query again the groups.list webservice using user admin and note the users inside group.a
6) list all users on the group by the web client

Results:
1) `"usernames": [ "celso", "ricardo", "alan", "orlando", "yuri", "rafael", "brunoc", "admin", "brunos", "antonio" ],`
2) username changed to 'rafaels'
3) `"usernames": [ "celso", "ricardo", "alan", "orlando", "rafaels", "rafael", "brunoc", "admin", "brunos", "antonio" ],` (yuri replaced by rafaels, and old rafael still appears)
4) username rafaels is merged again with LDAP, and is changed to rafael
5) `"usernames": [ "celso", "ricardo", "alan", "orlando", "rafael", "rafael", "brunoc", "admin", "brunos", "antonio" ],` (two rafael)
6) Users appears correctly (both rafael and yuri listed) on web client

This behavior with the webservice response happens with all other groups rafael belongs to. The webservice response becomes inconsistent, because one user is replaced by the "new" rafael, in this case, the user that vanished from the webservice response was yuri. When we did this same test with the user "alan", the user that vanished was "ricardo".
The webservice only show the correct users after restarting all nodejs nodes.
No issue found on the web interface.

**Comment by graywolf336** [comment]
This seems more like an issue with the ldap sync than with the rest api. If we're syncing changes from ldap, the admin should *not* be able to edit usernames in my honest opinion.

**Comment by rafacamargo123** [comment]
But if you go to the channel group.a on the web interface in any of the steps, all users appears correctly, with the correct username -- changed or synced.
In the REST API respose, one user is overriden by the new user. After step 2, yuri has disappeared from the REST response, even before the resync, when rafael login again.

**Comment by graywolf336** [comment]
Yes I realize that, but the rest api only returns what the server has and it does nothing special at all with the data except return it. Thus it's not the rest api and is instead something wrong with the data in the core of Rocket.Chat.
