### ISSUE TITLE
how to test codes changes without complete rebuilding bundle each time?

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7135]
I cloned Rocket.Chat from github and built a new bundle (meteor build --server https://localhost --directory /my/build/location). Now I'd like to change code my local git repo and test it without rebuilding a complete new bundle each time, which takes about minutes.

**Comment by MartinSchoeler** [comment]
@localguru For developing you can start the server in your localhost with the command `meteor`. It will detect changes to the code and restart the app automatically, its way faster than doing a complete rebuild (note that depending on your machine some packages still take a bit of time to build again, such as the i18n package)

**Comment by localguru** [comment]
So, it's for stable release just this?

git clone https://github.com/RocketChat/Rocket.Chat.git
git checkout master
cd Rocket.Chat
meteor npm start

**Comment by localguru** [comment]
Further starts with "meteor" after small codes changes take about 120 seconds. Is there a way to speed that up?

**Comment by whuber-work** [comment]
meteor detects code changes and restarts by itself, if there are just clientside changes the restart should be quick

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
