### ISSUE TITLE
Implement the built-in APP integration

### ISSUE THREAD

**Issue by thinkeridea** [RocketChat/Rocket.Chat#7138]
Sorry I ability is limited does not provide efficient code for this function, I think everyone use for a variety of application message for integration, and many do not beautiful (including official provided sample), and there are a lot of problems, a lot of people don't write js, even not a programmer, the bitterness put many people to give up this powerful tool.

I want to make an official can application integration of markets, when add the integration you just need to configure related integration, and don't have to see a pile of terrorist code, also can let more people to use and improve the work achievement.

I want to make an official can application integration of markets, when add the integration you just need to configure related integration, and don't have to see a pile of terrorist code, also can let more people to use and improve the work achievement.

If really achieve these I think I'll put yourself first gitlab integrated in a month, let more people see the beautiful gitlab prompt message.

**Comment by sampaiodiego** [comment]
you can write your own app now :tada: 

if that is not what you want, please let me know
