### ISSUE TITLE
How to easily add some text to the login screen

### ISSUE THREAD

**Issue by chainmueller** [RocketChat/Rocket.Chat#7139]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

RC is running with docker-compose

Hello,

is there a possibility to add some text to the login screen, espacially to the "login-card"? I am not really into JS. I just found the readonly files in "/app/bundle/programs/web.browser/" and in "/app/bundle/programs/web.cordova/".

And if there is a possibility will it survive an update? I guess not because a new docker container is created then.

Thanks in advance

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
