### ISSUE TITLE
Hiding rooms is confusing

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#714]
I just by accident hide a room. How can I unhide it? It seems that I have to wait for somebody to write something?

Also, if all my rooms get hidden (or even if I favorite them), the channel list says "You aren't part of any channel yet." This is not really true. I am part of channels, only they are hidden and/or favorited.

**Comment by geekgonecrazy** [comment]
Duplicate of #625

**Comment by mitar** [comment]
Opened #716 for the second sub-issue.
