### ISSUE TITLE
How to change the icon in Livechat

### ISSUE THREAD

**Issue by chainmueller** [RocketChat/Rocket.Chat#7140]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

RC is running with docker-compose

Hello,

how can I change the icon in the lower right corner of the livechat window?

thanks in advance

**Comment by rahul7471** [comment]
@chainmueller @sampaiodiego @MartinSchoeler Did you find any solution to the above issue.

My current issue: I get a rectangular bar for live chat on lower right on my web page. But I wanted it to change to something like chat button.

I can see "Appearance" option where I can change in preview option to chat Window or chat button.
But when i make it chat button, I am not able to see it as button.

Any help on this? urgently need a solution.

**Comment by sampaiodiego** [comment]
@rahul7471 you cannot change it the way you want.. you can only change its color and text at the moment.

@chainmueller which icon specifcally do you want to change?

**Comment by rahul7471** [comment]
@sampaiodiego thanks for quick reply.
I wanted to make this icon as chat button
![icon](https://user-images.githubusercontent.com/16912580/26880689-e07e77ce-4bb2-11e7-836e-d2d018b64cd5.png)

as chat button

**Comment by chainmueller** [comment]
@sampaiodiego thanks for your reply. We would love to change the Rocket.Chat logo at the bottom into ours.

**Comment by sampaiodiego** [comment]
@chainmueller the only way to change the "powered by logo" is editing the source code and building it from source.

if you would like to change the widget look and fool like @rahul7471 , that will be possible on the future.

**Comment by martman07** [comment]
> @chainmueller the only way to change the "powered by logo" is editing the source code and building it from source.

Do you know what file would need to be edited?

**Comment by martman07** [comment]
@sampaiodiego 

> @chainmueller the only way to change the "powered by logo" is editing the source code and building it from source.

Do you know what file needs to be edited?  we are running rocket chat on ubuntu 14.04 from a snap and can not seem to find the file.

**Comment by chainmueller** [comment]
@sampaiodiego I thought so. Thank you for your answer. 

@martman07 as @sampaiodiego mentioned, you cant change it in compiled state. You have to take the sourcecode, make your changes and build it from source.

Source Code:
https://github.com/RocketChat/Rocket.Chat 

And I think these are the two sourcefiles where the changes has to be made. Pls correct me if I am wrong:

https://github.com/RocketChat/Rocket.Chat/blob/744d25a6264c0daf3c3c357fc65754010c4fa476/packages/rocketchat-livechat/app/client/views/poweredBy.html
https://github.com/RocketChat/Rocket.Chat/blob/6ad93856d20720e219e808c824de11967ceffded/packages/rocketchat-livechat/app/client/stylesheets/main.less

**Comment by sampaiodiego** [comment]
that's right @chainmueller ..

I'll close the issue since it looks like resolved =)

**Comment by luckyrabbitllc** [comment]
I also wanted a Drift-style chat button. I was able to make it work with this css:

`
<style>
@media(max-width:991px) {
	[data-state="closed"],
	[data-state="opened"],
	.rocketchat-container,
	#rocketchat-iframe {
			display:none !important;
	}
}

[data-state="closed"] .rocketchat-container,
[data-state="closed"] #rocketchat-iframe{
	display:none;
}
[data-state="opened"] .rocketchat-container,
[data-state="opened"] #rocketchat-iframe{
	display:block;
}
[data-state="closed"] i, 
[data-state="opened"] i {
		padding: 15px !important;
    width: 50px !important;
    z-index: 999999999999999999999999999999 !important;
    display: block !important;
    height: 50px !important;
		}
[data-state="closed"]::before {
		font-family: FontAwesome !important;
    content: "\f086" !important;
    color: #fff !important;
    font-weight: 600;
    float: left;
    FONT-SIZE: 19PX !IMPORTANT;
    height: 50px;
    PADDING: 11px 15PX !important;
}
[data-state="closed"] #rocketchat-iframe {
		padding:25px;
}
[data-state="opened"] #rocketchat-iframe {
	display:inline-block;
}
[data-state="opened"]  {
	height:300px !important;
}
div[data-state="closed"],
div[data-state="closed"] 	#rocketchat-iframe,
div[data-state="closed"] 	.rocketchat-container  {
		width: 50px !important;
    height: 50px !important;
    position: fixed !important;
    border-radius: 25px !important;
    bottom: 25px !important;
		right: 25px !important;
		background:royalblue !important;
}
div[data-state="closed"]:hover #rocketchat-iframe, 
div[data-state="closed"]:hover, 
div[data-state="closed"]:hover .rocketchat-container {
		background:#0a7eff !important;
		transition:background 0.3s;
}

div[data-state="opened"],
div[data-state="opened"] 	#rocketchat-iframe,
div[data-state="opened"] 	.rocketchat-container  {
	display: block !important;
	visibility:visible;
}
</style>
`

and this JS, (I'm using jQuery, but it could be refactored for other frameworks easily)

`
<script>
$( document ).ready(function() {
			$(document).on("click", "[data-state=closed]" , function() {
            $(this).data('state', 'opened').attr('data-state', 'opened');
        });
});
</script>
`

**Comment by tim-soft** [comment]
Has there been any movement on the live chat widget customization front? 

Decoupling it's UI from rocket chat source seems pretty desirable

**Comment by sampaiodiego** [comment]
@tim-soft yes, we have plans to re-write the widget in react and with that add some more customizations. but this is for a mid-term milestone

**Comment by shahzad285** [comment]
Hi @startupengineIO, I used your css I was able to get the chat icon but its not like what you have it in the image, there is no chat image on the icon there is just a square box like below.

![image](https://user-images.githubusercontent.com/9222537/45474246-e01f0580-b756-11e8-85b9-79be7c6644e4.png)

Can you please help me out.
Thank you

**Comment by gkarmas** [comment]
> Hi @startupengineIO, I used your css I was able to get the chat icon but its not like what you have it in the image, there is no chat image on the icon there is just a square box like below.
> 
> ![image](https://user-images.githubusercontent.com/9222537/45474246-e01f0580-b756-11e8-85b9-79be7c6644e4.png)
> 
> Can you please help me out.
> Thank you

check the code, he's using Font Awesome. Check on their website how to install font awesome.

**Comment by abhiram595** [comment]
In the css @startupengineIO remove this
[data-state="closed"]::before {
font-family: FontAwesome !important;
content: "\f086" !important;
color: #fff !important;
font-weight: 600;
float: left;
FONT-SIZE: 19PX !IMPORTANT;
height: 50px;
PADDING: 11px 15PX !important;
}
 and add image of chat icon like this using content 
div[data-state="closed"],
div[data-state="closed"] #rocketchat-iframe,
div[data-state="closed"] .rocketchat-container {
content:url('../images/chat_box.png');
width: 50px !important;
height: 50px !important;
position: fixed !important;
border-radius: 25px !important;
bottom: 25px !important;
right: 25px !important;
background:white !important;
}

**Comment by shahzad285** [comment]
HI @abhiram595 @gkarmas  Thankyou for your response I was able to fix it as mentioned by Abhiram but I forgot to comment here. It will help others.

Thankyou

**Comment by stevenjwright** [comment]
@sampaiodiego hey, has there been any updates on this? :)

**Comment by sampaiodiego** [comment]
the new widget is live https://github.com/RocketChat/Rocket.Chat.Livechat

but there is no option to remove the logo.. @renatobecker might be able to provide more info if this is planned or not.

**Comment by renatobecker** [comment]
> @sampaiodiego hey, has there been any updates on this? :)

We're planning to make big changes/improvements to the `Livechat Appearance` feature in the short-term and `yes`, the ability to add company branding on the widget is part of the plan.

**Comment by Skjolbir** [comment]
> 
> 
> > @sampaiodiego hey, has there been any updates on this? :)
> 
> We're planning to make big changes/improvements to the `Livechat Appearance` feature in the short-term and **yes**, the ability to add company branding is part of the plan.

Any update yet?
I dont even mind changing the icon, just would love to put "live chat" under it so its more obviously a chat button. A lot of people wont recognise the rocketchat logo as a chat button.

**Comment by backspace420** [comment]
And It would be better to make add wysiwyg within the GUI so that we can create and custom our livechat. Just like what livehelperchat has.
