### ISSUE TITLE
How to hide the email information in livechat window?

### ISSUE THREAD

**Issue by chainmueller** [RocketChat/Rocket.Chat#7141]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

RC is running with docker-compose

Hello,

how can I hide the email adress in the livechat window when conversation starts? (<div class="info">)

![grafik](https://cloud.githubusercontent.com/assets/25984706/26670405/c86484f4-46b1-11e7-8dca-aa313f34e6ac.png)

thanks in advance

**Comment by sampaiodiego** [comment]
duplicated of #6612

**Comment by sampaiodiego** [comment]
@GetGeeks the status is closed :smiley: 

this feature was implemented by https://github.com/RocketChat/Rocket.Chat/pull/8149 and is available since `0.60.0` release :wink:
