### ISSUE TITLE
Can't access image in folder public/images with url

### ISSUE THREAD

**Issue by EzailRak** [RocketChat/Rocket.Chat#7142]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1 - x64

I am new on meteor.js and rocketchat, I have placed a myimg.png image in the "public/images" folder but I can't access it with the url localhost:3000/images/myimg.png. Someone can help me?

**Comment by EzailRak** [comment]
.

**Comment by EzailRak** [comment]
Hello!

**Comment by EzailRak** [comment]
Nobody can help me?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
