### ISSUE TITLE
# after IP address when try to recover password

### ISSUE THREAD

**Issue by Sabbathrade** [RocketChat/Rocket.Chat#7148]
Rocket.Chat Version:  0.56.0
Running Instances: 
DB Replicaset OpLog:
Node Version: 4.8.1 x64

Hello,

I installed RC from snap on Ubuntu 16.04 x64
when try to recover password is shows me link for recovering pass but with # after IP address, so RC returned me back to home

example

192.168.1.100:3000/#/reset-password/P-YIXmH7eqUzHnUUe2C6EL_Y-epxL7smKpVE0OPWHuI

When /# is deleted it is working fine

@pkgodara helped me in #support RC, but I just wanted to report this as possible bug

Cheers,
Radomir

**Comment by jszaszvari** [comment]
ROOT_URL environment variable is what populates that data

**Comment by geekgonecrazy** [comment]
hm... i'm not sure how this is happening.  As per: https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/sendForgotPasswordEmail.js#L23 this should be working.

**Comment by pkgodara** [comment]
It happened only first time, after that there was no `/#` in the link.

**Comment by geekgonecrazy** [comment]
@pkgodara so sounds like it was a fluke.  I'll go ahead and close this then.
