### ISSUE TITLE
avatar image accessible without login

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7149]
Rocket.Chat Version: 0.56.0

Hi,

why is a avatar image of an user accessible without login?

  https://demo.rocket.chat/avatar/username

Beside the fact, that it's a way to figure out user names, it's a privacy issue if it's not a public open server.

Ciao
Marcus

**Comment by MartinSchoeler** [comment]
The original issue about this was closed by mistake, reopened it, please continue the discussion there #3480. Thanks!
