### ISSUE TITLE
Style of home page content is unstyled

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#715]
Some default CSS should be applied to the home page content. Currently for example lists (`<ul></li>`) do not have bullet points.

**Comment by geekgonecrazy** [comment]
So problem here is actually that it is styled. Otherwise it'd show bullet points by default.  We'll need to figure out how to handle this..

**Comment by marceloschmidt** [comment]
@mitar what are you trying to accomplish?

**Comment by mitar** [comment]
Just have HTML content on the home page which renders normally (and preferably in theme with the rest of the system).

**Comment by marceloschmidt** [comment]
Do you mean content for Home Body? Can't you add `<style>` tag there?

![image](https://cloud.githubusercontent.com/assets/1986378/9921804/20a13a76-5cb8-11e5-9758-6235208c055a.png)

**Comment by mitar** [comment]
Yes. I can. And I did that. But the issue is that it would be great if there would be some defaults. Currently, what you get is pretty broken (like lists do not show bullet points).

I would argue that probably style of terms of use and home page should be the same. So some nice defaults, that links look the same across the project and so on.

**Comment by mitar** [comment]
And then I can use `<style>` tags (which BTW should not be outside `<head>` by the standard, but luckily browsers do respect them) to make some customizations. But I should not have to use `<style>` to even make things work in the first place.

**Comment by geekgonecrazy** [comment]
Can you list some specifics that make styling difficult? Obviously we need some css present to make defaults work and look good.  So unreasonable to just strip everything out.

**Comment by mitar** [comment]
Lists were in my case how I found this.

**Comment by mitar** [comment]
But also links have no styling. Which might be what we want.

**Comment by marceloschmidt** [comment]
Custom styling is possible via CSS under Administration / Layout
