### ISSUE TITLE
Clear history information?Automatic cleaning?

### ISSUE THREAD

**Issue by thinkeridea** [RocketChat/Rocket.Chat#7151]
I think there should be a clear message history, but I couldn't find it, don't know if I delete a message channel N days ago, I don't know how to clean up automatically, of course I hope is clear channel, some channel data need to be kept very valuable, and some of the channel information is timely, maybe after a few days have no meaning.

I don't want to delete the database information directly, that will lead to upload information is left.

**Comment by WebSavvyGuy** [comment]
Yes, tested a server running over 100 users and it kept crashing probably because the messages keep building up.   Would love to see this feature.

**Comment by MartinSchoeler** [comment]
duplicate of #2355
