### ISSUE TITLE
Bug: Message kills RocketChat

### ISSUE THREAD

**Issue by Zomono** [RocketChat/Rocket.Chat#7153]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.8.1

I found a message, which kills the Browser-Instance of RocketChat. If you submit the following message to some channel of your choice, some Javascript of RocketChat stucks in an infinit loop:
_Remove the first backslash_
```
\```
without smart tabs

t---function(first, 
t---t---t---.second) {
t---}

with smart tabs

t---function(first, 
t---.........second) {
t---}
```

After posting this message the corresponding channel is broken for all users, while other channels and chats are still fine. By submitting this message to all channels of a RockatChat-Server one can deny the whole service except for private messages.

**Comment by sampaiodiego** [comment]
this should have been fixed by https://github.com/RocketChat/Rocket.Chat/pull/6991

can you please try to update your rocket.chat and test it? you should try using our `develop` release.

**Comment by mottobug** [comment]
Is there an docker image tag that we can use for the development release? We are using docker for our rocketchat deployment.

**Comment by sampaiodiego** [comment]
yes you can use `rocketchat/rocket.chat:develop` image.

**Comment by mottobug** [comment]
We are running now 0.57.0-develop out of the docker image, bug is still present

**Comment by mottobug** [comment]
In addition we are getting bugs with smileys unter chat messages, we are doing a rollback

**Comment by mottobug** [comment]
...which is not possible, due to the following error:

Exception in callback of async function: Error: [Can't find migration version 94]

:-(

**Comment by mottobug** [comment]
Seems like every other rocketchat installation is vulnerable. 

You can check that in the #general channel on:

https://demo.rocket.chat/

which is now also dead.

**Comment by sampaiodiego** [comment]
you could remove the migration record on database (it should be safe to re-run the migrations again when you update rocket.chat on the future).

also do you mind opening a new issue about the smile bug?

**Comment by sampaiodiego** [comment]
I still was unable to reproduce it on the latest develop release. I've sent a message and everything looks fine:
![image](https://cloud.githubusercontent.com/assets/8591547/26727225/56fceec0-477c-11e7-9d02-16f7c3d59a25.png)

please don't post on demo server because it's not running the latest `develop` release.

**Comment by mottobug** [comment]
We are running the develop release from docker hub, version shows as 0.57.0-develop, i'm pasting the content above in a new chat and the browser immediately freezes until a timeout (chrome). This happens with Chrome, Firefox, Safari. The old chat which contains the messages postet with version 0.56.0 are also dead. The only way is to remove the chatroom which results in complete loss of data.

**Comment by sampaiodiego** [comment]
ok, I'm sorry, you're right.. the bug is still present on our `develop` docker tag.. looks like for some reason the image was built from a 14 days old code (instead of latest/current code)..

I'll fix the image and ask you to test again soon, ok?

**Comment by mottobug** [comment]
ok, thanks

**Comment by sampaiodiego** [comment]
@mottobug the `develop` docker image has been updated.. I've tested and the bug is definitely fixed..
