### ISSUE TITLE
Smiley author caption bug in current developer release

### ISSUE THREAD

**Issue by mottobug** [RocketChat/Rocket.Chat#7155]
Rocket.Chat Version: 0.57.0-develop
Running Instances: 1
DB Replicaset OpLog: no
Node Version: latest release

Every message thats tagged with a smiley (from somebody else) will show as if its your smiley. So you get descriptions like this

@myusername, @myusername, @myusername, @myusername, @myusername, @myusername, @myusername with :rofl:

This occours after an upgrade from 0.56.0 to 0.57.0-develop

**Comment by graywolf336** [comment]
Can you provide a screenshot?
