### ISSUE TITLE
Snap Caddy SSl servering on port 2015

### ISSUE THREAD

**Issue by wihodges** [RocketChat/Rocket.Chat#7156]
I followed Snap install with caddy proxy configuration for SSL.
RocketChat runs perfectly from either the server ip address, but couldn't get the site to load at domain name. After running "sudo systemctl status snap.rocketchat-server.rocketchat-caddy" I noticed it outputted the siteURL with :2015 port added on. Site renders with port number but trying to figure out how to run without.

Output of status
`● snap.rocketchat-server.rocketchat-caddy.service - Service for snap application rocketchat-server.rocketchat-caddy
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-caddy.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-06-02 18:03:46 UTC; 8s ago
 Main PID: 1319 (caddy)
    Tasks: 5
   Memory: 17.8M
      CPU: 414ms
   CGroup: /system.slice/snap.rocketchat-server.rocketchat-caddy.service
           └─1319 caddy -conf=/var/snap/rocketchat-server/653/Caddyfile -host=localhost:8080

Jun 02 18:03:46 ubuntu-rocketchat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-caddy.
Jun 02 18:03:46 ubuntu-rocketchat /usr/bin/snap[1319]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2.24]): older than "/usr/bin/snap" (2.25)
Jun 02 18:03:48 ubuntu-rocketchat snap[1319]: Activating privacy features... done.
Jun 02 18:03:48 ubuntu-rocketchat snap[1319]: https://xxx.xxx.com:2015
Jun 02 18:03:48 ubuntu-rocketchat snap[1319]: WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".`

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1 -x64

Side note, I'm running DO VPS server with 1gb of Ram

**Comment by geekgonecrazy** [comment]
Can you give us a peek at your Caddyfile?  Of course blank out domain like above.

**Comment by wihodges** [comment]
Caddyfile:
`xxx.xxxx.com
tls self_signed
proxy / localhost:3000 {
  websocket
  transparent
}
`
I tried with 
https:// before domain with restart as well, didn't seem to make a difference. 
I noticed a couple variations on the documentation page - https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl
Should it also port attached: xxx.xxx.com:8080 ?

**Comment by geekgonecrazy** [comment]
having something like:
```
xxx.xxxx.com {
  proxy / localhost:3000 { 
    websocket 
    transparent 
  }
}
```

of course if you want tls self_signed you can use.  But if you exclude of course caddy will take care of providing an ssl cert.

**Comment by wihodges** [comment]
That was easy! I feel like an idiot now, haha. 
Great work btw blown away with easy of installation via snap as well as the app itself. I've installed a lot of apps and none have been this easy minus the user error of course.

**Comment by geekgonecrazy** [comment]
Awesome!  Glad to hear.  We for sure love snaps for ease of install :)
