### ISSUE TITLE
Audio and Video Calls broken

### ISSUE THREAD

**Issue by JacobCZ** [RocketChat/Rocket.Chat#7161]
Rocket.Chat Version: ```0.57.0-develop (also tested on 0.56.0)```
Running Instances: ```1```
DB Replicaset OpLog: ```Enabled```
Node Version: ```v5.12.0```

When I enable WebRTC and try calling someone either directly or in a room, either audio or video, the call sometimes connects, but the audio almost never works, the controls on the page lock up and no buttons or other controls related to the call appear on the screen.

**Comment by MartinSchoeler** [comment]
@JacobCZ Do you see any errors in the browser console?

**Comment by JacobCZ** [comment]
@MartinSchoeler Yeah, this one:

```WebSocket connection to 'ws://domain.censored.sorry/sockjs/201/ygz9vogi/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500```

I suspect this might have something to do with the Apache reverse proxy, but then again, I've set it up exactly like in the documentation...

**Comment by JacobCZ** [comment]
Update: I've tried accessing the app directly (without the proxy) and the aforementioned error no longer shows. Howewer, calls still do not work, and I get the following error, when I click the call button...

```NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}```
