### ISSUE TITLE
Delete Direct Messages Rooms?

### ISSUE THREAD

**Issue by WebSavvyDude** [RocketChat/Rocket.Chat#7162]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog:
Node Version:

Delete Direct Message rooms command?

Is there a way to delete all the direct message rooms created in the database?   We have an active site using RC, and when we log into the Admin Panel > Rooms ....there are literally thousands of direct message rooms created so we want a way to purge these and delete them from the database and RC server.

**Comment by geesper** [comment]
It looks like there may be a way to do this through the api. What criteria are you looking for to delete these DM channels?

For example, are you hoping to delete all DM rooms for deactivated accounts? Ones that haven't had messages for 30 days?

**Comment by WebSavvyGuy** [comment]
@geesper 

Thanks for the reply.   I would be looking ideally for something we can control from the admin panel so we can pick and choose and it would be more useful to everyone.   But if not i would say to have them deleted for 1) once the user closes it   2) one that hasnt had messages for 2 days or so.

**Comment by waveyuk** [comment]
@WebSavvyGuy I too am looking for the same as you.  Don't want the server being littered with old, no longer used, DM's :)

**Comment by WebSavvyGuy** [comment]
Yes, i think alot of people would like this and if someone can share what to do, that would help a lot of people out.

**Comment by josephmiller2000** [comment]
Same here :) looking for this option to delete unwanted or un-used direct messages that are older than few days. We are not facebook to keep the whole conversation inside a single server. We need something to delete old messages and keep the server fast and active for realtime chatters.

**Comment by kgbm3** [comment]
o/ guys, just looking for a way to close (not hide!) a Direct Message on the Android 6.0 client. 

I had been directed here from #support but it seems that this is a different kind of thread; nevertheless, is this possible?.. 

Tap-and-hold produces the little "eye" icon to hide the Direct Message, however it has been opened by mistake - and it's not needed! :) 

Screenshot @https://image.ibb.co/myPmpk/Screenshot_20170725_233048.png

**Comment by TheMythPT** [comment]
Well, hope this helps someone.
on the DM:
```
Open Menu
Choose Room Info
Choose Edit
Choose Delete
```
And done!

**Comment by sampaiodiego** [comment]
we have a prune messages feature already, does that solves your issue? you can define for how long messages will be saved, and you can define different params for public channels, private channels and DMs

**Comment by Perflyst** [comment]
Prune messages can only be used as admin (or with special permission, but than this user can do this with any rooms even he is not owner of it).

There is no way to delete direct message rooms as normal user.

**Comment by sampaiodiego** [comment]
right @Perflyst .. the main issue though is asking how to do purge all DMs from a server. please feel free to open an issue request what you just described.

I'll be closing this one in the meantime.

**Comment by mano87** [comment]
Why is this post simply closed? Is there already a solution?

How can we ensure in the EU that DNs can be deleted by the respective user?

**Comment by nealhamiltonjr** [comment]
Is this a possibility? We need for users to delete their own direct messages and wipe the whole conversation from the server. They should be able to do this one at a time..like click on the hamburger icon and simple hit delete. Users that get a lot of dm/s should be a able to purge them in bulk. Additionally, admins/managers should be able to delete old stale dm/s from employees that have left the company. This is a requirement in government and other sensitive operations. The admin should be able to turn this feature on or off based on business requirements. This is one of the only features missing in rocket chat that is a business necessity.
