### ISSUE TITLE
Zapier Messages Won't Create a Notification

### ISSUE THREAD

**Issue by fuzunspm** [RocketChat/Rocket.Chat#7165]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: 
Node Version: v4.8.1

When i receive message from Zapier Trigger it won't send any notification or increment the unread counter. I believe this is the same for all webhook bots.

**Comment by graywolf336** [comment]
Is the connected account your own?

**Comment by fuzunspm** [comment]
Yes it's on my own local server. Integration works but no notifications or unread badge

**Comment by graywolf336** [comment]
And what was the account you connected to Zapier? If it was your account you use on a daily basis, you won't be getting notifications nor unread badges as it is actually your account posting the messages

**Comment by fuzunspm** [comment]
yes i missed that. issue should be closed

**Comment by graywolf336** [comment]
Awesome, thanks for following up 👍
