### ISSUE TITLE
Cordova Android app does not work when compiling Rocketchat

### ISSUE THREAD

**Issue by megamaced** [RocketChat/Rocket.Chat#7166]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Yes
Node Version: 4.8.2

Hi,

I have compiled Rocketchat like this;

```
zypper in npm4 nodejs4
npm install -g inherits n
/usr/local/bin/n lts
curl https://install.meteor.com/ | sh
cd Rocket.Chat-0.56.0/
meteor npm install
meteor add rocketchat:internal-hubot meteorhacks:kadira
meteor build ../rccompiled
```

I then move the compiled tar.gz onto the server, extract it and run

`cd /srv/www/rocketchat/programs/server`
`npm install`

When I start the Rocketchat service everything works apart from the mobile app Cordova. It downloads the files (117 files) and then just displays the 3 loading dots indefinitely.

If I download the official compiled Rocketchat .tgz from rocket.chat website and run that then Cordova works. 

If I do a diff of /srv/www/rocketchat/programs/web.cordova then I see two files which differ between my custom compile and the official build and they are the single .js file and the program.json which seems to reference the .js file. I have attached those here in the zip. If I overwrite those files with the official version files then Cordova also works but this seems hacky

[web.cordova.zip](https://github.com/RocketChat/Rocket.Chat/files/1052040/web.cordova.zip)

**Comment by rahul7471** [comment]
@megamaced Can you help me on this:
I have an android app built with cordova-ionic and I have a chat server deployed on ubuntu machine.
Now i want to integrate **live chat** into my android app. I am not able to finds, how to do that.
It would be great if you can help me in getting started.

I am able to integrate same live chat on my WebApp

**Comment by goiaba** [comment]
@megamaced We have the same problem here. Have you figured out how to solve it?

**Comment by megamaced** [comment]
@goiaba Not yet.

Still doing the workaround of copying the 8b30c08d68fc362b382342c0e204430d16399153.js and package.json from the official build

**Comment by geekgonecrazy** [comment]
This one hasn't received activity in a while.  Going to go ahead and close.
