### ISSUE TITLE
Send email notifications in bulk

### ISSUE THREAD

**Issue by tkambler** [RocketChat/Rocket.Chat#7167]
Feature Request:

Currently, when I am off-line and receive messages via Rocket.Chat, those messages are emailed to me individually. In other words, if someone sends me 10 messages while I'm off-line, I get 10 emails, which is pretty annoying.

Please consider sending these messages out in bulk increments of say... 10 minutes?

**Comment by localguru** [comment]
I like that idea +1

**Comment by pkgodara** [comment]
I fear, in that case, replying messages through emails might be difficult. Have anyone seen anything like that before? Both bulk notifications and reply individually through emails simultaneously? Let me take a look at that.

**Comment by sampaiodiego** [comment]
I think you're right @pkgodara .. there is no way to have both features.. but they are also different issues.

I'll close this in favor of #854 and #741 .. both related to bulk email notification
