### ISSUE TITLE
Configure SMTP server without username and password

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#717]
Currently SMTP server can be configured through web interface only if it uses username and password, but in our case we use Docker container and our network stack assures that the SMTP server is not open, so we do not use authentication.

The workaround is to configure `MAIL_URL` manually, which is not too hard with Docker, but still.

There should also be some hint that you have to restart your Docker/Meteor for this change to go in effect because MAIL_URL from web settings is configured only at startup.

**Comment by geekgonecrazy** [comment]
Related to #372

**Comment by sampaiodiego** [comment]
this is already done. probably by https://github.com/RocketChat/Rocket.Chat/commit/147ce2d626a37c462de8592c39d2d8ca54e4067e
