### ISSUE TITLE
Text in Info page can't be selected

### ISSUE THREAD

**Issue by jniederm** [RocketChat/Rocket.Chat#7170]
Text in Info page (`/admin/info`) can't be selected in Firefox 53.0.2. I would be nice to
* at least don't prevent users to select text on info page
* or better to also add a button "Copy version info" that would fill the clipboard with all necessary info to file a github issue.

Rocket.Chat Version: 0.56.0-rc.1, hash: 48efadb3e4b60e31a241a29ecbc3adcda4d3723b

**Comment by MartinSchoeler** [comment]
This issue was fixed on the latest version, please try it out. Thanks!
