### ISSUE TITLE
channel crash on message (attached)

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#7176]
Rocket.Chat Version:  current stable
Running Instances: 7
DB Replicaset OpLog: yes
Node Version:  v4.7.0

Crash observed on a special rocketchat message - database row attached. crashes client and browser. 

[channelcrasherrocketchat.txt](https://github.com/RocketChat/Rocket.Chat/files/1056372/channelcrasherrocketchat.txt)

**Comment by MartinSchoeler** [comment]
duplicate of #6814
