### ISSUE TITLE
issue with the tab name

### ISSUE THREAD

**Issue by pojoba02** [RocketChat/Rocket.Chat#7178]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by pojoba02** [comment]
hello, is there any way you can help me with editing the tab name in rocket.chat?
which folder?

**Comment by MartinSchoeler** [comment]
@pojoba02 This can be changed under Administration > General on the Site name setting:
![screenshot from 2017-06-07 10-12-58](https://user-images.githubusercontent.com/20868078/26880232-2757b2f8-4b6a-11e7-8e5d-ebe8d17dadf3.png)

**Comment by pojoba02** [comment]
Am having an issue with just a blue screen appearing on all the browser am
using
