### ISSUE TITLE
iOS Push Notifications Error 'Got error code 8 for token'

### ISSUE THREAD

**Issue by szluohua** [RocketChat/Rocket.Chat#7179]
Rocket.Chat Version: 0.54
Running Instances: cordova app
DB Replicaset OpLog:
Node Version: 4.7.3
``
![push](https://user-images.githubusercontent.com/18567056/26865148-072eb48a-4b8e-11e7-9e1f-bbea2cf96e01.png)
What is the reason for this?

**Comment by szluohua** [comment]
`function sendPush(service, token, options, tries = 0) {
	const data = {
		data: {
			token: token,
			options: options
		}
	};

	return HTTP.post(RocketChat.settings.get('Push_gateway') + `/push/${service}/send`, data, function(error, response) {
		if (response && response.statusCode === 406) {
			console.log('removing push token', token);
			Push.appCollection.remove({
				$or: [{
					'token.apn': token
				}, {
					'token.gcm': token
				}]
			});
			return;
		}

		if (!error) {
			return;
		}

		SystemLogger.error(`Error sending push to gateway (${tries} try) ->`, error);

		if (tries <= 6) {
			const milli = Math.pow(10, tries + 2);

			SystemLogger.log('Trying sending push to gateway again in', milli, 'milliseconds');

			return Meteor.setTimeout(function() {
				return sendPush(service, token, options, tries + 1);
			}, milli);
		}
	});
}`
I found the cause of the problem,** response.statusCode === 406**,and **token.apn** was deleted.So what is the reason that will cause cordova to return to 406?

**Comment by phamduc0810** [comment]
hi @szluohua , I have the same problem when custom rọcket chat code. Have you found the reason and resolved this issue? Could you please tell me how to fix this?
