### ISSUE TITLE
Hide absent people in HL auto-completion

### ISSUE THREAD

**Issue by Ulrar** [RocketChat/Rocket.Chat#7180]
Hi,

We've been using Rocket.Chat for a while now at work, and since the version that allows to display names instead of usernames, it's been pretty great.
The last thing that bothers me (a lot, I have to say) is when I'm trying to HL someone and for some reason the auto-completion suggests people that aren't even in that channel / group.

It'd be great for that auto-completion to only suggest people that are present.
Thanks

**Comment by MartinSchoeler** [comment]
@Ulrar This is a long discussed topic, please see #2588 and i will close this, since is a duplicate
