### ISSUE TITLE
Rocket.Chat crashing

### ISSUE THREAD

**Issue by WebSavvyDude** [RocketChat/Rocket.Chat#7183]
Rocket.Chat Version: 0.56
Running Instances: 
DB Replicaset OpLog:
Node Version:

We are running a few instances of Rocket Chat on one server (pretty good specs on this server) but as soon as the users hit lets say over 150 users, the Rocket Chat starts to run very slowly and becomes unresponsive.

The other instances of Rocket Chat running on the same server (but with less users) has no affect on them and are perfectly fine.   Only the one with the 150 users has a CPU load that spikes to 100%.

The server still has plenty of unused ram.

Leads me to believe that RC is not built to handle a large number of users at all.     File uploads turned off, even registrations turned off.

No apparent explanation as to why it does this.

**Comment by WebSavvyGuy** [comment]
@sampaiodiego if there is any help you need in terms of looking at our server while many users are online, please do not hesitate to ask.

**Comment by geekgonecrazy** [comment]
Couple of quick questions. 
1. Is Mongo in replicaset mode?
2. How are you deploying the instances?
3. Are you setting INSTANCE_IP environment variable?

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy 

Here is my admins reply:

Is Mongo in replicaset mode? 
No

How are you deploying the instances? 
By Uploading build manually and run it by node main.js after setting env. variable  Root_url, mongo and port


Are you setting INSTANCE_IP environment variable?
No

Please note:  My admin discovered something today about one of the directories running out of space (perhaps a misalocation of our hard drive space as this server has a large hard drive)

He mentioned something “the data path is running out of space." My mongo data path is /data/db/.

Do you think that is the issue?

**Comment by geekgonecrazy** [comment]
For multi-instances you should see a warning in the admin screen if you don't have replicaset mode.  Its needed for multiple instances.
> By Uploading build manually and run it by node main.js after setting env. variable Root_url, mongo and port

INSTANCE_IP shouldn't be needed then.

> He mentioned something “the data path is running out of space." My mongo data path is /data/db/.

Absolutely that would cause all kinds of performance issues.

But either way if you are using multiple instances you need mongo in replicaset mode or its not going to work properly.

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy 

Its weird cause i know what you are talking about the warning...i did see it before but for some reason it disappears after.

We have RC installed under different ports in different directories (like /home/server1,  /homeserver2, etc) So not sure if that still counts as multiple instances.

**Comment by geekgonecrazy** [comment]
our definition of multi-instances is more than one copy of Rocket.Chat running pointing to same database.  If they each have their own database then they are pretty much considered separate severs.

So yeah in your case i'd switch to replicaset.  I believe all of our installs instructions now recommend this: https://rocket.chat/docs if not please call it out.  Because we recommend it even for single instance rocket.chat servers.  But for multi-instance its required to run properly.

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy I dont believe our installs are pointing to the same database.    We actually have RC installed so that there are actually one Administrator for each installed instance.  I would need to check with my Admin on that.  

All i know is we have RC installed like 3 or 4 times on different domains.   Whether they point to the same database or not hmm....i always though it was different because we have one main Administrator for each install.   The rooms, users, are all seperate from each other also.

I need to double check on that point....

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy 

I can now confirm that we do not run multiple instances of RC on our server.  We actually run multiple installs of RC.  Each has its own domain and separate databases.

Would you suggest performance wise, that multiple instances OR separate RC installs would be better for performance?  (assuming sharing a database or having seperate databases would not matter for us)

**Comment by geekgonecrazy** [comment]
@WebSavvyGuy ok so for 150 actively connected and talking users we'd recommend 2 instances of Rocket.Chat running.  To do this first you will need to enable replicaset on mongo.  Then first up a second instance of rocket.chat for the same server.  In your load balancer just add it as a second host for that domain.  This should solve your issues.

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy

Yes i have run into issues installing that on a server with Apache as those instructions in your documentation is for nginx

I can get as far as the part where you have to use the upstream part ... thats only for nginx though

**Comment by geekgonecrazy** [comment]
@WebSavvyGuy You'll need to check out the cluster section of the apache docs: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html#cluster

**Comment by WebSavvyGuy** [comment]
Hi @geekgonecrazy 

Ive given up on Apache and moved to install it on Ubuntu with Nginx.

I still am starting to lag/server slow as the users go up and I think I will need a third instance of RC to increase performance.

Is this even possible?

**Comment by geekgonecrazy** [comment]
@WebSavvyGuy yes for sure possible.

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy That would be great.   Still having some issues with this whole Replica thing.  We had a few installations of RC on our server but when we set up this Replicaset its causing alot of weird issues including getting the UI from our other servers or not loading at all.    

Is there any way to contact you directly? (i.e email or skype)

Would love to get this up.  We have a very popular chat website and if any bugs are going to show up, our site will find it but we can't seem to get past the stage of even running smoothly at this point.

**Comment by geekgonecrazy** [comment]
Once you set up replicaset on the database make sure you are setting MONGO_OPLOG_URL on every server connected to the server.  

Something like:
```
MONGO_URL=mongodb://mongoaddress:27017/serverdatabase
MONGO_OPLOG_URL=mongodb://mongoaddress:27017/local
```

We and other members of the community are in the [#support channel](https://demo.rocket.chat/channel/support) some times during the day when we are available for more real time communication.

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy 

I can barely get to that support channel  (3 dots loading).   Not sure whats going on but even the demo rocket chat seems to be having issues from time to time.

**Comment by geekgonecrazy** [comment]
From the sound of it you switched your load balancer to point to both instances and didn't change the database.  So one refresh you hit the instance pointing to RC1's database.  Next refresh you hit the instance pointing to RC2's database.  So you still are basically running two different servers just randomly switching between them.

To combine them you will have to adjust the RC2 instance to be pointing to the database of RC1.  Then once you start you will actually have a multi-instance server.  You also at that point should be getting the same content etc between refreshes.

**Comment by WebSavvyGuy** [comment]
@geekgonecrazy 

Ok finallly got everything working in terms of replicaset (i think).   We have 4 instances and currently a few users in the chat room (not live yet) and its at 100% load.

So, now im totally lost as to what is going on.  Any ideas why i would be at 100% cpu load with very few users and 4 instances?

**Comment by sampaiodiego** [comment]
closing due inactivity
