### ISSUE TITLE
Push notifications in native Android/iOS apps with chat loaded in webview iframe

### ISSUE THREAD

**Issue by hborisov1** [RocketChat/Rocket.Chat#7185]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.8.3

I have two native mobile apps (Android and iOS) and one web application which have similar functionalities and share one and the same backend module. I want to have chat functionality implemented alongside the other functionalities. So I deployed Rocket.Chat server instance and both mobile and web applications can access it via iframe (on mobiles, the iframe is loaded in webview). 

Everything is working fairly well, the only problem is that I can not make the mobile push notifications to work with the chat. I have a project in Google Developer Console, I disable the default gateway, and I setup  the GCM API key and GCM Project number. 

I thing I am missing the part where the generated push notification token of the device is sent to Rocket.Chat and written in the "_raix_push_app_tokens" collection. How can I update the server with my device tokens?

I installed the Rocket.Chat app from Google Play and when I tried to send push notification using the default gateway, I successfully received the notification. But how can I integrate this app as part of my app?

**Comment by rafaelks** [comment]
@hborisov1 You'll have to change your apps to register the push token to the logged in user using our REST APIs or our RealTime API. 👍
