### ISSUE TITLE
Auth with user in LDAP

### ISSUE THREAD

**Issue by danymanya** [RocketChat/Rocket.Chat#7186]
Hello.
I've installed rocket chat server in Ubuntu 16.04 server, it's configure to work with ldap auth, but I've problems with that. The first time users can autenticate with "username" and "password", like in the ldap, but after the first time, users needs put the mail to login in rocket chat, otherwise, they can't login. 
I don't know how fix this, someone can help me?.
Thanks

**Comment by admin-crowd-iugo** [comment]
set your login field correctly e.g. cn
unique identifier field should be something like 
objectGUID,ibm-entryUUID,GUID,dominoUNID,nsuniqueId,uidNumber,uid
user data field map
{"cn":"name", "mail":"email"}

**Comment by danymanya** [comment]
This work for me.
