### ISSUE TITLE
How to embedded or iframe ROCKET CHAT in a website

### ISSUE THREAD

**Issue by josephmiller2000** [RocketChat/Rocket.Chat#7201]
Rocket.Chat Version: 0.56.0 
Running Instances: linux(centos)
DB Replicaset OpLog:Disabled
Node Version:4.5.0 - x64

I tried different iframe codes even CSS responsive codes too. Iframe works fine(perfect) for desktop version.

In mobile ( its not converting into ) mobile layout.. still sticking to the desktop layout.

Is there anyway to do this? if we can do this.. it might be very helpful for us to keep the chatters inside the same page and dont want to send them to new pop up link.

**Comment by MartinSchoeler** [comment]
Please see: https://rocket.chat/docs/developer-guides/iframe-integration/#iframe-integration for details about iframe integrations
----
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
