### ISSUE TITLE
can't update requirePasswordChange

### ISSUE THREAD

**Issue by karamata** [RocketChat/Rocket.Chat#7203]
Rocket.Chat Version: 0.55.1
Running Instances: ubuntu 14.04
DB Replicaset OpLog: 
Node Version:

when I create user by rest api, requirePasswordChange always true

I also update by rest api for field requirePasswordChange = false, it still not update as I want

is it a bug?

**Comment by graywolf336** [comment]
Guess I don't understand what you're saying...
