### ISSUE TITLE
Hide Favorites in leftnav if there are none

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#721]
Instead of saying "You haven't added any favorites yet." the entire block should be hidden if there are no favorites and then appear if there is 1+ favorites added... and disappear again if you remove all favorites.

**Comment by geekgonecrazy** [comment]
Very closely related to: #716

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/49d275482e97a9981c8b5e28e1dd01358c59b082
