### ISSUE TITLE
Bug: Old uploaded files are not accessible

### ISSUE THREAD

**Issue by Scream85** [RocketChat/Rocket.Chat#7213]
Dear Rocket.Chat dev team,

After the upgrade from 0.56.0 to 0.57.0-rc.1, I can't access the previously uploaded files. Newly uploaded files are working. Storage type is GridFS.
![image](https://user-images.githubusercontent.com/29313645/26992809-3a38f40a-4d58-11e7-8186-0ed39e4fa650.png)

![image](https://user-images.githubusercontent.com/29313645/26992669-9b5a0e28-4d57-11e7-9f57-0840d2e45f9c.png)

Thank you!

Rocket.Chat Version: 0.57.0-rc.1
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: v4.8.2

**Comment by lucasvanhalst** [comment]
Probably same issue as #7172

**Comment by adocampo** [comment]
Just upgraded from 1.0.3 to 1.3.2 (manual installation on Debian) and old files and avatars are gone. The files are on the File System, (I cannot find the setting where avatars are saved), but they return a 404.

After searching the github issues, it seems a very old problem, but I couldn't find a solution and the I see this issue still opened. Is there a way to solve it that I missed?

**Comment by geekgonecrazy** [comment]
if using a snap or docker image make sure you are using a path that will persist reboots.  Going to go ahead and close this one for age since no one else has added their problem here or upvoted
