### ISSUE TITLE
User level/Gender Option/Disable Private For VIP role users

### ISSUE THREAD

**Issue by josephmiller2000** [RocketChat/Rocket.Chat#7217]
Rocket.Chat Version: 0.56.0
Running Instances: 	1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

Hello team,

I have few suggestion and support question to modify.

1. Looking for gender option for users. ( a small male or female icon near their names ). Easy to identify male or female chatters in a 100 of live chatting chat rooms. ( a. male, b. female, c, no need or no gender ) options.

2.  We have special ROLE (VIP) this roles are only for females.( who are verified by chat admins or mods ). This role must have some customized or special option to block private conversation. ( i means guest or register your are not allowed to send private conversation messages to these role chatters ). But, if vip members want to chat with anyone(guest or reg user ). They can send private conversation message and then go on.

3. Admin/Mods/Vip/Reg User/Guest User ( colour userlevels ). Yes we have role tags, but it aint gonna be pretty. We need different colour usernames on chat name list.

4. Name list userlevel (sorting) - 
 a, top admin list
 b, mod list
 c, vip list
 d, reg user
 e, guest users

![snap_2017 06 10_04h22m10s_005_](https://user-images.githubusercontent.com/24210340/26997075-7438ebe2-4d94-11e7-8f0e-27841ee53a84.png)

If these settings and customization are possible to work it and fix, Then rocketchat will be #1 chatting platform for all in this world.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
