### ISSUE TITLE
SAML2 Login Succeeds, but login window doesn't close

### ISSUE THREAD

**Issue by mlbiam** [RocketChat/Rocket.Chat#7221]
Rocket.Chat Version:  0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

This is on a hosted instance.  I have SAML2 login configured, and it seems to let me login but the login popup window never closes.  Once I'm logged in, the session is open in both the login window AND the original window.  Its usable for the macOS app and the web client but the Android client never loads the profile.

**Comment by mlbiam** [comment]
I also tried the iOS app with the same results

**Comment by pierre-lehnen-rc** [comment]
The error reported on this issue was fixed at some point but the issue was left behind, so I'm closing it now.
