### ISSUE TITLE
Add advanced Piwik settings for sub domain support

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#7225]
In order to use one Piwik instance for tracking several sub domains (multiple Rocket.Chat instances), some advanced piwik settings have to be configureable. This kind of configuration should be part of the administration UI of Rocket.Chat.

Therefore 3 options should be configurable via Admin UI.

Prepend the site domain to the page title when tracking
`_paq.push(["setDocumentTitle", document.domain + "/" + document.title]);`
Track visitors across all subdomains
`_paq.push(["setCookieDomain", "*.your.domain.tld"]);`
In the 'Outlinks' report, hide clicks to known alias URLs
`_paq.push(["setDomains", ["*.your.domain.tld"]]);`

Rocket.Chat Version: 0.56

**Comment by graywolf336** [comment]
Feel free to add this functionality via a pull requeset :+1:

**Comment by ruKurz** [comment]
This issue is already resolved by https://github.com/RocketChat/Rocket.Chat/pull/7324
