### ISSUE TITLE
REST API: channels.info lists only online users?

### ISSUE THREAD

**Issue by pjotrek-b** [RocketChat/Rocket.Chat#7227]
I would need a list of all users registered in a given channel.

In the [Rocket.Chat's REST API documentation](https://rocket.chat/docs/developer-guides/rest-api/channels/info) I only found "channels.info" to provide a username list.

But that list only contains users that are *currently online* in that channel.
Is there any way to list offline users, too?
(Similar to the functionality in the web-GUI: "Show all" - vs "Show only online")

Thank you very much in advance :smile: 

> Rocket.Chat Version: v0.56.0
> Running Instances: 1
> DB Replicaset OpLog: Enabled
> Node Version: v4.8.1

**Comment by graywolf336** [comment]
No, I just verified it doesn't return only the online users it returns all of the users. Tested locally and only one user is online but I got all of the users in the channel.

**Comment by pjotrek-b** [comment]
Oh. Interesting.
Great to hear that it's possible. Now I have to figure out where my error is. :blush: 

Thanks for checking.
I'll go check my code. :disappointed: 

May I keep this issue open to post the solution when I find it?
