### ISSUE TITLE
direct messages received not displayed after login

### ISSUE THREAD

**Issue by homologus** [RocketChat/Rocket.Chat#723]
Hello,

I recently installed rocket.chat in my server and was trying it on my own with two accounts. I noticed that often when one person (A) is logged out and another person (B) sends a direct message, that message does not show up on A's screen after A logs in. The message is not lost, because I can clearly see it in mongodb dump, it somehow never shows up on A's account.

I can reproduce this behavior very consistently. Did anyone else notice something similar?

**Comment by engelgabriel** [comment]
can you give us the steps to reproduce?

**Comment by geekgonecrazy** [comment]
Unable to produce.. :(

1. I created two users userA and userB.  
2. I logged userB off.
3. I send a new message (none had been done before) from userA (still logged in) to userB (not logged in)
4. I logged userB back in.

Message was waiting for it. 

Did I miss any steps on this?

**Comment by homologus** [comment]
Let me investigate more, because it seems like the behavior is more complicated than what I described. 

Here are two screenshots and you can see the difference.

![missing2](https://cloud.githubusercontent.com/assets/3611756/9708613/56cb90f2-54d3-11e5-8bf7-89523fb3a7c5.PNG)
![missing1](https://cloud.githubusercontent.com/assets/3611756/9708614/56cc2bc0-54d3-11e5-99e2-0216e4e25b68.PNG)

However, when I press browser reload on the window, the missing messages update properly. So, it could be that the browser is not rendering the messages.

**Comment by rodrigok** [comment]
Seems that we don't reload the messages from opened rooms after login, you have the messages from before logout and after login. Probably the solution will be close all rooms in RoomManager on logout.

**Comment by homologus** [comment]
Thanks rodrigok.

**Comment by Sing-Li** [comment]
@homologus  - can you please see if the problem has been fixed.   

Might have been fixed by - https://github.com/RocketChat/Rocket.Chat/commit/e9d43e9a0bed8d0370b1a20747ad2b7e9649506f

**Comment by homologus** [comment]
Yes, it is. Thanks Sing-Li.
