### ISSUE TITLE
All the differentd browser show blue screen only with no login panel

### ISSUE THREAD

**Issue by pojoba02** [RocketChat/Rocket.Chat#7233]
Am having an issue with my login panel, it just show a blue screen without the login panel,

**Comment by mikeboltonca** [comment]
I had a similar issue that related to the iframe settings. Disable iframe in Administration > Accounts > iframe. If you're logged out and can't access the administrative settings page, you'll need to change the config file (sorry I can't tell you where).

**Comment by MartinSchoeler** [comment]
@pojoba02 could you give us more info on your Rocket.Chat version and what settings have you changed. Thanks!

**Comment by pojoba02** [comment]
Hi, I have 95 version and I think I change some settings on the permissions

On Jun 13, 2017 5:35 AM, "Martin Schoeler" <notifications@github.com> wrote:

@pojoba02 <https://github.com/pojoba02> could you give us more info on your
Rocket.Chat version and what settings have you changed. Thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/RocketChat/Rocket.Chat/issues/7233#issuecomment-308101545>,
or mute the thread

**Comment by glebtv** [comment]
Disabling Iframe integration worked for me, thanks!
