### ISSUE TITLE
Database Migration Problem between snap and meteor

### ISSUE THREAD

**Issue by mrzhuangda** [RocketChat/Rocket.Chat#7234]
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: V6.10.0

I was previously deploy the Rocket.Chat by snap,and all the chat record is in that version. Now i want to deploy it by meteor-up,and how can i migrate the data ? Any idea on how to fix this?

**Comment by geekgonecrazy** [comment]
run the command: `sudo rocketchat-server.backupdb` on the server with the snap.  It'll spit out a logs showing you where your data is.  Take that and restore it where ever your new database is.
