### ISSUE TITLE
Android File Share Connector Inoperable?

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7238]
Date of this post is 2017-06-13

Rocket.Chat Server v0.56
Server: Ubuntu 16.04 LTS Server with Snappy v2.25
Desktop application: RocketChat+ v2.7.0 running on Ubuntu MATE Desktop 16.04.2 LTS

Android Apps running on S4 Smartphone and S2 Tablet with Marshmallow 6.0
RocketChat+ Rated 3.6 is version 1.0.14 released 6/7/2017
RocketChat Rated 3.3 is version 2.5.0 released 12/22/2016

Update 2017-06-14
Only the hsare connector for RocketChat v2.5.0 released 12/22/2016 is installed on mobile devices. Share connector for RocketChat+ is not installed.  Is there a share connector component of RocketChat+ v1.0.14 released 6/7/2017 ?

Neither Android app receives Shared files from other Android applications.  The Slack share connector works perfectly to share files on the same phones and tablet.

Update: 2017-06-14
Attempts to share text in the carrier text messaging app through the Rocket share connector also inoperable. Slack share connector for exact same operation works perfectly.

Has this problem been identified?

**Comment by sweetsmoke** [comment]
Any news for this. Still no possibility to Share.
