### ISSUE TITLE
chat message can not show special characters

### ISSUE THREAD

**Issue by ZhaoVitapublic** [RocketChat/Rocket.Chat#7240]
We have a problem by sending chat message with special characters like _, * etc.
By sending messages, the markdown parser doesn't offer the escape opportunity to present some special character like _, etc..

For example , we want send a normal message with a word like "Bla_bla_123" in italic:

We expect to show as  
_Bla_bla_123_, 
but rocket chat shows the message like
_Bla_\_bla\_123\_ .

Reference see following code on https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-markdown/markdown.js line 31:
```
// Support _text_ to make italics
msg = msg.replace(/(^|&gt;|[ >*~`])\_([^\_\r\n]+)\_([<*~`]|\B|\b|$)/gm, '$1<span class="copyonly">_</span><em>$2</em><span class="copyonly">_</span>$3');
```

Is there any possibility to handle this problem?

**Comment by localguru** [comment]
Can confirm

```_Bla_bla_123,_``` becomes to _Bla_bla_123,__

**Comment by martinvonwittich** [comment]
Yes, I'm also missing a general way to escape all Markdown special characters. GitHub allows this by prefixing any special characters with a backslash. For example:

`_test_` becomes _test_
`\_test\_` becomes \_test\_
\\\`\\\`\\\` becomes \`\`\`

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #8989.

Cheers
Thomas
