### ISSUE TITLE
[BUG] posting messages via API as non member to private rooms or read only channels

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7241]
Rocket.Chat Version: 0.56.0, 0.57.3
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: 4.5

Using API it's possible as **non room member** to post messages to **any private room** (knowing room names provided ;) ). This is even possible if a private room is set to read only.

Beside that it's possible to post messages via API to any channel, which is set to read only.

**Comment by bbrauns** [comment]
Same here

**Comment by hard2er** [comment]
same here.

**Comment by localguru** [comment]
Still possible in 0.57.3
