### ISSUE TITLE
Problem with Android application

### ISSUE THREAD

**Issue by danymanya** [RocketChat/Rocket.Chat#7244]
Hi!, I've installed rocket chat server on Ubuntu 16.04 server, but when i try to connect from app on Android, the server give me a message, the message says: "waiting for server connection, trying again...".
Any ideas?

**Comment by localguru** [comment]
More infos. Firewall? Rocket.Chat logfiles? Can you connect via browser from your cell phone to Rocket.Chat?

**Comment by danymanya** [comment]
We don't have firewalls, with browsers Connecticut with out problems, maybe the app uses specific ports or specific configuration, I don't know.

**Comment by danymanya** [comment]
This is the view from the tablet I'm trying to connect, from browser I can connect with out problems.
Sorry for my english, is very basic.
![screenshot_20170614-113850](https://user-images.githubusercontent.com/5981676/27144287-9e161748-5107-11e7-82d9-d47af07a0637.png)

**Comment by JackNWeems** [comment]
Are you using SSL? I don't remember if the symptoms were exactly the same but when I first set up rocket chat I didn't have the intermediate certificates installed for Nginx and I saw something similar. I could connect using a web browser but the Android client would fail. Installing the intermediate certificates provided by my CA fixed the issue.

**Comment by Archer4l** [comment]
Try remove application and install again. Some ppl in my team had similar problem and reinstalled app help them.

**Comment by ToniIltanen** [comment]
1. Do you have SSL in use?
2. Did you use a reversy proxy, and if you did, did you also remember to forward Websockets?

An example reverse proxy for apache:

```
NameVirtualHost *:443
<VirtualHost *:443>
    ServerAdmin someone@yourdomain.com
    ServerName yourdomain.com
    SSLCertificateFile /etc/letsencrypt/live/yourdomain.com/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

<Location />
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3005/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3005/$1 [P,L]

ProxyPassReverse / http://localhost:3005/			
	
SSLCertificateChainFile /etc/letsencrypt/live/yoursite.com/chain.pem
</VirtualHost>
```

**Comment by rafaelks** [comment]
@danymanya I'm really sorry for the delay... is this issue still happening for you?

**Comment by danymanya** [comment]
@rafaelks not problem, this issue not happening now. With a fresh installation and new rules in my firewall solved that. Thanks a lot.

**Comment by rafaelks** [comment]
Amazing! Closing it for now 👍
