### ISSUE TITLE
Livechat widget takes over whole screen on mobile

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#7247]
For some reason my livechat widget works as expected if you open it before scrolling, after scrolling it takes over the whole screen and can't be closed?!

Anyone else experiencing this bug on mobile?  I've seen it on iOS Safari.

q./

**Comment by sampaiodiego** [comment]
I could not reproduce it.. do you have any additional information? maybe a gif or a video

**Comment by lpmop** [comment]
Hi, we have same problem when I open website and scroll it,  then open livechat window i see blank page - this is related with code https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/assets/rocket-livechat.js#L556 

When we set permanently set scrollPosition  to 0 work fine but after open livechat window all site is scroll to top. 
On Your website You use "new-livechat" what it is?

**Comment by renatobecker** [comment]
> Hi, we have same problem when I open website and scroll it, then open livechat window i see blank page - this is related with code https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/assets/rocket-livechat.js#L556
> 
> You can reproduce this bug on chrome - responsive mode (the last version of RC )
> 
> When we set permanently set scrollPosition to 0 work fine but after open livechat window all site is scroll to top.
> On Your website You use "new-livechat" what it is?

https://github.com/RocketChat/Rocket.Chat.Livechat

**Comment by mehmetalianil** [comment]
This is also too intrusive for me. 
If I setup a trigger for the livechat, say, with people that stayed 10 sec on the webpage, the chat window appears. Thought on desktop the window is not that obstructive, on mobile it is made full screen. 

I think there should be an option to trigger popped down, such that the user can actually "accept" the interaction. Otherwise it is very intrusive.

![image](https://user-images.githubusercontent.com/551129/58955057-3297ca80-879b-11e9-9885-ce99fbda3323.png)

Like this? 
![image](https://user-images.githubusercontent.com/551129/58955125-59ee9780-879b-11e9-88bf-c6d0cbdce5e9.png)

**Comment by renatobecker** [comment]
> This is also too intrusive for me.
> If I setup a trigger for the livechat, say, with people that stayed 10 sec on the webpage, the chat window appears. Thought on desktop the window is not that obstructive, on mobile it is made full screen.
> 
> I think there should be an option to trigger popped down, such that the user can actually "accept" the interaction. Otherwise it is very intrusive.
> 
> ![image](https://user-images.githubusercontent.com/551129/58955057-3297ca80-879b-11e9-9885-ce99fbda3323.png)
> 
> Like this?
> ![image](https://user-images.githubusercontent.com/551129/58955125-59ee9780-879b-11e9-88bf-c6d0cbdce5e9.png)

Please, open a new issue on the new Livechat repository describing your requirement.
https://github.com/RocketChat/Rocket.Chat.Livechat

**Comment by renatobecker** [comment]
We're going to improve the appearance of the Livechat triggers, the widget won't be maximized anymore, we gonna display the trigger messages outside the button so the new feature will improve the UI and UX on mobile as well.
We're planning to have the new design in short-term, so I'm going to close this issue.

Thanks.
