### ISSUE TITLE
Let a person lost message text format documents

### ISSUE THREAD

**Issue by thinkeridea** [RocketChat/Rocket.Chat#7248]
I tried to send a special format in chat rooms, most is not support (such as HTML, CSS, markown table, etc...).And I try to use the program to generate a character form today, but got an unexpected show effect, more interesting is, however, I can't find the related message format document, I think there should be a copy of the document to guide users to send creative message.

Here is my attempt to use more lines of code format \`\`\` code ```

![image](https://user-images.githubusercontent.com/12491807/27119007-8bf5e1a2-5110-11e7-8303-baf5733e4544.png)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
