### ISSUE TITLE
Email field optional

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7254]
Could it be possibly considered to have the email field as an optional field?  Some of my users don't wish to disclose their email address but there is no way to turn off the requirement to input an email address

Rocket.Chat Version: 0.56.0 
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by SeanPackham** [comment]
If you use an OAuth provider to authenticate you can skip email signup/login.
