### ISSUE TITLE
Number of Online Users Next to Channel Name

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7255]
Would it be possible to implement the ability to show the number of active (online) users available in each channel?

Rocket.Chat Version: 0.56.0 
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by TwizzyDizzy** [comment]
I'm not quite sure whether this is a piece of information that is worth the valuable space in the sidebar. The sidebar is the main piece of interaction and I think it should only contain information that is REALLY important.

Can you explain why that might be important? The only thing I can think of is, that when you're new to a server, you want to see which are the most active channels.

Cheers
Thomas

**Comment by jszaszvari** [comment]
It's up to the end user to decide what's imported for them. If this gets implemented then as long as it's a option that can be toggled and isn't forced on then nobody will be unhappy.

**Comment by TwizzyDizzy** [comment]
Mhhh. Mhhh... you're right. Then.. I think I just wouldn't make it the default.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi folks, I just stumbled across #4490. As there is already a visualization and a PR (dunno of which quality and state), I'd like to close this one here. If you do not agree, please get back to me :)

Cheers
Thomas
