### ISSUE TITLE
[Realtime-API] - sendMessage results in invalid user error

### ISSUE THREAD

**Issue by m00s** [RocketChat/Rocket.Chat#7256]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Hi there,
I'm trying to use the realtime API to post a direct message to another user.
I'm using the [send message](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message#send-message) method from the doc but the result is:
```
"{"msg":"result","id":"990","error":{"error":"error-invalid-user","reason":"Invalid user","details":{"method":"sendMessage"},"message":"Invalid user [error-invalid-user]","errorType":"Meteor.Error"}}"
```

Using the REST API everything works fine, since I'm sending the cookie to authorize the call.
Am I missing something?

**Comment by graywolf336** [comment]
Please show us what code and what exactly you're trying to send..

**Comment by m00s** [comment]
@graywolf336 

```
this.socket.send({
      "msg": "method",
      "method": "sendMessage",
      "id": this.uid(),
      "params": [
        {
            "rid": "EFTLYNaRGxuE6MqcaocGtwnNDxborzKkPv",
            "message": "Yo"
        }
      ]
    });
```

- Other events/messages work fine, so I guess the socket connection is working properly
- I tried also specifying a message `_id` within the params property, same result
- I also tried to copy the frame sent from your client on rocket.chat when sending a message from the UI, that has basically those same parameters, same error.

**Comment by vagnnermartins** [comment]
Hello @m00s , have you solved the problem?

I have the same problem.

```
Meteor.call('livechat:registerGuest', guest, function(error, result) {
	if (error != null) {
		console.log('ERROR :: Meteor.call')
	}
	RocketChat.Livechat.sendMessage({ guest, message: registerData.message })
	return RocketChat.API.v1.success({});
});
```

The first time, the message is sent with success, after console shows: 
**Error: Invalid user [error-invalid-user]**

**Comment by juliomac** [comment]
Hi @vagnnermartins  and @m00s ! Have any of you solved it?

What is the proper way to use the sendMessage method through DDP?

I am trying:

                      conn.call('sendMessage',
                                {
                                    _id: "message-id",
                                    rid: message.rid,
                                    msg: "Hello from bot"
                                }
                            );

**Comment by ggazzo** [comment]
>                   conn.call('sendMessage',
>                             {
>                                 _id: "message-id",
>                                 rid: message.rid,
>                                 msg: "Hello from bot"
>                             }
>                         );

your payload seems correct could you paste the response? thanks

**Comment by raza2022** [comment]
so what's the solution of the issue which faced by few users, I am facing the same issue, any update/docs/help linked to that issue
