### ISSUE TITLE
Have way of batch upload files to channel

### ISSUE THREAD

**Issue by mcsooks** [RocketChat/Rocket.Chat#7257]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: v4.8.2

I've read in one of the rocket.chat issues (https://github.com/RocketChat/Rocket.Chat/issues/1773) that "one message can have only one file upload," but can you allow batch uploading files to a channel? 

In slack, when a user uploads multiple files to a channel, it automatically creates a queuing process of adding a title+comment for each file uploaded, which saves time and is very convenient. Currently in rocket.chat you have to upload files individually, which is tedious. In our use-case, we are uploading multiple images (screenshots).

**Comment by rodrigok** [comment]
We already support batch uploads
