### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7259]
Is there any documentation on language strings used in Rocket Chat?  For example, I wish to change the "More Channels..." text to "Click for More Channels" but cannot seem to find the language string used.

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by lucasvanhalst** [comment]
You could always try searching using the github search function: https://github.com/RocketChat/Rocket.Chat/search?utf8=%E2%9C%93&q=More+Channels+extension%3Ajson&type=

The string you're looking for appears to be "More_channels"

**Comment by waveyuk** [comment]
@lucasvanhalst thanks for that - really helped!

**Comment by geekgonecrazy** [comment]
@waveyuk the files are there in the repo.  But we actually manage translations via lingohub.  If you shoot us an email to translations@rocket.chat with the email you would like invited and the language we will invite you to lingohub where you can edit.
