### ISSUE TITLE
Is this project working?

### ISSUE THREAD

**Issue by rbajaniya** [RocketChat/Rocket.Chat#7261]
Please tell me this project is working or not.
I have just run this project and getting so many **errors**.

**Comment by ellisgl** [comment]
Works for me under Linux just fine.

**Comment by rbajaniya** [comment]
Which software and packages required?

**Comment by lucasvanhalst** [comment]
Try setting it up using docker, that way you don't have to install any dependencies (besides docker itself) and it's guaranteed to work.

**Comment by rasos** [comment]
I just set up another instance on Debian Jessy and all works fine.

**Comment by geekgonecrazy** [comment]
@rbajaniya absolutely we have many different ways of deploying rocket.chat.  https://rocket.chat/docs might be of use to you.  

https://rocket.chat/docs/installation/paas-deployments
https://rocket.chat/docs/installation/manual-installation/ubuntu

**Comment by geekgonecrazy** [comment]
Please re-open if you have any specific errors after trying one of the deployment methods.
