### ISSUE TITLE
Cannot create direct message room via API

### ISSUE THREAD

**Issue by Star1122** [RocketChat/Rocket.Chat#7262]
Rocket.Chat Version: 0.57.0
Node Version: 4.8.2

I am trying to open direct message room while creating new user. I can create new user via user.create API but I cannot create dm room between the new user and users already created. I got hint that the dm room ids are combined with userIds from support. I tried to create room id by combining new user id and other user id but the new roomIds are not recognized.

Is there any other way to create dm room between users programmatically?

**Comment by geekgonecrazy** [comment]
Its possible its a matter of using: https://rocket.chat/docs/developer-guides/rest-api/im/open since direct messages aren't typical rooms.  

@graywolf336 might be able to give you a better answer :smile:

**Comment by Star1122** [comment]
Thanks, @geekgonecrazy .
Yes, I tried to use that but as I mentioned, roomIds created by combining user Ids is not recognized.
Please look at the screenshot.
![clipboard - june 13](https://user-images.githubusercontent.com/21158589/27196639-95a23a38-520b-11e7-8348-d9911abd834a.jpg)

**Comment by geekgonecrazy** [comment]
Yeah i'll have to defer this one.  I'm not familiar enough with it to be helpful on this one.

**Comment by graywolf336** [comment]
You can't exactly open a new direct message room. You have to send a message to the user and it will then start it. That's how it is on the UI and this it's not exactly possible internally.

**Comment by geekgonecrazy** [comment]
So if was to just send a message via: https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage would it create the room?  Or is it going to fail because the room doesn't exist

**Comment by graywolf336** [comment]
Yes, send a message to `@username` and it will work as direct message rooms "always exist" to Rocket.Chat.

**Comment by graywolf336** [comment]
This has been requested a few more times and will be implemented once a pull request gets merged that is coming up.
