### ISSUE TITLE
Enable scheduling of LDAP "Sync Users" function

### ISSUE THREAD

**Issue by gregs007** [RocketChat/Rocket.Chat#7263]
Currently you can sync existing RC users with LDAP by clicking on a button in the LDAP admin console. Suggest to add Sync LDAP users on interval in hours or minutes. This would facilitate RC being able to disable locked out/disabled accounts from LDAP database as mentioned in #6174 #4554 and  #7235

**Comment by bhotrock** [comment]
I would like this as well.  Even if someone has a "work around" that could be put into a script run by a cron job, that would work for me.  Just not sure what the script would need to do to accomplish "clicking the the 'Sync Users' button".

 Also, a scheduled sync would automatically add new users when they are added to LDAP.  As discussed in other issues, it would be best to NOT delete users who no-longer exist in LDAP, but rather de-activating them.
