### ISSUE TITLE
Multiple spaces displayed as a single space

### ISSUE THREAD

**Issue by thinkeridea** [RocketChat/Rocket.Chat#7264]
I found that sends the message contains multiple Spaces in a row, the display is the width of only one, when this is HTML display problem, but I hope can do processing, users want to display a message and send is consistent, need to change the white space in your message to &nbsp;

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by mfilotto** [comment]
My use case : 
My message has multiple lines with a title and a description
I want to pad titles to have something readable, this way :
```
- RECSMA   : aucune version trouvée (en éliminant les commits de merge)
- RECSEP   : la branche de recette n'existe pas. Veuillez vous rapprocher d'un administrateur pour configurer ce projet
- INT      : aucune version trouvée (en éliminant les commits de merge)
- PREPROD  : aucune version trouvée (en éliminant les commits de merge)
- PROD     : aucune version trouvée (en éliminant les commits de merge)
```

**Comment by MartinSchoeler** [comment]
As we can see on the GitHub comment box if you add multiple spaces it will trim it down to 1, an alternative to this is to use block quotes, as seen on this screenshot
![Screen Shot 2019-11-12 at 16 58 53](https://user-images.githubusercontent.com/20868078/68706072-f9476000-056d-11ea-814b-52c646f971f7.png)
@sampaiodiego 
Thanks!

**Comment by thinkeridea** [comment]
This is a scheme, but I will not use block quotes to format normal communication information. I usually use it in format code or special information. I think as a chat platform, we need to deliver messages according to the user's intention, rather than just providing a parser for markdown. If I want to promote the use of all people in the company, I think it should be a chat tool, which does not need everyone to learn markdown. Even though it is very simple, there are people in the company who do all kinds of work, and they are not willing to learn markdown

**Comment by KimchaC** [comment]
I am also frustrated by this, since I oftentimes want to post bullet points with different indentation.

I found it's possible to use an empty character copied from the second selection box on http://emptycharacter.com/:
```
No indentation
 ‎ ‎ ‎ ‎- First level
 ‎ ‎ ‎ ‎ ‎ ‎ ‎- Second level
 ‎ ‎ ‎ ‎- First Level
```

(These are not spaces, but special space-like characters that are not removed by rocket chat)
