### ISSUE TITLE
Exception while invoking method 'MethodName' TypeError: this.aggregate is not a function

### ISSUE THREAD

**Issue by nitinjiniguru** [RocketChat/Rocket.Chat#7265]
I am working in rocketchat-lib/server/models folder.

I created my file for database operation and Insert,update,remove and find methods are working completely fine.

now i want to get some relational data but it gives me this.aggregate method is not function..
I have followed the steps [meteor aggregate](https://github.com/meteorhacks/meteor-aggregate)
then also add following command as well
meteor add monbro:mongodb-mapreduce-aggregation

as i am working on server side 

but still i am facing same problem.

**Comment by geekgonecrazy** [comment]
We'll need a lot more info related to the customization you made to even begin to help

**Comment by nitinjiniguru** [comment]
In the  rocketchat-lib/server/models I created a new model file and crated a document and it reflects in database as well.

now i have two different collection and those are relational.

if i do `this.findOne({_id: aid});` then its works fine and it returns me that collection data

but when i try to use aggreagate method as below


`return this.aggregate([
		    {
		      $match:{
		       _id:aid   
		       },
		    },
		    {
		      $lookup:
		        {
		          from: "rocketchat_sample_collection",
		          localField: "_id",
		          foreignField: "aid",
		          as: "relationalData"
		        }
		   }
		]);`

then its not working.


rocketchat_sample_collection is contains aid which is pk of the my current collection

**Comment by geekgonecrazy** [comment]
I don't believe meteor has that command available out of the box.  Check our something like this: https://github.com/meteorhacks/meteor-aggregate

**Comment by geekgonecrazy** [comment]
Went ahead and closed as this is more development related not bug related or feature request related.

**Comment by nitinjiniguru** [comment]
I already tried with [https://github.com/meteorhacks/meteor-aggregate](https://github.com/meteorhacks/meteor-aggregate) 
and when i use
`var metrics = new Mongo.Collection('metrics');
var pipeline = [
  {$group: {_id: null, resTime: {$sum: "$resTime"}}}
];
var result = metrics.aggregate(pipeline);`

then it gives me error that 

There is already a collection named "metrics"

and if i try by this then it gives me error as i have mentioned in title

**Comment by geekgonecrazy** [comment]
Might try a collection name not being used anywhere else.  Also, you might ask about this in that repo.  A quick search of our code base we.arent using aggregate.  So unless someone else from the team has some other experience, there isn't any of our code to reference.

**Comment by nitinjiniguru** [comment]
I am using same model class method of the rocket chat

I have declared my collection name in 

`constructor() {
		super('collectionName');
	}`
so inside every model method i have used **this** object and its working completely fine but only .aggregate is not working.

**Comment by nitinjiniguru** [comment]
i found the solution for this RocketChat.models.collectionName.model.aggregate()

but now i want to use aggregate in client side?
