### ISSUE TITLE
Offer to send as attachment when message too long

### ISSUE THREAD

**Issue by rillig-nm** [RocketChat/Rocket.Chat#7267]
Rocket.Chat Version: unknown
Running Instances: unknown
DB Replicaset OpLog: unknown
Node Version: unknown

When using the web client for Rocket.Chat, I cannot send long text messages. When I try, I only get an error message.

Instead of this error message, I expected a more helpful response from Rocket.Chat, something like "This message is too long. Should I send it as a file attachment instead?"

**Comment by soundstorm** [comment]
This is adjustable from the admin panel, there a maximum message length can be set. So ask your Rocket.Chat admin to adjust this setting or send it as txt file.

**Comment by rillig-nm** [comment]
Thanks for the suggestion. Would it be worthwhile nevertheless to offer the option of sending the long text as an attachment?

**Comment by geekgonecrazy** [comment]
i've converted the title to something more along the lines of a feature request

**Comment by lindoelio** [comment]
Hi! I'm motivated to work on this feature out. As soon as possible I'll send a PR with my implements suggestion.

Anyone have any more ideas about how it should be, besides what has already been commented?

**Comment by leonardorocco** [comment]
would be great to have this feature added!
