### ISSUE TITLE
Link Previews not working in all cases

### ISSUE THREAD

**Issue by jclabaugh** [RocketChat/Rocket.Chat#727]
I have found multiple URLs that show a link preview in Slack but do not in Rocket.Chat.

Examples:

https://xebialabs.com/periodic-table-of-devops-tools

http://www.vox.com/2015/9/4/9260353/august-jobs-report

http://www.infoworld.com/article/2937829/cloud-computing/the-private-cloud-is-for-suckers.html

**Comment by geekgonecrazy** [comment]
The 2nd and 3rd work for me.  The first still doesn't

**Comment by jclabaugh** [comment]
on Slack, the first link previews like this
<img width="863" alt="screen shot 2015-09-09 at 5 22 59 pm" src="https://cloud.githubusercontent.com/assets/14165558/9774592/8dcbab5a-5717-11e5-97cd-d76bb179f69c.png">

**Comment by geekgonecrazy** [comment]
An interesting note.. When I curl the link, curl thinks that link has invalid ssl.  This may be the reason..

**Comment by jclabaugh** [comment]
could add the command line switch (-k or --insecure) when using curl so that it doesn't disregard wildcard cert's for subdomains or self-signed cert's

Allow connections to SSL sites without certs

**Comment by geekgonecrazy** [comment]
Right that's what I did as soon as it failed.  Let me verify this is actually what's happening on rocket.chat.

This might be what's happening with your other issue as well.

**Comment by geekgonecrazy** [comment]
#749 fixes the issue mentioned here.
