### ISSUE TITLE
Leaving owner

### ISSUE THREAD

**Issue by Gyaviste** [RocketChat/Rocket.Chat#7271]
Rocket.Chat Version:  0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.5.0
---
If you are the only one channel owner pressing leave will show an alert that you need to set another owner before leaving, you will be displayed as user that is in channel for other users and other users can still join channel, but you can't do anything in channel even join it.

**Comment by ggazzo** [comment]
hey @Gyaviste I think we already fixed this issue here #10851 could you check please?
