### ISSUE TITLE
Listen incoming message from server

### ISSUE THREAD

**Issue by dhthong92** [RocketChat/Rocket.Chat#7272]
Rocket.Chat Version: 0.57.0-develop
Running Instances:  1
DB Replicaset OpLog: Enabled
Node Version: 4.8.3

Can someone explain in details for me the way to listen any incoming messages from server?
I write a client using REST API in C++, but I only know the way to post message to server, I want to whenever server receive any message, it broadcast to all client connected to it. I've seen the Subscriptions docs but do not understand clearly. Can someone give me an example? Thanks in advance!

**Comment by dhthong92** [comment]
Any help :( I mean that I want my client to subscribe messages from server and each time the server receives any messages, it publish to all client connected to it. Do the REST API have any APIs like subscribe or listen for this purpose? Sorry if my question's silly because I do not know much about meteor :(

**Comment by ToniIltanen** [comment]
Do you mean chat messages? You can broadcast them through the integrations to your API (Outgoing webhook). For more (and for an example), check out https://rocket.chat/docs/administrator-guides/integrations

**Comment by dhthong92** [comment]
Yah, it's exactly what I mean. But if I use Outgoing Webhook, I have to write another push server to manage my connected client as well. Does Rocket Chat support any API like listen or subscribe directly from server?

**Comment by ToniIltanen** [comment]
I dont understand. 

Incoming Webhook => you send something to rocket.chat, and assign which channels to show you message
Outgoing Webhook => You send something out from rocket.chat, and you have a separate API listening for messages.

So you can have a singular backend somewhere, which also pushes messages into incoming webhook listening on rocket.chat, and listens messages sent from the outgoing webhook on rocket.chat.

**Comment by jszaszvari** [comment]
Yes it supports this via the real time API not the standard rest API. 

The real time API uses DDP I believe. 

When I get back to my office in 30 mins I will post you a example I wrote that 'listens' to a stream of messages in a channel.

**Comment by ToniIltanen** [comment]
Also, you can make an hc solution, and poll directly from the rc database. 
If you use MongoDB, you can use capped collections and tailable cursors which allows mongodb to push data to listeners. 

An example: http://jwage.com/post/30490196727/mongodb-tailable-cursors

**Comment by dhthong92** [comment]
@jszaszvari Yah that's what I'm searching. But I saw in their docs that Realtime API does not release yet and I have point my client to [](http://demo.rocket.chat) right? Waiting for your example sir
@ToniIltanen yah, it can be considered as another solution, but I believed that Realtime API is what I need and much more effeicient. Anw thanks for your help :)

**Comment by jszaszvari** [comment]
@dhthong92 Sorry I am running late, I am on my way home from work now and will post you some details when I get home. 

It has been released, it's just not all documented or officially supported, but I am sure it will be soon.

Had a issue at work that I needed to deal with - When i get back in from of my computer in 1 or 2 hours I will post it here for you to have a go with, Just writing a README so you know how to use it. 

Basically what it does is you can subscribe to a message-stream for a user, a channel, or everything. 

If I am subscribed to the channel stream then everything that happens is streamed in real time like this:

```
Subscription Msg: {"msg":"changed","collection":"stream-room-messages","id":"id","fields":{"eventName":"gCCmdeFSQJFoLRigB","args":[{"_id":"DECdyQK6QAgWcQBpN","rid":"gCCmdeFSQJFoLRigB","msg":"Test message","ts":{"$date":1497855314750},"u":{"_id":"uLJ2GkWEz4KXywZrJ","username":"john_szaszvari","name":"John Szaszvari"},"_updatedAt":{"$date":1497855314751}}]}}


Subscription Msg: {"msg":"changed","collection":"stream-room-messages","id":"id","fields":{"eventName":"gCCmdeFSQJFoLRigB","args":[{"_id":"qRjtZFirXsEGW9RxE","rid":"gCCmdeFSQJFoLRigB","msg":"Another message","ts":{"$date":1497855321044},"u":{"_id":"uLJ2GkWEz4KXywZrJ","username":"john_szaszvari","name":"John Szaszvari"},"_updatedAt":{"$date":1497855321045}}]}}
Subscription Msg: {"msg":"ping"}
```

A quick GIF of it in action: 

![ezgif-2-eb541d6666](https://user-images.githubusercontent.com/872463/27273255-91bd1a24-5511-11e7-9dd1-3c5eff69dd73.gif)

**Comment by dhthong92** [comment]
@jszaszvari Nice, this's really what I need right now. This is the first time I hear about DDP, I will spend a little bit time to take a look at it. Anw, hope your example can make my life become easier :(

**Comment by MartinSchoeler** [comment]
@dhthong92 was your question answered? If yes, please close this issue. Thanks!

**Comment by dhthong92** [comment]
Not yet, he told me waiting for his scripts in details because he are busy in his office right now. I will close this issue after my problem has been fully solved.

**Comment by jszaszvari** [comment]
@dhthong92  

Apologies for the delay 

Here you go. Send me a message if you need assistance

https://github.com/jszaszvari/rocketchat-ddp-listener

**Comment by graywolf336** [comment]
Don't forget to check out the documentation for the real time API: https://rocket.chat/docs/developer-guides/realtime-api
