### ISSUE TITLE
Option for mandatory Two Factor Auth for Users in Certain Roles

### ISSUE THREAD

**Issue by kpcyrd** [RocketChat/Rocket.Chat#7275]
Similar to #7100 I'm looking for a way to **require** MFA for certain roles, like administrators. This feature could also be used to require MFA for everybody except certain roles, like bots.

I think this would be a great addition to the MFA feature introduced recently, since there is currently no good way to get adoption from users.

**Comment by Marian0** [comment]
+1 👍🏼
