### ISSUE TITLE
This specific message causes channels to break/crash

### ISSUE THREAD

**Issue by SarCaustic** [RocketChat/Rocket.Chat#7276]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: ?
Node Version: v4.8.1
I'm using the snap install under Ubuntu 14.04

I am having issues with a specific message causing causing the rocket.chat to crash for the sender and receiver. This occurs in both public and private channels and private chats.
I tested on a junk user on the rocket.chat demo and it doesn't cause any issues.

here is the message:

    ```a single h is voiced while a double hh is aspirated, complete opposite on the other sounds...```

Thanks for any advice.

**Comment by SarCaustic** [comment]
After some searching I found duplicates, I just don't know how to fix anything since it's contained within Snap.

**Comment by purp** [comment]
Can you point out the duplicate issues here to help others find the right one?

**Comment by SarCaustic** [comment]
The issue was #6814.
I was able to update to 0.57.0-rc.2 via snap after Aaron did a reupload.
