### ISSUE TITLE
How to delete a forever-service?

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#7277]
Rocket.Chat Version: 0.56
Running Instances: 
DB Replicaset OpLog:
Node Version:

I am having some issues with deleting some "forever-services" that i set up for some Rocket.Chat instances that i am no longer using.

```
root@server:~# forever remove servicename
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
error:   Cannot start forever
error:   script /root/remove does not exist.
root@server:~# forever delete servicename
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
error:   Cannot start forever
error:   script /root/delete does not exist.
```

I tried both remove and delete commands but those are the errors i am getting.

The reason i want to delete them is because everytime i reboot my server they are starting up again, so stopping them is not good enough.

Thanks

**Comment by danilomiranda** [comment]
@WebSavvyGuy maybe some problem with your forever. Try to uninstall and install again
`$ [sudo] npm uninstall forever [-g]`
`$ [sudo] npm install forever [-g]`

**Comment by WebSavvyGuy** [comment]
@danilomiranda 

If i do that will that have any affect on my existing services and my RC installs because i installed them by service.?

**Comment by danilomiranda** [comment]
Sorry @WebSavvyGuy I don`t know. That need some research and I can`t right now.

**Comment by WebSavvyGuy** [comment]
@danilomiranda ok no problem.  i am going to leave it for now.  Dont want to take any chances.   Our reboots are few and far between anyways.

**Comment by graywolf336** [comment]
@MartinSchoeler this has nothing to do with integrations and is instead how he setup his server...

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
