### ISSUE TITLE
Video/Webcam Request Permission window issue and webcam approval

### ISSUE THREAD

**Issue by josephmiller2000** [RocketChat/Rocket.Chat#7278]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

1. 
![snap_2017 06 18_12h02m49s_001_](https://user-images.githubusercontent.com/24210340/27258683-d8a168ee-541e-11e7-99cb-823c0dc39e88.png)

You can check the attached screenshot to find the issue. In mobile phones, this request notification is kinda messy and it need to be fixed based on devices. It looks like hidden inside screen.
--------------------------------------------------------
2.  There is not confirmation message during video acceptance for declined. 
  a, if a user send a cam request to another user. They get pop up message to accept or decline. If that person accepts video call request, the other party should get a small notification referring that your video request is accepted and please wait until the cam connects and ready to chat. 
 b, If the other party declines the video call. Requesting user must get a small notification stating( your video call request has been declined by {user}.

Lot of chat users requested to fix this problem. Thanks and hope someone will find a fix for it.

**Comment by MartinSchoeler** [comment]
This issue was fixed with the latest versions. Closing this

![Screen Shot 2019-11-04 at 13 46 22](https://user-images.githubusercontent.com/20868078/68140231-3d04ee80-ff0a-11e9-8c27-edc5344e1535.png)
