### ISSUE TITLE
Apostrophe rendering as an escape code

### ISSUE THREAD

**Issue by cpitman** [RocketChat/Rocket.Chat#7284]
Rocket.Chat Version: 0.57-rc2
Running Instances: 4
DB Replicaset OpLog: Yes

In the latest RC, we're seeing that any apostrophes (ie ') are rendered as an escape code for a split second before correctly rendering as an '. This is in the web client, and we didn't notice this happen in 0.56-rc4.

**Comment by cpitman** [comment]
Here is a video of what we are seeing: https://drive.google.com/file/d/0BzuLnkicjO2qalV1TU1TMmsyVlk/view?usp=sharing

**Comment by MartinSchoeler** [comment]
duplicate of #7202
