### ISSUE TITLE
<user> has come online message

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7286]
It would be helpful to have the chat software alert other users that a member has signed in.  This message should be transmitted to all chat rooms the user signing in belongs to.

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by localguru** [comment]
Hmmm ... wouldn't that flood the rooms, especially on rooms with a lot members? If so, there should be an option to disable it.

**Comment by marceloschmidt** [comment]
This is not our vision for the product. We're not implementing. Feel free to implement this as an app. Thanks.
