### ISSUE TITLE
[Feature-Request] API KEYS

### ISSUE THREAD

**Issue by leewillmore** [RocketChat/Rocket.Chat#7289]
Rocket.Chat Version: 0.56.0

It would be nice to have the ability to create API keys for Rocket Chat. These keys could be used to login to Rocket Chat using the REST API without the need for a Username and Password combination. The key would be configured against a user.

Regards

**Comment by wcgcoder** [comment]
Agreed. Some of us tie our instance to external authentication. Maintaining extra accounts is either a major pain or impossible depending on who controls the directory.

**Comment by geekgonecrazy** [comment]
I believe this has actually been implemented.  @MarcosSpessatto or @graywolf336 do either of you know how this works?

**Comment by graywolf336** [comment]
Yes and no. There is the ability to generate a user token, however it appears to have been removed from the UI and is no longer accessible unless interacted with via code.
