### ISSUE TITLE
Desktop Notifications should show the avatar of who sent the message

### ISSUE THREAD

**Issue by soonahn** [RocketChat/Rocket.Chat#729]

**Comment by rodrigok** [comment]
If user set avatar as **initials** the image of avatar is a SVG and the notification don't displays the image.

**Comment by soonahn** [comment]
There should be channel settings as well.  A user should be able to set what sort of notifications they want per channel.  If I want all messages in a certain channel to give me a desktop notification, they should.

**Comment by geekgonecrazy** [comment]
This was closed via #775
