### ISSUE TITLE
Files/filenames get mixed up when uploading 3+ files

### ISSUE THREAD

**Issue by marcingodlewski** [RocketChat/Rocket.Chat#7291]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1 - x64

Problem occurs repeatedly when I try to drag 3 files (e.g. "a.xlsx", "b.xlsx", "c.xlsx") into the chat window for upload. The recipient gets 3 deliveries but with filenames mixed up, e.g. "a.xlsx", "b.xlsx", "b.xlsx" and the contents of files not matching the filenames

**Comment by 1stposition-ad** [comment]
same problem for pdf files, sometimes when you try to send two files at once, the same file is sent twice, but with the names of the two files sent.
example:
Sending a.pdf and b.pdf to an user, the user gets a.pdf and b.pdf, but once you open the files you notice it's twice a.pdf .

**Comment by localguru** [comment]
Can confirm, tested on demo.rocket.chat. Uploaded 3 files a.txt, b.txt and c.txt.

![bildschirmfoto vom 2017-06-23 23 10 39](https://user-images.githubusercontent.com/8544984/27500680-cbb99a30-5869-11e7-9c6d-bea55d93ed89.png)

**Comment by Brondahl** [comment]
I have a very similar issue.
For me I upload 2 files, and both files do get uploaded, but they're displayed with the same names.

OS: Win 10.
Browser: FF
RC vers: 0.57.2

**Comment by marcingodlewski** [comment]
It's been 7 weeks since this issue was originally posted and there is no follow-up from the maintenance team - not even labeled as bug, which it obviously is, quite a serious one.
There should be no doubt about labeling as this is easily reproducible, even at demo.rocket.chat today.
I understand that you cannot guarantee immediate resolutions for all bugs, but no label at this point is concerning.

**Comment by estshy** [comment]
Any progress on that?

**Comment by autioch** [comment]
I almost reported same issue. Is this going to be fixed? Quite problematic when you send list of items to delete and duplicate :)

**Comment by marcingodlewski** [comment]
Issue still exists. Any progress?

**Comment by localguru** [comment]
Bug still exists in 0.58.2. Any progress here?

**Comment by bbrauns** [comment]
We would appreciate a bug fix as well: v0.58.2

**Comment by localguru** [comment]
Just tested on demo.rocket.chat (0.59.0-rc.9) and it seems to be fixed. Thanks!

**Comment by marcingodlewski** [comment]
@localguru I'm afraid not.
I also checked demo.rocket.chat a moment ago and still the 3 files were confused
![image](https://user-images.githubusercontent.com/29565393/30904975-d35e663a-a373-11e7-900e-4158012c1cdb.png)

**Comment by localguru** [comment]
@marcingodlewski You're right. I tested it with images, which works fine. With text files it's wrong on demo.rocket.chat too.
![test](https://user-images.githubusercontent.com/8544984/30921274-5d5c3a2e-a3a6-11e7-8c45-e23f70881743.jpg)

**Comment by rrepolona** [comment]
Sorry i post here. i'm not sure if i have the same issue as this.

When i send a file to a person, when they download the files the name is different.
Is this a security feature or a bug?

kindly check attach image

-= original filename =-
![2017_10_17_11_23_45_](https://user-images.githubusercontent.com/5317204/31645620-9ea8e7aa-b32f-11e7-930b-fc049099a6b9.png)

-= downloaded filename =-
![2017_10_17_11_24_08_root_v157_7_154_220_data_vhosts_sms_hrceb cyscorpions com_htdocs_app_config](https://user-images.githubusercontent.com/5317204/31645611-99855448-b32f-11e7-9eeb-4f59fbf6c187.png)

**Comment by marcingodlewski** [comment]
@rrepolona I don't think your issue is related to this one

**Comment by Lawri-van-Buel** [comment]
@rrepolona the link and button are not the same. And are you using something other than gridfs?

**Comment by marcingodlewski** [comment]
Link to #8494

**Comment by rrepolona** [comment]
@marcingodlewski @Lawri-van-Buel 

thanks for your help, im using Amazon for file uploads instead of gridfs.

i believe the original filename (uploaded filename) should be the same as the download filename.
but for us the download filename is different :( is this related to Amazon feature, or security related?

thanks

**Comment by marcingodlewski** [comment]
Any update to this?
Problem still exists in 0.59.3

**Comment by marcingodlewski** [comment]
Apparently working in v60

**Comment by edisonchen1985** [comment]
hi, we are still using version 0.59, when uploading multi-files, they get mixed up. But it looks like in the new version of https://open.rocket.chat, this issue has been fixed. But I can not find any update information in the commit history about this issue, can anybody help to tell which file need to be changed to fix that?Thanks in advance!

**Comment by edisonchen1985** [comment]
@marcingodlewski  do you have any info about that? thanks

**Comment by marcingodlewski** [comment]
I don't believe this issue was specifically mentioned.
I guess it was #9206 that did the trick

**Comment by edisonchen1985** [comment]
@marcingodlewski thanks. I just replaced my local's file of messageBoxActions.js with the new one. ( I am still using 0.59.0 for some reason), but this bug still happens when uploading several files together. Do you still have this issue, and you know to update that?

**Comment by marcingodlewski** [comment]
@edisonchen1985 we're currently at 0.60.4 and the bug is most definitely gone. Probably the fix was somewhere else than what I linked above, but I can't help you further with that...

**Comment by engelgabriel** [comment]
@edisonchen1985 @marcingodlewski @1stposition-ad @localguru I also believe the problem has been solved. Please reopen this issue otherwise. Thanks.
