### ISSUE TITLE
Translation in Admin only translates last string

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7296]
If you enter a string of translations in the Admin backend under General settings, it appears only the last string is translated.  For example:

`{"en":{"More_channels":"# Click here for more channels"},"en":{"Name":"Nickname (we don't recommend using your full name)"},"en":{"Name_optional":"Nickname (we don't recommend using your full name)"},"en":{"Email":"Email (in the form of <yourname>@<your-address.com>- not shown to others)"}}`

In the the above example, only the Email translation is performed, all the others are ignored.

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by lucasvanhalst** [comment]
that's because the input you got is wrong, it should be: 
```json
{"en":
  {
    "More_channels":"# Click here for more channels",
    "Name":"Nickname (we don't recommend using your full name)"},
    "Name_optional":"Nickname (we don't recommend using your full name)"},
    "Email":"Email (in the form of <yourname>@<your-address.com>- not shown to others)"
  }
}
```

**Comment by waveyuk** [comment]
@lucasvanhalst 
D'oh! <face-plant!>
Don't I feel an idiot :) I was reading literally the instructions on the screen and just assumed that you had to specify the language identifier for each translation.  Amended the translation as you suggested and it's worked perfectly.
Thanks for your help!
