### ISSUE TITLE
Turn "LOAD MORE" automatic when it comes into view, with loader.

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#73]

**Comment by engelgabriel** [comment]
Should be configurable #222

**Comment by marceloschmidt** [comment]
Now the "Load more" is automatic. Do we really need this to be configured under settings?

**Comment by engelgabriel** [comment]
Nopes.

**Comment by geekgonecrazy** [comment]
I have a feeling this will be re-requested :) But it does belong in a separate issue even if so.
