### ISSUE TITLE
The Russian language is not activated.

### ISSUE THREAD

**Issue by Ma33x** [RocketChat/Rocket.Chat#7300]
The Russian language is not activated. I was not able to save another language. The standard is only English. I apologize for using Google Translate. See screenshots.
![image](https://user-images.githubusercontent.com/29602017/27384378-18a94f16-56a8-11e7-8d46-3bee099b8841.png)
![image](https://user-images.githubusercontent.com/29602017/27384416-30ce26d4-56a8-11e7-926f-3d6283c9ff34.png)
![image](https://user-images.githubusercontent.com/29602017/27384406-28812daa-56a8-11e7-9bfb-a190b3a06c3c.png)
![image](https://user-images.githubusercontent.com/29602017/27384437-4494cec0-56a8-11e7-84df-72964e96ef60.png)
What do friends do?

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

**Comment by MartinSchoeler** [comment]
@Ma33x  i couldn't reproduce this bug. Is the Russian language the only one that doesn't works?

**Comment by MartinSchoeler** [comment]
Closing this due lack of response
