### ISSUE TITLE
Channel Join method has no entry in API documentation

### ISSUE THREAD

**Issue by sasakura-sora** [RocketChat/Rocket.Chat#7301]
https://rocket.chat/docs/developer-guides/rest-api/channels

There is no entry for the Join method:
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/channels.js#L289

Is this deliberate as joining a room is implicit whenever doing an action on the room requires it (e.g. sending a message)?

**Comment by graywolf336** [comment]
No reason, just was skipped over on accident. Feel free to submit a pull request here to add it :) https://github.com/RocketChat/Rocket.Chat.Docs
