### ISSUE TITLE
Lift rate limit on createDirectMessage for bots

### ISSUE THREAD

**Issue by jangmarker** [RocketChat/Rocket.Chat#7302]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.0

In #5200 the rate limit on `sendMessage` got lifted for bots. However, if a bot wants to send a lot of direct messages at the same time it also needs `createDirectMessage` to not have a rate limit (the Hubot adapter for instance uses `createDirectMessage` to find the correct room).

**Comment by jangmarker** [comment]
@graywolf336 I've created a patch in #7326.

**Comment by graywolf336** [comment]
Hi @jangmarker, I have reviewed your pull request and requested some changes. Thanks for the pull request!
