### ISSUE TITLE
Slash Command Parameter Suggestions

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#7307]
The slash commands right now inside of Rocket.Chat only suggest parameters which start with `#` or `@`. Adding the ability to provide suggestions to the user for any configurable parameters along with where the suggestions come from would be superb!

For example, let's say someone creates a GitHub slash command. It provides one main command and several subcommands which those then take other parameters. For example: the command `/github assign <repository> <issue-number> <person>` would bring up suggestions when typing where the repository would go, the issue, and person being assigned. The slash command would be able to pull data from various resources and provide the suggestions asynchronously.

Also need a way to format the data which is being shown along with what is inserted into the message box when the user selects one of the suggestions. Ideally this would be done in a way that it's very generic and several packages can make usage of it.

**Comment by marceloschmidt** [comment]
We have plans of implementing this with the Rocket.Chat Apps.
