### ISSUE TITLE
Status Message on User Account/Profile

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7310]
It would be extremely helpful to have the ability to write a status message against their account which would also show on their profile.  For example, "I am away until the 1st July.  I will answer any messages on my return" or "If your message is urgent please email me on joe@abc.com"

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by waveyuk** [comment]
Hi guys...
Was wondering if this is going to make it into a build any time soon? It's something that definitely needs to be addressed.  Or at the very least (and possibly a better solution to cover all possible permutations) allow the Admin to create custom fields which can be displayed on the profile of the user.  I can see this having many benefits of the latter as people could enter not only status/bio information but maybe stuff like their twitter account, facebook profile, linkedin profile etc etc.
Thanks
Dave

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by oinadmin** [comment]
+1
