### ISSUE TITLE
Can no longer type accent on Mac App

### ISSUE THREAD

**Issue by Humeira** [RocketChat/Rocket.Chat#7315]
Hello,

I'm currently using Rocket.Chat V2.8 on MacOS Sierra 10.12.4 and accent doesn't seem to work anymore. 

It worked well in previous version. I have recently updated the app.

**Comment by MartinSchoeler** [comment]
@Humeira could you be more specific? Which character you cant type? What version of the server are you running? And are you using the app or the browser? Thanks for your feedback!

**Comment by MartinSchoeler** [comment]
Closing this due lack of response
