### ISSUE TITLE
[Feature-Request] Terms of Service and Privacy Police on entry side are not localized

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7328]
Rocket.Chat Version: 0.56.0 and 0.57.0-develop

On the entry side "By proceding you are agreeing to your Terms of Service and Privacy Police" is not localized to the on Administration/General set "language". The login mask is localized correctly.

**Comment by MartinSchoeler** [comment]
@localguru Since this text can be changed under Administration/Layout/Content/Login Terms there is no need of localization. 
<img width="1036" alt="screen shot 2017-07-03 at 2 04 32 pm" src="https://user-images.githubusercontent.com/20868078/27802221-cd6fff36-5ff8-11e7-8205-e90c2e34e8a2.png">
