### ISSUE TITLE
User Roles for Rooms Not Displayed

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7329]
If you add a user as a moderator to a room in the Administration settings, when you view the Permissions in the back end, no users you add are displayed even though they have the Moderator permissions.

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by MartinSchoeler** [comment]
duplicate of #5898
