### ISSUE TITLE
jitsi 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7331]
Rocket.Chat Version: 56 
Running Instances: 1
DB Replicaset OpLog: yes
Node Version: 4.6

jisti doesnt work on phones its say download app

**Comment by jszaszvari** [comment]
jitsi only works on mobile devices with the App. It's not native. 

Download the JITSI MEET app.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
