### ISSUE TITLE
Snap based server on Ubuntu is unreachable by app

### ISSUE THREAD

**Issue by Kiendeleo** [RocketChat/Rocket.Chat#7332]
## My Setup
- Operating System: Ubuntu 16.04 X64
- App Version: Latest Snap

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
I have a snap running on a VirtualBox Ubuntu 16.04 server. The server is configured with a NAT and has a fully qualified domain name.   The server is on Samba controlled network so there is a DNS server that resolves the FQDN of the server.  The RocketChat server is set up with a self-signed certificate. 

The Client is a Ubuntu 16.04 desktop using the Rocketchat-desktop snap.  The desktop can access the chat server from chrome, but the desktop app says, "No valid server found at the URL" The same issue occurs on the Android App

### Current Behavior
Desktop and Android apps don't connect despite being able to access the server through Chrome browser.

### Expected Behavior
Desktop and Android connect to the chat server

**Comment by localguru** [comment]
Is the self signed cert the problem, because app and desktop client don't know the root CA?

**Comment by Kiendeleo** [comment]
I am having trouble finding the documentation on how to add a publicly signed cert to the snap based server. Could you point me in the right direction

**Comment by localguru** [comment]
Sorry, I use the bundle install. May be this doc helps:

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl

**Comment by geekgonecrazy** [comment]
@Kiendeleo letsencrypt will encrypt for you using caddy built into the snap, but your domain will have to be externally visible I believe.

**Comment by Kiendeleo** [comment]
I am trying to run this inside of a private network, so not accessible from the outside except by VPN.  I do have a certificate authority on the primary server for that network so I am trying to find instructions on how to add the certificate generated by that to the caddy config file.

Also, If I remove `tls self_signed` from /var/snap/rocketchat-server/current/Caddyfile then run  `sudo systemctl restart snap.rocketchat-server.rocketchat-caddy` the process fails to start.  Not sure where the Caddy log files are to diagnose this.

**Comment by geekgonecrazy** [comment]
caddy logs would be available via:

```
sudo journalctl -u snap.rocketchat-server.rocketchat-caddy
```

**Comment by Kiendeleo** [comment]
The only error I am getting when I run that command is: `cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2.24]): older than "/usr/bin/snap" (2.25)`

**Comment by Kiendeleo** [comment]
Also I am getting a warning `WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".`

**Comment by geekgonecrazy** [comment]
Generate a cert using your CA.  Copy the cert and key to /var/snap/rocketchat-server/common  Then replace `tls self_signed` with `tls /var/snap/rocketchat-server/common/file.cert /var/snap/rocketchat-server/common/file.key`

Of course use what ever file names you want

**Comment by Kiendeleo** [comment]
Sorry for the delay, but I finally was able to take the time to test this, and it worked. Thank you @geekgonecrazy

**Comment by Kiendeleo** [comment]
Ok clarification, I now have it loaded with my certs, the desktop app connects (ubuntu installed via snap) after a cert warning, however, neither Android app will connect.  Recket.chat+ gives the following error: `There's a connection error. Please try later`  The rocket.chat app gives the following error: `Failed to connect to server: abort. abort`

**Comment by geekgonecrazy** [comment]
The case will be the same with mobile :(. If self signed it's not going to connect unless it trusts the certificate authority

**Comment by geekgonecrazy** [comment]
sorry i'm used to using that term for any certifact not considered valid.  Which generally is self-signed.  But in your case its just because it doesn't trust the CA.  So if you add the CA as trusted to mobile, it should work.

Easy way to test this is to access via your mobile browser.  If your browser gives the warning screen.  Then the mobile app also isn't going to work.

**Comment by geekgonecrazy** [comment]
Feel free to open again or create a new issue if you find any bugs with Rocket.Chat 

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
