### ISSUE TITLE
Issue with the Emojione png or svg

### ISSUE THREAD

**Issue by pojoba02** [RocketChat/Rocket.Chat#7335]
Rocket.Chat Version: 0.57
Running Instances: Linux
DB Replicaset OpLog:Enbaled
Node Version:4.8.3
Hello, am having an is issue with emojione png and svg after the upgrade to v3, images doesn't show up.

**Comment by inetfuture** [comment]
same here, just updated the latest docker image

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that have happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
