### ISSUE TITLE
Can't start docker in development installation

### ISSUE THREAD

**Issue by insaneisnotfree** [RocketChat/Rocket.Chat#734]
Hi.

I've followed the instructions in https://github.com/RocketChat/Rocket.Chat for the development installation and it gives me this error
```
Rocket.Chat]# docker run -it -p 3000:3000 -v "$(pwd)":/app danieldent/meteor
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
run: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.
```
Am I in the correct folder?

**Comment by geekgonecrazy** [comment]
The error makes it sound like you are running from a disk or maybe /tmp or something.  You did a git clone and actually changed into the Rocket.Chat directory right?

Also in my experience the `"`'s around `$(pwd)` aren't needed.

**Comment by insaneisnotfree** [comment]
I did change to the Rocket.Chat directory and it seems it seems removing the `"`'s around `$(pwd)` resolved the error: `You're not in a Meteor project directory`

**Comment by geekgonecrazy** [comment]
Does it actually run at this point?  

The docker error might be to do with the actual file system docker has set up for storing the containers.

**Comment by insaneisnotfree** [comment]
No, it does not run. It created the image but didn't started it
```
Rocket.Chat]# docker ps -a
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS                     PORTS               NAMES
6442afb4b889        danieldent/meteor   "meteor"             6 seconds ago                                                      suspicious_fermi
```

**Comment by geekgonecrazy** [comment]
It doesn't even report the status or ports? Wow.. 

What operating system is Docker running on?

**Comment by insaneisnotfree** [comment]
docker is running on centos 7

```
Rocket.Chat]# uname -a
Linux ##############.##.####.## 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
Rocket.Chat]# docker info
Containers: 3
Images: 56
Storage Driver: devicemapper
 Pool Name: docker-253:0-35597694-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.366 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.15 GB
 Metadata Space Used: 3.318 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 486.2 MiB
Name: ##############.##.####.##
ID: XVZG:OEL3:3FDG:OVZ2:774U:6OPS:QNQG:Q7VP:E2WK:JFHU:P7M4:GHUR
```

The error with iptables was resolved this way docker-library/mysql#72

However I have the same error on the beginning
```
Rocket.Chat]# docker run -it -p 3000:3000 -v $(pwd):/app danieldent/meteor
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
run: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.
```

Note: The domain name is hidden on purpose.

**Comment by geekgonecrazy** [comment]
Seems your docker install is setup up very strangly.

```
 Data file: /dev/loop0
 Metadata file: /dev/loop1
```

Both are on loopback devices?  Did you set this? Cause i've never seen it do that before... 

Also as long as $(pwd) is being ran while in the Rocket.Chat folder it should map correctly. Might also replace that with the full actual path.  Might work.

Or it could be related to the devicemapper storage location.

**Comment by insaneisnotfree** [comment]
When I run with `docker-compose up`it runs perfectly. 

If I change that what values are preferred on `Data file` and `Metadata file`

**Comment by geekgonecrazy** [comment]
@insaneisnotfree to be honest I have no idea... I'd google that loopback error its throwing you.

Very interesting that everything comes up with `docker-compose up`  Makes me wonder if maybe it was running out of memory?  The meteor build command that happens in the development image is very memory heavy.

**Comment by geekgonecrazy** [comment]
@insaneisnotfree i'm going to go ahead and close this issue.  Please let me know if you need more help.  Feel free to also jump into the [demo](https://demo.rocket.chat) chat.  We tend to hang out there.  :)
