### ISSUE TITLE
#general room fails to open and hangs rocket.chat

### ISSUE THREAD

**Issue by peterdalydickson** [RocketChat/Rocket.Chat#7340]
Rocket.Chat Version: **0.56.0**
Running Instances: **1**
DB Replicaset OpLog: **Disabled**
Node Version: **v4.8.1**

Whether I access rocket.chat via iOS, desktop or browser, selecting the #general room causes it to hang.

<img width="1440" alt="_ __chat___conquer_the_chaos" src="https://user-images.githubusercontent.com/17453188/27537894-a12317be-5a6d-11e7-887a-cff17e882de5.png">

Any ideas how I can a) troubleshoot; b) resolve the issue?

**Comment by MartinSchoeler** [comment]
@peterdalydickson is there anything on the browser console? Does this happens every time you enter `general`? And does this happens only on general channel? Thanks!

**Comment by peterdalydickson** [comment]
1. Nothing in browser console
2. Happens everytime I enter `general`
3. It only happens on `general` channel

Debug log when I enter `general`...
```
[34mI20170626-13:00:11.977(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ method loadHistory -> userId: vqL53A4x77xJgGbNT , arguments:  { '0': 'GENERAL',   '1': null,   '2': 50,   '3': Sat Jun 24 2017 07:40:13 GMT+0000 (UTC) } 
[34mI20170626-13:00:11.979(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ method canAccessRoom -> userId: vqL53A4x77xJgGbNT , arguments:  { '0': 'GENERAL', '1': 'vqL53A4x77xJgGbNT' } 
[34mI20170626-13:00:11.992(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ publish stream-room-messages -> userId: vqL53A4x77xJgGbNT , arguments:  { '0': 'GENERAL', '1': false } 
[34mI20170626-13:00:11.995(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ method canAccessRoom -> userId: null , arguments:  { '0': 'GENERAL', '1': 'vqL53A4x77xJgGbNT' } 
[34mI20170626-13:00:12.010(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ publish stream-notify-room -> userId: vqL53A4x77xJgGbNT , arguments:  { '0': 'GENERAL/deleteMessage', '1': false } 
[34mI20170626-13:00:12.735(0) rocketchat_logger rocketchat_logger.js:377 [34mMeteor ➔ method getRoomRoles -> userId: vqL53A4x77xJgGbNT , arguments:  { '0': 'GENERAL' } 
```

**Comment by peterdalydickson** [comment]
If it helps...

Using the desktop app, with a clean install of 2.8.0 from DMG, I can access all public and direct channels.

If I click to access `general` and then quit Rocket.Chat... it hangs on restart.

**Comment by MartinSchoeler** [comment]
Could be related to #6825

**Comment by peterdalydickson** [comment]
Looks like it, yes

**Comment by geekgonecrazy** [comment]
if it happens every time... it might be more related to #6262 if you have access to the db you could find the last message sent in GENERAL and see if this is the case with a query something like this:
`db.getCollection('rocketchat_message').find({rid: 'GENERAL'}).sort({ts: -1})`

**Comment by peterdalydickson** [comment]
I do have access to the db, but I've no hands-on experience with mongo... only mysql etc.

How do I get in to run the command you mentioned?

Thanks for your help.

**Comment by peterdalydickson** [comment]
I got in with `docker exec -it c15b09f59aae mongo`.

`db.getCollection('rocketchat_message').find({rid: 'GENERAL'}).sort({ts: -1})` doesn't return anything.

**Comment by peterdalydickson** [comment]
Ah... did `use rocketchat` first and got some output!

Checking now...

**Comment by peterdalydickson** [comment]
[https://github.com/RocketChat/Rocket.Chat/issues/6814#issuecomment-306917195](https://github.com/RocketChat/Rocket.Chat/issues/6814#issuecomment-306917195) fixed it for me @geekgonecrazy 

Thank you 👍🏼

**Comment by MartinSchoeler** [comment]
Glad this issue was resolved, i will close this then.

**Comment by geekgonecrazy** [comment]
@peterdalydickson sorry on the delay response, but glad you got it figured out :+1: this next release that issue should no longer be a problem

**Comment by bbrauns** [comment]
what exactly is causing this error and will there be a fix in the next release?
