### ISSUE TITLE
can't upload odt with Electron Client, even if "application/vnd.oasis.opendocument.text" is set Accepted Media Types

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7343]
Rocket.Chat Version: 0.56.0 

I've add "application/vnd.oasis.opendocument.text" to "Accepted Media Types", but can't upload .odt in Electron Client 2.8.0. It's working in a Browser.

**Comment by geekgonecrazy** [comment]
Doesn’t seem to be new reports.  I assume fixed?  Closing
