### ISSUE TITLE
Pagination of LDAP users in sync

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#7348]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: v4.5.0

Hey guys, today i found out that the rocket chat only sync up to 500 Users from ldap. We have like ~600 Users. Do you know how to enable e.g. pagination in rocket chat or fix this issue?

(it tells that 500 users in total and 500 are active.)

Kind regards,

**Comment by geekgonecrazy** [comment]
@hExPY what ldap server are you using?  I'm assuming this is the max number your ldap server will return in a single payload.  Looking over the code on our side there is no limit.  But there also doesn't appear to be any pagination.

Your server may have a setting somewhere to configure how many are returned.  I'd take a look there for a quicker fix.

**Comment by hExPY** [comment]
Hi @geekgonecrazy we're using openldap. Yes. 500 is the maximum and after 500 theres a pagination. I'll have to figure out if its possible to set up the return of more than 500 users.

Thanks!!
