### ISSUE TITLE
REST API: Create user request fails without edit-user- permissions

### ISSUE THREAD

**Issue by sasakura-sora** [RocketChat/Rocket.Chat#7351]
Rocket.Chat Version:  0.56.0
Running Instances: 2+ 
DB Replicaset OpLog: enabled
Node Version: 4.5

1. Using the REST API with a user with the Bot role.   The Bot role has been granted the permission User-Create.
2. Send a User/Create request with every optional property defined (including a non-default role) except customFields.
3. Response is a 400 with error: error-not-allowed **but the user is still created**.

In order to receive a 200 without errors the Bot role must be granted:
- edit-other-user-active-status
- edit-other-user-info
- edit-other-user-password

The request should should either fail without the permissions above and not create the user or not require those permissions on-top of User-Create.

I haven't been able to check what status the newly created user is in after calling create without the edit permissions when receiving a 400.

**Comment by graywolf336** [comment]
@sasakura-sora We would love to have a pull request which fixes this. Or a pull request which updates the documentation that states those are requirements to use until it is fixed. Thanks!

**Comment by theorenck** [comment]
explain and close
