### ISSUE TITLE
Deactivation of "post-readonly" does not have any effect

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#7356]
Rocket.Chat Version: 0.56.0
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: 4.5.0

**Background** 
I like to establish a "news" channel, which is read-only. Just a subset of users (e.g. bots) should have the permission to post to that channel.

**Issue**
When an admin prohibits an user to post in read-only channels by detaching the privilege of the related role (e.g. removing the right from the bot role), it does not work. The user is still able to post messages in read-only channels.

**Steps to reproduce**
1. Add "poste-readonly" to role bot
2. Create new user; role=user, bot
3. Create new channel by admin, invite user
4. Set channel properties: read only = true
5. login as user
6. user is able to write messages into the channel
7. verification by another test user that the channel is read only
8. remove "poste-readonly" from role bot
9. user has still the right to post messages to channel => BUG?

**Comment by MartinSchoeler** [comment]
As a workaround for this you can unset and then set the room to `read only` again after removing the `post-readonly` permission

**Comment by timkinnane** [comment]
Duplicates #4769 - I have a fix for this and will submit PR next week.

**Comment by engelgabriel** [comment]
Closed in favor of older issue #4769
