### ISSUE TITLE
Feature: Integration of polls / surveys

### ISSUE THREAD

**Issue by pixelbrackets** [RocketChat/Rocket.Chat#7366]
Hi,

a very common feature I expect in every social communication webplatform are surveys / polls. This feature is requested from time to time in the issue tracker and elsewhere (eg. #3244 #3615). 

All tickets eventually suggest to use a userscript as long as this is no core feature (https://gist.github.com/sampaiodiego/db4b60717e7ac0051024dde23c6a902e).

So my question is: Are pools ever gonna be integrated natively into Rocket.Chat? 
If no: fair enough. The discussions in the last tickets indicated that there is work in progress. A "no" statement would end speculations.
If yes: Is there a timeframe? Is there something I (or other people) could do to help you guys with this, eg. code, sponsoring money, time?

**Comment by graywolf336** [comment]
Will this become a feature of the core rocket.chat? No. Will something be added to Rocket.Chat in the future (2 months or so) that will make this easier? Yes. See #6890 for some details of what was discussed and there is a lot to come as more gets detailed.

So, I am going to close this as the answer to your question is no. However, be watching that issue for when the final solution is added.
