### ISSUE TITLE
Custom home (login destination)

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#7367]
Why don't we offer admins the ability to define a custom login destination - it could be a simple setting in 'General' that allows you to select a channel or the 'home' page to be the first place people land when they login.

*Personally, I rarely have use for the home page content defined in Layout > in most cases I would just set the destination to '#general' 

q./

**Comment by geekgonecrazy** [comment]
I believe this is what this issue is aiming for as well: #6794

**Comment by designgurudotorg** [comment]
Looks like all the action on this is here: https://github.com/RocketChat/Rocket.Chat/pull/7350
