### ISSUE TITLE
Links not browsable on iOS in the Cordova App

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#7368]
Using the latest version of the original/Cordova iOS app, when i click on any link the page opens within the app itself (instead of Safari) and can't be scrolled plus there's no browser nav so I can't get back to the RC app without manually closing the app and then re-opening it!

Massive UX flaw - is this noted in any other issues? Couldn't find anyone else's posts here about it on GitHub.

q./

**Comment by jszaszvari** [comment]
theres a PR that has not been merged yet that appears to fix this 


https://github.com/RocketChat/Rocket.Chat/pull/7205

**Comment by graywolf336** [comment]
Closing as #7205 has been merged. Please test with the latest `develop` version and open this issue again if you run into problems again.
