### ISSUE TITLE
Dialog boxes are not responsive (delete, upload, etc..)

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7369]
Rocket.Chat Version: 0.56

Screenshots:
![2017-06-29 17_12_19-jump list for dbeaver](https://user-images.githubusercontent.com/23452628/27692225-d06878e2-5cee-11e7-81e5-6a623b787a28.png)

![image](https://user-images.githubusercontent.com/23452628/27692254-e4c46828-5cee-11e7-8914-a9a31810039c.png)

If the window is sized down to a small width, the dialog boxes for "Delete Message" and "Upload file, audio, image" is not responsive.

**Comment by rodrigok** [comment]
@danieljhochman @karlprieb will work on this and fix until friday (07/07)
