### ISSUE TITLE
Webhook: process_incoming_request: unable to skip/ignore requests without error (400)

### ISSUE THREAD

**Issue by fmuecke** [RocketChat/Rocket.Chat#7374]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 	v4.8.1

**The situation:**

- We need to process an incoming webrequest from MS Team Foundation Server (v2017.1)
- We want to process only certain requests (=skip/ignore all others)

**What we've tried:**

- If we return with `{ error: { success: true, message: 'hodor' } }` the request is answered  with `bad request` which will lead to a **disabled** webhook on the TFS side after a few requests (too many errors).
    ![image](https://user-images.githubusercontent.com/7921024/27725802-4877be68-5d78-11e7-827b-3f9ba493cc0a.png)

- If we return an empty result, we get spammed all over in the destination channel.
    ![image](https://user-images.githubusercontent.com/7921024/27725770-2b17e456-5d78-11e7-9310-5d5c4796b55b.png)

*How can we answer the request with `success` and avoid getting an empty message written to the channel?*

**Comment by fmuecke** [comment]
I believe it should be easily possible to quiet rocket.chat if it receives empty messages.

**Comment by graywolf336** [comment]
This is possible. Your outgoing integration must explicitly return false from either `prepare_outgoing_request` ([see source](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/lib/triggerHandler.js#L635-L638)) or `process_outgoing_response` ([see source](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/lib/triggerHandler.js#L680-L683)).

**Comment by fmuecke** [comment]
Yea, sure, that's what the documentation says for **out**going webhooks.
But I don't see how this is going to work with **incoming** WebHooks.
Or am I missing something here?
