### ISSUE TITLE
Ability to change base upload uri via AdminCP

### ISSUE THREAD

**Issue by anhld** [RocketChat/Rocket.Chat#738]
Current base upload uri is `/ufs/rocketchat_uploads/` Can we make it configurable via AdminCP?
##

**Comment by shtefcs** [comment]
:+1:

**Comment by shtefcs** [comment]
Or just put some generic name for upload folder, like `uploads`

**Comment by sunnipaul** [comment]
I even prefer per room upload folder.

**Comment by shtefcs** [comment]
@sunnipaul good idea

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
