### ISSUE TITLE
Automate Builds for Windows

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#7381]
We have a few manually zipped up windows builds.  But not automated

**Comment by rdutina** [comment]
Where I can find Rocket.Chat releases for Windows Server 2012?

**Comment by geekgonecrazy** [comment]
Currently the only way is from source.  The builds were old versions of Rocket.Chat and have been removed.  We are working on automating the builds for windows still

**Comment by rdutina** [comment]
Hi,

is there any written procedure or instructions on how to do that?

For version 0.36 I’ve been following https://rocket.chat/docs/installation/manual-installation/windows-server <https://rocket.chat/docs/installation/manual-installation/windows-server> procedure but for newest RocketChat release, I cannot find anything under “the Rocket.Chat releases page”. I would appreciate any help or guideline you can provide me with…

Thanks



Regards,

MSc. Radoslav Dutina

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as the policy has now been adopted to not officially support Windows server setups. If anybody feels the urge to contribute a [community-supported guide](https://rocket.chat/docs/installation/community-supported-installation/): feel free :)

Cheers
Thomas

**Comment by JordanGithub7** [comment]
hi @geekgonecrazy  have you don the builds for windows? Is there any experience on it?

**Comment by geekgonecrazy** [comment]
As stated above we don't support windows
