### ISSUE TITLE
Problem assigning channel/users over REST API: "Invalid Room"

### ISSUE THREAD

**Issue by pjotrek-b** [RocketChat/Rocket.Chat#7382]
I've written an importer which adds new channels to a Rocket.Chat server and assigns a list of (existing) users to it, using the REST API (in PHP).

It works fine, but when a user is logged in while being invited to a channel (by the importer) it cannot enter the room, but a message "**Invalid Room**" is displayed.

When refreshing the browser client a few times, or logging out-and-back-in again, the user can join and use the channel as expected.

I could not find any documentation or issue about this.
Is there any way I can force the clients to update their channel/users after I've changed it using the REST API?

Grateful for any hints :smile:
Thank you in advance!

> Rocket.Chat Version: v0.56.0
> Running Instances: 1
> DB Replicaset OpLog: Enabled
> Node Version: v4.8.1

**Comment by graywolf336** [comment]
Closing this as I can't seem to reproduce. Can you provide extremely basic steps to reproduce on a brand new instance when you open this issue again? Thanks!
