### ISSUE TITLE
rocket.chat v0.57 has different default database name - crashes docker container

### ISSUE THREAD

**Issue by achaiah** [RocketChat/Rocket.Chat#7384]
Rocket.Chat Version: 0.57.0-rc.3

It looks like someone has renamed the default database name from 'db' to 'mongo' in the newest version (0.57.0-rc.3) and now docker deployments are crashing because they're looking for / linking to the wrong db. This should be reverted or at least provide a warning / fallback when the new mongo db name is not found. Docker deployments with old db will fail because of the renaming.

```
/app/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [mongo:27017] on first connect
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    - - - - -
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
```

P.S. docker.chat v0,56 works fine.

**Comment by geekgonecrazy** [comment]
This is having issues connecting to the host not to the database.  You'll need to check your docker command.  

if you mongo is running with a container of the name `db` you'll need to do `docker run -d --link db:db {restofcommandhere like normal}`

**Comment by achaiah** [comment]
OK sorry I may not have been exact in my description. That is correct... the default host has changed in the latest code.  `docker run -d --link db:db` does not work any more in 0.57 while it does for 0.56.  That's a confusing change that breaks docker deployment.

**Comment by geekgonecrazy** [comment]
@achaiah check your MONGO_URL environment variable too.  

We don't control the name of the mongo container.

So first what ever you mongo container is named you do:
`docker run -d --link {your mongo container name}:db`
or 
`docker run -d --link {your mongo container name}:{your mongo container name}`

After you link it... you need to make sure you MONGO_URL is correct
`docker run -d --link {your mongo container name}:db -e MONGO_URL=mongodb://db/rocketchat rocketchat/rocket.chat:0.56.0`

or of course swap db in both cases with {your mongo container name}

**Comment by achaiah** [comment]
> We don't control the name of the mongo container.

Yes, I'm aware of that. However, something internal to the rocket.chat docker container used to point at a default mongo container called `db`.  I suppose it's the `MONGO_URL` property?  Previously, starting up a mongo container with `--link db:db` was sufficient to have rocket.chat docker container run with default settings. However, starting with v 0.57 this is no longer the case.

Basically what I'm saying is this:  I had a mongo db container and rocket.chat container running no problem.  I upgraded rocket.chat to v0.57_rc3 _without touching the mongo db container_ and rocket.chat can no longer start.  When I downgrade rocket.chat back to 0.56 the connection problem goes away.  So it looks like a setting has been changed that requires a separate restart of the mongo db container.  But instead of calling `--link db:db` what should the new mapping be that rocket.chat v0.57_rc3 is expecting?

**Comment by geekgonecrazy** [comment]
Here's the dockerfile on 0.56.0 - https://github.com/RocketChat/Rocket.Chat/blob/0.56.0/.docker/Dockerfile#L29

0.57.0-rc.3 - https://github.com/RocketChat/Rocket.Chat/blob/0.57.0-rc.3/.docker/Dockerfile#L29

**Comment by achaiah** [comment]
Hmm well that's the thing, the command hasn't changed since I first started using rocket.chat (v 0.52).  Instead of linking containers directly (because it's brittle as heck) I use a docker bridge network. So the commands in order are:
`docker network create --driver bridge caddynet`
`docker run --name db --network=caddynet --restart=on-failure:10 -v /data/rocket_db:/data/db -d mongo:3.2 mongod --smallfiles`
`docker run --name rocketchat  --network=caddynet --restart=on-failure:10 -d rocket.chat`

... of course for v0.57 I replace the image name with the appropriate `rocketchat/rocket.chat:version`

I keep the db container running and just bring up new instances of rocket.chat as they become available. Every upgrade worked fine until v0.57.

**Comment by geekgonecrazy** [comment]
@achaiah ah I think I got it!

I'm guessing you initially used `rocket.chat:0.52.0`. Then at this point or some other point you might have seitched to `rocketchat/rocket.chat:0.57.0`

https://github.com/RocketChat/Docker.Official.Image/blob/master/Dockerfile#L33 the community managed one there appears to have db in the MONGO_URL

**Comment by achaiah** [comment]
Aha, that's it! Strange, I guess I was under the impression that since it was an official image there would be no differences between it and the `rocketchat/rocket.chat:version` build.  I only used rocketchat/rocket.chat build because I wanted to try the latest RC and the "official" release didn't have any RC builds. What would be the best way for me to proceed then?  Should I pass `MONGO_URL=mongodb://db:27017/meteor` as an environment variable to the RC docker image?  Also, any way to resolve the inconsistency with the community managed rocket.chat image?

Thanks

P.S. I believe all documentation for rocket.chat refers to `mongodb://db:27017` as the correct string and I have not seen `mongodb://mongo:27017` mentioned anywhere.

**Comment by geekgonecrazy** [comment]
@achaiah best way forward would be exactly as you said to specify the environment variable. 

I would always recommend to use an environment variable to set the path and never to rely on environment variable set.

As to correcting it... Problem is now changing it will result in more cases like your very own.

I'll create a ticket for unifying connection strings.
