### ISSUE TITLE
Failed to get access to local media: audio,vedio when open video conference in Rocket chat

### ISSUE THREAD

**Issue by kyle-kai** [RocketChat/Rocket.Chat#7388]
Rocket.Chat Version: 0.55.0-develop
Running Instances:  localhost
DB Replicaset OpLog: 
Node Version: 4.7.3 - x64

when I set the video conference configuration as the following below, I start jitsi video conference it comes an error:Failed to get access to local media(audio, video), but when I satrt it in an new window, it works fine, how can I fix the problem, I want to start video conference in rocket chat?

<img width="1346" alt="1" src="https://user-images.githubusercontent.com/29189686/27783647-9c52eaec-6009-11e7-8ae5-1d9f88e56ba0.png">

<img width="546" alt="2" src="https://user-images.githubusercontent.com/29189686/27783660-aa3530de-6009-11e7-8a08-109ef9c0f528.png">

<img width="1657" alt="3" src="https://user-images.githubusercontent.com/29189686/27783985-f61e1a82-600a-11e7-8bc4-bdac15116863.png">

<pre><code> 
[modules/RTC/RTCUtils.js] <t.value>:  Get media constraints Object
2lib-jitsi-meet.min.js:2 [Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
(anonymous) @ lib-jitsi-meet.min.js:2
Logger.js:125 [modules/RTC/RTCUtils.js] <>:  Failed to get access to local media. Error  NavigatorUserMediaError Object
r @ Logger.js:125
Logger.js:125 [modules/xmpp/strophe.jingle.js] <new t>:  Configured STUN servers:  Array(3)
Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  Lip-sync enabled !
Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  (TIME) Strophe connecting:	 815.0200000000001
Logger.js:125 [conference.js] <>:  failed to create local tracks Array(2)0: "audio"1: "video"length: 2__proto__: Array(0) r
i @ Logger.js:125
Logger.js:125 [modules/RTC/RTCUtils.js] <t.value>:  Get media constraints Object
Logger.js:125 [modules/RTC/RTCUtils.js] <>:  Failed to get access to local media. Error  NavigatorUserMediaError Object
r @ Logger.js:125
Logger.js:125 [conference.js] <>:  failed to create local tracks Array(1) r
i @ Logger.js:125
Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  (TIME) Strophe connected:	 1955.1300000000003
Logger.js:125 [modules/xmpp/xmpp.js] <t.value>:  My Jabber ID: 4f727a27-52bb-4045-ad34-39726c44366c@dlingvideo.phicomm.com.cn/cc401e62-4a22-44f2-9c9a-
</code></pre>

**Comment by MartinSchoeler** [comment]
@kyle-kai  This could be happening because of this https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

You can see this on the log you sent `[Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

Could you test this again with another browser?

**Comment by MartinSchoeler** [comment]
Closing due lack of updates.
