### ISSUE TITLE
Is it possible for administrator to remove other users' messages?

### ISSUE THREAD

**Issue by homologus** [RocketChat/Rocket.Chat#739]
Hello,

 I am a newbie with rocket.chat and love the program.

Couple of questions - 

I am logged in as an administrator and I cannot remove messages from others in the chat/direct message area. Is that how the chat is currently implemented or is it my lack of understanding of all knobs?

Is it possible for someone to include others in listen-only mode to a private room? I like to have only a few assigned speakers and many other listeners.

Best, M.

**Comment by marceloschmidt** [comment]
Removing others messages is currently possible only if deleting that user, through Administration / Users.

New tasks related to this issue: 

- [ ] Delete user messages (adminstrator)
- [ ] Create room permissions for read-only / speak

**Comment by IQ2022** [comment]
can we have permisions set for admin to create moderators and to ban/kick users from channels? also limit Channel creation only to Admin, unless users are authorized to do so.

**Comment by marceloschmidt** [comment]
We depend on #292 for moderators

**Comment by marceloschmidt** [comment]
Create room permissions for read-only / speak: #825
