### ISSUE TITLE
can't create channels with dots in name using slash command

### ISSUE THREAD

**Issue by d-ushakov** [RocketChat/Rocket.Chat#7391]
Rocket.Chat Version: 0.57.0-rc.1 (reproduced for 0.56.0 too)
Running Instances: 4
DB Replicaset OpLog: Enabled
Node Version: v4.8.2

Can't create channels with dots in name using slash command. Same channel can be created via UI.

Scenario:
1. /create "#test.test.test"
2. repeat step 1 again

Expected:
Channel "test.test.test" created.

Actual:
Channel "test" created. On second attempt it fails with "The channel #test already exists."

Workaround:
change packages/rocketchat-slashcommands-create/server.js line 15 to add dot into regexp:
from
    const regexp = /#?([\d-_\w]+)/g;
to
    const regexp = /#?([\d-_.\w]+)/g;

Proper fix should re-use RocketChat.settings.get('UTF8_Names_Validation').

**Comment by Broutard** [comment]
Same issue with /invite-all-from /invite-all-to
