### ISSUE TITLE
Unread messages on top in searchbar

### ISSUE THREAD

**Issue by mstruebing** [RocketChat/Rocket.Chat#7393]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Hello I would love to know if it would be possible to integrate the search feature (ctrl+k) comparatively  to the one in slack.
I miss that the latest unread channels and private messages are not on top of this search bar after pressing this shortcut and so they aren't instant selectable - I have to leave the keyboard and scroll the message list up and down in order to see where new stuff happens.

Thx in advance

Edit:
PageUp and PageDown also doesn't scroll the current channel up and down :)

**Comment by M-Krieger** [comment]
I definitely would like to have this too. As a previously slack user I miss that feature very much.

**Comment by theorenck** [comment]
On the current version, the behavior is fixed, please let us know if you're still having this problem. Thanks.
