### ISSUE TITLE
LiveChat Switch Department

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#7397]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

There is a bug in switching dept.
Conversation closed is not noticed by agent and even after dept. change previous agent keeps on receiving messages. The department switching just doesn't work out perfectly.

**Comment by sacOO7** [comment]
Any updates? Please !!!!

**Comment by cenourinha** [comment]
We have verified this bug. When we, as livechat agent, use the "Forward" option, Rocket.chat doesn't respect the routing method "Guest pool". Instead it seem to redirect to a random live agent.

I think this should alert the live agents for that department and then allow them to accept the incoming live chat request.

**Comment by renatobecker** [comment]
Hi @sacOO7!
Which `routing method` are you using?
I've tested this issue in both `Least Amount` and `Guest Pool` routing methods.
As @cenourinha described previously, using `Guest Pool` method, the `Forward` option is not sending the chat back to the`Incoming Livechats` and, yes, this is not a correct behaviour, so I will take a look on this.
But, using the `Least Amount` routing method, the redirecting is working as expected, so I suggest you to test our latest version.
Let me know if in our most recent version the issue has not been fixed, giving me more details about your tests.

Thanks.

**Comment by tctovsli** [comment]
I have this issue with 0.66.0, installed from source.
When user uses "Switch department", the messages still goes to the same agent as before, even if that agent is in some other department!
This also persists between browser sessions, so there is currently no way for the user to start a new chat with some other department without asking the agent to forward the chat.

**Comment by renatobecker** [comment]
Hi @tctovsli!
This issue was already fixed by #11011, but unfortunately it was not included on **0.66.**.
I'll make sure to add this fixed in our next version -> **0.67**.
