### ISSUE TITLE
LiveChat User registration 

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#7398]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

If user is registered in a particular department and conversation is closed.
Second time user with same username and email cant login into another department.
Agent from previous department is assigned again, it's like user login to previous department without considering department parameter.

**Comment by sacOO7** [comment]
Any updates? Please !!!!

**Comment by renatobecker** [comment]
Hi @sacOO7!
Sorry to answer you late, I will work on this issue to fix it as soon as possible.
