### ISSUE TITLE
LiveChat Agent Presence

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#7399]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Agent is shown available to user if he logs out with status other than invincible before logout.

**Comment by sacOO7** [comment]
Any updates? Please !!!!

**Comment by renatobecker** [comment]
Hi @sacOO7,
I tried to simulate this issue in the same way you describe, but it's not happening.
So, I wonder if you have tried this again in recent versions?
I'll be waiting for your feedback.

Thanks!
