### ISSUE TITLE
Fully test on Mobile and fix bugs

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#74]

**Comment by riaan53** [comment]
Hi,

Will this include cordova? Will you also support offline mode (which is a important for cordova) with ground db? 

I have tested with iOS cordova and it doesnt look bad, with a bit of tweaks here and there you can have full iOS and Android support - which will be fantastic :)

Regards,
Riaan

**Comment by rodrigok** [comment]
I think that we can create a cordova version first and then start native versions.

**Comment by marceloschmidt** [comment]
Can we close this?

**Comment by engelgabriel** [comment]
yes. to generic.
