### ISSUE TITLE
Feature request: database sanitizing 

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#7400]
Due to previous problems and some crashes, I get a lot of errors in the log that indicate things that are just wrong in the database. Example included below. Perhaps something that walks through the database and weeds out impossible things would be nice 

`Empty Room for Subscription { _id: 'NmwtMsTEdpd4gREZk',
  rid: '966ncuZr7keAvtr8NeiiFSTdA4GJuLTPrW',
  ts: Wed Nov 23 2016 12:58:38 GMT+0100 (CET),
  ls: Thu Nov 24 2016 02:57:45 GMT+0100 (CET),
  open: false,
  _updatedAt: Fri Jun 30 2017 16:08:43 GMT+0200 (CEST),
  name: 'redacted',
  t: 'd',
  alert: false,
  unread: 0,
  u: { _id: 'eiiFSTdA4GJuLTPrW', username: 'redacted' },
  meta: { revision: 0, created: 1499161473796, version: 0 },
  '$loki': 2085,
  _room: undefined,
  _user:
   { _id: 'eiiFSTdA4GJuLTPrW',
     createdAt: Tue Sep 08 2015 07:43:05 GMT+0200 (CEST),
     services: { password: [Object], email: [Object], resume: [Object] },
     emails: [ [Object] ],
     status: 'online',
     active: true,
     name: 'redacted',
     lastLogin: Tue Jul 04 2017 11:45:30 GMT+0200 (CEST),
     statusConnection: 'online',
     utcOffset: 10,
     username: 'redacted',
     avatarOrigin: 'upload',
     settings: { preferences: [Object] },
     roles: [ 'user' ],
     language: 'en',
     type: 'user',
     _updatedAt: Tue Jul 04 2017 11:45:30 GMT+0200 (CEST),
     meta:
      { revision: 3,
        created: 1499161472927,
        version: 0,
        updated: 1499161530398 },
     '$loki': 72 },
`

Rocket.Chat Version: 0.57.0-rc.2
Running Instances: 3
DB Replicaset OpLog: Enabled
Node Version: v4.6.1

**Comment by Sing-Li** [comment]
An ongoing GSoC project will address this functionality.   See:  

https://rocket.chat/docs/contributing/google-summer-of-code-2018/

And to be continued pending GSoC 2019.
