### ISSUE TITLE
502 bad gateway after every reboot

### ISSUE THREAD

**Issue by davidverhage** [RocketChat/Rocket.Chat#7402]
Rocket.Chat Version: 0.57.0 [known due to manual installation]
Running Instances: ??
DB Replicaset OpLog: ??
Node Version: v4.2.6 [extracted from terminal by: node -v]
?? - information unavailable due to the following issue: 

After rebooting the server even with rocket.chat as service I keep receiving bad gateway on the nginx machine. Port via proxy has been set and works when manully running node main.js but in the forever setting (digital ocean explanation) I cannot connect to the platform.

Other subdomains do work so the server build is clearly functional and again - running node main.js sets up everything nicely but when closing terminal screen node stops running, thats why I turned to the forever service solution.

Anyone know or see what I may have missed in this case / is this a known bug/issue? please link me to a working solution as I am integrating this with a cms - it is a must that it is up and running.

Kind regards

**Comment by geekgonecrazy** [comment]
If you you get 502 that just simply means that nginx cannot connect to Rocket.Chat.  Which means one of two things...
1. Rocket.Chat isn't running
2. Rocket.Chat is still starting.

Based on your description it sounds like Rocket.Chat isn't running.

**Comment by waveyuk** [comment]
Hi.
I too am getting the bad gateway 502 error since my Snap updated this evening. I am seeing the following in my terminal when issuing `sudo systemctl status snap.rocketchat-server.rocketchat-server.service`

`● snap.rocketchat-server.rocketchat-server.service - Service for snap application rocketchat-server.rocketchat-server
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-07-05 00:13:49 BST; 4min 33s ago
 Main PID: 1446 (startRocketChat)
    Tasks: 11
   Memory: 377.9M
      CPU: 20.331s
   CGroup: /system.slice/snap.rocketchat-server.rocketchat-server.service
           ├─1446 /bin/bash /snap/rocketchat-server/671/bin/startRocketChat
           └─1967 node /snap/rocketchat-server/671/main.js

Jul 05 00:15:59 gbmnet snap[1446]:   at meteorInstall.server.startup.migrations.xrun.js (/snap/rocketchat-server/671/programs/server/app/app.js:4808
Jul 05 00:15:59 gbmnet snap[1446]:   at fileEvaluate (packages/modules-runtime.js:197:9)
Jul 05 00:15:59 gbmnet snap[1446]:   at require (packages/modules-runtime.js:120:16)
Jul 05 00:15:59 gbmnet snap[1446]:   at /snap/rocketchat-server/671/programs/server/app/app.js:9754:1
Jul 05 00:15:59 gbmnet snap[1446]:   at /snap/rocketchat-server/671/programs/server/boot.js:303:34
Jul 05 00:15:59 gbmnet snap[1446]:   at Function._.each._.forEach (/snap/rocketchat-server/671/node_modules/underscore/underscore.js:153:9)
Jul 05 00:15:59 gbmnet snap[1446]:   at /snap/rocketchat-server/671/programs/server/boot.js:128:5
Jul 05 00:15:59 gbmnet snap[1446]:   at /snap/rocketchat-server/671/programs/server/boot.js:352:5
Jul 05 00:15:59 gbmnet snap[1446]:   at Function.run (/snap/rocketchat-server/671/programs/server/profile.js:510:12)
Jul 05 00:15:59 gbmnet snap[1446]:   at /snap/rocketchat-server/671/programs/server/boot.js:351:11
`

**Comment by waveyuk** [comment]
I have just noticed something else... Earlier when running `snap refresh` it stated it was upgrading to 0.57.0.
However... if I now do a `snap list` it's stating it's running 0.56.0
`Name               Version  Rev   Developer   Notes
core               16-2     2312  canonical   -
rocketchat-server  0.56.0   671   rocketchat  -`

I'm not very confused as `snap info rocketchat-server` shows

`tracking:           stable
installed:          0.56.0 (671) 169MB -
refreshed:          2017-05-17 02:10:06 +0100 BST
channels:
  latest/stable:    0.56.0         (671) 169MB -
  latest/candidate: 0.57.0         (801) 162MB -
  latest/edge:      0.57.0-develop (807) 161MB -`

**Comment by shubhampatel812** [comment]
I also facing the same issue.

**Comment by daneb255** [comment]
Hey!
Here ist the same issue with the same version.

Name               Version  Rev   Developer   Notes
core               16-2     2312  canonical   -
rocketchat-server  0.56.0   671   rocketchat  -

checked the status: active(running)
checked nginx: running
checked ports: ok (3000)

**Comment by lchojnowski** [comment]
Here's the same issue :-).

**Comment by roed** [comment]
I'm having the same issue. When I view the status, it says something about a migration:
 Not migrating, control is locked. Attempt 1/30.. etc

**Comment by 1stposition-ad** [comment]
Same issue here ... also using snap, hosted by digital ocean, ...

**Comment by lxsndl** [comment]
In case it helps, journalctl output of the problem:

`Jul 05 09:08:34 chat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Jul 05 09:08:34 chat /usr/bin/snap[972]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2.24]): older than "/usr/bin/
Jul 05 09:08:36 chat snap[972]: Mongo is not available, can't start. Waiting 10 seconds and trying again
Jul 05 09:08:46 chat snap[972]: Checking if oplog has been enabled, and enabling if not
Jul 05 09:08:47 chat snap[972]: MongoDB shell version: 3.2.7
Jul 05 09:08:47 chat snap[972]: connecting to: test
Jul 05 09:08:53 chat snap[972]: Will load cache for users
Jul 05 09:08:53 chat snap[972]: 9 records load from users
Jul 05 09:08:53 chat snap[972]: Will load cache for rocketchat_room
Jul 05 09:08:53 chat snap[972]: 27 records load from rocketchat_room
Jul 05 09:08:53 chat snap[972]: Will load cache for rocketchat_subscription
Jul 05 09:08:53 chat snap[972]: 62 records load from rocketchat_subscription
Jul 05 09:08:53 chat snap[972]: Will load cache for rocketchat_settings
Jul 05 09:08:53 chat snap[972]: 487 records load from rocketchat_settings
Jul 05 09:08:55 chat snap[972]: Updating process.env.MAIL_URL
Jul 05 09:08:57 chat snap[972]: Will load cache for rocketchat_permissions
Jul 05 09:08:57 chat snap[972]: 71 records load from rocketchat_permissions
Jul 05 09:08:57 chat snap[972]: Will load cache for rocketchat_roles
Jul 05 09:08:57 chat snap[972]: 10 records load from rocketchat_roles
Jul 05 09:08:59 chat snap[972]: LocalStore: store created at
Jul 05 09:09:03 chat snap[972]: Exception in callback of async function: Error: [Can't find migration version 98]
Jul 05 09:09:03 chat snap[972]:   at Object.Migrations._findIndexByVersion (/snap/rocketchat-server/671/programs/server/packages/rocketchat_migrations.js:405:
Jul 05 09:09:03 chat snap[972]:   at Object.Migrations._migrateTo (/snap/rocketchat-server/671/programs/server/packages/rocketchat_migrations.js:272:22)
Jul 05 09:09:03 chat snap[972]:   at Object.Migrations.migrateTo (/snap/rocketchat-server/671/programs/server/packages/rocketchat_migrations.js:201:20)
Jul 05 09:09:03 chat snap[972]:   at meteorInstall.server.startup.migrations.xrun.js (/snap/rocketchat-server/671/programs/server/app/app.js:4808:24)
Jul 05 09:09:03 chat snap[972]:   at fileEvaluate (packages/modules-runtime.js:197:9)
Jul 05 09:09:03 chat snap[972]:   at require (packages/modules-runtime.js:120:16)
Jul 05 09:09:03 chat snap[972]:   at /snap/rocketchat-server/671/programs/server/app/app.js:9754:1
Jul 05 09:09:03 chat snap[972]:   at /snap/rocketchat-server/671/programs/server/boot.js:303:34
Jul 05 09:09:03 chat snap[972]:   at Function._.each._.forEach (/snap/rocketchat-server/671/node_modules/underscore/underscore.js:153:9)
Jul 05 09:09:03 chat snap[972]:   at /snap/rocketchat-server/671/programs/server/boot.js:128:5
Jul 05 09:09:03 chat snap[972]:   at /snap/rocketchat-server/671/programs/server/boot.js:352:5
Jul 05 09:09:03 chat snap[972]:   at Function.run (/snap/rocketchat-server/671/programs/server/profile.js:510:12)
Jul 05 09:09:03 chat snap[972]:   at /snap/rocketchat-server/671/programs/server/boot.js:351:11`

**Comment by gubiq** [comment]
#7409 fixed it for me.

**Comment by johnlund** [comment]
:arrow_up: fixed it for me too. Thanks @gubiq

**Comment by amenk** [comment]
@gubiq @johnlund does not seem to be a permanent fix

**Comment by daneb255** [comment]
for the moment it´s okay :) @gubiq thanks!

**Comment by amenk** [comment]
@daneb255 Keep an eye on it ... guessing it will recur after 1-2 hours

**Comment by daneb255** [comment]
Running just only few minutes. Then snap automatically switched back to 0.56

**Comment by 1stposition-ad** [comment]
@amenk i can confirm, after 2 hours the problem came back.

**Comment by GenericUK** [comment]
Same for me running on Raspbian Jessie. RocketChat status says running but it's not starting and port is not being opened.

This is the log from last nights upgrade

Jul 04 22:27:27 raspberrypi snap[10166]: ➔ System ➔ startup
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ +------------------------------------------------------+
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |                    SERVER RUNNING                    |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ +------------------------------------------------------+
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |                                                      |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |  Rocket.Chat Version: 0.57.0                         |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |       NodeJS Version: 4.8.1 - arm                    |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |             Platform: linux                          |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |         Process Port: 3000                           |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |             Site URL: https://chat.boardmark.co.uk/  |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |     ReplicaSet OpLog: Enabled                        |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |          Commit Hash: 3e3ae86025                     |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |        Commit Branch: HEAD                           |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ |                                                      |
Jul 04 22:27:27 raspberrypi snap[10166]: ➔ +------------------------------------------------------+

sudo snap list
Name               Version  Rev   Developer   Notes
core               16-2     2314  canonical   -
rocketchat-server  0.56.0   673   rocketchat  -

sudo snap revert rocketchat
error: cannot revert "rocketchat": no revision to revert to

**Comment by lchojnowski** [comment]
Looks like this is problem spreads over autoupdates :-(.

**Comment by geekgonecrazy** [comment]
Any of those experiencing issues with the snaps i'll repost from: #7409 

> Sorry for the trouble guys.
> 
> Basically.. 0.57.0 came out we released the snap. Revision 801. We then had a few people encounter issues with avatars. So we halted the roll out.
> 
> Unfortunately... we didn't stop it in time. Anyone that had already upgraded to 0.57.0 during the window it was deployed.. was then rolled back to 0.56.0 when we stopped the roll out.
> 
> Since its listed as the newest snap available... it keeps updating your snap regardless of what revision you install.
> 
> I've gone ahead and released it back so revision 801 is the latest. We have an avatar fix in the works and will be able to roll it out in a very short amount of time to fix anyones avatars that broke.
> 
> Sorry again for the troubles.

**Comment by johnlund** [comment]
Thank you @geekgonecrazy

**Comment by GenericUK** [comment]
Thanks, `sudo snap refresh rocketchat-server` has now installed Version: 0.57.0 and is working fine.

**Comment by geekgonecrazy** [comment]
This topic kind of got hijacked by snap related discussion.  So I will go ahead and close if.  Original Poster still has issues feel free to re-open or mention me and I can continue to try and help you.

**Comment by clarm060** [comment]
Just wanted to put this out there if you installed Rocket Chat on CentOS7 this could be an issue with SELinux blocking the Nginx Upstream loopback to 127.0.0.1 or Localhost.

you can run : `setsebool -P httpd_can_network_connect 1` which will allow the upstream connection to succeed allowing your proxy to work!

**Comment by geekgonecrazy** [comment]
@clarm060 thanks for sharing!  It would be awesome if you could add as a note to our docs: https://github.com/rocketchat/docs might help others with this problem

**Comment by clarm060** [comment]
Sure I will build a pull request for it.
