### ISSUE TITLE
WordPress OAuth Issues

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7406]
Hi.
I'm trying to get the WordPress OAuth working but with no success. Please could someone guide me as to what information I need to enter into the following fields in RocketChat admin

WordPress URL (currently I have https://public-api.wordpress.com/oauth2/authenticate)
WordPress Id (Currently I have the 5 digit code referenced as Client ID on WordPress App)
WordPress Secret (Currently have the long code referenced as Client Secret)

When I try to log in using Wordpress I get the Authorisation Screen, and I click on "Approve" but get a "Internal Server Error" when the RocketChat server login page reloads.

Rocket.Chat Version:  0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.2

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
