### ISSUE TITLE
WebIRTC issue and call options / Info page loading issue

### ISSUE THREAD

**Issue by josephmiller2000** [RocketChat/Rocket.Chat#7407]
Rocket.Chat Version: 0.57.0
Running Instances:  1
DB Replicaset OpLog: Disabled
Node Version:
![snap_2017 07 05_04h44m46s_004_](https://user-images.githubusercontent.com/24210340/27844272-bf7e86fa-613c-11e7-8fa7-0ed3aae38a93.png)
Its keep saying loading after upgrading to new version.

Audio and video calls are not working. it was working fine before with older version.

Please fix it as soon as possible.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
