### ISSUE TITLE
Rest API method to retrieve all groups in server

### ISSUE THREAD

**Issue by bmduarte** [RocketChat/Rocket.Chat#7408]
Hi!

Currently the rest method channels.list returns all channels in server.
After testing with a full admin account, the method json result doesn't return any groups.
Additionally, the REST method groups.list "lists all of the private groups the calling user has joined".

How can one retrieve all groups in server?

Best regards
Bruno

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Ative
Node Version: v4.8.1

**Comment by graywolf336** [comment]
Currently not possible, but feel free to submit a pull request adding this feature so that it gets added. :+1:
