### ISSUE TITLE
[E-mail notifications] Alert offline users when they are @mentioned or DM'd [$525]

### ISSUE THREAD

**Issue by jclabaugh** [RocketChat/Rocket.Chat#741]
Slack has this function where it will email you direct messages or mentions that are posted while you are offline so you are notified of the message within a specific timeframe so you know you need to respond (or not) using their app.

I suggest mimicking Slack on this feature for a few reasons that I think might make some sense.

if you were to keep the offline messaging frequency simple... either 

a.) after 10 min offline for only @ mentions and DMs or 
b.) not at all _and_ have it user configurable in User Settings, it would keep operational costs down as well as the overall amount of email chatter (lots of messages in short bursts). 

And if you don't allow in-line email responses to these rocket.chat email messages directly from the email client using a URL (like Basecamp & Github do allow), in doing so, you would drive more user traffic, greater overall daily usage and add more 'stickiness' to the app overall, which is what we all want.
##

**Comment by rockneverdies55** [comment]
+1

**Comment by kakawait** [comment]
:+1:  in my use case is only missing *slack* feature

**Comment by mhkeller** [comment]
+1

**Comment by royalaid** [comment]
+1

**Comment by steedos** [comment]
+1 

发自我的 iPhone

**Comment by sunnipaul** [comment]
+1.  Really useful

**Comment by phillip-white-sociomantic** [comment]
+1 definitely needed

**Comment by internalfx** [comment]
+1

**Comment by artisin** [comment]
+1

**Comment by neurobe** [comment]
'email notification upon mention' is an example of what a more generalised Action Manager would do. there is a $500 bounty for that under Calendar. https://github.com/RocketChat/Rocket.Chat/issues/1366

**Comment by engelgabriel** [comment]
I will accept the PR #2112 as a partial solution to this issue now, as I want to merge it asap to avoid greater conflicts with PR #2198

Some comments on what needs to be done still:
- We should not send an email on @all mentions by default, but must be configurable.
- We have to check the statusConnection field.
- We must send emails just to verified addresses.

Also important:
- We would like @jd365 opinion here, as he is one of the main backers of the issue.
- I agree with @jclabaugh about "mimicking Slack on this feature" as much as possible.

**Comment by lwrbakro** [comment]
+1

**Comment by cpitman** [comment]
Any thoughts on making it so that users can reply to these emails? If not, it would be helpful if they were marked with a noreply replyto address.

**Comment by lovetheidea** [comment]
+1

**Comment by CandyOgre** [comment]
If this issue already resolved, why it not closed ? @jclabaugh

**Comment by bhbarbosa** [comment]
Please make "Offline Email Notifications" the same way "Merge private groups with channels". Of course this is an User choice, but at least for me, the default "opt in" for every DM/Mention is a killer. Make a default option come from the server properties.

**Comment by Mte90** [comment]
Any news for that issue?

**Comment by steven-tib** [comment]
I agree with @bhbarbosa about the property from the admin panel/server properties. would be good if we can enable/disable it by default.

Also, the notifications might become disturbing because it can actually flood e-mails if someone starts sending multiple direct messages. It can quickly reach huge amounts of emails. 

Would it be possible to add a "date flag" so the first e-mail notification get sent and then the next emails notifications are not sent within the next 30 minutes (or delay to be defined in the settings)

(I've already got few complaints from my gentle testers so I'm worried about the reaction of real users/customers)

**Comment by rodrigok** [comment]
Can we close this issue? It was implemented already

**Comment by lindoelio** [comment]
Can I work on this issue? It was really implemented?

**Comment by gdelavald** [comment]
I'll close this since it was already implemented. If anyone find problems with this feature please open a new issue.

**Comment by apastuhow** [comment]
@engelgabriel 
> We should not send an email on @ALL mentions by default, but must be configurable.
Was it done? Where can I configure it?
