### ISSUE TITLE
Rocket-chat irc

### ISSUE THREAD

**Issue by navya-uppalapati** [RocketChat/Rocket.Chat#7412]
Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: v4.8.3

How does the irc plugin actually work?
From the administration irc - I enable true and filled in details of host , port and restarted rocket chat.
In the console terminal it says:

I20170705-05:36:46.132(-4)? [irc] validateLogin ->  { type: 'password',
I20170705-05:36:46.132(-4)?   allowed: true,
I20170705-05:36:46.133(-4)?   methodName: 'login',
I20170705-05:36:46.134(-4)?   methodArguments: [ { user: [Object], password: [Object] } ],
I20170705-05:36:46.135(-4)?   user: 
I20170705-05:36:46.135(-4)?    { _id: 'tCzr8paESaWkFRYjj',
I20170705-05:36:46.139(-4)?      createdAt: Wed Jul 05 2017 04:29:45 GMT-0400 (EDT),
I20170705-05:36:46.140(-4)?      services: { password: [Object], email: [Object], resume: [Object] },
I20170705-05:36:46.141(-4)?      emails: [ [Object] ],
I20170705-05:36:46.141(-4)?      type: 'user',
I20170705-05:36:46.142(-4)?      status: 'offline',
I20170705-05:36:46.142(-4)?      active: true,
I20170705-05:36:46.142(-4)?      name: 'admin',
I20170705-05:36:46.143(-4)?      _updatedAt: Wed Jul 05 2017 05:36:25 GMT-0400 (EDT),
I20170705-05:36:46.143(-4)?      roles: [ 'admin' ],
I20170705-05:36:46.144(-4)?      lastLogin: Wed Jul 05 2017 05:03:00 GMT-0400 (EDT),
I20170705-05:36:46.144(-4)?      statusConnection: 'offline',
I20170705-05:36:46.145(-4)?      utcOffset: 2,
I20170705-05:36:46.145(-4)?      username: 'admin',
I20170705-05:36:46.146(-4)?      settings: { profile: {} } },
I20170705-05:36:46.147(-4)?   connection: 
I20170705-05:36:46.147(-4)?    { id: '6ypf2pYS3Xeyh7Ygg',
I20170705-05:36:46.147(-4)?      close: [Function],
I20170705-05:36:46.148(-4)?      onClose: [Function],
I20170705-05:36:46.149(-4)?      clientAddress: 'x.x.x.x',
I20170705-05:36:46.153(-4)?      httpHeaders: 
I20170705-05:36:46.154(-4)?       { 'x-forwarded-for': 'x.x.x.x',
I20170705-05:36:46.154(-4)?         'x-forwarded-proto': 'ws',
I20170705-05:36:46.155(-4)?         host: 'x.x.x.x:3000',
I20170705-05:36:46.155(-4)?         'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
I20170705-05:36:46.156(-4)?         'accept-language': 'en-US,en;q=0.8' } } }

If a send a message in the channel, the console terminal says:

I20170705-05:37:36.586(-4)? [irc] sendMessage ->  userName: admin
I20170705-05:37:36.587(-4)? [irc] ircSendMessageCache.set ->  key: admin,#testing,hello ts: 1499247456580
I20170705-05:37:36.588(-4)? [irc] sendRawMessage ->  PRIVMSG #testing :hello

But I am nowhere connected with my irc host. Not sure how this is exactly working :/ 
Can you please help me in solving this?

**Comment by k0nsl** [comment]
I have never been able to get this to work as well. I run my own IRC network using `charybdis` as IRCd.

If anyone would like to try using my IRC network, then please go ahead. You can get a random server by connecting the `irc.k0nsl.org` round robin, running on standard port 6667 and SSL on port 6697.

**Comment by pokapow** [comment]
Same question: How to use IRC protocole with rocket chat ? I enebled the plugin, I use rizon network, but then ? No answer about it ...

**Comment by rodrigok** [comment]
Should be fixed by #8656 let me know if it was not.
