### ISSUE TITLE
Current version Node is not supported

### ISSUE THREAD

**Issue by greendruid** [RocketChat/Rocket.Chat#7414]
Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0 (by "node --version")

Hello! After I upgraded RC from 0.54.1 to 0.57.0 at both of servers I can't to start Rocket.Chat. I got the next error:
```
➔ rocketchat_logger rocketchat_logger.js:377 System ➔ error
➔ +---------------------------------------------------+
➔ |                    SERVER ERROR                   |
➔ +---------------------------------------------------+
➔ |                                                   |
➔ |  Rocket.Chat Version: 0.57.0                      |
➔ |       NodeJS Version: 6.10.3 - x64                |
➔ |             Platform: linux                       |
➔ |         Process Port: 3000                        |
➔ |             Site URL: https://$URI  |
➔ |     ReplicaSet OpLog: Disabled                    |
➔ |          Commit Hash: 3e3ae86025                  |
➔ |        Commit Branch: HEAD                        |
➔ |                                                   |
➔ |  YOUR CURRENT NODEJS VERSION IS NOT SUPPORTED,    |
➔ |  PLEASE UPGRADE / DOWNGRADE TO VERSION 4.X.X      |
➔ |                                                   |
➔ +---------------------------------------------------+
```
I try to fix permissions and change Node.js version (by "n 4.5"). But has no success :(

**Comment by TwizzyDizzy** [comment]
Well whatever you did, it seems as though you still started RC with NodeJS 6.10.3. It seems as though this is rather a issue on your side, than on RC side.

Cheers
Thomas

**Comment by phuyem** [comment]
Haha, this one is tricky. Here is the easy fix. I even run smootly on node 8.8.0, yay !!

First open .node_version.txt file ( which is located next to main.js ), to know which version you need.

Then force the system to use the same major nodejs.

Here is how  to do on Ubuntu : 

sudo npm install -g n
sudo n 4.8.4

https://rocket.chat/docs/installation/manual-installation/ubuntu
