### ISSUE TITLE
Separate the messages in window by alias (but same user)

### ISSUE THREAD

**Issue by praveenmsp** [RocketChat/Rocket.Chat#7415]
Rocket.Chat Version: All
Running Instances: Any
DB Replicaset OpLog: 
Node Version: 6

Lets say we have single user called chatAdmin, who is posting on behalf of two different users (anonymous) as Agent & Client, the messages posted in the messenger are coming as single timeline instead of separate. 

Below is a sample where chatAdmin is the actual owner/user posting on behalf of two aliases (Susane & agent1). The issue is with message "its 1919191919"

**Susane** @chatAdmin Owner 4:52 PM
Hello

**rocket.cat** 4:52 PM
Good 'aye!, chatAdmin

**Susane** @chatAdmin Admin Owner 4:52 PM
Where is my order
chatAdmin Owner 4:53 PM
User rocket.cat removed by chatAdmin.

**agent1** @chatAdmin Owner 4:53 PM
Give your order number (actually posted by agent1)
its 1919191919 (actually posted by susane, which should come in separate context) 
Its on your way (actually posted by agent1)

Susane @chatAdmin Owner 5:17 PM
hello

**Comment by graywolf336** [comment]
Closing as this is working, please reopen with the exact steps to reproduce this on a brand new installation of Rocket.Chat.

![image](https://user-images.githubusercontent.com/850391/28233305-7e5b4f7e-68bb-11e7-815d-3f15361546c7.png)
