### ISSUE TITLE
Keycloak integration (custom OAuth provider: openID protocol) 

### ISSUE THREAD

**Issue by bakhtizin** [RocketChat/Rocket.Chat#7418]
Rocket.Chat Version:  0.56.0 
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.1 - x64 

Some additional info:
➔  Platform: linux                      
➔  Process Port: 3000                        
➔  Site URL: http://chat.inumio.com:3000 
➔  Doployed via provided docker image

After numerous configuration attempts, I cannot proceed any further. It's definitely has something to do with my lack of knowledge in js and js frameworks. Any help will be much appreciated. I believe that Rocket.Chat is keycloak compatible, there are several closed issues on this topic. I can see active session for user in keycloak administration console (user is authenticated), but redirect takes me back to Rocket.Chat login page. 

I keep recieving following errors (taken from running container log):
```
{"line":"431","file":"oauth.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with keycloak at http://localhost:8080/auth/realms/RocketChat/protocol/openid-connect/token. connect ECONNREFUSED 127.0.0.1:8080","time":{"$date":1499265254399},"level":"warn"}
```
And it is followed by:
```
Exception while invoking method 'login' Error: Failed to complete OAuth handshake with keycloak at http://localhost:8080/auth/realms/RocketChat/protocol/openid-connect/token. connect ECONNREFUSED 127.0.0.1:8080
  at CustomOAuth.getAccessToken (/app/bundle/programs/server/packages/rocketchat_custom-oauth.js:157:17)
  at Object.handleOauthRequest (/app/bundle/programs/server/packages/rocketchat_custom-oauth.js:226:28)
  at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
  at middleware (packages/oauth.js:203:5)
  at packages/oauth.js:176:5
```

My configurations for `Custom OAuth Keycloak` look like this:
```
Enable: True
URL: http://localhost:8080/auth/
Token Path: http://localhost:8080/auth/realms/RocketChat/protocol/openid-connect/token
Identity Path: http://localhost:8080/auth/realms/RocketChat/protocol/openid-connect/userinfo
Authorize Path: http://localhost:8080/auth/realms/RocketChat/protocol/openid-connect/auth
Scope: openid
Token Sent Via: Payload
Id: rocket
......
Username field: username
```

**Comment by assadvirgo** [comment]
@bakhtizin @MartinSchoeler can you please help me setting up Identity Server or if you can guide me how can i write a custom package to handle this.

I get the same error as mentioned by @bakhtizin after some digging I found that Dynabic.Crocket expect a query param code= while IdentityServer is posting "id_token" in body which cann't be accessed in rocket_custom_oauth package via the query string hence an empty token causes the error.

**Comment by ottomMT** [comment]
Could we have a WeChat login, so we could use it in China,thanks a lot

**Comment by bakhtizin** [comment]
After several attempt, I've finally found a solution to my issue.

> Just read the  contents of the existing tickets carefully!  

 Thus, the problem was _(of course)_ my misconfiguration and _(of course)_ it was already answered! In order to get the things working following should be set:

1. Token Path: `/realms/{realm_name}/protocol/openid-connect/token`
2. Identity Path: `/realms/{realm_name}/protocol/openid-connect/userinfo`
3. Authorize Path: `/realms/{realm_name}/protocol/openid-connect/auth`
4. Token Sent Via: `Header`
5. Id: `Correct Client ID from Keycloak administration console`
6. Secret: `Configure Rocket.Chat client as a confidential client and paste here the secret`
7. Username field:  `preferred_username`

**Comment by rackmuthu** [comment]
I trying to integrate the Rocket chat with the keycloak.
My Rocket Chat is 0.63.3v . And my  Keycloak is 4.0.0v.
My Keycloak configuration:
id : rocketchat
Client Protocol: Openind Connect
Access Type : Confidential
Valid Redirect URIs : http://192.168.10.97/_oauth/keycloak

Rocket Chat OAuth Configuration
URL: http://192.168.10.230/auth
Token Path : realms/sample/protocol/openid-connect/token
Identity Path: realms/sample/protocol/openid-connect/userinfo
Authorize Path: realms/sample/protocol/openid-connect/auth
Scope: openid
Token Sent Via: header
Id: rocketchat
Secret: keycloak secret id
Username field: joe (my custome name)

Here sample is my realm name.

But after this configuration the rocket chat login page does not redirect to keycloak page.
And i am not seeing any login rocket chat and keycloak.

How to solve my problem.Any one know the solution, please tell me

**Comment by rackmuthu** [comment]
Finally i was find solution for rocket chat and keycloak integration.
Here i am not write any name for username field in rocket chat keycloak custom oauth.
And another important point is i am using rocket chat 0.63.3 v. 
Here, when i am hitting the rocket chat URL i will never redirect to keycloak login page.
Instead on redirection. i can seen the keycloak button in the rocket chat login screen.


![image](https://user-images.githubusercontent.com/24887166/39989312-3cdbada8-5787-11e8-8f13-7804c2afc3bb.png)

The blue color button is gateway of keycloak login page.
