### ISSUE TITLE
FileSystem Upload Method Results In Internal Server Error

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7420]
Rocket.Chat Version: 0.56
Migration 93
Running Instances: 1
Node Version: SNAP 671

FileSystem upload setting will not store uploaded files into designated directory

/var/snap/rocketchat-server/uploads set 777 owners root:root

RC already can write to this folder for server purposes.  Why aren't the files being uploaded? After Upload progress bar proceeds to 100% "Internal server error is now displayed.

GOAL
A backup and restore with GridFS does not preserve attached files. FileSystem method has been elected to allow frequent crontab based backup of the RC attached files.  Then when the RC server crashes, the Mongo backup will restore channel logs and a separate operation can restore the attached files.

**Comment by waveyuk** [comment]
Hi @ml48603 
You need to create a folder called "uploads" (or whatever you want) in /var/snap/rocketchat-server/common and point the `File System -> System Path` to /var/snap/rocketchat-server/common/uploads
Hope that helps!

**Comment by ml48603** [comment]
Thanks!  I created the /var/snap/rocketchat-server/common/uploads 775 root:root directory changed the upload method to FileSystem.  Restarted the MongoDB and RC servers, restarted the RC Linux desktop app and files are now being uploaded to the file system directory.  Thanks a million.

Mark, Saginaw Michigan

**Comment by waveyuk** [comment]
You're welcome @ml48603
