### ISSUE TITLE
Asana Integration

### ISSUE THREAD

**Issue by itnazeer** [RocketChat/Rocket.Chat#7422]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

I am trying to integrate Asana with Rocketchat and I did not find plugins to integrate and Asana support said to contact Rocket to develop. Please help me integrating Asana.

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
