### ISSUE TITLE
"More private groups..." search causes browser refresh

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7423]
When clicking on the "More private groups..." and then using the search functionality, when hitting the return key, the browser refreshes, causing it to throw the user back to the login page temporarily.

Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by MartinSchoeler** [comment]
Confirmed on demo and latest develop branch. this happens when the `Merge private groups with channels` preference is set to off.
