### ISSUE TITLE
User Status "away" not showing in profile panel

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7424]
If a user's status is set to away, when viewing their profile in the right-hand profile pane, the orange "away" icon does not show.  It shows correctly for Available, Busy and Offline modes however.

Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by rasos** [comment]
Confirmed - the away circle is missing left of the user name. 

BTW, when is a user set to "away" status automatically? After how many minutes being away from the desktop? And what happens when I manually change my status? How can I get back to automated status setting?

**Comment by ggazzo** [comment]
I think its working now, please feel free to (re)open if you find some problem 
![image](https://user-images.githubusercontent.com/5263975/40525573-3ab04074-5fb7-11e8-9524-f6287dc5ed8f.png)

@rasos My Account > Preferences
![image](https://user-images.githubusercontent.com/5263975/40525592-5a593d68-5fb7-11e8-9e51-b43e41898985.png)
