### ISSUE TITLE
PUSH Privacy Settings Not Working

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7425]
Rocket.Chat Version:  0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: Build SNAPS 671

From Administration > PUSH Settings > Privacy the following settings are in effect:

Show message in notification FALSE
Show channel/group/username in notification FALSE

Within my user settings > Preferences the setting: 
Offline Email Notifications is set to "Every Mention/DM

The resulting email that is sent still has the name of the user that RC messaged and the contents of the message that was typed.  

How can I achieve the desired result of receiving an email message that does not include the name of the user that RC messaged me and the content of the message that was sent?  

Only the email without mesaging user and message text needs to be received to prompt me to check my mobile device for RC activity.

**Comment by geekgonecrazy** [comment]
Ok so push notification privacy does not apply to email notifications.  Please feel free to open a new issue about email privacy settings as they are two different things
