### ISSUE TITLE
Saving SNAPS Package of a specific version and build of RC for Linux

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7426]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: Build 671 SNAPS

This is the first version of the RC server that actually triggers audible PUSH notifications to my Cyanogen CM13 Samsung Galaxy S4 smartphone.  I don't want to lose this capability when the next RC build of 0.56.0 is released for SNAPS.

Where can I download RC v0.56.0 SNAPS Build 671 package for a manual SNAPS install on a AMD64 Ubuntu Linux 16.04.2 LTS Server ?    Does the SNAPS environment no permit this ?

Thanks,
Mark

**Comment by geekgonecrazy** [comment]
@ml48603 the whole idea of snaps is that its easy for you to install and it auto updates.  I believe if you check history in the [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) you'll find where another user as managed to download for purely offline use of Rocket.Chat.  Maybe that will be of use to you.

As to the issues described... please open an issue if you loose notifications between upgrades.   This shouldn't happen.
