### ISSUE TITLE
Using Internal Hubot on 0.57.0

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7427]
Hi.
I'm a little confused on how to use the new Internal Hubot.  I've created a new directory under /var/snap/rocketchat-server/common/scripts/
In that directory I've placed two scripts... one called `seen.coffee` and `darksky.coffee` (the latter downloaded from https://github.com/github/hubot-scripts/blob/master/src/scripts/darksky.coffee).  In the Scripts To Load field I've entered `seen.coffee,darksky.coffee`.  My username of the bot is called `gbm.bot`.  If I issue `@gbm.bot weather london` nothing happens.  If I issue `@gbm.bot help` I get:
**SurreyUK: bot help - Displays all of the help commands that Hubot knows about.
bot help <query> - Displays all help commands that match <query>.**
So I know it's working.
Am I missing something obvious?

Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by waveyuk** [comment]
Scratch the above!! I figured it out :)

**Comment by engelgabriel** [comment]
For the sake of helping other, what were you doing wrong @waveyuk ? Maybe we can make more clear and add info on the documentation.

**Comment by waveyuk** [comment]
@engelgabriel  I was right clicking the filename in the web page and just downloading it.  This generated a HTML file.  What you have to do is go into the link, copy the script, then paste it into a file, and save it as a .coffee file and then uploading that to the directory I created :)
Simple when you look at the file rather than diving in with blind faith!
