### ISSUE TITLE
user cannot login (ldap setup)

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#7429]
Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: no
Node Version: 4.8.3

Hello Devs.

I have a user who cannot login anymore. He is still logged in via rocketchat app but is not able to login via lets say android app. There he gets the following error:

![img_0594_anon](https://user-images.githubusercontent.com/631865/27902675-d65b2f54-6236-11e7-83fe-561dfb455b7d.png)

Any ideas on that?

thanks and cheers

**Comment by maxdwit** [comment]
Possible duplicate of https://github.com/RocketChat/Rocket.Chat/issues/7405

**Comment by KervyN** [comment]
Try to disable LDAP Avatar Sync

**Comment by himbeere** [comment]
Sync Data is disabled. Is the "Sync User Avatar" active despite of that? Anyways i disabled that switch. Now it looks like this:

![bildschirmfoto 2017-07-06 um 13 30 22](https://user-images.githubusercontent.com/631865/27909141-8b8bdd48-624f-11e7-964c-f3df7a7e9c64.png)

Problem persists.

**Comment by KervyN** [comment]
Well, we have sync data enabled so this will not suite your problem.

**Comment by sampaiodiego** [comment]
@himbeere can you please try please enabling `Merge existing users`?
![image](https://user-images.githubusercontent.com/8591547/28090729-b1064dca-6663-11e7-97d9-5095529c2394.png)

**Comment by himbeere** [comment]
@sampaiodiego I am a little worried about that. Are the ldap passwords synced to the mongodb then? And if so, are they encrypted?

**Comment by sampaiodiego** [comment]
@himbeere the password is already being saved (encrypted) when the user logs in..

the option `merge existing users` will not get all users and passwords from LDAP and store in rocket.chat though. :wink:

**Comment by himbeere** [comment]
Okiedokie. Adjusted that setting. Now the user gets 403. 
![img_0619_anon](https://user-images.githubusercontent.com/631865/28157855-223fb314-67b8-11e7-81cf-32dc48f7a9c5.png)

Is it neccessary to restart RC after changing that setting?

thanks and cheers
t.

**Comment by rodrigok** [comment]
Closed by #7472
