### ISSUE TITLE
Create an option to go straight to direct message when clicking on a user's name

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7436]
Right now, when you click on a user's name it goes to the profile page. Many users will prefer to go directly to chat with that user.

**Comment by danieljhochman** [comment]
@gdelavald @rodrigok  - This only seems to be working when you click their name from within the chat area. If you click their name from the members list or in a linked @ version of their name from within the chat, it still goes to the profile.

**Comment by rodrigok** [comment]
@danieljhochman Thanks by the review, I've created a new PR adding this missing parts (https://github.com/RocketChat/Rocket.Chat/pull/7608)

**Comment by danieljhochman** [comment]
Thanks @rodrigok !
