### ISSUE TITLE
Administrative settings are not restored by MongoRestore 

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7437]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: SNAPS Build 671

RC Server crashed on a Ubuntu 16.04.2 LTS x64 server installation and RC was completely reinstalled, including the SNAPS environment.  The procedures used are from RC Docs website:
https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps

MongoDB Backup was performed with 
# snap run rocketchat-server.backupdb

When the MongoDB was restored the Administrative settings were not written to the database.  MongoDB was restored with:
# /snap/rocketchat-server/current/bin/mongorestore --db parties /var/snap/rocketchat-server/671/dump/parties/

Is this because the Administrative settings were never backed up in the first place? Or because the mongorestore command did not include the correct switches to write the Administrative settings to the new MongoDB ?

I read in the MongoDB reference document in the mongorestore section about the available command line switches.  I didn''t see anything here to cause Administrative settings to be overwritten in the virgin MongoDB installation.
https://docs.mongodb.com/manual/reference/program/mongorestore/

**Comment by geekgonecrazy** [comment]
@ml48603 all settings would be backed up by the backupdb command.

Can you do an `ls -l` in your `dump/parties` folder?

**Comment by ml48603** [comment]
geekgonecrazy: it's skidmark2 on Team: demo.rocket.chat 

# ls -lah /var/snap/rocketchat-server/829/dump/parties
total 3.0M
drwxr-xr-x 2 root root  4.0K Jul 20 07:25 .
drwxr-xr-x 3 root root  4.0K Jul 20 07:25 ..
-rw-r--r-- 1 root root   161 Jul 20 07:25 instances.bson
-rw-r--r-- 1 root root   191 Jul 20 07:25 instances.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 meteor_accounts_loginServiceConfiguration.bson
-rw-r--r-- 1 root root   239 Jul 20 07:25 meteor_accounts_loginServiceConfiguration.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 meteor_oauth_pendingCredentials.bson
-rw-r--r-- 1 root root   421 Jul 20 07:25 meteor_oauth_pendingCredentials.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 meteor_oauth_pendingRequestTokens.bson
-rw-r--r-- 1 root root   315 Jul 20 07:25 meteor_oauth_pendingRequestTokens.metadata.json
-rw-r--r-- 1 root root   100 Jul 20 07:25 migrations.bson
-rw-r--r-- 1 root root    90 Jul 20 07:25 migrations.metadata.json
-rw-r--r-- 1 root root  1.9K Jul 20 07:25 _raix_push_app_tokens.bson
-rw-r--r-- 1 root root   101 Jul 20 07:25 _raix_push_app_tokens.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 _raix_push_notifications.bson
-rw-r--r-- 1 root root   456 Jul 20 07:25 _raix_push_notifications.metadata.json
-rw-r--r-- 1 root root  1.3K Jul 20 07:25 rocketchat_avatars.bson
-rw-r--r-- 1 root root   20K Jul 20 07:25 rocketchat_avatars.chunks.bson
-rw-r--r-- 1 root root   238 Jul 20 07:25 rocketchat_avatars.chunks.metadata.json
-rw-r--r-- 1 root root   542 Jul 20 07:25 rocketchat_avatars.files.bson
-rw-r--r-- 1 root root   240 Jul 20 07:25 rocketchat_avatars.files.metadata.json
-rw-r--r-- 1 root root   260 Jul 20 07:25 rocketchat_avatars.metadata.json
-rw-r--r-- 1 root root  6.2K Jul 20 07:25 rocketchat_cron_history.bson
-rw-r--r-- 1 root root   343 Jul 20 07:25 rocketchat_cron_history.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_custom_emoji.bson
-rw-r--r-- 1 root root   451 Jul 20 07:25 rocketchat_custom_emoji.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_custom_sounds.bson
-rw-r--r-- 1 root root   278 Jul 20 07:25 rocketchat_custom_sounds.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_import.bson
-rw-r--r-- 1 root root   183 Jul 20 07:25 rocketchat_import.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_integration_history.bson
-rw-r--r-- 1 root root   209 Jul 20 07:25 rocketchat_integration_history.metadata.json
-rw-r--r-- 1 root root   371 Jul 20 07:25 rocketchat_integrations.bson
-rw-r--r-- 1 root root   195 Jul 20 07:25 rocketchat_integrations.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_custom_field.bson
-rw-r--r-- 1 root root   213 Jul 20 07:25 rocketchat_livechat_custom_field.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_department_agents.bson
-rw-r--r-- 1 root root   223 Jul 20 07:25 rocketchat_livechat_department_agents.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_department.bson
-rw-r--r-- 1 root root   328 Jul 20 07:25 rocketchat_livechat_department.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_external_message.bson
-rw-r--r-- 1 root root   221 Jul 20 07:25 rocketchat_livechat_external_message.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_inquiry.bson
-rw-r--r-- 1 root root   799 Jul 20 07:25 rocketchat_livechat_inquiry.metadata.json
-rw-r--r-- 1 root root  1.7K Jul 20 07:25 rocketchat_livechat_office_hour.bson
-rw-r--r-- 1 root root   567 Jul 20 07:25 rocketchat_livechat_office_hour.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_page_visited.bson
-rw-r--r-- 1 root root   520 Jul 20 07:25 rocketchat_livechat_page_visited.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_livechat_trigger.bson
-rw-r--r-- 1 root root   203 Jul 20 07:25 rocketchat_livechat_trigger.metadata.json
-rw-r--r-- 1 root root  992K Jul 20 07:25 rocketchat_message.bson
-rw-r--r-- 1 root root  1.9K Jul 20 07:25 rocketchat_message.metadata.json
-rw-r--r-- 1 root root   306 Jul 20 07:25 rocketchat_oauth_apps.bson
-rw-r--r-- 1 root root   191 Jul 20 07:25 rocketchat_oauth_apps.metadata.json
-rw-r--r-- 1 root root  374K Jul 20 07:25 rocketchat_oembed_cache.bson
-rw-r--r-- 1 root root   285 Jul 20 07:25 rocketchat_oembed_cache.metadata.json
-rw-r--r-- 1 root root  6.1K Jul 20 07:25 rocketchat_permissions.bson
-rw-r--r-- 1 root root   193 Jul 20 07:25 rocketchat_permissions.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_raw_imports.bson
-rw-r--r-- 1 root root   193 Jul 20 07:25 rocketchat_raw_imports.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_reports.bson
-rw-r--r-- 1 root root   185 Jul 20 07:25 rocketchat_reports.metadata.json
-rw-r--r-- 1 root root   926 Jul 20 07:25 rocketchat_roles.bson
-rw-r--r-- 1 root root   329 Jul 20 07:25 rocketchat_roles.metadata.json
-rw-r--r-- 1 root root  5.4K Jul 20 07:25 rocketchat_room.bson
-rw-r--r-- 1 root root   731 Jul 20 07:25 rocketchat_room.metadata.json
-rw-r--r-- 1 root root  255K Jul 20 07:25 rocketchat_settings.bson
-rw-r--r-- 1 root root   371 Jul 20 07:25 rocketchat_settings.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 rocketchat_smarsh_history.bson
-rw-r--r-- 1 root root   199 Jul 20 07:25 rocketchat_smarsh_history.metadata.json
-rw-r--r-- 1 root root 1017K Jul 20 07:25 rocketchat_statistics.bson
-rw-r--r-- 1 root root   279 Jul 20 07:25 rocketchat_statistics.metadata.json
-rw-r--r-- 1 root root   11K Jul 20 07:25 rocketchat_subscription.bson
-rw-r--r-- 1 root root  1.9K Jul 20 07:25 rocketchat_subscription.metadata.json
-rw-r--r-- 1 root root   56K Jul 20 07:25 rocketchat__trash.bson
-rw-r--r-- 1 root root   298 Jul 20 07:25 rocketchat__trash.metadata.json
-rw-r--r-- 1 root root   46K Jul 20 07:25 rocketchat_uploads.bson
-rw-r--r-- 1 root root   345 Jul 20 07:25 rocketchat_uploads.metadata.json
-rw-r--r-- 1 root root   824 Jul 20 07:25 ufsTokens.bson
-rw-r--r-- 1 root root    89 Jul 20 07:25 ufsTokens.metadata.json
-rw-r--r-- 1 root root  5.4K Jul 20 07:25 users.bson
-rw-r--r-- 1 root root  3.3K Jul 20 07:25 users.metadata.json
-rw-r--r-- 1 root root     0 Jul 20 07:25 usersSessions.bson
-rw-r--r-- 1 root root   307 Jul 20 07:25 usersSessions.metadata.json

**Comment by geekgonecrazy** [comment]
> -rw-r--r-- 1 root root 255K Jul 20 07:25 rocketchat_settings.bson
-rw-r--r-- 1 root root 371 Jul 20 07:25 rocketchat_settings.metadata.json

That is the settings that you change in the administrative panel.  So for sure present in the back up.

Are you getting any errors while restoring?

What kind of settings are you noticing that aren't set still?

**Comment by ml48603** [comment]
When I did the restore no personal settings or administrative settings were retained.  Settings appeared to be default after the restore to 671.

I haven't attempted a backup/restore since the SNAPS auto-refresh from Build 671 to 801 that crashed my server.  Build 812 to 829 auto-refresh happened last night without mishap.

If administrative settings are retained in 
-rw-r--r-- 1 root root 255K Jul 20 07:25 rocketchat_settings.bson
-rw-r--r-- 1 root root 371 Jul 20 07:25 rocketchat_settings.metadata.json

Where are the personal settings? Or are personal settings stored in the same files?

**Comment by geekgonecrazy** [comment]
personal settings would be on the users collection primarily

Are you disabling rocket.chat while you import the db?

`sudo systemctl stop snap.rocketchat-server.rocketchat-server`
Do your import
`sudo systemctl start snap.rocketchat-server.rocketchat-server`

See more docs on that here: https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps#how-do-i-restore-backup-data-to-my-snap-

**Comment by ml48603** [comment]
It was some time ago.  I can't remember for sure.  I do have it in my notes to stop the RC server during the backup/restore.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Have walked several more people through this successfully so seems to work ok
