### ISSUE TITLE
Unify connection strings amung deployment methods

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#7439]
It seems cases like our official docker image has a differing connection string then the docker image build via our CI.

Ref #7384

**Comment by vcapretz** [comment]
Should we updated the connection string on this repo or on the Docker.Official.Image? 

As people are probably using the Dockerfile inside Rocket.chat we could update the info on the Docker repo

**Comment by geekgonecrazy** [comment]
Changing is easier said then done.  A lot of people use both images. I think we will need to investigate the data to see if we can even do this.  

Biggest thing is to do our best to make as close as possible.  Especially db name, and our suggested mongo container name
