### ISSUE TITLE
Feature request: change limits of search results

### ISSUE THREAD

**Issue by rafacamargo123** [RocketChat/Rocket.Chat#7440]
Rocket.Chat Version: 0.56.0
Running Instances: 4
DB Replicaset OpLog: Enabled
Node Version: v4.5.0

The Search on the main page is limited to 5 results only and there is no parameter to change this setting.

It would be nice if this value could be changed globally, like a new parameter on Administration page.

Thank you

**Comment by miguelzabala** [comment]
+1

**Comment by apastuhow** [comment]
agree!

**Comment by rodrigok** [comment]
It doesn't seem to apply anymore.

**Comment by HRJG** [comment]
Hey I'm having this issue as well, where I'm only be able to get a result of 5 same names, if I had 10 Jessica it will only display 5 Jessica
