### ISSUE TITLE
Scrollbar styling only available in webkit

### ISSUE THREAD

**Issue by sasakura-sora** [RocketChat/Rocket.Chat#7446]
Rocket.Chat Version:  0.56.0

I would like to be able to style scrollbars across all browsers with the theme capabilities provided by Rocket Chat.

The existing scrollbar styling is done using -webkit only CSS - https://webkit.org/blog/363/styling-scrollbars/
This has no support in other browsers - http://caniuse.com/#search=css%20scrollbar

As webkit-scrollbar is not on a standards track this would require a JS solution.

I personally have had a lot of success using Perfect Scroll (https://github.com/noraesae/perfect-scrollbar) but there are many other options.

**Comment by karlprieb** [comment]
Hey @sasakura-sora we know that and it's sucks 👎 
We are redesigning our web client and will use an JS solution to the new scroolbars :)

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/19701
