### ISSUE TITLE
Slack import fails when encountering file upload

### ISSUE THREAD

**Issue by zw42** [RocketChat/Rocket.Chat#7447]
Rocket.Chat Version: 0.57.1 (Ubuntu snap)
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Have an issue when importing from Slack: causes an exception when it needs to upload a file. From the log:

`snap[9263]: Exception in defer callback: TypeError: Cannot read property 'get' of undefined
snap[9263]:   at _class.uploadFile (/snap/rocketchat-server/812/programs/server/packages/rocketchat_importer.js:325:24)
snap[9263]:   at /snap/rocketchat-server/812/programs/server/packages/rocketchat_importer-slack.js:555:20
snap[9263]:   at Array.forEach (native)
snap[9263]:   at /snap/rocketchat-server/812/programs/server/packages/rocketchat_importer-slack.js:458:22
snap[9263]:   at Array.forEach (native)
snap[9263]:   at [object Object].<anonymous> (/snap/rocketchat-server/812/programs/server/packages/rocketchat_importer-slack.js:456:32)
snap[9263]:   at packages/dispatch_run-as-user.js:211:14
snap[9263]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
snap[9263]:   at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
snap[9263]:   at /snap/rocketchat-server/812/programs/server/packages/rocketchat_importer-slack.js:442:13
snap[9263]:   at Array.forEach (native)
snap[9263]:   at /snap/rocketchat-server/812/programs/server/packages/rocketchat_importer-slack.js:440:34
snap[9263]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
snap[9263]:   at packages/meteor.js:445:45`

This issue was not present in 0.56.0 (using the same Slack import file).

**Comment by graywolf336** [comment]
@sampaiodiego @rodrigok this is broke because of the change to file uploads.

**Comment by sampaiodiego** [comment]
@graywolf336 yes, it looks like. 

@zw42 what file upload storage are you using?

**Comment by zw42** [comment]
@sampaiodiego using GridFS, also tried FileSystem but the same issue persisted
