### ISSUE TITLE
S3 file upload support no longer works after upgrade to 0.57.1

### ISSUE THREAD

**Issue by cdhowie** [RocketChat/Rocket.Chat#7449]
Rocket.Chat Version: 0.57.1
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: v4.8.3

After upgrading to 0.57.1, all file uploads fail with the message "invalid-store".  Changing the file storage backend from S3 to something else and then back resolves the problem until the Rocket Chat service is restarted, and then uploads fail again.

There are no log entries to indicate why this might be happening.

**Comment by k0nsl** [comment]
Please see:
https://github.com/RocketChat/Rocket.Chat/issues/7411

**Comment by cdhowie** [comment]
@k0nsl The error message is different, and there is nothing logged, contrary to statements made on that issue. This leads me to believe the issues are not exactly the same.

**Comment by geekgonecrazy** [comment]
Not sure which pr fixed but closing cause it should be fixed since no follow up reports
