### ISSUE TITLE
"Edit-feature" for non-administrators

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#745]
Wouldn't it make sense to let ordinary (non-administrators) edit their own messages, or perhaps, create a special group (such as "moderators") with less privileges than an administrator?

**Comment by geekgonecrazy** [comment]
Ordinary users can edit their own messages.  Have been able to for a good while.

A role system is planned.  I think a moderator role is a must, in use in public communities especially.

**Comment by marceloschmidt** [comment]
I'll close this issue as duplicate of #292, since message editing is a feature that already exists and can be enabled or disabled on settings.
