### ISSUE TITLE
Markdown Codeblock double-escaping

### ISSUE THREAD

**Issue by JeromeJ** [RocketChat/Rocket.Chat#7450]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: ???
Node Version: 4.8.2

I'm aware I used the Markdown wrongly, but it seems the langage's name is being parsed twice.

I narrowed down the issue is probably happening around [here](https://github.com/RocketChat/Rocket.Chat/blob/2d8aa63bc383c7cf3c40720787f7d8c26bd1bd0d/packages/rocketchat-markdown/markdowncode.js#L65).

Screenshot below:

![image](https://user-images.githubusercontent.com/650065/27986885-e4da1bdc-6405-11e7-8a98-58f3b20f4368.png)

![image](https://user-images.githubusercontent.com/650065/27986965-ce06e286-6406-11e7-84da-c17f17e05793.png)

**Comment by gdelavald** [comment]
This should be fixed on 0.57.

**Comment by rodrigok** [comment]
Please reopen if the issue persists.
