### ISSUE TITLE
Enable users blocking DM

### ISSUE THREAD

**Issue by l0k1-smirenski** [RocketChat/Rocket.Chat#7451]
There is no user-level blocking. Moderators can mute users in rooms, but users cannot mute other users in DM. This gives users no effective way to deal with trolls properly.

**Comment by lucasvanhalst** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/7452 and you can already do that, search for the 'embed link previews' option

**Comment by l0k1-smirenski** [comment]
search... where?

**Comment by l0k1-smirenski** [comment]
I'm sorry, I meant to be posting the issue about blocking DM... No, it's not possible. Administrators can mute users in a room but DMs cannot be blocked.

**Comment by l0k1-smirenski** [comment]
I discovered how to use this feature. Closing.
