### ISSUE TITLE
need help -- cannot run 

### ISSUE THREAD

**Issue by sitexa** [RocketChat/Rocket.Chat#7457]
Rocket.Chat Version: 0.57.1
Running Instances: 
DB Replicaset OpLog:
Node Version: v8.1.3
Meteor Version: 1.5
OS Version:  Darwin Kernel Version 16.6.0
Master branch

debug.log::
`
0 info it worked if it ends with ok
1 verbose cli [ '/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v4.8.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Rocket.Chat@0.57.1~prestart: Rocket.Chat@0.57.1
6 silly lifecycle Rocket.Chat@0.57.1~prestart: no script for prestart, continuing
7 info lifecycle Rocket.Chat@0.57.1~start: Rocket.Chat@0.57.1
8 verbose lifecycle Rocket.Chat@0.57.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle Rocket.Chat@0.57.1~start: PATH: /Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/Users/open/NodeProjects/Rocket.Chat/node_modules/.bin:/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin:/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/.bin:/Users/open/.nvm/versions/node/v8.1.3/bin:/opt/local/bin:/opt/local/sbin:/Users/open/.gvm/bin:/Users/open/anaconda3/bin:/Users/open/.rvm/gems/ruby-2.1.2/bin:/Users/open/.rvm/gems/ruby-2.1.2@global/bin:/Users/open/.rvm/rubies/ruby-2.1.2/bin:/usr/local/gradle-2.14.1/bin:/Users/open/Applications/mongodb/bin:/Users/open/activator-dist-1.3.10/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/open/bin:/Users/open/.rvm/bin:/Users/open/Applications/Umlet:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/open/Library/Android/sdk/platform-tools:/usr/local/mysql/bin:/usr/local/nexus-2.13.0-01-bundle/nexus-2.13.0-01/bin:/usr/local/go/bin:/Users/open/GoPath/bin:/Users/open/.rvm/bin:/Users/open/go/bin
10 verbose lifecycle Rocket.Chat@0.57.1~start: CWD: /Users/open/NodeProjects/Rocket.Chat
11 silly lifecycle Rocket.Chat@0.57.1~start: Args: [ '-c', 'meteor npm i && meteor' ]
12 silly lifecycle Rocket.Chat@0.57.1~start: Returned: code: 1  signal: null
13 info lifecycle Rocket.Chat@0.57.1~start: Failed to exec start script
14 verbose stack Error: Rocket.Chat@0.57.1 start: `meteor npm i && meteor`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:862:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid Rocket.Chat@0.57.1
16 verbose cwd /Users/open/NodeProjects/Rocket.Chat
17 verbose Darwin 16.6.0
18 verbose argv "/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "start"
19 verbose node v4.8.3
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error Rocket.Chat@0.57.1 start: `meteor npm i && meteor`
23 error Exit status 1
24 error Failed at the Rocket.Chat@0.57.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`

**Comment by lucasvanhalst** [comment]
Use node 4.x and it should work. Anything higher is not supported

**Comment by sitexa** [comment]
After I set node version to v4.5.0, Rocket.Chat still refuse to work.
Exception from console:
```
MacOS:Rocket.Chat open$ meteor npm start

> Rocket.Chat@0.57.1 start /Users/open/NodeProjects/Rocket.Chat
> meteor npm i && meteor


> Rocket.Chat@0.57.1 postinstall /Users/open/NodeProjects/Rocket.Chat
> cd packages/rocketchat-katex && npm i

[[[[[ ~/NodeProjects/Rocket.Chat ]]]]]

=> Started proxy.
=> Started MongoDB.
Node#before is deprecated. Use Node#raws.before
/Users/open/.meteor/packages/less/.2.7.9.1fv9ffj++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/open/NodeProjects/Rocket.Chat/node_modules/mocha/node_modules/debug/src'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1586:35)
    at readDirectory (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:338:26)
    at Watcher._fireIfDirectoryChanged (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:490:23)
    at /Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:747:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:736:7)
    at new Watcher (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:435:10)
    at setupClientWatcher (/tools/runners/run-app.js:800:23)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:811:7)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@0.57.1 start: `meteor npm i && meteor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@0.57.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm/_logs/2017-07-11T01_03_48_887Z-debug.log
```
 and the log file:
``` 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v4.8.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Rocket.Chat@0.57.1~prestart: Rocket.Chat@0.57.1
6 silly lifecycle Rocket.Chat@0.57.1~prestart: no script for prestart, continuing
7 info lifecycle Rocket.Chat@0.57.1~start: Rocket.Chat@0.57.1
8 verbose lifecycle Rocket.Chat@0.57.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle Rocket.Chat@0.57.1~start: PATH: /Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/Users/open/NodeProjects/Rocket.Chat/node_modules/.bin:/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin:/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/.bin:/Users/open/.nvm/versions/node/v4.5.0/bin:/opt/local/bin:/opt/local/sbin:/Users/open/.gvm/bin:/Users/open/anaconda3/bin:/Users/open/.rvm/gems/ruby-2.1.2/bin:/Users/open/.rvm/gems/ruby-2.1.2@global/bin:/Users/open/.rvm/rubies/ruby-2.1.2/bin:/usr/local/gradle-2.14.1/bin:/Users/open/Applications/mongodb/bin:/Users/open/activator-dist-1.3.10/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/open/bin:/Users/open/.rvm/bin:/Users/open/Applications/Umlet:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/open/Library/Android/sdk/platform-tools:/usr/local/mysql/bin:/usr/local/nexus-2.13.0-01-bundle/nexus-2.13.0-01/bin:/usr/local/go/bin:/Users/open/GoPath/bin:/Users/open/.rvm/bin:/Users/open/go/bin
10 verbose lifecycle Rocket.Chat@0.57.1~start: CWD: /Users/open/NodeProjects/Rocket.Chat
11 silly lifecycle Rocket.Chat@0.57.1~start: Args: [ '-c', 'meteor npm i && meteor' ]
12 silly lifecycle Rocket.Chat@0.57.1~start: Returned: code: 1  signal: null
13 info lifecycle Rocket.Chat@0.57.1~start: Failed to exec start script
14 verbose stack Error: Rocket.Chat@0.57.1 start: `meteor npm i && meteor`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:862:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid Rocket.Chat@0.57.1
16 verbose cwd /Users/open/NodeProjects/Rocket.Chat
17 verbose Darwin 16.6.0
18 verbose argv "/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/open/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "start"
19 verbose node v4.8.3
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error Rocket.Chat@0.57.1 start: `meteor npm i && meteor`
23 error Exit status 1
24 error Failed at the Rocket.Chat@0.57.1 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by sitexa** [comment]
I get it work now. It's not node version limit, but the MacOS ulimit isse. https://gist.github.com/abernix/a7619b07b687bb97ab573b0dc30928a0
