### ISSUE TITLE
Add and promote adoption of code ownership

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#7458]
There's a new Github feature to identify code owners, for big projects with lots of contributors.
https://github.com/blog/2392-introducing-code-owners

I think it would be highly beneficial for Rocket.Chat to add some owners for the various packages and core code where there's a specific team member responsible. It's quite common for someone to ask about a specific area and get bounce around while the person with appropriate experience is found. This would fast track that and lead to better informed contributions.

**Comment by geekgonecrazy** [comment]
We're relocating all discussion type issues over to our forum: https://forum.rocket.chat

That way they do not get lost in the clutter of issues and features.
