### ISSUE TITLE
Bug in chat.update API call

### ISSUE THREAD

**Issue by gerricom** [RocketChat/Rocket.Chat#7459]
Rocket.Chat Version: 0.57.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3

* * *

I'm using some of the API calls of Rocket.Chat to send and update status reports from our CRM. For one of this reports, it is necessary to update existing messages in Rocket.Chat and this is currently not working.

I'm trying to send the following request:

```
POST /api/v1/chat.update HTTP/1.1
X-Auth-Token: fw7KEtEU_XEcn-L1s568Xnqi_XT_bzCmOtWiwKzVwUx
X-User-Id: 5wh5EXP79hDg3L4WP
Content: application/json
Content-Type: application/json; charset=utf-8
Host: chat.local
Connection: close
User-Agent: Paw/3.1.1 (Macintosh; OS X/10.12.5) GCDHTTPRequest
Content-Length: 75

{"roomId":"K2EbA7Kg63CfngGfT","msgId":"GTmmkvqXsweHWXamm","text":"foo bar"}
```

And I get the following answer: 

```
HTTP/1.1 400 Bad Request
Date: Mon, 10 Jul 2017 07:09:14 GMT
Access-Control-Allow-Origin: *
Cache-Control: no-store
Pragma: no-cache
content-type: application/json
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked

{
  "success": false,
  "error": "Cannot read property 'description' of undefined"
}
```

**Comment by MartinSchoeler** [comment]
Maybe a message with a attachment is causing this? Since only files with attachments have the `description` property

**Comment by gerricom** [comment]
Ok. This is a message without an attachment - so this might be the problem here.

**Comment by graywolf336** [comment]
`{ parseUrls: false }`

**Comment by gerricom** [comment]
Thanks, @graywolf336!

**Comment by graywolf336** [comment]
This should still be considered a bug since there is an error occurring.
