### ISSUE TITLE
Access to History as pages and ability to download locally (by Admin Only). 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#746]
it would be a good idea to be able to access History folders and view them as pages, and have the ability for the (Admin) to download them -  and option to keep or remove from server.

![image](https://cloud.githubusercontent.com/assets/12454319/9770345/bd2d230c-56fd-11e5-8c4d-a41766678873.png)
##

**Comment by armandomonzone** [comment]
hi guys!!

Someone have news about the revier the chat history??

I tried to export database and I can´t :(

Do you help me??

**Comment by geekgonecrazy** [comment]
Going to close in favor of #758
