### ISSUE TITLE
rocket chat new collection created but not working for real time update

### ISSUE THREAD

**Issue by nitinjiniguru** [RocketChat/Rocket.Chat#7460]
Rocket.Chat Version: 0.56.0 
DB Replicaset OpLog: Enabled
Node Version:4.8.2 - x64 

I have created a new collection . and created page for the list of the data of that page

collection : sample_collection

created model for the collection named : sampleCollection

in server side i have created a file inside the rocketchat-lib and also publish the method.

`Meteor.publish('sampleData.all', function () { 
  return RocketChat.models.sampleCollection.find();
});`

from client side i have subscribed to the the method 

`Meteor.subscribe('sampleData.all');`

when i insert in database but it not reflects on browser.

is there i missed any thing to declare?

**Comment by graywolf336** [comment]
Please see the code base for answers but also Meteor guides, as this is a general how-to question and not an issue or bug with the core of Rocket.Chat.

**Comment by nitinjiniguru** [comment]
I have checked and got the solution from the guide
I have once closed but somehow(by mistake) it was again opened.

Thanks
