### ISSUE TITLE
How can i get Realtime Msg via php

### ISSUE THREAD

**Issue by naguchennai** [RocketChat/Rocket.Chat#7461]
https://rocket.chat/docs/developer-guides/realtime-api
It sis possible get room message via php in realtime? 
php websocket not conected rocket chat server.. any php websocket code?

**Comment by graywolf336** [comment]
@naguchennai I am going to close this issue as this seems like a question which his better fit for Google (php use websockets) or for Stackoverflow and is not an issue with Rocket.Chat itself.
