### ISSUE TITLE
Explain api channels.archive

### ISSUE THREAD

**Issue by naguchennai** [RocketChat/Rocket.Chat#7464]
https://rocket.chat/docs/developer-guides/rest-api/channels/archive

Any one explain what is this? why is this?

**Comment by MartinSchoeler** [comment]
It is a api call for archiving channels, archiving a channel marks it as read only and then removes it from the channel list on the left side nav.

**Comment by amonemian** [comment]
@MartinSchoeler  what about direct messages? how can I mark them as read with rest-api?
channels.archive does not work for direct messages!
