### ISSUE TITLE
Allow configuration of UploadFS

### ISSUE THREAD

**Issue by gerricom** [RocketChat/Rocket.Chat#7465]
I ran into a little problem with our current hoster. I'm using the german [uberspace](https://uberspace.de) project for hosting a Rocket.Chat instance for our little team of seven users. Everything runs quite smoothly in this environment but file uploads are an issue here.

UploadFS uses in its standard configuration a temporary dir located at `/tmp/ufs/...`. Uberspace encourages you to use a local tmp dir instead because nobody knows, what the global tmp dir can end up. So as sometimes file uploads are stuck, I took a close look. UploadFS allows you to set a custom tmp dir (`UploadFS.config.tmpDir`). For testing purposes, I changed this hardcoded in the initialization of ufs, but it would be nicer, to have a option to change this, if one needs to change it.

**Comment by luto** [comment]
@rodrigok can you please outline what an acceptable solution would like? what do you think about respecting [`$TMPDIR`](https://en.wikipedia.org/wiki/TMPDIR) here?

**Comment by d-sko** [comment]
If @luto's suggestion is acceptable, I can make a pull request for it.

**Comment by geekgonecrazy** [comment]
Seems acceptable.  Hopefully we can get merged
