### ISSUE TITLE
(•) Rocket.Chat may currently be slowing down Firefox.

### ISSUE THREAD

**Issue by kpcyrd** [RocketChat/Rocket.Chat#7473]
When monitoring `about:performance` in firefox, my rocketchat tab periodically switches from `(•) Rocket.Chat currently performs well.` to `(•) Rocket.Chat may currently be slowing down Firefox.`.

I'm not sure what's the reason for this, but it seems rocketchat periodically keeps my content process busy, which freezes all tabs in the current 1-content-process-if-addons-enabled model of firefox.

Rocket.Chat Version: 0.56.0

**Comment by kpcyrd** [comment]
Maybe I should add: I'm in some very large rooms, it might make sense to reduce the number of messages that are loaded in the backlog, as those might slow down the browser. Is this value configurable?

**Comment by lucasvanhalst** [comment]
This boils down to issue #31 which still hasn't been addressed, even though it is very important :(

**Comment by geekgonecrazy** [comment]
Yeah it pretty much is because of the changes we need to make proposed in #31 

Closing in favor of that one.  If you have other specific reasons you've been able to identify clearly, please feel free to open an issue about that specifically
