### ISSUE TITLE
State of Rocket.Chat?

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#7476]
Hi folks,

at first: this issue is NOT intended to spread [FUD](https://de.wikipedia.org/wiki/Fear,_Uncertainty_and_Doubt) or misinformation. It is motivated by a serious concern about what the current state of Rocket.Chat is. These are my observations:

* as of now: 1967 open issues. Such an amount of open issues is not practical
  * to handle for you as developers
  * to handle for somebody who wants to report an issue
  * and leads, in turn, to duplicates which worsens the problem

* While you still manage to tag almost all new issues (which is very important):
  * you don't close issues that are not relevant anymore (e.g. https://github.com/RocketChat/Rocket.Chat/issues/6134)
  * you don't close issues that are, quite obviously, no RC issue (e.g. https://github.com/RocketChat/Rocket.Chat/issues/5080 - short answer would be: "no RC issue, restore your backups and go ahead. close issue.")

Could you give me any feedback on this?

Cheers
Thomas

**Comment by antgel** [comment]
Fair comment. I don't know for sure, but the impression I got is that RC exploded (in a good way), and perhaps the processes are somewhat behind. Interested to see what the team has to say on it - in this agile world, backlog grooming is essential - it never takes as long as one thinks it will, and it pays invaluable dividends.

**Comment by timkinnane** [comment]
Hey @TwizzyDizzy I totally agree and raised very similar points in discussion on demo.rocket.chat a while back. I proposed a solution re guidelines that I was going to contribute myself, but I've since been very caught up in another project. Perhaps you can pick it up and draft something with the resources I pointed to? https://demo.rocket.chat/channel/contributors?msg=76tyMwJj937SGjAXk

Another tactic could be to automate issue maintenance via probot.
https://github.com/apps/probot-stale

**Comment by Chripallo** [comment]
I agree with this and hope something is changed. Having almost 2,000 open issues is problematic. There's still issues that are left open from years ago that people wanted but nothing came of it. My group and I love Rocket.Chat's project and hope to see it thrive, but it won't in this current state.

The fact that such a disruptive issue (breaking custom file and avatar uploads) was passed through to the snap package and then having no fix still after a week with nothing shown in the pipeline for another few weeks is ridiculous. We need changes in how this project is maintained, else this will kill the project.

**Comment by WebSavvyGuy** [comment]
I have to agree.   We were planning to use this software on some high traffic public sites but after even some light to moderate testing, have run into all kinds of issues.   Some of the issues brought up many times in the past already.   I would love to see this project take off because it has a lot of potential.

**Comment by TwizzyDizzy** [comment]
@Chripallo 

> Our problem is that such a disruptive issue (breaking custom file and avatar uploads) was passed through to the snap package. It's been a week and there's still no released fix and there's nothing shown in the pipeline until 0.57.3, which is still a couple weeks away. We need changes in how this project is maintained, else this will kill the project.

Indeed, this is something I wanted to bring up in my initial remarks, too. But as this was rather a feeling than me having "hard" evidence, I dropped it. But yes: I, too, have the feeling, that the quality of releases is somewhat sloppy and the lack of fast solutions to issues resulting from this is kind of unlovely.

But let me highlight one thing, as I don't want to be misunderstood: With Rocket.Chat being open source, I greatly appreciate the time anybody (be it developers of some company or just random folks) puts into this. That being said, I have the feeling, that the current state of affairs leads to or is a downward spiral. May this issue be a place to discuss what can be done from the community or the people from Rocket.Chat.

This is why I would love to hear some opinion from the likes of @rodrigok @engelgabriel @marceloschmidt or @sampaiodiego :)

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Hey guys!  I'm not one of the ones mentioned.  :smile: But just wanted to drop a note.  

We are very much aware of the issues.  We are in the process of making improvements to our issue triage process.  

I think one of the first steps for us is to bring up the issue quality.  We are trying to encourage that via: #7492 

As a result of that we are trying to encourage people with "how to" (or we as we tag them here "support") questions to ask on Stackoverflow(with our Rocket.Chat tag) or even our community server.  

A few in the team have suggested probot.  But the fear here is it comes off rude when a bot suddenly comes along and closes an issue. While we don't want the issues to get out of control.  We also really value continuing the warm inviting community feel that isn't found in a lot of open source projects.

We are also trying to streamline our release process.  I think you've probably noticed a longer gap in the release cycle.  We are trying to improve this process.  Extremely fast is great, but leads to too many things changing too fast.  We now have release candidate releases that we will run on our community server to try and shake out bugs.

Of course this release we had a bit of a hiccup with unifying avatar uploads and file uploads.  We tested a lot of different cases, but some slipped through.  We are definitely trying to address these.

Thanks for your patience and caring enough to bring this topic up!  If you have suggestions please feel free to give them to us.  A good place on the community server to reach us would be: [#contributors](https://demo.rocket.chat/channel/contributors)

**Comment by sampaiodiego** [comment]
hi guys.. I couldn't say it better than @geekgonecrazy .. 

although we are aware of the high issue number, we don't want to close them all, we see some value on many of them.

also as pointed by @geekgonecrazy we're in process of making all process better. we love to hear the community and see what are the most urgent things we should do better.

so thanks for opening this issue, hopefully we sort this things out and start making it even better.

**Comment by admin-crowd-iugo** [comment]
urgent things are stability first everything else next. losing chats, files and avatars and any user content is not acceptable. period. everything else is secondary to stability. 
next is upgrades which have a clear process and no weird glitches which cause problems to production databases. 
problem is rocket chat is so unstable we upgrade every 10-15 releases after we had to roll back our production several times to due server breaking bugs. this is not good.

**Comment by timkinnane** [comment]
Thanks for giving the team's perspective @geekgonecrazy and @sampaiodiego.
I think all users and contributors appreciate your approach to valuing our input. I do feel that the sentiment is turning a little sour though and the risks of too many open issues and unstable releases outweighs the need to be overly considerate of etiquette. I think you could be a bit more opinionated about enforcing quality discussion and contribution and the community mood would improve overall from just having some clarity.

**Comment by TwizzyDizzy** [comment]
> I do feel that the sentiment is turning a little sour though and the risks of too many open issues and unstable releases outweighs the need to be overly considerate of etiquette. I think you could be a bit more opinionated about enforcing quality discussion and contribution and the community mood would improve overall from just having some clarity.

I was taking my time to get the words right, but you took 'em right of my mouth. Thanks for that!

If somebody thinks he should be running an instance of a software (be it on the internet or just on an intranet) they should be able to diagnose an issue properly and get straight to the technical issue, sorting the relevant from the irrelevant and thereby enabling any contributor to get a grasp of the issue fast and do the best to support them to solve it. Being overly polite doesn't help anyone in the long run.

And yes: I do think that one can politely say:
* you didn't describe your problem adequately (without the need to tell them exactly how would it would be better - that's what the issue template above can do)
* your issue has nothing to do with Rocket.Chat, please seek help at some other place

@admin-crowd-iugo: while I feel @timkinnane 's
> the sentiment is turning a little sour though

.. in your words, I do think you're right. A release breaking elemental stuff is "not acceptable" (as in nothing one wishes for).

I'm just asking myself where to go from here with this issue...

* the issue template is a good thing and should be incorporated
* are the enough people to handle incoming issues?
** if not, would it be an option to appoint additional people who might get the privilege to manage issues on here

One question still occupies my mind: the recent breaking of the avatar upload or the LDAP authentication... why did they happen? Is the code to complex? Are tests missing? What was it and can it be changed?

Cheers & thanks to everybody weighing in :)

Cheers
Thomas

**Comment by localguru** [comment]
At the moment there are 296 open bugs. What about collecting the most important bugs in a separate issue and vote on them, so we get a better priority.

**Comment by geekgonecrazy** [comment]
@localguru typically if we are sorting we'd do so by number of comments and by number of thumbsups.  

Gathering and voting in a single issue would cause too much chaos and only would get opinion of a subset of the community.

**Comment by MartinSchoeler** [comment]
Closing this since we are working in reducing the number of issues and updating our issues and support guidelines. Thanks for all your opinions guys!
