### ISSUE TITLE
Emoji Picker is not displayed in IE11

### ISSUE THREAD

**Issue by keitaro1020** [RocketChat/Rocket.Chat#7480]
Rocket.Chat Version: 0.57.1
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: v4.8.3

Emoji Picker is not displayed in IE11. When I narrow the width of the window (Sidenav disappeared).

**Comment by MartinSchoeler** [comment]
Confirmed on demo server

**Comment by keitaro1020** [comment]
div class="main-content content-background-color"  -> z-index:120;
div class="emoji-picker secondary-background-color"  -> z-index is undefined

emoji-picker hides behind main-content.
emoji-picker is displayed if set "z-index:121;".

**Comment by MartinSchoeler** [comment]
Tested on the latest release and it seems to be working now, if this keeps happening, please reopen this. Thanks!
