### ISSUE TITLE
Certain functional tags (strong, br) also URL encoded in error messages.

### ISSUE THREAD

**Issue by FrankSpierings** [RocketChat/Rocket.Chat#7481]
Rocket.Chat Version: 0.57.0
Running Instances: ?
DB Replicaset OpLog: ?
Node Version: ?

I reported a XSS in rocket chat through Hackerone. This has been fixed, but the fix introduced a functional bug. Error messages are now displayed url encoded, but this impacts the tags <strong> and <br />. 
Reproduce: add an incorrect name for a channel or emoji. An error similar to this will appear: `<strong>NAME</strong> is not a valid name, <br />`

**Comment by MartinSchoeler** [comment]
I couldn't reproduce this on the latest develop version. 
<img width="304" alt="screen shot 2017-07-14 at 11 05 15 am" src="https://user-images.githubusercontent.com/20868078/28215479-913bea86-6884-11e7-9cfb-874c893c0177.png">

Could you give us more info on how to reproduce this?
Thanks!

**Comment by FrankSpierings** [comment]
You are right, I currently cannot reproduce this issue either. I will close this ticket. Sorry for the inconvenience.
