### ISSUE TITLE
Link Preview broken for links with underlines

### ISSUE THREAD

**Issue by id101010** [RocketChat/Rocket.Chat#7482]
Rocket.Chat Version: 0.54.0
Running Instances: ?
DB Replicaset OpLog: ?
Node Version: ?

The Link-Preview parser has trouble handling links that feature underlining such as wikipedia disambiguations. 

Example:

The Link 
https://en.wikipedia.org/wiki/Bear_(disambiguation) 

produces a preview which directs to 
https://en.wikipedia.org/wiki/Bear

The issue could be related to #6895

**Comment by localguru** [comment]
Can't confirm on 0.57.1

![rc_lp](https://user-images.githubusercontent.com/8544984/28250356-8393139e-6a66-11e7-8df7-0ca4190ce1be.jpg)

**Comment by localguru** [comment]
I think it's duplicate of "Url in parsed in a wrong way" #7169

**Comment by id101010** [comment]
But this is wrong, isn't it? The website suggested by the preview is not the one in the link. Another example:

![image](https://user-images.githubusercontent.com/7494467/28250982-501d92a6-6a74-11e7-8db4-63102951ea9d.png)

Sodium Chloride is not the NaCl i was looking for when posting this link. ;)

**Comment by id101010** [comment]
@localguru Yes, this looks exactly like the same issue. Haven't found #7169 yet. :) Should we close this one?

![image](https://user-images.githubusercontent.com/7494467/28251017-ef249f66-6a74-11e7-888e-92344fe12ffb.png)

**Comment by localguru** [comment]
It's your issue. But yes, I would close it with a hint to #7169

**Comment by id101010** [comment]
Closing issue. It is already covered by #7169.

**Comment by id101010** [comment]
Closing issue. It is already covered by #7169.
