### ISSUE TITLE
Video Call doesn't work if started from mobile

### ISSUE THREAD

**Issue by tapule** [RocketChat/Rocket.Chat#7483]
Rocket.Chat Version: 0.57?? (https://demo.rocket.chat)
Running Instances: ??
DB Replicaset OpLog: ??
Node Version: ??

Hi,
I was testing the video call and I have noticed that it only works if you start the call from the web app, if you try to start the video call from the mobile (android cordova) it doesn't work.
It throws this error:
NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}

Any hint??

Greetings.

**Comment by teamsoo** [comment]
<img width="848" alt="screen shot 2560-07-15 at 12 28 06 am" src="https://user-images.githubusercontent.com/9608690/28223152-7f015656-68f4-11e7-9f38-525f1006389a.png">

Same issue here on my server running https behind Apache2. Any idea?

**Comment by teamsoo** [comment]
@tapule Have you found a fix yet?

**Comment by geekgonecrazy** [comment]
@rodrigok I think this has something to do with the little server serving the cache?

**Comment by teamsoo** [comment]
so it's possible that the little cache server is running http in Cordova and it might be treated as unsecured origin when making a call to external.

It's running as "localhost.local" and somehow the log in Chrome Inspect show xhr requests origin as
```
Origin: http://httpsmyservercom.meteor.local
```

and according to the link https://goo.gl/Y0ZkNV
```
“Secure origins” are origins that match at least one of the following (scheme, host, port) patterns: 
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —) 
```

**Comment by geekgonecrazy** [comment]
Yup! That looks to be it.  I'm not sure if its even possible to handle that over https.  Not sure what the solution here would be.. :(

**Comment by teamsoo** [comment]
@geekgonecrazy I'm able to make it works now by changing the host to **localhost** because **localhost** is treated as a secure origin. 

Should I make a PR out of this (at Cordova repo)? I'm not sure if changing from 

```
'host': @baseUrlToDir(baseUrl) + '.meteor.local'
```

to

```
'host': 'localhost'
```

will have any bad effect.

**Comment by rodrigok** [comment]
@teamsoo If you change the server to `localhost` only it will not work for multiple servers, it will override the cached files when you add a new server

**Comment by tapule** [comment]
@teamsoo I didn't find a fix, I will try yours.

**Comment by geekgonecrazy** [comment]
I’m gonna aid the GitHub bit and go ahead and close this.  A loooot has changed since then.  So any info here is outdated
