### ISSUE TITLE
Allow room names to have spaces

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7488]
Currently room names do not allow spaces. Please add the ability for room names (both public and private) to allow spaces.

**Comment by localguru** [comment]
I like the idea. +1

**Comment by jszaszvari** [comment]
I dislike the idea. What chat apps allow this? Just serves to confuse people and helps make room names inconsistent

**Comment by roygold7** [comment]
I am unable to create a channel with spaces in its name. I've tried adding a space to the RegExp in the UTF-8 option in Adminstration > General > UTF-8.
Is there an option in the administration settings that I missed? Is it addressed in the documentation?

**Comment by sampaiodiego** [comment]
please check https://github.com/RocketChat/Rocket.Chat/pull/7595

**Comment by roygold7** [comment]
Okay, allowing special chars lets me type spaces in the new channel's name input, but then it creates the channel with hyphens instead of spaces in the channel's name.
Also, the name appears three times on the page and is inconsistent regarding the spaces and hyphens.

![screenshot](https://user-images.githubusercontent.com/40822827/42288282-b486b61e-7fc2-11e8-8aae-1f8e665f20da.png)

**Comment by sampaiodiego** [comment]
@roygold7 ok, that's a new issue.. as you saw it was not designed this way back on #7595

do you mind opening a new issue regarding this inconsistency? thx

**Comment by kaiiiiiiiii** [comment]
Sounds like the issue I addressed in #10515, just with spaces instead of underscores.

**Comment by softwaredoug** [comment]
This is pretty annoying if you create a Discussion (which allows spaces) then rename the discussion. It forces you to put dashes or something in the name. Lack of spaces in room names just feels arbitrary. We are just starting to use Rocket Chat from Flowdock, which allowed spaces in names... which only improved the readability of the room names

**Comment by roygold7** [comment]
@softwaredoug 
> This is pretty annoying if you create a Discussion (which allows spaces) then rename the discussion. It forces you to put dashes or something in the name. Lack of spaces in room names just feels arbitrary. We are just starting to use Rocket Chat from Flowdock, which allowed spaces in names... which only improved the readability of the room names

If I recall correctly, we managed to get around this by adding a space to the regex in the setting `UTF8_Names_Validation` in the General section of the settings.

**Comment by softwaredoug** [comment]
> @softwaredoug
> 
> > This is pretty annoying if you create a Discussion (which allows spaces) then rename the discussion. It forces you to put dashes or something in the name. Lack of spaces in room names just feels arbitrary. We are just starting to use Rocket Chat from Flowdock, which allowed spaces in names... which only improved the readability of the room names
> 
> If I recall correctly, we managed to get around this by adding a space to the regex in the setting `UTF8_Channel_Names_Validation` in the General section of the settings, and changing the `UI_Allow_room_names_with_special_chars` to the `false` option under the User Interface section in the Layout section of the settings

Thanks! Funny I tried that, and somehow "@" replies stopped working. But the allow room names special chars did it! Woohoo!

**Comment by roygold7** [comment]
> > @softwaredoug
> > > This is pretty annoying if you create a Discussion (which allows spaces) then rename the discussion. It forces you to put dashes or something in the name. Lack of spaces in room names just feels arbitrary. We are just starting to use Rocket Chat from Flowdock, which allowed spaces in names... which only improved the readability of the room names
> > 
> > 
> > If I recall correctly, we managed to get around this by adding a space to the regex in the setting `UTF8_Channel_Names_Validation` in the General section of the settings, and changing the `UI_Allow_room_names_with_special_chars` to the `false` option under the User Interface section in the Layout section of the settings
> 
> Thanks! Funny I tried that, and somehow "@" replies stopped working. But the allow room names special chars did it! Woohoo!

There's definitely a way for "@" replies to still work but I'm not really involved with the project anymore so I don't know how to fix it but I'm sure it's just a matter of paying around with settings.

**Comment by nallathambis** [comment]
> I am unable to create a channel with spaces in its name. I've tried adding a space to the RegExp in the UTF-8 option in Adminstration > General > UTF-8.
> Is there an option in the administration settings that I missed? Is it addressed in the documentation?

Thanks you, the above change worked [0-9a-zA-Z-_. ]+
