### ISSUE TITLE
Please recommend whether to user ImageMagick or GraphicsMagick

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#7493]
Rocket.Chat Version: v0.56.0
Running Instances: 2
DB Replicaset OpLog: YES
Node Version: v4.5.0

We are currently setting up an environment and have to make the decision whether to use ImageMagick and/or GraphicsMagick. Can you please recommend which one to use?

In this blog [1] I read, that in some cases the one is better than the other.
Does RC use either ImageMagick or GraphicsMagick, or is there a combination of both possible.

Any advice appreciated! 

[1] https://blog.trackduck.com/2014/11/12/imagemagick-vs-graphicsmagick-one-better-process-images-website/

**Comment by geekgonecrazy** [comment]
I think we actually make use of both.  In snaps we use graphicsmagick and in our docker image we use imagemagick.

I've personally had some issues with snaps and imagemagick.  I don't recall exactly what they were, but switching to graphicsmagick resolved them.

--- 
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
