### ISSUE TITLE
Changing sounds in preferences throws errors

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#7497]
Tested on demo and latest develop branch

When you try to change the sounds under account > Preferences the browser console throws this error 

<img width="629" alt="screen shot 2017-07-14 at 1 14 12 pm" src="https://user-images.githubusercontent.com/20868078/28220564-5de2c62a-6896-11e7-9a74-30293324891c.png">

**Comment by localguru** [comment]
can't reproduce it on 0.57.1 and demo.rocket.chat

**Comment by MartinSchoeler** [comment]
@localguru what os are you using? And what browser are you using?

**Comment by localguru** [comment]
@MartinSchoeler Linux both server and client. On client side I use Firefox 54.0 (64-Bit)

**Comment by MartinSchoeler** [comment]
Giving preference to #8424 since it has more info in it
