### ISSUE TITLE
Favorites Are In Alphabetical Order by Username, even when Use Real Name is True

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#7498]
Rocket.Chat Version: 0.56.0
Running Instances: 2
DB Replicaset OpLog: Enabled
Node Version: v4.8.2

We have turned on the feature to "Use Real Name", which is great.  And we find that in the side bar, the list of users under the "Direct Messages" setting are in alphabetical order, by first name, which is great.  However, the list of users under "Favorites" is still being orgaznized by username, even though the full name is being shown.  So, for example, a Favorites list might look like this:

Favorites (4)
Eric Smith
Jon Andrews
Jake Wilson
Will Jones

In our system, these usernames are created as esmith, jandrews, jwilson, and wjones.  The listing is alphabetized by username.  It should be orgazined like this:

Favorites (4)
Eric Smith
Jake Wilson
Jon Andrews
Will Jones

**Comment by zipper2110** [comment]
Same goes for direct messages list, it is sorted by username, event though real names are displayed.

**Comment by zipper2110** [comment]
Also, it sorts the list by capital A-Z first, then by lowercase a-z, so the user who has a username starting with a letter "M" going before user that has username starting with "a".

**Comment by amelkor** [comment]
Shall be very pleasured if this problem will be fixed. Also would be great to add groupping for favorite users, as it presents in Lync for example. Do we need to create a feature request or something?

**Comment by vesvalo** [comment]
Still actual in 0.62.2.

**Comment by ggazzo** [comment]
@mddvul22 could you try on 0.66 ? I think we fixed (:

**Comment by Gummikavalier** [comment]
Not fixed in 0.66.0.

Capitals letters are now sorted properly in channel view, but we still get users sorted by their account instead of real name.

**Comment by melaniebi** [comment]
Sorting by real names works for us in 0.66.0. But if getting a new direct message the position of the user changes and get sorted by username till the next reload.
