### ISSUE TITLE
Docker instance reporting MongoDB warning since 0.57.1

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#7499]
Rocket.Chat Version: 0..57.1
Running Instances: 1 (2 reported)
DB Replicaset OpLog: Disabled
Node Version: 4.8.1

Just upgraded our internal chatops instance to 0.57.1 using docker. Admin page has a new warning:

> Error: Rocket.Chat requires oplog tailing when running in multiple instances
> 
> Please make sure your MongoDB is on ReplicaSet mode and MONGO_OPLOG_URL environment variable is defined correctly on the application server

Why does it think I have multiple instances? It never used to do this.

**Comment by geekgonecrazy** [comment]
@antgel that warning should go away.  Basically every time you start your server an entry is made into the instances collection that is unique for every instance of Rocket.Chat started.  That record some times takes a little while to expire.

If it doesn't go away please feel free to re-open this issue!
