### ISSUE TITLE
SAML functionality doesn't understand XML namespaces

### ISSUE THREAD

**Issue by spb** [RocketChat/Rocket.Chat#7501]
Rocket.Chat Version: 0.57.2
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 

I'm trying to connect Rocket to a SAML Identity Provider which produces namespaced XML output -- that is, the opening tag looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<ns0:Response xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Destination="http://192.168.100.11:3000/_saml/validate/rocket" ID="id-ytAv5fmS43dwtScyH" InResponseTo="a23pJZsh6M9KeuKBq" IssueInstant="2017-07-15T09:06:10Z" Version="2.0">
```

Submitting this to Rocket's validation endpoint results in "Error: Unable to validate response url: Error: Unknown SAML response message". Manually removing the namespace from the Response tag results in getting a step further - it then complains that there's no Assertion tag, when in fact there is an <ns1:Assertion>, which as far as I can tell is perfectly valid.

I attempted to produce a patch for this, but running Rocket out of a Git checkout (a) was dog-slow, and (b) timed out after two minutes attempting to process a request after I made a single trivial modification to the relevant code. I suspect I just don't understand whatever weird Node or Meteor magic is going on. In either case, the SAML processor should probably remove namespace prefixes from tag names before attempting to process them.

**Comment by arminfelder** [comment]
I think this is related to #7723

**Comment by spb** [comment]
Yes, it's the same bug. pysaml2 is actually the same library I was using when I filed this issue.

**Comment by arminfelder** [comment]
please take a look at: #8511

**Comment by pierre-lehnen-rc** [comment]
Closing this, as the current version already supports namespaces.
