### ISSUE TITLE
Wrong size on verification box

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#7502]
The size of the verification box is wrong on smaller screens. It looks like this on mobile units

![image](https://user-images.githubusercontent.com/17712562/28240982-9e6c10f2-698b-11e7-9f8d-073c53a0c36f.png)

**Comment by TheReal1604** [comment]
@Molle500 This is also true for the file-upload windows..

**Comment by MartinSchoeler** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/7404
