### ISSUE TITLE
Highlight matching words in message search results

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7505]
This is basic search results functionality which Slack has:
![image](https://user-images.githubusercontent.com/23452628/28246591-67e3baa8-6a26-11e7-96f8-d6811d1440a0.png)

Also, when you jump to the message, the animation/highlight should be much slower so you can actually see it - see how Slack does it.

**Comment by danilomiranda** [comment]
Assign that to me o/

**Comment by ashwaniYDV** [comment]
@rodrigok I want to work on it. I have accessed the searched text and message. Now I have to just highlight the searched text in each message.
But I am confused here, where should I do the highlight work? Should it be good to do it in the message.html, message.js template?
