### ISSUE TITLE
Error while running meteor

### ISSUE THREAD

**Issue by tanmoyopenroot** [RocketChat/Rocket.Chat#7508]
After clone, got this error while running meteor...
![screenshot from 2017-07-17 06-59-25](https://user-images.githubusercontent.com/25791025/28253148-7fe8fb58-6abd-11e7-9504-81ddbcc09bad.png)

openroot@hp:~/Tanmoy/Working Stuffs/openSource/Rocket.Chat$ meteor
[[[[[ ~/Tanmoy/Working Stuffs/openSource/Rocket.Chat ]]]]]

=> Started proxy.                             
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
sh: 0: Can't open /home/openroot/Tanmoy/Working
/home/openroot/.meteor/packages/less/.2.7.9.by3u3b++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

**Comment by MartinSchoeler** [comment]
@tanmoyopenroot have you run `meteor npm install` before running the app?

**Comment by tanmoyopenroot** [comment]
@MartinSchoeler I did that before running `meteor`

**Comment by engelgabriel** [comment]
@tanmoyopenroot can you please try again with the latest version on the develop branch and reopen this issue if the problem persists?
