### ISSUE TITLE
Match error: Unknown key in field username. in users.setAvatar rest call

### ISSUE THREAD

**Issue by mojtab23** [RocketChat/Rocket.Chat#7509]
Rocket.Chat Version: 0.57.2
Running Instances: 1
DB Replicaset OpLog: enabled
Node Version: v4.8.2
--
According doc https://rocket.chat/docs/developer-guides/rest-api/users/setavatar
I'm trying to call (/api/v1/users.setAvatar) to set user avatar but I get this error :
{
    "success": false,
    "error": "Match error: Unknown key in field username"
}
when I change username to userId and test It works but with username it's not working.

**Comment by graywolf336** [comment]
Please show an example command of how you are able to reproduce this.

**Comment by localguru** [comment]
Can't reproduce it. This is working fine for me on 0.57.1

```
curl -H "X-Auth-Token: mytoken" -H "X-User-Id: myuserid" \
-F "image=@hubot.jpg" https://myserver/api/v1/users.setAvatar
```

**Comment by graywolf336** [comment]
@localguru you even tried setting the avatar to another user by providing their username?

**Comment by localguru** [comment]
@graywolf336 no, I only tested to change my own avatar. If I try - as admin - to change another user's avatar I get an error:

```
{
  "status": "error",
  "message": "You must be logged in to do this."
}
```

**Comment by graywolf336** [comment]
What command was you using to do it? As it is possible, we developed it and tested it a while back.

**Comment by localguru** [comment]
Same as above just with the userid of another user

```
curl -H "X-Auth-Token: my-admin-user-token" -H "X-User-Id: another-user-id" \
-F "image=@hubot.jpg" https://myserver/api/v1/users.setAvatar
```

**Comment by graywolf336** [comment]
That's why then, that is the incorrect usage. Check the documentation: https://rocket.chat/docs/developer-guides/rest-api/users/setavatar

**Comment by localguru** [comment]
Sorry, don't understand. Could you post an example please.

**Comment by graywolf336** [comment]
You always have to use your own user id when calling it. However, some api endpoints allow passing in a `userId: 'id'` or `username: 'uusernamehere'` in the body of the call. That is what I'm talking about

**Comment by W0olFy** [comment]
Hi all.

I can confirm that in current version 0.57.2 api request users.setAvatar not working if you use username parameter in payload of request.

Example:
```
curl -H "X-Auth-Token: adminauthtoken" \
     -H "X-User-Id: adminuserid" \
     -H "Content-type:application/json" \
     -d '{"username": "username", "avatarUrl": "http://domain.tld/link/to/avatars/user_avatar.jpg"}' \
     http://my_rocketchat_instance/api/v1/users.setAvatar
```
Result:
```
{
  "success": false,
  "error": "Match error: Unknown key in field username"
}
```

Ok, let's try userId instead:
```
curl -H "X-Auth-Token: adminauthtoken" \
     -H "X-User-Id: adminuserid" \
     -H "Content-type:application/json" \
     -d '{"userId": "userIdhere", "avatarUrl": "http://domain.tld/link/to/avatars/user_avatar.jpg"}' \
     http://my_rocketchat_instance/api/v1/users.setAvatar
```
Result:
```
{
  "success": true
}
```
Good. Now let's look at source:
[line 189 of users.js](https://github.com/RocketChat/Rocket.Chat/blob/0.57.2/packages/rocketchat-api/server/v1/users.js#L189)

i don't see here anything about username parameter.

Please correct me if i am wrong.
