### ISSUE TITLE
Documentation on Incoming WebHook parsing

### ISSUE THREAD

**Issue by kurobeats** [RocketChat/Rocket.Chat#7510]
Rocket.Chat Version: latest (installed via snap)
Running Instances: 1
DB Replicaset OpLog: ?
Node Version: ?

I'm just having trouble finding the documentation on how to filter/format the incoming webhook messages. To provide context, webhook alerts from 411 come through like so:  
`
[<http://411.test.local/alert/12893|Alert>]
` 
so ideally would like to be able to "prettify" it into a clickable link or add titles etc.

**Comment by graywolf336** [comment]
Webhooks itself doesn't have any special links parsing, it's just like regular chat links. And those are done via markdown style.
