### ISSUE TITLE
Rocket Chat 0.57.2 fails to launch on Fedora 64Bit

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#7512]
Rocket.Chat Version: 0.57.2
Node Version: 4.7.2 - x64

I have run Rocket.Chat on Fedora 64bit here for over a year. I just found out that is has been offline for a week and I attempted to restart it using the systemD service file I had previously created. The service said it was restarted, but Rocket Chat was still unreachable.

I then downloaded the latest version of Rocketchat and installed it. I ran npm install and then used the systemD service to start rocket chat. I could see in the error output that the environment variables had not been set for some reason - even though they are specified in the systemD file.

I then set the environment variables manually from the command line and ran rocketchat from the command line too. This time it all worked correctly. I used Ctrl+Z to close the Rocket.Chat server instance that was running in the command line and looked for reasons as to why the systemD service wasn't launching rocket chat correctly. I didn't find anything but I decided to rerun rocketchat from the command line again, just as I had done earlier and now I am finding that I cannot launch it correctly from the command line either.

Here's he exception that's visible in the command line Interface:

```
Using FileSystem for custom emoji storage
Exception in callback of async function: Error: listen EADDRINUSE 0.0.0.0:3000
  at Object.exports._errnoException (util.js:907:11)
  at exports._exceptionWithHostPort (util.js:930:20)
  at Server._listen2 (net.js:1250:14)
  at listen (net.js:1286:10)
  at net.js:1395:9
  at nextTickCallbackWith3Args (node.js:469:9)
  at process._tickDomainCallback (node.js:416:17)

��� System ��� startup
��� +------------------------------------------------+
��� |                 SERVER RUNNING                 |
��� +------------------------------------------------+
��� |                                                |
��� |  Rocket.Chat Version: 0.57.2                   |
��� |       NodeJS Version: 4.7.2 - x64              |
��� |             Platform: linux                    |
��� |         Process Port: 3000                     |
��� |             Site URL: https://chat.mysite.net/  |
��� |     ReplicaSet OpLog: Disabled                 |
��� |          Commit Hash: 5ee53de581               |
��� |        Commit Branch: HEAD                     |
��� |                                                |
��� +------------------------------------------------+
```
Do I need to clear some kind of cache somewhere? or maybe reboot the server?

here's the SystemD file I have been using (succesfully until recently):
```
[Unit]
Description=RocketChat Server
After=network.target remote-fs.target nss-lookup.target mongod.target nginx.target  # Remove or Replace nginx with your proxy

[Service]
ExecStart=/usr/bin/node /mypath/rocketchat/Rocket.Chat/main.js    # Specify the location of node and location of main.js
Restart=always                                               # If set to always, the service will be restarted regardless of whether it exited cleanly or not, got terminated abnormally by a signal, or hit a timeout.
RestartSec=10                                                # Restart service after 10 seconds if node service crashes
StandardOutput=syslog                                        # Output to syslog
StandardError=syslog                                         # Output to syslog
SyslogIdentifier=nodejs-example
#User=<alternate user>
#Group=<alternate group>
Environment=NODE_ENV=production PORT=3000 ROOT_URL=https://chat.mysite.net
MONGO_URL=mongodb://localhost:27017/rocketchat

[Install]
WantedBy=multi-user.target
```

Anyone know what I am missing here?
thanks

**Comment by localguru** [comment]
SystemD looks fine to my mind. Have you tried to remove the comments ```#```?

**Comment by localguru** [comment]
"Ctrl+Z" send to background, so the process is still running and I guess that's why you can't start it a second time from console with the same environment variables. Use "Ctrl+C" to stop it instead.

**Comment by propertunist** [comment]
@localguru - aha! thanks, i had no idea of the difference between Ctrl+C and Ctrl+Z. I closed down the terminal and opened a new one and rocketchat is now working again. Gold star for you! :)
