### ISSUE TITLE
anonymous feature "invalid user" cant sign up as anonymous

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7515]
Rocket.Chat Version: 0.57.2
Running Instances: 1
DB Replicaset OpLog: yes
Node Version: 4.8.1

the bug of anonymous "invalid user" isnt solved still same as the ex build 0.57.0 
![screenshot-localhost-3000-2017-07-17-15-39-41](https://user-images.githubusercontent.com/16228448/28292914-4163cf22-6b06-11e7-9d8a-01e49052f9d5.png)

**Comment by MartinSchoeler** [comment]
Yes this fix will be released with version 0.57.3

**Comment by fifou17** [comment]
@MartinSchoeler ohh sorry i didnt know thank you
