### ISSUE TITLE
Hide deactivated users from rooms members

### ISSUE THREAD

**Issue by Romich777** [RocketChat/Rocket.Chat#7518]
Deactivated users shown in room members with invisible status.
I think it will be more useful to hide them in room members list

**Comment by localguru** [comment]
Good idea, but I would flag them as "deactivated". I might be a difference in communication if you know an user will be able to read the channel/room after re-activation, than not being a room member at all.

**Comment by MartinSchoeler** [comment]
This should be working on the latest version. Feel free to reopen this if you find this issue again. Thanks!
