### ISSUE TITLE
Archive + Freeze Channel

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#752]
Can we add the ability to archive and freeze a channel - for QA and Legal compliance reasons?

**Comment by Sing-Li** [comment]
:+1:   @Megatronic79  really knows what business users need !  :smile:

**Comment by geekgonecrazy** [comment]
@Megatronic79 we've got the base methods in place.  We'll get the rest of the logic built out and get this in place :)

**Comment by Megatronic79** [comment]
good work guys!

**Comment by Theaxiom** [comment]
#722 should be merged maybe?

**Comment by graywolf336** [comment]
Duplicate of #722.
