### ISSUE TITLE
how to extend the text message? 

### ISSUE THREAD

**Issue by gordanyang** [RocketChat/Rocket.Chat#7521]
how can i  extend the text message like below?
i want to add **_ext:{...}**
```
{
    "msg": "method",
    "method": "sendMessage",
    "id": "42",
    "params": [
        {
            "_id": "message-id",
            "rid": "room-id",
            "msg": "Hello World!",
            "_ext": {..}
        }
    ]
}
```
Rocket.Chat Version: 
Running Instances: 0.57
DB Replicaset OpLog:
Node Version: 4.8

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
