### ISSUE TITLE
Push token not sent since 0.56

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#7530]
Even if token is registered correctly with our own GCM key:    
`[34mI20170719-22:18:36.809(2) rocketchat_logger.js:377 [34mMeteor ➔ method raix:push-update -> userId: ijjpgnnnnnbLBQcqz , arguments:  { '0':     { appName: 'qt mobile client',      token: { gcm: 'dnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnng' },      userId: 'ijjpgnnnnnbLBQcqz' } }`

No push messages are sent and I can not send any tokens to myself for testing.

This works on a similar instance we run with the same GCM keys with RC 0.52.  

Has anything changed with token handling? 

Rocket.Chat Version: 0,56 + tested also with 0.57.1
Running Instances: 1
Node v4.7.1

**Comment by geekgonecrazy** [comment]
Do you have your own mobile applications or are you using ours?

If you are using ours published in the apps store, you do not need GCM keys.  All you need is to set use gateway to true.

**Comment by teamsoo** [comment]
Push works fine on my custom Cordova build + 0.56 & 0.57.2 servers

**Comment by rasos** [comment]
I had to remove all tokens from the MongoDB and restart Rocket.Chat and re-login the client, now push messages are again delivered.

Additionally, applied again patch https://github.com/RocketChat/Rocket.Chat/issues/6988#issuecomment-304784404 so that notifications are always delivered, regardless whether online status of client is online or offline.

**Comment by antgel** [comment]
FWIW, I had to do the same thing (remove all tokens from MongoDB). I wish I'd kept the logs of what were there - I seem to remember some token being exceptionally long - not sure if that was the actual cause of the problem.
