### ISSUE TITLE
create a mailing list for API changes

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#7531]
having a mailinglist, which informs about upcoming API changes(even really small ones !), would help to keep track, for App developers!

**Comment by antgel** [comment]
Why not just follow discussions here and release changelogs? IMHO, RC information is already spread in too many different places.

**Comment by arminfelder** [comment]
Exactly the spreading is the problem, I can not always check discussion threads to figure out if my application will still work in a few days. I strongly belief that the API has to be rock solid, needs a revision number and has to be an api change alert mailinglist(or ro channel...), as e.g. google offers

**Comment by graywolf336** [comment]
@arminfelder The changes will always be listed on https://github.com/RocketChat/Rocket.Chat/blob/develop/HISTORY.md along with https://github.com/RocketChat/Rocket.Chat/releases

**Comment by geekgonecrazy** [comment]
Release notes are definitely the best place to look.  Going to go ahead and close this.  Feel free to also open a discussion on our forums to go in a more depth discussion.  Its a bit more fitting there since not directly related to a feature or bug related to Rocket.Chat the server.  :smile:
