### ISSUE TITLE
Joinning channel - users block on loading screen

### ISSUE THREAD

**Issue by Crivaledaz** [RocketChat/Rocket.Chat#7534]
Hi,

I have updated Rocket.Chat two days ago from 0.56.0 to 0.57.2. It was fine, even if the installation process is a bit complex on an offline server (internal company network without internet) because of npm use.

However, since two days my team knows issues to join public channel. In fact, we have chosen to disable channel preview for user (uncheck the box "preview-c-room"), but when a user wants to join a channel, loading is infinitely long. So users cannot join any new channel by themselves, but they can only be added by an administrator.

This issue only concern user when "preview-c-room" is disabled, because when I activate the preview for users, they can join any public channel without problem.

Thanks for your help,

Crivaledaz

Rocket.Chat Version: 0.57.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0 and 4.8.2 (I have tried both)
OS : Centos 7

**Comment by localguru** [comment]
I can confirm!

* Operating System / Version / Architecture (64 bit?): Ubuntu 16.04 LTS, 64 bit
* Browser type & Version: Firefox 54.0 (64-Bit)
* Desktop Environment (if desktop app) / Version: Linux, Rocket.Chat+ Version 2.8.0
* Rocket.Chat Version: 0.57.1, self build bundle
* Running Instances: 1
* DB Replicaset OpLog: yes
* Node Version: 4.5
* mongodb-org: 3.4.5
* Logfile
[log.txt](https://github.com/RocketChat/Rocket.Chat/files/1162045/log.txt)
