### ISSUE TITLE
Oauth problem: twitter works, fb and google don't

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#7536]
version: 0.57

It is weird, twitter Oauth login works, but facebook and google doesn't, no matter what i do.
facebook when i click the button, auth login page won't even pop up, on right corner saying `internal error`;
google oauth when i click the button, login auth window does pop up, but shows error saying: redirect URL doesn't match. 

Isn't the redicrect url the one on RC admin Oauth section?

**Comment by geekgonecrazy** [comment]
Can you provide more info on what steps you've actually taken so far?

**Comment by ottomMT** [comment]
Could we have a WeChat login, so we could use it in China

**Comment by ottomMT** [comment]
or, how i config it with WeChat login? no docs

**Comment by geekgonecrazy** [comment]
@ottomMT your question is very off topic.. But you will need to implement custom oauth.. more info here: http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/web/login/login

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  @jy2008 please re-open or follow up with one of our support methods
