### ISSUE TITLE
SlackBridge - Editing message

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#7539]
### Description:

Editing a message in slack with SlackBridge installed causes an exception
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Linux 4.4.0-83-generic
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 2
* DB Replicaset Oplog: yes
* Node Version: v4.8.4

### Steps to Reproduce:

1. Edit a message in slack with SlackBridge enabled
2. Review the logs

### Expected behavior:

The message should be updated in RC to match slack's edit

### Actual behavior:

No edit occurs in RC

### Relevant logs:

[34mI20170721-14:12:47.696(-7) Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.   at AccountsServer.userId (/app/bundle/programs/server/packages/accounts-base.js:566:37)   at Object.Meteor.userId (/app/bundle/programs/server/packages/accounts-base.js:363:19)   at _class.cloneAndSaveAsHistoryById (/app/bundle/programs/server/packages/rocketchat_lib.js:5072:56)   at Object.RocketChat.updateMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:3826:30)   at SlackBridge.processSlackMessageChanged (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:1834:17)   at SlackBridge.onSlackMessage (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:675:12)   at /app/bundle/programs/server/packages/rocketchat_slackbridge.js:1011:13   at runWithEnvironment (packages/meteor.js:1176:24)

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/14273
