### ISSUE TITLE
e-mail address is everytime invalid

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [RocketChat/Rocket.Chat#7540]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Debian 8.8
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: don't know
* Node Version: this from docker

[22:00:18] chat:~# lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch

### Steps to Reproduce:

1. Right now I'm using a free e-mailer address which works, but I want to change it to my personal .net address.
2. When I want to add it, I get an alert, that this e-mail address is invalid.

Please forgive me, that I don't want to publish here my the domain name.

### Expected behavior:

The e-mail address will be changed.

### Actual behavior:

The e-mail address will not be changed.

Can you give me a hint, which kind of check rocketchat does? I want to investigate this problem.

cheers

**Comment by pkgodara** [comment]
Does it have format like <username@something.something>. Maybe use some example which would replicate the exact format, so that it could be investigated.

**Comment by Unterstrichmoepunterstrich** [comment]
> Does it have format like username@something.something.

its firstname@lastname.net

**Comment by geekgonecrazy** [comment]
@Unterstrichmoepunterstrich is it a valid domain?  If not you might need to turn off dns name check.

Administration->Account->Registration

![image](https://user-images.githubusercontent.com/51996/28494802-b125b996-6efe-11e7-8fa6-c922689b2726.png)

**Comment by LeeThompson** [comment]
I've having this same problem too.  Nothing in blocked domains.  Try to change a user account's e-mail address and 'invalid domain' no matter what (it is a valid domain, I can send mail to it, I can browse to it...).   This particular domain is a .net.

Server Setup Information:
```
Version of Rocket.Chat Server: 1.3.2 (22894861c5)
Operating System: Synology DSM 6.2 (Linux: 3.10.105)
Deployment Method(snap/docker/tar/etc): docker
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
Node Version: 8.11.4
MongoDB: 4.2.0 (wiredTiger)

```
