### ISSUE TITLE
ctrl + tab not working on Brave browser

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#7548]
### Description:

When using RC via brave browser, ctrl + tab does not work as intended.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Deployment Method: Tested on demo.rocket.chat and my own rpi snap server

### Steps to Reproduce:

1. Run the RC-client from Brave browser versions 17.19 and 18.9beta on macOS 10.12.6
2. Enter a channel or a direct message, i.e. not 'Administration'.

### Expected behavior:

ctrl + tab should let user select next tab.

### Actual behavior:

ctrl + tab does not let user select next tab.

Using the menus 'Windows -> Select Next/Previous Tab' works as intended.

**Comment by MartinSchoeler** [comment]
This only happens when the message input have focus

**Comment by drasbeck** [comment]
I can confirm this.

**Comment by graywolf336** [comment]
I this should be an issue with Brave and not Rocket.Chat. Can you reproduce this in Chrome or Firefox? If not, then it's an issue with Brave and if we start creating "fixes/workarounds" for browser issues then I don't think that is good.

@RocketChat/core I am going to close this, however feel free to open it again should you feel I am in the wrong here.

**Comment by drasbeck** [comment]
As this issue is Brave only, I have opened an issue with them.

**Comment by scorpp** [comment]
still observing same very issue with [Vivaldi](https://vivaldi.com/) browser. Chrome and Opera both work fine.

**Comment by drasbeck** [comment]
The issue has since been corrected in Brave.
