### ISSUE TITLE
Alias not changing when messages are sent without receiving other messages between

### ISSUE THREAD

**Issue by Davide95** [RocketChat/Rocket.Chat#7549]
### Alias not changing when messages are sent without receiving other messages between.
The alias of the user doesn't change in the web client in this scenario:

### Steps to Reproduce:

1. A send a message A1 and set his alias (e.g. "Rob")
2. B send a message B1
3. A send a message A2 and set his alias (e.g. "Mum")

In this case everything is ok. But the bug appear if
1. A send a message A1 and set his alias (e.g. "Rob")
3. A send a message A2 and set his alias (e.g. "Mum")

### Expected behavior:

The web client should change the alias from "Rob" to "Mum" for the second message

### Actual behavior:

The alias remains "Rob"

**Comment by TheMythPT** [comment]
Any updates on this? I'm using a [bridge](https://github.com/42wim/matterbridge) to relay Rocket.chat to IRC back and forth and i'm facing the same issue, almost 2y later.

**Comment by Sparkfiber** [comment]
Same issue - not resolved as of yet, but it is problematic when attempting to use a bridge/bot - it does the same thing for the profile picture.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/14257
