### ISSUE TITLE
Emojis are not rendering

### ISSUE THREAD

**Issue by negram** [RocketChat/Rocket.Chat#7551]
### Description:

After last update to commit ea5a319a5e we lost smiles in the chats. They are unseen in both chats as replaced ":)" and reactions to messages. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.0-develop
* Operating System:
* Deployment Method(snap/docker/tar/etc): etc
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version: 

### Steps to Reproduce:

1. Open chat
2. Post a smile or react on a message.

### Expected behavior:

See a emoticon

### Actual behavior:

emoticon isn't shown

### Relevant logs:

<img width="454" alt="screen shot 2017-07-24 at 10 14 11" src="https://user-images.githubusercontent.com/195510/28516512-6627dbc0-7059-11e7-868a-522c3898921b.png">
<img width="234" alt="screen shot 2017-07-24 at 10 14 52" src="https://user-images.githubusercontent.com/195510/28516513-663dae8c-7059-11e7-8efd-244a2527f6fd.png">
<img width="674" alt="screen shot 2017-07-24 at 10 17 42" src="https://user-images.githubusercontent.com/195510/28516514-663fedaa-7059-11e7-887d-2c37099be7a9.png">

**Comment by MartinSchoeler** [comment]
Confirmed on latest develop version

**Comment by flantascience** [comment]
+1 Got the same thing happening for me

**Comment by mborhade** [comment]
some emojis are working after running `meteor add qnub:emojione` ,
but still some are not working there...
![emojis](https://user-images.githubusercontent.com/10369619/28561395-d94be690-713b-11e7-9c27-d3ced1b3d90c.png)

**Comment by flantascience** [comment]
@mborhade    is that something I can run on Heroku easily?  I have only run commands on my local system like that
