### ISSUE TITLE
Disable logging of certain rooms, such as direct messages

### ISSUE THREAD

**Issue by JohnBFrm** [RocketChat/Rocket.Chat#7553]
### Description:

Currently all messages from all rooms are being logged to the database (MongoDB). We'd like to disable the logging of direct messages, so they are kept completely private.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

### Expected behavior:

Direct messages are not to show up in the logs, or in the database

### Actual behavior:

Messages are logged and show up in the database

**Comment by MartinSchoeler** [comment]
Maybe you are looking for something like [Off The Record Messaging](https://rocket.chat/docs/user-guides/off-the-record#off-the-record)

**Comment by JohnBFrm** [comment]
Hi Martin,

We've checked OTR, but it sadly doesn't fit the full criteria. We would love to be able to disable direct message logging entirely, so none of them end up in the database/saved.

**Comment by WebSavvyGuy** [comment]
This would also help to reduce unnecessary load on the server.   This is a good suggestion and something we are looking for as well and if we had it as optional, that would be even better.  We would like to see them completely deleted upon users closing their browser window and not stored anywhere.

**Comment by marco-aa** [comment]
@JohnBFrm i think it a usefull feature, too
at the moment i use a work around inspired by #795 by the way the want a similar feature

```
use yourMongDB-parties-or-rocketchat
db.rocketchat_message.createIndex( { "ts": 1 }, { expireAfterSeconds: 65 } )
``` 
mabye you have to change ts:1 to ts:XXX - and i have disabled fileupload and users can only edit / delete messages for 60 seconds this should prevent side effects. If you login later the messages are deleted by the expireAfterSeconds inside the mongoDB

**Comment by WebSavvyGuy** [comment]
@marco-aa 

Hi thanks for pointing to that link.

Do you have any idea of this error?   If i use another value such as "ts":100 it works, but not sure what this all means.  What does the "ts" represent?   Can this "script" be deleted?

```
rs0:PRIMARY> db.rocketchat_message.createIndex( { "ts": 1 }, { expireAfterSeconds: 3600 } )

{
	"ok" : 0,
	"errmsg" : "Index with name: ts_1 already exists with different options",
	"code" : 85
}
```

**Comment by marco-aa** [comment]
Dear @WebSavvyGuy i'm new to mongodb - what i read was you define this way a index. The index { "ts": 1 } was created befor i guess at creation time of the collection or via a migration. If you use { "ts": 100  } you create a new index. The expire defines the time how long mongo will hold the entry in the collection for rocket_message. It's a like in memcache the database engine will remove the data by it self.
As long as no migration/software update will use the same index key-name it will work i guess. 
``db.rocketchat_messages.getIndexes()`` will show you the created indexes

**Comment by marceloschmidt** [comment]
We've implemented the auto-prune feature, which may solve this problem for you. Thanks.
