### ISSUE TITLE
Set Max upload size in Settings under Administrator Account

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#756]
Useful for when the system is being used internally on a LAN where file size and upload speed is not an issue.

**Comment by jelenajjo** [comment]
:+1:

**Comment by jelenajjo** [comment]
Yep we need this for sure! 

:+1:

**Comment by shtefcs** [comment]
I had cases on my team chat that we needed this, so we moved conversation over skype cause of file limit.

:+1:

**Comment by gmsecrieru** [comment]
Depends on #913 -- otherwise clients would need to refresh screen for settings to apply.

**Comment by storrgie** [comment]
+1
