### ISSUE TITLE
Cannot Redefine URL of RocketChat

### ISSUE THREAD

**Issue by HewittJC** [RocketChat/Rocket.Chat#7560]
### Description:

Setting up server with docker I should be able to set rocket chat to be visible at https://example.com/chat-url

According to my searches I only need to change the ROOT_URL in the docker compose file. This has led to an "unknown path" error message.

### Server Setup Information:

* Version of Rocket.Chat Server: Latest (as of this post date)
* Operating System: Ubuntu Server 16.04
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1

### Steps to Reproduce:

1. Install using docker
2. Make nginx listen on my obfuscated URL (i.e. location '/chat-url/')
3. Go to said url

### Expected behavior:

See login screen

### Actual behavior:

Error message that reads "unknown path"

### Other Info

If I change the ROOT_URL to just https://example.com/ I get a blue screen (the default background image) and the loading dots that are there indefinitely.

If I change the ROOT_URL to https://example.com/chat-url/ I see "unknown path" when I navigate to that location.

If I allow my site to be accessed in the nginx config as https://example.com/ then I can see the login and it works just fine. So the install works but I am unable to change the URL location correctly.

Also, when I am looking at the web inspector I notice that the main request is successful but the .css files all have 403 errors due to the fact that they are being looked for at https://example.com/file.css instead of https://example.com/chat-url/file.css

**Comment by HewittJC** [comment]
The issue was that I needed to explicitly pass the "/chat-url/" in my proxy_pass line in my nginx config...

**Comment by premdasvm** [comment]
> 
> ### Description:
> 
> Setting up server with docker I should be able to set rocket chat to be visible at https://example.com/chat-url
> 
> According to my searches I only need to change the ROOT_URL in the docker compose file. This has led to an "unknown path" error message.
> ### Server Setup Information:
> 
>     * Version of Rocket.Chat Server: Latest (as of this post date)
> 
>     * Operating System: Ubuntu Server 16.04
> 
>     * Deployment Method(snap/docker/tar/etc): Docker
> 
>     * Number of Running Instances: 1
> 
> 
> ### Steps to Reproduce:
> 
>     1. Install using docker
> 
>     2. Make nginx listen on my obfuscated URL (i.e. location '/chat-url/')
> 
>     3. Go to said url
> 
> 
> ### Expected behavior:
> 
> See login screen
> ### Actual behavior:
> 
> Error message that reads "unknown path"
> ### Other Info
> 
> If I change the ROOT_URL to just https://example.com/ I get a blue screen (the default background image) and the loading dots that are there indefinitely.
> 
> If I change the ROOT_URL to https://example.com/chat-url/ I see "unknown path" when I navigate to that location.
> 
> If I allow my site to be accessed in the nginx config as https://example.com/ then I can see the login and it works just fine. So the install works but I am unable to change the URL location correctly.
> 
> Also, when I am looking at the web inspector I notice that the main request is successful but the .css files all have 403 errors due to the fact that they are being looked for at https://example.com/file.css instead of https://example.com/chat-url/file.css

same issue i'm facing now, how did u fix it.?

**Comment by nguyenorlab** [comment]
sorry, anyone fixed this issue??

**Comment by Michuelnik** [comment]
> sorry, anyone fixed this issue??

I've had an error in the provided compose.yml, check with `docker-compose config`.
It rendered an erroneous trailing `}` to the ROOT_URL:
`ROOT_URL=https://rocketchat.example.com/}`
After fixing this the error went away.

**Comment by kavishkagihan** [comment]
> > sorry, anyone fixed this issue??
> 
> I've had an error in the provided compose.yml, check with `docker-compose config`. It rendered an erroneous trailing `}` to the ROOT_URL: `ROOT_URL=https://rocketchat.example.com/}` After fixing this the error went away.

I am having the exact same issue, but my config looks fine. 

```
ROOT_URL=http://chat.dev.local/
HOST_PORT=80
```


And even rocketchat itself says what the exact is.

```
rocketchat_1  | +------------------------------------------------+
rocketchat_1  | |                 SERVER RUNNING                 |
rocketchat_1  | +------------------------------------------------+
rocketchat_1  | |                                                |
rocketchat_1  | |  Rocket.Chat Version: 6.4.8                    |
rocketchat_1  | |       NodeJS Version: 14.21.3 - x64            |
rocketchat_1  | |      MongoDB Version: 5.0.22                   |
rocketchat_1  | |       MongoDB Engine: wiredTiger               |
rocketchat_1  | |             Platform: linux                    |
rocketchat_1  | |         Process Port: 3000                     |
rocketchat_1  | |             Site URL: http://chat.dev.local/}  |
rocketchat_1  | |     ReplicaSet OpLog: Enabled                  |
rocketchat_1  | |          Commit Hash: 133e7444b6               |
rocketchat_1  | |        Commit Branch: HEAD                     |
rocketchat_1  | |                                                |
rocketchat_1  | +------------------------------------------------+

```

I am not using a reverse proxy either, just trying to access it directly with the hostname and the ip. It still gives me the `Unknown path` error.

**Comment by tongjun741** [comment]
You can enter the docker container and print the ROOT_URL environment variable to check whether it is correct.
`echo $ROOT_URL
http://192.168.1.127:3000/}`

Modify ROOT_URL in compose.yml: to http://YourIp:3000/

**Comment by userLlamma** [comment]
> > sorry, anyone fixed this issue??
> 
> I've had an error in the provided compose.yml, check with `docker-compose config`. It rendered an erroneous trailing `}` to the ROOT_URL: `ROOT_URL=https://rocketchat.example.com/}` After fixing this the error went away.

You are genious, how could this happen with tested docker image?
