### ISSUE TITLE
Unread Favicon not being added on direct message

### ISSUE THREAD

**Issue by zahaim** [RocketChat/Rocket.Chat#7568]
### Description:

Users accessing RocketChat with browsers are not aware of direct messages. Adding a notification with a count of unread direct messages like in gmail would be beneficial. Something like `(1)` before the name of RocketChat instance on the browser tab.

### Server Setup Information:

Any versions actually.

### Steps to Reproduce:

1. Use browser to reach RocketChat
2. Get direct message

### Expected behavior:

See (1) before the name of RocketChat instance

### Actual behavior:

Do not see (1) before the name of RocketChat instance

**Comment by MartinSchoeler** [comment]
Confirmed on latest develop branch, but strangely enough it work as intended on our demo server
