### ISSUE TITLE
Anti-Virus checking on file uploads?

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#757]
Some form of AV checking for uploaded files before its available for everyone on the channel to open, if its flagged reject the upload.
##

**Comment by mhenninghaus77** [comment]
it´s a very important Feature!!! Do you know a Workaround instead?

**Comment by k0nsl** [comment]
Yes, something local or VirusTotal (or similar) integration would have been a great feature to have.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

The concept of scanning for viruses is dead from a security perspective. Scanners (especially those that implment the file format they scan) introduce more code that opens up attack surface, also signature-based models are too slow in deployment to be of use.

Closing this.

Cheers
Thomas
