### ISSUE TITLE
New feature: allow extensions to gear bar

### ISSUE THREAD

**Issue by pascalrobert** [RocketChat/Rocket.Chat#7575]
### Description:

It would be great to be able to extend the gear bar to add custom actions in it. For example, let's say you want to push a post to a ticket in JIRA, we could add an icon with an action in the gear bar to do so.

**Comment by geekgonecrazy** [comment]
This functionality is actually currently in process of being added via rocketlets.

**Comment by graywolf336** [comment]
Will be included with #6890 :)

**Comment by graywolf336** [comment]
Closing this in favor of #6890
