### ISSUE TITLE
Add WeChat Oauth

### ISSUE THREAD

**Issue by ottomMT** [RocketChat/Rocket.Chat#7576]
Could we have a WeChat login, so we could use it in China,thanks a lot

**Comment by geekgonecrazy** [comment]
Going to close and refer this to a feature request already open on the forums: https://forums.rocket.chat/t/wechat-integration-planned/122/5

But just to note, you can still login with username and password :smile:

**Comment by lhr0909** [comment]
We took our first pass and managed to hack the custom OAuth process to support WeChat OAuth for now - https://github.com/xanthous-tech/Rocket.Chat/pull/1

We would love to get feedback in this PR and make some adjustments to make it proper before raising the PR into this repo. Thanks.
