### ISSUE TITLE
Include alias in reply to bot message with alias

### ISSUE THREAD

**Issue by jangmarker** [RocketChat/Rocket.Chat#7581]
### Description:
When replying to a message with an alias that is a valid user's name or id (e.g. sent by hubot using `customMessage`) the reply is targeted at the bot only, but not to the alias.

### Server Setup Information:
* Version of Rocket.Chat Server: 0.55.1
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.8.0

### Steps to Reproduce:

1. Make sure you have a user "some.user" in your Rocket.chat
1. Use the Rocket.chat hubot adapter's `customMessage` function with `alias=some.user`
   ```JavaScript
   robot.adapter.customMessage({
     msg: "reply to me, please!",
     channel: roomId,
     alias: "some.user",
     avatar: avatarUrls["some.user"],
   });
   ```
2. open the room in Rocket.chat and reply to the message the bot just sent

### Expected behavior:

The reply is addressed to `@some.user`, too. If the alias is a user's display name, the corresponding id should be used.

### Actual behavior:

The reply is only addressed to `@hubot`.

### Explanation with graphics

![image](https://user-images.githubusercontent.com/6429953/28856273-a61819c0-7707-11e7-86ea-99d20808ec4e.png)   **=>**   ![spectacle n17483](https://user-images.githubusercontent.com/6429953/28856381-44c69a38-7708-11e7-932f-77619d622285.png)

In the left picture, you see that at 11:19 AM the hubot sent a message with the alias "root" (which is a valid user). When root replied to this message at 11:20 AM the reply is targeted at hubot (`@hubot thank you!`).
Because the alias of the original message is a valid user, I would like the reply to look like this: `@hubot @root thank you!`) - as shown in the right picture.

I know this can be achieved by manually writing `@root` in the reply, but it is more convenient, especially for inexperienced users, if Rocket.chat does that by itself.

**Comment by graywolf336** [comment]
@jangmarker can you post a screenshot to provide some visual aid of what the current behavior is versus what you are expecting?

**Comment by jangmarker** [comment]
> @jangmarker can you post a screenshot to provide some visual aid of what the current behavior is versus what you are expecting?
I've added graphics, is it clearer now?

**Comment by timkinnane** [comment]
This is not any clearer to me. I'm trying to figure out what the desired behavior is, but the references are confusing. I don't understand why the Hubot is using a user's name as an alias, and it seems like you're asking for a system change that would modify the text of a message sent **to** hubot, by the user. I don't think there's ever a situation where we would want to be automatically editing user's messages, regardless if they're talking to bots.
I would suggest this could be achieved for your instance by a Hubot script, if you give the bot permission to edit other user's messages, it could check the incoming message, see if it's responding to the bot that was using an alias, then modify the message to include the alias. I still don't understand why you would do any of that, but I don't think it would be an accepted change in Rocket.Chat core.
I'm closing this now, if this comment misunderstood the issue, please re-open.
