### ISSUE TITLE
DDP slingshot/uploadRequest returns "The directive rocketchat-uploads does not seem to exist"

### ISSUE THREAD

**Issue by Davide95** [RocketChat/Rocket.Chat#7584]
### Description:

In order to send an attachment on Rocket.Chat following [docs](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message) I have to send a slingshot/uploadRequest request, but it returns an error message: "The directive rocketchat-uploads does not seem to exist".

### Server Setup Information:
* GridFS for storage

### Actual behavior:

The request is:
```
{
   "msg":"method",
   "method":"slingshot\/uploadRequest",
   "id":"1501153850875-5",
   "params":[
      "rocketchat-uploads",
      {
         "size":10,
         "name":"testo.jpg",
         "type":"application\/octet-stream"
      },
      {
         "rid":"aac7KBHmdfwMnHvFk"
      }
   ]
}
```

The response is:
```
{
   "msg":"result",
   "id":"1501153850875-5",
   "error":{
      "reason":"The directive rocketchat-uploads does not seem to exist",
      "errorType":"Meteor.Error",
      "error":"Invalid directive",
      "message":"The directive rocketchat-uploads does not seem to exist [Invalid directive]"
   }
}
```

**Comment by haffla** [comment]
In the docs it says

`"rocketchat-uploads", // no ideia`

Is it even possible to upload files via Realtime API? Care to comment someone?

**Comment by haffla** [comment]
It only works with AmazonS3, sadly

**Comment by zofe** [comment]
up,  I need upload file via custom javascript api via google cloud storage

**Comment by Davide95** [comment]
> up, I need upload file via custom javascript api via google cloud storage

Unfortunately it still sucks.
I found a way long time ago. You just have to (temporary) get rid of DDP and move to WSS.
You can probably find the solution here (https://cgit.kde.org/scratch/davider/canaveral.git/about/) or here (https://github.com/KDE/brooklyn/blob/master/src/main/java/bots/RocketChatBot.java).
Let me know :)

**Comment by zofe** [comment]
@Davide95 thanks!

**Comment by geekgonecrazy** [comment]
Slingshot no longer used.  Closing

**Comment by fralau** [comment]
The documentation still gives that as a model
(https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message/#sending-a-file)

**Comment by geekgonecrazy** [comment]
It shouldn't be, this would be the ideal way now to upload files: https://rocket.chat/docs/developer-guides/rest-api/rooms/upload/

**Comment by geekgonecrazy** [comment]
PR to fix: https://github.com/RocketChat/docs/pull/1359
