### ISSUE TITLE
LDAP authentication not working!

### ISSUE THREAD

**Issue by ryan-plz** [RocketChat/Rocket.Chat#7585]
Rocket.Chat Version: 0.57.2
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.5

Hi everyone. I'm a Newbie. 

I've installed and set up LDAP authentication, Test Connection Success, Sync User Success. But When log in returns "User not found or incorrect password".
I'm using below setting.

LDAP Enable: True
Login Fallback: False

Domain Base: dc=xx,dc=xxxx
Domain Search Filter: memberOf=CN=Employees,OU=SecurityGroups,DC=xx,DC=xxxx
Enable LDAP user group filter: False
Domain Search User ID: sAMAccountName
Domain Search Object Class: user
Domain Search Object Category: 
Username Field: sAMAccountName
Unique Identifier Field: 
Sync Data: True
Sync User Avatar: True
User Data Field Map: {"cn":"name","mail":"email"}
Default Domain: dc=domain,dc=xxxx
Merge existing users: True
Import LDAP users: False

What's wrong with that configuration? Many Thanks!

Logs :+1:
 [34mI20170722-18:10:08.281(7) [34mMeteor ➔ method ldap_test_connection -> userId: ft2XuWbBX7smZdnGA , arguments:  {} 
[34mI20170722-18:10:08.283(7) [34mLDAP ➔ Connection.info Init setup 
[34mI20170722-18:10:08.284(7) [34mLDAP ➔ Connection.info Connecting ldap://IP Active DirectoryD:389 
[34mI20170722-18:10:08.285(7) [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://172.29.151.20:389',   timeout: 600000,   connectTimeout: 600000,   idleTimeout: 600000,   reconnect: false } 
[34mI20170722-18:10:08.291(7) [34mLDAP ➔ Connection.info LDAP connected 
[34mI20170722-18:10:08.291(7) [34mLDAP ➔ Connection.info Disconecting 
[34mI20170722-18:10:10.093(7) [34mMeteor ➔ method ldap_sync_users -> userId: ft2XuWbBX7smZdnGA , arguments:  {} 
[34mI20170722-18:10:10.095(7) [34mLDAP ➔ Connection.info Init setup 
[34mI20170722-18:10:10.096(7) [34mLDAP ➔ Connection.info Connecting ldap://IP Active DirectoryD:389 
[34mI20170722-18:10:10.097(7) [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://IP AD:389',   timeout: 600000,   connectTimeout: 600000,   idleTimeout: 600000,   reconnect: false } 
[34mI20170722-18:10:10.100(7) [34mLDAP ➔ Connection.info LDAP connected 
[34mI20170722-18:10:10.101(7) [34mLDAP ➔ Connection.info Disconecting

**Comment by Archer4l** [comment]
Hi. Try set  Sync User Avatar: False and check login again.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
