### ISSUE TITLE
An idea for gitlab integration

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#759]
The idea is possibly when you visit home page of a project in gitlab, you have the rocket.chat popup window available so you can live chat with other project members.
##

**Comment by geekgonecrazy** [comment]
Oops. :) 

So would this really be us or more of the gitlab team?  I mean we could implement the methods to allow this.  But actual implementing would be theirs.

**Comment by Sing-Li** [comment]
![marcelo](https://cloud.githubusercontent.com/assets/122633/10031757/fe0afaee-614c-11e5-9f9f-e6976596e39c.png)

So we're ready!  ( thanks a million -- @sampaiodiego ! )    

Gitlab can integrate this into their product as an option.   

But in the meantime, @rockneverdies55,  you can hack it into Gitlab CE for your own hosted projects.

**Comment by rodrigok** [comment]
Awesome :smiley: :clap: :sunglasses: 

Looks great, congratulations

**Comment by jaimathur** [comment]
Hi Sing-Li,
I want to integrate Rocket.Chat into GitLab so that when a user comes to home page of GitLab they should see the small rocket.chat window and the users can chat with each other. Kindly guide with the procedure of how to integrate rocket.chat with gitlab.

**Comment by pushpdeep** [comment]
@Sing-Li 

I want to integrate Rocket.Chat into GitLab so that when a user comes to home page of GitLab they should see the small rocket.chat window and the users can chat with each other. Kindly guide with the procedure of how to integrate rocket.chat with gitlab.

**Comment by graywolf336** [comment]
@Sing-Li do you still have the code for this feature somewhere?

**Comment by pushpdeep** [comment]
@graywolf336 @Sing-Li  Just eagerly waiting for this feature

**Comment by jelenajjo** [comment]
This is awesome!

**Comment by pushpdeep** [comment]
@Sing-Li Hey, so can you share the way you could do it for a local project within CE . i am eager to try this out.

**Comment by StephanBleh** [comment]
@Sing-Li when is it possible in EE?

**Comment by SeanPackham** [comment]
This depends on GitLab choosing to integrate Rocket.Chat. Closing issue.
