### ISSUE TITLE
In a readonly channel, the Owner could not sent messages

### ISSUE THREAD

**Issue by ottomMT** [RocketChat/Rocket.Chat#7597]
In a readonly channel, the Owner could not sent messages, and just the admin could.

I think its unreasonable.

**Comment by jszaszvari** [comment]
That defeats the purpose of a 'Read Only' channel. They should be used for notifications or incoming webhooks

**Comment by ottomMT** [comment]
Ok,thank you!

I have guessed:the owner say, others just listen~

**Comment by MartinSchoeler** [comment]
@ottomMT this behavior can be changed by adding or removing the `post-read-only` permission. If you add this permissions to the `owner` they will be able to post in read only channels
