### ISSUE TITLE
About the "rocket.chat" bot, renamed,and come out again!

### ISSUE THREAD

**Issue by ottomMT** [RocketChat/Rocket.Chat#7598]
In the admin panel, the users,I have rename the bot called "rocket.chat".

But when I was muted, there was a bot called "rocket.chat" remind me "you were muted...balabala"

So,my question is ,where from this "rocket.chat" bot. 

Thanks!

**Comment by jszaszvari** [comment]
That's not the bot that's a setting under 

Admin -> Messages -> Hide "User Muted / Unmuted" messages

**Comment by ottomMT** [comment]
Thank you very much!
