### ISSUE TITLE
Inform user of email validation after account register

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#76]

**Comment by engelgabriel** [comment]
Needs to take in consideration #22

**Comment by wildaces215** [comment]
Is this issue still open?

**Comment by mnt** [comment]
I could probably do this 😄

**Comment by engelgabriel** [comment]
Please do @mnt  :)

**Comment by engelgabriel** [comment]
@MartinSchoeler please verify this one.

**Comment by MartinSchoeler** [comment]
you must have the SMTP setting active to this to happen.
