### ISSUE TITLE
Uploaded files list, either an option on the right hand pane or thru history option?

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#760]
Would be good if you can see a list of all files uploaded to a channel, it could be available thru the history option and maybe searchable? Useful to find specific drawings\documents when the channel content is high.

**Comment by Megatronic79** [comment]
same goes for URL links added to the channels ( Much like the Hip Chat client has?)

**Comment by rockneverdies55** [comment]
+1

Definitely a good idea.

**Comment by Sing-Li** [comment]
Hmmm... our uploaded files are externally accessible without authentication. Need to think hard b4 proceeding with this one, we don't want every Rocket.Chat hoster to inadvertently become a free XBMC video host.

**Comment by Megatronic79** [comment]
Yeah sure, could we have the option to have some channels that require authentication to follow the URL to the document? was the reason they are publically available for sharing?

if so maybe we could lock all documents to internally authenticated users and have the option to send out a link via email and set a pass code to acces? keeps everything under control?

Much like OwnCloud's share option?

**Comment by graywolf336** [comment]
@Sing-Li #724 is an issue I created about uploads not being protected at all, which is an issue for me as I don't want any files to be made publically accessible unless they are explicitly marked as public downloads.

**Comment by Megatronic79** [comment]
So we should mark this ticket as depends on #724

**Comment by geekgonecrazy** [comment]
This is definitely planned.  But I agree we should for sure finish #724 to prevent abuse.

**Comment by marceloschmidt** [comment]
Related to #308

**Comment by gmsecrieru** [comment]
Closing this based on #955

**Comment by gmsecrieru** [comment]
Closing this based on #955

**Comment by Megatronic79** [comment]
Yep tested that earlier looks good!

Should focus on the #724 for the public facing instances.

**Comment by gmsecrieru** [comment]
:+1:
