### ISSUE TITLE
URL issues

### ISSUE THREAD

**Issue by moisesmcardona** [RocketChat/Rocket.Chat#7600]
Whenever I add a link that contains @myusername, the message would be converted to this:

`@moisesmcardona/app-para-el-chat-steemhispanos-chat-chat-oficial-de-mi-witness-para-la-comunidad-hispana" target="_blank" rel="noopener noreferrer">https://steemit.com/spanish/@moisesmcardona/app-para-el-chat-steemhispanos-chat-chat-oficial-de-mi-witness-para-la-comunidad-hispana`

Instead of showing the correct message which should be the link only:

`https://steemit.com/spanish/@moisesmcardona/app-para-el-chat-steemhispanos-chat-chat-oficial-de-mi-witness-para-la-comunidad-hispana`

Is this a known bug or bad configuration at my server?

I'm using the latest release 0.57.2.

Thanks for your support!

**Comment by TwizzyDizzy** [comment]
Still present in 0.61.0, just verified on open.rocket.chat.

**Comment by MartinSchoeler** [comment]
It seems to be working in 0.71.0. If you experience this again, please open a new issue with updated details. Thanks!
