### ISSUE TITLE
Reply to chat from email notifications

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7601]
Allow users to reply to missed direct message notifications via email. 

The reply address would be a unique identifier @ the domain and the email message would be converted into a direct message reply. 

This could theoretically be implemented for rooms/channels as well but may be a bit more complex.

**Comment by pkgodara** [comment]
WIP #7342 .

**Comment by rodrigok** [comment]
Closed via #7342
