### ISSUE TITLE
Accessing the database in Rocket chat

### ISSUE THREAD

**Issue by YehualashetGit** [RocketChat/Rocket.Chat#7603]
I have deploy Rocket chat using Docker hub and integrate it to GitHub and it works perfectly, but I cannot Access the mongo shell to update and see user and also to do some staff .so can any one help me how to access it Thank you!!!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by YehualashetGit** [comment]
ok but, I am asking not reporting a bug if u know, how to access the database in docker server please answer me now !!

**Comment by YehualashetGit** [comment]
Hello,agin, please tell me how to access the database of rocketchat , I
deployed using docker and I am un able to access, so can u give me some
directions to access it tank u!!!
