### ISSUE TITLE
Need to see the list of all users 

### ISSUE THREAD

**Issue by zipper2110** [RocketChat/Rocket.Chat#7604]
It would be really helpful to see the list of all chat users somewhere instead of searching users using the search textfield.

If you click on the search textfield you almost get that list, but it doesn't display all users, just a subset.

There is about 30 users in our chat, and there is a strong need to see the list of all users somewhere around, one click away at most (it could be an "all users" link somewhere with a popup window). Click on a user opens direct message dialog with that user.

Is there a way for me to tune the chat right now to get that list? If not, then can this feature be planned and placed in the issues list at least for someone to implement it in the future?

Or am I completely wrong with that desire to have the list of all users in the chat UI?

**Comment by jblobel** [comment]
Doesn't the default channel serve this purpose ?

**Comment by zipper2110** [comment]
Technically it does, except it is not untuitive and you can't have it in your sight all the time. My point is the list of all users might be the starting point of the app: you look through the list, find the user you want to write to, leave a message then go through the list again and so on.

**Comment by jblobel** [comment]
Maybe you should use ICQ or Pidgin if you want a user oriented chat application...

**Comment by sampaiodiego** [comment]
you can see that on `Directory` page =)

**Comment by deadmanIsARabbit** [comment]
@sampaiodiego that is not correct. 
The `directory` page doesn't have the ability to show only those users who are online.
The `default` channel would serve this purpose (in a cheated manner) if the user list would also have a keyboard shortcut. Theoretically there could be still users online which are not in the default channel.

So something like the `search` page but with more then those few entries that are currently visible and without any channels would rather serve this purpose.

**Comment by sampaiodiego** [comment]
@deadmanIsARabbit that is a different need than the one asked on the issue.

in fact, there is no place to get all online users of the entire server. that could be fixed by adding a filter on Directory page, what do you think?

**Comment by deadmanIsARabbit** [comment]
@sampaiodiego Sure that would be a fix. But a keyboard shortcut for a direct access to this filter would be essential.
CTRL+ALT+L(ist) maybe? It seems it is neither used by Chrome nor by Firefox. 

And I think this would satisfy what @zipper2110 requested?  I mean as long as you have fast access it should be sufficient. 

May I ask if it would be a general solution to make the items on the `side nav` collapsible and integrate this filter there underneath the `private messages` maybe? (But i would totally see this in another ticket)
