### ISSUE TITLE
Customfields not displayed

### ISSUE THREAD

**Issue by marco-aa** [RocketChat/Rocket.Chat#7607]
Dear Community,

i'm running rocket.chat 0.57.2 via snap on Ubuntu 16 LTS.

I added a customfield via REST-API and i can see it in mongodb. 

The customfield is not displayed to other users i added view-full-other-user-info to users and guest roles.

looks like the last comments in #2304

**Comment by MartinSchoeler** [comment]
We're sorry, but your issue doesn't follow our issue guidelines and templating. Please, [double-check](https://rocket.chat/docs/contributing/reporting-issues) and re-open if you believe this needs further discussion.
