### ISSUE TITLE
Jitsi-meet login credentials

### ISSUE THREAD

**Issue by ctel** [RocketChat/Rocket.Chat#7611]
We attempt to integrate jitsi (with prosody) more tightly into rocket-chat: Is there a simple way to pass the user credentials to jitsi-meet? If configuring jitsi to only allow authenticated users, users always see the user-password popup within jitsi (due to its iframic/xmpp-ish nature). Is that the intended way or did I configure something horribly wrong?
Alternatively I thought about integrating a simple external auth provider into prosody using the rocket chat api: Is there an API endpoint within rocket-chat, so one could build the following (or similar) setup?
```
rocketChat <-- authenticates with user credentials -- browser
rocketChat <-- creates an auth token for this session+user --> browser
rocketChat <-- delegated token-test by authprovider -- external-prosody <-- uses created auth token and user for auth -- jitsi-meet <-- API(jitsi) -- browser
```

**Comment by dmoldovan123** [comment]
+1

**Comment by geekgonecrazy** [comment]
I don't believe we have a way to do that currently.

**Comment by fchiacchiaretta** [comment]
+1
A deeper integration with jitsi-meet would be great; I currently have my own jitsi-meet server with prosody and would like to programmatically send fixed credentials to prosody from Rocket.Chat.

**Comment by xnextx** [comment]
+1

**Comment by Brightside56** [comment]
+1

**Comment by rrzharikov** [comment]
+1

**Comment by alonelion1987** [comment]
Hello team!

I have a solution to this problem and I **_would like to contribute_**.

My code solves the problem with external JWT- authorization. If the application Jitsi-Meet is configured on your server with mandatory authorization through JWT- tokens, then in your RocketChat, in the settings, you can specify your domain, enable JWT- authorization, specify the application identifier ("iss") and the secret key application. When creating a videoconference in your RocketChat through Jitsi, a one-hour token will be created with the context of this authorized user in your RocketChat and authorized in your Jitsi-Meet app. You can read more about JWT- authorization here https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md.
