### ISSUE TITLE
Message Timelines

### ISSUE THREAD

**Issue by guarilha** [RocketChat/Rocket.Chat#762]
In some cases it's interesting to filter messages of a given type (file uploads & links #760, starred messages #310, @-mentions) and display them on a timeline. 

Slack does this a lot. A couple of examples: 

![image](https://cloud.githubusercontent.com/assets/902478/9819193/0533916e-5883-11e5-9af1-2082dd90c4be.png)

![image](https://cloud.githubusercontent.com/assets/902478/9819240/3591ad5a-5883-11e5-9eeb-5b55e262236b.png)

**Comment by Sing-Li** [comment]
:+1: The ability to access messages concurrently on multiple timelines, in additional to 'the 'natural' server one, at native+ speed is one of the fundamental requirements for unlocking the next generation of Rocket.Chat features - #279

**Comment by engelgabriel** [comment]
Done
