### ISSUE TITLE
What is the best and simplest way to deploy fork version in production

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7626]
I'm a little new in RC and done some play with it as a fork. Now I want to deploy my customized version to an Ubuntu VPS. I saw that most of the deploy method use `https://rocket.chat/releases/latest/download` so I want to know what is the best way to deploy RC to an Ubuntu VPS with high reliable state (for example with PM2 cluster and Mongo ReplicaSet)
Have anyone can help me about it?
I can't find anything in docs about custom fork deployment.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
