### ISSUE TITLE
How to change MongoDB port?

### ISSUE THREAD

**Issue by jpotts-IIL** [RocketChat/Rocket.Chat#7627]
### Description:

I have another service that is running an instance of MongoDB, as such the port is already being used and RocketChat cant run.

The RocketChat Server is running, but ther RocketChat Mongo is not. Is it possible to change the port for rocketchats instance of MongoDB

This is the error in the log file for Mongo:
`snap[12175]: 2017-08-01T14:46:34.788+0100 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 127.0.0.1:27017`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Ubuntu 17.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by jakswa** [comment]
+1 -- already running mongodb
