### ISSUE TITLE
Feature request: permission mention-here which is an analog of mention-all

### ISSUE THREAD

**Issue by ryjones** [RocketChat/Rocket.Chat#7631]
I would like a permission as previously implemented as mention-all, called mention-here with the same abilities to restrict use of the @ here alias

**Comment by cr22rc** [comment]
+1

**Comment by ghaskins** [comment]
+1

**Comment by kchristidis** [comment]
+100

**Comment by jyellick** [comment]
+1

**Comment by Asara** [comment]
Please implement this!  It would be highly appreciated.

**Comment by smithbk** [comment]
+1

**Comment by smithbk** [comment]
+1
