### ISSUE TITLE
Issue with text message container

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat#7632]
* Version of Rocket.Chat Server: 0.58.0-rc.0
* Operating System: Ubuntu Linux 16.04.1 LTS
* Deployment Method: snap
* Nove Version: 8.1.3
* NPM Version: 5.1.0

With the new update of rocketchat 0.58.0-rc.0, the text message container gets broken when a long text is submitted... as you can see the box gets overflowed in the page...

![](http://i.imgur.com/suaj3EC.jpg)

**Comment by MartinSchoeler** [comment]
fixed by #7629
