### ISSUE TITLE
Change Default Notification

### ISSUE THREAD

**Issue by sagarshah8814** [RocketChat/Rocket.Chat#7633]
Hello,

I want to set default notification automatically as all messages for desktop and mobile, currently it is mentions. Can anyone tell me how this can be done?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
