### ISSUE TITLE
how to pass RoomName or RoomID to WebRTC or jitsi video bridege 

### ISSUE THREAD

**Issue by MayraDesai** [RocketChat/Rocket.Chat#7637]
<div>
    <h2 id="meet">Jitsi</h2>

</div>
@section Scripts {
<script src="https://meet.jit.si/external_api.js"></script>
<script type="text/javascript">
    var domain = "demo.rocket.chat/";
    var options = {
        roomName: "direct/Jaydeep",
        width: 700,
        height: 700,
        parentNode: document.querySelector('#meet')
    }
    var api = new JitsiMeetExternalAPI(domain, options);
</script>
    }

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
