### ISSUE TITLE
Direct Messages ignoring mentions only notification settings. 57.1 - 58.rc0

### ISSUE THREAD

**Issue by stalley** [RocketChat/Rocket.Chat#7640]
### Description:

Direct messages will notify on all messages regardless of mobile or desktop preferences for all messages
or mentions only. Setting to no notifications for desktop or mobile DOES work.

Channels seem to be working properly.

### Server Setup Information:

* Version of Rocket.Chat Server: Tested on 57.1,57.2 and 58.rc0
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: No
* Node Version: 4.5.0

### Steps to Reproduce:

1. Change notification for direct message for desktop or mobile to mentions either via user options or admin default if using 
    58.rc0
2.  Send message in direct message to user.
3. Desktop will show notification and if away mobile will show notification.

### Expected behavior:

Should follow the same rules as channels and only notify mentions if mentions are selected.

### Actual behavior:

Desktop or Mobile will show all message even if mentions only is selected

**Comment by vnkmpf** [comment]
Same problem. I would like to add it happened even in v 0.59 / develop.

Also when in DM you check Right panel -> Notifications -> Disable notifications,
both desktop notifications and sound notifications are always active.

**Comment by TwizzyDizzy** [comment]
Still present in 0.62.1?

Cheers
Thomas

**Comment by vnkmpf** [comment]
I'm testing on 0.62.2.
When I disable notifications in DM for a user, no popup appears = correct.
When I set it to "nothing", no popup appears = correct.
When set to "mentions", popup does appear. I'm not sure if this should or should not appear. There probably isn't much reason to use "@" in DM, on the other hand, the settings say "mentions".

It looks like working fine with global settings to me.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Splendid, thanks for getting back. Then I'm closing this for now :)

Cheers
Thomas
