### ISSUE TITLE
API login doesn't work with an LDAP user when "Login Fallback" parameter is False

### ISSUE THREAD

**Issue by AceSlash** [RocketChat/Rocket.Chat#7642]
### Description:
Configure LDAP auth with "Login Fallback" parameter to False.

Log yourself with a valid user normally to validate that the user/pass is valid.

Use the same user/pass to perform an API authentication:
```
curl -H "Content-type:application/json" http://localhost:3000/api/v1/login -d '{ "username": "supervisor", "password": "xxxxxxx" }'
{
  "status": "error",
  "message": "Unauthorized"
}
```
Change the "Login Fallback" parameter to True, then log yourself again on the web interface with the same user to store the password in the local database, you then set the "Login Fallback" parameter to False again, it doesn't mater.

The authentication will now work with the same login/pass:
```
curl -H "Content-type:application/json" http://localhost:3000/api/v1/login -d '{ "username": "supervisor", "password": "xxxxxxx" }'
{
  "status": "success",
  "data": {
    "authToken": "KJQhGtdtBb0ecSn3CUQCpCWNUB6nVhpA226GEMM_72M",
    "userId": "tkBC5AEQvDLZ5SqNc"
  }
}
```
The API should ask LDAP when a user tries to use it and LDAP is active.
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: 4.5.0

**Comment by AceSlash** [comment]
I can't reproduce this on an other instance... I think that the issue is that I did use the "Sync Users" Button with "Import LDAP users" before trying to log in with the user on the API.

**Comment by Siedlerchr** [comment]
See also  #4961

**Comment by monspid** [comment]
I have the same problem. I cannot login with LDAP login.

**Comment by maximus-dv10** [comment]
Same here. Is there any updates on this ticket?
