### ISSUE TITLE
How to integrate Rocket.chat in drupal 7 ?

### ISSUE THREAD

**Issue by shreeshagundmi** [RocketChat/Rocket.Chat#7646]
Hi team,

I am new to Rocket.chat drupal module.

i am using drupal 7 and trying to install rocket.chat module. 

can any one please help me how to integrate rocket live chat in drupal 7?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
