### ISSUE TITLE
entering multi line messages does not expand text area in 0.58.0-rc.0

### ISSUE THREAD

**Issue by 7obywankenobi** [RocketChat/Rocket.Chat#7647]
### Description:

Regression in Rocket.Chat Server 0.58.0-rc.0 (works in 0.57.2):

Entering a multi line message does not expand area and renders all lines >= 4 below the fold and not readable at all.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.0-rc.0
* Operating System: CentOS 7.3
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: ?
* DB Replicaset Oplog: ?
* Node Version: 4.8.4

### Steps to Reproduce:

1. enter multi line message
2. see 4th line scrolling out of visible area. No way to read text; text area does not expand

Testet with the following Clients
- Ubuntu 16.04.2 x64 Firefox 54.0
- Ubuntu 16.04.2 x64 RocketChat Desktop Client 2.8.0
- Windows 10 Build 1703 Chrome 59.0.3071.115

### Expected behavior:

entire multi line message visible

### Actual behavior:

only first three lines visible:

![multiline_bug](https://user-images.githubusercontent.com/12797925/28913372-1337df82-7838-11e7-89ca-851b795cabc2.png)

**Comment by MartinSchoeler** [comment]
fixed by #7629
