### ISSUE TITLE
Do not scroll header when scrolling permissions is set

### ISSUE THREAD

**Issue by zahaim** [RocketChat/Rocket.Chat#7648]
### Description:

When scrolling Permissions down it's hard to know which columns goes for which role.
Is it possible to "freeze" header line of this table for easily identify matching role?

### Server Setup Information:

* Version of Rocket.Chat Server: any
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: any
* DB Replicaset Oplog: n/a
* Node Version: n/a

### Steps to Reproduce:

1. Enter Administration menu
2. Enter Permissions
3. Scroll down

### Expected behavior:

Seeing header line all the time

### Actual behavior:

Header line is not visible

**Comment by Sing-Li** [comment]
This is completed.
