### ISSUE TITLE
Rocketchat throws exception when Hubot listens to all rooms

### ISSUE THREAD

**Issue by tiredofit** [RocketChat/Rocket.Chat#7653]
### Description:

I have RC running under docker, and then also a hubot container as well set to listen to all rooms. When I attempt to request information from the bot (ie help) Rocketchat issues an exception.

### Server Setup Information:

* Version of Rocket.Chat Server: 58.rc.0 - Also occurs 57.2
* Operating System: Alpine Linux
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances:  1
* DB Replicaset Oplog: Mongo Oplog
* Node Version: 4.8

### Steps to Reproduce:

1. Set hubot to listen to all channels via docker-compose
2. Send a request to hubot

### Expected behavior:

A response from the bot

### Actual behavior:

Nothing in the room, but logs show exceptions.

### Relevant logs:
````bash
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:03 GMT+0000 (UTC)] INFO MongoDB connected
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO Message received with ID id
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO Message receive callback id NMM2PhMmwyq8gvmsn ts Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO [Incoming] daveconroy: sdbot
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO Checking to see if method: getRoomNameById exists
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO Looking up Room Name for: EEEzkMB6oKs6rqxF8
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO setting roomName: it-support
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:25 GMT+0000 (UTC)] INFO Message sent to hubot brain.
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO Message received with ID id
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO Message receive callback id 5ftG6nQ5iALxXMHpc ts Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO [Incoming] username: sdbot hello
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO setting roomName: it-support
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO Message sent to hubot brain.
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO Sending Message To Room: it-support
talk-xxx-org-hubot-app      | [Thu Aug 03 2017 15:40:29 GMT+0000 (UTC)] INFO Looking up Room ID for: it-support
talk-xxx-org-app            | Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined
talk-xxx-org-app            |   at [object Object].Meteor.methods.sendMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:14412:59)
talk-xxx-org-app            |   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1110:26)
talk-xxx-org-app            |   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
talk-xxx-org-app            |   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1858:12)
talk-xxx-org-app            |   at /app/bundle/programs/server/packages/ddp-server.js:904:20
talk-xxx-org-app            |   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
talk-xxx-org-app            |   at /app/bundle/programs/server/packages/ddp-server.js:903:47
talk-xxx-org-app            |   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
talk-xxx-org-app            |   at /app/bundle/programs/server/packages/ddp-server.js:902:46
talk-xxx-org-app            |   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:875:21)
talk-xxx-org-app            |   at /app/bundle/programs/server/packages/ddp-server.js:754:85
talk-xxx-org-app            | 
````

Relevant Env vars from my Docker-compose:

````bash
      - ROCKETCHAT_URL=talk-xxx-app:3000
      - ROCKETCHAT_ROOM=''
      - ROCKETCHAT_USER=sdbot
      - ROCKETCHAT_PASSWORD=xxx
      - BOT_NAME=sdbot
      - LISTEN_ON_ALL_PUBLIC=true
      - RESPOND_TO_DM=true
      - RESPOND_TO_EDITED=true
      - MONGODB_URL=mongodb://talk-xxx-org-db/hubot-brain
````

**Comment by geekgonecrazy** [comment]
This looks very much like an issue specifically with hubot and your script and when it tries to send a message to rocket.chat.


To help you with this we will need to see some of your code used

**Comment by tiredofit** [comment]
I can't even get it to give me a "bot help" output in any other rooms... I get the same exception..

**Comment by geekgonecrazy** [comment]
So no scripts have been added by you and you are using the latest hubot container?  Doing docker pull `rocketchat/hubot-rocketchat` does anything come down?

**Comment by tiredofit** [comment]
Latest images from Docker Hub - I was previously running my own Alpine Linux build and decided to make sure that wasn't the problem.
Tried a fresh install (via my own image) getting the same issue.
Tried a fresh install (via rocketchat/rocket.chat) getting the same issue..

Attempted to even just execute a `bot help` in #general and still throws the exception.
Only thing that I have configured is LDAP to support logins.

**Comment by tiredofit** [comment]
Just for reference I went back to 0.56 and still the same issue. My only hope is that you can see if there is an issue in my docker-compose that would be triggering this problem.

**Comment by wargamesqcf** [comment]
I am also encountering this issue with .57.2, it was fine in .56

**Comment by geekgonecrazy** [comment]
Can you do a docker pull on the hubot-rocketchat image and see if the latest improves things?

**Comment by wargamesqcf** [comment]
I did docker pull hubot-rocketchat, and it claims I am on the latest.

**Comment by geekgonecrazy** [comment]
One way to ensure is to do: `rocketchat/hubot-rocketchat:v1.0.11`

**Comment by wargamesqcf** [comment]
forced 1.0.11 and same issue

[34mI20170808-08:26:05.501(0) Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined   at [object Object].Meteor.methods.sendMessage (/app/bundle/programs/server/packages/rocketchat_lib.js:14077:59)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1028:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)   at /app/bundle/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)   at /app/bundle/programs/server/packages/ddp-server.js:755:85

**Comment by geekgonecrazy** [comment]
is this a private group or is this a public channel? 

Looks like the error happened here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/sendMessage.js#L40 which means it couldn't find the room for some reason.

Also is the bot user actually in the room?

**Comment by tiredofit** [comment]
Still the same issue as well on my end.
My rooms have a `-` in them e.g. `it-support`. Hubot shows that it's listening to all rooms, but doesn't appear in the room listing. In the rooms that have a `-` is where the exception gets thrown. Regardless, even in a room like `#general` hubot doesn't respond, even though in the logs it says it does..

**Comment by geekgonecrazy** [comment]
Can you try actually adding hubot to the rooms to see what difference that makes.

**Comment by geekgonecrazy** [comment]
Also please consider hopping in [#hubot](https://demo.rocket.chat/channel/hubot) where we can troubleshoot in more real time..

**Comment by tiredofit** [comment]
Joined - 

With the following settings the bot actually joins the channels. If I change `LISTEN_ON_ALL_PUBLIC` to `true` it will never join and which is where the problems start occuring. It would be tedious to add the comma seperated list of all channels (which change regularly) to ROCKETCHAT_ROOM. 

````bash
      - ROCKETCHAT_ROOM=it-support,heartbeats
      - LISTEN_ON_ALL_PUBLIC=false
      - RESPOND_TO_DM=true
      - RESPOND_TO_EDITED=true
````

**Comment by geekgonecrazy** [comment]
Alright to the bottom of this issue.  So if you talk to your bot via: `@botusername command` its gonna work just fine.  Because when you mention a user it brings the user into the channel before the message fully sends, which makes the necessary subscriptions needed be populated when hubot goes to respond.

But... if you talk to the bot via: `botname command` and the bot user is not actually a member of the channel.  It hears the message... but when it goes to send it can't because it is not a member of the channel.

So two solutions: 
1. Invite the bot to the channels so you can use `botname command`
2. Always mention by `@botname command` causing the bot to join and then be able to respond.

A note... on private groups you'd have to invite the bot to the channel for it to even see the message.  So don't forget that :)

An issue has been created here: https://github.com/RocketChat/hubot-rocketchat/issues/233 to track adding something to prevent this from being needed.
