### ISSUE TITLE
Connect to different database based on subdomain

### ISSUE THREAD

**Issue by ajshukury** [RocketChat/Rocket.Chat#7654]
We have hosted RocketChat on AWS and I have two questions and not sure if possible. Couldn't find anything on the docs.

- Separate database and application servers
- Connect to a specific database based on the subdomain in URL

Any thoughts?

Cheers

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
