### ISSUE TITLE
Username Not found in Direct Message

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#7655]
### Description:
- Username Not found in Direct Message

### Server Setup Information:

* Version of Rocket.Chat Server: 0.53.0
* Operating System: Windows
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v4.7.3

### Expected behavior:
> There is a user, I should have to able to DM them

### Actual behavior:
> Username not found

### Relevant logs:

```Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rN4DJxNMf2yArqaAN", : "USER.NAME", : "d", : null } at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15) at [object Object].<anonymous> (packages/meteor.js:213:24) at [object Object].MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:831:49) at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27) at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21) at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3882:31) at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:9565:32) at ModelsBaseDb.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:9640:16) at ModelSubscriptions.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:4193:36) at [object Object].Meteor.methods.createDirectMessage (/app/bundle/programs/server/app/app.js:5917:35) at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1093:26) at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1817:12) at /app/bundle/programs/server/packages/ddp-server.js:905:20 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at /app/bundle/programs/server/packages/ddp-server.js:904:41 at [object Object]._.extend.withValue (packages/meteor.js:1122:17) at /app/bundle/programs/server/packages/ddp-server.js:903:46 at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21) at /app/bundle/programs/server/packages/ddp-server.js:755:85 - - - - - at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11) at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22) at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1048:67 at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18 at nextTickCallbackWith0Args (node.js:436:9) at process._tickDomainCallback (node.js:406:13)```

**Comment by MartinSchoeler** [comment]
Hey @ramanamatya could you give us the steps to reproduce this bug? And did you had a user with the same username as your deleted in the past? Thinking this could be related to #5938

**Comment by ramanamatya** [comment]
@MartinSchoeler , No we didn't has any same username deleted in the past.

**Comment by NoahMarconi** [comment]
I'm using the web client and have this same issue. Has there been progress on replicating and correcting the bug?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Can please try to reproduce this on latest stable and check, whether it might be related to #6535? I think there are already several issues talking about `E11000 duplicate key error index` so a search for error might also bring up some other things to try for you. I'll happily reopen if you find this to be different (and if so, in what way) than all the other E11000 errors :)

Cheers
Thomas
