### ISSUE TITLE
Installing RocketChat Server on Suse Leap 42.3 - Steps, Suggestions, Hints, etc

### ISSUE THREAD

**Issue by jdashn** [RocketChat/Rocket.Chat#7657]
Hello,

I am going to be attempting to install RC Server onto openSuse Leap 42.3 I just wanted to see if there were any other folks out there who've done this, if there has been success, what steps were taken, any hints, things to watch out for? 

Thanks! 

Jdashn

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
