### ISSUE TITLE
Open external links in browser

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#7659]
The native mobile apps open links within a browser that can be closed easily but with Cordova you get locked into an embedded browser that can't be closed when opened by clicking a link in any chat - anyone working on fixing that?  I'd love to see a default or config setting to open links in new tabs/the default browser automatically.

**Comment by jszaszvari** [comment]
There's a PR that hopefully will come out with next release that fixes that. It's already approved.

**Comment by jszaszvari** [comment]
This is the one https://github.com/RocketChat/Rocket.Chat/issues/7368

**Comment by MartinSchoeler** [comment]
fixed by #7205
