### ISSUE TITLE
Userlist does not show up in Safari

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#7660]
### Description:

When clicking the userlist in Safari, it does not show.   It works fine when tested on Chrome.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.rc0
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Use Safari browser
2. Click the userlist

### Expected behavior:

See the userlist

### Actual behavior:

The userlist does not show

**Comment by MartinSchoeler** [comment]
Seems to be working with the current latest release, if you happen to experience this again, please reopen this. Thanks!
