### ISSUE TITLE
Programmatic API documentation

### ISSUE THREAD

**Issue by trusktr** [RocketChat/Rocket.Chat#767]
I only see network based APIs documented in the wiki.
##

**Comment by geekgonecrazy** [comment]
I think at this point its changing / expanding at a pretty rapid rate.  But this would be good to have.

**Comment by marceloschmidt** [comment]
This is related to #454 and #455. We need to make our methods callable by APIs.

**Comment by graywolf336** [comment]
https://rocket.chat/docs/developer-guides/rest-api
