### ISSUE TITLE
Livechat user ends chat doesn't offer to send transcript

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#7681]
### Description:

With option enabled to send chat transcripts enabled.  When a user ends the chat, it doesn't offer them to send an email.

But it does when the agent closes the conversation.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.0-rc.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances:  4
* DB Replicaset Oplog: true
* Node Version: same as our docker image

### Steps to Reproduce:

1. Enable Administration->Livechat->Ask visitor if they would like a transcript after chat closed
2. Start a conversation from website
3. Click end chat

### Expected behavior:

Should prompt them to send transcript

### Actual behavior:
Nothing happens just ends conversation

**Comment by CONFORM-IT** [comment]
Second this issue, same problem on 0.58.3. 
Always sending a transcript would be fine, too.

**Comment by tctovsli** [comment]
0.65.1 still has this issue. Built from source.
