### ISSUE TITLE
javascript focus method not working on messages-box textarea

### ISSUE THREAD

**Issue by jgtoriginal** [RocketChat/Rocket.Chat#7682]
### Description:

The `focus` method doesn't work on the messages-box textarea
If you open the developer tools and try to do `$('textarea').first().focus()` for focusing the user on the textarea on the main chat screen, it will not focus on the textarea at all.

This impacts on the functioning of textarea, because it turns out that if you want to programatically focus on it, it wouldn't be possible.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0 
* Operating System: Linux, Mac, Windows.
* Deployment Method(snap/docker/tar/etc): development
* Number of Running Instances: n/a
* DB Replicaset Oplog: n/a
* Node Version: 1.5

### Steps to Reproduce:

1. Go to demo.rocket.chat
2. open any channel or DM
3. double click anywhere outside the main textarea
4. open your browser's developer tools
5. go to the JS console and write `$('textarea').first().focus() ` in order to focus on the texarea programatically

### Expected behavior:

The browser would focus on the textarea, showing a blinking caret.

### Actual behavior:

The browser doesn't focus on the textarea.

### Relevant logs:
n/a

**Comment by bermanmaxim** [comment]
Actually under chrome at least, the console keeps focus even with a focus() instruction.

See this [stackoverflow question](https://stackoverflow.com/questions/14783585/jquery-focus-command-doesnt-work-from-chrome-command-line).

Did you have a problem also with a focus() instruction that was not fired in the console?

**Comment by MartinSchoeler** [comment]
@jgtoriginal if the problem still happens outside of the browser console, please reopen this. Thanks!
