### ISSUE TITLE
messages 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7683]
its nice to have a bubble message it will look more modern and more beautifull

**Comment by ShalokShalom** [comment]
+1

**Comment by aditya19496** [comment]
Can I start working on it?

**Comment by jszaszvari** [comment]
This would be suited to a customer theme, not core functionality. 

I feel most people would think it's tacky/a gimmick. 

Could all be done in the custom CSS section of the admin area I would think.

**Comment by aditya19496** [comment]
you wish to have an option to select theme, just like youtube?

**Comment by geekgonecrazy** [comment]
yes I would suggest doing this via administration->layout-> custom css

I don't think this belongs as a core feature.
