### ISSUE TITLE
Embed RocketChat as iFrame's tutorial 

### ISSUE THREAD

**Issue by kang298** [RocketChat/Rocket.Chat#7684]
I want to intergrate Rocketchat into my system with the same account so when registering an account, I use REST api to register 1 user in RocketChat also.

Now I want to show RocketChat as a part in my system in a iframe but skip log-in step. 
I have read this post 
https://rocket.chat/docs/developer-guides/iframe-integration/authentication
but almost does not understand :(.
This is how it look.
<img width="1280" alt="screen shot 2017-08-08 at 16 55 36" src="https://user-images.githubusercontent.com/5018309/29061680-d050ecba-7c59-11e7-922d-fb788074abf2.png">

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by Mindtoeye** [comment]
People have been asking this question over and over again and every single entry in your issue tracker has been closed with the same comment that they should look elsewhere. Maybe actually providing a decent example would make sure you don't constantly get these requests?

**Comment by richardblondet** [comment]
Stumbled upon this resource looking for this. Found an example in the (Rocket.chat iFrame auth docs)[https://docs.rocket.chat/guides/developer/iframe-integration/authentication]. Attaching here in case more people land here 
🖖
