### ISSUE TITLE
Message box not scrolling to follow additional multilines added on Mac OS X client 2.8.0

### ISSUE THREAD

**Issue by keeprock** [RocketChat/Rocket.Chat#7685]
### Description:

Multi line message becomes hidden as I type new lines into it. Like, someone turns off a scrolling, which was working perfectly before.

Window resizing doesn't solve it either.

Reloading and restarting entire system doesn't help. 

I can confirm at least one more use case with the same issues I'm having. So, it is not my system messed it up somehow.

![image](https://user-images.githubusercontent.com/5209820/29064047-740db3ee-7c30-11e7-88bd-ca7f6e19d1ba.png)

### Server Setup Information:

* Version of Rocket.Chat Server: Client version 2.8.0
* Operating System: Mac OS X 10.11 El Capitan
* Deployment Method(snap/docker/tar/etc): n/a
* Number of Running Instances:  n/a
* DB Replicaset Oplog: n/a
* Node Version: n/a

### Steps to Reproduce:

1. Load El Capitan. 
2. Make sure you've got Rocket Chat 2.8.0 installed
3. Right long message with a bunch of new lines in it

### Expected behavior:

You can see your message fully

### Actual behavior:

You can not see it and there no way to drag your window to uncover it.

**Comment by MartinSchoeler** [comment]
This issue was already fixed and it will be available on the next release #7629
