### ISSUE TITLE
Parse Slack-style URLs as links

### ISSUE THREAD

**Issue by TomaszDom** [RocketChat/Rocket.Chat#7686]
### Description:

Parse Slack-style URLs as links.

`<http://something.something/something/|Link name>`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Ubuntu Server 16.04.2
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: true
* Node Version: 4.5

### Steps to Reproduce:

1. Use SlackBridge to mirror content from Slack to Rocket Chat's rooms
2. Have Slack-style links pushed from SlackBridge like `<http://something.something/something/|Link name>`
3. See supposed links as normal text instead of links: `<http://something.something/something/|Link name>`

### Expected behavior:

Parse URL as link.

### Actual behavior:

URL doesn't get parsed as link

**Comment by jszaszvari** [comment]
This works when using a incoming integration but not in the chat clients

**Comment by MartinSchoeler** [comment]
Maybe convert it to markdown on during the import?

**Comment by TomaszDom** [comment]
How can I convert it to markdown during import?

**Comment by TomaszDom** [comment]
This turns out to be unrelated to SlackBridge, normal incoming webhooks configured in RocketChat, incoming from Microsoft Team Foundation Server 2017 Update 2 using its Slack integration are also affected.

**Comment by TomaszDom** [comment]
Any progress on this?

**Comment by Sing-Li** [comment]
Web client already parse it as markdown.  But mobile is likely not supporting it yet.  Passing the case to mobile team for further investigation.

**Comment by diegolmello** [comment]
@Sing-Li Mobile do support it. Can we close this issue?

**Comment by Sing-Li** [comment]
Sure. Thanks!
