### ISSUE TITLE
Demo Server Times Out

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#769]
You guys are probably aware of this already, but in case you're not the demo server is currently unavailable and times out.

![2015-09-11_16-51-35](https://cloud.githubusercontent.com/assets/850391/9827176/5f35cc5a-58a5-11e5-9f33-9655634e5f46.png)

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9827368/edbab460-58b7-11e5-8f65-4b9435c8a730.png)

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9827396/1fbdeaf4-58b8-11e5-942d-1e0b026d90f2.png)

it is stuck like that for over 1 hour...

**Comment by graywolf336** [comment]
Yikes :cry:

**Comment by engelgabriel** [comment]
Time to move to CoreOS with Dockers...

**Comment by geekgonecrazy** [comment]
Feels like a small piece if me is missing ;-)

Digitalocean is usually pretty good about getting these things resolved.  :)

**Comment by geekgonecrazy** [comment]
> Time to move to CoreOS with Dockers...
:+1: that sounds like fun!

**Comment by Sing-Li** [comment]
What happened?  Where am I?   What am I going to do ?!##_@(@(# ~~~~!!

..... What is the meaning of life ???!!!!!     Oh ... everything if flashing forward.   Oh NO!

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9827438/7b9a79d2-58b8-11e5-9eef-813017a4388c.png)

Something happened just before it went down...

**Comment by geekgonecrazy** [comment]
Ah ha!  I thought deploys were taking longer then usual!  I thought it was just the meteor build process.  But nope it was getting starved for cpu cycles

**Comment by engelgabriel** [comment]
Everything happens for a reason.. (or we can just create a reason)...

Its about time to move to High Availability mode

https://cloud.google.com/container-engine/

**Comment by engelgabriel** [comment]
To apply, contact your Accelerator, Incubator, or VC about Google Cloud Platform for Startups.

:(

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9827854/1e57a29a-58bd-11e5-89b8-ed6d947519d4.png)

We shall see...

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9828379/d13555ec-58c2-11e5-9e49-1637bd8e2012.png)

**Comment by graywolf336** [comment]
Hopefully you get a refund or something for the time it has been down.

**Comment by geekgonecrazy** [comment]
Also in a situation like this you'd think they'd transfer your vps out to another host to get you back up as soon as possible...

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9828477/589a2336-58c4-11e5-8e98-a64d4498bf53.png)

Getting there I think...

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9828892/026e70dc-58cb-11e5-9d1c-20f959e95848.png)

fingers crossed

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9829050/2f7d4654-58ce-11e5-81b5-204b75d5bf52.png)
