### ISSUE TITLE
Anonymous still see deleted room general

### ISSUE THREAD

**Issue by Cikcak** [RocketChat/Rocket.Chat#7692]
I enabled anonymous, deleted general room, set another room to default, but when I open my rocket.chat and automaticaly I'm anonymous (untill I log in), I still see room general, which cannot be opened.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.3
* Operating System: Debian stretch/sid
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

### Steps to Reproduce:

1.  Enable Anonymous
2.  Open Rocket.chat

### Expected behavior:

I expect room general is not shown.

**Comment by Hudell** [comment]
Duplicate of #3870
