### ISSUE TITLE
Feature Request: Token Controlled Access Chat Channels

### ISSUE THREAD

**Issue by AdamBLevine** [RocketChat/Rocket.Chat#7693]
Distributed blockchain technology offers a game-changing shift in how we can think of, and interact with ownership on the internet.  We'd like to add the optional ability for access to specific chat channels be gated by what blockchain-tokens a user possesses. 

The Tokenpass API is an OAUTH2 provider which offers users the ability to use "offchain" tokens without maintaining a wallet, and also to cryptographically prove that they own a particular blockchain identity. User accounts can access chats when logging in with their associated tokenpass id based on whatever tokens they have relative to the rules of that particular service.

Here are some screens from tokenpass to give you a little more context.

![image](https://user-images.githubusercontent.com/6858319/29095862-5050879e-7c47-11e7-9628-d2bb961669c3.png)

![image](https://user-images.githubusercontent.com/6858319/29095882-60962686-7c47-11e7-92d7-a73d9cf84611.png)

![image](https://user-images.githubusercontent.com/6858319/29095946-8ecdcb62-7c47-11e7-841b-809ad4df2de3.png)

![image](https://user-images.githubusercontent.com/6858319/29095966-a1beacdc-7c47-11e7-9b22-460562e9fb75.png)

![image](https://user-images.githubusercontent.com/6858319/29095995-d24a37d6-7c47-11e7-91c6-ac8684f12ec9.png)

Things like cryptographic verification could be done entirely via the API and built into rocket chat as new /commands or users.

**We're interested in sponsoring the addition of**
**a) Login with Tokenpass integration** 

**b) allow user token balances to be read dynamically when a user is accessing a room.** 

**c) allow admins to set conditional visibility and access to designated chat channels based on the token balances of each user**

Tokenpass home: https://tokenpass.tokenly.com/
Full API documentation http://apidocs.tokenly.com/tokenpass/#api-access

Thank you, and great project!

**Comment by Mjons** [comment]
Such a good idea...
