### ISSUE TITLE
Add setting to allow audio notifications for All Messages

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7696]
Just like we have for Desktop, Email, & Push - allow the user to select the trigger for audio notifications. Currently, it only triggers for Mentions. Allow the user to choose "Mentions" or "All Messages". Not sure we need the third option of "Nothing" as that's already available under "Audio"->"None".

This setting should be shown in the "Notifications" flex tab in every Room/DM as the other options are shown.

**Comment by aditya19496** [comment]
Can I start working on it?

**Comment by aditya19496** [comment]
Its almost complete.

**Comment by aditya19496** [comment]
Its complete.
