### ISSUE TITLE
general room doesnt load

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7701]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.3
* Operating System:ubuntu
* Deployment Method(snap/docker/tar/etc): no
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version:4.8.0

rocket.chat rooms doesnt load its load blank

**Comment by hardlydavis** [comment]
Same here, and after quitting a direct user->user message I was unable to re-load it. Let me know if I can offer any testing or sanitised logs

**Comment by pettitto** [comment]
Got the same issue here too, but on Debian Stretch, same version of Rocket Chat (0.57.3).

I managed to resolve the issue by clearing my local db cache within the browser.

In Chrome: Inspect Element > Application tab > Clear site data (at the bottom of the page). I'm wondering if there's an issue with corrupt caching or given that the room has a large number of messages in it, that it's trying to cache too much data, more than a browser/client can handle?

**Comment by hardlydavis** [comment]
My scenario was on a fresh install so very little chat history had been generated. I also found that clearing cache/cookies or incognito resolved, but didn't take long to recur..

**Comment by MartinSchoeler** [comment]
@fifou17 @pettitto @hardlydavis I think it could be related to the bug fixed in this pr #7687 , could you guys test out with the latest develop version? Thanks!

**Comment by fifou17** [comment]
@MartinSchoeler i will test the latest dev version

**Comment by erikyuzwa** [comment]
Is `localforage` a typo or on purpose? Just triggers my OCD is all. :)

I haven't been able to access #General for about a week or so, and deleting the browser database was the fix. Thanks!

**Comment by hardlydavis** [comment]
Happy to try, but I'm a bit new to snap (but followed that path when installing).

Does dev  version translate into the snap verbiage below at all?

       --edge Install from the edge channel
       --beta Install from the beta channel
       --candidate
              Install from the candidate channel
       --stable
              Install from the stable channel

**Comment by fifou17** [comment]
@MartinSchoeler its works fine in other builds so you can close this thread i have tested the rc release its worked fine thanks

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
