### ISSUE TITLE
rocket.chat avatar file system 

### ISSUE THREAD

**Issue by Fazil93** [RocketChat/Rocket.Chat#7704]
* Version of Rocket.Chat Server: 0.57.3
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 4.8.0

rocket .chat avatars doesnt load after uploading em and there is no option to change avatars to file system

**Comment by trungducnet** [comment]
me too :(

**Comment by salamachinas** [comment]
Same here.
 After update 0.56 -> 0.57.3 change file system settings
```
[34mI20170809-15:02:51.082(0) Setting default file store to GridFS 
[34mI20170809-15:02:53.543(0) (rocketchat_migrations.js:147) Migrations: Not migrating, already at version 99
```
After setting it back to File system - avatars coems back

**Comment by MartinSchoeler** [comment]
@fifou17 could you explain a little better ? Cant you see the file system under administration -> File Upload -> Storage Type setting?

**Comment by fifou17** [comment]
no @MartinSchoeler  yes i see it and it set to file system but all the avatars goes to the database and its get not stored in the file system like the avatars was stored in the file when i upgraded all avatars got wiped from the file and got moved to the database

**Comment by fifou17** [comment]
@MartinSchoeler 
![capture d ecran 158](https://user-images.githubusercontent.com/16228448/29171067-14aba402-7dd3-11e7-85d2-094d3ade10ef.png)

**Comment by geekgonecrazy** [comment]
This is fixed.  Setting file store works across uploads and avatars
