### ISSUE TITLE
Blank channel when coming directly from url

### ISSUE THREAD

**Issue by nyddogghr** [RocketChat/Rocket.Chat#7705]
### Description:

Channel is blank when coming directly from an URL like https://demo.rocket.chat/channel/support.
This doesn't happen on the demo rocketchat, only our own internal one
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Unknown
* Deployment Method(snap/docker/tar/etc): Unknown
* Number of Running Instances: Unknown
* DB Replicaset Oplog: Unknown
* Node Version: Unknown
* Browser version: chromium 60

### Steps to Reproduce:

1. Go to a rocketchat channel by loading directly the page (like https://demo.rocket.chat/channel/support)
2. Channel is blank
3. Go to another channel/user, no issue
4. Go back to first channel, still blank

### Expected behavior:

Channel loads correctly

### Actual behavior:

Channel stays blank, until I load another channel from the URL and go back to the first one.

### Relevant logs:
Logs when coming from the url:
```
Exception in template helper: TypeError: Cannot read property 'split' of undefined
    at a [as parseNotEscaped] (https://chat.ott.arkena.com/9eedba55dddecd21a5b4e6e2af81726a28e1a13d.js?meteor_js_resource=true:400:1223)
```
```
TypeError: Cannot read property 'split' of undefined
    at a [as parseNotEscaped] (https://chat.ott.arkena.com/9eedba5….js?meteor_js_resource=true:400:1223)
```
```
TypeError: Cannot set property 'scrollTop' of null
    at https://chat.ott.arkena.com/9eedba5….js?meteor_js_resource=true:246:28579
```
```
TypeError: Cannot read property '0' of null
    at https://chat.ott.arkena.com/9eedba5….js?meteor_js_resource=true:139:29744
```
Logs when coming from another channel:
```
Exception in defer callback: TypeError: Cannot set property 'scrollTop' of null
    at https://chat.ott.arkena.com/9eedba5….js?meteor_js_resource=true:246:28579
```

**Comment by MartinSchoeler** [comment]
Probably fixed by #7687
