### ISSUE TITLE
Extra new line inserted in markdown code block

### ISSUE THREAD

**Issue by morremeyer** [RocketChat/Rocket.Chat#7707]
### Description:

Until recent versions (I don't remember which one, sorry), code markup could be done as follows:

\`\`\`
Text
\`\`\`

which displayed as 

```
Text
```

This behviour changed, as 

\`\`\`
Text
\`\`\`

now displays as

```

Text
```

and you need

\`\`\`Text
\`\`\`

for 

```
Text
```

This is really annoying as all other markdown implementations (at least known to me), e.g. GitHubs own ignore that newline after the \`\`\`. 

Maybe this need discussion, I'm not sure of that.

### Server Setup Information:

* Version of Rocket.Chat Server: `0.57.2`
* Operating System: Mac OS Sierra 10.12.6
* Deployment Method(snap/docker/tar/etc): unknown
* Number of Running Instances: 1
* DB Replicaset Oplog: unknown
* Local Version: `2.8.0`

### Steps to Reproduce:

1. Paste one of the above examples in your Rocket.Chat
2. See the described behaviour

### Expected behavior:

No change in behaviour the following should work as it did earlier:

\`\`\`
Text
\`\`\`

which displayed as 

```
Text
```

### Actual behavior:
It works as follows:

\`\`\`Text
\`\`\`

for 

```
Text
```

**Comment by fnkr** [comment]
CommonMark also say's it should be rendered like

```
this
```

http://spec.commonmark.org/0.28/#fenced-code-blocks

**Comment by xenithorb** [comment]
I think this should be re-categorized as a proper bug, and re-titled "Markdown code fencing produces extra newline"

**Comment by xenithorb** [comment]
Inner HTML for the pre's:

` ``` ` on same line: 

```html
<code class="code-colors hljs subunit"><span class="copyonly">```<br></span><span class="hljs-keyword">test
</span><span class="copyonly"><br>```</span></code>
```
With extra space:

```html
<code class="code-colors hljs subunit"><span class="copyonly">```<br></span>
<span class="hljs-keyword">test
</span><span class="copyonly"><br>```</span></code>
```

So I'm guessing we either need to stop sending extra `<br>`s or we need to strip leading newlines from the input. Remember these are encased in `<pre>` tags, so the line breaks are going to render.

**Comment by mauricemeyer** [comment]
@xenithorb I fully agree with that. I prefer the "stop sending extra `<br>` solution" as it looks cleaner to me.

**Comment by xenithorb** [comment]
1. It only happens with the `original` markdown parser 
2. Because of that, I believe the bug is on this line: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-markdown/parser/original/code.js#L61
  I would fix it but I'm not good with JS, and I'm not certain what the team's goal here would be in a "proper fix"

**Comment by graywolf336** [comment]
There was a pull request to fix this, but I can't find it now for some reason...

**Comment by xenithorb** [comment]
@graywolf336 https://github.com/RocketChat/Rocket.Chat/pull/8510 Found it 

Perhaps triage https://github.com/RocketChat/Rocket.Chat/pull/9754 to go along with this fix too?
