### ISSUE TITLE
Change scroll bar in flex-panel

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#771]
@Morgul suggested this fix in chat.  Figured i'd make an issue so we can keep up with the issue / potential fix.

http://noraesae.github.io/perfect-scrollbar/

**Comment by marceloschmidt** [comment]
:+1:

**Comment by engelgabriel** [comment]
I dont like overwriting the native scrollbars... It always have a bad performance when the machine is busy. We will change the right flex-panel so the icons are in the top.

See https://chat.creators.co/ for reference.
