### ISSUE TITLE
hubot intern doesnt load the folder scripts 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7713]
* Version of Rocket.Chat Server: 0.57.3
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc):none
* Number of Running Instances:  1 
* DB Replicaset Oplog: enabled 
* Node Version: 4.8.0

hubot intern doesnt load the scripts from the folder

**Comment by timkinnane** [comment]
Please see the [last comment on this related issue](https://github.com/RocketChat/Rocket.Chat/issues/8025#issuecomment-381470969).
