### ISSUE TITLE
Creating new room with deleted room name

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#7717]
Room created with a roomName, deleted again and created with same name, it was creating a problem for me. Newly created room wasn't supposed to contain any messages, but still I can see them. I was unable to add members to the new room.

**Comment by localguru** [comment]
Which version?

**Comment by sacOO7** [comment]
Current version of demo app

**Comment by ruberVulpes** [comment]
try refreshing the browser once creating the channel

**Comment by jblobel** [comment]
> try refreshing the browser once creating the channel

This is not an answer...

**Comment by ruberVulpes** [comment]
> try refreshing the browser once creating the channel
>>This is not an answer...

When you refresh the page it allows you to add members into the recreated room.

**Comment by jblobel** [comment]
Okay it may be a turnaround, but for 99% of users, for normal users, this is way too complicated. So this is still an issue.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @sacOO7,

I cannot reproduce this in 0.61.0.

If this is still present, please get back to me and provide further information (see https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md).

Cheers
Thomas
