### ISSUE TITLE
Rocket.Chat support channel notifications

### ISSUE THREAD

**Issue by amateo** [RocketChat/Rocket.Chat#7719]
Since last Tuesday (8/9) I'm receiving a lot f emails notifying me that I've been mentioned in the support channel of the demo chat, but I haven't. 
Because there are a lot, I configured my account to not receiving email notifications, but I continue receiving them.

**Comment by MartinSchoeler** [comment]
Have you tried to change the notification setting on the room? 
<img width="433" alt="screen shot 2017-08-11 at 2 21 44 pm" src="https://user-images.githubusercontent.com/20868078/29224373-6e5d9a28-7ea0-11e7-92f4-1b0585656666.png">

**Comment by amateo** [comment]
Running Linux client, I can't use right icons, its window is not open.
I have disabled push notifications on my account, but I'm still receiving them.
It's happening since Tuesday.

**Comment by MartinSchoeler** [comment]
Those settings are the default ones if you change the notifications on a channel they will be overwritten. Can't you access our demo server on the browser? https://demo.rocket.chat/ . Thanks!

**Comment by amateo** [comment]
I couldn't set the setting (using a mobile interface).
I unsubscribed to the channel and resubscribed to it again and now I'm not receiving notifications.
