### ISSUE TITLE
Upgrade node.js to 4.8.4 or above

### ISSUE THREAD

**Issue by HumphRey123** [RocketChat/Rocket.Chat#7724]
### Description:
Hi,

node.js below 4.8.4 has security problems. Look here: https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/ . Is RC latest compatible with node.js 4.8.4. Your support asked me to open an issue here.

regards
Humph

**Comment by localguru** [comment]
+1

**Comment by miltonfuller** [comment]
+1

**Comment by localguru** [comment]
Anything new on this? Is node.js 4.5.0 a "must" or can we upgrade to >= 4.8.4 ?  :smile_cat:

**Comment by localguru** [comment]
The docs still say node.js 4.5.0, see https://rocket.chat/docs/installation/manual-installation/ubuntu . Is this official or just old docs?

**Comment by dmoldovan123** [comment]
+1

**Comment by Lemmmy** [comment]
My server is running on 4.8.4 just fine.

**Comment by localguru** [comment]
See, 

https://github.com/RocketChat/hubot-rocketchat/issues/239
https://github.com/RocketChat/Rocket.Chat.Docs/issues/373

It's unclear which version should be used, but everything < 4.8.4 is a security risk. So, is RC nodejs 4.8.4 compatible?

**Comment by Lemmmy** [comment]
Again, as I said, it works on 4.8.4.

**Comment by vcapretz** [comment]
Done on https://github.com/RocketChat/Rocket.Chat.Docs/pull/376 @HumphRey123, I think we can close this one
