### ISSUE TITLE
Tradução customizada não funciona

### ISSUE THREAD

**Issue by nicolasdezena** [RocketChat/Rocket.Chat#7726]
### Server Setup Information:

* Version of Rocket.Chat Server: v0.57.3

Estou tentando traduzir algumas palavras porém não está funcionando, segue meu JSON:

`{
 "en": {
  "Channels": "Rooms"
 },
 "pt": {
  	"Read_Only_Channel": "Apenas leitura",
        "Read Only Channel": "Apenas leitura",
 },
 "pt-BR": {
  	"Read_Only_Channel": "Apenas leitura"
         "Read Only Channel": "Apenas leitura",
 }
}`

Alguém saberia me ajudar?

**Comment by geekgonecrazy** [comment]
Please update and try again.  A lot has changed.  Closing
