### ISSUE TITLE
Android app gets stuck on the Delete Message/Report Abuse/Cancel screen

### ISSUE THREAD

**Issue by rm234179** [RocketChat/Rocket.Chat#773]
this happens if you touch a message for too long, but you cannot get out of this without closing down the app. (see the attached screenshot)

![rocketchat_android](https://cloud.githubusercontent.com/assets/6712253/9832300/99b75874-5933-11e5-925d-10a6412898d4.png)

**Comment by geekgonecrazy** [comment]
:+1: I get this every once in a while too.  Pretty annoying.  :)
