### ISSUE TITLE
Admin & MyAccount FlexNavs should not revert to  listCombinedFlex (ie Rooms NavFlex) when exited

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#7732]
Account Box has facility to register additional menu fields. (accountBox.html line21)
These may well be used to implement several related menus. So when exiting MyAccount or any other flexNav, your should be returned to this AccountBox menu, not the Rooms NavFlex which it currently does.

cheers

**Comment by engelgabriel** [comment]
@karlprieb in the new design, this is a dropdown menu, so I am not sure this is still a valid request?

**Comment by neurobe** [comment]
Fixed by new UI. Tks
