### ISSUE TITLE
When tried login with jQuery Ajax request, error occured 500 Internal Server Error [Enable CORS = true]

### ISSUE THREAD

**Issue by distlibs** [RocketChat/Rocket.Chat#7735]
I tried send request using jQuery Ajax and login in Rocket Chat server:
```
 $.ajax({
       'type': 'POST',
       'url': 'http://192.168.30.46:3000/api/v1/login',
       'data': JSON.stringify({
             'username': 'admin',
             'password': 'admin'
        }),
       'contentType': 'application/json',
       'dataType': 'json',
       'processData': false,

       'success': function (response) {
          console.log(response);
        }
});
```
When send similar request with PHP works fine.
Cors enabled:
![cors](https://user-images.githubusercontent.com/30928251/29260591-75a51682-80d3-11e7-866f-74fd1e6943f8.png)
Error displayed in browser console:
`Response for preflight has invalid HTTP status code 500`

![error](https://user-images.githubusercontent.com/30928251/29260629-a39eb098-80d3-11e7-8489-4bec78038d3d.png)
Response from server:
```
TypeError: Cannot read property 'authRequired' of undefined
  at Route.share.Route.Route._authAccepted (/home/adminas/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/nimble_restivus.js:403:17)
  at Route.share.Route.Route._callEndpoint (/home/adminas/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/nimble_restivus.js:357:17)
  at /home/adminas/dev/Rocket.Chat/.meteor/local/build/programs/server/packages/nimble_restivus.js:250:33
  at packages/simple_json-routes.js:98:9
```

![response](https://user-images.githubusercontent.com/30928251/29260705-26e37c90-80d4-11e7-864b-27b9a0f4802c.png)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by huynhquocmy** [comment]
Hi @distlibs, Did you solve your problem ? I got the same here.

**Comment by distlibs** [comment]
Hi @huynhquocmy. Didn't solved.

**Comment by huynhquocmy** [comment]
wow @distlibs, it has been 2 months already. So how's your RocketChat life now ? 👯‍♂️

**Comment by huynhquocmy** [comment]
@distlibs I workaround by changed RocketChat.API.v1 = new API({
	version: 'v1',
	useDefaultAuth: true,
	prettyJson: true,
	enableCors: true,
	auth: getUserAuth()
});

RocketChat.API.default = new API({
	useDefaultAuth: true,
	prettyJson: true,
	enableCors: true,
	auth: getUserAuth()
});

manually set enableCors: true from the file

packages\rocketchat-api\server\api.js

and it works perfectly. Hope it works for you.

**Comment by distlibs** [comment]
@huynhquocmy thanks.

**Comment by PalakjainJain** [comment]
Hey @huynhquocmy i am also facing same problem and i used docker to install rocket chat.can you tell me where do i need to make this changes.

**Comment by huynhquocmy** [comment]
@PalakjainJain Please see my above comment, it should works.

**Comment by Coveragepyantony825** [comment]
https://jquerys.space/questions/click-the-login-button-using-jquery-to-gain-access



I pieced it together
