### ISSUE TITLE
Get error when use logout API

### ISSUE THREAD

**Issue by tuananhhedspibk** [RocketChat/Rocket.Chat#7736]
I use `axios.get(`) to logout with rocket chat logout API - in React APP
Here is my code:

```
axios.get(constant.API_BASE_URL + constant.API_SIGN_OUT, constant.headers)
      .then(response => {
      })
      .catch(error => {
        alert(error);
      })
```

```
header = {
    headers: {
      'X-Auth-Token': JSON.parse(localStorage.rocket_chat_user).auth_token,
      'X-User-Id': JSON.parse(localStorage.rocket_chat_user).user_id
    }
  }
```

I had check auth-token and user-id, every things is ok but i got "500 error" with logout API
Can anyone help me? Thanks you a lots guy

**Comment by localguru** [comment]
What happens if you try just curl:

```
curl -H "X-Auth-Token: ${AUTHTOKEN}" \
     -H "X-User-Id: ${USERID}" ${SERVER}/api/v1/logout
```

**Comment by tuananhhedspibk** [comment]
It's OK with terminal but when i use GET method with headers, normally it will send OPTION method before but when OPTION method was sent, i get ''500 error''

**Comment by graywolf336** [comment]
You need to post to it. https://github.com/kahmali/meteor-restivus#logging-out
