### ISSUE TITLE
wanted: Rocketchat._dummy package.  Add-on developers start here!

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#7740]
A package which is a start point for developers wanting to expand RC.
Rocket._dummy would:
. register two entries in Admin NavFlex: Dummy 1 and Dummy 2
. selecting Dummy 1/2 would bring up DummyFlex1/2, each having links to PageDummy1A/1B, 2A/2B
. selecting PageDummy1A etc would invoke Template_PageDummy1A

. register same for FlexTabs
. register Settings_Dummy1/2: setting1, setting 2 (they may change the color of the respective pages maybe
. register new RocketChat.Authorisation for Dummy1/2
.others?
(you get the picture)
cheers

**Comment by graywolf336** [comment]
Related to #6890 since you're just wanting to extend Rocket.Chat and there is work in progress to do this without forking the code.

**Comment by neurobe** [comment]
Covered by #6890.
