### ISSUE TITLE
incorrect markdown format with bold in named link 

### ISSUE THREAD

**Issue by pandada8** [RocketChat/Rocket.Chat#7741]
### Description:

markdown content are incorrectly formated

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.0-rc.1
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: true
* Node Version: 4.8.4

### Steps to Reproduce:

![image](https://user-images.githubusercontent.com/3305174/29301320-ddd4a58a-81ad-11e7-9423-5f3b97ecf432.png)

first one is `inno opened <https://link|!41 Plugin log 2> in <https://link|link>: *Plugin log 2*`
second one is `inno opened <https://link|!41 *Plugin log 2*> in <https://link|link>: *Plugin log 2*`

screenshot from official demo

**Comment by rgembalik** [comment]
Same here on the newest version. Both link formats will result in icorrect messages:
* `[ *The Google* ](https://google.com)` wil render `<span class="copyonly">*</span><strong>The Google</strong><span class="copyonly">*</span>` (all being the link)
* `<https://google.com|*TheGoogle*>` will render `<span class="copyonly"*TheGoogle>`, where link ends before asterisk
The correct behavior would be to see boldened `The Google` link

Why is that important? Many integrations that work with slack would use such notation. E.g. Gitlab. The message that op provided is taken from Gitlab integration (or at least we have the same messages on Gitlab).

**Comment by rgembalik** [comment]
The issue still exists in server version 2.3.1.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
