### ISSUE TITLE
[Feature] User avatars from external source

### ISSUE THREAD

**Issue by mjovanovic0** [RocketChat/Rocket.Chat#7743]
We have internal service for employee images and in that service we have API for fetching user image.

We would like to be able to set user avatar as URL to that service so that avatar is not downloaded into Rocket.Chat configured storage.

Example:
For user `test` service URL would be `https://acme.com/api/v1/test` and service call returns PNG/JPEG image (depending on what type of image user uploads).

Rocket.Chat for user avatar provides `/avatar/{username}` which loads user avatar from configured storage.
Provide a way to either change `/avatar/{username}` to `https://acme.com/api/v1/{username}` or maybe easier approach would be performing HTTP.302 - Redirect to `https://acme.com/api/v1/{username}` from `/avatar/{username}` when accessed.

**Comment by localguru** [comment]
Good idea. On thing to keep in mind with external content: If the remote service doesn't offer https you will get SSL warnings in your browser's status bar, same as with non ssl link previews, see #7490

**Comment by mjovanovic0** [comment]
@RocketChat/core

**Comment by mjovanovic0** [comment]
@RocketChat/core

**Comment by mjovanovic0** [comment]
@RocketChat

**Comment by phlbrz** [comment]
Hello all,
I know it is an old feature not approved yet, but I think it's a great idea. Thank's to @mjovanovic0 .

Like sync.js store avatar, it could be the same to avoid performance issues when loading the image. e.g.: https://github.com/RocketChat/Rocket.Chat/blob/9f883b897655971cf0533f29190516a2c24d352d/packages/rocketchat-ldap/server/sync.js#L207

Could I use an url that is not an API and using template var as username? e.g: http(s)://acme.com/${username}.jpg ? 
@RocketChat @RocketChat/core

**Comment by mjovanovic0** [comment]
@phlbrz As long as the URL returns image binary as payload and correct `Content-Type` header I don't see a reason why you should not use `http(s)://acme.com/${username}.jpg`.

Also regarding storing avatar locally, I would like for that to be an option that admin can choose, as for our use case this is not applicable because users can change their image at any time in image service and we want that image to propagate to every external service that use image (Rocket.Chat, GitLab, other internal apps).

Currently we achieve this by implementing custom logic on image service to call Rocket.Chat REST API `/api/v1/users.setAvatar` but we would like to remove this custom develop solution.
