### ISSUE TITLE
 CORS broken: OPTIONS requests returns 500 Internal Server Error

### ISSUE THREAD

**Issue by tuananhhedspibk** [RocketChat/Rocket.Chat#7747]
```javascript
axios.get(constant.API_BASE_URL + constant.API_SIGN_OUT, constant.headers)
      .then(response => {
        localStorage.removeItem('rocket_chat_user');
        window.location = constant.BASE_URL;
      })
      .catch(error => {
        alert(error);
      })
```

In this code, I sent `GET` request with a header, But the call that is failing really is `OPTIONS ` that the browser sends before this request. This request is not even being sent and I got "500 Internal Server Error"

**Comment by huynhquocmy** [comment]
@tuananhhedspibk Any update for this error ? I got the same thing and spend a lot of time for it already.

**Comment by MarcosSpessatto** [comment]
Hey @tuananhhedspibk do you still have this error? Because I think that is fixed already [in this PR](https://github.com/RocketChat/Rocket.Chat/pull/11953).

**Comment by MarcosSpessatto** [comment]
@huynhquocmy any news?
