### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by ankit213** [RocketChat/Rocket.Chat#7753]
### Description:

I have used send message method as below, Here I am added condition "**this. sock. readyState!== WebSocket. OPEN**". For check websocket connected or not. If I didn't use this condition it will throw the error in send message method "WebSocket is already in CLOSING or CLOSED state."

```
MeteorDdp.prototype.send = function(msg) {
    if (this.sock.readyState !== WebSocket.OPEN) {
          return true;
        };
    } else {
        console.log(this.sock.readyState);
        this.sock.send(JSON.stringify(msg));
    }
};
```
### Steps to Reproduce:
 
**Step 1:** I send message "Hi" using "Send message" method. At that time readyState was become 1. Means websocket is connected so it will work fine. 
**Step 2:** Now after 10-15 seconds, I try to send another message, say "Hello", at that time readyState become 3 instead of 1.

### Expected behaviour:
Websocket will not close automatically and send message will work fine after some time.

Thank You.

**Comment by geekgonecrazy** [comment]
Please feel free to open topic on our forum if this is still an issue. 

Closing
