### ISSUE TITLE
"Hide right side bar with click" setting breaks the flex tab

### ISSUE THREAD

**Issue by jszaszvari** [RocketChat/Rocket.Chat#7756]
### Description:

After updating to 0.58.0 I am no longer to open the right sidebar in any browser, Clicking the icons do nothing.  Am getting no errors in the browser console either.

![image](https://user-images.githubusercontent.com/872463/29375446-5b591d7e-82f8-11e7-81fa-8e3a7df11750.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.0
* Operating System: OS X and Widnows
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances:  5
* DB Replicaset Oplog: Yes

### Steps to Reproduce:

1. Click on anything in the sidebar

### Expected behavior:

Sidebar should open.

### Actual behavior:

Sidebar does not open. 

### Relevant logs:
Nothing coming up in console log in browser or server logs that would indicate a issue.

**Comment by jszaszvari** [comment]
Not working either in the Electron client.

**Comment by jszaszvari** [comment]
Tested on iOS and Android browser just now - Same issue

**Comment by jszaszvari** [comment]
I can confirm that rolling back to 0.57.3 has made the sidebar start working again. Just did it now.

**Comment by Gummikavalier** [comment]
This happens on desktop browsers (Chrome, Firefox at least) too when personal profile option
**Hide right side bar with click**
is enabled (with RC 0.58.0).

**Comment by jszaszvari** [comment]
@Gummikavalier  Good Find! 

That indeed does make it start working again, Only issue is the rest of the users now. Might need to find a way to turn that off for everyone.

**Comment by Gummikavalier** [comment]
@jszaszvari I think it is off by default.

I had enabled it by myself in personal profile, so there might be an option in the Admin-settings if it's on in your setup by default.

**Comment by geekgonecrazy** [comment]
@rodrigok 

@diegodorgam I know you saw this.  Do you have the: 
> Hide right side bar with click
Option in your preferences?

**Comment by Gummikavalier** [comment]
Works now in 0.58.1. Tested Chrome, Firefox and app. Thanks! 👍
