### ISSUE TITLE
Is there a place where is the list with all emoji and all theyr code ?

### ISSUE THREAD

**Issue by PowaBanga** [RocketChat/Rocket.Chat#7757]
Hi all,
I look for a place where are listed all emoji and theyr codes, because I am trying to create a them for pidgin client....

Cheers

**Comment by simonv3** [comment]
@PowaBanga do you mean all standard Unicode emojis?

The standard: 
http://www.unicode.org/reports/tr51/

And I think this is probably a good place to start:
http://unicode.org/Public/emoji/5.0/emoji-data.txt

**Comment by PowaBanga** [comment]
me, what i look for is a list of your special code like `:smile:` but thanks for your links, they will be usefull for me

**Comment by simonv3** [comment]
Maybe this will help? https://github.com/RocketChat/Rocket.Chat/blob/a729aaa2baffea9338e1b0443cbac1780813bdd6/packages/rocketchat-emoji-emojione/emojiPicker.js

**Comment by PowaBanga** [comment]
yes, thank you ! i think that i have to do the rest of the work myself now :)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by PowaBanga** [comment]
Ok sorry, i asked that because it is not in the guidelines, or I did not find.

But simonv3 help good, thanks
