### ISSUE TITLE
Hide "More private groups" when the user has no private groups.

### ISSUE THREAD

**Issue by Morgul** [RocketChat/Rocket.Chat#776]
Just noticed that if you have no private groups, you're still given the option of looking for more private groups, which clearly, you won't have:

<img width="248" alt="screen shot 2015-09-12 at 12 26 03 pm" src="https://cloud.githubusercontent.com/assets/770655/9832720/9a2e6926-5949-11e5-8193-5a0e2e4b1b92.png">

Probably should only show 'More private groups' once the user has more than a set limit. 3? 5? Not sure what the best limit is.

**Comment by gmsecrieru** [comment]
I can look into this! :)

**Comment by gmsecrieru** [comment]
I kept thinking about the suggested limit and IMHO this would go beyond the issue itself, which was displaying a "useless" UI element. 

Let me know what you folks think about [this suggestion](https://github.com/gmsecrieru/Rocket.Chat/commit/55d9b111207d39ae97f7d6b492efbecd2f8a1300) so I can move this further or open a PR later today :)

**Comment by Morgul** [comment]
@gmsecrieru Agreed. I mean, the optimum solution is to only show the element if there's no longer any room for private chats; for now, it's consistent with channels, i.e. only show it if the list of private groups is > 1.

**Comment by geekgonecrazy** [comment]
@gmsecrieru yeah I think that would maybe be a separate ordeal.  It might be kind of nice to limit.. but it could be potentially hard to get right.


on a related note.  It'd be amazing to paginate the channel lists some how. Both public and private.  Can get pretty large.

**Comment by Morgul** [comment]
@geekgonecrazy I think the current scrolling is fine, but it definitely needs a filter input. :)
