### ISSUE TITLE
[REST API] Authentication with Facebook

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#7766]
We need an API that will allow the mobile apps to use the Facebook SDK to authenticate the user, without using the oAuth methods currently being used.

```
            "serviceName": "facebook",
            "accessToken": accessToken,
            "idToken": idToken,
            "expiresIn": Int(expirationDate.timeIntervalSinceNow),
            "scope": "profile"
```

**Comment by rafaelks** [comment]
Updating it, added information needed.

**Comment by rafaelks** [comment]
That won't be necessary anymore, the native apps won't be using the native SDKs for now and we don't have a plan to do that in near future.

**Comment by rackmuthu** [comment]
How to authenticate with keycloak using the REST API
