### ISSUE TITLE
[REST API] Authentication with Google

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#7768]
We need an API that will allow the mobile apps to use the Google SDK to authenticate the user, without using the oAuth methods currently being used.

**Comment by rafaelks** [comment]
Updating: we have this API already in WebSocket, so just need to replicate.

**Comment by MarcosSpessatto** [comment]
@rafaelks, see #8947

**Comment by rafaelks** [comment]
@MarcosSpessatto It doesn't have the authentication API yet, does it?

**Comment by MarcosSpessatto** [comment]
In this PR, have Google authentication API only.

**Comment by rafaelks** [comment]
@MarcosSpessatto Hmmm!!! Is it the `/login` API? How should we use it?

**Comment by MarcosSpessatto** [comment]
I'll create docs for this endpoint ;)

**Comment by rafaelks** [comment]
That won't be necessary anymore, the native apps won't be using the native SDKs for now and we don't have a plan to do that in near future.
