### ISSUE TITLE
Unread mention indicator doesn't always go away until switching channels.

### ISSUE THREAD

**Issue by Morgul** [RocketChat/Rocket.Chat#777]
I've noticed a few times that the unread mention indicator doesn't always go away once you've read past the mention. In order to clear it, you need to switch channels and switch back.

For reference, this is the indicator I mean:
<img width="259" alt="screen shot 2015-09-12 at 12 31 33 pm" src="https://cloud.githubusercontent.com/assets/770655/9832887/9b390a28-594a-11e5-9d9f-43e7207df48e.png">

**Comment by Morgul** [comment]
Some additional information. The text stays bold as if there's new messages as well; those seem likely to be caused by the same bug.

I seem to be able to trigger this consistently by being in another tab in Chrome, having someone say something in channel, and then come back to it.

**Comment by rodrigok** [comment]
@Morgul, I did some changes related to messages loading and how the **mark as read** works, can you verify if this issue still occurs for you?

**Comment by Morgul** [comment]
@rodrigok Are the changes in a branch somewhere, or have they been merged? (I haven't had a chance to setup a dev instance yet, so I've just been testing with the auto built docker.)

**Comment by rodrigok** [comment]
@Morgul the changes are in the branch master:

https://github.com/RocketChat/Rocket.Chat/commit/199f45bd92af72c4cb2c9d564ff33174b03fc5c4
https://github.com/RocketChat/Rocket.Chat/commit/a96095c32130a72e2d00e41f971da52429ee18d3

**Comment by marceloschmidt** [comment]
Probably related to #523

**Comment by Morgul** [comment]
@rodrigok Sorry it took so long for me to getting to test this; work has been a bit insane. But, I can no longer seem to reproduce this.

**Comment by rodrigok** [comment]
@Morgul nice, there is a lot of issues with the unread mark, bar and "mark as read", we are trying to improve and find the best behavior :smile:
