### ISSUE TITLE
Avatar Upload Doesn't Work 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7771]
* Version of Rocket.Chat Server: 0.58.0
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances:  1 
* DB Replicaset Oplog: yes
* Node Version: 4.8.3

avatar doesnt change while tryna change the avatar its upload but no change

**Comment by MartinSchoeler** [comment]
The problem seems to be with the upload avatar feature, since i can change my avatar via url just fine

**Comment by MartinSchoeler** [comment]
Actually, #7643 fixes this

**Comment by fifou17** [comment]
@MartinSchoeler thank you
