### ISSUE TITLE
rocket.chat doesnt load on mobile 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#7772]
* Version of Rocket.Chat Server: 0.58.0
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances:  1 
* DB Replicaset Oplog: yes
* Node Version: 4.8.3

rocket .chat doesnt load on mobile isnt responsive 

![telechargement](https://user-images.githubusercontent.com/16228448/29401122-d653e502-8327-11e7-8dff-ea22a23df66d.png)

**Comment by ArchimedesFM** [comment]
I have the same Problem with Rocket.Chat Server 0.58 and iOS-App Rocket.Chat 2.5.0 (iPhone SE).
In some cases you can see the right menue, but not in all channels. In Landscape Mode you can see all elements. The Problem does not exist with Rocket.Chat+.

**Comment by soundstorm** [comment]
Seems like this is because of #7776
