### ISSUE TITLE
LDAP Login does not work if LDAP profile picture sync is enabled.

### ISSUE THREAD

**Issue by KervyN** [RocketChat/Rocket.Chat#7773]
Welcome to the house of fun.

### Description:
If you enable the LDAP profile picture sync, people are not able to login with their LDAP credentials. Ironically syncing the LDAP profile pictures does work if you enable it and click "Sync LDAP".

### Server Setup Information:
* Version of Rocket.Chat Server: 
   0.58.0
* Operating System: 
   Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc):
   1. killall node
   2. git clone
   3. npm install
   4. restart server
* Number of Running Instances:
   5 on single host
* DB Replicaset Oplog:
`replication:
  replSetName: rs0
  oplogSizeMB: 100`
* Node Version:
`$ node -v
v4.5.0`
* LDAP Filter:
`{"filter": "(&(objectClass=Person)(memberOf:1.2.840.113556.1.4.1941:=CN=chat,CN=xxxx,DC=xxxx,DC=xxxx)(userPrincipalName=#{username}))", "scope": "sub", "userDN": "CN=xxxx,CN=xxxx,DC=xxxx,DC=xxxx", "password": "xxxx"}`

### Steps to Reproduce:
* Login to RC with your admin account
* Enable LDAP profile picture sync.
* Try to login again
* Fail hard (User not found or password wrong)
* Make a sad face, because you are the only admin available and can't login to unset the LDAP profile picture sync and no one can login.
* wait until colleague comes around who is still logged in
* unset LDAP profile picture sync
* Login works

#### Bonus:
* Enable LDAP profile picture sync, sync all LDAP Accounts, disable LDAP profile picture sync to have all LDAP profile pictures synced ¯\_(ツ)_/¯

#### Bonus2:
* Enable LDAP profile picture sync
* try to login
* fail hard
* click "password reset"
* click mail in link
* set a password you like
* be happy to get logged in
* be not abled to login again. Neither with the new, nor with the old password. (We don't sync pw changes back to the LDAP.)

I would like to provide logs, but the are no logs. Even debug does not show anything relevant.

### Expected behavior:
Let user login into RC while LDAP profile picture sync is enabled

### Actual behavior:
people are not able to login with their LDAP credentials if LDAP profile picture sync is enabled.

### Relevant logs:
I would like to provide logs, but the are no logs. Even debug does not show anything relevant.

![image](https://user-images.githubusercontent.com/1584820/29400777-d14eaf90-832e-11e7-8fd1-846e486008ee.png)
![image](https://user-images.githubusercontent.com/1584820/29400800-e9d71264-832e-11e7-9e21-2ba7f9ec9540.png)

**Comment by MarPiRK** [comment]
The same issue (version 0.58.0, Docker image).

**Comment by JigSawFr** [comment]
Remain on 0.59.x

**Comment by TwizzyDizzy** [comment]
Can I somehow help debugging to fix this rather urgent issue as it blocks us from upgrading from 0.56.0 to a recent release of RC.

Cheers
Thomas

**Comment by willihelm** [comment]
+1

**Comment by mkretzer** [comment]
+1

**Comment by TwizzyDizzy** [comment]
Those +1 don't really help ;) Please use the Emoji-reaction instead :)

**Comment by TwizzyDizzy** [comment]
Hi folks,

it seems as though @sampaiodiego has a fix for this. Please see https://github.com/RocketChat/Rocket.Chat/issues/7405#issuecomment-328795696 and give it a shot ASAP. Please also comment on issue #7405 and not here.

I would also suggest to close **THIS** issue here in order to consolidate all efforts in #7405.

Cheers
Thomas

**Comment by sampaiodiego** [comment]
thanks @TwizzyDizzy .. I'm closing this in favor of #7405 :+1:

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:34525 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1droTf-001Plj-02
	for greg@biomassiv.es; Tue, 12 Sep 2017 11:55:59 -0500
Date: Tue, 12 Sep 2017 09:55:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1505235319;
	bh=xRovLfyAFTds+Lq7CmLYrG0x7KxM+lnBuAXuftXGvcE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=SjYIO+EelvVzOiU5cn0v6IVD7Pn6itW9lCkZRP6/KL2wekc8EPIp666DE/42EMMcN
	 //ptO06TyOfI1bg2e/iLsPDjBAjvlJIPL+EHvX131YYO8Vyu6CF/7R4JHUDZzVOkzo
	 uMM+pZbMRdcPHdIZg+UkMOVKZHp3QBXjYyHpO1lI=
