### ISSUE TITLE
Long channel topic leads to over-wide window

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#7776]
Just updated to 0.58.0, the channels with longer topics show following behaviour:

Top bar (#channelname topic...) resizes to fit topic (single row). The message-UI also resizes to match top bar. Both run out of the browser window and the overflowing content is hidden; you can't scroll horizontally, other problem is, that you can only change the topic from the Rocket.Chat App, as the sidebar disappears too.
Somehow - if you managed it to change the topic to something shorter - the items in the sidebar are no longer clickable on a desktop client. [Separate issue?]
Screenshots are in referenced issue #7772

**Comment by stalley** [comment]
You can mostly fix this temporarily by putting the below in Layout-> Custom CSS

`.fixed-title h2 {
    width: 100%;
    overflow: hidden;
    white-space: normal;
    text-overflow: ellipsis;
    font-size: 22px;
    font-weight: 500;
    line-height: 29px;
    flex: 1;
}`

**Comment by gregs007** [comment]
Confirmed here as well, 0.58.0. Persists on all browsers-- especially evident on mobile browsers

**Comment by soundstorm** [comment]
@MartinSchoeler the "Closes" keyword does not trigger a close of the mentioned *multiple* issues when merged. You have to write it down as `Closes #7756, closes #7776, closes #7772` [GitHub Reference](https://help.github.com/articles/closing-issues-using-keywords/)
Otherwise the issues will remain open until manually closing.

 Closing this manually.
