### ISSUE TITLE
[Feature] "Logout from other logged in locations" button should be accessible even if "Allow User Profile Change" is set to False

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7777]
### Description:

We have disabled 

 - ```Allow User Profile Change```
 - ```Allow Username Change```
 - ```Allow Email Change```
 - ```Allow Password Change```

because attributes like ```Name```, ```Username```, ```EMail``` are fully set by SAML/Shibboleth login. 

With this configuration(```Allow User Profile Change``` set to False) it's no longer possible to use the ```Logout from other logged in locations``` button. Activating ```Allow User Profile Change``` would make a user be able to change ```Name``` field in his profile, what we don't want.

A solution might be to move the ```Logout from other logged in locations``` button to a different menu item or add a permission like ```Allow Name Change``` (True/False)" under ```Administration/Accounts``` so the User Profile can be displayed, but the user can't change his ```Name``` field.

### Expected behavior:

```Logout from other logged in locations``` button should be accessible even if ```Allow User Profile Change``` is set to False.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.3

**Comment by localguru** [comment]
see #7126 too

**Comment by AmShaegar13** [comment]
Should we move the button to "Security"? At least, that's where I searched for it.
