### ISSUE TITLE
Why is there a bcrypt hash involved when using method spotlight

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#7783]
["{\"msg\":\"method\",\"method\":\"spotlight\",\"params\":[\"max\",[{\"_id\":\"TBf6pmyAFo4Nz6tyx\",\"services\":{\"password\":{\"bcrypt\":\"$2a$10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}},\"username\":\"max.mustermann\",\"status\":\"away\",\"active\":true,\"roles\":[\"admin\"],\"name\":\"Max Mustermann\",\"statusConnection\":\"online\",\"utcOffset\":2,\"requirePasswordChange\":false,\"avatarOrigin\":\"upload\",\"statusDefault\":\"away\",\"emails\":[{\"address\":\"max.mustermann@email.com\",\"verified\":false}]},\"max.mustermann\"],{\"users\":true,\"rooms\":true}],\"id\":\"36\"}"]

RC version 0.57.2

**Comment by MartinSchoeler** [comment]
Please use our [forums](forums.rocket.chat) to ask questions like this. Thanks!
