### ISSUE TITLE
Bug: Click on user opens user sidebar tab

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#7784]
When clicking on a username, the default is to store the username in a variable and when clicking on the users tab in the sidebar using this to show info about that user.
I'd like to click on a user and see the tab immediately.

The `view all >` could be aligned top left instead of bottom right as it's more a "go back" action.

**Comment by MartinSchoeler** [comment]
This is a bug, the flex tab should open when clicking a user

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that have happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
