### ISSUE TITLE
Start server failed

### ISSUE THREAD

**Issue by fengsaofly** [RocketChat/Rocket.Chat#7787]
Dear all,
I'm fresh for this project.My server is Ubuntu 14.04.5 LTS.
when I run the command:
` sudo snap install rocketchat-server`
 I got this:

> cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied

PS:I run my server as a Root.I login snap as a new Ubuntu SSO account.

could anyone do me a favor? thanks in advance.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by cbartram** [comment]
Was this ever resolved, im having the same issue?

**Comment by Jfaler** [comment]
Rebooting the server resolved this issue for me.
