### ISSUE TITLE
Favicon alert not there.

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#7788]
### Description:

I am in the default room of general, but I do not have rocket chat focus, it is just a background tab, when some post a message i no longer have an alert update in the favicon of rocketchat's tab saying hey someone posted a message in the room you are in.

Only happened when I updated from 57 to 58

### Server Setup Information:

* Version of Rocket.Chat Server: 58.1
* Operating System:win 10
* Deployment Method(snap/docker/tar/etc): docker-compose
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version:

### Expected behavior:

I expect there to be a little green favicon icon over laided my favicon image

### Actual behavior:

the alert favicon doesn't appear.

**Comment by wargamesqcf** [comment]
Notification at all aren't working for general default channel. Logged on seen a ton of new messages but doesn't say I have any or where it the new messages start.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
