### ISSUE TITLE
Couldn't find Website in Internet Explorer 11.0.43

### ISSUE THREAD

**Issue by simon-doerflinger** [RocketChat/Rocket.Chat#7789]
Hey everyone,

I have the Problem that my Rocket.Chat Website isn't loading in the Internetexplorer. This only don't work on on Version 11.0.43 in 11.0.44 it's all fine.

I would appreciate any help on this

Thanks in advance

Simon

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.3
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

### Expected behavior:

Work fine

### Actual behavior:

Won't load the website

**Comment by simon-doerflinger** [comment]
So I set IE back to Default and it worked. I don't know what was wrong but now it's fine

**Comment by simon-doerflinger** [comment]
Close #7789

**Comment by pkgodara** [comment]
@simon-doerflinger I think this `closes #xxx` works with PRs only. You'll have to close the issue manually.
