### ISSUE TITLE
RocketChat / RocketChat+ Google / Facebook Mobile O-auth Authentication issues

### ISSUE THREAD

**Issue by SkinkaCru** [RocketChat/Rocket.Chat#7792]
Three issues here related to the same subject, oauth authentication through mobile apps

**Google oauth issues  :** 

 * You can't connect from the RocketChat mobile app using Google account. You get an error unknown. It's working using the RocketChat+ app.
 * On RocketChat+, it doesn't use your Google mobile account, you have to connect through a web login interface. 

**Facebook oauth issue :** 

 * If you connect from the RocketChat mobile app using Facebook account, it will ask you to create a new account instead of using your existing account (that you've created on a laptop previously)

#### _Server Setup Information_
* Version of Rocket.Chat Server: Latest
* Operating Systems: Ubuntu AWS / Android 7.1.1 on Nexus 6
* Deployment Method: Docker
* Number of Running Instances:  1

**Comment by geekgonecrazy** [comment]
Apps are completely different now.  So the oauth there have been completely rebuilt.  Closing
