### ISSUE TITLE
Right side bar menu on general channel disappeared when the page width min of 768px

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#7794]
### Description:

Right side bar menu on general channel disappeared when the page width min of 768px.
<img src="https://image.ibb.co/ifLK1a/ezgif_com_crop.gif">

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 2
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.3

**Comment by dmoldovan123** [comment]
one my browsers work perfect, Right side bar menu on general channel NOT disappeared

**Comment by MartinSchoeler** [comment]
This was already fixed by #7781
