### ISSUE TITLE
Desktop Notifications not working with Rocket.Chat+ 2.8

### ISSUE THREAD

**Issue by monty241** [RocketChat/Rocket.Chat#7795]
I've configured desktop notifications on Windows 10, Rocket.Chat+ 2.8.0, 1 instance, deployment: snap, db replicaset: ?, node: ?.

The test desktop notifications button works and shows in the bottom right corner a popup.

However, no other notifications appear. Rooms etc all default from account.

Reproduction:

1. Enable in account desktop notifications for messages.
2. Press test. Works.
3. Have someone send something. Nothing appears.

Expectation:

On step 3 a popup appears.

**Comment by aditya19496** [comment]
I will work on it.
Was working on Audio Notification part. Someone modified the code and my previous code is not working anymore. If I fix it, both issues will be solved.

**Comment by dkoryavov** [comment]
+1
server: Rocket.Chat 0.58.1
client: web or Rocket.Chat.Electron 2.8

Desktop notifications does not work at all . On the previous version (0.57.3) desktop notifications worked fine.

**Comment by lcharette** [comment]
+1, on MacOS Sierra. So it's not related to Windows

**Comment by lcharette** [comment]
As described in the related issue above, I had issues with notifications failing on web and Electron app for `All messages` notifications on some channel. I found out it was related to this setting. Changing this to a higher level made the notifications works again. It may be related to your issue.

![capture d ecran 2017-10-19 a 20 22 59](https://user-images.githubusercontent.com/2566513/31800366-59c54134-b50e-11e7-82ab-29b972303258.png)

**Comment by jeeringsole** [comment]
+1
server: RocketChat 0.61.0
client: Web or rocket chat Electron 2.10.5

Changing "max room members before disabling all message notifications" from 100 to 500 fixed the issue. Max of 19 users in one of the channels.

**Comment by donagrejja** [comment]
Using version 0.69.0

This is still an issue.
I can't seem to use the workaround either.

Notifications just won't work no matter what client I use.

**Comment by monty241** [comment]
Tested on 69 too. Better for subsquent messages, I get a flashing Rocket.Chat client. For initial message the counter remains at 0 and no-flashing even when a chat is assigned. Workaround is the new webhook on new message (not yet tested).

**Comment by garethwarry** [comment]
Confirmed an issue. Notifications were working, then upgraded the Windows client to version 2.13.3, and notifications no longer work. Happened to everyone on the server who upgraded their client. Fixed it by going to the Help dropdown menu in the client and selecting "Reset App Data". So, maybe it's a version migration issue?

**Comment by sampaiodiego** [comment]
we have updated notifications logic and this should be fixed now.

please let me know if this is still an issue and I reopen it.
