### ISSUE TITLE
Unclear meaning of Unread Tray Icon Alert

### ISSUE THREAD

**Issue by monty241** [RocketChat/Rocket.Chat#7797]
I've configured unread tray icon alert to true on Windows 10, Rocket.Chat+ 2.8.0, 1 instance, deployment: snap, db replicaset: ?, node: ?.

It is not clear to me what it means. There is no help for it.

![image](https://user-images.githubusercontent.com/7579444/29455960-aefaa5d0-8413-11e7-824e-0e0e6d9f6fcc.png)

Does unready tray icon alert mean the (1) in picture? If so, please relabel since tray for me means the tray in windows below as (2) in picture.

When it should be shown on (2) as a message, please make it flash and display something on (2).

**Comment by MartinSchoeler** [comment]
This is a electron app issue, please reopen this [here](https://github.com/RocketChat/Rocket.Chat.Electron) . Thanks!

**Comment by aspiers** [comment]
Was this ever refiled? I can't find it.
