### ISSUE TITLE
Update Real Time Api Documentation

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#7799]
Real Time Api Documentation is not up to date. For example there is a solve for my problem in #6665 but it is not described in the documentation

**Comment by jszaszvari** [comment]
As this is a open source project, if you feel like something is missing that should be there, and you have the answer for, please feel free to update the documentation by using the "Edit on GitHub" button.

![image](https://user-images.githubusercontent.com/872463/29465214-df87fe6a-847b-11e7-8002-a4c6faa16a31.png)

**Comment by graywolf336** [comment]
As has already been said, you can edit the documentation yourself and we would appreciate the contribution! The source for the documentation can also be found here: https://github.com/RocketChat/Rocket.Chat.Docs
