### ISSUE TITLE
Image upload preview not complete

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#780]
Some times the upload doesn't show the whole image just the top portion.

![image](https://cloud.githubusercontent.com/assets/51996/9834148/9a5602bc-5974-11e5-9faa-e00b6ed0dc62.png)

**Comment by marceloschmidt** [comment]
Can anyone confirm this is still an issue? I have tested it locally and on demo server with multiple image sizes and formats, and all seemed OK. If this is still a bug, we'll reopen it.

**Comment by geekgonecrazy** [comment]
i'll keep an eye out.  I think i've seen it recently.  But can't be 100% sure.

**Comment by geekgonecrazy** [comment]
Figured it out!

If you paste an image when you have the window small enough to collapse the menu this happens:
![image](https://cloud.githubusercontent.com/assets/51996/12900956/7f2e34b2-ce7e-11e5-8f36-d559c259bae5.png)

Normal size it shows just fine:

![image](https://cloud.githubusercontent.com/assets/51996/12900991/aa6b144c-ce7e-11e5-80e3-b8fcedcbc3c4.png)

**Comment by rodrigok** [comment]
See https://github.com/RocketChat/Rocket.Chat/pull/2310
