### ISSUE TITLE
Error Login API REST

### ISSUE THREAD

**Issue by fadao23** [RocketChat/Rocket.Chat#7802]
Hello, I have a bug with the API REST LOGIN , and I don't udestand why... 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances:  1
* DB Replicaset Oplog: 
* Node Version:

Actually all api request run except de api/v1/login.. 

That is my code : 

`    var x = new XMLHttpRequest();
    x.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
        console.log(JSON.parse(this.responseText));
    }
    };
    x.open("POST", 'http://52.xx.Xx.xx:3000/api/v1/login');
    x.setRequestHeader("Content-type","application/json");
    x.send(JSON.stringify({"user": "fadao23","password": "test12345", }));`

And every time i have this error : 

> 500 (Internal Server Error)

> Response for preflight has invalid HTTP status code 500

And if i enter in the broswer bar the URL (http://52.xx.Xx.xx:3000/api/v1/login') of my API i have this : 

`{
  "status": "error",
  "message": "API endpoint does not exist"
}`

Someone can help me ?

Thanks

**Comment by graywolf336** [comment]
You need to enable CORS.

And the reason it doesn't work when you go there is because it's a POST endpoint and not a GET.
