### ISSUE TITLE
Custom Translation Failed

### ISSUE THREAD

**Issue by gueeme** [RocketChat/Rocket.Chat#7804]
I'm trying to translate some terms that are not yet in standard language but it's still in English.
The syntax I am using is in the template reported in the translation section.

{
 "en": {
  "Channels": "Rooms"
 },
 "pt": {
  "Channels": "Salas"
       "Mark_as_unread": "Marcar como não lida",
       "Reply": "Responder",
       "Use_User_Preferences_or_Global_Settings": "Usar preferências das configurações globais",
       "Hide_Unread_Room_Status": "Ocultar status da sala não lida",
       "Unread_Tray_Icon_Alert": "Alerta de mensagem não lida na bandeja",
       "Disable_Notifications": "Desativar Notificações",
       "Notification_Duration": "Duração da Notificação",
 }
}

**Comment by MartinSchoeler** [comment]
You are missing a comma after "Salas" and there should not have a comma after "Duração da Notificação"

Custom translations should be a valid [javascript object](https://www.w3schools.com/js/js_objects.asp)

**Comment by JHoffmanME** [comment]
@MartinSchoeler This issue is closed, but I am having the same trouble.  I validated this JSON and can't sort out why none of the below translations work.  I have tried restarting the server as well.  Is there a new defect, or am I missing something?  Any help much appreciated.
`{
	"en": {
		"Hide_room": "Close Chat",
		"No_channels_yet": "Nothing yet" 
	}, 
    "fr": {
		"Hide_room": "Close Chat",
		"No_channels_yet": "Nothing yet" 
	}
}
`
