### ISSUE TITLE
Text from conversation is blocked while I am typing my message

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#7805]
### Description:

There's no error message.  But you can see that new things people are writing get covered up by the box I am typing my message in.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.58
* Operating System:  Ubuntu   (I'm running Chrome in Windows 7 for this issue though)
* Deployment Method(snap/docker/tar/etc): Heroku
* Number of Running Instances:  1
* DB Replicaset Oplog: yes
* Node Version:  v4.8.4

![utyj7sie2wsgrgfz2](https://user-images.githubusercontent.com/12577122/29476750-53ae1494-841a-11e7-9062-db3d617d0973.png)

**Comment by PsychoPath23** [comment]
The issue occurs when someone else is writing a comment. You are able to scroll the list to see the overlapped message, but that's pretty annoying

**Comment by MartinSchoeler** [comment]
Can you test this on the latest release? If you are still experiencing this issue, please open a new issue with updated details. Thanks!
