### ISSUE TITLE
Anonymous Users stay "registered", they should be deleted.

### ISSUE THREAD

**Issue by WebSavvyGuy** [RocketChat/Rocket.Chat#7806]
### Description:

Right now, when a user log ons chat anonymously, that name will still be registered in the database under the anonymous role (even if they have left forever).  I think we should have anonymous users automatically deleted after logging out or closing their browser or automatically deleted when a button is clicked in the admin panel.  (without having to delete them one by one which, for large sites, would take a very very long time)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Chat anonymously and select a username.
2. Leave the chat by closing the browser
3. That name can no longer be used forever.

### Expected behavior:

When an anonymous user logs off or leaves, that name should be deleted and be allowed to be used by another person in the future.

This will help also with load issues and just keep Rocket Chats database more clean.

I can understand that some may want to keep those stored, so there should be a way to delete them all automatically with a click of a button at the very least.

**Comment by rasos** [comment]
We have restricted anonymous use for Rocket.Chat read-only. So people can get around, but need to Sign in to start talking.

**Comment by WebSavvyGuy** [comment]
I have gone through my admin panel and see the users who are saved there are "anonymous offline" users.   Basically it means that username will forever be unable to be used again.

We need to remove "anonymous offline" users instantly.    They have no value for what this feature is supposed to represent.

**Comment by float1** [comment]
Yeah, I hope this will be impemented :+1:

**Comment by SeanPackham** [comment]
This is the expected behaviour. As rasos suggested: 

> We have restricted anonymous use for Rocket.Chat read-only. So people can get around, but need to Sign in to start talking.
