### ISSUE TITLE
Reloading the browser causes an empty conversation panel

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#7807]
### Description:

Open a room and reloading the browsers page causes an empty conversation panel.
This behavior does not occur on each reload.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.56.0
* Operating System: OSX and Unix  -> Platform darwin
* Deployment Method(snap/docker/tar/etc): tar, local
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* NodeJS Version: 4.8.2 - x64
* Commit Hash: 3018807507
* Tested with browsers: Chrome and Safari

### Steps to Reproduce:

1. Open any room, that has at least one message
2. Press F5 or reload the browsers page
3. Only the left column of Rocket.Chat is being loaded
4. The right hand panel is missing, no message / input box is shown at all

If the unexpected behavior does not occur, perform these steps multiple times.

### Expected behavior:

normal chat view/panel is being displayed

### Actual behavior:

No chat view/panel is being displayed

### This behavior does not occur on:

- `develop branch` (commit 10499e0)
- `version 0.58.1` (commit 060ce7d)

### Relevant logs:

In the browsers console several errors are shown:

**1. TypeError: Cannot read property 'split' of undefined**
Markdown.js:12 - Exception in template helper: TypeError: Cannot read property 'split' of undefined [`RocketChat.settings.get('Markdown_SupportSchemesForLink'`)]
Stack: RoomManager.js:58 -> getDomOfRoom

Later when the page has been loaded
RocketChat.settings.get('Markdown_SupportSchemesForLink') —> returns `[ 'http' , 'https' ]`

Assuming that `getDomOfRoom` is called before the RocketChat settings have been initialized

**2. Exception from Tracker recompute function: undefined**
TypeError: Cannot set property 'scrollTop' of null
`openRoom.js:4 openRoom(type, name)`
`roomDom.querySelector('.messages-box > .wrapper') —> undefined`

no errors in the server log

**Comment by danieljhochman** [comment]
See fix here I believe: 
#7687

**Comment by pettitto** [comment]
Can confirm this issue has been resolved in the latest release (0.58.1)

**Comment by danieljhochman** [comment]
Please close...

**Comment by vcapretz** [comment]
hi @ruKurz does this behavior stills occurs? I tried to reproduce it with no success, if it's fixed you can close the issue :smiley:

**Comment by danieljhochman** [comment]
Would be great if **anyone** could close issues. Admins could still monitor and re-open if something was closed in error.
