### ISSUE TITLE
Scrollbar shown in message input field

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7811]
### Description:

There is a scrollbar shown in the message input field if your browser isn't at 100% zoom level / you use the build-in windows scaling set at 150% for example.

### Server Setup Information:

* Version of Rocket.Chat Server: 10499e02cef140bfc7a57e52b6b194489498f2f3

### Steps to Reproduce:

1. Check out 10499e02cef140bfc7a57e52b6b194489498f2f3
2. Zoom in your browser to 150%
3. A scrollbar appears in the message input without entering anything in it

### Expected behavior:

![https://i.imgur.com/86uEtV3.png](https://i.imgur.com/86uEtV3.png)

### Actual behavior:

![https://i.imgur.com/pm8vu7z.png](https://i.imgur.com/pm8vu7z.png)

**Comment by aditya19496** [comment]
I will check it out.
