### ISSUE TITLE
Ver 58.1 problem css on mobile browser and app

### ISSUE THREAD

**Issue by pusadev** [RocketChat/Rocket.Chat#7819]
![2017_08_21_13 27 44](https://user-images.githubusercontent.com/31211921/29520513-a7e05eaa-8681-11e7-8a05-fc585fe6ceaf.png)

New version on rocket chat have problem on list member and open member profile

when click on username right tab dont scroll down, more dont see link "SEE ALL" for back to all members (see picture)

**Comment by ggazzo** [comment]
![image](https://user-images.githubusercontent.com/5263975/40525888-708c0c9e-5fb9-11e8-9b14-fc8fa1c9f38a.png)
 we have a new design now, should be working :)
