### ISSUE TITLE
Swipe with flex panel breaks

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#782]
![image](https://cloud.githubusercontent.com/assets/51996/9834171/fedd85fc-5974-11e5-8a42-9ccf9b3a89d0.png)

To reproduce: 

Open search then swipe from left to right to open menu.

**Comment by engelgabriel** [comment]
Does this still happens?

**Comment by geekgonecrazy** [comment]
I haven't seen it do exactly like that one.  But often after navigating a while the panel will slide back and be over the top of the buttons.

**Comment by marceloschmidt** [comment]
Is that on the cordova app, or on a mobile browser?

**Comment by geekgonecrazy** [comment]
@marceloschmidt I don't use the mobile browser on mobile now that cordova works :D  so cordova app.

**Comment by bott0r** [comment]
happens all the time on android too, can be fixed when changing the the angle one holds the mobile-phone, i.e. 90deg roation that refreshes the screen.

**Comment by marceloschmidt** [comment]
Fixed in https://github.com/RocketChat/Rocket.Chat/commit/7d180866b98142211d09b0ed0da768edeb48ba1b
