### ISSUE TITLE
[BUG] [UI] Close button needs some padding-top

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7820]
Hi,
I have some small issue with new design. Close button icon needs some `padding-top` see below image:
![close button design](https://user-images.githubusercontent.com/25859075/29521707-e0034e86-869b-11e7-8a7e-cba4ba60d6d3.png)
And this is after add `padding-top: 2px;` to `<i class="icon-cancel"></i>`:
![close button design_2](https://user-images.githubusercontent.com/25859075/29521708-e03b4c96-869b-11e7-99ef-068afe88d61f.png)

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): -
* Number of Running Instances: 
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4 - x64

**Comment by Lemmmy** [comment]
The circle around the button seems to have been removed in #7894.

**Comment by mnlbox** [comment]
Yes you right. So I close this issue too. :wink:
