### ISSUE TITLE
[BUG] [UI] Some padding and margin issue with new design in RTL layout

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7821]
@MartinSchoeler I have 3 issue with new design ( #7643 ) in RTL layout I describe these issues based on below image:
1. Extra space between side menu and page content. Because this extra space some of content not visible.
2. menu items needs some padding or margin from right but it's not available now.
3. Username also need some padding or margin from right but it's not available now.

All of these works well with previous design and breaks in new design 😢 
![rtl issue](https://user-images.githubusercontent.com/25859075/29522500-946f3004-869e-11e7-8e9c-3035d5ba41f8.png)

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): -
* Number of Running Instances: 
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4 - x64

**Comment by mnlbox** [comment]
Guys any update about this?
Many users use RTL language and now new design break app. :cry: 

**/CC:** @MartinSchoeler , @karlprieb , @sampaiodiego , @gdelavald

**Comment by gdelavald** [comment]
@mnlbox hey, this will be fixed for the next Release Candidate. Thanks for your patience.

**Comment by mnlbox** [comment]
see this:
![7821](https://user-images.githubusercontent.com/25859075/29759442-158ceb9a-8bd1-11e7-9d34-ace21b5f2b55.gif)

**Comment by cyclops24** [comment]
@karlprieb are you still working on this?

**Comment by gdelavald** [comment]
@cyclops24 feel free to create a branch and submit a PR for this.
