### ISSUE TITLE
Input text at bottom of page

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7824]
Version of Rocket.Chat Server: 10499e02cef140bfc7a57e52b6b194489498f2f3

In Firefox, at the very bottom of the page, the text you input in the message field is shown.

![](https://i.imgur.com/LSjXp3a.png)

**Comment by Lemmmy** [comment]
Bump - having the same issue

**Comment by zardyh** [comment]
I'm having the same issue in Chrome 60.

**Comment by Nabile-Rahmani** [comment]
Happens on Firefox Nightly 57.0a1, too.

Reproduction steps:
1. Click on the left pane.
2. Press `Page Down`/`End`.

**Comment by Lemmmy** [comment]
Reproduction steps work if the pane isn't full. If the pane is showing a scrollbar, then the issue doesn't happen.

**Comment by Lemmmy** [comment]
The element that shows the duplicate message is .autogrow-shadow. However, upon setting it to `display: none`, theres still ~4 pixels of white gap below the page.

**Comment by ggazzo** [comment]
i'm closing because its nice now ;)
