### ISSUE TITLE
Code snippet to jump to login page when anonymous?

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#7827]
We have set up Rocket.Chat allowing read-only access to channels for anonymous users. The login page is immediately skipped when visiting the chat server and goes to the Welcome page, which is a good user experience.
However, users find it hard to find the login button - it appears only at the bottom rather small when you click on a channel with write access for users. 
![joinedchannel](https://user-images.githubusercontent.com/485723/29558354-1d2d53b6-872c-11e7-8d0d-6c82d3810e6b.png) which is 
```
<div>
<button class="button register">
<span>Sign in to start talking</span>
</button>
</div>
```

How can I put a big login button on the welcome screen? Pasting the button code is not sufficient.

### Server Setup Information:
* Version of Rocket.Chat Server: 0.58.1
* Operating System: Debian

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by rasos** [comment]
Ten let's phrase it as a feature request (based on user feedback): Could we have an option for a larger Login button when visiting Rocket.Chat anonymously, e.g. on the left bottom corner or as patr of the footer or welcome page?

**Comment by rasos** [comment]
We have solved it simply with 
`<button class="button" type="remotelogin" value="remotelogin" onclick="Meteor.loginWithRemotelogin({})">Sign-in with remotelogin</button>`
Replace "remotelogin" with the preferred login method, as defined e.g. as oAuth login.
