### ISSUE TITLE
Custom CSS has no effect. 

### ISSUE THREAD

**Issue by Mustafa-C** [RocketChat/Rocket.Chat#7828]
In the Settings > Layout > Custom CSS, the CSS has no effect.
The code I am trying is:
`.avatar {
    height: 100% !important;
    width: 100% !important;
    overflow: hidden !important;
    position: relative !important;
    border-radius: 50% !important;
}`

**Comment by karlprieb** [comment]
Hey @Mustafa-C ! Which RocketChat version are you running?
