### ISSUE TITLE
New proposal layout for Member List

### ISSUE THREAD

**Issue by AdrianoCahete** [RocketChat/Rocket.Chat#783]
I think that layout for member list is a little bit annoying, because the scrollbar.
That scrollbar needed to only appear on member list itself, not with header.

So, i made a fast proposal (i cloned myself for test purposes):
![member_list](https://cloud.githubusercontent.com/assets/37474/9836268/1ac3cb72-59e9-11e5-9f29-2eb27dd87b2a.png)

All classes and styles are for test, just see the layout. :)

**Comment by Morgul** [comment]
Personally, I agree about not scrolling the header. However, the scroll bar needs some written as well, see #771.

**Comment by AdrianoCahete** [comment]
I like that scrollbar too. I'll try to implement that js, if i can't do, someone implement and i fix the css.

**Comment by geekgonecrazy** [comment]
:+1: Yeah the header staying put would be good.  :)

**Comment by marceloschmidt** [comment]
Closing this in favor of #771.
