### ISSUE TITLE
User info pop-up doesn't scroll to the bottom with a small client window

### ISSUE THREAD

**Issue by PsychoPath23** [RocketChat/Rocket.Chat#7832]
### Description:

If having a small client, clicking a user to start a conversation or block them won't allow scrolling down to the button options without expanding the client window

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Windows 10
* Deployment Method(snap/docker/tar/etc): Rocket.Chat+ client?
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: 2.8.0

### Steps to Reproduce:

1. Launch the client
2. Have the client's window size set fairly small
3. Select another user to bring up their user pop-up
4. Scroll the pop-up

### Expected behavior:

The user is able to scroll down far enough to see the button options and start a conversation or block the user (as appropriate)

### Actual behavior:

The pop-up only scrolls so far such that the button options aren't viewable unless the client window is expanded vertically

### Relevant logs:

http://i.imgur.com/h8D1Ium.jpg
^ fully scrolled down

http://i.imgur.com/8dBibEf.jpg
^ Expanded client window

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
