### ISSUE TITLE
Record audio in MP3 or OGG instead of WAV

### ISSUE THREAD

**Issue by AdamBLevine** [RocketChat/Rocket.Chat#7844]
The audio message feature is great but it's crazy to upload an uncompressed audio file.  

![image](https://user-images.githubusercontent.com/6858319/29594245-91536c16-8764-11e7-8297-df61f664781d.png)

This feature would be more efficient and useful if by default a more efficient audio codec such as .mp3 or .ogg was used. This would allow longer files to be uploaded and for those files to consume less storage and bandwidth.

**Comment by AdamBLevine** [comment]
Related: https://github.com/RocketChat/Rocket.Chat/issues/4552

It looks like a mp3 encoder add-on already exists for the wav recorder.

**Comment by amonemian** [comment]
@AdamBLevine how can I change the wav records into mp3 or ogg to transfer more efficiently?
Have you got any progress in installing the add-on? It would be appreciative if you let me know about the steps...
