### ISSUE TITLE
0.58.1 Notifications aren't sent by email

### ISSUE THREAD

**Issue by xklx** [RocketChat/Rocket.Chat#7845]
After updating from 0.57.2 to 0.58.1, notifications to the email from the rooms are not sent.
In room settings:
![image](https://user-images.githubusercontent.com/3716225/29610602-60ed9566-8803-11e7-8c64-eb4fda8aaec5.png)

Subscription
`{
        "_id" : "j7DGcBG3fwnAaq3h4",
        "open" : true,
        "alert" : false,
        "unread" : 0,
        "ts" : ISODate("2017-02-09T08:27:11.456Z"),
        "rid" : "46oKMSBcpDt5ox3wj",
        "name" : "test_room",
        "t" : "p",
        "u" : {
                "_id" : "zLFDfX8nxRbo2D3Kp",
                "username" : "test"
        },
        "_updatedAt" : ISODate("2017-08-23T08:22:17.574Z"),
        "ls" : ISODate("2017-08-23T08:22:17.574Z"),
        "f" : true,
        "mobilePushNotifications" : "all",
        "unreadAlert" : "all",
        "desktopNotifications" : "all",
        "desktopNotificationDuration" : 0,
        "disableNotifications" : false,
        "userMentions" : 0,
        "groupMentions" : 0
}`

**Comment by TheReal1604** [comment]
@xklx seems to be fixed in 0.58.2 https://github.com/RocketChat/Rocket.Chat/pull/7758

Can you test the issue pls and respond back? (Or close the issue directly). Thx!

**Comment by xklx** [comment]
Updated to 0.58.2.
Error not fixed.

**Comment by antgel** [comment]
Is there nothing in the logs about this, when they are set to debug mode?

**Comment by antgel** [comment]
@xklx Does this work for you now?

**Comment by geekgonecrazy** [comment]
Closing due to no response
