### ISSUE TITLE
Rocketchat has two running instances after restarting via systemd

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#7849]
### Description:

When restarting RC with systemd (`systemctl restart rocketchat`), the info page in the admin area does show two running instances, though it is expected, of course, that there's only running one.

![image](https://user-images.githubusercontent.com/179595/29624298-ff48dd5e-8828-11e7-89f0-b171f3ed0e3f.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.67.0-rc.1
* Operating System: Oracle Linux 7.5
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: false
* Node Version: 8.11.3

### Steps to Reproduce:

1. start RC, check admin/info: running instances, should be 1, if you're running one instance
2. restart RC via `systemctl restart rocketchat` 
3. check admin/info: running instances, should be 2, even though you want to run one instance
4. `ps aux | grep [n]ode | wc -l` is 1 though, so it's not actually a case of two running instances, but some other error in (maybe) counting the running instances

### Expected behavior:

It should be shown, that only 1 instance is running, which is actually the case

### Actual behavior:

It is shown, that 2 instances are running, which is not the case. Furthermore the warning to enable the MongoDB oplog is shown.

### Relevant logs:
`systemctl cat rocketchat`

    [Unit]
    Description=Rocket.Chat Server
    After=syslog.target
    After=network.target
    
    [Service]
    Type=simple
    Restart=always
    StandardOutput=syslog
    SyslogIdentifier=RocketChat
    User=rocketchat
    Group=rocketchat
    Environment=MONGO_URL=mongodb://user:password@host:27017/rocketchat?ssl=true
    Environment=ROOT_URL=https://my-chat-host
    Environment=PORT=3000
    WorkingDirectory=/opt/rocketchat
    ExecStart=/bin/node /opt/rocketchat/bundle/main.js
    
    [Install]
    WantedBy=multi-user.target

**Comment by TwizzyDizzy** [comment]
Well.. furthermore, as I just realized, the uptime calculation seems to be stuck, as it doesn't increase on reloading the info page. This might be a similar / related problem.

Cheers
Thomas

**Comment by Darkneon** [comment]
In the Mongo DB there's a collection named `instances`, does it get updated after a restart?

**Comment by TwizzyDizzy** [comment]
Two-part-answer:

**The time display problem**: I suspect, that the instance uptime is calculated by subtracting `_createdAt` from `_updatedAt` which is the uptime of that instance. Right? `_updatedAt` has the correct value and gets updated frequently (~ every 2 seconds). So I actually have no idea what is the problem here.

**The 'two instances are shown'-problem**: indeed, after restarting via `systemctl restart rocketchat` there are two instances in the instance collection in MongoDB, as shown below:
![image](https://user-images.githubusercontent.com/179595/29672786-81557cde-88ed-11e7-8237-d920b84e4161.png)

Cheers
Thomas

**Comment by Darkneon** [comment]
I took a quick peek and the `exit` signal is not caught in the package `konecty:multiple-instances-status` which contains the handler to remove the instance from the DB. 

I will need to investigate more but my guess at the moment is RC is forcing an early exit or preventing the signal from bubbling up.

**Comment by TwizzyDizzy** [comment]
Cannot reproduce anymore on `1.0.0-beta.2`
