### ISSUE TITLE
Ability to set a 'topic' for a channel

### ISSUE THREAD

**Issue by Morgul** [RocketChat/Rocket.Chat#785]
This is a classic IRC feature, and something I've always enjoyed. A lot of good IRC channels use this as an 'announcements' section; an easy place to get little snippets of news about the channel. I'm not necessarily sold on the idea of just slavishly borrowing IRC features; I'd be more than happy with a slightly more modern spin on the idea. 

(Basically, I'm open to suggestions, I don't immediately have many myself.)

In any event, I think something like this would be a nice feature to have. :)

**Comment by AdrianoCahete** [comment]
We can merge this suggestion with #328

**Comment by geekgonecrazy** [comment]
I agree this would be great to have.  Lets consolidate this into the existing issue #328
