### ISSUE TITLE
Missing livechat tab bar icons

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#7850]
### Description:
In new UI livechat tab bar panel icons for "knowledge base" and "past chats" are missing.

Bonus: the alignment of livechat toggle is not good on linux

![clipboard - august 15](https://user-images.githubusercontent.com/8591547/29629244-86ce422a-880e-11e7-8803-e5e4969baaab.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Open a livechat conversarion

### Expected behavior:

See tab bar full of icons

### Actual behavior:

There is an empty space on tab bar.

**Comment by gdelavald** [comment]
Fixes in latest RC.
