### ISSUE TITLE
Missing verified email indicator and 'resend verification email' button

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#7851]
### Description:

Both elements and functionality are missing on the new UI

![image](https://user-images.githubusercontent.com/8591547/29629604-caa7788a-880f-11e7-9413-9972fc88495c.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Go to My Account page

### Expected behavior:

Show if my email is already verified and if not show the 'resend verification email' button.

### Actual behavior:

No indicator or button are shown.

**Comment by aditya19496** [comment]
I will work on it.

**Comment by aditya19496** [comment]
Will create a pull request tomorrow.
