### ISSUE TITLE
[BUG] Show "Invalid user" message sometimes after visit login page

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7858]
Hi guys,
I see "Invalid user" red message sometimes after visit login page. I saw it also on a fresh install and also after `meteor reset`:
![screenshot from 2017-08-27 15-55-27](https://user-images.githubusercontent.com/25859075/29749431-9dc4c6ea-8b40-11e7-9398-78013a7d3e13.png)

I can't catch it or find any reason about this. Do you have any idea?
### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): -
* Number of Running Instances: 
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4 - x64

**Comment by mnlbox** [comment]
@rodrigok do you have any idea?

**Comment by mnlbox** [comment]
@MartinSchoeler do you have any idea about this?

**Comment by mnlbox** [comment]
I see this again. This time I check Firefox console and this error message be there:
```
Error logging in with token: Error: You've been logged out by the server. Please log in again. [403] undefined
```

**Comment by mnlbox** [comment]
@ggazzo , @karlprieb are you any suggestion? I see this error message again today. :cry:

**Comment by cyclops24** [comment]
Part of #8494

**Comment by engelgabriel** [comment]
This happens when the Auth Token expires or is deleted. This is part of the Meteor Accounts package, and we don't have much control over it. We will replace the package with our own soon, so this issue won't be relevant anymore.

**Comment by mnlbox** [comment]
@engelgabriel Any news about new Account Package. This old issue causes bad UX for users :thinking:

**Comment by mnlbox** [comment]
@engelgabriel

**Comment by mnlbox** [comment]
@engelgabriel @ggazzo Guys this is still happens after 1 year. Any plan for this?

**Comment by Boby** [comment]
+1 on this
