### ISSUE TITLE
Channels search not overlaps livechat and has weird margins

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#7870]
### Description:
![overlaps](https://user-images.githubusercontent.com/8591547/29697204-1f391dc6-8924-11e7-969c-6cee437eda88.PNG)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.0
* Operating System: Windows

**Comment by engelgabriel** [comment]
Caused by https://github.com/RocketChat/Rocket.Chat/pull/7865

**Comment by geekgonecrazy** [comment]
Also related the status icon bleeds off the side when searching

![image](https://user-images.githubusercontent.com/51996/29697857-4b25c7ac-8917-11e7-919b-c7203bbbbcbe.png)

**Comment by gdelavald** [comment]
@geekgonecrazy that last commend was fixed by #7880
