### ISSUE TITLE
LEAVE and HIDE channels buttons are missing on the new UI

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#7872]
![image](https://user-images.githubusercontent.com/1000217/29697476-c6dd22ce-8925-11e7-848f-6a3006d7430b.png)

**Comment by aditya19496** [comment]
i will do it.

**Comment by sasakura-sora** [comment]
Same controls are also missing on Direct Messages and Private Groups.

**Comment by cyclops24** [comment]
@engelgabriel any news about this?

**Comment by karlprieb** [comment]
@cyclops24 I will fix that tomorrow :)
