### ISSUE TITLE
File upload no longer works on mobile after ui redesign 

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#7876]
On mobile Web view, clicking the plus on the message and clicking Computer does nothing. This seems to have stemmed somewhere since the new ui redesign.

**Comment by gdelavald** [comment]
@Lemmmy Hey, I just tested this on the demo server and also locally and it seems like it's working fine. Could you maybe add a video of this or add some reproduction steps?
Thank you.

**Comment by Lemmmy** [comment]
Seems it works fine in the Chrome browser on android, but not in the Rocket.Chat app (the Web view one)

**Comment by Lemmmy** [comment]
Here is a video showing the behaviour: https://youtu.be/e_vDE3g8hrQ

**Comment by k0nsl** [comment]
In `0.59.0-rc.1` with FF `55.0.2` this is no issue.

**Comment by JigSawFr** [comment]
Same problem (as shown on the video) identified on RocketChat+ Mac App. (a web view too in think).
Nothing appear if you click on add files but if you continue, it will work after many tries.

**Comment by gdelavald** [comment]
@JigSawFr Hey, which version of the Mac App are you using? Asking because I couldn't reproduce this in the latest version (2.9.0).

**Comment by ledainam** [comment]
@gdelavald : i have same issue when upgrade to 0.59.1 
i used mobile app Rocketchat (not Rocketchat+) both android and iOS. 
in previous 0.58, it worked fine.
