### ISSUE TITLE
How can I update my RocketChat while running in Docker?

### ISSUE THREAD

**Issue by tuliobaars** [RocketChat/Rocket.Chat#788]
I've just deployed Rocket Chat inside a docker container, it's up and running. I'm having a problem figuring out on how to detect and update the software. This is my first time using docker.

**Comment by Sing-Li** [comment]
@tuliobaars   It will depend on which image you used to deploy in docker. `rocket.chat` image?  `rocketchat/rocket.chat` image? or other?

**Comment by Morgul** [comment]
Really, you should just need to do a `docker pull` of the image you deployed, and then recreate the container. However as that's a bit of a pain, I have an alternative.

The solution I've chosen is to leverage the `rocketchat/rocket.chat` image, and a `docker-compose.yml` script. I've put them up in a gist for you to modify and use as you see fit:

* https://gist.github.com/Morgul/67ec3f3b7ac061f32c3a

**Comment by Sing-Li** [comment]
@Morgul  very interesting.  

Do you mind taking over this , https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux

... and perhaps add  an 'update'  operation ...

**Comment by Morgul** [comment]
@Sing-Li No, I wouldn't mind at all. An update operation should be pretty straightforward.

**Comment by Sing-Li** [comment]
@Morgul  Awesome!   Please go ahead and submit a PR.  

Thanks in advance for your help (feel free to mod the base scripts to something more useful).  Pierre, the original author, is actually a hoster - so those scripts were prepared with automat hosting in mind.  Also, please feel free to mod the doc.  TA

**Comment by geekgonecrazy** [comment]
@tuliobaars were you able to get it updated?

**Comment by gmsecrieru** [comment]
Closing this one. Please report back should the need arise.
