### ISSUE TITLE
Sidebar link to fork repo not legible after UI Redesign

### ISSUE THREAD

**Issue by mrinaldhar** [RocketChat/Rocket.Chat#7891]
The link at the bottom of the left sidebar to fork Rocket.Chat Github repo has a dark color over the dark background (after redesign). 

Screenshot attached. 
<img width="409" alt="screen shot 2017-08-25 at 3 26 46 pm" src="https://user-images.githubusercontent.com/5917608/29709408-cf65aafe-89a9-11e7-8d28-40350c9febb0.png">

**Comment by farodin91** [comment]
It would be also cool to level the rocket chat text more center to the input field.

**Comment by rodrigok** [comment]
Fixed by #7882
