### ISSUE TITLE
Online and Away status of DM candidates on the side bar seems indistinct after UI redesign

### ISSUE THREAD

**Issue by madguy02** [RocketChat/Rocket.Chat#7892]
The presence status seems indistinct after the redesign mostly due to color mismatch and missing proper sizing of DM candidates appearing on the sidebar

**Comment by aditya19496** [comment]
Can I start working on it?

**Comment by madguy02** [comment]
@MartinSchoeler

**Comment by gdelavald** [comment]
Hey, we have made some modifications in the status based on feedback and the design we are implementing for the next release
