### ISSUE TITLE
Misaligned cross button in sidepane.

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#7896]
### Description:

Misaligned cross button in sidepane.

![screenshot from 2017-08-25 19-08-53](https://user-images.githubusercontent.com/16938349/29716653-c3ec69ea-89c9-11e7-9497-66bab7ea2cc9.png)

### Server Setup Information:

On demo server, 0.59.0.rc-1 I guess.

### Steps to Reproduce:

1. Click any icon in sidepane.

### Expected behavior:

Aligned cross inside circle.

### Actual behavior:

Cross not in center of circle.

**Comment by Lemmmy** [comment]
May have been fixed in #7894 - the circle aroudn the cross was removed.

**Comment by pkgodara** [comment]
Seems so. Lets close it.

**Comment by mnlbox** [comment]
Maybe related: #7820
