### ISSUE TITLE
How to get users presence when it changed using Realtime API [Question]

### ISSUE THREAD

**Issue by distlibs** [RocketChat/Rocket.Chat#7897]
### Description:

I can't find in Realtime API subscription to get other users presence (online, offline) when it changed. Is there a possibility to get it using 0.59.0-rc.0? I only find REST API method /api/v1/users.getPresence.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): git clone
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4 - x64

**Comment by graywolf336** [comment]
Please see the package's documentation which handles that: https://github.com/Konecty/meteor-user-presence#server-methods

Feel free to submit a pull request adding that information to our documentation. 👍 https://github.com/RocketChat/Rocket.Chat.Docs

**Comment by KBelous** [comment]
you need to subscribe to stream-notify-logged subscription with user-status event.
https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-notify-logged/
