### ISSUE TITLE
Markdown: striked text is not supported

### ISSUE THREAD

**Issue by Calinou** [RocketChat/Rocket.Chat#79]
Markdown allows you to write striked text by surrounding text with `~~` (two tildes). ~~Example.~~

It doesn't appear to be possible in Rocket.Chat.

**Comment by chrisidefix** [comment]
Actually, I just tried this in the demo and it works fine - either someone already implemented it there or this issue should have been closed?

**Comment by Calinou** [comment]
It works, but you use only one tilde, not two, which is strange.

**Comment by chrisidefix** [comment]
Yes, I get what you are saying now - I guess implementing this would be fairly straight forward. I suggest to keep both options, though (so entering `~test~` and `~~test~~` would both result in ~~test~~).

**Comment by rodrigok** [comment]
Agree, I will fix it.
