### ISSUE TITLE
option to hide "room announcements" and "topic" changes

### ISSUE THREAD

**Issue by Simonlee2112** [RocketChat/Rocket.Chat#7900]
I would like the option to be able to hide "room announcements" and "topic" changes in a channel.
This is somewhat possible at the moment by changing the secondary font colour but it does not get rid of the message itself.

Ideally it would be similar to the hiding of join / leave messages

Server Setup Information:

You are currently hosting the site

Rocket.Chat Version: 0.58.2
NodeJS Version: 4.8.4 - x64
Platform: linux
Process Port: 3000
ReplicaSet OpLog: Enabled
Commit Hash: 988103d
Commit Branch: HEAD

**Comment by Simonlee2112** [comment]
Would you know if this is likely to be implemented soon.
Or if it could just be done on our site that would be great (i can give you more details for this)

**Comment by robguinness** [comment]
I second this. It's annoying to have those messages, especially when you are setting up a channel and maybe tweaking the topic slightly.

**Comment by BrennenHodge** [comment]
I agree. Any updates on this?

**Comment by BrennenHodge** [comment]
I found a solution: Prune the messages you want to remove. You're able to select the time when the notifications happened.

**Comment by supra08** [comment]
@MartinSchoeler, @sampaiodiego  can I take up this issue?

**Comment by sampaiodiego** [comment]
sure @supra08 .. we'll be more than happy =)

**Comment by Sing-Li** [comment]
Our UI team will get to this in time.  But calling on the community to implement it in the meantime.

**Comment by ritwizsinha** [comment]
I am working on it

**Comment by ggazzo** [comment]
closed by #16243

**Comment by Mekk** [comment]
I am using Rocket Chat 4.7 and while it is indeed possible to disable various system messages by editing „Hide System Messages” options, it doesn't seem possible to disable the information which this issue mentions in the title: room announcement change.

I just disabled absolutely everything there was in this menu and I am still looking at sequence of „Room announcement changed to: …” notifications.
