### ISSUE TITLE
Double scroll on 'keyboard shortcuts' menu in sidepane.

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#7901]
### Description:

![screenshot from 2017-08-25 19-33-57](https://user-images.githubusercontent.com/16938349/29717467-e89e0e3a-89cc-11e7-9bf0-7bf3f9493ff5.png)

### Server Setup Information:

demo server. 0.59.0.rc-1

### Steps to Reproduce:

1. Open `keyboard shortcuts` in sidepane.

### Expected behavior:

single scroll on right side.

### Actual behavior:

Double scroll on right.

**Comment by aditya19496** [comment]
Solving this out.
