### ISSUE TITLE
Message textarea not vertically centered on firefox

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#7903]
# Chrome
![](https://shitty.download/0ZHw.png)
![](https://shitty.download/W1uC.png)

# Firefox
![](https://shitty.download/p3GA.png)
![](https://shitty.download/s2mf.png)

**Comment by karlprieb** [comment]
@Lemmmy I can't reproduce this bug on Firefox 55 and 56. In which version that problem occur to you?

**Comment by Lemmmy** [comment]
57.

**Comment by MartinSchoeler** [comment]
@karlprieb @Lemmmy this seems to happens only on windows OS

**Comment by Lemmmy** [comment]
I'm on Linux.

**Comment by mnlbox** [comment]
I also using Linux.

**Comment by mnlbox** [comment]
Thanks guys it's fixed now. 😉
