### ISSUE TITLE
Chat box no longer auto-focuses when typing

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#7905]

**Comment by inklit** [comment]
this affects me too

**Comment by aditya19496** [comment]
Its working fine for me. Can you tell me how its not working?

**Comment by Lemmmy** [comment]
Click outside the message box (e.g. on someone's message) and start typing. Before, it would focus the textbox. Now it does not.

**Comment by aditya19496** [comment]
Ok I will look into it. Thanks for informing.
