### ISSUE TITLE
Sidebar using name instead of username for avatar URLs

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#7907]
![](https://shitty.download/mVb5.png)

All users shown have avatars on rocketchat - but only some of them are showing up in the sidebar.

This issue does not exist in the chat window or members list.

**Comment by engelgabriel** [comment]
We need to see the console log to be able to replicate the issue.

**Comment by Lemmmy** [comment]
I've found the source of the issue - the avatars in most places in the UI transform the name to lowercase (e.g. lemmmy), but in the sidebar the case is not transformed at all (e.g. Lemmmy). It seems /avatar/$AVATAR is case sensitive, and prefers lowercase. Any uppercase in the name causes it to show the default letters avatar.

**Comment by NexFive** [comment]
I have the same problem
