### ISSUE TITLE
RocketChat call webService on android client

### ISSUE THREAD

**Issue by MahdiPishguy** [RocketChat/Rocket.Chat#7911]
since 3 days ago i'm trying to find which file or implementation on android client is for RocketChat REST web services, for example:

`/api/v1/login`

unfortunately i cant find implementation classes for them to learn that for developing client application, Thanks in advance

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
