### ISSUE TITLE
Offline email notifications do not work for users just added to new private rooms

### ISSUE THREAD

**Issue by iansrx** [RocketChat/Rocket.Chat#7913]
### Description:

The users I add to a new private room does not receive offline email notifications even though they are @mentioned. 

All the default notification settings for both the room and the user is set to receive email notifications upon being @mentioned while logged out.

This problem goes away the moment the user goes to the notification setting of the room (on the right toolbar), changes the value of "Notification > Email" to 'Mention', and optionally sets it back to the default.

This prevents me from adding users to rooms and trusting that they are receiving email notifications when they are offline.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Linux x64
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v4.8.4

### Steps to Reproduce:

1. Check that Email Verification is set to True (Administration > Accounts > Registration > Email Verification : true)
2. Create a new private room, add any user to this private room (ex. user-B)
3. Make sure user-B is logged out, then send a message @mentioning user-B. (Also make sure that user-B My Account > Preferences > Offline Email Notifications is set to default value of : 'Every Mention/DM').
4. Since user-B is logged out, this user should receive an email notification of this mention. But seems no email notification is received. 
5. Login as user-B, go to this newly created private room.
6. Set the Notification settings (right toolbar) of this room to "Email : Mentions". Save.
7. Logout user-B, and have any user send another message @mentioning user-B. This time there will be an email notification received.
8. Login again as user-B, and set the Notification settings of this room back to "Email : Use account preference".
9. Logout user-B, and have any user send another message @mentioning user-B. An email notification will still be received.

It appears that user-B has to do this for every new room they get added to. Otherwise, user-B does not get those offline email notifications.

### Expected behavior:

Users just added to rooms should receive offline email notifications according to the default room notification settings which is: "Use account preference". Which in turn defaults to: "Every Mention/DM"

### Actual behavior:

Users don't seem to follow the default room offline email notification settings. And has to be changed-then-reverted manually before it works.

### Relevant logs:
No errors found in Rocket.Chat UI > Administration > View Logs

**Comment by pkgodara** [comment]
Intended to be solved in #7754 , I guess.

**Comment by danieljhochman** [comment]
Are you sure this is being solved by #7754 ?
Also, just to confirm, this is a problem for @ name mentions AND @all mentions? I've only tested this for @all mentions and it has the same problem as described above.

**Comment by pkgodara** [comment]
@iansrx can you reproduce it now on latest code, check if its resolved?

**Comment by danieljhochman** [comment]
I tried this on demo.rc which is running the latest release candidate and it still doesn't work when I do @all in the room, no one (with the default email settings) get an email...
