### ISSUE TITLE
CORS broken: OPTIONS requests returns 500 Internal Server Error 

### ISSUE THREAD

**Issue by tuananhhedspibk** [RocketChat/Rocket.Chat#7915]
Rocket.Chat version: 0.58.0

Anyway, I am trying to make an API call from the browser. It sends an OPTIONS request before POST to /api/logon to check CORS. The thing is, I am getting 500 Internal Server Error on this OPTIONS request, which is rendering Rocket Chat impossible to access from the browser.

**Comment by rodrigok** [comment]
This is an option in the library we are using (restivus) and it's disabled. 
We can create an option to enable it on admin panel.

**Comment by tuananhhedspibk** [comment]
![screenshot from 2017-08-30 13-49-09](https://user-images.githubusercontent.com/15076665/29858946-04dc11bc-8d8a-11e7-9f2d-5ddb6edb8b6f.png)
I set "Enable CORS" in General Option tab of admin account, but still getting 500 errors
I use Docker compose to run RocketChat

**Comment by ramdesh** [comment]
Hello, is there any further feedback on this? I am also receiving a 500 Internal Server Error when hitting the REST API through a browser as it sends the OPTIONS request first.

**Comment by huynhquocmy** [comment]
Hi @ramdesh, Have you solve your problem ? I got the same here.

**Comment by ramdesh** [comment]
@huynhquocmy, no - it seems it requires a code change on the server itself. I overcame this problem by implementing a node.js based middleware that routes requests from the UI to the chat server.

**Comment by huynhquocmy** [comment]
Thanks @ramdesh , I solved problem already.
```
I workaround by changed RocketChat.API.v1 = new API({
version: 'v1',
useDefaultAuth: true,
prettyJson: true,
enableCors: true,
auth: getUserAuth()
});

RocketChat.API.default = new API({
useDefaultAuth: true,
prettyJson: true,
enableCors: true,
auth: getUserAuth()
});

manually set enableCors: true from the file

packages\rocketchat-api\server\api.js
```
