### ISSUE TITLE
[Feature] Use more general calendar system for better localization

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7916]
Hey guys,
recently I saw [material-ui date-picker](http://www.material-ui.com/#/components/date-picker) that use ECMAScript Internationalization API (like [this polyfill](https://github.com/andyearnshaw/Intl.js)) for support more calendar system and localization.
I think it's a good Idea to use same thing as a new approach here, so RC can support more calendar system and better localization.
Now It's need to fork RC for any language with non-gregorian calendar.

What is your idea?

**Comment by madguy02** [comment]
@Sing-Li

**Comment by mnlbox** [comment]
@karlprieb , @sampaiodiego , @gdelavald, @ggazzo, @Sing-Li Guys are you any idea about this:

**Comment by mnlbox** [comment]
Any news about this?

**Comment by sampaiodiego** [comment]
@mnlbox we don't have any news about this currently. I'm not sure as well how this affects the back end. Does MongoDB need to support this as well?

**Comment by marceloschmidt** [comment]
If you mean localization of the Gregorian calendar, that's already built into Rocket.Chat. Reopen if you actually meant other calendar systems, please? Thanks.
