### ISSUE TITLE
[BUG] [Redesign] Misalign message textbox placeholder on Firefox 55

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7920]
I see message textbox placeholder like below in new design (in Firefox 55 placeholder text not vertically align to middle):
![firefox](https://user-images.githubusercontent.com/25859075/29749884-24841c1c-8b4b-11e7-868d-fbd3e3d00ae8.png)

But it's correct in chromium 60.0.3112.78 (Developer Build) like below:
![chromium](https://user-images.githubusercontent.com/25859075/29749894-3b552af8-8b4b-11e7-8cdf-f0705cfe2a83.png)

I used Rocket.Chat Version: 0.59.0-develop

**Comment by ggazzo** [comment]
hey @mnlbox can check again? here seems fine
![image](https://user-images.githubusercontent.com/5263975/29824609-5a99c51e-8ca8-11e7-8590-dee7c2872d63.png)

**Comment by mnlbox** [comment]
@ggazzo It's still buggy for me
![7920](https://user-images.githubusercontent.com/25859075/29825764-9a4790c8-8cea-11e7-8b48-a9a259e215a7.png)

**Comment by MartinSchoeler** [comment]
@mnlbox @ggazzo this bug is happening on the windows operating system

**Comment by MartinSchoeler** [comment]
Closing this one in favor of #7903

**Comment by mnlbox** [comment]
@MartinSchoeler I'm using Linux OS.
We can continue about this in #7903
