### ISSUE TITLE
Google vision explanation

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7926]
It's not clear from the UI that you need to use google cloud storage to enable the 'tags via Google vision' feature.
I only know by looking at the code here https://github.com/RocketChat/Rocket.Chat/pull/6301/files#diff-3612b53428e12d64cfde6a45db4f7606R7

Unless you're planning on enabling this for all upload types some kind of explanation is needed IMO.

**Comment by dstepp** [comment]
Agreed with @lucasvanhalst . I just set up an S3 bucket and tried to enable Google Vision and it didn't work. Need to update the documentation.

**Comment by anushasingh** [comment]
Can I take up this issue?
