### ISSUE TITLE
Cleaning MongoDB

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#7928]
Hey guys,

I've been wondering if there is a solution to clean up the database eg. Deleting all data older than x days. If not is it on a Roadmap? Or are there any other supported solutions available? 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
