### ISSUE TITLE
Home page top menu HOSTING title is set to "Download"

### ISSUE THREAD

**Issue by andersonfoscarini** [RocketChat/Rocket.Chat#7930]
### Description:

Hi, guys. 
I was checking your website and, when hovering the mouse on the HOSTING menu, I've seen that the "title" for HOSTING is set to "Download", where I believe it should be set to "Hosting".
I believe this is easy to fix, but very important in terms of accessibility for your website.

### Steps to Reproduce:

1. Open home page https://rocket.chat
2. Hover mouse on HOSTING, on the top menu
3. See that "Download" shows up

### Expected behavior:

It should show "Hosting"

### Actual behavior:

It shows "Download"

### Relevant logs:
From inspecting the element:
<a href="/hosting" title="Download">Hosting</a>

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I think this is not relevant anymore since website relaunch.

Cheers
Thomas
