### ISSUE TITLE
REST API for login not setting proper expiry date for Meteor 

### ISSUE THREAD

**Issue by sushix2** [RocketChat/Rocket.Chat#7937]
When you call the api/v1/login API it doesn't set the loginTokenExpires in local storage properly.  So if you refresh the page, your user will be logged out

![image](https://user-images.githubusercontent.com/2138032/29784418-c34ffd1a-8bd8-11e7-88fd-fa13f47214f7.png)

**Comment by graywolf336** [comment]
Technically this isn't an issue, since the rest api tokens aren't really meant to be used for login tokens even though they do work. The tokens returned from the rest api are meant to be long term and this only effects when it is being used on the website. Working as intended.
