### ISSUE TITLE
Suggestion: Remind me

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#7946]
Hey folks,

What about a right click item on any message "Remind me" and "Remind Channel" in x time? So you could post:

"Let's meet here in 2 hours", right click -> Remind Channel -> 2 hours
and everyone would be a reminder in due time.

A "/remind" command would rock, too.

"/remind "Take bottle out of freezer" 15m"
I will remind you in 15 minutes of "Take bottle out of freezer".

This would soo much whoop the Llamas ass.

-Chris.

**Comment by localguru** [comment]
check out https://github.com/RocketChat/hubot-rocketchat

**Comment by jszaszvari** [comment]
This is easily solved by one of the hundreds of remind me scripts out there for Hubot. Does not need to be and should not be core-functionality.

**Comment by christianreiss** [comment]
Nnnnot really.

All those scripts can do a simple alarm clock, ie, "remind me in 50 minutes". Within slack you can really right click any message and hit "Remind me of this in...". After time has passed the messages repops up with an alarm.

Think of an Integration "Server XYZ down" you could right click that message, say "Remind me in 5 Minutes". In 5 Minutes this would be triggered again and peeps can check if the server was just down for reboot or something else.

There are many more examples where direct alarms to messages are useful.

"Lets meet tomorrow at 12."
"Send the email at 6, would you"
"Customer called, xyz will happen at zz"

This way is simply superior. Even only considered to typing "somebot remind me of meeting" "6 hours" in comparison to a right click / option menu.

-Chris.

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,

**Comment by phlegx** [comment]
@geekgonecrazy It would be helpful to be able to click on a message then select "remind me later" and then select the time frame when the reminder should be send. I found this very useful in slack.

**Comment by geekgonecrazy** [comment]
Absolutely, this is functionality we plan to allow Rocket.Chat apps to solve.

**Comment by timlem** [comment]
@geekgonecrazy - is this functionality available anywhere?  I've been unable to find a solution

**Comment by murtaza98** [comment]
Hello All :wave: I'm quite excited to share my new Reminder app over here. It provides a solution to most of the issues mentioned over here. Check out [this doc](https://add-reminders.gitbook.io/docs/) for more info about this app. 

Also, feel free to reach out to me on any below-mentioned channels if you wish to share any feedback or suggestions or even criticism.

Open server of Rocket.Chat: https://open.rocket.chat/direct/murtaza.patrawala
Email: murtaza98.professional@gmail.com
[LinkedIn](https://www.linkedin.com/in/murtaza-patrawala-b17419166/)
