### ISSUE TITLE
[FIX] Document README.md. Drupal repo out of date

### ISSUE THREAD

**Issue by Lawri-van-Buel** [RocketChat/Rocket.Chat#7950]
### Description:
The Readme is out of date in regards to where the drupal module's source is located. 
Also we now have a stable release of the drupal 8 module of rocket chat.

Pull request https://github.com/RocketChat/Rocket.Chat/pull/7948

**Comment by engelgabriel** [comment]
closed via https://github.com/RocketChat/Rocket.Chat/pull/7948
