### ISSUE TITLE
add support for custom config fields to webhooks

### ISSUE THREAD

**Issue by TheBelgarion** [RocketChat/Rocket.Chat#7959]
I would love to separate the code of a webhook snippet from any configuration variables.

e.g. for an outgoing Hook which calls JIRA to gather some information, i need some user credentials, but I rather not add them to my snippet / code as I do version control on most of my code.

It would be nice to have a Field, where you can add a configuration as JSON which is then passed to the call of the script class.

To don't break the design, it might be best to just add the "config"  to the request parameter which is sent to process_incoming_request(request) so you can access 'request.config.user' for a predefined username.

**Comment by Sing-Li** [comment]
We are no longer expanding the capabilities of standlone webhooks.  Please refer to Apps development for further information.   This should be readily achievable via our Apps framework.
