### ISSUE TITLE
Message tags

### ISSUE THREAD

**Issue by pshute** [RocketChat/Rocket.Chat#7967]
Flowdock lets users add tags to messages, eg #printers. Clicking on a tag in a message displays all messages with matching tags on the right hand side. 

I think this would be a useful alternative to creating a lot of narrow topic channels, as people could post to more generalised channels, but add tags that function to some extent as sub channels.

**Comment by pshute** [comment]
This is probably a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2873

**Comment by mnlbox** [comment]
+1
It can be a very useful feature. Many messenger like Telegram also have a same feature called `hashtag`

**Comment by idanielblake** [comment]
+1

**Comment by andrewzamkovenko** [comment]
+1!

**Comment by AlxndrPsclt** [comment]
+1 Business chats a tools to organize information, this would be super useful (seems expected?).

**Comment by 42robots** [comment]
Is there any update on this cool feature ? Best

**Comment by asadi110** [comment]
+1

**Comment by krausdavid** [comment]
+1

**Comment by nopynoop** [comment]
+1

**Comment by marceloschmidt** [comment]
This is somewhat covered by our future implementation of threads. Thanks for the suggestion.

**Comment by alexander-potemkin** [comment]
From now, when threads are there, I would call it threads organizer and still vote for it hardly - in my particular example, I need to mark daily status report with #report hashtag, to make sure I can quickly see them, instead of checking the whole events log, which is called main chat window.
