### ISSUE TITLE
esc key not working in firefox

### ISSUE THREAD

**Issue by bibimarujp** [RocketChat/Rocket.Chat#7968]
in editing message, esc key not working in firefox. In chrome it works.
firefox:
![firefox](https://user-images.githubusercontent.com/24547736/29854304-048b4408-8d80-11e7-92f5-6cf3f1dbb645.gif)

chrome:
![chrome](https://user-images.githubusercontent.com/24547736/29854316-151dca66-8d80-11e7-8c62-faf5e258b332.gif)

Version of Rocket.Chat Server: demo
Browser: firefox 55.0.2

**Comment by johnvoloski** [comment]
@bibimarujp Hi. Could you tell which operational system you used? I tried to simulate the problem but i did not succeed.

**Comment by bibimarujp** [comment]
Add-ons were involved. I ran correctly if I disabled add-ons.
@johnvoloski thanks for I tried to simulate.
