### ISSUE TITLE
OTR e-mail notifications: remove message payload

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#7974]
When absent and I receive E-Mail messages, the message I receive contains encrypted text. 
![bildschirmfoto_2017-08-30_11-05-28](https://user-images.githubusercontent.com/485723/29864492-33d78152-8d73-11e7-9937-9fe7568db7bc.png)

Instead, replace the message with a sentence "Encrypted Message". Like the desktop notifications already do.

**Comment by jdsatava127** [comment]
We are also running into this issue on version 6.4.4. It is fairly easy to recreate with these steps.

1. Have both users online
2. Initiate OTR
3. Have 1 user switch their status to offline and close their RC client
4. User still online continues to send OTR messages. These will show up as emails like the screenshot above.

Switching status from online should close any active OTR sessions so these emails don't appear.
