### ISSUE TITLE
Rocket.Chat ghost mode on view received chats

### ISSUE THREAD

**Issue by MahdiPishguy** [RocketChat/Rocket.Chat#7975]
is any feature disable notify other user in room/channels/group when we get message? for example user A after send message for me, rocket.chat dont notify user to know i read that

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
