### ISSUE TITLE
Email Notifications not showing image or file info

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7976]
RC Version 0.58.2

If a user uploads an image or file it triggers an email alert (according to the user's notification settings). The email is blank. 

Either, no email should send OR the email should at the very least contain the test "Uploaded filename.png". Better yet, it should display the image or link to file if it's not an image.

**Comment by sampaiodiego** [comment]
hi @danieljhochman 

as you can see on PR, I'm not adding an `<img/>` on the email because uploaded files are protected by default, so it would show a broken image if the email was not opened on the same browser the user has logged in on the rocket.chat instance.
