### ISSUE TITLE
Outgoing webhook delete message

### ISSUE THREAD

**Issue by Eloo** [RocketChat/Rocket.Chat#7977]
Hi, 
i'm trying to create a scripted fileupload webhook which is deleting the posted FileMessage by using the fileid from the request and a Meteor call. But it seems that i can't access Meteor in the script. 
I guess Meteor is not accessible in the scripts by purpose but so how can i delete a delete using webhooks?

The use case is that i want to only publish files after this outgoing webhook was proceeded.
Any suggestions?

Thanks

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
