### ISSUE TITLE
How Screen Sharing in 0.59.0-rc.2 - Linux Client App

### ISSUE THREAD

**Issue by danielo926** [RocketChat/Rocket.Chat#7979]
How i can screen sharing in Linux Client App?

I must install extension before screen sharing

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by gdelavald** [comment]
@danielo926 if the Linux App screen sharing is not working, please report as a bug to [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron/issues) so we can track it properly.
