### ISSUE TITLE
Sometimes Icons don't render on firefox on ubuntu

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#7980]
![screenshot from 2017-08-30 10-52-20](https://user-images.githubusercontent.com/20868078/29876403-0d86ab40-8d73-11e7-9c8c-c8e992820434.png)

**Comment by karlprieb** [comment]
On which Firefox version do tested? Can you be a little more descriptive?

**Comment by MartinSchoeler** [comment]
Tested on a firefox 54.0 (64-bit) (firefox for ubuntu canonical - 1.0) on a ubuntu 16.04 LTS

**Comment by Lemmmy** [comment]
Having this issue on firefox 55, nixos and archlinux. Works fine on firefox 57.

**Comment by cyclops24** [comment]
Guys I see same issue on Firefox 55.
Why new UI design have many issue on Firefox? :thinking:

**Comment by mfueser** [comment]
We have this issue with Firefox 54... Is there an option to use the old design?

**Comment by Lemmmy** [comment]
I don't think the new design is released in a stable version yet - just revert back to a stable version?

**Comment by cyclops24** [comment]
@karlprieb It's still happens sometimes. :cry:

**Comment by cyclops24** [comment]
Part of #8494

**Comment by agulov** [comment]
Face this uissue using Firefox 52 esr on Windows. Rocket 0.59 release.

**Comment by magicbelette** [comment]
Rocket.Chat version 0.52.9
Firefox 52.3

Pretty anoying bug as Firefox 52 is an ESR.
Any lead on how to help on this ?

Cheers

**Comment by magicbelette** [comment]
No luck here...

I tried something simple with svg to be sure (based on RocketChat 0.59.3 simplified sources, see below). It works like a charm with FF 52 et Chrome. I also tried the full code of RocketChat 0.59.3 but without css and I still don't see icons.

Ideas ?

```
<!DOCTYPE html>
<html>
<head/>
<body>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none">
<symbol id="icon-pin" viewBox="0 0 20 20">
<g stroke="currentColor" stroke-width="1.5" fill="none" fill-rule="evenodd"><path d="M13.497 14.719l3.119 3.12" stroke-linecap="square"></path><path d="M2.48 9.725a1.588 1.588 0 0 1-.004-2.239l4.627-4.627a1.583 1.583 0 0 1 2.24.004l-.37-.37a1.59 1.59 0 0 1-.003 2.243l-.124.124 3.743 3.744s2.496-1.247 4.992 1.248l-8.112 8.111c-2.495-2.495-1.248-4.991-1.248-4.991L4.478 9.228l-.125.125c-.62.62-1.624.621-2.244.002l.371.37z"></path></g>
</symbol>

<div class="tab-button" title="Pin">
        <button aria-label="Pin">
                <svg class="rc-icon tab-button-icon tab-button-icon--pin" aria-hidden="true">
                        <use xlink:href="#icon-pin"></use>
                </svg>
        </button>
</div>
</body>

**Comment by Gummikavalier** [comment]
I've been testing some things too but to no avail. To me it looks like all elements that are not visible on the screen are base64 encoded SVG icons.

All of those missing icons have changed after 0.58 I think, and maybe they have some property that bugs with Firefox ESR.

**Comment by agulov** [comment]
It seems to work if we use absolute url for href in <use> tag, for example
`<use href="https://rebelraven.rocket.chat/channel/general#icon-bell"></use>`
instead of
`<use href="#icon-bell"></use>`

Please, rocket.chat guys, fix it!

**Comment by Lemmmy** [comment]
@agulov Could it be a HTTPS issue? Try `href="/channel/general#icon-bell"` and `href="http://rebelraven.rocket.chat/channel/general#icon-bell"` (http instead of https)

**Comment by agulov** [comment]
@Lemmmy 
`href="/channel/general#icon-bell"` works, i can see icon
`href="http://rebelraven.rocket.chat/channel/general#icon-bell"` does not work

**Comment by exagon** [comment]
Sorry, I can't understand how I can resolve this issue on my installation ( 0.59.3 ), someone can help me ?
thanks

**Comment by kimgb** [comment]
Minimally tested hack for anyone that needs a temporary fix. JQuery/JavaScript is not my strong point, improvements appreciated. This goes in Administration -> Layout -> Custom Scripts.

This makes use of the absolute URL workaround pointed out by @agulov above. It appears to fix the icon problems in previous versions of Firefox without breaking Chromium or Firefox 59 - I haven't tested any other browsers. Use with caution and don't forget to take it out after a proper fix has been released.  

    // Hack to get SVG icons working on Firefox 52 ESR and other pre-59 versions
    $(document).ready(function(){
      $("svg > use").map(function(){ 
        var svg_string = $(this)[0].href;
    
        if (svg_string.baseVal.startsWith("#")){
          svg_string.baseVal = window.location.href + svgs.baseVal; 
          svg_string.animVal = window.location.href + svgs.animVal;
        }
      });
    })

**Comment by fnollet** [comment]
Thanks for the fix! Works like a charm!

**Comment by mhenninghaus77** [comment]
Yes, this Workaround works at my instance too, thanks a lot!

**Comment by kimgb** [comment]
This test `if (!added || (added.localName !== 'use' && !added.children.length))` was giving me a ton of "undefined has no properties" JavaScript errors, and in this case I don't think the children length check is needed. You should be OK to replace it with `if (!added || added.localName !== 'use')` if the errors bother you or are causing actual trouble.

**Comment by amateo** [comment]
Neither of both patches supplied by @kimgb works for me. Tested with rocket.chat 0.59.4 and firefox ESR 0.52.2
