### ISSUE TITLE
Room/DM Panel Blank after removing Admin Priveleges

### ISSUE THREAD

**Issue by tiredofit** [RocketChat/Rocket.Chat#7982]
### Description:

We temporarily provided Admin level access to someone in our organization and revoked the priveleges.
Now they are reporting that the Channel/Group/DM Listing on the left hand side is entirely blank.
Upon restoring Admin priveleges the left panel reappears.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Docker/Alpine
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Mongo
* Node Version: 4.8.4

### Steps to Reproduce:

1. Grant Admin priveleges
2. Revoke Admin priveleges

### Expected behavior:

To not remove the left panel

### Actual behavior:

Removes the left panel of Chats/DMs/Groups

**Comment by ggazzo** [comment]
I can't reproduce anymore
