### ISSUE TITLE
Unable to customize fetched model data (to show only certain rooms)

### ISSUE THREAD

**Issue by lifeofcoding** [RocketChat/Rocket.Chat#7987]
I just need a little direction, been wondering this code, trying to customize what rooms are fetched based on a hash value in the url. I can do this fine via frontend, but need to prevent the data from ever being set on RocketChat.models.Rooms on the frontend, monkey patching the find method in the models on the server side doesn't seem to do it, the room I am filtering doesn't show in the data in the console log, but still shows up on the room lists, (and yes I am also doing this on subscriptions model)

Any tips, advice, would be appreciated!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
