### ISSUE TITLE
Bot on bot mayhem with enter message responses

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#7990]
https://github.com/RocketChat/Rocket.Chat/blob/752aef30b2dee3a4d970ccdf40d180589872ce02/packages/rocketchat-lib/lib/MessageTypes.js#L65-L73

I've got a couple of bots that send a welcome message to new users. A problem occurs now and then when they overlap and start welcoming each other, especially when they have a default catch all response if they don't understand the command. e.g.

```
@foobot has joined the room
@barbot Welcome to the room @foobot!
@foobot I'm sorry, I didn't understand that.
@barbot I'm sorry, I didn't understand that.
@foobot I'm sorry, I didn't understand that.
@barbot I'm sorry, I didn't understand that.
... // goes on for a thousand years
```

I can get around this by doing a user request through the API to find out if the incoming user is a bot, but that's a fairly expensive process.

Would it make sense just to include some more meta in the 'uj' message event. Event just an `isBot` boolean would be enough, but it might be nice to have a `roles` array for more varied add-ons to do other stuff, like welcome users, but not admins.

**Comment by twardnw** [comment]
This would be very helpful to us too

**Comment by timkinnane** [comment]
I only just discovered, within the adapter there's a `.customMessage` method, which allows you to set a `bot` bool property. Not super helpful unless the instances where bot's are responding to each other are known specific sends, which you could replace with the customMessage and let the other bot check for the property. That's a way to solve it with existing packages, but I'm mostly saying this for future me to have some context when I come back to make a PR for this.

**Comment by twardnw** [comment]
That helps for bots for sure, it would also be useful to have core identify messages that come from webhook/integrations (a larger issue for us)

**Comment by timkinnane** [comment]
@twardnw I'm closing and moving this issue to the hubot adapter. Can you please open a new issue requesting support for a new property on the Rocket.Chat message object that would be set true for any message originating from webhooks/integrations. I'd do it but I don't use that feature so I'm not sure what would specifically help you.

**Comment by timkinnane** [comment]
@twardnw I just found a discussion on issue #7718 showing I was wrong about the bot param. Any message created by a bot or webhook integration should have the `bot` property, which is an object, not a boolean as I stated. The bot object should include an `i` property with the ID of the integration that called the API endpoint. Hopefully that can help your situation and if it doesn't, at least you can make a new issue to specifically address why your integrations aren't being identified.
