### ISSUE TITLE
[BUG] [Redesign] Side menu close button have small buggy overlap on user info tab

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7992]
It's a little misalign on user info tab. See this:
![close overlap](https://user-images.githubusercontent.com/25859075/29918660-76880bdc-8e5b-11e7-9b56-5dfc1f98a96c.png)

**Comment by aditya19496** [comment]
I will look into it.

**Comment by ggazzo** [comment]
this is on purpose

**Comment by cyclops24** [comment]
@ggazzo It's not fixed yet.
Please reopen this until working PR.

**/CC:** @karlprieb , @rodrigok , @MartinSchoeler
