### ISSUE TITLE
[Question] Where is "rocket.cat" avatar file?

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7993]
Hi guys,
I can't find `rocket.cat` avatar (below image) in `/public` or `/public/images/logo` folders.
Where is it and where is other default images or media?
![rocketcat](https://user-images.githubusercontent.com/25859075/29918905-88dcc646-8e5c-11e7-81ec-242bc58dce1b.jpg)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by mnlbox** [comment]
@MartinSchoeler I think it's a missed topic in docs and needs small answer :thinking:

**Comment by mnlbox** [comment]
@rodrigok, @ggazzo

**Comment by ggazzo** [comment]
`private/avatars/rocketcat.png`
