### ISSUE TITLE
"Save Mobile Bandwidth" Setting cannot be disabled / Setting to disable it globally would be great.

### ISSUE THREAD

**Issue by johnyb0y** [RocketChat/Rocket.Chat#7994]
### Description:

When setting "Save Mobile Bandwidth" Setting to "No" in your Profile Setting page, clicking "Save" at the end of the page, and after that revisiting the page, it's back to "Yes".

Also:
"Save Mobile Bandwidth" seems to be **enabled by default**? I think for most setup's it would be better to be disabled by default. 
Also, it would be great, if you could disable this globally for all users.

### Server Setup Information:

* Version of Rocket.Chat Server: 058.1
* Operating System: Debian 9.1 Stretch
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: Yes, 1 ReplicaSet
* Node Version: 4.8.2

### Steps to Reproduce:

1. Go to your "Profile" Settings page. Disable "Save Mobile Bandwidth".
2) Press "Save" and revisit the Page -> It's back to Enabled.

### Expected behavior:

Setting it to Disabled should disable it.

### Actual behavior:

Setting it to Disabled does not change anything, and it's back to Enabled upon revisiting the Profile Settings page.

Any ideas?
Thanks for your answers!

**Comment by Sing-Li** [comment]
Fixed already.  Please re-open if there is still problem.
