### ISSUE TITLE
[Feature] Ability to exclude some emoji from admin panel

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7995]
Hi guys.
I think it's very useful if we can exclude some emoji from admin panel for all users.
Now we can do this only with fork and hard code changes in emoji package.

It can be implement with two option in admin panel:
1. Exclude one pack at all (for example: `Food & Drink`)
2. Or exclude just some emoji from each pack (for example: `:lemon:` from `Food & Drink` and `:penguin:` from `Animals & Nature` packs)

What's you idea?

**Comment by marceloschmidt** [comment]
Users could still use the unicode for the emoji. We don't see this as a good feature. Thanks for suggesting.

**Comment by marceloschmidt** [comment]
You do have a words blacklist, so you may block the words that represent an emoji, or even the unicode.
