### ISSUE TITLE
Loading image and site title loads slowly (ranges between 1 to 5 seconds)

### ISSUE THREAD

**Issue by jonathanhartman** [RocketChat/Rocket.Chat#800]
As I understand it, this is a limitation of the templating framework being used. Nothing can be done on the server side and Rocket.Chat changes the title as quickly as possible when the page loads. Is it possible to populate the header image and site title a little quicker? A 5 second delay, which happens from time to time, is a bit problematic.

**Comment by engelgabriel** [comment]
i'll investigate.

**Comment by engelgabriel** [comment]
Maybe http://pem-musing.blogspot.de/2014/12/the-fastest-loading-screen-for-meteor.html
