### ISSUE TITLE
LiveChat error opening new rooms

### ISSUE THREAD

**Issue by gustavo-mmh** [RocketChat/Rocket.Chat#8008]
Estou ainda em fase de testes no Rocketchat, e deu o seguinte problema, quando eu abro uma conversa 
em um computador, escolho departamento e crio um nome e email, ao falar no chat, aparece o nome do usuário recem criado abaixo da conversa para que eu responda com minha conta que é do suporte, até ai tudo bem. No entanto, ao clicar na conversa para falar com o 'cliente', abre um chat antigo já fechado, e o recém aberto, fica como se tivesse uma mensagem não lida, mas não abre. o screenshot ilustra
![image](https://user-images.githubusercontent.com/31542242/29972970-4e068cfc-8f04-11e7-8a64-128534bb67fa.png)
o usuário 'teste ilha 1' foi recém criado por mim, e no meu chat aparece que esta sendo atendido pelo meu usuário 'video arte', no entanto no meu usuário video arte, quando clico na conversa abre esse outro teste já fechado.

**Comment by sampaiodiego** [comment]
Provavelmente corrigido quando migramos os usuários do livechat. Vou fechar a issue, caso ainda esteja ocorrendo com a versão atualizada, por favor, me avise que abro a issue novamente. Obrigado

-----

Probably fixed when we move livechat visitors away from regular user. Closing for now
