### ISSUE TITLE
Emojione style conflicting with bootstrap datepicker

### ISSUE THREAD

**Issue by skemb321** [RocketChat/Rocket.Chat#801]
Hi, I just want to ask if this file is used somewhere?
I just want to know because the class ` .dropdown-menu` is conflicting with bootstrap's datetimepicker and I wasn't able to find any other solution other than removing it from source. I really need your help. Thanks.

https://github.com/RocketChat/Rocket.Chat/blob/master/client/stylesheets/utils/_emojione.import.less

**Comment by marceloschmidt** [comment]
As far as I can tell from my tests, it's safe to remove `.dropdown-menu {` section from this file. I'll run a few more tests and create a PR for this if confirmed. If you can do your tests without this section, let me know. Thanks.

**Comment by skemb321** [comment]
Thanks! Will also do some test. Thanks!
