### ISSUE TITLE
Allow User to Direct Message Their Own Self

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#8015]
The ability to direct message yourself is desired as it can be a room to store random things or test formatting. This was prevented via https://github.com/RocketChat/Rocket.Chat/pull/1017

**Comment by Lemmmy** [comment]
Quote from @NickBusey on #3886:
> There is actually code preventing this from happening. I'm not sure why, and tried to remove it, unsuccessfully last year. I would still love to be able to message myself. Would be great to have an auto-syncing scratch pad on all devices.

It would be worth revisiting that. This is a feature I would like to see too.

**Comment by graywolf336** [comment]
Good find @Lemmmy, I tired to find issues referring to this but I missed that one.

**Comment by yannicklansink** [comment]
Is this already implemented?
