### ISSUE TITLE
 links in the announcement-bar should be clickable

### ISSUE THREAD

**Issue by horvan** [RocketChat/Rocket.Chat#8021]
### Description:

The links in the announcement-bar. see screenshot as well as in the group description should be clickable or at least copyable

![screenshot-drupalchat eu-2017-09-02-11-26-07](https://user-images.githubusercontent.com/5676367/29994542-177f3d86-8fd2-11e7-9994-d9c3895cb1e8.png)

**Comment by Gummikavalier** [comment]
You can put clickable link into announcement bar like this

`[Link name](https://link.to.somewhere)`

But the problem is that they are too dark with RC default layout. It would be good if you were able to choose text color somehow.

**Comment by seriouz** [comment]
The blue/purple on blue is worst case!

![image](https://user-images.githubusercontent.com/4722613/30271639-5b8545a4-96f1-11e7-93ec-ac78eb04f5c3.png)

**Comment by savikko** [comment]
As a workaround, just add to Custom CSS (you find it from Admin / Layout):

```
.announcement a{
 color: white; 
}
```

**Comment by AmShaegar13** [comment]
There is still a little problem with it: When clicking a link the dialog pops up which is empty. Also, the popup does not support links. Is it intended to use links or generallyl markdown in announcements?

**Comment by supra08** [comment]
@ggazzo, can I take this up?
