### ISSUE TITLE
Highlight word mentions don't appear in mentions tab

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#8022]
Only @mentions appear in the mentions tab. I think highlight words and username mentions should appear in there too - unless there is reason for them not to.

Often people mention our team members indirectly without @mentioning them, but it is still hard to find these messages - we get notified for them but can't find them in the mentions tab, and have to scroll through thousands of messages of backlog on mobile, or search for them on desktop.

**Comment by viluon** [comment]
***Bump**! T'is true.

**Comment by geekgonecrazy** [comment]
I don't think this is really a bug, or feature request.  Mentions tab is for mentions only.  Highlight is meant to simply highlight so you can spot it.

**Comment by viluon** [comment]
> Often people mention our team members indirectly without @mentioning them, but it is still hard to find these messages - we get notified for them but can't find them in the mentions tab, and have to scroll through thousands of messages of backlog on mobile, or search for them on desktop.

@geekgonecrazy This issue has not been resolved.

**Comment by geekgonecrazy** [comment]
As said above the mentions are for mentions only.  Highlights do not belong there.

**Comment by viluon** [comment]
@geekgonecrazy you seem to be ignoring a fundamental UX flaw in RocketChat:
> have to scroll through thousands of messages of backlog on mobile, or search for them on desktop.

**Comment by geekgonecrazy** [comment]
@viluon maybe a flaw.  But its also off topic for this issue.

We are looking at group mentions and other things of that nature.  As well as improving mentions overall.  But no plans to include highlights.  Because highlights are not mentions.

If you would like to open another issue regarding the UX flaw please feel free to.  But regarding the topic of conversation here I have addressed it.
