### ISSUE TITLE
"Mentions" email setting send emails even when not mentioned

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#8027]
Reproduced in 0.58.2 and 0.59.0-rc.3

Steps to reproduce:
1. Open Room
2. Set email notifications to "All Messages"
3. Get emails for new messages
4. Change setting to "Mentions"
5. You will still get emails for "All Messages" with the subject as "You have been mentioned by..." even though you were not mentioned.

Note: This may simply be a bug with the "Mentions" setting. Things seems to work fine when "Use account preference" is selected.

**Comment by pkgodara** [comment]
#7754 might fix. This issue has been lately. Looking desparately for fix.

**Comment by aspiers** [comment]
I just started experiencing this with 0.69.2, but weirdly so far only for one channel of many I'm in.
