### ISSUE TITLE
Two instance + CAS: sometimes can't login with error 'no matching login attempt found'

### ISSUE THREAD

**Issue by idanielblake** [RocketChat/Rocket.Chat#8032]
Hi!. We have two instance behind nginx according to the wiki. Users login with CAS. Sometimes they get this error on login. by Clicking multiple times on CAS button they can Log in at last. I think this issue is related to "two instances" (nginx mabye?). We tested with one instance for three days and everything was fine. Can you help?

Centos 7
RC 0.58.2 OpLog & https enabled 
Instances 2
CAS 5.1.3
MongoDB 3.4
Node 4.5
no errors on CAS logs and RC

Thanks

**Comment by MartinSchoeler** [comment]
Not enough information provided. Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by idanielblake** [comment]
more info provided.

**Comment by j2ro** [comment]
I saw a very similar issue the other day with an OAUTH Rocket.Chat integration (although it was with a single instance of Rocket.Chat).

**Comment by idanielblake** [comment]
Using ip_hash method for load balancing seems solve the problem partially.
[https://www.nginx.com/blog/choosing-nginx-plus-load-balancing-techniques/](url)

**Comment by AmShaegar13** [comment]
This is a big issue for us as well. We are currently setting up RocketChat company wide. Multiple instances on distributed hosts + CAS are absolutely mandatory. Today, we recognized that CAS wont work with multiple instances as it is currently implemented.

If I understand the code correctly, [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-cas/server/cas_server.js#L51) where info of the signed in user is stored with a one-time token. Bad thing is: `_casCredentialTokens` is just a local object, actually. This is the reason why CAS login works sometimes and with a single instances only but fails with multiple instances. You have to be routed to the same server twice in a row to login successfully.

This said, I would like to fix that. Sad thing is, I have never contributed to RocketChat before. I will try to setup everything locally today and see if I can do something about it.

Here is what I plan to do after reading through existing code:
1. Create a new database model `CredentialTokens`
2. Store tokens in MongoDB using this model
3. Cleanup used and outdated tokens from the databse after let's say 60 seconds.

How do you think about this?

**Comment by AmShaegar13** [comment]
@MartinSchoeler how can we drive this thing forward? The label indicates, that there is more info necessary. Is that still true?

I built my branch for our internal company setup and use CAS auth across 12 instances now without and problems. Can we get this fix reviewed somehow?

We don't want to run a custom patched version in production, as this complicates updates a lot.
