### ISSUE TITLE
[mention-all] permission does not work for roles other than "user"

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#8033]
RC Version: 
Steps to reproduce:
1. Remove [mention-all] permission from "user" role
2. Enable  [mention-all] permission for a different role such as "moderator" or "leader"
3. Moderators or Leaders still cannot @all mention. They get a rocket.cat message that "Notify all in this room is not allowed"

**Comment by rebeld** [comment]
We just encountered this, our community is growing to the point where unfettered access to (at)all is becoming a nuisance so we tried to disable it and lost the ability altogether. Any idea of a milestone for a fix for this?
