### ISSUE TITLE
Jira plugin integration

### ISSUE THREAD

**Issue by RenanJochem98** [RocketChat/Rocket.Chat#8034]
### Description:

A simple plugin, where Rochet Chat show new Jira issues, short descriptions

**Comment by TomaszDom** [comment]
Just create a new incoming webhook, don't forget to enable it (very top of the webhook form), configure it, "Enable Script" and paste the contents of this script into the text box:

https://raw.githubusercontent.com/malko/rocketchat-jira-hook/master/jira-rocketchat-hook.js

Then create a webhook as admin in Jira and paste the newly created incoming webhook URL from rocketchat, configure rules in JIRA (for which actions should the webhook be fired, etc.).

It works beautifully.

**Comment by TomaszDom** [comment]
I'm not saying an integrated JIRA plugin shouldn't be created to make this process easier, but in the meantime this works fine.
