### ISSUE TITLE
Rocket.Chat doesn't send push messages if connection to mongodb was lost or primary election occurs

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#8038]
### Description:

If a rocket.chat instance lose the connection to its database and restore it, all works fine except push messages are not send anymore until a restart of the instance. Push messages are sent via push gateway.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: YES
* Node Version: shipped in docker image

### Steps to Reproduce:

1. Start your MongoDB Docker Container
2. Start your Rocket.Chat Docker Container
3. Send some test messages -> push is working
4. Stop mongodb docker container, wait 10 sec
5. start mongodb docker container
6. Wait for reconnecting of the rc docker container
7. Send some test messages -> no push messages anymore

### Expected behavior:

Push messages should be send if a docker rocket.chat containers fail-over or reconnect to the database.

### Actual behavior:

At a fail over or a reconnection to the database no push messages are sent anymore until a complete restart of the RC docker container is done.

### Relevant logs:

No relevant log messages (just seeing that there are no log entries after reconnection)

**Comment by dmoldovan123** [comment]
+1

**Comment by litewhatever** [comment]
+1

**Comment by geekgonecrazy** [comment]
Also likely related to this: https://github.com/meteor/meteor/issues/8598

**Comment by TheReal1604** [comment]
@geekgonecrazy some news to this issue.

We had a neutron cluster restart where the rocket-chat containers lost their network connectivity for several seconds. The normal "push messages are not send" happend and after some time the cpu load of the node processes inside the containers is rising heavily.

This could be seen on this graph:

![image](https://user-images.githubusercontent.com/5877910/36969211-2b783418-2065-11e8-9c94-f7eb5af6b9cd.png)

I couldnt find any "RC-Logs" that are in connection to the rising cpu load. Also, it seems that there is also a memory leak caused by this. (Memory consumption was heavily rising after the short connection loss)

**Comment by geekgonecrazy** [comment]
Did it ever drop?  If not sounds like we are holding on to variables not being used after the disconnect 🤔

**Comment by TheReal1604** [comment]
@geekgonecrazy it just drops after a complete container restart.

**Comment by geekgonecrazy** [comment]
Ok so something is definitely up here.  We should look into it closer. At least it reconnects.. but if it reconnects wastes memory and push notifications don't work... Its not super useful for it to auto-recover the connection to mongo

**Comment by geekgonecrazy** [comment]
Ran across this a few times now.  Push notifications stop going out.  Then reboot instance and suddenly they all go out.  Accompanying this you can see mongo errors where at one point even briefly it suffered an interrupt in connection.

**Comment by sampaiodiego** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/11667
