### ISSUE TITLE
Capability for the server to send a message to only one user

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#804]
In case the title doesn't make sense, it would be useful to have a method to display a message to the user who does a command or some other action where it only shows up for them.

My use case for this is a user enters the following command `/join #channelthatdoesntexist`. The channel doesn't exist, so we send the user a message in the current channel they're viewing saying "Hey, `#channelthatdoesntexist` channel doesn't exist. Try again but verify your spelling.".

**Comment by rodrigok** [comment]
Hey @graywolf336 you can do this as soon as this PR be merged https://github.com/RocketChat/Rocket.Chat/pull/805

**Comment by graywolf336** [comment]
@rodrigok awesome!! :smile:

**Comment by marceloschmidt** [comment]
I don't really understand why you'd need a notification for this. Isn't a toastr good enough for telling the user that he's typed a wrong room name?

**Comment by graywolf336** [comment]
Yes it could, but I think contextual wise since they typed it inside the chat box a user would expect to receive some form of output in the area they inputted the command.

**Comment by graywolf336** [comment]
Now that we've got this ability, can this be closed? Or was there something else that needed to be worked on/changed about it?

**Comment by rodrigok** [comment]
For more needs we can open more specific issues.
