### ISSUE TITLE
In-channel search results do not give you the option to scroll to the original message

### ISSUE THREAD

**Issue by skyanth** [RocketChat/Rocket.Chat#8043]
### Description:

Since updating to 0.59.0, when searching for in-channel text the results are missing the 'scroll to original message' icon.

I note that there is a "permalink" button, but when you click it it only says "Copied" but doesn't actually copy anything. That's a different issue (I notice #8030 will be fixed for the next release), but I'm just saying it here to show there's no workaround either.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0
* Operating System: Ubuntu

### Steps to Reproduce:

1. Search for some text in a channel
2. Click the three dots next to the emoji reaction icon for any search result
3. Notice that there is no option for scrolling to the message.

### Expected behavior:

Earlier versions had this scroll-to-original-message functionality and it was awesome for reading the message in context.

**Comment by Eloo** [comment]
can confirm this in 0.59.0-rc3

**Comment by gdelavald** [comment]
Fixed by #7988
