### ISSUE TITLE
When 'message' textbox is focused, Ctrl+Tab doesn't work

### ISSUE THREAD

**Issue by jniederm** [RocketChat/Rocket.Chat#8052]
### Description:
It seems that 'message' input box (where message is being composed) is silently swallowing Ctrl+Tab keypress event which prevents switching browser tabs. 

### Server Setup Information:

version: 0.58.0, 9a9f1580b47c5a1331c08f0415eef7906338d478

### Steps to Reproduce:

1. Open multiple tabs in browser, rocket chat instance being on of them
2. Open come contact
3. Focus message input box
4. Press Ctrl+Tab

### Expected behavior:
Other tab is shown (tab were switched)

### Actual behavior:
No response to Ctrl+Tab key events

**Comment by oguhpereira** [comment]
@jniederm @MartinSchoeler This problem is not occurring in version `2.1` using chrome.

- OS: Linux Ubuntu
- Browser: Chrome
