### ISSUE TITLE
Changes made to Rocket.Chat are not included after building

### ISSUE THREAD

**Issue by johnyb0y** [RocketChat/Rocket.Chat#8056]
I'm new to developing with Meteor. I intend to create a PR for a problem i noticed in Rocket.Chat: https://github.com/RocketChat/Rocket.Chat/issues/8000

I git cloned the Rocket.Chat dev branch and made a change to a certain file: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-oembed/client/oembedImageWidget.html

After that i ran the build-script successfully. My build started, but the change is not included. Using the Chrome Dev Tools to inspect the change, i still see the original unchanged code.

I know it's a rather generic question and i'm sure the solution is kind of stupid, but any idea why ?

Thank you!

**Comment by johnyb0y** [comment]
Ok, just read about the Package managment system. I'm on the right track.

**Comment by MartinSchoeler** [comment]
@johnyb0y for development you should be starting the cloned repo with the command `meteor npm start` and it will detect for any changes in the code and restart properly. Also please refrain from posting this kind of question on github, as we want to keep it mainly for bugs and feature requests, if you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat) .Thanks!
