### ISSUE TITLE
Some js errors

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat#8058]
Using the firefox  console log i couldn't raise a ticket about the issues i found, hope it helps

![](https://i.imgur.com/AmDsxBH.jpg)

**Comment by gdelavald** [comment]
Thanks for reporting this issue, but we couldn't reproduce this, if you have any other information that will help us debug please reopen the issue.

**Comment by JohnnyKing94** [comment]
Did you use firefox console?
Did you use the latest dev version of Rocket.Chat?
