### ISSUE TITLE
Don't Make Hashtags Which Aren't Channels Clickable

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#807]
Others might disagree with this, but I feel that if a word after a hashtag isn't a channel that exists then it shouldn't be clickable. This way people can use hashtags without others thinking they're talking about a channel if it doesn't exist.

**Comment by Morgul** [comment]
I agree. It confused me the other day to see rocketbot display a github comment talking about `issue #45`, with the `#45` clickable, but not taking me to the github issue.
