### ISSUE TITLE
Access Through Firewall

### ISSUE THREAD

**Issue by zoldy2** [RocketChat/Rocket.Chat#8071]
I setup a rocketchat server and I am able to access it on my local network using http://servername:3000 ...   like I do with many other web apps I want to access outside the network I ported this through our firewall using port 3000 on one of our static IP addresses.

I have looked this setup over and over and the only conclusion I can come to is more ports have to be opened up.    is port 3000 the only port that should be required or are there more.    My connection just times out

**Comment by localguru** [comment]
Yes it's just the port you define via `PORT=30000`. I would recommend nginx as reverse proxy and use SSL.

**Comment by Lawri-van-Buel** [comment]
Also for stuff like the realtime api you need to support websockets.
