### ISSUE TITLE
Livechat Title Background Color options missing from Administration Settings

### ISSUE THREAD

**Issue by andrelecomte** [RocketChat/Rocket.Chat#8072]
### Description:

Unable to update the Livechat Title Background Color from within the Administration Settings menu. The Livechat Title Background Color drop-down box is missing all options.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

--

### Steps to Reproduce:

1. Deploy Rocket.Chat Server: 0.58.2 on Linux using snap
2. Open Livechat settings from the Administration menu
3. Try to set a Livechat Title Background Color from the drop-down menu 

### Expected behavior:

Livechat Title Background Color drop-down menu should show color options or allow a hex color value.

### Actual behavior:

Livechat Title Background Color drop-down menu is empty and a hex color value cannot be entered.

**Comment by aditya19496** [comment]
Can I add this feature?

**Comment by jszaszvari** [comment]
Seeing this too, Dropdown is not functioning 

![image](https://user-images.githubusercontent.com/872463/31948025-77c7c37a-b921-11e7-8c40-712e8d101c38.png)

**Comment by sampaiodiego** [comment]
Just so you guys know, you can still change it from livechat appearance page (click on your avatar at top left corner > Livechat > Appearance). Changing from admin panel is buggy indeed.
