### ISSUE TITLE
Long topic names causes sidebar and send button to disappear on Firefox

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#8075]
![](https://shitty.download/qP1W.png)

Right sidebar and send button have gone off-page. Only happens on Firefox, not Chrome. 
0.59.0-develop, e568f8a

**Comment by MartinSchoeler** [comment]
This will be fixed on #7750

**Comment by ChrisPWill** [comment]
Issue still occurs for me on RocketChat 0.60.3 [397857ef1c32988597da42264f4638604526e184](https://github.com/RocketChat/Rocket.Chat/commit/397857ef1c32988597da42264f4638604526e184).

Issue occurs on Firefox 57.0.4

**Comment by ggazzo** [comment]
@Lemmmy I believe we fixed this issue, any problem please open again

## firefox 57
![machs_firefox_57 0](https://user-images.githubusercontent.com/5263975/42294037-7f1f4c1a-7fb4-11e8-95ab-55f5a94baaae.jpg)

## firefox 56
![machs_firefox_56 0](https://user-images.githubusercontent.com/5263975/42293857-7b687444-7fb3-11e8-9374-548566ab0fb1.jpg)
