### ISSUE TITLE
Authentication Issue involving RC Token and SimpleSAMLphp

### ISSUE THREAD

**Issue by rickwarren** [RocketChat/Rocket.Chat#8081]
### Description:

When attempting to authenticate via SAML using SimpleSAMLphp as an Identity Provider, it is not being redirected to the correct endpoint in order to successfully login.

### Server Setup Information:

* Version of Rocket.Chat Server: latest
* Operating System: Alpine Linux
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1

### Steps to Reproduce:

1. Click SAML button
2. Enter SSO login credentials in the popup
3. Get error page with nothing helpful to say.

### Expected behavior:

After authenticating with the Identity Provider, the user should get logged in.

### Actual behavior:

The user gets redirected to example.com/_saml/validate/<provider>/  and receives the following error message:

Sorry, an annoying error occured

TypeError: Cannot read property '0' of undefined
Close Window

due to not being redirected to the url that it seems to require which would be example.com/_saml/validate/<provider>/<token>/

**Comment by localguru** [comment]
How does your SAML config in RC look like? We have no problems with RC and Shibb.

**Comment by rickwarren** [comment]
Custom Provider:    saml
Custom Entry Point:    https://sso.example.org/simplesamlphp/saml2/idp/SSOService.php
IDP SLO Redirect URL:    https://sso.example.org/simplesamlphp/saml2/idp/SingleLogoutService.php
Custom Issuer:    https://talk.example.org/_saml/metadata/saml
Custom Certificate:    CERT without BEGIN and END tags
Public Cert Contents:    CERT with BEGIN and END tags
Private Key Contents:    KEY with BEGIN and END tags
Generate Username:    True

**Comment by rickwarren** [comment]
Here is the auth request:

<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    ID="id-7XBub6o6KsWRwTp6L"
                    Version="2.0"
                    IssueInstant="2017-09-12T20:46:56.422Z"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="https://talk.example.org/_saml/validate/saml"
                    Destination="https://sso.example.org/simplesamlphp/saml2/idp/SSOService.php"
                    >
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://talk.example.org/_saml/metadata/saml</saml:Issuer>
    <samlp:NameIDPolicy xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                        Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
                        AllowCreate="true"
                        />
    <samlp:RequestedAuthnContext xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                                 Comparison="exact"
                                 >
        <saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>

and here is the response:

<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                ID="_eb56c1dd0667c53b65b287a90b6c3235ee613cbdfc"
                Version="2.0"
                IssueInstant="2017-09-12T20:45:52Z"
                Destination="https://talk.example.org/_saml/validate/saml"
                InResponseTo="id-7XBub6o6KsWRwTp6L"
                >
    <saml:Issuer>https://sso.example.org/simplesamlphp</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
            <ds:Reference URI="#_eb56c1dd0667c53b65b287a90b6c3235ee613cbdfc">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                <ds:DigestValue>k1nPYo0yOpZRr/7ZeNYcDvphdJ4=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue></ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate></ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    ID="_6cbf4eca9282c343efd8821b1ca05d2e24d543fedd"
                    Version="2.0"
                    IssueInstant="2017-09-12T20:45:52Z"
                    >
        <saml:Issuer>https://sso.example.org/simplesamlphp</saml:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
                <ds:Reference URI="#_6cbf4eca9282c343efd8821b1ca05d2e24d543fedd">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                    <ds:DigestValue>BfVxikG7Y5QrQEVtoNewK1oZ9MM=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue></ds:SignatureValue>
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate></ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml:Subject>
            <saml:NameID SPNameQualifier="https://talk.example.org/_saml/metadata/saml"
                         Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
                         >3b55aeef96fe50fccdd2e36803093bae9fd562e8</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData NotOnOrAfter="2017-09-12T20:50:52Z"
                                              Recipient="https://talk.example.org/_saml/validate/saml"
                                              InResponseTo="id-7XBub6o6KsWRwTp6L"
                                              />
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2017-09-12T20:45:22Z"
                         NotOnOrAfter="2017-09-12T20:50:52Z"
                         >
            <saml:AudienceRestriction>
                <saml:Audience>https://talk.exmaple.org/_saml/metadata/saml</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2017-09-12T20:45:52Z"
                             SessionNotOnOrAfter="2017-09-13T20:45:52Z"
                             SessionIndex="_6ccfd3bacd0dfc7e953390bcf2ecafa654028b843f"
                             >
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="cn"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">Rick Warren</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="sn"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">Warren</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="givenName"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">Rick</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="uid"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">rickwarren</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="mail"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">rickwarren@example.org</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="memberOf"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string"></saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="groups"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            />
            <saml:Attribute Name="UserID"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">rickwarren</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="email"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">rickwarren@example.org</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>

**Comment by rickwarren** [comment]
Anyone?

**Comment by rickwarren** [comment]
This isnt a feature/integration/plugin.....this is functionality that you already have that is not working correctly.

**Comment by pierre-lehnen-rc** [comment]
I'll assume this one was either a misconfiguration or something that has already been fixed, as SimpleSAMLphp works perfectly well with Rocket.Chat now.
