### ISSUE TITLE
Desktop Notifications Setting Overriding Audio Notification Setting

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#8082]
Reproduced in 0.58.2 and 0.59.0-rc.4

Steps to Reproduce:
1. Start with default desktop and audio settings (Use account preference) - i.e. Mentions
2. Change the Desktop setting to "All Messages"
3. You will now get desktop notifications AND audio notifications for ALL messages

Expected Behavior:
Changing the Desktop setting should not impact the audio setting.

**Comment by aditya19496** [comment]
i will look into it.

**Comment by aditya19496** [comment]
Its this way because everytime you receive a desktop notification, you also receive a audio notification too.
@ggazzo You want me to change this thing?

**Comment by danieljhochman** [comment]
Of course these should be separate . That's what the settings UI implies.
