### ISSUE TITLE
Rocket Chat UI Customisation via Code

### ISSUE THREAD

**Issue by bhagaban** [RocketChat/Rocket.Chat#8083]
I wish to know how to change the Rocket UI via code. I tried to look but couldn't located the client side files. I am looking to do some heavy customisation which cant be done from the Admin settings. 

How can this be achieved ?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
