### ISSUE TITLE
Sending attachments in live-chat does not work

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8088]
### Description:
When sending an attachment from Rocket.Chat to a live-chat guest, it is not transferred to the client. 

### Server Setup Information:
* Version of Rocket.Chat Server: v0.58.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: Yes
* Node Version: v4.5.0

### Steps to Reproduce:

1. Attach a file in a live-chat

### Expected behavior:

Either attachments are not allowed within live chats or the attachment has to be sent.

**Comment by MartinSchoeler** [comment]
Duplicate of #6516
