### ISSUE TITLE
Atom package that integrates a chat messaging client into the editor

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#809]
Probably a webview and not like https://atom.io/packages/slack-chat
##

**Comment by geekgonecrazy** [comment]
:+1: 

How deep of an integration?  Like a simple channel switcher and channel feed?  Minus all other extra features.  Maybe a button to pop into full rocket.chat app?

**Comment by SeanPackham** [comment]
I like the sound of this feature but think it something that can be created by the community if they have the need for it.
