### ISSUE TITLE
Desktop-notifications are showing G1, G2, ... instead user names, in live-chat 

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8090]
### Description:

When an incoming live-chat message triggers the desktop notification, the user name of the live chat client is not being displayed. Instead G1, G2, ... is shown in the notification test.

### Server Setup Information:

* Version of Rocket.Chat Server: v0.58.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: Yes
* Node Version: v4.5.0

### Steps to Reproduce:

1. Open Rocket.Chat in one browser session
2. Open a Live-Chat window in a another browser session.
3. Start a new live chat and enter user name
4. Send a message
5. Look at the notification ...

### Expected behavior:

The entered user name is displayed in the notification text

### Actual behavior:

G1, G2, etc. ist displayed instead the user name

**Comment by ashwaniYDV** [comment]
I thing this issue is not valid in latest version of livechat
