### ISSUE TITLE
change rocketchat logo from Desktop Notification

### ISSUE THREAD

**Issue by codinol** [RocketChat/Rocket.Chat#8093]
Is there any way to change the default rocket chat icon showing on Desktop notifications?

Please help

![screen shot 2017-09-11 at 7 33 29 pm](https://user-images.githubusercontent.com/31839463/30278524-2cb31df0-9728-11e7-9b5c-69440dcabac5.png)

**Comment by premanandmanimaran** [comment]
Hi 
I want to know how to change the Notification server name , like you have teamseadapp.com.

Also How to change the Desktop App icon ?

Thanks

Prem

**Comment by tassoevan** [comment]
Please check our forum (https://forums.rocket.chat/c/community-support) and community support channel (https://open.rocket.chat/channel/support) for help.
