### ISSUE TITLE
Feature Request: Prefill LiveChat Prechat form

### ISSUE THREAD

**Issue by msypes** [RocketChat/Rocket.Chat#8096]
It would be nice if we could prefill the prechat form, or add to its fields.  E.g., with a Wordpress installation, it would be convenient to fill the existing fields with the logged in user's info, so that they're not required to input the information again, for both convenience and reduction of errors.

**Comment by renatobecker** [comment]
Hi @msypes!
Sorry for the late answer.. 
I want to say that now you can do what you're asking for. Please, take a look at here: #10918.
We've improved our Livechat Iframe API, so you can use it tho pre-fill the Livechat form fields or do even more, like using the `registerGuest` method, then it is not necessary to display the Livechat registration form.

I hope you can now improve the experience using the Livechat.
Thanks.
