### ISSUE TITLE
Avatar Image upload issues - Docker [rocketchat v0.58.2]

### ISSUE THREAD

**Issue by DarkBlaez** [RocketChat/Rocket.Chat#8098]
Can anyone point me to a solution to this issue. I see this issue has persisted in one form or another since 2015 with various reslutions or stated fixes. However, this issue persist

Using example docker-compose.yml modified for correct URL for my local install, volumes mapped locally, docker ce v17. This is under RancherOS but nothing special about this OS. I have seen this same issue under CentOS 7.3 with docker. Docker and Linux are nothing new to me so looking to skip right to the heart of the issue.

Startup - rocketchat
Setting default file store to GridFS
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
ufs: temp directory created at "/tmp/ufs"
➔ System ➔ startup
➔ +---------------------------------------------------------+
➔ |                      SERVER RUNNING                     |
➔ +---------------------------------------------------------+
➔ |                                                         |
➔ |  Rocket.Chat Version: 0.58.2                            |
➔ |       NodeJS Version: 4.8.4 - x64                       |
➔ |             Platform: linux                             |
➔ |         Process Port: 3000                              |
➔ |             Site URL: http://<some ip>:3000 |
➔ |     ReplicaSet OpLog: Enabled                           |
➔ |          Commit Hash: 988103d449                        |
➔ |        Commit Branch: HEAD                              |
➔ |                                                         |
➔ +---------------------------------------------------------+

I have mapped /app/uploads to a local directory with wide open permissions (not that I should have to)

Thoughts?

Thanks in advance
DB-

**Comment by MartinSchoeler** [comment]
@DarkBlaez Could you be more specific about the issue you are having with the file uploads?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
