### ISSUE TITLE
Ability to clear current window messages up to "Load more" button

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#81]
Command (or CTRL) + K clears current window messages up to "Load more" button, which when clicked would retrieve all previous messages. If user re-enters room, messages are loaded as usual.

**Comment by marceloschmidt** [comment]
It's now enabled. You can press CTRL (or Command) + Shift + K. Shift was added because CTRL+K will move the cursor to the search bar on Google Chrome (Linux and Windows)
