### ISSUE TITLE
Don't auto-link 10 digit numbers

### ISSUE THREAD

**Issue by dbussert** [RocketChat/Rocket.Chat#810]
any 10 digit number typed in will be auto-linked as a telephone number.  Chat should not assume a 10 digit number (with no hyphens even) is a telephone number.  We post calculations and lat/lon, and it will pull out even part of a number and link it.

![image](https://cloud.githubusercontent.com/assets/2479487/9865757/60211ad6-5b28-11e5-96d1-4b79353ab938.png)

**Comment by marceloschmidt** [comment]
We use https://www.npmjs.com/package/autolinker and it does have an option for not parsing phone numbers. I just wonder if that should be the default behavior, an admin settings or a user settings. @RocketChat/owners what's your take on this?

**Comment by marceloschmidt** [comment]
@sampaiodiego @rodrigok @engelgabriel @Sing-Li @geekgonecrazy @gmsecrieru

**Comment by geekgonecrazy** [comment]
:) I'd think it'd be user specific. Cause it seems like that'd kinda be a personal preference

**Comment by engelgabriel** [comment]
Should be an admin settings for the default behavior and overwrittable by an user settings

**Comment by geekgonecrazy** [comment]
:+1: I like that.

**Comment by rwakida** [comment]
Too much configuration settings is overwhelming.  

I think if the user wants to enter a phone number, they should either format it themselves or use a specific syntax that the autolinker understands to convert to a phone number.  Like in GitHub how we type :&nbsp;+1:  to specify :+1: 

Also, if we auto format, then there has to be a way to specify the format.  Or would we guess based on their locale?

**Comment by dbussert** [comment]
If the syntax specific for phone numbers was better, it would solve this specific issue.  For a US number, it should only match 123-456-6789, not any 10 digits.  I don't know how that library handles international numbers, but I believe everyone uses 1 or more dashes somewhere.

**Comment by mitar** [comment]
Those configuration settings is just for admins though. I think this is OK. Slack also has a lot of settings, but somehow it is good.

Why would parsing numbers be useful at all? Where do they point to?

**Comment by engelgabriel** [comment]
They would create the call... so if you have a softphone.. you can just click and it will dial. Skype can also dial phone number on web pages.

**Comment by mitar** [comment]
So I see it reasonable that this would be enabled by default for phone apps, but on desktop is probably strange default?

**Comment by gmsecrieru** [comment]
_Update_: Looks like this is affecting 8+ digits:

![digits](https://cloud.githubusercontent.com/assets/190883/10292078/924b2e00-6b83-11e5-9b61-c9b29720bdd5.gif)

**Comment by LeonardOliveros** [comment]
No results with disabling phone: false in the package / rocketchat-autolinker / autolinker.coffee still affecting more than 8 digits

**Comment by LeonardOliveros** [comment]
![Uploading Captura de pantalla de 2015-10-05 16:13:39.png…](No results)

**Comment by richardwlu** [comment]
:+1:
