### ISSUE TITLE
Where do I set the moderators for channels?

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#8100]
I see that there is a place to control what Permissions Admins/Mods/etc have... but I don't see where I can assign the role to a User.

**Comment by localguru** [comment]
You can select roles on the user's profile.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
