### ISSUE TITLE
SMTP Can't support STARTTLS login way, use SSL way worked find.

### ISSUE THREAD

**Issue by NeverMin** [RocketChat/Rocket.Chat#8102]
### Description:

Rocket Chat can't support STARTTLS(587) login way, use SSL(465) way worked find.

My tested:
`export MAIL_URL=smtps://rocketchatnotify@gmail.com:passowrd@gmail.com:465/`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Node Version: 4.7.1

### Steps to Reproduce:

1. Admin -> Email -> SMTP
2. smtps 
3. click send test mail

#### OR
1. `export MAIL_URL=smtps://notify@outlook.com:passowrd@smtp-mail.outlook.com:587/`
2. node main.js
3. click resend verification email

### Expected behavior:

* get test mail

### Actual behavior:

* UI display: Error trying to send mail: 139956548945728

### Relevant logs:
console:
```
Updating process.env.MAIL_URL
Updating process.env.MAIL_URL
Sending test email to userid@domain.com
```

**Comment by localguru** [comment]
Hi, 

I don't use the env.MAIL_URL, but just configured email settings in Administration/E-Mail/SMTP and it's working fine with TLS with our local smtp relay. Never tested with outlook.com.

**Comment by NeverMin** [comment]
Hi @localguru , thank you for your reply, I just tested gmail.com same issue: in Administration/E-Mail/SMTP same GmailID, 465 worked fine, but 587 can't send email.

**Comment by TomaszDom** [comment]
Are you able to connect to the mail server from the chat server in the first place?

Try running `nc -z smtp-mail.outlook.com 587`, if it "hangs" on the command then you can't connect, if it exits cleanly, then you can estabilish a connection.

As a data point I can say that I'm able to use STARTTLS on port 587 with no issues (self-hosted e-mail server) with self-hosted rocket chat 0.58.0.

**Comment by NeverMin** [comment]
Hi @TomaszDom , here is console log:
```
user@hostname:~$ nc -vz smtp-mail.outlook.com 587
Connection to smtp-mail.outlook.com 587 port [tcp/submission] succeeded!
user@hostname:~$ telnet smtp-mail.outlook.com 587
Trying 40.100.2.98...
Connected to outlook.ms-acdc.office.com.
Escape character is '^]'.
220 HK2PR02CA0210.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 12 Sep 2017 23:53:13 +0000
EHLO hostname
250-HK2PR02CA0210.outlook.office365.com Hello [hostname_IP]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
QUIT
221 2.0.0 Service closing transmission channel
Connection closed by foreign host.
```

**Comment by TomaszDom** [comment]
I think you should set the protocol to smtp and not smtps on port 587, it should work.

**Comment by localguru** [comment]
Ah, yes. I've set protocol to `smtp` and port to `587` too. Pool is set to `yes`, but don't know what's that for.

**Comment by NeverMin** [comment]
Hi @TomaszDom @localguru , thank you for your tips, I try set to `smtp` and port `587`, but IgnoreTLS and pool set to `False`, so it worked. settings like this:
![smtp settings](https://user-images.githubusercontent.com/2797432/30371271-a719e68e-98ac-11e7-90b6-094cfd518420.png)

I don't know why.

**Comment by TomaszDom** [comment]
It worked because the protocol used on port 587 is ESMTP, not the legacy SMTPS that is used on port 465, so your initial configuration was incorrect, I didn't notice it immidiately.

**Comment by localguru** [comment]
Ah, good to know. When setting up SMTP some time ago I played with the settings too, but didn't remember that point yesterday. Thanks for updating me.

**Comment by NeverMin** [comment]
Oh, thanks to you both.
