### ISSUE TITLE
Cannot change username

### ISSUE THREAD

**Issue by navya-uppalapati** [RocketChat/Rocket.Chat#8103]
User cannot able to change username. Says your rocketchat administrator has disabled the changing of usernames. But it is set to true in Account settings.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1 
* DB Replicaset Oplog: Disabled
* Node Version: v6.6.0

![rc1](https://user-images.githubusercontent.com/29859290/30318904-aeb43c68-97ae-11e7-8dba-5d7a7adb86d8.PNG)

Need help! Awaiting for your response

**Comment by localguru** [comment]
Hi, don't understand. Where is "your rocketchat administrator has disabled the changing of usernames" in settings?

**Comment by navya-uppalapati** [comment]
Hi,
If I go to my account settings and place the cursor on username, it popups saying that "your rocketchat administrator has disabled the changing of usernames"

**Comment by MartinSchoeler** [comment]
@navya-uppalapati could you post a screenshot of your profile page on account settings? Thanks!

**Comment by dulman** [comment]
@MartinSchoeler 
We also have allowed useres to change their username. But useres aren't able to change their username.
"Your rocketchat administrator has disabled the changing of usernames."

![image](https://user-images.githubusercontent.com/20679842/36731683-b49e0568-1bcb-11e8-8c2d-51033eb26890.png)

**Comment by gdelavald** [comment]
Hey @navya-uppalapati, is LDAP enabled in your server?

**Comment by pauloriply** [comment]
Same problem. LDAP enabled.

**Comment by gdelavald** [comment]
@pauloriply LDAP Enabled instances do not allow username change, this explains your problem.

@navya-uppalapati if you have LDAP enabled as well I'll go ahead and close the issue.

**Comment by navya-uppalapati** [comment]
Yes, ldap is enabled

**Comment by gdelavald** [comment]
Ok, I'll close the issue as this is working as intended.

**Comment by kai-uwe-rommel** [comment]
But this is wrong. When a user initially starts using RocketChat, he/she can authenticate via LDAP and then define his/her nickname (user name). Sometimes users choose inappropriate (such as ambiguous) user names and later need to change them. 

The limitation would be OK, if I could force a fixed user name for all users (such as DisplayName or UID from the LDAP record of the user).
