### ISSUE TITLE
[Feature Request] Override Livechat agent's avatars by a single image

### ISSUE THREAD

**Issue by icosamuel** [RocketChat/Rocket.Chat#8106]
Rocket.Chat Version: 0.58.2

Sometimes our LiveChat agents use their personal (internal to our business) account to serve our LiveChat clients. To enforce professionalism or just standardize the service image, it would be great to have a configurable image that replaces all user's avatar only in context of the LiveChat.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:57389 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1drnEx-000ikW-3U
	for greg@biomassiv.es; Tue, 12 Sep 2017 10:36:43 -0500
Date: Tue, 12 Sep 2017 08:29:49 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1505230562;
	bh=P0V7lY6c0OPYodEliHp+bADoBXch+oHzrZr7FpK1S6k=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=HVo7kB47p+rJY116ozFjvgSCjjOcXM7iJeKQOoqJTtYbBExyGMYHHHFd0sRiBgowN
	 /9MDhuPX5RMij2g8s4DpAzo/kmRbf37CLeOfmZrrar+fhZAVFf7Faovdd/VDW93Jab
	 XWvE0OOJNGgIugazlNKsRuDZgB+djIHKUw1k7c9k=

**Comment by icosamuel** [comment]
our team duplicated the rocketchat server in order to have a dedicated one for livechat support. We will ask our agents to use a particular picture for answering guests. No need for this feature anymore so i'm closing it.
