### ISSUE TITLE
Cannot update avatar when using google cloud storage

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#8109]
### Description:

I'm actually not sure if it's related to GCS, but you cannot update avatars anymore on my server.

See here: 
![https://i.imgur.com/meAJXto.gif](https://i.imgur.com/meAJXto.gif)

It looks like it worked for a split second, then reverts back to the old avatar. No errors on the server or on the client. Normal file upload in channels works fine, so I doubt it's a permission issue.

### Server Setup Information:

* Version of Rocket.Chat Server: master e568f8a8ece4512a0813d278f8b7cee1d2f40d46
* Deployment Method(snap/docker/tar/etc): docker
### Steps to Reproduce:

See image
### Expected behavior:

Avatar upload should work

### Actual behavior:

Avatar isn't updated, no error messages shown

### Relevant logs:

Nothing relevant.

**Comment by geekgonecrazy** [comment]
I believe solved by one of the numerous prs touching this
