### ISSUE TITLE
Rocket.Chat Apps Admin Interface

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#8111]
### Description:

Create a UI to select Apps active on the server.

**Comment by mnlbox** [comment]
@gdelavald What is the Rocketlet state now? Is there any document for it?

**Comment by ggazzo** [comment]
![image](https://user-images.githubusercontent.com/5263975/30497506-787e53f4-9a29-11e7-8037-de10d4e267e0.png)

**Comment by gdelavald** [comment]
@mnlbox Hey, they are currently in alpha stage, currently being developed outside of the RC organization on GitHub, but will be moved and the code opened as soon as we get to a stable (and actual usable) state.

**Comment by arthurgiustina** [comment]
Same discussion here: https://github.com/RocketChat/Rocket.Chat/issues/9128
