### ISSUE TITLE
how to  statistics Jitsi time cost

### ISSUE THREAD

**Issue by kyle-kai** [RocketChat/Rocket.Chat#8114]
Hi, I am doing something with rocketchat , I use jitsi for video chat in rocket chat, if I want to develop a function to  statistics the video using time for each user, how can I do? this function is important for rocket chat system, who can answer this question, thank you!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
