### ISSUE TITLE
How to display {{name}} in chat message?

### ISSUE THREAD

**Issue by greatdinosaur** [RocketChat/Rocket.Chat#812]

**Comment by marceloschmidt** [comment]
By {{name}} I suspect you mean the user name that sent the message?

**Comment by greatdinosaur** [comment]
Yes, I modified /client/views/app/message.html
<img width="933" alt="eaf2666c-1cdd-474f-b146-108c3fa7f658" src="https://cloud.githubusercontent.com/assets/16178/9894996/d95b0e54-5c5c-11e5-9d67-d5a97156d781.png">

it's not display in front page

**Comment by marceloschmidt** [comment]
That's because messages do not include user's real name in their document, only _id and username. We don't have plans for adding users' names in message object.
