### ISSUE TITLE
Where to find API URL of iframe integration

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#8125]
I am trying RC iframe integration.
I am reading https://rocket.chat/docs/developer-guides/iframe-integration/authentication
I cannot understand the API URL part. How do i obtain the API URL?

**Comment by giorgiopaolucci** [comment]
try this doc.
It helped me to implement....
bests.
http://webdevllc.biz/index.php?/blog/2016/12/how-to-iframe-rocket-chat

**Comment by jy2008** [comment]
Thanks very much, i am still confusing tho, so do i just set up pages using the files?

**Comment by eddiekollar** [comment]
@giorgiopaolucci the link no longer works. Is there new location of this blog post?

**Comment by gabriellsh** [comment]
Please refer to the new docs https://developer.rocket.chat/reference/api/rest-api
