### ISSUE TITLE
Application is not able to access the publish method

### ISSUE THREAD

**Issue by nitinprajapati1404** [RocketChat/Rocket.Chat#8127]
Rocket.Chat Version: 0.56.0
DB Replicaset OpLog: Enabled
Node Version:4.8.2 - x64

I have a publish method on serverside. which has two parameters

`Meteor.publish("smaplePublish",function(firstParam,secondParam){
  console.log(firstParam,"firstParam");
  // return data accordingly from the colleciton
})`

And I have subscribed it from the  client side

`Meteor.subscribe("smaplePublish",firstParam,secondParam)`

that's works fine for the web

but as mobile application is not able to consume this publish method

As i have checked the documentation and also try to follow the instruction but there is only for the streams not for the custom publish method

I have followed [https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/](url) for the documentation

So what should i do for the access custom publish method in mobile application?

**Comment by JigneshPatel23** [comment]
May be this is also related one if anyone can help here.
https://github.com/RocketChat/Rocket.Chat.Android/issues/460

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
