### ISSUE TITLE
Descenders of glyphs in channel names not visible in sidebar

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#8129]
### Description:

**On Chromium + Firefox:** The [descenders](https://en.wikipedia.org/wiki/Descender) in channel names are not visible in the left sidebar.

Only in Firefox: sidebar does not align with top menu in sidebar

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.5
* Operating System: Oracle Linux 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4

### Steps to Reproduce:

Not really applicable, as UI bug. See screenshot below.

### Expected behavior:

Not really applicable, as UI bug. See screenshot below.

### Actual behavior:

![image](https://user-images.githubusercontent.com/179595/30423874-8130e43e-9944-11e7-8fec-33917dcbb57b.png)

### Relevant logs:
Not really applicable, as UI bug. See screenshot above.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8154
