### ISSUE TITLE
LiveChat file upload, chat limits and queue

### ISSUE THREAD

**Issue by Oddadmix** [RocketChat/Rocket.Chat#8130]
Hi, I wanted to ask about two things.

the first thing is can live chat support file upload from the guest, agent side? 
for the live chat agent, is there a way to set a hard limit on the chat and enable queueing for guests?

Thanks in advance.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
