### ISSUE TITLE
Browser crash possible with KaTeX

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#8156]
`\[\begin{pmatrix}a\\[99999em]\end{pmatrix}\]` can crash browsers, see [Khan/KaTeX#109](https://github.com/Khan/KaTeX/issues/109)

**Comment by Dadibom** [comment]
confirmed, both in chrome and the desktop app

**Comment by dennis-f** [comment]
confirmed ... my admin hates me now

**Comment by julio-cfa** [comment]
It will be this issue's birthday soon, but it is being fixed here: https://github.com/RocketChat/Rocket.Chat/pull/33246.
