### ISSUE TITLE
RocketChat Triggering Button

### ISSUE THREAD

**Issue by lucasbagb** [RocketChat/Rocket.Chat#8157]
### Description:

I need RocketChat to activate a job in a running pipeline. This job has a "button" trigger that can be pressed by the user. How can I make this be activated by RocketChat? I do not want it to start a new pipeline, but continue to the one that has already been started.

### Server Setup Information:

* Version of Rocket.Chat Server: latest
* Operating System: RedHat 7.2
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 4.8.1

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
