### ISSUE TITLE
does rocket.chat offer the ability for members to not have permissions to direct message other members?

### ISSUE THREAD

**Issue by miguelmota** [RocketChat/Rocket.Chat#8160]

**Comment by AdamBLevine** [comment]
Yes, as an admin on the server go to Administration -> Permissions and de-select this setting for the usergroup you want to remove it from

![image](https://user-images.githubusercontent.com/6858319/30506281-824c7680-9a2f-11e7-83ec-3b858c341802.png)

**Comment by miguelmota** [comment]
Thanks!

**Comment by AdamBLevine** [comment]
Yeah absolutely.  Are you also trying to address the slack phishing
epidemic in the crypto world?

Adam B. Levine
CEO, Tokenly <http://tokenly.com>

**Comment by miguelmota** [comment]
@AdamBLevine yep, we're exploring alternative platforms to Slack. Rocket.chat looks amazing thus far

**Comment by AdamBLevine** [comment]
Worth mentioning then that in a few weeks you'll be able to create rooms on
rocket.chat servers that gate access by what ERC20 tokens a user has
(non-custodial).   We have this support in testing with bitcoin layer
tokens now and we think it's the long term solution for communities - just
have  public areas for new users and private areas for community who
actually own some of the tokens.   And to your question here, we're going
to apply this sort of control to user roles as well so token holders can
have different permissions automatically.
