### ISSUE TITLE
[BUG] Channel/group names are switching to lowercase with dashes

### ISSUE THREAD

**Issue by imeleges** [RocketChat/Rocket.Chat#8163]
Greetings,

Discovered very interesting behavior with my new RC server on CentOS.
If I'll create a new channel/private group with a space in the name "**Test Room**" it will  turn in to the name "**test-room**". 
More fun is that channel/group name will be changed to "**Test Room**" if there's a new message, as soon I checked all unread messages, name is turning back to "**test-room**"

General settings for **UTF8 Names Validation is [0-9a-zA-Z-_.]+**
I also have another server but on Ubuntu with the same settings and there's no problems.

Does anyone know what's wrong?

Server Setup Information:
* Version of Rocket.Chat Server: 0.58.2
* Operating System: CentOS 7
* Number of Running Instances: 1
* Node Version: 4.5.0

Thanks for your help

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I'm closing this in favour of #9738. Please see that error and also #10669 to get a complete picture.

The fact that the channel name needs to be normalized ("stripped of every special character") for some cases probably makes sense for internal use but it should always be displayed as the "original name" in user-facing UIs.

Cheers
Thomas
