### ISSUE TITLE
next page of message search not working

### ISSUE THREAD

**Issue by inetfuture** [RocketChat/Rocket.Chat#8164]
### Description:

When I search message in any channel or direct chat, the first page shows, then I scroll down to the bottom, an loading indicator shows, but the next page never comes up, here is a screenshot:

![desktop screenshot](https://user-images.githubusercontent.com/1363189/30508303-224f9054-9ac6-11e7-8909-fd1e0e77ea05.png)

seems this is a client bug, it did not send the second query.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Ubuntu 14.04
* Deployment Method(snap/docker/tar/etc): docker(rocketchat/rocket.chat:latest)
* Number of Running Instances:  1

**Comment by matheusml** [comment]
@inetfuture I could not reproduce this error.
Could you please take a look at this small video and explain what I am doing wrong?

![https://media.giphy.com/media/3o7aCZ7V9hV5iRuaNq/giphy.gif](https://media.giphy.com/media/3o7aCZ7V9hV5iRuaNq/giphy.gif)

**Comment by inetfuture** [comment]
Upgraded to the latest just now, this problem no longer exists
