### ISSUE TITLE
[BUG] [UI] Wrong user menu position in RTL languages

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8165]
Hi guys,
Wrong user menu position in RTL languages. See below gif for more detail:
![peek 2017-09-16 10-19](https://user-images.githubusercontent.com/8266479/30509563-b5f615b0-9ac8-11e7-98b2-79def0581ee5.gif)

**Comment by cyclops24** [comment]
Maybe related to this: #8154

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8154
