### ISSUE TITLE
Broken Link in README.md about how it all started

### ISSUE THREAD

**Issue by SebAlbert** [RocketChat/Rocket.Chat#8169]
Sorry for not using the form, but it seems inappropriate for reporting a broken link in the README.md

The link "how it all started" pointing to http://osdelivers.blackducksoftware.com/2016/06/10/rocket-chat-hosted-chat-services/ is broken: The response seems to replace and then complain about the hostname, it reads:

> Invalid URL
> 
> The requested URL "http://%5bNo%20Host%5d/2016/06/10/rocket-chat-hosted-chat-services/", is invalid.

This is of course an indirect problem of the documentation and not a primary bug of RocketChat.

**Comment by MartinSchoeler** [comment]
Please reopen this on our [docs](https://github.com/RocketChat/Rocket.Chat.Docs) repo. Thanks!
