### ISSUE TITLE
Help with SlackBridge - Rocket.Chat to Slack not stable

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#8174]
* Version of Rocket.Chat Server: 0.55.1
* Operating System: Linux x64
* Number of Running Instances: 2
* Node Version: v4.2.6
--

I am running into a strange issue with SlackBridge in a relatively old version of rocket.chat. My apologies if the issue has already been resolved in newer versions. Please let me know. 

Issue - I've been able to use slackbridge to do a two-way sync between slack and rocket.chat. Messages from slack to rocket.chat is always synced. However, rocket.chat to slack works only when I (in order)

1. create the channel in slack first 
2. invite bot, rocket.chat user

If I create a channel in rocket.chat first, then create corresponding channel in slack then slack to rocket.chat works, but not rocket.chat to slack. 

Thanks for your help in advance.

**Comment by lindoelio** [comment]
Hi @akachapati! This issue already have a thread at #6509. Keep yourself in the loop there :-)
