### ISSUE TITLE
[Discussion] When UI redesign completely finish?

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#8175]
Hi guys,
First I would say tanks for this awesome changes and new beautiful design :wink I think RC team work on a very good path and RC have a shiny future, but I have small question.

Now I have many issue on new design on this part:
- [x] Many bug and incomplete task about new design.
- [ ] Some bugs on Firefox 55, 54
- [x] Many RTL bugs
- [ ] Some UX bugs

Please let's talk about this:
1. What is your plan to completely switch to new UI?
2. Which milestone (when?) we can see new design ready for production and bug free?
3. Is it possible to temporary disable new design from admin panel (new design breaks completely for me on RTL and Firefox and I need to temporary disable it until stable version 😞 )

**Comment by rodrigok** [comment]
Hi @mnlbox thanks for this question. Lets try to answer it 😄 

**1. What is your plan to completely switch to new UI?**
Wha do you mean? The date or the objective?
We will release the menu and text box release in version 0.59, the messages area and header in version 0.60

**2. Which milestone (when?) we can see new design ready for production and bug free?**
There is no milestone set to complete the redesign, it's a huge amount of work and we are trying to complete it as soon as possible, you can follow the progress in this epic https://github.com/RocketChat/Rocket.Chat/issues/7839 (use ZenHub to see more details)

**3. Is it possible to temporary disable new design from admin panel (new design breaks completely for me on RTL and Firefox and I need to temporary disable it until stable version 😞 )**
No, there is no way to disable the design, it changes a lot of our code base and CSS, we changed some technologies and UX decisions, so it's not possible to keep both.
The current version is under development, we will release the 0.59.0-rc.6 today with some fixes, we are not planing to release the final versions with UX/UI bugs.
What you can do now is open issue describing the problems you have with the new version and we will fix them util the final release.

**Comment by cyclops24** [comment]
@rodrigok Thanks for your answer.
So I can aggregate RTL issues here as list (like @mnlbox)
- [ ] #8165 
- [ ] #8179 
- [ ] #8180
- [ ] #8181
- [ ] #8182
- [ ] #8183
- [ ] #8184
- [ ] #8185
- [ ] #8186
- [ ] #8187

I think @karlprieb can help here in RTL issues 😉

**Comment by cyclops24** [comment]
@karlprieb I updated above post.

**Comment by cyclops24** [comment]
Guys please check RTL before merge if not new issues born after each merge PR 😢 (Like this: #8223 scrollbar breaks after redesign)

Thanks for your attention 😉 

**/CC:** @rodrigok , @karlprieb , @ggazzo

**Comment by cyclops24** [comment]
@rodrigok Please reopen #8186

**Comment by cyclops24** [comment]
Sidebar related issues:
- [ ] #8264 [BUG] [UI] Sidebar selected color not readable

**Comment by cyclops24** [comment]
Translation issues: (i18n)

- [ ] #8201 [BUG] [UI] "Members List" online users count not avaiable in RTL

**Comment by engelgabriel** [comment]
@cyclops24 Ideally you should refer to this issue on on the others, so it is easy to track status here.

**Comment by cyclops24** [comment]
@RocketChat/core Please reopen this: https://github.com/RocketChat/Rocket.Chat/issues/5592

**Comment by engelgabriel** [comment]
Let's close this track issue and track the issue using labels and the project board.
