### ISSUE TITLE
User avatar as PNG, JPG or BMP with image resize

### ISSUE THREAD

**Issue by lindoelio** [RocketChat/Rocket.Chat#8178]
Add endpoint on Rocket.Chat API that allow parameters for transform and resize avatars.

For example: '/avatar/username?format=png&height=20&width=20' should return one PNG image with 20 pixels of width and 20 pixels of height.

Part of this was requested on #7908; It's a extension for that.

**Comment by sampaiodiego** [comment]
This is not the path we should follow.

if one wants multiples avatar sizes, those should be configured previously and then be generated upon upload.
