### ISSUE TITLE
[BUG] [UI] Menu and reaction button position is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8179]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![02](https://user-images.githubusercontent.com/8266479/30548359-2deaf5ba-9ca7-11e7-8a69-0582ec6d6d44.gif)
![07](https://user-images.githubusercontent.com/8266479/30548373-3a43d7aa-9ca7-11e7-84b6-75dccd316597.png)

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8154

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
