### ISSUE TITLE
[BUG] [UI] "<username> is typing" (in arabic یکتب...) alignment is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8180]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![03](https://user-images.githubusercontent.com/8266479/30548837-7b856fe8-9ca8-11e7-89ff-d7d44bc93e3d.png)

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
