### ISSUE TITLE
[BUG] [UI] "Unread message" alignment issue in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8181]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![04](https://user-images.githubusercontent.com/8266479/30549150-45ec5f1c-9ca9-11e7-90b8-402202ed5bc8.png)

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
