### ISSUE TITLE
[BUG] [UI] Replied message title alignment is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8182]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![05](https://user-images.githubusercontent.com/8266479/30549293-a4f84c32-9ca9-11e7-9193-4b8df31fcb33.png)
## Note:
**Green border** is correct (username in right and date in left)
**Red border** is incorrect (date in right and username in left)

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8154

**Comment by cyclops24** [comment]
@karlprieb , @rodrigok This is not fixed see below image:
![02](https://user-images.githubusercontent.com/8266479/30573815-2988e4a0-9d0b-11e7-8184-7eec5bde5586.png)

## Note:
**Green border** is correct (username in right and date in left)
**Red border** is incorrect (date in right and username in left) 
I think It's a float issue. (need `float: right`)

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
