### ISSUE TITLE
[BUG] [UI] Attachment icons alignment is incorrect

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8183]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
It's incorrect alignment in RTL mode (Arabic):
![06](https://user-images.githubusercontent.com/8266479/30549689-ad8ecfc8-9caa-11e7-9e39-df35a22b155f.png)
And it's correct alignment in LTR mode (English):
![6 1](https://user-images.githubusercontent.com/8266479/30549785-f6ca0c3e-9caa-11e7-86d2-52f3737db437.png)

**Comment by cyclops24** [comment]
It's also not align in LTR (English) See this:
![03](https://user-images.githubusercontent.com/8266479/30574083-e6ba759c-9d0c-11e7-99bc-9013cbd1c098.png)

@MartinSchoeler please label this as a bug :wink:

**Comment by engelgabriel** [comment]
@gdelavald this needs to be fixed before the release of the version `0.59.0`

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175

**Comment by cyclops24** [comment]
@engelgabriel  I done it. Please see #8271

**Comment by engelgabriel** [comment]
thanks @cyclops24 I'll merge it now
