### ISSUE TITLE
[BUG] [UI] Scrollbar has extra left padding in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8184]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
This is incorrect Scrollbar and we have extra left padding that incorrect because in LTR we haven't extra right padding.
![08](https://user-images.githubusercontent.com/8266479/30549878-2e8c49e8-9cab-11e7-88b0-071e58617836.png)
It's a correct LTR scrollbar because it doesn't extra right padding:
![8 1](https://user-images.githubusercontent.com/8266479/30550061-a30c2432-9cab-11e7-9be3-8a278e312006.png)

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8154

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
