### ISSUE TITLE
[BUG] [UI] Textbox menu position also is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8185]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![11](https://user-images.githubusercontent.com/8266479/30550263-267db01a-9cac-11e7-816d-96f149f410a2.gif)

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/8154

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
