### ISSUE TITLE
[BUG] [UI] Some bug in create room modal in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8186]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![12](https://user-images.githubusercontent.com/8266479/30550422-a9a6eb78-9cac-11e7-83ca-4b686df40f4f.gif)

**Comment by cyclops24** [comment]
This is also another alignment issue about this page:
![01](https://user-images.githubusercontent.com/8266479/30573598-10a006ae-9d0a-11e7-903b-ffabd6c68768.gif)

**Comment by cyclops24** [comment]
@karlprieb , @rodrigok Cross icon to cancel button on modal still has bug in Firefox 55:
![16](https://user-images.githubusercontent.com/8266479/30651283-7a86377e-9e3a-11e7-9436-ad7e43fd04a4.png)
Other parts fixed completely, thanks @karlprieb 😉

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
