### ISSUE TITLE
[BUG] [UI] Cross alignment is incorrect in search textbox in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8187]
Hey guys,
I found this bug in a chat with @ggazzo I think @karlprieb can join us here to solve this.
![14](https://user-images.githubusercontent.com/8266479/30550526-ee830484-9cac-11e7-9d8f-630e004e787d.gif)

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
