### ISSUE TITLE
Bitcoin donations

### ISSUE THREAD

**Issue by frabrunelle** [RocketChat/Rocket.Chat#819]
In the README, there is a section called [Donate](https://github.com/RocketChat/Rocket.Chat#donate), but it only contains a Paypal button.

I would prefer to make a bitcoin donation. Can you add a bitcoin address to the README? :smile: 

I'm following this project very closely and I like it a lot! Cheers.

Another thing to consider would be to use [Bountysource](https://www.bountysource.com/) to accept [monthly donations](https://salt.bountysource.com) from the community and let people post [bounties](https://www.bountysource.com/teams/rocketchat) on issues.

**Comment by engelgabriel** [comment]
Cool! I'll add a bitcoin address :)

I'll also investigate your other suggestions! Thanks, much appreciated.

**Comment by engelgabriel** [comment]
Added
