### ISSUE TITLE
[BUG] [UI] "User Info" buttons alignment is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8198]
Hi,
@karlprieb in "User Info" tab, buttons alignment is incorrect in RTL. See below image contain rulers:
![04](https://user-images.githubusercontent.com/8266479/30575480-5208b896-9d16-11e7-8335-3aa52da724cd.png)
We need space between buttons like LTR (English) mode:
![08](https://user-images.githubusercontent.com/8266479/30576442-29387bf2-9d1d-11e7-93e0-71a42e54542b.png)

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
