### ISSUE TITLE
[BUG] [UI] "Save Changes" button in preferences alignment is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8199]
Hi guys,
@karlprieb "Save Changes" button in preferences alignment is incorrect in RTL see below images please.
This is LTR (English) that is correct: 
![05](https://user-images.githubusercontent.com/8266479/30575881-01ea8db4-9d19-11e7-9797-434212a6eeca.png)
This is RTL (Arabic) that is incorrect and maybe related to [this line](https://github.com/RocketChat/Rocket.Chat/blob/5518bff8a8df7768a7af364fbe6e67135d5c0478/packages/rocketchat-theme/client/imports/general/base_old.css#L285) (`text-align: right;`):
![06](https://user-images.githubusercontent.com/8266479/30575897-26e6d334-9d19-11e7-94f2-ead92a504af0.png)

**Comment by cyclops24** [comment]
I think also it's better to add some `margin-bottom: 20px;` there like this:
![07](https://user-images.githubusercontent.com/8266479/30576022-172a7198-9d1a-11e7-98d5-168932a59ef4.png)

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175

**Comment by karlprieb** [comment]
Save button is on top header now and working fine on RTL
