### ISSUE TITLE
Cannot access general chatroom

### ISSUE THREAD

**Issue by steynvanesveld** [RocketChat/Rocket.Chat#82]
Actions: First adding and then removing the general chatroom from my favorites.

Result: I can't re-join the general chatroom. Message "You don't have permission to view this room" pops up.

**Comment by engelgabriel** [comment]
Thanks. What icon did you click? The "star", the "x" or the "exit"?

**Comment by steynvanesveld** [comment]
I can't reproduce the problem, but I think it was "Exit room".

**Comment by engelgabriel** [comment]
OK.. we are developing the missing ability to search and join channels... it will fix you problem. I'll let you know when it is done.

**Comment by sampaiodiego** [comment]
solved by #118
