### ISSUE TITLE
If the private room creator leave room cannot join back

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#820]
And the /invite command doesn't work on a private group

**Comment by sampaiodiego** [comment]
what you mean cannot join back? he must be invited by the new owner of the room.

**Comment by geekgonecrazy** [comment]
I think this is desired behavior.  If you leave you are no longer owner.  Who ever is in the room is now owner.

I think currently if just you in the room it doesn't allow you to leave.  But that's a completely separate thing.

**Comment by oinirio** [comment]
Now I understand the desired behavior.

Thanks
