### ISSUE TITLE
[BUG] [UI] "Members List" buttons and textbox alignments is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8200]
Hi,
@karlprieb in "Members List" tab, buttons and textbox alignments is incorrect in RTL. See below image contain rulers:
![10](https://user-images.githubusercontent.com/8266479/30576553-f2f0c968-9d1d-11e7-8711-c53b601e47b5.png)
We need space between buttons and a full width textbox below of them like LTR (English) mode:
![09](https://user-images.githubusercontent.com/8266479/30576580-0f82ad08-9d1e-11e7-8070-f0e5c3f0049b.png)

**Comment by cyclops24** [comment]
@karlprieb, This part also have another small alignment issue on RTL.
In LTR (English) space between buttons and textbox and below parts is less than RTL (Arabic)
Here is RTL:
![11](https://user-images.githubusercontent.com/8266479/30576698-d8ba9cda-9d1e-11e7-8d9a-42ae5dd955a4.png)
And it's LTR:
![12](https://user-images.githubusercontent.com/8266479/30576713-e71f25f2-9d1e-11e7-8ec7-39c05dab4718.png)

I think LTR approach (less space) is more beautiful and has better UX.

**Comment by gdelavald** [comment]
This issue will be moved to release 0.60 since the UI Redesign will change most of the sidebar layout.

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175

**Comment by ggazzo** [comment]
we dont have this screen no more, so I'm closing this issue. Any problem with rtl please let me know :)
