### ISSUE TITLE
[BUG] [i18n] "Members List" online users count not avaiable in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8201]
Hi,
@karlprieb in "Members List" tab, online users count not avaiable in RTL. See below images for more info.
Here in LTR (English) we have 3 value (green line: showing count, blue line: online count, orange line: total count)
![13](https://user-images.githubusercontent.com/8266479/30577038-ff4a772e-9d20-11e7-8468-9400dff3e027.png)
But in RTL we just have 2 value (green line: showing count, orange line: total count) and we miss online count
![14](https://user-images.githubusercontent.com/8266479/30577271-7462a01c-9d22-11e7-8ed0-cd8c5e210438.png)

**Comment by gdelavald** [comment]
This issue will be moved to release 0.60 since the UI Redesign will change most of the sidebar layout.

**Comment by cyclops24** [comment]
@gdelavald It's not related to UI it's a i18n bug about `Showing_online_users` key. 😉 
I try to fix it.

**Comment by karlprieb** [comment]
Hey @cyclops24 it's a translate problem :( Can you help us making a PR with the right translation? It's the `Showing_online_users` key.

In `en_US` we use three parameters on this key `"Showing_online_users": "Showing: <b>__total_showing__</b>, Online: __online__, Total: __total__ users"`, in `ar` instead we are using only two paramenters `"Showing_online_users": "معروض <b>__total_showing__</b> من __total__ عضو"`

**Comment by cyclops24** [comment]
Hi @karlprieb, Yes I can provide PR for it. :wink:

**Comment by cyclops24** [comment]
Part of #8175

**Comment by cyclops24** [comment]
@karlprieb I fix it in lingohub. Can you check it there?
