### ISSUE TITLE
[BUG] [UI] "Channel Setting" buttons alignment is incorrect in RTL

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8202]
Hi guys,
@karlprieb "Save Changes" button in preferences alignment is incorrect in RTL see below images please.
This is LTR (English) that is correct:
![15](https://user-images.githubusercontent.com/8266479/30577463-b265fb9c-9d23-11e7-810f-8728d577b59f.png)
This is RTL (Arabic) that is incorrect: (buttons must be align to left of the textbox)
![16](https://user-images.githubusercontent.com/8266479/30577472-baf27272-9d23-11e7-9bf3-84ba8ecc7972.png)

**Comment by gdelavald** [comment]
This issue will be moved to release 0.60 since the UI Redesign will change most of the sidebar layout.

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
