### ISSUE TITLE
[Question] Personal email gateway (GSoC'17) #7342

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#8206]
Hello rocket.chat team, 

Eagerly waiting for the next stable release which contains this
https://github.com/RocketChat/Rocket.Chat/pull/7342

With the above, will I be able to post a new message (non-reply) into a channel via email or does this work only when responding to an offline notification?

Thanks for your help.

**Comment by pkgodara** [comment]
@akachapati As par now, Only responding (reply) to offline notifications is supported. Posting into channel is a good feature to implement in future. :)

Next stable release will take some time, UI has changed completely, so continous bug fixes coming up.

**Comment by pkgodara** [comment]
Close #8206

Kindly use demo.rocket.chat for questions. You would get faster replies..
