### ISSUE TITLE
Clipboard doesn't work.

### ISSUE THREAD

**Issue by akky0001** [RocketChat/Rocket.Chat#8212]
### Description:

Clipboard doesn't work on version 0.59.0-rc5 and rc6.
It works on version 0.59.0-rc4. https://github.com/RocketChat/Rocket.Chat/pull/8039

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc6
* URL: https://demo.rocket.chat (This incident also occurs on your demo site.)

### Steps to Reproduce:

1. Access demo site using web browser.
2. Copy the message using copy button.(Or "Permalink")
3. Try to paste the message.(ctrl+v)
### Expected behavior:

Can paste the message.
### Actual behavior:

Cannot paste the message.
### Relevant logs:

None.

**Comment by jszaszvari** [comment]
Just tested and can confirm. 

Using Chrome and Firefox.

**Comment by akky0001** [comment]
Hi,
Does your "confirm" mean "can paste", or "cannot paste"?
I also use Chrome and Firefox.

I tested again after clearing cache.
But This incident occurred again.

**Comment by Rzeszow** [comment]
I cannot paste.

**Comment by mychecknix** [comment]
I have a similar problem with the clipboard.

I use xubuntu with xfce and Rocket.Chat 2.9.0:

I mark text outside of Rocket.Chat an paste it into the chat-input-fild (which i cannot resize…) with the middle mouse button. If I am fast it works. After 5-10 seconds it does not paste what I marked, it pasts a older value what I have had in the clipboard before. I also have the same problem with ctrl+v.
