### ISSUE TITLE
Reaction button is hard to see

### ISSUE THREAD

**Issue by jblobel** [RocketChat/Rocket.Chat#8217]
### Description:
It's a UI/UX design problem.
With the new UI, the reaction button has been redesign. It had been pushed away to the other side of the screen.
It is pretty hard to see because it is a small light grey icon on white , and the fact that it is on the right side on the screen while the message is on the left side makes it pretty easy for the user to miss it.

### Server Setup Information:

* Version of Rocket.Chat Server: current demo version https://demo.rocket.chat/ (0.58 or 0.59 ?)
* Chrome Desktop

### Steps to Reproduce:

1. Put your mouse over a message
2. Look at the button

![image](https://user-images.githubusercontent.com/6414633/30643393-0529dca4-9e0f-11e7-9637-74c1637e48b9.png)

### Expected behavior:

I can think of two solutions for this  : 
1 - the "slack" way. Obviously the redesign is inspred by slack, who puts the reaction button at the same place. But it is far more readable, because it is bigger and put in a box. Like this : 
![image](https://user-images.githubusercontent.com/6414633/30643877-d21e35d8-9e10-11e7-8c07-f3fa74c96988.png)
That's good because people are used to slack

2 - the "old" way. In previous versions of Rocket.Chat, the reaction button used to right next to the time : 
![image](https://user-images.githubusercontent.com/6414633/30644018-4210d170-9e11-11e7-9332-69f4affebc3f.png)
That's good because it keep context : it is right next to the message, so I know what I am doing.

I would prefer the second option, but both sounds good.

What do you think ?

**Comment by engelgabriel** [comment]
We can try to make them more visible on the right. I'll ask our UX team.
