### ISSUE TITLE
"Read Only Channel" radio button always disabled in "Create a New Channel" modal

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8224]
Hi guys,
Why we need "Read Only Channel" radio button in "Create a New Channel" modal?
It's always disable so why it's there?
![17](https://user-images.githubusercontent.com/8266479/30651612-7cab52a4-9e3b-11e7-81f5-5423fc1b727d.png)

**Comment by geekgonecrazy** [comment]
@cyclops24 i've just renamed the issue.  I'm not seeing a case where its ever enabled.  Even as an Admin on the system it seems to never be able to be toggled
