### ISSUE TITLE
Enters channel when clicking action button on channel nav

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8225]
### Description:
If you click the action button on a channel to hide or leave it enters the room.

Also in case of when in collapsed the side bar disappears when you click it and you get this:

![image](https://user-images.githubusercontent.com/51996/30653400-9879cdee-9df0-11e7-9b17-5329a746d064.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.7
Community server specs :)

### Steps to Reproduce:

1. Hover the channel you want to leave or hide
2. Click the action buttons
3. Click leave or hide

### Expected behavior:
Should not enter the channel, it should simply open the pop up

### Actual behavior:
Enters channel and if using reduced size it collapses nav and leaves the popup floating awkwardly in space.

**Comment by karlprieb** [comment]
Fixed by #8243

**Comment by geekgonecrazy** [comment]
@karlprieb if side nav is collapsed and you open and click to bring the menu up it still collapses nav leaving the box floating in space.

It no longer enters channel. So that part is fixed.  But still causes nav to collapse on click
