### ISSUE TITLE
Hovering over channel makes mentions disappear

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8226]
### Description:

Hovering over channel makes mentions disappear and replaced by action button

Before hover:
![image](https://user-images.githubusercontent.com/51996/30653792-ac1c1dd8-9df1-11e7-8829-053ee74a8d7a.png)
During hover:
![image](https://user-images.githubusercontent.com/51996/30653812-b901a87e-9df1-11e7-92d6-12fc8cdfd50d.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.7
Community Server

### Steps to Reproduce:

1. Hover over a channel with mentions

### Expected behavior:

Mentions shouldn't disappear

### Actual behavior:
Mentions disappear

**Comment by graywolf336** [comment]
Confirmed
