### ISSUE TITLE
[BUG] "Leave Room" return "Internal Server Error"

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8227]
Hi @karlprieb ,
When I click on a chat action button and click "Leave Room" it's return "Internal Server Error". See this:
![19](https://user-images.githubusercontent.com/8266479/30653938-bc5eec52-9e41-11e7-8b6c-12a0b11638c1.gif)

**Comment by geekgonecrazy** [comment]
Technically here it shouldn't even be allowing you to leave, only to hide it.
