### ISSUE TITLE
Group video call not working - redirects them to audio call

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#8228]
### Description:

Three users who are all able to have one-to-one video calls with each other formed a private group and attemped a video call.  It didn't throw an error, it just automatically routed them into a group audio call instead.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.58.1
* Operating System:  Linux
* Deployment Method(snap/docker/tar/etc):  Heroku Dyno
* Number of Running Instances:  1 
* DB Replicaset Oplog:  Enabled
* Node Version:  v4.8.4

**Comment by flantascience** [comment]
Hmmm - looks like that worked.   Was I doing something wrong before?

**Comment by tlebris** [comment]
Not at all, it's an old bug #3413
