### ISSUE TITLE
Implement Unit Testing

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#8229]
Refactor Functions and add to CI

**Comment by engelgabriel** [comment]
Initial tests implemented. Now need to improve code coverage

**Comment by decko** [comment]
Guys, there is somewhere we could find more about this issue? I would love to contribute to Rocket.Chat's test infrastructure but I can't find issues about this(Ok, only this one). Maybe a label?
Also, some dev want to talk or write about it?
