### ISSUE TITLE
Display "last seen" information for not online users

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#823]
I think it's sometimes useful to know since when user was not online. 

Support for displaying the last time user was seen online would be nice to have feature.
##

**Comment by k0nsl** [comment]
:+1:

**Comment by marceloschmidt** [comment]
That's available for admins. Not too hard to make it available for all.

**Comment by cyclops24** [comment]
+1

**Comment by ccfang** [comment]
@rockneverdies55 This issue should already be provided when open the permission `view-full-other-user-info`

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @rockneverdies55 

> Support for displaying the last time user was seen online would be nice to have feature.

I'm not sure, whether there exists data collection to provide you with the time a person was last **active**. Currently the time that can be seen by getting assigned the `view-full-other-user-info` privilege is taken from MongoDB collection `users`, the attribute (dunno if that's the correct terminology) is called `lastLogin` and reflects the last actual successfull login process.

So I think the "feature" you requested already exists. If you do not agree, please let me know :)

Cheers
Thomas

**Comment by tahajahangir** [comment]
"Last seen" or "last online" time **is not** last login time. Users may have open sessions for days or weeks. Many messaging platforms (e.g whatsapp or telegram) provide precise last online time (e.g _3 minutes ago_).

@TwizzyDizzy This is a separate feature (and also may need server side implementation to store last online time in a high-write-capable db, e.g redis). I think the issue can be reopened (and should not have `subj: ui/ux` tag).

**Comment by vynmera** [comment]
This should really be reopened. Last seen is very, _very_ useful for teams!

Last login is not accurate to last seen, last seen should be based on something like our autoaway, not session logins, durations, etc.

Furthermore, **we need to keep from abusing `view-full-other-user-info`**. I can't stress this enough, but that permissions is an insecure overkill.
Using that permission, you can for example find out whether someone is "invisible" or actually offline. Something you really don't want!!

**Comment by Tayyaba03** [comment]
Hi, I have a question where do you see user info if `view-full-other-user-info` is turned on. As for me, I don't see the last login details of the user on user info.

**Comment by BenWiederhake** [comment]
This indeed should be reopened.  Humans tend to be reachable in multiple ways, and this indicator is a easy and rather reliable way to tell when the other person will be online again.  "Last seen 7 months ago"?  Ah, better write a mail.  "Last seen 3 hours ago"?  Great, they actually use our group's slack instance!

From what I gather, the info is already there in the database, and users can easily opt-out by setting their status to "invisible". What's stopping this feature?  Just lack of motivated implementers, or something else?

**Comment by dormeiri** [comment]
Please reopen this issue, it is really necessery. We want to know if the users actually use our chat

**Comment by httpsOmkar** [comment]
+1

**Comment by NextPageDevelopment** [comment]
+1

**Comment by m-roshani** [comment]
+1

**Comment by pokapow** [comment]
I confirme, the only way to know for me is scraping my nginx logs and match IP with rocketchat users ...

**Comment by DocSauer** [comment]
> This indeed should be reopened. Humans tend to be reachable in multiple ways, and this indicator is a easy and rather reliable way to tell when the other person will be online again. "Last seen 7 months ago"? Ah, better write a mail. "Last seen 3 hours ago"? Great, they actually use our group's slack instance!
> 
> From what I gather, the info is already there in the database, and users can easily opt-out by setting their status to "invisible". What's stopping this feature? Just lack of motivated implementers, or something else?

+1
