### ISSUE TITLE
Using Rocket.Chat in an existing app.

### ISSUE THREAD

**Issue by trusktr** [RocketChat/Rocket.Chat#8238]
Hello, I'm curious to know about using RocketChat in an existing Meteor app. The db stuff is reactive, so in theory I could make other chat widgets that could feed into the live chat room of Rocket.Chat. I'd like to make an app that has small chat widgets associated with various parts of the UI, as well as the whole Rocket.Chat experience.

- How easy is it to make Rocket.Chat run on a sub-route of the main app?
- Are any of the existing widgets easy to use outside of Rocket.Chat? For example, is the chat view a component that I can re-use and stick it somewhere else?

F.e., suppose I want to make a kanban board, and inside the board is chat associated with that board, or inside each card might be card-specific chat, etc. I'm evaluating how flexible Rocket.Chat might be for such custom sorts of chat features, or if I should just make my own. :)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
