### ISSUE TITLE
Annoying Hide/Leave Rooms buttons - please back to previous 

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8239]
### Description:

New Hide/Leave Rooms buttons require 2 clicks to select each option instead 1. This is very annoying because you waste your time clicking if you have many conversations with different people each day. Everyone in my team will hate this so I can't upgrade to 0.59 if this function will work like that.. Please make it like in 0.58.* versions. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.7
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: ~
* DB Replicaset Oplog: ~
* Node Version: ~

### Steps to Reproduce:

1. Click "3 dots" on left side
2. Select Hide/Leave

### Expected behavior:

1. Click Hide or Leave.

**Comment by jblobel** [comment]
On the contrary, I think leaving / hiding a channel was too easy.

Channel shouldn't be created and deleted on the go just for short conversations. They should serve a purpose and live long lifes.
You don't want people to come and go as they please, you want people to joint teams, to join groups, projects and stick with it.
I don"t say that they should be prisonners, but they shouldn't be invited to quit channels too early.

If you look at the slack approach, it goes like this : 
![image](https://user-images.githubusercontent.com/6414633/30701649-14225704-9eeb-11e7-9b3b-9603ff62c80e.png)
1 you click on the gear icon
2 you scroll all the way down to quit a channel

It's uneasy, but it encourage people to stick in the channel, to get involve.

In RC previous versions, users could leave or hide channels by incident. Now it's a little bit better, but it could still happen. Furthermore, as it is the first option you see next to a channel name, users are encourages to leave channels.
I guess the new approach (hidden in a menu) is inspired by Facebook : 
![image](https://user-images.githubusercontent.com/6414633/30701946-e5efd0c2-9eeb-11e7-9bff-2cefbda1af6f.png)
where you foolow the same pattern : 1 -  click on the hamburger menu, 2 - click on "leave group"
I would prefer the slack approach, but anyway, new UI is an improvement on that point. Good work guys :)

**Comment by Venomen** [comment]
Yeap, but people in my work are using Rocket.Chat that way (~300 people registered in Rocket):
- top left side "unreaded new messages" from Unread Rooms Mode
- mid left side "Favourites" contacts, people you talk very often and you wan't to have them "open"
- below Favourites - Channels that you are involved
- down left bellow Channels - Direct Messages - people that you don't talk often, but you have some tasks with them to do, so you make it open till task is complete, then you close it. And this is the most important thing: you don't want to have them open, bacause we will have them a lloooooot, so you close it after completed task/talk. Thats why we need that option HIDE/LEAVE so fast in 1 click.

We have tested many contact/view options about rooms and priv/direct channels, and this is the best way to using rocket in our work with ~ 300people in Rocket.Chat :)

**Comment by engelgabriel** [comment]
@Venomen the idea is that we will have many other quick actions on that menu.. like MUTE, MARK AS READ, NOTIFICATION LEVEL, ETC...

Do you think that having the HIDE button on the heading of that channel would work for your use case? So when you finish the task, you have a single click on the channel header.

What do you think?

**Comment by Venomen** [comment]
Yeap, if HIDE button will be near that DirectMessage name, then it would be great.

**Comment by rodrigok** [comment]
@Venomen What if we have an option to automatically hide inactive rooms like skype does?

**Comment by SakakiOftech** [comment]
I want the direct message with inactive user to be hidden automatically.

**Comment by ggazzo** [comment]
hey @Venomen, we are releasing a slash command `/hide` and I'm thinking in create an option "Do not ask again" (for hide rooms) what do you think?

**Comment by Venomen** [comment]
@ggazzo hello, yeah, thats even better idea ;-) 
btw offtopic: we have ~400 active users atm, and mongo is kinda slow when it comes to some deep searching, you guys thinking about switching to some postgresql or other faster db solution?

**Comment by ggazzo** [comment]
what kind of search?

**Comment by Venomen** [comment]
@ggazzo any search in conversations for example (when a lot of people are connected) can be even 30-60sec. Cpu, mem & disks are ok. It could be our rocket db size (~4GB) but still it's slow.

**Comment by engelgabriel** [comment]
@Venomen by "deep searching" you mean regular expressions? Maybe we are missing a full text search index?

**Comment by Venomen** [comment]
@engelgabriel I mean any search. Maybe this would help, generally searching in Rocket is just slow. Some additional caching should be involved if it has to be MongoDb?
