### ISSUE TITLE
Put please contacts with unread messages on top

### ISSUE THREAD

**Issue by vmacari** [RocketChat/Rocket.Chat#8240]
### Description:

Every time I see a notification about unread message, I have to search  WHO WROTE ? 

Please, move contacts with unread messages on top, and keep them into a FIFO, as all chats do.

### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by jblobel** [comment]
"as all chats do", do you have a concrete example ? Some screenshots ?

**Comment by vmacari** [comment]
Sorry, I mean "as all other messengers do".

Skype for example, moves chats/contacts with unread messages on top of the list.

Thank you.

**Comment by gdelavald** [comment]
@vmacari This might be what you are looking for, Unread Room Mode, check the preferences for this option:
![image](https://user-images.githubusercontent.com/6303966/30701347-6fdbcd6c-9ec0-11e7-9aca-bc6fc07f2bca.png)

**Comment by vmacari** [comment]
Thank you. Was hard to find those prefs on Darwin. 

In my account ... Unread Rooms Mode True/False ... 

Would be great if Preferences are accessible from Top bar system menu. 

Thank you

**Comment by gdelavald** [comment]
@vmacari Please add the suggestion as an issue in the Electron [repository](https://github.com/RocketChat/Rocket.Chat.Electron)
