### ISSUE TITLE
[i18n] Added the ability to translate "Click To Join!"

### ISSUE THREAD

**Issue by Rzeszow** [RocketChat/Rocket.Chat#8249]
https://github.com/RocketChat/Rocket.Chat/blob/336f9c7a080d64a483f63054919efe4c2b2badca/packages/rocketchat-videobridge/server/methods/jitsiSetTimeout.js#L18

**Comment by MartinSchoeler** [comment]
@Rzeszow That is great! Could you create a pr for this?

**Comment by Rzeszow** [comment]
No sorry. At this moment i don't have a time.

**Comment by cyclops24** [comment]
Part of #8175
