### ISSUE TITLE
Audio call Only

### ISSUE THREAD

**Issue by SatvinderSinghNC4** [RocketChat/Rocket.Chat#8256]
### Server Setup Information:

* Version of Rocket.Chat Server:0.58.2
* Operating System:Linux-Centos7
* Deployment Method(snap/docker/tar/etc):tar
* Number of Running Instances: 1
* DB Replicaset Oplog:disabled
* Node Version: 4.5.0 - x64 

### Steps to Reproduce:

1. Log in
2.  Go into a Channel
3.  Do a direct message

### Expected behavior:

There be an option for audio call only
### Actual behavior:

In direct message or channel, there is no option for Audio Call only, only see the option for video call.

**Comment by jacobkjhan** [comment]
Hi! Could I try to tackle this using WebRTC?

**Comment by mmickelson** [comment]
I would LOVE to see this option. My team never uses video, just audio.

Is there an update?

**Comment by yuritoledo** [comment]
+1

**Comment by marceloschmidt** [comment]
This is planned to be implemented sometime in the future via a SIP integration.

**Comment by Toub** [comment]
What about a "call" button starting existing video service, with video disabled by default? Similar to slack behavior.

Then the user can switch to video later, if necessary.

**Comment by danger89** [comment]
+1

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Implemented the latest and maintained releases.

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
