### ISSUE TITLE
Translation not showing for Hide_Livechat_Warning

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8263]
### Description:

![image](https://user-images.githubusercontent.com/51996/30769562-16986590-9fe1-11e7-9167-7de721d1de60.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.8
Community Server

### Steps to Reproduce:

1. Click to hide livechat

### Expected behavior:
Should show translation message

### Actual behavior:

Shows `Hide_Livechat_Warning`

### Relevant logs:
None

**Comment by geekgonecrazy** [comment]
@karlprieb not sure why this isn't showing for this one.  Seems to show for the rest of the hide / leave

**Comment by karlprieb** [comment]
@geekgonecrazy here is working. Could you wipe your cache and test again?

![image](https://user-images.githubusercontent.com/9200155/30826861-68bd086a-a20e-11e7-8ad0-93d1c6b6bcac.png)

**Comment by sampaiodiego** [comment]
it might be something related to our build cache..

I would suggest to not use travis cache on tag builds to avoid this kind of error, @RocketChat/core what do you think?

**Comment by geekgonecrazy** [comment]
This sounds right.   Building after clearing meteor build cache it works right.  But going through travis it doesn't.   Is there a way to have just the translation stuff invalidated in the build cache?

**Comment by engelgabriel** [comment]
https://forums.meteor.com/t/weird-behaviour-of-tap-i18n-package/15454/10

> Thanks for that info! At least this is a better workaround than doing a full meteor reset, as I am doing now.

**Comment by geekgonecrazy** [comment]
so looks like just deleting `.meteor/bundler-cache` might do the trick

**Comment by engelgabriel** [comment]
The issue is that the i18n package is the package that takes longer to build :( 

If we are building it on every PR, they will all take a lot longer.
