### ISSUE TITLE
[BUG] [UI] Sidenav selected color not readable

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8264]
Hi guys,
Sidebar selected color not readable. I think it's related to #8255 , #8257  See below gif:
![peek 2017-09-23 09-37](https://user-images.githubusercontent.com/8266479/30770685-6636f0f0-a043-11e7-97a3-1847228ab085.gif)

**/CC:** @ggazzo , @rodrigok

**Comment by engelgabriel** [comment]
Needed to reset the setting, as we have not implemented the migration yet.

`Admin -> Layout -> Customize Theme -> RESET` and `SAVE`

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
