### ISSUE TITLE
[BUG] [i18n] "Create Channel"  modal placeholders not translatable

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8268]
Hi guys,
Channel name placeholder not translatable. See [this line](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/views/app/createChannel.html#L42) (`placeholder="Type channel name"`)

**/CC:** @karlprieb , @rodrigok , @ggazzo

**Comment by cyclops24** [comment]
"username" at in [this line](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/views/app/createChannel.html#L66) (`placeholder="{{_ "username"}}"`) also not contain value and this key not exist in `en.i18n.json` file.

**Comment by engelgabriel** [comment]
Part of https://github.com/RocketChat/Rocket.Chat/issues/8175
