### ISSUE TITLE
"Jump to" in search results

### ISSUE THREAD

**Issue by robhawkins** [RocketChat/Rocket.Chat#827]
How tough would it be to add a "jump to" or "skip to" feature to the results of search?  It would be handy to be able to see the context around search results by clicking on some link or the time.  Cheers!

**Comment by rophy** [comment]
+1

**Comment by boisletterink** [comment]
Very similar to #1550, and also related to #1942.

**Comment by rophy** [comment]
It seems this was recently implemented by #1749.

**Comment by Sing-Li** [comment]
@rophy - thx :+1:
