### ISSUE TITLE
RocketChat LiveChat DDP Documentation

### ISSUE THREAD

**Issue by bhagaban** [RocketChat/Rocket.Chat#8276]
Hi, Would be great if you update the Realtime LiveChat Documentation with more information. 

https://rocket.chat/docs/developer-guides/realtime-api/livechat-api/sendmessagelivechat

_`{"msg":"method","method":"sendMessageLivechat","params":[{"_id":"XqEEHhQHvhFmK3Zoz","rid":"TT9iMmzusfcLq8sv2","msg":"test","token":"7T4jzes7rX3Fr6cQ2"}],"id":"11"}`_

What does **_id** here represent ? Is it the _**userId**_ collected in the previous steps ?
What does **token** here represent ? Is it the _**token**_ collected in the previous step ?
What does **"id":"11"** refer to ?

Also the offline Message documentation is missing.

https://rocket.chat/docs/developer-guides/realtime-api/livechat-api/sendofflinemessage

**Comment by shraddharsh** [comment]
Hi,
I have been trying to figure out how is rid generated on client side.
Whenever I send a random string I get an error stating 400 error regarding Meteor matching 
Can someone help me out?

**Comment by renatobecker** [comment]
Hi @shraddharsh.

Please, share your code here, it will help us to reproduce the steps your have been doing.
Thanks.

**Comment by shraddharsh** [comment]
Hi @renatobecker ,
It was my bad, I have been sending improper token on wrong array index and that was causing the issue.
Thanks for your response anyway.
