### ISSUE TITLE
Room unread status not showing

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#8279]
### Description:

Room unread status not showing even though they have unread messages.

### Server Setup Information:

demo server, 0.59.0-rc.8

Both dev and support channels have unread messages still shown normal as below.

![screenshot from 2017-09-24 16-56-54](https://user-images.githubusercontent.com/16938349/30782133-9f019b86-a149-11e7-82f5-8497319e5821.png)

### Expected behavior:

Room names having unread messages should be highlighted.

**Comment by engelgabriel** [comment]
Bug created on https://github.com/RocketChat/Rocket.Chat/pull/8257
