### ISSUE TITLE
Create a cog or other icon for dropdown actions on message

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#828]
Available actions: edit, delete, star, pin

**Comment by marceloschmidt** [comment]
We need someone with design/ui skills to get that done. @AdrianoCahete @geekgonecrazy any volunteers? :)

**Comment by AdrianoCahete** [comment]
I'll see this weekend.... If @geekgonecrazy want to see it before, np!

**Comment by geekgonecrazy** [comment]
closed via #831
