### ISSUE TITLE
Screen Share MAC Client

### ISSUE THREAD

**Issue by SatvinderSinghNC4** [RocketChat/Rocket.Chat#8281]
### Description:

Rocket Chat Mac Client

### Server Setup Information:

* Version of Rocket.Chat Server:0.58.2
* Operating System:Linux CentOS7
* Deployment Method(snap/docker/tar/etc):tar
* Number of Running Instances: 1
* DB Replicaset Oplog:disabled
* Node Version:4.5.0 - x64

### Steps to Reproduce:

1. Install the mac client (Version 2.9.0)
2. Start a Video conference
3. Do screen share

### Expected behavior:

See windows to select what you want to share

### Actual behavior:

When you hit share on entire screen nothing happens, on the Tab for application no window shows up.
This works on the web instance.

**Comment by SatvinderSinghNC4** [comment]
The behavior is the same in the windows client as well. Tried on 2.9.0..

**Comment by MartinSchoeler** [comment]
This seems to be a desktop app problem, please reopen this [here](https://github.com/RocketChat/Rocket.Chat.Electron) Thanks!
