### ISSUE TITLE
[Feature] Mumble Web into the Toolbar (right)

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat#8285]
Here is a nice project called Mumble_Web https://github.com/Johni0702/mumble-web

It works fine 4 me and would like a great idea to include this into the right toolbar like Jitsi Meet.

The greatest one will to include this with authentication between channelname / username from RocketChat.

**Comment by bott0r** [comment]
This would rival more voice focused applications such as discord. I hoped for a little inspiration from discord towards RC :D

**Comment by DoM1niC** [comment]
Yes indeed :)

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
