### ISSUE TITLE
Few UI bugs at 0.59.0-rc.*

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8288]
### Description:

As on screenshot:
1. Problem with highlight color when room is selected
2. Old-ugly color at left servers bar

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.8
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: ~
* DB Replicaset Oplog: ~
* Node Version: ~

![screen](https://user-images.githubusercontent.com/3985913/30798794-1ace863e-a1db-11e7-94e8-d8566da9c057.png)

**Comment by rodrigok** [comment]
@Venomen About the second item, please take a look at this issue https://github.com/RocketChat/Rocket.Chat.Electron/issues/513 it's related to another project, the desktop app (Electron)

**Comment by engelgabriel** [comment]
For problem 1, you needed to reset the setting, as we have not implemented the migration yet.

`Admin -> Layout -> Customize Theme -> RESET` and `SAVE`
