### ISSUE TITLE
User name clipping on line height on account box

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#8289]
### Description:

**On Chromium + Firefox:** The color of an active private message in the sidebar is just "grey". If you hover over it with the mouse, it looks like it seems to be intended.

Only in Firefox: the sidebar alignment error from #8129 seems to have re-appeared. Glyphs in sidebar are visible. Also on firefox, the descenders of glyphs in the sidebar (for example the @ from the username handle is cut off on the bottom, **this time only your own username at the top of the sidebar**)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.8
* Operating System: Oracle Linux 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4

### Steps to Reproduce:

Not really applicable, as UI bug. See screenshot below.

### Expected behavior:

Not really applicable, as UI bug. See screenshot below.

### Actual behavior:

![error](https://user-images.githubusercontent.com/179595/30799974-d2d26e78-a1de-11e7-8e9b-d908643e00f4.png)

### Relevant logs:
Not really applicable, as UI bug. See screenshot above.

**Comment by TwizzyDizzy** [comment]
Still present in 0.59.0-rc.12

**Comment by himbeere** [comment]
and in rc13 present too. but i guess the devs are aware of this.

**Comment by himbeere** [comment]
Uh and this bugs affects the channel names too here.

**Comment by TwizzyDizzy** [comment]
Oh. Yeah, correct. Should've mentioned that in the initial post.

**Comment by himbeere** [comment]
I guess you could adjust the subject still?

**Comment by TwizzyDizzy** [comment]
I have reset all my layout settings. It turns out, that the initial problem "grey channel names" must have come from my settings. Anyway. Having reset every layout setting, the following problems persist:

![image](https://user-images.githubusercontent.com/179595/31775757-c0ba25fa-b4e9-11e7-9a23-e0e5a247a17a.png)

**Comment by cyclops24** [comment]
Maybe related: #8264

**Comment by TwizzyDizzy** [comment]
Hi @rodrigok,

I have to reopen this, as the scrollbar issue in the Firefox Window below is still (not again, it has been ever since) present in 0.60.0-rc2. The issue in the sidebar has been fixed though.

![](https://user-images.githubusercontent.com/179595/30799974-d2d26e78-a1de-11e7-8e9b-d908643e00f4.png)

Cheers
Thomas

**Comment by rodrigok** [comment]
@TwizzyDizzy @karlprieb told me that this scroll bar in Firefox is an expected behavior.

**Comment by karlprieb** [comment]
All browsers have scrollbar. The difference is that in Chromium the scrollbar have a css style.

**Comment by TwizzyDizzy** [comment]
> All browsers have scrollbar. The difference is that in Chromium the scrollbar have a css style.

Exactly: in Firefox the scrollbar is also there (and works), yet it is white and thereby "breaks" the layout.

Cheers
Thomas

**Comment by rodrigok** [comment]
@TwizzyDizzy I agree it's a layout problem, but since it's not an urgent issue I'll keep it open but move to the next release.

**Comment by TwizzyDizzy** [comment]
I agree on the urgency. Glad though, that I'm not using Firefox and my OCD will not trigger everytime I use that chat :D

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #10047. The issue remaining in the issue at hand is the same is described there - with a lot less clutter than here (because another issue has been solved here).

Cheers
Thomas
