### ISSUE TITLE
Bug: force autoinvite user to channel by mention his username in channel

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8290]
### Description:

If you write msg on some channel with mention his username -  @User.Rocket.Chat.Name - he will be automatically added to channel and even if he leave, you still can do this action again (and again, and again :d ) and add him anytime you want - just by mentioning his username ;d. 

### Server Setup Information:

* Version of Rocket.Chat Server: any
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: ~
* DB Replicaset Oplog: ~
* Node Version: ~

### Steps to Reproduce:

1. Go to any channel
2. Write msg on channel containing some username
3. Watch how this user is auto-added to channel
[[ 4. If he leave, just do this again to make him angry :) ]]

### Expected behavior:

1. Go to any channel
2. Write msg on channel with mention user name
3. **Send notify** to this user and let him decide - if he wants to be added to channel in that way (or some other solution, it's just my simple proposition)

**Comment by Venomen** [comment]
Its ok now in 0.59.1 , you can close this.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
