### ISSUE TITLE
CAS - Add support to specify certification authority cert

### ISSUE THREAD

**Issue by urrusjm** [RocketChat/Rocket.Chat#8293]
### Description:
i'm experiencing some issues with CAS and certification authority certs.
After i login in CAS from rocketchat service i get an error "no matching login attempt found". When i set logs to debug i get:
rocketchat_logger rocketchat_logger.js:376 [34mCAS ➔ debug Using CAS_base_url: https://cas.htc.ar/cas/ 
rocketchat_logger rocketchat_logger.js:376 [31mCAS ➔ error error when trying to validate: unable to verify the first certificate 

The CAS certificates are from COMODO, there are not self signed certificates, but it's seems like rocket chat or nodejs don't have the ca-certificates in the store.

is there a way to manually specify the path to a ca-certificate?
if not, would be a good improv for cas deployments.

### Server Setup Information:

* Version of Rocket.Chat Server:0.58.2
* Operating System: debian 9
* Deployment Method: snap
* Number of Running Instances :1 
* DB Replicaset Oplog:
* Node Version:v4.8.3

**Comment by hugocostadev** [comment]
Is this still the case?  Sorry for the late reply 

Check the CAS docs: https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/cas

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by hugocostadev** [comment]
Hahahaha going back to old issues and triaging them! Thanks
