### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by SatvinderSinghNC4** [RocketChat/Rocket.Chat#8294]
### Description:

If you have a user created locally, and delete it, if you add it back again as the same user name either locally or through LDAP, you will not be able to log in, it will keep saying unknown user or incorrect password
### Server Setup Information:

* Version of Rocket.Chat Server:0.58.2
* Operating System:Linux (CentOS 7)
* Deployment Method(snap/docker/tar/etc):tar
* Number of Running Instances: 1
* DB Replicaset Oplog:disabled
* Node Version:4.5.0 - x64

### Steps to Reproduce:

1. Delete a user though the UI
2. Add the user back in either locally or through LDAP
3. 

### Expected behavior:

 You should be able to log in

### Actual behavior:

If you have a user created locally, and delete it, if you add it back again as the same user name either locally or through LDAP, you will not be able to log in, it will keep saying unknown user or incorrect password

**Comment by TwizzyDizzy** [comment]
Please make sure, that you are not experiencing the error mentioned in #7405. LDAP authentication has been broken in some cases (when fetching an avatar from LDAP) and has just recently been fixed in RocketChat 0.59.0-rc.5.

Cheers
Thomas

**Comment by SatvinderSinghNC4** [comment]
That was is, i enabled Sync users, and disabled sync avatar and now i can log in.

Thank you for your help, you guys are awesome.
