### ISSUE TITLE
change default notification settings while creating rooms

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#8297]
Would be nice to be able to set/change default notification sending settings when creating rooms (or even later if admin)

There are times we need some rooms to be sending notification to every attendee on each message post.  

To be able to set room's default notification setting to accomplish that would be more convenient than typing *at-all* in each message (not everyone doing it or forgetting to type it) or telling/warning people *hey do this to change your personal notification receiving settings so that you get notification on every message*.

**Comment by marceloschmidt** [comment]
Users have default preferences that an admin should not override. We don't think this would be a good practice.

**Comment by rockneverdies55** [comment]
I meant admin sets the baseline (the defaults) on creation. Then users override those later on if they want to.

**Comment by darkpal** [comment]
+1 For example I create a private room called "announcements" and every message in this room should trigger notifications for all users without need to use @all. So it would be nice to have possibility to override (once or permanent) global notification settings for specific rooms.

**Comment by dormeiri** [comment]
+1
