### ISSUE TITLE
Capture a "Message Flow" and send to Knowledge Base

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#830]
In the DEMO room, knowledge is often shared by members that can be useful for others.

But once the message flow scrolls off screen - it is unlikely to be ever found again.

Implement a way to capture and send a message flow to - a  knowledge-base, forum, or FAQ.
##

**Comment by takavfx** [comment]
Yes, it always happen at conversations among a lot of people engaged.

How about build integration connects between forum systems like Discourse?
But I'm not sure how could I make it.

I hope that it's coming soon.

**Comment by erlend-sh** [comment]
I posted a video and screenshot in #6583  of how we currently do this with Slack-Discourse.

**Comment by timkinnane** [comment]
Just ping to say I'm interested in developing this. Currently working on new bot features for workflows like this, so it could be a way to demonstrate that value. But it could be a couple months away. ...oh... I just noticed the original date. haha, hopefully can wait a tad longer :P

**Comment by timkinnane** [comment]
Closing this issue to clean backlog of bot/integration suggestions, collected now under #10174
