### ISSUE TITLE
Move Tab Bar icons to Top Bar

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#8301]
### Description:
Modify the header component to add the quick access items.
Add the popover with the toolbar items.

[Link to design](https://projects.invisionapp.com/share/TKC46XUZB#/screens/238383977)

**Comment by ggazzo** [comment]
see here #7750

**Comment by mrsimpson** [comment]
Hiding options which are often used by a particular user behind the three dots is a step backwards for many.
It was super useful if the displayed components were customizable (per user). Ideally, one could open the drawer and then drag the required tool to the toolbar.

**Comment by gdelavald** [comment]
@mrsimpson Thanks for the feedback.
The plan is to be able to customize the toolbar in a way that the user has access to his own most used features the way he wants, however I understand your concern about the usability there.
Perhaps @engelgabriel can explain the decision behind this.
CC @arthurgiustina

**Comment by HammyHavoc** [comment]
The UX looks far more modern like that; good use of space.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/7750
