### ISSUE TITLE
Team Member Profile on Contextual Bar

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#8308]
### Description

Create the Team Member information component on the new Team Member view.
- User information: Role, Email, Phone, Timezone.
- Enable edition of the fields for admins on the Manage Users interface

Link to design for [visualization](https://projects.invisionapp.com/share/TKC46XUZB#/screens/238921835) and [edition](https://projects.invisionapp.com/share/TKC46XUZB#/screens/240049422)

**Comment by ggazzo** [comment]
@karlprieb I need this icons 
![image](https://user-images.githubusercontent.com/5263975/32239944-1d88334a-be53-11e7-96e0-256abb754ffe.png)

**Comment by ggazzo** [comment]
![image](https://user-images.githubusercontent.com/5263975/32240506-a66ca762-be54-11e7-9927-1c13cbaa3cd2.png)

**Comment by rasos** [comment]
Has this been merged?  Where are the user profile fileds shown?  
How can a user edit his/her profile information? In RC 0.58.1, it is only possible during registration.
