### ISSUE TITLE
When using marked markdown parser, Issue tracker links does not work.

### ISSUE THREAD

**Issue by makotookamura** [RocketChat/Rocket.Chat#8311]
### Description:

When using **original** markdown parser, we can use Issue tracker links.
But change to **Marked** makrdown parser, does not generated links.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.8
* Deployment Method(snap/docker/tar/etc): docker

**Comment by pfunk1978** [comment]
I can confirm this is happening on 0.59.4. Huge bummer, because we would like to use table markdown in our environment

**Comment by pfunk1978** [comment]
@MartinSchoeler Just checking in on this issue. Still happening in 0.63

**Comment by xmedeko** [comment]
It works in 2.17.1 already.
