### ISSUE TITLE
No internationalization of Livechat-texts

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#8312]
### Description:
In the livechat-widget, texts are partly not translated although the translation is available in the source.
<img width="334" alt="livechat_i18n_1" src="https://user-images.githubusercontent.com/17176678/30847819-2d9dc32a-a29d-11e7-9311-e2c17baae4a7.png">

You can also see that the user's language is properly detected. Texts which are also available in the `rocketchat-i18n`-package are properly translated, such as `Type_your_message`
<img width="703" alt="livechat_i18n_2" src="https://user-images.githubusercontent.com/17176678/30847822-30db76f4-a29d-11e7-9cda-dfcc9e98aa92.png">

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1

### Steps to Reproduce:

* Check out github.com/assistify/Rocket.Chat/tree/master/ (I am not sure that the texts are already merged into the current `develop` @ RC
* Open a new livechat and check the translations

**Comment by mrsimpson** [comment]
@sampaiodiego I experienced in the past that i18n in my custom packages are also not effective: I had to move them to `rocketchat-i18n`

**Comment by sampaiodiego** [comment]
@mrsimpson the point is that the ["livechat mini-app"](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-livechat/app) is completely separated meteor app. his source code is inside rocket.chat package, but it is not part of rocket.chat itself.

so for translations on ["livechat mini-app"](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-livechat/app), his [own translations strings](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-livechat/app/i18n)..

what happens sometimes (please see #8263 and #8267 - both affected our production build) is that you need to `meteor reset` the ["livechat mini-app"](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-livechat/app) so translations will be processed again.

**Comment by mrsimpson** [comment]
@sampaiodiego I tried a local build, `meteor reset` in `packages/rocketchat-livechat/app` as well as in the root (i've seen that in the travis configuration). No change.
Any other advice, a flag I need to set or similar?

**Comment by icosamuel** [comment]
I'm experiencing the same issue when translating the plugin according to the host-page's locale. These are the only texts I can't manage to get to work with Tapi18n.

**Comment by icosamuel** [comment]
After some investigating, I found that the translation behavior is inconsistent
In this example, only the `Yes` button is translated *even though they all have the same underlying mechanism*.

**packages/rocketchat-livechat/app/client/views/options.js**
```
text: t('Are_you_sure_do_you_want_end_this_chat'),
confirmButtonText: t('Yes'),
cancelButtonText: t('No'),
```
**packages/rocketchat-livechat/app/i18n/fr.i18n.json**
```
"Are_you_sure_do_you_want_end_this_chat": "Êtes-vous sûr de vouloir mettre fin à cette conversation ?",
"Yes": "Oui",
"No": "Non",
```
![rc-livechat-trad](https://user-images.githubusercontent.com/5400332/31231334-9a7b767c-a9b4-11e7-8ab3-33048eaab70e.png)

**Comment by mrsimpson** [comment]
@sampaiodiego I just debugged the widget and noticed, that by the time the options menu is getting created, the `TAPi18n.getLanguage()` returns the default one ("en"). Once the chat is loaded, it returns the proper client language.
I've also seen that the language is set in a method-call-callback in `Template.livechatWindow.onCreated`. I assume that the rendering of the options menu happens before the callback has completed and is not reactively re-triggered.

**Comment by sampaiodiego** [comment]
@mrsimpson from what @renatobecker discovered, seems like the livechat widget uses i18n files of rocket.chat app. he opened this PR https://github.com/RocketChat/Rocket.Chat/pull/9966 , could you give it a look?

**Comment by mrsimpson** [comment]
@sampaiodiego @renatobecker basically merged all the translations into the translation s of the main app. While I believe this works, it's a bit ... strange to me. However, I also noticed that translations added in other packages than `rocketchat-i18n` are disrespected. I also had to move our translation files into the rocketchat-package. I however did not merge them, which works fine and at least keeps some things in order.

So if giving up the i18n-files in the livechat-app itself is your solution, I can of course live with that.

**Comment by sampaiodiego** [comment]
unfortunately the way we build and serve the livechat-app, makes `tapi18n` package request translations to the main rocket.chat app.. we couldn't find a way to change the request path though, so that's why we move all livechat translation to `rocketchat-i18n`.

if we had it as a different app/process running, it should work as expected.

**Comment by mrsimpson** [comment]
@sampaiodiego yup, understood. I still don't know whether the TAPi18n-package is a blessing or a curse, but the configuration definitely is the latter. 
@renatobecker just fyi: You don't have to merge the files, see https://github.com/assistify/Rocket.Chat/commit/3340357e7f0809b6aea391e7fb913c2f2a402f87

**Comment by renatobecker** [comment]
@mrsimpson, I tried to load the livechat translation files during the `Package.onUse` (rocketchat-livechat/package.js), the same way it is done in `rocketchat-i18n`, but it just didn't work well.
So, because of this, we decided to unify the translation files inside `rocket.chat package`.

**Comment by mrsimpson** [comment]
@renatobecker I tried the same and many hours of my life reconfiguring TAPi18n. Without any success. I was hoping you had ad better connection to the Javascript library world ;)
Now, I can only imagine to get it solved with a [meteor build plugin](https://docs.meteor.com/api/packagejs.html#build-plugin-api)or by simply adding the file-copy to the build process (in the CircleCI-build-chain)

**Comment by sampaiodiego** [comment]
@mrsimpson I've also spent many hours of my life today fighting against TAPi18n package.

the solution I've found was similar to what you said, but I did on Rocket.Chat build itself, [check it out](https://github.com/RocketChat/Rocket.Chat/compare/livechat-translation-restructure?expand=1#diff-ab553266cce592c04a6041e05da050f6)

this will let everybody with duplicated files on filesystem, but they ignored by git, they will probably don't even notice.

what you guys think on this implementation?

**Comment by mrsimpson** [comment]
@sampaiodiego I believe that's good enough!
Compared to just including it in the build, your solution also loads the i18n when launching locally via `meteor run`.
I believe adding a README in the i18n-package about the specialties might help, wdyt?

```
This package contains internationalization for Rocket.Chat.
Due to limitations of the i18n-library used, _only_ translations from this very folder will be respected.
Thus, if you extend Rocket.Chat with custom packages which have got own translation files, you'll have to put them into this package. They should be named `<package>.<language>.i18n.(json/yaml).`  

Alternatively, you can add the the i18n-files in your package and then copy it to this folder during build time. In this case, you should add the copied files to the `.gitignore`. See the `package.json` for a sample how this is done for the livechat-package.
```

**Comment by graywolf336** [comment]
Good news it that Rocket.Chat Apps makes usage of the i18n package's runtime configuration of languages. However, this is only on Rocket.Chat side and not on the LiveChat side since the Apps don't touch anything related to the LiveChat. Just thought I'd share since it has worked fine as far as I can tell from the current uses.

https://github.com/RocketChat/Rocket.Chat/blob/a9aea3640262482d7111abe3b5c231aa80da897e/packages/rocketchat-apps/client/orchestrator.js#L27-L41

**Comment by AndreVolpi** [comment]
Hello, is there a PR or a plan to make it so the translations on the LiveChat are actually used?

I took a quick look at the source code and it looks to me like it should at least be getting the language from the browser, but for our installation (purelly installing the docker container) the Livehcat is always in english and never uses any other language (no matter the application language or the browser language or any other thing).

**Comment by sampaiodiego** [comment]
Now that the old/legacy livechat widget is gone, this issue doesn't apply anymore.

If you have new suggestions or additions to the new livechat widget, please refer to https://github.com/RocketChat/Rocket.Chat.Livechat

**Comment by vineethvijay-MyT** [comment]
@AndreVolpi Did you got this fixed? We are facing the same issue.

**Comment by AndreVolpi** [comment]
> @AndreVolpi Did you got this fixed? We are facing the same issue.

No, we gave up on it as a company. (also having the chat didn't give a positive impact on our website so didn't make sense)
