### ISSUE TITLE
Disable up / down edit last message when writing new message.

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#832]
Currently the up starts editing the previous message even if you are already writing new message.

**Comment by geekgonecrazy** [comment]
Maybe it should just not goto previous message.  Not sure about having it move in the input box.

**Comment by mitar** [comment]
Move in the input box is a normal behavior in the form input (at least on Mac OS X).

**Comment by graywolf336** [comment]
Yeah if you've got content in the textbox then the up arrow shouldn't go to editing the previous message, that's my thoughts.

**Comment by natewind** [comment]
This still happens to me all the damn time in the web UI on 8.6.0.
