### ISSUE TITLE
Show FB link (social connections) on your own account profile

### ISSUE THREAD

**Issue by RichGriese** [RocketChat/Rocket.Chat#8320]
Talking with Aaron Ogle in support, he indicated to me that on my trial beta that because in the avatar section, it shows an option to use my FB avatar that the system is connected to my FB profile. Yet, when I look at my profile, I don't see the FB link that I see for another user on the system. Aaron said that the the view for your own profile is different than the view for others. I would like to see my FB link in my profile and be able to navigate to it, if I am connected to FB.

Cheers! Rich G

**Comment by marceloschmidt** [comment]
Please check if this has been implemented in recent UI changes. I believe it has. Reopen if not. Thanks.
