### ISSUE TITLE
Rocket.Chat not loading while using a reverse proxy

### ISSUE THREAD

**Issue by vilP1l** [RocketChat/Rocket.Chat#8323]
Hello, I recently set up rocket.chat on my raspberry pi using snaps. It worked fine while i connected by port but when I setup a reverse proxy using apache's mod_proxy that sets the domain to pi.mydomain/chat it would get stuck on loading

My rocket.chat version is 0.58.2
My OS is raspbian (debian)
I deployed it using Snaps
1 running instance
My node version is 4.8.2

Steps to Reproduce:

1. Install mod_proxy 
2. Edit /etc/apache2/sites-enabled/000-default.conf and include the following:
<VirtualHost your_ip:80>
ServerAdmin it@domain
ServerName pi.domain
ErrorLog /var/log/pi.domain_error.log
TransferLog /var/log/pi.domain_access.log
LogLevel info
<Location />
Order allow,deny
Allow from all
</Location>
ProxyPreserveHost On
ProxyPassMatch ^/sockjs/(.*)/websocket ws://ip:3000/sockjs/$1/websocket
ProxyPass /chat http://ip:3000/
ProxyPassReverse /chat http://ip:3000/
</VirtualHost>
3. Restart apache and go to pi.your_domain/chat

I expected it to work but it got stuck on loading

logs:
In the logs it shows that different css, and js files are not found. How would i fix this?

**Comment by seriouz** [comment]
I'm using a nginx reverse proxy with ssl and it just works fine!

**Comment by vilP1l** [comment]
@seriouz are you using a subdir? so like domain/chat

**Comment by magicbelette** [comment]
@vilP1l in Becareful, in debian 8 mod_proxy doesn't support websocket proxifying.
Cheers

**Comment by reetp** [comment]
Debian 8 should have Apache 2.4 which should handle mod_proxy ? I have mine on CentOS6/Apache 2.2 with a backported patch and it works :-)

Re subdirs there is plenty in the bugs on subdirectory issues.

Can you get it to run proxied WITHOUT the subdirectory first ?

**Comment by vilP1l** [comment]
how would i do that for example how would i set it to chat.domain what dns records would i need

**Comment by TwizzyDizzy** [comment]
Please use the [forums](https://forums.rocket.chat/) for such questions, as this is not Rocket.Chat bug!

Cheers (+close)
Thomas
