### ISSUE TITLE
Mass delete users

### ISSUE THREAD

**Issue by kadafax** [RocketChat/Rocket.Chat#8324]
Is there a way to mass delete users ?
From the UI I can only delete one by one and as I have totally missed my LDAP import, I now have 300+ account to delete... So before I trash the whole mongo db, is there a way to mass delete users or at least is there a way to only dump users db directly in the mongo db ?

**Comment by engelgabriel** [comment]
Unfortunately, there is not UI for this yet, but you can delete the users directly on the database on the `users` collection.

**Comment by kadafax** [comment]
Okay, thanks for the quick answer.

For the record, here is a quick how-to for the mongodb noob like me:
Start the mongo shell with "mongo" and then:
> use rocketchat
> db.users.drop()

**Comment by gabrielranulfo** [comment]
> Okay, thanks for the quick answer.
> 
> For the record, here is a quick how-to for the mongodb noob like me:
> Stop rocket.chat and enter the mongo shell with "mongo" and then:
> 
> > use rocketchat
> > db.users.drop()

this command dele all users =/

**Comment by bigf-oo-t** [comment]
It is better to remove only LDAP users run the command:
`db.users.remove({"ldap": true});`

**Comment by dimmthewitted** [comment]
How to remove an individual user?    

LDAP integration documentation in Rocket Chat could really use some community support.

**Comment by rocknr011** [comment]
> How to remove an individual user?

You can remove an individual user directly from the admin panel. This is the safer way.

**Comment by Mte90** [comment]
There is no way to just delete the anonymous users?

**Comment by bzzworld** [comment]
> 

db.users.deleteMany({"roles": "anonymous"});
