### ISSUE TITLE
WebRTC Video Chat Fullscreen totally broken

### ISSUE THREAD

**Issue by seriouz** [RocketChat/Rocket.Chat#8325]
The fullscreen function for WebRTC video calls is completely broken:

![rocketchat-fullscreen-destroyed](https://user-images.githubusercontent.com/4722613/30911692-ed0c09c8-a389-11e7-91c1-08da73604d51.jpg)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.9
* Operating System: Ubuntu 16 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: none
* Node Version: do not know

### Steps to Reproduce:

1. Install Rocket.Chat via Docker
2. Make a WebRTC call
3. Click on the full screen button
4. Be amazed of the broken look.

### Expected behavior:
A fullscreen view of one chat participant and a small bar with a preview window of the other attendees and a close button.

**Comment by ElieMyIdea** [comment]
+1

**Comment by fcourtaud** [comment]
+1

**Comment by EdwardWu7** [comment]
+1

**Comment by tonkoandrew** [comment]
+1

**Comment by Archer4l** [comment]
+1

**Comment by KevinYwanauskas21** [comment]
+1

**Comment by LifeIsAParadox** [comment]
+1

**Comment by ramrami** [comment]
I've created a PR to solve this issue : #9953
