### ISSUE TITLE
Cannot change password on the profile page.

### ISSUE THREAD

**Issue by akky0001** [RocketChat/Rocket.Chat#8328]
### Description:
I attempted to change the password on the profile page, but I could not change it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc9(your demo site)

### Steps to Reproduce:

1. Access to Demo site.
2. Try to change only password on the profile page.
3. The "Save changes" button doesn't change color.(Cannot click the button.)

### Expected behavior:
Can change new password.(The "Save changes" button changes color.)

### Actual behavior:
Cannot change new password. 

### Relevant logs:

None.

**Comment by SeanPackham** [comment]
No longer an issue in 0.62.0
