### ISSUE TITLE
is it has some error in en.i18n.json?

### ISSUE THREAD

**Issue by youxiaoriqi** [RocketChat/Rocket.Chat#8329]
when i open en.i18n.json file in notepad ++ with utf-8, some string look like this blow:
![image](https://user-images.githubusercontent.com/5238752/30920916-bdf9255a-a3d7-11e7-8079-6ef67bcb0ae6.png)

thanks!

**Comment by MartinSchoeler** [comment]
I believe that is not a rocket.chat problem, please reopen this if you find any problems with other editors or IDEs. Thanks!
