### ISSUE TITLE
Unread duplicated between unread view and favorites

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8330]
### Description:
If you have an unread in favorites as well as unread mode turned on... you see this:
![image](https://user-images.githubusercontent.com/51996/30923032-75c735cc-a370-11e7-9970-e728ddc9ee15.png)

I thought this one had been added.  But looking over the issues we never opened one for this.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.9
Community server

### Steps to Reproduce:

1. turn unread mode on
2. favorite a channel
3. have someone send a message in the favorited channel while you are looking at a different channel.

### Expected behavior:

It shouldn't show both places. Its confusing

### Actual behavior:
It shows both places.

### Relevant logs:
Not relevant and no logs.

**Comment by cyclops24** [comment]
Part of #8175

**Comment by engelgabriel** [comment]
This was done on purpose, it is not a but, it is a feature.

**Comment by geekgonecrazy** [comment]
🤔  should we make the other ones stay in their groups too then?  Because the channels section / private group section and direct messages it moves them to unread section.  So behavior isn't consistent.  

To me its confusing.  If we do this we should float unread to the top of favorites and not include them in unread.  If we want them to stay in favorites.  The duplicate throws me off.

I click in favorites and suddenly channels are disappearing above in the unread panel and the UI jumps.  Or I keep feeling this nagging that I have even more unread down below among the other groups that I must then check.

Idk to me it just feels very off and confusing to ever show any channel more then once in a list

**Comment by engelgabriel** [comment]
I agree, it was not my choice, I just know it was done intentionally. Let's review this decision.

**Comment by mnlbox** [comment]
@theorenck Any news?

**Comment by MartinSchoeler** [comment]
Since this was a discussion, please move this thread to https://forums.rocket.chat/ Thanks!
