### ISSUE TITLE
Clicking 'hang up' button in Jit.si video chat should close chat pane

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat#8339]
# Description:

Co-workers have been confused as to how to dismiss the Jit.si video conference pane. They intuitively feel that 'hanging up' the call should dismiss the chat pane

![peek 2017-09-28 11-18](https://user-images.githubusercontent.com/17307/30956118-cdf0a822-a43e-11e7-9247-246c7e7d8d36.gif)

### Steps to Reproduce:

1. Open a private chat window
2. Click 'video chat' icon on sidebar
3. After chat loads, press red 'hang up' icon in Jit.si
4. Observe that chat sidebar does not close
5. Press small chat icon on sidebar to close pane

### Expected behavior:

The pane should close when ending the call. E.g. clicking hang up should close the pane.

### Actual behavior:

Pressing 'hang up' ends the Jit.si call, but does not close the pane.

**Comment by danieljhochman** [comment]
+1 - our team feels the same way.

**Comment by marceloschmidt** [comment]
This has been solved with the re-design of jitsi integration.
