### ISSUE TITLE
Users being logged out after small period of time

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#8341]
Referencing https://github.com/meteor/meteor/issues/9140

After a few reconnects (due to internet source switching or even closing laptop) you may got logged out by rocket.chat.

The PR https://github.com/meteor/meteor/pull/9148 will fix this once merged and updated here.

**Comment by alexweissman** [comment]
@sampaiodiego was this only confirmed in 0.59?  I'm having this same problem in 0.58.3.

**Comment by sampaiodiego** [comment]
hey @alexweissman .. yes, this seems to affect `0.58.3` as well..
