### ISSUE TITLE
cfg files not accepted 

### ISSUE THREAD

**Issue by davidfm** [RocketChat/Rocket.Chat#8342]
### Description:

We cannot upload `*.cfg` files despite having white listed all media types.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

### Steps to Reproduce:

1. White list all media types (Accepted Media Types = blank)

2. Try and upload a `.cfg` file

### Expected behavior:
The `.cfg` file is uploaded successfully
### Actual behavior:

> Media Types Not Accepted *.cfg

**Comment by marcingodlewski** [comment]
Same here, v0.58.2

**Comment by marcingodlewski** [comment]
Ok, I believe this was addressed in #8172 and coming in 0.59
