### ISSUE TITLE
My database is getting really large and costly... am I doing something wrong?

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#8344]
### Description:

I've had my new deployment live for only a month.  I've got the uploads going to an Amazon Bucket, so there isn't a large file size building up there (that happened on an old deployment!).   I don't have very many users, there's probably less than a dozen users who are consistently on the site, actively communicating.  In the first month alone, I'm seeing us approach a 1GB database and this will only grow exponentially as the existing users continue chatting and we add more users.  I'm becoming very concerned about the scalability of this platform... but maybe I have some settings wrong.

If I add up the individual collections within the database, I get about 60 MB.  Yet Compose.io is saying I actually register at over 500 MB.  They gave me this kinda detailed rundown but I honestly don't understand how this works.  It seems like I'm getting a 10x charge here.

They sent me this:

set-560ab4eb75eea0f4a00007e6:PRIMARY> db.stats(1024*1024)
{
	"db" : "PUNet",
	"collections" : 50,
	"objects" : 222593,
	"avgObjSize" : 458.46085007165544,
	"dataSize" : 97,
	"storageSize" : 140,
	"numExtents" : 99,
	"indexes" : 197,
	"indexSize" : 77,
	"fileSize" : 496,
	"nsSizeMB" : 16,
	"dataFileVersion" : {
		"major" : 4,
		"minor" : 6
	},
	"extentFreeList" : {
		"num" : 0,
		"totalSize" : 0
	},
	"ok" : 1
}

And then this for the 'actual sizes on disk':

17M	PUNet.0
32M	PUNet.1
64M	PUNet.2
129M	PUNet.3
257M	PUNet.4
16M	PUNet.ns

### Server Setup Information:

* Version of Rocket.Chat Server:   0.58.1
* Operating System:   Linux
* Deployment Method(snap/docker/tar/etc):  Heroku dyno for app, Compose for database
* Number of Running Instances:  1
* DB Replicaset Oplog:  Enabled
* Node Version:   v4.8.4

**Comment by Lemmmy** [comment]
On my 2 month old instance, I have a 3 GB OEmbed cache. You could try clearing that. However, if you are on a replicaset, a large portion of the database could be the oplog (mine is nearly 15 GB) - however the size of that is limited ([more details on oplog sizes here](https://docs.mongodb.com/manual/core/replica-set-oplog/)).

By running a query found in [the comments of this gist](https://gist.github.com/joeyAghion/6511184) you can also find the size of the individual collections. For example, my largest collections are `rocketchat__trash`, `rocketchat_oembed_cache` and `rocketchat_upload.chunks` (though I have moved file uploads to minio).

**Comment by flantascience** [comment]
OEMbed cache... where can I clear that?   @Lemmmy

**Comment by flantascience** [comment]
And omg 15 GB oplog?   That would cost me >$200/month

**Comment by flantascience** [comment]
This is what I've got in my system... adds up to around 60 MB though they are claiming 600+

COLLECTIONS     DOCUMENTS     SIZE
_raix_push_app_tokens	1	8 KB
_raix_push_notifications	0	8 KB
assets.chunks	7	2.01 MB
assets.files	7	8 KB
avatars.chunks	77	5.26 MB
avatars.files	77	40 KB
custom_sounds.chunks	1	136 KB
custom_sounds.files	1	8 KB
instances	0	8 KB
meteor_accounts_loginServiceConfiguration	0	8 KB
meteor_oauth_pendingCredentials	0	8 KB
meteor_oauth_pendingRequestTokens	0	8 KB
migrations	1	8 KB
rocketchat__trash	0	5.07 MB
rocketchat_cron_history	0	8 KB
rocketchat_custom_emoji	0	8 KB
rocketchat_custom_sounds	1	8 KB
rocketchat_import	0	8 KB
rocketchat_integration_history	0	8 KB
rocketchat_integrations	0	8 KB
rocketchat_livechat_custom_field	0	8 KB
rocketchat_livechat_department	0	8 KB
rocketchat_livechat_department_agents	0	8 KB
rocketchat_livechat_external_message	0	8 KB
rocketchat_livechat_inquiry	0	8 KB
rocketchat_livechat_office_hour	7	8 KB
rocketchat_livechat_page_visited	0	8 KB
rocketchat_livechat_trigger	0	8 KB
rocketchat_message	202415	82.3 MB
rocketchat_oauth_access_tokens	1	8 KB
rocketchat_oauth_apps	2	8 KB
rocketchat_oauth_auth_codes	3	8 KB
rocketchat_oauth_refresh_tokens	1	8 KB
rocketchat_oembed_cache	29	10 MB
rocketchat_permissions	66	40 KB
rocketchat_raw_imports	0	8 KB
rocketchat_reports	0	8 KB
rocketchat_roles	9	8 KB
rocketchat_room	590	680 KB
rocketchat_settings	476	680 KB
rocketchat_smarsh_history	0	8 KB
rocketchat_statistics	7466	21.5 MB
rocketchat_subscription	1928	680 KB
rocketchat_uploads	6834	10.7 MB
rocketchat_uploads.files	1807	680 KB
ufsTokens	8	8 KB
users	335	680 KB
usersSessions	0	8 KB

**Comment by flantascience** [comment]
Compose tells me this re: my oplog: No, your oplog is a static size. We start you at 2GB at Compose, and don't charge for it. If you ever do need a larger oplog, you'll have to ask by special request. However, we only charge for oplog above the free 2GB that we provide by default.

**Comment by geekgonecrazy** [comment]
Did you at some point have large files that you cleared out?  Its possible with mongo that you might need to compact.  I'd ask Compose about this discrepancy.  They should be able to run a compact on your database.

Normally it'd be done via something like: `db.repairDatabase()`

Alternatively.  You could export your database.  Delete the db.. and then re-import it.

**Comment by flantascience** [comment]
How/why would exporting it and re-importing it help?

Jim Flannery

jim-flannery.com
p. 860-578-4966
e. jim@jim-flannery.com
s. jim_flannery

**Comment by geekgonecrazy** [comment]
Mongo preallocates space to improve the write performance.  Exporting and deleting removes space.  Importing again is only allocating what is needed.

Prior to exporting I'd drop the oembed collection.
