### ISSUE TITLE
Bug: Role Tags are sometimes shown, sometimes not

### ISSUE THREAD

**Issue by cvalkan** [RocketChat/Rocket.Chat#8350]
### Description:
Role tags for (some) users are sometimes shown, sometimes not. 

We are two administrators and while I can see most of the role tags, my fellow admin only sees some of them. The two following screenshots were taken at the same time. Please note the missing "Guest" tags in the second picture, e.g. for the user "Espria".

Admin 1:
![espria_1](https://user-images.githubusercontent.com/26460672/31006495-293fe044-a4fd-11e7-8022-2bd74a4ba6e8.png)

Admin 2:
![espria2](https://user-images.githubusercontent.com/26460672/31006538-4e8a3bc4-a4fd-11e7-95c5-7395a82f5c36.png)

In the following picture, the user "Pete" has no "Guest" tag, despite having the role "User" for which we have set the description "Guest".

![no tag_](https://user-images.githubusercontent.com/26460672/31006626-b61f0238-a4fd-11e7-9d0e-266b6b378f03.png)

![users_](https://user-images.githubusercontent.com/26460672/31006641-c651363a-a4fd-11e7-9fe9-ed7526dd0a18.png)

![role tag guest](https://user-images.githubusercontent.com/26460672/31006987-38448a20-a4ff-11e7-8ad6-c49f46060040.png)

A few hours later (without changing anything), the tag suddenly appeared on my screen:
![tag appeared_](https://user-images.githubusercontent.com/26460672/31006700-10518ff0-a4fe-11e7-93e5-32a37bf25354.png)

### Server Setup Information:

Version: 0.58.2
OS Platform: Linux, x64, 4.4.0-83-generic
Numer of Running Instances: 1
Node Version: v4.8.4

**Comment by nORKy54** [comment]
Admin 2 is in compact mode (account préférence)

**Comment by nORKy54** [comment]
You can use this to show roles in compacte mode: 
`.compact .message .info .role-tag{
  display: inline;
}
`

**Comment by cvalkan** [comment]
Thank you nORKy54. 

But how comes that some of the tags are shown to Admin 2, while others are not?
Admin 1 also didn't see user Pete's tag for a while.

Can I make sure that all the tags are (immediately) shown to every user on every device? It's an important security feature that people can see who's a team member and who's a guest.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
