### ISSUE TITLE
DNS SRV record

### ISSUE THREAD

**Issue by lpalgarvio** [RocketChat/Rocket.Chat#8353]
### Description:

Hello,
Are DNS SRV records supported or planned?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by lpalgarvio** [comment]
Hello @MartinSchoeler 

What i'm asking is not a support request.

It is a feature request.

Are there plans to support DNS SRV records on Rocket.Chat server and clients?

Luis

**Comment by madguy02** [comment]
@MartinSchoeler can you please reopen this issue?

**Comment by lpalgarvio** [comment]
Another reminder, 11 March 2018

**Comment by madguy02** [comment]
@Ipalgarvio , DNS Sec records are used for server discovery, and RC does not need to have it right now. But why exactly you require DNS Srv right now? It's better if you can share why is this a requirement right now? Thanks

**Comment by JSzaszvari** [comment]
There's no valid reason I can think of for DNS SRV records unless you are thinking about implementing some sort of discovery, which can already be accomplished by deploying a config with your client. 

@lpalgarvio @madguy02 if you wish to follow up on this feature request please post it at  https://forums.rocket.chat in the feature request section. The forums are where feature requests that are not currently on the road map can be discussed

**Comment by madguy02** [comment]
@JSzaszvari  this is actually a feature which is a part of Federation, we need server discovery when we are federating between servers. I am working on that. Apart from that there isn't any need to set up the DNS srv records.

**Comment by JSzaszvari** [comment]
Ah good stuff. Thanks for filling me in :)

**Comment by lpalgarvio** [comment]
By having SRV records supported, RocketChat can for example allow running the server on a subdomain, without taking space on the root domain, and without forcing users to know that subdomain.

ie, allows this:
example.com - your organization website
www.example.com - alias for the root domain
chat.example.com - your rocketchat

clients lookup example.com and connect to chat.example.com

This is the behaviour currently used by Jabber/XMPP and Matrix
