### ISSUE TITLE
Correct filters for organizational units, and how to connect multiple domains?

### ISSUE THREAD

**Issue by simakmak** [RocketChat/Rocket.Chat#8354]
Good afternoon guys. I had two questions: 
1. How to specify several OUs in the domain database. What I want: Suppose I have such a structure 
ou=adm,ou=groups,dc=domain,dc=local 
ou=users,ou=groups,dc=domain,dc=local
 How do I write a domain database, could pick up several organizational units at once? I tried to write them through a comma-separated point 
ou=adm,ou=groups,dc=domain,dc=local;ou=users,ou=groups,dc=domain,dc=local 
But this did not lead me to success. Then I subtracted what the person did as follows: 
ou=adm+ou=users,ou=groups,dc=domain,dc=local
 But so, I also did not work, so how do I correctly do it? 
2. There is a chance that I will soon have to connect a second domain. That is: domain.local two.domain.local Can I somehow integrate users from two domains at once? Thank you for your attention)) I hope for your help)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
