### ISSUE TITLE
Meteor allow/deny vulnerability disclosure 

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#8369]
Hello Devs.

Is rocketchat vulnerable to: https://blog.meteor.com/meteor-allow-deny-vulnerability-disclosure-baf398f47b25?

thanks and cheers

**Comment by engelgabriel** [comment]
While Rocket.Chat does not use the features in which the vulnerability was discovered we still advise all users to upgrade their Rocket.Chat server to the latest stable (0.58.3) or release candidate (0.59) version. If you have any questions or concerns please create an issue or email us.

https://rocket.chat/blog/meteor-allowdeny-vulnerability-disclosure
