### ISSUE TITLE
Docker Internal Server Error while trying to upload

### ISSUE THREAD

**Issue by SerdarN92** [RocketChat/Rocket.Chat#8376]
### Description:

I´ve installed Rocketchat on Docker and was trying to upload a file, but i always get Internal Server Error.

I´ve installed it with the following command:

docker run --name rocketchat -e "VIRTUAL_HOST=xxx.de,www.xxx.de" -e "LETSENCRYPT_HOST=xxx.de,www.xxx.de" -e "LETSENCRYPT_EMAIL=info@xxx.de" -v /uploads:/fileuploads -e "ROOT_URL=https://www.xxx.de"  --link db -d rocket.chat

Iam using Nginx as proxy.

### Server Setup Information:

Version of Rocket.Chat Server: 0.58.2
Operating System: Ubuntu 16.4
Deployment Method(snap/docker/tar/etc): docker
Number of Running Instances: 1

### Steps to Reproduce:

1. 
2. 
3. 

### Relevant logs:
[34mI20171003-06:40:13.386(0) Exception while invoking method 'ufsComplete' Error: EACCES: permission denied, open '/ow3G2KtSe44CE5hA9.pdf'   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].Meteor.methods.ufsComplete (/app/bundle/programs/server/packages/jalik_ufs.js:818:24)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1110:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1858:12)   at /app/bundle/programs/server/packages/ddp-server.js:904:20   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at /app/bundle/programs/server/packages/ddp-server.js:903:47   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at /app/bundle/programs/server/packages/ddp-server.js:902:46   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:875:21)   at /app/bundle/programs/server/packages/ddp-server.js:754:85      - - - - -   at Error (native)

**Comment by beg1294** [comment]
I had same problem when I put storage type to 'file system', try to change filesystem from  settings->file upload->Storage type

**Comment by SerdarN92** [comment]
@beg1294 its already on Type FileSystem .. still same problem

**Comment by beg1294** [comment]
@SerdarN92 so put it on GridFS

**Comment by SerdarN92** [comment]
Thanks @beg1294  that was the solution.
