### ISSUE TITLE
[UX] [i18n] Use enter separator rather than comma in highlight preferences

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#8377]
Hi guys,
I want talk about this part of app:
![highlight](https://user-images.githubusercontent.com/25859075/31114498-413a25b6-a82b-11e7-8e23-a8f0b71c9f5d.png)

I think it's better to use `Enter` character as a separator rather than comma in highlight preferences because comma in any language is difference for example in Arabic comma is `،` but in English is `,` so it's so difficult to use highlight feature in other language with below steps:
1. Type a word in Arabic
1. Switch keyboard layout to English
1. Type a comma
1. Switch keyboard layout to Arabic
1. Type another word

If we use `Enter` as a separator this feature can be more useful for non-English users.
I find related code here:

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-account/client/accountPreferences.js#L156

**Comment by mnlbox** [comment]
#8175

**Comment by cyclops24** [comment]
@mnlbox, @karlprieb, @engelgabriel It's can be a useful improvement. 👍
