### ISSUE TITLE
[BUG] GCM notifications stuck after few days

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#8378]
### Description:

GCM notifications stuck after few days of usage. They are not pushed to devices. Moreover if we restart docker, RocketChat sends every previous notification which was not pushed earlier, so users of our chat get millions of notifications every time we restart server.
### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Centos7
* Deployment Method: docker
* Number of Running Instances: 500
* Mongo 3.2.11  Docker

**Comment by geekgonecrazy** [comment]
This one should be solved in newer releases
