### ISSUE TITLE
Lang Error > date message

### ISSUE THREAD

**Issue by yepzy** [RocketChat/Rocket.Chat#8379]
Hi,

I've seen an error in lang En. On the date of messages
https://up2sha.re/file?f=dJD7ldBQ

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
