### ISSUE TITLE
Create Channel button hidden

### ISSUE THREAD

**Issue by rwakida** [RocketChat/Rocket.Chat#838]
The create new channel button in the listChannelsFlex footer is hidden. If you view the html, it's present, but hidden by the RocketChat logo 

To replicate:
1. login as user
2. click on "More channels"
3. scroll to bottom.  There should be a button that allows you to create a new channel.

**Comment by marceloschmidt** [comment]
@rcaferati can you take a look at this one? it looks like a simple z-index on footers would solve this, but I'll let you decide that ;) Thanks!

**Comment by rabbihossain** [comment]
I might be able to solve it. Seems a easy fix. Should I go for it?

**Comment by marceloschmidt** [comment]
sure @rabbihossain ! thank you!

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:36951)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZmS7r-003OI0-FY
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:54:17 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=RdTDdSBXO5WTGhOFP68HB15qvPg=; b=JHgytGtBO/5ryrLg
	+337S+Riv9E0APQp/ImIgyHl47bfU7qLAqBYwjfFl9rZBULqby0NTynUaOvbEhKF
	bytxHExCVnuaq0JL4LdzUuzmb3RT26ikLGruQkgRX7PZuyLcz4OH9r1WJvE0b8N3
	AqCjb3LWsX2HRg/EyC+uKsPm2pk=
Received: by filter0439p1mdw1.sendgrid.net with SMTP id filter0439p1mdw1.7902.561EB2E019
        2015-10-14 19:54:08.273750657 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id JUD_zMIXS6abNcboSY2usg
	for <greg@biomassiv.es>; Wed, 14 Oct 2015 19:54:08.319 +0000 (UTC)
Date: Wed, 14 Oct 2015 12:54:08 -0700

**Comment by rabbihossain** [comment]
@marceloschmidt , I have sent a PR. Please have a look on it.

**Comment by gmsecrieru** [comment]
Fixed on [e87b795](https://github.com/RocketChat/Rocket.Chat/commit/e87b7959eb034255553331240cd1346a165fec1e)
