### ISSUE TITLE
API to pull unread messages

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#8383]
We need the Rest API to be able to pull the following:
1. Username/name of person who sent me the message
2. Message text (or at least X chars of the beginning of the message)
3. Message timestamp

Use case: We want to alert our users when they have a new message, but don't want them to have to load the whole chat screen. Instead, we want to enable the user to quickly check who sent them a message and what they said. If they want to read more or reply they can click to open the full RC window.

**Comment by bakhtizin** [comment]
:+1:

**Comment by alexandrejuma** [comment]
Also need this!
