### ISSUE TITLE
[BUG] Private and Read Only channel not working well

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8388]
Hi guys,
We have a scenario,
I want to create a `Private` and `Read Only channel`.
As we see below in `Read Only` channel we want "Only authorized users can write new messages"  
![28](https://user-images.githubusercontent.com/8266479/31136805-0dd2b15c-a876-11e7-893d-bbd6612e13b6.png)
But we can't post any new message see below gif:
![27](https://user-images.githubusercontent.com/8266479/31140587-b3b54f0c-a881-11e7-9482-27a1b6c94289.gif)

**Comment by cyclops24** [comment]
Part of #8175

**Comment by MartinSchoeler** [comment]
@cyclops24 This is not a UI redesign bug, this related to the backend of rocket.chat

**Comment by MartinSchoeler** [comment]
Are you sure that your user has the `post-readonly` permission

**Comment by cyclops24** [comment]
I think it's an old bug in channel setting:
#4769

**Comment by cyclops24** [comment]
Part of #8494

**Comment by localguru** [comment]
Same here on 0.58.4, `post-readonly` permission is set for admin, moderator and owner

**Comment by localguru** [comment]
@cyclops24 Workaround: as origin owner set another user to owner. This second owner then can set ' post rights` the origin owner. Don't think that this is the expected right concept. 

This bug should be fixed.

**Comment by JSG01** [comment]
same

**Comment by timkinnane** [comment]
Duplicates #4769 - I have a fix for this and will submit PR next week.

**Comment by engelgabriel** [comment]
closed in favor of older issue #4769
