### ISSUE TITLE
Add Kerberos Authentication

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#839]
##

**Comment by askya** [comment]
Hello everybody. Thank you for providing us that good software which is rocket.chat. Thank you again.
Please did ldap-kerberos is already supported? I have already installed rocket.chat and bind it to openldap et and want to bind openldap with kerberos. Therby, I want to know if it will work.
Thank you.

**Comment by bambus1980** [comment]
Whaiting too much! is is working now?

**Comment by askya** [comment]
Hello bambus1980.
No, it is not working. I still using the LDAP authentication encrypted with TLS certificate.
Do you want to suggest me something? I am open.
Thanks.

**Comment by askya** [comment]
I am back to great developers who are working on Rocket.Chat project. I hope they will setup Kerberos authentication in Rocket.Chat very soon at our benefice.
Thank you for your WORK. It is great.

**Comment by geekgonecrazy** [comment]
This is not something we plan to add to our code base.

Please feel free to open a detailed topic in our [forum](https://forums.rocket.chat) for others to vote on and allow us to re-evaluate

**Comment by KarlisVe** [comment]
Adding link to related Rocket.Chat forum topic for voting:   [Kerberos-LDAP](https://forums.rocket.chat/t/kerberos-authentication-ldap-single-sign-on/653/2)

**Comment by askya** [comment]
Hello
Thanks again.
I will follow it.

**Comment by askya** [comment]
Hello
Thanks again.
I will follow it.

**Comment by KongNan** [comment]
Waiting ....
