### ISSUE TITLE
Bad Font

### ISSUE THREAD

**Issue by dbigham** [RocketChat/Rocket.Chat#8393]
### Description:

New Font is Unreadable

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.3
* Operating System: Windows (Client)
* Deployment Method(snap/docker/tar/etc): ?
* Number of Running Instances: ?
* DB Replicaset Oplog: ?
* Node Version: ?

### Steps to Reproduce:

1. Open the application.
2. Try to read text.

### Expected behavior:

Text should be readable.

### Actual behavior:

Font is so narrow as to be unreadable.

![image](https://user-images.githubusercontent.com/1895770/31175967-2b869ac4-a8df-11e7-88d0-a9f98740ae91.png)

**Comment by MartinSchoeler** [comment]
We need more information to proceed, like server version.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by dbigham** [comment]
```
{
  "version": "0.58.3",
  "success": true
}
```

**Comment by Lemmmy** [comment]
Does this happen on the new UI too (e.g. on demo.rocket.chat)?

**Comment by dbigham** [comment]
Yes.

(I presume this was a recent change because up until yesterday, our corporate version of rocket chat didn't have this font.)

**Comment by ggazzo** [comment]
@dbigham do you know if we fixed this problem?

**Comment by vynmera** [comment]
Only thing I can think of that would cause this other than a custom font is someone having Roboto installed on their computers, and the font-weights mismatching... @dbigham do you happen to have Roboto installed?

**Comment by dbigham** [comment]
Our current version is now:
{"version":"0.63.2","success":true}
... and the font is unchanged.

However, I noticed a message above asking me to check demo.rocket.chat.  I apparently replied to that, but I'm wondering if I only saw the "new UI" part of that request and not the demo.rocket.chat part? Can't remember.

In any event, demo.rocket.chat's font is OK for me:

![image](https://user-images.githubusercontent.com/1895770/42405482-9651df22-8164-11e8-9c96-14728cee821b.png)

When I inspect, it shows the font family as:

-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Meiryo UI',Arial,sans-serif

Meanwhile, our organization's rocket chat has:

-apple-system,BlinkMacSystemFont,Roboto,'Helvetica Neue',Arial,sans-serif,'Apple Color Emoji','Segoe UI','Segoe UI Emoji','Segoe UI Symbol','Meiryo UI'

I notice @vynmera 's message above asking whether I have Roboto installed. Not that I know of -- I don't know what Roboto is.

Some further experimentation: If I inspect the source in Chrome and start modifying the font-family by repeatedly removing fonts from the left side of the font-family list, it seems that "Roboto" is the font that it's using. That's the bad font.

Possibly related: For years now, I've been noticing more and more websites on the Internet using either that font or a similar font which is so thin as to be almost readable for me. It's super super annoying and I wonder to myself why the website's designers would do such an unintelligent thing. Possibly related? Is it some kind of configuration issue with my PC that is causing it to use a bad font?

**Comment by dbigham** [comment]
Just uninstalled "Roboto" from my system, which appears to be a Google font. Presto. Rocket chat's font now looks beautiful, and I've also noticed that Google Chrome's settings are also no longer using that hideous font. Hallelujah! Thanks for the brilliant tip @vynmera !
