### ISSUE TITLE
[API] Adjust REST API to match the fields on RealTime stream

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#8400]
### Description:

We're starting to use the REST API to list starred & pinned messages in the native iOS app and we noticed that the mapping of the fields are different from the RealTime API. I was thinking that we should do the same, to avoid doing workaround on the clients to map the same model.

I understand that some of this fields are doing this way in RealTime because of Meteor's implementation, but we need to follow a pattern in the communication. The fields needs to have the same structure in order to avoid hacks & workarounds in the code to map the same model.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.11
* Operating System: Linux
* Node Version: v4.8.4

### Steps to Reproduce:

1. Request starred items using the REST API:
  > /api/v1/channels.messages?roomId=GENERAL&query={ "starred._id": { "$in": ["${userid}"] } }
2. Request pinned items using the REST API:
  > /api/v1/channels.messages?roomId=GENERAL&query={ "pinned": true }

### Expected behavior:

On the list of messages, there's a few differences:

1. `_createdAt` field should come with a `$date` property inside containing timestamp;
2. `_updatedAt` should contain a `$date` property inside with timestamp;
2. `ts` should contain a `$date` property inside with timestamp;

Example of RealTime object:

```json
{
    "mentions" : [],
    "_id" : "bP9L5EvqjX5AJKA4o",
    "_updatedAt" : {
      "$date" : 1507148840827
    },
    "channels" : [],
    "rid" : "eFwou2EY5S7bvYWPY",
    "u" : {
      "name" : "Kalvin Krajca",
      "username" : "Kalman98",
      "_id" : "noEQdogoNax8jHwWJ"
    },
    "ts" : {
      "$date" : 1507148840708
    },
    "msg" : "Just for reference, that's the admin page for it."
}
```

### Actual behavior:

```json
{
  "pinnedBy" : {
    "username" : "manolisep",
    "_id" : "edthE6jTFJX8i8DN9"
  },
  "_id" : "W5qAj8Wf9kR9LFroR",
  "_updatedAt" : "2017-04-26T20:10:32.866Z",
  "rid" : "GENERAL",
  "pinned" : true,
  "groupable" : false,
  "u" : {
    "username" : "victor.bueno",
    "_id" : "TBrtQg68jWvAh7v9p"
  },
  "pinnedAt" : "2017-04-26T20:10:32.866Z",
  "t" : "uj",
  "ts" : "2017-04-26T20:09:43.520Z",
  "msg" : "victor.bueno"
}
```

**Comment by graywolf336** [comment]
@RocketChat/core This **breaks current functionality** of the rest api if we switch over to this format and also it isn't "common accepted json" practice for the json dates. Are we sure we want to do this?

**Comment by rafaelks** [comment]
I wanted to open the discussion here... I believe the best way to show a date right now is like this...

> _updatedAt: 1507148840827

We can leave it for v2, no problem. Right now we can make a workaround in the code and leave a comment. What do you think?

**Comment by xbolshe** [comment]
[rfc 7493  The I-JSON Message Format](https://tools.ietf.org/html/rfc7493)

```
4.3.  Time and Date Handling

   Protocols often contain data items that are designed to contain
   timestamps or time durations.  It is RECOMMENDED that all such data
   items be expressed as string values in ISO 8601 format, as specified
   in [RFC3339], with the additional restrictions that uppercase rather
   than lowercase letters be used, that the timezone be included not
   defaulted, and that optional trailing seconds be included even when
   their value is "00".  It is also RECOMMENDED that all data items
   containing time durations conform to the "duration" production in
   Appendix A of RFC 3339, with the same additional restrictions.
```

**Comment by rafaelks** [comment]
I'm closing this issue because this won't be fixed in version 1 of the API.
