### ISSUE TITLE
Notification sounds still play on busy

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8403]
### Description:
Notification sounds still play when status is set to busy.

We don't show notifications but we still play the sound.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0

### Steps to Reproduce:

1. Set status to busy
2. Turn sound up
3. Put Rocket.Chat in background
3. Have someone DM or mention you

### Expected behavior:

Silence

### Actual behavior:
A ding

**Comment by uselessanim** [comment]
Any progress about this bug?

**Comment by geekgonecrazy** [comment]
closed with #9042
