### ISSUE TITLE
[Bug] The notify.mp3 file is missing

### ISSUE THREAD

**Issue by icosamuel** [RocketChat/Rocket.Chat#8409]
### Description:
I investigated the sound issue, since it's not playing and have found [this PR](https://github.com/RocketChat/Rocket.Chat/pull/3443) on the subject. Everything is supposed to work, the file is loaded by `<source src="/sounds/notify.mp3" type="audio/mpeg" />`

**Under `/public/sounds/`, there should be a file named `notify.mp3`** used for the livechat notification sounds, on the client side. But it's not there. I copied and renamed `chime.mp3` in order to make up for the missing file, then it worked on my dev env!

There is also a warning in Firefox that makes you think it's the mime types on your server that are not configured `HTTP “Content-Type” of “text/html” is not supported. Load of media resource http://localhost:3000/sounds/notify.mp3 failed.`

### Server Setup Information:
* Version of Rocket.Chat Server: 0.58.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1

### Steps to Reproduce:
1. Open `hostname/packages/rocketchat_livechat/assets/demo.html`
2. Talk to an agent
3. Notice that when he answers you, no sounds are played

**Comment by eugenekainara** [comment]
+1

**Comment by crowdstar5566** [comment]
+1

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/6921be6237124fd08e45c27ab7ca75d2622351fc
