### ISSUE TITLE
Momentjs and i18n

### ISSUE THREAD

**Issue by Surfoo** [RocketChat/Rocket.Chat#841]
According to the code (and the display on the browser), the use of momentjs [doesn't include the internationalization of dates](https://github.com/RocketChat/Rocket.Chat/blob/ef8d94695a7f3e575b7809421ca0fc8ca8106f14/client/views/app/privateHistory.coffee#L19-L22) but momentjs support it: http://momentjs.com/docs/#/i18n/

Moreover, I found the directory `bundle/programs/server/assets/app/moment-locales/` with all locales... It is not used?

**Comment by marceloschmidt** [comment]
We do load the corresponding moment locale: https://github.com/RocketChat/Rocket.Chat/blob/master/client%2Fstartup%2Fstartup.coffee#L34-L35

Can you show us where it did not correctly translate the date?

**Comment by Surfoo** [comment]
Layout is in french, but not the date:
![example1](https://cloud.githubusercontent.com/assets/553659/9991561/465059bc-606b-11e5-8a74-0996509dfda9.jpg)

**Comment by marceloschmidt** [comment]
Thanks! I'll look into that!

**Comment by marceloschmidt** [comment]
Fixed it: https://github.com/RocketChat/Rocket.Chat/blob/master/client%2Fstartup%2Fstartup.coffee#L34-L36

Will be available on next deploy.

**Comment by marceloschmidt** [comment]
Done

**Comment by Surfoo** [comment]
Thanks!
