### ISSUE TITLE
Can't log in with AD user/LDAP configuration issue

### ISSUE THREAD

**Issue by VedranOP** [RocketChat/Rocket.Chat#8410]
### Description:

I set multiple configuration sets for LDAP(Windows) connection and I can't log in with user from desired group. Sync and test connection is successful. Please help!

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.3
* Operating System: Ubuntu 16.04 
* Deployment Method:snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version:

Log with user from AD group.
### Actual behavior: User not found or wrong pass and in logs I dont see any error.

Screenshots are below:
![1](https://user-images.githubusercontent.com/22936644/31231085-2198888a-a9e6-11e7-96bf-001c8dc0a8e8.png)
![2](https://user-images.githubusercontent.com/22936644/31231086-219d7e9e-a9e6-11e7-95c8-4b08516ee489.png)
![3](https://user-images.githubusercontent.com/22936644/31231087-219db472-a9e6-11e7-9e9e-aac4da766762.png)
![4](https://user-images.githubusercontent.com/22936644/31231089-21a47460-a9e6-11e7-8ad6-67b04843e177.png)
![5](https://user-images.githubusercontent.com/22936644/31231088-219f9922-a9e6-11e7-91aa-d3ca88c4215e.png)

**Comment by Gummikavalier** [comment]
Did you set
`Domain Search User`?
(Not Domain Search User ID)

We have it in form:
`CN=ldap_search_user,OU=Users,DC=example,DC=com`

Also can you see all your users listed under `Users` after you have pressed `Sync Users` on the LDAP page? (May take some 20 seconds to get populated after initiating sync.)

**Comment by VedranOP** [comment]
@Gummikavalier Yes, I even chnaged couple, created new one etc. 
Test does not go well if you don't, I think?

When I select import users, in users tab I don't see AD users from CHAT group. But Sync test goes well.

**Comment by Gummikavalier** [comment]
Ok. From what I see the differences to our setup would then be, leaving out encryption stuff, that we don't use the group (CN) directly in the base DN (looking at your first picture) but:

`OU=xx,DC=xx,DC=local`

and do `domain search filter` that would look like

`memberof=CN=CHAT,OU=XX,DC=XX,DC=local`

Also we don't have anything in `Default Domain` and we have `Merge existing users = false`

**Comment by Gummikavalier** [comment]
Also I forgot to add: Login fails if you don't have anything in the mail attribute in AD.

**Comment by VedranOP** [comment]
@Gummikavalier  thank you for your help....I changed all as you did and still only 2 users in users tab and I can not log in with desired users :(

**Comment by VedranOP** [comment]
still no solution....

**Comment by Gummikavalier** [comment]
I checked that AD does not have attribute called `name` by default. You have one in your `User Data Field Map`.

`{"name":"name", "mail":"email"}`

You should use one of these:
`givenName`
`sn`
`displayName`
`sAMAccountName`

For example `{"displayName":"name", "mail":"email"}`

**Comment by rodrigok** [comment]
@VedranOP Did you solve your problem?

If not please let me know and we can chat directly to find the solution or fix some bug.

**Comment by VedranOP** [comment]
I made a fresh reinstall and now all good. Thank you... :)

**Comment by rodrigok** [comment]
Ok, I'll close this issue.

Let me know directly if you have more issues in LDAP (https://open.rocket.chat/direct/rodrigo.nascimento)

Thanks
