### ISSUE TITLE
[Bug] Can't send a message

### ISSUE THREAD

**Issue by icosamuel** [RocketChat/Rocket.Chat#8412]
### Description:
I could not consistently reproduce this bug, but under certain circumstances, the `enter` button alone will only add a `new line` character in the messagebox, as if I would be holding `shift`. The icon also does not change to the `send button` which would allow me to send it mannualy.

Restarting the Rocketchat client seems to fix the problem, but it's far from a permanent solution.

### Server Setup Information:
* Version of Rocket.Chat Server: 0.58.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1

### Expected behavior:
![send_message_bug_2](https://user-images.githubusercontent.com/5400332/31234612-5843d23c-a9bd-11e7-87e7-9fa8334753dc.png)

### Actual behavior:
![send_message_bug_1](https://user-images.githubusercontent.com/5400332/31234616-5ca8c36e-a9bd-11e7-9b7d-077f5833d5be.png)

**Comment by himbeere** [comment]
Yes. Saw that too the other day. Thought i hit the wrong key combination or something. 0.58.3.

**Comment by tykisson** [comment]
I had this happen as well. Found if I hit backspace to remove everything it would go back to normal. 0.58.4

**Comment by ggazzo** [comment]
I will close this issue because we changed all this composer and code... any problem please open again :)
