### ISSUE TITLE
Session verification

### ISSUE THREAD

**Issue by OsamaMahmood** [RocketChat/Rocket.Chat#842]
After a password reset link is requested and a user's password is then changed, not all existing sessions are logged out automatically. 
Logging in with the new password doesn't invalidate the older session either: 
I could browse your website using two sessions 
(in two different browsers) which were initiated using two different passwords.

IMPACT:-

If someone have the password for a user and has logged in to his account and the owner changes its password but the attacker will still have access to the account (If he is using the session)

**Comment by marceloschmidt** [comment]
Seems this has already been fixed... Closing.
