### ISSUE TITLE
No X-Frame Header Set

### ISSUE THREAD

**Issue by OsamaMahmood** [RocketChat/Rocket.Chat#843]
There is no X-Frame Header in the response of the web demo.rocket.chat which lead it to Clickjacking Vulnerability
##

**Comment by rodrigok** [comment]
@OsamaMahmood can you explain more and how we can test this issue?

Thanks

**Comment by Megatronic79** [comment]
@OsamaMahmood if you are securing this site with a reverse proxy such as apache the n you can easily protect against these other  types of vulnerability’s. Look at the security modules and general apache hardening for more details you can test against these issues with products such as burp – find that here https://portswigger.net/burp/

**Comment by OsamaMahmood** [comment]
@rodrigok if you want to test it with tools it is also fine but the most easy way is that you try to load it in an iframe tag it it loads it mean it is not  using X-Frame Header

**Comment by rodrigok** [comment]
@OsamaMahmood so this header is to prevent load Rocket.Chat into an iframe?

If yes, we use iframe to load multiple chats in our desktop application.

**Comment by OsamaMahmood** [comment]
Yes it will prevent loading in iframe

**Comment by Megatronic79** [comment]
@rodrigok  Maybe we set the x-frame to SAMEORIGIN - to satisfy the desktop app requirement and the click jacking issues raise? again this can just be done in the reverse prox.

**Comment by OsamaMahmood** [comment]
yes that will be good it will solve this issue and also satisfy your requirement

**Comment by rodrigok** [comment]
We don't know what is the **origin** of the Desktop app, so we will do some tests and add an option in the settings to define a list of allowed domains for iframe

**Comment by TwizzyDizzy** [comment]
Still relevant today.

**Comment by Sx3** [comment]
Still same
when X-Frame Header Set the desktop app is not loading the content properly

**Comment by rodrigok** [comment]
We will test this again and check if it still a problem with our Desktop App.

If it's not, we will add this enabled by default with an option to disable it, probably allowing to set the domains to restrict.

Important to note that this change is a BREAKING change and should be release in the next major version only.

**Comment by Sing-Li** [comment]
How are we doing with testing this?   Thanks.
