### ISSUE TITLE
[Bug] Text being cut off for some letters latest release candidate

### ISSUE THREAD

**Issue by jszaszvari** [RocketChat/Rocket.Chat#8432]
### Description:

Text of some of the 'larger' letters is being cut off at the bottom.

Had a look but could not find this reported yet. Apologies if it's a duplicate. 

Tried different browsers and different machine. Same issue. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.11

![image](https://user-images.githubusercontent.com/872463/31309995-a5a42b10-abdb-11e7-9d85-c8ed60f9767f.png)

![image](https://user-images.githubusercontent.com/872463/31309997-ab1c96c2-abdb-11e7-89ed-8885ba5d7327.png)

**Comment by TwizzyDizzy** [comment]
Curious. I had this issue reported here: https://github.com/RocketChat/Rocket.Chat/issues/8129 and it should have been (and was for me) fixed with PR https://github.com/RocketChat/Rocket.Chat/pull/8154 that has been released with https://github.com/RocketChat/Rocket.Chat/releases/tag/0.59.0-rc.6.

**Comment by jszaszvari** [comment]
It's stopped happening now. not sure where it got fixed.. But all good!
