### ISSUE TITLE
[Bug] If import failed second import try will result in 2x the amount of import data

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8435]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4
--

### Steps to Reproduce:

1. 
2. 
3.

**Comment by graywolf336** [comment]
@maxpen which importer are you using? Because there is a ton of code in Slack's to prevent this.
