### ISSUE TITLE
[Bug] [UX] Can't select generated codes for 2fa or use them to disable 2fa

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8440]
### Description: When you enable 2fa, https://gyazo.com/f3ef03e8aca93aadcdc8c992f1582ab9

When there is a pop up with the securty backup codes  nothing can be selected from the text on it. 

Actually alot on the site cant be selected, the entire account page content is copy paste locked and alot of other places too...

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

1.  scan barcode
2.  get key
3.  enter key
4. get backup codes pop up window in <code>code block</code>
5. can't COPY the backup codes.
6. When trying to use the codes I copied through inspect element they fail and can't be used!

**Comment by mariaeduardacunha** [comment]
Tested in the latest version (3.0.0-develop) and this issue doesn't happen anymore. Also, links shouldn't be highlighted. If you happen to experience this issue again, please reopen this with updated details. Thanks!
