### ISSUE TITLE
Cannot open channel from the search results list

### ISSUE THREAD

**Issue by steven-tib** [RocketChat/Rocket.Chat#8442]
### Description:

On demo.rocket.chat it's not possible to open a new channel form the search results. It always redirects back to the home/welcome screen after few seconds of trying to load the channel.

I was still able to open a new channel from a link in a conversation by clicking on the #channel link. Once you have clicked this link and the channel has been opened once (not yet joined), it's then also possible to open it from the search results list.

### Server Setup Information:

* Version of Rocket.Chat Server: demo.rocket.chat @ 8th of october 2019

### Steps to Reproduce:

1. Search anything in the search field
2. Click on a channel that you know you never visited before
3. Wait for the channel to load

### Expected behavior:

After step 3. should open the channel

### Actual behavior:

After step 3. you get automatically redirected to the home/welcome screen instead of the actual channel

**Comment by cyclops24** [comment]
@steven-tib Good catch. 😉 
Guys I have same issue with new RC.

**/CC:** @karlprieb , @ggazzo

**Comment by cyclops24** [comment]
Part of #8175.

**Comment by rodrigok** [comment]
Fixed by #8514
