### ISSUE TITLE
How to allow direct messages between my channel members only?

### ISSUE THREAD

**Issue by mborhade** [RocketChat/Rocket.Chat#8444]
How to allow direct messages between my channel members only? (do not show other channel members).
user may be in one or more channels and I want to allow direct messages only between those members.
any solution ?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
