### ISSUE TITLE
Bot output changed from 0.5.10 to 0.57.3

### ISSUE THREAD

**Issue by tbaehr** [RocketChat/Rocket.Chat#8445]
I have written a small integration to get some values from Jira.
After upgrading from 0.5 to 0.57 the behavior changed, even all older messages are not shown with their HTML markup instead of BOLD numbers for each jira issue type.

example: 
```HTML
 by priority
Normal
<span class="copyonly">*</span><strong>70</strong><span class="copyonly">*</span>  
Major
<span class="copyonly">*</span><strong>8</strong><span class="copyonly">*</span>
Minor
<span class="copyonly">*</span><strong>4</strong><span class="copyonly">*</span>  
Critical
<span class="copyonly">*</span><strong>1</strong><span class="copyonly">*</span>
```

used to be just simple
Normal
<span class="copyonly">*</span><strong>70</strong><span class="copyonly">*</span>  

(just noticed that the markdown here does actually parse the above line correctly and I had to put em in HTML tag )

so did the markup generator/parser get changed for BOT messages?

Output is generated in the integration via

 attachment.fields.push({title: i, value: '[ *'+PRIO[i]+'* ](' + link + i+')' , short: true});

**Comment by geekgonecrazy** [comment]
Wow what a jump!

Yes I know for certain the markdown parser has received attention many times since 0.5

It didn't just get changed for bot message but across the board.
