### ISSUE TITLE
[Bug] [UX] Be able to delete log messages too [with permission setting]

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8450]
### Description: One should be able to delete messages like: 
Pinned a message:
thecryptonetworktm was set moderator by matt

You can do this in Slack as well so I think its good to add here too. In case you fuck up and do something stupid you can delete the log. To prevent abuse set this as a permission setting too so not everyone can do this who happen to be a mod or admin but maybe only owner level. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

1. 
2. 
3.

**Comment by rodrigok** [comment]
Closing this by inactivity
