### ISSUE TITLE
How do I register device token to send Push Notification on cordova app using API

### ISSUE THREAD

**Issue by imrealashu** [RocketChat/Rocket.Chat#8452]
I have an existing cordova app on which I've implemented the Realchat websockt. I want our app to handle push notifications for chat by RC server only. 
The way mentioned in sample cordova app is that I need to login to get my device token registered on RC server which I think won't do in my case. I need to register device token using API only.
Is there any way to achieve ? or any way around ?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by robindijkhof** [comment]
@imrealashu Did you already find an answer? If so, could you share it with me?
