### ISSUE TITLE
[bug] [ux] Away status doesn't show in flex-tab area

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8453]
### Description: https://gyazo.com/f43856e177bbc3c7876e7f3e06dc9650

If someone could provide me with the css meanwhile to fix this that would be great! 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

1. 
2. 
3.

**Comment by ggazzo** [comment]
I think its working now. If I'm wrong please reopen (:

![image](https://user-images.githubusercontent.com/5263975/40525390-28741b02-5fb6-11e8-9298-868d83a5c9d1.png)
![image](https://user-images.githubusercontent.com/5263975/40525375-167b4ccc-5fb6-11e8-8476-e9fa3ad88323.png)
