### ISSUE TITLE
[Feature] Integrate this slack security bot its an FREE alternative to metacert

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8455]
### Description: https://github.com/demisto/alfred
https://dbot.demisto.com/

### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by timkinnane** [comment]
Specific bot requests are out of scope for these issues, but we collect them under one issue related to general bots features here: #10174
