### ISSUE TITLE
Custom sound: says wrong file format but is mp3

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#8460]
When uploading an mp3 file as custom sound, it says wrong file format. But the suggested encoding is mp3. Using 120kHz / 44100/ 2ch.

This had worked until RC 0.56 with the same sound file but is not working anymore with RC 0.58.1.

**Comment by rasos** [comment]
Duplicate of #6200 - apparently the fix was not sufficient.

**Comment by rasos** [comment]
Issue is still open in RC 0.62 - upload of mp3 custom sound files only possible with Chromium, not with other browsers.

**Comment by vynmera** [comment]
Yep, broken in FF here too, always have to switch to Chromium for it. FF also seems to not pick up the requested mimetypes - the file picker shows all file types by default.

**Comment by vynmera** [comment]
This will be fixed in #11139.
