### ISSUE TITLE
Emojis not visible

### ISSUE THREAD

**Issue by olliff** [RocketChat/Rocket.Chat#8465]
### Description:

Emojis are not visible in Emoji and Reaction menu
![2017-10-11 23_23_18-rocket chat](https://user-images.githubusercontent.com/7170155/31468272-637ad8f6-aedd-11e7-92b9-8caa9d70ab93.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: CoreOS alpha
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4 - x64

### Steps to Reproduce:

1. Join any public / private channel as admin or user
2. Open Emojis / Reactions menu - emojis are not showing up

### Expected behavior:

should be obvious

### Actual behavior:

emojis are not showing up

### Relevant logs:

only some ldap errors, nothing related
no errors in Browser Console

Edit: custom emojis are displayed properly

**Comment by timothyparez** [comment]
Same in 0.58.4
Did see this in the browser console: 

`There is no route for path: /packages/packages/emojione_emojione_assets/sprites/emojione.sprites.png`

**Comment by olliff** [comment]
emojis in mobile app work for me too

**Comment by exagon** [comment]
have the same problem

**Comment by bibimarujp** [comment]
changed sprites.css directory in #8078
I think it is necessary to change the path in [sprites.css](https://github.com/vcapretz/Rocket.Chat/blob/a4b2e684f7c9da2cd7b912a5ecf33f0d5bd39cbb/packages/rocketchat-emoji-emojione/client/sprites.css#L15)
```
- background-image: url("../../packages/emojione_emojione/assets/sprites/emojione.sprites.png");
+ background-image: url("../../../packages/emojione_emojione/assets/sprites/emojione.sprites.png");
```

**Comment by timothyparez** [comment]
Reported in #8663 as well
And fixed by commit: https://github.com/mutdmour/Rocket.Chat/commit/5de2ca41728d11660d6c2b468030541cc41a5abc

**Comment by ryoshimizu** [comment]
also changed packages directory in sprite.css to reference relative url

**Comment by randomsymbols** [comment]
![gmlXMc jpg](https://user-images.githubusercontent.com/22531452/74100895-5491ea00-4b7f-11ea-9d98-8422d846e321.png)

Linux Rocket Chat version 2.17.2

**Comment by gstlouisgit** [comment]
what's the deal with this?  I have this problem and it is dated from 2017 and is this still going on?
