### ISSUE TITLE
Live chat disorder opening chats

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#8466]
### Description:

i was searching In livechat->current chats as admin to view some chats ,
but i found some chats have issue to opening 

some examples to clarify : In my current chat list i have guest 1 - guest 2  ..... guest 20

when i click on "guest 18" it opens this link rocket.chat/live/5 

and when i click on guest 5 again it opens rocket.chat/live/5 the same chat.

Some chats in the list are duplicated while their names and status are different !

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Deploy on an ubuntu VM (LXD) by clone and node main.js
* Number of Running Instances: 1
* DB Replicaset Oplog: Enable
* Node Version: 4.8.4

### Steps to Reproduce:

1. have several guest live chats 
2. close some of them after finishing
3. go to your current chatlist
4. click randomly on different latest chats

### Expected behavior:

Click on the chat and go to related chat link 

### Actual behavior:

Click on a chat that you see still it's open and it's for a different date with a different name and you will go to an old and closed chat .(other chat anyway)

### Relevant logs:
`[34mI20171011-19:12:15.776(0) Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined   at [object Object].Meteor.methods.sendMessage (/home/rchat/programs/server/packages/rocketchat_lib.js:14442:59)   at [object Object].methodsMap.(anonymous function) (/home/rchat/programs/server/packages/rocketchat_lib.js:1109:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/home/rchat/programs/server/packages/ddp-server.js:1857:12)   at /home/rchat/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /home/rchat/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /home/rchat/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/home/rchat/programs/server/packages/ddp-server.js:874:21)   at /home/rchat/programs/server/packages/ddp-server.js:753:85  
[34mI20171011-19:12:37.713(0) Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined   at [object Object].Meteor.methods.sendMessage (/home/rchat/programs/server/packages/rocketchat_lib.js:14442:59)   at [object Object].methodsMap.(anonymous function) (/home/rchat/programs/server/packages/rocketchat_lib.js:1109:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/home/rchat/programs/server/packages/ddp-server.js:1857:12)   at /home/rchat/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /home/rchat/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /home/rchat/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/home/rchat/programs/server/packages/ddp-server.js:874:21)   at /home/rchat/programs/server/packages/ddp-server.js:753:85  
[34mI20171012-01:36:39.154(0) Exception in defer callback: Error: Can't send mail - all recipients were rejected: 550 5.1.1 <sup1246@mysite.org>: Recipient address rejected: User unknown in local recipient table   at Object.Future.wait (/home/rchat/programs/server/node_modules/fibers/future.js:449:15)   at Mail._syncSendMail (packages/meteor.js:209:22)   at smtpSend (packages/email.js:116:13)   at Object.Email.send (packages/email.js:174:5)   at Object.Email.send (packages/rocketchat_monitoring.js:3496:28)   at /home/rchat/programs/server/packages/rocketchat_lib.js:1804:14   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at packages/meteor.js:452:25   at runWithEnvironment (packages/meteor.js:1188:24)      - - - - -   at SMTPConnection._formatError (/home/rchat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)   at SMTPConnection._actionRCPT (/home/rchat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1338:28)   at SMTPConnection.<anonymous> (/home/rchat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1293:30)   at SMTPConnection._processResponse (/home/rchat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)   at SMTPConnection._onData (/home/rchat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)   at Socket.<anonymous> (/home/rchat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)   at emitOne (events.js:77:13)   at Socket.emit (events.js:169:7)   at readableAddChunk (_stream_readable.js:153:18)   at Socket.Readable.push (_stream_readable.js:111:10)   at TCP.onread (net.js:540:20)  `

Browser has not any error in console .

**Comment by MartinSchoeler** [comment]
Hey I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
