### ISSUE TITLE
Create Documentation about scalability

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#847]
We have a few deployments that we can collect some numbers and create a wiki page describing the scalability of Rocket.Chat

Some interesting meteor references:

http://stackoverflow.com/questions/18083835/how-many-concurrent-users-can-a-web-app-built-in-meteor-js-handle

**Comment by guarilha** [comment]
I think #520 may contain relevant information for this task

**Comment by dandv** [comment]
Right now I see 44,050 users in the demo chat:

![image](https://cloud.githubusercontent.com/assets/33569/13831549/c34eca5a-eb91-11e5-8db2-fa3058266a01.png)

Is this number correct? Are all those clients maintaining a DDP connection to the server? If so, rock on!

**Comment by engelgabriel** [comment]
Hi, please follow https://github.com/RocketChat/Rocket.Chat.Docs/issues/68
