### ISSUE TITLE
Option Email -> Direct Reply missed

### ISSUE THREAD

**Issue by boldt** [RocketChat/Rocket.Chat#8470]
### Description:

Looking into the docs, Rocket.Chat offers direct-reply via mail:

https://docs.rocket.chat/administrator-guides/email/direct-reply

We installed version 0.58.4 via docker. The option "Direct Reply" does not exists. We cannot set up POP3 or IMAP.

**Comment by localguru** [comment]
I think this is a new feature in upcoming 0.59

**Comment by MartinSchoeler** [comment]
Yes this feature will arrive in `0.59`.

**Comment by boldt** [comment]
What do you think about adding version numbers to the features in the docs?
