### ISSUE TITLE
RocketChat installed, yet browser URL is not loading showing 403 forbidden

### ISSUE THREAD

**Issue by rocketchatdev** [RocketChat/Rocket.Chat#8471]
I have installed rocket chat following https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04#step-1-%14-installing-dependencies

Server is AWS, Ubuntu 14. 

2017/10/12 14:34:09 [error] 15294#0: *47 directory index of "/usr/share/nginx/html/" is forbidden

RocketChat serve working fine in the console but when we try to open the URL it shows 403 forbidden. While there was default index.html file it was showing up but when we removed that it started showing 403 forbidden.

**Comment by root-dir** [comment]
I think you forgot to disable the default page
Run this:
`sudo rm /etc/nginx/sites-enabled/default`
`sudo service nginx restart`

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
