### ISSUE TITLE
Error on setting a new password on recovery

### ISSUE THREAD

**Issue by Smokyish** [RocketChat/Rocket.Chat#8472]
### Description:

A complex issue of the password recovery showing an Error when it should be working and showing an Error and still setting the password, but not informing the user of it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

```
1. request password recovery
2. try to change password with being logged in as another user = error, no password change
3. try to change password without being logged = no error, password changed
no 2fa set

1. request password recovery
2. try to change password with being logged in as another user = error, no password change
3. try to change password without being logged in = error, no password change
4. request new password recovery
5. try to login without being logged in = error, password changed

Second was with 2fa, though i'm not convinced that it was a deciding factor
```

### Expected behavior:

Password is changed without an error and user is informed that the password was successfully changed.

### Actual behavior:

This seems like either a complex issue or multiple issues, finding consistency on the behaviour was difficult. Sometimes you get the error for no apparant reason, sometimes you get the error when you're logged in as another user and sometimes you get the error and the password is actually changed nonetheless.

### Relevant logs:
Nothing in the logs with verbosity 0, Errors only.

**Comment by geekgonecrazy** [comment]
@gdelavald not sure who should take a look.  Please re-assign to appropriate person.

**Comment by alandroid** [comment]
Need this fixed asap..
