### ISSUE TITLE
Feature request: Monitor active users

### ISSUE THREAD

**Issue by parkerrome** [RocketChat/Rocket.Chat#8473]
We would like to be able to monitor logged in users. We'd like to be able to see log-in activity and IP addresses logged for each log-in instance for each user (one for each device).

**Comment by marceloschmidt** [comment]
We are planning to implement a setting for admins to enable/disable IP logging. We have other issues requesting it as well. Closing this on behalf of those, such as https://github.com/RocketChat/Rocket.Chat/issues/8428.
