### ISSUE TITLE
Issue tracker contains many issues that are more support questions

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#8478]
It's so difficult to see what the real issues are. I don't know why Rocket.Chat attracts a sort of community who seem to ask half-baked questions in here, but it would be great if the issues were closed with a polite note to go to #support, which I'm sure would benefit from the traffic as ironically it's pretty quiet in there for the size of the project. I guess #support should also be better advertised / documented.

**Comment by MartinSchoeler** [comment]
@antgel This topic was already discussed a lot in #7476 We try to close as many new issues as possible, but today we don't have enough manpower to go through all the 1900 issues and close the unnecessary ones. But we are welcoming any help, if you find any issues that can be closed, mark me and from time to time I will go there and close it. Thanks!
