### ISSUE TITLE
RocketChat and android 4.4.2

### ISSUE THREAD

**Issue by electravis** [RocketChat/Rocket.Chat#8481]
### Description:

I am able to connect to the demo version of rocket chat however on our live server I keep get connection errors try again. This is only happening on my android 4.4.2 devices all other models are able to log in just fine.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System:  ubuntu
* Deployment Method(snap/docker/tar/etc): SNAP
* Number of Running Instances:  1

**Comment by Gummikavalier** [comment]
It could be that Snap installation or your web server config does not have TLS1.1 enabled (only TLS1.2). Android 4.4.2 does not seem to work without.

**Comment by cwilso03** [comment]
I did the initial setup/config for the system @electravis is referring to.  The Snap installation bundles the web server components.  According to Qualys SSL Labs online test, TLS1.1 is enabled on that system. 

The error seems to be the same as #3447 (https://github.com/RocketChat/Rocket.Chat/issues/3447).

**Comment by Gummikavalier** [comment]
Ok. Just that I got that error too until I got connection and encryption handshake working. Also ciphers could affect together with the protocol.

Just in case that someone has this problem and caused by encryption limitations, here are ssl-parameters that work with our installation with Android 4.4.2:

```
        ssl_ciphers HIGH:!aNULL:!MD5:!3DES;
        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

Note: TLSv1 was required for Android 4.1.

**Comment by cwilso03** [comment]
Clarifying my earlier comment, the Snap installation bundles the web server components, but https was subsequently enabled following this guide:  https://docs.rocket.chat/installation/manual-installation/ubuntu/snaps/autossl
