### ISSUE TITLE
LDAP Not Working in the newest Build (*Beta*)

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat#8493]
Hey Guys,

I use the last develop Version of RocketChat, after the new LDAP Features my Login is totaly broken & tried to fix this in the settings without success.

I use openLDAP in the localhost without Cert or something, nothing was changed before I upgrade RocketChat.

**Sync**

> Field username: uid
> Field to auth: objectGUID,ibm-entryUUID,GUID,dominoUNID,nsuniqueId,uidNumber,uid,mail
> Field to compare: {"givenName":"name", "mail":"email"}
> Sync & Merge contact: yes
> AvatarSync: no

**Search**

> Filter: (objectclass=inetOrgPerson)
> Scope: sub
> Search Field: uid

I started use the current stable and setup the same settings and all works great. I can't & wouldn't downgrade. THX RocketChat 4 Nice Support, I think the issue or problem 4 me will fixed soon.

*No Group Filter active!

**Comment by gjsman** [comment]
Possible duplicate of #8462

**Comment by DoM1niC** [comment]
Ahhh THX Yep the RC12 runs OK 4 me.... sry my misstake
