### ISSUE TITLE
[BUG] [LIST] Old or important bugs list

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8494]
Hi guys,
I think #8175 issue from @mnlbox is very very useful to manage UI and RTL issues. For example we report near 40 issue and fix near 25 UI issues there.
I saw many old and important functionality related issue in this repo that some of theme lost between others for a long time, so I think it's better to aggregate old and important functionality issues here to manage better.

**Comment by engelgabriel** [comment]
Let's track those issues with labels and a our roadmap project board.
