### ISSUE TITLE
How to disable the "new user" sound automatically?

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#8495]
We all know the sound :)    It sounds like an airplane maybe?  Like I've just been given the right to take off my seat belt and move about the cabin.   I know that individual users can go in and adjust the sound... but how do I just disable sounds **by default**?

**Comment by flantascience** [comment]
Anyone on this?  It's drives pretty much every new user nuts and then I've got to explain to them how to change it in their user preferences.

**Comment by notnamed** [comment]
I found the option. Admin -> Accounts -> Default User Preferences. What works best for me was setting Audio Notifications Default Alert to Nothing and setting Notifications sound volume to 0.
