### ISSUE TITLE
desktop app do not show pasted image

### ISSUE THREAD

**Issue by ntvis** [RocketChat/Rocket.Chat#8498]
Description:
Server Setup Information:

    Version of Rocket.Chat Server: 0.58.4
    Operating System: ubunut 16.04 x64
    Deployment Method(snap/docker/tar/etc): tar
    Number of Running Instances: 1
    DB Replicaset Oplog: Disabled
    Node Version: v4.5.0
    desktop app version: 2.9.0
    desktop app OS: windows 7 x64

Steps to Reproduce:

    1) paste a image in channel
    2) desktop app do not show the image

Expected behavior:

desktop app show the image

Actual behavior:

desktop app do not show the image,but in navigator,the image is shown.

after some research ,I find the diffrent between the desktop app and navigator:

in navigator, the image src is
https://mydomain/chat/chat/file-upload/YRZki2DeLLtZibXHk/WX20171016-093654.png

in app ,the image src is
/chat/file-upload/YRZki2DeLLtZibXHk/WX20171016-093654.png

and my server run behind a reserve proxy server sub directory /chat
https://mydomain/chat/

It seems that the desktop app ignor the sub path /chat/
Is this a bug?

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #937](https://github.com/RocketChat/Rocket.Chat.Electron/issues/937) via [**ZenHub**](https://www.zenhub.com/)
