### ISSUE TITLE
[Bug] Active link not highlighted in sidebar

### ISSUE THREAD

**Issue by itaditya** [RocketChat/Rocket.Chat#8500]
In the My account settings view (https://demo.rocket.chat/account/profile). The currently active link in the sidebar is not highlighted. This is disturbing the UX of the app. It would be nice if the currently active window is also highlighted just like it is done in the chat window sidebar. I would love to take on this issue

**Comment by itaditya** [comment]
As this is a simple improvement, it would really help me start contributing to the project. Should I take this ?

**Comment by ggazzo** [comment]
@itaditya hey, feel free to help (:

**Comment by supra08** [comment]
@ggazzo, is anyone working on this? If not, can I take this up?

**Comment by rajvaibhavdubey** [comment]
@ggazzo The PR asssociated with the issue has been stale since January, can i take this up?
ThankYou :smile:

**Comment by ashwaniYDV** [comment]
I would like to work on it
