### ISSUE TITLE
Bug in loader appearance

### ISSUE THREAD

**Issue by itaditya** [RocketChat/Rocket.Chat#8501]
In the Member list tab. the loader which appears before the request is complete is splitting and only half of the vertical portion is being shown. This might be the case of app responsiveness. 
![image](https://user-images.githubusercontent.com/15871340/31597896-86b2bfda-b268-11e7-8965-9d84c88d86d6.png)

I would love to take on this issue

**Comment by cyclops24** [comment]
Part of #8175

**Comment by cyclops24** [comment]
@karlprieb can you take a look at this?

**/CC:** @ggazzo

**Comment by ggazzo** [comment]
fixed  :)
![image](https://user-images.githubusercontent.com/5263975/47164688-e876dd00-d2ce-11e8-8a67-f1f10111c276.png)
