### ISSUE TITLE
[Bug] Search bar not visible in certain states.

### ISSUE THREAD

**Issue by itaditya** [RocketChat/Rocket.Chat#8503]
### Description:

Pressing Ctrl + P must always ensure that the search bar is also visible and not just focus on it.

### Steps to Reproduce:

1. Click on the menu icon in the sidebar present on the right side of the user name.
2. Now the dropdown is opened which hides the search menu. No problem.
3. Press Ctrl + P. Now the search menu is in focus but because the dropdown is currently on top of it. A user can't make out what he is typing.

![image](https://user-images.githubusercontent.com/15871340/31598461-7355cd6c-b26b-11e7-887e-d9c3cf77349f.png)

**Comment by cyclops24** [comment]
Part of #8175

**Comment by itaditya** [comment]
@cyclops24, as #8175 aims to remove many UI discrepancies, should I work on that. What is the current state of that issue

**Comment by cyclops24** [comment]
@itaditya we aggregate new UI related issue there. So you can work on any open issue that list there. :wink:

**Comment by itaditya** [comment]
oh ok, so in my PR should I mention the issue #8175  or #8503 ?

**Comment by cyclops24** [comment]
Definitely you should mention current issue ( #8503 )
