### ISSUE TITLE
Image autoloading does not work behind proxy

### ISSUE THREAD

**Issue by kakawait** [RocketChat/Rocket.Chat#851]
Autoloading gif/image feature is important feature for our team building (or flaming) but when using Rocket.Chat behind corporate proxy feature is broken even with `http_proxy` and `https_proxy` variable set.

Indeed you are using `http` or `https` package from NodeJs that does not respect env variable like `http_proxy` or `https_proxy`.

In order to support proxy you should:

1. Try `request` package instead that respect env variable (https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables)
2. Use such package https://www.npmjs.com/package/http-proxy-agent with `http`/`https` to handle proxy for both `http` and `https` (more information http://blog.vanamco.com/proxy-requests-in-node-js/)

**Comment by VPusher** [comment]
:+1:

**Comment by kakawait** [comment]
If it's candidate to *contribution*/*PR* we should decide if it's possible to remove `http`/`https` node package for `request` package or you want to keep it and try to enable proxy feature on its?

**Comment by indiggio** [comment]
:+1:

**Comment by Sing-Li** [comment]
Closing this one instead of #1194  - hopefully some Digital Ocean hackers will pick it up and add a fix soon.
