### ISSUE TITLE
Meteor 1.2 (HELP TO TEST)

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#852]
We updated the project to the, just released, Meteor 1.2.

The updated code is in this branch https://github.com/RocketChat/Rocket.Chat/tree/meteor-1.2 and we need help to test if is everything working.

**Comment by sampaiodiego** [comment]
:ok_hand:

**Comment by garg** [comment]
When creating a new account I am seeing in the console:

```
$ git status
On branch meteor-1.2
Your branch is up-to-date with 'origin/meteor-1.2'.
nothing to commit, working directory clean
```

```
I20150927-09:52:09.883(-4)? Exception while invoking method 'registerUser' TypeError: Cannot call method 'insert' of undefined
I20150927-09:52:09.884(-4)?     at Ap.insertUserDoc (accounts_server.js:1248:25)
I20150927-09:52:09.884(-4)?     at AccountsServer.<anonymous> (server/lib/accounts.coffee:51:8)
I20150927-09:52:09.884(-4)?     at AccountsServer.insertUserDoc (packages/underscore/underscore.js:763:1)
I20150927-09:52:09.884(-4)?     at createUser (packages/accounts-password/password_server.js:980:1)
I20150927-09:52:09.884(-4)?     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1049:1)
I20150927-09:52:09.884(-4)?     at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:7:21)
I20150927-09:52:09.885(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2554:1)
I20150927-09:52:09.885(-4)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20150927-09:52:09.885(-4)?     at livedata_server.js:708:19
I20150927-09:52:09.885(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
^C
```

It fails on Account_servers.js part of Accounts-base in:

```
Ap.insertUserDoc = function (options, user) {
```

when running this line:

```
    userId = this.users.insert(fullUser);
```

Because this.users is undefined.

**Comment by garg** [comment]
Accounts-Base used Meteor.users.insert in 1.2.0  but 1.2.1 uses this.users. Meteor.users still returns an object but this.users is undefined. 

Any reason why this.users on serverside would return as undefined in this case?

**Comment by gmsecrieru** [comment]
`Ap` object is created on `accounts_common.js` from a call to AccountsCommon.prototype which, AFAICT, does not call AccountsCommon constructor method -- created (this snippet)[https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20count%20%3D%200%3B%0Avar%20AccountsCommon%20%3D%20class%20AccountsComon%20{%0A%09constructor%20%28options%29%20{%0A%09%09this._options%20%3D%20{}%0A%09%09this.users%20%3D%20{%20%27my%27%3A%20%27usersCollection%27%2C%20find%3A%20function%28%29%20{%20console.log%28%27foo%27%29%20}%20}%0A%09%09console.log%20%28%27AccountsCommon%20constructor%20called%20%27%20%2B%20%2B%2Bcount%20%2B%20%27%20times!%27%29%0A%09}%0A}%0A%0Avar%20a%20%3D%20new%20AccountsCommon%3B%0Avar%20b%20%3D%20new%20AccountsCommon%28%29%3B%0Avar%20c%20%3D%20AccountsCommon.prototype%3B%0A%0Ab.users.find%28%29%3B%0Ac.users.find%28%29%3B] for testing.

I would say this is an accounts-base bug. Thoughts?

**Comment by marceloschmidt** [comment]
@gmsecrieru what makes you think meteor's code is trying to do this exactly? I don't think they are trying to access an instance variable through it's prototype.

I think this is what we should expect to happen: https://gist.github.com/marceloschmidt/6d8cd7b38d1d9fb986f9

It doesn't explain why meteor's code isn't working though :(

**Comment by gmsecrieru** [comment]
@marceloschmidt The `Ap` object, which is created on [accounts_common.js](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js) from [AccountCommon`s prototype](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L212) has a method called insertUserDoc, which is declared on [accounts_server.js](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1204) and called by account-password.

The call to what-should-be users collection object is done from within `Ap` as [this.users](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1248). The problem here is that `this.users` is set within [AccountCommon constructor](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L23), thus `Ap.users === undefined` until we call the constructor method.

**Comment by marceloschmidt** [comment]
Also, this is definitely something we did, because removing this piece of code makes it work again: 

https://github.com/RocketChat/Rocket.Chat/blob/master/server%2Flib%2Faccounts.coffee#L48-L59

I think you can close that issue you opened at Meteor and I'll focus on fixing this on our side.

**Comment by marceloschmidt** [comment]
Yes, but if you look at `packages/accounts-base/globals_server.js` you'll see that Accounts is set to `new AccountsServer`, which runs the constructor for later on calling `Accounts.insertUserDoc`

**Comment by gmsecrieru** [comment]
But the triggered exception is coming from `Ap`, not `AccountsServer`:

I20150927-09:52:09.883(-4)? Exception while invoking method 'registerUser' TypeError: Cannot call method 'insert' of undefined
I20150927-09:52:09.884(-4)?     at **Ap.insertUserDoc (accounts_server.js:1248:25)**

**Comment by marceloschmidt** [comment]
I just fixed that in https://github.com/RocketChat/Rocket.Chat/commit/b523eb9d18c223166b923579533be764d2d4b6ae

**Comment by gmsecrieru** [comment]
:+1: working on 1.2.0.2

**Comment by gmsecrieru** [comment]
Closing as Meteor 1.2 was already merged into `master`

**Comment by vikas0121** [comment]
Please help
while calling this method process get stuck.
_id = insertUserDoc.call(Accounts, options, user)

input:
{ username: 'Guest_3129810000-14:35',
 department: 'mt3uAwpz4dSqow7pg',
 type: 'visitor',
 custid: 0,
 country: undefined,
 userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36',   ip: '127.0.0.1',  host: 'localhost:3000' }
