### ISSUE TITLE
[Release Candidate Bug] Reset the layout colors make it transparent

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#8523]
### Description:
Colors in the layout menu reset to "transparent" not to the default rocket.chat colors.
Found this after I upgraded my demo system to RC15.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0.rc15
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances:  3
* DB Replicaset Oplog: yes

### Steps to Reproduce:

1. upgrade to 0.59.0.rc15
2. try to reset my custom set colors in the layout admin interface
3. it resets it to #FFFFFF but it is displayed transparent

### Expected behavior:

The colors should reset to the default rocketchat colors.

### Actual behavior:

It reset the color to transparent

**Comment by eloo** [comment]
same in 0.59.0

**Comment by rodrigok** [comment]
Version 0.59.1 https://github.com/RocketChat/Rocket.Chat/releases/tag/0.59.1 is building and will be available in a few minutes with fixes for LDAP and Color issues

**Comment by TheReal1604** [comment]
@rodrigok you’re awesome!

**Comment by TheReal1604** [comment]
@rodrigok updated my systems to 0.59.1 and the color reset works fine now! Really thanksf or the fast fix.
