### ISSUE TITLE
LiveChat Script, ability to set language by GET-Parameter?

### ISSUE THREAD

**Issue by typoworx-de** [RocketChat/Rocket.Chat#8525]
Is it possible somehow to set the default-language for LiveChat Script-Snippet by giving any GET-Parameter to the Script-URL?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
