### ISSUE TITLE
Difference in release archives

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#8526]
### Description:

It seems as though there has been a change in the release archives presented on the [Rocket.Chat download page](https://rocketchat.github.io/download/). This change doesn't, for example, reflect in the [manual installation documentation for CentOS](https://docs.rocket.chat/installation/manual-installation/centos/)

Before the relaunch, the release candidates and stable releases looked like this

`find ./rocket.chat-0.59.0-rc.9/ -maxdepth 2`

    ./rocket.chat-0.59.0-rc.9/
    ./rocket.chat-0.59.0-rc.9/bundle
    ./rocket.chat-0.59.0-rc.9/bundle/README
    ./rocket.chat-0.59.0-rc.9/bundle/programs
    ./rocket.chat-0.59.0-rc.9/bundle/star.json
    ./rocket.chat-0.59.0-rc.9/bundle/.node_version.txt
    ./rocket.chat-0.59.0-rc.9/bundle/server
    ./rocket.chat-0.59.0-rc.9/bundle/main.js

Nowadays, there are only links to github and those releases look like this (and always looked like this):

`find ./Rocket.Chat-release-candidate/ -maxdepth 1`

    ./Rocket.Chat-release-candidate/
    ./Rocket.Chat-release-candidate/private
    ./Rocket.Chat-release-candidate/.snapcraft
    ./Rocket.Chat-release-candidate/example-ecosystem.json
    ./Rocket.Chat-release-candidate/.editorconfig
    ./Rocket.Chat-release-candidate/lib
    ./Rocket.Chat-release-candidate/client
    ./Rocket.Chat-release-candidate/README.md
    ./Rocket.Chat-release-candidate/.meteor
    ./Rocket.Chat-release-candidate/.dockerignore
    ./Rocket.Chat-release-candidate/example-build-run.sh
    ./Rocket.Chat-release-candidate/.postcssrc
    ./Rocket.Chat-release-candidate/SECURITY.md
    ./Rocket.Chat-release-candidate/.stylelintrc
    ./Rocket.Chat-release-candidate/packages
    ./Rocket.Chat-release-candidate/publish_packages.sh
    ./Rocket.Chat-release-candidate/.gitignore
    ./Rocket.Chat-release-candidate/FEATURES.md
    ./Rocket.Chat-release-candidate/scalingo.json
    ./Rocket.Chat-release-candidate/.openshift
    ./Rocket.Chat-release-candidate/HISTORY.md
    ./Rocket.Chat-release-candidate/package-lock.json
    ./Rocket.Chat-release-candidate/nginx-multi-config.txt
    ./Rocket.Chat-release-candidate/.codeclimate.yml
    ./Rocket.Chat-release-candidate/.scripts
    ./Rocket.Chat-release-candidate/.travis
    ./Rocket.Chat-release-candidate/.travis.yml
    ./Rocket.Chat-release-candidate/.eslintignore
    ./Rocket.Chat-release-candidate/.eslintrc
    ./Rocket.Chat-release-candidate/.stylelintignore
    ./Rocket.Chat-release-candidate/package.json
    ./Rocket.Chat-release-candidate/.sandstorm
    ./Rocket.Chat-release-candidate/.docker
    ./Rocket.Chat-release-candidate/docker-compose.yml
    ./Rocket.Chat-release-candidate/example-pm2.json
    ./Rocket.Chat-release-candidate/install.sh
    ./Rocket.Chat-release-candidate/LICENSE
    ./Rocket.Chat-release-candidate/server
    ./Rocket.Chat-release-candidate/.github
    ./Rocket.Chat-release-candidate/mocha.opts
    ./Rocket.Chat-release-candidate/example-settings.json
    ./Rocket.Chat-release-candidate/app.json
    ./Rocket.Chat-release-candidate/public
    ./Rocket.Chat-release-candidate/tests
    ./Rocket.Chat-release-candidate/CODE_OF_CONDUCT.md

If have not tested this, yet, but I guess this will also impact the https://github.com/RocketChat/Rocket.Chat.Ansible role.

Could you shed some light on this difference?

Cheers
Thomas

### Server Setup Information:

not relevant

### Steps to Reproduce:

not relevant

### Expected behavior:

not relevant

### Actual behavior:

not relevant

**Comment by TwizzyDizzy** [comment]
Or in other words: how do I get from the Github release archive to the bundle?

**Comment by christianreiss** [comment]
I came here for exactly the same issue. I deployed several instances of RocketChat, using `wget https://rocket.chat/releases/latest/download -O rocketchat.tgz` untarring and done. Now this leads to a html page from aws. A manual download yields the source; I am unable to find the binary packages.

I shrieked in horror when I noticed the re-launch.

**Comment by TwizzyDizzy** [comment]
Turns out: old-style tarballs can still be fetched at https://s3.amazonaws.com/download.rocket.chat/build/rocket.chat-[github release tag].tgz

Cheers
Thomas

**Comment by christianreiss** [comment]
This issue was closed without providing any answer or reason. Someone missclicked?
I will re-open a new ticket with same contents.

**Comment by geekgonecrazy** [comment]
https://download.rocket.chat/stable should now do the same as https://rocket.chat/releases/latest/download we're working on hooking the old endpoint back up if at all possible.

**Comment by reetp** [comment]
@geekgonecrazy can you please get this back asap.
The old system worked perfectly well so that we could specify a 'bundle' to download.
I use the bundle to build a RPM and this has messed up my scripting.

**Comment by TwizzyDizzy** [comment]
@reetp check this issue, your answer is in there: https://github.com/RocketChat/Rocket.Chat.Ansible/issues/44
