### ISSUE TITLE
Admin masterkey for private groups

### ISSUE THREAD

**Issue by pokapow** [RocketChat/Rocket.Chat#8533]
Do there is a way to active a masterkey for admin ? I would like to have the possibility to enter to any private groups. Actualy I can only see the groups name, numbers of messages and users, but that it.

Or, can we read directly the messages in the server ? Where are they store ? In database ? If yes can you please explain hox to explore the mongodb of rocket ?

**Comment by marceloschmidt** [comment]
We implemented auditing on Enterprise edition. Please contact sales@rocket.chat if you would like to give it a try.
