### ISSUE TITLE
migrate from 0.58 to 0.59

### ISSUE THREAD

**Issue by ledainam** [RocketChat/Rocket.Chat#8534]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.58
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 01
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4

Dear support team,
How to migrate from 0.58 to 0.59 with tar deploy ? 
I saw that 0.59 have many change from server structure and also change in manual deploy.
Thanks.

**Comment by TomaszDom** [comment]
You are correct that it's not documented anywhere, get ready to pay for the $399/month support plan! 

You need to stop your rocketchat instances, make backups (also not documented), delete your Rocket.Chat installation directory and proceed with normal installation in the same place.

Here's what I do on Ubuntu 16.04.3 with two Ngnix load-balanced instances using the "forever" service named rocketchat1 and rocketchat2, your mileage may vary depending on your particular configuration:

```
sudo -i
curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz
tar -xzvf rocket.chat.tgz
mv bundle Rocket.Chat
service rocketchat1 stop
service rocketchat2 stop
rm -rf /opt/Rocket.Chat
mv Rocket.Chat /opt/
cd /opt/Rocket.Chat/programs/server
export PORT=3000
npm install
service rocketchat1 start
service rocketchat2 start
```

**Comment by localguru** [comment]
That's documented here, see `Update` at the end of the site:

https://docs.rocket.chat/installation/manual-installation/ubuntu/#2-install-rocketchat

**Comment by TomaszDom** [comment]
Wow, didn't notice, must have been added recently.

**Comment by TomaszDom** [comment]
The only missing thing is that the tar release link:

https://cdn-download.rocket.chat/build/rocket.chat-0.59.0.tgz

**Comment by KervyN** [comment]
@TomaszDom You are my Hero. Thanks for the link

**Comment by andreas-bulling** [comment]
@TomaszDom why is this link different from the one that is on the Rocket.Chat website? Is this tgz also available through the official Rocket.Chat git repository and/or website? If one downloads the tgz from here: https://github.com/RocketChat/Rocket.Chat/archive/0.59.0.tar.gz it is a completely different package (I guess the sources while your link points to the bundle?).

**Comment by TomaszDom** [comment]
The link to the bundle disappeared with the website re-design. Now the website links to the source packages, which almost nobody except developers use.

https://rocket.chat/releases/latest/download - and this link still directs to the previous stable version.

**Comment by andreas-bulling** [comment]
Thanks a lot for the clarification. It seems the website urgently needs fixing then... unless this was done on purpose (although I can't imagine why that would be the case given that the documentation still has the correct link)

**Comment by KervyN** [comment]
Don't update yet if you use LDAP: https://github.com/RocketChat/Rocket.Chat/issues/8462

**Comment by rodrigok** [comment]
Version 0.59.1 https://github.com/RocketChat/Rocket.Chat/releases/tag/0.59.1 is building and will be available in a few minutes with fixes for LDAP and Color issues

**Comment by andreas-bulling** [comment]
@rodrigok please add the link to the bundle to the main page again (instead of the link to the sources) - it is the link 99% of users need. Is the 0.59.1 build ready by now? At least https://cdn-download.rocket.chat/build/rocket.chat-0.59.1.tgz doesn't work yet...

**Comment by andreas-bulling** [comment]
the binary is there - but the colors in the admin interface are still wrong...

**Comment by ledainam** [comment]
You save my life @TomaszDom . 
Thanks you so much.

**Comment by SeanPackham** [comment]
You can use the following shortcuts for the latest stable build and release candidate build: 
- https://download.rocket.chat/stable
- https://download.rocket.chat/candidate

**Comment by MartinSchoeler** [comment]
The proper links were added to the website so i will close this issue.
<img width="1041" alt="screen shot 2017-10-23 at 9 28 25 am" src="https://user-images.githubusercontent.com/20868078/31886820-a6f46188-b7d4-11e7-87c9-d7a2380c40c1.png">

**Comment by andreas-bulling** [comment]
@SeanPackham is the link updated automatically? 0.59.2 is not available yet...

**Comment by mddvul22** [comment]
Why is this closed?  The "Past Releases" link still points to the source packages that, as @andreas-bulling mentions, almost nobody uses.   @MartinSchoeler, it seems that the "proper" links have still not been added to the website.  Please reopen.  If one downloads the source tgz from the "Past Releases" link, it is a completely different type of package than what is downloaded when somebody downloads "Latest Stable".

**Comment by ledainam** [comment]
still missing in tar release link for 0.60
![image](https://user-images.githubusercontent.com/25676833/33919935-dc6280d4-dfed-11e7-8e02-cf3a4965556d.png)
https://github.com/RocketChat/Rocket.Chat/releases/tag/0.60.0-rc.0
