### ISSUE TITLE
Internal Server Error since the 0.59.0 when changing the theme variables

### ISSUE THREAD

**Issue by flayks** [RocketChat/Rocket.Chat#8536]
### Description:

I was using the RC13 so far so good and since the stable release to 0.59.0 I had my theme completely broken so started from scratch removing the MongoDB entries etc. But then impossible to customize again the theme's variables anymore, I just get a notification with a flat "Internal Server Error", but in the logs I get this:

> Exception while invoking method 'saveSetting' TypeError: Cannot read property 'type' of undefined
>   at [object Object].Meteor.methods.saveSetting (rocketchat/programs/server/packages/rocketchat_lib.js:15464:18)
>   at [object Object].methodsMap.(anonymous function) (rocketchat/programs/server/packages/rocketchat_lib.js:1276:26)
>   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
>   at maybeAuditArgumentChecks (rocketchat/programs/server/packages/ddp-server.js:1857:12)
>   at rocketchat/programs/server/packages/ddp-server.js:903:20
>   at [object Object].EVp.withValue (packages/meteor.js:1134:15)
>   at rocketchat/programs/server/packages/ddp-server.js:902:47
>   at [object Object].EVp.withValue (packages/meteor.js:1134:15)
>   at rocketchat/programs/server/packages/ddp-server.js:901:46
>   at [object Object]._.extend.protocol_handlers.method (rocketchat/programs/server/packages/ddp-server.js:874:21)
>   at rocketchat/programs/server/packages/ddp-server.js:753:85

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0
* Operating System: Debian 9.1
* Deployment Method: Manual install
* Number of Running Instances: 1
* Node Version: v4.8.4

**Comment by TwizzyDizzy** [comment]
Do you have a list of the documents you deleted from the `rocketchat_settings` collection?

I did the same: stopping rocketchat, deleting all `theme*` documents + the `css` document. I didn't get any error, they got recreated with default settings on starting Rocket.Chat.

Cheers
Thomas

**Comment by rodrigok** [comment]
@flayks Did you restart your instance? Cuz if you delete the setting the update will not work, cuz it tries to get the setting from database first to check the value type.

If you restart the instance all the settings will be created with the default values.

**Comment by MartinSchoeler** [comment]
Hey @flayks , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
