### ISSUE TITLE
LDAP Login with userprincipalName not possible in version 0.59.0

### ISSUE THREAD

**Issue by KervyN** [RocketChat/Rocket.Chat#8537]
### Description:
Hi,
we updated to from version 0.58.4 to version 0.59.0

Currently it is not possible to login with the LDAP credentials.
The authentication works, but the user is not found in the list of already available user.

`rocketchat_logger rocketchat_logger.js:375 LDAPSync ➔ error { [Error: LDAP Authentication succeded, there is no email to create an account. Have you tried setting your Default Domain in LDAP Settings? [LDAP-login-error]]
  isClientSafe: true,
  error: 'LDAP-login-error',
  reason: 'LDAP Authentication succeded, there is no email to create an account. Have you tried setting your Default Domain in LDAP Settings?',
  details: undefined,
  message: 'LDAP Authentication succeded, there is no email to create an account. Have you tried setting your Default Domain in LDAP Settings? [LDAP-login-error]',
  errorType: 'Meteor.Error' }`

LDAP Setting: (Sync / Import)
Username field: sAMAccountName
Unique Identifier: objectGUID,ibm-entryUUID,GUID,dominoUNID,nsuniqueId,uidNumber
std Domain: <empty>
merge existing user: true
sync data: true
user attribute matching: {"cn":"name", "mail":"email"}
sync profile images: false
background sync: false

LDAP Setting: (User Search)
Filter: memberOf:1.2.840.113556.1.4.1941:=CN=chat,CN=Users,DC=TLD,DC=intern
Scope: sub (no idea what that is)
Search field: userPrincipalName

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 4
* DB Replicaset Oplog: yes
* Node Version: 4.8.4

Question2: is it possible to roll back to the old version?

**Comment by KervyN** [comment]
We are currently debugging what the exact problem is: currently it looks like the ldap plugin is broken

**Comment by TwizzyDizzy** [comment]
Please refer to https://github.com/RocketChat/Rocket.Chat/issues/8462 - *I think* this is your problem. I reported directly after it broke, it has not been fixed as of yet.

**Comment by KervyN** [comment]
sure, just close this.
