### ISSUE TITLE
History vanish when click a second time on the same quote

### ISSUE THREAD

**Issue by prusse-martin** [RocketChat/Rocket.Chat#8538]
### Description:

When clicking on a quote a seconda time the whole chat history vanishes.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: ?
* Deployment Method(snap/docker/tar/etc): ?
* Number of Running Instances: ?
* DB Replicaset Oplog: ?
* Node Version: ?

### Steps to Reproduce:

1. Quote a message in a chat;
2. Click the quote (the time link) so the quote is highlighted; 
3. Wait a few seconds and click on the quote again;

### Expected behavior:

The quote is normally highlighted on every click.

### Actual behavior:

On the second click the chat history became blank.

### Relevant logs:

I can't access https://rocket.chat/docs/contributing/reporting-issues#gathering-logs (404).

The problem is how the url is constructed. It is now just appending a new query:
`https://<url>/channel/luncho?msg=Zd8wKiTqBGfHEZ9ir?msg=Zd8wKiTqBGfHEZ9ir`

Notice how the url, it should have just one `?msg=...`.

### Workaround

In case someone hit this it is possible to fix switching channels and reloaing the page.

**Comment by AmShaegar13** [comment]
Fiixed; https://docs.rocket.chat/contributing/reporting-issues/#gathering-logs

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
