### ISSUE TITLE
client console

### ISSUE THREAD

**Issue by johnnykatz** [RocketChat/Rocket.Chat#8553]
Hi.
I am developing a project where I make calls from a desktop client to a client in a raspberrypi, since the raspberry I have no graphical environment, I have only one button with which to answer the call. They can guide me if there is any customer by console or give me an idea where to start.
Thank you very much!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
