### ISSUE TITLE
Cannot Display Additional Fields Without Showing Email Etc

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#8554]
Hi.
I was excited about the ability in 0.59 to show additional fields on a user's profile, only to find out that to do so, you also need to show the extended information such as email etc.
Is it not possible to have the ability to show these extended fields without showing the other information as I don't want people seeing other people's email addresses (and it's not possible for someone to register for an account without giving their email)?
Thoughts?
Dave

**Comment by rasos** [comment]
And please make it easy for a user to edit the additional fields by just clicking on where they are shown.

**Comment by sampaiodiego** [comment]
Emails are currently only showed to admins.
