### ISSUE TITLE
The hot mistakes seen by us over the years of use

### ISSUE THREAD

**Issue by nbotmb** [RocketChat/Rocket.Chat#8558]
![1](https://user-images.githubusercontent.com/32950528/31808366-791e0ecc-b57b-11e7-849a-5caa3d83921c.png)
### Server Setup Information:

Version of Rocket.Chat Server: 0.59.1
Operating System: Debian 8
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 01
DB Replicaset Oplog: Disabled
Node Version: 4.8.4

### Steps to Reproduce:

1. 
Uncomfortable visual view of chat

### Expected behavior:

Comfortable visual view of chat

### Actual behavior:

We'd like to present you to change 3 hot defects annoying us 1 years yet. 
**1/** Please, allow the ability to adjust the width of the right column. He is very wide by choice. 
**2/** Please, make the possibility of personal contact to the user in the chat in one click. The click "User's Login" creates a name in the chat.  
**3/** Pay attention to bug in Firefox browser. There is a white band in left side (screen).
Thank you.

![123](https://user-images.githubusercontent.com/32950528/31808246-f7425bc4-b57a-11e7-86c2-01cf8ff98c35.png)

**Comment by geekgonecrazy** [comment]
A lot of UI redesign.  Hopefully it’s much better :)
