### ISSUE TITLE
Multi Monitor problem with Rocket Chat Client for Windows

### ISSUE THREAD

**Issue by Bntn-cgm** [RocketChat/Rocket.Chat#8559]
Hi,

there is a Problem with the Rocket Chat client for windows in Multi-Monitos environments.
It is simple to reproduce and very annoying in daily use.

Setup:
Laptop, 
additional Monitor attached, 
Windows 10 (but Version does not matter), 
any Version of Rocket Chat for Windows.

Reproduction of Bug:
Start Windows and Rocket Chat,
Place Rocket Chat on second screen,
Stop windows,
detach second screen,
start windows,
start rocket chat
rocket chat stays on "second screen".
I found no way to reach that window again until i plugged in a second screen
AND placed it in the same position relative to the main monitor like the monitor
before.

This also happens in docking environments and is very annoying. I have to dock and
undock several times a day and every program switches to mainscreen after undock.
only Rocket chat stays on the onlonger available screen.

**Comment by GENSUSAN** [comment]
I am Gen Susan by name and am from united state America I will like you to contact me through my email okay I have an important issue to shear with you and I will like you to pay attention to me is very very urgent okay kindly contact me at gensusan0@gmail.com for more details okay love you

**Comment by MartinSchoeler** [comment]
Closing this and giving preference to https://github.com/RocketChat/Rocket.Chat.Electron/issues/380
