### ISSUE TITLE
Bug in pop up menu in mobile version of RocketChat

### ISSUE THREAD

**Issue by nbotmb** [RocketChat/Rocket.Chat#8560]
### Description: Menu bug in mobile version of RocketChat (not "+")

When long tapping in message on mobile version of RocketChat, pops up menu and it look like this:

![screenshot_2017-10-19-09-40-54-458_com konecty rocket chat](https://user-images.githubusercontent.com/32950528/31809342-fbcb0c86-b57f-11e7-9e5b-be1964230c9f.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 01
* DB Replicaset Oplog: Disable
* Node Version: 4.8.4

### Steps to Reproduce:

1. Install mobile version of RocketChat (not "+" version)
2. Long tap to any message 
3. Profit!

**Comment by TwizzyDizzy** [comment]
Might be clever, then, to report this issue in the repository for the android app and not here (here being the repository of the Rocket.Chat Server): https://github.com/RocketChat/Rocket.Chat.Android

Cheers
Thomas

**Comment by nbotmb** [comment]
Ok, thanks!
