### ISSUE TITLE
[Feature Request] Allowing uppercase letters in channel name on channel creation

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#8563]
Currently it is not possible to create channels with uppercase letters in the channel name. However, feedback from non-tech people (especially business people) is, that lowercase channel names look pretty unprofessional in an enterprise environment. 

**Feature Request:**
Allow uppercase letters in the channel name on creation. 

*Side note*: In 0.59 the user cannot insert uppercase letters on channel creation. This behavior is okay, since it prevents uppercase letters. From an user perspective this is not intuitive, because the user does not get a hint that uppercase letters are prevented.

**Comment by mrsimpson** [comment]
In 0.59, there is a configuration option to allow special characters in the room-name:
Layout -> User Interface -> allow special characters...
<img width="697" alt="room-name-setting" src="https://user-images.githubusercontent.com/17176678/31826104-73622840-b5b4-11e7-872b-d153ae45237f.png">
<img width="936" alt="room-name" src="https://user-images.githubusercontent.com/17176678/31826105-73b75720-b5b4-11e7-9c44-ebdd2cc35221.png">
