### ISSUE TITLE
Links open up on top of Rocket.Chat window in Chrome

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#8564]
### Description:

In Chrome clicking a link opens it in the same window. Clicking link in the preview part opens up a new tab.

In Firefox both actions open up the new tab.

### Steps to Reproduce:

1. Click link in the message part.

### Expected behavior:

Link opens up in the new tab.

### Actual behavior:

Link opens up in the same window as where Rocket.Chat is displayed.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 5
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Gummikavalier** [comment]
Hmm, looks like I cannot reproduce this anymore, although it worked like a clock earlier. I had refreshed browsers many times and all...
Will close this if we cannot reproduce it for a week or two.

**Comment by localguru** [comment]
can not reproduce this with Google Chrome Version 62.0.3202.62 (Offizieller Build) (64-Bit)

**Comment by PeeterAngelo** [comment]
Not a problem with Chrome, happens in Firefox as well, seems to happen with scheme:// links, the problem is in the generated HTML.

![image](https://user-images.githubusercontent.com/9083644/32173276-b7a55596-bd7e-11e7-825c-496cc0002ab2.png)

Top link's HTML is:
<a href="http://rocket.chat" target="_blank" rel="noopener noreferrer">rocket.chat</a>

Middle link:
<a href="https://rocket.chat">https://rocket.chat</a>

Preview link:
<a href="https://rocket.chat" target="_blank"><strong>Rocket.Chat - Free, Open Source, Enterprise Team Chat</strong></a>

Middle link (the one where scheme:// is specified) is missing the target="_blank" attribute.

**Comment by PeeterAngelo** [comment]
target="_blank" is also missing when you create the link with Markdown e.g. `[link text](https://rocket.chat)`

**Comment by tuudik** [comment]
:+1:

**Comment by Gummikavalier** [comment]
We haven't seen this anymore (currently runnin 0.59.3), even without _blank in the href. The problem just vanished. :|

**Comment by PeeterAngelo** [comment]
Does not seem to be happening in the app (tested on Windows), but it does happen in Chrome.

**Comment by ndousson** [comment]
I can confirm that this always happen in chrome with the latest release (0.60.0-develop). We use RC in entreprise and all collabs have the problem. Hope that will can be fixed one day.

**Comment by akachapati** [comment]
Is it possible to do something with Layout > Custom CSS to alter this behavior?

**Comment by tzar** [comment]
We have this issue in chrome with the marked parser

**Comment by ulope** [comment]
Happening here as well. Multiple browsers, RC version 0.64.0.

**Comment by jtimon** [comment]
I can reproduce it on chromium for the instance my company runs. It started hapening after we updated the last time, I think. Sorry, I don't have more details, I will ask.

**Comment by jhfrontz** [comment]
Also an issue on MacOS (Safari 11.1/MacOS 10.11.6).

**Comment by tzar** [comment]
I'm working around this for now with this userscript in case it's useful to anyone (replace \<add-your-domain-here\>):

```js
// ==UserScript==
// @name         Rocket.Chat Link Fixer
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Forces links in messages in rocketchat to open in a new window
// @author       tzar
// @match        https://<add-your-domain-here>/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    $(document.body).on("click", ".message a", function(evt) {
        evt.preventDefault();
        evt.stopPropagation();
        window.open(this.href, '_blank');
    });
})();
```

**Comment by PeeterAngelo** [comment]
The workaround posted above works in Chrome but unfortunately seems to break behavior in the client...

**Comment by kaiiiiiiiii** [comment]
Can you guys please update your RC instance to the latest version (0.64.2) and try again? I can not reproduce the issues behavior with that version, all links get rendered with a `target="_blank"` (macOS, High Sierra, tested with latest Chrome & Safari/Windows 10, tested with latest Chrome).

Thanks

**Comment by PeeterAngelo** [comment]
I'd love to, but 0.64.* breaks slackbridge.

**Comment by kaiiiiiiiii** [comment]
Hi @ndousson,

I still struggle to reproduce the issues behavior on open.rocket.chat =/

![screen shot 2018-05-21 at 11 08 13](https://user-images.githubusercontent.com/4711233/40299730-7f8ecda0-5ce7-11e8-86fb-37daba1d599b.png)

**Comment by ndousson** [comment]
Hi @kaiiiiiiiii,

I've created a new private channel to be in the same context than you and i can't reproduce link with target="_blank".

![screenshot_20180521_113332](https://user-images.githubusercontent.com/6339309/40301207-af7e514e-5ceb-11e8-85da-536d17128ce1.png)

As you can see in the capture above, the problem is always here.

I'm on Google Chrome **Version 66.0.3359.181 (Build officiel) (64 bits)** release.

I don't know why this happen for me and not for you 😞

**Comment by ulope** [comment]
@kaiiiiiiiii do you you have the marked parser in use?

**Comment by PeeterAngelo** [comment]
Ah yes, indeed this might be related to the Marked parser, I mentioned here https://github.com/RocketChat/Rocket.Chat/issues/8564#issuecomment-340446641 that the problem also appears when creating a link with Markdown

**Comment by tzar** [comment]
Based on: https://github.com/markedjs/marked/issues/655#issuecomment-383226346

In: https://github.com/RocketChat/Rocket.Chat/blob/217073f4c010e8472a7521c998e89fd47c7a68ee/packages/rocketchat-markdown/parser/marked/marked.js

We should add:

```js
var linkRenderer = renderer.link;
renderer.link = function(href, title, text) {
    var html = linkRenderer.call(renderer, href, title, text);
    return html.replace(/^<a /, '<a target="_blank" rel="nofollow" ');
};
```

**Comment by tgoetzke** [comment]
Can confirm that depending on the chosen markdown parser the links receive `target="_blank"` attribute or not. Changing the markdown parser to **Original** creates the correct HTML syntax.
Tested with Rocket.Chat version 0.65.1 in Chrome and Firefox.

That would make this issue a duplicate of #8115

The **[solution](https://github.com/RocketChat/Rocket.Chat/issues/8564#issuecomment-390809020)** posted by [tzar](https://github.com/tzar) should fix it.

**Comment by MatthiasHertel** [comment]
Can confirm this behaviour , is there any plan to add `target="_blank"` attribute to the the **marked** markdown parser ?

**Comment by hmc-jellyfish-s19** [comment]
Is there a workaround for this? I'm having the same issue right now.

**Comment by gabriellsh** [comment]
Can't reproduce this in 3.7.0-develop. Tried Every possible type of link:

* [Rocket.Chat](https://rocket.chat/)
* rocket.chat
* https://rocket.chat/

I found a fix for this implemented about 1.5 years ago #13245.

**Comment by JakobFerdinand** [comment]
This ticket should be reopened.
since Release [3.10.5](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.5) and also now in [3.11.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.11.0) the problem is there again.

It´s exactly the same behavior like it is described here.

**Comment by alexander-potemkin** [comment]
it is, indeed... 

> This ticket should be reopened.
> since Release [3.10.5](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.10.5) and also now in [3.11.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.11.0) the problem is there again.
> 
> It´s exactly the same behavior like it is described here.

**Comment by alexander-potemkin** [comment]
@gabriellsh , could you please, re-open the ticket on this regress?

**Comment by Gummikavalier** [comment]
I could not reproduce the issue on 3.11.1 just by putting a link into the message or topic of the channel (latter using markdown syntax [name](url)).

Both chrome and firefox open a new tab when I click this link. Can you advise me to how to reproduce the issue?

I've noticed that if I put links into Home page those need target="_blank", but not anywhere else.

**Comment by alexander-potemkin** [comment]
> I could not reproduce the issue on 3.11.1 just by putting a link into the message or topic of the channel (latter using markdown syntax `[name](url)`).
> 
> Both chrome and firefox open a new tab when I click these links. Can you advise me to how to reproduce the issue?
> 
> I've noticed that if I put links into Home page those need target="_blank", but not anywhere else.

This failing behavior (opening links inside the Rocket.Chat) works for any normal links - put https://google.com and the link would be opened inside.

Same for the attachments, basically...

**Comment by alexander-potemkin** [comment]
Agh, no, pardon me - in my case the problem is with outdated version inside Mac AppStore - I'm running 3.0.3 actually... raised a new ticket: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1974

**Comment by Gummikavalier** [comment]
Thanks, good to know it was the older client.

**Comment by alexander-potemkin** [comment]
yeah... any chance you can give a punch to the 1974 ticket? I guess it's quite a major issue, as the AppStore is the only official distributor for the RocketChat client, as far as I can see?

**Comment by JakobFerdinand** [comment]
I just retried with `3.11.1` and the problem still exists.
As bevor, it´s just when using `Marked` as markdown parser.

![image](https://user-images.githubusercontent.com/16666458/107918487-09689f00-6f6a-11eb-97fe-1482eb1d981a.png)

**Comment by digitaldonkey** [comment]
This also happened Rocket chjat client in 3.1.1. 

Opening external links in an (most of the time) outdated Electron view is a high security risk!!!
If this is not considered a bug I'll switch.

**Comment by gabriellsh** [comment]
I'll open a new issue and link this. I edited the main comment but does not seem to be working...

**Comment by gabriellsh** [comment]
Actually, in retrospect, I tested this on:

Rocket.Chat Version: 3.12.0-develop
Parser: Marked and Original
Desktop Client version: 3.0.6 & 3.1.1 (Windows) & 3.0.7 (macOS)

Both open links in the default browser. This could be due to an outdated desktop client version.

We DO HAVE a few places that don't follow the markdown config and endup redirecting the window both in the browser and desktop client, but it's not related to Marked or this issue. Please, correct me if I'm wrong and this happens in the latest versions of the desktop client.

PS.: Tested simple message links, like `https://google.com`, and in markdown, like `[google](https://google.com.br)`

**Comment by gabriellsh** [comment]
BTW seems like those places are actually now following the config. See #20767 for reference.

**Comment by JakobFerdinand** [comment]
I tested it with `3.12.1`. It works there. 👍
