### ISSUE TITLE
Convert ASCII to Emoji does not work when Marked Markdown support is enabled

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#8565]
### Description:

Convert ASCII to Emoji does not work when Marked Markdown is enabled.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  5
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4

### Steps to Reproduce:

1. Enable Convert ASCII to Emoji in personal user profile settings. (This is on by default.)
2. Check the database that setting is really `"convertAsciiEmoji" : true,`

### Expected behavior:

ASCII emojis should be converted to graphic emojis.

### Actual behavior:

ASCII emojis are not converted to graphic emojis.

**Comment by ondrejtichacek** [comment]
Still not working properly with the version 0.62.2. The conversion from ASCII to Emoji is inconsistent withing a single message -- see print screen below:
![message snapshot](https://puu.sh/zSOI7/134115b928.png)

**Comment by xmedeko** [comment]
Still not working in 2.17 :-(

**Comment by dossantg** [comment]
Same issue in 3.8.0

**Comment by PapsOu** [comment]
The issue is still present in version `3.12.0`

**Comment by Gummikavalier** [comment]
Yeah, this is pretty longstanding. I'm closing this down in favor of that more official one. Thanks for spotting it! :+1:

**Comment by xmedeko** [comment]
@Gummikavalier why closing the issue? The bug still persist.

**Comment by Gummikavalier** [comment]
Because it is a duplicate of a later issue that devs have opened themselves: https://github.com/RocketChat/Rocket.Chat/issues/11214

Discussions regarding issues are best kept in there.

**Comment by xmedeko** [comment]
Ah, sorry, I have overlooked that. Thanks for the reply.
