### ISSUE TITLE
[BUG] Can't disable Offline Email Notifications (0.59.1)

### ISSUE THREAD

**Issue by bedaes** [RocketChat/Rocket.Chat#8568]
### Description:

My instance automatically updated to 0.59.1. Since then all users receive offline email notifications again even if they have set "Offline Email Notifications: Disabled"

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.2.6

### Steps to Reproduce:

1. Upgrade to 0.59.1
2. Write message to offline user

### Expected behavior:

Gets an email notification depending on what is set in account preferences.

### Actual behavior:

Always receives an email notification, even if "Offline Email Notifications: Disabled" is set

**Comment by Gummikavalier** [comment]
On our setup for some users disabling it works while for others it does not.

At least one person who had had it disabled before RC 0.59.1 has this problem, while the rest possibly don't.

In our comparison case user profile preference settings in the database was:
`"emailNotificationMode" : "disabled",`
for both accounts.

**Comment by fuzunspm** [comment]
We are having this issue also, it needs to be fixed since it’s sending all messages as emails

**Comment by JonathanSidego** [comment]
I'm dealing with this, too.
Still trying to find a temporary workaround.

**Comment by Venomen** [comment]
any updates on this? this is the most important issue in latest version ;)

**Comment by ledainam** [comment]
i have same issue. Pls help us to fix it. 
Thanks.

**Comment by rafaelks** [comment]
Happening here too, on `0.59.2`.

**Comment by Venomen** [comment]
Still on 0.59.3

**Comment by dmoldovan123** [comment]
Still on 0.59.3

**Comment by Venomen** [comment]
any news about patching production version? or how we can do it?

**Comment by Venomen** [comment]
Still on 0.59.4, 0.59.6

**Comment by rodrigok** [comment]
@Venomen Is that related with UI problem, like not being able to change the preference or it's related with functionality?

**Comment by TwizzyDizzy** [comment]
@rodrigok from his initial message it's not about setting this option but rather about the functionality: if you set the option to not get mails when you're offline, your're still getting sent those.

**Comment by BastianTrifork** [comment]
Any updates on this? I'm still having this issue
