### ISSUE TITLE
Script personalizado

### ISSUE THREAD

**Issue by nicolasdezena** [RocketChat/Rocket.Chat#8572]
Galera será que conseguem me ajudar? 

Fiz um script personalizado la no menu layout, acontece que sem querer dentro do setInterval eu removo a tag de formulario ou seja não consigo fazer mais nada, qualquer formulario do admin esta sendo removido, como que que eu faço para ressetar isso?

Abs,
Nicolas Dezena

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
