### ISSUE TITLE
cor de fundo da lista de contatos

### ISSUE THREAD

**Issue by welsoncj** [RocketChat/Rocket.Chat#8573]
### Description:

bom dia, 

tenho um leve problema de daltonismo e a cor de fundo da lista de contatos esta me trazendo problemas, tem como mudar a cor do fundo em alguma configuração?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System:
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
