### ISSUE TITLE
Global setting 'Merge private groups with channels' does not work

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#8578]
### Description:

Global setting to merge private groups with channels does not have effect.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 5
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4

### Steps to Reproduce:

1. As an admin under `Layout -> User interface` set the `Merge private groups with channels` to value `true`.
2. Login as an user who has not changed this option in his/her own profile.

### Expected behavior:

Channels and private groups should be merged to the single view on the left pane.

### Actual behavior:

Channels and private groups are still shown separately.

User can change this setting in personal profile and merging works, so the problem is only with the global setting.

**Comment by localguru** [comment]
Can not reproduce this on open.rocket.chat (0.59.1) using settings in personal preferences; channels and private groups are merged.

**Comment by Gummikavalier** [comment]
@localguru Yes, the setting under personal preferences works. The global one under admin settings does not.

**Comment by divergefx** [comment]
I am having this issue with latest version 0.63.1

**Comment by Gummikavalier** [comment]
Old and obsolete. Closing.
