### ISSUE TITLE
Can't add snippet in 0.59.1

### ISSUE THREAD

**Issue by jsivak** [RocketChat/Rocket.Chat#8585]
### Description:

In 0.59.1 there doesn't appear to be a way to create a Snippet.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Docker image rocketchat/rocket.chat:0.59.1
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:
0. Enable Snippet support in Administration > Message > Allow Message Snippeting
1. Create an IM post
2. Edit by clicking on the "..." button
3. Expect a "snippet" icon to be displayed, but none found

Note: I was previously using a 0.58.3 Rocket.chat database and pulled the 0.59.1 docker image and ran it on the existing data. I expected that it updated the database as needed.

Thanks

**Comment by karlettoh** [comment]
Still ongoing in 0.59.3.
+1

**Comment by jsivak** [comment]
I've also done a "fresh" install of 0.59.3, and there is still no method/way to create/add a snippet. So I don't believe its related to any type of "migration" from 0.58.x.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing, since I cannot reproduce this anymore in 0.61.0. If this is still going on under some circumstance, please get back to me! :)

Cheers
Thomas
