### ISSUE TITLE
Resend_verification_mail not i18n'd

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#8586]
### Description:
The resend email verification text to be i18n'd

### Server Setup Information:

* Version of Rocket.Chat Server: `0.59.1`

### Steps to Reproduce:

1. Create an account on a server that requires email verification
2. Don't confirm right away
3. Go to My Account -> Profile -> see text

### Expected behavior:
The text be i18n'd and not the key be shown.

### Actual behavior:
![image](https://user-images.githubusercontent.com/850391/31847373-e0c643a4-b5e0-11e7-9a17-6b0f71fc4cf3.png)

**Comment by gdelavald** [comment]
Same for these tooltips:
![image](https://user-images.githubusercontent.com/6303966/31847409-f146af6a-b5fa-11e7-9921-185550226309.png)
