### ISSUE TITLE
Private group doesn't display in room list

### ISSUE THREAD

**Issue by darthunix** [RocketChat/Rocket.Chat#859]
Steps to repeat an problem.
1. Add a user to a private group Group1.
2. User  can see a line "More private groups" in Private Groups div
3. User leaves room Group1
4. User readded to Group1
5. Now he can't reenter this room any more via interface, because there is no line "More private groups" anymore.  But if User enter http://host:3000/group/Group1 in web browser he reenters this group chat.

Can you fix this problem, so a User can reenter this group via web interface?

**Comment by rwakida** [comment]
This is a side effect of issue #857.  PR #860 should fix this.  Please retest once #860 is merged.  

User is not re-added to room because adding the user to the room from the right "members list" area is broken in master.  You run into the same problem if you create the private group without adding the user.  Then try to add the user from the right "members list" area.

**Comment by sampaiodiego** [comment]
#860 was merged.

can you test if it continues to happen @darthunix ? thanks

**Comment by BdevNameless** [comment]
Hello every1. I have the same problem as @darthunix.
I'm even able to add users into empty private group using right-side panel. But after a user leaves this group, he can't enter it any more via left-side roomlist. I'm still able to add this user again to the group, and i can see him in  "members list" , but he doesn't see the group in his roomlist. He also gets no notification about re-adding to the group. Though, he can enter the room again using direct url as @darthunix mentioned.

**Comment by rwakida** [comment]
Hi @BdevNameless.  

> But after a user leaves this group, he can't enter it any more via left-side roomlist
The user cannot re-enter a "private group".  They must be added by the private group moderator.  Thus, the "More private groups" link will not appear

>I'm still able to add this user again to the group, and i can see him in "members list" , but he doesn't see the group in his roomlist...Though, he can enter the room again using direct url
I tested using the latest from master, and it worked for me.  i.e.The private group automatically appears for the user after they are re-added by the private group moderator.  Can you confirm you have the latest from master.  Try creating a new private group (you'll run into the issue you described if you created the private group before the #860 fix)

**Comment by BdevNameless** [comment]
Thank you @rwakida. I'll check my source's relevance.

**Comment by jclabaugh** [comment]
I have found if a user is added to a private group, then intentionally or unintentionally (quite easy to do by accident in left panel) leaves that private group, the private group moderator can add that user back to the group but that user won't see the group listed in their left panel _until_ the moderator types a message, then everything is 'normal' again. The re-added user can see the private group in the left panel.

I think that perhaps the left panel is a fixed width and the hide/leave icons take up most of the 'real estate' to the right of the private group's label (especially if the group's name is long) that single-clicking in the left panel to try to open a private group to read messages, depending on where the user clicks, can actually hide or remove them from a group accidentally when they did not desire for that action to happen. Not sure how to adjust for this but there has to be an easy way with UI/UX to make this less of an unintended consequence of a single-click to open a private groups' chat. This happens a lot if the message counter is visible (lives over the top of 'leave group' icon). It appears that the onClick works to hide/leave even before the corresponding icon appears onHover.

**Comment by darthunix** [comment]
@sampaiodiego the bug is fixed, thanks!
