### ISSUE TITLE
LiveChat messages all appear to come from the same user. 

### ISSUE THREAD

**Issue by jszaszvari** [RocketChat/Rocket.Chat#8595]
### Description:

When starting a live-chat from the widget on a website, the Live-chat messages are coming from the name of the agent that you are connected too

I'm also not being asked to receive a E-Mail transcript of the chat even though the setting is turned on.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0
* Operating System: Alpine
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 
* DB Replicaset Oplog: yes

### Steps to Reproduce:

1. Embed the widget in a web-site
2. Initiate a live-chat session

### Expected behavior:

For the messages to come from a "LiveChat Guest" / Like it worked before where you could distinguish who was who 

### Actual behavior:

Messages sent by the agent and by the customer show up on both ends as coming from the agent it was connected too

### Relevant logs:
I'm not seeing any errors at all in RocketChat with debug mode 

The Chrome Web Inspector shows this

``Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (VM232 extensions::schemaUtils:115)
    at Object.<anonymous> (VM303 extensions::binding:363)
    at f (VM240 kwift.CHROME.min.js:1)
    at VM240 kwift.CHROME.min.js:1``

Here is a animation of whats going on

![2017-10-23_11-27-30](https://user-images.githubusercontent.com/872463/31868116-09cb060c-b7e6-11e7-8fb6-2a0bd218955f.gif)

**Comment by MartinSchoeler** [comment]
@jszaszvari if you open the livechat on a window that you already are logged on rocket.chat this will happen, try using a anonymous window

**Comment by jszaszvari** [comment]
@MartinSchoeler  Yep you are 110% correct

Apologies for being an absolute idiot! 

Closing
