### ISSUE TITLE
Close/Min/Max buttons on OSX will overlap the profilepicture if serverlist is closed.

### ISSUE THREAD

**Issue by ausminternet** [RocketChat/Rocket.Chat#8600]
![image](https://user-images.githubusercontent.com/5732325/31875845-3b96987e-b7d0-11e7-921e-b35095ec4e91.png)

This can be fixed by adding more `padding-top` to `.sidebar__account` if serverlist is closed.

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #573](https://github.com/RocketChat/Rocket.Chat.Electron/issues/573) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #574](https://github.com/RocketChat/Rocket.Chat.Electron/issues/574) via [**ZenHub**](https://www.zenhub.com/)
