### ISSUE TITLE
0.59 Creation dialog on mobile not usable

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#8603]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1

### Steps to Reproduce:
1. Open open.rocket.chat on a mobile device - either via browser or the cordova app
2. Try to create a new channel

### Actual behavior:
You'll not be able to create the channel, as you cannot reach the create-button.
No scrolling is possible!
![a34i5](https://user-images.githubusercontent.com/17176678/31885069-8f3ed79c-b7ef-11e7-8edc-26d86070b9b3.png)

### Workaround:
Not ideal, but at least not a blocker anymore
```css
.full-modal {
	overflow: auto;
}
```

**Comment by cyclops24** [comment]
Part of #8175
