### ISSUE TITLE
Context-Menu on mobile browsers / devices

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#8604]
### Description:

The context-menu on mobile devices is awkwardly positioned and does not allow to select some functions

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1

### Steps to Reproduce:

1. Open open.rocket.chat on a mobile device
2. Trigger the context-menu (the three vertical dots next to the username)
3. Locate the Logout button

### Actual behavior:

You'll not be able to find it as it's outside the viewport
![99q70](https://user-images.githubusercontent.com/17176678/31885091-9d8591d8-b7ef-11e7-8830-57190f8b76cf.png)

**Comment by geekgonecrazy** [comment]
Double checked this on chrome on 0.59.2 happens same there.

**Comment by immanuelfodor** [comment]
Same here on 0.69.1, Chrome Android. I feel the way the window height is calculated is wrong, the mlsplacement is almost equal to the titlebar's height. Any message context menus or the administration menu popup on the sidebar is affected.
