### ISSUE TITLE
[BUG] Auto-Fill happening in My Account -> Profile screen?

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#8605]
When I enter the profile screen (where I can change my username), my username is changed and the "Save changes" button is enabled

![](https://i.imgur.com/LIPUEY4.png)

Server: team.rocket.chat
Browser: Safari

**Comment by karlprieb** [comment]
I can't reproduce this issue on `develop` branch, it occurs only on our server?
