### ISSUE TITLE
Can't change several user options since 0.59.1

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat#8606]
Since 0.59.1 its impossible to change user options like Use Emojis, Auto Load Images, Save Mobile Bandwidth and others in My Account menu. Some of the options can be changed though. 
This can be reproduced even on demo RC server - just open https://demo.rocket.chat/account - change Use Emojis to False, hit save button and then reload the page - Emojis are still set to True.

**Comment by Gummikavalier** [comment]
This bug existed in 0.58.x too. The settings get saved but next time you enter the page they are not read from the database. If you don't do any changes afterwards the settings stay active.

See #7818

**Comment by MartinSchoeler** [comment]
Did some testing and it seems to be fixed in the latest version. Please reopen this if you experience this issue again. Thanks for the feedback!
