### ISSUE TITLE
No chat history or clear all chat history

### ISSUE THREAD

**Issue by mbowling4** [RocketChat/Rocket.Chat#8612]
I need be to able to make Rocket Chat save no chat history (or wipe history every 24 hours). I have been tossing myself into this for a few days now and have not been able to figure out anything as a solution. My client needs to be able to say they have no internal chat history or chat logging happening on their rocket chat system. (but will settle for 24 hours of history)

Anyone has a solution to this?

Version of Rocket.Chat Server: 0.59.1
Operating System: Ubuntu 16.04.3
Deployment Method: Snap

**Comment by MartinSchoeler** [comment]
Please take a look at https://github.com/RocketChat/Rocket.Chat/issues/7228
