### ISSUE TITLE
Remove: Number of Channels / Favourites shown as it may be mistaken for number of unread messages

### ISSUE THREAD

**Issue by pettitto** [RocketChat/Rocket.Chat#8616]
### Description:

We're using Rocket Chat at my place of work circa ~240 users using it. The feedback I've received following the 0.59.1 upgrade is that the number of channels/favourites/direct messages is, at a glance, easy to mistake for how many unread messages you have.

I'm not completely sure that the number of channels/favourites etc is really needed, however the number of unread messages would be more more benefit?

It's not a complaint, but one to see what other people's views are?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Debian 9.0
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version:

**Comment by RichardFoxworthy** [comment]
agree - I find this channel count to be unnecessary and distracting. I had thought this was a new feature in 59.x but can see that it was present in earlier versions, only was much less prominent. 

I reckon it should either be removed or made optional

**Comment by Gummikavalier** [comment]
Workaround to hide the number of channels badge in `Layout -> Custom CSS`

```
h3.rooms-list__type {
	span.badge {
		display: none;
	}
}
```

**Comment by skfin** [comment]
Yes, please bring back the unread message count next the channel/DM names as well
