### ISSUE TITLE
Direct copy-paste of images not working in Firefox

### ISSUE THREAD

**Issue by Schwoebel** [RocketChat/Rocket.Chat#862]
I am using Firefox 40.0.3 on Windows10 and I am not able to directly copy and paste images from my desktop to the web-client from MS paint or photoshop. 

It does work in chrome on the same computer however.
##

**Comment by geekgonecrazy** [comment]
This might be related to an issue I see every once in a while.  If I paste an image in, i've noticed sometimes it not letting me paste text in afterwards.  Only happens sometimes.  Sounds like it could be related though.

**Comment by flarehl** [comment]
Switching issue from other feature request of images opening as download. I'll take my name off the other one in a bit.

**Comment by evant89** [comment]
Is the problem resolved?
