### ISSUE TITLE
Can't find new releases download link

### ISSUE THREAD

**Issue by Ulrar** [RocketChat/Rocket.Chat#8620]
Hi,

I can't find the new releases downloads, I used to just
```
    wget https://rocket.chat/releases/0.58.0/download
```
And proceed from there, but all of those are now 404 not found. Where can I find the newer releases ?

**Comment by jszaszvari** [comment]
This will download the latest stable: https://download.rocket.chat/stable

RC/Beta: https://download.rocket.chat/candidate

and: https://github.com/RocketChat/Rocket.Chat/releases

**Comment by Ulrar** [comment]
Is the source code link the same as the old releases ? No need to do something extra besides the usual npm install ?

Although, is it safe to skip releases these days ? Last time I tried it tried applying a newer migration without applying the previous ones to mongo and I had to restore a backup to solve it. I've been applying each update in order every since, to be safe.

**Comment by MartinSchoeler** [comment]
@Ulrar we have changed our download links, please follow the links in @jszaszvari suggestion. Thanks!

**Comment by soundstorm** [comment]
@MartinSchoeler this breaks the semi automatic update tools for our system :( So no way to get a release by the release tag anymore?
