### ISSUE TITLE
Livechat - Fails if Guest Pool Choosen

### ISSUE THREAD

**Issue by matyhaty** [RocketChat/Rocket.Chat#8623]
### Description:

If you choose 'Guest Pool' as the directing option, there is no way of accepting a user.

From a screenshot seen, there is meant to be a pop up saying do you wish to take on this user - however not getting this.

Installed on Digital Ocean - Snap - Ubuntu 16

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version: 4.8.4

### Steps to Reproduce:

1. Set Livechat on, and direction to Guest pool
2. Have app open, or via desktop
3. Start a new live chat
4. click incoming live chat
5. Goes into 'room'
6. replies not seen by user

### Expected behavior:

Probably a pop up to accept the chat
Chat functions as per normal expectations

### Actual behavior:

Nothing, and user doesnt see your messages

**Comment by MartinSchoeler** [comment]
Fixed on #8577
