### ISSUE TITLE
Livechat - No Push Notification

### ISSUE THREAD

**Issue by matyhaty** [RocketChat/Rocket.Chat#8624]
### Description:

I have push notifications working when mentioning someone, and when a chat is underway.

However there is no push when a new chat is added to pool or when one is directed to you.

Makes a very time sensitive aspect fail.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version: 4.8.4

### Steps to Reproduce:

1. Set Livechat on, and direction to Guest pool
2. Have app open, desktop closed
3. Start a new live chat
4. Not notification pushed

### Expected behavior:

A push notification

### Actual behavior:

Nothing

**Comment by coreyman** [comment]
I'm having the same issue with 'least amount'. I don't think live chat push notifications for new chats work at all. This is a major bug, and I may have a look at what I can do to help fix it later. Is this feature planned yet?

**Comment by puetzstef** [comment]
Hi there,

this behavior is really a problem when using the live chat. Without the push notifications, important messages will eventually not be answered in an acceptable amount of time. Is there a fix planned for this?

Greetings
Stefan

**Comment by Dos4gwexe** [comment]
same here. Server 0.60.4. No new chat notification. A must have option.

**Comment by michaelkrog** [comment]
The same in 0.62.0

**Comment by sampaiodiego** [comment]
we have different problems to consider on this issue..

the most important one I think is, why do you want to receive a push notification if to be able to receive a livechat you need to be online? what's the purpose on receiving a push notification when you are online?

**Comment by jaspertouchet** [comment]
I use it on the app as a backup to my team in the office. Unless I'm constantly checking the app, there is no way for me to know that there is a live chat incoming. It's the first live chat that I have ever experienced without push on incoming.

**Comment by Avalarion** [comment]
We have RocketChat online in Background all the day, but if a potential customer writes us we should be able to react instant.

**Comment by sampaiodiego** [comment]
by definition rocket.chat only sends push notifications if you're completely offline (not connect to the server by any means).

I can see the importance of sending push notifications for incoming livechats, but it might be hard to define when a push notification should be sent or not. sending to everyone, including those who are actively using the interface might be frustrating.

**Comment by jaspertouchet** [comment]
Really? I get push notifications even when changing screens on my iPhone in the middle of an active conversation. I stay online and active all day. Without push notifications, I wouldn't know that a message came through. Push works as it should on everything except live chat notifications.

**Comment by Avalarion** [comment]
I am talking about Firefox / Chrome Pushes, don't know if this makes a difference for you. But having some kind of alerting would be really nice, just to get informed that someone you can't call back, because you don't know him, is trying to reach you or your team.

**Comment by sampaiodiego** [comment]
that makes a huge difference @Avalarion =)

push notifications are notifications sent to mobile phones.

the ones showed by web browsers are called desktop notifications 😉

**Comment by michaelkrog** [comment]
If I log out of everything and start a live chat I don’t get any push notifications. I have to open the app to check.

**Comment by coreyman** [comment]
@sampaiodiego I don't know why it would be hard to define if a push notification should be sent or not. Push notifications should always be sent when you are away or offline for mentions in any channel that is not being viewed on desktop, this includes new private messages to you(live chat).

There could also be a drop down setting for "Trigger push notifications when." where users can configure when they want to receive push notifications.

**Comment by sampaiodiego** [comment]
> @sampaiodiego I don't know why it would be hard to define if a push notification should be sent or not. Push notifications should always be sent when you are away or offline for mentions in any channel that is not being viewed on desktop, this includes new private messages to you(live chat).

@coreyman this is exactly what happens _right now_ . but the whole point of the issue is the step 3 on "how to reproduce", currently rocket.chat does not send a push notification for **new livechats** .. and this happens exactly because if you are _offline_ you will **not** receive a _new livechat_.. 

> There could also be a drop down setting for "Trigger push notifications when." where users can configure when they want to receive push notifications.

we also have this already. which for livechats are automatically set for "every message". but again, this is for existing livechats, the ones you received because you were online the moment they were created.

**Comment by coreyman** [comment]
> @coreyman this is exactly what happens right now . but the whole point of the issue is the step 3 on "how to reproduce", currently rocket.chat does not send a push notification for new livechats .. and this happens exactly because if you are offline you will not receive a new livechat..

Yea it's been a bit since I had the issue (Dec 2017) so I couldn't remember but I thought that was the case. That clears it up a bit and makes the issue sound like it is easily resolvable. Just give us a dropdown that allows new livechats when agents are offline.

**Comment by Avalarion** [comment]
Just to know if I should leave this ticket. We don't need Push Notifications but Browser Notifications which are not working for us aswell. Should this be handled here aswell or do you know a better place?

**Comment by shionphan** [comment]
Has the problem been solved? The same issue.

**Comment by sampaiodiego** [comment]
it was not yet.. but #10221 should fix it.

**Comment by shionphan** [comment]
@sampaiodiego Mobile phone can not receive message from live chat (guest message)

**Comment by shionphan** [comment]
@rodrigok  Good news, I will hava a test.
