### ISSUE TITLE
API: channels.list returns only joined channels

### ISSUE THREAD

**Issue by himpich** [RocketChat/Rocket.Chat#8625]
### Description:
Trying to retrieve a full list of all channels (channels.list) lists only the channels the user (admin role) has joined (like channels.list.joined)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 14.04
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 4
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4

### Steps to Reproduce:
```bash
# Logging in
loginResult=$(curl -s $server/api/v1/login -d "username=$user&password=$pass")
authToken=$(echo $loginResult | sed 's/.*authToken\":\ \"//' | sed 's/\".*//')
userId=$(echo $loginResult | sed 's/.*userId\":\ \"//' | sed 's/\".*//')

curl -s -H "X-Auth-Token: $authToken" -H "X-User-Id: $userId" $server/api/v1/channels.list
```

### Expected behavior:
To get a list of all public and private channels

### Actual behavior:
I only get a list of channels the user $user has joined. The $user has the admin role.

### Relevant logs:
no logfiles

**Comment by Fab1en** [comment]
I can see the same behaviour on Rocket Chat v0.59.2

**Comment by Fab1en** [comment]
Is this related to #8729 ?

**Comment by jgtoriginal** [comment]
@himpich according to the [docs](https://rocket.chat/docs/developer-guides/rest-api/#rocket-chat-rest-api) 

`api/v1/channels.list` Retrives all of the channels from the server.
`/api/v1/channels.list.joined`  Gets only the channels the calling user has joined.

So I'd assume that @Fab1en is right, this might be related to  #8729

**Comment by himpich** [comment]
The User I am using has (only) the admin role. The admin role has all rights checked. I removed all checks and re-added them (according to #8729) - this did not change anything. The curl command still only returns the two joined channels and nothing else.

Can anyone confirm that he can get a _full_ channel list via /api/v1/channels.list ?
(in order to check if it's something with my installation or a generic problem)

**Comment by Fab1en** [comment]
@himpich I confirm that I the bug disappears when *view-joined-room* permission is **unchecked**. That helps a lot, thanks !

Now, that bug should be solved...

**Comment by MarcosSpessatto** [comment]
@himpich and @Fab1en, I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/10009) solve the problem.

**Comment by MarcosSpessatto** [comment]
@himpich, @Fab1en, I'm closing this issue, because I believe this problem is solved. Please, if you can test with the newer version of rocket.chat. And if the problem persists, feel free to open new issue.
