### ISSUE TITLE
Ability to create a word's Blacklist

### ISSUE THREAD

**Issue by AdrianoCahete** [RocketChat/Rocket.Chat#863]
Sometimes we need to ban certains words (something like [Chrome's 3030 bug](https://code.google.com/p/chromium/issues/detail?id=533361) )

**Comment by klatys** [comment]
@AdrianoCahete This should already be fixed - see administration > message > `Allow Message bad words filtering` + `Add bad words to the blacklist`

**Comment by Sing-Li** [comment]
Thanks @klatys

**Comment by alvarow** [comment]
is there a white list ?

If I enable that, then I can't say "talk to Dick, he'll explain you the reasons"

**Comment by pusadev** [comment]
Where is the blacklist??

when active bad words to the blacklist, in the blacklist have other words, how remove or where is the file blacklist
