### ISSUE TITLE
Installation on Ubuntu 16 using 'snap' not functional

### ISSUE THREAD

**Issue by typoworx-de** [RocketChat/Rocket.Chat#8631]
I've tried installing rocket-chat using 'snap' on Ubuntu 16.04 LTS.
https://docs.rocket.chat/installation/manual-installation/ubuntu/snaps/

After the silent installation (no reported issues) the service is not running yet?
Trying to start does not work:

sudo systemctl status snap.rocketchat-server.rocketchat-server.service
> ● snap.rocketchat-server.rocketchat-server.service - Service for snap application rocketchat-server.rocketchat-server
>    Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service; enabled; vendor preset: enabled)
>    Active: inactive (dead) (Result: exit-code) since Di 2017-10-24 19:19:13 CEST; 16s ago
>   Process: 26254 ExecStart=/usr/bin/snap run rocketchat-server (code=exited, status=1/FAILURE)
>  Main PID: 26254 (code=exited, status=1/FAILURE)

> systemd[1]: snap.rocketchat-server.rocketchat-server.service: Unit entered failed state.
> systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
> systemd[1]: snap.rocketchat-server.rocketchat-server.service: Service hold-off time over, scheduling 
> systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-server.
> systemd[1]: snap.rocketchat-server.rocketchat-server.service: Start request repeated too quickly.
> systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-server.

Trying to start manually (using ExecStart command from above) results in:
> /usr/bin/snap run rocketchat-server
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks

Removal and Re-Installing does not resolve the problem for me. It's not really clear which permissions are wrong or how to fix this.

**Comment by marceloschmidt** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by marceloschmidt** [comment]
The contributors most likely able to help are:

@unixfox

Possible duplicate or related issues are:

- #4752: Updating snap not possible if rocket.chat was stopped and restarted

**Comment by unixfox** [comment]
I'm still a beginner of snap but I found on [askubuntu](https://askubuntu.com/questions/888497/snap-confine-refuses-to-launch-application-to-avoid-permission-attack) a tip to maybe resolve the issue:
```
sudo apt purge snapd snap-confine && sudo apt install -y snapd
```

Your issue @typoworx-de is related to the fact that snap-confine is running without confinement.

If the command above doesn't work I would suggest you a reinstall of the system or a kernel upgrade (https://unix.stackexchange.com/questions/379421/cant-run-any-snap-using-linux-4-12-snap-confine-has-elevated-permissions-and).

**Comment by geekgonecrazy** [comment]
👍  exactly what I would recommend.  over all make sure you have your system updated.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
