### ISSUE TITLE
UI/UX: Lack of "More channels..." button

### ISSUE THREAD

**Issue by volas** [RocketChat/Rocket.Chat#8633]
After the redesign in 0.59, we can only see all channels in the search for "#", but this it is not very obvious.

**Comment by MartinSchoeler** [comment]
Please see #8571

**Comment by waveyuk** [comment]
Very disappointing that the "More Channels" option has been removed before a replacement (all be it a better way) has been implemented. On my system there are in excess of 30 channels and now my users have no way of knowing what channels are available to join.
