### ISSUE TITLE
Username at top of sidebar should follow "Use Real Name" setting

### ISSUE THREAD

**Issue by skfin** [RocketChat/Rocket.Chat#8638]
Hi, just a small request that the name of the logged-in user, shown at the top of the left sidebar, be displayed as the user's real name instead of "@username" when the real-name setting is true.

We use RC in a professional environment and I think it would look a bit cleaner without the "@username"

**Comment by edubrites** [comment]
I'm with the same problem...

**Comment by janrudolph** [comment]
Found the same and closed my issue.

**Comment by geekgonecrazy** [comment]
With the new redesign that has actually been changed up.  So this should not longer be an issue.  Please let me know if it still is
