### ISSUE TITLE
LDAP sync breaks non ASCII UTF-8 characters in user names after authentication [0.59.2]

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#8649]
### Description:

LDAP sync breaks Nordic characters in user's full name after authentication in 0.59.2.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 5
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4

### Steps to Reproduce:

1. In admin console Enable Layout -> User Interface -> Use Real Name
2. Upgrade from RC 0.59.1 to 0.59.2
3. Log out existing session with a user whose name has non ASCII UTF-8 character.
4. Log back in and observe user name list in admin console. Also type a message as the user.

### Expected behavior:

User's name should be ok and contain UTF-8 characters such as ä.

### Actual behavior:

User's name has changed both in Admin user list and any new messages to contain wrongly decoded characters such Ã¤ (which should be ä).

The issue did not exist in 0.59.1 or earlier.

**Comment by efih** [comment]
have same issue , version 0.59.2

**Comment by Gummikavalier** [comment]
I'll also add that since fullname is used in direct room topic bar (if you have Use Real Name option enabled), ASCII formed full names "leak" from there to the channel list. This happens even if one downgrades back to 0.59.1 and updates users via LDAP, then logs back in, or manually fixes the name in the user list.

I could not find malformed names in the database (didn't know where to look originally), so I had to delete all direct rooms using GUI. (After I had found delete button workaround in #8658 comments.)

**Comment by ArchimedesFM** [comment]
We have the same issue with newly imported users username und name - Version 0.59.2
I can edit them manually and they dont break again after LDAP-Sync, but maybe after login but i can't test this.

**Comment by Gummikavalier** [comment]
@ArchimedesFM For us it happened only after doing actual login. Running LDAP sync from the setting didn't trigger it, nor did it fix it afterwards.

**Comment by efih** [comment]
i fix manually also, but after logout&login its happened again

**Comment by hartois** [comment]
Also confirmed on 0.59.2

**Comment by zahaim** [comment]
same for Polish characters in 0.59.2

**Comment by traxanos** [comment]
The LDAP Plugin totally broken.

- During the sync LDAP fields escape chars wrong.
- The manual sync doesn't work correctly - it will only sync new user because the function importNewUsers will call.
- The automatic sync will not work, too. It doesn't start the cron like the description.

Only the sync during the login by user will wort, but with broken escaping.

**Comment by traxanos** [comment]
So the first patch ist for fixing manual sync:
https://gist.github.com/traxanos/ed7a0ce104fd0afa170f20d509d4d459

**Comment by traxanos** [comment]
The other problem why special chars are broken is the handling with ldap fields as BINARY!!!
What the hell why the use the field as binary!

https://github.com/RocketChat/Rocket.Chat/commit/e2b0379dc967f59148c8e4b8aeaf4b9a0f914e80

When you revert this the encoding is working again.

**Comment by rodrigok** [comment]
Thanks guys, I'll take a look ASAP

**Comment by rodrigok** [comment]
Guys, version [0.59.3](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.59.3) is building and will be available soon with this fix.

**Comment by rodrigok** [comment]
Please let me know if there are more issues related to LDAP

**Comment by Gummikavalier** [comment]
Seems to work ok for us with 0.59.3. Thanks! :)

**Comment by deogracia** [comment]
with 0.59.3, works for me now. thanks!
