### ISSUE TITLE
Spotify Integration

### ISSUE THREAD

**Issue by herau** [RocketChat/Rocket.Chat#865]
Be able to launch the spotify app through a link in RocketChat like 
![screen shot 2015-09-23 at 5 49 48 pm](https://cloud.githubusercontent.com/assets/2950666/10050235/a63e02f0-621b-11e5-81e2-59c7a0fbdce7.png)

instead of currently

![screen shot 2015-09-23 at 5 51 12 pm](https://cloud.githubusercontent.com/assets/2950666/10050263/d38a6f32-621b-11e5-83e1-61e6ffce55c6.png)

**Comment by kakawait** [comment]
can be closed? see #904 merged

**Comment by herau** [comment]
Yes of course ! Thanks @kakawait

**Comment by jaschadub** [comment]
In 0.46.0 release this functionality seems to not be working.

**Comment by drasbeck** [comment]
0.56.0 this is what I get from pasting Spotify links:

<img width="460" alt="screen shot 2017-06-18 at 22 18 17" src="https://user-images.githubusercontent.com/8578706/27263906-2e580ef0-5474-11e7-8ee6-463b0bb9d53b.png">
