### ISSUE TITLE
Password reset does not work for plaintext emails

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8650]
### Description:
This is an example of an email payload:

> ----_NmP-8e44dd23afefc409-Part_1
> Content-Type: text/plain
> Content-Transfer-Encoding: quoted-printable
> 
> Hello,
> 
> To reset your password, simply click the link below.
> 
> https://open.rocket.chat/#/reset-password/${removed}
> 
> Thanks.
> 
> ----_NmP-8e44dd23afefc409-Part_1
> Content-Type: text/html
> Content-Transfer-Encoding: quoted-printable
> 
> Hello,
> 
> To reset your password, simply click the link below.
> 
> https://open.rocket.chat/reset-password/${removed}
> 
> Thanks.
> 
> ----_NmP-8e44dd23afefc409-Part_1--

You'll notice that the html version has `/reset-password` where as the plain text version has `/#/reset-password`

`/#/reset-password` is redirected to the home page, where as `/reset-password` shows the page desired.

Here is where the email is constructed it looks like: https://github.com/meteor/meteor/blob/devel/packages/accounts-password/email_templates.js#L7

Here is where the url is built: https://github.com/meteor/meteor/blob/devel/packages/accounts-base/url_server.js#L7

Not sure why the html and the plain text version differ.  Also not sure why this used to work and now does.

I can only assume this happens with all other emails sent by the accounts package.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2

### Steps to Reproduce:

1. have password reset
2. open email in plain text email client
3. click the link

Alternatively in gmail or other inspect the original email and see output like mine above.

### Expected behavior:

Either redirect... or send the correct url

### Actual behavior:

See above

### Relevant logs:
None.

**Comment by geekgonecrazy** [comment]
@ggazzo @karlprieb feel free to re-assign.  Not sure where this should go.  But seems in meteor account package.   :)

**Comment by xenithorb** [comment]
I'd also like to point out that the HTML embedded message does NOT put an `<a href=>` around the URL, which it probably should because it won't render a link in a lot of email clients without it.

**Comment by geekgonecrazy** [comment]
Looks like also not necessarily translated, so might be beneficial to take over sending of the emails from the accounts package if we can?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @geekgonecrazy 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #3883 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate
