### ISSUE TITLE
Mongo process at 100 percent causing delay in sending messages and logging on

### ISSUE THREAD

**Issue by stalley** [RocketChat/Rocket.Chat#8651]
### Description:
Experiencing heavy lag that appears to be database related from the logs. OS load is ok but mongo process is at 100 percent more often than not and monogtop reports significant delay on the rocketchat.usersSessions collection.

Logging on has a significant delay, and typing messages can be anywhere between 5 - 10 seconds before fully sending.

### Server Setup Information:
Version	0.58.0-rc.1
Database Migration	99
Database Migration Date	Tue Oct 24 2017 22:52:21 GMT-0400 (Eastern Daylight Time)
Installed at	Tue Oct 03 2017 16:53:38 GMT-0400 (Eastern Daylight Time)
Uptime	15 hours, 59 minutes, 55 seconds
Running Instances	3
OpLog	Enabled

Commit
Hash	16926f838695bdd297e581239820dff60eed4f70
Date	Tue Aug 8 15:18:24 2017 -0300
Branch	HEAD
Tag	0.58.0-rc.1
Author	Rodrigo Nascimento
Subject	Bump version to 0.58.0-rc.1
Runtime_Environment
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	3.10.0-514.el7.x86_64
Node version	v4.5.0
OS Uptime	1 days, 4 hours, 22 minutes, 3 seconds
OS Load Average	0.93, 0.99, 1.01
OS Total Memory	7.64 GB
OS Free Memory	2.53 GB
OS CPU Count	4

Build_Environment
OS Platform	linux
OS Arch	x64
OS Release	4.4.0-83-generic
Node version	v4.8.4
Date	August 8, 2017 2:27 PM
Usage
Total Users	134
Active Users	134
Inactive Users	0
Online Users	77
Away Users	12
Offline Users	45
Total Rooms	206
Total Channels	5
Total Private Groups	47
Total Direct Message Rooms	154
Total Livechat Rooms	154
Total Messages	4024
Total Messages in Channels	102
Total Messages in Private Groups	1254
Total Messages in Direct Messages	2677
Total Messages in Livechats	0

Broadcast Connected Instances
Address	localhost:3001
Auth	true
Current Status > Connected	true
Current Status > Retry Count	0
Current Status > Status	connected
Instance Record > ID	TNnHXuSjYY24YyWHs
Instance Record > PID	22259
Instance Record > Created at	October 24, 2017 10:51 PM
Instance Record > Updated at	October 24, 2017 10:52 PM

Address	localhost:3002
Auth	true
Current Status > Connected	true
Current Status > Retry Count	0
Current Status > Status	connected
Instance Record > ID	gNN6f3PGijq7krMyK
Instance Record > PID	22285
Instance Record > Created at	October 24, 2017 10:52 PM
Instance Record > Updated at	October 24, 2017 10:52 PM

### Relevant logs:
From top command:

top - 15:07:34 up 1 day,  4:37,  1 user,  load average: 1.12, 1.05, 1.03
Tasks: 189 total,   2 running, 187 sleeping,   0 stopped,   0 zombie
%Cpu0  : 32.6 us,  1.0 sy,  0.0 ni, 66.1 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu1  :  3.3 us,  0.7 sy,  0.0 ni, 95.7 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu2  : 17.7 us,  0.0 sy,  0.0 ni, 82.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 98.7 us,  0.7 sy,  0.0 ni,  0.3 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  8010808 total,  2925940 free,  1928172 used,  3156696 buff/cache
KiB Swap:  8257532 total,  8257532 free,        0 used.  5681152 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S P  %CPU %MEM     TIME+ COMMAND                                                                                                                                                             
21816 mongod    20   0 5439688 158164  97204 S 1  55.7  2.0 808:02.15 mongod                                                                                                                                                              
22233 root      20   0 1933620 621464  12600 R 3  50.7  7.8 175:41.51 node                                                                                                                                                                
22285 root      20   0 1700072 536424  12468 S 0  35.0  6.7  93:53.36 node                                                                                                                                                                
22259 root      20   0 1675328 514704  12480 S 2  14.7  6.4  90:56.36 node                                                                                                                      
22323 nginx     20   0  126884   8568   2400 S 1   0.3  0.1   1:28.68 nginx     

From mongotop:

2017-10-25T19:09:32                                                ns       total        read       write 
                                               rocketchat.usersSessions      5818ms         5ms      5813ms
                                                           rocketchat.users        39ms        29ms        10ms
                                                                local.oplog.rs         4ms         4ms         0ms
                                                     rocketchat.instances         2ms         1ms         1ms
                                         rocketchat.rocketchat__trash         0ms         0ms         0ms
                                                    rocketchat.migrations         0ms         0ms         0ms
        rocketchat.meteor_oauth_pendingRequestTokens         0ms         0ms         0ms
               rocketchat.meteor_oauth_pendingCredentials        0ms         0ms         0ms
rocketchat.meteor_accounts_loginServiceConfiguration         0ms         0ms         0ms`

**Comment by geekgonecrazy** [comment]
A couple of things to consider:
1. Hop on up to a stable release :)  0.59.2 was just released.
2. Look at moving mongo off the same box as Rocket.Chat.
3. While moving take a look at swapping the mongo engine to mmapv1 instead of wiredtiger.

**Comment by stalley** [comment]
@geekgonecrazy I saw the same issues with 58.3, trying to wait to move to 59.x till all the UI overhaul bugs are worked out. I would imagine numbers 2 and 3 will prove the most beneficial. I will try those.

**Comment by geekgonecrazy** [comment]
Yeah i'd at least goto 58.4 that way you are on a stable release.  :) 

Please let me know how it goes.  👍

**Comment by stalley** [comment]
@geekgonecrazy So after following your suggestions everything is much more responsive. I would imagine the biggest help was moving mongo to its own server. It does still look like the userSessions collection is the biggest drain though, which does cause the occasional slow down, but nothing like it was.

  PID        USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                             
 9169 mongod    20   0 1222148 419312   8588 S  15.9 10.8 100:40.04 mongod      

    ns    total    read    write    2017-10-27T13:43:54-04:00
rocketchat.usersSessions    159ms     1ms    157ms

**Comment by geekgonecrazy** [comment]
@stalley great!  Out of curiousity did you change to mmapv1 in the process?

**Comment by stalley** [comment]
@geekgonecrazy I did yes. Stability has been great since those changes. I'll close this out. Thank you for all the help.

**Comment by geekgonecrazy** [comment]
Perfect thanks for reporting back
