### ISSUE TITLE
Missing delete button in Direct Message / Channel

### ISSUE THREAD

**Issue by ledainam** [RocketChat/Rocket.Chat#8658]
### Description:
My instance updated to 0.59.1. Since then i didn't see delete button in Direct Message and Channel(Both public and private). I have admin role also.

### Server Setup Information:

Version of Rocket.Chat Server: 0.59.1
Operating System: Centos 7
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 2
DB Replicaset Oplog: Enabled
Node Version: v4.4.8

### Steps to Reproduce:

Upgrade to 0.59.1
Delete Direct message room / channel

### Expected behavior:

Get a delete button to delete direct message room / channel

-->

**Comment by corecache** [comment]
This is a duplicate of #8562 - check the original report, there is a quickfox for Layout -> custom css

**Comment by ledainam** [comment]
@corecache : Thanks you :)
