### ISSUE TITLE
Push notifications don't work in Chrome, FF in Windows 7 when call @ or direct message

### ISSUE THREAD

**Issue by patsevanton** [RocketChat/Rocket.Chat#8659]
Push notifications don't work in Chrome, FF in Windows 7 when call @ or direct message

Rocket.Chat
Version 0.59.1

Runtime_Environment
OS Type Linux
OS Platform linux
OS Arch x64

OS Release  4.4.0-93-generic
Node version    v4.8.4

Chrome  61.0.3163.100

Also: Groups have many unreadable notifications

If press to "test Desktop Notification", then we will see Push notifications

Push notifications work in Chrome in Ubuntu 16.04 when call @ or direct message

**Comment by sampaiodiego** [comment]
we have made many changes on push notifications logic, this should be fixed by now.

please let me know if it is still an issue.
