### ISSUE TITLE
Per-channel verbose notifications

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/Rocket.Chat#866]
The ability to specify on a per-channel basis to be notified every time a new message is posted to a channel instead of *only* when @mentioned.

**Comment by bnikolaus** [comment]
+1

**Comment by mhkeller** [comment]
+1 I just got this request from people using our instance

**Comment by geekgonecrazy** [comment]
@mhkeller @bnikolaus please refer to #1068
