### ISSUE TITLE
Update to 0.59.2 from 0.59.1

### ISSUE THREAD

**Issue by exagon** [RocketChat/Rocket.Chat#8660]
Hi at all and sorry for the stupid questions, but how can upgrade to the latest release 0.59.2  ?

When I download the stable version on https://download.rocket.chat/stable I download the 0.59.1, so where I find the 0.59.2 ?

Thanks a lot
EXA

**Comment by magicbelette** [comment]
Hi,

It seems that it's just been updated.
https://download.rocket.chat/build/rocket.chat-0.59.2.tgz

**Comment by MartinSchoeler** [comment]
Please use the link provided by @magicbelette

**Comment by exagon** [comment]
thanks a lot
