### ISSUE TITLE
nodejs update from 4.8.4 to 4.8.5

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#8661]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): bundle self build
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 4.8.4

see: https://nodejs.org/en/blog/vulnerability/oct-2017-dos

If updating nodejs from 4.8.4 to 4.8.5 do I have to rebuild my bundle on 4.8.5 too or is to sufficient using 4.8.5 as executing nodejs version?

Ciao
Marcus

**Comment by Lemmmy** [comment]
Did you even try it? You don't have to rebuild the bundle, it will work fine.

**Comment by rodrigok** [comment]
@localguru The important version is the version you use to run the application, if everything works fine you are good. Usually the bundle built with a major nodejs version will be compatible with all minors.

**Comment by localguru** [comment]
@Lemmmy Upgraded via nvm without rebuilding the bundle today, seems to work fine.

@rodrigok Obrigado!
