### ISSUE TITLE
Emoji not visible / different colors in Chrome 

### ISSUE THREAD

**Issue by exagon** [RocketChat/Rocket.Chat#8663]
With : 
Rocket Chat 0.59.2
Google Chrome | 61.0.3163.100 (Build ufficiale) (a 64 bit) (cohort: Stable)

i can't see emoji and colors of avatar is always the same ( blue ), but with desktop application I can see emoji and different colors for avatars.
![emoji](https://user-images.githubusercontent.com/2110701/32058066-551c4b9a-ba69-11e7-9486-5340316e0e08.jpg)

**Comment by karlprieb** [comment]
Fixed here #8822
