### ISSUE TITLE
Empty Room for Subscription

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#8664]
### Log ###
```
rocket                |   Empty Room for Subscription { _id: 'aCirYGRAFfcbdBysF',
rocket                |   rid: 'QEPfxDJn5TJoq8XxCZJxmKhwEhLj4jhuBX',
rocket                |   ts: Tue Oct 04 2016 13:38:03 GMT+0000 (UTC),
rocket                |   ls: Tue Mar 28 2017 08:15:01 GMT+0000 (UTC),
rocket                |   open: false,
rocket                |   _updatedAt: Tue Aug 01 2017 14:03:02 GMT+0000 (UTC),
rocket                |   name: 'Alice',
rocket                |   t: 'd',
rocket                |   alert: false,
rocket                |   unread: 0,
rocket                |   u: { _id: 'ZJxmKhwEhLj4jhuBX', username: 'Bob' },
rocket                |   meta: { revision: 0, created: 1509034722678, version: 0 },
rocket                |   '$loki': 185,
rocket                |   _room: undefined,
rocket                |   _user:
rocket                |    { _id: 'ZJxmKhwEhLj4jhuBX',
rocket                |      createdAt: Sun Jan 31 2016 22:27:59 GMT+0000 (UTC),
rocket                |      services:
rocket                |       { password: [Object],
rocket                |         email: [Object],
rocket                |         resume: [Object],
rocket                |         totp: [Object] },
rocket                |      emails: [ [Object] ],
rocket                |      status: 'online',
rocket                |      active: true,
rocket                |      roles: [ 'admin' ],
rocket                |      name: 'Bob',
rocket                |      lastLogin: Thu Oct 26 2017 16:19:16 GMT+0000 (UTC),
rocket                |      statusConnection: 'online',
rocket                |      utcOffset: 2,
rocket                |      username: 'Bob',
rocket                |      avatarOrigin: 'upload',
rocket                |      settings: { profile: {}, preferences: [Object] },
rocket                |      language: 'fr',
rocket                |      statusDefault: 'online',
rocket                |      requirePasswordChange: false,
rocket                |      type: 'user',
rocket                |      _updatedAt: Thu Oct 26 2017 16:19:16 GMT+0000 (UTC),
rocket                |      meta:
rocket                |       { revision: 4,
rocket                |         created: 1509034722542,
rocket                |         version: 0,
rocket                |         updated: 1509034756984 },
rocket                |      '$loki': 2 },
rocket                |   fname: undefined }
```

### Server Setup Information:

* Version of Rocket.Chat Server: rocketchat/rocket.chat:0.59.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances:  1
* DB Replicaset Oplog: Enabled
* Node Version: Node version in rocketchat/rocket.chat:0.59.2

**Comment by MartinSchoeler** [comment]
Could you give us more info? Like when this log is happening? Thanks!

**Comment by avignat** [comment]
It happens each time I logged in. This room was deleted a long time ago (~August) while I was using 0.58.X I think.

**Comment by simopaasisalo** [comment]
I see the same kind of errors relating to private conversations to users that have been deleted. These conversations are not visible in Administration/Rooms.

**Comment by lhaig** [comment]
I see the same error for an old user that was deleted. 

Version	0.57.1
Database Migration	99

Docker container

**Comment by avignat** [comment]
Still present in 0.61.0

**Comment by CoMPaTech** [comment]
Having this for a while too with one of our users who (back then) was created wrongly in LDAP, but deleting her account didn't do much good - after logging on again this persisted. Unfortunately she's not part of our chat group anymore, though the error still exists when I log in.

**Comment by Gandalf-the-Grey** [comment]
Maybe it would be a good idea if such issues could be fixed during database upgrade/migration step (consistency/sanitization) while deploying new version (or explicitly while running with `--sanitize` or something similar)

**Comment by DiJu519** [comment]
I'm hitting this issue because i was once debugging a different issue and deleted an ldap based user.

When that user rejoined, i lost the ability to direct msg them. Now i see logs similar to OP's.

Is it considered safe to manually remove these from the MongoDB?

**Comment by avignat** [comment]
Still here 0.62.0

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #6535.

Cheers
Thomas
