### ISSUE TITLE
[FIX] Missing the room name in the /api/v1/im.list REST API result.

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat#8665]
### Description:

There is not the room name key in the [/api/v1/im.list](https://docs.rocket.chat/developer-guides/rest-api/im/list) REST API result.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2 (`open.rocket.chat`)

### Steps to Reproduce:

1. Simply call the /api/v1/im.list REST API.
2. See the JSON result.

### Expected behavior:

The JSON result should be with the room name, like:
```
{
   "total":1,
   "offset":0,
   "success":true,
   "count":1,
   "ims":[
      {
         "msgs":90,
         "lm":"2017-09-29T14:43:54.207Z",
         "t":"d",
         "usernames":[
            "you.username",
            "username.of.the.other.user"
         ],
         "_id":"8WCaFa2Jve4FNjMYacBD6dHc7oBvGjkruM",
         "name":"username.of.the.other.user",
         "_updatedAt":"2017-09-29T14:43:54.286Z",
         "ts":"2017-08-15T17:56:09.013Z"
      }
   ]
}
```

### Actual behavior:

```
{
   "total":1,
   "offset":0,
   "success":true,
   "count":1,
   "ims":[
      {
         "msgs":90,
         "lm":"2017-09-29T14:43:54.207Z",
         "t":"d",
         "usernames":[
            "you.username",
            "username.of.the.other.user"
         ],
         "_id":"8WCaFa2Jve4FNjMYacBD6dHc7oBvGjkruM",
         "_updatedAt":"2017-09-29T14:43:54.286Z",
         "ts":"2017-08-15T17:56:09.013Z"
      }
   ]
}
```

### Note:

If we are using "Real names" enabled, we won't have the user's real name just by getting this API. I think that the API should, at least, return all the values that we need in order to use it. I also think that the logic *should* be handled by the API related to what value should I display or not.

```
{
    "lm":"2017-08-18T18:01:33.580Z",
    "t":"d",
    "title": "The title",
    "otherUser": { ${userObject} },
    "lastMessage": "Foobar...",
    "_id":"8WCaFa2Jve4FNjMYaEBxBoWMx8GfzNndNT",
    "unread": 15,
    "alert": 2
}
```

**Comment by paulovitin** [comment]
I took a look in method which create direct message room, and property "name" for room is not setted. I believe just to fill the property with "username.of.the.other.user" then and the return will be auto.

Thats ok folks? If ok, I can send a PR later.

The problem is legacy direct messages rooms. Any idea?

**Comment by xbolshe** [comment]
Direct Messages Room has no name as described [here](https://rocket.chat/docs/developer-guides/schema-definition/)

```Room Name (t:d -> empty)```

**Comment by c0dzilla** [comment]
Following @xbolshe 's comment, I think this can be closed now as it is expected behaviour?

**Comment by filipedelimabrito** [comment]
Closing this issue since we'll have the API v2 and there is another issues more important.
