### ISSUE TITLE
Missing filesize in mongo table if upload in ios app

### ISSUE THREAD

**Issue by tomcsi** [RocketChat/Rocket.Chat#8666]
### Description:

If I uploaded the image file from ios mobile app, then the preview image cannot downloaded, because I got this error message:

GET https://rchat.xxxxx.tls/file-upload/v75aPyzdNTiqFKfwi/VMuM8UoKqZ6SAvm9py0l.jpeg net::ERR_CONTENT_LENGTH_MISMATCH

The file record in mongo:
```
{ "_id" : "v75aPyzdNTiqFKfwi", "description" : "", "name" : "VMuM8UoKqZ6SAvm9py0l.jpeg", "size" : 426352, "store" : "FileSystem:Uploads", "type" : "image/jpeg", "rid" : "zskyjbjpMdhLASTmC", "complete" : true, "uploading" : false, "extension" : "jpeg", "progress" : 1, "userId" : "gSWEz8mYotSFkhLf6", "_updatedAt" : ISODate("2017-10-26T14:54:32.221Z"), "instanceId" : "XaY5auqibQ5TMCyui", "etag" : "j57AKnN6CBaWevc2h", "path" : "/ufs/FileSystem:Uploads/v75aPyzdNTiqFKfwi/VMuM8UoKqZ6SAvm9py0l.jpeg", "token" : "1B289af818", "uploadedAt" : ISODate("2017-10-26T14:54:33.811Z"), "url" : "/ufs/FileSystem:Uploads/v75aPyzdNTiqFKfwi/VMuM8UoKqZ6SAvm9py0l.jpeg" }
```

The size in filesystem:
```
-rwxr--r-- 1 rocketchat rocketchat  165155 Oct 26 14:54 v75aPyzdNTiqFKfwi.jpeg
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: False
* Node Version: 4.8.4

**Comment by soundstorm** [comment]
Seems to be related to https://github.com/RocketChat/Rocket.Chat.iOS/issues/1075#issuecomment-352935852
So the file size is present but not correctly calculated. Not happening on iOS Rocket.Chat Cordova App, just with Rocket.Chat+ (testing on Android currently not possible as I have no such device).

**Comment by soundstorm** [comment]
@MartinSchoeler this can be closed too :)
@rafaelks fixed this in https://github.com/RocketChat/Rocket.Chat.iOS/issues/1091
