### ISSUE TITLE
A button to directly join a channel

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#867]
I know this is more of a artsy request.  But we need a button like gitter has that would let developers include a button on their README to join directly to their channel.

**Comment by sampaiodiego** [comment]
depends on #604

**Comment by sampaiodiego** [comment]
with the addition of roles, we can now have a role "guest-user" which can only navigate into channels and read its messages

**Comment by geekgonecrazy** [comment]
ah!  Yes this is true! :+1:

**Comment by rodrigok** [comment]
@sampaiodiego @geekgonecrazy we already have this button, but user must create an account to see the button and messages. I don't know if roles are related to this issue, it's more related to be able to configure channels as public readable.

**Comment by geekgonecrazy** [comment]
@rodrigok we have a button that is stand alone?

Like: 

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/RocketChat/Rocket.Chat.iOS?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

**Comment by rodrigok** [comment]
@geekgonecrazy we can use this

![Rocket.Chat](https://img.shields.io/badge/Rocket.Chat-JOIN%20CHAT-brightgreen.svg?style=flat)

`https://img.shields.io/badge/Rocket.Chat-JOIN%20CHAT-brightgreen.svg?style=flat`

**Comment by geekgonecrazy** [comment]
@rodrigok that works!  :+1:

**Comment by engelgabriel** [comment]
Added to https://demo.rocket.chat/images/join-chat.svg
