### ISSUE TITLE
Two or more users can't stay logged in simultaneously using ddp-login module.

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#8670]
### Description:
The problem being once after logging in with a ddp client, messages are subscribed smoothly and are received and sent smoothly but as soon as a second user logs in using the same ddp-login module, the socket displays a response message as follows:
{"msg":"result","id":"7","result":false}

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: true
* Node Version: 4.8.4

### Steps to Reproduce:

1. Using Rocketchat's realtime API, login to rocketchat with the help of ddp-login node module
2. Exchange some messages, these messages are sent.
3. Now login a different user
4. This user can send and receive messages.
5 Now try to send messages through the first logged in user, the user cannot send messages and in the subscribed method, result is received as **{"msg":"result","id":"7","result":false}**

### Expected behavior:

Concurrent users cannot simultaneously send and receive messages using websockets

### Actual behavior:

Concurrency gives problems

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
