### ISSUE TITLE
In which file Rocket.Chat (Version: 0.57.0-develop) have database connection ?

### ISSUE THREAD

**Issue by mborhade** [RocketChat/Rocket.Chat#8678]
I want to know the database connection of Rocket.Chat , need to access single instance on multiple databases (multi-tenant setup) .

Thanks,
Mangesh

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
