### ISSUE TITLE
Missing sidebar icon and emoji icon

### ISSUE THREAD

**Issue by exagon** [RocketChat/Rocket.Chat#8683]
RC : 0.59.2
Google Chrome : 49.0.2623.112 (Build ufficiale) m (a 32 bit)

Missing some icons :

![clipboard - 27 ottobre 2017 14-42](https://user-images.githubusercontent.com/2110701/32107909-4d0a836e-bb30-11e7-9f96-56c6dc93d698.png)

**Comment by MartinSchoeler** [comment]
Duplicate of #7980

**Comment by exagon** [comment]
the bug is not fixed on Google Chrome : 49.0.2623.112 (32bit )
