### ISSUE TITLE
User unable to open Direct Message room

### ISSUE THREAD

**Issue by xWyatt** [RocketChat/Rocket.Chat#8684]
### Description:

When trying to DM one other specific user, the user is unable to load the room. There are no errors reported in the log. 
It only occurs with one specific user trying to DM one other specific user, they are able to open all other DM rooms, Private Rooms, and Channels.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): Manual install
* Number of Running Instances:  2
* DB Replicaset Oplog: Enabled
* Node Version: 4.6.2

### Steps to Reproduce:
By clicking on the other specific username while signed in as this other user.

### Expected behavior:
User should be able to open an existing (13000+ message) direct message chat with another existing user

### Actual behavior:
The client hangs trying to open with three dots in animation (See attached photo). They are able to click out of this and go into other rooms.
<img width="950" alt="clipboard - october 27 2017 9-50 am" src="https://user-images.githubusercontent.com/3946540/32111197-6f0de360-baff-11e7-8a19-cc5a9ec9269a.png">

### Relevant logs:

There are no errors showing up in the logs

**Comment by MartinSchoeler** [comment]
@xWyatt Seems related to #8556

**Comment by xWyatt** [comment]
Can confirm this is related to that issue.

Typing \`\`\`U ...\`\`\` also crashes that Direct Message room.

Would it be conducive to leave this issue open, or close it as a duplicate of the aforementioned?

**Comment by andpiazza** [comment]
@MartinSchoeler @xWyatt this issue seems related to #9163.
Per my last comment there, this affects channel and direct messages:

This issue happens for Channels and Direct Messages (DM):
http://instance.rocket.chat/channel/channel_name
http://instance.rocket.chat/direct/username
all being directed to
https://instance.rocket.chat/channel/general

**Comment by ggazzo** [comment]
@xWyatt  is still an issue? please let me know

**Comment by xWyatt** [comment]
@ggazzo I cannot replicate the issue any longer- it is not a further issue.

Thanks!
