### ISSUE TITLE
Cannot Create LocalStore

### ISSUE THREAD

**Issue by 42robots** [RocketChat/Rocket.Chat#8686]
### Description:

When trying to setup File System Storage for File Uploads, i get an access denied error when rocket chat tries to create the corresponding folders set for the File System Path.

I am running one instance in a docker environment.

The Volumes are setup as follows:

volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
    - ./uploads:/data/uploads

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.3
* Operating System: debian81
* Deployment Method(snap/docker/tar/etc): DOCKER
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4 - x64 

### Steps to Reproduce:

1. 

Go to Administration -> File Upload

2. 

Set "System Path" to "File System" 

3. 

Set "Storage Type" to "File System" and set "System Path" to "/data/uploads" and save changes

4. 

restart rocket chat

### Expected behavior:

rocket chat should create the corresponding folders under /data/uploads

### Actual behavior:

At Start Up i get:

LocalStore: cannot create store at /data/uploads (EACCES: permission denied, mkdir '/data')

Any hint highly appreciated. This points to problems with permissions, but i can't figure out whats going wrong.

Best,
Chris

**Comment by geekgonecrazy** [comment]
the folder you are mounting can't be written to by the container.  This is usually the case if you set the folder to your home folder.
