### ISSUE TITLE
Show the TOPT code in 2FA configure page.

### ISSUE THREAD

**Issue by johnnyasantoss** [RocketChat/Rocket.Chat#8688]
### Description:

There's no easy way to get the code of the TOPT in plain text while configuring 2FA.

### Steps to Reproduce:

1. Try to configure 2FA in your browser based password manager.

### Expected behavior:

Show the code that is in the QR Code in plain text.

### Actual behavior:

There's just a QR Code.

**Comment by sampaiodiego** [comment]
not sure when this was done, but you can already get the code in plain text:

![image](https://user-images.githubusercontent.com/8591547/36268045-a3a09dfc-125c-11e8-86fa-11a93bed2e3e.png)
