### ISSUE TITLE
Missing strings to translate

### ISSUE THREAD

**Issue by Surfoo** [RocketChat/Rocket.Chat#869]
Hello,

Some keys are missing in the `i18n` directory:

- Accounts_AvatarStoreType
- Accounts_AvatarStorePath
- Accounts_AvatarResize
- Accounts_AvatarSize
- Delete_Room_Warning
- Room_has_been_deleted

**Comment by gmsecrieru** [comment]
@Surfoo could you please add them to `i18n/en.i18n.json` and any other languages you feel comfortable writing and submit a PR? 

Thanks!
