### ISSUE TITLE
Possible to make a chat-hub

### ISSUE THREAD

**Issue by phuyem** [RocketChat/Rocket.Chat#8693]
We are planning to use comet chat for 1 (or many) website(s) . Each website has around hundred of thousands to millions users. Concurrent online is about 50-500 users. Also within our website (s) , we already have friend-list things. as people usually chat only to their friends, not those millions strangers.
 
We have spent almost a week to play with the demo, source code, and MOST importantly the API. They all look very promising.  So our questions are

1.  Possible to make it a quite high chat hub. 500 concurrent users is no way a crazy number but quite high for us.
2.  What should our developer look into or start with to develop a "contact list" feature. 
3. By the way, how to start a chat windows between user A ( sender ) to user B from our website ?

**Comment by theblazehen** [comment]
@phuyem You may want to look at matrix.org with riot.im. You have really fine grained room permissions etc, very nice API and AFAIK the riot.im public server has over 10k concurrent users.

Point 3 should be pretty simple to do with matrix.org at least
