### ISSUE TITLE
Add user settings / preferences API endpoint

### ISSUE THREAD

**Issue by dennispost** [RocketChat/Rocket.Chat#8694]
**Add an user settings / preferences endpoint to api, to make it possible to change user settings via authenticated api call.**

Currently you get these settings object via socket message. But there is no way to change it via api or socket message.

```json
[...]
"settings" : {
      "preferences" : {
        "newRoomNotification" : "door",
        "useEmojis" : true,
        "hideFlexTab" : false,
        "unreadRoomsMode" : false,
        "unreadAlert" : true,
        "convertAsciiEmoji" : true,
        "collapseMediaByDefault" : false,
        "saveMobileBandwidth" : true,
        "autoImageLoad" : true,
        "hideUsernames" : false,
        "highlights" : [

        ],
        "emailNotificationMode" : "disabled",
        "desktopNotificationDuration" : 0,
        "notificationsSoundVolume" : 100,
        "newMessageNotification" : "chime",
        "hideAvatars" : false,
        "hideRoles" : false,
        "viewMode" : 0,
        "desktopNotifications" : "all",
        "sendOnEnter" : "normal",
        "mobileNotifications" : "all"
      }
}
[...]
```

**Comment by jgtoriginal** [comment]
@dennispost you got an endpoint to both get and set settings. Check the [new docs](https://rocket.chat/docs/developer-guides/rest-api/settings/)

**Comment by graywolf336** [comment]
@jgtoriginal sadly they're not user preferences, they're only the server's settings.

**Comment by jgtoriginal** [comment]
@graywolf336 nice, I happen to need some user preferences methods, which I'm about to code the next week. Will focus basically on `name`, `email`, `avatar` & `password` for now.
I usually go by the code conventions when it comes to customization, is this something that might help you guys?

**Comment by graywolf336** [comment]
@jgtoriginal Feel free to implement the user's preferences rest api and submit a pull request, we will review it and provide feedback. :+1:

**Comment by jgtoriginal** [comment]
@graywolf336 will do, thx very much!
