### ISSUE TITLE
No Customize Theme option in Admin Panel - UI bugs in 0.59.*

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8698]
### Description:

After migrating to 0.59.* I have this issue on one of my instances. Just like on the screenshot below, option "Customize Theme" isn't there in Layouts. How can I force it to install again or to display it ?

![custom](https://user-images.githubusercontent.com/3985913/32148319-7ccd61ae-bcf5-11e7-86f7-cdd06caa73fa.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.*
* Operating System: debian 9
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2 
* DB Replicaset Oplog: yes
* Node Version: 4.5.0

### Steps to Reproduce:

1. just go to Administration > Layout 

### Expected behavior:

I should have it ;)

### Actual behavior:

Customize Theme disappeared. Changing language doesn't help, also reinstalling the app version from console - no results.

### Relevant logs:
nothing

**Comment by ggazzo** [comment]
Sorry about the delay @Venomen but we don't have this feature any more, but you can use the custom css to make the same theming... btw: we are rewriting the ui and we have plans to offer a better theming experience, thanks...
