### ISSUE TITLE
Can't change room type - UI bugs in 0.59.*

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8699]
### Description:

It's **impossible** to choose room type and save it. Frame is to close and also SAVE buttons disappeared.. Reinstalling app and reseting css doesn't help. Scrolling page down and searching by "tab key" for this hidden options also no luck.

![uibugs](https://user-images.githubusercontent.com/3985913/32148431-1acd519c-bcf7-11e7-975c-5462f7f0048d.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.*
* Operating System: debian 9 
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: yes
* Node Version: 4.5.0

### Steps to Reproduce:

1. Go to Administration > Rooms > Click on some Room 
2. Try to change this room type and save it 

### Expected behavior:

I should have my buttons ;)

### Actual behavior:

Save buttons disappeared and frame is to close.

### Relevant logs:
nothing

**Comment by TwizzyDizzy** [comment]
probably related to #8546

**Comment by DRON4eg** [comment]
there was another such ticket there saw a temporary solution to this problem
Custom CSS ->
`.flex-tab .channel-settings .button {visibility: visible}`

**Comment by TheReal1604** [comment]
@DRON4eg thx for the workaround
