### ISSUE TITLE
[Bug - Livechat] Missing sidebar tab "old conversations"

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#8703]
### Description:

In previous versions, a livechat agent could easily track all conversations with a customer. A menu in the right sidebar listed all previous chats with the same customer. This is not available since 0.59. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2
* Operating System: Linux
* Node Version: v4.5.0

### Steps to Reproduce:

1. Start livechat
2. Take livechat in the backend. You will not find the list in the right sidebar.
3. Close livechat
4. Open new livechat with same customer
5. Take livechat in the backend. You will not find the list in the right sidebar.

### Expected behavior:

List of all previous livechat chats with the customer is displayed in the right sidebar.

=> Please add the list again.

**Comment by mrsimpson** [comment]
The button is there, but no icon. `icon-chat` (as used in livechat) is missing in `packages/rocketchat-ui-master/public/icons.svg`

**Comment by mrsimpson** [comment]
Still, the tab can be opened - once you know where to click
![livechat-historic](https://user-images.githubusercontent.com/17176678/32166343-d195006e-bd65-11e7-91e6-574968ec2c42.png)
