### ISSUE TITLE
LDAP cyrillic fonts

### ISSUE THREAD

**Issue by psybox56** [RocketChat/Rocket.Chat#8704]
Hello. I have a rocket.chat server 0.59.2 running on ubuntu 16.04.2 x86_64
LDAP authentication. 
Few days ago, After update, when i login into chat i see this picture.  in my profile in field "name" 
ÐÑÐ¶Ð´Ð¸Ð½ ÐÐ¸ÑÐ°Ð¸Ð» ÐÐ»ÐµÐºÑÐµÐµÐ²Ð¸Ñ
![err00](https://user-images.githubusercontent.com/33217418/32162672-9b8772e8-bd7b-11e7-99f9-595959ea7a60.jpg)
Why this happens?

**Comment by marceloschmidt** [comment]
[GitMate.io](https://gitmate.io) thinks possibly duplicate or related issues are #7714 (Oneclick deployment not working for heroku ), #8422 (Can we record screen share in Rocket chat like audio and video??), #8455 ([Feature] Integrate this slack security bot its an FREE alternative to metacert), #8121 (Username not found), and #8435 ([Bug] If import failed second import try will result in 2x the amount of import data).

**Comment by psybox56** [comment]
` [34mI20171030-14:01:39.475(5) [34mLDAP ➔ Search.debug BaseDN DC=cbu,DC=lan 
[34mI20171030-14:01:39.505(5) [34mLDAP ➔ Search.info Search result count 1 
[34mI20171030-14:01:39.507(5) [34mLDAP ➔ Auth.info Authenticating CN=Нуждин Михаил Алексеевич,OU=Пользователи,DC=cbu,DC=lan 
[34mI20171030-14:01:39.511(5) [34mLDAP ➔ Auth.info Authenticated CN=Нуждин Михаил Алексеевич,OU=Пользователи,DC=cbu,DC=lan 
[34mI20171030-14:01:39.516(5) [34mLDAPHandler ➔ info Querying user 
[34mI20171030-14:01:39.518(5) [34mLDAPHandler ➔ debug userQuery { 'services.ldap.id': '25077eda4da21e41934b12597995311d' } 
[34mI20171030-14:01:39.523(5) [34mLDAPHandler ➔ info Logging user 
[34mI20171030-14:01:39.540(5) [34mLDAPSync ➔ info Syncing user data 
[34mI20171030-14:01:39.543(5) [34mLDAPSync ➔ debug user { email: undefined, _id: 'hm9r9pzhZo8WrX5bY' } 
[34mI20171030-14:01:39.553(5) [34mLDAPSync ➔ debug ldapUser { dn: 'CN=Нуждин Михаил Алексеевич,OU=Пользователи,DC=cbu,DC=lan',   controls: [],   objectClass:     [ <Buffer 74 6f 70>,      <Buffer 70 65 72 73 6f 6e>,      <Buffer 6f 72 67 61 6e 69 7a 61 74 69 6f 6e 61 6c 50 65 72 73 6f 6e>,      <Buffer 75 73 65 72> ],   cn: 'ÐÑÐ¶Ð´Ð¸Ð½ ÐÐ¸ÑÐ°Ð¸Ð» ÐÐ»ÐµÐºÑÐµÐµÐ²Ð¸Ñ',   sn: 'ÐÑÐ¶Ð´Ð¸Ð½',   description: 'ÐÐµÐ´ÑÑÐ¸Ð¹ Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð¸ÑÑ',   givenName: 'ÐÐ¸ÑÐ°Ð¸Ð» ÐÐ»ÐµÐºÑÐµÐµÐ²Ð¸Ñ',   distinguishedName: 'CN=ÐÑÐ¶Ð´Ð¸Ð½ ÐÐ¸ÑÐ°Ð¸Ð» ÐÐ»ÐµÐºÑÐµÐµÐ²Ð¸Ñ,OU=ÐÐ¾Ð»ÑÐ·Ð¾Ð²Ð°ÑÐµÐ»Ð¸,DC=cbu,DC=lan',   instanceType: '4',   whenCreated: '20170711060737.0Z',   whenChanged: '20171030053611.0Z',   displayName: 'ÐÑÐ¶Ð´Ð¸Ð½ Ð.Ð.',   uSNCreated: '13902',   memberOf:     [ <Buffer 43 4e 3d 52 4f 43 4b 45 54 5f 43 48 41 54 2c 43 4e 3d 55 73 65 72 73 2c 44 43 3d 63 62 75 2c 44 43 3d 6c 61 6e>,      <Buffer 43 4e 3d d0 a1 d0 be d1 82 d1 80 d1 83 d0 b4 d0 bd d0 b8 d0 ba d0 b8 20 d0 a6 d0 91 d0 a3 2c 4f 55 3d d0 93 d1 80 d1 83 d0 bf d0 bf d1 8b 2c 44 43 3d ... >,      <Buffer 43 4e 3d 49 54 2c 4f 55 3d d0 93 d1 80 d1 83 d0 bf d0 bf d1 8b 2c 44 43 3d 63 62 75 2c 44 43 3d 6c 61 6e>,      <Buffer 43 4e 3d d0 90 d0 b4 d0 bc d0 b8 d0 bd d0 b8 d1 81 d1 82 d1 80 d0 b0 d1 82 d0 be d1 80 d1 8b 20 d0 b4 d0 be d0 bc d0 b5 d0 bd d0 b0 2c 43 4e 3d 55 73 ... > ],   uSNChanged: '143352',   name: 'ÐÑÐ¶Ð´Ð¸Ð½ ÐÐ¸ÑÐ°Ð¸Ð» ÐÐ»ÐµÐºÑÐµÐµÐ²Ð¸Ñ',   objectGUID: '%\u0007~ÚM¢\u001eAK\u0012Yy1\u001d',   userAccountControl: '66048',   badPwdCount: '0',   codePage: '0',   countryCode: '0',   badPasswordTime: '131538265390810010',   lastLogoff: '0',   lastLogon: '131538276592157394',   pwdLastSet: '131479342386439278',   primaryGroupID: '513',   objectSid: '\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000èô\u0015Ä¥þ%`§ßü\u0012\u0004\u0000\u0000',   adminCount: '1',   accountExpires: '9223372036854775807',   logonCount: '847',   sAMAccountName: 'NMA',   sAMAccountType: '805306368',   userPrincipalName: 'NMA@cbu.lan',   objectCategory: 'CN=Person,CN=Schema,CN=Configuration,DC=cbu,DC=lan',   dSCorePropagationData:     [ <Buffer 32 30 31 37 30 37 32 30 30 35 33 34 32 37 2e 30 5a>,      <Buffer 32 30 31 37 30 37 31 32 30 35 30 39 31 30 2e 30 5a>,      <Buffer 31 36 30 31 30 31 30 31 30 30 30 30 30 30 2e 30 5a> ],   lastLogonTimestamp: '131538153710269142',   'msDS-SupportedEncryptionTypes': '0',   mail: 'test@test.ru' }  `

**Comment by micleclickme** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/8691

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
