### ISSUE TITLE
Error uploading files when 2 instances working

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8709]
### Description:

If I have 2 intances of RocketChat turned on, then on some random users (not all of them, only this users logged to the second) I have problems with uploading files. Upload is at veeerrry low percent, and in the end can't upload. In logs I have:

[Error: FileNotFound: no file with id g9av3QcqNgRMyLp8L found]
[Error: FileNotFound: no file with id 4QsNPqDDxDfBZFNE9 found]

I tried changing upload directory, upload type etc - all failed. Only turning off second instance helps.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.*
* Operating System: debian 9
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: yes
* Node Version: 4.5.0

### Steps to Reproduce:

1. Open conversation
2. Send file

### Expected behavior:

1. File should be delivered
 
### Actual behavior:

1. Upload hangs

### Relevant logs:
from rocket app log:
[Error: FileNotFound: no file with id g9av3QcqNgRMyLp8L found]
[Error: FileNotFound: no file with id 4QsNPqDDxDfBZFNE9 found]

**Comment by AmShaegar13** [comment]
Make sure both instances are started with INSTANCE_IP and PORT environments set and are able to communicate with each other. Especially when they are on different hosts because INSTANCE_IP defaults to `localhost`.

**Comment by Venomen** [comment]
Both are runnig well and communicating with each other..

**Comment by geekgonecrazy** [comment]
What file store are you using?

**Comment by Venomen** [comment]
> What file store are you using?
Local. Simple dir (/home/rocket/Rocket.Chat/files) @ ext4

**Comment by geekgonecrazy** [comment]
ok a couple more things.  Is user they are running as same as user who owns folder?  And are they on the same host or different hosts?

**Comment by Venomen** [comment]
Same user, same host. Just for testing and I see this error.

**Comment by geekgonecrazy** [comment]
@Venomen if for testing give another directory a shot like: `/tmp/rocketchat-files` something that won't be blocked access to write.  I think i've had in fedora where even if I had permissions set to 777 selinux disallowed access to home folders.

**Comment by Venomen** [comment]
I think that should be closed, working ok since 2018.

**Comment by geekgonecrazy** [comment]
Thanks for following up 👍

**Comment by xgdgsc** [comment]
I don' t know if I have an issue related. I have one remote machine that uses an internal server say at 192.168.1.2:8000, and I ssh tunnel that to local machine using `ssh -L 8000:192.168.1.2:8000`, and add this as 'localhost:8000' in rocket desktop at a local machine. Then chating using message works. But file loading would get stuck at 0%. I once see error message in console that seems it still tries to access 192.168.1.2 for file uploading.

**Comment by Venomen** [comment]
@xgdgsc it's resolved with start option - `export INSTANCE_IP=192.168.x.x`- at each host you have to add self ip.

**Comment by xgdgsc** [comment]
What does that mean? I' ve tried `INSTANCE_IP=127.0.0.1 rocketchat-desktop` but with same result

**Comment by Venomen** [comment]
@xgdgsc it has to be external_ip, not local (internal)

**Comment by AmShaegar13** [comment]
You'd need to start the Rocket.Chat server with `INSTANCE_IP=127.0.0.1` to make it work for you. However, this will break file uploads for everyone else connecting to Rocket.Chat directly using 192.168.1.2.

**Comment by xgdgsc** [comment]
Thanks. Restarting server is definitely not an option. I don' t know why messaging works with my tunnel approach but not file uploading. Can' t think of a way of using for now.
