### ISSUE TITLE
Add callback URI to custom oAuth menu

### ISSUE THREAD

**Issue by nonsintetic** [RocketChat/Rocket.Chat#871]
When you create a custom oAuth method in the settings interface there's no section indicating what the callback URI is. 
This is a required part of the oAuth process which you need to fill out on the oAuth server,  thus it should be available, especially since it changes based on the name of the method you provided (case sensitive too i believe).
For this **i suggest a pre-filled un-editable text input** so you can copy-paste it with ease.

The callback URI is something like this now:
http://*your rocketchat server link*/_oauth/*name you provided for the method*

**Comment by marceloschmidt** [comment]
Actually, there is one already ;) it's not been deployed yet, but if you pull the code from master, you'll see it. It's the first information under your custom oauth section.
