### ISSUE TITLE
LiveChat blank page

### ISSUE THREAD

**Issue by Ismaw34** [RocketChat/Rocket.Chat#8710]
### Description:

LiveChat returns a Blank page

### Server Setup Information:

* Version of Rocket.Chat Server: Tested on 0.59.0~0.59.3
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: v4.5.0

### Steps to Reproduce:

Go to http://yourserver/livechat

### Expected behavior:

Open a wizard to input your name an mail to start the livechat

### Actual behavior:

A blank page shows up

### Relevant logs:
No relevant logs, no errors, no warnings.

**Comment by Ismaw34** [comment]
Closing issue, nobody was available on the lichechat service.

**Comment by timiil** [comment]
me too, i am compilie the source code and run the app from a docker container, just return a blank page, but with some html element if i check the page source.

i try ie, ff , chrome, safari on IPAD, all blank.

i am doubt something wrong with the CSS stylesheet ?
