### ISSUE TITLE
Can not select text from home or privacy policy or Terms of service

### ISSUE THREAD

**Issue by jblobel** [RocketChat/Rocket.Chat#8723]
### Description:

When a user see a static text page (home, terms of services or pricavy policy), he is unable to select text.

This is not a good a good thing because he might want to select, copy and paste parts of it to ask questions. As those are like texts of law or tutorials, users might want to be able to keep some parts for their personal uses.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.55.1

### Steps to Reproduce:
See 
[your instance]/terms-of-service
or
[your instance]/privacy-policy
or
[your instance]/home

and try to select text.

### Expected behavior:

Being able to select text

### Actual behavior:

Can not select text

### Possible solution:

Remove the not input / not text aera criteria from these contents. Actually it is this code that is applied  : 
> not(input):not(textarea), :not(input):not(textarea)::before, :not(input):not(textarea)::after {
>     -webkit-user-select: none;
>     -moz-user-select: none;
>     -ms-user-select: none;
>     user-select: none;

It should be removed.

**Comment by darthgera123** [comment]
i can work on this issue

**Comment by simonv3** [comment]
This looks like it's been fixed at least in 0.59.0-develop. cc @MartinSchoeler or someone who can close it.
