### ISSUE TITLE
LDAP Avatar Sync not working

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat#8728]
### Description:

I updated Rocket from v56.* to the latest 59.*. After the Upgrade all the Avatars were gone. I expacted that to happen because of the changes made to the storage of the pictures. However the avatars wont sync by executing the LDAP synchronisation. Only when I log out and login again my avatar is synced from LDAP correctly.

### Server Setup Information:

* Version of Rocket.Chat Server: 59.3
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.5.0

### Steps to Reproduce:

1. Update from 56.* to 59.*
2. Try synchronize all missing Avatars from LDAP

### Expected behavior:

All Avatars should be synced.

### Actual behavior:

None of them is synced.

**Comment by willihelm** [comment]
Over nigth all avatars synced correctly. I wonder why they did not sync by manualy performing the LDAP sync.

**Comment by maxdwit** [comment]
0.59.x Same here. It synced over night...
Any hints why?
