### ISSUE TITLE
I want rocketbot response to user direct message, just like slack

### ISSUE THREAD

**Issue by steedos** [RocketChat/Rocket.Chat#873]
For Example, 
If I say "help" to, he will response list of commands i can execute. 
If I say "help emotions", he will response list of emotions i can use.
If I say "weather", he can response the weather of my city.

Currently, RocketBot can only response to message in specified channel, The internal robot response to every message on every room.

**Comment by marceloschmidt** [comment]
I'm not sure if I understood this right. Are you trying to say that you'd like rocketbot **not** to be on every room? You think that you should only interact with rocketbot via private messages?

**Comment by steedos** [comment]
Yes, for example, If i say hello to others, rocketbot always response, It's very strange.

**Comment by geekgonecrazy** [comment]
@steedos so this is actually just the behaviour of how we have the bot configured.

It would be nice to have the bot respond to direct messages... but that's not really rocketchat related.  

So maybe create an issue here: https://github.com/RocketChat/RocketBot for rocketbot specific requests?

**Comment by rashminair90** [comment]
Hi..can someone help me with API call for reading last message from the channel? I want to send notification to channel and accept their approval before deleting something.

**Comment by reetp** [comment]
> Hi..can someone help me with API call for reading last message from the channel? I want to send notification to channel and accept their approval before deleting something.

Don't ask on this issue - ask in the forums / open.rocket.chat  or see the above links to bots or maybe even try reading the documentation.

https://rocket.chat/docs/developer-guides/
