### ISSUE TITLE
Minify Livechat dynamic JavaScript

### ISSUE THREAD

**Issue by SeanPackham** [RocketChat/Rocket.Chat#8730]
The Livechat embed code fetches a couple of large unminified JavaScript files: 

- `livechat.js`
- `external_api.js`

These should be minified.

**Comment by sampaiodiego** [comment]
[external_api.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-videobridge/client/public/external_api.js) isn't related to livechat (but where did you see it being loaded?)

as I can see from [open server asset](https://open.rocket.chat/livechat/livechat.js?_dc=72661cb46d48f1b33b3e8fcfd79993fbe356ad20), `livechat.js` is minified.. is this file you're talking about?

**Comment by phlegx** [comment]
@sampaiodiego the `external_api.js` script is loaded from inside `livechat.js` script. See here: `$.getScript(t+"/packages/rocketchat_videobridge/client/public/external_api.js`
