### ISSUE TITLE
Rocketchat not querying Ldap for user data

### ISSUE THREAD

**Issue by ErWagon** [RocketChat/Rocket.Chat#8733]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2
* Operating System: Ubuntu 14.04
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 4.8.4 'Argon'

### Steps to Reproduce:

1. Change user's AD password
2. try to log in with new password
3. Rocketchat log gives the following: 
 rocketchat_logger rocketchat_logger.js:375 [31mLDAPHandler ➔ error [Error: User not Found] 

### Relevant logs:
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...3Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...4Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...4Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"data ...1Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"parse...2Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"Parsi...2Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...2Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...6Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://127.0.
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"data ...6Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"parse...6Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"Parsi...7Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...7Z","v":0}
Oct 31 17:32:41 rocketchat rocketchat-server.rocketchat-server[26660]: rocketchat_logger rocketchat_logger.js:375 LDAPHandler ➔ error [Error: User not Found]
Oct 31 17:32:42 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...8Z","v":0}
Oct 31 17:32:42 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...9Z","v":0}
Oct 31 17:32:42 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","level":10,"msg":"end e...7Z","v":0}
Oct 31 17:32:42 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...7Z","v":0}
Oct 31 17:32:42 rocketchat rocketchat-server.rocketchat-server[26660]: {"name":"ldapjs","component":"client","hostname":"rocketchat","pid":26678,"clazz":"Client","ldap_id":"918__ldap://...7Z","v":0}

**Comment by ledainam** [comment]
same issue on 0.59.3

**Comment by ErWagon** [comment]
I'm now on 0.59.3 and the problem persists.

**Comment by ErWagon** [comment]
I reverted the snap as far back as I could (0.59.1) and the problem continues.  Any suggestions?

**Comment by ErWagon** [comment]
If I reset user passwords within Rocketchat, they can access the system, which is another indicator it's not attempting to contact LDAP for authentication.

**Comment by danzone** [comment]
Same problem in our installation

**Comment by ErWagon** [comment]
This is fixed.  Previously we were adding the sAMAccountname at the end of the User Search Filter... (&(objectCategory=person)(objectclass=user)(sAMAccountName=#{username})).  This value was also being supplied in the Search Field which apparently caused a problem.  The Filter we are using now is (&(objectCategory=person)(objectclass=user)).
