### ISSUE TITLE
Mention number not disappearing even when message read

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#8747]
Running 0.59.1. RC open as usual, with a given channel being displayed. 

Meanwhile, user has been doing other things (not even in the browser), and sees RC mentions via number in favicon and number next to channel name (let's say we have multiple monitors and can see RC and other windows all the time).

User brings RC to focus to read latest messages including mentions, however unread mention numbers in favicon and sidebar are **not cleared** unless the user scrolls around (we believe Ctrl-Home then Ctrl-End does the job).

The whole team sees it so it's not a client issue. Please let us know if you need any more information on this issue.

**Comment by antgel** [comment]
Still see this annoying bug on 0.59.3.

**Comment by gabriellsh** [comment]
Tested 3.0.0-develop. Doesn't seem to happen anymore, if you still face this, please reopen.
