### ISSUE TITLE
[Feature request] Per channel option to clean up messages after selected period of time.

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#8757]
Channel option to clean up the messages after a selected period of time would be nice. Room owners would be able to set the message retention time.

The main purpose of this would be additional security (in case of database leak), but also preventing database growth.

Similar option is requested here #8749, but since the private channels contain membership information, setting the rooms up from the scratch would cause unnecessary work.

**Comment by modongmd** [comment]
1

**Comment by vynmera** [comment]
This will be possible in #11236 :)
