### ISSUE TITLE
why delete message by receivers  delete message from sender?

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#8759]
Why delete message by receivers  delete message from sender?

**Comment by marceloschmidt** [comment]
[GitMate.io](https://gitmate.io) thinks possibly duplicate or related issues are #7714 (Oneclick deployment not working for heroku ), #8422 (Can we record screen share in Rocket chat like audio and video??), #8455 ([Feature] Integrate this slack security bot its an FREE alternative to metacert), #8121 (Username not found), and #8435 ([Bug] If import failed second import try will result in 2x the amount of import data).

**Comment by azizkhani** [comment]
@marceloschmidt  what ? I think is not bug it is not support feature .when message send in direct one message insert in mongo . when receiver user delete that . main message delete physical and sender dose not see that . i think it will send two message or change delete message to logical delete

**Comment by azizkhani** [comment]
@MartinSchoeler what is your idea about this issue?
