### ISSUE TITLE
[FEATURE] Make LDAP users emails auto verfied

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#8764]
### Description:

LDAP admin checks LDAP emails, so LDAP users should have emails automatically verified. 
They should get email verified during they first logging in to Rocket.Chat.

### Actual behavior:
We have to verify all users manually with REST API.

Auto verification ldap users.

![image](https://user-images.githubusercontent.com/18348137/32364945-0570449c-c078-11e7-8ef8-c4cd808f9cc8.png)

**Comment by Gummikavalier** [comment]
Our setup seems to do auto verification for LDAP users, new ones and ones that have not logged in at all included.

**Comment by monspid** [comment]
From what version? We have already 0.58.2.

**Comment by Gummikavalier** [comment]
We are currently at 0.59.3 but we've been using Rocket.Chat starting from the version 0.56.0, going through all release versions since. Emails have always been verified for our users.

We get new users slowly but steadily, so we'd have noticed if the automatic verifying wouldn't have worked.

Our setup has other registration methods disabled; I'm guessing that maybe automatic verifying process would work only in these conditions.

**Comment by instantchow** [comment]
running 0.59.3 installed via Ansible and I do not have auto verification

**Comment by photoninger** [comment]
our LDAP users also have automatic verified email addresses and we also have registration disabled.
BUT our LDAP users still have in their profile in preferences the message "You need to verify your email address to get notifications".
It does not help to trigger a verification email and click the link. The message is still there.
That is very confusing for our users...
In admin view all LDAP users have a verified email address...

**Comment by marceloschmidt** [comment]
Rocket.Chat already automatically adds the email as verified when integrating LDAP. Thank you.

**Comment by photoninger** [comment]
@marceloschmidt That's right. But if you read my last comment LDAP users are confused when they check their preferences...

**Comment by marceloschmidt** [comment]
@photoninger I see your point. @rodrigok can we make sure we only display that message if the e-mail is not verified?

**Comment by sternenseemann** [comment]
We are still experiencing the initially described issue with Rocket.Chat 3.10.4: Our users login via LDAP, but their email addresses are not verified automatically. When checking the users view in the admin interface this can be confirmed.

**Comment by sternenseemann** [comment]
> We are still experiencing the initially described issue with Rocket.Chat 3.10.4: Our users login via LDAP, but their email addresses are not verified automatically. When checking the users view in the admin interface this can be confirmed.

This was the result of a configuration error. Rocket.Chat can sometimes still successfully create new users for an LDAP account even though the email field is not mapped correctly, resulting in LDAP users with an assigned email which is not verified.
