### ISSUE TITLE
Group audio call not working correctly in Rocket.Chat 0.59 dev

### ISSUE THREAD

**Issue by mborhade** [RocketChat/Rocket.Chat#8767]
Hi 

Group audio call not working correctly in Rocket.Chat 0.59 dev, call drops while screen share, also screen share also not working in gtoup call.
getting uncaught type error at  `window.audioContext && window.audioContext.close();`  in WebRTCClass.js  for close.

also not getting desktop alert for call.

Thanks,
Mangesh

**Comment by geekgonecrazy** [comment]
Issue for very old version.  Closing
