### ISSUE TITLE
Misleading user information after first login after self registration

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8768]
When the setting "Manually Approve New Users" is enabled, the user is redirected to the login page and by trying to login it pops up a misleading message:
<img width="283" alt="bildschirmfoto 2017-11-03 um 12 35 04" src="https://user-images.githubusercontent.com/853776/32372039-8408ba08-c093-11e7-9112-35d7f19873e6.png">

The user needs to be informed that "somebody" has to activate his account, before he is able to login.

**Comment by mrsimpson** [comment]
@MartinSchoeler I fixed this already in our branch. Will provide a PR with a cherry pick once merged

**Comment by rodrigok** [comment]
This was fixed already, after the account creation the system shows more information about the activation process.

![image](https://user-images.githubusercontent.com/234261/73967916-97419100-48f7-11ea-8bd4-568a4e4b9a95.png)
