### ISSUE TITLE
hubot to Send Twitter feed to specified channels.  - similar to SLACK

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#877]
Two valuable Features: 
1- Would like to add a feature similar to SLACK, have a twitter feed (selected followers) to be sent to a specified room automatically once they tweet

2- Also ability to set a channel for tweeting out, anything submitted will be sent out.
##

**Comment by IQ2022** [comment]
Another feature to email out the messages from certain Channels - like ALERTS..

**Comment by goobersmooch** [comment]
Some type of twitter integration would be nice.

**Comment by iroes** [comment]
You can try this: https://github.com/icon42/hubot-twitter-subscriptions

**Comment by robbyoconnor** [comment]
@iroes I tried that and it did not work well at all.

**Comment by IQ2022** [comment]
is there an easy way to add webhooks to have twitter feed into a channel? from a specific user or mulitple users?

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,
