### ISSUE TITLE
Wrong sidebar color for administration interface

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#8770]
Hi,

I am using 0.59.3 now and since the upgrade to 0.59 the sidebar color is wrong:

![screen shot 2017-11-03 at 14 21 54](https://user-images.githubusercontent.com/377856/32375622-9e814c9c-c0a2-11e7-8c60-122d2de36f19.JPG)

I never customised any of these colors and for 0.58.x versions everything was fine.

**Comment by Gummikavalier** [comment]
That's white for us (I don't know if that is correct color either).
