### ISSUE TITLE
[Feature request] More fine grained permission system

### ISSUE THREAD

**Issue by fldpi** [RocketChat/Rocket.Chat#8771]
### Description:

Currently, rocket chat does not allow giving permissions for subcategories of "Settings". This leads to some issues, if, e.g. one wants to allow someone to edit the main page or change the CSS but does not want to give them access to the LDAP settings (since they contain sensitive data).

Instead, one should be able to set permissions for the individual subcategories.

**Comment by mxmo0rhuhn** [comment]
There is now a Bounty for that.
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51126931)](https://www.bountysource.com/issues/51126931-feature-request-more-fine-grained-permission-system?utm_source=51126931&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by mrsimpson** [comment]
I'm already working on that. Also without bounty ;-)
50% done.

**Comment by mxmo0rhuhn** [comment]
Happy to hear that you started without a bounty - but don't hesitate to claim it later :) 
We're very happy about this feature!

**Comment by mrsimpson** [comment]
;-) it is actually done. See #8942. I’ll keep the PR up to date with the latest release so that those in need can merge it. Only as the Rocket.Chat guys start merging it, I’ll update it to develop
