### ISSUE TITLE
Live chat

### ISSUE THREAD

**Issue by johnboker** [RocketChat/Rocket.Chat#8773]
### Description:

Livechat doesn't seem to work.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 4.8.4

### Steps to Reproduce:

1. Install on ubuntu using snap  
2. Setup SSL using Caddy
3. Enable Livechat
4. Set routing method to "Guest pool"
5. Embed widget on website
6. In an incognito window in chrome start a chat from the embedded widget
7. See that there is a livechat session that is open if you're the admin under "Current Chats"
8. Notice no entries in the guest pool

### Expected behavior:

I expect there to be a user in the guest pool waiting for a livechat agent to being a chat.

### Actual behavior:

No users are in the guest pool.  When i go to the current chats and click on a chat it opens the chat window, but it wont send a message to the widget.  

The widget does show that I'm typing, but when i press enter to send the message the message stays grayed out and doesnt get sent.  

The widget continues to say "Connecting to an Agent".

The 

### Relevant logs:

`[34mI20171103-18:34:18.732(0) Exception from sub stream-notify-room id HsZeYnCPMdBALHwK8 TypeError: Cannot read property 'indexOf' of undefined   at [object Object].<anonymous> (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:4937:25)   at Streamer.isReadAllowed (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_streamer.js:341:38)   at [object Object].<anonymous> (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_streamer.js:476:16)   at [object Object].<anonymous> (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:1295:15)   at packages/matb33_collection-hooks.js:307:21   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)   at maybeAuditArgumentChecks (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:1857:12)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:1180:16   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at [object Object]._.extend._runHandler (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:1179:51)   at [object Object]._.extend._startSubscription (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:1027:9)   at [object Object]._.extend.protocol_handlers.sub (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:815:12)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:753:85 ` 

`[34mI20171103-18:34:22.189(0) Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined   at [object Object].Meteor.methods.sendMessage (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:15629:59)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:1276:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:1857:12)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:874:21)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:753:85`  

`[34mI20171103-18:35:39.156(0) Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined   at [object Object].Meteor.methods.sendMessage (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:15629:59)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:1276:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:1857:12)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:874:21)   at /snap/rocketchat-server/1188/programs/server/packages/ddp-server.js:753:85  `

After restarting the server then starting a chat through the widget and sending one message this error is displayed: 

`[34mI20171103-19:13:50.962(0) Exception in defer callback: TypeError: Cannot read property 'length' of undefined   at /snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:2750:53   at /snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:320:25   at Array.reduce (native)   at Object.RocketChat.callbacks.run (/snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:313:6)   at /snap/rocketchat-server/1188/programs/server/packages/rocketchat_lib.js:4115:32   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at packages/meteor.js:452:25   at runWithEnvironment (packages/meteor.js:1188:24) ` 

![screen shot 2017-11-03 at 2 43 13 pm](https://user-images.githubusercontent.com/4153912/32390976-c65f57fa-c0a6-11e7-975a-f9ed571c8601.png)
![screen shot 2017-11-03 at 2 30 32 pm](https://user-images.githubusercontent.com/4153912/32390989-d42e07fa-c0a6-11e7-82c4-8e7e7975a6e9.png)
![screen shot 2017-11-03 at 2 30 03 pm](https://user-images.githubusercontent.com/4153912/32390990-d7bdfb14-c0a6-11e7-8722-9a121529eb0e.png)

**Comment by sampaiodiego** [comment]
did you create livechat agent? going to `Livechat > User Management` you **have** to added at least one agent.
