### ISSUE TITLE
RSS integration into channels 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#878]
have RSS Feed pushed into a channel, like news, events, etc.
##

**Comment by jonbaer** [comment]
Would this be something better suited for hubot-rocketchat to handle instead? ie: https://www.npmjs.com/package/hubot-rss-reader ...

**Comment by Sing-Li** [comment]
:+1:  Relieves the chat server of the work load, and helps to keep the RSS fetch/process code simple and independent.

**Comment by Ulrar** [comment]
Hi,

That's exactly what I'm trying to setup, but that script isn't on hubot-scripts. How do you add other scripts to the internal hubot ? That doesn't seem to be documented.

**Comment by DalePayman** [comment]
+1

**Comment by cyclops24** [comment]
+1

**Comment by jszaszvari** [comment]
use hubot for this, it shouldn't be in core. there's plenty of rss modules for hubot.

**Comment by cyclops24** [comment]
You mean this?
https://www.npmjs.com/package/hubot-rss-reader

**Comment by TwizzyDizzy** [comment]
I agree with @jszaszvari. This is nothing that should be included in the core of Rocket.Chat, there's plenty of possibilities to get content into Rocket.Chat.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

**Comment by albjeremias** [comment]
Is there a simple tutorial on how-to do this? or do I really have to go to this channel and ask? :)) thanks

**Comment by boldwade** [comment]
@albjeremias , did you ever figure this out? It's a mystery to me as well on how I would set this up.

**Comment by yodatak** [comment]
I just found how to use this if your are interested https://github.com/Flipez/hubot-rss-rolf

**Comment by yodatak** [comment]
```
git clone https://github.com/RocketChat/hubot-rocketchat-boilerplate
cd hubot-rocketchat-boilerplate
# edit the external-scripts.json and put this 
[
"hubot-rss-rolf",
"hubot-mongodb-brain"
]

npm install
npm install hubot-rss-rolf -save
npm install hubot-mongodb-brain -save
npm install coffee-script@&quot;&gt;=1.9&quot; -save
npm install mongodb@2.2


# create and put into the .env file this
export ROCKETCHAT_URL=chat.CXXXXXX.org
export ROCKETCHAT_USER=mybotuser
export ROCKETCHAT_PASSWORD=mypassword
export ROCKETCHAT_ROOM=general
export ROCKETCHAT_USE_SSL=true
export DEBUG=hubot-rss-reader*      # debug print
export HUBOT_RSS_INTERVAL=600       # 600 sec (default)
export HUBOT_RSS_HEADER=:sushi:     # RSS Header Emoji (default is &quot;sushi&quot;)
export HUBOT_RSS_USERAGENT=hubot    # (default is &quot;hubot-rss-reader/#{package_version}&quot;)
export HUBOT_RSS_PRINTSUMMARY=true  # print summary (default is &quot;true&quot;)
export HUBOT_RSS_PRINTIMAGE=false   # print image in summary (default is &quot;true&quot;)
export HUBOT_RSS_PRINTMARKDOWN=true # use markdown message (default is &quot;false&quot;)
export HUBOT_RSS_PRINTERROR=false   # print error message (default is &quot;true&quot;)
export HUBOT_RSS_IRCCOLORS=true     # use IRC color message (default is &quot;false&quot;)
export HUBOT_RSS_LIMIT_ON_ADD=false # limit printing entries on add new feed. (default is 5)
export HUBOT_RSS_DUMP_USERS=&quot;&quot;      # limit dump to special user (list without spaces eg. &quot;user1,user2&quot;)


source .env
bin/hubot
```
I cant belive that is so difficult and undocumented to have just a simple rocketchat bot

**Comment by merauder** [comment]
@yodatak thanks for the instructions, however I am getting the following error.  The Hubot connects for a few seconds, and then crashed with this (hostname changed for posting only):

`[Sat Jan 28 2023 15:07:18 GMT-0500 (Eastern Standard Time)] INFO [startup] Rocket.Chat adapter in use
[Sat Jan 28 2023 15:07:18 GMT-0500 (Eastern Standard Time)] INFO [startup] Respond to name: Hubot
[Sat Jan 28 2023 15:07:18 GMT-0500 (Eastern Standard Time)] INFO [startup] Respond to alias: rssbot
[Sat Jan 28 2023 15:07:18 GMT-0500 (Eastern Standard Time)] INFO [connect] Connecting {
  username: 'rssbot',
  password: '********',
  ldap: false,
  host: 'mysite:8080',
  useSsl: true,
  timeout: 20000,
  rooms: [ 'cloudstatus' ],
  allPublic: false,
  dm: false,
  livechat: false,
  edited: false,
  integrationId: 'js.SDK',
  roomCacheMaxSize: 10,
  roomCacheMaxAge: 300000,
  dmCacheMaxSize: 10,
  dmCacheMaxAge: 100000
}
[Sat Jan 28 2023 15:07:18 GMT-0500 (Eastern Standard Time)] INFO [connect] Connected
[Sat Jan 28 2023 15:07:18 GMT-0500 (Eastern Standard Time)] INFO [login] Logging in rssbot
[Sat Jan 28 2023 15:07:19 GMT-0500 (Eastern Standard Time)] INFO [subscribe] Preparing subscription: stream-room-messages: __my_messages__
[Sat Jan 28 2023 15:07:19 GMT-0500 (Eastern Standard Time)] INFO [subscribe] Stream ready: 2
[Sat Jan 28 2023 15:07:19 GMT-0500 (Eastern Standard Time)] INFO [reactive] Listening for change events in collection stream-room-messages
[Sat Jan 28 2023 15:07:19 GMT-0500 (Eastern Standard Time)] INFO [joinRoom] Calling (async): ["6DnndpzH6yD3wNNof"]
[Sat Jan 28 2023 15:07:20 GMT-0500 (Eastern Standard Time)] ERROR Unable to load /home/merauder/hubot-rocketchat-boilerplate/node_modules/hubot-rss-reader/scripts/hubot-rss-reader: /home/merauder/hubot-rocketchat-boilerplate/node_modules/hubot-rss-reader/libs/rss-checker.coffee:26:5: error: Can't reference 'this' before calling super in derived class constructors
    @entries = new Entries @robot`

**Comment by brianread108** [comment]
Did this ever get fixed? Am really interested in RSS feeds to Rocket.chat channels.
