### ISSUE TITLE
Iframe auth workflow needed.

### ISSUE THREAD

**Issue by phuyem** [RocketChat/Rocket.Chat#8781]
For people who is new to Rocketchat like me, it is really hard to figure out how it works. It took me days to understand it by reading the docs ( which are very well written) and the source code. 

https://docs.rocket.chat/developer-guides/iframe-integration/authentication/

The workflow is something like this, just someone in the future google this page  : 

1/ Enable Iframe in Admininstraton> Accounts > Iframe
2/ Rocketchat will disable its login page, so that
3/ When user enter Rocketchat website, the software will try to login using a token getting from API URL ( api from your website, not from Rocketchat )
4a/ If successful, then user is logged in automatically
4b/ If failed, the IFrame URL ( a login page from your website, not Rocket chat ) will be show for user to authenticate 
5/ If successful,  your website is responsible to redirect user to chat screen, somewhat.

**Comment by eddiekollar** [comment]
Also useful to look at [/packages/rocketchat-iframe-login/iframe_client.js](https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-iframe-login/iframe_client.js) to understand the workflow mentioned above by @phuyem

**Comment by MartinSchoeler** [comment]
@phuyem Could you reopen this on our [docs](https://github.com/RocketChat/Rocket.Chat.Docs) Repository?

**Comment by christtrc** [comment]
@phuyem Hi, I have a problem to use iframe auth.  The API URL called from iframe page has nothing to be related with current user in parent page. How can I know the current login user in the API URL handling method of the server side (I use java)? 
When I use session to solve this, but the session id which loginToken generate method have is different with API URL auth method. Any help, thanks.
