### ISSUE TITLE
[BUG] File name changed after upload (multi files upload)

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#8783]
Hi guys,
When I try upload multi files with drag and drop RC change last file name.
I upload this files:
* 1.txt
* 2.txt
* 3.txt
* 4.txt
But RC changed these files to:
* 1.txt
* 2.txt
* 3.txt
* 1.txt
See this gif for more info:
![peek 2017-11-05 11-04](https://user-images.githubusercontent.com/8266479/32412835-24f3e286-c219-11e7-8e6f-ebbbdff15072.gif)

**Comment by marcingodlewski** [comment]
This is an old bug, reported here #7291 in June, but sadly never resolved.
However I confirm that the problem still exists in 0.59.3

**Comment by cyclops24** [comment]
@marcingodlewski Thanks for your reply, so I can close this issue and monitor #7291 issue.
Thanks for your attention.
