### ISSUE TITLE
Initial password for new users does not work

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8784]
When creating a new user via Admin UI using the options: "Random Password" & "Require password change", the user is (sometimes) not able to login successful.

Rocket.Chat Version: 0.59.2
NodeJS Version: 4.8.4 - x64

**Comment by MartinSchoeler** [comment]
@ruKurz What is the error that the user get when logging in?

**Comment by ruKurz** [comment]
@MartinSchoeler seems like the issue occurred only once and we are not able to reproduce now. So I close this Issue / open it again, when we know what causes the problem. Sorry for the inconvenience. Cheers !
