### ISSUE TITLE
Cannot setup project for code development on Win7

### ISSUE THREAD

**Issue by itaditya** [RocketChat/Rocket.Chat#8790]
### Description:

Cannot setup project for code development on Win7

### Server Setup Information:

* Operating System: Win 7
* Node Version: v8.4.0

### Steps to Reproduce:

1. Ran `meteor npm start`.

### Relevant logs:
[2017-11-06T12_46_32_807Z-debug.log](https://github.com/RocketChat/Rocket.Chat/files/1446326/2017-11-06T12_46_32_807Z-debug.log)

**Comment by mrsimpson** [comment]
@itaditya Prior to 0.60 (which is about to be released), Rocket.Chat is based on Meteor 1.5 which includes Node 4. With 0.60, it will support Meteor 1.6 and Node 8.
Apart from that, I had very poor experience with Meteor on Windows. Some dependencies made compilation basically impossible.
Recommend using Linux (in a virtual Box if only needed infrequently) or Mac.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
