### ISSUE TITLE
Link to opening issues is gone

### ISSUE THREAD

**Issue by krishnoid** [RocketChat/Rocket.Chat#8797]
### Description:
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues 

I visited this page but it said:
<hr />
<strong>Whoops we can't find it</strong><br>
Please let us know if what you are looking for has completely disappeared
<hr />

Sorry if this is the wrong place to report this, but ... I visited this page to see how to open issues but it said:
goto 10

**Comment by geekgonecrazy** [comment]
Where was this link found?  

Link is now: https://docs.rocket.chat/contributing/reporting-issues/
