### ISSUE TITLE
Would like Portable/PortableApps Windows version

### ISSUE THREAD

**Issue by krishnoid** [RocketChat/Rocket.Chat#8798]
### Description:

For the Windows desktop client, it would be great to have a portable version where the application itself, application settings, and data files are are in one directory, which can be on a portable or network drive.  This could be a roll-your-own sort of thing, or a [PortableApps-format](https://portableapps.com/development) portable application.

### Steps to Reproduce:

1. Attempt to install Windows installer
2. See no option for portable install
3. Be sad

### Expected behavior:

An option for a portable install, or a separate PortableApps installer.

### Actual behavior:

Nope

**Comment by JuanMiguelBG** [comment]
+1

**Comment by geekgonecrazy** [comment]
This is specific to the desktop client.  Feel free to open an issue there: https://github.com/rocketchat/rocket.chat.electron  but I don't think its something we plan to do

**Comment by rasos** [comment]
@arminfelder can we achieve this with the RC compatible fairchat Qt mobile client, if we optimize it for desktop?

**Comment by arminfelder** [comment]
@rasos yes of course

**Comment by kaiiiiiiiii** [comment]
There’s no need for an extra application, you can archive that with the already existing Rocket.Chat Electron app (run electron-builder with portable as target format). 

And as @geekgonecrazy already mentioned, please open an issue in the electron app repository for that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
