### ISSUE TITLE
Compress and make faster Voice messages!

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#880]
I test audio sending in demo
with 1mbit/s internet speed it took a long time to upload and sent !
i think that was because of high quality of recordings!
in native apps you can reduce the quality and convert audio before send ! like all of messengers (whatsapp , telegram , imo , viber and ...)
in addition , i think download link of recorded audio is useless and just make rooms messy!
better to use a tiny player for voice messages !
##

**Comment by Sing-Li** [comment]
:+1:   optimized handling of voice data type, especially for mobile, will be a **killer** feature.

**Comment by MartinSchoeler** [comment]
Hey @{name}, I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
