### ISSUE TITLE
Edit and download icons are not updated for new UI

### ISSUE THREAD

**Issue by kokeksibir** [RocketChat/Rocket.Chat#8803]
Old font-awesome icons are rendered for post edit and download attachment buttons.
<img width="350" alt="screen shot 2017-11-07 at 09 30 37" src="https://user-images.githubusercontent.com/1814767/32480189-2235df9e-c396-11e7-9169-7fca0efc40c1.png">

**Comment by MartinSchoeler** [comment]
Yes, we still haven't finished the ui redesign, so this will be done on the next versions.
