### ISSUE TITLE
Prevent man-in-the-middle attacks during user registration by admin

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8808]
### current situation

After creating a user via admin UI, the user retrieves one mail, that contains both: `username and password` as plain text.

### expected behavior

The goal of this issue is to prevent man in the middle attacks during user registration by the administrator.

### Possible solutions

- #9842 - Invalidate the initial password after a time period
- send username and password in separated mails
- Create a registration link, which becomes invalid after a short time (similar to invalidate password)
- (send encrypted mails)

What else could be done to prevent username / passwords from being sent in plain text and unencrypted?

**Comment by shanewils92** [comment]
This can be changed by going to Admin -> Email -> Registration via Admin. Remove the [password] entry and it will no longer send along with the username.

```html
<h2>Welcome to <h1>[Site_Name]</h1></h2><p>Go to [Site_URL] and try the best open source chat solution available today!</p><p>You may login using your email: [email] and password: [password]. You may be required to change it after your first login.
```

**Comment by ruKurz** [comment]
Thank you very much for the quick reply! In the meanwhile this idea came also up to my  ;-)

**Comment by ruKurz** [comment]
But then the user can never login.

**Comment by ruKurz** [comment]
When creating this issue, I didn't choose the title well. I updated the title, the description and reopen this issue.

**Comment by rodrigok** [comment]
Now it's possible to invite users using invite links, they have time to expire and usage limits.

When creating users via admin page it's possible to enter a manual password instead of generating a random one, it's possible to not set it via email.

Since we added the [invite links](https://github.com/RocketChat/Rocket.Chat/pull/15933) feature I'll close this issue.
