### ISSUE TITLE
[BUG] Snippet avatar display

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#8809]
* Version of Rocket.Chat Server: ***newest open.rocket.chat***

I think pictures describes the issue.

## How to get that:

![image](https://user-images.githubusercontent.com/18348137/32506805-cc2b1f4c-c3e5-11e7-8fae-9eb651281a09.png)

## It should be a nice avatar, but it looks awful
![image](https://user-images.githubusercontent.com/18348137/32506855-f7c45470-c3e5-11e7-9fbe-6ba022435423.png)

**Comment by jsivak** [comment]
@monspid I can't see how to add snippets in 0.59.3. Can you tell me how you were able to create a snippet?

Thanks

**Comment by monspid** [comment]
Actually i do not know how. There is no button to do this. I think it was a snippet which was added before 0.59.

**Comment by jsivak** [comment]
Ok, I already have a bug submitted for that #8585

**Comment by rodrigok** [comment]
Closed via #8937
