### ISSUE TITLE
LDAP Error building Rocket.Chat with mup on Ubuntu 15.04

### ISSUE THREAD

**Issue by MehdiMahmoudi** [RocketChat/Rocket.Chat#881]
Hi,
I'm trying to deploy RocketChat using the mupx command (mup development version) on a Ubuntu 15.04 machine.
I got the following error while building:

"error: rocketchat:ldap is not compatible with architecture 'os.linux.x86_64'"

Not that I hadn't had this before when building on Ubuntu 14.10. Both are x86_64 architectures.

Any ideas?
Thanks!

**Comment by bosung90** [comment]
I am trying to deploy to Ubuntu 15.10 using mupx and I get error saying "x Uploading bundle: FAILED No such file"

**Comment by jalagrange** [comment]
I am having the same problem when I try to build the app for deployment. I get: "ldap is not compatible with architecture 'os.linux.x86_64'"

**Comment by garg** [comment]
Same here:
~~~
Errors prevented bundling:
While linking the program:
error: rocketchat:ldap is not compatible with architecture 'os.linux.x86_64'


=> Build Error. Check the logs printed above.
~~~

Appears to be a dup of #1114

**Comment by jalagrange** [comment]
Yup I solved it the same way, it built fine directly on Linux

**Comment by Sing-Li** [comment]
@garg  and @jalagrange  -  OSX ABI is  `os.osx.x86_64`  :disappointed:
