### ISSUE TITLE
Users with create-token permission can create one for admin then...

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#8814]
### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
Create an user, lets say John, with any role. 
2. 
Assign create token to John
3. 
Now John can create token for admin then he can use it to do crazy stuff

### Expected behavior:
I dunno what to say, it looks really not secure to me. Admin users should be president-level of protection...

### Actual behavior:

John can access the system as admin via API

**Comment by makibras** [comment]
to be addressed via environment variable
