### ISSUE TITLE
Save and Delete Buttons for Channel and Private Channel not available

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#8815]
### Description:

Hey guys, since we update to 0.59.3 the save and delete buttons for channel and private groups disappeared.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: Enabled
* Node Version: v4.5.0

### Steps to Reproduce:

1. Log in as admin
2. Open admin panel
3. Click on chats
4. Click on general
5. Edit the channel

### Expected behavior:

A save and/or delete button is present.

### Actual behavior:

No button available

### Relevant logs:
<img width="435" alt="bildschirmfoto 2017-11-08 um 07 47 34" src="https://user-images.githubusercontent.com/8867063/32535135-1ef00c56-c459-11e7-88a6-c196b8b50073.png">

Thank you very much for helping us. :-)

Kind regards,

**Comment by Paulpatou** [comment]
See this topic https://github.com/RocketChat/Rocket.Chat/issues/8562

A quick fix is adding this to layout->customcss:

.flex-tab .channel-settings .button {visibility: visible}


the fix work for me.

**Comment by hExPY** [comment]
@Paulpatou also works for me. Therefor i wait for the next patch.

Thank you very much. :-)
