### ISSUE TITLE
status not appear on desktop rocketchat

### ISSUE THREAD

**Issue by franckche** [RocketChat/Rocket.Chat#8817]
Hello

since I upgrade to 0.59.3.  user status (online, busy, ...) doesn't appear anymore on desktop version but it's ok on android phone (app from playstore).

It looks like it's a css problem, if I try to modify css it' working well.
what I tried in css :
```
bar-item__user-status--online {
    background-color: #2de0a5;
    /* background-color: var(--status-online); */    (I need to uncheck this line for working good)
}
```

So I tried to modify the custom css and force it but it's look like the custom css isn't applied.

do you any idea ?

thanks

**Comment by ggazzo** [comment]
key @franckche I closed this issue because I'm quite confident it was fixed, any problem let me know
