### ISSUE TITLE
Administration: LDAP page link deprecated

### ISSUE THREAD

**Issue by simopaasisalo** [RocketChat/Rocket.Chat#8827]
### Description:
Hi,

I noticed that the LDAP page in Administration links to a deprecated address in the wiki. The link points to https://rocket.chat/docs/administrator-guides/authentication/ldap/ but the correct address should be https://docs.rocket.chat/administrator-guides/authentication/ldap/

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances:  1

### Steps to Reproduce:

1. Go to administation
2. Go to LDAP settings
3. Try to open the link in the description

### Expected behavior:

The LDAP wiki page should open

### Actual behavior:

A 404 page pops up

**Comment by shikhar-scs** [comment]
The link https://rocket.chat/docs/administrator-guides/authentication/ldap/  already redirects to https://docs.rocket.chat/administrator-guides/authentication/ldap/. It might be that they have fixed it now and so this shouldn't be an issue now . close?

**Comment by shikhar-scs** [comment]
Btw I have already found where to do that. @MartinSchoeler

**Comment by shikhar-scs** [comment]
Are we doing anything about this @MartinSchoeler ? I've already filed a PR for the same #9081 and there hasn't been much response there too of late. Either this issue can be closed or the PR there can be merged.

**Comment by rodrigok** [comment]
The documentation link was already fixed.

Thanks by your report and let us know if you have any other issue.
