### ISSUE TITLE
ON-Demand Channel Creation from Login

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#883]
Can we have a front-end api, that request meeting (could be paid sessions) and takes them into a private channel (one on one).. 
##

**Comment by IQ2022** [comment]
we could have small app (can be added into a site or anywhere else) that has the following info:
name, email, reason for discussion, payment and meet now. ---> take you to a room ( if approved or paid).  then can have voice or video one-on-one..

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
