### ISSUE TITLE
Como fazer o backup do mongo?

### ISSUE THREAD

**Issue by nicolasdezena** [RocketChat/Rocket.Chat#8832]
Instalei o rocketchat via snapshot no ubuntu, como faço para fazer o dump do mongo?

Esta me dando o seguinte erro, com o comando mongodump:

connected to: 127.0.0.1
assertion: 17369 Backing up users and roles is only supported for clusters with auth schema versions 1 or 3, found: 5

E com esse não acontece nada, a pasta parties fica vazia:
 mongodump --db parties
connected to: 127.0.0.1
2017-11-09T17:36:19.394-0200 DATABASE: parties   to     dump/parties

Abs,
Nicolas Dezena

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
