### ISSUE TITLE
make ldap avatar source field customizable

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#8835]
### Description:
We are storing several versions of avatars in our LDAP.
ldapUser.thumbnailPhoto and ldapUser.jpegPhoto 

As you can see in this GIST: https://gist.github.com/traxanos/e4134f46dc6c525e3b102dcfcaf62813
At this moment the thumbnail is preferred:
`+    var avatar = ldapUser.object['thumbnailPhoto'] || ldapUser.object['jpegPhoto'];          `

I would like to have an option within the ldap configuration page, to select the source for the LDAP avatar.

If there is an existing way to set the mapping right, I'am interested to know.

* Version of Rocket.Chat Server: 0.59.3.
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap + tar on  different instances
* Number of Running Instances:  2

### Steps to Reproduce:
1. open administration page / LDAP
2. No option to select the avatar field from LDAP

### Expected behavior:
1. open administration page / LDAP
2. Option field to enter the LDAP Field we would like to use within rocket.chat as  avatar.

### Actual behavior:
Wrong picture ( size ) from the LDAP is used.
Optional: Choose one LDAP field for the small Avatar, and another one for the user avatar.

**Comment by traxanos** [comment]
Yes please add a configuration field for avatar synchronisation.

**Comment by 0x6c** [comment]
Same for me. As avatars from ldap are looking terrible, and size of thumbNail photo is not customizable for example in AD.

**Comment by alexbartsch** [comment]
@MartinSchoeler What do you think. Maybe old, but still a legitimate request. And, furthermore, only a small change.
