### ISSUE TITLE
Embedded media not working on custom instance

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#884]
This is a support request. I've successfully installed Rocket.Chat on a production server (Ubuntu 14.04) following the instructions provided in the wiki. There seems to be some features missing compared to the demo version and I was hoping someone could explain how to enable them.

The most obvious missing feature is the preview of embedded media. Uploading a file just shows the file url but not a preview (if its an image). Pasting a link does not show a preview.

The other missing feature is the audio recording button next to the chat field.

Is there a concept of plugins that I'm missing?

Any help appreciated.

**Comment by kakawait** [comment]
There is a bug describe here #763 and #849 that break autoload feature for embedded media. Try to restart your meteor application it can fix it (do not clean your mongodb!)

**Comment by tanc** [comment]
Thank you, a simple restart has enabled the functionality of media embedding.

Any idea about the audio recording? Is that a plugin?

**Comment by kakawait** [comment]
@tanc are you using stable version or latest source code from Github master branch?

**Comment by tanc** [comment]
I'm fetching and building from https://github.com/RocketChat/Rocket.Chat/archive/master.tar.gz

**Comment by kakawait** [comment]
that strange I just run app from master source code I have the button. I'm not RocketChat member or developer so I can't help you more. I can just say you there is no plugin system or feature activation for record button.

**Comment by tanc** [comment]
Ok, no problem, thanks for your help :-)

I'll close this issue as it was more around getting media embed working.

**Comment by jclabaugh** [comment]
I think you have to be using a webRTC-compliant browser (Chrome, Firefox). Safari on OS X won't show the record button due to a lack of RTC compliance.

**Comment by tanc** [comment]
Great! That was exactly it, Chrome and Firefox display the button, Safari doesn't. Thanks!
