### ISSUE TITLE
Support requesting authentication redirect instead of popup for iframe

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#8840]
### Description:
Rambox wants to be able to add SSO support for Rocket.Chat.  But since most of our auth providers pop out it breaks the flow in electron.  So they need a way to be able to request the flow happen in the same window instead of a popup.

I would think maybe something like /login?nopopup=true or something to communicate popups aren't allowed?

**Comment by jonny0303** [comment]
+1 👍

**Comment by saenzramiro** [comment]
If Rocket.Chat can add a flag to the URL like @geekgonecrazy said, it will be perfect for us.

**Comment by geekgonecrazy** [comment]
:top: for clarity us is referring to rambox.

https://github.com/saenzramiro/rambox/issues/64

**Comment by marceloschmidt** [comment]
Custom OAuth allows you to specify if you want a popup or redirect. @geekgonecrazy can you check if this solves it and then close if it does?

**Comment by rodrigok** [comment]
<img width="1227" alt="screen shot 2019-02-21 at 11 12 56 am" src="https://user-images.githubusercontent.com/234261/53174964-be5d6080-35c9-11e9-8962-b0677467bf95.png">

**Comment by geekgonecrazy** [comment]
I don’t personally use rambox.  But I would think that would fix.  :)

If anyone else is following this ticket using rambox please let us know if this doesn’t work and we can reopen
