### ISSUE TITLE
i'm tring develping base on this source , but rebuild is too slow ,is it has any way to rebuild it very fast when i change the code

### ISSUE THREAD

**Issue by youxiaoriqi** [RocketChat/Rocket.Chat#8843]
i'm tring develping base on this source , but rebuild is too slow ,is it has any way to rebuild it very fast when i change the code? thank you !!!

**Comment by MartinSchoeler** [comment]
@youxiaoriqi Try running the server with `meteor npm start`, after the server is built, every change will cause a refresh.
