### ISSUE TITLE
Unread Notification Not Clearing

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#885]
The unread notifications not clearing for some reason has annoyed me and I've finally seen a pattern recently, here are the steps to replicate it:
1. Create new channel, `unread-test` in my case
2. Have someone else join, `geekgonecrazy` in my case
3. Chat a couple times
4. Unfocus the window while leaving that channel up
5. Have the other person spam to the point the unread mark goes out of view.
6. Read all the chat (bar should show correct information) and make sure it marks as read
7. Unfocus the window again
8. Have the other person spam even more
9. Type something without reading the chat
10. Have the other person spam even more
11. See the unread amount of step 10 plus step 8. __bug__
12. Scroll up to the message sent in step 9 and see the unread bar go away.
13. Scroll up so message sent in step 9 is out of view and the unread bar comes back. __bug__

**Comment by rodrigok** [comment]
13 steps? Fear!!! :smile: 

Thanks, I will try to reproduce ASAP

**Comment by graywolf336** [comment]
Yeah pretty much :stuck_out_tongue_winking_eye: if you need help reproducing, ping me and I'll help.

**Comment by gwillen** [comment]
Hm, I can't tell if this issue is describing the same problem I'm seeing. I'm seeing channels having the has-alert CSS class (e.g. showing in bright white boldface) even though I've scrolled all through their contents and nothing seems unread. Is that closely related to this issue or separate? I see discussion of the unread bar in the chat window, but not of whether the channel is also showing as unread. Thanks!

**Comment by graywolf336** [comment]
Yes, that's the same thing which is happening here.

**Comment by internalfx** [comment]
My users have complained about this as well.

**Comment by tulip0** [comment]
This bug definitely makes Rocket extremely difficult to use. 

![unread](https://cloud.githubusercontent.com/assets/15009664/12051038/ccc48cfe-af51-11e5-90fe-53c8f4234b7f.png)

At a minimum, shouldn't the unread flags be cleared when the user has made a reply in that channel?There seems to be a related bug where the client insists there's unread messages both above and below the view, even when there is none. 

![rocket](https://cloud.githubusercontent.com/assets/15009664/12051029/959772aa-af51-11e5-9990-eedb818d815d.png)

I've not been able to find a quick workaround unfortunately.

**Comment by gwillen** [comment]
One of my coworkers suggested a workaround which seems to 'unstick' the notification eventually: Repeatedly (1) clicking the channel and then (2) scrolling to the top and bottom of the window. Usually after something like 5 or 10 tries, this seems to work. Not really sure why, but it beats leaving it around forever.

**Comment by graywolf336** [comment]
@gwillen a quick workaround would be pressing escape on the keyboard after going out of the channel and back in.

**Comment by asmartin** [comment]
+1 I have also noticed notifications that are not cleared like this

**Comment by Ruuudi** [comment]
+1

**Comment by Molle500** [comment]
+1

**Comment by gwillen** [comment]
@marceloschmidt Is there is a commit that fixes this issue?

**Comment by marceloschmidt** [comment]
There were multiple commits regarding this, the latest one being dffc11b.

**Comment by gwillen** [comment]
Thank you, that's awesome! That helps me track what I should be encouraging our IT guy to update to, and when.
