### ISSUE TITLE
[NEW] Improve Apple Push Notifications payload & add ability to reply on iOS

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#8863]
### Description:

1. Category key in the payload
_needed for actionable notifications in iOS_
2. Use title key
_for better looks instead of only alert with \n_
3. Show server name or host 
_we now support multiple servers in iOS so we need to differentiate_
4. Localization

We receive this for messages:

```swift
"aps" : {
    alert : "cardoso\nok",
    badge : 2,
    sound : default
}
```

We need this if it's in a channel:

```swift
"aps" : {
    "category" : "MESSAGE"
    "alert" : {
        "body" : "ok",
        "title-loc-key" : "notification.messages.received.channel.title",
        "title-loc-args" : ["cardoso", "general"]
    },
    "badge" : 2
}
```

And this if it's a DM:

```swift
"aps" : {
    "category" : "MESSAGE"
    "alert" : {
        "body" : "ok",
        "title-loc-key" : "notification.messages.received.dm.title",
        "title-loc-args" : ["cardoso"]
    },
    "badge" : 2
}
```

If the user can't reply to this message (eg. muted or read-only channel)

```swift
"aps" : {
    "category" : "MESSAGE_NOREPLY"
    "alert" : {
        "body" : "ok",
        "title-loc-key" : "notification.messages.received.channel.title",
        "title-loc-args" : ["cardoso", "important"]
    },
    "badge" : 2
}
```

PS: Add other categories if available

Apple docs: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1

**Comment by cardoso** [comment]
Noticed we also don't show the server in the notification. We need that now that we support multiple servers in iOS :)

**Comment by sampaiodiego** [comment]
any way we can support both new and old apps? I mean, once we change the `alert` object, will it break non-updated apps (that does not support new `title` and `body` properties)?

**Comment by cardoso** [comment]
@sampaiodiego It can't break the App. These properties are handled by the operating system :)
