### ISSUE TITLE
Delete Users in Bulk

### ISSUE THREAD

**Issue by egroeg** [RocketChat/Rocket.Chat#8875]
### Description:

I want to delete all users at once.  How can this be achieved?

**Comment by phishticks** [comment]
There's already a "deleteUser" function; my guess you could loop through the list of all active users in the room and call the function for each of them. Where would you like it to be put though?

**Comment by egroeg** [comment]
Sorry, I actually ended up using RoboMongo and just multi-selected and deleted from the users collection.
