### ISSUE TITLE
Display all existing channels (as non-admin)

### ISSUE THREAD

**Issue by JeromeJ** [RocketChat/Rocket.Chat#8876]
### Description:

Unable to list all existing channels (without performing a partial search of the individual channel name).

### Server Setup Information:

* Version of Rocket.Chat Server: v59.3
* Operating System:  Debian GNU/Linux 8 (jessie)
* Deployment Method(snap/docker/tar/etc): custom
* Number of Running Instances:  1
* DB Replicaset Oplog: N/A
* Node Version: v4.8.6

### Steps to Reproduce:

N/A

### Expected behavior:

A way to display a list of all (non-private) existing channels.
(That doesn't require to be admin and go through the admin panel)

### Actual behavior:

Didn't find a way to display said list.

### Relevant logs:

N/A

**Comment by a321465** [comment]
Apparently this was done on purpose.  See https://github.com/RocketChat/Rocket.Chat/issues/8571

**Comment by karlprieb** [comment]
We're working on a new feature called Discovery.
It will be a page with all channels and filters :)

**Comment by matejdivecky** [comment]
Our team miss this feature a lot! Is there a possibility to put it back, untill Discovery will be implemented? Or is there any estimate when it could be?

**Comment by kenton-r** [comment]
Having a way to Discover channels with tags for organization would be good and needed for our situation.

**Comment by Eiken** [comment]
I get a lot of users complaining about this as well.

The Discovery page is nice but it lacks pagination so it only shows 10 channels at a time.

**Comment by ggazzo** [comment]
@JeromeJ I think its done :) feel free to open again if I'm wrong
