### ISSUE TITLE
APM level monitoring with newrelic

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#8879]
### Description:

I am struggling to make a APM level monitoring of rocketchat app with new relic . According to new relic documentation the steps to perform are :

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: MacOS
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 2
* DB Replicaset Oplog:
* Node Version: 4.8

### Steps to Reproduce:

Steps :

Inside the project directory run :
`npm install newrelic --save`

Add the depencdency inside the package.json file
“newrelic”: “^1.15.0”

Copy the newrelic.js file from the folder node_modules to the project main directory
`cp node_module/newrelic.js .`

Requre the newrelic inside app.js
`require(“newrelic");

I am stuck with step number 4 .` I am not sure where to require("newrelic")` in the rocketchat project directory .

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
