### ISSUE TITLE
Minify Live Chat files

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#8880]
Hi!

The files for /packages/rocketchat_livechat/assets/rocket-livechat.js and /packages/rocketchat_videobridge/client/public/external_api.js should really be minified for better performance; Google PageSpeed points it out as possible to compress.

**Comment by sampaiodiego** [comment]
Closing as duplicated of #8730 

@HammyHavoc please can you give more details at that issue, thx
