### ISSUE TITLE
IM History API not working (both for username and roomId)

### ISSUE THREAD

**Issue by alexandrejuma** [RocketChat/Rocket.Chat#8887]
### Description:

IM History API not working (both for username and roomId)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Linux RHEL 3.10.0-693.5.2.el7.x86_64
* Deployment Method(snap/docker/tar/etc): yum
* Number of Running Instances: 1
* DB Replicaset Oplog: N/A
* Node Version: v4.8.4

### Steps to Reproduce:

1) Create channel
2) Post some messages
3) Try to fetch them with im.history API

### Expected behavior:

The API should work and retrieve the messages, but it always throws an error with both username and roomId.

### Actual behavior:

curl -H "X-Auth-Token: glvHGrVfGAD1XJFfx5wlGvhhSB2j8LMT4dKAhPKVHn_" -H "X-User-Id: FCoudumh5pQmhttp://localhost:3000/api/v1/channels.info?roomName=Incident_394121
{
  "channel": {
    "name": "Incident_394121",
    "fname": "Incident_394121",
    "t": "c",
    "msgs": 7,
    "u": {
      "_id": "FCoudumh5pQmx5WnL",
      "username": "alexandre.juma"
    },
    "customFields": {},
    "ts": "2017-11-16T15:29:22.219Z",
    "ro": false,
    "sysMes": true,
    "_updatedAt": "2017-11-16T22:00:03.939Z",
    "_id": "ARmZnKRWGbHGiueAR",
    "username": "outrouser",
    "lm": "2017-11-16T22:00:03.930Z",
    "usernames": [
      "outrouser",
      "alexandre.juma"
    ]
  },
  "success": true
}

curl -H "X-Auth-Token: glvHGrVfGAD1XJFfx5wlGvhhSB2j8LMT4dKAhPKVHn_" -H "X-User-Id: FCoudumh5pQmx5WnL" http://localhost:3000/api/v1/im.history?roomId=ARmZnKRWGbHGiueAR
{
  "success": false,
  "error": "[invalid-channel]",
  "errorType": "invalid-channel"
}

curl -H "X-Auth-Token: glvHGrVfGAD1XJFfx5wlGvhhSB2j8LMT4dKAhPKVHn_" -H "X-User-Id: FCoudumh5pQmx5WnL" http://localhost:3000/api/v1/im.history?username=alexandre.juma
{
  "success": false,
  "error": "Invalid user [error-invalid-user]",
  "errorType": "error-invalid-user"
}

**Comment by alexandrejuma** [comment]
I'm sorry, I was trying to query history messages for a channel, not a IM. After using the correct API I got it working.

Example:

> curl -H "X-Auth-Token:wYsOEuJf7P7IiTg3ORhetb7mqf8VrzBj61U1LpsfPSI_" -H "X-User-Id: FCoudumh5pQmx5WnL" http://localhost:3000/apiv1/channels.history?roomName=general\&unreads=true

**Comment by graywolf336** [comment]
Thanks for following up.
