### ISSUE TITLE
[Bug] Long room announcement cut off

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#8888]
### Description:

When creating a long or multi-line announcement, it's not being displayed completely.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3

### Steps to Reproduce:

1. Create a very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very  very long text for the announcement
2. See it cut
![announcement cut off](https://user-images.githubusercontent.com/17176678/32935645-524de22a-cb71-11e7-81ad-17b406b279e9.png)

**Comment by rodrigok** [comment]
Needs to fix for mobile where we don't have tooltip option
