### ISSUE TITLE
Text selection with Shift+(up or down) behaves oddly

### ISSUE THREAD

**Issue by zarvox** [RocketChat/Rocket.Chat#889]
When editing text in the "Message" field, sometimes I want to delete some or all of a message.

Since I'm on a laptop without a convenient way to type home or end, I usually use Shift+Up Arrow or Shift+Down Arrow to select and delete the text I want to highlight.

Instead of highlighting the text in the `<textarea>`, Rocket.Chat begins history editing when Up and Down are pressed, even if Shift is held.

**Comment by marceloschmidt** [comment]
Just a note: this is osx specific... linux does not have that behavior.
