### ISSUE TITLE
Group/Channel API : addUser is needed 

### ISSUE THREAD

**Issue by phuyem** [RocketChat/Rocket.Chat#8890]
Your API is amazingly good, I have been really enjoying integrating with it. But I think we need **addUser** function. 

Also, addRoomLeader  , addRoomModerator, addRoomOwner could be merged into 1 function addRoomUser ( userId, roles ).

I am on my way to doing it myself, just post here for discussion. I will add the source here  once I have finished it

**Comment by madguy02** [comment]
hi, @phuyem  i wanted to know more about the function addUser. How do you require it? Or are you talking about https://rocket.chat/docs/developer-guides/rest-api#groups ( here we have invite option) but yeah there is no option to add roomleader and roommoderator.

**Comment by graywolf336** [comment]
There is currently an endpoint to add users, it's called `*.invite`. We also have endpoints for `addOwner` and `addModerator`. https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/channels.js#L41
