### ISSUE TITLE
Number of conversations/channels/groups in UX isn't intuitive

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#8892]
On Discord, the numbers are on each channel/group/chat and indicate the number of unread messages. I think it would be best to display this instead of a number stating the number of conversations/channels/chats. This has me flicking through chats looking for unread messages regularly.

**Comment by engelgabriel** [comment]
I agree with @HammyHavoc 👍

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/16036
