### ISSUE TITLE
Integrating LiveChat with telegram

### ISSUE THREAD

**Issue by amonemian** [RocketChat/Rocket.Chat#8896]
Hi everybody.

I want to use a telegram bot in order to send my end users' comments in to the LiveChat Queue and vice versa?

**Comment by amonemian** [comment]
As @lindoelio labeled the issue as the "new feature", it seems that currently it is not available.
My question is, how can I change the "LiveChat" packages/libs to achieve my goal? which files from which sections should be effected?
Thanks.

**Comment by rsmartins78** [comment]
Up
