### ISSUE TITLE
error: snap "rocketchat-server" not found

### ISSUE THREAD

**Issue by tnonguyen** [RocketChat/Rocket.Chat#8898]
Hello to you all,

I'm trying to install rocketchat-server, but it seems I can't make it work on my VPS.

I've installed snap just fine. Now that I try to hint the command line : 
`sudo snap install rocketchat-server`
I get the following error message : 
`error: snap "rocketchat-server" not found`

Going through the web, nobody seems to get that error, so I'm a little confused as to what to do next. I was supposed to get a functionnal RocketChat Server within 30 seconds, but it's been hours and I can't seem to understand what is wrong.

What I'm trygin to accomplish :
- install RocketChat on my VPS
- my VPS is on Ubuntu 16.04.3 LTS
- if I run `uname -i` I get `aarch64`, sooo I'm guessing I have a 64 bits OS ? (the docs say 32 bit is not supported)
- by the way I'm testing rocketchat on a Scaleway server (a friend told me that it could be the problem, but well, i'm not knowledgeable enough)

Thank you for your answers (and sorry for my non native english)

**Comment by shionphan** [comment]
https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/
```
Ubuntu 16.04 LTS gives message “snap not found”, whats wrong?
Make sure you’re using x64 or amd64 (or armhf) images, especially on VPS or VMs. x86 is 32 bit and not supported.
```

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, since it's no Rocket.Chat bug. Probably related to you VPS provider or your architecture. I'll reopen if this turns out to be a general SNAP error by additional evidence.

Cheers
Thomas

**Comment by zofe** [comment]
@tnonguyen news about rocketchat snap on Scaleway vps?
