### ISSUE TITLE
Messages are not refreshed after coming back online

### ISSUE THREAD

**Issue by littlep13** [RocketChat/Rocket.Chat#8899]
### Description:

Messages are not refreshed correctly if your device went offline and come back online. This is tested on iOS 10.3.3 browser. I've done my own build of v0.59.3

### Server Setup Information:

* Version of Rocket.Chat Server: v0.59.3
* Operating System: Ubuntu14.04

### Steps to Reproduce:

1. Logon to Rocket.Chat from two devices, A and B
2. Open a channel on A
3. Set device A to Offline
4. The “Waiting for server connection, trying again in XX seconds” appears on screen
5. On B, from the same channel that A has opened, send some messages
6. On A, send some messages in Offline status.
7. Turn A back to online, and wait for the re-connection of the channel

### Expected behavior:

Messages (in the offline time window) from B should be shown on device A in proper sequence. 

### Actual behavior:

On device A, messages (in the offline time window) from B were not being populated, but on device B, the message from A (in the offline time window) would be shown. If you kill the Rocket.Chat session of A and restart, you will find the messages were populated correctly.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
