### ISSUE TITLE
Use named parameters in translations

### ISSUE THREAD

**Issue by ujuc** [RocketChat/Rocket.Chat#89]
hi

I translate `i18n/en.i18n.json` > `i18n/ko.i18n.json`.

1 problem..

this line `Room name changed to: <em>%s</em> by <em>%s</em>`
Korean translate is `방이름 변경 : <em>%s</em> 에서 <em>>%s</em>`

edit `<em>%s1</em> by <em>%s2</em>`.
Korean translate is `<em>%s2</em> 에서 <em>%s1</em>`

Thanks.

**Comment by engelgabriel** [comment]
Can you do a Pull Request?

**Comment by engelgabriel** [comment]
@marceloschmidt I think we have to use name parameters.

@ujuc Can you submit your file in a Pull Request so we can test it?

**Comment by ujuc** [comment]
@engelgabriel yes :smile:

**Comment by marceloschmidt** [comment]
I've started using named parameters for phrases that include more than one %s. I have already inserted the correct named parameters where you had put %s1 and %s2. Please update accordingly if needed. Thanks for your help!

**Comment by marceloschmidt** [comment]
PR ready to merge: https://github.com/RocketChat/Rocket.Chat/pull/98

**Comment by ujuc** [comment]
:+1:
