### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by r0b0t3k** [RocketChat/Rocket.Chat#8903]
### Description:

Description in file

### Server Setup Information:

* Version of Rocket.Chat Server:0.59.3
* Operating System:windows server 2008 r2
* Deployment Method(snap/docker/tar/etc): tAR
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:4.8.4

### Steps to Reproduce:

1. just installing

[npm-debug.log](https://github.com/RocketChat/Rocket.Chat/files/1487379/npm-debug.log)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Windows is none of our supported platforms. Please feel free, though, to ask the community in the [forums](https://forums.rocket.chat/c/community-support).

Cheers
Thomas
