### ISSUE TITLE
[API] users.logout or users.invalidateToken is necessary 

### ISSUE THREAD

**Issue by phuyem** [RocketChat/Rocket.Chat#8909]
We have the wonderful api "users.createToken" to use rocketchat "as some user".  I think we need to have "users.logout" or at least "users.invalidateToken". 

I know there is a built in RESTIVUS login/logout but it is not the right way (I think)

P/S : hope it is not a duplicate as I did the search before posting

**Comment by graywolf336** [comment]
I'm closing as the restivus logout is the right way to do it.

However, please explain why you don't think it is the correct way to do it and then based upon that answer we can determine whether it needs to be opened again.
