### ISSUE TITLE
Upgrade to the latest release

### ISSUE THREAD

**Issue by exagon** [RocketChat/Rocket.Chat#8911]
Hi to all,
I need some clarifications please.

I've installed RC 0.59.3 in Ubuntu with mongodb, but I read of some fixed issues and I need to uderstand how can I update to the latest release, because on the download page I see only the 0.59.3.

Someone can explaine me ?
Thanks in advance.
regards

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
