### ISSUE TITLE
No buttons to make channels defaults

### ISSUE THREAD

**Issue by crsCR** [RocketChat/Rocket.Chat#8918]
This was reported here and people tried to reopen - but not happened... https://github.com/RocketChat/Rocket.Chat/issues/7004

### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by MartinSchoeler** [comment]
Reopened #7004
