### ISSUE TITLE
Add recording voice chat feature

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#8926]
As requested per my [tweet](https://twitter.com/hammyhavoc/status/932740634380824576), I'm opening this issue as I would like to see the ability to record voice chats come to RocketChat; very useful for obvious reasons. :- )

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/9726

**Comment by HammyHavoc** [comment]
@rodrigok This is recording voice messages. My "voice chat" thing was more about recording calls.
