### ISSUE TITLE
BUG: Input field for chat not available after video call

### ISSUE THREAD

**Issue by dsokac** [RocketChat/Rocket.Chat#8927]
### Description:

After leaving the video call session without exiting the full screen mode, I can not reach the input field for chat and right bar si missing. When I resize the window the input field can be seen but still unreachable. I am using RocketChat win 10 application.

### Server Setup Information:

* Version of Rocket.Chat Server:2.10.1
* Operating System: debian 9 (stretch)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: MongoDB shell version: 3.2.17
* Node Version: v4.5.0

### Steps to Reproduce:

1. Start the video chat session
2. Open the full screen view
3. Stop the video session without changing the view (it should be full screen)

### Expected behavior:

The application should switch automatically from full screen view to original after the session is left.

### Actual behavior:

The application returned to its initial view with full screen mode still on. The text input field is gone and unreachable, and the right bar that normally apears is gone from the window.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
