### ISSUE TITLE
SAML based SSO is not working in Electron Desktop application

### ISSUE THREAD

**Issue by kajisaap** [RocketChat/Rocket.Chat#8943]
### Description:
We are trying to authenticate users of on-prem hosted RocketChat via Google G suite SSO and for that, we have successfully setup SAML configuration in both IDP(SAML apps under G suite) and RocketChat app(Under SAML in *Administration* control panel). We did all the required setup and the setup is working fine through browser. 

<img width="1034" alt="saml_login_cf" src="https://user-images.githubusercontent.com/722803/33222468-924bd896-d125-11e7-939a-59c9c4a297a0.png">

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu 16.04.3
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Yes
* Node Version: 

### Steps to Reproduce:
Not sure if it is happening to other IDPs. People, please chime in if you encounter this issue with other IDPs. 

### Expected behavior:
Since it is working via browser, it should also work with Desktop app.

### Actual behavior:
<img width="790" alt="screen shot 2017-11-24 at 2 24 35 pm" src="https://user-images.githubusercontent.com/722803/33222456-77ed629e-d125-11e7-9e47-7d02de840416.png">

**Comment by pierre-lehnen-rc** [comment]
This issue was left here for two years without attention, but SAML is working on the electron app these days, so I'm going to close it.
