### ISSUE TITLE
can't change room settings in admin panel, no save button present

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8944]
### Description: https://gyazo.com/53328f9fdb6aa44559f62f7ec6413188

This is a big issue. Right when I gotta do a migration I cannot chose which channels uses auto join! I remember from using earlier versions this was possible. I need to do a migration and this feature really needs to work for me to proceed. The save button appears gone. I think this is a CSS issue but the button element isn't even present in the html structure. 

### Server Setup Information:

Version of Rocket.Chat Server: 0.59.3
--

Operating System: Ubuntu 4.4.0-101-generic
Deployment Method(snap/docker/tar/etc):snap
Number of Running Instances: 1
DB Replicaset Oplog:
Node Version: v4.8.4
--

### Steps to Reproduce:

1. 
2. 
3.

**Comment by indiadamjones** [comment]
User bump here.  Thanks maxpen for mentioning this bug, glad I looked for it before posting.  I got a private conversation that I can't delete.  I can't change the room to private.  Had this functionality in the previous version, please HALP!!!  Thank you RocketChat team.

**Comment by indiadamjones** [comment]
Found it!  The CSS visibility property looks set to hidden!  Change this rule:
.flex-tab .channel-settings .button {visibility:visible;} <--

**Comment by geekgonecrazy** [comment]
please update to 0.59.6 where this has been fixed.

**Comment by maxpen** [comment]
@geekgonecrazy when I do sudo snap refresh rocketchat-server
I get there is no update available, what to do? I can't upgrade to 0.59.6
