### ISSUE TITLE
[mobile] Start recording video message button is not visible

### ISSUE THREAD

**Issue by cyberb** [RocketChat/Rocket.Chat#8949]
Before fix:
<img src="https://user-images.githubusercontent.com/885528/33235632-d43bb2bc-d233-11e7-90b5-d525d6594bae.png" width="400" />

After fix:
<img src="https://user-images.githubusercontent.com/885528/33235641-06dcafe6-d234-11e7-9b21-965866e53450.png" width="400" />

To fix:
Replace css:
````
right: 66px;
````
with
````
max-width: calc(100% - 66px);
````
Version: 0.59.3

**Comment by cyberb** [comment]
I was not able to find this in source (just a browser hack) to create a pull request.
If anyone can point me at source css, I could to a PR.

**Comment by maxpen** [comment]
@cyberb do you also got the issue you can't set which channels are default? SEe my issue #8944

**Comment by cyberb** [comment]
@maxpen I am new to rocket chat, so I do know what are you talking about. I would keep this issue to the specific problem I have mentioned. If you are experiencing mobile view specific problem I would ask you to publish a screenshot of the problem to your issue so it is easy to see what is wrong. I am personally interested in helping mobile view issues as I am using mobile phone 99% of my time.

**Comment by maxpen** [comment]
@cyberb my bad. I've mailed you.
