### ISSUE TITLE
Bug: Broken layout for macOS when toggled server list

### ISSUE THREAD

**Issue by JannikZed** [RocketChat/Rocket.Chat#8951]
### Description:

The layout for the macOS client has a broken layout with Rocket.chat server version 0.59.3: 
<img width="607" alt="bildschirmfoto 2017-11-26 um 17 09 23" src="https://user-images.githubusercontent.com/7526174/33241933-23d3d824-d2cd-11e7-8578-8083c127830f.png">

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: macOS 10.13.1
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

On macOS click VIEW -> toggle server list

The view looks perfect with opened server list: 
<img width="504" alt="bildschirmfoto 2017-11-26 um 17 19 29" src="https://user-images.githubusercontent.com/7526174/33241978-018c9200-d2ce-11e7-86f0-065718cb70f2.png">

**Comment by MartinSchoeler** [comment]
Please reopen this issue [here](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!

**Comment by JannikZed** [comment]
thanks, you are right!
