### ISSUE TITLE
Error: EPERM: operation not permitted, unlink while tryna build google-vision package in windows 10 64bit

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#8952]
### Description:
while tryna build rocket.chat in windows 10 64bit  using meteor npm start i get error 

C:\Users\user\AppData\Local\.meteor\packages\tap_i18n\1.8.2\plugin.tap-i18n-compiler.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
      ^
Error: EPERM: operation not permitted, unlink 'C:\Users\user\Desktop\Rocket.Chat\packages\rocketchat-google-vision\.npm\package-new-1mfqu7f.7h7i\node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@0.59.3 start: `meteor npm i && meteor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@0.59.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Server Setup Information:

* Version of Rocket.Chat Server: 0 59.3
* Operating System: Windows 10 
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:yes
* Node Version: 4.8.4

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
