### ISSUE TITLE
Links with anchors break badly

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#8954]
@reitzig commented on [Mon Nov 27 2017](https://github.com/RocketChat/Rocket.Chat.Electron/issues/616)

## My Setup
- Operating System: Ubuntu 16.04
- App Version: 2.9.0
- Server Version: 0.57.3

- [ ] I have tested with the latest version
	(Latest version not available as installer/package.)
- [X] I can simulate the issue easily

## Description

Inserting a link with anchor label results in broken HTML in both web and desktop client.

### Current Behavior

I see `#crypto" target="_blank" rel="noopener noreferrer">https://developer.android.com/preview/api-overview.html#crypto`.

![2017-11-27_01](https://user-images.githubusercontent.com/4246780/33257260-d5a5f18a-d355-11e7-8404-ac1692f3e30b.png)

### Expected Behavior
See the equivalent of `[https://developer.android.com/preview/api-overview.html#crypto](https://developer.android.com/preview/api-overview.html#crypto)`.

**Comment by reitzig** [comment]
Reproduced with server version 0.59.3.
