### ISSUE TITLE
 LiveChat: Include website url in email sent when agents are offline

### ISSUE THREAD

**Issue by valentincollado** [RocketChat/Rocket.Chat#8961]
### Description:

In the email sent with the form (name, email, message) when agents are offline, It would be interesting to include the url of the website from which it was generated.  In this way companies with several websites (stores, restaurants, hotels,...) could know for which site information is requested.

**Comment by valentincollado** [comment]
![image](https://user-images.githubusercontent.com/8128340/33571409-311ab82c-d930-11e7-8cd0-edc6890a1292.png)

**Comment by Avalarion** [comment]
We'd also like to have this feature!
