### ISSUE TITLE
Cannot disable emojis

### ISSUE THREAD

**Issue by dariosusman** [RocketChat/Rocket.Chat#8964]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Linux (AWS)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.5.0 - x64

### Steps to Reproduce:

1. Go to "My Account", Preferences
2. Switch "Use Emojis" to False.
3. Click "Save Changes".
4. Reload or just close the "My account" tab/window.

### Expected behavior:

Typing ':S' must NOT be translated to raise the emoji selection window... or any emoji for that matter when disabled..
Also, the setting does not appear to get really saved. 
![gkrellshoot_2017-11-28_134539](https://user-images.githubusercontent.com/20441763/33332230-79114404-d442-11e7-94bb-12130acdaa9f.jpg)

### Actual behavior:

Asks to select an emoji and automatically selects one upon hitting enter. Have to hit escape before hitting enter to avoid the emoji.

### Relevant logs:
Logs don't show anything out of the ordinary. Even on debug mode.

**Comment by dariosusman** [comment]
From the debug log:
0|main     | rocketchat_logger rocketchat_logger.js:375 Meteor ➔ method saveUserPreferences -> userId: TBTRyscyHuDcoQNW2 , arguments:  { '0': 
0|main     |    { newRoomNotification: 'door',
0|main     |      newMessageNotification: 'chime',
**0|main     |      useEmojis: '0',**
0|main     |      convertAsciiEmoji: '1',
0|main     |      saveMobileBandwidth: '1',
0|main     |      collapseMediaByDefault: '0',
0|main     |      viewMode: 0,
0|main     |      hideUsernames: '0',
0|main     |      hideRoles: '0',
0|main     |      hideFlexTab: '0',
0|main     |      hideAvatars: '0',
0|main     |      mergeChannels: '-1',
0|main     |      sendOnEnter: 'normal',
0|main     |      roomsListExhibitionMode: 'category',
0|main     |      autoImageLoad: '1',
0|main     |      emailNotificationMode: 'disabled',
0|main     |      highlights: [ 'dsusman', 'dario', 'Dario' ],
0|main     |      desktopNotificationDuration: '',
0|main     |      desktopNotifications: 'default',
0|main     |      mobileNotifications: 'default',
0|main     |      unreadAlert: '1',
0|main     |      notificationsSoundVolume: 100 } }


Reloading the channel or page shows it to be back on/true.

**Comment by graywolf336** [comment]
`convertAsciiEmoji` what effect does that have?
