### ISSUE TITLE
Owner cannot set self as leader or moderator

### ISSUE THREAD

**Issue by smullow** [RocketChat/Rocket.Chat#8965]
In a recent discussion in our Chat community, it came to our attention that owners of channels cannot set themselves as moderators or leaders of a channel. The discussion was initiated by a question about the difference between the three roles, and the mention that a leader's avatar, status and "chat now" option can be displayed at the top of a room, which many people find a desirable capability (that's how it was discovered that owners of a channel cannot change their own roles). 
Also in the discussion, it came up that even though an owner is not supposed to be able to leave a channel or group without designating someone else as an owner, it actually happened to one user, so now there is an ownerless group that he can't join unless he is invited.
Since the presumption is an owner cannot change his or her role so there will be no accidental abandonment of channels, that actually has happened, and in the meantime, owners of channels who would like to take advantage of the leader function cannot.
Unless we are missing something obvious! 
Thank you!

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by geekgonecrazy** [comment]
This will be fixed by: #8411

**Comment by localguru** [comment]
see #8388 : owner of a read only channel can't permission to post to own user.

**Comment by geekgonecrazy** [comment]
This one is only a matter of the option not visibly being available.  Sounds like the other one may be deeper.  So related by not likely the same.
