### ISSUE TITLE
Rate limiting for message sending

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#897]
Right now you could send as many messages as you want as fast as you want, and the server just has to take it. 

We need to rate limit.  Maybe configurable incase people want to be able to have a bot spam really quickly

**Comment by AdrianoCahete** [comment]
> configurable 

:+1: 

Something like irc, maybe? Lines per second.
More than this, server just ignore and send a notice for the user.

**Comment by Sing-Li** [comment]
We might not have the time luxury to just rate-limit message sending.

Rate limiting needs to be core of every single server-side method, directly or indirectly invokable by client.  Rate limiting criterion may also vary per API.

This is another use-case for an interpreted policy system on top of our permissions and roles. For instance:

* _adminstrators can change avatar at any time, as frequently as desired_

* _regular users can change avatar no more than once every 5 minutes_

DoS damages imparted on truly reactive systems may be amplified by the scalability of the system :disappointed:

**Comment by marceloschmidt** [comment]
Started working on this: https://github.com/RocketChat/Rocket.Chat/commit/b97231b45b4aa67d40de179baa94e6358451a553

Any ideas on how to improve this? Maybe adding toggles on settings? @RocketChat/owners

**Comment by marceloschmidt** [comment]
I agree with what somebody said in another issue. Too many settings will clutter everything and make it hard for any sysadmin to manage their instance. Do you think we should just stipulate our own limits?

**Comment by sampaiodiego** [comment]
I don't think a lot of settings are that bad. 
maybe we could make a clean settings page with the most important/common settings and another tab/menu with "advanced settings" with a **lot of settings**..

**Comment by marceloschmidt** [comment]
Whatever the case is, we definitely need a new settings page. Current layout is not user-friendly.

**Comment by sampaiodiego** [comment]
agreed!

2015-10-08 0:02 GMT-03:00 Marcelo Schmidt <notifications@github.com>:

> Whatever the case is, we definitely need a new settings page. Current
> layout is not user-friendly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/897#issuecomment-146404219>
> .
>



-- 
.Diego Sampaio

**Comment by Hostile** [comment]
So we are year later. Was that sorted?

**Comment by geekgonecrazy** [comment]
@Hostile we've enforced a limit.  I can' remember what it is exactly, but its not configurable at the moment. 

@marceloschmidt can you recall?  I think this is the only reason this ticket remains open?

cc @RocketChat/core

**Comment by engelgabriel** [comment]
@marceloschmidt why was this part commented?

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/sendMessage.coffee#L44

Was it because of the import and slack bridge packages were calling the methods rather than the functions before? Can we uncomment this?

**Comment by engelgabriel** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/commit/1c312aff5ea851cf43f790d17275c05ce50f2c00

**Comment by geekgonecrazy** [comment]
👍 

@Hostile so limit right now is:  `5 msgs/second`

**Comment by AdrianoCahete** [comment]
> limit right now is: 5 msgs/second

User is notified when reach this limit?

**Comment by rodrigok** [comment]
@lorek123 it is, unless the user is a bot or admin
