### ISSUE TITLE
iOS push notification does not work

### ISSUE THREAD

**Issue by annguyen-iosdev** [RocketChat/Rocket.Chat#8971]
Hello guys, 
Due to your last support and docs, I config the web admin site and iOS app for pushing notification.
The first start looks good. But the last step, I did not receive the message on phone. Help me check pls.
----- (1) Web admin config
<img width="1119" alt="screen shot 2017-11-29 at 6 27 28 pm" src="https://user-images.githubusercontent.com/16201598/33373271-b7b0b5ea-d533-11e7-8d86-58b4c76f0016.png">
----- (2) Successfully connect and send device token
<img width="431" alt="screen shot 2017-11-29 at 6 33 21 pm" src="https://user-images.githubusercontent.com/16201598/33373307-dfc1c060-d533-11e7-89ae-90b13fc9acbd.png">
------(3) Test pushing message from admin site
<img width="947" alt="screen shot 2017-11-29 at 6 28 29 pm" src="https://user-images.githubusercontent.com/16201598/33373335-fbebf74c-d533-11e7-9b1f-4f10c5afe4b5.png">
--- (4) BUT, did not have any message on device (closed / opend status)
Thanks
p/s: I test that token and certificate on https://pushtry.com/ and it works
Related to https://github.com/RocketChat/Rocket.Chat/issues/2431

**Comment by toantt** [comment]
My team has the same issue! Please help me!

**Comment by hoanganh200870** [comment]
I'm in the same situation. I tried to put keys on admin site but it still doesn't work. It's hard to know the right way. Anyone can help?

**Comment by annguyen-iosdev** [comment]
the notification in the app works now. the config with Push on admin site should be passed all text in the .pem file.It looks like:
`Bag Attributes
    friendlyName: 
...
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----`
and
`Bag Attributes
    friendlyName:
...
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----`
Thanks.

**Comment by vaibhavmane** [comment]
# **its working issue in certificates create certificate properly** and change server side gateway 
you can check your notification on pushtry.com/
if it working fine then your certificates work properly otherwise **issue** in server side 


The binary interface of the production environment is available through
 gateway.push.apple.com:2195;
 the binary interface of the development environment is available through
 gateway.sandbox.push.apple.com:2195

**Comment by vaibhavmane** [comment]
and at the admin side copy as it is certificate and key (whole certificate not a key only).

**Comment by 44online98** [comment]
Hi @all
I'm fork new project from Rocket.Chat.iOS. I want to setup Push Notification on env Production. 
I need to disable  *Debug*, disable  *Gateway*, enable *Production* and
pass all text in the .pem to *APN Key*, *APN Cert*, *APN Dev Key*, *APN Dev Cert*, is it right?
