### ISSUE TITLE
Searching for Wikipedia contributors 

### ISSUE THREAD

**Issue by SeanPackham** [RocketChat/Rocket.Chat#8976]
Hi Rocket.Chat Community, the Rocket.Chat team would love to see Rocket.Chat have a well written, neutral and strongly sourced Wikipedia article. The core team is too close to the subject to ethically be authors and therefore we need an experienced Wikipedia contributor to publish an article and be available during the approval process.

I have written an [example draft](https://docs.google.com/document/d/1tJ8cjVKo30-__vXH14on1-bT01jHRT1365osBUYPlec/edit?usp=sharing), feel free to use as much of as you want. The document also contains a link to a previously rejected article and a list of sources with summaries.

Ideally the first version should be as short as possible to minimize the approval time. Once published it can then serve as a foundation for others to build upon.

**Comment by engelgabriel** [comment]
Lets use our newsletter for this.
