### ISSUE TITLE
Twitter URLs don't display properly

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#8977]
When posting a link to a tweet it is not displayed nicely. The image is not parsed and only a white twitter bird is where the image from the tweet should be.

Server Version: 0.59.3

To reproduce just send a message with a twitter link: https://twitter.com/i/web/status/935872556501995522

**Comment by satyapramodh** [comment]
i made a fix by preferring ogImage (open graph image) if available over the normal image for links that render via oembedUrlWidget. Please review and give your suggestions! @MartinSchoeler 
thanks
