### ISSUE TITLE
Cannot login to Live Chat with existing user

### ISSUE THREAD

**Issue by alexloiko** [RocketChat/Rocket.Chat#8978]
Cannot login to Live Chat with existing user
### Description:

As a 3rd-party site owner I want to login RocketChat user to integrated Live Chat pop-up.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.8.4

### Steps to Reproduce:

For now live chat window became logged-in if there exists logged-in RocketChat portal in some other tab (it means Meteor local storage properties are set and available for Live Chat)

Its valuable to have ability to login with some approach (cookie token, js method call, local storage or some other way to integrate with livechat) and track user chat with helpdesk knowing that user is already registered one.

For now we try to login calling /api/v1/login and putting token and userid to local storage (for us "Meteor.loginToken:/:/chat" and "Meteor.userId:/:/chat" corresponding)
But live chat removes tokens after page reload (even if we set "Meteor.loginTokenExpires:/:/chat" by hands)

### Expected behavior:

Somehow login existing RocketChat user to Live Chat to have ability to define registered site user as RocketChat user.

### Actual behavior:

There is no documented ability to login existing user to Live Chat

**Comment by sampaiodiego** [comment]
since #9048 was merged, livechat users/visitors are no longer rocket.chat regular users, this means they will not be logged in if they open the main chat. is that something what you want? or do you want to call some API on livechat widget to "pre-register" the visitor if you already knows who he is?

**Comment by tryelse** [comment]
@sampaiodiego Thank you for the answer.
For now we are looking for functionality to track livechat users as regular ones (to keep their history, to know who is writing to support) but as I understand it was decided to separate livechat and regular ones :(
One of solutions we found is to put main chat window to iframe, same sized as livechat. But in such a way we lose livechat functionality (queues, agents, departments, offline hours, etc)
We want to use rocket.chat for internal portal, where authorized users are able to write to support (also authorized users).
How to do that with rocket.chat?

**Comment by sampaiodiego** [comment]
@tryelse you can already look at past livechats of a visitor on a tab panel on the right.

if you have a way to identify a visitor from outside rocket.chat you can use then [custom fields](https://rocket.chat/docs/developer-guides/livechat-api/#-set-custom-field-) .. custom fields information will be available on the "info panel" of a livechat session.

I guess this covers your needs.

**Comment by misli** [comment]
> since #9048 was merged, livechat users/visitors are no longer rocket.chat regular users, this means they will not be logged in if they open the main chat. is that something what you want? or do you want to call some API on livechat widget to "pre-register" the visitor if you already knows who he is?

And how can I "pre-register" the already known visitor?

**Comment by sampaiodiego** [comment]
please look at `Register visitor` section: https://rocket.chat/docs/developer-guides/livechat-api/#register-visitor
