### ISSUE TITLE
Console error while authenticating via the Wordpress method (oAuth)

### ISSUE THREAD

**Issue by nonsintetic** [RocketChat/Rocket.Chat#898]
While authenticating via Wordpress this error pops up in the console and the UI shows an Error 502 preventing login.

W20150925-20:13:42.745(0) (oauth_server.js:398) Error in OAuth Server: Cannot read property 'error' of null
I20150925-20:13:42.979(0)? Exception while invoking method 'login' TypeError: Cannot read property 'error' of null
I20150925-20:13:42.979(0)?     at CustomOAuth.getAccessToken (packages/rocketchat:custom-oauth/custom_oauth_server.coffee:72:19)
I20150925-20:13:42.980(0)?     at Object.handleOauthRequest (packages/rocketchat:custom-oauth/custom_oauth_server.coffee:94:23)
I20150925-20:13:42.980(0)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
I20150925-20:13:42.980(0)?     at middleware (packages/oauth/oauth_server.js:173:1)
I20150925-20:13:42.980(0)?     at packages/oauth/oauth_server.js:146:1

**Comment by rodrigok** [comment]
This issue was solved?

**Comment by nonsintetic** [comment]
yes, it was my wordpress site blocking the /oauth/ folder with a password, so that's why that error popped up. You can still handle it so it doesn't error out, but it works as intended otherwise. thank you :)
