### ISSUE TITLE
Rocket Chat: No releases for windows server currently available for Windows server 2012 R2

### ISSUE THREAD

**Issue by ZipherAloha** [RocketChat/Rocket.Chat#8986]
Hi everyone,

I have question to ask about Rocket chat installer for Windows server 2012 R2.
I'm follow step to setup windows server 2012 R2 for Rocket chat. But when at topic "Rocket.Chat files" I go download Rocket chat app via link **https://rocket.chat/docs/installation/manual-installation/windows-server/releases**, the page show "No releases for windows server currently available". Anyone know how to download Rocket.Chat files for windows server 2012 R2? 

Thank you.

**Comment by cy4n** [comment]
https://rocket.chat/docs/installation/manual-installation/windows-server

**Comment by graywolf336** [comment]
@ZipherAloha where did you find that link at? This way we can get the link updated to the one @cy4n posted above

**Comment by ZipherAloha** [comment]
@cy4n @graywolf336 Thank you for your help. Refer to @cy4n posted link above, at topic "Rocket.Chat files". Step 1. Download the latest Rocket.Chat Windows Release from **the Rocket.Chat releases page**. After click link (as below pic), then the next page show "No releases for windows server currently available". This is why I cannot download Rocket Chat files.

 ![image](https://user-images.githubusercontent.com/34153617/33533851-4ae1d6c8-d8d6-11e7-976c-1ea47aac398a.png)

![image](https://user-images.githubusercontent.com/34153617/33534091-01b35d3a-d8d8-11e7-8526-f70635d0caa6.png)

Thank you.

**Comment by HammyHavoc** [comment]
Lack of mobile support is irritating.

**Comment by JmMa** [comment]
me too,Why now "No releases for windows server currently available".

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as the policy has now been adopted to not officially support Windows server setups. If anybody feels the urge to contribute a [community-supported guide](https://rocket.chat/docs/installation/community-supported-installation/): feel free :)

Cheers
Thomas
