### ISSUE TITLE
@mentions, @all broken since 0.59.3

### ISSUE THREAD

**Issue by Flauschbaellchen** [RocketChat/Rocket.Chat#8988]
### Description:

@mentions and @all highlights are boken since update to 0.59.3

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3, 0.59.4
* Operating System: Linux Debian 8
* Deployment Method(snap/docker/tar/etc): tar bundle
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 4.5.0 - x64

### Steps to Reproduce:

1. Try to @mention someone or try to highlight all users with @all
2. The selection popups is shown but after hitting enter the mention is just normal text and no highlight is sent to other users.

### Expected behavior:
@someone should highlight "someone" and @all should highlight all users currently present within the channel

### Actual behavior:
Nothing happens. The @-mention is interpreted as normal text

### Relevant logs:
No log output regarding warnings or errors.

**Comment by TwizzyDizzy** [comment]
Hi there,

I just tried to reproduce your issue and **cannot** confirm this behaviour. I'm on 0.59.4 and @mentions work as expected.

You might wanna add additional information (e.g. browser version) to help other to further debug this.

Cheers
Thomas

**Comment by Flauschbaellchen** [comment]
Hi Thomas :)

I'm using Firefox Version 57.0 on Ubuntu 16.06.3. Same error on Chromium 62.0.3202.94.
@-mentions on open.rocket.chat are working as expected with the same browsers.

Loading the history from a channel does not show older @-mentions as highlights but as normal text, too.

Node packages:
```
root@rocketchat:/home/rocketchat/rocket-chat-0.59.4/programs/server# npm list
meteor-dev-bundle@0.0.0 /home/rocketchat/rocket-chat-0.59.4/programs/server
├── amdefine@1.0.1
├── ansi-regex@0.2.1
├── ansi-styles@1.1.0
├── asap@2.0.6
├── chalk@0.5.1
├── core-util-is@1.0.2
├── duplexer2@0.1.4
├── escape-string-regexp@1.0.5
├── fibers@1.0.15
├── has-ansi@0.1.0
├── inherits@2.0.3
├── isarray@1.0.0
├── meteor-promise@0.8.5
├── multipipe@1.0.2
├── UNMET DEPENDENCY node-gyp@3.6.0
├── UNMET DEPENDENCY node-pre-gyp@0.6.34
├── object-assign@4.1.1
├── process-nextick-args@1.0.7
├── promise@8.0.1
├── readable-stream@2.3.3
├── safe-buffer@5.1.1
├── semver@5.3.0
├── source-map@0.1.32
├── source-map-support@0.3.2
├── split2@2.1.1
├── string_decoder@1.0.3
├── strip-ansi@0.3.0
├── supports-color@0.2.0
├── through2@2.0.3
├── underscore@1.5.2
├── util-deprecate@1.0.2
└── xtend@4.0.1

npm ERR! missing: node-gyp@3.6.0, required by meteor-dev-bundle@0.0.0
npm ERR! missing: node-pre-gyp@0.6.34, required by meteor-dev-bundle@0.0.0
```

```
root@rocketchat:/home/rocketchat/rocket-chat-0.59.4/programs/server# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/home/rocketchat/rocket-chat-0.59.4/programs/server)```

**Comment by cy4n** [comment]
works for me too on 0.59.3
![screen shot 2017-12-01 at 15 15 52](https://user-images.githubusercontent.com/1135762/33486504-9a6e81ec-d6aa-11e7-934b-62e1cfa2c5dc.png)

**Comment by sampaiodiego** [comment]
@Flauschbaellchen is it vanilla rocket.chat or have you modified it somehow? do you have any custom CSS? you might want to inspect the element and see what CSS is overwriting the default (and working) one

**Comment by Flauschbaellchen** [comment]
It's a vanilla installation downloaded from `https://download.rocket.chat/build/rocket.chat-0.59.4.tgz` without any modifications.

After the `npm install` I'm starting the server with:
```
export ROOT_URL=https://chat.example.com # this is not the real domain, of course :)
export PORT=80 # nginx proxy with 80 -> 443 and SSL-certs
export MONGO_URL=mongodb://localhost:27017/rocketchat

cd /home/rocketchat/rocket-chat-0.59.4 && node main.js
```

The HTML inspection shows the following:
```HTML
<div class="body color-primary-font-color " dir="auto" data-unread-text="Unread Messages">
  @user <span class="copyonly">*</span><strong>this is a test</strong><span class="copyonly">*</span>
</div>
```
Thus the a-link is missing like
```HTML
<a class="mention-link " data-username="user" title="">@user</a>
```
instead of old plain @user

**Comment by sampaiodiego** [comment]
I'm assuming `@user` in your test is valid username.. is it right?

I did the same test as you described and this is what I got:
![image](https://user-images.githubusercontent.com/8591547/33488488-e9ee7424-d697-11e7-82e0-77ecaec11747.png)

this is the expected behavior

**Comment by Flauschbaellchen** [comment]
Yes, this is a valid user... maybe the server just thinks that this is an invalid one? Maybe a database corruption after the update?
Is there a way I can check this (e.g. login to the database and query the list of users available within a channel?)
However, even @all does not work and this is not a valid "user".

Further tests:
1. I mentioned an user currently available within a channel.
2. User does not get a notification
3. User left the channel
4. When clicking on the username the profile on the right side still says "remove from room" (maybe another bug?)
5. User rejoins the channel
6. I retry to @-mention him, but still no notifications

**Comment by Flauschbaellchen** [comment]
Retested it with the new packaged 0.59.6 stable release downloaded from the webpage.
However, no changes so far as it has been wrongly packaged and includes the 0.59.4 release.

**Comment by archang3l-media** [comment]
@Flauschbaellchen We had the same problem with our rocketchat installation but some option in /admin/General Subsection UTF8 fixed it... What are your Settings there?

**Comment by Flauschbaellchen** [comment]
@archang3l-media wow, thanks, that was the right hint.
The setting has been changed to "[^\u0000-\u007F]+" while upgrading from 0.59.2 to 0.59.3.
I reset it back to the default value "[0-9a-zA-Z-_.]+" and now the highlighting is working again.

Thanks for the help and support!
