### ISSUE TITLE
https://download.rocket.chat/stable gives me 0.95.3 not 0.95.6

### ISSUE THREAD

**Issue by hniemann** [RocketChat/Rocket.Chat#8990]
https://download.rocket.chat/stable gives me 0.95.3 not 0.95.6

**Comment by sampaiodiego** [comment]
we moved to the old URL.. where did you find this one? so we can fix it the right one which is https://releases.rocket.chat/latest/download/ thx

**Comment by nikaro** [comment]
This is the URL sets in the Ansible Galaxy role.

@hniemann to make it work you can override with these variables:
```
rocket_chat_tarball_remote: https://releases.rocket.chat/latest/download
rocket_chat_tarball_sha256sum: e04e534b135f06ef580c7e3c50a2e46b68786c88be0770e47c5ae27e5dab5c06
```
