### ISSUE TITLE
Accessing through Proxy doesn't allow changing of Avatars

### ISSUE THREAD

**Issue by pettitto** [RocketChat/Rocket.Chat#8992]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.53.0
* Operating System: Stretch
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: N/A
* Node Version: N/A

### Steps to Reproduce:

1. Click "My Account"
2. Click "Profile"
3. See "Loading suggestions" which hangs for 30 seconds or so

### Expected behavior:

Have ability to turn suggestions off as behind a proxy it might not work

### Actual behavior:

Loading suggestions makes you wait unnecessarily to change the avatar

**Comment by compuguy** [comment]
This also applies if you have RocketChat on a network with no internet access (or heavily restricted).

**Comment by AmShaegar13** [comment]
This one is crucial. Our instance has no internet access but uploading avatars from local should still be possible.

**Comment by pitops** [comment]
Loading suggestions takes too long to load which makes the user believe that the system is broken hence why i was searching github issues for it and alas here is an issue for it.

It would be greatly appreciated if you can fix/ or have the option to toggle off suggestions.

**Comment by Flanoir** [comment]
+1

**Comment by AmShaegar13** [comment]
@MartinSchoeler what do you think, shouldn't this be labelled bug? This is blocking users on isolated Rocket.Chat instances.

**Comment by sharenz** [comment]
+1

**Comment by AmShaegar13** [comment]
I created #9978 to address this problem. Personally, I don't need to configure suggestions. I think, there are too many confusing options already.

#9978 changes that default options are displayed always and suggestions are just shown when available.
