### ISSUE TITLE
How to make a bi-directional communication between a client and a server In Rest API 

### ISSUE THREAD

**Issue by iruthaya** [RocketChat/Rocket.Chat#8997]
### Description:

 I am using the REST API to integrating with my existing ionic mobile application. my application requirement is direct message only. REST API call's are working as expected, but how to make a bi-directional communication between a client and a server like web socket. Does it support socket.io ?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 14.04.5 LTS
* Deployment Method: Docker

Please any one help me on this.

Thanks in Advance 
Arun Iruthaya Thomas J

**Comment by antgel** [comment]
Closing, GitHub issue tracker is for bug reports and feature requests. Please go [here](https://rocket.chat/docs/getting-support) for support options.

**Comment by graywolf336** [comment]
For future reference, please check the real time api: https://rocket.chat/docs/developer-guides/realtime-api/

**Comment by iruthaya** [comment]
@graywolf336  Thanks for your valuable reply..
