### ISSUE TITLE
Build URL broken

### ISSUE THREAD

**Issue by hypery2k** [RocketChat/Rocket.Chat#8998]
### Description:

Since 0.59.6 the build download URL is not working

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Debian 9
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: 4.8.4

### Steps to Reproduce:

1. Go to https://download.rocket.chat/build/rocket.chat-0.59.6.tgz

### Expected behavior:

Download the tgz ;)

### Actual behavior:

4.0.4

### Relevant logs:
-

**Comment by gramakri** [comment]
It seems 0.59.5 is not working as well. 0.59.4 works.

**Comment by k0nsl** [comment]
Thanks for confirming. I thought I was going batty for a moment when trying to pull `0.59.6` and it would say it did so, but that was not the case -- it never pulled it and I am stuck on `0.59.4`.

**Comment by geekgonecrazy** [comment]
Link fixed.  If it gives you problems can also access directly here: https://s3.amazonaws.com/download.rocket.chat/build/rocket.chat-0.59.6.tgz

Basically what happened is... 0.59.4 was cut.  We had some issues with our CI... two additional tags were created... but really the only release was 0.59.4 :) 

0.59.4 0.59.5 0.59.6 are all the same release.
