### ISSUE TITLE
Report abuse - removed?

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#8999]
### Description:
When translating Rocket.Chat, I found some items related to "report abuse". However, I didn't find it in the message menu.
Has this feature been removed recently?

### Server Setup Information:

* Version of Rocket.Chat Server: develop (0.60)

**Comment by karlprieb** [comment]
This feature exist only on Cordova iOS client, in the future this feature will be global.

**Comment by mrsimpson** [comment]
Now that’s why I call “mobile first” Scnr 😈

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #3514. If you do not agree, please get back to me :)

Cheers
Thomas
