### ISSUE TITLE
"Welcome Messages" should be grouped in a single line

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#90]
It is very annoying the way it works now.. but mainly because there are so many people entering out demo server.

**Comment by engelgabriel** [comment]
![screen shot 2015-06-01 at 11 43 28](https://cloud.githubusercontent.com/assets/1000217/7915375/8a9387c2-0853-11e5-9aea-5c8ac652d0e4.png)

**Comment by rodrigok** [comment]
Group messages is a good ideia too.
![captura de tela 2015-06-01 as 12 32 48](https://cloud.githubusercontent.com/assets/234261/7916453/5527ff76-085a-11e5-93b3-aac363b28c95.png)

**Comment by engelgabriel** [comment]
100% Agreed!

konecty*Gabriel Engel*Co-founder and CEOskype: gabriel_engel

gabriel.engel@konecty.com

+55 51 98089422 <+555198089422>

+55 51 30855151 <+555130855151>

www.konecty.com
