### ISSUE TITLE
Premium Chat

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#900]
Have an option to add a premium chat room would be great, add payment system (stripe, visa, etc) would be great value added.  admin and chat owners can customize and add this option.. 
##

**Comment by AdrianoCahete** [comment]
Option to release some usergroups with X, Y and Z permissions for Premium users would be good too.

**Comment by shtefcs** [comment]
And what would premium chat room do ?

**Comment by IQ2022** [comment]
if you have sales, or if you an expert, people can book paid appointment with you and have a chat or discussion, slide show, demo, phone call you name it.. that's what a premium room means.  You want more idea's contact me :)

**Comment by shtefcs** [comment]
Nice ideas, like I could provide SEO consulting to clients. Room can track time spend on it and charge ^^.

Nice idea :+1:

**Comment by IQ2022** [comment]
:smile: there are more..

**Comment by ninja-** [comment]
I think the best implementation of this would be via creating invites for users that paid. But you need to consider that all channels are currently public etc. so you wouldn't want that exposed to your clients...

**Comment by IQ2022** [comment]
we also can have a few public chat rooms for your current work/team/support,just to talk in general or just to build traffic. . if you needed to sell courses/webinars/have an expert advise, scheduling an appointment etc.. all  that will be at a premium and you can add features per minute, hour/ month/year etc.. you can either have this from within the chat room (right panel) - book appointment>pay> enter a room, or from login page have an option to pay for new rooms..

**Comment by ninja-** [comment]
ok I think that the internal api is more suitable to this than I expected(so no need for bots), you can start by looking at the livechat module which to me still looks like magic :)

**Comment by IQ2022** [comment]
just thought of this, perhaps use the first page when first login into the Rocket chat, to have hyper link into channels (and payment option on those channels) -

**Comment by bitalias** [comment]
Integrate Bitcoin. Would be awesome!

**Comment by IQ2022** [comment]
or instead of bitcoins, have people buy time slots :) (tokens) to chat or book a session..

**Comment by shtefcs** [comment]
@IQ2022 for that

**Comment by graywolf336** [comment]
*(These are my personal thoughts which don't reflect the entire team)*

With permissions, this shouldn't be too hard to do now.

`<random-personal-thoughts>`Although there comes into play the fact that it'd be nice for the developer who implements this to get some compensation since others will be making money off his/her development. But it is open source, so that's not expected. `</random-personal-thoughts>`

**Comment by IQ2022** [comment]
In home page of RC, when a user login can we add section for membership options?  

here is the api that can be used inside RC. https://stripe.com/docs/api

**Comment by jelenajjo** [comment]
Excited to see this

**Comment by designgurudotorg** [comment]
This thread has been running for quite some time... any developments people are aware of re: paid chat on rocketchat?

**Comment by hdavy2002** [comment]
wondering any updates on this

**Comment by geekgonecrazy** [comment]
I think a lot of people have managed to do this around integrating the login provider to handle payments and subscriptions.

We have a lot of different API's and such that can help facilitate this. 

Our Rocket.Chat App store will probably allow people to add in plugins to let other people make money.  But I don't think this is a goal of Rocket.Chat
