### ISSUE TITLE
Desktop: Red badge with dot ("."), when no new messages.

### ISSUE THREAD

**Issue by seriyvolk83** [RocketChat/Rocket.Chat#9001]
When there are no new messages the app icon shows red badge with a dot ("."). This is really confusing. It should not show badge at all.

**Comment by karlprieb** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #638](https://github.com/RocketChat/Rocket.Chat.Electron/issues/638) via [**ZenHub**](https://www.zenhub.com/)
