### ISSUE TITLE
Using a hash sign (#) as a bot trigger does not work

### ISSUE THREAD

**Issue by amenk** [RocketChat/Rocket.Chat#9002]
### Description:

We try to use the hash sign as a trigger. Currently we work around this by using `!#` as the trigger which is not that convenient.

We are aware, that this would also trigger when mentioning channel names, but we would filter those out by an regex. We are only interessted in numerical issue numbers.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.4

### Steps to Reproduce:

1. When defining the `#` as a trigger word in `/admin/integrations/outgoing/` and pressing save, we get a server error.

### Expected behavior:

It's allowed an works

### Actual behavior:

Sever error

### Relevant logs:

       Exception while invoking method 'updateOutgoingIntegration' TypeError: Cannot read property 'trim' of undefined   at Object._validateOutgoing [as validateOutgoing] (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_integrations.js:346:20)   at [object Object].Meteor.methods.updateOutgoingIntegration (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_integrations.js:2343:41)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_lib.js:1109:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:1857:12)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:903:20   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:902:47   at [object Object].EVp.withValue (packages/meteor.js:1134:15)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:901:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:874:21)   at /snap/rocketchat-server/1142/programs/server/packages/ddp-server.js:753:85

**Comment by graywolf336** [comment]
A better work around is to not have a trigger setup and filter every message inside of the script of your integration. Basically inside your integration make sure the message starts with `#2374` and if it doesn't then return false.

**Comment by amenk** [comment]
@graywolf336 Do you have an example?

**Comment by graywolf336** [comment]
Do you have a custom script running on your integration? If so, you would merge this into it:

```js
class Script {
   prepare_outgoing_request({ request }) {
     if (request.data.text && request.data.text.indexOf('#') !== 0) {
       return false;
     }
     
     return {
       message: {
         text: 'Hiya!'
       }
     };
   }
}
```

**Comment by amenk** [comment]
Thanks. No I use a webhook. Can I combine outgoing script and webhook?

**Comment by graywolf336** [comment]
Yes you could.
