### ISSUE TITLE
'The field Roles is required' error displays even when new user has a role set

### ISSUE THREAD

**Issue by peterdalydickson** [RocketChat/Rocket.Chat#9005]
### Description:

Issue title says it all!

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: MaOS 10.13.1
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Click to add a new user
2. Fill in all required fields
3. Untick 'Join default channels'
4. Click 'Save'

### Expected behavior:

New user is created

### Actual behavior:

<img width="462" alt="fullscreen_04_12_2017__09_45" src="https://user-images.githubusercontent.com/17453188/33546501-11ebb408-d8d9-11e7-9e40-d6dd5e8e1af2.png">

**Comment by karlprieb** [comment]
Hey @peterdalydickson you need to click on the ADD ROLE button before save :)

**Comment by peterdalydickson** [comment]
Realise that now!

Thanks.

**Comment by ulope** [comment]
That UX could use some work. Just ran into this as well.

**Comment by vynmera** [comment]
perhaps checkboxes, or a Discord-like roles [+]?
