### ISSUE TITLE
can ping rocketchat server but not get to webgui

### ISSUE THREAD

**Issue by balla2185** [RocketChat/Rocket.Chat#9008]
![image](https://user-images.githubusercontent.com/34148129/33570887-ef3dbf26-d8f3-11e7-807d-898dd6e7c57a.png)

any ideas? yes i have even put the port in on web so it reads 192.168.8.20:3000

**Comment by balla2185** [comment]
running nmap on that ip shows that port 3000 is not open not sure where to go from here

**Comment by localguru** [comment]
Connection on localhost:3000 possible? Firewall? More infos please.

**Comment by graywolf336** [comment]
Please ensure that the firewall on the server allows connections through port 3000.

I'm closing this as this is a setup issue and not an issue with Rocket.Chat itself. Feel free to continue the discussion and if we determine there is an issue with Rocket.Chat, we can open the issue back up.
