### ISSUE TITLE
"Update to release METEOR@1.2.0.1 is impossible"

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#901]
I was just about to get to bed when I ran into this problem. I'm on Debian 8 and running RC via the instructions for deploying a "development installation" (not via Docker).

Hope this makes some sense. I'm going to bed.

>root@myhost:/home/nodejs/Rocket.Chat# meteor update
>Update to release METEOR@1.2.0.1 is impossible:
>While reading package from `/home/nodejs/Rocket.Chat/packages/rocketchat-livechat`:
>package.js:42:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
>package.js:43:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
>package.js:44:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
>package.js:45:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.

>This project is at the latest release which is compatible with your current package constraints.
>=> Errors while upgrading packages:

>While reading package from `/home/nodejs/Rocket.Chat/packages/rocketchat-livechat`:
>package.js:42:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
>package.js:43:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
>package.js:44:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.
>package.js:45:6: The `isAsset` option to `addFiles` is deprecated. Use PackageAPI#addAssets instead.

**Comment by garg** [comment]
Look at this branch - https://github.com/RocketChat/Rocket.Chat/tree/meteor-1.2

**Comment by AdrianoCahete** [comment]
If i remember, RC master branch run on Meteor 1.1.

RC have another branch with 1.2 running, like @garg posted.

**Comment by marceloschmidt** [comment]
@k0nsl does using branch meteor-1.2 solves the problem?

**Comment by k0nsl** [comment]
Hi @marceloschmidt !

I have not tried using that branch, as I incidentally got my instance working one day ago and I haven't really messed around with it much since -- particularly as I have a bunch of active participants online every day.

I can fire up a copy of it somewhere else and test, of course. But for now my issue is solved and to be frank, it was very likely an issue created by myself while doing tasks when I was obviously too tired :P
Best wishes,
-k0nsl
