### ISSUE TITLE
Library included in server bundle contains insecure RPATH

### ISSUE THREAD

**Issue by antiphase** [RocketChat/Rocket.Chat#9010]
```
-bash-4.2$ objdump -x bundle/programs/server/npm/node_modules/meteor/emojione_emojione/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs | grep RPATH
  RPATH                /home/vagrant/phantomjs/src/qt/lib
```

0.59.4 as downloaded as "Latest stable"

**Comment by geekgonecrazy** [comment]
Can you provide more details?  Also maybe explain why this is an issue?

**Comment by antiphase** [comment]
RPATHs are runtime library loader paths. Sorry to Wikipedia you, but https://en.wikipedia.org/wiki/Rpath

The binary listed above (`bundle/programs/server/npm/node_modules/meteor/emojione_emojione/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs`) as included in the server bundle (`https://releases.rocket.chat/latest/download`) contains an RPATH which is outside of the distributed files, specifically `/home/vagrant/phantomjs/src/qt/lib`.

This is considered insecure because it may allow libraries to be dynamically loaded at runtime by a malicious user with write access to that RPATH.

I don't know if this is something you built or just acquired from elsewhere pre-built, but someone has accidentally included this path in their binary at build time, and it shouldn't be there.

**Comment by geekgonecrazy** [comment]
looks like its in phantomjs used by another library.  We can at least look into it to see if we can resolve it.

Thanks :)

**Comment by sampaiodiego** [comment]
we don't have phantomjs as dependency anymore so I'll be closing this
