### ISSUE TITLE
Enter to send broken with new modal

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9016]
### Description:
Caused by: #8882
If you paste a file into channel and then try to enter on new modal it doesn't send any more.

### Server Setup Information:
Current develop branch and develop server.

### Steps to Reproduce:

1. Copy Image
2. Ctrl + v in channel
3. Hit enter to send

### Expected behavior:
Send the file

### Actual behavior:
Nothing

**Comment by karlprieb** [comment]
Fixed on #9171
