### ISSUE TITLE
Iframe integration: Sending commands NOT WORKING

### ISSUE THREAD

**Issue by kiselevo** [RocketChat/Rocket.Chat#9019]
**iframe.contentWindow.postMessage("{ externalCommand: 'go', path: '/admin/General' }", '*');**

nothing happens

**IframeIntegration -> Enable Receive -> True**

still not working, any idea? Please help.

**Comment by rodrigok** [comment]
Can you paste here a screenshot of your iframe admin configuration?

**Comment by kiselevo** [comment]
Closing the issue. Valid code:

this.iframe.nativeElement.contentWindow.postMessage({
                externalCommand: 'login-with-token',
                token: token
 }, '*');

**Comment by anvlkv** [comment]
Hi, in docs it says `event: 'login-with-token'` and here it is `externalCommand`
Of course the one in the docs does nothing and this one works...
