### ISSUE TITLE
Public gateway privacy clarification

### ISSUE THREAD

**Issue by flaviovs** [RocketChat/Rocket.Chat#9027]
Can anyone elaborate a bit more about what travels through Rocket.Chat notification gateways?

I think that most people that self-host a RC server are interested in maintaining privacy control of the messages exchanged on them, and it is not clear what actually goes back and forth between self-hosted instances and the RC gateway WRT notifications.

More specifically, are message contents sent to RC servers upon notifications? What exactly goes **outside** a self-hosted installation and the connected clients?

Any insight will be appreciated.

p.s.: I can provide a PR to documentation explaining this, if desirable.

**Comment by rodrigok** [comment]
Hi @flaviovs 

The entire content of push notifications are sent to our gateway, over HTTPS, and afterwards send to Apple/Google, we do not store any information and we can't identify servers or users.

We store 2 things:
1. Metrics, only the count (number) of notifications sent to Apple and to Google to track if we need to scale
2. The device token (in memory) when Apple/Google reply with error to return `405` as HTTP status code to Rocket.Chat instances be able to delete invalid tokens, then we immediately delete that device token from memory

As you can see [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/lib/cordova.js#L76-L77) we send `token` and `options` to our gateway, where `options` are described [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/lib/PushNotification.js#L28-L41)

**Comment by flaviovs** [comment]
@rodrigok, thank you for the comprehensive response.

Quick question: do the settings under "Push" configuration ("Show channel/group/username in notification" and "Show message in notification") change anything WRT channel/user and message contents that are sent to the RC gateway, and Google/Apple afterwards?

**Comment by rodrigok** [comment]
@flaviovs Yes, since our mobile apps can't change the notifications before show up in the device's screen and since we don't touch the notification data on gateway step we need to omit that information before send to the gateway.

So, if you disable the `Show message in notification` and disable `Show channel/group/username in notification` our gateway will not receive that data.

**Comment by flaviovs** [comment]
That clears up my issue. Thank you very much
