### ISSUE TITLE
Log off a user by schedule

### ISSUE THREAD

**Issue by sttyru** [RocketChat/Rocket.Chat#9028]
### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System: 0.58.4
* Deployment Method(snap/docker/tar/etc): by tar
* Number of Running Instances:  1
* DB Replicaset Oplog: Disabled
* Node Version: v4.5.0

_i removed templates for describe of errors because my issue was not linked with an abnormal behaviour._
Can you tell me the way for enforce disconnecting a user by timeout of an idle (with a status 'away' or 'busy')? This measure is necessary because some careless users do not want to logout from the system at shared PCs after a workday. It's unsafe... Will i be able to implement of this procedure via command line and periodically by cron??

Thank you!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, since you can set the validity of the session in days in admin area. Also there somewhere is an issue to make it possible to not only use days, but hour or a smaller unit.

Cheers
Thomas
