### ISSUE TITLE
[Windows App:Rocket.Chat+]New avatar won't be applied in my own's pc.

### ISSUE THREAD

**Issue by T-Motodate** [RocketChat/Rocket.Chat#9030]
### Description:
At the windows app(the Rocket.Chat+).
New avatar, that uploaded in the "Avatar" pane in the my account section, won't be applied in my own's PC.
However, in the other PC's Rocket.Chat+, new avatar was applied.

### Server Setup Information:
*Rocket.Chat+ version ... 2.10.1. Howver, this issue occurred in ver 2.9.x

### Steps to Reproduce:
1. Moves to "My Acount" section.
2. Moves to "Avatar" Pane in the left side bar.
3. Selects the image file, and click upload button.
4. Appears the message that applied the new avatar in green box.
5. However, new avatar won't be applied in my own pc. The old avatar is still applied.
6. After application reload or current server reload, new avatar  won't be applied.

**Comment by MartinSchoeler** [comment]
@T-Motodate Does this happens only on the desktop app? If yes, please close this issue and open it here: https://github.com/RocketChat/Rocket.Chat.Electron Thanks!

**Comment by T-Motodate** [comment]
@MartinSchoeler Thank you for your reply.
Yes, and excuse me that I'd recognized this space includes the desktop app.
I close this issue, and open again there.
