### ISSUE TITLE
请问这样该如何解决

### ISSUE THREAD

**Issue by LiuSuY** [RocketChat/Rocket.Chat#9031]
![image](https://user-images.githubusercontent.com/25116549/33696533-a3d0c65e-db3d-11e7-99df-770155a64a8e.png)

**Comment by LiuSuY** [comment]
![image](https://user-images.githubusercontent.com/25116549/33697033-deb4ddb2-db3f-11e7-9dae-15645dd26f38.png)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
