### ISSUE TITLE
Using `PORT` is not a good idea

### ISSUE THREAD

**Issue by codemug** [RocketChat/Rocket.Chat#9033]
### Description:

Using the `PORT` environment variable for default rocket.chat port assignment is not a good idea. It can either lead to unexpected behavior or unintentional automation in certain scenarios such as deployment of rocket.chat docker container using an orchestration engine. I faced one issue when using DC/OS for deployment of a hybrid container that contains rocket.chat and another service being run through [supervisor](http://supervisord.org/).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: CentOS Linux release 7.4.1708
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* Node Version: 4.8.4

### Steps to Reproduce:

I created a docker image with two services, one of them is rocket.chat and another one being exposed at port 8088. The service lifecycle is managed through supervisor inside the container and the container is deployed though DC/OS with the following port mapping:

`    "portMappings": [
      {
        "containerPort": 8088,
        "hostPort": 8088,
        "protocol": "tcp",
       },
      {
        "containerPort": 3000,
        "hostPort": 3000,
        "protocol": "tcp",
       }
`

And ofcourse, I do provide the `PORT` environment variable:

`
"env": {
  "ROCKET_CHAT_URL": "http://0.0.0.0:3000",
  "PORT": "3000",
  "MONGO_URL": "mongo-endpoint"
}
`

### Expected behavior:

The rocket.chat server should initialize on `3000`

### Actual behavior:

It initializes on `8088`

### Relevant logs:
`
Will load cache for users
2 records load from users
Will load cache for rocketchat_room
1 records load from rocketchat_room
Will load cache for rocketchat_subscription
1 records load from rocketchat_subscription
Will load cache for rocketchat_settings
565 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
74 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
{"line":"145","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 104","time":{"$date":1512636025529},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Exception in callback of async function: Error: listen EADDRINUSE 0.0.0.0:8088
  at Object.exports._errnoException (util.js:907:11)
  at exports._exceptionWithHostPort (util.js:930:20)
  at Server._listen2 (net.js:1253:14)
  at listen (net.js:1289:10)
  at net.js:1398:9
  at nextTickCallbackWith3Args (node.js:522:9)
  at process._tickDomainCallback (node.js:469:17)

➔ System ➔ startup
➔ +-----------------------------------------------+
➔ |                 SERVER RUNNING                |
➔ +-----------------------------------------------+
➔ |                                               |
➔ |  Rocket.Chat Version: 0.59.3                  |
➔ |       NodeJS Version: 4.8.4 - x64             |
➔ |             Platform: linux                   |
➔ |         Process Port: 8088                    |
➔ |             Site URL: http://localhost:3000/  |
➔ |     ReplicaSet OpLog: Disabled                |
➔ |          Commit Hash: 21c4efa08a              |
➔ |        Commit Branch: HEAD                    |
➔ |                                               |
➔ +-----------------------------------------------+
`

### Reason: 

Doing a `env | grep 8088` yields:
`
PORT0=8088
PORTS=8088,3000
PORT_8088=8088
PORT=8088
`
The `PORT` variable is a very generic variable which can be used or overridden by other applications such as the orchestration engine DCOS in my case.

**Comment by codemug** [comment]
My workaround for now was to reassign the `PORT` in a bash script

**Comment by rodrigok** [comment]
@codemug that env variable `PORT` is handled by the framework MeteorJS, we don't have control over it. Please open an issue in their repository https://github.com/meteor/meteor/issues
