### ISSUE TITLE
Upload file is not working in Internet Explorer 11

### ISSUE THREAD

**Issue by fadanner** [RocketChat/Rocket.Chat#9036]
### Description:

When i try to upload a file or picture with Internet Explorer 11 (11.0.9600.18762 Update 11.0.45) the file upload doesn't work. The windows file selection dialogue shows up, but if I click open, nothing happens.
When i open the developer toolbar of IE11 it shows a Javascript error:

`e.remove() -> Object doesn't support property or method 'remove'`

Error even occurs on open.rocket.chat

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: Ubuntu Linux Kernel 4.4.0-89-generic
* Deployment Method: Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: activated
* Node Version: v4.8.4

### Steps to Reproduce:

1. Click the 'plus' to add a file
2. Choose computer
3. Select a file allowed for uploading
4. Press open
5. Error -> nothing happes or Javascript error

**Comment by fadanner** [comment]
Does anyone have an idea on this?

**Comment by mphslaats** [comment]
If you try uploading that same picture again. Does that work?? Because that is my issue: https://github.com/RocketChat/Rocket.Chat/issues/9154

**Comment by fadanner** [comment]
No, that does not work, neither with the same picture nor with another picture.
