### ISSUE TITLE
Trying to access chatMessages before data present

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9038]
### Description:
Occasionally you'll reload and you'll just get a white screen.  Some times it'll take several reloads before it loads the page.

Boils down to this:
```
[Error] TypeError: undefined is not an object (evaluating 'chatMessages[u.openedRoom].input')
	(anonymous function) 
```

Taking a look at: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-message/client/messageBox.js#L470

This makes sense.  Basically onRendered in this template is called before `chatMessages` has even been defined or populated.

Some times data loading is fast enough that this doesn't happen.  But when there is a slight delay the data isn't there in time.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0+

### Steps to Reproduce:

1. Put server under some load
2. Refresh like mad
3. Hope the condition hits.

### Expected behavior:

Should either wait for this data... or should at least verify there before trying to access it.

### Actual behavior:

Blank page

### Relevant logs:

```
[Error] TypeError: undefined is not an object (evaluating 'chatMessages[u.openedRoom].input')
	(anonymous function) (f79e342366a21ea0345d878e108dbcceb4008c06.js:245:54875)
```

**Comment by geekgonecrazy** [comment]
@ggazzo added you.  Looks like you were last in the area so might be most familiar :)

**Comment by GurjinderSingh** [comment]
+1 same problem 

```
Exception from Tracker recompute function: undefined
TypeError: e.getDate is not a function undefined
TypeError: chatMessages[u.openedRoom] is undefined
```

**Comment by bumbar1** [comment]
Occasionally still experiencing white pages (I suspect this race condition) in our office.

We're on 0.63.0 and have been having this issue since 0.62.x. Mainly happens on iphones and rarely on androids. We're using cordova apps since native ones don't (yet) support custom gitlab url auth.

**Comment by tassoevan** [comment]
@ggazzo Was it fixed?

**Comment by geekgonecrazy** [comment]
I haven't seen this any more.  Is there a PR or something that should be linked?
