### ISSUE TITLE
Anonymous Read Default Room instead of Homepage

### ISSUE THREAD

**Issue by madelung** [RocketChat/Rocket.Chat#9041]
Hello everyone!

I hope you can help me with the following topic:

From #6794, I would love to have the same option for anonymous readers as well instead of the homepage. Any advice on how to do it is truly appreciated.

Thanks.

**Comment by bsbits** [comment]
Any update on this feature ?

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
