### ISSUE TITLE
Custom oauth nested usernameField

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#9051]
### Description:

I'd like to setup Nextcloud as oAuth provider for RocketChat.
The json sent by Nextcloud on the identity path looks like this:
```
{"ocs":{"data":{"id":"myuserid"}}}
```

I tried `#{"ocs"."data"."id"}` in Username field but without success.

If I understand correctly the [current code](https://github.com/RocketChat/Rocket.Chat/blob/b44415903ff7c6ee76a67faafb584cfc7b3ea47a/packages/rocketchat-custom-oauth/server/custom_oauth_server.js#L263-L277) there is no way I can configure it right now.

Can you confirm me that please?
Once it is confirmed, I'll look into providing a PR to fix it.

Thanks!

**Comment by geekgonecrazy** [comment]
doesn't look that will work no matter how you slice it.  Honestly not sure what the #{ } support is supposed to even really accomplish.

```
test = {"ocs":{"data":{"id":"myuserid"}}}
username = `#{"ocs"."data"."id"}`.replace(/#{(.+?)}/g, function(match, field) {
 console.log(field)
	if (!test[field]) {
	    throw new Error("blah");
	}
	return test[field];
});
```

returns error.

I've used this solution before in the past: https://stackoverflow.com/a/22129960
```
Object.resolve = function(path, obj) {
    return path.split('.').reduce(function(prev, curr) {
        return prev ? prev[curr] : undefined
    }, obj || self)
}
```
would let you just use `ocs.data.id`

@sampaiodiego @rodrigok thoughts?
