### ISSUE TITLE
More subtle join/leave messages

### ISSUE THREAD

**Issue by joepie91** [RocketChat/Rocket.Chat#906]
A small UX proposal. Right now, the join/leave messages are taking up a _ton_ of space in the room, making it hard to follow conversation over a longer period of time.

My proposal would be to make join/leave messages into smaller, 'inline' messages instead, like this:

![selection_421](https://cloud.githubusercontent.com/assets/1663259/10117647/91cbecb6-645e-11e5-8b60-64986766597e.png)

This would make it easier to 'scan' over them while following a conversation. On multiple subsequent joins/leaves, they could be grouped together with less margin inbetween, like this:

![selection_422](https://cloud.githubusercontent.com/assets/1663259/10117674/5557a882-645f-11e5-86fc-36a7d2387120.png)

The exact spacing inbetween entries would be up for discussion of course, but as a general proposal. I think it'd really help to focus more on the conversation, rather than on room state.
##

**Comment by AdrianoCahete** [comment]
I like this idea. I just change timestamp to before the name.

**Comment by rwakida** [comment]
:+1:

**Comment by joepie91** [comment]
@AdrianoCahete That was what I had in mind at first, but my concern is that it makes it harder to 'scan' over the names in chat and find somebody in particular, as the nicknames for messages are at a different (horizontal) position than those for joins.

I'm not really sure which solution is better, or how much this would matter.

**Comment by Sing-Li** [comment]
Definitely an @rcaferati  UX issue. 

Perhaps even 'bubble burst animated away' after a minute, collapsing other message flows?  Kinda like some Vegas / Monte Carlo slot machines.

**Comment by nahtnam** [comment]
:+1:

**Comment by geekgonecrazy** [comment]
I think a very simliar style was proposed for /me

**Comment by nahtnam** [comment]
@geekgonecrazy IMO `/me` should remain how it is, because the user is pretty much typing a message.

**Comment by geekgonecrazy** [comment]
@nahtnam problem with that is its exactly the same as _ message _

IRC would be the inspiration :)  That's where it came from :)

**Comment by nahtnam** [comment]
?

**Comment by gmsecrieru** [comment]
Related to #661

**Comment by engelgabriel** [comment]
<img width="1342" alt="compressed reply message" src="https://user-images.githubusercontent.com/1000217/55685517-7f8f2a00-592d-11e9-8aa4-90575ec99654.png">

**Comment by engelgabriel** [comment]
you can see it working at https://threads-qa.rocket.chat
