### ISSUE TITLE
Users with the same emails are not added to the list of users.

### ISSUE THREAD

**Issue by Levainen** [RocketChat/Rocket.Chat#9060]
My Setup
- Operating System: ubuntu server 16.04
- App Version: 0.59.4
- Deployment Method: snap

Greetings.
At me in the company there are some departments. At each department one mail box which is registered in LDAP and some users.
Is it possible to untie the user's identification from the mail and only bind to the login?

Thank you in advance.

**Comment by SeanPackham** [comment]
Currently this is not supported, each user needs a unique email address.
