### ISSUE TITLE
User still online after logout using REST API /api/v1/logout

### ISSUE THREAD

**Issue by distlibs** [RocketChat/Rocket.Chat#9064]
### Description:

User still online after logout using REST API [/api/v1/logout](https://rocket.chat/docs/developer-guides/rest-api/authentication/logout/). Also websocket connection are killed. I did not have a problem before. Earlier statusConnection field in User collection was automatically setted to offline after some time. I think it's related to [#9047](https://github.com/RocketChat/Rocket.Chat/issues/9047). After [#9049](https://github.com/RocketChat/Rocket.Chat/pull/9049) pull request exception not thrown to console but problem related with user statusConnection still exist when using REST and Realtime APIs.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-develop (4d46831543)
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): git pull
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.8.1 - x64

**Comment by distlibs** [comment]
I think this issue come after this commit [Improve API login endpoint to be compatible with DDP](https://github.com/RocketChat/Rocket.Chat/commit/06ddcc267aa8a68aa64a25c9c7920ae0ba7a7a42) . UserPresence.activeLogs(); prints two connections for same user. After logout one connection killed and one still exist.

**Comment by VibhorCodecianGupta** [comment]
@distlibs I couldn't spot `UserPresence.activeLogs();`. Could you pin-point the exact location of the code? I am trying to understand the websocket process. Where is the socket being opened? It'd be great if you could just point it out :D

**Comment by distlibs** [comment]
`/home/adminas/dev/Rocket.Chat/packages/rocketchat-livechat/server/unclosedLivechats.js`
I added `UserPresence.activeLogs();` myself for user presence testing:

```
UserPresenceMonitor.onSetUserStatus((user, status/*, statusConnection*/) => {
   UserPresence.activeLogs();

   if (!monitorAgents) {
	return;
   }
   if (onlineAgents.exists(user._id)) {
	if (status === 'offline' || user.statusLivechat === 'not-available') {
		onlineAgents.remove(user._id, () => {
			runAgentLeaveAction(user._id);
		});
	}
   }
});
```
Now try to login with REST API /api/v1/login and then login with Realtime API using an authentication token returned by REST API.
`
