### ISSUE TITLE
Can't set user as owner / moderator for the channel

### ISSUE THREAD

**Issue by Kusmarius** [RocketChat/Rocket.Chat#9069]
According to documentation from:
https://rocket.chat/docs/user-guides/channel-actions/
user can do the following actions:
**Members List**
...
...
Set that user as owner of the channel;
Set that user as moderator of the channel;
...

However it's just a member list.
Even Role admin can't do the operations stated in the documentation. 
Simply there is no such option in Rocket chat version 0.59.4.

How can we set a owner / moderator on the channel?
Regards

**Comment by hartois** [comment]
1. Open Members list
2. Click on member:
![scr999](https://user-images.githubusercontent.com/11641656/33852181-8fe51d12-deca-11e7-9790-088826adada8.png)

**Comment by hartois** [comment]
I think that for a more understandable interface, need to add the "settings" icon or something like that.
It took me about 15 minutes to find these buttons))

**Comment by Kusmarius** [comment]
Well "click on user" opens a private chat in my case.
Simply there's no menu options like your screenshot nor any buttons.

@hartois 
Where did you found those buttons?
Thanks

**Comment by hartois** [comment]
![scr667](https://user-images.githubusercontent.com/11641656/33869295-001425b2-df19-11e7-9d78-7d1252dcb4a3.png)
![668](https://user-images.githubusercontent.com/11641656/33869299-05efbef6-df19-11e7-80f3-bdaef2088d33.png)

**Comment by Kusmarius** [comment]
@hartois 

That's exactly what im doing...however it opens a private chat window.
What could be wrong?

**Comment by rodrigok** [comment]
@Kusmarius Is your setting `Admin > Layout > User Interface > Click to Create Direct Message` enabled?

**Comment by Dartui** [comment]
@rodrigogs after disabling this option I am able to edit user permissions per channel. Everything works great, but buttons do not change their color and text after setting this permissions. If i click again I will get `error-user-already-owner` message

**Comment by Kusmarius** [comment]
@rodrigok 

You are right "Click to Create Direct Message" is True in my case.
This issue can be closed.
Thanks.
