### ISSUE TITLE
Rocket Chat turned on as soon as I leave my VPS

### ISSUE THREAD

**Issue by diogorocha18** [RocketChat/Rocket.Chat#9071]
Hi, 
Unfortunately I can not get Rocket Chat turned on as soon as I leave my VPS, can you help get some solution to ALWAYS stay connected?

greetings

**Comment by diogorocha18** [comment]
Im Resolver, ty xd

**Comment by Lemmmy** [comment]
Run it in a systemd service, snap, docker container, screen, tmux or pm2.
