### ISSUE TITLE
Allow replies on Windows 10 desktop notifications like Skype

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#9076]
Skype allows users to respond directly to a message's notification, it would be really nice if we could do this in RocketChat, it's disruptive opening and closing the window sometimes. :- )

**Comment by karlprieb** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #637](https://github.com/RocketChat/Rocket.Chat.Electron/issues/637) via [**ZenHub**](https://www.zenhub.com/)
