### ISSUE TITLE
Remove from the group in UI before leaving the group.

### ISSUE THREAD

**Issue by k4ni5h** [RocketChat/Rocket.Chat#9080]
### Description:
When solo owner leaves the group, group name removed from UI on warning prompt.

### Server Setup Information:
* Version of Rocket.Chat Server:
* Operating System:Arch Linux-64bit
* Deployment Method(snap/docker/tar/etc):snap

### Steps to Reproduce:
1. Create a group having more than 1 member with 1 owner.
2. If the owner tries to leave the group show a warning prompt "You are the last owner. Please set new owner before leaving the room" but at UI you leave the group.

### Expected behavior:
The group remains at UI.

### Actual behavior:
The group name is missing.

**Comment by kanishonpc** [comment]
I wants to work on this issue. Can I proceed?

**Comment by rafaelks** [comment]
This one duplicates #5358.

**Comment by karlprieb** [comment]
I'll close this issue as it is duplicated from #5358
