### ISSUE TITLE
Rocket.Chat not loaded in Safari browser on Windows.

### ISSUE THREAD

**Issue by rajan-goswami** [RocketChat/Rocket.Chat#9082]
### Description:

Running Rocket.Chat on Safari (version 5.1.7) not loading.
hitting https://open.rocket.chat/home not opening rocket.chat

### Server Setup Information:

* Version of Rocket.Chat Server: Unknown
* Operating System: Windows 10
* Deployment Method(snap/docker/tar/etc): None
* Number of Running Instances:  None
* DB Replicaset Oplog:  None
* Node Version: Default

### Steps to Reproduce:

1. Open https://open.rocket.chat/home in Safari. 

### Expected behavior:

It should load rocket.chat meteor app in browser.

### Actual behavior:

Rocket.Chat is not loaded and getting following error in console.

**SyntaxError: Unexpected token '='**

### Relevant logs:
SyntaxError: Unexpected token '='

**Comment by karlprieb** [comment]
Hey @rajan-goswami Safari for Windows is not updated since 2012 and we doesn't support this browser.

Thank you for you report!
