### ISSUE TITLE
Cannot create rooms in 0.60.0-rc.0 in Firefox 57

### ISSUE THREAD

**Issue by AmShaegar13** [RocketChat/Rocket.Chat#9086]
### Description:

Cannot create rooms anymore.

I am using Firefox 57.0.2 (64-bit) on Arch Linux.

I am aware of #9077 but I'm running 0.60.0-rc.0 and get no error in browser console nor server log. Also, this happens with Firefox only. Chromium can create channels and groups.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-rc.0
* Operating System: Debian 8.10
* Deployment Method(snap/docker/tar/etc): tar with pm2
* Number of Running Instances: 3
* DB Replicaset Oplog: yes
* Node Version: v8.8.1

### Steps to Reproduce:

1. Open Rocker.Chat in Firefox
2. Click on `+` to create a new room.
3. Try to create a new room (public or private).

### Expected behavior:

A new room (public or private) is created.

### Actual behavior:

Nothing happens if you were on `/home` before. If you where in a room before you are redirected to `/group/oldroomtitle?type=p&name=newroomtitle&users=`.

### Relevant logs:

No logs about this found. Neither in browser console nor server logs.

**Comment by TwizzyDizzy** [comment]
this is a dupe of: #9077

**Comment by AmShaegar13** [comment]
If so, I'm sorry. But I wasn't sure. I don't get a 

> channel link on leftside, 

Nothing happens in my case. Also, Chromium works just fine. Nvm, we'll find out ;)
