### ISSUE TITLE
Create a New Channel dialogue: no scrolling possible if window small

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#9090]
### Description:

If you have a very small browser window or a small screen and you try to add a new channel, then the situation might arise, where you want to create the "Create" button but cannot reach it, because you cannot scroll down.

Might also be present for other dialogues - haven't tested that.
I also haven't tested, whether this is also present in earlier versions or whether this has been introduced only with 0.60.0-rc.0.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-rc.0
* Operating System: Oracle Linux 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: -
* Node Version: 8.9.3

### Steps to Reproduce:

* Make your browser window small
* klick the "+" to create a new channel
* try to scroll down in the right area to reach the "Create" button in the form

### Expected behavior:

Scrollbar appears, scrolling is possible

### Actual behavior:

No scrolling possible, everything below lower bound of browser window is not accessible.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Closing this issue in favour of newly created #9093 that seems to handle UI bugs/regressions in 0.60.0-rcX.

**Comment by sampaiodiego** [comment]
Reopening since this was not fixed
