### ISSUE TITLE
UI bugs on 0.60 release

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9093]
small button
![image](https://user-images.githubusercontent.com/9200155/33900647-5a3c27a0-df56-11e7-86ad-213fd018f88c.png)

scroll on "Create a New Channel" page:
![image](https://user-images.githubusercontent.com/9200155/33900664-69fa00e0-df56-11e7-98e7-73a5bde3e4d0.png)

big icons on channel list:
![image](https://user-images.githubusercontent.com/9200155/33900675-7a92fbe6-df56-11e7-8b1c-df5c3dea37e1.png)

**Comment by TwizzyDizzy** [comment]
Hi there, @sampaiodiego 

the scrolling issue (see above or #9090) is not fixed.

Cheers
Thomas
