### ISSUE TITLE
[BUG] Upload REST API not honoring file size limit

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#9096]
@RocketChat/core 

/api/v1/rooms.upload/:rid added in #8947 

You can upload files of any size despite of the limit settings.
Tried with and without admin account.

**Comment by geekgonecrazy** [comment]
Need to check file size before we actually upload: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/rooms.js#L76
