### ISSUE TITLE
[Sandstorm] Uploads are improperly linked

### ISSUE THREAD

**Issue by pjamar** [RocketChat/Rocket.Chat#910]
After uploading an image the resultant link in the chatroom wouldn't point to the proper place.

Steps to reproduce:
 1. Install Sandstorm instance
 2. Open general chat channel
 3. Push the clip icon and select and image to upload
 4. Upload
 5. Once finished a link to localhost will appear "http://127.0.0.1:8000/ufs/rocketchat_uploads/DNcsdWrAXzCPutzpx.jpg"

Expected:
 Find a link that works. In my specific case I could see the image by using two URIs:
  - my_grain_uri/ufs/rocketchat_uploads/DNcsdWrAXzCPutzpx.jpg although with Sandstorm.io frame on it (not suitable for download)
  - long_id.myhostname.com/ufs/rocketchat_uploads/DNcsdWrAXzCPutzpx.jpg

**Comment by Sing-Li** [comment]
Thanks for the detailed report!   @pjamar

**Comment by Sing-Li** [comment]
This should be fixed in the current base code.   Need to verify after the next cut.

**Comment by engelgabriel** [comment]
Can anyone test the version from https://s3.amazonaws.com/rocketchatbuild/rocket.chat.latest.spk and let me know if it is fixed?

**Comment by Jan02** [comment]
@engelgabriel it stalls when creating a new grain

**Comment by engelgabriel** [comment]
Thanks @Jan02 I noticed it yesterday :( https://github.com/RocketChat/Rocket.Chat/issues/1496

**Comment by Sing-Li** [comment]
Verified fixed on v0.9.0 by several users. Closing.
