### ISSUE TITLE
[Wishlist/Feedback] Rocket.Chat in 2018 - on premise adoption

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#9100]
### Description:

The year's end is approaching and we as consumers of and contributors to Rocket.Chat are thinking where we'll be heading to in 2018.

Our setting: We're a small group inside a big company providing Rocket.Chat on premise as alternative to SaaS-Services. We currently serve about 2000 users in about 30 clients - and it will hopefully be much more soon. We act as kind-of reseller and get very immediate feedback from our colleagues - and this sets the stage.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60 + some own additions

### Steps to Reproduce:

1. optional: Fork RC
2. optional: Adapt it to your needs
3. Roll it out to your company

;)

### Expected behavior:
What was expected from our customers:
> "It should just work"

> "Like Slack"

> "Wherever I am I want to be able to participate"

> "we want to integrate it into our custom system"

> "No hassle"

### Actual behavior:
What our customers say
> "The apps just feel amateurish"

> "The web client is fine, the new UI looks much cleaner"

> "wordings and texts are inconsistent and make it feel unprofessional"

> "It's good to see continuous progress"

> "I am missing feature <reminder/standup bot/integration with oneDrive, ...>"

### My verdict
Rocket.Chat is truly an awesome tool with an incredible team, philosophy and community. You're almost "there" 🥇 

In order to really get kicking also in bigger enterprises (and to be a real competitor to the SaaS-offerings by Slack and alike), you need to fulfill the core interaction "send a message" just a tiny bit better:

* **Get as many capable developers in order to provide not amazing, but at least mature mobile apps** - because this is [where it sucks and matters](https://blog.intercom.com/where-do-you-suck-where-does-it-matter/)
* Get the Rocket.Chat-Apps infrastructure out of the door (#6890). This will allow community to improve the functional scope more easily and bring you in the position of running a platform business model.
* Show some progress by beautifying the UI - without changing too much in the backend in order to save effort
* Continue to integrate PRs from the community for features of which the community is sure it needs them in the core product.
* **Forget about all further technical enhancements** (refactorings, new technologies or platforms) - you're good enough on that

@engelgabriel I thought of writing this on open.rocket.chat instead of on Github, but finally decided for the latter: I'd wish others to participate on these thoughts. If you consider it inappropriate, close it.

@community: Are you also running RC on premise? What's your experience?

**Comment by jszaszvari** [comment]
> Get the Rocket.Chat-Apps infrastructure out of the door (#6890). This will allow community to improve the functional scope more easily and bring you in the position of running a platform business model.

Could not agree more. The mobile apps and this feature should be the core focus as that’s where every other competitor is bounds ahead at the moment. 

What surprises me is that more noise has not been made about features like slacks interactive messages which allow end to end workflows to be completed in the chat. That’s the sort of stuff that the big adopters are after.

**Comment by jszaszvari** [comment]
I came across this a long time ago , I think it’s from a presentation that @engelgabriel  did a long time ago, and it was exactly the direction that things needed to be heading In ![6c5cf199-c2b3-4a35-a12c-3e4e85b48568](https://user-images.githubusercontent.com/872463/33934434-fd50a500-e04c-11e7-8b04-bc642215f9e5.png)

It feels like it’s been left to one guy on the side, who’s doing an amazing job by the way @graywolf336 to make this sort of thing a reality. There neeeds to be a ecosystem, not just a app.

**Comment by kkumaresan** [comment]
Hi, we at Mongrov have developed a react-native mobile client library for Rocket.Chat. Please check this url: https://github.com/mongrov/roverz . Works both on iOS and Android. If you get a chance, do check this project for a comprehensive native mobile app using Rocket.Chat. We welcome your feedback 🙂

**Comment by geekgonecrazy** [comment]
@mrsimpson thanks for posting this.  :smile: discussions seem to get lost here on our issue tracker.  

We've recently started making better use of our forum.  Others from the community have started making use of it to deliver feedback: https://forums.rocket.chat/t/the-good-the-bad-and-the-ugly-my-personal-assessment-of-the-rocket-chat-github-state/264

Rocket.Chat Apps are extremely important to us.  They are a key part of our plans going forward.  The ability to modify and extend with out having to fork is very important to us.

We're closing out as many of these discussion tickets as possible in favor of the forum.  Going to go ahead and close this one.  Please feel free to hit me up if you need help moving over.  I think some of your feedback is addressed in that linked forum post. 

Thanks!
