### ISSUE TITLE
Sub domains in chat 

### ISSUE THREAD

**Issue by diogorocha18** [RocketChat/Rocket.Chat#9103]
Good afternoon,

I would like to know if it was possible to create systems of private groups like Slack, test.rocket.chat being chosen from the beginning the sub domain desired by each one, each having full control over that created sub domain chat or something similar.

Thanks for replay..

**Comment by diogorocha18** [comment]
Upup, can help my pls?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  Believe it has been asked and answered elsewhere.  

Summary: yes, We do this and provision instances for each sub domain
