### ISSUE TITLE
SAML error on IE11 - No matching login attempt (credentialToken undefined)

### ISSUE THREAD

**Issue by codyx** [RocketChat/Rocket.Chat#9104]
_First thing first, it actually works on Chrome so the SAML setup is properly configured._

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.6
* Operating System: linux x64 4.13.0-17-generic
* Deployment Method(snap/docker/tar/etc): docker+ansible
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9.0

### Steps to Reproduce:

1. Launch IE11
2. Go the Rocket.Chat homepage
3. Click on the SAML login button

### Expected behavior:

Be successfully authenticated and redirected to the chatroom.

### Actual behavior:

"No matching login error" SAML error thrown (here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-accounts-saml/saml_server.js#L101)  
It also shows a popup on which it is written 'Verified'.

### Relevant logs:
Server log: SAML loginResult => { actionName: 'validate',   serviceName: 'sg-rocketchat',   credentialToken: undefined } 

![screen-saml-error](https://user-images.githubusercontent.com/9106507/33934695-f842fd18-dff9-11e7-9a81-97eb50e5dc5c.png)

**Comment by pierre-lehnen-rc** [comment]
Fixed by #15836
