### ISSUE TITLE
Rocket-Chat Livechat bad request received

### ISSUE THREAD

**Issue by amonemian** [RocketChat/Rocket.Chat#9105]
I am trying to connect to my rocket-chat server by Java Stomp Websocket client. but at the begining, after receiveing "o" and "server_id : 0", I receive "msg: error, reason: Bad request" from server. 

Would you please help me on this issue?

Thanks in advance,

**Comment by amonemian** [comment]
As I mentioned in [issue#8896,](https://github.com/RocketChat/Rocket.Chat/issues/8896) I am trying to link livechat and telegram together. The current issue is based on that issue.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
