### ISSUE TITLE
email notifications on DM even when disabled

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#9112]
I had a complaint from a user who told me email notifications for direct mentions were being sent despite it being disabled in profile.  I checked mongo, and here's what's in the database:

{ "_id" : "...", <snip> 
"emails" : [ { "address" : "REDACTED", "verified" : true } ], 
 "settings" : { "preferences" : { <snip> "emailNotificationMode" : "disabled",  <snip> }, 
 <snip> }

Looks like something is ignoring that preference.

**Comment by TwizzyDizzy** [comment]
Hi @sinteur,

This might a duplicate of #8568

Also: please be kind and adhere to the issue template ([the text you removed when opening this bug](https://github.com/RocketChat/Rocket.Chat/issues/new)) in order to help friendly community members to help you more effectively. :)

**Comment by karlprieb** [comment]
Hey @sinteur witch Rocket.Chat version are you using? I can't reproduce this error on `develop` branch.

**Comment by sinteur** [comment]
It's been happening since early .56 versions, and still happens on 0.59.6. Note that it's not happening with ALL users. I'm not ruling out a database corruption of some sort, so if there's specific queries you'd like to see the results of let me know

**Comment by gabrielloberg** [comment]
Still an issue on 0.62.1

**Comment by DmitryApollonov** [comment]
Still an issue on 0.62.2

**Comment by gdelavald** [comment]
This one seems very tricky to reproduce.
@DmitryApollonov @gabrielloberg @mddvul22 @sinteur any other details that could help us tracking down the issue?
User preference and room settings in which they were mentioned that triggered the email would help a lot, please report here if you have that information. Thanks!

**Comment by sinteur** [comment]
I'm on 0.64.1 at the moment, I'll upgrade soon. I'll keep an eye out for you

**Comment by ggazzo** [comment]
thanks :)

**Comment by sinteur** [comment]
(runningn 0.65.1 now)

**Comment by ggazzo** [comment]
we are facing some problems with notifications in general (fixed here #11024), but just for emails ... we will test again... :)

**Comment by mddvul22** [comment]
We are currently running version 0.65.1.  I have users who have disabled offline notifications.  (Looking in the mongo database, I see the following for their account:

"emailNotificationMode" : "nothing"

Yet, they are getting email notifications.  But this doesn't happen for every user.  If I disable email notifications for my own account, the setting works.  So, it is only happening to some of our users.

**Comment by gabriellsh** [comment]
Tested 3.0.0-develop, seems fixed. In any case please reopen this issue.
