### ISSUE TITLE
How to send direct message in Rochet Chat using REST Api? 

### ISSUE THREAD

**Issue by freyderBard** [RocketChat/Rocket.Chat#9113]
I work with codeigniter. And i try to build own chat in my project using REST APi of Rochet Chat. But I don't know how to send private message or create direct room. In documentation this topic doesn't exist.If you know ansver help me. Thanks.

**Comment by MartinSchoeler** [comment]
You can find the documentation on the direct message api [here](https://rocket.chat/docs/developer-guides/rest-api/im/)

**Comment by filippotoso** [comment]
This should be reopened.

Nowhere in the linked direct message api documentation is specified HOW to send a message to a direct message session.

Here's a list of the documented APIs:

- /api/v1/im.close
- /api/v1/im.create
- /api/v1/im.history
- /api/v1/im.files
- /api/v1/im.messages.others
- /api/v1/im.list
- /api/v1/im.list.everyone
- /api/v1/im.open
- /api/v1/im.setTopic

None of this sends a message.

**Comment by newincpp** [comment]
I'm sorry to re-open this but /api/v1/chat.postMessage is for channel only.  I couldn't found any /api/v1/im.postMessage or equivalent for im/dm in the documentation. if it does exist ?
or maybe I should use chat.postMessage ? If yes the "channel" is set as requiered but im dot have any so what should I do ?

**Comment by juliomac** [comment]
Yes you can. Just testes and worked with this:

          curl -H "X-Auth-Token: TAKE-YOUR-TOKEN-FROM-YOUR-LOGIN-JSON" \
          -H "X-User-Id: YOUR-USER-ID" \
          -H "Content-type:application/json" \
          http://URL-OF-YOUR-ROCKET-CHAT/api/v1/chat.postMessage \
          -d '{ "channel": "@NAME-OF-USER-TO-RECEIVE-DM", "text": "This is a direct message!" }'

In channel, just replace #CHANNEL for @USERNAME
