### ISSUE TITLE
Question: snap 0.59.6 says it is 0.59.4, latest tgz supplies 0.59.3

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#9114]
Can someone please explain the current version?

- snap 0.59.6 says it is 0.59.4,
- latest tgz supplies 0.59.3 

It's early in the morning. sip coffee. 
I meant: When is the curl to the latest tgz supplying 0.59.4/0.59.6 . Sorry.

**Comment by maxdwit** [comment]
Today 3. January 2018:

Snap is at 0.60.2
stable download link supplies 0.59.3
curl -L https://download.rocket.chat/stable -o rocket.chat.tgz  is at 0.59.3
Develop Download is at 0.60
 curl -L https://download.rocket.chat/develop -o rocket.chat.tgz

Isn't the download/stable Link for the tgz not updated when new releases for snapd are made?

**Comment by geekgonecrazy** [comment]
This should be resolved.  CLosing
