### ISSUE TITLE
failed when gradle is syncing

### ISSUE THREAD

**Issue by mey5am** [RocketChat/Rocket.Chat#9116]
every time imprt the source to android studio 3.0 show this error
Error:Project :xabber declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :xabber:MemorizingTrustManager.

**Comment by mey5am** [comment]
![untitled5](https://user-images.githubusercontent.com/34536128/33984190-fb00fc80-e0cb-11e7-848b-fb69f11f6ba5.png)

**Comment by mey5am** [comment]
just Explanation me very very simple

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
