### ISSUE TITLE
Channel creation is broken on develop branch (particular case)

### ISSUE THREAD

**Issue by gnidorah** [RocketChat/Rocket.Chat#9117]
### Description:

On develop branch channel creation fails with "No private group with name "test3" was found!" for admin with login e.g. "admin" after someone registers named after him e.g. "admin2".

### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System: Linux, Chrome
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

$ cd /tmp
$ git clone https://github.com/RocketChat/Rocket.Chat
$ cd Rocket.Chat
$ git branch
develop
$ git rev-parse HEAD
33e27197e0853bc567a3894b62105f7e00b9ecaa
$ meteor npm start

1. Say admin name is "admin"
2. Register a new user for e.g. via admin panel and use "admin2" as value for login
3. Now admin can't create new channels, until he deletes "admin2" user
### Expected behavior:

It should work like the previous time I've checked out (rev 820cccd7a3df2eab2ecf0ca03c352539ec634b1b)

### Actual behavior:

there is an error now "No private group with name "test3" was found!"

**Comment by rodrigok** [comment]
@gnidorah Can you test using our latest commit?

**Comment by gnidorah** [comment]
@rodrigok Unfortunately no change. This particular issue (still) only happens when second user is registered in the system. Once I delete the second user, I'm able to create new rooms again. I've not yet tested what happens if there are more than 2 users registered in the system.

**Comment by gnidorah** [comment]
@rodrigok Unfortunately no change. This particular issue (still) only happens when second user is registered in the system. Once I delete the second user, I'm able to create new rooms again. I've not yet tested what happens if there are more than 2 users registered in the system.

**Comment by gnidorah** [comment]
It seems also that the issue is actually harder to trigger. It happens if second user has admin name as part of his name. So the following triggers issue for me:
1. Say admin name is "admin"
2. Register a new user for e.g. via admin panel and use "admin2" as value for login
3. Now admin can't create new channels, until he deletes "admin2" user

**Comment by ggazzo** [comment]
I just checked here, impossible to reproduce on the latest version, please open again if the problem persists :)
