### ISSUE TITLE
Feature > jump to quote or message link without copying the whole link 

### ISSUE THREAD

**Issue by lyricalpolymath** [RocketChat/Rocket.Chat#9119]
When posting a message with a link to another message
today it copy pastes the whole message, even if it's a very long one.

It would be great to have something like the **right hand button (Jump to message)**

- for quotes
- and for links to prior messages

this would enable to jump to the relevant conversation.

Alternatively it could be useful to fold the connected message, and style it (smaller, greyer), so as to clearly differentiate the main message from the referenced one.

is it possible to paste some javascript in the message creation textfield?
I know it could be used for fishy things ... but it would be enough to do a link to

`RoomHistoryManager.getSurroundingMessages(ChatMessage.findOne("r2eAsYYWP3pXZBwbr"), 1)`

maybe I can implement something if you could point me in the right direction :)
thanks

**Comment by rodrigok** [comment]
It's already possible if you click on the message date/time

![Screen Shot 2020-02-13 at 15 32 32](https://user-images.githubusercontent.com/234261/74466601-4e00bc80-4e76-11ea-9bed-009f94fd4b9c.png)
