### ISSUE TITLE
Security Issue Create Admin without Priveleges

### ISSUE THREAD

**Issue by bochos-bln** [RocketChat/Rocket.Chat#9122]
### Description:

Removing Admin Role to other users without the right and create a new Admin without right.

### Server Setup Information:

* Version of Rocket.Chat Server: 59.3
* Operating System: ?
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: ?

### Steps to Reproduce:

1. Having a new Role for assigning custom roles e.g. Role Admin with no right to:
access-permissions], [assign-admin-role]
2. With that User edit the Admin, (needed because basically  we want to add an other role to other users), 
- remove admin role, save fail
- add any other role e.g. bot, saved user has no more the admin role
- if this happend with the last admin, anybody can add a new admin by registration page

### Expected behavior:
- Admin is still admin

### Actual behavior:
admis looses admin priveleges

### Relevant logs:
-

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
