### ISSUE TITLE
RocketChat Apps need an icon

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9124]
![image](https://user-images.githubusercontent.com/9200155/34002809-cb9d0916-e0da-11e7-8e33-8b5b14eab55e.png)

**Comment by arthurgiustina** [comment]
![rocket-chat-apps-icon](https://user-images.githubusercontent.com/30700871/34582302-93024610-f17a-11e7-976e-65f584ba0efb.png)

@karlprieb @theorenck @engelgabriel 

Any of these icons?

IMO the space-shuttle will be great for this

**Comment by engelgabriel** [comment]
Let's go with cube, at least for now.

**Comment by engelgabriel** [comment]
![image](https://user-images.githubusercontent.com/1000217/34877032-66f2d5aa-f78b-11e7-9c17-149922428929.png)

**Comment by theorenck** [comment]
@engelgabriel may I consider approved?
