### ISSUE TITLE
Rocket.Chat Apps installation page layout

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9125]
![image](https://user-images.githubusercontent.com/9200155/34003042-657c21b6-e0db-11e7-954c-ff15965907a2.png)

**Comment by arthurgiustina** [comment]
![manage apps](https://user-images.githubusercontent.com/30700871/34627681-b19734d6-f248-11e7-9bee-d5c2b6902254.png)

![install new app](https://user-images.githubusercontent.com/30700871/34627682-b1ba164a-f248-11e7-97ca-844e133191bb.png)

@karlprieb @theorenck @graywolf336 @engelgabriel 
Abstract link: https://share.goabstract.com/c9d403fb-1312-42d5-baf5-89335c139518

**Comment by engelgabriel** [comment]
```
{
    "id": "792cb6be-5db9-4752-af84-7010ed59573f",
    "name": "Guggy Command",
    "nameSlug": "guggy-command",
    "description": "Provides a command for generating gifs based upon text provided.",
    "version": "1.0.8",
    "requiredApiVersion": ">=0.6.29",
    "author": {
        "name": "Bradley Hilton",
        "homepage": "https://github.com/graywolf336/temporary-rocketlets-dev-environment",
        "support": "https://github.com/graywolf336/temporary-rocketlets-dev-environment/issues"
    },
    "classFile": "GuggyRocketlet.ts",
    "iconFile": "icon.png"
}
```

**Comment by arthurgiustina** [comment]
![install new app](https://user-images.githubusercontent.com/30700871/34631649-8d136926-f258-11e7-8b91-daa2be091886.png)
\
![app details](https://user-images.githubusercontent.com/30700871/34631650-8d37abe2-f258-11e7-9bbf-1078e7122a90.png)

@graywolf336 @theorenck @karlprieb @engelgabriel 
Abstract Link: https://share.goabstract.com/72d05bba-d9ae-4749-807d-da8f8a1479b6

**Comment by engelgabriel** [comment]
Added my comments

**Comment by arthurgiustina** [comment]
![install new app](https://user-images.githubusercontent.com/30700871/34890884-c048bdd4-f7ba-11e7-816d-cebe23225a4d.png)

![app details](https://user-images.githubusercontent.com/30700871/34890889-c076a94c-f7ba-11e7-95d8-9e256a7793e0.png)

@engelgabriel @graywolf336 @theorenck @karlprieb 
Abstract updated: https://share.goabstract.com/6bb2ec08-78e6-4ab6-81e9-ef821bc640a5
