### ISSUE TITLE
Rocket.Chat Apps grid

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9128]
![image](https://user-images.githubusercontent.com/9200155/34003601-d5868fcc-e0dc-11e7-9763-db1b20a98346.png)

A list of installed apps. This grid will show all apps (enabled and disabled).

**Comment by arthurgiustina** [comment]
![list of apps](https://user-images.githubusercontent.com/30700871/34483858-4679efd8-efa8-11e7-8e48-33cfda5898ce.png)

@karlprieb @theorenck **Take a look**

Link to Abstract: https://share.goabstract.com/5514d7f0-039e-46e0-ae94-62185b512073

**Comment by arthurgiustina** [comment]
![manage apps](https://user-images.githubusercontent.com/30700871/34631699-c2c6aa10-f258-11e7-8c66-453acf18c379.png)

@theorenck @graywolf336 @karlprieb 
Abstract Link: https://share.goabstract.com/72d05bba-d9ae-4749-807d-da8f8a1479b6

**Comment by engelgabriel** [comment]
Added my comments

**Comment by arthurgiustina** [comment]
Update

![manage apps](https://user-images.githubusercontent.com/30700871/34890883-c014d992-f7ba-11e7-83f3-a380f9d81d9a.png)

![install new app](https://user-images.githubusercontent.com/30700871/34890884-c048bdd4-f7ba-11e7-816d-cebe23225a4d.png)

![app details](https://user-images.githubusercontent.com/30700871/34890889-c076a94c-f7ba-11e7-95d8-9e256a7793e0.png)

@engelgabriel @graywolf336 @theorenck @karlprieb 
Abstract updated: https://share.goabstract.com/6bb2ec08-78e6-4ab6-81e9-ef821bc640a5
