### ISSUE TITLE
Implement setting changed callback

### ISSUE THREAD

**Issue by rwakida** [RocketChat/Rocket.Chat#913]
Allows us to validate or react to RocketChat setting changes.  

For example, when the SMTP settings are updated, we can set the MAIL_URL environment variable.  Likewise, when the Account_EmailVerification is set to true, we can check if the SMTP settings are configured (fix #766)

**Comment by gmsecrieru** [comment]
:+1:

**Comment by engelgabriel** [comment]
This has been implemented.
