### ISSUE TITLE
Cannot bypass domain whitelist when manually adding a user

### ISSUE THREAD

**Issue by kmoore134** [RocketChat/Rocket.Chat#9139]
### Server Setup Information:

Rocket Chat - 0.59.4

### Steps to Reproduce:

1. Setup a list of whitelisted domains (or a single one)
2. Go to admin panel -> users and try to manually add somebody outside that domain

**Comment by SeanPackham** [comment]
This is the expected behaviour.

**Comment by rsc1975** [comment]
I reach out this issue, looking for the possibility to bypass the "domains whitelist", this feature It's really desirable, In our organization all the users are from our mail domain "company.com", however, It's quite usual to invite to external users (from our customers) to collaborate with them in software projects and other cases.

So, maybe an additional parameter like "emails whitelist" additional to "domains whitelist" would be nice, It would give more flexibility. 

Anyway, just for other users that need it, right now you can by pass the restriction, if you disable the domains whitelist, then add the user and then re-enable de domains whitelist, the existing users keep in the system. It's not an ideal solution, but It works.

**Comment by ulope** [comment]
This is also a problem for us for the same reason @rsc1975 mentioned. Signup needs to be restricted to the "local" domains but external users (esp. in guest role with only access to a few channels) need to be able to be added by admins.

We're currently working around this by temporarily removing the whitelisted domains, adding the users, then re-adding the whitelist.

Obviously, that's not a very secure or user-friendly process.
