### ISSUE TITLE
Auto-scroll breaks on lazy image loading

### ISSUE THREAD

**Issue by joepie91** [RocketChat/Rocket.Chat#914]
When saying `@rocketbot map me The Netherlands`, the following happens:

![selection_426](https://cloud.githubusercontent.com/assets/1663259/10122790/47b4c1cc-6524-11e5-9cda-28d446305b35.png)

It only scrolls down far enough to account for the text, but not for the corresponding image(s). The images fall below the fold. This is likely because the scroll happens *before* the images are completely loaded, and it doesn't scroll again *after* they are loaded.

What it *should* look like:

![selection_427](https://cloud.githubusercontent.com/assets/1663259/10122792/742b9b68-6524-11e5-8585-18772096792d.png)

**Comment by engelgabriel** [comment]
Fixed, a long time ago.
