### ISSUE TITLE
Messages with the class ' livechat_video_call ' and ' jitsi_call_started ' is empty

### ISSUE THREAD

**Issue by Praunda** [RocketChat/Rocket.Chat#9143]
### Description:

At the start of a video call there is two info message bubbles appears empty, in my DOM. Both of those empty bubbles has 2 different class every same time -- livechat_video_call -- and -- jitsi_call_started --.

### Server Setup Information:

* Version of Rocket.Chat Server: 060-develop
* Operating System:  Ubuntu
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* Node Version: 4.2.6

### Expected Behaviour:

at the end and the start of a video call I want to inform livechat video call finished and started.

**Comment by lucassmacedo** [comment]
I have the same problem!
