### ISSUE TITLE
Two vps requirements 

### ISSUE THREAD

**Issue by diogorocha18** [RocketChat/Rocket.Chat#9145]
Good afternoon, as my VPS has as requirements:

The first:
KVM OpenStack
SLA 99.99%
1 vCore (s)
2.4 GHz
6 GB RAM
25GB
High Availability (Ceph)

The second:
KVM OpenStack
1 vCore (s)
2.4 GHz
4GB RAM
20 GB SSD
Local RAID 10

Could you tell me how many users simultaneously and so I can have in each one please?

Thank you all

**Comment by TwizzyDizzy** [comment]
This github project is no proper channel for support. Please refer to the support channel on the official Rocket.Chat demo instance: https://open.rocket.chat/channel/support

"Issue" can be closed.

Cheers
Thomas
