### ISSUE TITLE
UI: Descenders of glyphs are cut off

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#9151]
### Description:

Descenders of glyphs are cut off in the sidebar where the last message is shown below the channel name. See screenshot. The lower half of the letter "g" is cut off in the name Diego.

Cheers
Thomas

### Server Setup Information:

Version of Rocket.Chat Server: 0.60.0-develop
Operating System: unknown (not running this instance myself)
Deployment Method(snap/docker/tar/etc): unknown (not running this instance myself)
Number of Running Instances:  unknown (not running this instance myself)
DB Replicaset Oplog:  unknown (not running this instance myself)
Node Version:  unknown (not running this instance myself)

### Steps to Reproduce:

![untitled](https://user-images.githubusercontent.com/179595/34072143-22d7b4a8-e282-11e7-8a4d-4ef44ed3f1e1.png)

### Expected behavior:

Descenders should not be cut off.

### Actual behavior:

Descenders are cut off.

### Relevant logs:

See screenshot above

**Comment by TwizzyDizzy** [comment]
According to the release notes of [0.60.0-rc.4](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.60.0-rc.4) this was supposed to be fixed. I can't confirm it being fixed in 0.60.0-rc.4 - neither in Firefox nor in Chromium. See the attached screenshot below:

![untitled](https://user-images.githubusercontent.com/179595/34161314-914e6616-e4d0-11e7-8178-9e2da78bba95.png)

Cheers
Thomas

**Comment by rodrigok** [comment]
@TwizzyDizzy I can't reproduce, can you specify your OS and Browser versions?

**Comment by TwizzyDizzy** [comment]
Whooot... OK. This is weird. Only thing I can think of right now: Maybe my deployment failed without me noticing and I was actually still looking at rc.2 - I'll re-check tomorrow. Sorry for the fuzz!

Cheers
Thomas

**Comment by rodrigok** [comment]
@TwizzyDizzy I did a better solution https://github.com/RocketChat/Rocket.Chat/pull/9181

**Comment by TwizzyDizzy** [comment]
Hi @rodrigok 

nope, deployment went fine and I was actually looking at rc.4

Windows 7 Enterprise: Firefox 57.0.2 - **no problem** (looks like CSS font fallback to Arial, also no font-Anti-Aliasing)
Windows 7 Enterprise: Chrome 63.0.3239.108 - **no problem** (looks like CSS font fallback to Arial, also no font-Anti-Aliasing)
Elementary OS Loki (Ubuntu 16.04/LTS Spin-Off): Firefox 57.0.1 - **problem**
Elementary OS Loki (Ubuntu 16.04/LTS Spin-Off): Chromium 63.0.3239.84 - **problem**

Cheers
Thomas

**Comment by rodrigok** [comment]
@TwizzyDizzy Can you test our latest develop version? You can test it here https://unstable.rocket.chat

**Comment by TwizzyDizzy** [comment]
Looks good on all 4 combinations:

* Windows FF
* Windows Chrome
* Linux FF
* Linux Chromium 

Cheers
Thomas

**Comment by rodrigok** [comment]
Awesome, thanks 😄
