### ISSUE TITLE
Last sent message reoccurs in textbox

### ISSUE THREAD

**Issue by mphslaats** [RocketChat/Rocket.Chat#9153]
Hey,

I am using Rocket.Chat (0.59.4 Under latest CentOS) for quite a while now, however I ran into a problem.
I use Rocket.Chat in browser (Chrome on Android 6 and Safari on IOS) and in both cases I get the following problem:
Every time I open a channel my last message is displayed in the textbox. So I first need to remove my last message before I can start writing a new one.

![screenshot_2017-12-17-22-10-09](https://user-images.githubusercontent.com/15626597/34083851-304df3ae-e377-11e7-8528-3ac87ae6d768.png)

**Comment by bandycj** [comment]
This still happens on mobile 0.60.2.

**Comment by rodrigok** [comment]
@bandycj Ok, I'll check it. Can you be more specific?

It's happening on Android?
Which browser are you using?
Which Android version?
Any extra information could help us.

Thanks

**Comment by bandycj** [comment]
It’s happening on iOS 11.2.1 using the client app which I believe is just an iOS web view which would make it safari.

**Comment by bandycj** [comment]
I’ve tried complete removing the server setting and app and reinstalling to make sure I don’t just have stale assets.

**Comment by rodrigok** [comment]
@bandycj Can you test using safari too?

**Comment by bandycj** [comment]
It appears to work fine in mobile safari.

**Comment by bandycj** [comment]
I’m not sure if the nature of the bug, but could it be that I’m seeing some lingering effect of running a server with the bug? Like the bug set some state on the channel that is cleared only when visiting the channel with an updated server?

**Comment by rodrigok** [comment]
Yes, there was a bug that just didn't clear the state when sending messages using the `send` button on mobile, the new version will not clear that old state when you enter in a channel that old version didn't clear, the new version will clear the state when you send a new message only.

So let met know if you send a new message (after the new server version) and that message keep showing after accessing that channel again.
