### ISSUE TITLE
I have to upload a picture twice to make it work

### ISSUE THREAD

**Issue by mphslaats** [RocketChat/Rocket.Chat#9154]
Hey,

I lately ran into a problem on several devices while using Rocket.Chat (0.59.4 Under latest CentOS). I sometimes have to upload a picture twice before Rocket.Chat is able to upload it. If I upload the picture for the first time nothing happens... This happened to me on both Android and Windows 10.

**Comment by rodrigok** [comment]
Which version are you using?

**Comment by mphslaats** [comment]
I am running Rocket.Chat version 0.59.4 on CentOS 7 with the latest updates.
And I am sometimes getting the problem on Windows 10 (multiple laptops) and most of the time on at least three Android devices (one of the has Andoid 6, the others I don't know).

**Comment by HammyHavoc** [comment]
Do you end up with duplicate pictures at any time? We've been getting 2 - 3 of the same picture sometimes, I'm wondering if it's due to people having to try uploading multiple times.

**Comment by mphslaats** [comment]
No I have two ways how it goes wrong:

The first one is that I try to upload a picture and nothing happens, even after waiting for a minute or so. After a minute I tried to upload that same picture and it works.

The second way is that it shows me the upload bar on the top but even after ten minutes it is at 0%, therefore I cancel it and if I try it again it uploads immediately.

**Comment by rodrigok** [comment]
@mphslaats which browser are you using? Can you record a video/gif of your problem happening?

**Comment by mphslaats** [comment]
In Chrome Version 63.0.3239.84 (Official Build) (64-bit) on latest Windows 10 it only shows me this for ten minutes until I stop it:
![hallo 387](https://user-images.githubusercontent.com/15626597/34221454-5d7d47ce-e5b8-11e7-8761-e6158a357551.png)

On mobile (Android 6 with the latest Chrome browser) it goes wrong ass follows:
https://youtu.be/jjk13_Q2jms

**Comment by rodrigok** [comment]
Did you test using chrome on linux or mac os?

**Comment by mphslaats** [comment]
I have not run into this problem on the latest Ubuntu Mate yet.
And I have not tested in on a Macbook or IMac (because I don't have one). However it occurs on a IPhone 7 as well.

**Comment by rodrigok** [comment]
Fixed by #9206
