### ISSUE TITLE
AutoTranslation glitches since v59.4

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#9155]
### Description:

Auto-translated message text content renders embedded between visible `<p>` and  `</p>` tags 
Auto-translate toggle icon does not appear in message context menu

### Server Setup Information:

* Version of Rocket.Chat Server: 59.4
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Enable AutoTranslate via Message ---> AutoTranslate menus in Admin console - requires Google API key
2. Make sure your user has AutoTranslate permission enabled in Permissions in Admin console
3. AutoTranslate icon should now appear in right-hand flextab menu
4. Open flextab and set switch to 'on' position
5. Select a target language for AutoTranslate to translate messages into

### Expected behavior:

All new messages sent into the channel should now appear in the target translation language
Each translated message should have translation toggle switch enabled in context menu

### Actual behavior:

Messages do appear in target translated language, but also have `<p>` and `</p>` tags visible:
<img width="763" alt="screen_shot_2017-12-18_at_12_00_29_pm" src="https://user-images.githubusercontent.com/1432373/34086034-8fb02d74-e3ec-11e7-91f2-e2eda4eb1a91.png">

Translated messages do have toggle switch enabled in context menu, but icon is missing:
<img width="232" alt="screen_shot_2017-12-18_at_12_12_52_pm" src="https://user-images.githubusercontent.com/1432373/34086066-ec0127fe-e3ec-11e7-9790-9c241bfdc8d6.png">

**Comment by RichardFoxworthy** [comment]
These issues are still present for autotranslate in v0.61

**Comment by RichardFoxworthy** [comment]
These problems are still present in v0.62 ... does no-one else use translation?

**Comment by nkeilar** [comment]
Also noticed issues. Seemed not to automatically translate messages either, had to click that every time.
