### ISSUE TITLE
less 出错

### ISSUE THREAD

**Issue by LiuSuY** [RocketChat/Rocket.Chat#9156]
![image](https://user-images.githubusercontent.com/25116549/34089653-cc18ef6c-e3ec-11e7-9545-a05d6a14ddbd.png)

**Comment by MartinSchoeler** [comment]
@LiuSuY Please use the english language when creating issues, otherwise the devs and the community won't be able to help you. Thank you.

**Comment by LiuSuY** [comment]
Well, thank you
