### ISSUE TITLE
feature wish: add rel="noreferrer" to links

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#9159]
### Description:

clicking on a link in a chat window may leak information to a destination site since the chat room will end up in the webserver log in the referrer field. Have an option in the settings to add rel="noreferrer" to a link, as per https://stackoverflow.com/questions/5033300/stop-link-from-sending-referrer-to-destination

### Server Setup Information:

* Version of Rocket.Chat Server: any
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: any
* DB Replicaset Oplog: any
* Node Version: any

### Steps to Reproduce:

see description

### Expected behavior:

see description

### Actual behavior:

see description

**Comment by AmShaegar13** [comment]
You could use the [Referer-Policy Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) in your proxy to achieve that.

**Comment by sinteur** [comment]
Neat. That indeed works. @rocketchat team perhaps add that tip to the install docs or hardening guide?

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by marceloschmidt** [comment]
Noreferrer and noopener are already part of every link on Rocket.Chat. Thanks.
