### ISSUE TITLE
Bug on changeavatar (docker)

### ISSUE THREAD

**Issue by pouleta** [RocketChat/Rocket.Chat#916]
Hello,

After start rocketchat from docker-composer, I got an error.

It came from https://chat.domain.dom/changeavatar
On the action to use a new avatar (upload, gravatar), by admin and simple users too.

Configuration: fedora 22, a front NGINX, with https and invalid certificate (valid on www.XXX not on chat.XXX).

```
[publish] settings
[publish] subscription
[publish] userData
[publish] activeUsers
[publish] admin-settings
[methods] hasPermission ->  arguments: { '0': 'EuFxLqgvy7cbGoP2K', '1': 'view-privileged-setting' }
[methods] getRolesForUser ->  arguments: { '0': 'EuFxLqgvy7cbGoP2K', '1': undefined }
[publish] permissions
[publish] activeUsers
[methods] setAvatarFromService ->  userId: EuFxLqgvy7cbGoP2K contentType: image/png service: gravatar

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
```
[methods] resetAvatar ->  userId: EuFxLqgvy7cbGoP2K arguments: {}
[methods] setAvatarFromService ->  userId: EuFxLqgvy7cbGoP2K contentType: image/jpeg service: upload

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by k0nsl** [comment]
I had similar issues with the "internal" store for avatar and it turned out to be a simple permissions issue. So, check your permissions and report back :)

**Comment by pouleta** [comment]
I have no idea where the permissions are set for the docker.
Maybe I should report it to https://github.com/RocketChat/Docker.Official.Image ?

**Comment by k0nsl** [comment]
Oh, docker. Sorry, I read the issue too quickly. My instance isn't deployed via docker -- still, the error was precisely the same as yours:
![rocket.chat avatar issue](https://i.knsl.org/2015-09-25_23-47-50.png)

**Comment by royalaid** [comment]
I too am getting this issue with a crash with regards to avatars

**Comment by pouleta** [comment]
I replace the Accounts_AvatarStorePath from the dashboard with "/tmp" and it worked,
so It was the same issue you described (permissions on the directory).

**Comment by gmsecrieru** [comment]
Maybe we could add an environment variable to setup a temp directory during startup @RocketChat/owners ?

**Comment by Sing-Li** [comment]
Awesome!  It is a bug. We really should check permission b4 saving the path.

**Comment by geekgonecrazy** [comment]
So by default it saves to GridFS, which doesn't need directory write permissions.

So in the case where you set a path while you're in a docker image there is only really one thing we can do.  That is check to make sure its writable like @Sing-Li suggests.

Otherwise its really up to the person using it.

You'd want to do something like:

```
docker run -d --name rocket.chat -v $PWD/avatarstore:/avatarstore -p 3000:80 rocketchat/rocket.chat
```

Then on the host modify the permissions of that directory to allow writing from the container.  So you could do something as simple as:

```
chmod 777 avatarstore
```

**Comment by royalaid** [comment]
So I have tired what is suggested above. It appears that that the images are getting saved properly but it rocket.chat refuses to display the image. It appears the link for the image-url is localhost, changing it to host.domain.com fixes the problem but I am not sure why the link is defaulting to localhost and not my domain

**Comment by engelgabriel** [comment]
Are you setting the ROOT_URL environment variable correctly?

**Comment by royalaid** [comment]
That would be the problem! I am guessing it got reset when I a did pull on the repo. Thanks for the help.
