### ISSUE TITLE
在google-version 一直过不去，即使过了最终的结果也是失败

### ISSUE THREAD

**Issue by LiuSuY** [RocketChat/Rocket.Chat#9160]
![image](https://user-images.githubusercontent.com/25116549/34098909-dfc60dc0-e418-11e7-9e01-d4265c4d7d67.png)

**Comment by MartinSchoeler** [comment]
@LiuSuY Please use the english language when creating issues, otherwise the devs and the community won't be able to help you. Thank you.

**Comment by LiuSuY** [comment]
thank you， Your suggestion is a good idea
