### ISSUE TITLE
rocketchat-mongo not starting

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#9161]
### Description:
Mongo service stopped running after refreshing snaps, followed [https://github.com/RocketChat/Rocket.Chat/issues/4752#issuecomment-261750822](https://github.com/RocketChat/Rocket.Chat/issues/4752#issuecomment-261750822). Basically backed up /var/snap/rocketchat-server/common, reinstalled snap, restored common. rocketchat-mongo ran, but server was only accessible via the local IP and port 3000, didn't seem to recognize my username either, so guessing the information did not restore correctly.

rocketchat-caddy also became inactive, but guessing that's because it wasn't loading the configuration as expected.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.6
* Operating System: Ubuntu Core 16-2.29.4.2
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1

I seem to have a mongod.lock in my common directory, removing it in the restored directory does not seem to make any difference, though mongo troubleshooting isn't my area of expertise.

I also seem to have a common directory within common. Perhaps there is an issue with the command on that comment? Based on that idea, I tried
`sudo cp -R ~/rc-backup/* /var/snap/rocketchat-server/`
instead of
`sudo cp -R ~/rc-backup/* /var/snap/rocketchat-server/common`

Now rocketchat-mongo is enabled but currently inactive after running `sudo snap start rocketchat-server`, this was the issue I was having after refreshing the Snap in the first place.

Manually starting it with `sudo systemctl start snap.rocketchat-server.rocketchat-mongo` results in it appearing active in `sudo snap start rocketchat-server` but only temporarily.

Seems that [https://github.com/RocketChat/Rocket.Chat/issues/5450#issue-199135830](https://github.com/RocketChat/Rocket.Chat/issues/5450#issue-199135830) is my current issue. Tried `dist-upgrade` as per [https://github.com/RocketChat/Rocket.Chat/issues/5450#issuecomment-270949965](https://github.com/RocketChat/Rocket.Chat/issues/5450#issuecomment-270949965), but bash on Ubuntu Core informs me 'command not found'.

The Pi 2 has 647 free of 920 in terms of RAM according to `free -m`.

**Comment by HammyHavoc** [comment]
Some further info after running `systemctl status -l`:

```
 localhost.localdomain
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Tue 2017-03-14 20:24:11 UTC; 9 months 4 days ago
   CGroup: /
           ├─1120 /sbin/cgmanager -m name=systemd
           ├─init.scope
           │ └─1 /lib/systemd/systemd fixrtc
           ├─system.slice
           │ ├─dbus.service
           │ │ └─1152 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
           │ ├─cron.service
           │ │ └─1139 /usr/sbin/cron -f
           │ ├─systemd-journald.service
           │ │ └─511 /lib/systemd/systemd-journald
           │ ├─system-serial\x2dconsole\x2dconf.slice
           │ │ └─serial-console-conf@ttyAMA0.service
           │ │   └─1397 /bin/bash /usr/share/subiquity/console-conf-wrapper --serial
           │ ├─snapd.service
           │ │ └─1164 /usr/lib/snapd/snapd
           │ ├─systemd-timesyncd.service
           │ │ └─992 /lib/systemd/systemd-timesyncd
           │ ├─ssh.service
           │ │ └─1205 /usr/sbin/sshd -D
           │ ├─systemd-logind.service
           │ │ └─1143 /lib/systemd/systemd-logind
           │ ├─systemd-networkd.service
           │ │ └─704 /lib/systemd/systemd-networkd
           │ ├─system-console\x2dconf.slice
           │ │ └─console-conf@tty1.service
           │ │   └─1408 /bin/bash /usr/share/subiquity/console-conf-wrapper
           │ ├─systemd-udevd.service
           │ │ └─658 /lib/systemd/systemd-udevd
           │ ├─snap.rocketchat-server.rocketchat-server.service
           │ │ ├─1965 /bin/bash /snap/rocketchat-server/1196/bin/startRocketChat
           │ │ └─2093 sleep 20
           │ └─rsyslog.service
           │   └─1134 /usr/sbin/rsyslogd -n
           └─user.slice
             └─user-1000.slice
               ├─session-1.scope
               │ ├─1237 sshd: hammyhavoc [priv
               │ ├─1364 sshd: hammyhavoc@pts/
               │ ├─1365 -bash
               │ ├─2094 systemctl status -l
               │ └─2095 pager
               └─user@1000.service
                 └─init.scope
                   ├─1344 /lib/systemd/systemd --user
                   └─1346 (sd-pam)

```

**Comment by geekgonecrazy** [comment]
Taking a look on community server: https://open.rocket.chat/channel/ubuntu-snap?msg=TSGuhcumm8kRa9bPC Conversation starts here.  Will transplant solution here. :)

**Comment by HammyHavoc** [comment]
Never did solve the issue, but many thanks to @geekgonecrazy for his hours of time troubleshooting the problem. After several days of downtime, we literally just had to call it a loss and move on as the time spent troubleshooting it was fast becoming much larger than the time it would take to start from scratch. A couple dozen users into rolling RC back out. :- )

**Comment by geekgonecrazy** [comment]
If we had more uninterrupted time I think we could have got it. Make sure to check snap faq for backup command.  I'd recommend doing frequently
