### ISSUE TITLE
Right toolbar not displayed in firefox ESR

### ISSUE THREAD

**Issue by amateo** [RocketChat/Rocket.Chat#9179]
Hi,

  I have upgraded from 0.58.4 to 0.59.4. Since then, the toolbar at right of the screen is not displayed in firefox ESR. I have tested in other versions of firefox, chrome and the standalone client and it is displayed, but not in firefox ESR. The space of the toolbar is displayed and buttons are there (and "usable") but the icons are not displayed.

![screenshot](https://user-images.githubusercontent.com/3133951/34150172-d870cc10-e4a7-11e7-955a-7ded14ea90a1.png)

**Comment by magicbelette** [comment]
See https://github.com/RocketChat/Rocket.Chat/issues/7980
