### ISSUE TITLE
Push Notifications not being sent on Rocket.Chat 0.60.rc3

### ISSUE THREAD

**Issue by archang3l-media** [RocketChat/Rocket.Chat#9187]
### Description:

Push Notifications are not working with rocket.chat 0.60.0-rc.3

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-rc.3
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 5
* DB Replicaset Oplog: enabled
* Node Version: Node 8.9.1

### Steps to Reproduce:

1. Set up Push notifications with or without gateway.rocket.chat
2. Send a Test Push notification (generate a token on your phone first)

### Expected behavior:

I get a push notification

### Actual behavior:

Nothing happens.

### Relevant logs:
https://pastebin.com/gqFNz2r3
I deleted all private Data before pasting the Logs
Except for the `Dec 19 21:13:12 rocketchat RocketChat: createdBy: '<SERVER>' part...
In the Server Logs the Tokens seem correkt but the '"createdBy: '<SERVER>'" seems off.

Full Logs can be sent via Mail, but I prefer not publicly disclosing API Keys or user Names/IDs

**Comment by geekgonecrazy** [comment]
Lot has changed here.  Going to close
