### ISSUE TITLE
Selecting message notification does not open that message.

### ISSUE THREAD

**Issue by themikeanello** [RocketChat/Rocket.Chat#9207]
### Description:

Selecting message notification does not open that message.

### Server Setup Information:

* Version of Rocket.Chat Server: No idea.
* Operating System: macOS High Sierra 10.13.2
* Deployment Method(snap/docker/tar/etc): No idea.
* Number of Running Instances: 1
* DB Replicaset Oplog: No idea.
* Node Version: Don't know.

### Steps to Reproduce:

1. Receive a message notification.
2. Select the message notification (mouse click).
3. Rocket.Chat opens to last conversation, not the message in the notification.

### Expected behavior:

I expect selecting a message notification to open Rocket.Chat to that message.

### Actual behavior:

Rocket.Chat opens to last active conversation.

### Relevant logs:
No logs needed.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
