### ISSUE TITLE
Reduce white space above messagebox

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9214]
### Description:

![image](https://user-images.githubusercontent.com/51996/34267899-50c7aeac-e644-11e7-97a0-c0a0ed8638a8.png)

Its really only noticeable when you scroll.

I know this area is needed to display the typing indicators.  Not sure how one could accomplish if at all.

@karlprieb is such magic possible? :)

**Comment by tobywhughes** [comment]
Perhaps there could be a button that hides the typing indicators (along with the white space above and the title at the top. It could be a semi-fullscreen button.

**Comment by SamSaffron** [comment]
I still struggle with the original decision here, cause both mattermost and slack manage to have the typing indicator below the composer fine and it totally eliminates the issue, this works fine on phones in both cases

**Comment by engelgabriel** [comment]
@SamSaffron we will make it only appear when someone is typing, and we will add a padding so it won't cover the last message when you are scrolled to the bottom.

This is a quick change and we can improve more on the next UX interaction.

**Comment by karlprieb** [comment]
@engelgabriel ok

**Comment by ggazzo** [comment]
@geekgonecrazy what do you think about this solution (if you arent on bottom list), just to avoid this white space

![image](https://user-images.githubusercontent.com/5263975/40980400-ae811bea-68ae-11e8-8c01-85962aa1f540.png)

**Comment by vynmera** [comment]
Why not make a white gradient from the typing indicator, so the messages fade into it? To keep the typing text itself visible you can add a bit of extra shadow in the background color onto the text.

I'm not at home right now, so all I can give is this low-quality mockup:
![](https://i.imgur.com/aX791c0.jpg)

**Comment by ggazzo** [comment]
hi @vynmera I made the same test, actually is just about opinion... I dont care about the white space... but there are some users that do. I liked both, lets the community talk more.

**Comment by geekgonecrazy** [comment]
@ggazzo I think this would also be an acceptable solution.  Because it would now be shown in the box instead of seemingly floating

**Comment by MartinSchoeler** [comment]
This seems to be resolved in the latest version, closing this. Thanks!
