### ISSUE TITLE
IRC Client Connect

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [RocketChat/Rocket.Chat#922]
I am confused about the IRC implementation. Does Rocket Chat have an IRC server that allows clients to connect to the channels? Like from pidgin?

**Comment by geekgonecrazy** [comment]
@phillip-white-sociomantic this plugin is pretty much allowing rocket.chat to join an irc channel.

**Comment by phillip-white-sociomantic** [comment]
Ahh ok. Thanks for clearing up

**Comment by comzeradd** [comment]
Can you elaborate a bit on that? I couldn't find any documentation on how to enable the irc plugin. @geekgonecrazy

**Comment by geekgonecrazy** [comment]
Its currently commented out.  You'd have to uncomment it in the .meteor/packages and then build.  We have it disabled currently as like you said it doesn't have documentation, and we don't have a nice clean way of toggling it on / off

**Comment by bott0r** [comment]
It would be outstanding to be able to connect to irc servers from the RC instance.

**Comment by bott0r** [comment]
Is there any news on this ?

**Comment by iltar** [comment]
Any updates on the IRC plugin?

**Comment by geekgonecrazy** [comment]
See #216
