### ISSUE TITLE
Cursor floats one line above text in text entry box, sometimes multiple lines above.

### ISSUE THREAD

**Issue by Sentinelrv** [RocketChat/Rocket.Chat#9220]
### Description:

In Safari mobile when I go to type a message in the text box, the cursor floats one line above where the text should be. This has happened for about a month now maybe. It is confusing because it's difficult to know what line the text is going to appear on.

Something else I've noticed is that sometimes when editing a message and moving the cursor around, the cursor will somehow end up more than one line above where it should be, sometimes two or three lines, which makes it impossible to edit messages.

Picture included in the link below...

https://i.imgur.com/tW7smGp.png

I'm using iPhone 6 Plus, iOS 11.2.1.

### Server Setup Information:

* RocketChat 0.59.6
* Latest Docker

### Steps to Reproduce:

1. The cursor is automatically one line above once where it should be in the text box, sometimes multiple lines when editing.

### Expected behavior:

Cursor should be on the same line.

### Actual behavior:

Cursor is on a different line.

**Comment by Sentinelrv** [comment]
I have to mention that this was happening before the UI redesign.

**Comment by briansugar** [comment]
@acinader

**Comment by TwizzyDizzy** [comment]
So is this still present on current stable?

Cheers
Twizzy

**Comment by Sentinelrv** [comment]
I think it has been fixed, just tried it and didn’t notice it anymore.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Thanks for the feedback! :)

Cheers
Thomas
