### ISSUE TITLE
Attach file button does not register when tapped on Safari Mobile.

### ISSUE THREAD

**Issue by Sentinelrv** [RocketChat/Rocket.Chat#9221]
### Description:

In Safari mobile when I tap on the new icon to attach a file, nothing happens. It used to be a paperclip, but was changed to a monitor icon (which does not seem as intuitive to me). All 3 icons to the left of it work, but tapping the fourth icon does nothing. I've been unable to upload anything from mobile because of this.

I'm using iPhone 6 Plus, iOS 11.2.1.

### Server Setup Information:

* RocketChat 0.59.6
* Latest Docker

### Steps to Reproduce:

1. Tap the attach file icon.

### Expected behavior:

Tapping icon should bring up upload screen.

### Actual behavior:

Tapping icon does not register.

**Comment by karlprieb** [comment]
Hey @Sentinelrv I think I fixed this problem on #9206 . Can you test on unstable.rocket.chat that run develop branch?

**Comment by Sentinelrv** [comment]
Sorry, I don't know how to do that. I don't run our chat instance and was only trying to make sure the issue was known about.

**Comment by gabriellsh** [comment]
Tested on open.rocket.chat, iPhone 6s, iOS 13.3, safari, works fine. If you still face this issue, please reopen.
