### ISSUE TITLE
Upload file screen where you hit send does not launch with Edge browser.

### ISSUE THREAD

**Issue by Sentinelrv** [RocketChat/Rocket.Chat#9222]
### Description:

In Microsoft Edge, if I click the plus symbol and try to attach a file, the menu opens up for me to select a file, but once I choose a file and try to open it, nothing happens. The usual screen that pops up that says "upload file?" and allows me to send the file does not come up. The process ends after clicking open. This happens with any type of file. I tried the same with FireFox and Chrome and they both worked, but Edge will not allow me to continue to the next step.

Using Windows 10 version 1709
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

### Server Setup Information:

* RocketChat 0.59.6
* Latest Docker

### Steps to Reproduce:

1. Open chat in Edge.
2. Click plus icon.
3. Click add files from computer.
4. select file and click open or double click file.

### Expected behavior:

Popup to continue uploading should launch.

### Actual behavior:

Popup to continue uploading does not launch.

**Comment by gabriellsh** [comment]
Tested on open.rocket.chat, Windows 10, Edge 44.18362. Works fine. If you still face this issue, please reopen.
