### ISSUE TITLE
Beautify status icon in user list

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9224]
The status icon in the user list indicates if a user is online. In the current version the icon is placed on the left of the profile picture. In my opinion this breaks the clear line on the left side of the design. 

Current version:
<img width="131" alt="online-status-old" src="https://user-images.githubusercontent.com/3596824/34290825-bcd70e8e-e6f9-11e7-99c9-82852e1feda0.png">

I suggest an alternative design:
<img width="133" alt="user-status-new" src="https://user-images.githubusercontent.com/3596824/34290934-27704ed6-e6fa-11e7-9a4e-a6d1d4e92ffa.png">

CSS Code (not cross-browser or cross-device tested!):

```
.sidebar-item__user-status {
    margin-left: 29px;
    z-index: 1;
    margin-top: 8px;
}
```

What do you guys think of this design approach?

**Comment by TwizzyDizzy** [comment]
Hi @janrudolph 

I agree with you general reasoning, yet the clear, visual line on the left part of the left sidebar is currently already broken by the hash icon (for public channels) and the lock icon (for private groups). See the screenshot below.

![image](https://user-images.githubusercontent.com/179595/34320136-0db1dcd6-e7f3-11e7-8c6a-86172c75a029.png)

Yet I very much agree with you, that the current state with stuff left from this imaginary line is kind of disturbing. I'm wondering: what does one really use the hash and the lock icon for. Probably to visually indicate what kind of channel this is. But for that, I think, you already have the separation into **Channels** and *Private Groups* - so I think there's actually no need for these icons.

Would you agree?

Cheers
Thomas

**Comment by Gummikavalier** [comment]
@TwizzyDizzy Those icons are needed if you set `merge channels` in options. Personally I'd lose initial avatars in channels unless they get some extra features in the future.

What @janrudolph suggests might cause trouble with avatars with much green, yellow or red hues, so the dot would need additional contouring.

**Comment by janrudolph** [comment]
@Gummikavalier If you add 

`border: 1px #04302C solid;`

with `#04302C` is my background color of the left column, it looks like this

<img width="200" alt="status-icon" src="https://user-images.githubusercontent.com/3596824/34522127-7f6b81f0-f091-11e7-98bd-de6b1e4f23c9.png">

What do you think?

**Comment by Gummikavalier** [comment]
@janrudolph Looks good to me. :)

**Comment by RichardFoxworthy** [comment]
Current design for presence colour indicator looks especially silly with LiveChat 

<img width="113" alt="screen_shot_2018-01-04_at_3_34_40_pm" src="https://user-images.githubusercontent.com/1432373/34585682-deb6d36c-f1f4-11e7-9d5c-a8a9aeeba629.png">

@janrudolph soloution with coloured dot in corner of avatar will be a big improvement I think

**Comment by engelgabriel** [comment]
We also have been struggling with this, and here are some points to consider:

- Channels and Groups will get the option to have real pictures avatars.
- We think that most people will prefer to merge all rooms into a single list order by activity, so the room type icons are important.
- Displaying avatar on the list will be optional
- Design need to cater for the compat and the detailed version of the list

I am open to suggestions, and I also like the proposed change, but I think we'd have to add the @ back in that case.

**Comment by janrudolph** [comment]
@engelgabriel Thanks for your reply. Just one question: Why do we need the @ in the list? In the current implementation users are indicated by their profile picture or initials. Do you plan to replace these options with the @ or add the @ as third alternative?

I just thought, why not add "badges" at each channel/profile picture to indicate the channel type? My rough prototype looks like this: 

![channel-type-badges](https://user-images.githubusercontent.com/3596824/34662207-2dc3e1dc-f44f-11e7-918a-cf7d6d9a235a.png)

For sure, we should beautify this ;-) Such an implementation will keep the left sidebar compact even in the extended version. I think the challenge will be to have a clear design in the sidebar, especially when an user is member of many channels.

By the way, in a compact version the status icon will look like this:

![compact-status-icon](https://user-images.githubusercontent.com/3596824/34662319-0ed56506-f450-11e7-983c-ceb943403e6a.png)

What do all the UX guys think about this topic? ;-)

**Comment by engelgabriel** [comment]
![image](https://user-images.githubusercontent.com/1000217/35885486-12f5f88a-0b75-11e8-8e5b-9cc2c974b559.png)

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/9608
