### ISSUE TITLE
Server downloads are down

### ISSUE THREAD

**Issue by AmShaegar13** [RocketChat/Rocket.Chat#9225]
### Description:

I cannot download prebuilt server packages from https://rocket.chat/download anymore. I'm getting a 502 Bad Gateway. Looks like https://rocketchat.konecty.com/ is completely broken at the moment.

### Steps to Reproduce:

1. Navigate to https://rocket.chat/download
2. Try to download a server package

### Expected behavior:

Download the tgz.

### Actual behavior:

502 Bad Gateway

**Comment by sampaiodiego** [comment]
fixed.. thanks =)
