### ISSUE TITLE
[new feature] Public channel without registration

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#9231]
Currently the only way to interact with people in a Rocket.Chat is either a Livechat Widget (which connects only to one person if online) or public registration.

I just created a [Python relay](https://gist.github.com/soundstorm/91cc6553b117b98b919498b99d3836e2) which opens a WebSocket e.g. website visitors. The messages will be published via a incoming webhook to an channel and responses will be written back by an outgoing webhook. So any guest may send a short question to the channel and any RC user may respond.

We'd like to have this feature implemented in RC itself, as the Python relay server adds a bit overhead and needs two additional ports.

**Comment by rotanid** [comment]
thanks @soundstorm , having public channels which don't need registration would really be nice.
i know this feature from HipChat, where you could enable guest access for a channel which would give you a link you can send to people or publish.

**Comment by pierreozoux** [comment]
You can already do it, go to /admin/Accounts and check annonomous read/write.
