### ISSUE TITLE
Mandatory 2FA

### ISSUE THREAD

**Issue by horstepipe** [RocketChat/Rocket.Chat#9233]
I'd love to see the abilty to force the users activating the 2-factor-authentication.
In a first step, it would be nice to have an overview about which users have it enabled and which don't.

**Comment by rasos** [comment]
We have deployed RC with an identity provider (keycloak) and de-activated self-registration in RC.

**Comment by horstepipe** [comment]
Thanks, but in principle I‘m happy with the 2FA. I just want to make sure all users have it enabled.

**Comment by zhouxi4oling** [comment]
Also need this. We consider it to be the pre-condition to open RC on the internet.

**Comment by rasos** [comment]
@zhouxi4oling our set up is: RocketChat server is authenticating against SAML. Users are managed with the keycloak identity provider (which mirros them to an OpenLDAP). User sign-up is managed in keycloak. keycloak has a nice 2FA feature, on Android you use e.g. FreeOTP for the token. The fairchat app (compatible to RocketChat servers) has a SAML connector (pre-configured for fairlogin, but can be customised for any other SAML identity provider).

**Comment by horstepipe** [comment]
Need to come back to this topic again.
Is there some way to check manually (e.g. somewhere in the database files) which users have enabled 2fa?
So I can talk to the users who didn't enable it yet?

**Comment by DavidVisscher** [comment]
I too would really appreciate being able to enforce two factor. Our security policies require two-factor authentication for all internet-facing systems. If there is a way to at least check if a user has it enabled, we could develop a script to inform them to enable it.

**Comment by ulope** [comment]
@horstepipe You can query directly in mongodb:
```
db.users.find({"services.totp": {$exists: true}}, {"username": 1, "_id": 0})
```
This will return a list of usernames that have totp (i.e. 2FA) enabled. To get the inverse change the `exists` condition to `false`.

(If you're running this in the mongodb shell it can be helpful to set `DBQuery.shellBatchSize = 1000` to prevent pagination.)

**Comment by horstepipe** [comment]
thank you very much @ulope 
I'll try it out

**Comment by horstepipe** [comment]
> 
> 
> @horstepipe You can query directly in mongodb:
> 
> ```
> db.users.find({"services.totp": {$exists: true}}, {"username": 1, "_id": 0})
> ```
> 
> This will return a list of usernames that have totp (i.e. 2FA) enabled. To get the inverse change the `exists` condition to `false`.
> 
> (If you're running this in the mongodb shell it can be helpful to set `DBQuery.shellBatchSize = 1000` to prevent pagination.)

Hey ulope, 
could you please give me some further guidance? I installed Rocket.Chat via snap btw.
I managed to start the mongo console, but it looks like it opens an empty database.
With db.stats() it shows

`{
        "db" : "test",
        "collections" : 0,
        "objects" : 0,
        "avgObjSize" : 0,
        "dataSize" : 0,
        "storageSize" : 0,
        "numExtents" : 0,
        "indexes" : 0,
        "indexSize" : 0,
        "fileSize" : 0,
        "ok" : 1
}`

I didn't change the port of the rocket.chat database, so shouldn't it auto-connect to it?
Any clue how I can connect to my rocket.chat database in a snap environment?

**Comment by ulope** [comment]
@horstepipe You need to select the correct db first. Use `show dbs` to get a list and then `use <db-name>` to switch to it.

**Comment by horstepipe** [comment]
> 
> 
> @horstepipe You need to select the correct db first. Use `show dbs` to get a list and then `use <db-name>` to switch to it.

thank you very much, that worked :-)

**Comment by geekgonecrazy** [comment]
#9748 implements in the UI.. but doesn't force it at api level so mobile can carry on despite being forced

**Comment by damian-centrone** [comment]
This is already implemented. Tested on IOS and windows
