### ISSUE TITLE
rocketchat.service: main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by ledainam** [RocketChat/Rocket.Chat#9236]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: Yes
* Node Version: 4.84

### Relevant logs:

> 
Dec 25 15:52:01 smchat rocketchat: Exception while invoking method 'sendMessage' WriteError({"code":11000,"index":0,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: rocketchat.rocketchat_message.$_id_  dup key: { : \"PGQYkJpRrkRxnarGT\" }","op":{"_id":"PGQYkJpRrkRxnarGT","rid":"GmC6a5KfYzdT6dCZRifiLorTjvagpp7vCY","msg":":relieved:","ts":"2017-12-25T08:52:01.339Z","u":{"_id":"GmC6a5KfYzdT6dCZR","username":"xxxx","name":"xxxx"},"mentions":[],"channels":[],"_updatedAt":"2017-12-25T08:52:01.342Z"}})
Dec 25 15:52:01 smchat rocketchat: at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
Dec 25 15:52:01 smchat rocketchat: at [object Object].<anonymous> (packages/meteor.js:209:22)
Dec 25 15:52:01 smchat rocketchat: at [object Object].MongoConnection.(anonymous function) [as insert] (/opt/Rocket.Chat/programs/server/packages/mongo.js:790:49)
Dec 25 15:52:01 smchat rocketchat: at Object.<anonymous> (packages/matb33_collection-hooks.js:395:18)
Dec 25 15:52:01 smchat rocketchat: at Object.collection.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:146:21)
Dec 25 15:52:01 smchat rocketchat: at [object Object].insert (/opt/Rocket.Chat/programs/server/packages/mongo.js:3767:38)
Dec 25 15:52:01 smchat rocketchat: at ModelsBaseDb.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:11680:54)
Dec 25 15:52:01 smchat rocketchat: at _class.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:5262:36)
Dec 25 15:52:01 smchat rocketchat: at EventEmitter.RocketChat.sendMessage (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:4107:45)
Dec 25 15:52:01 smchat rocketchat: at [object Object].Meteor.methods.sendMessage (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:15659:21)
Dec 25 15:52:01 smchat rocketchat: at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1276:26)
Dec 25 15:52:01 smchat rocketchat: at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Dec 25 15:52:01 smchat rocketchat: at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1857:12)
Dec 25 15:52:01 smchat rocketchat: at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:903:20
Dec 25 15:52:01 smchat rocketchat: at [object Object].EVp.withValue (packages/meteor.js:1134:15)
Dec 25 15:52:01 smchat rocketchat: at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:47
Dec 25 15:52:01 smchat rocketchat: at [object Object].EVp.withValue (packages/meteor.js:1134:15)
Dec 25 15:52:01 smchat rocketchat: at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:901:46
Dec 25 15:52:01 smchat rocketchat: at [object Object]._.extend.protocol_handlers.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:874:21)
Dec 25 15:52:01 smchat rocketchat: at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:753:85
Dec 25 15:52:01 smchat rocketchat: - - - - -
Dec 25 15:52:01 smchat rocketchat: at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
Dec 25 15:52:01 smchat rocketchat: at toError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
Dec 25 15:52:01 smchat rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:669:23
Dec 25 15:52:01 smchat rocketchat: at handleCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
Dec 25 15:52:01 smchat rocketchat: at resultHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:421:14)
Dec 25 15:52:01 smchat rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
Dec 25 15:52:01 smchat rocketchat: at nextTickCallbackWith0Args (node.js:489:9)
Dec 25 15:52:01 smchat rocketchat: at process._tickDomainCallback (node.js:459:13)
>  

> 
Dec 25 16:11:57 smchat kernel: node[29047]: segfault at 1bbfbfbd8318 ip 0000000000c09780 sp 00007ffccd941570 error 4 in node[400000+12e5000]
Dec 25 16:11:57 smchat systemd: rocketchat.service: main process exited, code=killed, status=11/SEGV
Dec 25 16:11:57 smchat systemd: Unit rocketchat.service entered failed state.
Dec 25 16:11:57 smchat systemd: rocketchat.service failed.
> 
i think  it maybe error related mongodb.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Can please try to reproduce this on latest stable and check, whether it might be related to #6535? I think there are already several issues talking about `E11000 duplicate key error index` so a search for error might also bring up some other things to try for you. I'll happily reopen if you find this to be different (and if so, in what way) than all the other E11000 errors :)

Cheers
Thomas
