### ISSUE TITLE
Make Admin -> Info SAME order as GitHub issues requirements to simplify issue creation

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#9238]
### Description:

When filling out a GitHub issue, the required "Server Setup Information section" (see the next section) is difficult to pick off from our Administration screen ...   Admin -> Info

Suggest to create a section in EXACT REQUIRED ORDER/FORMAT (see the next section)  to reduce friction when testing and creating  GitHub issues.

### Server Setup Information:

* Version of Rocket.Chat Server:  Version | 0.60.0-rc.5
* Operating System:  ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 6
* DB Replicaset Oplog: Yes
* Node Version:  v8.8.1

**Comment by hugocostadev** [comment]
There are some infos that are not relevant to maintainers... 
Do you still think that it's valid?

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/f9519f2f-fd4c-42c9-8abf-64fb8a3bc170)
