### ISSUE TITLE
RocketChat  sync problem with LDAP

### ISSUE THREAD

**Issue by OtavioCapila** [RocketChat/Rocket.Chat#9239]
### Description:

RocketChat didn't sync with LDAP after upgrading to 0.59.6 Docker version

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.6
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 4
* DB Replicaset Oplog:
* Node Version: v.4.8.7

### Steps to Reproduce:

1. Administration
2. LDAP
3. Sync/Import
4. Execute Synchronization Now

### Expected behavior:

Every new users in AD to sync

### Actual behavior:

No new users sync to Rocket.Chat

### Relevant logs:
 
![capturar](https://user-images.githubusercontent.com/29285724/34359929-2daa5070-ea43-11e7-9d48-282d4af3d57a.PNG)

![capturar2](https://user-images.githubusercontent.com/29285724/34359859-9d7600d0-ea42-11e7-9244-dd1874558114.PNG)

**Comment by Hudell** [comment]
Closing this old issue as the sync is working on newer versions. If there is still a problem, please include additional details.
