### ISSUE TITLE
Enabling email verification forces pre-existing accounts, even admins, to verify after log out.

### ISSUE THREAD

**Issue by doomdance** [RocketChat/Rocket.Chat#924]
This issue coupled with #766 or #911 can make for a sticky situation that requires manually editing the database to recover from. The behavior I expect would be that all existing users (or at the least, admin users) would be verified true at the time email verification is enabled.

**Comment by rwakida** [comment]
Implement #913 or observe rocketchat_settings changes

**Comment by engelgabriel** [comment]
Admin users won't be required to verify email
