### ISSUE TITLE
Support build version resource on server, client, and other artifacts

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#925]
Our CI (Continuous Integration) system will seed a 'version number' resource into the git repository prior to each build.

We need to:
* implement a server-side method to access this resource
* embed this resource into the client, and add access to it (perhaps via help or about)
* ensure other artifacts - Cordova, Electron, etc can also access and view it

**Comment by engelgabriel** [comment]
Done
