### ISSUE TITLE
Request Remove deactivated users from all rooms

### ISSUE THREAD

**Issue by imtrobin** [RocketChat/Rocket.Chat#9250]
Hi, when I deactivate a user, is it possible to have a way to unsubscribe them from all the rooms. Currently I have many rooms and I have to do it manually for every one.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
