### ISSUE TITLE
[API]How can i get the all messages to the particular channel ?

### ISSUE THREAD

**Issue by sachinrkeche** [RocketChat/Rocket.Chat#9251]
Hello Developers, 
I am fetching this API [https://ctsichat.mvoipctsi.com/api/v1/channels.history](url) GET request require parameter are X-Auth-Token="", X-User-Id="" and roomId=""  I tried this one to fetch the history of the single channel but I didn't get the expected result, in their mismatch is the documentation or I am doing something wrong? please help me out.

**Comment by graywolf336** [comment]
Best place to look is our documentation and then the source code.

https://rocket.chat/docs/developer-guides/rest-api/channels/history/

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/channels.js#L458

**Comment by sachinrkeche** [comment]
Thank you so much i got it @graywolf336 .

**Comment by graywolf336** [comment]
👍

**Comment by sachinrkeche** [comment]
I am getting the message list from "groups.history" but this API doesn't return the all messages I am trying for this one "channels.history" but this API doesn't work with the same parameter that i have been passed for "group.history" the user id which i am sending is itself of member of that channel  but, still i am getting this error when i fire this ["channels.history"]API from Postman

{
    "success": false,
    "error": "The parameter \"roomId\" or \"roomName\" is required [error-roomid-param-not-provided]",
    "errorType": "error-roomid-param-not-provided"
}
