### ISSUE TITLE
 Kick user from Channel not possible- options missing

### ISSUE THREAD

**Issue by marzie82** [RocketChat/Rocket.Chat#9254]
### Description:
Removing user from existing Channel is not possible. Klicking on "Userslist" and choosing User starts a converstation instead off showing Menu with options.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: Linux (ubuntu 16.04.)
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances:  1
* DB Replicaset Oplog: yes
* Node Version: Linux

### Steps to Reproduce:
1. Open any channel, klick on members list
2. choose a member you like to remove
3. menu with options does not appear

### Expected behavior:

1. Open any channel, klick on members list
2. choose a member you like to remove
3. see menue with possibility to remove user from current channel

### Actual behavior:

nothing, by choosing a member Rocket.Chat jumps to a new conversation
### Relevant logs:
![expected](https://user-images.githubusercontent.com/33508334/34383043-06ae90dc-eb13-11e7-8307-fcb3b5377bc3.jpg)

**Comment by marzie82** [comment]
The screenshot shows the expected screen when I try to remove a User from A Channel- this screen I don't get with my installation. Trying with rocket.chat works well.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

This is an administrative option under Layout > "User Interface: "Click to create direct message" (at the bottom)

![image](https://user-images.githubusercontent.com/179595/40208980-fe6ccba2-5a3c-11e8-85e0-6992be142a84.png)

Cheers
Thomas
