### ISSUE TITLE
The custom logo does not show

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#9261]
### Description:

**I have specified the custom logo and favicon files but rocketchat shows the default ones.**

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu 
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: none 
* Node Version: 4.8.4

**Comment by TwizzyDizzy** [comment]
Would you care to test this again on the latest release 0.60.1?

Cheers
Thomas

**Comment by zxweed** [comment]
Sure, but there are another problem in the 0.60.1 - it won't run, https://github.com/RocketChat/Rocket.Chat/issues/9275

**Comment by TwizzyDizzy** [comment]
Now that #9275 got solved, any news on that on the current stable version? :)

Cheers
Twizzy

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this due to lack of feedback.

Cheers
Thomas
