### ISSUE TITLE
Android App whitescreen after snap upgrade to .60

### ISSUE THREAD

**Issue by caesarcxiv** [RocketChat/Rocket.Chat#9265]
### Description:

Snap updated to .60 and Android client is unusable. Client is completely white after the "loading ... " screen.

Attempted uninstall / reinstall of android client from play store.

### Server Setup Information:

* Version of Rocket.Chat Server: .60
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.3

### Client OS
Android 8.1 

### Steps to Reproduce:

1. Run .6 in snap
2. Download android app from play store
3. enter rocket url, files download, white screen.

### Expected behavior:

App works

### Actual behavior:

White screen

### Relevant logs:
34mMeteor ➔ publish null -> userId: null , arguments:  {} 
logged under debug on server everytime app is opened

**Comment by ledainam** [comment]
I have same issue. Pls help us to fis this.

**Comment by pkostiuk** [comment]
Same issue here but running 0.60 in Docker.

**Comment by caesarcxiv** [comment]
Stumbled accross this and downloaded rocketchat+

Issue fixed. I would recommend the play store description be updated to point users to the new client.

https://forums.rocket.chat/t/rocket-chat-vs-rocket-chat/35/2

**Comment by rodrigok** [comment]
@caesarcxiv We are planing to make the native apps the official ones soon.

**Comment by robertwessen** [comment]
rocketchat+ does not correct the issue for us (and others)
https://github.com/RocketChat/Rocket.Chat/issues/9270

**Comment by robbyoconnor** [comment]
@rodrigogs RocketChat+ hasn't worked for us yet.

**Comment by rodrigok** [comment]
@robbyoconnor I just released a new (2.6.0) version of our cordova app for Android, can you test it?

@rafaelks can you check why Rocket.Chat+ is not working?

**Comment by rafaelks** [comment]
@rodrigok It is working. @robbyoconnor issue was replied [here](https://forums.rocket.chat/t/rocket-chat-vs-rocket-chat/35/19?u=rafaelks) already.

**Comment by Horgix** [comment]
Same issue here: total whitescreen after update, the Android application is totally unusable because of this :(

* Android version: `4.4.3`
* RocketChat version: `0.62.2`
* RocketChat mobile version : `2.7.0`

**Comment by geekgonecrazy** [comment]
Closing.  Cordova apps completely deprecated
