### ISSUE TITLE
Redirected to /home when marking message as unread via reaction menu

### ISSUE THREAD

**Issue by pettitto** [RocketChat/Rocket.Chat#9267]
When using the 'reaction' option in a chat, there's an option for "Mark as Read" when an unread message is displayed, if I use this in any room on any unread message, I get immediately redirected back to <example url>: rocket.chat/home

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60
* Operating System: Stretch
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* Node Version: v8.8.1

### Steps to Reproduce:

1. Find an unread message in a chat room
2. Locate the 'react' option and press the three dots
3. Press "Mark as UnRead"

### Expected behavior:

Unread message banner is removed and remain in chat room

### Actual behavior:

Unread banner is removed, then redirected to /home

**Comment by TwizzyDizzy** [comment]
I can confirm this behaviour on 0.60.1.

Cheers
Thomas

**Comment by rodrigok** [comment]
@pettitto @TwizzyDizzy Can you show me where did you find the `Mark as Read` menu? Maybe a screenshot?

**Comment by TwizzyDizzy** [comment]
@rodrigok there you go - I use "Mark as unread", yet it's the same as if this was an unread message and I wanted to mark it as read.

![ezgif-3-56a5f168b8](https://user-images.githubusercontent.com/179595/34419307-523b9540-ec03-11e7-9e72-0a1781cdddb6.gif)

Cheers
Thomas

**Comment by pettitto** [comment]
Thanks @TwizzyDizzy - was just about to post back with one!

**Comment by rodrigok** [comment]
@pettitto @TwizzyDizzy I wasn't able to find the option to mark as **read** in message's menu

**Comment by pettitto** [comment]
Let me get another example tomorrow (UK) time, and see if we can understand what’s causing the behaviour.

**Comment by TwizzyDizzy** [comment]
Don't wanto to scramble, but might this be also a privilege-related issue in terms of that you're not allowed that function, or a server option or a user preference?

Cheers
Thomas

**Comment by pettitto** [comment]
So, from a bit more digging, it actually happens when you mark a message as "Unread" - sorry for the confusion.

**Comment by rodrigok** [comment]
@pettitto That was what I thought 😄 

So, that is the correct behavior, since you mark as unread you need to leave the room to not mark as read again by activity.

Do you have a better suggestion for that?

**Comment by pettitto** [comment]
Ah - sorry!

I can understand why the behaviour works in this way since a message is marked as "read" once you get into a room/channel.

I think the functionality works fine as it is. I was thinking of how we might be able to add an "acknowledge" button if you wanted to mark a message as unread but stay in the room.

I realised that actually, the functionality that's there is correct and I am probably thinking more about how we might be able to "flag" a message that you might want to come back to easily/quickly later.

Hope that makes sense?

Anyhow, I'll close this as it's not an issue as discussed.

**Comment by TwizzyDizzy** [comment]
> So, that is the correct behavior, since you mark as unread you need to leave the room to not mark as read again by activity.

Ah... well... from that perspective it makes sense, indeed. Could have seen this coming ^^ ...

> I am probably thinking more about how we might be able to "flag" a message that you might want to come back to easily/quickly later

Well that, I assume, is the intended function of **starring** a message - so that's already possible.

Cheers
Thomas
