### ISSUE TITLE
where can I find the API codes for the iOS/Android

### ISSUE THREAD

**Issue by edisonchen1985** [RocketChat/Rocket.Chat#9268]
Dear all, it's our great honor to use this amazing Rocket.Chat application. Right now we are trying to work on the iOS/Android native Rocket.Chat to add more features on them to somehow match with the Cordova version. 

The issue is we are quite new to Meteor/Rocket.Chat system, we really can not figure out where is the API codes? Can anybody help to tell us where can we change/add the codes for native iOS/Android? 
Are they under the folder server/methods?
Thanks!

**Comment by rodrigok** [comment]
@edisonchen1985 It depends on what you want to add, can you describe it better?

**Comment by edisonchen1985** [comment]
@rodrigok  thanks a lot for your reply. For example when the native iOS/Android code calls `subscriptions/get` , the server response back a json object, right now we want to do sth before it return the json object, but we can not find where can we add the codes. (we can not find in which file is the  `subscriptions/get` in?) 
Thanks a lot for further reply!

**Comment by rodrigok** [comment]
@edisonchen1985 With a quick search here https://github.com/RocketChat/Rocket.Chat/search?utf8=%E2%9C%93&q=subscriptions%2Fget&type= you are able to find the correct file, will be the 3rd result `server/publications/subscription.js` at line 35

**Comment by rodrigok** [comment]
Is that what you need? Can I close this issue?

**Comment by edisonchen1985** [comment]
@rodrigok Sorry for my late response. It looks like that is what I am looking for. I will double check with my colleagues when the holiday is over. Thank you very much for the help and Happy New Year to you.
