### ISSUE TITLE
Livechat return conversation to the pool if agent goes offline

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#9278]
### Description:
Currently if an agent goes offline you can only choose to close his opened livechats or forward them. Would be nice to have an option to send it back to the pool (when using Guest Pool routing method), so any other online agent can take it.

**Comment by josep112** [comment]
After finishing a conversation in Livechat, the return until the call returns but does not release the chat to enter the message. Version Rocketchat 0.74

**Comment by renatobecker** [comment]
@josep112, can you please open a new issue describing the steps to reproduce this case?
Thanks.

**Comment by josep112** [comment]
Renatobecker ok!
