### ISSUE TITLE
LDAP Sync: final batch not processed (without pagination)

### ISSUE THREAD

**Issue by sscholl** [RocketChat/Rocket.Chat#9279]
### Description:

I use LDAP without pagination (by setting LDAPP_Search_Page_Size to 0), because my LDAP Server is not able to provide pragination. When I use the LDAP Sync Feature (by hand or by cronjob), 500 users are imported at maximum. I guess this is because of the missing pagination feature, but my LDAP sends all ~800 users.

Can you increase the default value or make it configurable? 

Thank you!!!

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.1
*  Database Migration: 105
* Operating System: linux 3.10.0-693.el7.x86_64 x64
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* Node Version: v8.9.3

### Steps to Reproduce:

1. Configure LDAP with more than 500 users
2. set LDAPP_Search_Page_Size to 0
3. set Search_Size_Limit to 1000
4. Execute LDAP_Sync_Now

### Expected behavior:

All LDAP Users shoud be imported (more than 500).

### Actual behavior:

Only 500 users are imported.
After log message ```LDAPSync ➔ info Import running. Users imported until now: 500``` import stops.

### Relevant logs:
```20171229-11:58:44.846(0) rocketchat_logger rocketchat_logger.js:278 LDAPSync ➔ info Import running. Users imported until now: 500```

**Comment by rodrigok** [comment]
@sscholl There is no hard limit in our code.

Was it working before version 0.60? Could it be a hard search limit in your LDAP server configuration?

**Comment by rodrigok** [comment]
We tested imports with more then 200.000 users with and without pagination.

**Comment by sscholl** [comment]
@rodrigok  Thanks for your answer! I can see, that my LDAP is returning ~800 users, so my guess here is Rocket.Chat. I see the value 500 for example here in the source code:
https://github.com/RocketChat/Rocket.Chat/blob/e2c0fc958c85c796a8e111b3eb060645336bfcde/packages/rocketchat-ldap/server/ldap.js#L389

Or is it possible, that I have a problem with asynchronous jobs?

**Comment by rodrigok** [comment]
@sscholl That's the internal batch control, is not related with LDAP pagination.

But I found the error, it's not processing the final results of the final batch, I'll fix ASAP, release a new version and let you know.

Thanks

**Comment by sscholl** [comment]
Very nice!!! Thank you :)
