### ISSUE TITLE
Setting "Collapse Embedded Media by Default" to false doesn't allow for YouTube Previews to show up clicking the arrow

### ISSUE THREAD

**Issue by JoeArcher007** [RocketChat/Rocket.Chat#9282]
### Description:

If "Collapse Embedded Media by Default" is enabled in user's preferences, clicking the '>' beside a link doesn't open the preview / collapsed media. It will not open and cannot be opened. This is true for YouTube links as well.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0 (Has been happening for a bit I believe)
* Operating System: Ubuntu 17.10 Server
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled? (I can't find other info for this at the moment.)
* Node Version: v8.9.3

### Steps to Reproduce:

1. Enable the Collapse Embedded Media by Default option in User Preferences
2. Try to check a preview for a YouTube link, or other web page. It should be collapsable and work
3. Disable the same option 'Collapse Embedded Media by Default'
4. Try it again, and you cannot open the YouTube link.

I will also state in my environment, it looks like other links actually are not collapsed with this option. But that my be my instance as well.

### Expected behavior:

With the option set, it should still allow for links to be opened within to show a preview or the embedded YouTube video.

### Actual behavior:

You can't click on the YouTube '>' and show the preview. It will not open.

### Relevant logs:

I couldn't find any errors in Browser Logs.

[34mI20171229-10:50:56.455(-5) [34mMeteor ➔ publish null -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.480(-5) [34mMeteor ➔ method autoTranslate.getSupportedLanguages -> userId: null , arguments:  { '0': 'en' } 
[34mI20171229-10:50:56.482(-5) [34mMeteor ➔ method listCustomSounds -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.484(-5) [34mMeteor ➔ method listEmojiCustom -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.488(-5) [34mMeteor ➔ publish roles -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.490(-5) [34mMeteor ➔ publish stream-importers -> userId: null , arguments:  { '0': 'progress', '1': { useCollection: false, args: [] } } 
[34mI20171229-10:50:56.493(-5) [34mMeteor ➔ publish meteor_autoupdate_clientVersions -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.495(-5) [34mMeteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'updateCustomSound',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:50:56.497(-5) [34mMeteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'deleteCustomSound',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:50:56.498(-5) [34mMeteor ➔ publish activeUsers -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.500(-5) [34mMeteor ➔ publish userData -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.502(-5) [34mMeteor ➔ method public-settings/get -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.517(-5) [34mMeteor ➔ publish stream-notify-all -> userId: null , arguments:  { '0': 'public-settings-changed',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:50:56.519(-5) [34mMeteor ➔ method permissions/get -> userId: null , arguments:  {} 
[34mI20171229-10:50:56.565(-5) [34mMeteor ➔ method UserPresence:online -> userId: null , arguments:  { '0': null } 
[34mI20171229-10:51:14.023(-5) [34mMeteor ➔ publish roles -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.024(-5) [34mBaseCache ➔ debug rocketchat_roles Falling back _publishCursor to model with query: undefined 
[34mI20171229-10:51:14.029(-5) [34mMeteor ➔ publish stream-importers -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'progress', '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.029(-5) [34mMeteor ➔ publish meteor_autoupdate_clientVersions -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.033(-5) [34mMeteor ➔ publish stream-notify-all -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'updateCustomSound',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.034(-5) [34mMeteor ➔ publish stream-notify-all -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'deleteCustomSound',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.035(-5) [34mMeteor ➔ publish activeUsers -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.036(-5) [34mBaseCache ➔ debug users Falling back _publishCursor to model with query: { username: { '$exists': 1 },   status: { '$in': [ 'online', 'away', 'busy' ] } } 
[34mI20171229-10:51:14.037(-5) [34mMeteor ➔ publish userData -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.038(-5) [34mBaseCache ➔ debug users Falling back _publishCursor to model with query: Xau8ijAzdKwiqJv8K 
[34mI20171229-10:51:14.039(-5) [34mMeteor ➔ publish stream-notify-all -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'public-settings-changed',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.041(-5) [34mMeteor ➔ publish null -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.152(-5) [34mMeteor ➔ publish stream-notify-logged -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Users:NameChanged',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.170(-5) [34mMeteor ➔ publish stream-notify-logged -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'updateEmojiCustom',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.172(-5) [34mMeteor ➔ publish stream-notify-logged -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'deleteEmojiCustom',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.175(-5) [34mMeteor ➔ publish stream-notify-logged -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'updateAvatar', '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.177(-5) [34mMeteor ➔ publish stream-notify-logged -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'permissions-changed',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.178(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/message',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.180(-5) [34mMeteor ➔ publish userData -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.180(-5) [34mBaseCache ➔ debug users Falling back _publishCursor to model with query: Xau8ijAzdKwiqJv8K 
[34mI20171229-10:51:14.182(-5) [34mMeteor ➔ publish activeUsers -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.183(-5) [34mBaseCache ➔ debug users Falling back _publishCursor to model with query: { username: { '$exists': 1 },   status: { '$in': [ 'online', 'away', 'busy' ] } } 
[34mI20171229-10:51:14.184(-5) [34mMeteor ➔ method getUserRoles -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.186(-5) [34mMeteor ➔ publish stream-notify-logged -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'roles-change', '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.188(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/otr',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.189(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/webrtc',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.192(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/notification',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.194(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/audioNotification',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.195(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/subscriptions-changed',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.200(-5) [34mMeteor ➔ method rooms/get -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:14.205(-5) [34mMeteor ➔ publish stream-notify-user -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': 'Xau8ijAzdKwiqJv8K/rooms-changed',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:14.206(-5) [34mMeteor ➔ method subscriptions/get -> userId: Xau8ijAzdKwiqJv8K , arguments:  {} 
[34mI20171229-10:51:24.601(-5) [34mMeteor ➔ method loadHistory -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y',   '1': null,   '2': 50,   '3': 2017-12-29T15:32:47.470Z } 
[34mI20171229-10:51:24.603(-5) [34mMeteor ➔ method canAccessRoom -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y', '1': 'Xau8ijAzdKwiqJv8K' } 
[34mI20171229-10:51:24.606(-5) [34mMeteor ➔ publish stream-room-messages -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:24.607(-5) [34mMeteor ➔ method canAccessRoom -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y', '1': 'Xau8ijAzdKwiqJv8K' } 
[34mI20171229-10:51:24.615(-5) [34mMeteor ➔ publish stream-notify-room -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y/deleteMessage',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:25.085(-5) [34mMeteor ➔ method getRoomRoles -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y' } 
[34mI20171229-10:51:25.120(-5) [34mMeteor ➔ publish stream-notify-room -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y/typing',   '1': { useCollection: false, args: [] } } 
[34mI20171229-10:51:25.124(-5) [34mMeteor ➔ publish stream-notify-room -> userId: Xau8ijAzdKwiqJv8K , arguments:  { '0': '9Y3MsDRN4jBySRG5y/webrtc',   '1': { useCollection: false, args: [] } }

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "type: bug"

Just reproduced this as stated above in 0.64.1.

Cheers
Thomas
