### ISSUE TITLE
wish: don't use error color just for marking messages (.first-unread)

### ISSUE THREAD

**Issue by wemu** [RocketChat/Rocket.Chat#9287]
In around version 0.60 there is a new marker for unread messages. It seems to use the error color:

https://github.com/RocketChat/Rocket.Chat/blob/d7e0e70c3700d53de2b965b1b948cce1fce3dfad/packages/rocketchat-theme/client/imports/general/base.css#L132

But unread messages are not an error (in my opinion). Please use an own css name and don't re-use names that have a different purpose. 

I also find it hard using the Chrome Dev Tools to overwrite these ::before and ::after styles in the custom css settings.

**Comment by HammyHavoc** [comment]
Couldn't agree more!

**Comment by MartinSchoeler** [comment]
We are currently refactoring most of the ui to react, so this will be probably fixed by then, for now I'll close this. Thanks!
