### ISSUE TITLE
Capitalize the 'U' and 'M' of 'unread messages'

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#9292]
Capitals are used everywhere else in the UX, introducing lowercase looks really out of place and messy.
<img width="704" alt="unred 2" src="https://user-images.githubusercontent.com/503951/34448929-6c91ff0a-ecea-11e7-90c4-7fdbaa764170.PNG">

**Comment by HammyHavoc** [comment]
<img width="331" alt="um" src="https://user-images.githubusercontent.com/503951/34472786-61064a46-ef61-11e7-99cf-32032489417c.PNG">

**Comment by ggazzo** [comment]
as @thiagosanchz said: 
> @HammyHavoc Thanks for your feedback, we'll working on our message components and we'll need to review our rules to UX write.
