### ISSUE TITLE
Cannot update mongodb port 

### ISSUE THREAD

**Issue by BlessBau** [RocketChat/Rocket.Chat#9294]
I changed my mongodb port to 28182
updated my environment 
```
MONGO_URL=mongodb://127.0.0.1:28182/adaptive
ROOT_URL=http://localhost/
PORT=3121
MONGO_OPLOG_URL=mongodb://localhost:28182/local
```
For some reason, rocket chat is still trying to connect using the port 27017

**Comment by jszaszvari** [comment]
How did you update your environment? 

if you are on linux you need to run 

export MONGO_URL=mongodb://127.0.0.1:28182/adaptive

not just

MONGO_URL=mongodb://127.0.0.1:28182/adaptive

How are you starting the app?

**Comment by geekgonecrazy** [comment]
Closing due to no response
