### ISSUE TITLE
[BUG] Sorting of usernames is case-sensitive

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#9295]
Usernames can be chosen as mixed case strings, which results in an order of usernames like following (sidebar):
A
B
C
a
b
c

They should be up or downcasted before sorting.

**Comment by graywolf336** [comment]
This is because we use JavaScript's default sort: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by rafaelks** [comment]
This is causing this weird sorting.

![2018-04-03 15 39 58](https://user-images.githubusercontent.com/551004/38268854-7e1d36da-3755-11e8-8701-f72c5f9de88a.gif)
