### ISSUE TITLE
For (private) rooms, allow non-creator to add people to the room

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#930]
Right now only whoever created a private room can invite others to join it. It would ease our lives a lot if we could let 1) every current member invite others, or 2) let the creator grant one or more others the privilege to do so.
##

**Comment by mhkeller** [comment]
+!

**Comment by declankenny** [comment]
Every user to private room relationship could be defined with a type, Room Manger or Room Member. 
* The person who creates the room defaults to a Manager.
* A Manager can add other users, who default to Members.
* A Manager can promote a Member to be a Manager.
* A Manager can demote a Manager to be a Member, with the caveate that after the demotion there must be at least one remaing Manager.

**Comment by sinteur** [comment]
Why not just make it possible to have all current users add people by default  - keep it simple

**Comment by declankenny** [comment]
Thinking a little more about this. User permissions at the room level would also address #825 by having a reader permission, as opposed to writer. Also the room owner/manager should be able to set the default permission for new memebes to any permission level.
This would allow a room owner/manager to make a room 'read only', default role = reader, while allowing select members to have write access.

**Comment by mrogaski** [comment]
You could create a set of invite permissions (invite_c, invite_p, etc)  and assign those to roles.  

But, having the ability to add overrides to the role permissions at the channel level would be great.  We would like to allow users to create and delete rooms, but there are channels that we want to lock down (i.e. #general, etc).

**Comment by jkot** [comment]
👍

**Comment by s19n** [comment]
+1

**Comment by palicand** [comment]
+1

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
