### ISSUE TITLE
Sound notification when window is focused

### ISSUE THREAD

**Issue by megamaced** [RocketChat/Rocket.Chat#9302]
I would like an option under My Account - Preferences to set Rocketchat to do a sound notification on messages even when the Rocketchat app window is in focus - like Pidgin does.

**Comment by armand1m** [comment]
Okay, this seems fairly easy to implement.

**Comment by armand1m** [comment]
Lets see what the team thinks about this feature, it would be nice to hear some options before starting working on it.

**Comment by megamaced** [comment]
theres a bounty on it of $100 :-D

**Comment by RationalCoding** [comment]
It's there if you decide you want it.

**Comment by megamaced** [comment]
Cool, but I am not sure there is a need to have a different sound when the window is in focus? I was thinking more just a simple check box that enables the same sound notification when the Rocketchat app is in focus

**Comment by megamaced** [comment]
Here is an example of the Preferences in Pidgin that enable sound on window focus

![image](https://user-images.githubusercontent.com/22581049/34516901-b2dfc17a-f070-11e7-9cc5-2057a154d953.png)

**Comment by RationalCoding** [comment]
The name of that preference on Pidgin (at least to me) seems to imply that notification sounds will/won't play when the window is focused.

**Comment by RationalCoding** [comment]
How about an option: "Mute sounds when window is unfocused".

Or maybe: "Mute sounds when window is focused" ?

**Comment by megamaced** [comment]
The default would be off, so the toggle should say "Enable sound notification when window is focused"

**Comment by RationalCoding** [comment]
That doesn't quite fit. How about "Mute Focused Conversations" in the sounds section

**Comment by megamaced** [comment]
Your suggestion is the opposite of mine, so your suggestion would require the default settinng to be enabled and my suggestion requires the default to be disabled in order to replicate the current behaviour. So i dont think it makes much difference either way, so long as the user has a way to make the application still make notification sounds when its the active in focus window. Whats most important is getting it merged :-D

**Comment by RationalCoding** [comment]
Alright, I've implemented that then. Sorry I misunderstood you the first time. This seems quite useful for users with multiple monitors (or who make RocketChat very small), since they have the window focused but may not have noticed new messages.

**Comment by megamaced** [comment]
Our users have 5 monitors :-)

**Comment by RationalCoding** [comment]
Is the team interested in merging this? If not, is it possible to implement it as an extension/plugin?
