### ISSUE TITLE
deleted users are still listed as "favorite rooms"

### ISSUE THREAD

**Issue by childnode** [RocketChat/Rocket.Chat#9304]
### Description:

deleted users are still listed as "favorite" rooms
perhaps related to #9157

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: irrelevant
* Deployment Method(snap/docker/tar/etc): irrelevant
* Number of Running Instances: irrelevant
* DB Replicaset Oplog: irrelevant
* Node Version: irrelevant

### Steps to Reproduce:

1. create 2 users
2. login as user1
3. begin chat with user2
4. mark private chan as "favorite"
5. delete user2

### Expected behavior:
6. user2 disappears from "rooms" list

### Actual behavior:
6. still see "user2" as "room" in sidebar favorites

**Comment by geekgonecrazy** [comment]
see: #6535 once fixed should solve your problem
