### ISSUE TITLE
issues compiling

### ISSUE THREAD

**Issue by LiuSuY** [RocketChat/Rocket.Chat#9305]
![image](https://user-images.githubusercontent.com/25116549/34485076-9cffd95c-f003-11e7-9d8b-a071f9bafa9a.png)

**Comment by geekgonecrazy** [comment]
did you modify files in .meteor/build directly?

**Comment by MIKNOTAURO** [comment]
I'm getting something similar when I try to make the bundle
this is part of my  traceback

meteor build --server "http://localhost:3000" --directory ../

**********************************
/home/miknotauro/.meteor/packages/meteor-tool/.1.6.0_1.1cy0n0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
SyntaxError: Unexpected token < in JSON at position 55214
....
any help/advise?

**Comment by geekgonecrazy** [comment]
is this with modifications done to the code or a fresh checkout from develop?

**Comment by MIKNOTAURO** [comment]
@geekgonecrazy with a fresh checkout from develop I'm getting this ->

meteor build --server "http://localhost:3000" --directory ../
*******************

postcss-custom-properties: /home/dev/MeteorJS/services/Rocket.Chat/packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css:151:3: variable '--sidebar-header-small-padding' is undefined and used without a fallbackpostcss-custom-properties: /home/dev/MeteorJS/services/Rocket.Chat/packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css:151:3: variable '--sidebar-header-small-padding' is undefined and used without a fallback
************
And it's also the same error with fresh checkout from latest tag (0.60.3)

**Comment by geekgonecrazy** [comment]
hm... seems like something is up with your dev environment.  

Did you follow this: https://rocket.chat/docs/developer-guides/quick-start/

**Comment by MIKNOTAURO** [comment]
Finally, I was able to make the build, but the issue is still there.
***********
npm ERR! Cannot read property '0' of undefined

postcss-custom-properties: /home/miknotauro/Documents/Projects/MeteorJS/ChatService_CA/Oct217/Rocket.Chat_CA/packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css:151:3: variable '--sidebar-header-small-padding' is undefined and used without a fallbackpostcss-custom-properties: /home/miknotauro/Documents/Projects/MeteorJS/ChatService_CA/Oct217/Rocket.Chat_CA/packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css:151:3: variable '--sidebar-header-small-padding' is undefined and used without a fallback 
***************
 I've already tried some different enviroments
My actual env is:
meteor 1.6.0.1
node 8.9.3
npm 5.6.0

which one should I use?

**Comment by LiuSuY** [comment]
If it is possible to suggest you use it in Ubuntu, it will take about 20 minutes to run. I've been running on Windows 10, and I've been through a lot of hopelessness, and I've had a slow, slow process, and I'm going to crash on 谷歌-version, service.js, and atob. Js, and I hope to help you.

**Comment by geekgonecrazy** [comment]
Look like on some sort of *nix OS.  

I'll I can think is must have some dependencies somewhere that are incorrect. 

Make sure you clone, `meteor npm i` before you do `meteor build`

**Comment by LiuSuY** [comment]
Maybe, as you said, it's a bit of a problem at compile time.

**Comment by MIKNOTAURO** [comment]
@geekgonecrazy I already did... I read on some posts that could be my npm version ( apparently, is a knowing issue in some projects) ... and they solved it switching to yarn...I've never tried yarn though, but I'm wondering how difficult would be make this change on my repo?

**Comment by LiuSuY** [comment]
I tried to use yarn or cnpm to still not solve this problem. I think it was the default location of the package manager at run time. good luck

**Comment by MIKNOTAURO** [comment]
@geekgonecrazy
Hey Guys,
I've been trying different environments, even a clean linux ubuntu xenial installation but I'm still getting this

postcss-custom-properties: /home/ubuntu/Rocket.Chat/packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css:151:3: variable '--sidebar-header-small-padding' is undefined and used without a fallback

Have you  tried to make the build with this environment?

**Comment by geekgonecrazy** [comment]
@rodrigok @karlprieb either one of you have ideas here?  I tried locally and no issues

**Comment by LiuSuY** [comment]
My successful operation is such a hope to help you

Step 1 git clone https://github.com/RocketChat/Rocket.Chat.git

ExpressVPN on the step 2 link

Step 3 NPM install

Step 4 meteor

I don't think expressVPN is necessary here, because my network problem uses expressVPN. When the GIT clone project comes down, the direct meteor start can be executed step by step in the environment of the node4.8.4 version if there is a mistake. I usually meet these mistakes ["chromedriver@2.34.1", "PhantomJS", "rocketchat:google-vision", "less@2.7.9"].

![2018-01-17 10-16-35](https://user-images.githubusercontent.com/25116549/35022229-c014c480-fb6f-11e7-9038-3926ba4bf382.png)
![2018-01-17 10-19-52](https://user-images.githubusercontent.com/25116549/35022314-46c99ef6-fb70-11e7-804d-af3db681f559.png)
![2018-01-17 10-21-05](https://user-images.githubusercontent.com/25116549/35022315-48dcdeba-fb70-11e7-8eaf-9ca97fb1a748.png)

All dependencies downloaded to complete the execution of meteor
If meteor is wrong after execution, I think it depends on the packet error and deletes the local reinstall dependency under the node_modules and.Meteor
