### ISSUE TITLE
Can I use my existing OneSignal account to route the rocket.Chat push messages?

### ISSUE THREAD

**Issue by murilo-yoshida** [RocketChat/Rocket.Chat#9308]
### Description:

On our current setup, Rocket.Chat is no longer delivering PUSH messages to the mobile devices.
Reason is not certain but I believe it to be linked with the amount of notifications sent, we must have passed the allowed quota.
We have a OneSignal API account for our apps and we would like to use it as a notification gateway.

The PUSH notification gateway is unclear as to whether OneSignal would serve as a push gateway out of the box or whether we would need to develop a proxy gateway.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.3
* Operating System: debian (linux 3.16.0-4-amd64)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 3
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Go to Administration -> Push
2. Click on "SEND A TEST PUSH TO MY USER"
3. A message appears: 
"Success
Your push message was sent to 3 devices."

### Expected behavior:

A test push message received on my device (any of them)

### Actual behavior:

No push message arrives

### Relevant logs:
No relevant logs or errors on the browser were observed.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
