### ISSUE TITLE
Document Url in Outgoing Webhook

### ISSUE THREAD

**Issue by amonemian** [RocketChat/Rocket.Chat#9315]
How can I view my document url( for example my image_url) in outgoing webhook script?

I have read the integration document [here](https://rocket.chat/docs/administrator-guides/integrations/), but there is no sufficient information about request data.
The only available items are:

 // request.params            {object}
    // request.method            {string}
    // request.url               {string}
    // request.auth              {string}
    // request.headers           {object}
    // request.data.token        {string}
    // request.data.channel_id   {string}
    // request.data.channel_name {string}
    // request.data.timestamp    {date}
    // request.data.user_id      {string}
    // request.data.user_name    {string}
    // request.data.text         {string}
    // request.data.trigger_word {string}

Thanks,

**Comment by AmShaegar13** [comment]
What exactly do you mean by document url? This is all you get. You can easily log to console what's in `request` with this script:

```
class Script {
  prepare_outgoing_request({ request }) {
    console.error(JSON.stringify(request, null, 2));
  }
}
```

```
1|rocket.c | 2018-01-03 13:00:56 584: {
1|rocket.c |   "params": {},
1|rocket.c |   "method": "POST",
1|rocket.c |   "url": "http://localhost",
1|rocket.c |   "data": {
1|rocket.c |     "token": "******",
1|rocket.c |     "bot": false,
1|rocket.c |     "channel_id": "******",
1|rocket.c |     "message_id": "******",
1|rocket.c |     "timestamp": "2018-01-03T12:00:56.556Z",
1|rocket.c |     "user_id": "******",
1|rocket.c |     "user_name": "******",
1|rocket.c |     "text": "Foo",
1|rocket.c |     "alias": "Finn Glöe"
1|rocket.c |   },
1|rocket.c |   "npmRequestOptions": {
1|rocket.c |     "rejectUnauthorized": true,
1|rocket.c |     "strictSSL": true
1|rocket.c |   },
1|rocket.c |   "headers": {
1|rocket.c |     "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36"
1|rocket.c |   }
1|rocket.c | }
```

**Comment by graywolf336** [comment]
Closing due to @AmShaegar13's comment and because we need more information. All the information can be viewed via the console. We welcome pull requests for the documentation per each type.

**Comment by amonemian** [comment]
Thank you @AmShaegar13. 
It is useful if the sent item is a text like "foo". The problem is when you send an image into rocket chat.
As you can see, there is no evidence of the sent photo(image_url) or sth else.

**Comment by AmShaegar13** [comment]
That's correct. All you get ist `"text": "Uploaded an image"`. Looks like this currently not supported.

**Comment by amonemian** [comment]
@AmShaegar13  any suggestion to have access to image_url or attachment?

**Comment by AmShaegar13** [comment]
You might be able to access the image_url of a given message using the REST API. But I didn't try it.

**Comment by graywolf336** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/f82e5723dfd5abd618a72e8827670b4d4ce100da/packages/rocketchat-integrations/server/lib/triggerHandler.js#L378-L398

If you're wanting the file upload, then use the event for the file upload as it has all the information about file uploads.

**Comment by amonemian** [comment]
Thank you @graywolf336 , but again the problem exists. Even uploading a photo, just trigger the "sendMessage" event, not "fileUploded" event. No evidence of file or image info.

**Comment by amonemian** [comment]
Thank you @graywolf336 

I am trying to set webhooks for my rocketchat, but I can trigger that for "User Created" mode. (all other types are ok).

I think it might be related to the "Target Room" setting, which I tried different states (@admin, #general , ...)
but unfortunately I could not get the webhook message.
