### ISSUE TITLE
Automatically delete attached files

### ISSUE THREAD

**Issue by Foremi** [RocketChat/Rocket.Chat#9317]
I’d like to recommend implementing an option regarding file upload, that allows all attachments to be deleted after a certain amount of time. For example: every file that is older than 14 or 30 days would be deleted from all channels on the server. Furthermore, it would be advantagous to have an option that allows a maximum number of uploaded files, and if the users upload more files than allowed, the oldest file will be deleted. Rright now all uploaded files are stored on the server, it takes up a lot of space in the long run. Furthermore, attachments from private conversations cannot be deleted, so some users can take up GBs of space. Thank you very much.

**Comment by Nosferous** [comment]
Yes please!!! My staff is needing more attachment demand in terms of max file size allowed, the compromise is I'm going to set a policy to delete their attachments after X days. It would be fantastic to have these features to automatically do this in a best practice routine.
