### ISSUE TITLE
Webhook CRUD API

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#9318]
Our webhook code is maintained in git, then I have to do something like `cat rocketchat-github.js |xsel -b` then paste it into whichever integrations are relevant. It would be great if I could script this by calling the REST API.

**Comment by graywolf336** [comment]
Is this an incoming or outgoing webhook? As they both have rest apis.

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/api/api.js#L321

OR

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/integrations.js

**Comment by antgel** [comment]
@graywolf336 Thanks. I read the documentation and I didn't find it there. :)

**Comment by graywolf336** [comment]
Did any of them help you out?
