### ISSUE TITLE
"unread messages" line does not vanish

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#9319]
Hi Devs.

Just upgraded to 0.60.2. MacOS App 2.10.1.

My Problem. The recently red "unread messages" line does not vanish anymore. I scrolled the chatroom the "unread messages" message appears in manytimes up and down. Known issue?

thanks and cheers

**Comment by himbeere** [comment]
![bildschirmfoto 2018-01-03 um 17 33 34](https://user-images.githubusercontent.com/631865/34529444-454044dc-f0ac-11e7-9b51-e9cf6d0ec6e3.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close 

This should be fixed in 0.61.0

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat open.

Sorry - I just reproduced this on 0.61.1, too.

Cheers
Thomas

**Comment by pzgz** [comment]
Also can reproduce in 0.62.0-develop, commit hash: b288eeb86a76360ee8069dbfc9103cc8886e1a56, I am using develop branch.

The unread messages line won't disappear unless you send message in that channel.

**Comment by richardwlu** [comment]
I am on 0.63.2 and this is happening for us where the user needs to send a message or go to another chatroom for it to disappear. Scrolling up to read the messages doesn't hide it and there's no way to manually close it.

@TwizzyDizzy Do you know what the expected behavior is?

**Comment by TwizzyDizzy** [comment]
Well. I'm not a developer here, but my expectation as a user would be: scroll down to the bottom and thereby implicitly assume that I have read everything and remove the red-line marker, as now there's nothing unread anymore. I think that would also be a reasonable expectation.

Cheers
Thomas

**Comment by richardwlu** [comment]
@TwizzyDizzy Thank you for the response. I agree with what you're expecting. I suppose if we can receive a straightforward answer from a dev I can relay the message to our users.

**Comment by Episodio1** [comment]
Same here with 0.64.2 
"unread message" bar stays there, even if user changes chatroom.

**Comment by diggamies** [comment]
Rocket.Chat Version 0.65.1 has the same issue on Mac OSX app 2.11.0.

**Comment by martbart** [comment]
Same here. Running 0.72.3 as Ubuntu snap on Ubuntu 18.04, using Firefox 64.
The red unread bar only disappears when I respond. Changing the room and coming back again has no effect

**Comment by martbart** [comment]
What's interesting is that the unread sign (1) next to the channel name on the left and in the tab title disappears when I read the message. What remains is the read line in the chat window as posted by ghost above.
Btw, it's a direct chat with another user if that changes anything

**Comment by sampaiodiego** [comment]
for me it works fine most of the time. if I see the red bar and let it on the screen after a few seconds, it disappear.

I've found a definition [in the code](https://github.com/RocketChat/Rocket.Chat/blob/9a39789f30c38e66d3afe404fad45fc7e509bffb/packages/rocketchat-ui-utils/client/lib/readMessages.js#L8):

```
/* DEFINITIONS
- If window loses focus user needs to scroll or click/touch some place
- On hit ESC enable read, force read of current room and remove unread mark
- When user change room disable read until user interaction
- Only read if mark of *first-unread* is visible for user or if flag *force* was passed
- Always read the opened room
- The default method *read* has a delay of 2000ms to prevent multiple reads and to user be able to see the mark
*/
```

If it is not working as you expect, you can also try debugging it by running this (on latest version) on your browser's console:
```
require('meteor/rocketchat:ui-utils').readMessage.debug = true
```

it will enable some debug messages describing what is happening.

**Comment by ggazzo** [comment]
closing it on favor of: https://github.com/RocketChat/Rocket.Chat/issues/15189
