### ISSUE TITLE
[NEW] API endpoints for custom emojis

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#9326]
REST APIs for listing, creating and deleting custom emojis

**Comment by MarcosSpessatto** [comment]
- [x] list - #9629

**Comment by rafaelks** [comment]
This one can be closed already, thanks @MarcosSpessatto 👍

**Comment by pschorf** [comment]
I saw the list API was added in #9629, is there an API to add custom emoji?

**Comment by cardoso** [comment]
I don't think so @pschorf . At least not a REST API.

Do you mind opening a new issue?
