### ISSUE TITLE
No variable for the sidebar font color

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat#9329]
### Description:

I cant change the sidebar font color.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.2
* Operating System: Ubuntu LTS 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: active
* Node Version: 8.8.1

### Steps to Reproduce:

I want to change the main font color for the channel etc. on the left sidebar, but i cant find a functional setting under "Layout" for that.

### Expected behavior:

A color change for the text in the left sidebar.

### Actual behavior:

No color change possible

![image](https://user-images.githubusercontent.com/26709898/34566618-669d530a-f15f-11e7-9b58-2f3f5ddfa0be.png)

**Comment by robbyoconnor** [comment]
Just following this.

**Comment by rlach** [comment]
Rocketchat 0.62.1 - The issue still persists. 

Quick analysis shows that on .sidebar-item class variable for primary font color gets overriden by `--sidebar-item-text-color` that cannot be set anywhere.
![screenshot from 2018-03-07 14-44-15](https://user-images.githubusercontent.com/5655000/37095416-2a18c15c-2216-11e8-9aeb-da38a24fbed2.png)

In meanwhile I use custom CSS to sidestep the issue:
`
.sidebar-item {
  color: red;
}
`

**Comment by robbyoconnor** [comment]
@rlach yes -- overriding that doesn't quite work -- in fact, it overrides the ability to be notified of new messages since it changes color to gives hints that there are unread messages.

**Comment by rlach** [comment]
@robbyoconnor Yes, that's true. If you want those notifications you need to do a bit more:

```
.sidebar-item {
  color: black;
}

.sidebar-item.sidebar-item--unread {
  color: red;
}
```

Nonetheless, it's very hacky and I only see it as temporary workaround. It should be configurable from admin panel.

**Comment by MartinSchoeler** [comment]
@ArchimedesFM Could you test this out with the latest release? I could not reproduce this issue. Also, you can change the color of the text on the sidebar by changing the `Primary Light` and `content` variables. Thanks!
