### ISSUE TITLE
WebRTC [$250]

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#933]
- [x] Direct call
- [x] Group call
- [x] Show all remote videos
- [x] Close connections on remote close
- [x] Fix mute in Firefox
- [x] Allow select the main video
- [x] Join an existent call
- [x] Option active/deative camera
- [x] Option to mute
- [x] Audio call
- [x] Join calls with audio only
- [x] Show more information about the call before accept
- [x] Redirect to correct room on accept
- [x] Auto accept call
- [x] Call as monitor (without local video and audio, only in direct rooms)
- [x] Overlay
- [x] Screen sharing
- [x] Option to disable in general settings
- [ ] Allow to respond video calls with only audio
- [ ] Option to disable for room
- [ ] Button to enable auto accept calls
## Start video or audio calls in direct or group rooms

![captura de tela 2015-10-03 as 15 12 21](https://cloud.githubusercontent.com/assets/234261/10264443/de24ce92-69e1-11e5-9ddd-a6fbff87d60c.png)
## Join calls in progress

![captura de tela 2015-10-03 as 15 14 00](https://cloud.githubusercontent.com/assets/234261/10264440/de0a73da-69e1-11e5-8e8d-abc67df2c03d.png)
## Accept or reject audio calls

![captura de tela 2015-10-03 as 15 13 47](https://cloud.githubusercontent.com/assets/234261/10264441/de0b364e-69e1-11e5-8af8-c284649f7252.png)
## Accept or reject video calls

![captura de tela 2015-10-03 as 15 12 56](https://cloud.githubusercontent.com/assets/234261/10264442/de210f0a-69e1-11e5-93d1-331cda8eb36c.png)
## Accept or reject monitoring calls

![captura de tela 2015-10-01 as 14 56 27](https://cloud.githubusercontent.com/assets/234261/10264444/de28b3e0-69e1-11e5-9707-d2438ed0c35a.png)
## See all videos and click to show one bigger

![captura de tela 2015-10-03 as 15 15 14](https://cloud.githubusercontent.com/assets/234261/10264439/de0668b2-69e1-11e5-9efa-6fa1858f2354.png)
## Share your screen

![captura de tela 2015-10-03 as 15 15 47](https://cloud.githubusercontent.com/assets/234261/10264438/de043f9c-69e1-11e5-94f0-88b4365c1545.png)
## Expand the UI

![captura de tela 2015-10-03 as 15 16 06](https://cloud.githubusercontent.com/assets/234261/10264436/ddfcb3b2-69e1-11e5-925e-9226a407e5dd.png)
![captura de tela 2015-10-03 as 15 16 01](https://cloud.githubusercontent.com/assets/234261/10264437/ddfff4be-69e1-11e5-98f5-3dd951a9a9f5.png)
##

**Comment by cybercorey** [comment]
Hi there, I'm keen to test these new features.
I've git pulled your branch "webrtc" and built it however I cannot find anything new. I am using the same database would this have caused this?

**Comment by Sing-Li** [comment]
no ... create a private group of a few users

**Comment by cybercorey** [comment]
I must be blind, I cannot find the option to start a video call inside a private group.

**Comment by Sing-Li** [comment]
click on the right panel ... and click join

**Comment by cybercorey** [comment]
Ahh worked it out, i had the new copy running with a different folder name! Cheers for your Help

**Comment by Sing-Li** [comment]
let us know if you can get 3 or more parties going ... on my LAN, I'm having some problems with the current code  :smile:

**Comment by cybercorey** [comment]
Will do! getting 4 on now!

**Comment by Sing-Li** [comment]
cool. r u on a lan?  any browser running on the same machine as the server?

**Comment by cybercorey** [comment]
All over wireless, all using Chrome server is running in a VM on my machine. Started lagging once the 3rd person joined

**Comment by Sing-Li** [comment]
yes ... it would lag ... it is a mesh network where everyone connect to everyone else.  But in your case, every machine is on the same 192.168.x.x subnet?

**Comment by cybercorey** [comment]
Got 4 of us on currently all working pretty smooth, yes all on the same ip range

**Comment by Sing-Li** [comment]
cool.  thanks for helping to test!

**Comment by cybercorey** [comment]
No worries, one of us left now we are unable to click on one of our streams (keeps showing someone elses)

**Comment by cybercorey** [comment]
Another note: Getting some interesting results leaving and joining again. Prompts people to join the chat while they are in the chat. Also I (A) can now see B while B can see A and C and C can see only A (seems like it was unable to obtain connections to existing group members or something haha.

**Comment by Sing-Li** [comment]
can you please confirm that all four users have different IP, and that the server also has different IP than all the users?

**Comment by cybercorey** [comment]
Yup, all IP address's were different

**Comment by rodrigok** [comment]
@cybercorey we did some improvements in connectivity, can you test again?

**Comment by Sing-Li** [comment]
So it seems like we have a problem when one of the browser has the same IP address as the server.  I'll test that again to make sure.

**Comment by Sing-Li** [comment]
Latest code, test results.  On LAN:

server IP:      192.168.38.102
client 1 IP:     192.168.38.102
client 2 IP:     192.168.38.110
client 3 IP:     192.168.38.111

client 1 uses  http://localhost:3000/  to access sever 
client 2 and client 3 uses  http://192.168.38.102:3000/  to access server

client 1 gets "START" button in general, sees own video
client 2 gets "START" button in general (not "JOIN") ... sees own video... see very intermitten 'connecting' from client 1
client 3 gets "START" button in general (not "JOIN") ... sees own video ... sees nothing else

Retrying sometimes get "Group Join Room" popup on client 2 - NEVER on client 1.

No error on Client 1 console.
On Client 2 and Client 3 console - see this (almost exact on both):

(server is executed via standard 'meteor' dev command ...note the avatar load failure ...trying to do localhost load on client 2 and client 3 ....   do we need to set ROOT_URL on dev config?  would it matter for webrtc sessions?)

![screenerr](https://cloud.githubusercontent.com/assets/122633/10270386/e0134dd2-6abd-11e5-8285-8bf1522c530a.png)

**Comment by rodrigok** [comment]
@Sing-Li why all clients gets "START" and not only client 1?

**Comment by graywolf336** [comment]
How does the screen sharing work?

**Comment by mckuchta** [comment]
I think there should be a HTML5 notification when there call invite.  Is this a planned feature.

**Comment by mckuchta** [comment]
It would be nice to have global controls of the current group call, with a link to the room it is being hosted.

**Comment by bott0r** [comment]
It would be nice to have something similar to "push to talk" and  "voice activation" instead of continuous transmission

**Comment by brylie** [comment]
I am having troubles with stuttering audio and video freezing. Is it possible to adjust the call 'quality', e.g. for lower bandwidth or CPU devices?

**Comment by sagar-srivastava** [comment]
does anyone have an idea why my audio and video chat buttons are not clickable at all. I tried both windows client and chrome browser on windows 8.1. my server is a newly setup server on docker

**Comment by brylie** [comment]
@sagar-srivastava consider opening a new issue that is specific to your question.

**Comment by Sing-Li** [comment]
New solution testing this week.

On https://demo.rocket.chat

When you are in a Direct Message or Private Group. You will notice a new video button on the toolbar , just click it anytime to start a video conference with all those in the room

**Comment by hughlroberts** [comment]
There's quite a few bugs in this system and really need some improvements made in the system. I've been locked out of my entire session and had to remove the server to get the screen to go away. Quite a few bugs in this system.
![screen shot 2016-12-07 at 4 49 16 pm](https://cloud.githubusercontent.com/assets/22516740/21043690/3f3f250e-be20-11e6-9b3f-45d435b94871.png)

**Comment by armand1m** [comment]
Is there anyone working on this?

**Comment by rodrigok** [comment]
@armand1m currently no, be we are looking for some help here or find some one to focus in webrtc.

**Comment by pokapow** [comment]
I would like to help you to improve webRTC debugging tools, and using improvement in rocket.chat ?
How can I get start to help you ?

**Comment by real19** [comment]
So I would like to implement similar functionality of group calling. on the iOS mobile app. Any ideas where to start?

**Comment by devopsec** [comment]
What deliverable's are still needed for this?

**Comment by Sing-Li** [comment]
WebRTC features are already part of our core.  That will be the limit of our support/implementation.
