### ISSUE TITLE
Deleting message with store last message not removing

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9332]
### Description:

If you have store last message turned on and then delete last message... that message still is on the channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3

### Steps to Reproduce:

1. Turn on Store Last Message
2. Send a message
3. Delete that message

### Expected behavior:

Remove.  Or show something like message deleted or something

### Actual behavior:

Message stays

**Comment by geekgonecrazy** [comment]
I assume the same happens if you edit the message as well

**Comment by sampaiodiego** [comment]
this should have been fixed by https://github.com/RocketChat/Rocket.Chat/pull/9227 I'll check what happened

**Comment by geekgonecrazy** [comment]
ah didn't even see: #9202 :blush:

**Comment by soundstorm** [comment]
@geekgonecrazy @sampaiodiego  but can we add a function that iterates through all channels when toggling the option on and stores the last message? If you turn that feature on, it will show "No messages yet" even if there are messages in the channel (although I deactivated the feature again as we have too many channels).

**Comment by sampaiodiego** [comment]
you need to enable `Show Deleted Status` to reproduce the error

**Comment by sampaiodiego** [comment]
@soundstorm I thought doing that whenever you turn the feature on, but it would be too heavy on server.

**Comment by geekgonecrazy** [comment]
@soundstorm I think that would be extremely heavy.  Look at open.rocket.chat for instance.  We have a looooooooooooooooooooooot of channels :)
