### ISSUE TITLE
fibers@2.0.0 break the install on server node v9.2.0

### ISSUE THREAD

**Issue by petrk94** [RocketChat/Rocket.Chat#9334]
### Description:

Hello
I try to install rocketchat on the shared hoster uberspace, but it breaks while install fiber@2.0

### Server Setup Information:

* Version of Rocket.Chat Server: latest
* Operating System: CentOS 6 (Shared hosting)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1 
* Node Version: v9.2.0

Error log:
493 silly doParallel update-linked 8
494 silly doSerial install 8
495 silly install fibers@2.0.0
496 info lifecycle fibers@2.0.0~install: fibers@2.0.0
497 verbose lifecycle fibers@2.0.0~install: unsafe-perm in lifecycle true
498 verbose lifecycle fibers@2.0.0~install: PATH: /package/host/localhost/nodejs-9.2.0/lib/node_modules/$
499 verbose lifecycle fibers@2.0.0~install: CWD: /var/www/virtual/digiharz/rocketchat.kirpeit-solutions.$
500 silly lifecycle fibers@2.0.0~install: Args: [ '-c', 'node build.js || nodejs build.js' ]
501 info lifecycle fibers@2.0.0~install: Failed to exec install script
502 verbose unlock done using /home/digiharz/.npm/_locks/staging-46dbf51208bda723.lock for /var/www/virt$
503 warn meteor-dev-bundle@0.0.0 No description
504 warn meteor-dev-bundle@0.0.0 No repository field.
505 warn meteor-dev-bundle@0.0.0 No license field.
506 verbose stack Error: fibers@2.0.0 install: `node build.js || nodejs build.js`
506 verbose stack spawn ENOENT
506 verbose stack     at ChildProcess.<anonymous> (/package/host/localhost/nodejs-9.2.0/lib/node_modules$
506 verbose stack     at ChildProcess.emit (events.js:159:13)
506 verbose stack     at maybeClose (internal/child_process.js:943:16)
506 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
507 verbose pkgid fibers@2.0.0
508 verbose cwd /var/www/virtual/digiharz/rocketchat.kirpeit-solutions.de/Rocket.Chat/programs/server
509 verbose Linux 2.6.32-642.6.2.el6.x86_64
510 verbose argv "/package/host/localhost/nodejs-9.2.0/bin/node" "/package/host/localhost/nodejs-9.2.0/b$
511 verbose node v9.2.0
512 verbose npm  v5.5.1
513 error file sh
514 error code ELIFECYCLE
515 error errno ENOENT
516 error syscall spawn
517 error fibers@2.0.0 install: `node build.js || nodejs build.js`
517 error spawn ENOENT
518 error Failed at the fibers@2.0.0 install script.
518 error This is probably not a problem with npm. There is likely additional logging output above.
519 verbose exit [ 1, true ]

I hope you can help
Thanks

**Comment by talus46** [comment]
I'm having same issue but on Debian 8.1

**Comment by geekgonecrazy** [comment]
Try nodejs 8.x. This is the version needed

**Comment by petrk94** [comment]
I have tried it again with the settings on my another shared host server with NodeJS v4.8.4 and Rocketchat 0.58.2 this is working good, can someone at least say why this issue happens?
--

**Comment by geekgonecrazy** [comment]
@petrk94 you have to use the appropriate node.js version for the version of Rocket.Chat
0.58.x was 4.8 and now we are with the current LTS 8.x

**Comment by petrk94** [comment]
@geekgonecrazy 
I will try it today later.

**Comment by talus46** [comment]
thanks @geekgonecrazy the right node version did help

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this out.

**Comment by petrk94** [comment]
@geekgonecrazy tried it with NodeJS v8.9.1 and works well, the design is even smoother and looks modern. How to update 0.58.2 to the 0.60.4 without loosing the data and messages from users?

**Comment by geekgonecrazy** [comment]
Update node like you did and start up with same environment variables as you did with 0.58.2

**Comment by petrk94** [comment]
@geekgonecrazy so I don't need to care about database stuff of the MongoDB?

**Comment by geekgonecrazy** [comment]
If there are migrations(which there are a couple between 0.58.2 and 0.60.4) they will run on start.  Making the data work with 0.60.4

**Comment by mixrat** [comment]
Trying to upgrade to 0.60.4 using Node.js 8.9.1 but I get the same error as the OP...
 `Failed at the fibers@2.0.0 install script. This is probably not a problem with npm.`
I have overcome this before by installing fibers separately with `npm install fibers`, but no luck now.
