### ISSUE TITLE
Multiple SlackBridge configurations

### ISSUE THREAD

**Issue by Wouter0100** [RocketChat/Rocket.Chat#9339]
A feature request to support multiple SlackBridge configurations. I hoped it was possible to connect different Slack instances with my centralized Rocket.Chat. I have multiple Slack instances because of some customers with their own Slack instance and so a general overview in Rocket.Chat would be perfect.

**Comment by p-thurner** [comment]
+1

**Comment by craigfearnsides** [comment]
+1

**Comment by markwooff** [comment]
+1

**Comment by golflima** [comment]
+1

**Comment by latoile** [comment]
+1

**Comment by golflima** [comment]
As a workaroud, https://github.com/42wim/matterbridge allows to connect multiple Slack channels to one (or multiple) RocketChat channel(s).

**Comment by tharrisonbcg** [comment]
+1

**Comment by Hudell** [comment]
So I did some basic testing here: I created two instances of the SlackAdapter class created on the PR #10205. Receiving messages from multiple slack channels worked without any extra code, but to send messages to multiple slack servers, we need to change the RocketAdapter class to support multiple instances of the SlackAdapter on it, then change the settings to support multiple configurations.

**Comment by nemonik** [comment]
+1
