### ISSUE TITLE
Don't ask for credentials when valid Basic Auth is provided

### ISSUE THREAD

**Issue by mschaefers** [RocketChat/Rocket.Chat#9340]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): docker (official image)
* Number of Running Instances: 1

### Steps to Reproduce:

I protect my RC instance with an extra layer of basic auth in apache.

### Expected behavior:

RC should detect a provided basic authentication header and use this information to try to login the user. Only if this fails, the standard login prompt is presented

### Actual behavior:

When I open RC, apache asks for basic auth credentials.
However, when I enter valid credentials, RC asks me to login, although the very same credentials would be valid RC user credentials.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I don't think that this is going to be implemented (@geekgonecrazy if you think otherwise, please reopen).

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by geekgonecrazy** [comment]
I'd say if you are handling basic auth...then you should also handle logging in too.  Maybe a login token or something
