### ISSUE TITLE
Update Emojione

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#9342]
We are using a newer version of Emojione on iOS for the next update (1.8.0) and it supports more emojis than the web version.

This presents the following problem:

|iOS|Web|
|-|-|
|![](https://i.imgur.com/jb9aMsj.jpg)|![](https://i.imgur.com/dyoLddd.png)|

**Comment by sampaiodiego** [comment]
Closing as duplicate of #6740
