### ISSUE TITLE
Sort order of unread rooms, favorites, channels and direct messages.

### ISSUE THREAD

**Issue by cr22rc** [RocketChat/Rocket.Chat#9344]
The order of these should be case insensitive.
Second there should be an option to sort by last referenced. Sort those I view to the top. Most likely those are the ones you're most active on.

**Comment by antgel** [comment]
I'm surprised there wasn't an existing issue for this important feature, surely a lot of people want this. @engelgabriel @MartinSchoeler @geekgonecrazy Are you aware of any?

**Comment by geekgonecrazy** [comment]
I believe this is being taken into consideration with some redesign changes coming over on the sidebar.

**Comment by marceloschmidt** [comment]
Both suggestions have been implemented.

**Comment by clevertree** [comment]
@antgel If it's not obvious yet why this feature was held back for years, when it would take an afternoon to complete - 
**Corporate Sabotage**. Big Tech can't compete with open source, but they can certainly pay off free techs of open source projects like this one to sabotage their own work, or in this particular case, make the product less competitive with BigTech. I don't think anything short of naming and shaming will slow the spread of **Corporate Sabotage** in open source projects >:(
