### ISSUE TITLE
Make the message box autofocus an option

### ISSUE THREAD

**Issue by mbouchard** [RocketChat/Rocket.Chat#9347]
https://github.com/RocketChat/Rocket.Chat/blob/397857ef1c32988597da42264f4638604526e184/packages/rocketchat-ui-message/client/messageBox.html#L28

The presence of the `autofocus` attribute should be made an option because it's causing Rocket.Chat to steal the focus when it's integrated in an iframe.

This is a problem when a user is typing something in an input text outside the Rocket.Chat iframe and suddenly he's typing in the Rocket.Chat's message box without noticing it because the iframe stole the focus after it has loaded.

**Comment by xnextx** [comment]
+1
This is a big problem when we integrate our service with iframe.

**Comment by sdelfi** [comment]
+1
Will there be any changes on this issue?

**Comment by acflint** [comment]
+1
This issue has caused my client some grief. They've had people accidentally type sensitive information into the chat box. We're Cloud subscribers, and very much looking forward to an update on this one.

**Comment by davidpiesse** [comment]
+1. :)
