### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by BlessBau** [RocketChat/Rocket.Chat#9348]
I have created a simple iframe with an id "rock" and loaded the rocket.chat app on it.

I was trying to login like document.getElementById('rock').contentWindow.Meteor.loginWithPassword('username', 'password');

But I am getting this error: 
SecurityError: Permission denied to access property "Meteor" on cross-origin object

I just want to embed Rocket.chat on a mobile device, and can't find any docs about it. 
TIA

**Comment by BlessBau** [comment]
I found another way to make it work. :-)

**Comment by anujdhimanjava** [comment]
@BlessBau  Can please help me how can you solve this issue .Because i encounter same issues  

"SecurityError: Permission denied to access property "Meteor" on cross-origin object"  when calling iframe.contentWindow.Meteor.loginWithPassword('username', 'password');"

**Comment by forij** [comment]
Please you can say what the way you use to login in iframe RocketChat
