### ISSUE TITLE
Create a channel tab for channel information

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#935]
Allow channel creators to add room information on this panel. Let users write Markdown for this information.
##

**Comment by AdrianoCahete** [comment]
I don't know if panel is better. I think about put a icon ![info](https://upload.wikimedia.org/wikipedia/commons/b/b0/Information_icon_ff.png) before channel name, in channel top bar.

**Comment by sunnipaul** [comment]
That's what I am looking for too.  I hope it can be built soon.  Channel tab is good.

**Comment by Rohlik** [comment]
We already have this implemented, right? If yes, we can close this...

**Comment by marceloschmidt** [comment]
Right @Rohlik thanks for point that out ;)
