### ISSUE TITLE
Messagebox not scrolling to the last line

### ISSUE THREAD

**Issue by vnkmpf** [RocketChat/Rocket.Chat#9350]
### Description:

Typing multi-line message after certain number of lines message box (textarea) does not scroll to last line and manual scroll-down is required.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: 8.9.3
* Browsers: Firefox 57.0.4 (64bit), PaleMoon 27; works fine in Vivaldi (webkit)
* Client OS: Linux Mint

### Steps to Reproduce:

1. Write multi-line (8+ lines) message with ctrl + enter.

### Expected behavior:

Message box is scrolled to last inserted line.

### Actual behavior:

Message box stays scrolled to the line that last changed its size (in my case the 8th).
It still writes under the 8th line, but you have to scroll down or use arrow keys.

### Relevant logs:
-

### Screenshots
Until the 8th line everything works fine
![messagebox1](https://user-images.githubusercontent.com/30214167/34641014-c0319440-f2fd-11e7-858a-49f3bcbdb47a.png)

With 9th line textarea doesn't scroll down, but you see the 9th line inserted by scrollbar on the right.
![messagebox2](https://user-images.githubusercontent.com/30214167/34641019-d529eef6-f2fd-11e7-8fde-9dbada5cbbca.png)

After scrolling down you see the text
![messagebox3](https://user-images.githubusercontent.com/30214167/34642126-8e9acaee-f30e-11e7-841b-251e711c25c8.png)

**Comment by ggazzo** [comment]
hey @vnkmpf we had a lot of changes here, I think its working (: any problem let me know
