### ISSUE TITLE
Emojis are not correctly replaced in longer messages

### ISSUE THREAD

**Issue by vnkmpf** [RocketChat/Rocket.Chat#9351]
### Description:

Some ASCII emoticons in message are not correctly replaced with Emoji variant.
I do have enabled emojis in preferences.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: 8.9.3
* Browsers: Firefox 57, Vivaldi, Palemoon, every browser I have tested

### Steps to Reproduce:

1. Type emojis especially in multi-line message (see included screenshots).

### Expected behavior:

All emoticons are replaced with their emoji variant.

### Actual behavior:

Certain emoticons aren't replaced.
To me it looks like mostly those followed with newline.

### Relevant logs:
-

### Screenshots
The first emoticon (line 1) isn't replaced (multiline message)
![emojis_1](https://user-images.githubusercontent.com/30214167/34642407-c643b614-f312-11e7-85dc-fcfb6f0232e1.png)

The last emoji (line 1) isn't replace (multiline message)
![emojis_2](https://user-images.githubusercontent.com/30214167/34642414-dad17472-f312-11e7-8c27-42c29e7b0032.png)

When using `:slight_smile:` everything works fine (line 1)
![emojis_3](https://user-images.githubusercontent.com/30214167/34642418-faa1e944-f312-11e7-9284-a8c7fe7178c2.png)

Multiple emoticons works, when sent in 2 messages (line 1 = msg 1, line 2 = msg 2)
![emojis_4](https://user-images.githubusercontent.com/30214167/34642426-16a41f68-f313-11e7-9e10-e96c5575aec3.png)

The same sent as single message doesn't work for ending emoticons
![emojis_5](https://user-images.githubusercontent.com/30214167/34642429-25d3b0d4-f313-11e7-9a1a-3cba9de778ce.png)

**Comment by Otiel** [comment]
I think this is the same issue as #9498.

**Comment by karlprieb** [comment]
Hey @vnkmpf thank you for your report! I tried here and you're right. We'll keep track of it, but it's not our priority to fix that right now.

**Comment by vnkmpf** [comment]
Sure, I knew broken emojis are not top priority :) 
I was even wondering, if it can be some emoji library bug - not rocketchat's. But didn't give any research to it.

**Comment by gabriellsh** [comment]
Tested 3.0.0-develop, Chrome Version 80.0.3987.87 (Official Build) (64-bit), macOS Catalina 10.15.2, works fine. If this still affects you, please reopen.

**Comment by gabriellsh** [comment]
I just found out that this happens still, but only when using Marked parser.

**Comment by MartinSchoeler** [comment]
Gazzodown should've fixed that, closing this, if it still happens on the latest version, please open a new issue. Thanks!
