### ISSUE TITLE
ship qualia:reval for quality of life

### ISSUE THREAD

**Issue by janat08** [RocketChat/Rocket.Chat#9352]
### Description:
qualia:reval allows you to change front end while bypassing meteor reloads

### Expected behavior:
reval allows you to use editor to immidiately change how front end acts/looks without waiting for meteor to reload, and it's only a dev package. It also shows button within app for in-browser editor permitting collaboration, but it doesn't work well at detecting right template.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as I fail completely to understand what you're asking. Please also respect the issue template. If you're requesting a feature, please head over to thee forums: https://forums.rocket.chat/c/feature-requests

Cheers
Twizzy
