### ISSUE TITLE
Max Room Members limit does not get overridden by user notifications="all messages"

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#9357]
On our default #general and #offtopic channels, messages just triggering notifications if mentioned, although mobile/desktop notifications are set to trigger on all messages. Still present in 0.60.x

~Guess:
Maybe this is a bug caused by Slack import, I'll check my files (but they are older than one year, so have to search for them)~ Settings for notifications are not included in Slack export files, so they can't influence this behaviour. I'll have a look into the mongo, but my guess is, that this will reveal nothing helpful.

**Comment by soundstorm** [comment]
@engelgabriel the `rid` is `GENERAL` and `OFFTOPIC` instead of a cryptic string.

**Comment by Maqsyo** [comment]
same problem here.
No Mobile/Desktop-Notifications for "all messages". only for mentions

**Comment by srgcdev** [comment]
Same problem here. I don't receive notifications in channels despite notifications are configured for all messages.

**Comment by Hudell** [comment]
I've been trying to replicate the issue here, but the notifications showed up properly every time (except when my status is busy, but that is by design).

**Comment by srgcdev** [comment]
@Hudell The problem I commented occurs on windows in the channels chats.
I receive the notification (and I can see it during 2 seconds because I configure it this way) but if I missed the notification I can't notice if there are pending message on channels to read because the unread count in the system try icon is not updated and the window in the task bar doesn't blink despite I configure the channel to do that.

**Comment by soundstorm** [comment]
@Hudell as mentioned, the `rid`s on those channels  differ from the normal auto-generated string as they are plain text. Don't know if this applies to your installation as well.

**Comment by Hudell** [comment]
@soundstorm  Yes, the general channel always has that fixed id. I've tried running more tests here and was still unable to replicate the issue. 

Have you checked the channel's notification preferences? It overrides the users's global notification preferences, so even if the user is set to display notifications on every message, it will only show notifications on mentions for the channels that are configured like that.

@srgcdev I think your problem may be unrelated to the one described in this issue, as you mentioned that the notification pops up properly.

**Comment by soundstorm** [comment]
@Hudell okay, then lets see.
I've set
- #general to use my global preferences
- #offtopic to notify on every message
So settings for these channels should work to send out notifications regardless of trigger words.

**Comment by soundstorm** [comment]
@Hudell can reproduce with any account on our instance.

**Comment by soundstorm** [comment]
```
> db.rocketchat_room.find({"name":"general"})
{ "_id" : "GENERAL", "ts" : ISODate("2016-12-21T01:26:38.049Z"), "t" : "c", "name" : "general", "usernames" : [ ... ], "msgs" : 1744, "default" : true, "_updatedAt" : ISODate("2018-04-03T19:24:00.097Z"), "lm" : ISODate("2018-04-03T02:15:42.798Z"), "importIds" : [ "C050MEJ2J" ], "topic" : "Wichtige Ankündigungen, Diskussionen und Fragen" }
```

```
> db.rocketchat_room.find({"name":"offtopic"})
{ "_id" : "kgYFD5tdpepALBdby", "name" : "offtopic", "t" : "c", "usernames" : [ ... ], "msgs" : 1592, "u" : { "_id" : "FSDQcz2Sd2uYPMbCv", "username" : "joachimh" }, "ts" : ISODate("2016-12-22T10:49:18.624Z"), "ro" : false, "sysMes" : true, "_updatedAt" : ISODate("2018-04-03T19:25:46.533Z"), "importIds" : [ "C050MEJ2L" ], "lm" : ISODate("2018-04-03T19:25:46.504Z"), "default" : true, "topic" : "Eventuell abseits von Arduino - für reinen Quatsch #freitagsgespraech" }
```

```
> db.users.find({"username":"sndstrm"})
{ "_id" : "AuFSZhiWTKBnduXPb", "createdAt" : ISODate("2016-12-21T01:36:06.157Z"), "services" : { ... }, "emails" : [ { ...} ], "type" : "user", "status" : "offline", "active" : true, "roles" : [ "admin", "bot", "livechat-manager", "livechat-agent", "user" ], "_updatedAt" : ISODate("2018-04-03T19:22:50.681Z"), "name" : "Luca 卖家", "lastLogin" : ISODate("2018-04-03T19:22:50.681Z"), "statusConnection" : "online", "utcOffset" : 1, "username" : "sndstrm", "statusDefault" : "offline", "language" : "de", "settings" : { "preferences" : { "newRoomNotification" : "none", "newMessageNotification" : "none", "useEmojis" : true, "convertAsciiEmoji" : true, "saveMobileBandwidth" : true, "collapseMediaByDefault" : false, "autoImageLoad" : true, "emailNotificationMode" : "disabled", "roomsListExhibitionMode" : "category", "unreadAlert" : true, "desktopNotifications" : "all", "mobileNotifications" : "all", "enableAutoAway" : false, "highlights" : [ "Luca" ], "desktopNotificationDuration" : 0, "viewMode" : 0, "hideUsernames" : false, "hideRoles" : false, "hideAvatars" : false, "hideFlexTab" : true, "sendOnEnter" : "desktop", "roomCounterSidebar" : false, "sidebarSortby" : "alphabetical", "sidebarShowUnread" : true }, "profile" : {  } }, "avatarOrigin" : "facebook", "importIds" : [ "U0519TXJF" ], "statusLivechat" : "not-available", "operator" : true, "livechatCount" : 1 }
```

Seems all okay so far.

```
> db.rocketchat_subscription.find({"name":"general"})
{ "_id" : "wR6xJkLdpfg6js56R", "open" : true, "alert" : false, "unread" : 0, "ts" : ISODate("2017-01-28T10:59:16.626Z"), "rid" : "GENERAL", "name" : "general", "t" : "c", "u" : { "_id" : "AuFSZhiWTKBnduXPb", "username" : "sndstrm" }, "_updatedAt" : ISODate("2018-04-03T17:20:25.165Z"), "ls" : ISODate("2018-04-03T17:20:25.165Z"), "desktopNotifications" : "all", "desktopNotificationDuration" : 0, "userMentions" : 0, "groupMentions" : 0, "f" : true }
```
So this uses my user settings

```
> db.rocketchat_subscription.find({"name":"offtopic"})
{ "_id" : "rx8jk6CcGDHwYqhXE", "open" : true, "alert" : false, "unread" : 0, "ts" : ISODate("2016-12-22T10:49:18.624Z"), "rid" : "kgYFD5tdpepALBdby", "name" : "offtopic", "t" : "c", "u" : { "_id" : "AuFSZhiWTKBnduXPb", "username" : "sndstrm" }, "_updatedAt" : ISODate("2018-04-03T19:25:46.520Z"), "ls" : ISODate("2018-04-03T19:25:46.520Z"), "mobilePushNotifications" : "all", "desktopNotifications" : "all", "desktopNotificationDuration" : 0, "userMentions" : 0, "groupMentions" : 0, "f" : true }
```
And this should override my settings and force push notifications, but neither web client nor RC+ on iOS does receive that.

Last option would be to rename the channel, recreate a new #general/#offtopic and change all values to the new one. But this would break # links.

**Comment by sampaiodiego** [comment]
@soundstorm just to confirm, do you receive a push notification if you're mentioned at those channels at the same conditions?

I've also found [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js#L236). does it apply to your case?
![image](https://user-images.githubusercontent.com/8591547/38275991-0a754960-376a-11e8-8192-050ba6a23e50.png)

**Comment by soundstorm** [comment]
@sampaiodiego yeah, that's right.
The number of users exceeds 100, just set it to 0 to check, then used the wrong account to publish a message (and therefor got no notification regardless of the settings) but this fixed it.

The description is then misleading, as the "notify on all messages" will not override this limit. So maybe I leave that open to fix the description or the behaviour.

**Comment by sampaiodiego** [comment]
yay 🎉 at least we found it! damn..

yep, I found the description misleading as well.. need to dig deeper to see if either the description or the implementation is wrong 😉
