### ISSUE TITLE
REST API call chat.getMessage returns error

### ISSUE THREAD

**Issue by MariusSpangenberger** [RocketChat/Rocket.Chat#9358]
If I call the chat.getMessage from the REST API, I get an error:

`curl -H "X-Auth-Token: TOKEN" -H "X-User-Id: USERID" serverip:3000/api/v1/chat.getMessage -d '{ "msgId": "messageID" }'`
returns
`{"status":"error","message":"API endpoint does not exist"}`

For some further testing I tried the same call without a payload:
`curl -H "X-Auth-Token: TOKEN" -H "X-User-Id: USERID" serverip:3000/api/v1/chat.getMessage`
this one returns a correct error:
`{"success":false,"error":"The \"msgId\" query parameter must be provided."}`

I tested it in cli with curl and in Java with Unirest with the same result.
Rocketchat server runs on ubuntu 16 lts, installed with snap, version 0.60.2.

attendant rocket.chat code:
https://github.com/RocketChat/Rocket.Chat/blob/5c733384f2cc62437edaadf2df250b72c75aed54/packages/rocketchat-api/server/v1/chat.js#L65
rochet.chat rest api command site:
https://rocket.chat/docs/developer-guides/rest-api/chat/getmessage/

**Comment by graywolf336** [comment]
The documentation is wrong. That endpoints is a GET and not a put. As the error message says, you must provide the `msgId` via a query parameter.

@MartinSchoeler the documentation on this needs to be fixed

**Comment by MartinSchoeler** [comment]
@graywolf336 https://github.com/RocketChat/docs/pull/499

**Comment by MariusSpangenberger** [comment]
It works fine with a GET instead of a POST call, thanks!
