### ISSUE TITLE
Feature Request - Prevent convert private group/channel - public channel

### ISSUE THREAD

**Issue by ledainam** [RocketChat/Rocket.Chat#9360]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.60
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 

### Steps to Reproduce:

1. 
Created private channel
2. 
Admin user converted private channel to public channel. 
Other users can join without permission from channel creator

### Expected behavior:

No one can convert from private channel to public channel except channel creator to protect personal privacy.

### Actual behavior:

Admin user can convert from room list without permission from channel creator.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @ledainam

to be honest: admin is king. There's no debate about that. One might discuss whether this needs to be a UI option, but in the end the admin could do anything in MongoDB anyway, so I guess there is no way to prevent an admin from doing this. And I think there shouldn't be.

Unless you specifically encrypt message content in the database with user-supplied keys, there is no way to prevent an admin from intruding your privacy. Well.. hold on. OTR-Chat of course but there are also some current issues with that.

I am therefore closing this issue. If you don't agree, please reply and tell us why my argument is wrong. :)

Cheers
Thomas
