### ISSUE TITLE
Source code naming convention

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#9363]
When building a RPM from the source I have issues with RC versions as Spec files do not like the use of hyphens in the version number:

So this is OK:

rocket.chat-0.59.6

This is not:

rocket.chat-0.60.4-rc.1

Is it possible to change the hyphen to another character?

e.g. 

rocket.chat-0.60.4.rc.1

**Comment by TwizzyDizzy** [comment]
Sooo... some questions

1) the hyphen in the software is no problem?
2) I take it your package build process is automated, so couldn't you just replace the `-rc.` with `.rc.` or whatever suits your needs?

PS: please also let us know whether you will publish the  resulting packages :)

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing due to lack of feedback.

Cheers
Thomas
