### ISSUE TITLE
Long channel topics over-expand UI (FF, Arch Linux, i3)

### ISSUE THREAD

**Issue by brandonson** [RocketChat/Rocket.Chat#9371]
### Description:

Running on Arch Linux, FF 57.0.3, using i3wm for window management. I have my monitor in portrait mode, and when the channel topic is sufficiently wide, the chat window expands off the right-hand side of the screen. Blocking the channel topic element (using uBlock origin) fixes the issue.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4

Other info unknown, sorry.

### Steps to Reproduce:

* Load rocket chat site.
* Open a channel with a long topic

### Expected behavior:

Chat portion of site should stay within browser window. Presumably the topic should either be truncated, or should wrap to multiple lines.

### Actual behavior:

Site expands to wider than the window.

**Comment by gregs007** [comment]
Server Setup Information:
Version of Rocket.Chat Server: 0.59.4
Operating System: linux
Deployment Method(snap/docker/tar/etc): docker
Number of Running Instances: 1
DB Replicaset Oplog: enabled
Node Version: 4.8.4

**Comment by geekgonecrazy** [comment]
I believe this has been fixed with latest release.  Please update and re-open if still occurs

**Comment by jhermann** [comment]
@geekgonecrazy I still get this with Rocket.Chat Server: 0.60.4

Could you give a number for "latest", and possibly reopen this?

**Comment by geekgonecrazy** [comment]
@jhermann latest release is 0.61.1
