### ISSUE TITLE
Text in message box continuously shifts when message exceeds certain size.

### ISSUE THREAD

**Issue by gregs007** [RocketChat/Rocket.Chat#9372]
### Description:
When entering text over a certain number of lines, the scroll bar appears and continuously makes all the text shift around when each character is typed. Video provided at https://youtu.be/neYJWkhKNKU

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.4
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: enabled
* Node Version: 4.8.4

### Steps to Reproduce:

1. Enter several lines of text into message window until scrollbar appears
2. Type each character and watch text shift

### Expected behavior:
1. The text should remain static when entering each character.

See video: https://youtu.be/neYJWkhKNKU

**Comment by geekgonecrazy** [comment]
@gregs007 new version released where this is fixed.  Please update and reopen if still applies
