### ISSUE TITLE
Add ability to disable all message parsing

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9373]
### Description:
Sometimes we will get a message that breaks the channel for all clients.  Basically highlightjs will struggle and it'll just blow up.

We need a way to disable highlightjs so people can remove the offending message.

  
Also... Some prefer not to have syntax highlighted

**Comment by SamSaffron** [comment]
Note, the particular snippet we had that failed works fine at Discourse which uses the same version of hljs, I have never really seen any cases where hljs goes into such a tailspin that it never finishes parsing. 

I think the request is more around the fact that some users prefer no syntax highlighting in chat cause it can get distracting.

**Comment by geekgonecrazy** [comment]
Unfortunately we've actually ran across one in the past.  They fixed it pretty quickly upstream.
Ref: #6814

I think it might be trying to guess which syntax is used instead of just ignoring if they don't specify a type. 

It's been a while since I've been in that code so memory is a bit Rusty.

**Comment by Sing-Li** [comment]
The demand for this is low after 2 years.  We will close it for now.
