### ISSUE TITLE
Deleting a user should instantly remove messages from that user

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#9374]
### Description:

If I delete a user, the messages are removed, but this isn't reflected until clients reload the channel(s). 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: n/a
* Node Version: 8

### Steps to Reproduce:

1. Create extra user
2. Type some messages in a channel
3. Delete extra user

### Expected behavior:

I would expect all messages to be instantly removed but they are not. 

### Actual behavior:

Messages remain until the client is reloaded.

**Comment by geekgonecrazy** [comment]
This one could be tough.. when a user deletes a single message it makes sense to send an event.  But let's just imagine what would happen if you sent events to every client connected when deleting... Say my user.

For one the server would likely chew through some CPU removing my user as is.  But then imagine it had to fire events to inform all connected users of each message being deleted.

So we can't use the same delete as we do now.  We'd have to pretty much create a new one just for this type of bulk update type of thing.

**Comment by robbyoconnor** [comment]
I'm not sure how slack handles this type of thing, but it's surely possible..

**Comment by geekgonecrazy** [comment]
For sure possible.  Might be able to just have client side react and remove messages when it's alerted to the user being deleted.

**Comment by robbyoconnor** [comment]
Maybe for the current active channel only? Loading the others shouldn't be affected...assuming you don't keep a local cache of messages... if you do...then this is easier, just invalidate the cache.

**Comment by pettitto** [comment]
Would it be preferable to have this as an option, as there could be a valid reason to want to go back to view messages from a certain user?

Imagine having conversations between 3 or more people in a chat room, then if a user and their messages get deleted, the conversation wouldn't make sense.

The reason I'd be in favour of having this as an option, would be for auditing reasons.

**Comment by vynmera** [comment]
This will be fixed in #11236.
