### ISSUE TITLE
[PR8411] [BUG] [UI] Create new channel icon align break

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#9379]
Hi,
Create new channel icon align breaks in #8411 see this:
![04](https://user-images.githubusercontent.com/8266479/34783691-74e006d8-f641-11e7-8f8d-109a6aafabec.png)

My browser is Firefox 57.0.1
**/CC:** @karlprieb @ggazzo @rodrigok

**Comment by cyclops24** [comment]
Part of #8175

**Comment by engelgabriel** [comment]
fixed
