### ISSUE TITLE
CTRL + P doesn't work anymore

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#938]
![image](https://cloud.githubusercontent.com/assets/1986378/10180949/bc6b8828-66e8-11e5-8f01-b0f9f36e6762.png)

**Comment by storrgie** [comment]
It appears that this is now bound to CTRL + SHIFT + P, which is the default for new private window in firefox.

**Comment by marceloschmidt** [comment]
Not the focus of this issue. The problem with this one is searching for a string and other results showing.
