### ISSUE TITLE
[BUG] [UI] [RTL] Create channel radio button align breaks

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#9382]
Create channel radio button align breaks after release version 60. See this:

![10](https://user-images.githubusercontent.com/8266479/34785584-d072047e-f646-11e7-8d14-02ad49780fe6.png)

/CC: @karlprieb @ggazzo @rodrigok

**Comment by cyclops24** [comment]
Part of #8175

**Comment by TwizzyDizzy** [comment]
Is this still an issue? I'm asking because #8175 is closed by now...

Cheers
Twizzy

**Comment by karlprieb** [comment]
@TwizzyDizzy I tested here and yes, is still an issue.
