### ISSUE TITLE
[PR8411] [BUG] [UI] [Discussion] We don't need Room Info for direct messages

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#9383]
Guys, I think we don't need **"Room Info"** for direct messages because we have **"User Info"** page for that. See this:
![11](https://user-images.githubusercontent.com/8266479/34785905-c222fb70-f647-11e7-9767-7a1f5c581635.gif)

What is your plan for this?
**/CC:** @karlprieb @ggazzo @rodrigok 
It's related to #8411

**Comment by rodrigok** [comment]
Uhm, good question.

@karlprieb @engelgabriel what do you think?

**Comment by karlprieb** [comment]
I agree with @cyclops24 .
I think we should remove the room info panel.
