### ISSUE TITLE
Web interface doesn't work in IE 11 in intranet sites Compatibility View

### ISSUE THREAD

**Issue by simnv** [RocketChat/Rocket.Chat#9385]
### Description:

Web interface doesn't work in IE 11 in intranet sites Compatibility View, which is default Internet Explorer 11 behavior for intranet sites.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Centos 6.9 on server, Windows 10 on client
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 1
* Node Version: node/8.9.3

### Steps to Reproduce:

1. Install Rocket.Chat on one of the local intranet sites
2. Open Rocket.Chat in Internet Explorer 11

### Expected behavior:

Page should open.

### Actual behavior:

Empty page, lots of JavaScript errors in the browser console.

### Additional information:

If I open Compatibility View settings, and uncheck the "Display intranet sites in Compatibility View" box, Rocket.Chat works normally.

### Possible remediation:
`<meta http-equiv="X-UA-Compatible" content="IE=edge" />` tag should be before the script tag in the page head.

**Comment by josephsmith1990** [comment]
Any update on this issue?  It seems simnv has the solution, just needing Rocket.Chat to implement. It means moving: 
<meta http-equiv="X-UA-Compatible" content="IE=edge" / >   tag ahead of the script tag.  
The alternative of unchecking "Display intranet sites in Compatibility View" box doesn't work for many of us in a corporate setting to push it across to all users as it breaks a bunch of legacy Intranet sites.

**Comment by pagnotta** [comment]
+1

But are you sure the solution works? Tried it temporarily on my server by editing `/opt/Rocket.Chat/programs/server/packages/rocke tchat_ui-master.js` so that it injects the `<meta http-equiv="X-UA-Compatible" content="IE=edge" / >` tag before the script in the head, but IE11 still didn't load.

Would be a showstopper, since IE11 is default for intranet pages on our desktops.

**Comment by josephsmith1990** [comment]
Pagnotta - Theortically, it should work. Everything I'm reading and experience shows that it's a question of moving it ahead of the script tag.   How did you run the temporary server?  I thought Rocket.Chat web-interface calls the Rocket.Chat hosted .js file.  You're saying you just hosted it on your end, and had it refer there?

Hopefully someone can validate this on their end. It really should be a 30 second operation for them and a quick win.  

Like you, showstopper if IE11 still doesn't work. It's the default country-wide across our corp.

**Comment by josephsmith1990** [comment]
...to add to my last comment, here's why the code (and where it's placed) matters for those of us in a corporate environment that: a) forces display of intranet sites in compatibility mode, and b) has IE11 as default browser:  http://tesmond.blogspot.com/2011/10/ie9-intranet-compatibility-mode-in.html 

The link also provides the solution :)

**Comment by simnv** [comment]
> But are you sure the solution works? Tried it temporarily on my server by editing `/opt/Rocket.Chat/programs/server/packages/rocketchat_ui-master.js` so that it injects the `<meta http-equiv="X-UA-Compatible" content="IE=edge" / >` tag before the script in the head, but IE11 still didn't load.
Since my original post there were more breaking changes to rocketchat, like the lack of es6 to es5 transpilation. For example, spread and rest syntax (dot-dot-dot) doesn't work in ie11.

You can test it yourself: open rocketchat link in ie11, press f12, choose Edge compatibility manually at the top corner:
![image](https://user-images.githubusercontent.com/3754755/55312564-4400e580-547f-11e9-8fca-932440dd696e.png)

You will see some errors in console that indicate that there are more things broken now. In my case it is for ...:
![image](https://user-images.githubusercontent.com/3754755/55312376-d05ed880-547e-11e9-91cb-9653ec152637.png)

Proposed change worked for 0.60.3, but it doesn't work now. We've moved on to Electron desktop client, since there are no other options.

**Comment by fadanner** [comment]
Having the same issue with 0.74.3.
Issue exists even on https://open.rocket.chat
IE11 logs
SCRIPT1002: Syntaxfehler d1eef865fbf5b68bd6eb0f292fa51263c005b1ba.js (5,1702140)
This is a major problem as we use IE11 in whole environment.

**Comment by fadanner** [comment]
Does anyone have an idea on this?
It is a very big problem for our users if the chat does not work in IE11.

**Comment by sfinity** [comment]
Having the same issue with 1.0.0-rc.2
'SCRIPT1002: Syntax Error 436769ec810494cebfd29cd81e6d6b2171ad84d3.js (5,1634318)'

**Comment by fadanner** [comment]
Any news on this? Bug is still open.

**Comment by pagnotta** [comment]
As pointed out by simnv in https://github.com/RocketChat/Rocket.Chat/issues/9385#issuecomment-478479029 it seems to be a problem of ES6 code which is not compatible with IE11, like e.g. the three dot (...) spread syntax for iterable objects. 

See https://kangax.github.io/compat-table/es6/ for compatibility.

Is there no transpilation to ES5?
