### ISSUE TITLE
[NEW] Default role for self-registered users

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#9386]
### Description:

As user register themselves, they are currently automatically assigned the `user` role. Particularly in corporate environments where you cooperate with partners, you'd want to allow them to cooperate, but with limited permissions.

### Proposal
For self-registration with authentication-services, there is already an option to configure the role to be used for newly registered users. Similarly, there should be an option for self-registered users.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4

### Steps to Reproduce:

1. Make sure that users don't need explicit activation by the admin
2. Register via the registration form

### Expected behavior:

The user registered is assigned a `guest` or  custom `newbie` role

### Actual behavior:

The user is a `user` immediately

**Comment by mrsimpson** [comment]
note to myself: How to find our that a user is seöf-registered in `server/lib/accounts.js`

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
