### ISSUE TITLE
Imgur Embed Support

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#939]
Adding Imgur embed support to expand http://imgur.com/gallery/YFjHVvW into
<img width="560" alt="screenshot 2015-09-29 19 20 38" src="https://cloud.githubusercontent.com/assets/2439803/10182949/33215e98-66df-11e5-9051-d3dc043a8151.png">
##

**Comment by graywolf336** [comment]
Should it just be the image? Or should there be details about it as well?

**Comment by royalaid** [comment]
The above is the default embed that Imgur provides. It could be either or and it a really a matter of preference

**Comment by AdrianoCahete** [comment]
And **IF** users put a nsfw img?
I think image embedds have to stay small.

**Comment by royalaid** [comment]
What about an expand on click option?

**Comment by AdrianoCahete** [comment]
> What about an expand on click option?

:+1:

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. The link mentioned in the first post, by now, pulls the image from imgur and shows it. There also exists an option for "click to load" for images. If you think I got something wrong, please get back to me :)

Cheers
Thomas
