### ISSUE TITLE
All users can delete a message as hide-only

### ISSUE THREAD

**Issue by mrhaxic** [RocketChat/Rocket.Chat#9396]
### Description:

Is there any option to make the delete message action for only disappearing and not retrieving it as the last message like WhatsApp ? for example we have direct message between user1, user2 then user2 wants to delete a message sent from user1 after that action user2 will not see the deleted message but user1 still able to read this message.

Thanks

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
