### ISSUE TITLE
The core-js npm package could not be found error in chrome console

### ISSUE THREAD

**Issue by assadvirgo** [RocketChat/Rocket.Chat#9397]
### Description:

Cloned the latest source code from the Rocket.Chat git master branch. Tried meteor npm start command it all compiled fine except few warnings. But when i used the widget code and placed it on the website got the following error.

Dropbox Image: https://www.dropbox.com/s/70isowwp6mz7vz9/Screenshot%202018-01-11%2010.40.24.png?dl=0

I've tried running the command in main folder of project source code but nothing helped. 
### Server Setup Information:

* Version of Rocket.Chat Server:60.4
* Operating System: MacOS High Serria
* Deployment Method(snap/docker/tar/etc):custom build
* Number of Running Instances: 1
* DB Replicaset Oplog: Not Enabled
* Node Version: 8.9.3
* Meteor Version: 1.6

**Comment by sampaiodiego** [comment]
this seems to be fixed on latest 0.61.1 version
