### ISSUE TITLE
How to sync user accounts from other CMS?

### ISSUE THREAD

**Issue by internalG** [RocketChat/Rocket.Chat#9398]
If Rocket is used as the chat feature for drupal, how to add the existing users in drupal to Rocket and sync new registration? Drupal takes the web site front-end, Rocket enables chatting for users. But the user account live as one in two frameworks. Any solution? Thanks.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
