### ISSUE TITLE
Systemd Debian Jessie/Stretch not starting

### ISSUE THREAD

**Issue by andypl78** [RocketChat/Rocket.Chat#9399]
### Description:

Rocket.Chat can not be started using systemd

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Debian Jessie/Stretch
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version: NodeJS Version: 8.9.4 - x64

### Steps to Reproduce:

1. 
Install from manual sites
https://rocket.chat/docs/installation/manual-installation/debian/
2. 
Configure Systemd like this tutorial
https://rocket.chat/docs/installation/manual-installation/pm2-systemd-upstart/

### Relevant logs:

Jan 12 14:42:59 vps-sys nodejs-rocket[4172]: Note: you are using a pure-JavaScript implementation of bcrypt.
Jan 12 14:42:59 vps-sys nodejs-rocket[4172]: While this implementation will work correctly, it is known to be
Jan 12 14:42:59 vps-sys nodejs-rocket[4172]: approximately three times slower than the native implementation.
Jan 12 14:42:59 vps-sys nodejs-rocket[4172]: In order to use the native implementation instead, run
Jan 12 14:42:59 vps-sys nodejs-rocket[4172]: meteor npm install --save bcrypt
Jan 12 14:42:59 vps-sys nodejs-rocket[4172]: in the root directory of your application.
Jan 12 14:43:00 vps-sys nodejs-rocket[4172]: Will load cache for users
Jan 12 14:43:00 vps-sys nodejs-rocket[4172]: 2 records load from users
Jan 12 14:43:01 vps-sys nodejs-rocket[4172]: Will load cache for rocketchat_room
Jan 12 14:43:01 vps-sys nodejs-rocket[4172]: 1 records load from rocketchat_room
Jan 12 14:43:01 vps-sys nodejs-rocket[4172]: Will load cache for rocketchat_subscription
Jan 12 14:43:01 vps-sys nodejs-rocket[4172]: 1 records load from rocketchat_subscription
Jan 12 14:43:01 vps-sys nodejs-rocket[4172]: Will load cache for rocketchat_settings
Jan 12 14:43:01 vps-sys nodejs-rocket[4172]: 598 records load from rocketchat_settings
Jan 12 14:43:03 vps-sys nodejs-rocket[4172]: Updating process.env.MAIL_URL
Jan 12 14:43:04 vps-sys nodejs-rocket[4172]: Starting Email Intercepter...
Jan 12 14:43:06 vps-sys nodejs-rocket[4172]: Will load cache for rocketchat_permissions
Jan 12 14:43:06 vps-sys nodejs-rocket[4172]: 74 records load from rocketchat_permissions
Jan 12 14:43:06 vps-sys nodejs-rocket[4172]: Will load cache for rocketchat_roles
Jan 12 14:43:06 vps-sys nodejs-rocket[4172]: 11 records load from rocketchat_roles
Jan 12 14:43:08 vps-sys nodejs-rocket[4172]: LocalStore: store created at
Jan 12 14:43:08 vps-sys nodejs-rocket[4172]: LocalStore: store created at
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: Exception in callback of async function: Error: Failed to load gRPC binary module because it was not installed for the current system
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: Expected directory: node-v48-linux-x64-glibc
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: Found: [node-v57-linux-x64-glibc]
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: This problem can often be fixed by running "npm rebuild" on the current system
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: Original error: Cannot find module '/opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Object.<anonymous> (/opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/grpc_extension.js:44:17)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Module._compile (module.js:570:32)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Object.Module._extensions..js (module.js:579:10)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Module.load (module.js:487:32)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at tryModuleLoad (module.js:446:12)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Function.Module._load (module.js:438:3)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Module.require (module.js:497:17)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at require (internal/module.js:20:19)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Object.<anonymous> (/opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/client.js:38:12)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Module._compile (module.js:570:32)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Object.Module._extensions..js (module.js:579:10)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Module.load (module.js:487:32)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at tryModuleLoad (module.js:446:12)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Function.Module._load (module.js:438:3)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Module.require (module.js:497:17)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at require (internal/module.js:20:19)
Jan 12 14:43:09 vps-sys nodejs-rocket[4172]: at Object.<anonymous> (/opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/index.js:30:14)

**Comment by cy4n** [comment]
did you try `npm install` or `npm rebuild` as the log says?
maybe you can also try to remove the node_modules folder or run `npm prune` before `npm install`

**Comment by andypl78** [comment]
According to the instructions after unpacking I made npm install.
I will check the other recommendations now ;)

**Comment by andypl78** [comment]
npm rebuild not working

```
root@vps-sys:/opt/apps/Rocket.Chat/programs/server$ npm rebuild

> fibers@2.0.0 install /opt/apps/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting
```

```
Jan 12 15:48:02 vps-sys nodejs-rocket[3989]: Expected directory: node-v48-linux-x64-glibc
Jan 12 15:48:02 vps-sys nodejs-rocket[3989]: Found: [node-v57-linux-x64-glibc]
Jan 12 15:48:02 vps-sys nodejs-rocket[3989]: This problem can often be fixed by running "npm rebuild" on the current system
Jan 12 15:48:02 vps-sys nodejs-rocket[3989]: Original error: Cannot find module '/opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'
Jan 12 15:48:02 vps-sys nodejs-rocket[3989]: at Object.<anonymous> (/opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/grpc_extension.js:44:17)

```

**Comment by andypl78** [comment]
remove node_modules and run npm install still not working and there is the same error as above.

```
root@vps-sys:/opt/apps/Rocket.Chat/programs/server$ npm install

> fibers@2.0.0 install /opt/apps/Rocket.Chat/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /opt/apps/Rocket.Chat/programs/server
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

added 136 packages in 3.77s
```

**Comment by andypl78** [comment]
run npm prune and npm install still not working.
gRPC binary is still looking for /node-v48-linux-x64-glibc/grpc_node.node but it is only /node-v57-linux-x64-glibc/grpc_node.node

```
root@vps-sys:/opt/apps/Rocket.Chat/programs/server$ ls /opt/apps/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/extension_binary/
node-v57-linux-x64-glibc
```

```
root@vps-sys:/opt/apps/Rocket.Chat/programs/server$ npm prune
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

up to date in 1.349s
root@vps-sys:/opt/apps/Rocket.Chat/programs/server$ npm install
npm WARN lifecycle meteor-dev-bundle@0.0.0~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@0.0.0 node npm-rebuild.js /opt/apps/Rocket.Chat/programs/server
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

up to date in 1.343s
```

**Comment by andypl78** [comment]
Ok i found the problem I have 2 diffrent versions node.js and now is working ;)
Thx for help.

```
root@vps-sys:/opt/apps/Rocket.Chat$ whereis node
node: /usr/bin/node /usr/local/bin/node /usr/include/node /usr/share/man/man1/node.1.gz
root@vps-sys:/opt/apps/Rocket.Chat$ /usr/bin/node -v
v6.12.3
root@vps-sys:/opt/apps/Rocket.Chat$ /usr/local/bin/node -v
v8.9.3
```

**Comment by miguelmota** [comment]
Same problem on a fresh git clone install

**Comment by reetp** [comment]
> Same problem on a fresh git clone install

Adding this to a bug closed over a year ago is not going to get you any help.

As you have also put the same comment on https://github.com/RocketChat/Rocket.Chat/issues/10161#issuecomment-486475681 you probably need to review your build process and you node/npm versions.

If you still have a problem first ask in https://open.rocket.chat or https://forums.rocket.chat
If it cannot be solved there they will ask you to open a new Issue
