### ISSUE TITLE
Integrate with custom meteor app .

### ISSUE THREAD

**Issue by nelreina** [RocketChat/Rocket.Chat#940]
Hi just beginning to use Meteor and created an production app already. 
I wanted to add chat functionality to the app, can I use rocket.chat with a existing meteor app, with all users already registered ?

**Comment by marceloschmidt** [comment]
This is a very broad request. You should take a look at our live-chat support, if that's what you're trying to do. Other than that, we don't currently have any way to integrate this to other meteor apps via packages, for example.

**Comment by nelreina** [comment]
Now I asked the other way around. Can I integrate my app in yours ?? 

Because I saw a presentation of ur CEO or one of the owners and he said you guy's wants to be the wordpress of the javascript community.

**Comment by marceloschmidt** [comment]
Yes, definitely! We're working on our API so others can do all kinds of stuff, from sending a message to setting preferences, all via API calls... what would be your use case?

**Comment by nelreina** [comment]
I build a package  tracking system for a client of my . Al his costumers can logged in to see the status of their packages , nothing special. But the owner ask  me if I can integrate a chat mechanism in the app. 
So every users have a user accounts already / I need a way to hook in your app. 

I love the app btw :)
