### ISSUE TITLE
several REST API do not return the expected values

### ISSUE THREAD

**Issue by MariusSpangenberger** [RocketChat/Rocket.Chat#9400]
the example result for _groups.kick_ and _groups.leave_ in the REST API documentation states a group (and success) as the return vauel but I only get 
`{"success":true}`

https://rocket.chat/docs/developer-guides/rest-api/groups/kick/
https://rocket.chat/docs/developer-guides/rest-api/groups/leave/ #

edit
Its the same for Chat.pinMessage
https://rocket.chat/docs/developer-guides/rest-api/chat/pinmessage/

edit2
Users.create does not return customFields if provided:
`curl -H "X-Auth-Token: token" -H "X-User-Id: id" -H "Content-type:application/json" server/api/v1/users.create -d '{"name": "CreateTest", "email": "email@user.tld", "password": "anypassyouwant", "username": "CreateTest", "customFields": { "twitter": "@userstwitter" } }'`
returns
`{"user":{"_id":"id", "createdAt":"2018-01-15T10:35:48.749Z", "services":{"password":{"bcrypt":"hash"}}, "username":"CreateTest", "emails":[{"address":"email@user.tld","verified":false}], "type":"user", "status":"offline", "active":true, "name":"CreateTest", "_updatedAt":"2018-01-15T10:35:48.800Z","roles":["user"]},"success":true}`
https://rocket.chat/docs/developer-guides/rest-api/users/create/

**Comment by graywolf336** [comment]
Please open issues to the correct repository and since we are an open source project, we highly welcome pull requests to correct the documentation! https://github.com/RocketChat/docs
