### ISSUE TITLE
How to bypass the notification system?

### ISSUE THREAD

**Issue by mrik974** [RocketChat/Rocket.Chat#9403]
Hi all, and first of all thank you for your amazing work with Rocket.Chat! 
I've been using it as a Slack replacement and it perfectly suits my needs.

Lately I've wanted to use it in a brand new project. Here's my issue about it. 
We're developing a product that will be kind of around a chat service. we chose Rocketchat because it is totally free and we have complete control of where the data is stored. 

However, this product is intended to have  features that are not directly related to Rocket.Chat. And we don't want the users to have direct control over Rocket.Chat, but rather have a special UI to create their groups and connect to them. 

This is why we chose to develop a different UI that connects the user to Rocket.Chat via it's Live APIs and a gateway that restricts the users interactions with Rocket.Chat administration.

It's working well, and now we want to move forward. We want to add Rocket.Chat notifications to our product. 
Users are already notified when they're logged in, but we'd love to send them an email or a text message, or a push notification (Desktop or mobile), depending on their choices. We already built a notification service for our other needs, and what we'd like to do is connect Rocket.Chat to it. 

I know the only way to use Rocket.Chat notifications is to use the official clients and web UI. 
But I want to build a work around. I thought of using the possibility of Rocket.Chat to connect to a `Notification Gateway`, but I can't find any documentation about the APIs I have to implement  to make it work.
Plus, the actual Rocket.Chat connection to a notification gateway is designed for mobile push notification. 
I think I can work it around too, by giving Rocket.Chat a dummy mobile ID for every user and let the gateway find the related user when needed. 
But even there I can't find the API I can call to register a mobile ID for a given user. 

Is there a way I can find it?

Thank you for your time and thanks again for this amazing product!

**Comment by geekgonecrazy** [comment]
Better topic for forum.
