### ISSUE TITLE
All messages in certain channels not displaying

### ISSUE THREAD

**Issue by crsCR** [RocketChat/Rocket.Chat#9404]
### Description:

All messages in 2 public channels of 11 were not displaying on iOS, Android, browser and Mac apps. A restart of the application brought them back again.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 6
* DB Replicaset Oplog:
* Node Version: 8.9.4

### Steps to Reproduce:

1. 
2. 
3.

**Comment by crsCR** [comment]
Already happened again - one channel empty...

**Comment by xWyatt** [comment]
I have users that are experiencing a similar issue where they get a notification that a new message has arrived (mainly on the Rocket.Chat app for Windows) yet no message shows in the room. 

Restarting the application, or refreshing it with Ctrl+R Seems to show the new message. Do you think this is related to the issue you are having @crsCR? If not, I will open a new Issue.

**Comment by crsCR** [comment]
Yes, restarting/refreshing sometimes (not always) brings them back.

**Comment by maik28** [comment]
Got this problem also in 0.68.3. bug occurs in DM and channels, browser and RC client. 

Opened a new issue #11516

Any advice?

**Comment by shaiton** [comment]
I just hit this issue today, against the linux desktop application (0.67, 
     commit 5c74cae8381bf0be43519ffa4ab969016cd52f05)

Only private channels were working as expected. Writting to a public chan was dispatched to others but appeard "grey" on local. And did not receive any incomming messages. But the channel status indicator was telling new unread messages..

Restarting the app and working again :/

**Comment by doktaschier** [comment]
We still have the same issue... any solutions?

**Comment by masahrpro** [comment]
I am not able to see any of the private channels on mobile app, only the public channel is visible and the ones created with the android app on mobile. Is this a known bug?

**Comment by MartinSchoeler** [comment]
Hey, I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
