### ISSUE TITLE
Using settings of the type "code: 'text/html'" for HTML E-Mail adds unwanted line breaks

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#9405]
### Description:

When reading settings of the type `code: 'text/html'` line breaks are replaced with `<br>`-tags. This leads to empty spaces and incorrect HTML in E-Mails. E.g. the setting `Invitation_HTML` uses a field of the type `code: 'text/html'`. When this setting is read `RocketChat.settings.get('Invitation_HTML');` line breaks are replaced by `<br>`-Tags. This leads to unwanted line breaks within the E-Mail body.

For this reason it is currently not possible to create mails embedding images as an attachment (Content-type: multipart/related). 

### Server Setup Information:

Rocket.Chat Version: 0.59.3
NodeJS Version: 4.5.0 - x64
Platform: linux
ReplicaSet OpLog: Enabled

### Steps to Reproduce:

1. Open: Admin --> E-Mail --> Edit Invitation Mail
2. Configure a Invitation Mail using HTML with several line-breaks
3. Invite a new User
4. Look at the source of the Mail, there are unwanted `<br>`-tags

### Expected behavior:

normal line-breaks `\n`

### Actual behavior:

unwanted `<br>`-tags in E-Mails

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
