### ISSUE TITLE
Problems installing rocket chat on centos - node v57

### ISSUE THREAD

**Issue by pacoeu** [RocketChat/Rocket.Chat#9406]
Hi,

I am trying to install rocket.chat on centos following https://rocket.chat/docs/installation/manual-installation/centos/. 

When trying to execute 'node main.js' the console shows this error:

Exception in callback of async function: Error: Failed to load gRPC binary module because it was not installed for the current systemExpected directory: node-v48-linux-x64-glibc
Found: [node-v57-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node'

It seems that the v48 version is installed on the server, and look for that version, however in the tutorial v57 is downloaded.

How can I solve this problem? Do you any way to upgrade node to v57?

Regards

**Comment by reetp** [comment]
Check your node version and see this https://github.com/RocketChat/Rocket.Chat/issues/9368

Not sure which version of CentOS you have but you are going to need node v8.x installed. The docs are a bit of a mess right now - the update to 0.60.x broke a lot of stuff for some of us.

**Comment by drndos** [comment]
Try cd /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_google-vision
npm rebuild

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. Node 5.7 is not supported. Node 8 is the new LTS and should be used since (I think) 0.62.0.


As for other issues with installing on Centos (especially sharp and fibers libraries) please search the issues, there are already open issues for that. They may help you. If you disagree, please let me know :)

Cheers
Twizzy
