### ISSUE TITLE
SlackBridge Out Channels

### ISSUE THREAD

**Issue by madboyprice** [RocketChat/Rocket.Chat#9408]
### Description:

Unable to 'Save Changes' after entering SlackBridge Out Channels. The button remains greyed out

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Linux (vzserver 7 - CentOS7)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 8.9.3 - x64

### Steps to Reproduce:

1. Select 'SlackBridge' in the Administration menu
2. Type the name of the Channel into 'SlackBridge Out Channels' and select, once the Channel name appears
3. 'Save Changes' remains greyed out

### Expected behavior:

I would expect the selected channel to be stored after being able to click 'Save Changes'

### Actual behavior:

Unable to 'Save Changes'

This then results in messages not be sent from RC to Slack:

[34mI20180114-21:33:31.770(13) [34mIntegrations ➔ Outgoing WebHook.debug Got the event arguments for the event: sendMessage { ........ } 
[34mI20180114-21:33:31.771(13) [34mIntegrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: BxWvXRSCBiav9WYrB 
[34mI20180114-21:33:31.772(13) [34mIntegrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.

**Comment by ceriseghost** [comment]
I'm having the same issue.

**Comment by zetahoq** [comment]
Same issue here as well

**Comment by markwooff** [comment]
Same on this end. When can we expect a fix?

**Comment by markwooff** [comment]
Was hoping a fix for this would be included in the 0.63.1 release. Bumping as I would love for this to be fixed so we can integrate Slack again 👍

**Comment by castironclay** [comment]
The only fix I've found is just to enable the 'Slackbridge out' for all channels. Then I'm able to send messages back to slack.

**Comment by vwbusguy** [comment]
Even if I change some other setting, like file uploads, the out channels still aren't actually saved after saving and refreshing.  I've yet to find a workaround in the UI, but I wonder if we can hack this directly in mongo in the meantime?

**Comment by EveBC** [comment]
We still cannot add channels to the `SlackBridge Out Channels` field. I have tested on 0.74.3 and 1.0.0-rc.0

Before Saving (shows channel below field):
![Screen_Shot_2019-04-03_at_3_56_27_PM](https://user-images.githubusercontent.com/40441914/55517289-9552d580-5635-11e9-8964-5def7a874ce8.png)

After Saving (still shows channel):
![Screen_Shot_2019-04-03_at_3_56_45_PM](https://user-images.githubusercontent.com/40441914/55517330-b5829480-5635-11e9-9244-279c391a4150.png)

After Refresh (channel missing):
![Screen_Shot_2019-04-03_at_3_56_52_PM](https://user-images.githubusercontent.com/40441914/55517366-d3e89000-5635-11e9-9883-e8f1d070fbab.png)

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/14273
