### ISSUE TITLE
"Sort by activity" - hiding the chanel list

### ISSUE THREAD

**Issue by efih** [RocketChat/Rocket.Chat#9409]
Hi Guys,

i have weird bug, when i chose the option "Sort by activity" on the my account preferences its hiding the current chanel list (please see the attach photos)
if i choose the anothers options, i see the chanel list currect

* Version of Rocket.Chat Server: 0.60.0
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* Node Version: v8.9.3

### Steps to Reproduce:

1. click on the menu and chose "my account"
2. on the option "Sidebar Channel List Mode" i choose > "sort by activity"

screen shots:
![image](https://user-images.githubusercontent.com/33001397/34917792-75f8434a-f953-11e7-8a45-9acf8636c489.png)
![image](https://user-images.githubusercontent.com/33001397/34917805-ace7e068-f953-11e7-9523-5307b2b0fedf.png)

**Comment by TwizzyDizzy** [comment]
Please try to reproduce this on the latest stable (maybe even wait for 0.63.0 (du to be released on April 3rd).

Had this too for a short time but it's been gone since.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, due to the lack of feedback. Gonna reopen if somebody can still reproduce this (note though, the the sort feature is now above the search bar in main UI).

Cheers
Thomas
