### ISSUE TITLE
Server ignores parameters for REST API channels.history (or group.history)

### ISSUE THREAD

**Issue by MariusSp** [RocketChat/Rocket.Chat#9411]
The Wiki page says channels.history (group.history as well) is a get call, so I tried

```
curl -H "X-Auth-Token: token" -H "X-User-Id: id" -H "count: 5" address/api/v1/channels.history?roomId=GENERAL

curl -H "X-Auth-Token: token" -H "X-User-Id: id" address/api/v1/channels.history?roomId=GENERAL&count=5
```

Either way I get the standard amount of 20 messages, it ignores my parameters. What am I doing wrong?

**Comment by xbolshe** [comment]
A problem is related with an incorrect request. curl does not use parameters after `&` in case of no quotes. A correct request shall be like:

curl -H "X-Auth-Token: token" -H "X-User-Id: id" "address/api/v1/channels.history?roomId=GENERAL&count=5"

**Comment by MarcosSpessatto** [comment]
@MariusSpangenberger, did you solve the problem, with the explanation of @xbolshe?

**Comment by MariusSpangenberger** [comment]
I stopped working on the project at the end of January, therefore I haven't tried @xbolshe explanation. Unfortunately I won't have time to look at it anytime soon. I will update everything and report back sometime in August.

**Comment by MarcosSpessatto** [comment]
@MariusSpangenberger any news?
