### ISSUE TITLE
New Feature: SAML Attribute Handling

### ISSUE THREAD

**Issue by mrdafe** [RocketChat/Rocket.Chat#9413]
### Description:
Allow the editing and creation of attributes using the Administration interface, similar to the functionality already available when using LDAP authentication.

For example, Google as an IdP does not have a default 'full name' attribute to pass to a SP such as Rocket.chat. It only provides first and last name attributes.

I would like to be able to configure Rocket.chat to set the Full Name/cn field to be the concatenation of firstname + space + lastname.

Another example, also with Google as an IdP, is to pass the user's email and have Rocket.chat take the first email part (firstname.lastname [@domain.tld]) as the username. By default, Google does not provide email part as an attribute to pass.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Hosted on rocket.chat cloud

### Steps for Future State with new feature:

1. Configure Rocket.Chat for using SAML for authentication
1.1 Set 'username' field to be %firstname.' '.%lastname
1.2 Set firstname = first_name attribute
1.3 Set lastname = last_name attribute
1.4 Set username = regex expression looking for string before the '@' character in email attribute
2. Configure custom SAML app in G Suite using Rocket.Chat metadata
2.1 Setup custom attribute 'first_name' and choose 'First Name' as value
2.2 Setup custom attribute 'last_name and choose 'Last Name' as value
3. Have a user authenticate to Rocket.chat using G Suite as SAML IdP
4. View user's profile

### Expected behavior:

Full name = First Last
Email = first.last@domain.tld
Username = first.last

### Actual/Current behavior:

Full name = First OR Last but not both
Email = first.last@domain.tld
username = first.last@domain.tld

**Comment by jthomae1** [comment]
+1

**Comment by localguru** [comment]
1.4 why creating the username from email? Take the username from the federation username and regex.

**Comment by arminfelder** [comment]
this should be implemented in https://github.com/steffow/meteor-accounts-saml first

**Comment by tbellembois** [comment]
+1
to support shibboleth auth

**Comment by arminfelder** [comment]
@tbellembois shibboleth would make things, like IDP discovery etc. easier, but I think this should be a separate issue

**Comment by lennartgrunau** [comment]
Any news here?

**Comment by pierre-lehnen-rc** [comment]
This feature was added on Rocket.Chat version 2.1.0
