### ISSUE TITLE
live chat does not work

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#9414]
## Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0-develop
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3

## The error I get 

On the chrome console where the livechat widget is embedded:
![image](https://user-images.githubusercontent.com/6703876/34931279-d747dd70-f982-11e7-87c5-a94251b2c14f.png)

### Option 1

![image](https://user-images.githubusercontent.com/6703876/34931397-6a6f5fb0-f983-11e7-9b3a-b3e21ba0b3cb.png)

The command suggested by the console message does not run.

### Option 2:
![image](https://user-images.githubusercontent.com/6703876/34931294-edeb4724-f982-11e7-94c0-d77f87a34798.png)

## Related issues

https://github.com/RocketChat/Rocket.Chat/issues/9397

**Comment by sampaiodiego** [comment]
this seems to be fixed on latest `0.61.1` version
