### ISSUE TITLE
delete option for announcements

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [RocketChat/Rocket.Chat#9415]
refers to #7124

I would really like to see a delete option for announcements like pinned messages.
Had the same problem described in #7124.
Pinned a message. When the message gets deleted, the announcement is still there.

( Beside the team channels i keep a notes channel for myself, where i regulary delete unneeded stuff.
Now i have a lingering announcement -.-)

**Comment by wanderingduck** [comment]
This is an issue for me as well. Pinning large messages is a nightmare and can render a group almost useless due to the clutter.

I would like an option to delete admin messages like these and an option to hide all admin (action) messages as they serve no purpose to the members.

**Comment by damian-centrone** [comment]
This is now working as expected

**Comment by TheGreatRefrigerator** [comment]
Hi @damian-centrone,

thanks for the update!
could you let me know, in which version this is fixed? We are running on 3.7.0. Would an update to 3.7.1 already fix this or should we wait for 3.8 ?

**Comment by damian-centrone** [comment]
Im testing on 3.8.0-rc.8

**Comment by TheGreatRefrigerator** [comment]
After updating to 3.8.0 we still encounter this problem in both the web client and the app:
After i added a message and pin + unpin 2x it looks like this:
![grafik](https://user-images.githubusercontent.com/23240110/101278423-6fdb7f00-37bb-11eb-85df-0e13c9f277bb.png)
The messages get removed from the "Pinned Messages" view of the channel but remain in the chat as text-corpses...

Even if i delete the original message, the 2 "announcements" saying `... pinned a message:` are still there

Not sure where the issue could come from, if it worked for you during testing 🤷‍♂️
