### ISSUE TITLE
Code block content font-weight set too high

### ISSUE THREAD

**Issue by tetrapus** [RocketChat/Rocket.Chat#9417]
### Description:
The default font weight for code blocks and inline code is set to 600 (semi-bold). This looks like this:
![screenshot from 2018-01-16 17 21 36](https://user-images.githubusercontent.com/712764/34974892-5dc4f8d6-fae3-11e7-8c87-0b17b81a39a2.png)
whereas without the css rule for `font-weight: 600` on `.rc-old code` it looks like this
![screenshot from 2018-01-16 17 22 02](https://user-images.githubusercontent.com/712764/34974941-92244ea6-fae3-11e7-9da8-c940c764500a.png)

which I presume is the expected behaviour, since it is a lot more legible and only the important tokens are bolded.

### Server Setup Information:
(tested on open.rocket.chat)
* Version of Rocket.Chat Server: 0.60.4
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Type `some string`

### Expected behavior:
Not bold

### Actual behavior:
Bold

### Relevant logs:
n/a

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
