### ISSUE TITLE
Launch our Zapier integration out of beta

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#9420]
Last week, Zapier announced an exciting milestone: integrating with 1,000 web tools! Sadly, because our Zapier integration is still in beta, Rocket.Chat isn’t yet one of them.

<img width="1136" alt="screen shot 2018-01-16 at 16 23 11" src="https://user-images.githubusercontent.com/1000217/35005836-f2af4b20-fadb-11e7-9026-955bc2466704.png">

Here's how to launch our integration:

- [ ] Create 10 pre-made Zaps.
- [ ] Embed those pre-made Zaps in 5 minutes or less.
- [ ] Add a Zapier help doc to your site.
- [ ] Reserve a spot for Rocket.Chat to be featured in Zapier email newsletter.
- [ ] Announce the launch of your Zapier integration with a blog post. 

https://zapier.com/apps/rocketchat

**Comment by TwizzyDizzy** [comment]
As discussed at the summit: please add a label "feature-needs-review" label.

/cc @SeanPackham 

Cheers
Thomas
