### ISSUE TITLE
Cant access admin panel after creating a new role

### ISSUE THREAD

**Issue by muhv7** [RocketChat/Rocket.Chat#9422]
### Description:

Added a new permission role and now can't access the admin panel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Ubuntu Server
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances:  1
* DB Replicaset Oplog: 
* Node Version:

### Steps to Reproduce:

1. Add new role, with set to room
2. Nothing
3. Admin panel gone even from the first admin user

**Comment by muhv7** [comment]
Tried this, doesnt work either. It's like the admin role doesnt exsist anymore?

db.users.update({username:'admin'}, {$set: {'roles' : [ "admin" ]}})

**Comment by muhv7** [comment]
Anyone? :) Any help would be really apriciated.

**Comment by muhv7** [comment]
You can close it. It was my own dumb mistake. It seems I edited the admin role and renamed it. The premissions were there but for some reason it wouldnt let me or other admins access the menu.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
