### ISSUE TITLE
'Query' field does not work with channels.list.joined, groups.list, groups.listAll, im.list

### ISSUE THREAD

**Issue by xbolshe** [RocketChat/Rocket.Chat#9423]
### Description:

There is no possibility to use 'query' field with methods like channels.list.joined, groups.list, groups.listAll, im.list becase 'query' is not supported. There is a problem to select rooms with specific properties/regex conditions like customFields.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0-develop on Jan 17, 2018
* Operating System: Ubuntu Server
* Deployment Method(snap/docker/tar/etc): Local compilation and launch a bundle
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 8.9.4

### Steps to Reproduce:

Using REST API:
1. Create a group with customFields.field1
2. Provide a 'query' parameter in groups.list request like { "customFields.field1": "aaa-1"} 
3. Check that only channels with "customFields.field1" = "aaa-1" are in the output

**Comment by sachinrkeche** [comment]
Hello Devs,
Still I'm not getting the expected result of this , I'm trying to pass the query parameter for this https://ctsichat.mvoipctsi.com/api/v1/groups.list?query= { "customFields.field1": { "$regex": "Coders"}} to filter the list of group but all groups are getting in the response , so using this query I expecting below result,

{
"name": "Coders",
"fname": "Coders",
"t": "p",
"msgs": 0,
"u": {
"_id": "LgHtJ3nDioaStn2dy",
"username": "sachin"
},
"customFields": {
"field1": "AndroidUsers"
},
"ts": "2018-01-24T08:04:45.372Z",
"ro": false,
"sysMes": true,
"_updatedAt": "2018-01-24T08:04:45.372Z",
"_id": "w5SRcgYTvwjxBaWZF",
"usernames": [
"sachin"
]
},

Is their any solution, what i am doing wrong, please help me out.

**Comment by sachinrkeche** [comment]
@xbolshe, Yes your right, I'm using  Rocket.Chat version 0.59.4 , you mean i have to upgrade the the version, Thanks you so much.
