### ISSUE TITLE
Don't hide "jump to message" behind popover menu (three dots)

### ISSUE THREAD

**Issue by erlend-sh** [RocketChat/Rocket.Chat#9430]
I just got a mention and I wanted to jump to it. At first I clicked around the message thinking that might make it jump up, but then I saw the toggle up to the right.

<img width="375" alt="screen shot 2018-01-17 at 13 24 41" src="https://user-images.githubusercontent.com/583842/35042855-76f6b306-fb8a-11e7-91a5-e51596a2b8cc.png">

If there's just one choice here anyways, why hide this behind a toggle? I'd much rather have a clearer "jump" icon (like an up arrow) that when clicked will take me to the message immediately. Even if you have expansion plans for this toggle there ought to be a one-click way of jumping to the mentioned message, as that will always be the `#1` thing I want to do after I've been mentioned.

**Comment by geekgonecrazy** [comment]
Yeah I would agree.. we need better UX here if only one item in the overflow.  Maybe even expose like we do the reaction in main channel view.
