### ISSUE TITLE
When starting Rocketchat Menu is shown but rest of screen is white?

### ISSUE THREAD

**Issue by B-Art** [RocketChat/Rocket.Chat#9436]
### Description:

When starting Rocketchat Menu is shown but rest of screen is white?

### Server Setup Information:

* Version of Rocket.Chat Server: Unknown (works fine within browser)
* Operating System: Windows 10 latest release 1709 (16299.192)
* Deployment Method(snap/docker/tar/etc): Windows Installer
* Number of Running Instances: Unknown
* DB Replicaset Oplog: Unknown
* Node Version: 2.10.1

### Steps to Reproduce:

1. Installation, after ending it shows white text on white background. (I can select what is invisable and paste it in another app like notepad, but is unreadable in de application itself.
menu was readable, though selecting debug mode made all black in stead of white. And the reverse.

2. If started from dock icon, even no menu is readable. (white font in white background)
Tried to copy text from update dialog pasting in to notepad makes it readable.

3. Uninstall and reinstall does not help.

### Expected behavior:

Text in contrasting color of background.

### Actual behavior:

Text in white on white background.

### Relevant logs:
{
  "version": "0.59.4",
  "success": true
}

**Comment by ggazzo** [comment]
hey @B-Art I think this problem was solved, please reopen if wanst...
