### ISSUE TITLE
In SC chat - my preference for offline email notifications is set to Disabled but the emails come anyways

### ISSUE THREAD

**Issue by Paul30081988** [RocketChat/Rocket.Chat#9438]
### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by geekgonecrazy** [comment]
You're gonna need to fill in more of this information.  Please fill it out and then re-open
