### ISSUE TITLE
file size limit notification can't be dismissed and remains persistent until reload

### ISSUE THREAD

**Issue by gregs007** [RocketChat/Rocket.Chat#9440]
Can currently be observed on all newer versions of RocketChat, including open.rocket.chat. Screen recording at https://youtu.be/w24BR4FVPHM

When file over size limit is attempted, notification can't be dismissed and remains persistent across channels until app reload.

**Comment by ricardojrgpimentel** [comment]
Every attempt at uploading a file, if it fails the notification cant be dismissed too.
