### ISSUE TITLE
[BUG] Channel name mixed- vs. lower-case

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#9448]
While the web frontend (and iOS App) allows mixed-case only when "special-characters" is turned on, REST-API will allow mixed-case at any time (so does the Android App and may break things) and will create a channel slug with allowed upper case. Slugs should be always lower case.

Eg. sending a request to create/rename a channel `#Channel` will create it, even if `#channel` exists as their ascii sequence differs.

Currently we just slugify if special characters option is set to active, which allows the case described ahead. If the option is set to on, all works as expected.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @soundstorm I hope you don't mind: I'd like to unify the issue you described and issue #4029. I have done a post there to describe the current situation and also took over your comment from here. Maybe you can check out this and link to your PR there (and also check, whether your PR would also tackle the other issues over there).

I hope this is OK for you, if not, please tell me :)

Cheers
Thomas
