### ISSUE TITLE
Search improvments

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#946]
## Scenario

I posted some *StackOverFlow* link on private chat few days ago, and when I searched `stackoverflow` in search, it didn't find it. So I needed manually to go all over the chat and find it.

Also, I think it should be link in Search Sidebar when we are searching for some term, which will lead to chat message in chat thats why search term will not be only taken from context, and it will give u posibility to see messages before and after that

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/7ff13e34-3443-45c0-a382-5bef63bd44ce/2015-10-01_2002.png)

**Comment by royalaid** [comment]
+1

**Comment by dandv** [comment]
Isn't this solved? There's a :point_left: icon under the cog in the search panel.

**Comment by geekgonecrazy** [comment]
Absolutely!  Thanks :grin:

![image](https://cloud.githubusercontent.com/assets/51996/14128447/a8df0086-f5e6-11e5-8c9e-a94c0144f6ea.png)


Snapshot for reference.  @shtefcs closing this.

**Comment by shtefcs** [comment]
It was actually two issues, but both are done.

Tnx
