### ISSUE TITLE
Room Info: 'Title' vs. 'Description' rendering

### ISSUE THREAD

**Issue by jhermann** [RocketChat/Rocket.Chat#9460]
### Description
If you use Markdown in a room's title and description, they render differently when showing the "Room Info" panel. Namely, the title is rendered as HTML (links appear as expected), while description renders in an "edit" variant showing the raw markdown, but with clickable links (i.e. `[label](url)` is shown as a clickable link).

### Server Setup Information
 * Version of Rocket.Chat Server: v0.60.4

### Expected behavior
Render 'Description' markdown as HTML in 'Room Info'.

### Related issues
 * #7260: Description has the same problem as mentioned there for 'Title'

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
