### ISSUE TITLE
Improvement: Send a message via REST API

### ISSUE THREAD

**Issue by hobbsome** [RocketChat/Rocket.Chat#9461]
Hello,

I am using Rocket.Chat on my own server. I am trying to create my own native app for iOS and Android. However, I noticed that in your API docs there is not a `send` request. I was wondering if this was possible?

Thanks,
Jackson =]

**Comment by graywolf336** [comment]
We do: https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/

**Comment by hobbsome** [comment]
Ah thank you very much!

**Comment by graywolf336** [comment]
No problem! :)

**Comment by graywolf336** [comment]
There's also a `chat.sendMessage` that isn't documented yet as it was just recently added. For the difference please see the comments in the code: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/chat.js#L148
