### ISSUE TITLE
Link titles not parsed correct

### ISSUE THREAD

**Issue by jarro2783** [RocketChat/Rocket.Chat#9467]
### Description:

Certain symbols break parsing of the text in a URL. For example, the message

    [T82: `hello`](https://example.com)

comes out as: `T82:=!=vnp5SesrkXFmjauw8=!=`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Ubuntu 16.04

### Expected behavior:

I expect the title to be parsed as markdown so that I get a link that looks like [T82: `hello`](https://example.com)

**Comment by TwizzyDizzy** [comment]
Also present on 0.61.0.

**Comment by jarro2783** [comment]
I think this is fixed. We're running 0.62.1 now and it appears to work. Not sure if someone wants to link up the commits or just close it.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
