### ISSUE TITLE
Renaming upload folder

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#947]
I think that folder for uploading attachment should have different name then `rocketchat_uploads`, regarding white labeling & branding.

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/f693d0ea-8959-4341-a227-a2b5d8678350/2015-10-01_2014.png)

**Comment by geekgonecrazy** [comment]
duplicate of #738 please move discussion there.

Thanks :)
