### ISSUE TITLE
[NEW] Moving "Choose messages" to different menu

### ISSUE THREAD

**Issue by erlend-sh** [RocketChat/Rocket.Chat#9471]
#### Moving "Choose messages" to different menu

The "Choose messages" button is a very handy feature, but it currently resides in the "Room Info" menu. This does not strike me as a very logical location for such a button.

<img width="158" alt="screen shot 2018-01-23 at 14 54 50" src="https://user-images.githubusercontent.com/583842/35279652-f18dcdc6-004d-11e8-8e07-65265ba1f885.png">

I suggest moving (or more specifically, repurposing) this button alongside these options where it's more discoverable:

![image](https://user-images.githubusercontent.com/583842/35279660-f8d2a62e-004d-11e8-87d7-f56f3d0eaa14.png)

In this new context it would probably be more appropriate to label it "Choose message" or "Select message".

**Comment by geekgonecrazy** [comment]
with 0.61.0 it now has its own place in contextual bar
![image](https://user-images.githubusercontent.com/51996/35537893-8c5dc208-0511-11e8-822f-535adf0aec71.png)

![image](https://user-images.githubusercontent.com/51996/35537900-9476bd0a-0511-11e8-90de-772148af8e39.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Erm... then I'm going to go ahead and close this? If not, please get back to me!

Cheers
Thomas
