### ISSUE TITLE
Is there a difference between Quote and Reply?

### ISSUE THREAD

**Issue by erlend-sh** [RocketChat/Rocket.Chat#9472]
These two actions appear identical:

<img width="242" alt="screen shot 2018-01-23 at 15 00 47" src="https://user-images.githubusercontent.com/583842/35279767-5201e98a-004e-11e8-91c7-c00dbdf9c3ae.png">

Since they're the same feature I would suggest removing "Quote".

**Comment by soundstorm** [comment]
Theo don't just appear identical, they are identical ;)

**Comment by gdelavald** [comment]
Hey, initially the reply had a mention of the user, so this would lead to a chain of replies as conversation, where the quote would be just the message highlighted without creating a new flow.
The semantics will probably be addressed once we discuss Threads again, but for now, yes they are the same.
Thanks for the suggestion, I will close the issue for now.
