### ISSUE TITLE
Set as owner/leader/moderator icons on members list are missing

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9473]
@arthurgiustina We need these icons

![image](https://user-images.githubusercontent.com/9200155/35285362-51f10ec6-0044-11e8-8a21-5203b22ff69c.png)

**Comment by arthurgiustina** [comment]
![owner-leader-moderator](https://user-images.githubusercontent.com/30700871/35298773-57be33c6-006a-11e8-808f-1950ae7ac56e.png)

@karlprieb @theorenck these are the options we can choose
