### ISSUE TITLE
Add users tab icon

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9474]
We need an icon that represent the 'invite users' action. Maybe we can add a 'plus' sign on the actual icon.

![image](https://user-images.githubusercontent.com/9200155/35285578-e93cabc8-0044-11e8-83fe-49fbd4ad2502.png)

**Comment by arthurgiustina** [comment]
Corresponding icons in Font Awesome 5 Light

![new-font-awe-01](https://user-images.githubusercontent.com/30700871/35297078-14b43544-0065-11e8-9b7a-765501677f93.png)

@karlprieb @theorenck
