### ISSUE TITLE
Though "Compact" view mode is set, when a user visit "Account Preference" view mode "Normal" is chose

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#9476]
@loloiccl commented on [Thu Jan 11 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/648)

## My Setup
- Operating System: mac OS High Sierra
- App Version: 2.9.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

### Current Behavior

Though "Compact" view mode is set, when a user visit "Account Preference" view mode "Normal" is chose.

### Expected Behavior

"Compact" is chose.

**Comment by gdelavald** [comment]
Closing this as this is not related to Electron. Please check the [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) repository for more information.

**Comment by hugocostadev** [comment]
Hi there!

Sorry, this error does not happen on the latest releases.

[Rocket.Chat](https://rocket.chat/) provides support for 6 months to the latest releases of each major version.

I would suggest you update your [Rocket.Chat](https://rocket.chat/) version to the latest stable version, which you can find it here: [https://github.com/RocketChat/Rocket.Chat/releases](https://github.com/RocketChat/Rocket.Chat/releases)

For more information about your support: [https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions](https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions)
