### ISSUE TITLE
Security Protocol

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#9480]
I have tried to locate the information on whether or not Rocket.Chat uses a security protocol and specifically if it uses the Signal Protocol developed by WhisperSystems.

I know it was one of the Google Summer of Code but beyond one article I found nothing else.  Can anyone advise on this?

**Comment by soundstorm** [comment]
RC is storing messages in plaintext; encryption only by HTTPS transfer AFAIK.

**Comment by c0fe** [comment]
That is nuts, is there any plans to change that?

**Comment by AmShaegar13** [comment]
This would go against one of the core features of Rocket.Chat. Messages are stored server-side and you can access them from everywhere with any device. With a security protocol like those you are asking for this should be nearly impossible.

Although, there is a plan to [implement OTR](https://github.com/RocketChat/Rocket.Chat/issues/36). Which has the afore-mentioned limitations . You cannot access messages from different devices nor from the same device after the current session has been closed.

**Comment by coder-hugo** [comment]
@AmShaegar13 this isn't correct. In your mentioned issue there are also discussions about using [OMEMO](https://en.wikipedia.org/wiki/OMEMO) for OTR messages. This is a multi-end-to-multi-end encryption and allows you to read your encrypted messages that are stored server-side on different devices without the need to exchange keys between your devices. There is just one important thing: All your devices must be registered on the server before the encrypted message was send. So new devices can't decrypt old messages. I'm using the OMEMO encryption on my private jabber server and this works pretty well.

**Comment by AmShaegar13** [comment]
Well, I'm no expert. Sounds good to me. Now we need an expert to implement it. That would be awesome.

**Comment by c0fe** [comment]
I am bit surprised by this since Signal app allows you to have encryption and read messages. Same goes for Skype (at least newer versions)

**Comment by jfml** [comment]
@c0fe Yeah, I was just thinking the same thing: Signal can read messages from different devices (I have no ideas how messages are stored), so what happened to the plan of implementing the Signal Protocol?

**Comment by jfml** [comment]
@c0fe Yeah, I was just thinking the same thing: Signal can read messages from different devices (I have no ideas how messages are stored), so what happened to the plan of implementing the Signal Protocol?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi folks! Please don't be mad at me, but I'm going to close this as there is no bug involved. Also, for a feature request (use Protocol X) it is not refined enough. But I kindly refer you to the feature request category in the forums: https://forums.rocket.chat/c/feature-requests

Please describe there what you want to be implemented and we'll see what the community is coming up with and what the feedback is.

Cheers
Thomas
