### ISSUE TITLE
Not able to upload pictures on both the website as the app

### ISSUE THREAD

**Issue by mphslaats** [RocketChat/Rocket.Chat#9483]
Hi, 

I am using Rocket.Chat for some time now and I have the following versions:
CentOS 7
MongoDB 3.4
Rocket.Chat 0.60.4

I recently updated Rocket.Chat to version 0.60.4. However I am not able to upload pictures anymore now. I tried it on the latest version of both Firefox and Chrome (on Windows 10). I also tried the Rocket.Chat app and Chrome browser on Android 6.
Is this a Rocket.Chat related issue or is it my MongoDB version (because I found out that I have 3.4 instead of 3.6).

Thanks in advance.

**Comment by rodrigok** [comment]
Hi @mphslaats 

It's probably related to windows, we had some fixes on that meaning, could you try our release candidate version?

Thanks

**Comment by mphslaats** [comment]
Hi,

I do not think that it is Windows related because I am not able to upload pictures via my Android 6 device (via both the app and Chrome browser).
I want to try the so called candidate version, but were can I find this because I cannot find them between the releases.

Thanks in advance. MPH

**Comment by mphslaats** [comment]
I fixed this by using the latest version which came out a few days ago,

Thanks^^
