### ISSUE TITLE
URL not detected properly

### ISSUE THREAD

**Issue by aboyton** [RocketChat/Rocket.Chat#9485]
### Description:

When I send the following URL the part after the `'` isn't detected as part of the URL.

https://foo.com/t='a'&s=1

### Client version
Rocket.Chat+: Version 2.10.1
Operating System: Mac OS 
### Steps to Reproduce:

1. Send https://foo.com/t='a'&s=1 in a message
2. View the message as either the sender or receiver

### Expected behaviour:

The whole URL be detected as a URL.

### Actual behavior:

I get the link [https://foo.com/t=](https://foo.com/t=)'a'&s=1

**Comment by sumedh123** [comment]
Taking a look. Will send pr asap.

**Comment by aboyton** [comment]
Is this bug still present since the fix was reverted?

**Comment by aboyton** [comment]
This is still broken. Can we reopen the ticket please?
