### ISSUE TITLE
Feature: Add a "user" shield

### ISSUE THREAD

**Issue by jhermann** [RocketChat/Rocket.Chat#9488]
Related to #6565.

 * Add a route like `/api/v1/shield.svg?type=user&username=someuser`
 * Display user's `name` and `status` (status via either the usual colored circle, or else by changing the shield's background)
 * Can then be used to link to direct chat web UI URL, and display the online status in wikis etc.

**Comment by graywolf336** [comment]
We currently have room shields, so I don't see why we can't do user shields: https://github.com/RocketChat/Rocket.Chat/pull/6565

**Comment by kb0304** [comment]
I want to work on this issue. Please guide me how to proceed.

**Comment by graywolf336** [comment]
@kb0304 Your best bet is to checkout the pull request I linked to.
