### ISSUE TITLE
Username_already_exist string missing

### ISSUE THREAD

**Issue by garychapman** [RocketChat/Rocket.Chat#9494]
### Description:

There is no string defined for `Username_already_exist` which is referenced in packages/rocketchat-ui-account/client/accountProfile.html

**Comment by sumedh123** [comment]
@garychapman I would like to work on this. Please assign.

**Comment by jszaszvari** [comment]
You can't assign GitHub issues. Just submit a pull request when completed.

**Comment by sumedh123** [comment]
@jszaszvari Sure. Will do.
