### ISSUE TITLE
Editing OTR Messages after OTR ended breaks encryption

### ISSUE THREAD

**Issue by georg94** [RocketChat/Rocket.Chat#9502]
### Description:

It is possible to edit OTR Messages after OTR was ended. In this case the message will be sent in clear text.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Debian 8.10
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 12
* DB Replicaset Oplog: yes
* Node Version: 8.8.1

### Steps to Reproduce:

1. Start OTR
2. Write a message
3. End OTR
4. Edit the just sent message

### Expected behavior:

It should either not be allowed to edit the message, or it just should not be sent.

### Actual behavior:

The message will be sent in clear text over the websocket in an `updateMethod` event

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases, we removed the option to delete OTR messages

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
