### ISSUE TITLE
DeprecationWarning: prom-client ... when starting Rocket Chat server

### ISSUE THREAD

**Issue by distlibs** [RocketChat/Rocket.Chat#9503]
### Description:

When I start Rocket Chat server using command `meteor` I get deprecation warning:
`(STDERR) (node:8753) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated` 

I think it can be related with:
`RocketChat.metrics.messagesSent = new client.Counter('messages_sent', 'cumulated number of messages sent');`
in  `packages/rocketchat-lib/server/lib/metrics.js`. 

If I change to this:
`RocketChat.metrics.messagesSent = new client.Counter({'name': 'message_sent', 'help': 'cumulated number of messages sent'});`
deprecation gone.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0-develop (fbbe16c155)
* Operating System:  Ubuntu 16.04.3 64-bit
* Deployment Method(snap/docker/tar/etc): git pull
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3 - x64

**Comment by geekgonecrazy** [comment]
Could you please open a PR with this change? Seems like your changes should fix it for everyone.

**Comment by jgtoriginal** [comment]
@geekgonecrazy I tested this solution and can confirm that it works. So just opened a PR as you suggested.
