### ISSUE TITLE
Contextual Tab Bar "More" Button is a different color than the others

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#9523]
This is a small issue but for those who theme Rocket.Chat it will be an issue, the "more" button on the contextual bar isn't the same color as the other options. To see this change the header's background color to black and the other icons are gray but the more button is black.

**Comment by rodrigok** [comment]
@graywolf336 or @karlprieb can you check if this was already solved?

**Comment by rodrigok** [comment]
I'll close this, please reopen if needed
