### ISSUE TITLE
Mark Direct Message as read with Rest Api

### ISSUE THREAD

**Issue by amonemian** [RocketChat/Rocket.Chat#9529]
### Description:

How can I mark a direct message as read? I have read the documentations, but could not find the solution. I checked the channels.archive, but it can archive a channel not direct messages.

**Comment by michielkn-mobitrace** [comment]
I didn't find how to use the restAPI but using the RealtimeAPI you can use the readMessages method to mark all messages in (a) room(s) as read.

`{"msg":"method","method":"readMessages","params":["roomId"],"id":"0"}`

**Comment by MarcosSpessatto** [comment]
If by chance this does not solve the problem, feel free to reopen this issue.

**Comment by HarshRmodi** [comment]
Hi @MarcosSpessatto

**Comment by HarshRmodi** [comment]
Hi @MarcosSpessatto 

I am working on an unread message with RoomID using real-time API 
I have applied
 `{"msg":"method","method":"readMessages","params":["roomId"],"id":"0"}`
It is working well but it called  ["stream-room-messages"](https://docs.rocket.chat/api/realtime-api/subscriptions/stream-room-messages) twice

Can you please provide me a solution

Thanks In Advance
