### ISSUE TITLE
Xkcd Embed Support

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#953]
Slack currently embeds xkcd like this:
![screenshot 2015-10-01 12 59 37](https://cloud.githubusercontent.com/assets/2439803/10232225/4f038f2e-683c-11e5-973f-4c5e9608d41f.png)
Rocket.Chat currently embeds xkcd like this:
![screenshot 2015-10-01 13 00 52](https://cloud.githubusercontent.com/assets/2439803/10232251/755cfd0e-683c-11e5-91ae-c309d3c51ab0.png)
It would be nice to have embed support for xkcd like slack does at the moment
##

**Comment by liamdawson** [comment]
I'm willing to give this a go.

**Comment by liamdawson** [comment]
I'm leaving this one at this time, btw.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
