### ISSUE TITLE
Problems with new profile view (user info)

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat#9536]
### Description:

1. Custom user fields are missing since I've upgraded to the latest version.
2. "View All Members" margin doesn't look right to me. There's no space between the button and the outer frame.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04 LTS x64
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: (OpLog = Enabled)
* Node Version: 8.9.4

### Steps to Reproduce:

1. Go into any channel
2. Open the Userlist
3. Open an user information page

### Expected behavior:

Custom user fields should be visible. Margin of the button should be bigger.

### Actual behavior:

Custom user fields are not visible. Outer Margin of the button is messed up.

### Relevant logs:
![rocketchat](https://user-images.githubusercontent.com/4711233/35508429-9956c3ae-04f0-11e8-8761-44c2ad775082.png)

**Comment by karlprieb** [comment]
Fixed here #10012

**Comment by karlprieb** [comment]
Sorry, is partially fixed. Custom fields isn't fixed yet.

**Comment by kaiiiiiiiii** [comment]
@karlprieb The custom fields issue has already been fixed in a previous release (0.62.x). I'll close this one again as both issues has been fixed :)

![2018-04-04 13_14_21-](https://user-images.githubusercontent.com/4711233/38304604-474f3d0a-380a-11e8-8a1b-8e255745c8b6.png)

**Comment by karlprieb** [comment]
Thank you @kaiiiiiiiii :)

**Comment by micw** [comment]
Hi, may it be that this is broken again?
I have added a custom field "Durchwahl". Users can see and edit this field in their profile. But I cannot see it on the user info.
I already added it to CustomFieldsToShowInUserInfo - had no effect.
