### ISSUE TITLE
[SUPPORT] Rocketchat setup on AWS ECS with Dynamic Port Mapping

### ISSUE THREAD

**Issue by nbhadauria** [RocketChat/Rocket.Chat#9537]
### Description:

I am setting up rocketchat setup on AWS ECS cluster using dynamic port mapping. I have been running rocket chat using Docker swarm cluster using swarm network so i was able to run multiple instance on same node But on AWS ECS you don't get swarm network. I will describe more what i have done till now below.

### Server Setup Information:

* Version of Rocket.Chat Server: rocketchat/rocket.chat:0.60.4
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 12
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3 - x64

### Setup Done till Now:
Setup a generic AWS ECS cluster using cloud formation template. Along with that I had setup following: 
* Application load balancer
* MongoDB cluster (Not on docker)
* S3 for storage 

Configured one Service on ECS configure container port 3000 to a dynamic port. It was working fine but document sharing was having issues.

Because of upload request being bounce from one instance to another it was not able to find the final uploaded content on the instance, So for a quick fix i set a sticky bit on load balancer for upload request.

For permanent fix i needed to setup INSTANCE_IP and PORT so instances can connect to one another.

I was able to accomplice the INSTANCE_IP by modifying run command to below:

INSTANCE_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4) node main.js

And instance entry in mongo db will look like below:

`chat-cluster0:PRIMARY> db.instances.find()
{ "_id" : "fc7obZFfucB5JAnin", "pid" : 1, "name" : "rocket.chat", "extraInformation" : { "host" : "10.0.0.112", "port" : "3000" }, "_createdAt" : ISODate("2018-01-23T07:16:09.176Z"), "_updatedAt" : ISODate("2018-01-29T11:12:12.799Z") }
{ "_id" : "kub8qf8NeW6Nt3fSu", "pid" : 1, "name" : "rocket.chat", "extraInformation" : { "host" : "10.0.0.125", "port" : "3000" }, "_createdAt" : ISODate("2018-01-23T07:18:16.960Z"), "_updatedAt" : ISODate("2018-01-29T11:12:07.062Z") }`

It was able to pick correct ip of the EC2 Instance but PORT was still missing and to find the dynamic port that is assign there was 2 options:
* Use AWS cli and call the ECS api to find the correct port map
* There is something called [Amazon ECS Container Metadata](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html)

I choose to use Amazon ECS Container Metadata, if you enable this you find the port and other details inside your docker container at $ECS_CONTAINER_METADATA_FILE.

Using that i was able to figure out the dynamic port assign to the container and assign the same as PORT. 

So instance entry in mongo db will look like below:

`chat-cluster0:PRIMARY> db.instances.find()
{ "_id" : "fc7obZFfucB5JAnin", "pid" : 1, "name" : "rocket.chat", "extraInformation" : { "host" : "10.0.0.112", "port" : "44684" }, "_createdAt" : ISODate("2018-01-23T07:16:09.176Z"), "_updatedAt" : ISODate("2018-01-29T11:12:12.799Z") }
{ "_id" : "kub8qf8NeW6Nt3fSu", "pid" : 1, "name" : "rocket.chat", "extraInformation" : { "host" : "10.0.0.125", "port" : "34481" }, "_createdAt" : ISODate("2018-01-23T07:18:16.960Z"), "_updatedAt" : ISODate("2018-01-29T11:12:07.062Z") }`

But now rocket chat will come up on dynamic port assign and not 3000

➔ +------------------------------------------------------+
➔ |                    SERVER RUNNING                    |
➔ +------------------------------------------------------+
➔ |                                                      |
➔ |  Rocket.Chat Version: 0.60.4                         |
➔ |       NodeJS Version: 8.9.3 - x64                    |
➔ |             Platform: linux                          |
➔ |         Process Port: 44684                           |
➔ |             Site URL: https://www.example.chat  |
➔ |     ReplicaSet OpLog: Enabled                        |
➔ |          Commit Hash: 34cd952f96                     |
➔ |        Commit Branch: HEAD                           |
➔ |                                                      |
➔ +------------------------------------------------------+

and since AWS application load balancer expect it be running on 3000 it was not able to connect to it. 

So i needed the entry like above in mongo db but service should start at port 3000, I could not find any help on internet so i modified the code a little. 

In file [presence.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/startup/presence.js) i added below:

      `if (process.env.INSTANCE_IP) {
                instance.host = String(process.env.INSTANCE_IP).trim();
        }
        /* This will read ECS_CONTAINER_METADATA_FILE file and set up dynamic port */
        if (process.env.ECS_CONTAINER_METADATA_FILE) {
                // Define JSON File
                var fs = require("fs");
                // Get content from file ECS_CONTAINER_METADATA_FILE
                var contents = fs.readFileSync(process.env.ECS_CONTAINER_METADATA_FILE);
                // Define to JSON type
                var jsonContent = JSON.parse(contents);
                // Check the container start to be ready before we read the ports
                while (jsonContent.MetadataFileStatus !== 'READY') {
                        // Get content from file ECS_CONTAINER_METADATA_FILE
                                var contents = fs.readFileSync(process.env.ECS_CONTAINER_METADATA_FILE);
                        // Define to JSON type
                                var jsonContent = JSON.parse(contents);
                }
                // Set the Port
                instance.port = String(jsonContent.PortMappings[0].HostPort).trim();
        };

        InstanceStatus.registerInstance('rocket.chat', instance);`

After this i am getting expected results, rocket chat starting at port 3000 but registering dynamic port with connect ip in mongo db.

Everything looks to be working fine, but i am still getting below error while uploading documents. I am not sure if its a serious issue or there are better ways to handle the same.

`rocketchat_logger rocketchat_logger.js:278 StreamBroadcast ➔ Stream.error Stream broadcast from '10.0.0.112:3000' to '10.0.0.112:44684' with name notify-user not authorized
rocketchat_logger rocketchat_logger.js:278 StreamBroadcast ➔ Stream.error Stream broadcast from '10.0.0.112:3000' to '10.0.0.112:44684' with name notify-user not authorized`

I am sorry in advance for posting this here, But i was not sure where to reach out for the same.

If i get this working i will share the full document with all the details to setup the rocket chat on AWS ECS and utilising spot instance for heavy load.

**Comment by nbhadauria** [comment]
I was not able to figure out the error above, so i want with different approach.

1. I setup multiple task definitions and fixing ports to be bind:

chat-cluster-3001	=> Run Command "export PORT=3001; INSTANCE_IP=`curl http://169.254.169.254/latest/meta-data/local-ipv4` node main.js"
chat-cluster-3002	=> Run Command "export PORT=3002; INSTANCE_IP=`curl http://169.254.169.254/latest/meta-data/local-ipv4` node main.js"
chat-cluster-3003	=> Run Command "export PORT=3003; INSTANCE_IP=`curl http://169.254.169.254/latest/meta-data/local-ipv4` node main.js"
..
chat-cluster-300N	=> Run Command "export PORT=300N; INSTANCE_IP=`curl http://169.254.169.254/latest/meta-data/local-ipv4` node main.js"

2. And setup same number of services mapped to same Target Group (in same application load balancer).

chat-cluster-3001 => Task defination : chat-cluster-3001 => Target Group : ecs-chat-cluster
chat-cluster-3002 => Task defination : chat-cluster-3002 => Target Group : ecs-chat-cluster
chat-cluster-3003 => Task defination : chat-cluster-3003 => Target Group : ecs-chat-cluster
..
chat-cluster-300N => Task defination : chat-cluster-300N => Target Group : ecs-chat-cluster

I have configured all the services to auto scale. 

I know it is just a hack, but i couldn't find a better way to do it.

**Comment by kajisaap** [comment]
@nbhadauria How has been your journey running rocketchat in ECS? 

It looks to be uncharted territory. 

As for getting INSTANCE_IP, how about fetching IP through meta-data EC2 service and giving that ENV to the meteor process. In this way, we don't have to patch the code.

**Comment by nbhadauria** [comment]
Just to update:

I am using ECS with mix of On demand and Spot instances and it has been working find for me.

The trick was to use "awsvpc" as network mode and everything worked fine.

And in container configuration command "export INSTANCE_IP=`hostname -i`; node main.js"

I would like to create a cloud formation temple for the same when i get time.

**Comment by alvarow** [comment]
I had to change Entrypoint to "/bin/bash,-c" and @nbhadauria trick worked great. TargetGroup type IP and the Rocket.chat instances show the proper awsvpc IP now.
