### ISSUE TITLE
[FEATURE] Alert of new version available

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#9542]
### Description:

Feature to alert administrators (could be configurable) when there is a new version of the Rocket.Chat server available and show if that update includes a security fix.

- Show an alert on top of the screen that could be dismissed (@arthurgiustina I need your work here)
- Send a message via Rocket.Cat to all administrators alerting about the update, so that could alert them via email or push notifications
- Send an email too alerting in case they changed the setting to not receive messages via email

The service will run in a cron job every day and will check against one of our services, for that the instance will need to inform their version, nodejs version, OS distribution and version and maybe some more data, always anonymously, of course this check could be disabled.

**Comment by arthurgiustina** [comment]
@rodrigok @theorenck 

![version 01](https://user-images.githubusercontent.com/30700871/35740002-a22bf012-081a-11e8-95a0-ce66528a3e28.png)

![version 02](https://user-images.githubusercontent.com/30700871/35740003-a24e7c36-081a-11e8-9154-361c80cee533.png)

![version 03](https://user-images.githubusercontent.com/30700871/35740004-a2738756-081a-11e8-8cfd-1cc6159b2814.png)

![version 04](https://user-images.githubusercontent.com/30700871/35740006-a2a14876-081a-11e8-99cb-2bebe8bfa2db.png)

**Abstract Link:** https://share.goabstract.com/68469a46-d39a-460c-a19a-764d74c97f7b

**Comment by arthurgiustina** [comment]
Full Screen Alert

![version 06](https://user-images.githubusercontent.com/30700871/35741303-9c5a3eb0-081e-11e8-81b6-daf65d1cae01.png)

![version 05](https://user-images.githubusercontent.com/30700871/35741304-9c7a8e04-081e-11e8-929e-f52d910ed8c5.png)

**Abstract Link:** https://share.goabstract.com/9a12110f-5c2a-4b99-8f2b-879090631605

**Comment by arthurgiustina** [comment]
![version 08](https://user-images.githubusercontent.com/30700871/35742578-055715ca-0822-11e8-86ee-6c9e356ed7f6.png)

![version 07](https://user-images.githubusercontent.com/30700871/35742579-05787abc-0822-11e8-937e-7fcb00579682.png)
