### ISSUE TITLE
Update steffo:meteor-accounts-saml

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#9545]
https://github.com/steffow/meteor-accounts-saml

**Comment by engelgabriel** [comment]
May be needed for https://github.com/RocketChat/Rocket.Chat/pull/9546

**Comment by megamaced** [comment]
Upgraded from 0.61.0 to 0.62.1.. Now my SAML auth is broken.. Config didn't change

RC configured to connect to Microsoft ADFS 2.0

I now get error

Sorry, an annoying error occured
TypeError: profile.nameIDFormat.indexOf is not a function

**Comment by arminfelder** [comment]
@engelgabriel I updated the steffow meteor-saml package, to hotfix the broken SAML since 0.62:

#10212 -> fix for release candidate
#10210 -> fix for develop
#10209 -> fix for master

**Comment by gerbsen** [comment]
@arminfelder @engelgabriel We have merged a [pull request](https://github.com/steffow/meteor-accounts-saml/pull/31) for encrypted assertions into `meteor-accounts-saml` do you guys see any chance that our changes make it to `develop`? if so, what would be the optimal way?

**Comment by arminfelder** [comment]
@gerbsen RC uses a slightly modified Version of the meteor-accounts-saml lib, which forces you, to merge it manually, which is ugly, but not too hard.

**Comment by gerbsen** [comment]
Thanks for your response @arminfelder This means we need to change this: https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/meteor-accounts-saml ?

**Comment by arminfelder** [comment]
@gerbsen yes

**Comment by gerbsen** [comment]
And would you consider merging this, i.e. are PRs welcome here?

**Comment by arminfelder** [comment]
@gerbsen PRs are certainly welcome, but it often takes quite some time get reviewed by someone who is allowed to

**Comment by tuxcrafter** [comment]
I am using Rocket.Chat 0.74.3 and I am having SLO errors with SAML. When looking at the code I see differences does the latest version of Rocket.Chat have the upstream patches from steffo? Would somebody be willing to help me out: https://github.com/RocketChat/Rocket.Chat/issues/13831

There is still html body generation in a few places in the code, can this be updated as well to be integrated better?
```
[root@rocketchat01 packages]# fgrep "<body>" steffo_meteor-accounts-saml.js
  let content = '<html><head><script>window.close()</script></head><body><H1>Verified</H1></body></html>';
    content = `<html><body><h2>Sorry, an annoying error occured</h2><div>${err}</div><a onclick="window.close();">Close Window</a></body></html>`;
```

**Comment by geekgonecrazy** [comment]
@rodrigok @pierre-lehnen-rc with all of the changes done in SAML is this still needed?
