### ISSUE TITLE
Statuses beneath username on a Direct Message begins with a lower case letter

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#9547]
This looks sloppy and doesn't match the statuses on the left where you set your own. Will try and sort a pull request ASAP for this. :- )

**Comment by TwizzyDizzy** [comment]
@HammyHavoc my suggestion for future requests: do a small screenshot - this makes things so much more understandable :) Also, in the future, please adhere to the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) :kissing_heart: 

Here we go, I think that's what you mean, right?

![image](https://user-images.githubusercontent.com/179595/35968803-26ffee16-0cc5-11e8-9f39-51629803d17b.png)

This is still present in 0.61.0.

Cheers
Thomas

**Comment by HammyHavoc** [comment]
@TwizzyDizzy No problem; I did it from my phone, so didn't get the template on the app I'm using for GitHub, sorry! :- )

Looks perfect! Thank you!

**Comment by sumedh123** [comment]
@HammyHavoc Did you start working on this? If not may I send a PR?
