### ISSUE TITLE
gitlab icon link error

### ISSUE THREAD

**Issue by akuma** [RocketChat/Rocket.Chat#9550]
### Description:

When send a gitlab link with `(...)`, the gitlab icon link is error.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: CentOS 6
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* Node Version: 8.9.4

### Steps to Reproduce:

1. send a gitlab link like: `(http://gitlab.example.com/foo/bar)`
2. click the gitlab icon link

### Expected behavior:

goto `http://gitlab.example.com/foo/bar`

### Actual behavior:

goto `http://gitlab.example.com/foo/bar)`

**Comment by sumedh123** [comment]
@akuma I cannot reproduce this issue. Can you give some more info on this one?

**Comment by akuma** [comment]
![2018-02-23 9 54 25](https://user-images.githubusercontent.com/237677/36574325-256ead1e-1880-11e8-8c13-c5dde45bbaed.png)

**Comment by karlprieb** [comment]
@akuma can you give as a real link so can we reproduce the issue? And if possible sent how did you wrote that message too.

**Comment by akuma** [comment]
The link is a git project link.

**Comment by karlprieb** [comment]
@akuma What do you wrote on message box? something like this? `[ ](http://gitlab.example.com/foo/bar)`?

**Comment by akuma** [comment]
@karlprieb yes.

**Comment by karlprieb** [comment]
Sorry @akuma but I can't reproduce that on 0.62
![image](https://user-images.githubusercontent.com/9200155/36920334-2d8302c4-1e3f-11e8-894a-c445d003a4a9.png)

**Comment by akuma** [comment]
@karlprieb The error link is the gitlab logo link，not the project name link.

**Comment by oguhpereira** [comment]
@tassoevan, @akuma I tested on Open Rocket.chat Server looks like it was solved.

the gitlab url is not add `)` to end.
