### ISSUE TITLE
[Upload File Problem] - File Size is too small

### ISSUE THREAD

**Issue by MICFTK** [RocketChat/Rocket.Chat#9552]
### Description:

When I upload a file using Rocket chat app on iOS, it prompts **File size is too small (min = 1) [file-too-small]**. It has no problem on desktop application.
[Error Screen](https://drive.google.com/uc?export=download&id=18jUztyKyzoLaVihXz2KN6o--E0Ll8g1X)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances:  1
* DB Replicaset Oplog:  -
* Node Version: v8.9.4

**File Upload Setting**
File Uploads Enabled: **True**
Maximum File Upload Size (in bytes): **200000000**
Accepted Media Types:  **< Empty >**
Storage Type: **GridFS**
Protect uploaded files: **True**
File Uploads Enabled in Direct Messages: **True**

### Steps to Reproduce:

1. Open Rocket Chat App on iOS
2. Open a chat with anyone and click the "+" icon -> Select "Choose From Libaray"
3. Choose any file/image

### Expected behavior:

File should be uploaded successfully

### Actual behavior:

File size is too small (min = 1) [file-too-small].

### Relevant logs:
n/a

**Comment by MICFTK** [comment]
Upgrade to 0.61 and the problem is fixed.

**Comment by zenjabba** [comment]
Having the same problem with 0.68.5 and iOS

**Comment by mariusherea** [comment]
Same, version 0.74.3, from iOS
