### ISSUE TITLE
Inline code `test`/`test` not parsed correctly

### ISSUE THREAD

**Issue by martinvonwittich** [RocketChat/Rocket.Chat#9553]
### Description:

This is a very minor issue, but I've noticed it several times now, and the Rocket.Chat behaviour seems to deviate from several other Markdown interpreters I've tested.

The problem is that Rocket.Chat won't display the following Markdown code correctly:

\`test\`/\`test\`

See Steps to reproduce below. I've tried several other Markdown interpreters I've found online, and they all display it correctly:

* https://dillinger.io/
* http://markdownlivepreview.com/
* https://stackedit.io/app
* https://markdown-it.github.io/

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Debian stretch
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3

### Steps to Reproduce:

Post this string in Rocket.Chat:

\`test\`/\`test\`

### Expected behavior:

It should be displayed like this (GitHub does it correctly):

`test`/`test`

### Actual behavior:

But instead it is displayed like this:

`test`/\`test\`

**Comment by c0dzilla** [comment]
I've made a pull request that's failing a test which is checking exactly what this issue complains about. So wanted to know: is there any particular reason why the regex has been written like this that I might be unaware of? Or should i modify the test?

**Comment by TwizzyDizzy** [comment]
Seems to be working for me by now on https://open.rocket.chat ... can you confirm this? :)

Cheers
Thomas

**Comment by martinvonwittich** [comment]
> Seems to be working for me by now on https://open.rocket.chat ... can you confirm this? :)

Nope, can still reproduce it in https://open.rocket.chat/channel/01test

I typed \`test\`/\`foobar\` and RocketChat rendered it as `test`/\`foobar\`.

**Comment by TwizzyDizzy** [comment]
OK. You're right. I don't know what I did up there, but I was talking rubbish obviously. Sorry for that.

Cheers
Thomas
