### ISSUE TITLE
As admin user on Rest API, I can list groups but can't get infos on groups when not member

### ISSUE THREAD

**Issue by tristanlt** [RocketChat/Rocket.Chat#9555]
### Description:

As admin user, I can get groups list (/v1/groups.listAll), but can't get informations on a group (/v1/groups.info?roomName=%s) if admin user wasn't group member. 

My use case is to detect orphaned or dead room with our monitoring system. Getting on all rooms instances, rooms without members and message for a while.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Ansible 2.4
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4

### Steps to Reproduce:

1. Auth as admin, retrieve authToken and userID
2. Use then credentials to retrieve all groups ("%s/v1/groups.listAll" % (api_url))
3. Getting all groups, membered or not 
4. Trying to get info on unmembered group ( "%s/v1/groups.info?roomName=%s" % (api_url, group) )
5. Getting 403 error

```python
#!/usr/bin/python
api_url = "https://myrocket.fqdn/chat/api"
username = "adminuser"
password = "secret" 

endpoint = "%s/v1/login" % (api_url)
data = { "username": username,
          "password": password }
r = requests.post(endpoint, data=data)
credentials = r.json()['data']
headers = { "X-Auth-Token": credentials['authToken'], "X-User-Id": credentials['userId'] }

endpoint = "%s/v1/groups.listAll" % (api_url)
r = requests.get(endpoint, headers=headers)
for c in r.json()['groups']:
    print(c['_id'], c['name'])
# Getting info for a group which haven't adminuser as member
endpoint = "%s/v1/groups.info?roomName=%s" % (api_url, 'admin-is-not-member-group')
r = requests.get(endpoint, headers=headers)
print(r.json()['success'])
```

### Expected behavior:

As admin, I hope to retrieve all groups informations.

### Actual behavior:

This request was forbidden, even for an admin user.

**Comment by graywolf336** [comment]
Closing as the information is the same in `groups.listAll` room objects as is `groups.info`.
