### ISSUE TITLE
Broadcast channels

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#9556]
The idea is to have a new option on create channel page called "Broadcast Channel", having it toggled on will disable "read only" toggle.

Only owners will have permission to write on this channel.

Every message on this channel will have an action button called "Reply" that once hit will redirection the user to direct room with the sender with clicked message auto-filled as a reply on the text box.

- [ ] Apply options on create channel and edit channel

- [x] Insert button 'reply' on each message

- [x] Open room by reply

- [x] block user list to normal users

**Comment by kb0304** [comment]
Hi @sampaiodiego , 
I would like to work on this feature. Could you please assign it to me.

**Comment by adrianovieira** [comment]
I'm trying to use this...

But if we set a channel as *read only* and *broadcast* one that `reply' button'` appears to be useless.

So, you it would "hide" that button, wouldn't it?

**Comment by sampaiodiego** [comment]
looks like we have an issue. the button is intended to work. can you please open an issue describing it please @adrianovieira ?

**Comment by adrianovieira** [comment]
Ok! But I'll perform an update of our instance (which is 3.0). After that I will open if the issue still there.

Thanks, by your quick response.
