### ISSUE TITLE
File list click on some files does nothing

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#9557]
* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap

Clicking on pdf or mp4 file does nothing. No download or view offered.

Also clicking on image only offer to view that image, no gallery mode triggered like how it work in the message window.

**Comment by bayareacoder** [comment]
Issue: On Mac client, when clicking pdf file in file list sidebar, nothing happens. 
Expected: open preview or start file download

Normal behavior seen:
On browser, when clicking pdf file in file list sidebar, it downloads the file.
On Mac client, when clicking image PNG it opens a preview.

**Comment by tassoevan** [comment]
I made a workaround for this, by forcing a download on click. I believe that, ideally, desktop client users expect files open directly in native applications instead of see a "Save file..." dialog.

**Comment by bayareacoder** [comment]
Yes, either in-app preview or file download are fine. Right now Mac client does not do anything so we can’t really use it since we can’t see uploaded PDF files from file list.

Where is this being tracked to be in next master branch, or is it already?

We self-deployed Rocket.Chat on Heroku using Heroku's ‘one-button deploy’ that picks up from master branch.

**Comment by adipose** [comment]
Using .66.3 on CentoOS this issue affects all windows clients.  Right click -> open link works fine, but clicking does nothing.  Incidentally, opening/downloading the files in the browser is not desirable.  The application should offer to open the file directly after downloading to a temporary location (%temp% on Windows).  The ability to save directly already exists within RocketChat.Electron.
