### ISSUE TITLE
Loading rooms quite slow

### ISSUE THREAD

**Issue by AmShaegar13** [RocketChat/Rocket.Chat#9571]
### Description:

Loading rooms for the first time after visiting the chat is quite slow. Usually, it takes more than 2 seconds. A performance profile in Chromium reveals that most of the time is lost in the client running javascript. Loading the actual data is quite fast.

This is a screenshot of a performance analysis when clicking on #support on https://open.rocket.chat/: https://prnt.sc/i8p6jl (Sorry for the link. It does not upload the image at the moment.)

This is the 45 MB analysis export: https://drive.google.com/open?id=167htvU6nhvGCbt_KLanBU6LpeKfmz9fU (4,9 MB compressed)

Is there anything we can do to speed this up? Many of our users come from Hipchat which is super fast and are quite annoyed now. We want Rocket Chat to be successful here so we need some assistence.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 12
* DB Replicaset Oplog: on
* Node Version: 8

### Steps to Reproduce:

1. Reload the chat to ensure room cache is cleared.
2. Click on a room with a long history
3. Wait for at least 2 seconds watching the loading indicator before any messages are displayed.

### Expected behavior:

I'd expect the room to be displayed in less than a second. At least fetching the history (`loadHistory` method) only takes 50 ms. Client-side computations should not add another 2 seconds to that.

### Actual behavior:

Th loading indicator is displayed while some javascript is executed for at least 2 seconds.

### Relevant logs:

See performance analysis in the description.

**Comment by amonemian** [comment]
How can we change the paging size of loading histories of  a room? It seems that RC loads a huge size of history when loading the room. (for example, 5 previous messages would be great)

**Comment by AmShaegar13** [comment]
This has been fixed some time ago.
