### ISSUE TITLE
Feature: Foreign content should not be loaded from unsecure connections.

### ISSUE THREAD

**Issue by ladidadida** [RocketChat/Rocket.Chat#9575]
### Description:

When sharing a link to a foreign site, that is not secured, or if the corresponding certificate is out of date, probably this might open security holes. What about just loading foreign content that is via secure https connection?  

### Steps to Reproduce:

1. Paste a link to an external ressource that has an outdated https certificate
2. Firefox issues that parts of the loaded site are not secure.

**Comment by localguru** [comment]
duplicate #7490

**Comment by engelgabriel** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/971

**Comment by engelgabriel** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/971
