### ISSUE TITLE
Rocket.Chat, Snap, DigitalOcean : but requests are slow

### ISSUE THREAD

**Issue by dotMastaz** [RocketChat/Rocket.Chat#9579]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: ubtuntu 16.04.3
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances:  1
* Server: DigitalOcean : 1GB Memory & 1vCPU
* Node Version:

### Steps to Reproduce:

I install Rocket.chat via Snap on a DigitalOcean Server

### Expected behavior:

It's very good but...

### Actual behavior:

I find it very slow, especially when I list users in the administration. it takes several seconds for the list of 4 users to appear.

Is it normal because i install Rocket.Chat via Snap ?

Thank you !

**Comment by dotMastaz** [comment]
I found the problem...
It's ClamAV : taking 50% of RAM...

Thank you !

**Comment by graywolf336** [comment]
So, this can be closed?

**Comment by brunorbarroso** [comment]
Hey, @dotMastaz. How did you install rocket.chat by snap in digitalocean?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this due to lack of feedback and also because the original issue didn't seem to have been an RC issue. If you disagree, please get back to me directly!

Cheers
Thomas
