### ISSUE TITLE
Slack-like Integration with GitHub

### ISSUE THREAD

**Issue by medvednikov** [RocketChat/Rocket.Chat#958]
Hello,

Sorry if this is explained somewhere else already. I couldn't find the answer.

I finished setting up Rocket Chat for my company. All internal notifications have been migrated via Rocket.Chat API.

Now the only thing we are missing is receiving notifications from GitHub (commits, pull requests etc).

What's the best way to achieve this?

Thanks a lot.

**Comment by geekgonecrazy** [comment]
@medvednikov currently we're achieving this using hubot.  We've got an adapter for hubot over at: https://github.com/RocketChat/hubot-rocketchat

Just adding the package: hubot-github-repo-event-notifier to hubot will allow you to receive github notifications.  If you check out our [community chat](https://demo.rocket.chat) this is how we are doing it there.

**Comment by Sing-Li** [comment]
@medvednikov please reopen or logon to demo if you need further support.
