### ISSUE TITLE
Multiline code inline

### ISSUE THREAD

**Issue by agustinventura** [RocketChat/Rocket.Chat#9581]
### Description:

One line code inline works as expected, but multiline is not working (shows the backticks and does not highlight the code).
See attached image:
![2018-02-02 11_33_50-rocket chat de agapa](https://user-images.githubusercontent.com/490045/35728822-176a451c-080d-11e8-8567-04732db97067.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Debian 8.9
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: No
* Node Version: 8.9.3

### Steps to Reproduce:

1. Copy any multiline code snippet, such as:
`public static void main (String ... args) {
    System.out.println("Hello world!");
}`
2. Open and close backticks in text editor or choose </> (inline_code).
3. Paste snippet
4. Send

### Expected behavior:

Should highlight all the lines in snippet, as for one line snippets.

### Actual behavior:

Shows the backticks and treat it as normal text.

### Relevant logs:
N/A

**Comment by AmShaegar13** [comment]
Multiline code is done by triple backticks.

```
` ` `bash
multi
line
` ` `
```

**Comment by agustinventura** [comment]
Thanks @AmShaegar13!!

**Comment by rgoerner** [comment]
@AmShaegar13  sorry for bothering, but multiple lines seems not to work with triple backticks on current version ?

**Comment by rgoerner** [comment]
It works with ``` without any space only, but marking as code - area still does not work as mentioned here: https://github.com/RocketChat/Rocket.Chat/issues/9625
