### ISSUE TITLE
Highlight: Text entry box label indicates the use of comma separator instead of <ENTER>

### ISSUE THREAD

**Issue by flam22** [RocketChat/Rocket.Chat#9583]
### Description:

Highlight: Text entry box label indicates the use of comma separator instead of `<ENTER>`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0

### Steps to Reproduce:

1. Goto user preference screen

### Expected behavior:

Help text should indicate the use of `<ENTER` as the separator to match up with the functionality.

### Actual behavior:

Help text indicates commas are used as the separator but functionally `<ENTER>` is now used.

### Relevant logs:

N/A

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

This fields accepts both ways, in the end the text with ENTER will be replaced and it'll be inserted commas 

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/6cceceeb-3f3f-40e0-b47b-5091c2831411)


---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
