### ISSUE TITLE
WhatsApp (for Business) intergration in Livechat

### ISSUE THREAD

**Issue by Wouter0100** [RocketChat/Rocket.Chat#9588]
Feature request to build the new Whatsapp For Business into the livechat software of Rocket.Chat. Could be done through, for example, Web WhatsApp.

**Comment by ElsimarGoncalves** [comment]
hi, 

some evolution of this theme ?

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

This feature already exists on the latest releases 
---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
