### ISSUE TITLE
Add wrapper for Babel's parser used for ESLint 

### ISSUE THREAD

**Issue by lindoelio** [RocketChat/Rocket.Chat#9593]
Add babel-eslint to Rocket.Chat core.

This wrapper allows us to lint all valid Babel code with ESLint. It provides, for example, to apply lint for class methods as arrow functions, which deliver better and easier scope bind control.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
