### ISSUE TITLE
Rocket.Chat and Redmine

### ISSUE THREAD

**Issue by phlegx** [RocketChat/Rocket.Chat#9595]
Hi! 

If someone requires notifications from Redmine to Rocket.Chat, it can use [phlegx/redmine_rocketchat](https://github.com/phlegx/redmine_rocketchat) plugin for Redmine.

Thx for this awesome chat! It rock's! 🚀 👍

**Comment by mrzegocki** [comment]
unfortunately  supports only Redmine version 2.0.x - 3.3.x.

**Comment by phlegx** [comment]
@mrzegocki This is a better option now: https://github.com/alphanodes/redmine_messenger

**Comment by reetp** [comment]
This should probably be closed and go into Documentation??

**Comment by phlegx** [comment]
Yes. Closing it. 

@reetp could you add it to the docs? Surely helpful for many.

**Comment by reetp** [comment]
https://github.com/RocketChat/docs/pull/1375
