### ISSUE TITLE
real name in email header From:  confuses users

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#9596]
### Description:

Since name the email Header `From:` contains the user's real name in offline notification emails, people start to answer those emails with their email client. But those emails are sent to the global `From Email` set in `Administration/Email/SMTP`.

`User Realname <globalfrom@domain.tld>`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): self build bundle
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 8.9.4

### Steps to Reproduce:

1. send an email to an user, which is offline. `Direct Reply`is disabled!
2. check header of the sent offline email

### Expected behavior:

The email address should fit the real name in `From:` header in an offline notification email, so that a reply by email is sent to the user's email address and not the the  global `From Email` set in `Administration/Email/SMTP` (`Direct Reply`is disabled).

Another idea could be to split up email address for offline notifications and global address, so that answers to offline notifications are sent to a kind of no-reply address, which runs an autoresponder.

### Actual behavior:

The email address doesn't fit the real name in `From:` email header.

**Comment by localguru** [comment]
See PR https://github.com/RocketChat/Rocket.Chat/pull/15767

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
