### ISSUE TITLE
missing real name in email header To: (naked_to)

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#9600]
### Description:

A real name is missing in email header `To:` which could result in a higher spam rating e.g. by spamassassin (naked_to).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): self build bundle
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 8.9.4

### Steps to Reproduce:

1. send a message to an user, which is offline
2. check the email header To: of that offline email notification

### Expected behavior:

email header `To:` should contain the real name of a user.

### Actual behavior:

email header `To:` only contains the user's email address (naked To: header)

**Comment by localguru** [comment]
Some code ideas

**packages/rocketchat-lib/server/functions/notifications/email.js:**
```
        const email = {
                to: emailAddress,
                subject: emailSubject,
                html: contentHeader + content + divisorMessage + link + contentFooter,
        };
        
+      const recipient = RocketChat.models.Users.findOneByEmailAddress(emailAddress);
+      email.to = `${ recipient.name } <${ emailAddress}>`;
```

**Comment by localguru** [comment]
See PR https://github.com/RocketChat/Rocket.Chat/pull/15767

**Comment by subham103** [comment]
@localguru, Is it intended behavior? While sending mail to another user I come across this which seems weird to me.
![Rocket Chat(1)](https://user-images.githubusercontent.com/43502196/74438444-2fa7ba80-4e90-11ea-8ea9-1a1412522c84.png)

Actually, I am unable to send mail to any user as it's giving me an error: `moment-locale-not-found`.
This seems like an issue to me. Kindly help how to reproduce this issue #9600
