### ISSUE TITLE
Bug: message storm on bidirectional integrations

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#9603]
### Description:

I have two rocket chat servers, and I want one particular channel to be seen on both servers, without having the same users on both. So I create an incoming integration on both, outgoing integration on both, and connect the servers that way, with each integration specifying the one channel I want linked. The result is a never ending message storm of integrations picking up each others messages.

suggestion; 1) have an outgoing ntegration ONLY send messages that are not themselves from an integration, or preferably 2) have a new type of integration specifically designed to link one (or more) channels from one server to one (or more) channels from a different server.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: debian
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2

**Comment by madguy02** [comment]
@sinteur I guess, you are trying to share a common channel between two instances of Rocket.Chat using Webhooks? Looking at your suggestion on (2), i think you are talking about trying to federate channels between RC servers?

**Comment by sinteur** [comment]
Correct, using webhooks. And I guess federating channels between servers is a decent way to describe it.

**Comment by madguy02** [comment]
OK, the idea of Federation is very much a WIP as of now.

**Comment by madguy02** [comment]
Once federation is implemented, this will solve most of the issues and we might not require web hooks.
Thanks for your suggestion

**Comment by graywolf336** [comment]
@sinteur Why not include the message id on each server so that you can verify it hasn't been sent already?

**Comment by sinteur** [comment]
That would be an option, but I prefer federation :-D

**Comment by graywolf336** [comment]
Without a doubt, but until then, as that is a ways off, this is one route you can go. :)

**Comment by alansikora** [comment]
Closing this, this should be fixed on newer versions.
