### ISSUE TITLE
internal hubot in snap installation does not work

### ISSUE THREAD

**Issue by schirrmie** [RocketChat/Rocket.Chat#9606]
Hi, we want to use the internal hubot but don't get it to work and need some help. We have Rocket.Chat 0.61.0 on Ubuntu installed with snap. We enabled internal Hubot under Administration settings. We configure a folder inside the snap installation and add scripts to load. Under View Logs we see that the scripts are successfully loaded. This is one example test.coffee script

module.exports = (robot) ->

  robot.respond /hello/i, (msg) ->
      msg.send 'Hello World'

I tried /hello or @rocket.cat /hello but nothing happend or only "No such command: /hello"

No Errors or anything else in the logs. What do we miss? Why we don't get the internal hubot get to work?

Thanks!

**Comment by timkinnane** [comment]
Please see the [last comment on this related issue](https://github.com/RocketChat/Rocket.Chat/issues/8025#issuecomment-381470969).
