### ISSUE TITLE
Can not quote message from the bot

### ISSUE THREAD

**Issue by kvaps** [RocketChat/Rocket.Chat#9614]
### Description:

No way for quote and resend message from the bot.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar 
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: v8.9.3

### Steps to Reproduce:

1. Open group with bot
2. Quote message from the bot
3. Send message to someone

### Expected behavior:

Quoted message sent

### Actual behavior:

Empty message sent

**Comment by graywolf336** [comment]
Can you show a screenshot of the message you're trying to quote?

**Comment by kvaps** [comment]
Sure,
![rocketchat-bug](https://user-images.githubusercontent.com/7556217/35884833-2e07eef0-0b8c-11e8-8f01-43828aa72674.png)

**Comment by kvaps** [comment]
UPD: Any qoute shows like so

**Comment by kvaps** [comment]
Sure, example message:

screenshot:
![123](https://user-images.githubusercontent.com/7556217/35885565-8ea4d190-0b8e-11e8-88d4-969a54421b67.png)
code:
```
**Zabbix database is down.** ```Zabbix database is down.```
```
this error in firefox console:
```
Error invoking Method 'sendMessage': Internal server error [500] 539c21bfd0b8a570b65fc22dca1869f7cfd87ee8.js:1:6261
```

**Comment by graywolf336** [comment]
Thanks :+1:

**Comment by kvaps** [comment]
I think solved
