### ISSUE TITLE
Notification about new message with quote, shows in raw markdown.

### ISSUE THREAD

**Issue by kvaps** [RocketChat/Rocket.Chat#9616]
### Description:

Notification about new message isn't human readable if it containes quote inside.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar 
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: v8.9.3

### Steps to Reproduce:

1. Send quote to someone
2. Check notification

### Expected behavior:

It should look like:
```
My message test. My message text. My message test...
```

### Actual behavior:

It's looks like:
```
[ ](https://example.org/direct/some.guy?msg=NfXi9h55Wwj3k9Moa) 
```

**Comment by c0dzilla** [comment]
I'm taking up this issue

**Comment by c0dzilla** [comment]
Push notifications don't contain markdown support. Showing quoted text as it is in the notification instead of markdown could be a viable solution.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
