### ISSUE TITLE
[REST API] channels.setType returns a 400 response error when trying to change a Private Group to a Channel.

### ISSUE THREAD

**Issue by bpabel** [RocketChat/Rocket.Chat#9619]
### Description:

`channels.setType` returns a 400 response error when trying to change a Private Group to a Channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.56.0
* Operating System: Ubuntu x64
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.1

### Steps to Reproduce:

1. Create a channel
2. Make it private
3. Use the REST API endpoint `channels.setType` setting type to `c`

### Expected behavior:

A 200 response containing a json representation of the channel with the type switched to `c`

### Actual behavior:

A 400 response error - "Bad Request for url"

### Relevant logs:

No relevant log messages when this error occurs.

**Comment by xbolshe** [comment]
If a channel is private (see step #2 above), need to use `groups.setType` with `c` instead of `channels.setType`. 

`channels.setType` cannot find a group room (aka a private channel) and returns HTTP 400. A response with HTTP 400 shall have a payload like `{"success":false,"error":"The required \"roomId\" or \"roomName\" param provided does not match any channel [error-room-not-found]","errorType":"error-room-not-found"}`. May you check this?

**Comment by bpabel** [comment]
Thanks.  Yes, using `groups.setType` allows me to set the room type back to channel (`c`).  

It's a bit confusing since using `channel.setType` when setting the channel to private *returns* a channel dictionary, even though it's no longer possible to access that same channel through the `channels` api.  

I will close this ticket, as it appears the api is working as intended.  I don't know enough about the underlying design of channels and groups/private channels to know if it is really necessary to separate them in the api, especially when using the unique Room Id's to access them.  

It would probably be good to update the REST Api docs to indicate that there is only one possible valid argument to `channels.setType` or `groups.setType`, since it would never be possible to call `channels.setType('c')` and `groups.setType('p')`.  Either that, or merge the channel and group apis, considering they're already nearly identical.
