### ISSUE TITLE
Rest API - open access to all users?

### ISSUE THREAD

**Issue by imclem** [RocketChat/Rocket.Chat#963]
Hi Guys,

Just set-up LDAP with RocketChat, on client-side everything works properly. On api side, I can't login with my LDAP credentials. I just get an Unauthorized error.

I've created a non-ldap account on the server, then used it on /login and this works properly.

Looks like login with LDAP account is not supported on the rest api side.

I would also be grateful if you could add the capability to generate Username/api-token from the admin UI. This way we can generate accounts to use with the rest API without password and we can revoke them if the service using them gets corrupted. 

Thanks in advance, RocketChat rocks!

**Comment by imclem** [comment]
I (We) at least need "Service" accounts. I've just created a Bamboo notification plugin who sends notification to a public (at this time) channel.

As I said in previous post for my usage, creating service accounts with Username/api-token would be sufficient.

**Comment by imclem** [comment]
FYI: https://github.com/imclem/Bamboo-RocketChat

**Comment by engelgabriel** [comment]
hi @imclem is this issue still a problem with the latest version or Rocket.Chat?

Nice plugin for bamboo! I'll test on our projects that use Bamboo :)

**Comment by rodrigok** [comment]
@imclem Now you can use OAuth to access our APIs and the new LDAP implementation (at branch develop) sync the user's password from LDAP to our account system, so you can login using your username and password too.

**Comment by eduardoarantes** [comment]
@rodrigok, are you saying that the new API will automatically create the user if the LDAP configuration is set?
I've just tried this and it didn't work.
from the login page, everything goes well.
