### ISSUE TITLE
Where is Audio & Video call Button ?

### ISSUE THREAD

**Issue by RiusmaX** [RocketChat/Rocket.Chat#9632]
### Description:

I've installed a fresh instance of Rocket.Chat 0.61 on Ubuntu 16.04 with snapd and when i'm in a private chat with someone, I can't see the "Call Button" for start an audio or a video call anywhere (WebRTC is set).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu Server 16.04 (fresh install)
* Deployment Method(snap/docker/tar/etc): snap (i've tried docker too)
* Number of Running Instances: 1
* DB Replicaset Oplog: Activated
* Node Version: 8.8.1

### Steps to Reproduce:

1. Run a VM with Ubuntu 16.04
2. Run in a terminal "sudo snap install rocketchat-server"
3. Go to http://<SERVER-IP>:3000
4. Create an account
5. Ask a Friend or take a second device to create a second account
6. Try to launch a call

### Expected behavior:

The buttons "Call" is displayed in the user section.

### Actual behavior:

Impossible to find the button anywhere. I can only use the Jitsi call feature.

**Comment by rasos** [comment]
Check if WebRTC is activated https://yourdomain.net/admin/WebRTC

**Comment by ElieMyIdea** [comment]
+1 
Duplicated by itself 😋  ? 
Like said before, WebRTC is enable in admin Panel with default parameters set ;)

Please need some help 🙏

**Comment by afroDC** [comment]
We're also experiencing the same issue.

**Comment by LifeIsAParadox** [comment]
same.

**Comment by xenithorb** [comment]
This should be probably retitled:

"WebRTC Administration options left behind after feature removal"

**Comment by der-eismann** [comment]
I just noticed that I can start audio & video calls, but only in private rooms. In open channels and direct messages the option is missing.

**Comment by xenithorb** [comment]
@der-eismann That sounds more like the `meet.jit.si` integration?

Does the button say "Video Chat?", if so that's the jitsi integration. 

The symptom of this bug for me is that if I disable that functionality from the admin panel via `Administration -> Video Conference - Enabled: False` then the menu for any conversation whether private, direct, or public looks like so:

![image](https://user-images.githubusercontent.com/10273878/36724317-da57a4ee-1b80-11e8-9d36-7e1d05070737.png)

**Comment by der-eismann** [comment]
No, I have jitsi and video conferences disabled and enabled WebRTC everywhere. But the audio & video calls are still missing from direct messages.

**Comment by xenithorb** [comment]
Indeed, I found it too:

![screenshot](https://user-images.githubusercontent.com/10273878/36732927-1d345ab6-1b9d-11e8-8be9-d7024621bd77.png)

Man that's in a really unintuitive spot.

**Comment by xenithorb** [comment]
Also, It's true that User<->User rooms don't have this... And to make things work the icon is overloaded:

![image](https://user-images.githubusercontent.com/10273878/36733437-a511e2ae-1b9e-11e8-89e4-ca0d9c03904c.png)

**Comment by karlprieb** [comment]
Hey guys, thank you all your reports!

@arthurgiustina will work on a better way to display this options (icons + label, or just icons, idk) and I will investigate that to make it work again!

**Comment by arthurgiustina** [comment]
![user information](https://user-images.githubusercontent.com/30700871/37368573-6c3228a2-26e5-11e8-82c2-87569238502c.png)

@karlprieb check this idea =)

**Comment by xenithorb** [comment]
I really like that, including how the mute icon is clearer about its intentions. Well done.

**Comment by Phuzzy112** [comment]
Hi all,
I'm about 90% done with putting RC into prod here, but am getting pressured about this. Any ETA that I could pass along?

PS love that mockup

**Comment by versavius** [comment]
Also in the drop down menu next to a user in the attached screenshot we have the "Video Chat" button if this was changed to two buttons "Audio Call" and "Video Call" as well as arthurgiustina suggestion that would make it so much easier to make audio/video calls.


![image](https://user-images.githubusercontent.com/11394779/37906668-c3ef2ab2-30fa-11e8-9701-9229d2790946.png)

**Comment by graywolf336** [comment]
@karlprieb when you guys go to do this, please add these convert this pull request to the new style: https://github.com/RocketChat/Rocket.Chat/pull/3635

**Comment by avignat** [comment]
Please bring those buttons back. I'm also affected running Rocket 0.65.0 with WebRTC enable for MP, private and public groups.

**Comment by jrichard8** [comment]
Version 0.64.2

WebRTC activated and dont have button to launch voice call. Whats wrong ?

**Comment by agustinventura** [comment]
Hi guys, this was scheduled for 0.65, is there any new milestone planned for the release?

**Comment by tonylemeunier** [comment]
Hi team,

First great job with this app.
I installed 0.65.1 and buttons are still missing.

Best Regards,

**Comment by flantascience** [comment]
So am I to understand correctly...
that th enew approach to doing a 'group' video call in a channel is to use Jitsi?     Or is there also a regular WebRTC approach?

I feel like every public channel use to have an option to just enable an Audio call or a Video call and the little boxes with people's videos would show up.   Now, it seems we've got to use Jitsi?     I don't have a big problem with that.

I guess my main goal is to not necessarily do a group video chat BUT to be able to livestream my screen to a large group of people at once.   Is that possible using this feature?  To have more  of a one-way call, without everyone having to be on a video.  Just a one-to-many approach?

**Comment by xenithorb** [comment]
In my experience it was just easier to have people go to a `meet.jit.si` link (and it has gotten really good at screensharing on both chromium and firefox lately.) 

What I liked the WebRTC feature for was 1-1 calling. It worked well for quick chats

**Comment by reetp** [comment]
We only used video for 1 to 1 and miss this a lot.

Not keen on being forced to use external services (GDPR & all that jazz)

**Comment by agustinventura** [comment]
@xenithorb that's exactly our use case, we just want WebRTC calls for 1-1 calling. Besides we can't use jitsi for some weird network reasons :)

**Comment by HammyHavoc** [comment]
Going to have to agree with @reetp; Nextcloud is offering a completely self-hosted chat, voice and video platform that ties in with their file system. Seems like an odd move for RocketChat to not support WebRTC anymore and to favour Jitsi of all things.

**Comment by daradurvs** [comment]
I vote for the folowing features:
- **Audio calling** from the user's directed conversation (1 <-> 1)
- **Video calling** from the user's directed conversation (1 <-> 1)

**Comment by darnux** [comment]
Whats the current situation regarding this topic?
I am running the lastest release and have Rocket.Chat WebRTC enabled but I am not able to start a private video chat.

**Comment by ealbers** [comment]
I also would like to know when this will be implemented. We are stuck on a previous release until this feature is added back to the current set.

**Comment by MisterJD** [comment]
Im was so happy about that to find a really good self hosted alternative to slack or discord for my team. Its very sad that an audio call or video call feature is currently missing (Jitsi is not an option for us). 

Hope for any updates on this topic in the near future.

**Comment by reetp** [comment]
Are any of the devs actually looking at this?

Now on 0.69.1 and you still can't start a call via a Direct Message despite the option still being there in Admin/WebRTC.

That's more than 6 months after this was reported as an issue and you said you would be looking at it.

If you want to drop Web RTC directly in favour of Jitsi (a bad move IMHO for those with privacy concerns) then fine, just make the decision and get on with it.

But leaving this just lying around untouched and uncared for is not great PR.

**Comment by ealbers** [comment]
I agree with reetp

**Comment by ealbers** [comment]
I applied your fix and that worked! Thank you so much!

**Comment by real19** [comment]
When are you guys planning to add all these calling features to mobile?

**Comment by real19** [comment]
I am a mobile developer and I would like to add them too..

**Comment by danpospisil** [comment]
Any update? We need this too.

**Comment by Shaverdoff** [comment]
0/70/0 still only public and private room video&audio call in webrtc even in Admin panel "Enable for Direct Messages" set true. pleeease... return that features

**Comment by pwittke** [comment]
any news when PR https://github.com/RocketChat/Rocket.Chat/pull/11962 will be implemented ? This issue exists for 9 months and @vkislichenko added a fix on Sep 5th. For 3 Update Versions this issue is ignored. We are holding back updates in order to keep this feature for our users.  :(

**Comment by jeffreyvanbarneveld** [comment]
Is this gonna be solved?

**Comment by Shaverdoff** [comment]
Nope. Still no any progress

Отправлено с iPhone

6 дек. 2018 г., в 22:15, Jeffrey van Barneveld <notifications@github.com<mailto:notifications@github.com>> написал(а):


Is this gonna be solved?

**Comment by ochbob** [comment]
Any news ?

**Comment by tassoevan** [comment]
The whole bunch of WebRTC support relied over the deprecated `URL.createObjectURL()` API which was removed for Google Chrome 71. AFAIK some browser-specific bugs and changes in the front-end team contributed for the postponing too. I'm still checking the amount of rework required to get this feature back on track.

**Comment by Shaverdoff** [comment]
So not all users netsurfing on Gh, some of them use ff;) like me:) This is only opinion, no claims

--
Gerasim Shaverdov | Deputy CTO | Altarix
Mobile: +7 937 070 66 84<tel:+7%20937%20070%2066%2084> | Skype/email: gerasim@altarix.ru<mailto:gerasim@altarix.ru>
Lenina av.25, Samara, Russia, 443068

28 дек. 2018 г., в 17:13, Tasso Evangelista <notifications@github.com<mailto:notifications@github.com>> написал(а):


The whole bunch of WebRTC support relied over the deprecated URL.createObjectURL() API which was removed for Google Chrome 71. AFAIK some browser-specific bugs and changes in the front-end team contributed for the postponing too. I'm still checking the amount of rework required to get this feature back on track.

**Comment by pwittke** [comment]
Any News?

**Comment by Shaverdoff** [comment]
in last FF there are no call button on dm. only strange block. in desktop electron client to - no call button.

**Comment by mixrat** [comment]
Hmm, I think you are right @Shaverdoff. I have an old RC 54 installation and the button is still there (for Chrome and FF) but once the other party accepts the call, there is no conversation status indicator and the call does not connect.

**Comment by hortonelectric** [comment]
Not having mobile support for audio and video calls in Rocket.chat is blocking my organization from adopting this in our enterprise application. Can somebody speak to the challenges or something, anybody from the dev team? We are willing to offer dev support!

**Comment by Shaverdoff** [comment]
> 
> 
> Not having mobile support for audio and video calls in Rocket.chat is blocking my organization from adopting this in our enterprise application. Can somebody speak to the challenges or something, anybody from the dev team? We are willing to offer dev support!

in mobile (ios or andr-backet) webrtc/jitsi/bigbluebutton not implemented. webrtc works only in PG and CH but how i see only in directmode (maybe i am wrong). you must click on Member list icons and choise people. like that

![default](https://user-images.githubusercontent.com/43804710/51743593-92c48480-20b6-11e9-86f5-ed7762f9bf65.png)

**Comment by tassoevan** [comment]
@hortonelectric AFAIK, Jitsi integration is coming soon to the iOS and Android (https://github.com/RocketChat/Rocket.Chat.Android/issues/466) apps.

**Comment by rasos** [comment]
@hortonelectric Jitsi integration is already available in the fairchat app (which can connect to any RC server, see Android / iOS stores).

**Comment by Shaverdoff** [comment]
> 
> 
> @Shaverdoff 'Start Audio Call' doesn't work for me on RC 0.73.2. Does it work for you?

only in CH & PG. even enable on direct - no option.

**Comment by Shaverdoff** [comment]
> 
> 
> @hortonelectric Jitsi integration is already available in the fairchat app (which can connect to any RC server, see Android / iOS stores).

on mobile ios client no any video options like start video(jitsi/BB) or something else like WebRTC. 
on mobile android client webrtc option is appears but it grayout like disabled, even if options turn on on server side.

**Comment by Shaverdoff** [comment]
> 
> 
> @Shaverdoff Jitsi must be configured on your server, then you see in the fairchat app in any chat or channel in the lower bar a video icon, which launches the Jitsi Meet app seamlessly (or suggests to install it first).
> 
> ![19-02-02 10-15-36 0019](https://user-images.githubusercontent.com/485723/52162419-1ba17880-26d4-11e9-9f9d-ecd2796f0a15.png)

ofcouse it configured.. 074 tar
m-p : IOS 12.1.3 client 3.2.0 (223)
this photo from mobile
![img_5599](https://user-images.githubusercontent.com/43804710/52164391-17904d80-270a-11e9-8294-ca6274acea3c.jpg)
and this photo from desktop client.
![2019-02-02 16 44 55](https://user-images.githubusercontent.com/43804710/52164412-735ad680-270a-11e9-8b2b-5c37dcdacf14.png)
do not know how in currently android version was, but cuple month ago no point to video not to mention about photo...

**Comment by rasos** [comment]
The screenshot with the cat is from the **fairchat app** - it is an independent app development compatible with RocketChat servers, which has video calls integrated. 

Android: https://play.google.com/store/apps/details?id=com.osalliance.rocketchatMobile

iOS: https://itunes.apple.com/at/app/fairchat/id1301616129?mt=8

Source Code: https://git.fairkom.net/chat/fairchat/

**Comment by Shaverdoff** [comment]
> 
> 
> The screenshot with the cat is from the **fairchat app** - it is an independent app development compatible with RocketChat servers, which has video calls integrated.
> 
> Android: https://play.google.com/store/apps/details?id=com.osalliance.rocketchatMobile
> 
> iOS: https://itunes.apple.com/at/app/fairchat/id1301616129?mt=8
> 
> Source Code: https://git.fairkom.net/chat/fairchat/

after add server and click to it - app crash) cool!) i wait until ios team with Refael as Lead will procced with video

**Comment by pwittke** [comment]
any updates?

**Comment by ministry-of-code** [comment]
How can it be that a core feature is fundamentally broken and nobody cares?

**Comment by Shaverdoff** [comment]
now even webrtc enable on pv - video/audio button do not work))

**Comment by reetp** [comment]
> How can it be that a core feature is fundamentally broken and nobody cares?

It's not that they don't care, but the direction of travel is to remove this sort of functionality from the core and move it to Apps/External programs eg in this case Jitsi and in say the case of the internal bot to an external bot system.

It means it simplifies the core making it easier to maintain and manage.

Also remember to date Rocket is essentially Alpha which means things get chopped and changed.

**Comment by ministry-of-code** [comment]
@reetp thanks for the information. we're in the process of evaluating to use rocket chat for our company and this does not really help to say "it's great, lets go with it". I understand that it makes sense to remove this stuff from core and replace with external services - but even these integrations are broken. We integrated Jitsi and it does not work. When someone start a video conference, nobody in the channel can join because the link simply does not work (nothing happens when the linked is clicked). Also, the admin menu entry WebRTC should be remove when it does not work/is not integrated any more.

**Comment by discon-nected** [comment]
I would say it is foolish to stop maintaining a core feature unless a viable app can replaceme it. Otherwise, we let things deteriorate while we anticipate something that may never come to pass. And in the case of WebRTC, I think 1 to 1 calls should always be a core functionality. What's next? Do we need to find an app for messages? Should RocketChat be reduced to an app container?

**Comment by HammyHavoc** [comment]
@discon-nected, ridiculous, right? With this thought process in mind and a lack of basic communication capability, we've been forced to go elsewhere for our communication needs.

**Comment by discon-nected** [comment]
@HammyHavoc I guess the RC team became busy selling their paid platforms. I have noticed issues are left open for years now, and closed with "This is better suited for apps"

i.e. https://github.com/RocketChat/Rocket.Chat/issues/7150

**Comment by Alwandy** [comment]
As some has mentioned, we're also currently evaluating to use rocket.chat but what hinders us is this functionality! We also do not want to use external apps / third party services to enable this feature, we really would like to use it if it's part of the core as we're self-hosting again for confidential reasons.

**Comment by pwittke** [comment]
Cutting a core feature that made many peoply move to RocketChat would be a mistake.

For many companies the sole reason of using such a system is to have it on a standalone basis with no external services connected due to privacy/security/confidentiality reasons.

And if the feature is planned to be removed I agree there should not be an option for it and the website should be updated.

But I guess we have to wait for the Devs to answer and clarify at one point in time.

![image](https://user-images.githubusercontent.com/6334940/54105849-9a28be80-43d4-11e9-8a5b-5b23412227c3.png)


![image](https://user-images.githubusercontent.com/6334940/54105825-87ae8500-43d4-11e9-97ea-9d305826bd82.png)

**Comment by ggazzo** [comment]
@discon-nected  we really want to move to apps... but it doesn't mean we gonna to abandon the features, it's how the framework/code structure works, our apps are our responsibility as the core code is. But on the other hand, if you don like some app/feature you could remove/install/develop a different app.
> I have noticed issues are left open for years now and/or closed with "This is better suited for apps".
again its not true, your team its not so huge as you think. ok, its true we have tried to make some money, but our development team is 100% on nonpaid features. (some examples, federantion, threads and the new livechat).
> I guess the RC team became busy selling their paid platforms.

@pwittke no! we never had this in mind, we have a planned project to fix/improve videos/audio, and I/we want to start very soon.

> And if the feature is planned to be removed I agree there should not be an option for it and the website should be updated.

**Comment by discon-nected** [comment]
> we really want to move to apps... but it doesn't mean we gonna to abandon the features

Then why can't I make audio calls?

**Comment by MathiasGmeiner** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/9632#issuecomment-471613510
Thanks for the clarification!

**Comment by ggazzo** [comment]
> > we really want to move to apps... but it doesn't mean we gonna to abandon the features
> 
> Then why can't we make audio calls (for over a year now)?
> 
> And don't get me wrong, I have no problem using RC developed apps, but using 3rd party apps to achieve what should be core functionality while at the same time compromising security is a problem. (i.e., Jistsi)

there are no excuses fot that, actually, I just can say we had no time to make a proper fix... but believe me, I'm not happy with that, please await for the next weeks :x

**Comment by discon-nected** [comment]
That's great news. I will wait impatiently :D

**Comment by rasos** [comment]
@Shaverdoff you may try again the fairchat app, the 1.2.1 version has got fixed the server change bug. It seamlessly calls the Jitsi Meet app when you get an invitation to join a conference call.

**Comment by Shaverdoff** [comment]
> 
> 
> @Shaverdoff you may try again the fairchat app, the 1.2.1 version has got fixed the server change bug. It seamlessly calls the Jitsi Meet app when you get an invitation to join a conference call.

in 12/1/4 iOS that fairchat forclose after try to enter server url and press connect. so...

**Comment by ggazzo** [comment]
@discon-nected please check #13675

**Comment by discon-nected** [comment]
Sweet. Thank you!

**Comment by danger89** [comment]
> 
> 
> Indeed, I found it too:
> 
> ![screenshot](https://user-images.githubusercontent.com/10273878/36732927-1d345ab6-1b9d-11e8-8be9-d7024621bd77.png)
> 
> Man that's in a really unintuitive spot.

But that is only for a audio call one-on-one?

What about a Jitsi audio call only in either a channel or private group?
