### ISSUE TITLE
SAML PEM errors

### ISSUE THREAD

**Issue by sc10n** [RocketChat/Rocket.Chat#9634]
Description:

I receive the following error when trying to login via SAML. 

````
Exception in callback of async function: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line     at Sign.sign (crypto.js:331:26)     at SAML.signRequest (/app/bundle/programs/server/packages/steffo_meteor-accounts-saml.js:560:16)     at /app/bundle/programs/server/packages/steffo_meteor-accounts-saml.js:649:33     at DeflateRaw.onEnd (zlib.js:131:5)     at emitNone (events.js:111:20)     at DeflateRaw.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1056:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
````
At the same time I get the following error in NGINX 
````
[error] 61958#0: *310 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.111, server: rocketchat.example.com, request: "GET /_saml/authorize/RocketChat/id-xxxx HTTP/1.1", upstream: "http://127.0.0.1:3000/_saml/authorize/RocketChat/id-xxxx", host: "rocketchat.example.com", referrer: "https://rocketchat.example.com/home"
````
I can log in fine with the local account that was created at first sign in. So I know the reverse proxy is working correctly. 

All the certificates used have been verified to be good. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: RHEL 7
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances:  1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3 - x64

**Comment by aziz75012** [comment]
hello,
Did you ever resolve this? I am getting the same thing.

**Comment by pkolmann** [comment]
Same issue here. @sc10n do you still have a clue how you solved this issue?

**Comment by pkolmann** [comment]
Same issue here. @sc10n do you still have a clue how you solved this issue?

**Comment by pkolmann** [comment]
For others, if they end up here...

refer to https://github.com/RocketChat/Rocket.Chat/issues/6317#issuecomment-285696028 

(in the custom Certificate, no header or footer should be added. In the Public Cert and Private Key Contents, you NEED TO HAVE the `----- BEGIN -----` and `---- END -----` lines
