### ISSUE TITLE
Change own Password by REST API

### ISSUE THREAD

**Issue by xlbs-rm** [RocketChat/Rocket.Chat#9638]
### Description:

Cannot Change own Password by REST API without permission: "edit-other-user-password"

### Server Setup Information:

* all including 60.X
* Operating System: all
* Deployment Method: docker
* Number of Running Instances: 1 

### Steps to Reproduce:

REST Auth normal User
REST POST /api/v1/users.update  
BODY: {
"userId": "XXXXXXX", "data": {
	"password": "newpass"
  }
}
+ Auth Header

### Expected behavior:
Changed Password

### Actual behavior:
Unchanged Password (without permission edit-other-user-password)
Changed Password (with permission edit-other-user-password)

Due its an Security Issue to let all Users Change other Users Password, the Ressource is not usefull. 

@See: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/functions/saveUser.js currently line 154 v0.61.0

Permission Test should skip for all own user Updates
like: >>>>>>>>>>>>>>>>>>>>>>
if (userId == userData._id || userData.password && userData.password.trim() && RocketChat.authz.hasPermission(userId, 'edit-other-user-password') ) {
			Accounts.setPassword(userData._id, userData.password.trim());
		}
<<<<<<<<<<<<<<<<<<<<
Untested, due no own Build Process for the Server

Related to: https://github.com/RocketChat/Rocket.Chat/issues/6860

**Comment by graywolf336** [comment]
Have you tried to change your password via the web interface? Does that work when you don't have that permission?

**Comment by xlbs-rm** [comment]
Just tried the web interface. There it works without the permission. Using the REST API it don't work without Permission.
The Difference is The Web Interface uses a undocumented Realtime Socket API Method "saveUserProfile"
https://rocket.chat/docs/developer-guides/realtime-api/method-calls/
https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/saveUserProfile.js

["{\"msg\":\"method\",\"method\":\"saveUserProfile\",\"params\":[{\"typedPassword\":\"PASSWORDHASHEDHASHED\",\"newPassword\":\"NEWPWCLEARTEXT\"},{\"customfield\":\value\"}],\"id\":\"42\"}"]

For saving the new password, the Web Interface requests the current Password again and sends it crypted to the server. The new Password will be send uncrypted. 

It would be nice if all functions are well documented.

**Comment by robindijkhof** [comment]
https://rocket.chat/docs/developer-guides/rest-api/users/updateownbasicinfo/

Was added is 0.62.2
