### ISSUE TITLE
Question: Do initial passwords, set by an admin when creating a user, get invalidated after a certain time, if they are not used?

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#9641]
enterprise scenarios require the invalidation of initial set passwords after a specific time, if those passwords have not been used. Is there any mechanism in Rocket.Chat to invalidate initial passwords after a certain time?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
