### ISSUE TITLE
Non regex message search requires whole word to match

### ISSUE THREAD

**Issue by pshute** [RocketChat/Rocket.Chat#9647]
If I search for "comp", it won't match messages containing "computer". If I search for "/comp/" it will. 

Is this deliberate? I would have thought the most common kind of search would be non regex, and that partial word matching would be assumed by most people.

**Comment by Jannibal** [comment]
I agree. We use Rocket internally (and with guests). Most users are developers, so for them this isn't a problem. But we're struggling with managers and guests to use Rocket as it is, and these small things deters un-savvy users from this awesome tool.

**Comment by ispryt** [comment]
Please change default method to /text/i

**Comment by ggazzo** [comment]
hey, @pshute what did you see this config?
Administration > Messages
![image](https://user-images.githubusercontent.com/5263975/40570610-d7cf2c98-6062-11e8-99de-2bc96a2287b3.png)

**Comment by pshute** [comment]
@ggazzo no, I hadn't seen that. Ours is set to False. I'm not sure if setting it to True would be a good idea though. It would sometimes help people who don't realise it doesn't do whole word searches, but often they won't realise search are now case sensitive. That might cause just as much trouble.

**Comment by ggazzo** [comment]
@pshute I'm not sure if I understand your problem because we use the option `insensitivity` when regexp is enabled ![image](https://user-images.githubusercontent.com/5263975/40592103-8f36f2aa-61f1-11e8-8999-4c926e14ef54.png)

**Comment by pshute** [comment]
@ggazzo Thanks, I didn't try changing the default to regex. I didn't know it became case insensitive.

**Comment by ggazzo** [comment]
No problem :) I will close the issue... any problem pls open again (or open a new issue)
