### ISSUE TITLE
Uploads without file extensions are unaccessible (404 Not Found)

### ISSUE THREAD

**Issue by Flauschbaellchen** [RocketChat/Rocket.Chat#9650]
### Description:

When uploading/sharing a file without a file extension, the file is successfully uploaded, but results in a "404 Not found" error page.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.4

* File Upload: Enabled
* File max size: 524288000
* Storage: FileSystem
* Accepted media types: Empty/Blank
* Protect uploaded files: Yes

The files are successfully created on the server side.

### Steps to Reproduce:

1. Upload file with extension like *.txt
2. Download is possible
3. Upload file without extension
4. Download is not possible

### Expected behavior:

Download should be possible

### Actual behavior:

Download results in a 404 Not Found Error page

### Relevant logs:
None.

**Comment by maxdwit** [comment]
verified with ".gitconfig" and "gitconfig" textfiles - Downloadlink gets an HTTP Error 500
verified with ".gitconfig.txt" -> Downloadlink works
I think this is an issue.

**Comment by tuudik** [comment]
👍 

Same with version 0.63.2

**Comment by Flauschbaellchen** [comment]
Still an issue in 0.64.1.

**Comment by danpospisil** [comment]
Just experienced this as well. Please fix it.

**Comment by fabien4455** [comment]
same on 0.70.4

**Comment by fabien4455** [comment]
And same on 0.71.1 please fix it !!

**Comment by Flauschbaellchen** [comment]
Can someone at least tag this issue as a bugreport? Maybe @tassoevan?

**Comment by fabien4455** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/12668

Reported as bug

**Comment by reetp** [comment]
> #12668
> 
> Reported as bug

This IS a 'bug' so you did not need to open it again, no matter how frustrated you are.

Closing in favour of #12668

**Comment by reetp** [comment]
@rocket-cat close

**Comment by Flauschbaellchen** [comment]
@reetp, this issue was opened 10 month ago, the other issue just only 2 weeks. sorry for disturbing... :/
