### ISSUE TITLE
asking for email id after chat is end

### ISSUE THREAD

**Issue by lokeshbhandari** [RocketChat/Rocket.Chat#9654]
### Description:

I have enter my email id in live chat. After chat end it prompting for email id to send mail, I have already already give at registration. How can I use same. Is there setting in administration for same ? Or I need to do some coding. 
### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 14.04 (64 bit)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: 
* Node Version: 8.9.3

### Steps to Reproduce:

1. 
2. 
3. 

### Expected behavior:
It prompting second time email id after chat is closed and send to email.

### Actual behavior:
Should not prompting to enter email id

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
