### ISSUE TITLE
Inconsistency between clients and server after a loss of message history

### ISSUE THREAD

**Issue by jorge-sanz** [RocketChat/Rocket.Chat#9659]
### Description:

We have lost 3-days database history trying to load more users from LDAP (that's not the problem treated in this issue). After that, channels created on that period of time cannot be loaded ("Loading messages..." always on screen) or left (they appear again when reopening the app) on client apps, unless you logout.

### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3. 

### Expected behavior:

Automatic synchronization of available/active channels between client and server, hiding unavailable/deleted/lost channels.

### Actual behavior:

Channels, whose message history have been lost from database, continue appearing on client apps: Rocket.Chat+ for macOS and iOS at least.

**Comment by hugocostadev** [comment]
E 
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
