### ISSUE TITLE
[BUG] GitLab authentication is not working

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9660]
### Description:

GitLab authentication is not working. We're blocked on having GitLab authentication on iOS because of this, PR is ready: https://github.com/RocketChat/Rocket.Chat.iOS/pull/1218.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61
* Operating System: Linux

### Steps to Reproduce:

1. Setup a server with GitLab OAuth
2. Try to authenticate with any GitLab user

### Expected behavior:

It should authenticate the user.

### Actual behavior:

It fails with `URI included is not valid.`.

**Comment by meghalagrawal** [comment]
Is this issue still there? Can I work on it?

**Comment by madguy02** [comment]
@meghalagrawal yes, if you think you have faced this issue or any other issue on your own, just mention in the comments to let people know that you are working on it and shoot a PR. Ask the appropriate person to review it once done
Thanks

**Comment by madguy02** [comment]
I guess this is already a WIP

**Comment by rafaelks** [comment]
@madguy02 I believe this is not WIP yet, so if you want to submit a PR, please do that @meghalagrawal 👍
