### ISSUE TITLE
Out of office auto response

### ISSUE THREAD

**Issue by megamaced** [RocketChat/Rocket.Chat#9661]
### Description:
Is there any way to set an out of office autoresponse message in Rocketchat? If I am going on holiday and someone DMs me or mentions me in a room, then a bot would message back with my predetermined message?

Or even the possibility to write away messages in the user status?

I have seen hubot out-of-office https://github.com/typingincolor/hubot-out-of-office/blob/master/src/out-of-office.coffee but its not quite there. It does not auto respond and would not work in DMs

Slack seems to have this https://github.com/shaunburdick/slack-ooo-personal

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: SLES 12 SP3
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: yes 
* Node Version: 8.x

**Comment by doctorwho92** [comment]
I would love to see this. It's one of the big hurdles in getting people to use less email and use RocketChat more.

**Comment by gabrielloberg** [comment]
+1

**Comment by timkinnane** [comment]
Please see the [last comment on this related issue](https://github.com/RocketChat/Rocket.Chat/issues/8025#issuecomment-381470969).

Also maybe worth adding to the discussion on #10174

**Comment by RedOne-Guerad** [comment]
https://github.com/RedOne-Guerad/rc-auto-reply
