### ISSUE TITLE
SNAP: Allow changing of DB engine

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9664]
Wiredtiger can be a bit.. wild with some users load.  We should provide an option to change the db engine... and perhaps change the default for all new installations to mmapv1 instead.

**Comment by lucasromanomr** [comment]
Should not the label be a bug? since it offers the option to do a snap installation, but a snap installation causes the application to crash constantly. Soon this would be a bug in the application that is installed via snap.

Anyway, should not this be treated as a problem?

**Comment by geekgonecrazy** [comment]
for most installs wiredtiger works just fine.  I know of many in production that have been running since the snap has been released and updated between every version with no down time.

**Comment by sketch242** [comment]
This is an old ticket, but mmapv1 is now deprecated in MongoDB 4.0, slated for removal in 4.2.

https://docs.mongodb.com/manual/release-notes/4.0/#deprecate-mmapv1

I saw that mmapv1 is recommended here
https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/

Seems like the documentation should probably be updated not to recommend mmapv1 anymore?

**Comment by geekgonecrazy** [comment]
I’m going to go ahead and close this.   But with HA installs we do still recommend mmapv1.  For now at least.  It’s actually working much better then it did a few months ago.  So we may actually change that recommendation
