### ISSUE TITLE
Weird Error: Valid Curve Name

### ISSUE THREAD

**Issue by damongrey** [RocketChat/Rocket.Chat#9669]
### Description: 

Log keeps reporting this error. Website also acting a bit funny. The registration issue may not be linked.

### Server Setup Information:

* Version of Rocket.Chat Server: Latest
* Operating System: Ubuntu 14.4x
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 8.4x

### Steps to Reproduce:

1. Continuous log reporting of error (see below)
2. Register new user and it pauses on "please wait."

### Expected behavior:

I need registration to return to work after hitting submit.
I also need this log to stop reporting this error.

### Actual behavior:

Registration stays as "please wait"
Log keeps reporting the error

### Relevant logs:

Exception in callback of async function: TypeError: First argument should be a valid curve name     at Object.createSecureContext (_tls_common.js:115:15)     at Object.exports.connect (_tls_wrap.js:1048:48)     at SMTPConnection._upgradeConnection (/home/damon/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:655:28)     at SMTPConnection._actionSTARTTLS (/home/damon/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1099:14)     at SMTPConnection._processResponse (/home/damon/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)     at SMTPConnection._onData (/home/damon/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)     at Socket._socket.on.chunk (/home/damon/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)     at emitOne (events.js:115:13)     at Socket.emit (events.js:210:7)     at addChunk (_stream_readable.js:266:12)     at readableAddChunk (_stream_readable.js:253:11)     at Socket.Readable.push (_stream_readable.js:211:10)     at TCP.onread (net.js:585:20)

**Comment by TwizzyDizzy** [comment]
Hi @damongrey 

this is probably no Rocket.Chat error but rather an issue with your SMTP connection (From a glance at your error I would guess some TLS cipher negotiation error). So please: your SMTP settings and the logfile of your SMTP daemon.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as you didn't provide any further information. If you still think this is a Rocket.Chat error, please get back to me and provide additional information on why you think this is a bug. We'll then consider re-opening this issue.

Cheers
Thomas
