### ISSUE TITLE
Emoticons broken with a question mark at the end

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#967]
Testcase:
1. type ":D?"
2. expected is a rendered emoticon
3. there is no emoticon rendered unlike ":D" and ":D!"

**Comment by S4KH** [comment]
Hi guys, I am new, is there any local test users created beforehand?

**Comment by gmsecrieru** [comment]
Based on [this comment](https://github.com/Ranks/emojione/issues/137#issuecomment-147127026) it looks like this is an expected behavior and your PR will not be merged. 

Closing as this is not an issue with RocketChat itself.
