### ISSUE TITLE
Name of files in file upload list cuts down at bottom due to overflow.

### ISSUE THREAD

**Issue by sumedh123** [RocketChat/Rocket.Chat#9671]
### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Show the name of the file thoroughly. Currently it cuts at the bottom.

### Expected behavior:

Show the name of the file thoroughly.

### Actual behavior:

<img width="141" alt="screen shot 2018-02-10 at 2 49 31 pm" src="https://user-images.githubusercontent.com/17925669/36062210-54f68a18-0e8d-11e8-852b-8fb2145f47c9.png">

**Comment by sumedh123** [comment]
I would like to work on this one.

**Comment by TwizzyDizzy** [comment]
Maybe @karlprieb can have a look at this PR? :)

Also @sumedh123: please specify the Rocket.Chat version you're running in your initial post.

Cheers
Thomas

**Comment by jszaszvari** [comment]
@TwizzyDizzy already a PR for this https://github.com/RocketChat/Rocket.Chat/pull/9672
