### ISSUE TITLE
Idle Timeout doesn't have any units

### ISSUE THREAD

**Issue by sybrenstuvel** [RocketChat/Rocket.Chat#9674]
https://github.com/RocketChat/Rocket.Chat/blob/2c65f2b0342300298073d0b831fdff6870d7dc9d/client/startup/startup.js#L94

Here it's just a number, without any indication of units. Same for the user interface, where the placeholder mentions a default of 300000. My guess is that it's in milliseconds, but that's just a guess. If so, maybe it would be better to change the units in the UI to seconds or minutes? Having an idle timeout down to the millisecond precision has IMO little practical value.

**Comment by 0x0000007** [comment]
I can work on that! 

I think minutes would be the best time unit for that. Am I right?

**Comment by sybrenstuvel** [comment]
Minutes seems the most useful, yes. Thanks for looking into this so quickly!

**Comment by kaiiiiiiiii** [comment]
Fixed in PR #9824.
