### ISSUE TITLE
LDAP authentication not possible with underscore symbol in login

### ISSUE THREAD

**Issue by rockenren** [RocketChat/Rocket.Chat#9677]
### Description:

As it says in title, LDAP auth not possible if username/login contents an underscore symbol (_).
If I understood correctly, underscore symbol is prohibited in login form.

In our organization we use lastname_firstname template as AD username (sAMAccountName).

### Server Setup Information:

* Version of Rocket.Chat Server: snap "stable"
* Operating System: Ubuntu Server 16.04 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

### Steps to Reproduce:

1. Enable AD authentication
2. Set sAMAccountName (default option) as username
3. Try to log in with username that contain an underscore symbol (for ex.: Jonh_Doe)

### Expected behavior:

Successful LDAP authentication.

### Actual behavior:

"User not found or incorrect password" error.
Successful LDAP authentication with username without underscore symbol in login (for ex.: JonhDoe).

### Relevant logs:
Will be provided later. I'm not at work now.

**Comment by jszaszvari** [comment]
Hi @rockenren 

This should not be the case. All our users have '_' in their username and can authenticate successfully.

Can you post a screenshot of your LDAP config with the sensitive bits removed so I can take a look?

Thanks,
John

**Comment by jszaszvari** [comment]
@rockenren 

Here's my setup with '_' working in the username

![image](https://user-images.githubusercontent.com/872463/36101219-cb3f446e-105c-11e8-8fe5-da0f174f3b04.png)

**Comment by rockenren** [comment]
Well, I've reinstall RC server, set up like on screenshots... and it works. Dont understand what was it.
Sorry for false bugreport, this can be closed.

Thank you for your help.

**Comment by jszaszvari** [comment]
I'm glad to hear!  Thanks for updating this with the outcome !😁

@aaron.ogle - good to close this one off. Thanks

**Comment by jszaszvari** [comment]
@geeksgonecrazy - Should be good to close this one off
