### ISSUE TITLE
List Channels Broken

### ISSUE THREAD

**Issue by mineZcash** [RocketChat/Rocket.Chat#9678]
Before updating my server to 0.60.3 a new user could find a list of channels on the left sidebar with the "more" text.

**Now that this is gone, new users don't know the channels available or how to search for them.**

My chat has 25+ public channels, If you start typing in the search bar it only shows 5 in alphabetical order! A new user not familiar with Rocket chat thinks there are only 5 channels. 

Since alot of channels on my server start with #Zcash a new user never sees them and leaves thinking that the server is inactive.

This is why the use of all the other channels by new users has dropped by 90% since updating to this new format!

Please allow Admin the option to auto-list *all available public channels* on the left bar for new users, or bring back the "more channels" button.

**Comment by AmShaegar13** [comment]
Duplicate of #8571

**Comment by mineZcash** [comment]
Closing to post in #8571
