### ISSUE TITLE
video-chat: firefox : chrome

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#968]
Now Firefox and chrome under ubuntu 14.04 can't use the micro and the camera.

Under Android 5 + chrome, it's works fine.

**Comment by Sing-Li** [comment]
@maxlinux2000 it has  *A LOT* to do with your system hardware and not just the browser versions.

Please check with this link -  if your browser + hardware stack works here , it will work:

https://test.webrtc.org/

**Comment by maxlinux2000** [comment]
![xrocket2](https://cloud.githubusercontent.com/assets/5683921/10255230/4e91d722-6949-11e5-8066-312ef6ec698c.png)

ok, firefox works fine.

I just tried too:
https://www.webrtc-experiment.com/RTCMultiConnection/AppRTC-Look.html

from my desktop (ubuntu with firefox) and my phone (android 5 with chrome), ando works just fine

**Comment by maxlinux2000** [comment]
OK, I undestand the problem under firefox.
Pressin the Video_chat button, don't appear the message to share the mic & camera, so the video char can't be start.
In the Console I can reat this:

InvalidAccessError: RTCPeerConnection constructor passed invalid RTCConfiguration - missing username: turn:team%40rocket.chat@numb.viagenie.ca:3478 rocketchat_webrtc.js

**Comment by geekgonecrazy** [comment]
@maxlinux2000 did firefox ask you to share these?

**Comment by Sing-Li** [comment]
@maxlinux2000 the screenshot you showed indicate that browser+system is *not* compatible with webrtc in general.

**Comment by geekgonecrazy** [comment]
@Sing-Li ah.. weird that it'd have one resolution and make it fail.  But makes sense why it fails.

**Comment by Sing-Li** [comment]
Once the new stack lands in master and is working for most folks.  We'll party and tune/tweak. Yes it is likely possible that we can 'query' in such a way to support these edge cases. And also improve the UX when browsers are not compatible ( for example  - don't show the button)
