### ISSUE TITLE
Random string of characters when sending `\([]\)`

### ISSUE THREAD

**Issue by nusje2000** [RocketChat/Rocket.Chat#9683]
### Description:

This is not a very complicated issue, I just have a simple question. When I send \`\\([]\\)\` to anyone, on any channel. I get this weird string of characters (`=!=tzLPMZngtWTMZNuXb=!=`). Can someone explain this to me.

**Comment by localguru** [comment]
Hmmm ... seems to a markdown bug.

**Comment by c0dzilla** [comment]
I'm taking up this issue.

**Comment by nusje2000** [comment]
I think it has something to do with katex but I am not sure

**Comment by engelgabriel** [comment]
Testing the PR I had the following result:

![image](https://user-images.githubusercontent.com/1000217/36305546-2d73c22c-12fb-11e8-930e-5bd58ad54218.png)

But I don't think that latex should be parsed at all inside code formatted boxes or inline code, what do you guys think?

**Comment by nusje2000** [comment]
I agree

**Comment by ggazzo** [comment]
fixed ;)
