### ISSUE TITLE
[Feature] Add option to deactivate email in livechat

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9684]
Due to privacy concerns, some livechat managers do not like to store any structured user data like `email` in livechat. Hence, there should be an option to deactivate the email input field in the livechat registration form. 

**Acceptance criteria:**
- When registering in livechat, an user does not have to specify an email address.
- The livechat admin is able to activate / deactivate the input field.

**Comment by sampaiodiego** [comment]
while we don't have a better page to configure pre-chat form fields, I was thinking in just having a toggle to disable the fields we current have.. I was thinking something like this, separate the current "livechat appearance" screen into three major groups (with an accordion style component), what do you think?

![image](https://user-images.githubusercontent.com/8591547/39049016-f8b58e92-4475-11e8-993e-f07e141f5f66.png)

**Comment by snake-py** [comment]
How can I deactivate emails for registration completely?
