### ISSUE TITLE
rocketchat is logging debug information although setting says "0 - Errors Only"

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#9685]
Hi Devs.

I'm currently running Rocketchat 0.61.0 but the behaviour mentioned in the subject exists since a few versions I guess. Can I check the mongodb for that setting? Maybe it gets not in effect for some reason? Any other ideas?

thanks and cheers

**Comment by jszaszvari** [comment]
Hi @himbeere 

Have you tried restarting the server process after making this change? 

Something to try is 
1. Turn debug in the log config back on
2. Restart the server
3. Turn it off again
4. Restart the server

Thanks,
John

**Comment by himbeere** [comment]
Hi @jszaszvari 

Thanks for your answer. It seems Rocketchat did not do anything wrong. The messages I see in the log are actually real error messages. I see messages like:

```
Empty Room for Subscription { _id: '3L2htdZmDS5E7m8Kf',
  rid: 'fWsrSs3o3ngpSNjPPjaH85Cbgivx9azMSF',
  u: { _id: 'fWsrSs3o3ngpSNjPP', username: 'existing_user' },
  name: 'deleted_user',
  t: 'd',
  open: false,
  alert: false,
  unread: 0,
  userMentions: 0,
  groupMentions: 0,
```

Obviousely users having direct messages open with users which already has been deleted. As I can see there is an existing bug. https://github.com/RocketChat/Rocket.Chat/issues/7162
