### ISSUE TITLE
"Leave" button in info panel does not work

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9688]
### Description:

When pressing the leave button in the right info panel, an user gets an `400` error message. The user is not able to leave the room.

Leaving by using the channel context menu in the left channel list works.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0

### Steps to Reproduce:

1. Create new channel and invite some other users
2. Try to leave the channel by clicking on the (i) Icon in the top bar and the on the leave button in the right corner.
3. You will get the error message.

### Expected behavior:

User can leave the channel.

### Actual behavior:

User cannot leave the channel by using the leave button in the right column.

![leave-400](https://user-images.githubusercontent.com/3596824/36140852-09f48322-10a3-11e8-9800-e4a0274514f1.png)

Leaving by using the button in the left column works.

![leaving-left-column](https://user-images.githubusercontent.com/3596824/36141109-e3e97876-10a3-11e8-9928-1adb5db0a8ed.png)

**Comment by ThomasRoehl** [comment]
On serverside this is the error:
```
Exception while invoking method 'leaveRoom' Error: Match error: Expected string, got null
I20180212-16:53:25.803(1)?     at exports.check (packages/check.js:55:15)
I20180212-16:53:25.803(1)?     at DDPCommon.MethodInvocation.leaveRoom (/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:15033:3)
I20180212-16:53:25.803(1)?     at DDPCommon.MethodInvocation.methodsMap.(anonymous function) (/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2134:26)
I20180212-16:53:25.803(1)?     at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
I20180212-16:53:25.804(1)?     at maybeAuditArgumentChecks (/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1826:12)
I20180212-16:53:25.804(1)?     at DDP._CurrentMethodInvocation.withValue (/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:892:126)
I20180212-16:53:25.804(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180212-16:53:25.805(1)?     at DDPServer._CurrentWriteFence.withValue (/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:892:98)
I20180212-16:53:25.805(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
I20180212-16:53:25.805(1)?     at Promise (/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:892:46)
I20180212-16:53:25.805(1)?     at new Promise (<anonymous>:null:null)
I20180212-16:53:25.805(1)?     at Session.method (/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:865:23)
I20180212-16:53:25.806(1)?     at /Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:744:85
I20180212-16:53:25.806(1)?
I20180212-16:53:25.806(1)? Sanitized and reported to the client as: Match failed [400]
I20180212-16:53:25.807(1)? undefined undefined
```

**Comment by TwizzyDizzy** [comment]
Can confirm this, also here's the log of a JS error on the client side after confirming the leave-warning with "Yes, leave it":

[my.host.name-1518535356407.log](https://github.com/RocketChat/Rocket.Chat/files/1720426/my.host.name-1518535356407.log)

Cheers
Thomas

**Comment by mrsimpson** [comment]
I noticed that the custom room type's warning text is not respected anymore.

**Comment by mrsimpson** [comment]
I am about to fix both issues
