### ISSUE TITLE
The option "Default Roles for Authentication Services" when register new users via auth service has no effect

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#9689]
### Description:
The option "Default Roles for Authentication Services" when register new users via auth service has no effect

### Server Setup Information:

* Version of Rocket.Chat Server: `0.59.3` (as well `0.61`)
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: yes
* Node Version: `4.7.3` - x64 (as well `8.9.4` - x64)

### Steps to Reproduce:

1. Activate "Registration via authentication service"
2. Set the option "Default Roles for Authentication Services"
 (`Accounts_Registration_AuthenticationServices_Default_Roles`) to `guest`
3. Sign On/In a new user using a auth service like SAML

### Expected behavior:

The newly created user should have the role `guest`

### Actual behavior:

The newly created user has the role `user` instead of guest

### Note: If fixing this issue it should be prevented to create users of the role `admin`

**Comment by janrudolph** [comment]
Addition: We noticed the same effect with every other defined role. If you define `bot` or `admin` as default, the user gets the role `user`. Moreover, a list of roles does not have an effect neither. If you set the default to `user, bot`, the user gets the role `user`.

**Comment by lkraider** [comment]
The role is hardcoded in the source file:
https://github.com/RocketChat/Rocket.Chat/blob/63a57fb7e5fedea0615f4d2b8f30c434b4df79ae/app/meteor-accounts-saml/server/saml_server.js#L178

**Comment by pierre-lehnen-rc** [comment]
Fixed on #15277
