### ISSUE TITLE
sending a PM to self, bugs out the user interface

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#969]

**Comment by Sing-Li** [comment]
@ninja-  please explain in more details on how to reproduce this.

**Comment by ninja-** [comment]
@Sing-Li try sending a private message using the "+" button. then - enter your own username and click the finish button. the result is an empty buggy entry on the list of private messages.

**Comment by gmsecrieru** [comment]
@ninja- Could you please provide a screenshot of this error? I just followed provided steps and could not reproduce.

**Comment by geekgonecrazy** [comment]
@gmsecrieru if I start one with my self I just get a blank screen

**Comment by gmsecrieru** [comment]
@geekgonecrazy I think this might have been addressed on `master` already. Could only reproduce on Demo server but at this point we are running outdated code!

![screen shot 2015-10-05 at 19 58 41](https://cloud.githubusercontent.com/assets/190883/10296053/84185e4e-6b9b-11e5-8ce6-b3d0247a4b9a.png)

**Comment by marceloschmidt** [comment]
@gmsecrieru we deployed a new version, can you test again, please?
