### ISSUE TITLE
New Users via LDAP get role guest and should be user 

### ISSUE THREAD

**Issue by GaWr26** [RocketChat/Rocket.Chat#9690]
We have a working environment connected to LDAP. Now we get new employees which are added to the LDAP Database. Once this syncs, the new Employees get rocket.chat users which only have the role guest. This should be user in our case.

Is there a way to change what role newly added users via LDAP sync are assigned?

* Version of Rocket.Chat Server: 0.61.0

**Comment by TwizzyDizzy** [comment]
Hi @flashguy22 

> Is there a way to change what role newly added users via LDAP sync are assigned?

I don't think there is. Yet I cannot reproduce your issue. New users that login for the first time via (in my case) Active Directory are assigned the "user" role (I think you meant `role` when you said `group` as there is no concept of groups in user management).

Cheers
Thomas

**Comment by Hudell** [comment]
Rocket.Chat now has the ability to link roles to LDAP groups, with the default role being user.
