### ISSUE TITLE
UX improvement: "Disable Notifications"

### ISSUE THREAD

**Issue by sybrenstuvel** [RocketChat/Rocket.Chat#9692]
### Description:

Each channel has a "Disable Notifications" setting. Enabling this setting disables the notifications. Such a negative setting (disable to enable, enable to disable) is hard to use. I would suggest simply calling it "Enable Notifications" and having it enabled by default.

### Steps to Reproduce:

1. Visit a channel
2. Click on the "Notifications" tab in the right-hand bar.

**Comment by 0x0000007** [comment]
Have you seen the new Notifications Preferences Panel?

![screen shot 2018-02-13 at 22 44 00](https://user-images.githubusercontent.com/4711233/36175398-8dff2dd6-110f-11e8-974b-4ec4ce31f29d.png)

**Comment by sybrenstuvel** [comment]
I thought we had a reasonably up to date install, guess not ;-) Thanks for showing the new interface, it looks good!
