### ISSUE TITLE
Hello, I would like to collaborate with your project, serving as a translator to English, which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [RocketChat/Rocket.Chat#9693]
### Server Setup Information:

* Version of Rocket.Chat Server:
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by 0x0000007** [comment]
Hey! There’s a Lingohub project for translations :)

More informations:
https://github.com/RocketChat/Rocket.Chat/blob/develop/README.md#translations

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as I suspect @LuigiBaute to be a bot. If not I am sorry - please get back to me in that case.

Cheers
Thomas
