### ISSUE TITLE
New User DM Causes Invalid User

### ISSUE THREAD

**Issue by mineZcash** [RocketChat/Rocket.Chat#9695]
### Description:

New user joins the server and sends Admin a Direct Message, but user and message is nowhere to be found.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 2
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.4

### Steps to Reproduce:

I receive a notification through email that a message has been received from new user. This is a user I have never had a DM with before. 

Open the mobile Browser and DM can't be seen on left sidebar. User can be seen in channels and user list. 

Clicking on Username shows user information, email, registration, etc... Click on "Conversation" button shows [ Invalid User ! ] notification.

Go to Search bar and type in Username, user shows as online, click on link and [ No user with username ••••• was found! ] notification.

### Expected behavior:

Click on Conversation allows Conversation

### Actual behavior:

User not found

### Relevant logs:

Not sure if Relevant, only unusual log;

Exception while invoking method 'afterVerifyEmail' TypeError: Cannot read property 'emails' of undefined   at DDPCommon.MethodInvocation.afterVerifyEmail (/app/bundle/programs/server/app/app.js:7035:37)   at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at DDPCommon.MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2130:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1826:12)   at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:892:126)   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)   at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:892:98)   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)   at Promise (/app/bundle/programs/server/packages/ddp-server.js:892:46)   at new Promise (<anonymous>:null:null)   at Session.method (/app/bundle/programs/server/packages/ddp-server.js:865:23)   at /app/bundle/programs/server/packages/ddp-server.js:744:85

**Comment by ggazzo** [comment]
I dont think we have this problem anymore, any problem let us know ;)
