### ISSUE TITLE
Meteor bug?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#970]
I don't know if this is a bug, but I have a little script that update meteor and rocket.chat and finally run it for testing.

in the terminal I can see this message:
-------------------------------------------------------------------------------------
The following top-level dependencies were not updated to the very latest
version available:
 * dispatch:run-as-user 0.0.2 (1.1.1 is available)
 * raix:push 2.6.13-rc.1 (3.0.0 is available) 
                                              
Newer versions of the following indirect dependencies are available:
 * cosmos:browserify 0.5.1 (0.8.0 is available)
 * matb33:collection-hooks 0.7.15 (0.8.1 is available)
 * simple:highlight.js 1.0.9 (1.1.0 is available)
To update one or more of these packages, pass their names to `meteor update`.
[[[[[ ~/Rocket.Chat ]]]]]  
------------------------------------------------------------------------------------------

but I thought the command  "meteor update", updating all packages...

**Comment by ninja-** [comment]
no worries, it's just outdated dependencies

**Comment by Sing-Li** [comment]
`meteor update` will update all core pages, those that the Meteor platform itself is dependent on - and tested against.   Rocket.Chat may or may not want/need the latest version of a third-party package.
