### ISSUE TITLE
Never expiring sessions.

### ISSUE THREAD

**Issue by phalcon30964** [RocketChat/Rocket.Chat#9702]
Hello team,

I'd like to know if there's any way to have users always connected. 

I'm using rocket.chat and I have some computers that should always be logged in our rocket.chat. I'm using general accounts to always have them connected but sometimes some people logs out those computers and I have to go to these computers and log in again.

Is there anyway in the api to have a forever access-token? or a permission to have those accounts not having password to log in?

**Comment by TwizzyDizzy** [comment]
Hi @phalcon30964 

what's your use case here? Why do those accounts "need to be" logged in always. From a security perspective, I think tokens that are valid forever are **bad practice**.

Cheers
Thomas

**Comment by localguru** [comment]
The use case would be interesting. Why not just reconnect the user from time to time or keep it active like a hubot does?

**Comment by phalcon30964** [comment]
HI @TwizzyDizzy , I do agree with you but I don't know how else to handle this situation. @localguru  hello, I tried just to log them in from time to time, but as I need those nodes to be used for many people I have freezed them to avoid people making changes, so when I try to log in again I have to defreeze those computers and them freeze them. This is a very time-consuming procedure. The problem is that some users log out computers by error sometimes and when the computer restarts they restart login with the access token that was invalidated by log out. Is there any way I can reactivate some access token after it has been invalidated via api? @localguru . Is the anyway i can know the access token a user have so I can figure out that token and keep it active.  Obviously only having admin permissions so no body else can do this.

**Comment by sampaiodiego** [comment]
you can create tokens that never expires on "Personal Access Tokens" sections of your account.

Regular login tokens will expire as usual.

**Comment by mjeedx** [comment]
So there is no other wany way to work without relogin, using Electron?

**Comment by sampaiodiego** [comment]
> So there is no other way to work without relogin, using Electron?

no, electron sessions will expire as well
