### ISSUE TITLE
Markdown links to non http/https protocol

### ISSUE THREAD

**Issue by schirrmie** [RocketChat/Rocket.Chat#9708]
Hi,

the markdown link syntax only allow http / https protocol like:
`[like this](http://someurl)`
The markdown should allow any protocol like sip:// or whatever.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version:

**Comment by c0dzilla** [comment]
Is markdown support for non http/https support being considered? I'd be willing to take up this issue if it is.

**Comment by c0dzilla** [comment]
Supporting protocols like 'mailto:' seems like a valid feature.

**Comment by 0x0000007** [comment]
Would be nice to have it as a configurable option, because I don’t want to allow every protocol :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schirrmie** [comment]
Configurable would be great. We have a company own protocol like company:// and need support for it. So please do not only allow common protocols like sip, ftp or mailto. Please support any protocol!

**Comment by sumedh123** [comment]
Yeah seems good idea to support any protocol rather than excluding some.

**Comment by nemaniarjun** [comment]
I would like to take this up :)

**Comment by nemaniarjun** [comment]
Wait, looks like its already supported? https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-markdown/settings.js#L30

**Comment by schirrmie** [comment]
How to set these settings? I don't find such a settings.js file in our ubuntu snap installation?

**Comment by williamjamir** [comment]
Anything new about this problem? I am using the dev version released today (04/25/2019) and the problem persists with links that are FTP

**Comment by juracy** [comment]
It's possible to change which protocol markdown links should accept in Administration / Message / Markdown / Markdown Support Schemes for Link

**Comment by hugocostadev** [comment]
The new message-parser already supports other protocols
