### ISSUE TITLE
Changing email does not automatically resend verification email

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9710]
### Description:

Changing my email address should automatically send me a a verification email. As a result, I need to click the 'resend verification email' button. There is currently a bug that makes that resend button not work: for this see #7577 

<img width="172" alt="resend" src="https://user-images.githubusercontent.com/3596824/36205361-c54828cc-118e-11e8-8b13-55ba67546744.png">

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59

### Steps to Reproduce:

1. Change email address
2. Button occurs

### Expected behavior:

The email should be sent automatically without user interaction.

### Actual behavior:

The user has to click the resend button.

**Comment by abhishek71994** [comment]
So do you want the button removed and the email be sent based on some key event? As in if the user presses enter? or do you mean that as soon as the user presses save changes, then the email is sent?

**Comment by janrudolph** [comment]
@abhishek71994 Right. The best way would be from my point of view: 
If the user changes the email address and presses save, a verification link is sent to the new email address. Additionally a short message should appear which tells the user that a verification is required.

**Comment by abhishek71994** [comment]
@janrudolph I understand but what about the use case where the user enters a wrong email id? Can I connect with you on the Rocket.chat channel?

**Comment by janrudolph** [comment]
@abhishek71994 Sure, this is possible. However, the user is able to change the email right away to correct the wrong address? 
sure, I am on open.rocketchat

**Comment by Joe-mcgee** [comment]
Hi, I'm new to the project and this seems like something a junior such as myself could tackle, have you guys already dug into it? or would it be free for me to take up

**Comment by abhishek71994** [comment]
@Joe-mcgee I'm working on this issue, kindly find another issue there are a lot of similar ones.

**Comment by abhishek71994** [comment]
@janrudolph Kindy check the PR

**Comment by janrudolph** [comment]
@abhishek71994 How have you implemented it now?

I thought about this issue yesterday: 
I think we should send the verification mail right after the user has changed the mail address (as discussed above). However, we should also provide a manual button, in case the server has not sent the mail.

**Comment by abhishek71994** [comment]
@geekgonecrazy

**Comment by geekgonecrazy** [comment]
To re-iterate on the PR.  Basically this PR removed the button.  It needs to be there if the users email isn't verified.  The only thing that should change is it should trigger the send email verification when the email address changes

**Comment by isabellarussell** [comment]
I have edited the description and issue title.

**Comment by rodrigok** [comment]
Closed by [this commit](https://github.com/RocketChat/Rocket.Chat/commit/028f08aec483cab758587da08ac76e961e0c08b5)
