### ISSUE TITLE
Unable to edit/delete messages in iOS application

### ISSUE THREAD

**Issue by serge-petrov** [RocketChat/Rocket.Chat#9712]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: Ubuntu 16.04.3 amd64
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

### Steps to Reproduce:

1. Open any chat in iOS Rocket.Chat+ application
2. Tap and hold own message 
3. No "Edit" or "Delete" option available

### Expected behavior:

"Delete" and/or "Edit" button expected to be found like in browser version

### Actual behavior:
No "Edit" or "Delete" option available

![image](https://user-images.githubusercontent.com/36478692/36208924-63f38fcc-11ab-11e8-8f99-19e9976a1c5c.png)

![image](https://user-images.githubusercontent.com/36478692/36208802-0a01178c-11ab-11e8-88bd-78771995d0f6.png)

**Comment by 0x0000007** [comment]
1. Wrong repository mate :) ([Rocket.Chat.iOS](https://github.com/RocketChat/Rocket.Chat.iOS))
2. There's already an open PR for this issue ([PR #1048](https://github.com/RocketChat/Rocket.Chat.iOS/pull/1048)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

As @0x0000007 said ;)

Cheers
Thomas
