### ISSUE TITLE
Cannot run, unable to resolve some modules. Windows 10 

### ISSUE THREAD

**Issue by ezioauditore0101** [RocketChat/Rocket.Chat#9713]
### Description:

PS E:\work\rocketchat\Rocket.Chat> meteor
[[[[[ ~\E\work\rocketchat\Rocket.Chat ]]]]]

=> Started proxy.
=> Meteor 1.6.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.

Unable to resolve some modules:

  "underscore" in /E/work/rocketchat/Rocket.Chat/client/lib/handleError.js (web.browser)
  "moment" in /E/work/rocketchat/Rocket.Chat/client/methods/deleteMessage.js (web.browser)
  "underscore.string" in /E/work/rocketchat/Rocket.Chat/client/lib/handleError.js (web.browser)
  "toastr" in /E/work/rocketchat/Rocket.Chat/client/lib/handleError.js (web.browser)
  "highlight.js" in /E/work/rocketchat/Rocket.Chat/client/startup/startup.js (web.browser)
  "toastr/build/toastr.min.css" in /E/work/rocketchat/Rocket.Chat/client/lib/toastr.js (web.browser)
  "highlight.js/styles/github.css" in /E/work/rocketchat/Rocket.Chat/client/startup/startup.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save underscore moment underscore.string toastr highlight.js

Unable to resolve some modules:

  "babel-runtime/helpers/extends" in /E/work/rocketchat/Rocket.Chat/server/publications/messages.js (os.windows.x86_64)
  "underscore.string" in /E/work/rocketchat/Rocket.Chat/server/lib/accounts.js (os.windows.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save babel-runtime underscore.string

=> Errors prevented startup:

   While minifying app stylesheet:
   packages/modules-runtime.js:231:12: Cannot find module 'postcss-import'
   at makeMissingError (packages/modules-runtime.js:231:12)
   at require (packages/modules-runtime.js:241:19)
   at Object.keys.forEach.pluginName (packages/minifier-postcss/plugin/minify-css.js:20:26)
   at Array.forEach (<anonymous>)
   at getPostCSSPlugins (packages/minifier-postcss/plugin/minify-css.js:19:38)
   at css.map.file (packages/minifier-postcss/plugin/minify-css.js:64:30)
   at Array.map (<anonymous>)
   at mergeCss (packages/minifier-postcss/plugin/minify-css.js:55:22)
   at CssToolsMinifier.processFilesForBundle (packages/minifier-postcss/plugin/minify-css.js:179:18)

=> Your application has errors. Waiting for file change.

### Server Setup Information:
I tried both 'meteor npm install' ; both of them did not work. 

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Windows 10
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version:  v8.9.4

### Expected behavior:

Running rocket.chat on localhost:3000

**Comment by ezioauditore0101** [comment]
Error 1

meteor npm install --save underscore moment underscore.string toastr highlight.js

> fibers@1.0.15 install E:\work\rocketchat\Rocket.Chat\node_modules\fibers
> node build.js || nodejs build.js


E:\work\rocketchat\Rocket.Chat\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Users\Binary\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
E:\work\rocketchat\Rocket.Chat\node_modules\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was
 not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Binary\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Binary\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\Binary\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd E:\work\rocketchat\Rocket.Chat\node_modules\fibers
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Binary\AppData\Roaming\npm-cache\_logs\2018-02-14T15_06_15_926Z-debug.log

**Comment by ezioauditore0101** [comment]
meteor npm install --save babel-runtime underscore.string

> fibers@1.0.15 install E:\work\rocketchat\Rocket.Chat\node_modules\fibers
> node build.js || nodejs build.js


E:\work\rocketchat\Rocket.Chat\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Users\Binary\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
E:\work\rocketchat\Rocket.Chat\node_modules\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was
 not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Binary\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Binary\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\Binary\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0_1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd E:\work\rocketchat\Rocket.Chat\node_modules\fibers
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN chai-as-promised@6.0.0 requires a peer of chai@>= 2.1.2 < 4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Binary\AppData\Roaming\npm-cache\_logs\2018-02-14T15_09_01_946Z-debug.log

**Comment by TwizzyDizzy** [comment]
Hi @ezioauditore0101 

First off: there is not one "latest" version of Rocket.Chat - nodejs always supports multiple versions concurrently. So please provide the output of `/path/to/node/binary/you/run/rocketchat/with/node -v`.

Cheers
Thomas

**Comment by ezioauditore0101** [comment]
@TwizzyDizzy : The node version installed is v8.9.4

**Comment by ezioauditore0101** [comment]
@TwizzyDizzy : The node version installed is v8.9.4

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @ezioauditore0101 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* help with build errors is best given over at: https://forums.rocket.chat/c/community-support (I'm sorry, I should have closed this issue right from the start because of this)

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
