### ISSUE TITLE
Verified property of user is always set to false if not supplied

### ISSUE THREAD

**Issue by MarcosSpessatto** [RocketChat/Rocket.Chat#9718]
`verified` property in `user.emails`, is always set to false, if not supplied. Related in [this](https://github.com/RocketChat/Rocket.Chat.iOS/issues/962#issuecomment-349052238) issue.

**Comment by dennispost** [comment]
@MarcosSpessatto thanks for addressing this issue but my problem was a different one.

In my opinion the server should trigger any verification process (e.g. same as initial registration of email) to verificate the new email address. Currently I can change my email address to a different one without any verification.
