### ISSUE TITLE
Please add the emoticons panel, like whatsapp or phpbb

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#972]
![xrocket](https://cloud.githubusercontent.com/assets/5683921/10254860/b5b54f9a-6946-11e5-9442-d3abfa3739de.png)

Pressing a button appears all the emoticons, so the user don't need to learn the codes :) :/ :| :( .....

**Comment by geekgonecrazy** [comment]
Duplicated of #480

Please refer there.
