### ISSUE TITLE
Horizontal scroll in some pages

### ISSUE THREAD

**Issue by c0dzilla** [RocketChat/Rocket.Chat#9722]
### Description:

Horizontal scroll is visible on home page, administration and my account pages. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 8.9.3

### Steps to Reproduce:

1. Open home page or administration/myaccount pages from left pane. Horizontal scroll is visible.

### Expected behavior:

Horizontal scroll should be hidden.

### Actual behavior:

Horizontal scroll is enabled.
![scroll](https://user-images.githubusercontent.com/23701803/36251187-42a096b0-1266-11e8-91d9-16d79051a3ed.png)

**Comment by c0dzilla** [comment]
I'll take up this issue.

**Comment by sampaiodiego** [comment]
fixed by #10300
