### ISSUE TITLE
Receive notifications only on @personal pings (not @all)

### ISSUE THREAD

**Issue by jeamland** [RocketChat/Rocket.Chat#9736]
I'd very much like to get a push notification when someone @-mentions me personally but not on @all and the like. Being able to tune notifications per-channel would be even more awesome.

**Comment by jszaszvari** [comment]
@rocket-cat label add "type: new feature"

**Comment by JSzaszvari** [comment]
You can already change them per-channel 

![image](https://user-images.githubusercontent.com/872463/36344771-516d3964-1473-11e8-888f-4e5c5132f04d.png)

![image](https://user-images.githubusercontent.com/872463/36344774-5d31e182-1473-11e8-9a78-7e4d53d16dd7.png)

**Comment by kaiiiiiiiii** [comment]
PR #10502 allows muting of @all and @here mentions on a per channel basis.

**Comment by Sing-Li** [comment]
close this. Please let us know if the PR above does not satisfy your use-case.
