### ISSUE TITLE
[Bug] Channel name differs between channel headline and info panel

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9738]
### Description:

The channel name in the right info panel is not correct. It shows the "technical" name instead of the correct display name. Please find an example in the attached screenshot:

<img width="503" alt="names-differ" src="https://user-images.githubusercontent.com/3596824/36296907-f9512116-12ef-11e8-8732-c1f7d4dd8a20.png">
 
### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Create new channel with some special characters
2. Compare channel name in headline and info panel

### Expected behavior:

Same names.

### Actual behavior:

Different names.

**Comment by TwizzyDizzy** [comment]
I'm not quite sure whether this is to be treated as a bug, but I can at least confirm it on 0.61.1.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
With this assertion, I totally agree ;)

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
I came across another issue where this is relevant, as the wrong channel name is displayed (the normalized one, not the one containing e.g. special characters). Gonna link to it in a second.

What I want to add. In the sidebar the wrong channel name seems to be used, too (probably the same variable as the one used in room info as shown in the screenshot above).

Cheers
Thomas

**Comment by exhuma** [comment]
I can confirm that the side-bar shows the wrong name as well. The only place I can see the "real" display-name is when opening the channel itself:

![image](https://user-images.githubusercontent.com/65717/39756162-c52100dc-52c8-11e8-9063-2aaba79e673e.png)

This RC instance is used in a multi-lingual environment with a lot of German and French speakers. Special characters can sometimes change the meaning of the word and is kinda important. Not to mention that it does not look very professional when you have orthographic errors in your application.

I think that at *least* the side-bar should show the proper display-name as that is the primary way how end-users select channels.

**Comment by janrudolph** [comment]
in 1.0.0 fixed
