### ISSUE TITLE
[BUG] iOS App applies "UI_Allow_room_names_with_special_chars" but does not tell you

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9740]
*moved on request by @rafaelks from* https://github.com/RocketChat/Rocket.Chat.iOS/issues/1267

- Your Rocket.Chat app version: 1.8.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: iPhone 5S

**You cannot create channels with special chars**
Even if you configured `UI_Allow_room_names_with_special_chars = true`, you cannot create channels with special chars in the app. You always get an error message. The app should apply the same rules as web application.

In fact the app does not ignore the property. Moreover it displays, that you are not allowed to create a channel with special chars but in the background the app creates the channels.

**Example**
I wanted to create the channel `my iPhone test`. The app told me I am not allowed to do so. I changed the channel name to `my-iPhone-test` (failed again), then to `my-iphone-test` (failed again) and finally to `myiphonetest` (success). But on the server all channels were created.

![rocket_chat_](https://user-images.githubusercontent.com/3596824/36262604-3e14d14a-1268-11e8-9f71-26cce1879cff.png)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
