### ISSUE TITLE
Changing login expiration from day to minute

### ISSUE THREAD

**Issue by icanates** [RocketChat/Rocket.Chat#9741]
### Description:

I can't change day into minute for minimum value of login expiration. Only I can find livechat.js for loginExpiration. But I found then that file is produced by Meteor while running. 

How to change it?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60-developer
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version:8.9.3 - x64

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
