### ISSUE TITLE
can't scroll to most recent messages after clicking "JUMP TO FIRST UNREAD"

### ISSUE THREAD

**Issue by aspiers** [RocketChat/Rocket.Chat#9743]
### Description:

After clicking "JUMP TO FIRST UNREAD", I can't scroll down to the most recent mesages.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: SUSE Linux Enterprise Server 12 
* Deployment Method: Docker (official)
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9.4 (comes with the image)

### Steps to Reproduce:

1. Go to a channel with a lot of messages you haven't read yet
2. Click "JUMP TO FIRST UNREAD"
3. Keep scrolling down as far as you can (e.g. with mouse wheel). Notice you can't scroll all the way to the most recent message - why not?

### Expected behavior:

You should be able to scroll all the way to the most recent message.

### Actual behavior:

Scrolling gets stuck at some old message.

### Relevant logs:

Will happily supply if you can't easily reproduce yourself.

**Comment by TwizzyDizzy** [comment]
Hi @aspiers 

please try to reproduce this in 0.61.1 (which is the latest version). There have been some changes to the whole "unread"-topic.

Cheers
Thomas

**Comment by aspiers** [comment]
@TwizzyDizzy Thanks a lot, will do!

**Comment by aspiers** [comment]
Report updated with missing info. Apparently we can try the upgrade this coming Thursday.

**Comment by rsimai** [comment]
Same comment as in #9744: we plan to do so. BTW, it seems this is browser dependent. I don't see this behavior with Chromium 64.0.3282.167 (openSUSE Build). What is yours?

**Comment by aspiers** [comment]
I'm on Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by aspiers** [comment]
We upgraded and I still see this problem.

**Comment by rsimai** [comment]
I tried this with Chrome 64.0.3282.186 (current build from Google) on a few channels but couldn't duplicate, same as with Chromium 64.0.3282.167 (current build from SUSE). For me the "Jump to recent messages" link instantly disappears when I click it.

**Comment by karlprieb** [comment]
Hey guys, we are tracking these performance issues and will make some improvements to fix that in the next releases.

**Comment by aspiers** [comment]
FWIW I still see this with our instance which @rsimai upgraded to 0.63.3.

**Comment by MartinSchoeler** [comment]
I've tested this on version 2.3.0-develop and could not reproduce this issue, I believe that this was fixed since we changed a lot of code regarding loading older/newer messages. If you experience this issue again, please open a new issue with updated details. Thanks!
