### ISSUE TITLE
"Jump to recent messages" link doesn't go away when clicked

### ISSUE THREAD

**Issue by aspiers** [RocketChat/Rocket.Chat#9744]
### Description:

The "Jump to recent messages" link doesn't go away after you click it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.4
* Operating System: SUSE Linux Enterprise Server 12
* Deployment Method: Docker (official)
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9.4 (comes with the image)

### Steps to Reproduce:

1. Go to a channel with a lot of messages you haven't read yet
2. Click "JUMP TO FIRST UNREAD"
3. Click "Jump to recent messages".

### Expected behavior:

"Jump to recent messages" should no longer be visible.

### Actual behavior:

The only way to get rid of the "Jump to recent messages" link is to reload the page.

### Relevant logs:

Will happily supply if you can't easily reproduce yourself.

**Comment by TwizzyDizzy** [comment]
Hi @aspiers 

please try to reproduce this in 0.61.1 (which is the latest version). There have been some changes to the whole "unread"-topic.

Cheers
Thomas

**Comment by aspiers** [comment]
Report updated with missing info. Apparently we can try the upgrade this coming Thursday.

**Comment by rsimai** [comment]
Yes, we plan to do so. BTW, it seems (same as in #9743) this is browser dependent. I don't see this behavior with Chromium 64.0.3282.167 (openSUSE Build). What is yours?

**Comment by aspiers** [comment]
I'm on Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by aspiers** [comment]
We upgraded and this problem seems to have been fixed.

**Comment by TwizzyDizzy** [comment]
Splendid, that's good to hear. Thanks for going the extra mile!

Cheers
Thomas
