### ISSUE TITLE
Nextcloud Client Side Support - minimal skeleton

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#9745]
Within Rocket.Chat, without starting additional apps, enable a user of Nextcloud to select files from his Nextcloud server/account  and upload (or reference) them  within  Rocket.Chat channels.

Need to build a minimal skeleton that eliminates the technical hurdles, and allow additional contributors to extend it into a full feature.

*From Frank (CEO NextCloud):*  
Information about the Nextcloud APIs that can be used:

Login Flow to get the app to password for authentication:
https://docs.nextcloud.com/server/13/developer_manual/client_apis/LoginFlow/index.html

WebDav. This is mostly standard WebDAV to browse the files:
https://docs.nextcloud.com/server/13/developer_manual/client_apis/WebDAV/index.html

Sharing. This is the API to get a sharing link for any file
https://docs.nextcloud.com/server/13/developer_manual/core/ocs-share-api.html

Federated Sharing. This is our current Federation API but work in progress.
https://lukasreschke.github.io/OpenCloudMeshSpecification/#federated-sharing

**Comment by caesarcxiv** [comment]
+1

**Comment by GoetheG** [comment]
@Sing-Li, this is a very good Idea. There should be more interaction with Nextcloud in general. Just take a look at Nextcloud Talk. Why not combining that? Is just a thought.

**Comment by Sing-Li** [comment]
Nextcloud integration has been handled in GSoC projects - successively - in 2018 and soon 2019.  We are, and will continue to,  work in conjunction with Nextcloud team.   Closing this issue.
