### ISSUE TITLE
[BUG] Code in markdown links renders strange link (works on mobile)

### ISSUE THREAD

**Issue by itsthejoker** [RocketChat/Rocket.Chat#9758]
### Description:

When building a markdown link that includes a code block in it (`like this`) it will not render correctly on desktop or in web view.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: All
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.3

### Steps to Reproduce:

1. Create a message that is a valid markdown link with a backtick code block inside: \[This is a \`test!`](https://google.com)
2. Send it to a channel

### Expected behavior:

I expect to see "This is a `test!`" as a valid clickable link. EDIT: also works on github: [This is a `test!`](https://google.com)

### Actual behavior:

![code in markdown link](https://user-images.githubusercontent.com/5179553/36345214-9a3867ec-13f4-11e8-81a7-f38cbb5d2241.PNG)

### Other

This maneuver does work on mobile using the latest Android: RN app:

https://photos.app.goo.gl/t22GH4bgUMbKp4AE3

**Comment by karlprieb** [comment]
Closed by #9884
