### ISSUE TITLE
[Bug] Live chat notifications not working for agents causing countless livechats to go unanswered

### ISSUE THREAD

**Issue by KevSta91** [RocketChat/Rocket.Chat#9760]
### Description:

Our agents are not getting notified when there is a new live chat. No sound plays which is resting in livechats not being answered. 

I've got management threatening to rip out our whole rocket.chat deployment because of this one issue. 

Over the past while we've had over 200 livechats fo unanswered because our agents get no notification that there is a new live chat that has entered the queue

I've looked at the code and can't figure out where the notification code would go so that this happens. 

This issue makes the livechat unusable in a professional environment as there's no way to know when a customer has sent a message or there is a chat waiting. 

The customers get a notification when a agent sends them a message but not the other way around. 

Hoping someone can point me in the right direction as our executive team says I have 5 days to fix this or they are moving the business to Microsoft Teams 😭😢

### Server Setup Information:

* Version of Rocket.Chat Server: 61.1
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 4 
* DB Replicaset Oplog: yes

### Steps to Reproduce:

1. Initiate a live chat using the default livechats widget 
2. Send a message 

### Expected behavior:

The livechat agents get a audible notification when there is a new or unanswered chat in the queue

### Actual behavior:

There is no sound or notification.

**Comment by JSzaszvari** [comment]
@KevSta91 I've been trying to figure this one out myself for a little while but unfortunately have not made any progress. 

In a similar position to you where I've got management going postal at me about this. 

I'll let you know if I find anything

**Comment by renatobecker** [comment]
We started working on that issue and I guess we will fix it by the end of today.

**Comment by MIKNOTAURO** [comment]
We've been waiting for this fix for a while... LiveChat is a killer feature for us... thanks guys!
and btw... nowdays, everybody use a circle as a chat button also, I think it fits better for mobile devices. 
Have you considered a UI refactor ?
Thanks in advance ;)

**Comment by renatobecker** [comment]
@MIKNOTAURO We are planning the Livechat roadmap and the redesign is one of the next features.
