### ISSUE TITLE
[bug] custom emoji's

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#9761]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: ubunutu
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

**Comment by JSzaszvari** [comment]
Hi @wargamesqcf 

Are you using Filesystem or GridFS for the Custom Emoji Filesystem? 

I've seen this before when using FIleSystem and either the folder for custom emojis does not exist or the server does not have permissions to write to it. 

If you turn on Debug logging and try to upload a custom emoji, does anything show up in the debug logs?

Thanks

**Comment by wargamesqcf** [comment]
I have other static images as custom emojis and they work great, i am just trying to use an animated gif as an emoji, and that is where i am running into an isssue.

**Comment by wargamesqcf** [comment]
well I figured out the problem, it was the naming of the gif. It was named perfect.001.gif and rocket had no idea how to deal with that. The issue I now face is instead of showing the entire image it only shows a croped verison of it.

https://i.imgur.com/Zv0ufxD.gif

**Comment by itsthejoker** [comment]
Why would you expect a rectangular emote to work? AFAIK no chat service handles anything but square ones.

**Comment by wargamesqcf** [comment]
there are ones that do handle non square ones. Discord does non square ones, but they do have an overall size limit so it resizes the emoji to fit into those dimensions or yells at you for being out of spec. Rocket is the only chat service to CHOP an emoji to fit it seems.
