### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#9769]
Data Subject Rights

Breach Notification

Under the GDPR, breach notification will become mandatory in all member states where a data breach is likely to “result in a risk for the rights and freedoms of individuals”. This must be done within 72 hours of first having become aware of the breach. Data processors will also be required to notify their customers, the controllers, “without undue delay” after first becoming aware of a data breach. 

[Right to Access](https://github.com/RocketChat/Rocket.Chat/issues/9767)
Part of the expanded rights of data subjects outlined by the GDPR is the right for data subjects to obtain from the data controller confirmation as to whether or not personal data concerning them is being processed, where and for what purpose. Further, the controller shall provide a copy of the personal data, free of charge, in an electronic fromat. This change is a dramatic shift to data transparency and empowerment of data subjects.

[Right to be Forgotten](https://github.com/RocketChat/Rocket.Chat/issues/9766)
Also known as Data Erasure, the right to be forgotten entitles the data subject to have the data controller erase his/her personal data, cease further dissemination of the data, and potentially have third parties halt processing of the data. The conditions for erasure, as outlined in article 17, include the data no longer being relevant to original purposes for processing, or a data subjects withdrawing consent. It should also be noted that this right requires controllers to compare the subjects' rights to "the public interest in the availability of the data" when considering such requests.

[Data Portability](https://github.com/RocketChat/Rocket.Chat/issues/9768)
GDPR introduces data portability - the right for a data subject to receive the personal data concerning them, which they have previously provided in a 'commonly use and machine readable format' and have the right to transmit that data to another controller. 

----

- [x] [Right to Access](https://github.com/RocketChat/Rocket.Chat/issues/9767)
- [x] [Right to be Forgotten](https://github.com/RocketChat/Rocket.Chat/issues/9766)
- [x] [Data Portability](https://github.com/RocketChat/Rocket.Chat/issues/9768)

**Comment by Wouter0100** [comment]
Maybe also looking into data retention for messages, for example? This would help implement the GDPR, see , for example, [here](https://ico.org.uk/for-organisations/guide-to-data-protection/principle-5-retention/).

We should store data as less as possible. Messages is of course a complicated matter I think, but keeping it infinity isn't worth the risk. So for example the ability to set a global "message retention policy" would be useful, so we are able to automatically delete messages after a year.

**Comment by mootari** [comment]
@Wouter0100 I disagree. One of the purposes of Rocket.Chat is to provide a searchable archive of past conversations. It can't fulfill that task when all messages are deleted indiscriminately after a fixed amount of time.

I could however see the usefulness of a per-channel setting so that channel owners can decide based on the purpose of the channel which retention time span might be useful.

**Comment by Wouter0100** [comment]
@mootari I do agree and personally I would prefer to store it too - but as the same with e-mail, e-mails with customers should also be deleted after a period of time in some circumstances. 

Per-channel with a server-wide default would in that case be an option, I suppose.

**Comment by rasos** [comment]
We have discussed the retention policy with users in EU and they would prefer a deletion peroid setting on three levels:

- global setting
- per channel setting
- per user setting

So a user could decided not to keep his/her messages as the provider or the channel admin set as default.

**Comment by rasos** [comment]
Another GDPR issue is showing minimum personal data in the room and directory search. It is configurable site-wide, which fields are taken for the search in admin/Accounts, but not, which fields are shown. Global search and directory serach should be a permission configurable per role.

**Comment by engelgabriel** [comment]
We need to separate the outstanding tasks into other issue:
https://github.com/RocketChat/Rocket.Chat/issues/2355

**Comment by rodrigok** [comment]
> Maybe also looking into data retention for messages, for example? This would help implement the GDPR, see , for example, here.
> 
> We should store data as less as possible. Messages is of course a complicated matter I think, but keeping it infinity isn't worth the risk. So for example the ability to set a global "message retention policy" would be useful, so we are able to automatically delete messages after a year.

@Wouter0100, @mootari and @rasos The expiration police for messages will be implemented in the future since it's not required by GPDR (it's not an unnecessary information). You already have the option to delete your profile and remove your messages or delete each message manually.

> Another GDPR issue is showing minimum personal data in the room and directory search. It is configurable site-wide, which fields are taken for the search in admin/Accounts, but not, which fields are shown. Global search and directory serach should be a permission configurable per role.

@rasos we will evaluate this idea and find some solution that match the GPDR requirements and the minimum viable system usability.

Any further questions about GDPR should be sent to our email gdpr@rocket.chat

Thanks
