### ISSUE TITLE
Email verification et al should look to `ROOT_URL` in `docker-compose.yaml` when deploying using `docker-compose`

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#977]
I'm setting up email verification of accounts and in my logs I get

```
rocketchat_1 | (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
rocketchat_1 | Hello,
rocketchat_1 | 
rocketchat_1 | To verify your account email, simply click the link below.
rocketchat_1 | 
rocketchat_1 | http://<local-ip-address>:8080/login/#/verify-email/2L_DqzGWdvRdTM0wQe4tjT-kvmMJIEoj-q9NtD1lOD_
rocketchat_1 | 
````

I imagine the local IP address will be replaced with the `MAIL_URL` location but [docker documentation suggests deprecating this method](https://docs.docker.com/compose/env/) and suggests using the `docker-compose.yml`. Since that file [already asks for the `ROOT_URL`](https://github.com/RocketChat/Rocket.Chat/blob/master/docker-compose.yml#L5), mail should look to that file if the env variable is not found.

**Comment by mhkeller** [comment]
After reading https://github.com/RocketChat/Rocket.Chat/issues/717, it looks like I misunderstood what `MAIL_URL` is. After restarting, the `MAIL_URL` works correctly but I second that issue's suggestion that you tell people that they need to restart the server after configuring `MAIL_URL`.

The local ip address should be replaced with the `ROOT_URL` variable, if deploying via docker

**Comment by mhkeller** [comment]
Nevermind. This is working as it should. I mistook the local url for the actual URL!

**Comment by dalenoe** [comment]
I was having the problem of emails not sending. After a restart of the server they started working.. Just in case this might help anyone else.
