### ISSUE TITLE
Link to livechat queue looking bad

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#9770]
### Description:

Since the new sidebar UI the livechat queue link is looking bad either with last message enabled or not, icon and text are misaligned:

![image](https://user-images.githubusercontent.com/8591547/36390419-beb4d752-1581-11e8-80cd-a1ef208840c1.png)

![image](https://user-images.githubusercontent.com/8591547/36390423-c0d11f28-1581-11e8-882a-976e9a4e1412.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.1
* Operating System: All
* Deployment Method(snap/docker/tar/etc): All
* Number of Running Instances: Any
* DB Replicaset Oplog: Yes
* Node Version: Any

**Comment by abhishek71994** [comment]
Has the live chat feature been recently added? Because I don't find it in my forked version.

**Comment by sampaiodiego** [comment]
@abhishek71994 this is definitely not new https://github.com/RocketChat/Rocket.Chat/pull/3815 =)

**Comment by abhishek71994** [comment]
When I am running the app on my system, it's not showing such an error, I have just one PR, new to this code base 😅 .

**Comment by karlprieb** [comment]
Already fixed in 0.63 release.
