### ISSUE TITLE
Livechat status indicator is on a weird location

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#9771]
### Description:

![image](https://user-images.githubusercontent.com/1432373/34585682-deb6d36c-f1f4-11e7-9d5c-a8a9aeeba629.png)

Not sure where is the right place for it, but this does not look to be it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.1
* Operating System: All
* Deployment Method(snap/docker/tar/etc): All
* Number of Running Instances: Any
* DB Replicaset Oplog: Yes
* Node Version: Any

**Comment by abhishek71994** [comment]
Could you please help me recreate this bug? I'm not able to understand the issue. If possible I'd like to contribute to this.

**Comment by sampaiodiego** [comment]
@abhishek71994 you need to have livechat turned on and then start any livechat. but I have submitted a PR for this already

**Comment by abhishek71994** [comment]
Did so but, I'm not able to start any.

**Comment by abhishek71994** [comment]
@karlprieb I would like to work on this. But last time I couldn't recreate the bug. Some help?

**Comment by theorenck** [comment]
@sampaiodiego we are waiting for a definition from design team.

**Comment by engelgabriel** [comment]
![image](https://user-images.githubusercontent.com/1000217/41196603-517fa4d8-6c1a-11e8-93c2-833778324390.png)
