### ISSUE TITLE
message action menu does not appear on message hover ( RC 2.10.5 - Windows 10 )

### ISSUE THREAD

**Issue by jim-mason-dmxio** [RocketChat/Rocket.Chat#9774]
searched current issues and did not see an issue for this on Windows 10 client ..
Issue:  message action menu does not appear on message hover ( RC 2.10.5 - Windows 10 )

When message is hovered or selected, the message is "greyed" correctly but no message action menu appears. I can send a new message in the chat  ( in edit mode ) fine but can't star an existing message

**Comment by jim-mason-dmxio** [comment]
can't find a place to report a defect for rocketChat.electron.  there's no channel.  can't find a jira site etc

**Comment by kaiiiiiiiii** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
