### ISSUE TITLE
Add a setting to disable big emojis

### ISSUE THREAD

**Issue by Otiel** [RocketChat/Rocket.Chat#9780]
Without text, emojis are displayed in a larger size (request #2786). I find this quite annoying. Could we have an option to disable this and always display emojis normal size?

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by awunder** [comment]
fwiw the large emojis are really annoying.. i really second this request

**Comment by awunder** [comment]
fwiw, i "solved" it via custom css

.emojione.big {
  width: xx;
  height: yy;
}
