### ISSUE TITLE
Change emoji set using Custom Emoji Filesystem

### ISSUE THREAD

**Issue by Otiel** [RocketChat/Rocket.Chat#9782]
Is it possible to upload a whole emoji set (I got 2182 png) to replace the default emojis? I thought this was the goal of Custom Emoji Filesystem, but when I set this value, my emojis aren't seen by Rocket.Chat.

![screenshot](https://user-images.githubusercontent.com/3851902/36419760-20b28646-1633-11e8-90aa-4f1b1f2cd0c9.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Otiel 

no, this is currently not possible. `Custom Emoji Filesystem` only refers to the place where custom emojis are saved. For custom emoji sets, please refer to other issues, for example: #1838.

Cheers
Thomas
