### ISSUE TITLE
Mute Feature: Hide messages from specific users

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#9785]
It would be great if I can select a specific user and hide all their messages across all chat rooms (or in a specific room). 

This is helpful for large chat rooms where a few "loud mouth" users make too much noise.

The messages will still be shown to others in that same room. The user can still DM me unless I select "Block User" which already exists.

**Comment by rodrigok** [comment]
## Specification:

- The list will be per room
- Will be saved in user's subscription as an array of users to mute
- Will be a field in room's setting using the component we already have to select users when creating a new channel
- Will affect the rendering of the messages
- Will hide the user's messages when listed in muted array but will keep the username adding a button to expand/show the messages

**Comment by theorenck** [comment]
@danieljhochman what do you think?

**Comment by danieljhochman** [comment]
@theorenck - looks good. Just adding what @rodrigok said:

It's per room and per user, the mute button could be added to the message's action menu and you could add the user in input inside the room's preference.

Not sure what "inside the room's preference" means exactly.

**Comment by danieljhochman** [comment]
@theorenck - this is approved for dev, right?

**Comment by rafaelks** [comment]
@rodrigok Can you describe in more details this one?

> Will hide the user's messages when listed in muted array but will keep the username adding a button to expand/show the messages

**Comment by rodrigok** [comment]
@rafaelks I did update my specification with more details, @ggazzo will start developing the feature, will define the methods, icons and layout with @karlprieb and our design team, they will keep updating this issue with the interface decisions and DDP APIs developed (we can create a wrapper in REST of course).

Let me know if you need more information

**Comment by rafaelks** [comment]
@rodrigok Sounds good. Waiting for the APIs and UI mocks. 👍
