### ISSUE TITLE
How to revoke users the opportunity to set their username on first login?

### ISSUE THREAD

**Issue by dbluxo** [RocketChat/Rocket.Chat#9787]
Is it possible to revoke users the opportunity to set their username on first login?
A couple releases ago the LDAP username was automatically set. Now the users have to set their username on first login.

* Version of Rocket.Chat Server: 0.61.0

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
