### ISSUE TITLE
Elements and text "selected" stalls UI (user-select)

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#979]
fixes some bugs and follows slack's behaviour

**Comment by graywolf336** [comment]
I don't follow what you mean here, mind explaining some more?

**Comment by ninja-** [comment]
yes for example when you click ctrl+a it will select the user interface elements and this causes some bugs. slack blocks selecting ui elements

**Comment by AdrianoCahete** [comment]
This is because #684 . We need to define the user interaction: users can or can't select texts?

**Comment by rodrigok** [comment]
What do you think? https://github.com/RocketChat/Rocket.Chat/pull/991

**Comment by gmsecrieru** [comment]
Opening this one again, seems the cause/related to #1011 and #1019

**Comment by AdrianoCahete** [comment]
I think it's better to create a "can_select"/"cant_select" (or something better) classes and apply in parent div's who can be or can't be selected.

**Comment by zarvox** [comment]
You probably want to allow selection of at least the messages/timestamps in the scrollback.  People frequently want to copy/paste something that was sent to them into an email or notes or code or any number of things.
