### ISSUE TITLE
Translate documents to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [RocketChat/Rocket.Chat#9795]
HI! I'd like to offer a contribution to this project by offering a translation in to Spanish which is my native language, I can translate any file with over a thousand words. Let me know if you guys are interested I'll apprecciate it. CHEERS!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as I suspect @LuigiBaute to be a bot. If not I am sorry - please get back to me in that case.

Cheers
Thomas
