### ISSUE TITLE
Layout too narrow on settings

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#980]
In the screenshot below, the browser is 1287 pixels wide but the settings boxes are very narrow, causing overlapping text that is unreadable even though there is a lot of unused whitespace to the right. The layout should expand to fill this space so that it is more readable.

![screen shot 2015-10-02 at 4 19 58 pm](https://cloud.githubusercontent.com/assets/498744/10257485/b996017a-6925-11e5-9532-031358b1c1fe.png)
##

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
