### ISSUE TITLE
Missing properties on IM List

### ISSUE THREAD

**Issue by robindijkhof** [RocketChat/Rocket.Chat#9801]
### Description:

Multiple properties are missing on IM list. Also username returns the user its own name.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.1
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): Manual install
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4

### Steps to Reproduce:

1. Authenticate
2. Call http://ROCKETCHAT_SERVER/api/v1/im.list

### Expected behavior:

Somethink like this:
`{
    "ims": [
        {
            "_id": "ByehQjC44FwMeiLbX",
            "name": "test-test",
            "t": "p",
            "usernames": [
                "testing1"
            ],
            "msgs": 0,
            "u": {
                "_id": "aobEdbYhXfu5hkeqG",
                "username": "testing1"
            },
            "ts": "2016-12-09T15:08:58.042Z",
            "ro": false,
            "sysMes": true,
            "_updatedAt": "2016-12-09T15:22:40.656Z"
        },
    ],
    "success": true
}`

### Actual behavior:

`{
	"ims": [{
		"_id": "4ZDkLHA2YefWF6JQDeQe84G8gnpaQ5HRzQ",
		"_updatedAt": "2018-02-15T14:30:37.218Z",
		"t": "d",
		"msgs": 17,
		"ts": "2018-01-10T11:27:56.144Z",
		"lm": "2018-02-15T14:30:37.198Z",
		"username": "MY_OWN_USERNAME"
	}],
	"offset": 0,
	"count": 1,
	"total": 1,
	"success": true
}`

**Comment by xbolshe** [comment]
An expected behavior shown above is related with a private group (`"t": "p"`), but IM (`"t": "d"`) has differences:
- no name as described [here](https://rocket.chat/docs/developer-guides/schema-definition/) - Room Name (t:d -> empty)
- another `_id` because of a concatination of user ids
- limited quantity of room members (2 users)

**Comment by robindijkhof** [comment]
@xbolshe thanks. From the devWarning in the groups/channels and from the source code I found how to get the users.
