### ISSUE TITLE
Can't Click on Your Profile Image to Change Status

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#9803]
### Description:

In the past we used to be able to click on our profile image in the top to change our status, as of the new design we no longer can.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.0
* Operating System: Linux

### Steps to Reproduce:

1. Login
2. Click on profile image in the top left
3. Have nothing happen

### Expected behavior:

I expect to be able to click on my profile image/status circle to be able to change my status.

### Actual behavior:

Nothing happens.

### Relevant logs:
![screen shot 2018-02-21 at 8 37 47 am](https://user-images.githubusercontent.com/850391/36485773-86763afe-16e2-11e8-834e-942472c55a6b.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I have verified, that this is fixed by https://github.com/RocketChat/Rocket.Chat/pull/9843.

Cheers
Thomas
