### ISSUE TITLE
docker virtualbox won't forward to port 80

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#981]
Following up on this comment https://github.com/RocketChat/Rocket.Chat/issues/676#issuecomment-137788217, I still can't get forwarding to work on port `80`. I imagine it's because `80` is protected and usually requires `sudo` to use. Perhaps there's some sort of permissions settings that needs to be changed to allow for this.

**Comment by geekgonecrazy** [comment]
@mhkeller hit us up on the community chat some time for this.  This is for sure docker / virtualbox related and not related directly to rocket.chat in any way.

So i'm going to close this.
