### ISSUE TITLE
clicking channel action collapses sidebar

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9812]
### Description:
They say a picture is worth a thousand words, so a gif is worth several thousand?

![menu-break2](https://user-images.githubusercontent.com/51996/36493271-d2d58e10-16f4-11e8-9f4d-b8f6f345ab75.gif)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.0

### Steps to Reproduce:

1. reduce screen width
2. open nav
3. click channel action on another channel

### Expected behavior:

sidebar should stay put

### Actual behavior:

sidebar goes away

**Comment by tassoevan** [comment]
Stale.
