### ISSUE TITLE
Channel list view extended - livechat queue misaligned

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9813]
### Description:
![image](https://user-images.githubusercontent.com/51996/36494176-efd1610e-16f6-11e8-83e1-b82177eb58a5.png)

Set view mode to extended and be a livechat manager and then you'll see this :top: 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.0

**Comment by tassoevan** [comment]
Stale.
