### ISSUE TITLE
Discovery says search messages instead of search channels

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9815]
### Description:
![image](https://user-images.githubusercontent.com/51996/36495155-01db637e-16fa-11e8-838a-1a6a2a2e4adf.png)

Says search messages, shouldn't it say search channels?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.0

**Comment by kb0304** [comment]
Should it update on selecting `Users` in the adjacent select option?
Or else we could keep it just `Search`?

**Comment by geekgonecrazy** [comment]
That or be just generic enough that covers both :smile:
