### ISSUE TITLE
Desktop notifications still not working

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#982]
I was following this issue around desktop notifications https://github.com/RocketChat/Rocket.Chat/issues/682 but my team and I still can't get them to work on latest versions of Firefox and Safari. Happy to jump into live chat to help debug!

**Comment by ninja-** [comment]
they work if you are mentioned :P

**Comment by mhkeller** [comment]
Hmm, we're still not seeing them even when @-mentioned. Are they supposed to work for DM-s as well?

Is there any relevant log output that would help debug?

**Comment by ninja-** [comment]
weird. could you check if they are working on chrome?

**Comment by mhkeller** [comment]
checked in chrome and not working there either. i dont know if it makes a
difference but we checked whether chrome was in foreground and in the
background.

On Fri, Oct 2, 2015 at 5:54 PM, ninja <notifications@github.com> wrote:

> weird. could you check if they are working on chrome?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/982#issuecomment-145165319>
> .
>



-- 
@mhkeller
mhkeller.com

**Comment by rodrigok** [comment]
@mhkeller are you accessing using HTTPS?

**Comment by mhkeller** [comment]
This one might be my error in updating to the newest version. Will test when I have access to that machine.

**Comment by mhkeller** [comment]
They're working now after properly updating. They do seem to take about 10 minutes to kick in, however.
