### ISSUE TITLE
user status missing on user info

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#9820]
### Description:

![image](https://user-images.githubusercontent.com/51996/36503416-aca27e42-1712-11e8-9a55-8995aa2fd9ef.png)
I frequently click a user in a channel to start a conversation or see if they are online.  Now it seems to be gone?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.0

**Comment by vishwakperera** [comment]
Oh I thought even after that PR it's still unresolved. My bad 😅
