### ISSUE TITLE
[0.62.rc] Message box disappear 

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#9825]
Reproducible on https://open.rocket.chat.
Browser: FF 60
RC version : `0.62.0-rc.0` or whatever version is on open.rocket.chat as of now(22-02). :)

Clicking on `Member List`, `Pinned Messages` and `Files List` the message box disappear.

![selection_002](https://user-images.githubusercontent.com/1280585/36516643-0310be68-17ba-11e8-8c15-0e612e854b50.png)

**Comment by TwizzyDizzy** [comment]
Hi @mmarif4u 

I cannot reproduce your issue on the latest **stable** of Firefox, which is 58.0.2. Also, please adhere to the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) and provide all the information requested there.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
EDIT: it seems like, in general, the message box disappears if you resize your browser window (`window.innerHeight`) to roughly < 580px... the smaller window gets, the more the message box gets pushed down and, eventually, out of sight.

This doesn't happen on Chromium, only on FF (`58.0.2`).

Cheers
Thomas

**Comment by mmarif4u** [comment]
@TwizzyDizzy thanks for confirming. As i already mentioned this happens on open.rocket.chat, so i cant help more in providing extra information.

In my case, browser window resize does not have any effect on this, but clicking Members List have.

**Comment by TwizzyDizzy** [comment]
I see. Then please add at least the version of open.rocket.chat to your initial post, which is `0.62.0-rc.0`, and mention the fact that it happens on that instance :)

Cheers & Thanks
Thomas

**Comment by mmarif4u** [comment]
Actually i mentioned that in the 1st line, `Reproducible on https://open.rocket.chat.`. :)

**Comment by TwizzyDizzy** [comment]
Yes, but when in X days/weeks somebody looks at this issue and we will be at 0.62.0-rc.5 or whatever, nobody will know, that at this point in time `0.62.0-rc.0` was running on open.rocket.chat. So it's rather important to state which exact version this is.

Cheers
Thomas

**Comment by mmarif4u** [comment]
I can't say which version open.rocket.server is on now, is it rc.0 or build directly against develop or master branch. But i will add `0.62.0-rc.0` to OP. :)
