### ISSUE TITLE
[0.62.rc] Scroll missing again in FF

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#9826]
Reproducible on https://open.rocket.chat.
Browser : FF 60

**EDIT:**
Cannot scroll the user list and any other list in FF anymore.

![selection_003](https://user-images.githubusercontent.com/1280585/36516719-583f7fb4-17ba-11e8-8db0-f14eeef0e19c.png)

**Comment by TwizzyDizzy** [comment]
Hi @mmarif4u

I can reproduce your issue on the latest stable of Firefox, which is 58.0.2 on Rocket.Chat 0.62.0-rc.0. 

That being said, please adhere to the issue template and provide all the information requested there.

Cheers
Thomas

**Comment by mmarif4u** [comment]
It happens on open.rocket.chat server, so i believe it will be easy to get more info from that instance/server.
