### ISSUE TITLE
Use more reactivity on the server side

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#983]
I noticed that for some changes to get into the effect on the client side you have to reload Rocket Chat. I think this is because some publish functions are not reactive. So, a shameless plug, maybe you should use our new [reactive publish](https://github.com/peerlibrary/meteor-reactive-publish) to fix that. :-)
##

**Comment by gmsecrieru** [comment]
Thanks for the suggestion, @mitar -- would you be willing to describe in more details which "some changes" or a good use-case for the mentioned component?

**Comment by mitar** [comment]
@gmsecrieru: I just did it, easier than explaining. See #995.

**Comment by sampaiodiego** [comment]
@mitar , on the package page, there is a warning saying the package could break queries not expecting to be reactive.. how do you think it should break rocket.chat queries?

**Comment by mitar** [comment]
I checked things a bit and you have not been using `Tracker.autorun` on the server side before, so I do not think you have a situation where you are using `Tracker.autorun` with database queries inside assuming that they are not reactive. So I think you should be good. :-)

**Comment by marceloschmidt** [comment]
@mitar can you tell us what are the direct benefits of using this package on RC? I can't remember of something that requires a server restart to take effect. Thanks.

**Comment by mitar** [comment]
No, not server restart. But client reload. Or at least close the channel and then open it again.

**Comment by marceloschmidt** [comment]
Oh, ok... can you provide an example? Thanks.

**Comment by mitar** [comment]
Hm hm. I think looking at the code more, you are currently anyway using less of publish functions and more streams. So I am not sure if this is much useful. So only for permission-based publications.

**Comment by MartinSchoeler** [comment]
@mitar should this issue be closed?

**Comment by mitar** [comment]
Yea. It can be.
