### ISSUE TITLE
No room counter when activity-based sorting is active

### ISSUE THREAD

**Issue by kartoffelheld** [RocketChat/Rocket.Chat#9833]
### Description:

Room counters aren't displayed in the new sidebar when using the activity-based sorting. They are displayed just fine when sorting in alphabetical order. I'm on a completely fresh installation of Rocket.Chat. I've seen this behaviour in Chome 64, Firefox 58 and Rocket.Chat Electron 2.10.5.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.0
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: 8.9.3
* mongoDB Version: 3.4

### Steps to Reproduce:

1.  Switch on "Show room counter on sidebar" in your account settings
2.  Change the sidebar sorting mode between "Alphabetical" and "Activity"
3.  Room counter appears and disappears

### Expected behavior:

Room counter is displayed for both sorting modes

### Actual behavior:

Room counter is only displayed in alphabetical sorting mode

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
