### ISSUE TITLE
Changes on database aren't reflected on Rocket.Chat

### ISSUE THREAD

**Issue by jpasantos** [RocketChat/Rocket.Chat#9836]
### Description:

Changing values on mongoDb doesn't update information on Rocket.Chat

### Server Setup Information:

* Version of Rocket.Chat Server:  0.59.4
* Operating System: Ubuntu 17.10
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version:  4.8.7
* mongoDB Version: 3.0.15

### Steps to Reproduce:

1. Stop Rocket
2. Change data on mongodb. Example: Remove OAuth record from meteor_accounts_loginServiceConfiguration
3. Start Rocket

### Expected behavior:

Changed made in database reflected on Rocket

### Actual behavior:

Document is recreated on database

**Comment by TwizzyDizzy** [comment]
Hi @jpasantos 

My first question would be: why do you do things directly in MongoDB?

And maybe reason for that is something that might classify as a bug, yet I think what you describe is nothing that should be done. Do it via the UI, if it's not possible via the UI it is not supposed to be done.

If you disagree, please clarify :)

Cheers
Thomas

**Comment by jpasantos** [comment]
Hi @TwizzyDizzy I want to deploy several instances of Rocket.Chat and I don't want to manually do steps using the interface to do the initial configuration as this can be tedious and cannot be scaled properly. I tried using the rest api but it doesn't allow me to do everything I need

**Comment by TwizzyDizzy** [comment]
Hi again,

> I want to deploy several instances of Rocket.Chat and I don't want to manually do steps using the interface to do the initial configuration as this can be tedious and cannot be scaled properly.

I sympathize. Yet if the API is missing that possibility, it should be extended. I'd rather see the effort going in that direction, if it's an addition that would also benefit most users and not only you.

Cheers
Thomas

**Comment by jpasantos** [comment]
i'm totally down with extending the API it really is the best option but I still wonder if something is happening in the background that is preventing me from doing this. What makes Rocket ignore changes on the database is bothering me.

Best regards

**Comment by TwizzyDizzy** [comment]
> What makes Rocket ignore changes on the database is bothering me.

Let's turn this around and let's have MongoDB/Rocket.Chat speak to us:

> Somebody fiddles with my internals to do what he wants but is ignoring the fact that the thing he does is not the only thing that needs to be done in this context, but also X, Y and Z. Is this user crazy?

;)

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

So I think I'll close this issue. But feel free to open a new feature request to extend the API with what you're thinking would make sense (not only to you but) for a broader audience.

Cheers
Thomas
