### ISSUE TITLE
Limit the validity of passwords

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#9840]
For security reasons, Rocket. chat should force users to change their password after a configurable period of time has elapsed.

This Issue includes to prevent re-use passwords in case of password changes: A password history prevents at least the re-use of passwords in case of password changes.
The number of passwords should be configurable.

**Comment by TwizzyDizzy** [comment]
Hi @ruKurz 

forcing regular password changes decreases overall security: https://www.ncsc.gov.uk/articles/problems-forcing-regular-password-expiry

Cheers
Thomas

**Comment by ruKurz** [comment]
@TwizzyDizzy I totally agree. But now we have it documented ;-)

**Comment by TwizzyDizzy** [comment]
I don't get that. Could you elaborate?

Cheers
Thomas

**Comment by ruKurz** [comment]
As described in your referenced article, enforcing password changes no longer corresponds to the current state of security recommendations. Through this issue documents the deliberate decision to implement Rocket. chat, enforcing password changes for good reasons not to implement.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

OK, then I got you right in the first place. And I have to disagree not on what you're trying to do, but with the means you're using. Here are some thoughts:

* who am I? I am no member of the Rocket.Chat team and cannot speak for the software or the history of their decisions. Would you accept my answer as valid documentation?
* maybe RC has not decided actively against it, but only didn't implement it
* for the RC project itself, such documentation would better be consolidated into one document somewhere in the documentation, not here on github.

And let me close with one other thought. I, myself, am working for a company that is certified under ISO/IEC 27001. Which means: I know the drill. What you're trying to get here is a "paper" trail to point to but I'm rather sure, that to the auditors it's not relevant whether Rocket.Chat decided against password changes, but rather **why you decided to use a software that may (or may not) have decided against such policy**. That's relevant to them.

Please tell me if I'm wrong or whether you actually just wanted to inspire Rocket.Chat to document their security decisions.

Cheers
Thomas

**Comment by ruKurz** [comment]
@TwizzyDizzy Like you, I am convinced that for this discussion at github the auditors do not care. The article (https://www.ncsc.gov.uk/articles/problems-forcing-regular-password-expiry) you have shared not only coincides with my assessment, but provides a relevant source of argument for deliberate decision to take a risk. So thank you again for sharing your thoughts and knowledge.
