### ISSUE TITLE
Fix Android Cordova build broken after Meteor 1.2 update

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#985]
Android Cordova build no longer works after update to Meteor 1.2.

Error is often a frustrating:

`com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice`

**Comment by JamesLefrere** [comment]
Hi, I've had some luck with a very similar issue. I don't know about the details of this project, but for my Meteor Cordova project, it was a case of having multiple versions of android-support-v4.jar, or sometimes a combination of android-support-v13.jar and android-support-v4.jar for example. Later versions of this library are backwards-compatible, so you'll need to remove the older versions or exclude them from being compiled in the relevant project's build.gradle file. Once you're just using one of these libraries in the whole project, it should compile properly. Good luck...
