### ISSUE TITLE
Sidebar Item Message Cropping

### ISSUE THREAD

**Issue by rdnn** [RocketChat/Rocket.Chat#9856]
### Description:

Commit [7771ea199c91f726525ef808fec39dabb2e8849f](https://github.com/RocketChat/Rocket.Chat/commit/7771ea199c91f726525ef808fec39dabb2e8849f#diff-ea821dc65bfa3b6375ef900a43be3de2R178) added a -3px margin to .sidebar-item__message which is causing cropping of item messages in the sidebar of the administration view.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0-rc.1
* Operating System: FreeBSD 11.1-RELEASE-p4
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: No
* Node Version: 8.9.3
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. Open "Administration" sidebar

### Expected behavior:

![expected](https://user-images.githubusercontent.com/2176343/36578803-94463502-182d-11e8-999a-314d136e16de.png)

### Actual behavior:

![actual](https://user-images.githubusercontent.com/2176343/36578865-dff90542-182d-11e8-8c73-7d5c4b0220ed.png)

### Relevant logs:

N/A

**Comment by kaiiiiiiiii** [comment]
Already fixed in PR #9845

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @rdnn 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #9808 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by rdnn** [comment]
@TwizzyDizzy Yeah, definitely a duplicate. I tried searching before submitting but didn't find the original issue.

All looks good!

Thanks!
