### ISSUE TITLE
[Bug] svg avatar is not displayed

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9859]
### Description:

Users can upload avatars in their profile. It is also possible to upload svgs as avatar. However an uploaded svg is not displayed. The user will find a blank avater after upload.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Login and go to the edit profile page
2. Upload an svg as avatar, for example this one: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/android.svg
3. Success message appears - but you will find a blank avatar now

### Expected behavior:

Svg avatar should be displayed

### Actual behavior:

Avatar is not displayed

**Comment by karlprieb** [comment]
Hey @janrudolph in fact using svg as avatar is not allowed, but our file upload button are not working as it should.

**Comment by karlprieb** [comment]
@janrudolph we will use this issue.
