### ISSUE TITLE
[Bug] Sending invitation mails not possible although permissions are correct

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9861]
### Description:

Admins / Managers are able to send invitation mails. Currently this is just possible for full admins. Users who have the permission `bulk register user` are not able to do so.  

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Create a role which entails the permission `bulk register user` 
2. Assign the new role to a user.
3. The user is able to view the "Send invitation email" menu. 
4. If the user likes to send the invitation mails, the user gets an error

### Expected behavior:

User is able to send invitation mails.

### Actual behavior:

<img width="110" alt="einladungen-versenden-fehlermeldung" src="https://user-images.githubusercontent.com/3596824/36585801-9baa5b82-187f-11e8-8b97-764622e9f906.png">

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
