### ISSUE TITLE
REST API cleanhistory dont work

### ISSUE THREAD

**Issue by xlbs-rm** [RocketChat/Rocket.Chat#9862]
### Description:
Logged in as Admin with Admin Default rights, various Options of latest, oldest, nothing happen success everytime true.

https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory/

### Server Setup Information:

* Version of Rocket.Chat Server:  0.61.0
* Operating System:  
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

/api/v1/channels.cleanHistory

POST 
{
	"roomId": "abcdefg.....",
	"latest": "2018-01-21T00:01:25.304Z", 
	"oldest": "2018-02-23T13:42:25.304Z",
	"inclusive":	true
}
+ Auth Header

### Expected behavior:

Channel History deleted

### Actual behavior:

Nothing happen

Clean Private Group would be also helpfull.

**Comment by richgansa** [comment]
I am experiencing the same with 0.61.1. Trying to clear the general room.

**Comment by xbolshe** [comment]
It seems that a time period in the request is incorrect: latest < oldest
```
"latest": "2018-01-21T00:01:25.304Z",
"oldest": "2018-02-23T13:42:25.304Z",
```

[Docs](https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory/) describes that

```
latest | 2016-09-30T13:42:25.304Z | Required | The end of time range of messages to clean
oldest | 2016-05-30T13:42:25.304Z | Required | The start of the time range of messages to clean
```

**Comment by xlbs-rm** [comment]
Confirm, it worked!
I didn't see it immediately because the app and the browser still showed cached content.
