### ISSUE TITLE
Everyday the service drops

### ISSUE THREAD

**Issue by lucasromanomr** [RocketChat/Rocket.Chat#9864]
### Description:

Every day the service drops, it arrives at a certain time the service simply falls, then I have to give a restart in it so that it works again.

Error:

<img width="1566" alt="captura de tela 2018-02-23 as 09 29 55" src="https://user-images.githubusercontent.com/3859282/36596276-df575da4-1883-11e8-9713-e90886775f82.png">

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.1
* Operating System: Linux Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: NO
* Node Version: 8.9.3 - x64
* mongoDB Version: 3.2.19

<img width="873" alt="captura de tela 2018-02-23 as 10 22 39" src="https://user-images.githubusercontent.com/3859282/36596277-df584430-1883-11e8-9cf8-9c8d48131633.png">

### Steps to Reproduce:

I just leave the rocketchat service open, about 24 hours later it stops working and I have to reboot again. The error is in the screenshot I gave the terminal

**Comment by JSzaszvari** [comment]
Can you please provide more of there isn't enough output above to see what is causing the problem.

**Comment by TwizzyDizzy** [comment]
Also, please provide the FULL information requested in the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md). Thanks!

Cheers
Thomas

**Comment by lucasromanomr** [comment]
I put it as text information I was missing. I also put two images, a link to the error that made the service stop and do the service status after I rebooted.

I did a whole in-feed manually, grabbed the tar, unzipped and followed the Rocket documentation

**Comment by TwizzyDizzy** [comment]
The error in your first image does not show the full error trace, only the end of it. Please get it from either /var/log/messages or /var/log/syslog (I think it's the latter on Ubuntu).

Cheers
Thomas

**Comment by lucasromanomr** [comment]
I took a look at the log (below) and I think there's something about slackBrigde, but I'm not sure about that.
```
Feb 23 13:09:33 ip-172-26-14-165 node[19186]: Exception in defer callback: TypeError: Cannot read property 'id' of undefined
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at SlackBridge.postDeleteMessageToSlack (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_slackbridge.js:1480:54)
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at SlackBridge.onRocketMessageDelete (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_slackbridge.js:1368:8)
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at /home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1157:27
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at Array.reduce (<anonymous>:null:null)
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at Object.RocketChat.callbacks.run (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1150:6)
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at /home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_lib.js:4388:25
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at packages/meteor.js:502:25
Feb 23 13:09:33 ip-172-26-14-165 node[19186]:     at runWithEnvironment (packages/meteor.js:1240:24)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]: Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls or publications.
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at AccountsServer.userId (/home/ubuntu/Rocket.Chat/programs/server/packages/accounts-base.js:501:35)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at AccountsServer.user (/home/ubuntu/Rocket.Chat/programs/server/packages/accounts-base.js:117:23)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at Object.Meteor.user (/home/ubuntu/Rocket.Chat/programs/server/packages/accounts-base.js:321:19)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at Filter.validateFileUpload [as onCheck] (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:93:23)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at Filter.check (/home/ubuntu/Rocket.Chat/programs/server/packages/jalik_ufs.js:558:57)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at FileUploadClass.insert (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:587:11)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at requestModule.get.Meteor.bindEnvironment.stream (/home/ubuntu/Rocket.Chat/programs/server/packages/rocketchat_slackbridge.js:846:14)
Feb 23 13:11:31 ip-172-26-14-165 node[19186]:     at runWithEnvironment (packages/meteor.js:1240:24)
Feb 23 13:13:55 ip-172-26-14-165 caddy[6920]: 2018/02/23 13:13:55 http: TLS handshake error from 177.53.170.30:51080: EOF
Feb 23 13:15:58 ip-172-26-14-165 caddy[6920]: 2018/02/23 13:15:58 http: TLS handshake error from 177.206.29.244:45482: EOF
````

**Comment by TwizzyDizzy** [comment]
@rocke-cat close

I will temporarily close this issue, as you failed to provide relevant information. If you decide to provide them and it then seems like that this is an actual issue, I'll happily reopen this issue.

Cheers
Thomas

**Comment by immanuelfodor** [comment]
I think this is the same issue as #10331 , I also run ito it, now trying to switch node versions wit the `n` tool.
