### ISSUE TITLE
User context menu doesn't contain "Administration" anymore, nor does the "three-dots" menu

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#9865]
### Description:

I have given the `[manage-emoji]` permission to normal users. This lead to them having an "Administration" menu with only one option: to add custom emojis.

With the new discovery menu, this option is not contained in the Status menu and it is not available as extended options in the menu ("three-dots menu" - which isn't even present, only the add channel [+]).

So currently it is not possible to access the custom emoji interface from the normal menu despite having the respective privileges.

Cheers
Thomas

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Operating System: Oracle Linux 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: 8.9.4
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. Please see image below

### Expected behavior:

* Give a possibility to access the administration menu, if you have the `[manage-emoji]` permission.

### Actual behavior:

![screen](https://user-images.githubusercontent.com/179595/36596523-4d576746-18a6-11e8-85a0-5351b54f34df.png)

### Relevant logs:

-

**Comment by TwizzyDizzy** [comment]
This is still present in 0.62.0

**Comment by c0dzilla** [comment]
@karlprieb may I send a pr for this? :)

**Comment by TwizzyDizzy** [comment]
Hey, @karlprieb, could you have a look at this PR? :)

Cheers
Thomas

**Comment by karlprieb** [comment]
@TwizzyDizzy this PR is approved already, just waiting to be merged.

**Comment by a-bern** [comment]
Hi @rodrigok 
Could you please explain why you closed this issue? The main problem is still not fixed. 
Users with "manage-integrations" for example permissions are still not able to see the admin menu.

Should we open a separate issue for each permission that requires the admin menu?

Thanks

Alex
