### ISSUE TITLE
Client crashes when posting ```x-:

### ISSUE THREAD

**Issue by leoluk** [RocketChat/Rocket.Chat#9868]
### Description:

The Rocket Chat client crashes when someone posts this:

    ```x-:

(reduced to minimum amount of characters necessary to trigger the bug)

Browser: Chrome 64.0.3282.167 (Official Build) (64-bit)

Dev Tools stop responding, nothing visible in console.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): installed from source
* Number of Running Instances: 1
* DB Replicaset Oplog: N/A
* Node Version: 4.2.6
* mongoDB Version: 2.6.10

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @leoluk 

I cannot confirm this on the latest stable version of Rocket.Chat (which is `0.61.2`) testing with Chromium `64.0.3282.167`. Please update your version of Rocket.Chat and try to reproduce the error there.

If you can reproduce it on the latest stable, I will happily reopen this issue :)

Cheers
Thomas
