### ISSUE TITLE
Display "Member of [channels]" in user information on Members List

### ISSUE THREAD

**Issue by gmsecrieru** [RocketChat/Rocket.Chat#987]
##

**Comment by gmsecrieru** [comment]
Possibly related to #69

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
