### ISSUE TITLE
Allow navigation history to be send to the CRM along with other requests

### ISSUE THREAD

**Issue by theorenck** [RocketChat/Rocket.Chat#9874]
### Description
Add a setting to control if the navigation history will be sent to the CRM along with other requests
- [x] add a setting
- [x] add it to the request payload

**Comment by renatobecker** [comment]
@theorenck, do you know if there is an `endpoint` to test this issue?

**Comment by renatobecker** [comment]
To continue this feature I have to wait for this review #10151.
