### ISSUE TITLE
Livechat Realtime API doc page is outdate

### ISSUE THREAD

**Issue by xvonabur** [RocketChat/Rocket.Chat#9875]
### Description:

Hello! It seems that `Livechat Realtime API` [doc page](https://rocket.chat/docs/developer-guides/realtime-api/livechat-api/) is outdate, because current livechat implementation does not use some methods and some responses are different. For example, I don't see token in response for `livechat:registerGuest`. Response contains `userId` only. 

And no calling `login` method on `https://open.rocket.chat/livechat` or my own server. I see calls for `loginByToken` in some cases.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

**Comment by engelgabriel** [comment]
Closed in favor of https://github.com/RocketChat/docs/issues/603
