### ISSUE TITLE
Multiple instances are not synced

### ISSUE THREAD

**Issue by amonemian** [RocketChat/Rocket.Chat#9881]
When using multiple instances of RC, everything is Ok but the sessions in different servers are not sync. I mean, when one message is seen in one room, it is not marked as read in another browser who is watching that room. The read message is still unread!

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
