### ISSUE TITLE
[BUG] Android Push notification is not working

### ISSUE THREAD

**Issue by dezzzus** [RocketChat/Rocket.Chat#9885]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: 
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 6.4
* mongoDB Version: 3.2 

### Steps to Reproduce:

1. Sign in by using android phone.
2. close rocket chat app
3. send message from desktop

### Expected behavior:

It shows new message by using notification.
[NEW]
In additional, I hope to change this push notification logic.
I want to receive push notification when I am online, too.
If I am talking in Channel A and User A sends message to me in Direct ChatRoom, I want to receive push notification of it.
So I made some changes on server side, too.
I need to receive current room id from mobile app.

### Actual behavior:
I can't find any push notification on my android phone.

**Comment by ggrish** [comment]
I think android push notification problem can be fixed by using another raix:push version.

**Comment by PhpXp** [comment]
In my testing, it works in Firefox but not in Chrome.
OS: Android 8.0.
Chrome version: Beta 65.0.3325.85
Firefox version: 58.0.2

**Comment by ggazzo** [comment]
we had a lot of changes since you opened this issue see: https://rocket.chat/2019/09/27/push-notification/

please open it again if the problem persists
