### ISSUE TITLE
Show name instead of username in invite form

### ISSUE THREAD

**Issue by idanielblake** [RocketChat/Rocket.Chat#9890]
### Description:

Hello, First of all thanks for you great work.
When you want to invite users to channels or private groups after search list will show users' avatar and usernames but we want to show real names instead of usernames.
Thanks in advanced :)

### Server Setup Information:

* Version of Rocket.Chat Server: 61.2
* Operating System: Centos 7
* Number of Running Instances: 4
* DB Replicaset Oplog: enabled
* Node Version: 8.4
* mongoDB Version: 3.6.1

**Comment by sanudatta11** [comment]
Can I work on it?

**Comment by karlprieb** [comment]
Hey @idanielblake as you can search for names on that list already, we will add the Name on the results when you turn on the "Use Real Name" option on admin, ok? So the result will return `Name @username` as we already do on messages.
![image](https://user-images.githubusercontent.com/9200155/36849807-c3967612-1d43-11e8-86ad-ec8b97450b02.png)

**Comment by karlprieb** [comment]
@sanudatta11 you can work on that fix if you want. Talk with me on open.rocket.chat if you need any help to understand what we want for this fix.
