### ISSUE TITLE
file upload filename

### ISSUE THREAD

**Issue by fog1992** [RocketChat/Rocket.Chat#9899]
### Description:

Is it possible to upload a file to Rocket.Chat and keep the filename? In our projects we use a samba-server to share files. I set up Rocket.Chat to store files in the samba shar folder. But they are unusable because Rocket.Chat changes the filename to a string like 7AE8tXkji7P53QAJP.  (same with minio and the filename filed in GridFS) I kown this is to have a unique id. 

### Server Setup Information:

* Version of Rocket.Chat Server:  0.60.4
* Operating System:  Debian 9
* Number of Running Instances:  1
* Node Version:  v8.9.3

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
