### ISSUE TITLE
LDAP not syncing password

### ISSUE THREAD

**Issue by OtavioCapila** [RocketChat/Rocket.Chat#9900]
### Description:

When i try to sync new users to Rocket.Chat,it only sync the user,but not the password,so i have to set a new password in Administration > Users > "Select User" > Edit and Change password.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): Docker 
* Number of Running Instances: 4
* DB Replicaset Oplog: Enable
* Node Version: V8.9.4
* mongoDB Version: idk

### Steps to Reproduce:

1.  Create a new Users in LDAP
2.  Do a sync in Rocket.Chat(LDAP > Execute Synchronization now)
3. Try to log in using the new User,and fail.... 

### Expected behavior:

Log in normally

### Actual behavior:

 An alert saying "Username and password are incorrect"

**Comment by rodrigok** [comment]
The LDAP server does not allow us to get the user's password but when the user login the auth process happens against the LDAP server and should allow the login, you probably configured your LDAP settings wrong and the auth is not happening so the server tries to fallback to local password that you set to the user (you can disable that fallback)

For the fallback we store the user's password when he do a successful login on LDAP server to allow the login when the LDAP is offline, again, you can disable that fallback.

**Comment by OtavioCapila** [comment]
I've made a user in AD to test,but still not working
![capturar](https://user-images.githubusercontent.com/29285724/36735492-1f863e02-1bb5-11e8-8a66-6009ab016631.JPG)
![capturar2](https://user-images.githubusercontent.com/29285724/36735498-238f45d4-1bb5-11e8-9096-f5ab5662ab01.JPG)
![capturar3](https://user-images.githubusercontent.com/29285724/36735524-2f884b60-1bb5-11e8-8838-5cb484a32553.JPG)

**Comment by OtavioCapila** [comment]
Is there something wrong with LDAP config in my RC?

![ldap1](https://user-images.githubusercontent.com/29285724/36737355-a0ed6886-1bb9-11e8-8574-db14c43a609b.JPG)
![ldap2](https://user-images.githubusercontent.com/29285724/36737356-a10d0b46-1bb9-11e8-8c26-e6a8c58b806d.JPG)
![ldap3](https://user-images.githubusercontent.com/29285724/36737357-a1331156-1bb9-11e8-8940-5c5d71fe7849.JPG)
![ldap4](https://user-images.githubusercontent.com/29285724/36737359-a15114bc-1bb9-11e8-8cc4-0fcd17893f17.JPG)
![ldap5](https://user-images.githubusercontent.com/29285724/36737360-a175c4f6-1bb9-11e8-98ed-e99cf0e6a57f.JPG)
![ldap6](https://user-images.githubusercontent.com/29285724/36737361-a194b38e-1bb9-11e8-9a0d-c27f1ea5003d.JPG)

**Comment by rodrigok** [comment]
Can you set your log level to `Debug`, try to login again a paste the server logs here?

**Comment by OtavioCapila** [comment]
![ldap7](https://user-images.githubusercontent.com/29285724/36741352-9e502258-1bc3-11e8-9734-d0bfe289511d.JPG)

**Comment by rodrigok** [comment]
@OtavioCapila Did you see the error? `User not in valid group`

**Comment by OtavioCapila** [comment]
@rodrigok I created that test user in the same OU where is my common user.
But,if i change manually the password of that users,it will logon without problem.

**Comment by OtavioCapila** [comment]
![ldap8](https://user-images.githubusercontent.com/29285724/36741547-2cc4e776-1bc4-11e8-8ad3-be39571073cb.JPG)
![ldap9](https://user-images.githubusercontent.com/29285724/36741548-2ce4da86-1bc4-11e8-9581-9a24d30d7905.JPG)

**Comment by OtavioCapila** [comment]
So i've changed the password,and there's no error
![ldap10](https://user-images.githubusercontent.com/29285724/36741649-67910038-1bc4-11e8-9f0a-8bab1ab0d79a.JPG)

**Comment by OtavioCapila** [comment]
I've changed the user password,and logged in normally(with the same error "User not in valid group")
![ldap10](https://user-images.githubusercontent.com/29285724/36741694-8627a5ce-1bc4-11e8-8a4d-dddf17a19b48.JPG)

**Comment by OtavioCapila** [comment]
Could be the version of NodeJS?

**Comment by fcoppolani** [comment]
If it can help : #9834

**Comment by OtavioCapila** [comment]
@fcoppolani Atlassian crowd are disabled.

**Comment by OtavioCapila** [comment]
Anyone?

**Comment by iesit** [comment]
> For the fallback we store the user's password when he do a successful login on LDAP server to allow the login when the LDAP is offline, again, you can disable that fallback.

Seems to me that it is a security issue to "cache" the user's password locally.  The user is authenticated with LDAP, so why store the user-entered password locally?

**Comment by rodrigok** [comment]
@iesit 
> to allow the login when the LDAP is offline, again, you can disable that fallback.

It's stored encrypted as the normal passwords.

**Comment by iesit** [comment]
> 
> 
> @iesit
> 
> > to allow the login when the LDAP is offline, again, you can disable that fallback.
> 
> It's stored encrypted as the normal passwords.

With LDAP -> Login Fallback set to False, I cannot authenticate users created outside of LDAP, which is important (I seem to recall there is a [forum post](https://forums.rocket.chat/t/ldap-auth-and-local-users/2504) regarding authenticating users through Rocket locally and using LDAP?).  While the inability to authenticate both LDAP and non-LDAP accounts is not insurmountable (and preventing Rocket from storing LDAP passwords locally should be avoided at all costs), it does require that new installations will need to manually add user(s) which are also in LDAP, set those desired users' role to include administrator AND ensure that LDAP -> Sync / Import -> Merge Existing Users = True, and ensure that the LDAP query returns those administrative users before synchronizing.

As others here and/or in similar issues have pointed out, if LDAP is offline, then there are bigger issues.  Rocket should not be storing LDAP passwords anywhere at any time because LDAP is the authority of the passwords.  If rocket can't authenticate a user with LDAP in realtime, then that user should not be able to log in.

Seems to me that if we removed the "password caching", then we would be able to set LDAP -> Login Fallback set to True, and allow both non-LDAP and LDAP users to log in.

Thank you for your time and effort!

**Comment by iesit** [comment]
Does closing this issue mean it was resolved?  (Maybe I'm not familiar with how Github works?)

It appears to me that LDAP passwords are still being stored in Rocket's database, which many would argue should NOT be happening in an Enterprise team chat.

Thanks!

**Comment by saschafoerster** [comment]
@iesit I guess it is a duplicate of #4554.
