### ISSUE TITLE
User's push token mysteriously disappears

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#9911]
### Description:

Our push notifications stopped working, 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0

### Steps to Reproduce:

1. Send a message whilst someone is offline.

### Expected behavior:

They get a push notification.

### Actual behavior:

1. No push is received (email is).
2. If the push was a test one from the admin interface, the green success bubble appears.

### Relevant logs:
```
rocketchat_1 | Meteor ➔ method push_test -> userId: c2dHmBiBDi6d2xePN , arguments:  {}
rocketchat_1 | Push: send message "@antony.gelberg" via query { userId: 'c2dHmBiBDi6d2xePN' }
rocketchat_1 | Push: send to token { gcm: 'c5BikYRvcNU:SECRET' }
rocketchat_1 | Push: send to token { gcm: 'ccGBcFzKlyg:SECRET' }
rocketchat_1 | Meteor ➔ publish null -> userId: null , arguments:  {}
rocketchat_1 | Meteor ➔ method public-settings/get -> userId: null , arguments:  {}
rocketchat_1 | Meteor ➔ method permissions/get -> userId: null , arguments:  {}
rocketchat_1 | Meteor ➔ publish null -> userId: 8PQiwGH7ojJsX8wDp , arguments:  {}
rocketchat_1 | Meteor ➔ publish activeUsers -> userId: 8PQiwGH7ojJsX8wDp , arguments:  {}
rocketchat_1 | BaseCache ➔ debug users Falling back _publishCursor to model with query: { username: { '$exists': 1 },
rocketchat_1 |   status: { '$in': [ 'online', 'away', 'busy' ] } }
rocketchat_1 | Meteor ➔ publish userData -> userId: 8PQiwGH7ojJsX8wDp , arguments:  {}
rocketchat_1 | BaseCache ➔ debug users Falling back _publishCursor to model with query: 8PQiwGH7ojJsX8wDp
rocketchat_1 | Meteor ➔ method subscriptions/get -> userId: 8PQiwGH7ojJsX8wDp , arguments:  {}
rocketchat_1 | Meteor ➔ method raix:push-update -> userId: 8PQiwGH7ojJsX8wDp , arguments:  { '0':
rocketchat_1 |    { id: '68b10751d4af4b81832541c858912edf',
rocketchat_1 |      appName: 'main',
rocketchat_1 |      userId: '8PQiwGH7ojJsX8wDp',
rocketchat_1 |      metadata: {},
rocketchat_1 |      token:
rocketchat_1 |       { gcm: 'dkdmabnMQOs:SECRET' } } }
```

Any clues what's (not) going on? I'm not the only one in my organization suffering this.

**Comment by antgel** [comment]
I just got a single push notification! So weird! But when I clicked test, I didn't get another one. I haven't done anything except log into Mongo, where I was considering deleting push tokens, but haven't yet.

**Comment by antgel** [comment]
Okay, it looks like the user's push token was deleted according to `db.getCollection("_raix_push_app_tokens").find({userId:"6JJXojrwYHDjHiHc4"});`. He logged out of and into the app, and it now works for him. If anyone knows how this could have happened, I'd love to know.

For my part, maybe my pushes weren't working because I had two push tokens stored for my user, after reinstalling my phone a few days ago. Deleted one, seems to be working. (Normal RC notifications are working, ironically tests aren't, but I can live with that...)

**Comment by sudhirbitsgoa** [comment]
Im also facing this issue
The token disappears. Not sure what is triggering this disappear
