### ISSUE TITLE
Forgot your password fails to send email

### ISSUE THREAD

**Issue by mysiar** [RocketChat/Rocket.Chat#9913]
### Description:

Email settings are set and tested. Can send test email, can send messages by email
Reset password doesn't work.
Typing registered email error is: **_cant send email all recipients were rejected_**
Typing dummy not existing email message is: **_If this email is registered we'll send instructions..._**

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux x64 4.4.0-97-generic
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.3 
* mongoDB Version:  3.2.19

### Steps to Reproduce:

1. click Forget password on web page
2. type your user email address & submit

### Expected behavior:

Receiving email with password reset link

### Actual behavior:

Error message cant send email all recipients were rejected

**Comment by kaiiiiiiiii** [comment]
#1766 #2077

I don't think this is a bug in Rocket.Chat. It sounds more like a misconfiguration of your SMTP settings or mail server.

**Comment by mysiar** [comment]
@kaiiiiiiiii thanks for the hint 
this line fixed it

export MAIL_URL=smtp://USERNAME:PASSWORD@HOST:PORT/
