### ISSUE TITLE
Realtime Api does not return ID

### ISSUE THREAD

**Issue by robindijkhof** [RocketChat/Rocket.Chat#9917]
### Description:

When using stream-room-messages I get some response but the actual id is "id"

### Server Setup Information:

 * Version of Rocket.Chat Server: 0.61.1
 * Operating System: Ubuntu 16.04 LTS
 * Deployment Method(snap/docker/tar/etc): Manual install
 * Number of Running Instances: 1
 * DB Replicaset Oplog:
 * Node Version: 8.9.4 

### Steps to Reproduce:

Using the realtime api subscribe to stream-room-messages.
Wait till it is ready.
Send a message in using the (web) client.

Object:
`{
      "msg": "sub",
      "id": SOME_GUID,
      "name": "stream-room-messages",
      "params":[ ROOM_ID, false ]
}`

### Expected behavior:

`{msg: "changed", collection: "stream-room-messages", id: "SOME_GUID", fields: Object}`

### Actual behavior:

`{msg: "changed", collection: "stream-room-messages", id: "id", fields: Object}`

**Comment by rodrigok** [comment]
@robindijkhof that's how the stream package works https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/server/server.js#L307 to prevent server's cache for meteor's subscriptions.

**Comment by lcl-account** [comment]
I encountered the same problem as you, how did you solve it.

**Comment by lcl-account** [comment]
@robindijkhof I encountered the same problem as you, how did you solve it.

**Comment by robindijkhof** [comment]
I don't think I did

**Comment by Polgabarro** [comment]
Same problem, what is the solution? For me it has not sense to return "id:id"

**Comment by movcmpret** [comment]
Are there any solutions yet?

**Comment by rodrigok** [comment]
Why do you guys need that id? We use that API for our web and mobile apps without any problem.

**Comment by movcmpret** [comment]
I'm using a custom event manager (js) with multiple `stream-room-messages` subscriptions. It would be nice to actually use a subscription id to differentiate the events coming from the websocket. My workaround is to search for the `roomid` in the returned object (in `fields`) to allocate the response to a specific room in order to fire an event for that.
