### ISSUE TITLE
Import Chat History

### ISSUE THREAD

**Issue by tyronegrandison** [RocketChat/Rocket.Chat#992]
If would be nice to a feature that allows the import of:
1) slack channels and their history
2) Chat histories from other IM programs

**Comment by graywolf336** [comment]
In progress ;)

**Comment by tyronegrandison** [comment]
Phenomenal.

**Comment by graywolf336** [comment]
How are you thinking the import should be done, @tyronegrandison? As currently the idea is to import the exported zip file from Slack, but that only contains users, channels, messages & files.

**Comment by tyronegrandison** [comment]
@graywolf336 does it contain user emails or just user names? If both username and user email then that  zip file is perfect for a first version.

**Comment by graywolf336** [comment]
Yes, it contains all that and more.

**Comment by tyronegrandison** [comment]
Then you are good to go. 

Any thoughts on importing chat histories from GChat, etc ?

**Comment by graywolf336** [comment]
Not sure yet, the framework for the importing is still in the works..how does one export from GChat?

**Comment by tyronegrandison** [comment]
I think Google Takeout (https://www.google.com/settings/takeout/custom/chat) is the recommended way.

**Comment by graywolf336** [comment]
I will have to look into it and see how the data is structured. Are you thinking Google Apps import or personal ones?

**Comment by tyronegrandison** [comment]
Thinking that Google Apps import should be first because then you can import histories from business users

**Comment by graywolf336** [comment]
Slack import is now in the development branch.
