### ISSUE TITLE
reset password url is redirecting to the login page.

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#9923]
@a11anarete commented on [Tue Feb 27 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/674)

### Description:

Password reset URL is going to the login page.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): RPM
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. When a user clicks on reset password.
2. User gets the email and a link to reset their password.
3. User then clicks on the reset password link.
4. User is redirected back to the login page.

### Expected behavior:

The link shows the reset password page

### Actual behavior:

The link goes to the login page

### Other information -- the email example below:

Hello,

To reset your password, simply click the link below.

`https://[hostDNS]/#/reset-password/[SHA256 hash]`

Thanks.

#### * I found that removing the # hash, the link goes to the correct URL.

`https://[hostDNS]/reset-password/[SHA256 hash]`

#### * Where can I change this in the code?

Thank you in advance.

---

@a11anarete commented on [Tue Feb 27 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/674#issuecomment-368912591)

Just for information, I was looking at the `app.js` which had this line and thought this was the problem.  I removed the `#/` and restarted the service but still the same error.

...
				Accounts.emailTemplates.resetPassword.html = function (userModel, url) {
					url = url.replace('/#/', '/');
					return html.replace(/\[Forgot_Password_Url]/g, url);
				};
...

---

@a11anarete commented on [Tue Feb 27 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/674#issuecomment-368912780)

code block:

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/sendForgotPasswordEmail.js#L14

---

@a11anarete commented on [Tue Feb 27 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/674#issuecomment-368912927)

I got around the problem by adding a place holder for the reset password URL.

``` javascript
https://hostname/reset-password/sha256
```
The only issue I have with this is this `sha256` part,  I attempted to use the URL with just `https://hostname/reset-password/` but the page hangs.

Can this be changed somehow, without the `/sha256` part?

Allan

---

@a11anarete commented on [Tue Feb 27 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/674#issuecomment-368920279)

I think I found where the `#/` is, thanks to @aaron.ogle

https://github.com/meteor/meteor/blob/devel/packages/accounts-base/url_server.js

Can the `#/` be remove as this seem to be causing the url issue?

**Comment by a11anarete** [comment]
@gdelavald is it me or is this going in a loop, #674 then #9923 and so on...  

Do you have a solution?

**Comment by karlprieb** [comment]
@a11anarete this is a Rocket.Chat web client issue and not a Rocket.Chat Desktop App issue, that's why @gdelavald brought #674 issue to this repository.

**Comment by karlprieb** [comment]
@a11anarete Sorry i looked at #3883 just now. I'll close this issue and we can keep that thread.

Duplicated of #3883
