### ISSUE TITLE
[BUG] Emoji is showing original and from Emojione into the message

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9924]
### Description:

The message is displaying both unicode & Emojione emoji image.

![screen shot 2018-02-27 at 15 53 10](https://user-images.githubusercontent.com/551004/36749000-469f27c4-1bd8-11e8-91b5-9a49b1c678d0.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.
* Operating System: Linux

### Steps to Reproduce:

Here's the HTML generated for the message:

```html
<span class="emojione emojione-1f44d big" title=":thumbsup:">👍</span>
```

**It's not ALWAYS reproducible**.

### Expected behavior:

It should render only one (or another).

### Actual behavior:

Sometimes it shows two different emojis (from unicode and from Emojione).

**Comment by rafaelks** [comment]
@karlprieb Added to you, but not really sure to who I should assign this.

**Comment by karlprieb** [comment]
@rafaelks do you know exactly when both emojis are displayed? It's just this message?

**Comment by rafaelks** [comment]
@karlprieb I saw happening with this message and a few times on the left-sidebar. I didn't find a way to  reproduce it yet.

**Comment by nemaniarjun** [comment]
@mrinaldhar I think we noticed this too?

**Comment by karlprieb** [comment]
We @RocketChat/ui tried to reproduce this bug without success, so I will close this issue.

If someone can reproduce and give us a step by step of how to do it I will open this issue again.
