### ISSUE TITLE
[IMPROVEMENT] Browser should never auto-fill values when editing another's user profile

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9925]
### Description:

We should not provide auto-fill values when editing another's user profile.

![screen shot 2018-02-27 at 16 02 05](https://user-images.githubusercontent.com/551004/36748928-14dac234-1bd8-11e8-807e-22593fffc2a6.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.
* Operating System: Linux

### Steps to Reproduce:

1. Open admin with Safari
2. Edit a user's profile
3. Safari will auto-fill some values (in yellow)

### Expected behavior:

Browser should **never** auto-fill those fields for me.

### Actual behavior:

Browser auto-fills and I can end up changing some other's user password by mistake.

**Comment by rafaelks** [comment]
@karlprieb Added to you, but not really sure to who I should assign this.

**Comment by kaiiiiiiiii** [comment]
@rafaelks I’ll take this one, if it’s ok for you guys :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karlprieb** [comment]
Go ahead @kaiiiiiiiii :) Thank you!
