### ISSUE TITLE
[BUG] When server is slow, if I send a message it appears like the other users sent it

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9926]
### Description:

![screen shot 2018-02-27 at 16 11 19](https://user-images.githubusercontent.com/551004/36749309-283c01d4-1bd9-11e8-9007-3bfcced775ea.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62
* Operating System: Linux

### Steps to Reproduce:

1. Server is slow;
2. Send messages in sequence with other user;

### Expected behavior:

It should separate messages to each user.

### Actual behavior:

It shows message from User A as from User B.

**Comment by rafaelks** [comment]
@karlprieb Assigned to you, but not really should who should be assigned.

**Comment by karlprieb** [comment]
Thank you for this report @rafaelks We already know that issue but we didn't created an issue for that. I'll investigate that.

**Comment by kajisaap** [comment]
We are planning to upgrade to the latest release - should we hold back? 

@rafaelks - how is your server resource wise? What triggers the resource depletion for the server? No. of connected users and their interaction?

@karlprieb - since when have we known about his issue? We are at 0.59.X

**Comment by karlprieb** [comment]
@kajisaap before 0.59 for sure, but it only happens on open.rocket.chat that is a huge server.
