### ISSUE TITLE
Permission for Delete Private Channels does not work

### ISSUE THREAD

**Issue by arakon5** [RocketChat/Rocket.Chat#9927]
### Description:

The permission "Delete Private Channels[delete-p]" seemed to be originally intended to allow private rooms to be deleted by their owners.  Changing this no longer seems to have any effect, due to the template having "canDeleteRoom" button commented out completely (packages/rocketchat-channel-settings/client/views/channelSettings.html)

Possibly due to commit:
https://github.com/RocketChat/Rocket.Chat/commit/752bccd6ccfdc66ef771b4cfd4404806b57eac98

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc):  tar
* Number of Running Instances:  1
* DB Replicaset Oplog: 
* Node Version: v8.9.3
* mongoDB Version: 

### Steps to Reproduce:

1. Set permissions so owners can delete private channels
2. Create a private channel
3. Go to Info, and no Delete button available.

### Expected behavior:

A delete button to be available.  This is important due to users needing to manage their own transient groups that will have limited lifespans and have no archive value.

### Actual behavior:
No delete button is displayed.

### Relevant logs:

<!-- For more information about collecting logs please see:

**Comment by nemaniarjun** [comment]
@ggazzo  Why was this done? https://github.com/RocketChat/Rocket.Chat/commit/752bccd6ccfdc66ef771b4cfd4404806b57eac98#diff-1a6f84da371f01b326a0fe7e72febe53R189
