### ISSUE TITLE
<div class="room-container"></div> is empty after reload page in Chrome

### ISSUE THREAD

**Issue by benoneb** [RocketChat/Rocket.Chat#9929]
What happens?
<div class="room-container"></div> is empty after reload page in Chrome.
Ubuntu 16.04 w/ Gnome
Chrome Version 64.0.3282.167 (Official Build) (64-bit)
We test with different Ubuntu versions and Chrome version and same behavior happen after reload window.
Only the room where the <CTRL + R> was executed get empty, other rooms work normally, including rooms that was blank/empty before by <CRTL + R> reload got fixed, but room where <CTRL + R> was last executed gets empty.

Works well without issues after reload in Firefox and Rocket.Chat+ 64bits client. The issue just occurs in Chrome.

Steps to reproduce 
1. Get in any room.
2. Ctrl + R.
3. Room div gets no content.

Thanks in advanced!
Benone

**Comment by MartinSchoeler** [comment]
@benoneb  Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information. We need to know at least the version of the server, since this could've been fixed in a new release. Thanks

**Comment by geekgonecrazy** [comment]
Closing due to lack of response
