### ISSUE TITLE
uploading avatar causes crash

### ISSUE THREAD

**Issue by ltdenard** [RocketChat/Rocket.Chat#993]
When I upload a png or jpg file as my avatar, it causes rocket chat crash with the following err in the logs. What other details should I include? 

Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

/var/www/rocket.chat/bundle/programs/server/packages/meteor.js:974
    throw new Error("Meteor code must always run within a Fiber. " +          
          ^
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Meteor.isRestricted (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:161:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:208:1)
    at Object.UserPresence.removeConnectionsByInstanceId (packages/konecty_user-presence/packages/konecty_user-presence.js:88:1)
    at process.<anonymous> (packages/konecty_user-presence/packages/konecty_user-presence.js:223:1)
    at process.emit (events.js:117:20)
    at process.exit (node.js:740:17)
    at process.catchException (/usr/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:52:15)
    at process.g (events.js:180:16)

**Comment by geekgonecrazy** [comment]
This is because its running into a permission issue writing the file.  I'm guessing you changed to Filesystem for avatar storage?

Also what platform?

**Comment by ltdenard** [comment]
This is what it was set to by default.. i think? If I can switch it to database storage, that's fine as well. 
https://i.imgur.com/WqTqEBl.png

I'm doing the standalone deployment without docker. Currently, i'm on a CentOS Linux release 7.1.1503 (Core) server.

The following is how I have installed everything so far. Most of it is a copy/paste from the original guide but I have added some things. 

# on chat server
yum install -y epel-release
yum install -y nginx nodejs nodejs-mongodb mongodb mongodb-server wget npm policycoreutils-python
yum group install "Development Tools"

npm install nave -g

nave usemain 0.10.40

curl https://install.meteor.com/ | sh

npm install pm2 -g

pm2 startup systemd

nano /etc/hosts
# add system name to 127.0.0.1

sed -i 's|#replSet = arg|replSet = node01|g' /etc/mongod.conf

systemctl enable mongod
systemctl start mongod

mongo

rs.initiate()

{
    "info2" : "no configuration explicitly specified -- making one",
    "me" : "localhost:27017",
    "info" : "Config now saved locally.  Should come online in about a minute.",
    "ok" : 1
}

exit


openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certificate.key -out /etc/nginx/certificate.crt

setsebool -P httpd_can_network_connect on
setsebool -P httpd_unified 1

nano /etc/nginx/nginx.conf
# remove http server block

nano /etc/nginx/conf.d/rocketchat.conf

# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

# HTTPS Server
server {
    listen 443;
    server_name rocketchat10.pingnattack.com;

    error_log /var/log/nginx/rocketchat.access.log;

    ssl on;
    ssl_certificate /etc/nginx/certificate.crt;
    ssl_certificate_key /etc/nginx/certificate.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

    location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}

# change root_url to chat url
# change host to hostname
HOST=https://rocketchat.pingnattack.com
MONGO_URL=mongodb://localhost:27017/rocketchat
MONGO_OPLOG_URL=mongodb://localhost:27017/local
ROOT_URL=https://rocketchat.pingnattack.com
PORT=3000


mkdir -p /var/www/
mkdir -p /var/log/rocket.chat
cd /var/www/
wget https://github.com/RocketChat/Rocket.Chat/archive/master.tar.gz
tar -xvzf master.tar.gz
mv Rocket.Chat-master rocket.chat

cd ./rocket.chat
meteor build --server "$HOST" --directory .

cd ./bundle/programs/server
npm install

cd ../..

rm -f pm2-rocket-chat.json
echo '{'                                                     > pm2-rocket-chat.json
echo '  "apps": [{'                                         >> pm2-rocket-chat.json
echo '    "name": "rocket.chat",'                           >> pm2-rocket-chat.json
echo '    "script": "/var/www/rocket.chat/bundle/main.js",' >> pm2-rocket-chat.json
echo '    "out_file": "/var/log/rocket.chat/app.log",'      >> pm2-rocket-chat.json
echo '    "error_file": "/var/log/rocket.chat/err.log",'    >> pm2-rocket-chat.json
echo "    \"port\": \"$PORT\","                             >> pm2-rocket-chat.json
echo '    "env": {'                                         >> pm2-rocket-chat.json
echo "      \"MONGO_URL\": \"$MONGO_URL\","                 >> pm2-rocket-chat.json
echo "      \"MONGO_OPLOG_URL\": \"$MONGO_OPLOG_URL\","     >> pm2-rocket-chat.json
echo "      \"ROOT_URL\": \"$ROOT_URL\","                   >> pm2-rocket-chat.json
echo "      \"PORT\": \"$PORT\""                            >> pm2-rocket-chat.json
echo '    }'                                                >> pm2-rocket-chat.json
echo '  }]'                                                 >> pm2-rocket-chat.json
echo '}'  >> pm2-rocket-chat.json


pm2 start /var/www/rocket.chat/bundle/pm2-rocket-chat.json
pm2 save

# made so avatar's don't crash the program
mkdir -p /var/www/rocket.chat/uploads/avatar/
chmod -R 777 /var/www/rocket.chat/uploads

firewall-cmd --zone=public --permanent --add-service=http
firewall-cmd --zone=public --permanent --add-service=https
systemctl enable firewalld
systemctl restart firewalld

nano /etc/systemd/system/pm2.service
# add to After= 
mongod.service 


nano /usr/lib/systemd/system/nginx.service
# add to After= 
mongod.service pm2.service



httpd_sys_script_rw_t

httpd_sys_content_t

chcon -Rv --type=httpd_sys_content_t /var/www
chcon -Rv --type=httpd_sys_script_rw_t /var/www/rocket.chat/uploads

**Comment by ltdenard** [comment]
Just discovered this. Turning Accounts_AvatarResize to False only causes the program to momentarily time out with the "try again" bar at the top but the upload happens to the database and the avatar changes.

**Comment by unquietwiki** [comment]
Hey, folks at my office were running into this, and had to use the new? feature to disable avatar changes. Problems have occurred since we installed last week: regardless of PNG, JPG, GridFS, Filesystem, or Gravitar. Anything we can do to help fix / troubleshoot this?

**Comment by marceloschmidt** [comment]
This problem seems to occur only when the resize option is turned on. Rocket.Chat uses GraphicsMagick for resizing, so you'd have to have that installed on your box. 

If you are willing to try that, here's how to install: https://gist.github.com/paul91/9008409

If that doesn't fix it, we may reopen this issue.

**Comment by geekgonecrazy** [comment]
@marceloschmidt should we maybe add a note to that toggle so that people at least know?  Maybe with a link to a wiki article explaining?

**Comment by marceloschmidt** [comment]
Absolutely! @sampaiodiego suggested we have a list of dependencies... Would that be the first one?

**Comment by unquietwiki** [comment]
Using Ubuntu 14.04, an "apt-get install graphicsmagick" & rebuilding the app appears to have done the trick. Thanks! :+1:
