### ISSUE TITLE
[BUG] Blank panel after renaming user

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat#9930]
I only get a green "saved" badge in the upper right corner, but no content at all in the side panel.

* Version of Rocket.Chat Server: 0.62.0-develop
* Operating System: osx

### Steps to Reproduce:

1. Go to users in admin panel
2. Edit an users username
3. Click save
4. See nothing than a blank panel

### Expected behavior:

An updated view of the user info page.

### Actual behavior:

![test](https://user-images.githubusercontent.com/4711233/36859936-4928953a-1d80-11e8-8966-d4a6f220bbe8.gif)

**Comment by vishwakperera** [comment]
Can I get this assigned to me?

**Comment by JSzaszvari** [comment]
You don't assign issues in GitHub. Just let people know you are working on it and then submit a PR.
