### ISSUE TITLE
Provide JOIN group/channel invitation URL

### ISSUE THREAD

**Issue by aphilsmith** [RocketChat/Rocket.Chat#9933]
A huge improvement would be to generate admin URL to invite users to join a group/channel. This is a powerful feature on Telegram that Rocket Chat sorely needs.

**Comment by nemaniarjun** [comment]
I am interested in taking this up, but seems like a huge improvement, would like if someone broke it down into smaller issues.

**Comment by ndroo** [comment]
Has anyone started on this? I agree its a great idea and would be interested to help move it along.

**Comment by geekgonecrazy** [comment]
This is actually implemented.  Goto users list on channel.  Down at the bottom can click invite.  This will let you generate an invite link and control how long it’s good for, how many redemptions etc
