### ISSUE TITLE
incorrect file path in "Deploying Rocket.Chat Server Binaries on a FreeBSD system" manual at https://rocket.chat/docs/installation/manual-installation/freebsd/universal/

### ISSUE THREAD

**Issue by gogosofta** [RocketChat/Rocket.Chat#9938]
fetch: https://download.rocket.chat/build/rocket.chat-freebsd-develop.tgz: Not Found

**Comment by geekgonecrazy** [comment]
The build was too old and vulnerable it had to be taken down.  Opened an issue on docs repo
