### ISSUE TITLE
No more 'unread room mode' for Sidebar Channel List Mode

### ISSUE THREAD

**Issue by himpich** [RocketChat/Rocket.Chat#9939]
### Description:

The Personal option "Sidebar Channel List Mode" is missing in 0.62.0 - no more unread room mode

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 4
* DB Replicaset Oplog: yes
* Node Version: -
* mongoDB Version: 3.2.9

### Expected behavior:

I have the option to set "Sidebar Channel List Mode" to "Unread room mode" like in < 0.62.0

### Actual behavior:

Option is missing

### Relevant logs:
-

**Comment by lostdesign** [comment]
![screenshot](https://i.imgur.com/B2XScWu.png)
As you can see in https://open.rocket.chat, its hidden underneath the global icon in the left sidebar.

**Comment by himpich** [comment]
Thanks for clarifying the new location of that option (found it and it's working). 

In that case we lost the previous setting...

**Comment by TwizzyDizzy** [comment]
So this is no actual issue, then, right? :) Still good to clarify, yet if there is no bug I'd like to close this issue :)

Cheers
Thomas

**Comment by himpich** [comment]
Issue closed to to "no bug"

Preserving old settings and maybe leave a hint in the old options would have been nice, but it's ok :)

**Comment by sigma67** [comment]
This needs to be updated in the documentation: https://rocket.chat/docs/user-guides/channels/
