### ISSUE TITLE
[BUG] Create new channel dialogue disappears below sidebar

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#9940]
### Description:

If you resize the window, at some point the "Create new channel" UI disappears below the sidebar. I think the width of the sidebar is not taken into account, as at some point the disappearance of the sidebar (in favour of "the burger menu") still triggers. See the GIF below for further details.

This happens on Firefox 58.0.2 as well as Chromium 64.0.3282.167.

### Server Setup Information:

Version of Rocket.Chat Server: 0.62.0
Operating System: Oracle Linux 7
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
DB Replicaset Oplog: -
Node Version: 8.9.4
mongoDB Version: 2.6.12

### Steps to Reproduce:

1. Resize width of window
2. Watch dialogue disappear "below" sidebar menu
3. See GIF below for details

### Expected behavior:

* Sidebar retraction should trigger earlier when resizing, so the dialogue stays visible

### Actual behavior:

* Dialogue disappears "below" sidebar menu

![ezgif-5-b8739e2bb1](https://user-images.githubusercontent.com/179595/36784679-93db916e-1c80-11e8-9d34-b0755e3231ef.gif)

### Relevant logs:
-

**Comment by c0dzilla** [comment]
Taking this up.

**Comment by c0dzilla** [comment]
@karlprieb while viewing a channel, the channel width reduces on reducing window width, with the sidenav's width not changing at all upto a certain width, after which sidenav retracts. In create channel view, is the same behaviour desired or sidenav should retract from the beginning as suggested in the issue?

**Comment by karlprieb** [comment]
@c0dzilla we are still thinking about it... so we didn't decide which is best for the UI, but we will fix this issue :)
