### ISSUE TITLE
Cannot pull image registry.connect.redhat.com/rocketchat/rocketchat

### ISSUE THREAD

**Issue by christianh814** [RocketChat/Rocket.Chat#9944]
### Description:
Deploying template into openshift fails because it cannot pull registry.connect.redhat.com/rocketchat/rocketchat

### Server Setup Information:

Irrelevant as I can't get the image

### Steps to Reproduce:

1. `oc new-app -f https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/.openshift/rocket-chat-persistent.json`
2. It doesn't pull
3. No one gets to chat

### Expected behavior:

Rocketchat comes up

### Actual behavior:

Image fails to pull

### Other info

I'm able to pull the image using my RH credentials; but my question is two.

1) If I (or someone else that has bought OCP) am running OpenShift enterprise; why do I need to provide a login? I've already paid for OCP.

2) Why does this upstream project hide an image behind a paywall?

**Comment by geekgonecrazy** [comment]
Taking a look at this and the PR.  Thanks for that btw.

Talking with redhat guys to see what we can do here.

**Comment by christianh814** [comment]
@geekgonecrazy <<bump>>

Any word? Which RH guys? I can ping them on our internal irc
