### ISSUE TITLE
Directory view does not scroll in Firefox

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#9951]
### Description:

Directory view does not scroll nor does it have visible scrollbar in Firefox 58.0.2.
Scrolling and scrollbar works on Chrome and Firefox ESR 52.6.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 5
* DB Replicaset Oplog: Enabled
* Node Version: v.8.9.4

### Steps to Reproduce:

1. Make sure that you have enough public rooms to list in Directory view
2. Try to scroll the directory list with Firefox 58.0.2 with mouse wheel

### Expected behavior:

You can browse through all available public rooms like in Chrome.

### Actual behavior:

Observe that there is no scrollbar in the Directory view.
The directory listing does not scroll.

**Comment by MartinSchoeler** [comment]
This issue was already fixed on the latest develop version. You can go to open.rocket.chat and test it on your current firefox. Thanks!

**Comment by Gummikavalier** [comment]
Thanks. Interesting... At first it didn't (at open.rocket.chat either), but then I resized my Firefox window once a bit smaller, and that triggered the scroll bar it and scrolling started working.

This same worked now on our 0.62 installation too.

**Comment by Gummikavalier** [comment]
How to reproduce: Make the Firefox browser screen small. Press F5. Go to Directory view. Note that scroll bar is visible. Do *not scroll*.

![screenshot from 2018-03-02 17-15-48](https://user-images.githubusercontent.com/6958942/36906010-7ae3981e-1e3d-11e8-89ce-5d09bf71a98c.png)

Increase the windows size until the scrollbar vanishes and see lots of white on the bottom. Try to scroll with mousewheel. The list does not scroll.

![screenshot from 2018-03-02 17-18-28](https://user-images.githubusercontent.com/6958942/36906123-c424bc88-1e3d-11e8-9f95-10c38649070b.png)

**Comment by Gummikavalier** [comment]
@MartinSchoeler Looks like this problem got worse in 0.64.0. Open.rocket.chat with FF 59.0.2 looks like this currently:

![screenshot from 2018-04-28 10-48-20](https://user-images.githubusercontent.com/6958942/39393757-e1018492-4ad1-11e8-843b-53f648784f7c.png)

**Comment by Gummikavalier** [comment]
Custom CSS workaround to fix the problem for anyone witnessing the same problem:
```
section.rc-directory {
	height: 99%;
}
```

**Comment by lightweight** [comment]
Thanks for the work-around, @Gummikavalier. Problem still there in 0.64.1.
