### ISSUE TITLE
Windows client: Unable to download files from channel file list

### ISSUE THREAD

**Issue by danila-kovalev** [RocketChat/Rocket.Chat#9954]
### Description:

It is not possible to download files from "files list" of the channel.
This is valid for win-client only
Using web-browser as a client or apple-mobile-app - there are no such problem

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: linux-x64-4.4.0-112-generic
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.8.1
* mongoDB Version: 

### Steps to Reproduce:

1. open "File list" of the channel -> files of the channel are displayed ok (one file is *.odt document)
2. click on *.odt 
3. no action

exception: if you click on picture file (*.jpg or *.png) - it is displayed in client

### Expected behavior:

User expect File->Save dialog window
Note: it is possible to download this file if you find it in discussion thread
But if the discussion thread is huge it is quite painfull and non-user-friendly to look for it scrolling back and forth through tons of text lines. 

### Actual behavior:

nothing happens

**Comment by rw4lll** [comment]
Also encountered with this bug. Download button inside chat is working but in dedicated channel filelist is not workint.

**Comment by MartinSchoeler** [comment]
Please reopen this [here](https://github.com/RocketChat/Rocket.Chat.Electron)

**Comment by danila-kovalev** [comment]
Reopened here:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/678
as suggested by MartinSchoeler
