### ISSUE TITLE
Add more friendly loading screen

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#996]
currently it's just "undefined" and a blue screen

**Comment by gmsecrieru** [comment]
Related to #800

**Comment by SaptakS** [comment]
I would like to contribute in this. Can you please guide me what are the things I should do?

**Comment by gmsecrieru** [comment]
@SaptakS This is an attempt to reproduce this situation:

![loading-undefined](https://cloud.githubusercontent.com/assets/190883/10280407/61d49134-6b43-11e5-95a1-5c4a3a734a7e.gif)

Issue #800 also has relevant information

**Comment by engelgabriel** [comment]
Fixed, long time ago.
