### ISSUE TITLE
[NEW] Directory REST APIs

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9961]

**Comment by graywolf336** [comment]
Can you explain what you mean by this?

**Comment by rafaelks** [comment]
@graywolf336 Sorry... I added it in the middle of a meeting and forgot to add more information. For the new "Directory" feature, is there any API available for us to develop in the mobile clients? If not, we'll need that. It's basically an API that list the users/channels, with the ability to sort and search on it.

**Comment by graywolf336** [comment]
Ah right, I completely forgot we went with that name for the explore/discovery feature.

If I am not mistaken, @ggazzo can correct me if I am wrong, but that feature simply uses the spotlight feature?

**Comment by rafaelks** [comment]
I'll move this one 0.64 because we **really** need the APIs in order to have this feature on the mobile apps.
