### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#9964]
### Description:

Installation fails, using the instructions here:

https://rocket.chat/docs/installation/manual-installation/ubuntu/

### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. download Rocket.Chat
2. perform npm install

### Expected behavior:

Successful build of Rocket.Chat

### Actual behavior:

Fatal Error

### Relevant logs:

https://hastebin.com/heqaqureqi.bash

**Comment by c0fe** [comment]
Also, g++ build-essential are installed:

`root@talk:/tmp/Rocket.Chat/programs/server# apt-get install g++ build-essential -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
g++ is already the newest version (4:5.3.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by lostdesign** [comment]
Seems like your node version is not matching with the required version for rocket.chat.
What does `node -v` say?

**Comment by c0fe** [comment]
@lostdesign 4.2.6

**Comment by kaiiiiiiiii** [comment]
Please install at least Node version 8.9.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
