### ISSUE TITLE
Add Sound Notifications To Highlighted Words

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#9965]
### Description:
Feature request to add a sound notification when a "Highlighted Word" has been triggered.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.2

**Comment by JSzaszvari** [comment]
@rocket-cat label add enhancement

**Comment by setpill** [comment]
This seems to already be working?

**Comment by richardwlu** [comment]
@setpill Can you show me how then? I do not see the feature. We should be able customize the sound to differentiate from a message and a highlighted message.

**Comment by setpill** [comment]
Under "My Account -> Preferences" there is a "HIGHLIGHTS" section where you can define words/phrases to receive notifications on. This functions in the same way (same sound) as if someone @-mentioned you/the room. So if you need to differentiate between being @-mentioned and having a word highlight triggered, I don't think that's currently possible, but it was not clear to me from the original issue description that that's what you meant :)

**Comment by geekgonecrazy** [comment]
based on that going to go ahead and close
