### ISSUE TITLE
HTML code in GitLab Slack notification integration

### ISSUE THREAD

**Issue by pasmon** [RocketChat/Rocket.Chat#9970]
### Description:

Opening merge request in GitLab displays HTML code in Rocket.Chat.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.2
* Operating System: RHEL 7.4
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 8.9.4
* mongoDB Version: 3.4.10

### Steps to Reproduce:

1. Configure incoming webhook without any script defined in Rocket.Chat
2. Configure "Slack notifications" integration in GitLab
3. Open new merge request in GitLab

### Expected behavior:

Merge request information notification is beautifully rendered in Rocket.Chat channel.

### Actual behavior:

Some ugly HTML code appears in the merge request opening notification.

### Relevant logs:
![gitlab_slack_integration_issue](https://user-images.githubusercontent.com/3045294/36886785-ae54bff8-1df6-11e8-8842-1f45a44f700f.png)

Seems to work fine in Slack (image from http://www.almtoolbox.com/blog/case-study-thomson-reuters-gitlab-jenkins-slack/):
http://www.almtoolbox.com/blog/wp-content/uploads/2017/06/gitlab-slack-bot-tr1.jpg

**Comment by pasmon** [comment]
HTML code visible also in case of merging the merge request.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @pasmon 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #8332 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by pasmon** [comment]
Thanks @TwizzyDizzy, this might indeed be same issue - I'll follow up on that one instead.
