### ISSUE TITLE
[Bug] SSO login error message not localized

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9971]
### Description:

Single Sign-on users cannot access a team, if `Accounts_ManuallyApproveNewUsers = true`. If users try to access the team, they get an error message. However, the error message is not localized.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Set `Accounts_ManuallyApproveNewUsers = true`
2. Try to login with SSO
3. Get error message 

### Expected behavior:

Get the same localized error message as local, not activated users.

Example in German:
<img width="180" alt="local-user-not-activated" src="https://user-images.githubusercontent.com/3596824/36888186-a577e5d8-1df4-11e8-87d2-eb94ebb9f832.png">

### Actual behavior:

Users see a not localized error message

<img width="186" alt="sso-not-activated" src="https://user-images.githubusercontent.com/3596824/36888201-ba217ba2-1df4-11e8-917f-ce822edb3fa0.png">

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
