### ISSUE TITLE
[Bug] Guests do not see channels in the left sidebar

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9974]
### Description:

Teams can invite guests in order to collaborate with non-team members. In the past, this works pretty fine. Since 0.61 guests do not see their channels in the left sidebar anymore (web app). In mobile it works as expected.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Add user and assign `guest` role
2. Invite guest to new channel
3. Login as guest user. In the web interface you do not find the channel in the channel list.

### Expected behavior:

Mobile:
![ansicht_handy](https://user-images.githubusercontent.com/3596824/36897188-e2148340-1e15-11e8-97f2-f3a1878c95d3.png)

### Actual behavior:

Web:
![ansicht_web](https://user-images.githubusercontent.com/3596824/36897226-ff23e778-1e15-11e8-96be-102a9b48bf3c.png)

**Comment by MartinSchoeler** [comment]
@janrudolph Could you test this against the latest version, since we had a lot of changes on the sidebar on version 0.62. Thanks!

**Comment by kaiiiiiiiii** [comment]
I can't reproduce the error in 0.62.0.

![2018-03-02 16_06_27- 16 netorium chat](https://user-images.githubusercontent.com/4711233/36905542-f03d4c7c-1e33-11e8-849d-5e16e0d63cf8.png)

**Comment by MartinSchoeler** [comment]
@janrudolph also you should check your permissions page, see if the guest has the appropriate `view` permissions

**Comment by janrudolph** [comment]
@MartinSchoeler @kaiiiiiiiii  
I launched a plain Rocket.Chat 0.62 server and tested it again. **Result:** _This kind of error occurs just with **private channels**._ Please find details below:

**Test-setup:**
1) Launch new server
2) Add two users: "jan" = `admin`, "peter" = `guest`
3) jan created a new **private channel** (aka group) and invited peter.
4) peter does not find the channel in the left sidebar. If peter opens the channel by pasting the URL in the browser address field, he can access the room. But the room is not listed in the sidebar, see screenshot attached. 

<img width="469" alt="guest-misses-room-list" src="https://user-images.githubusercontent.com/3596824/37208349-670baf70-23a1-11e8-840b-80f1a2ba7659.png">

I tested it again with **public channels**: These type of rooms are listed.

**Comment by mommi84** [comment]
This is temporarily solved by searching for the private channel (or promptly clicking on a received notification) and then marking it as favorite.

**Comment by arteislt** [comment]
+1

**Comment by danpospisil** [comment]
@MartinSchoeler - we are experiencing this issue as well on 0.65.1

**Comment by hasumashi** [comment]
In order for private channels to be visible by guests they have to have _View private room_ `view-p-room` permission added to their role.

**Comment by hasumashi** [comment]
Still, I think if they cannot view private channels in sidebar they also shouldn't be able to search for such channels.

**Comment by roura356a** [comment]
Our client are having the same issues. They don't see the private groups they are part of. No notification badge or anything. They can search, but when they are part of multiple groups gets annoying. For us is a big problem.
