### ISSUE TITLE
Can't connect to server via IOS/Android app from intenet.

### ISSUE THREAD

**Issue by madcry** [RocketChat/Rocket.Chat#9975]
### Description:

Can't connect from mobile app, from intenet

### Server Setup Information:

* Version of Rocket.Chat Server:  0.61.0
* Operating System:  1 Gb
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: lates
* Node Version: v8.9.3
* mongoDB Version: lates

### Steps to Reproduce:

1. when i'm trying to connect from ios/adndroid app from intenet on domain name with port, becouse RC server behind NAT like, domain.nm:3333,app download 120/120 files and show white screen with error: trying to connect to server: x sec. When i'm connect from webbrowser all going ok. Using cert Comodo CA Limited. And if i'm connect mobile to local wi-fi and connect to this server with local domain name, all ok too.

### Expected behavior:

1. Whanna to connect from mobile app.

### Nginx settings

```
# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

# Redirect Options
server {
  listen 80;
  server_name chat.domain.nm;
  # enforce https
  return 301 https://$server_name$request_uri;
}

# HTTPS Server
server {
    listen 443;
    server_name chat.domain.nm;

    error_log /var/log/nginx/rocketchat.access.log;

    ssl on;
    ssl_certificate /etc/nginx/ssl/rocket-chat.crt;
    ssl_certificate_key /etc/nginx/ssl/rocket-chat.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # dont use SSLv3 ref: POODLE

    location / {
        proxy_pass http://192.168.0.38:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}
```

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by TwizzyDizzy** [comment]
Mhhhhh... it depends: if, for example, the mobile client doesn't take the port numbers into consideration (and put it in every request that communicates with the server) it might very well be an issue (yet in the mobile client).
