### ISSUE TITLE
Apostrophe-containing URL misparsed

### ISSUE THREAD

**Issue by ExTechOp** [RocketChat/Rocket.Chat#9976]
### Description:

Pasted URLs mistakenly get truncated at apostrophes, although this is a valid character in an URL according to [RFC 3986](https://tools.ietf.org/html/rfc3986)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 5
* DB Replicaset Oplog: enabled
* Node Version: v8.9.4
* mongoDB Version: mongodb-server-2.6.12-6.el7.x86_64

### Steps to Reproduce:

1. Paste URL containing apostrophe, eg. `https://en.wikipedia.org/wiki/Devil's_advocate`
2. Observe preview
3. Access URL by clicking it

### Expected behavior:

The preview and page access would be for the Wikipedia page containing the apostrophe, eg. "Devil's advocate"

### Actual behavior:

The preview and access ends up being truncated at the apostrophe, eg. the Wikipedia page "Devil"

**Comment by c0dzilla** [comment]
Taking this up.

**Comment by sumedh123** [comment]
This issue was reported earlier and has a pull request https://github.com/RocketChat/Rocket.Chat/pull/9739
@c0dzilla

**Comment by c0dzilla** [comment]
Cool @sumedh123 , you can reference this issue as well in the pr so that others know it has been addressed :)

**Comment by c0dzilla** [comment]
Okay @ExTechOp , I'll have a look

**Comment by ExTechOp** [comment]
Over a year on, this still seems to be an issue with version 2.2.0: the posted URL does not get truncated (and clicking it will take you to the right place), but the preview does get truncated (and will take you to the incorrect place).
So https://en.wikipedia.org/wiki/Devil's_advocate gives correct direct link, but the clickable preview is for https://en.wikipedia.org/wiki/Devil and will take you to that page if clicked.
