### ISSUE TITLE
When keyboard opens in app in landscape screen it add extra white space under every screen and whole app layout messed up in landscape screen mode.

### ISSUE THREAD

**Issue by iamank1t** [RocketChat/Rocket.Chat#9977]
#### Expected behavior
Whenever i open keyboard in app in landscape screen to type something, the layout of screen or placement of elements needs to be remain consistence. And one more major thing is if app supports landscape and portrait mode then app layout needs to be consistence on both modes, no button, image or view needs to cut or overlap each other.

#### Actual behavior
Whenever i open keyboard in app in landscape screen, the keyboard adds extra white space under the screen of app which makes the app layout buggy. When i switch between screen rotation modes the app fails the auto adjusts its views to fit according to screen size. I can't point out specific screen because this is happening on whole app.

#### How to reproduce
To reproduce the bug follow the following steps :-
- Open the app and rotate device to landscape.
 - Go to any screen where you can open keyboard to type.
- After keyboard opens, now scroll the view and you can find extra white space under the screen.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v2.7.0
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=tCh-jkTo6WI
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/when-keyboard-opens-in-app-in-landscape-screen-it-add-extra-white-space-under-every-screen-and-whole-app-layout-messed-up-in">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MartinSchoeler** [comment]
This issue is a Rocket.Chat android app one, thus should be reopened [here](https://github.com/RocketChat/Rocket.Chat.Android)
