### ISSUE TITLE
[IMPROVEMENT] Remove all markdown from Push Notification

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9979]
### Description:

It doesn't make any sense to have markdown tags in our push notification message, if we remove it would be much cleaner and easier do read.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.
* Operating System: Linux

**Comment by rafaelks** [comment]
@theorenck Not sure who should be assigned here, but this one is very important for us in order to have a better experience on the mobile apps.

**Comment by c0dzilla** [comment]
Taking this up.

**Comment by c0dzilla** [comment]
@rafaelks needed some clarification on urls. What should be done with something like [text](url), removed completely or only show text/url?

**Comment by rafaelks** [comment]
@c0dzilla Good question. In this case, showing only the text. Basically, the text of the push notification needs to be the same text that user will read, without any "special" format (links included).

**Comment by rafaelks** [comment]
Moving this one to 0.64, will drastically improve the experience of receiving a notification on the mobile apps.

**Comment by Sameesunkaria** [comment]
This applies to the desktop notifications as well.

<img width="330" alt="screen shot 2018-05-17 at 10 05 54 pm" src="https://user-images.githubusercontent.com/7317008/40191252-8586fc8a-5a1e-11e8-82ef-48cbfa13f7f4.png">

**Comment by c0dzilla** [comment]
@rafaelks can you please check #9995 to see if everything works as expected?

**Comment by Aaryan-kapur** [comment]
can i start contributing to this, and take this up?
