### ISSUE TITLE
[BUG] blocked rooms, do allow jitsi calls

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#9983]
### Description:
jitsi meet calls do not respect the blocked attribute of a channel
### Server Setup Information:

* Version of Rocket.Chat Server: 0.60 and 0.62.2

### Steps to Reproduce:

1. block a channel
2. start anew video call in this channel

### Expected behavior:

should be refused by the server

### Actual behavior:

block is ignored

**Comment by graywolf336** [comment]
@arminfelder can you explain further what you mean? As I can not follow what exactly you mean by "blocked attribute"...

**Comment by arminfelder** [comment]
@graywolf336 with attribute I was referring to the JSON object attribute "blocked" from the room object. 
The problem is, if you block a user, the corresponding channel with that user is marked blocked and therefor readonly.
This readonly is not respected by the jitis video call functionality-> you can start new video calls inside a blocked channel.

**Comment by graywolf336** [comment]
So, a user who is blocked in the channel `#testing` can start a video call inside the `#testing` channel?

**Comment by arminfelder** [comment]
yes
