### ISSUE TITLE
[BUG] Web App Manifest origin incorrect, icon images reference wrong path

### ISSUE THREAD

**Issue by justinribeiro** [RocketChat/Rocket.Chat#9990]
### Description:

Currently the web app manifest definition located at `public/images/manifest.json` contains two errors as reported by Google Chrome DevTools:

1. Manifest: property 'start_url' ignored, should be same origin as document.
2. Icon downloaded from the manifest was empty or corrupted

### Expected behavior:

The manifest should allow the application to be added to the home screen on Android or other platforms that support the Web App Manifest API specification.

### Actual behavior:

1. Google Chrome for Android will install the incorrect icon on the homescreen.
2. Mozilla Firefox for Android will not properly prompt for homescreen addition.

### Relevant logs:

![image](https://user-images.githubusercontent.com/643503/36929635-814f5d4a-1e48-11e8-8764-95b91b1a9c46.png)

**Comment by christianprim** [comment]
manifest.json should look like this:
`{
        "name": "Rocket.Chat",
        "icons": [
                {
                        "src": "\/assets\/favicon_192.png",
                        "sizes": "192x192",
                        "type": "image\/png"
                },
                {
                        "src": "\/assets\/favicon_512.png",
                        "sizes": "512x512",
                        "type": "image\/png"
                }
        ],
        "start_url": "\/home",
        "display": "standalone"
}`
