### ISSUE TITLE
0.62 snap release

### ISSUE THREAD

**Issue by muhv7** [RocketChat/Rocket.Chat#9992]
Any plans to push the last update to snap? Seems the update has been out for 4-5 days now and snap is still on 0,61

**Comment by geekgonecrazy** [comment]
Yes definitely coming.  Some changes in our dependencies seems to be causing the snap to get caught in a review cycle. So I'm trying to figure out why, and how to keep it from needing manual review.

Seems to be related to the sharp package.  If anyone has ideas I'm all ears.  But that's all that's holding it up.  

Snap builds, just getting bounced by snap store until it can pass the automated security review

**Comment by nickbroon** [comment]
The snap now appears to be available, so this can be closed.

**Comment by geekgonecrazy** [comment]
Yes this is now resolved. The linked PR #10015 fixes for future releases
