### ISSUE TITLE
[BUG] command issues unclear error

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#9996]
### Description:

When running command "node main.js" an unclear error is thrown, this command is issued based on the commands provided in Rocket.Chat installation:

https://rocket.chat/docs/installation/manual-installation/ubuntu/

### Server Setup Information:

* Version of Rocket.Chat Server: Latest
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 4.2.6
* mongoDB Version: 3.2.19

### Steps to Reproduce:

1. Follow steps in the documentation
2. run "node main.js"

### Expected behavior:

Either provide better error message that provides better details as to what went wrong or start Rocket.Chat

### Actual behavior:

Error thrown

### Relevant logs:
Error Thrown:

`root@chat:/tmp/Rocket.Chat/programs/server# node main.js
module.js:328
    throw err;
    ^

Error: Cannot find module '/tmp/Rocket.Chat/programs/server/main.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

**Comment by kaiiiiiiiii** [comment]
Versions >= 0.60.0 require node 8.9.3 LTS. Please upgrade your node version and try again.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c0fe** [comment]
@kaiiiiiiiii still throwing out errors. Even though I did set the export commands, unless I am supposed to edit a particular file?

`root@chat:/tmp/Rocket.Chat# node main.js
/tmp/Rocket.Chat/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /tmp/Rocket.Chat/programs/server/packages/accounts-base.js:2010:15
    at /tmp/Rocket.Chat/programs/server/packages/accounts-base.js:2017:3
    at /tmp/Rocket.Chat/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /tmp/Rocket.Chat/programs/server/boot.js:220:19
    at /tmp/Rocket.Chat/programs/server/boot.js:471:5
    at Function.run (/tmp/Rocket.Chat/programs/server/profile.js:510:12)
    at /tmp/Rocket.Chat/programs/server/boot.js:470:11`

**Comment by kaiiiiiiiii** [comment]
Doesn’t look like your export VARS have been set correctly (‘Error: MONGO_URL must be set in environment’).

Can you provide me the shell commands you executed before ‘node main.js’?

**Comment by c0fe** [comment]
@kaiiiiiiiii not sure what the issue was but it is running now but only after running "node main.js" and it doesn't start automatically/persistent. Not sure what is going wrong. But here are my commands:

`apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 && echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list && apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get autoremove -y && apt-get autoclean && apt-get install mongodb-org curl graphicsmagick build-essential -y && apt-get install nodejs -y && apt-get install npm -y && npm install -g n && n 8.9.3 && nano /etc/mongod.conf && service mongod restart && service mongod restart && systemctl enable mongod && MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=001-rs && cd /tmp && curl -L https://releases.rocket.chat/latest/download -o rocket.chat.tgz && tar zxvf rocket.chat.tgz && mv bundle Rocket.Chat && cd Rocket.Chat/programs/server && npm install && cd ../.. && export ROOT_URL=http://rocketchat.domain.com:3000/ && export MONGO_URL=mongodb://localhost:27017/rocketchat && export PORT=3000 && export MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=001-rs && node main.js`

**Comment by kaiiiiiiiii** [comment]
You need to create a service or use something like pm2 to run it persistent. 

Have a look at:
https://rocket.chat/docs/installation/manual-installation/pm2-systemd-upstart/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c0fe** [comment]
@kaiiiiiiiii i feel like that link should include at the bottom. but this resolves everything. Thanks a lot!
